localstack/localstack

README.md
localstack/mock/lambda_api.py
localstack/utils/common.py
setup.py

Allow Lambdas to use `__file__` - import from file instead of exec'ing. Fix #10

Allow Lambdas to use __file__

---

.travis.yml

Fix travis configuration for aws-cli (missing environment variables)

Fix travis configuration for aws-cli

---

localstack/services/generic_proxy.py

Don't clobber the HEAD content-length with zero

Adding Content-Length header only when one is not found during proxy

---

Dockerfile

Set file ownership to current user in Docker image (to avoid high UIDs/GIDs breaking CI). Should fix https://github.com/localstack/localstack/issues/170

Fix file ownership in Docker image

---

localstack/services/install.py
requirements.txt
setup.py

This PR adds the missing `amazon-kclpy` package to requirements (local tests currently fail without the package). The PR also adds an exclusion marker to the package because we don't want it to be included in the localstack pip package.
Supersedes https://github.com/localstack/localstack/pull/180

Add missing amazon-kclpy package to requirements (updated PR)

---

localstack/utils/cloudformation/template_deployer.py
requirements.txt
tests/integration/templates/template1.yaml
tests/integration/test_cloudformation.py

Add support for Kinesis streams in CloudFormation templates. This PR builds on the original commit by @justinm and adds a simple test case. Also, it turned out that we needed to patch and bump the version of `moto` to get this working.

Add support for Kinesis streams in CloudFormation templates

---

localstack/services/apigateway/apigateway_listener.py

Pursuant to http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html#api-gateway-simple-proxy-for-lambda-output-format, this PR brings the behavior of Localstack's API Gateway response in line with what is expected from AWS.

Updated Lambda proxy behavior

---

localstack/ext/java/src/test/java/cloud/localstack/S3HttpsConnectionTest.java
localstack/services/dynamodb/dynamodb_listener.py

Return 'ConsumedCapacity' from DynamoDB `GetItem` API call. This used to work with dynalite, but stopped working when we switched to DynamoDBLocal. See https://github.com/localstack/localstack/issues/143

Return 'ConsumedCapacity' from DynamoDB GetItem

---

localstack/services/s3/s3_listener.py
localstack/utils/analytics/event_publisher.py
tests/integration/test_notifications.py

Use Queue ARN instead of URL for S3 bucket notifications. See https://github.com/localstack/localstack/issues/42

Use Queue ARN instead of URL for S3 bucket notifications

---

Makefile
README.md
localstack/constants.py
localstack/ext/java/pom.xml
localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java
localstack/services/awslambda/lambda_api.py
localstack/services/install.py

Refactor install script, put Java libs into a single jar file. This should make the first-time installation faster and more reliable, and actually removes the dependency to Maven for installing LocalStack.

Refactor install script and put java libs into a single jar

---

bin/localstack
localstack/ext/java/src/test/java/cloud/localstack/BasicFunctionalityTest.java
localstack/ext/java/src/test/java/cloud/localstack/SQSMessagingTest.java
localstack/services/sqs/sqs_listener.py
requirements.txt

* Support unicode names for S3 (see https://github.com/localstack/localstack/issues/142)
* Fix SQS Java tests using SSL

Support unicode names for S3

---

README.md
localstack/config.py

set no_proxy insted of ignore proxy, this is better solution for issue #239.

If http_proxy is set, the mock server health check fails, so bypass the proxy for internal requests.

---

localstack/dashboard/infra.py
localstack/services/awslambda/lambda_api.py
localstack/services/install.py
localstack/utils/common.py

Use native Python code to unzip archives (eliminates the dependency to the `unzip` command).

Use native Python code to unzip archives

---

localstack/services/s3/s3_listener.py
tests/unit/test_s3.py

S3 offsets a POST operation for use in browser-based uploads: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html
> POST is an alternate form of PUT that enables browser-based uploads as a way of putting objects in buckets. Parameters that are passed to PUT via HTTP Headers are instead passed as form fields to POST in the multipart/form-data encoded message body. 
This change modifies HTTP request bodies and response headers to match Amazon’s documented behavior. I’ve made these changes in `localstack.services.s3.s3_listener.ProxyListenerS3` — is this a good place for them? If yes, I’ll follow up with a few tests of the new behavior.

Add support for S3 REST Object POST

---

localstack/services/awslambda/lambda_api.py
localstack/utils/testutil.py
tests/integration/lambdas/lambda_environment.py
tests/integration/test_lambda.py

Adds custom environment variables for Lambda invocations when `LAMBDA_EXECUTOR=docker` is used. Part of https://github.com/localstack/localstack/issues/187.
I’ll expand on this if it’s a workable direction?

Added custom environment variable support for Lambda run under Docker

---

localstack/utils/common.py
setup.py

Adds call to `os.makedirs()` in `localstack.utils.common.download()` to ensure that downloaded files are created in new directories.
Closes https://github.com/localstack/localstack/issues/292

Create parent directories for download files

---

tests/integration/lambdas/lambda_python3.py

Mark f'strings' as noqa to silence linters on Python < 3.6

---

localstack/services/generic_proxy.py

GenericProxyHandler does not always send the correct data when
forwarding requests. self.data_bytes is not properly cleaned up on all
request types.
This commit resets self.data_bytes in the following cases:
- DELETE, HEAD and OPTIONS requests
- GET requests lacking content-length header

Set right request data in GenericProxyHandler

---

README.md

Link to https://github.com/localstack/awscli-local repository in README so people doesn't have to guess where to find it :smile:

Linking awslocal repo in README

---

localstack/services/s3/s3_listener.py

If no "boundary" is found, proceed as before. Closes #310.

Check for "boundary" parameter before assuming it exists

---

localstack/services/s3/s3_listener.py

Bucket notifications configuration requests were failing for a while, as they were picked up as file upload/download requests.

Ignore bucket notification configuration requests when sending s3 bucket notifications

---

localstack/services/infra.py
localstack/services/sqs/sqs_listener.py
localstack/utils/common.py
requirements.txt
tests/integration/test_notifications.py

Workaround to allow dots in SQS queue names. This is a temporary workaround to allow creation of fifo queues (currently not supported directly by ElasticMQ) - See #335

Workaround to allow dots in SQS queue names

---

tests/unit/test_lambda.py

What do you think about this way of testing @whummer. Uses the test_client instead of calling directly methods when there is request data.

Use flask's test_client to test lambda API posts

---

localstack/services/cloudformation/cloudformation_listener.py

Fixes error when deploying cloudformation stack:
TypeError: deploy_template() takes exactly 2 arguments (1 given)

Fixed usage of deploy_template for deploying cloudformation stack

---

localstack/constants.py
localstack/services/s3/s3_listener.py
localstack/utils/common.py
localstack/utils/kinesis/kinesis_connector.py
requirements.txt
tests/integration/test_lambda.py

* Import default service ports from [localstack-client](https://github.com/localstack/localstack-python-client). This way we can avoid duplication and maintain the default service ports in a single place. 
* This PR also contains a minor fix to return a missing newline in the responses returned by the S3 service.

Import default service ports from localstack-client

---

localstack/constants.py
localstack/ext/java/pom.xml
localstack/ext/java/src/main/java/cloud/localstack/LocalstackTestRunner.java
localstack/services/install.py
tests/integration/test_lambda.py

Fix config code to get service endpoints in Java.
Background: Our most recent build on master has failed because we removed the `DEFAULT_*` port configurations from `constants.py`, but the Java code was still relying on these variables to be available. (btw, we expect this PR build to fail initially, until the new Maven library has propagated to Maven Central)

Fix config code to get service endpoints in Java

---

Dockerfile
localstack/utils/aws/aws_stack.py

This PR supersedes #277 . Set default AWS settings via config file rather than environment variables.

Set default AWS settings via config file rather than environment variables

---

localstack/services/dynamodbstreams/dynamodbstreams_api.py

ShardIDs returned from the DynamoDBStreams emulator now mimic ShardIDs
in the production service.  Namely, they comply with the length requirements
in botocore.  Each returned ShardID is > 28 characters in length.
As ShardIDs from Kinesis are appended with `-$UUID5`.  The UUID5 value
generated is relative to the Kinesis stream name as well as the Kinesis
ShardID, ensuring that the value is consistent across multiple calls to
`describe_stream`.  Before ShardID values are passed through to
Kinesis, they are unwrapped to the original Kinesis value.

DynamoDBStreams Now Returns Valid ShardIDs.

---

localstack/ext/java/src/test/java/cloud/localstack/S3UploadTest.java

See comment for details: https://github.com/localstack/localstack/issues/359#issuecomment-337758803
It seems there is an issue that uploads over >128k do not work with the same error as being reported here. I get a message such as:
```
Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: 8eET31STItFmGOd/IrNlCA== in base 64) didn't match hash (etag: 7eebd4a71c4c983bd38c1a227c22b236 in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: 8eET31STItFmGOd/IrNlCA==, md5DigestStream: null, bucketName: 4d52e9a7-8666-4149-9ff8-70d22e035782, key: 187c0368-1f2b-4062-883a-cf40ccfff568)
```
Additionally if I suppress the exception and continue anyway the assert on the lengths of the returned object differs... so …

adds test cases for >128k and <128k Java S3 uploads

---

localstack/services/generic_proxy.py
localstack/services/s3/s3_listener.py
localstack/services/sqs/sqs_listener.py
localstack/utils/aws/aws_stack.py

* Map external port for SQS queue URLs. Addresses #394
* Allow specifying `config` for boto3 clients, and increase `read_timeout` on the boto3 client used for S3->Lambda integration (discussed in #408)

Map external port for SQS queue URLs

---

localstack/ext/java/src/main/java/cloud/localstack/LocalstackTestRunner.java
localstack/ext/java/src/test/java/cloud/localstack/S3LifecycleTest.java
localstack/services/s3/s3_listener.py

This PR adds some simple stubs to accept and store S3 lifecycle configurations.  In particular, the s3 client can PUT a lifecycle configuration and have it echoed back with a GET.
The lifecycle rules are not actually enforced.
This allows stacks that contain S3 lifecycle rules to set up against localstack without failing.

S3 lifecycle support

---

localstack/services/awslambda/lambda_api.py

Argument order for string pattern was wrong, breaking LAMBDA_REMOTE_DOCKER completely.
Note: this is a copy of #422 , rebased to latest version of `master`

Fix argument order for LAMBDA_REMOTE_DOCKER

---

localstack/config.py

Default to LAMBDA_REMOTE_DOCKER=true if running in Docker. Addresses #442

Default to LAMBDA_REMOTE_DOCKER=true if running in Docker

---

localstack/services/s3/s3_listener.py

Fixes #462.
It looks like #440 clobbered the `config` variable at these lines, which is needed further down.

Fix running Lambda from a notification

---

localstack/dashboard/infra.py
localstack/services/apigateway/apigateway_listener.py
localstack/services/dynamodb/dynamodb_listener.py
localstack/services/kinesis/kinesis_listener.py

I just added few conversions since data parameter could be b'{}', which json parser does not like (see my issue #463). It works now with python 3.5 on ubuntu. Need more comments?

Fix data parameter which is non-string passed to json parser

---

.gitignore
localstack/utils/cloudformation/template_deployer.py

Hi,
When you try to use Serverless Framework with Localstack is impossible to deploy because the Cloudformation generated by Serverless doesn't come with AccessControl property so the deployment breaks, I debug into the issue and we only need to make a quick fix and set a default value for this ACL to continue with the deployment.
This also fixes the issue #475  that I reported before.
NOTE: I also add a gitignore entry because I use PyCharm as IDE and there always create an .idea directory.

Set S3 ACL default value in case comes empty

---

.travis.yml
localstack/services/dynamodb/dynamodb_starter.py
requirements.txt
tests/integration/test_error_injection.py

* Avoid error log outputs for DDB startup (see #476)
* Run error injections only in one single test iteration (should reduce build times)
* Bump moto version

Optimize startup and error injection

---

README.md

Update README for `docker for mac` users.
fix issue #480

update READMED - #480

---

localstack/services/sns/sns_listener.py
tests/unit/test_sns_listener.py

Localstack's SNS emulation would be a little bit more realistic if notification messages had `MessageId` elements.
**This change adds a random uuid4 as a `MessageId` in outbound SNS messages.**

Add random uuid4 as SNS MessageId

---

localstack/services/sns/sns_listener.py

It seems that RawMessageDelivery has only been respected for sns->sqs.
Though the docs for [Raw Message Delivery](http://docs.aws.amazon.com/sns/latest/dg/large-payload-raw-message.html) state:
> Amazon SNS you can now enable raw message delivery for messages delivered to either Amazon SQS endpoints or HTTP/S endpoints.
Please let me know if anything else needs to be added.

Update sns forward_request for HTTP/S to handle RawMessageDelivery

---

localstack/services/apigateway/apigateway_listener.py
tests/unit/test_apigateway.py

API Gateway has path variables like `{param}` but also wildcard path variables like `{proxy+}`: https://aws.amazon.com/blogs/aws/api-gateway-update-new-features-simplify-api-development/
This PR adds support for wildcard path variables.

API Gateway should support wildcard path segments, e.g. {proxy+}

---

.travis.yml
Makefile

Fix Java CI config: If the Java code has changed, build Maven dependencies locally and use them for the tests.

Fix Java CI config

---

localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java
localstack/ext/java/src/test/java/cloud/localstack/sample/SerializedInputLambdaHandler.java
tests/integration/test_lambda.py

According to amazon documentation, RequestHandler can use POJOs as input: http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-req-resp.html
Executor will learn the type and try to deserialise the payload, then serialise the response if possible.
It will continue as normal if unable to serialise/deserialise.
One thing I did not do was to bump `localstack-utils` version, but since the build process requires some additional work I hope I can leave it up to @whummer ;)

Use POJO Type for RequestHandler input

---

README.md
localstack/services/infra.py

I've added support for an env var of the name `FORCE_NONITERACTIVE`.
It disables the `-it` flags when running with Docker (i.e. `localstack start --docker`).
This solves an issue I've encountered when trying to make localstack run in the background (via [hote.dev)](https://github.com/typicode/hotel).
I'm aware that mimicking CI environment via the `CI`/`TRAVIS` var is possible and will achieve the same effect, but I didn't want to abuse this.

Add support for FORCE_NONINTERACTIVE

---

localstack/services/awslambda/lambda_executors.py
tests/integration/test_lambda.py

Very small change to execute lambda asynchronously when forwarding DynamoDB events. Without it we were seeing timeouts on calls to dynamo db clients.

Execute lambda asynchronously for DynamoDB events

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py
tests/unit/test_s3.py

Fixes #558 
Since the JavaScript AWS SDK uses another approach for putting objects than that of boto(3), this adds support for getting the bucket name from the host instead of only allowing it to be part of the `path`.
In addition, this also then uses the entire `path` as the object `key` [as per the documenation](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html#RESTObjectPUT-requests).
---
I couldn't get the entire test suite to run properly locally or inside docker due to the below error though, any suggestions here?
```
======================================================================
ERROR: tests.integration.test_integration.test_kinesis_lambda_sns_ddb_streams
----------------------------------------------------------------------
Traceback (most recent call …
```

Add support to get s3 bucket name from hostname

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

This allows a browser to download it as a file, rather then try to
render it in the browser.
fixes https://github.com/localstack/localstack/issues/564 
^^ issue contains reproduction steps and more detail

AWS S3 sets the content-type to `binary/octet-stream` for GET Requests

---

localstack/utils/cloudformation/template_deployer.py

In cloudformation templates for SQS resources the property QueueName is not mandatory. If not specified, the logical name will be the resource name and the physical name will be generated. This pull requests makes it possible to create cloudformation stacks with queues that miss this property.

Fixed CloudFormation deployer for SQS

---

localstack/services/sns/sns_listener.py

Without this fix, the subject was being sent to lambda functions as
an array containing a single string i.e. [ "Subject" ], instead of just the string,
which is the behavior for other subscription protocols, and is how
it behaves in AWS

Use same subject for lambda notications as other protocols

---

localstack/services/s3/s3_listener.py
tests/integration/test_notifications.py

To be consistent with behavior in AWS, set SNS message subject to
'Amazon S3 Notification' when publishing to SNS in response to actions in S3.
Messages going to Lambda or SQS are unaffected.
Created a test for this in integrations/test_notifications.py

S3 Fix: Set message subject when publishing to SNS

---

localstack/services/cloudformation/cloudformation_listener.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/templates/template1.yaml
tests/integration/templates/template2.yaml
tests/integration/test_cloudformation.py

In Cloudformation the PhysicalResourceId of a SQS resource is the QueueUrl. Implemented this for ListQueueResources.
This should also be the case for DescribeStackResources/DescribeStackResource but it's very tightly connected to the template_deployer functionality.
With this pull request, Spring Cloud AWS Messaging works with localstack :D

 Cloudformation ListStackResources returns QueueUrl for PhysicalResourceId

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

According to https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html
, if there is a PUT without a content-type, 'binary/octet-stream' will be used
as the default.
This changes the previous attempt at fixing this default, which was just setting
the content-type for GET's, which would override the content type of the
uploaded file, rather then respect the original uploaded content-type, like it
should have.
Fixes https://github.com/localstack/localstack/issues/581
This functionally Reverts https://github.com/localstack/localstack/pull/565 , which incorrectly fixed #564 . 
Thanks for the help identifying this @viniciuskneves !

Instead of trying to set the default content-type on GET, set it on PUT

---

localstack/ext/java/src/main/java/cloud/localstack/docker/Container.java
localstack/ext/java/src/main/java/cloud/localstack/docker/DockerExe.java
localstack/ext/java/src/main/java/cloud/localstack/docker/command/PullCommand.java

We were getting intermittent test failures with the DockerTestRunner because the timeout for the Pull command was too short.  Pull command now has 10 minutes to complete.  Default for the rest of the commands is 1 minute.

Increase docker pull timeout

---

localstack/services/sqs/sqs_listener.py

Mocks 'TagQueue' action and returns a mocked successful response. This fixes the exceptions thrown in Terraform when you define tags in your sqs modules.
Tested on terraform with sqs endpoint redirected to localstack sqs endpoint where the sqs terraform files have tags attributes.

Mock TagQueue Action for sqs

---

localstack/services/dynamodb/dynamodb_listener.py
localstack/utils/testutil.py
tests/integration/test_dynamodb.py

- Mocks UpdateTimeToLive, DescribeTimeToLive, TagResource, UntagResource & ListTagsOfResource apis as they are not implemented in DynamoDB.
- Default response for DescribeTimeToLive is DISABLED.
- Fixes [this](https://github.com/terraform-providers/terraform-provider-aws/issues/1059) issue when integrating Terraform with localstack endpoints
Tested on terraform with dynamodb endpoint redirected to localstack dynamodb endpoint where the dynamodb tables in terraform files have ttl & tags attributes.

Mock missing local DynamoDB apis to avoid Terraform exceptions

---

localstack/services/awslambda/lambda_api.py
localstack/utils/common.py

Fix file permission issue in Java lambda tests, currently happening when running in Docker:
```
2018-02-25T17:48:09:WARNING:localstack.services.awslambda.lambda_api: Unknown error: [Errno 13] Permission denied: '/tmp/localstack/zipfile.efa5ebcc/LambdaCode.jar' Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 485, in create_function
result = set_function_code(data['Code'], lambda_name)
File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 392, in set_function_code
with open(main_file, 'rb') as file_obj:
IOError: [Errno 13] Permission denied: '/tmp/localstack/zipfile.efa5ebcc/LambdaCode.jar'
```

Fix file permission issue in Java lambda tests

---

localstack/services/awslambda/lambda_api.py
tests/unit/test_lambda.py

See #648
Supports:
https://docs.aws.amazon.com/lambda/latest/dg/API_GetEventSourceMapping.html
```
aws lambda get-event-source-mapping --uuid cef34cb4-39d9-497d-8a6e-3a7438d77826 --endpoint http://localhost:4574
```
[Terraform](https://www.terraform.io) makes this call to do it's thing.

add support for lambda GetEventSourceMapping

---

localstack/services/awslambda/lambda_api.py
localstack/utils/aws/aws_models.py
tests/unit/test_lambda.py

https://docs.aws.amazon.com/lambda/latest/dg/API_PutFunctionConcurrency.html
Additionally alters GetFunction to return the `Concurrency` key.
See Concurrency response example here:
https://docs.aws.amazon.com/lambda/latest/dg/API_GetFunction.html
Using tools like CloudFormation or Terraform the user can set the concurrency limit. For the purposes of localstack this doesn't have to do anything as it's for local testing only. I don't think the expectation would be there that this actually supports the requested level of concurrency.
But the ability to run CloudFormation or Terraform allows teams to mock that implementation and go from there with their testing.

add support for lambda PutFunctionConcurrency

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

In response to issue [#541](https://github.com/localstack/localstack/issues/541), content length header was being set 'correctly' for all requests, this masks the content-length header supplied by moto for HEAD requests. Other clients for example spark S3AFileSystem depend on the content-length from the HEAD request to pre-determine the object size. Others affected by this issue [#638](https://github.com/localstack/localstack/issues/638)  ... This pull request illustrates a possible fix that would retain the 'fix' [#541](https://github.com/localstack/localstack/issues/541), though it's possible the aws-sdk mentioned in that issue actually what is at fault, rather than moto / localstack

Allow content-length header to pass-through for HEAD requests

---

localstack/services/sns/sns_listener.py
tests/unit/test_sns_listener.py

Fixes issue #516. 
As stated in [AWS Documentation](https://docs.aws.amazon.com/sns/latest/api/API_Publish.html) if the message has a JSON MessageStructure it must contain a top-level JSON key of “default”,  other top-level keys can be defined to specific transport protocols.
So for a JSON MessageStructure if I have a message like this:
`{‘default’: ‘message’, ‘sqs’: ‘sqs message’}`
It firsts search for the subscriber protocol, if not found it will use the default value.
If the message’s MessageStructure is not set, nothing is changed.

Support MessageStructure json - Fix 516

---

localstack/package.json
localstack/services/sns/sns_listener.py
tests/unit/test_sns_listener.py

See: https://docs.aws.amazon.com/sns/latest/dg/message-filtering.html
This pull request adds support for SNS subscription filters. These filters decide which messages on the topic the subscriber will accept. If a message does not meet the filter conditions then it will not be passed to the subscriber.
Specifically each attribute in the filter policy will be matched against that corresponding attribute in the messages' `MessageAttributes`. If the value of the attribute fails to match at least one of the conditions specified against the attribute in the filter, then it will not be passed to the subscriber.
Currently AWS supports the following:
- Exact matches (whitelisting)
- Anything-But (blacklisting)
- Prefix
- Numeric (=, >, <, >=, <=)
- AND/OR logic

Add Filter Policy Support To Sns Subscriptions

---

bin/Dockerfile.base
localstack/constants.py
localstack/services/es/es_api.py
requirements.txt

The [latest AWS-supported Elasticsearch version is 6.2](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/what-is-amazon-elasticsearch-service.html#aes-choosing-version), and the AWS documentation "strongly recommends" using the latest supported version.
This also closes #659.

Bump Elasticsearch version to 6.2.0

---

localstack/package.json

This upgrades the Kinesalite dependency to version 1.13.0.
This version is significant because of the following resolved issue, which prevented testing of the KCL versions 1.9.x:
https://github.com/mhart/kinesalite/issues/59

v1.13.0 Kinesalite

---

localstack/services/awslambda/lambda_api.py
tests/unit/test_lambda.py

The `get_function` API should return the same response as the Lambda API when the function is not found, but this does not seem to be the case right now, which means it's broken with some tools that depend on proper responses when the lambda is not found:
Currently localstack returns:
```
curl http://localhost:4574/2015-03-31/functions/test -v
< HTTP/1.0 404 NOT FOUND
< Content-Type: application/json
< Content-Length: 57
< Access-Control-Allow-Origin: *
< Server: Werkzeug/0.14.1 Python/2.7.13
< Date: Tue, 03 Apr 2018 15:49:12 GMT
<
{
"ResponseMetadata": {
"HTTPStatusCode": 404
}
}
```
However the correct API response is: 
```
Content-Type:       application/json
x-amazon-ErrorType: ResourceNotFoundException
{
"Message":"Function not found: …
```

fix lambda_api.get_function to return correct error

---

localstack/services/es/es_starter.py

We've recently been running into the issue described [here](https://github.com/pires/docker-elasticsearch/issues/56):
```
mktemp: Invalid argument
```
The suggested solution is to set `$ES_TMPDIR` to fix the ES startup issue.

Set ES_TMPDIR to fix ES startup issue

---

README.md
localstack/constants.py
localstack/ext/java/pom.xml
localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java
localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDockerTestRunner.java
localstack/ext/java/src/test/java/cloud/localstack/docker/ContainerTest.java

Hello, again. I need this change for removing the runtime dependency of JUnit on the application. I already coded basic auto-configuration factories for the Spring Boot and it runs alright with this change. If you want you can checkout more here:
https://github.com/fabianoo/spring-localstack
I would need this change and a new version. Is it possible?
Best wishes,
Fabiano

Removes the last runtime dependency of JUnit on common code

---

localstack/services/es/es_api.py
tests/integration/test_elasticsearch.py

These updates came from testing with Terraform.  Terraform would fail to create the Elasticsearch domain because it never saw it as completed.  Making these changes allowed creating an Elasticsearch domain and applying an access policy to that domain for testing.

Update to Elasticsearch API to support addition of tags during testing and access policy

---

localstack/services/awslambda/lambda_api.py
tests/integration/test_lambda.py

Localstack currently expects Java Lambda functions to be uploaded as a `.jar` wrapped in a `.zip` file. As #385 notes, this is not what the Lambda API expects to be in the `ZipFile` payload. Instead it expects: 
```
1. "Fat" JAR - single jar file with all dependencies
2. ZIP - zip archive with class files in / and jar files in /lib
```
This PR allows localstack to accept format 1. 
Format 2 is a little harder to implement because it would require re-working the Java executor to handle the different locations of the class files in `/` and jar files in `/`. 
This change also cleans up some of the handler paths in the `set_function_code` function. The goal is be more explicit about how to properly form handlers for non python (and in particular Java) runtimes. I've tried to add addition …

Allow direct upload of Java JAR in Lambda API

---

localstack/utils/common.py
localstack/utils/persistence.py

On OSX, I am having permission errors and related, when trying deploy a simple Serverless function using Python runtime.
Caveats of this PR:
* Tests will be added later, before merging the PR
* Squashing can be done on merge, to keep the blame and reasoning before the merge.

Fix errors deploying Serverless on OSX

---

localstack/services/es/es_starter.py

The `ES_JAVA_OPTS` were being set, but not allowing the user to override specific settings (`-Xms` and `-Xmx`) which becomes problematic when dealing with large or complicated Elasticsearch indexes.
This simply adds syntax necessary to allow a user to completely override the contents of `ES_JAVA_OPTS`, with a fallback to the existing defaults.

Allow complete override of `ES_JAVA_OPTS`

---

localstack/services/sqs/sqs_listener.py

I'm using the aws js sdk locally in the browser. After hooking up lambda executions successfully, I was surprised to see sqs requests being denied by CORS. This turned out to be because localstack was 404ing on OPTIONS to the root url.
This change fixes that by returning a 200 instead. After the change I was able to send messages as expected.

fix sqs CORS preflight response

---

localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/utils/aws/aws_models.py
tests/integration/lambdas/lambda_integration.py
tests/integration/test_lambda.py

This adds some common properties to the LambdaContext, which is passed
to functions during invocations. In particular, the following properties
are added: function_name, function_version, invoked_function_arn.
The above properties are passed to lambda functions running inside docker.
Support for publishing during function creation has also been added,
which was a missing functionality, and was helpful in testing.
Note that this has a slight dependency on https://github.com/lambci/docker-lambda/pull/98, but shouldn't break anything if this was merged first.
Contributed by @quantcast

Lambda: add function properties to LambdaContext for invocations

---

localstack/services/awslambda/lambda_api.py
tests/unit/test_lambda.py

This API returns the Alias information given the alias name.
https://docs.aws.amazon.com/lambda/latest/dg/API_GetAlias.html
Contributed by @quantcast

lambda: implement GetAlias API

---

localstack/services/apigateway/apigateway_listener.py
localstack/utils/aws/aws_stack.py
tests/integration/lambdas/lambda_integration.py
tests/integration/test_api_gateway.py

This allows the API Gateway integration to properly dispatch HTTP requests to resources setup with HTTP method `ANY`.
Hopefully, this should fix #667 ... and maybe #449 as well.

Support resources with HTTP method 'ANY' in API Gateway

---

localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/services/dynamodb/dynamodb_starter.py
localstack/services/es/es_starter.py
localstack/services/infra.py
localstack/services/kinesis/kinesis_starter.py
localstack/services/sqs/sqs_starter.py
localstack/utils/common.py
tests/integration/__init__.py
tests/integration/test_lambda.py

`async` is a reserved keyword in Python 3.7 and currently breaks localstack, replaced all references with `asynchronous`. Tests passing.
See:
- https://docs.python.org/3/whatsnew/3.7.html 
- https://docs.python.org/3/reference/compound_stmts.html#async

changed `async` references to `asynchronous` to support Python 3.7

---

README.md

This fixes the contributors link on the README.md and should close https://github.com/localstack/localstack/issues/748
I agree to https://github.com/localstack/localstack/tree/master/doc/contributor_license_agreement

fix link for contributors

---

localstack/services/sns/sns_listener.py
tests/unit/test_sns_listener.py

This commit updates the calculation of the filter policy so that it works with message attribute values of type "String.Array"

Add support for arrays in sns filter policy

---

bin/Dockerfile.base
localstack/constants.py
localstack/package.json
localstack/services/sqs/sqs_listener.py
tests/integration/test_notifications.py
tests/integration/test_sqs.py

I opened this morning an issue about upgrading elasticmq dependency: https://github.com/localstack/localstack/issues/879
It seems that after the merge of adamw/elasticmq#143 FIFO queues should be available so I tried to bump to a more recent version. Not sure I missed something but I tried to create one FIFO queue and it still seems to not work
*Step to reproduce*
```
$ docker build -t localstack:custom .
$ docker run -d -e SERVICES=sqs -p 4576:4576 localstack:custom
$ aws --endpoint-url=http://localhost:4576 sqs list-queues
```
I created then the following terraform configuration:
References:
https://github.com/localstack/localstack/issues/718
https://www.terraform.io/docs/providers/aws/r/sqs_queue.html
```tf
provider "aws" {
region                      = "us-east-1"
access_key …
```

chore: bump elasticmq to v0.14.2

---

localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java

When an exception is thrown in this block before `this.localStackContainer` is initialized, then `stop()` is not invoked. However, in https://github.com/localstack/localstack/blob/a35b8d18286e4db8e8ac41931d7d61befc3a9ae8/localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDockerTestRunner.java#L45, `stop()` is called unconditionally and produces a `NullPointerException`.

LocalstackDockerTestRunner: Avoid NPE on failure

---

README.md

update docs to mention docker requirements where the version of docker-compose was not mentioned
16th August 2018

Update readme.md to mention docker requirements

---

localstack/dashboard/infra.py
localstack/services/es/es_api.py

Fix URL suffix for Elasticsearch Service `/tags` endpoint. This has been causing test errors with recent versions of `botocore`

Fix URL suffix for ES /tags endpoint

---

localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java
localstack/services/awslambda/lambda_api.py
localstack/services/sqs/sqs_listener.py
localstack/utils/aws/aws_models.py
localstack/utils/aws/aws_stack.py
localstack/utils/testutil.py
tests/integration/lambdas/lambda_integration.py
tests/integration/test_integration.py

Currently event notification configurations for lambda functions that use an SQS queue as the source are not taken into account. This PR adds that functionality based on the implementation of a similar Kinesis/Lambda interaction.

Add SQS/Lambda interaction.

---

requirements.txt

As it was suggest in the issue https://github.com/localstack/localstack/issues/889 a new version of moto has been recently released.
Changelog:
https://github.com/spulec/moto/blob/master/CHANGELOG.md#134
```
* IAM get account authorization details
* adding account id to ManagedPolicy ARN
* APIGateway usage plans and usage plan keys
* ECR list images
```

Bump moto to 1.3.4

---

README.md

Moto runs both in-memory as well as in server mode and the test suite runs against both execution modes. Localstack is *awesome* and is much needed and this clarifies the distinction between Localstack and Moto a little.

Removing obsolete references to Moto features

---

localstack/services/s3/s3_listener.py

Fix query parameter parsing in s3 put bucket notification configuration api call.
Details on issue can be found here...
https://github.com/localstack/localstack/issues/872

issue 872; fixes query param parsing for s3 notification put

---

docker-compose.yml

I'm happy that SecretsManager is available in LocalStack. Thanks for release!

Expose AWS SecretsManager service by default in docker-compose.yml

---

localstack/services/apigateway/apigateway_listener.py
localstack/services/awslambda/lambda_api.py
tests/integration/lambdas/lambda_integration.py
tests/integration/test_api_gateway.py
tests/unit/test_apigateway.py

queryStringParameters.
---
This is how the apigateway request is translated to an event for lambda AWS_PROXY integration in localstack.
this is my path_part definition `v1.2.0/{locale}/ab-tester/{target}`
.
.
.
```js
2018-09-28T11:31:51.571Z        b8de8ee4-ccde-12c8-68a1-44e666a4b318    Request:  { 
body: '',
headers:
{ 
'content-length': '0',
'accept-encoding': 'gzip, deflate',
host: 'localhost:4567',
accept: '*/*',
'user-agent': 'Mozilla',
connection: 'keep-alive',
'cache-control': 'no-cache',
'content-type': 'application/x-www-form-urlencoded' 
},
resource: '/restapis/A-Z40542153A-Z/dev/_user_request_/v1.2.0/de/ab-tester/learn_language_filter_target?learn_language_alpha3=POR',
queryStringParameters: {},
httpMethod: 'POST',
stageVariables: {},
path: …
```

Support queryStringParameters for Lambda AWS_PROXY apigateway.

---

Dockerfile

I had a lambda function being invoked by an SNS topic. I was getting very confused about why my lambda's printing to stdout was appearing in batches of 5 at once. Turns out this was nothing to do with localstack's sns+lambda doing some strange batching, but just Python's output buffering.
This sets the env-var to disable buffering in Docker, and I have verified this fixes my problem. Should I actually set this somewhere else so it works for non-Docker users? Though that might have surprising knock-on effects when it is not isolated with a container (ie, the env-var will affect other, non-localstack code).

Set PYTHONUNBUFFERED=1 to improve printing from Lambda

---

localstack/services/dynamodb/dynamodb_listener.py
tests/integration/test_dynamodb.py

Found out that the `LatestStreamArn` was returning the stream name with the `ddblocal` region. This PR extends the region replacement to also apply to that field.

Replace region in dynamodb LatestStreamArn

---

localstack/services/apigateway/apigateway_listener.py

Related to #960, while that PR meant that the `queryStringParameters` are passed to the lambda if it's called, a bug in the get_resource_for_path function meant it was never actually possible to invoke a lambda via a URL if you added a query string, as the regexp was excluding `?` characters and not allowing for them on the end.

Fix path matching to ignore query strings

---

localstack/utils/common.py

I've ran into a 'File exists' OSError a few times on the os.makedirs() call and this should take care of this unlikely but possible case.

 Handle mkdir() race conditions

---

localstack/services/apigateway/apigateway_listener.py
localstack/services/apigateway/helpers.py
localstack/services/awslambda/lambda_api.py
localstack/services/generic_proxy.py
tests/integration/lambdas/lambda_integration.py
tests/integration/test_api_gateway.py

requestContext
---
According to aws docs https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-lambda.html
the event that is passed to the lambda when aws_proxy integration type is used, should contain `requestContext` object that contains some information about the request.
In my case I use this object to get the the `sourceIp` of the request where my lambda behaviour depends on that `sourceIp`:
```js
const remoteIp = requestContext.identity.sourceIp;
```
So this PR is a solution to support the missing object in general, and in particular to support some of the information that my lambda behaviour depends on it such as the `sourceIP`
closes #996

Support requestContext object in aws_proxy integration type for apigateway.

---

README.md
localstack/config.py
localstack/services/sqs/sqs_listener.py

First, thanks for your amazing work on `localstack`!
Please treat this as a start of a conversation rather than a full-featured PR. I'm not certain that this is the right direction and would love your feedback.
The issue I'm having is that I'm running `localstack` behind a proxy, which is running on a specific host (which is covered by `HOSTNAME_EXTERNAL`, but is also on a different port from that of the proxy. So, when SQS returns the queue URL it returns the `HOSTNAME_EXTERNAL` that I set, but returns the local port and not the port that the client requests the proxy with.
`[proxy:80]` -> `[localstack:4576]` -> `[elasticmq:4561]`
What I've done at the moment, is I've set my SQS port to `:80` (which is what my proxy wants). This works, but in my opinion is more of a workaround because …

sqs: add ability to define the external port

---

localstack/services/sns/sns_listener.py
tests/unit/test_sns_listener.py

Correctly map SNS message attributes to SQS message attributes when RawMessageDelivery is enabled.
Fixes #655

Correctly map SNS message attributes to SQS when using RawMessageDelivery

---

requirements.txt

When you `pip install localstack` it wont work, due to version conflict of the module `PyYAML` so this fixes #1052

fix pyaml version

---

bin/Dockerfile.base
localstack/constants.py
localstack/services/install.py

Fix #1035
install ES plugin by  supports Amazon Elasticsearch Service
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-plugins.html

Install Elasticsearch plugins

---

localstack/ext/java/pom.xml
localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/ProcessTree.java

Fix test failures while running in JDK 9 and above due to failure to destroy process from removal of UNIXProcess class in java 9.

Resolve issues with building in Java 9 (and above) environments #1028

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py
tests/unit/test_s3.py

Refactor issue https://github.com/localstack/localstack/issues/614
Refactor to add a static helper method for readability and testability.
This helper method makes it explicit how we notify on Multipart Uploads; the only POST operations that starts with `uploadId`
Added an integration test for s3 multipart upload and unit tests.
Name                                                            Stmts   Miss  Cover   Missing
---------------------------------------------------------------------------------------------
localstack/services/s3/s3_listener.py                             319     63    80%   61, 64-66, 147-148, 154-155, 161-167, 170, 175-185, 200-203, 229, 231, 240-250, 255-260, 275-280, 429, 437, 459, 462-463, 466-469, 472, 482, 491-493, 514 …

Refactor #614: S3 Multipart upload notification testing

---

Dockerfile

This PR exposes the port 4584 which is used by the secretsmanager service.

Expose the port for secretsmanager by default in Dockerfile

---

localstack/services/s3/s3_listener.py
tests/unit/test_s3.py

When the AWS SDK requests the S3 bucket lifecycle it expects to have at least the root element LifecycleConfiguration and the current code does not return the expected result.

Fix missing root element in S3 Get_Lifecycle

---

localstack/services/awslambda/lambda_executors.py

[subprocess.Popen.wait](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait)
> This will deadlock when using stdout=PIPE or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use Popen.communicate() when using pipes to avoid that.
example:
```bash
$ dd if=/dev/zero of=file.txt count=1024 bs=1024
```
```python
import subprocess
process = subprocess.Popen('cat file.txt', shell=True, stdin=subprocess.PIPE, bufsize=-1, stderr=subprocess.PIPE, stdout=subprocess.PIPE, cwd=None)
process.wait()  # hanging
```

Fix subprocess.wait() hanging

---

.travis.yml
localstack/plugins.py
localstack/services/cloudformation/cloudformation_listener.py
localstack/services/cloudformation/cloudformation_starter.py
localstack/services/infra.py
localstack/utils/cloudformation/template_deployer.py
localstack/utils/common.py
tests/integration/templates/template1.yaml
tests/integration/test_cloudformation.py

This PR refactors the CloudFormation (CF) implementation.
The main change is to rebase the API onto the latest version of `moto`'s CF implementation. We currently use `moto` as the backend for CRUD functionality of CF stacks, as well as keeping track of CF events. However, in `moto` the CF implementation is tightly coupled to the other AWS service stubs (e.g., in-memory creation of CF resources like S3 buckets, Lambda functions, etc), which is not suitable for our purposes.
Therefore, in this PR we introduce a loose coupling between moto's CF's and our own APIs, by patching some methods in `moto` and forwarding CF requests to our `template_deployer.py` implementation.
This PR also contains some cleanup and removal of old/deprecated/unneeded code.

Refactor CloudFormation implementation

---

.gitignore
Dockerfile
README.md
bin/docker-entrypoint.sh
bin/supervisord.conf

Primarily this can be used to create resources on localstack which is why the aws cli is also installed so the script running inside container can use it.
It solves problems like https://github.com/localstack/localstack/issues/1014

Allow a init.d like dir to be used to execute scripts upon startup

---

localstack/services/apigateway/apigateway_listener.py
localstack/services/awslambda/lambda_api.py
localstack/services/cloudformation/cloudformation_listener.py
localstack/services/cloudformation/cloudformation_starter.py
localstack/services/infra.py
localstack/services/install.py
localstack/stepfunctions/models.py
localstack/utils/aws/aws_stack.py
localstack/utils/cloudformation/template_deployer.py
localstack/utils/common.py
tests/unit/test_misc.py

Add CloudFoundry integration for Step Functions and API Gateway

Add CloudFoundry integration for Step Functions and API Gateway

---

localstack/services/s3/s3_listener.py

This commit fixes issues #869 and #538.
It should also make the test from PR #1120 pass.

Fix the upload of empty S3 objects with chunk encoding

---

localstack/dashboard/web/package.json
localstack/services/awslambda/lambda_api.py
localstack/services/cloudformation/cloudformation_starter.py
localstack/services/dynamodb/dynamodb_starter.py
localstack/services/stepfunctions/stepfunctions_starter.py
requirements.txt

* Add support for mounting Lambda code locally. The primary goal is to make local Serverless applications deploy faster and with lower memory footprint.
* Add a simple `/_stats` endpoint in CloudFormation API for basic memory profiling
* Adjust max heap size for Java processes

Add support for mounting Lambda code locally

---

Makefile
README.md
localstack/constants.py
localstack/ext/java/pom.xml
localstack/services/awslambda/lambda_api.py
localstack/services/cloudformation/cloudformation_starter.py
localstack/stepfunctions/models.py
localstack/utils/aws/aws_stack.py
localstack/utils/cloudformation/template_deployer.py
tests/unit/test_lambda.py

* Fix mapping of environment variables in Lambda functions
* Ensure that the CloudFormation `Ref` attribute returns the appropriate value (ARN instead of resource name)
* Support updates in CF template deployment (e.g., update environment variables of a Lambda)
* Correctly set `physical_resource_id` in the `moto` resource objects that represent the CF stack

Refactor CF deployment for Lambda, DynamoDB & API GW

---

localstack/plugins.py
localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/services/stepfunctions/stepfunctions_listener.py
requirements.txt
tests/integration/test_stepfunction.py

Fix handling of Lambda invocation results.
* Update `flask` to latest version (fixes an issue with chunked transfer encoding in Lambda API)
* Fix Step Functions integration test (previously were hanging as soon as more than one state was defined in the state machine)
* Return `X-Amz-Function-Error` header in Lambda API

Fix handling of Lambda results

---

localstack/ext/java/src/main/java/cloud/localstack/docker/command/RunCommand.java

This is to address the issue https://github.com/localstack/localstack/issues/815 
right now the junit triggered docker containers will stay around and pile up since they are not removed automatically. 
I think it's ok to ALWAYS use the --rm option since the junit containers are meant to be temporary anyways. 
Thoughts?

Auto-remove docker contain after java unit test

---

localstack/services/apigateway/apigateway_listener.py

This fixes an error when sending a JSON encoded list via an AWS_PROXY to a lambda function.
When using the `aws-lambda-go/lambda` Go package the error looks like:
```
{
"errorMessage": "json: cannot unmarshal array into Go struct field APIGatewayProxyRequest.body of type string",
"errorType": "UnmarshalTypeError"
}
File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 301, in run_lambda event, context=context, version=version, asynchronous=asynchronous)
File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 136, in execute result, log_output = self.run_lambda_executor(cmd, environment, asynchronous)
File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 69, in …
```

Fix API gateway AWS_PROXY when sending a JSON list as payload

---

README.md
localstack/config.py
localstack/services/cloudformation/cloudformation_starter.py
localstack/services/dynamodb/dynamodb_starter.py
localstack/services/es/es_starter.py
localstack/services/firehose/firehose_api.py
localstack/services/infra.py
localstack/services/kinesis/kinesis_listener.py
localstack/services/kinesis/kinesis_starter.py
localstack/services/sqs/sqs_starter.py
localstack/services/stepfunctions/stepfunctions_starter.py

Fixes #294 - define dependent and composite services in config.
This PR introduces the notion of `API_DEPENDENCIES` and `API_COMPOSITES` in `infra.py`. 
`API_DEPENDENCIES` are used to define which APIs (e.g., `dynamodbstreams`) require which other APIs to be started as well (e.g., `kinesis`). The idea is that the user should not have to define the dependent APIs manually, but the framework should take care of this automatically.
`API_COMPOSITES` allow to define sets of APIs under a shorthand name. For example, `SERVICES=serverless` refers to a set of APIs that are frequently used for Serverless applications. These composites can be combined with other custom APIs the that user specifies.

Define dependent and composite services in config

---

localstack/services/dynamodb/dynamodb_listener.py

In case of a failing data modification in dynamodb (other response codes than 200) the dynamodbstream was still getting the data.
This PR fixes this issue for UpdateItem, DeleteItem  and PutItem.
Further, if PutItem is a MODIFY, the OldImage should be provided in the dynamodb stream. This is fixed as well.

Fix for incorrect response handling in dynamodb listener

---

Dockerfile

Dockerfile should expose all needed ports for Localstack/AWS services

Dockerfile should expose all needed ports for Localstack/AWS services

---

README.md
bin/docker-entrypoint.sh
bin/supervisord.conf
localstack/config.py

Add `START_WEB` config parameter, which allows to control whether the Web API should be started in Docker

Add START_WEB config parameter

---

README.md
bin/docker-entrypoint.sh
localstack/config.py

Closes #1102 
cc @whummer 
As mentioned in the issue, this only goes for Docker. I don't think it's worth doing it in localstack itself.
Maybe one very minor point of attention though: `LOCALSTACK_HOSTNAME` environment variable does already exist in localstack as a read-only environment variable. It'll be overridden by the localstack process itself, so I don't think it will cause any problem, apart from some confusion maybe.
Thanks.

Allow using 'LOCALSTACK_' prefix in Docker environment variables.

---

README.md

Update to make clear that the docker-compose file requires version 2.1 or greater.
This is related to #1177

Update docker compose version

---

bin/Dockerfile.base

Make target 'docker-build-base' is failing due to java version conflicts, with the following error:
```
Step 12/33 : RUN set -x && apk add --no-cache openjdk8="$JAVA_ALPINE_VERSION"     && [ "$JAVA_HOME" = "$(docker-java-home)" ]
---> Running in 27d520e1a379
+ apk add --no-cache 'openjdk8=8.191.12-r0'
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
openjdk8-8.201.08-r0:
breaks: world[openjdk8=8.191.12-r0]
The command '/bin/sh -c set -x && apk add --no-cache openjdk8="$JAVA_ALPINE_VERSION"     && [ "$JAVA_HOME" = "$(docker-java-home)" ]' returned a non-zero code: 1
make: *** [Makefile:49: docker-build-base] Error 1
```
- Updates Java Alpine version …

Make target 'docker-build-base' failing

---

localstack/services/firehose/firehose_api.py
tests/integration/test_integration.py
tests/unit/test_firehose.py

Addresses #1221 with behavior based off of docs [here](https://docs.aws.amazon.com/firehose/latest/APIReference/API_ListTagsForDeliveryStream.html).

#1221 Add firehose support for tags

---

localstack/services/cloudformation/cloudformation_starter.py
localstack/services/infra.py

Fix port mappings for CloudFormation API.
This fixes an issue where ports are not mapped correctly if users specify a composite service like `SERVICES=serverless`.

Fix port mappings for CloudFormation API

---

localstack/services/kinesis/kinesis_listener.py

Shamelessly pilfered from https://github.com/aventurella/localstack/commit/0a1b454, this commit addresses https://github.com/localstack/localstack/issues/654
This commit allows Terraform to run against Localstack and create Kinesis resources.

add UpdateShardCount support for Kinesis

---

README.md

When you change the local path (on the host side) of the volume /tmp/localstack, localstack has to know the target path on the host (don't know why though).
If you change:
```
volumes:
- /tmp/localstack:/tmp/localstack
```
to
```
volumes:
- /something/else:/tmp/localstack
```
You need to set HOST_TMP_FOLDER to /something/else
I had issues with lambda especially.

Add documentation about HOST_TMP_FOLDER

---

README.md

I was manipulating `HOST_TMP_FOLDER` in order to run local code with lambda but it was not the right way to go.
Thanks to https://github.com/localstack/localstack/pull/1142, there is a straight way to achieve this so I add it to the documentation.
I don't see any good reason to edit `HOST_TMP_FOLDER` so I suggest to remove the previous reference.

Add documentation to run lambda with local code

---

localstack/services/sqs/sqs_listener.py
tests/unit/test_sqs_listener.py

This PR is a followup to https://github.com/localstack/localstack/pull/1239
In production AWS, Lambda functions initiated by SQS have the schema of the `MessageAttributes` munged from one structure into another structure.  We found this out today while testing out a function in production.   
Unfortunately, I'm unsure if this is as a result of some sort of processing happening on the SQS egress side or on the Lambda ingress side.  Either way, the structure changes and needs more massaging.  I'm also uncertain as to whether this post-processing of the `MessageAttributes` payload will change between languages (e.g. JavaScript vs. Python) or if this will remain consistent.   Because of this uncertainty, I don't know if this is a bug in ElasticMQ or with the Localstack Lambda processing. …

Fixes the data schema for the MessageAttributes when being output to Lambda

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

This should fix #1250.
To reproduce:
```bash
$ aws --endpoint-url=http://localhost:4572 s3 mb s3://my_bucket
make_bucket: my_bucket
$ aws --endpoint-url=http://localhost:4572 s3api put-bucket-versioning --bucket my_bucket --versioning-configuration Status=Enabled
$ aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name my_queue
{
"QueueUrl": "http://localhost:4576/queue/my_queue"
}
$ aws --endpoint-url=http://localhost:4576 sqs get-queue-attributes --queue-url "http://localhost:4576/queue/my_queue" --attribute-names QueueArn --query Attributes --output text
arn:aws:sqs:elasticmq:000000000000:my_queue
$ notification_configuration=$(cat << EOF
{
"QueueConfigurations": [
{
"Id": "my_id",
"QueueArn": "arn:aws:sqs:elasticmq:000000000000:my_queue",
"Events": [ …
```

Expose correct versionId in S3 event message

---

localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
tests/unit/test_lambda.py
tests/unit/test_sns_listener.py

Fix Lambda event source mappings to respect the state (enabled/disabled). Default to enabled if no state is present.
This requires updated to `add_event_source_mapping` and `update_event_source_mapping`.
Added tests for these functions.

Respect the lambda event source mapping state that is passed in

---

bin/Dockerfile.base

Fix to avoid `aws` command to fail when displaying the help from inside the docker container `localstack/localstack:0.9.0`
```
bash-4.4# aws help
Could not find executable named "groff"
```

Fix: Added `groff` package to Dockerfile.base

---

localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java

This is to make the path correct after the python3 change in https://github.com/localstack/localstack/commit/0886a249ab8bbfea47b68597045a061ef5c55ece

#1293 fix PORT_CONFIG_FILENAME path to the python3.6 location

---

Dockerfile
bin/supervisord.conf
localstack/dashboard/api.py
localstack/services/infra.py

Do not modify docker.sock permissions by default, as this can have dangerous side-effects.
This PR reverts to the previous behavior where the LocalStack main process runs as `root` (by default) and hence should have access to `/var/run/docker.sock`.
Note that `root` is the default, but not enforced in `supervisord.conf` - users can overwrite the user by passing the `--user=..` to docker run when starting the container.

Do not modify docker.sock permissions by default

---

localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDockerExtension.java
localstack/ext/java/src/test/java/cloud/localstack/docker/Junit5NestedTest.java

By registering the Extension in the context, we can avoid multiple image creation and this way avoid Exception thrown.
See #1330 for more context.

Add support for @Nested Junit5 tests

---

localstack/services/awslambda/lambda_executors.py

It looks like duration on line 400 was always negative as the times in the invocation time dictionary is the invocation time * 1000. This makes that comparison symmetric.

Fix bad idle container time check

---

bin/docker-entrypoint.sh
bin/supervisord.conf

Ok, so this is kind of crazy. See [this docker-compose issue](https://github.com/docker/compose/issues/6018).
Unfortunately, we're logging a lot through our go1.x lambdas, which will eventually fill up the /dev/fd/2 descriptor. This causes a HARD hang on localstack that just ... confounded us for 96 developer hours. We inspected the threads once the program blocked, and saw that it was blocking one either print or writes to stderr. That was a new one for me. If we write to a file instead then tail both the out and the err streams, this issue goes away completely for us.
If you'd like to handle the output in a different way please let me know and I'll see what other solutions there could be.

Fix blocked out/err output under docker/docker-compose

---

localstack/services/awslambda/lambda_executors.py

Some runtimes, such as lambci/lambda:go1.x, read the _LAMBDA_SERVER_PORT to get the port they should bind to for IPC calls. At least in this environment, multiple calls to the same reused container can cause one of the invocations to silently fail because the port is already bound.
This simply assigns a port from the range 5000-5500 so that each invocation gets the sequentially least recently used port. 
If you'd like, this behavior can be gated behind an additional envvar (and the range can be configured similarly). Let me know your thoughts on this.

Assign unique ports under docker-reuse

---

localstack/services/sns/sns_listener.py
tests/integration/test_sns.py

This PR removes the auto registering of topic when receiving requests and throw an error when a publish is called on a non existent topic (just like SNS does).
I also tried this with a Java client and it works :)
Fixes #1319.

Check if the topic arn exists before publish

---

bin/Dockerfile.base
localstack/constants.py
localstack/services/es/es_api.py
localstack/services/es/es_starter.py
localstack/services/install.py
requirements.txt

https://aws.amazon.com/about-aws/whats-new/2019/04/amazon-elasticsearch-service-announces-support-for-elasticsearch-6-5/?nc1=h_ls

Upgrade ElasticSearch 6.5

---

localstack/services/awslambda/lambda_api.py
localstack/utils/aws/aws_models.py
localstack/utils/common.py
tests/unit/test_lambda.py

The responses returned from `list_versions`, `create_function`, `create_alias`, `update_alias` and `update_function_code` did not match the corresponding responses returned by AWS. This has been fixed in this PR.

Lambda responses match the corresponding AWS responses

---

Dockerfile
Makefile

Squash and reduce size of Docker image. Reduces the size of the uncompressed image from approximately 1.29GB to 702MB.

Squash and reduce size of Docker image

---

bin/Dockerfile.base
localstack/constants.py
localstack/services/es/es_api.py

https://aws.amazon.com/about-aws/whats-new/2019/06/amazon-elasticsearch-service-announces-support-for-elasticsearch-67/?nc1=h_ls
ingest-user-agent is already built-in ES
https://www.elastic.co/guide/en/elasticsearch/plugins/6.7/ingest-user-agent.html

Upgrade to ElasticSearch 6.7

---

localstack/ext/java/src/main/java/cloud/localstack/docker/Container.java
localstack/ext/java/src/test/java/cloud/localstack/docker/BasicDockerFunctionalityTest.java
localstack/ext/java/src/test/java/cloud/localstack/docker/ContainerTest.java

The LOCALSTACK_PORTS constant in Container.java didn't include the secretsmanager port (4584).  I added it plus a basic test to verify the plumbing.
This is to address #1350.

Support secretsmanager via LocalstackDockerExtension

---

Dockerfile
README.md
docker-compose.yml
localstack/constants.py
localstack/ext/java/src/main/java/cloud/localstack/Localstack.java
localstack/ext/java/src/main/java/cloud/localstack/ServiceName.java
localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java
localstack/plugins.py
localstack/services/infra.py
requirements.txt

This adds basic EC2 support using the prexisting Moto implementation. 
It needs an update to the client to pass through the proper port, although I've already bumped the requirements.txt version and submitted a PR - see [here](https://github.com/localstack/localstack-python-client/pull/15).
Open to any input! :)
Closes #691

Implement EC2 support through Moto

---

docker-compose.yml

Currently there isn't a one to one mapping in the ports.  Therefore it is causing the `docker-compose up` command to generate the error in the screenshot below: 
The PR here increases the ports to match the ranges and prevent this error.  If it needs to be decreased instead, I can go ahead and do that as well

Fix port range for docker-compose

---

localstack/services/sns/sns_listener.py
tests/integration/test_sns.py

When we try to send SMS through SNS, we don't have to use an existing topic. This fixes #1361.
Also I did a bit of refacto around the SNS tests as there was lots of code dupplicates.

Do not check topic existence for SMS using SNS

---

bin/docker-entrypoint.sh

PR #1181 introduced the ability to prefix localstack's environment
variables with `LOCALSTACK_` in the Docker image. However, it also
introduced a crash when a variable called `LOCALSTACK_` immediately
followed by a digit was present in the environment. The entrypoint
would try to re-export a variable starting with a digit which would
obviously fail.
The fix consist in skipping problematic variables in the entrypoint.
Such variable don't make sense for localstack anyways.
Fixes #1387

Fix corner-case with `LOCALSTACK_` prefix strip.

---

localstack/services/s3/s3_starter.py

The python executable that was used to start S3 was sometimes different from the one that was used to install and run localstack. Therefore, S3 service could not start. With my modification, the same python executable will always be used to start S3 as the one running localstack.
Fixes #808

Fixed incorrect python executable used to start S3

---

localstack/services/iam/iam_listener.py
localstack/utils/aws/aws_stack.py
tests/integration/test_iam_credentials.py

Localstack overwrites the account ID in ARNs in IAM responses from moto, but did not reset it when sending requests to it.
I added a test case to demonstrate the bug that this PR addresses.

Fixed IAM requests sent with wrong account ID to moto

---

localstack/services/awslambda/lambda_api.py
localstack/services/sns/sns_listener.py

Currently, when a Lambda function is invoked by a SNS topic, some attributes aren't forwarded. This PR includes the following attributes inside the object in the `Records` array:
- EventSource with a fixed value of `localstack:sns`
- EventVersion with a fixed value of `1.0`
- EventSubscriptionArn with the arn of the subscriptoin between the topic and function,
- MessageAttributes containing an object with the message attributes published in the original event
**Note for the `EventSource` attribute**: originally, this attribute have a fixed value of `aws:sns`. In my opinion, change this value gives an opportunity to the services that are using localstack to know in which environment they are being executed, but I would like to know what you think about.

Added MessageAttributes and others on SNS publish payload

---

requirements.txt

Having some issue running with `make reinstall-p3 init prepare-java-tests-if-changed`
```
...
Installing setuptools, pip, wheel...
done.
ERROR: awscli 1.16.206 has requirement PyYAML<=5.1,>=3.10; python_version != "2.6", but you'll have pyyaml 5.1.1 which is incompatible.
...
```
After version constraint update, it works fine.

awscli requires `PyYAML<=5.1,>=3.10`

---

README.md
localstack/plugins.py
localstack/services/infra.py
tests/integration/test_events.py

This adds a moto server for CloudWatch Events / EventBridge.
Relates to issue #103 but does not add a full implementation with event triggering. The benefit of merging this PR is that you can invoke CloudWatch Events APIs like `put_rule` and `put_events` against a local target. A separate PR would be required to add full event bus support with scheduled events, triggers and targets.

Add basic EventBridge (CloudWatch Events) support

---

localstack/services/dynamodbstreams/dynamodbstreams_api.py

python3.6 will return `TypeError: encoding without a string argument` when running ```uuid.uuid5(namespace=namespace, name=namestring.encode('utf-8'))``` , which seems to be only supported by python2, thus causing error on DynamoDB streams api.
Since LocalStack latest docker image runs on python3.6, I think this issue will cause shard_id generation failure in `dynamodbstreams_api.py`.
More reference regarding to this issue:
`https://bugs.python.org/issue34145`

Fix dynamodbstreams api uuid generation incompatibility with python 3.6

---

localstack/utils/server/multiserver.py

If you start localstack with only one (moto)service (e.g. `events) it will start it and stop it immediately.
I've found that the newly introduced multiserver causes this issue, cause it's thread is not returned [here](https://github.com/localstack/localstack/blob/4fe68f064b2f3d6dff2a102ba2de4793502ccf1b/localstack/services/infra.py#L385) in the main thread (and therefore the main thread is stopped [here](https://github.com/localstack/localstack/blob/4fe68f064b2f3d6dff2a102ba2de4793502ccf1b/localstack/services/infra.py#L395), as expected).

fix: prevent infra from stopping if multiserver is used

---

.travis.yml
localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java
localstack/services/awslambda/lambda_executors.py
localstack/utils/server/multiserver.py
requirements.txt

Command line arguments are limited in size, but the event body for lambda should be able to accommodate up to 6Mb of data.  Event bodies can be sent to [lambci/docker-lambda](https://github.com/lambci/docker-lambda) as either an environment variable, a command line argument, or as STDIN.  
Fixes #1055 and #1081

Lambda Event Body over STDIN

---

localstack/services/dynamodbstreams/dynamodbstreams_api.py

while trying to test my docker image for #1526 i ran into the issue supposedly fixed by #1469, but the same exception "encoding without a string argument" was happening. these tweaks made it work for me...

fix #1469 - must wrap stream_arn, not kinesis_shard_id

---

localstack/services/dynamodbstreams/dynamodbstreams_api.py

The DynamoDB streams endpoint was throwing away NextShardIterator, making it impossible for continuation through iterator reuse.

support NextShardIterator for continued GetRecords on a DynamoDB stream

---

README.md
localstack/config.py
localstack/services/kinesis/kinesis_starter.py

Ability to set two new environment variables (both of which default to values prior to this PR):
KINESIS_SHARD_LIMIT
KINESIS_LATENCY
Can fix #1524 by setting (should this be the default setting?)
KINESIS_SHARD_LIMIT=Infinity
When using localstack in a test environment in which many streams are created/destroyed over time, the latency introduced by kinesalite defaults, arbitrarily increase execution time and the tests eventually hang after repeated use due to #1524.
Possibly related issues (briefly reviewed some of the dialog in each):
#1091
#894
#918
#230
#789
#753
#514
For those having issues with the references tickets, see if running my docker build solves your issues: `parisholley/localstack:latest`
I haven't dug into, but I think the way the GeneralProxy is handling exceptions from …

support overriding kinesalite defaults

---

localstack/constants.py

I ran into issue #1416, which seems to result from interactions between Localstack and Moto where Localstack hardcodes AWS account ID 000000000000 into SQS queue ARNs, but Moto expects ARNs containing AWS account ID 123456789012.
This PR allows users of Localstack to workaround #1416 by supplying `TEST_AWS_ACCOUNT_ID=123456789012` as an environment variable to Localstack. It's not a true fix, but hopefully an acceptable stop-gap.

allow overriding aws account id with TEST_AWS_ACCOUNT_ID env var

---

bin/docker-entrypoint.sh

the supervisord logfiles are touched but not cleared on container
runtime which causes the scripts under `/docker-entrypoint-initaws.d/`
to run prematurely. This will most likely fix #1494 , #1457 , and #1412.
I'm not sure how much this impacts people on backward compatibility i.e. people using the supervisord logs directly instead of the containers logs.

clear tmp supervisord logs at container startup

---

localstack/services/awslambda/lambda_executors.py

Fixes #1583 — Add missing `--rm` flag to `docker create` for `LAMBDA_REMOTE_DOCKER=true`

Add --rm to docker create command to delete container on exit

---

localstack/services/awslambda/lambda_api.py

Fixes #1581 — only check that the qualifier exists for the lambda function if the lambda function exists in the first place.
I couldn't find any tests around this to add to — any advice on how to test this would be very welcome!

Fix not_found check on lambda execution

---

localstack/services/sns/sns_listener.py
tests/unit/test_sns_listener.py

This seems to be an official field on SNS messages
See https://docs.aws.amazon.com/en_pv/sns/latest/dg/sns-message-and-json-formats.html

Add Timestamp to SNS messages

---

Makefile
localstack/constants.py
localstack/dashboard/api.py
localstack/services/awslambda/lambda_executors.py
localstack/services/generic_proxy.py
localstack/utils/common.py
tests/unit/test_lambda.py

* set Java lambda debug port only when needed
* fix CORS in proxy (addresses #1573)
* allow customizing of certificate serial number
* add `LOCALSTACK_WEB_PROCESS` env variable to flag the process running the Web UI

Set Java lambda debug port only when needed; fix CORS in proxy

---

localstack/services/dynamodb/dynamodb_listener.py
localstack/services/dynamodbstreams/dynamodbstreams_api.py
localstack/utils/aws/aws_stack.py

Fixes (#1540)
After creating the dynamodb table with streams, or updating the table and enabling streams, StreamArn should be passed through to make stream definition in dynamodb streams uniform with dynamodb table definitions.

DynamoDB StreamArn should be uniform across dynamodb and dynamodbstreams API (# 1540)

---

localstack/services/dynamodbstreams/dynamodbstreams_api.py

Fixes #1604 
localstack docker image is using python 3.6.8, latest fix for describe stream fixed the crash for python 2.7 and broke it for the docker image, the cause is #1605. This PR will roll it back because the docker image is reference.

fix describe-stream crash for python3.6.8 (#1604)

---

localstack/ext/java/src/main/java/cloud/localstack/Localstack.java

Make setupInfrastructure public so tests can call the method when infrastructure is needed.
Closes:
https://github.com/localstack/localstack/issues/1615

Make setupInfrastructure public

---

README.md

Updates `README.md` to include code formatting around `/docker-entrypoint-initaws.d`

Adds missed code formatting to README.md

---

localstack/services/apigateway/apigateway_listener.py
tests/integration/test_api_gateway.py

This is an attempt to help fix this issue https://github.com/localstack/localstack/issues/1596 raised by @vballa whenever an SQS -> Lambda is triggered by previously it was erroring in the md5 hashing the response. This would only ever happen if an event source with a lambda was setup for the GW -> SQS -> lambda. 
The reason for this was that there was no "data" body for GET requests meaning that data in https://github.com/localstack/localstack/blob/e65705a6ebf93ed7fbb05b690ebeb2c9c4aa88ae/localstack/services/sqs/sqs_listener.py#L52 was None and therefore throwing an exception when trying to hash.
We could have fixed it by remapping the query params in the [forward_request](
https://github.com/localstack/localstack/blob/e65705a6ebf93ed7fbb05b690ebeb2c9c4aa88ae/localstack/services/sqs/sqs_l …

fix(bug): fix SQS->Lambda when setup with api gateway

---

localstack/services/firehose/firehose_api.py

Fixed firehose put-record-batch to return 'RequestResponses' as list of maps with 'RecordId' as a uuid4 similar to put-record
I couldn't find how to test this properly from your other test files, if you have any pointers to add a test for this let me know.

firehose put-record-batch response format

---

localstack/services/sns/sns_listener.py
tests/integration/test_sns.py

Currently calls like 
```
awslocal sns publish \
--target-arn "arn:aws:sns:us-east-1:000000000000:endpoint/APNS/abc/0f7d5971-aa8b-4bd5-b585-0826e9f93a66" \
--message "Hello world"
```
do not work, and give the error "Topic not found". The SNS docs state that only one of topic, target or phone number is required. This change means they'd be silently handled in the same way as SMS messages currently are, as per #1369

Allow sns publish to a target-arn

---

localstack/services/awslambda/lambda_api.py

I noticed that lambda deployment fails if the file path to the code has any spaces in it (When deploying without mounting flag enabled). I've found the error and added the fix.
It was missing quotes around the file path. I didn't think tests for this was necessary.

Fix: Lambda code mount fails with path with spaces

---

localstack/services/cloudformation/cloudformation_starter.py
localstack/utils/aws/aws_responses.py
localstack/utils/cloudformation/template_deployer.py

Minor refactoring in CF logic:
* make `describe_stack_resource` more resilient to errors
* make `parameters` optional in resource definition, default to plain parameters dict

Minor refactoring in CF logic to retrieve resource details

---

.env
docker-compose.yml

Addresses #1113
Basically allow for the container to have a name when it is launched.  Is it defined as an environment variable.  The `.env` file is there as according to the documentation here: https://docs.docker.com/compose/environment-variables/
Variables listed in the `.env` file can be read in when the user runs `docker-compose up`
The last change made is that there is a newer spec for compose files which is shown here: 
https://docs.docker.com/compose/compose-file/#variable-substitution
So I went ahead and updated the specs for the docker-compose file to a later version
Signed-off-by: Zuhayr Elahi <elahi.zuhayr@gmail.com>

ADDED an env variable to the docker compose file

---

localstack/package.json

When the persistence is enabled, the Kinesis mock service crash with the follow stacktrace 
```
Starting mock Kinesis (http port 4568)...
internal/modules/cjs/loader.js:797
throw err;
^
Error: Cannot find module 'leveldown'
Require stack:
- /opt/code/localstack/localstack/node_modules/kinesalite/db/index.js
- /opt/code/localstack/localstack/node_modules/kinesalite/index.js
- /opt/code/localstack/localstack/node_modules/kinesalite/cli.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
at Function.Module._load (internal/modules/cjs/loader.js:687:27)
at Module.require (internal/modules/cjs/loader.js:849:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.create (/opt/code/localstack/localstack/node_modules/kinesalite/db/index.js:31:35)
at kinesalite …
```

Upgrade kinesalite to fix leveldown module not found

---

localstack/services/apigateway/apigateway_listener.py
tests/integration/lambdas/lambda_integration.py
tests/integration/test_api_gateway.py

Fix encoding of non-ASCII results from API Gateway

Fix encoding of non-ASCII results from API Gateway

---

localstack/services/cloudformation/cloudformation_starter.py

Fix CloudFormation deployer to properly skip resource updates. 
Fixes an issue where CF keeps retrying to deploy resources, even if they already exist and are not requested for updating.
Fixes #1677

fix CloudFormation deployer to properly skip resource updates

---

README.md

The pip install command mentioned in the README for localstack[full] will not work if simply copied and pasted on Linux and other systems.  Added quotes to the command to make this easier to copy and paste.

adding double quotes to make copying and pasting of pip install easier

---

localstack/services/cloudformation/cloudformation_listener.py
localstack/services/s3/s3_listener.py
localstack/services/sns/sns_listener.py
localstack/utils/aws/aws_stack.py

* Support TemplateURL for ValidateTemplate API - fixes #660
* Support Marker argument for S3 list-objects  - fixes #636
* Overwrite default region in SNS request headers - fixes #731

Support TemplateURL for CF ValidateTemplate; support Marker for S3 ListObjects; honor DEFAULT_REGION for SNS

---

bin/Dockerfile.base

ref: https://github.com/localstack/localstack/issues/1619
ref: https://github.com/localstack/localstack/pull/1652
#1652 fixed the bug and upgrade the version of elasticmq in python code.
But in docker, the old version is used.

Upgrade elasticmq server's version in Dockerfile.base 0.14.5 -> 0.15.2

---

localstack/services/awslambda/lambda_api.py
tests/unit/test_lambda.py

Avoids matching on all prefixes but still matches on path prefixes.

smarter lambda event source ARN match fixes #1705

---

localstack/services/cloudformation/cloudformation_listener.py
localstack/utils/cloudformation/template_deployer.py
localstack/utils/common.py
tests/unit/test_lambda.py

Fix cloudformation template downloads from S3 URLs - direct downloads have been failing with 403 if no proper ACLs are provided.

Fix CloudFormation template downloads from S3 URLs

---

localstack/services/awslambda/lambda_api.py
tests/integration/test_sqs.py

* Extend test for SQS delete message - addresses #468
* Raise error for local Lambda mount in combination with `LAMBDA_REMOTE_DOCKER`

Extend test for SQS delete message

---

localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java
localstack/services/apigateway/apigateway_listener.py
localstack/services/apigateway/helpers.py
requirements.txt
tests/integration/test_api_gateway.py

Api Gateway authorizer endpoints didn't work correctly and crashed terraform. Fixed in this PR. Additionally added PUT/DELETE methods.

Fix API Gateway Authorizer Implementation

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

See #1734 for what this PR partially addresses (it handles the ErrorDocument functionality but not IndexDocument).
This adds emulation of S3's ErrorDocument website configuration. It should not change the behavior of a LocalStack S3 bucket that has no website configuration.

Add S3 website ErrorDocument emulation

---

localstack/services/awslambda/lambda_api.py
tests/integration/test_lambda.py

Fixed random statement id in order to use the provided by the requests #1788.
Updated tests and responses when the policies don't exists anymore.

Fix incorrect statement id in Lambda add-permission API

---

localstack/services/awslambda/lambda_api.py
localstack/utils/testutil.py
tests/integration/test_lambda.py

Allow Java Lambdas with code provided in multiple JAR files embedded in a ZIP file - fixes #385

Allow Java Lambdas with code provided in multiple JAR files

---

localstack/utils/common.py
tests/unit/utils/test_common.py

Proposed fix for Issue #1811.
1. Adds `@synchronized` decorator to provide thread-based locking support
1. Added `@synchronized` around `common.generate_ssl_cert`

Added @synchronized decorator to provide thread-based locking support for ssl cert creation

---

README.md
localstack/constants.py
localstack/plugins.py
localstack/services/infra.py
localstack/services/install.py
localstack/services/kms/kms_starter.py
localstack/utils/common.py
tests/integration/test_kms.py

Add initial support for KMS - addresses #206 .
This implementation is currently based on the wonderful [`local-kms` library](https://github.com/nsmithuk/local-kms), with pre-built binaries published here: https://github.com/localstack/localstack-artifacts/tree/master/local-kms
Note that moto has recently also added initial [support for KMS](https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md#kms), so we may want to consider switching to their implementation at some point, depending on API method coverage.

Add initial support for KMS via local-kms

---

Makefile
localstack/ext/java/src/main/java/cloud/localstack/Localstack.java
localstack/ext/java/src/main/java/cloud/localstack/TestUtils.java
localstack/ext/java/src/test/java/cloud/localstack/docker/BasicDockerFunctionalityTest.java
localstack/services/es/es_api.py
tests/integration/test_cloudwatch.py
tests/integration/test_logs.py

* Add test for CW logs multi-byte message - addresses #1828 
* Allow trailing slashes in Elasticsearch API requests - fixes #1139
* Add basic tests for CloudWatch - addresses #1123

Add test for CW logs multi-byte message; allow trailing slashes in Elasticsearch API; add CloudWatch tests

---

localstack/ext/java/src/main/java/cloud/localstack/Localstack.java
localstack/ext/java/src/main/java/cloud/localstack/TestUtils.java
localstack/ext/java/src/main/java/cloud/localstack/docker/Container.java
localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerAnnotationProcessor.java
localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerConfiguration.java
localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerProperties.java
localstack/ext/java/src/main/java/cloud/localstack/docker/command/PortCommand.java
localstack/ext/java/src/test/java/cloud/localstack/docker/ContainerTest.java
localstack/ext/java/src/test/java/cloud/localstack/docker/PortBindingTest.java

Fix Docker port mapping for JUnit test runner - fixes #1198 .
This PR ensures that the Docker ports are correctly exposed when using the `services` configuration in `LocalstackDockerProperties` (e.g., port `12345` in the example below):
```
@RunWith(LocalstackTestRunner.class)
@ExtendWith(LocalstackDockerExtension.class)
@LocalstackDockerProperties(randomizePorts = false, services = { "sqs:12345" })
public class PortBindingTest {
...
```

Fix Docker port mapping for JUnit test runner

---

localstack/services/es/es_api.py
localstack/services/s3/s3_listener.py

Fix S3 responses for Terraform deployment - fixes #1824 .
In particular, this PR fixes the error responses for APIs related to the following settings:
* bucket lifecycle
* bucket replication
* bucket encryption
* object lock configurations
This PR also contains a minor fix for case-insensitive filter rules - #1249

Fix S3 responses for Terraform deployment

---

localstack/services/awslambda/lambda_executors.py

This PR is to improve the changes made on https://github.com/localstack/localstack/pull/1771 that has changed the lambda executors to add the prefix `20191117-` to the image. 
As it says that this change is necessary to dotnetcore/python lambdas images, I added a check to add the prefix only to these images.

Changing to restrict prefix to only dotnet and python images

---

localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDockerExtension.java
localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerAnnotationProcessor.java
localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerConfiguration.java
localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerProperties.java

This PR is about adding an optional flag to use a singleton docker container instead of start/stop Localstack container for each test class
I agree to the contributor license agreement

Add optional useSingleDockerContainer annotation attribute

---

localstack/services/awslambda/lambda_executors.py

After the PR https://github.com/lambci/docker-lambda/pull/218 we got the issue #1777. This PR is to try to solve this.
* Defining a new value to DOCKER_LAMBDA_API_PORT and DOCKER_LAMBDA_RUNTIME_PORT port on each lambda container execution when network mode `host`.

Adding support to docker_lambda variable DOCKER_LAMBDA_API_PORT

---

localstack/plugins.py
localstack/services/es/es_api.py
localstack/services/es/es_starter.py
tests/integration/test_elasticsearch.py
tests/integration/test_s3.py

Lazily start up Elasticsearch instance on ES domain creation. This helps to significantly speed up startup time and reduce memory consumption for the default configuration.

Lazily start up Elasticsearch instance on ES domain creation

---

localstack/services/stepfunctions/stepfunctions_starter.py

Currently, when attempting to [execute workflow from task](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-nested-workflows.html), I get this error: {"Type":"TaskFailed","PreviousEventId":6,"TaskFailedEventDetails":{"ResourceType":"states","Resource":"startExecution.sync","Error":"StepFunctions-AWSStepFunctionsException","Cause":"The security token included in the request is invalid. (Service: AWSStepFunctions; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: 1a9d805b-55af-4bf3-8515-4bf49e4f81e3)"}}
This PR exposes the `--step-functions-endpoint` flag that was added to the jar but not documented properly in the AWS docs.

feat: expose sfn endpoint

---

localstack/services/s3/s3_listener.py

The objective of this PR is to add content-length header to success_action_status response because it sends an empty response if that header has no value.
This is related to https://github.com/localstack/localstack/pull/1849

Adding content-length header in success_action_status response

---

README.md

Removed example referring to non existent class LocalstackDockerTestRunner from README.

Removed example referring to non existent class LocalstackDockerTestRunner from README.

---

localstack/services/cloudformation/cloudformation_starter.py
localstack/utils/aws/aws_stack.py

Fix CloudFormation `Arn` attribute for CloudWatch LogGroups - fixes https://github.com/localstack/serverless-localstack/issues/60 (required for Serverless Enterprise)

Fix CF Arn attribute for CloudWatch LogGroups

---

localstack/services/awslambda/lambda_api.py
tests/unit/test_lambda.py

Addresses https://github.com/localstack/localstack/issues/1883
Rather than trying to pre-determine whether or not a given string is json-encoded based on the first character, simply give it a try, and assume that raised errors imply it was not.

Added invoke support for json types that are not maps or lists

---

localstack/ext/java/src/test/java/cloud/localstack/S3FeaturesTest.java
localstack/services/s3/s3_listener.py
requirements.txt
tests/integration/test_s3.py

* Fix issue and add test for S3 `listNextBatchOfObjects` - addresses #1061
* Fix S3 delete-objects for non-existing keys - fixes #1893

Add test for S3 listNextBatchOfObjects; fix S3 delete-objects for non-existing keys

---

README.md
localstack/utils/bootstrap.py

* Update documentation around Java/JUnit test runner
* Remove static Elasticsearch endpoint from documentation; re-add dependency between `es`<>`elasticsearch` service ports

Update documentation around Java/JUnit test runner

---

localstack/services/s3/s3_listener.py

Should fix https://github.com/localstack/serverless-localstack/issues/64

Fix URL encoding when reading key name for S3 Range fix

---

localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/utils/common.py

Skip unnecessary extraction of Java lambda archives - this can dramatically improve the performance of deploying large JAR files with lots of files contained.

Skip unnecessary extraction of Java lambda archives

---

localstack/constants.py
localstack/services/kms/kms_starter.py

Following on from @whummer's PR: https://github.com/localstack/localstack/pull/1839
Pulls in the binaries from the official local-kms repo. The URL will always return the latest stable tag of v3. Ensures new features (e.g. https://github.com/nsmithuk/local-kms/issues/12) are incorporated into localstack. Locking it to MAJOR version 3 ensures no backward breaking changes will be introduced.
Localstack has been given its own subfolder to allow for its naming convention: `local-kms.<arch>.bin`.
At present there are 3 pre-compiled versions:
* `local-kms.osx.bin`
* `local-kms.linux.bin`
* `local-kms.alpine.bin`
local-kms now also prefers some of its environment variables to be prefixed with `KMS_`.

Updated local-kms binary repository

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

If `headers_changed` is `True`, `modified_data` is not necessarily set.  This adds a Body to the `put_object` request to capture this issue.

fixes regression with underscores in S3 upload metadata #1975

---

localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
tests/integration/lambdas/lambda_integration.py
tests/integration/test_sns.py

This PR decouples SQS message processing and lambda execution by running lambdas asynchronously. It also adds a test on SNS-triggered lambdas to see if messages end up in the correct dead letter queue.
It addresses #1967.
@rfunix and @georgeyk contributed with suggestions and pairing.

Make lambdas triggered by SQS run asynchronously

---

localstack/ext/java/src/test/java/cloud/localstack/S3FeaturesTest.java
localstack/services/s3/s3_listener.py
localstack/utils/common.py
requirements.txt
tests/integration/test_s3.py

* Fix CreationDate format for S3 ListBuckets - fixes #1899
* Fix S3 metadata keys starting with an underscore
* Accept self-signed certs in Java tests

Fix CreationDate format for S3 ListBuckets

---

localstack/services/generic_proxy.py
localstack/services/infra.py

* Adjust urllib3 pool size to allow more parallel HTTP requests - fixes #1980
* Avoid auto-closing connections if no `Connection` header is closed - fixes connection issues with the Go AWS SDK.

Adjust urllib3 pool size to allow more parallel HTTP requests

---

localstack/services/awslambda/lambda_api.py
localstack/services/sqs/sqs_listener.py

Fix region for SQS queue ARNs in Lambda event source mappings - fixes #1763

Fix region for SQS queue ARNs in Lambda event source mappings

---

localstack/services/sqs/sqs_listener.py
localstack/services/sqs/sqs_starter.py
tests/integration/test_sqs.py

Hello,
This PR fix two issues with the attributes:
* When we create a queue, attributes not supported by ElasticMQ are not saved 
* When we query specific attributes, the unsupported attributes are all appended to the response
Also ElasticMQ now support tag operations (https://github.com/softwaremill/elasticmq/blob/master/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/TagQueueDirectives.scala), so i removed the hack around the tag and list methods.
There is still an issue around tagging on queue creation but it's on ElasticMQ side (https://github.com/softwaremill/elasticmq/pull/333).
Thanks

Fix SQS queue creation attributes and specific attribute retrieval

---

localstack/services/cloudformation/cloudformation_starter.py
localstack/services/es/es_api.py
localstack/utils/cloudformation/template_deployer.py
tests/unit/test_cloudformation.py

Refactor CloudFormation dependency resolution.
* Add dependency resolution loop to `FakeStack.initialize_resources`
* Fix lookup of existing `ApiGateway::GatewayResponse` resources
* Fix recursive resolution of references in `fn::join` CloudFormation macros
* Enhance logging with more details
* Add `get-compatible-elasticsearch-versions` Elasticsearch API method

Refactor CloudFormation dependency resolution

---

README.md
localstack/ext/java/src/main/java/cloud/localstack/deprecated/LocalstackExtension.java
localstack/ext/java/src/main/java/cloud/localstack/deprecated/TestUtils.java

LocalstackExtension was previously deprecated but was lacking the proper annotation.
This also fixes the documentation for JUnit 5 in the README to use LocalstackDockerExtension instead of the deprecated LocalstackExtension.
Resolves: #1928

Mark LocalstackExtension deprecated

---

localstack/services/es/es_api.py
localstack/services/s3/s3_listener.py
localstack/utils/persistence.py

Add persistence for Elasticsearch Service API calls - supports re-creation of ES domains across LocalStack restarts.

Add persistence for Elasticsearch Service API calls

---

localstack/services/sqs/sqs_listener.py
localstack/utils/bootstrap.py

* Fix setting of empty SQS queue attribute values - fixes #2046
* Modify payload to forward only supported queue attributes to SQS backend
* Ensure environment variable values are strings - should fix #1891

Fix setting of empty SQS queue attribute values

---

localstack/services/awslambda/lambda_executors.py

Fixes: https://github.com/localstack/localstack/issues/2045
Tested with localstack running inside of docker and lambdas are using local executor.

Expose java options for local lambda executors.

---

localstack/services/apigateway/apigateway_listener.py

Fixes: #2055
Check for None before iterating the parsed headers.

Check for None before iterating.

---

Dockerfile
Makefile
localstack/ext/java/src/main/java/cloud/localstack/Localstack.java

Fixes #2066
Similar approach to #1756 but changed everywhere the python path was used along the project.
I think in the long run we should be able to get this value dynamically so it won't break every time python version is updated

Update PYTHONPATH for Python 3.8

---

localstack/services/cloudformation/cloudformation_starter.py
localstack/utils/aws/aws_stack.py
localstack/utils/cloudformation/template_deployer.py

* Add support for static refs in CF `Fn::Sub` strings. Allows to define interpolated strings like `{'Fn::Sub': 'test region ${AWS::Region}'}`
* Minor fix for velocity templates

Add support for static refs in CF Fn::Sub strings

---

localstack/services/awslambda/lambda_executors.py
tests/unit/test_lambda.py

The CloudWatch log stream names created by lambda invocations were incorrect.  
The invocation time is in milliseconds, which wasn't accounted for by the _store_logs method resulting in date prefixes like '52112/01/29'
instead of '2020/02/22'.
So the lambdas thought they ware logging to stream names like:        
"2020/02/21/[$LATEST]549d751bde9d222e4917f4ac838986ed"
but were really logging to names like:
"+52111/12/10/[$LATEST]4b3dcbb1"
There will have to be an additional fix because there's still the issue of the short_uuid vs the long uuid.

Fix for mis-named logstreams created by lambda invocations.

---

localstack/services/awslambda/lambda_executors.py

This pull request is related to an issue I opened a few days ago: https://github.com/localstack/localstack/issues/2018
I chose to use the already existing environment variable LAMBDA_REMOVE_CONTAINERS to prevent containers from being deleted after 10 minutes. At the moment this variable is not taken in consideration when the docker-reuse executor is used.
Let me know your thoughts
Cheers

Use LAMBDA_REMOVE_CONTAINERS with docker reuse

---

README.md
localstack/services/cloudformation/cloudformation_starter.py
localstack/services/s3/s3_starter.py
tests/integration/test_s3.py

Integrate S3 starter into multiserver to reduce startup times and improve performance - fixes #2124

Integrate S3 starter into multiserver to improve performance

---

localstack/utils/cloudformation/template_deployer.py
tests/integration/test_cloudformation.py

* Set a random FunctionName when this property not provided

#1741 Missing required parameter in input: "FunctionName"

---

bin/Dockerfile.base
localstack/constants.py
tests/integration/test_sqs.py

See: https://github.com/softwaremill/elasticmq/pull/341
This PR makes it more compatible with string attributes.
Until now, string attribute has not been validated.
Now it will verify that string attribute does not contain invalid characters .

Use elasticmq 0.15.5 to handle invalid string attribute value

---

Makefile
localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/lambdas/lambda_echo.py
tests/integration/lambdas/lambda_function.py
tests/integration/test_lambda.py
tests/unit/test_lambda.py

* Fix lint error template_deployer.py
* Fix log steam name (That was an issue with get-log-events API)
* Add lambda integration test
- Create topic
- Create a lambda function that subscribe that topic
- Push an message with subject
- Get event message from cloudwatch logs to confirm subject exists in message event

#2131 Missing Message Subject at LambdaExecutor

---

localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/services/s3/s3_listener.py
localstack/services/sqs/sqs_listener.py
localstack/utils/aws/aws_stack.py
localstack/utils/aws/dead_letter_queue.py
tests/integration/test_api_gateway.py
tests/integration/test_sqs.py

Add message polling mechanism for Lambda-SQS integration.
This is a follow-up PR for the change in #2139 . Prior to this change, we used to intercept incoming SQS messages, check if they are linked to a Lambda function (via an event source mapping), and in that case call the Lambda directly with the event message, *without* forwarding the message to the actual SQS queue. This approach is fundamentally flawed, because Lambdas need to have access to the actual message `receiptHandle` in order to manipulate messages in the queue.
With this PR, we now implement an approach that is more in line with what's happening in real AWS. We're forwarding all SQS messages to the queues in all cases, and use a polling thread in the Lambda API to poll SQS queues for new messages. We're using a …

Add message polling mechanism for Lambda-SQS integration

---

requirements.txt

Allowing a range provides for more flexibility when integrating localstack into an existing project or package.
There's a bit of a cat-and-mouse game here, where we want to provide some flexibility in the ranges of packages that are allowed, but so many that it introduces subtle incompatibilities due to the increased number of combinations of package versions that are permitted.
----
Closes localstack/localstack#2019.

Use a range instead of exact pinned versions for some dependencies in requirements.txt.

---

localstack/services/awslambda/lambda_api.py
localstack/services/sns/sns_listener.py
localstack/utils/aws/dead_letter_queue.py
tests/integration/test_sns.py

Added support for SNS redrive policy.
Changed exception handle on lambda_api.process_sns_notification
Changed publish_message to check and send message to dead queue when redrive policy is set.
For proper usage follow the aws doc:
https://docs.aws.amazon.com/sns/latest/dg/sns-configure-dead-letter-queue.html

Added support to redrive policy on SNS product.

---

bin/supervisord.conf

When you start localstack from the official docker container you will get a warning from supervisor:
CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
this PR fixes this warning

fix supervisor warning when running in docker

---

localstack/services/awslambda/lambda_api.py
localstack/services/sqs/sqs_listener.py
localstack/utils/testutil.py
tests/integration/test_integration.py
tests/integration/test_lambda.py
tests/integration/test_sqs.py

Fixes #1364 
* SQS event source poll loop starts after `sqs:SendMessageBatch` events
* SQS -> Lambda trigger now properly respects batch size parameter instead of always sending 1 message (and will send a maximum of 10, consistent with AWS)
* Added integration test for SQS -> Lambda events
* Added sqs test for SendMessageBatch

fix lambda sqs event source for SendMessageBatch

---

localstack/services/s3/s3_starter.py

Fix Lambda deployment for `mountCode=true` - fixes https://github.com/localstack/serverless-localstack/issues/84 , fixes #2164

Fix Lambda deployment for mountCode=true

---

localstack/services/awslambda/lambda_api.py

It appears we only supported python 2.7-3.6 before this for the lambda api in local? This is an attempt to fix that.
Added python 3.7 and 3.8 support to localstacks lambda api.
@whummer let me know if this is incorrect!

Added python 3.* support to lambda api.

---

tests/integration/test_logs.py

* Add integration test for: list_tags_log_group
Fixes #1698

Add test for tag retrieval in Cloudwatch Logs

---

localstack/services/sns/sns_listener.py
localstack/utils/testutil.py
tests/integration/test_lambda.py
tests/integration/test_sns.py
tests/integration/test_sqs.py

* Refactor get lambda event logs functions
* Add integration tests: publish message with target arn
Issues fixed:
#1876 SNS lambda subscription not triggered when using TargetArn instead of TopicArn on publish
#1933 Specifying targetArn when Publish SNS message seems to no longer work

Test sns publish message with TargetArn

---

localstack/services/cloudformation/cloudformation_starter.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/test_cloudformation.py

* Patch moto IAM model
Fixed:
#925 Serverless CloudFormation templates using AWS::Partition fail

Add cfn support for IAM role resource type

---

localstack/services/iam/iam_starter.py
tests/integration/test_iam.py

Fix some iam issues on moto backend
* Patched detach_role_policy function
* Add missing managed policies
Issues fixed:
#2274 iam: Problem with AWSLambdaExecute permission
#2286 Error reading IAM Role in terraform destroy

Fix iam attach/detach issues

---

localstack/services/apigateway/apigateway_listener.py

For some reason the payload going through the listener is of binary type. I've tried to write a test reproducing the issue, but it seems the test setup isn't exactly the same as when not in the test environment.
Fixes this :
When sending this request :
```
POST http://localhost:4567/restapis/{{api_id}}/test/_user_request_/resolve
Content-Type: application/json
{
"firstName": "Charles",
"lastName": "Darwin"
}
```
It returns this error :
```
File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 459, in run_lambda
result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 132, in execute
return do_execute()
File …
```

Fix API Gateway to Lambda when payload is received as bytes

---

localstack/services/cloudformation/cloudformation_starter.py
localstack/services/cloudformation/service_models.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/test_cloudformation.py

- Events Rule
- S3 Bucket Policy
* Add integration tests:
- Events Rule
- Kinesis Stream
- S3 Bucket Policy
- SQS
Issues fixed:
#1616 No Moto CloudFormation support for AWS::KinesisFirehose::DeliveryStream / AWS::S3::BucketPolicy
#2058 Invoking CF stack destroy API call seems to delete the stack but not the resources it has provisioned

* Add CFN support for missing resource types

---

localstack/services/es/es_api.py
tests/integration/test_elasticsearch.py

* Expose external hostname for ES domain - fixes #1929
* Fix CreateElasticsearchDomain by starting process asynchronously in the background.
Note that this now requires to poll for creation status until `Created=true` is returned from the `DescribeElasticsearchDomain` API call, which is in line with how things are working in real AWS.

Fix CreateElasticsearchDomain by starting process asynchronously; expose external hostname for ES domains

---

localstack/services/cloudformation/cloudformation_starter.py
localstack/services/cloudformation/service_models.py
localstack/services/sns/sns_listener.py
localstack/services/sqs/sqs_listener.py
localstack/utils/aws/aws_stack.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/serverless/serverless.yml
tests/integration/test_serverless.py
tests/integration/test_sns.py

* Fix CloudFormation deployment for EventPattern attribute in Events::Rule - addresses #2241 
* Refactor SNS integration tests to create resources locally instead of globally
* Add CF support to update instances of IAM::Role

Fix CloudFormation deployment for EventPattern attribute in Events::Rule

---

localstack/utils/cloudformation/template_deployer.py
tests/integration/test_cloudformation.py

* Add handle delete action for stepfunctions's stateMachine
* Add integration test: cloudformation with events rule without name
Issue fixed:
#2359 Cloudformation doesn't create Cloudwatch event rule

Test cloudformation handle events rule without name

---

Dockerfile
localstack/services/cloudformation/cloudformation_starter.py
localstack/services/s3/s3_starter.py

Fix regression in CloudFormation deployment, caused by recent change in upstream `moto`.

Fix upstream regression in CloudFormation deployment

---

localstack/services/apigateway/apigateway_starter.py
tests/integration/test_api_gateway.py

* Patch apigateway models init functions
* Update integration test
Issue fixed:
#1030 ApiGateway doesn't work with simple AWSClient : responseTemplates should not be null

Fix response format of apigateway put_integration

---

localstack/services/awslambda/lambda_executors.py

#1160 describes problems caused by AWS SDK classes from the localstack-utils-fat.jar overriding classes defined in the actual Lambda jar/zip itself. This causes numerous incompatibility problems.
I was able to isolate and repro this problem with a minimal example ( https://github.com/krrg/localstack-java-classpath-debug )
@whummer implemented a partial fix for this that moved the `localstack-utils-fat.jar` later on the classpath, but this fix only applied to lambdas being run using the `docker` executor.
This PR takes a similar approach, but this time for lambdas being executed locally. Using the minimal example above, I verified that the classpath is now correctly ordered for local lambdas and that my example is able to be invoked without error.

Additional fix for #1160 when running Java lambdas locally

---

.gitignore
.travis.yml
Makefile
bin/Dockerfile.light
localstack/services/install.py

Create a stripped-down "light" version of the Docker image, with lazy loading of Elasticsearch libs, and with the (deprecated) dashboard Web UI sources removed.
The name of the light image is currently `localstack/localstack-light`. This change cuts down the image size (compared to the default `localstack/localstack`) by more than 20%.
In the future, we may want to make this the default behavior, to reduce image size and download volume overall.

Create stripped-down light version of Docker image, with lazy loading of ES libs

---

localstack/services/ec2/ec2_starter.py
localstack/services/s3/s3_listener.py

Fix deletion of EC2 NAT Gateways - instead of deleting the entry, its state should be set to `deleted`, otherwise Terraform fails. Should fix #2340

Fix deletion of EC2 NAT Gateways

---

localstack/services/events/events_listener.py
tests/integration/test_events.py

This PR adds support for scheduled rules that target step functions. This fixes the issue in comment https://github.com/localstack/localstack/issues/2359#issuecomment-622566572 
Note that the new integration test takes just over a minute to run for the same reason as `test_schedule_expression_event_with_http_endpoint` - because it has to add a scheduled execution and the best precision available is running every 1 minute.

Support stepfunctions in scheduled event rules

---

localstack/services/edge.py
tests/integration/test_edge.py
tests/unit/test_edge.py

Tweak the existing handling of POST form data to also treat multipart forms with a 'key' field as S3
I've kept the same logic for multipart forms as the existing logic used for normal form params - if it's a multipart form with a `key` field it's treated as S3.
Added unit tests with example form/multipart form data, and an integration test using presigned post URLs against the edge port.
Hopefully this is the last of the S3 weirdness around the edge port! :) 
Fixes #2464

Add correct handling of S3 multipart form upload via edge port (#2464)

---

localstack/services/dynamodb/dynamodb_listener.py
tests/integration/test_lambda.py

* Fix dynamodb listener
* Add integration test: Disabled event source mapping will not invoke lambda
Issue fixed:
#2541 Disabled lambda event source mapping still triggers lambda

Fix issue disabled event trigger lambda

---

localstack/services/apigateway/helpers.py
tests/unit/test_apigateway.py

Found an issue with path selection when the Path starts with a parameter. From the tests added  path_args = {'/{param1}/{param2}/foo/{param3}': {}, '/{param}/bar': {}} is the main culprit.

Fixing issue with path selection

---

localstack/services/sns/sns_listener.py
localstack/utils/aws/aws_stack.py
tests/integration/test_sns.py

* Add integration test: publish to topic using pure http request
Issue fixed:
#2438 SNS publish does not work with aws-sdk-java 2.11.8

Fix sns listener to handle parameters in path request

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

This PR fixes an issue for s3 where the response content for a presigned post (with `success_action_status` = 201) was incorrect when the "${filename}" variable was used in the key.  The "${filename}" variable should be replaced with the name of the provided file.
Given a POST to the presigned post url with the following parameters:
Bucket: my-bucket
Key: my-key-${filename}
Filename: file.txt
Success Action Status: 201
```
<PostResponse>
<Location>http://localhost/my-key-%24%7Bfilename%7D</Location>
<Bucket>my-bucket</Bucket>
<Key>my-key-${filename}</Key>
<ETag>d41d8cd98f00b204e9800998ecf8427f</ETag>
</PostResponse>
```
```
<PostResponse>
<Location>http://localhost/my-key-file.txt</Location>
<Bucket>my-bucket</Bucket>
<Key>my-key-file.txt</Key> …
```

Replace ${filename} variable in presigned post responses

---

localstack/services/cloudformation/cloudformation_starter.py
localstack/utils/aws/aws_stack.py
localstack/utils/aws/dead_letter_queue.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/test_cloudformation.py
tests/integration/test_dynamodb.py
tests/integration/test_integration.py

* Disable wait_for block (related to dynamodb stream) when creating dynamodb table
* Add action delete for dynamodb table resource type
Issues fixed:
#2607 Cloudformation does not work (tested with DynamoDBstack-amplify.txt template)
#2336 cloudformation deploy regression in latest version

Fix deploy dynamodb table resource issues

---

localstack/services/cloudformation/cloudformation_starter.py
tests/integration/test_cloudformation.py

* Update integration test
Issue fixed:
#2573 Cloudformation: using Ref on a DynamoDB Table is returning the ARN instead of the table name

Deploy stack with DynamoDB table: Ref returning table name

---

localstack/services/events/events_starter.py
tests/integration/test_events.py

Hi all. Thanks so much for developing localstack. I was playing around with cloudwatch events and got something I thought was strange, so I thought I'd try to fix it.
I believe that when cloudwatch events trigger a service (lambda, sqs, firehose, etc) it sends a wrapped version of the actual event, not just the event detail. Namely I think it looks something like this ([source](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/EventTypes.html)):
```
{
"version": "0",
"id": "fe8d3c65-xmpl-c5c3-2c87-81584709a377",
"detail-type": "RDS DB Instance Event",
"source": "aws.rds",
"account": "123456789012",
"time": "2020-04-28T07:20:20Z",
"region": "us-east-2",
"resources": [
"arn:aws:rds:us-east-2:123456789012:db:rdz6xmpliljlb1"
],
"detail": {
"EventCategories": [
"backup"
], …
```

Added Cloudwatch Event format to triggers.

---

localstack/services/events/events_starter.py
tests/integration/test_events.py

Hi,
I made an error on my last PR (#2670). I was sending a JSON-formatted string to a lambda instead of the actual dictionary. This fixes that error. If this isn't fixed, you'll get errors in `services/awslambda/labmda_executors.py`, line 69, `get_from_event`.
Sorry for the error.

Fix bug where lambda was sent JSON strings

---

tests/integration/test_sqs.py

The issue was fixed in the lasted version
- Add integration test 
Issue fixed
Lambda triggered by SQS event source doesn't delete SQS message #2536

Fix Lambda triggered by SQS event source doesn't delete SQS message #2536

---

localstack/services/cloudformation/cloudformation_starter.py

* get resource name from moto's parse_resource
* handle RestApi resource when missing "Name" property
Issue fixed:
https://github.com/localstack/serverless-localstack/issues/89

Fix missing name issue of ApiGateway:RestApi when deploy by serverless-localstack

---

localstack/services/install.py

In _install.py_, LocalStack downloads and installs a number of third-party files. Until now, the common pattern in most of the `install_*` functions was the following:
1. check if the installation directory exists.
2. if not, create it.
3. download and install the required software.
If step 3 fails (for example, the download is dropped midway through) or if a user accidentally deletes one of the executables, the installation directory will exist but will not contain the required software. Step 1 will evaluate to false, and installation will never be reattempted again. This issue is then hard to debug, for example I've hit a case where the LocalStack service would start up happily but would then reject all requests with a 502 as the underlying Java service could not start because of a …

Check for file rather than directory existence

---

localstack/utils/cloudformation/template_deployer.py
tests/integration/test_cloudformation.py

* Delete role polices before deleting IAM::Role resource
Issue fixed:
#2790 CloudFormation: Delete stack containing IAM role with inline policy fails

Fix issue when deleting stack contains role with inline policy

---

localstack/services/s3/s3_starter.py
tests/integration/test_s3.py

Issue fixed:
#2724 Localstack not returning correct error code when retreiving S3 files in DEEP_ARCHIVE storage class.

Patch s3 moto method to handle retrieving DEEP_ARCHIVE object

---

localstack/services/cloudformation/cloudformation_listener.py
tests/integration/test_cloudformation.py

CloudFormation's DeleteStack wrapper would create an `aws_stack` client in
order to list the resources contained in the stack for deletion. This
client was created without specifying a `region_name` parameter which meant
that even if the stack was created in a given region the deletion would
always be attempted in us-east-1.
This change fixes that by specifying the region name sent in the request
itself.

Use the correct region when getting CloudFormation stack resources to delete.

---

localstack/services/kinesis/kinesis_listener.py
tests/integration/test_kinesis.py

Changed register_stream_consumer ConsumerCreationTimestamp output from a formatted string to a UNIX timestamp.
See https://github.com/localstack/localstack/issues/2834

Change register stream consumer timestamp output format to UNIX per AWS docs

---

localstack/services/cloudformation/cloudformation_starter.py
localstack/services/sns/sns_listener.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/test_cloudformation.py

* Handle delete action for restApi resource
* Fix missing physical resource id for restApi
* Fix issue with restApi's resource, deployment
* Add integration test: cfn handle serverless api resource
Issues fixed:
#2641 Serverless Api resource creation errors without explicit Name property in CloudFormation template
#2642 Error during CreateDeployment call when trying to create a Serverless Api in CloudFormation template

Fix cfn deploy serverless api resource

---

localstack/utils/aws/aws_stack.py

In my scenario i would like to use localstack firehose with S3 somewhere else. 
First problem is that `aws_stack.get_s3_client` doesn't make use of `S3_BACKEND` at all. Second problem: my S3 requires `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` and this change will make use of them if the env variables are set

use url set in S3_BACKEND as endpoint_url for s3 client 

---

localstack/constants.py
localstack/utils/aws/aws_stack.py

Add MAX_POOL_CONNECTIONS environment variable for customizing the number of connections (default remains at 150 as before)

Allow setting max_pool_connections via environment variable

---

README.md

I always forget to pass environment variables especially for being selective which services to start. I put this tiny example at the end of configuration section.
I'm hoping this could be useful for future.

Updated Configuration section with an environment variable example

---

localstack/services/apigateway/apigateway_listener.py
localstack/services/awslambda/lambda_api.py
tests/integration/test_api_gateway.py

Fix for #2970 
* APIGateway should send the method it is called with to the backend not the method the backend is called with

APIGateway should send the method it was called with.

---

localstack/services/awslambda/lambda_api.py
localstack/utils/aws/aws_models.py
tests/integration/test_lambda.py
tests/unit/test_lambda.py

This PR adds more API supports for `Lambda Asynchronous invocation`.
**APIs Added:**
- UpdateFunctionEventInvokeConfig
- DeleteFunctionEventInvokeConfig
**Fixed API behaviour:**
- PutFunctionEventInvokeConfig
Added features requested by issue: #2926 .

Added asynchronous invocation support

---

localstack/services/cloudformation/cloudformation_starter.py
tests/integration/serverless/package.json
tests/integration/serverless/serverless.yml

addresses https://github.com/localstack/serverless-localstack/issues/105
It seems that in the refactor of moto, they no longer return `BucketName` in the `Properties` when you call `parse_resource_and_generate_name`
It seems that we're already handling cases like this in `add_default_resource_props` so I've added another case to handle this.

Fix serverless deploy: set bucket name if missing in resource_props

---

localstack/services/awslambda/lambda_api.py

Fixed AWS Behaviour for uploading big zip files based on #2990 .
**Validation Removed:**
- Lambda handler function validation when creating lambda function.
**Validation Added:**
- File size limit is less then 69905067.
AWS message:
```
An error occurred (RequestEntityTooLargeException) when calling the CreateFunction operation: Request must be smaller than 69905067 bytes for the CreateFunction operation
```

fix lambda handler/length validation

---

localstack/services/firehose/firehose_api.py

This PR was implemented to fix issue #2544 .
Added expectation handling for `es_type` that is used as `doc_type` which is deprecated in es 7.

fix "TypeName" as optional param for es7

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

When 404 is returned and ErrorDocument is defined, the error
document object is fetched from the bucket, but if the document is
missing we get an endless loop.

Endless loop when error document is missing

---

localstack/services/awslambda/lambda_api.py
localstack/services/iam/iam_starter.py
tests/integration/test_lambda.py

This PR fixed (adds support) for add-permission in lambda. Also this will add resolve the issue reported by #3040 .
Fixed: Response for `lambda add-permission`.
Extended test case for `add-permission`.

fixed lambda add permission

---

README.md
bin/docker-entrypoint.sh

I am proposing to create a variable `INIT_SCRIPTS_PATH` to define the path of the initialization files.
This solves a problem for me where pipelines mount the volume with the files from the repository, however I must not manipulate these files, but I can reference the existing path.

create env INIT_SCRIPTS_PATH for specify path for init files in docker

---

README.md
localstack/constants.py
localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/utils/common.py
localstack/utils/testutil.py
tests/integration/test_lambda.py

Fix Java Lambda executor to use lambci mechanism (disable deprecated custom Java Lambda handling in LocalStack). Based on #3076

Fix Java Lambda executor to use lambci mechanism

---

localstack/utils/bootstrap.py
localstack/utils/cloudwatch/cloudwatch_util.py

Issue addressed: #3037
Added cloudwatch as a dependency in bootstrap.py, to start whenever lambda is enabled.

Add cloudwatch as a static dependency for Lambda API

---

localstack/services/logs/logs_listener.py
tests/integration/test_logs.py

Fix invalid account ID in CloudWatch logs listener ARNs
Addresses #2883

Fix invalid account ID in CloudWatch logs listener ARNs

---

README.md

The docker-compose.yml file in the root director is using the version 2.1 file spec. This requires Compose 1.9.0+. Updating readme.md to reflect this. docker-compose latest version is currently at 1.27.4 
See: https://docs.docker.com/compose/compose-file/compose-versioning/#version-21

Update readme.md with proper dependency version

---

README.md

Add documentation about how to setup Localstack `docker-compose.yml` file to use  the official AWS CLI v2 docker container. (see #3088)

Add docs about using AWS CLI version 2 Docker image

---

localstack/services/dynamodbstreams/dynamodbstreams_api.py
tests/integration/test_dynamodb.py

The dynamodb streams' record sequence number is mismatched from the shard's starting and end sequence number.
When we call ddbstreams.describe_stream(...) we get shards with SequenceNumber that looks like the following:
{'ShardId': 'shardId-00000001603400000000-000000000000', 'SequenceNumberRange': {**'StartingSequenceNumber': '49611974300205315735694662545343431332397447507475431426'**}}
But when we call ddbstreams.get_records(...) we get records with SequenceNumber that looks like this:
{'ApproximateCreationDateTime': datetime.datetime(2020, 10, 22, 17, 37, 41, 162566, tzinfo=tzlocal()), 'Keys': {'id': {'S': 'a1c3bd2e'}}, 'NewImage': {'attr1': {'S': 'value1'}, 'attr2': {'S': 'value2'}, 'id': {'S': 'a1c3bd2e'}}, **'SequenceNumber': '1',** 'SizeBytes': 77, 'StreamViewType': …

Fix: Dynamodb streams sequence number mismatch

---

localstack/utils/common.py

Add log output listener to shell command thread - allows clients to consume and process individual log lines from a spawned process.

Add log output listener to shell command thread

---

localstack/services/apigateway/apigateway_starter.py
tests/integration/test_api_gateway.py

This PR has been created to fix the upstream response. If the authorization type is 'CUSTOM' or 'COGNITO_USER_POOLS', then the request should be responded with 'authorizationId' parameter
Issue Ref: #1315

Patch: the api-gw response.resource_methods method

---

localstack/services/s3/s3_listener.py

Currently, when fetching s3 notifications `Id` field is generated on response so it differs from call to call, also ID that is provided when creating notification is ignored.
This fix should make use of provided `Id` when notifications are created (defaults to UUID) and return the said `Id` on `GET`.

Fix: S3 notifications `Id` field not being handled properly

---

localstack/services/awslambda/lambda_api.py
tests/integration/test_lambda.py

Added a validation before creating a policy for a function. Without it, creating a policy that already exists throws an Error in localstack and Error 500 in awslocal.
Could be the fix to the [Issue 3040]( https://github.com/localstack/localstack/issues/3040)

Check if lambda function policy exists before creating it

---

localstack/services/secretsmanager/secretsmanager_starter.py
tests/integration/test_secretsmanager.py

**Patched:**
- Moto implementation for secretsmanager `get-resource-policy`
**Added:**
- API implementation for secretsmanager `put-resource-policy`
- API implementation for secretsmanager `delete-resource-policy`
**Test:**
- Added test cases for `get-resource-policy` `put-resource-policy` `delete-resource-policy`
This PR will fix the issue #3195 .

feature: resource policy support for secretsmanager

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

This change disables compression for falsy S3 response bodies.
If an HTTP request has an `Accept-Encoding: gzip` header when an S3 response has a 204 status code, the empty body is compressed with gzip into a non-empty body. This causes some HTTP clients, [like tornado](https://github.com/tornadoweb/tornado/blob/b120df9b584dc59881b72854a4b8e73b16b25159/tornado/http1connection.py#L630-L638), to raise an exception.

S3 listener: fix nonzero content length for gzipped 204 status

---

localstack/services/apigateway/apigateway_starter.py
localstack/services/awslambda/lambda_api.py

This PR fixed the issue mentioned in #3209 .
`cacheClusterStatus` variable was missing in the response in `CreateStage` api when the `cacheCluster` is enable.
Lamda IAM policy should contain qualifier in the ARN.

fix apigateway cachingclusterstatus

---

localstack/services/ssm/ssm_listener.py

Fixing issue where SSM couldn't get parameters created from SecretsManager when the name contains slashes (#3237)

Fix SSM & SecretsManager integration with secrets named with slashes (#3237)

---

localstack/services/s3/s3_starter.py
tests/unit/test_s3.py

Now the instances of  **FakeKey** and  **FakeBucket** are being remove from the attribute instances on creation, to avoid storing the object references even after the object was deleted.
posible solution to [issue 3143](https://github.com/localstack/localstack/issues/3143)

avoid instance collection

---

Dockerfile
Makefile
localstack/services/apigateway/apigateway_starter.py
localstack/services/awslambda/lambda_api.py
localstack/services/cloudformation/cloudformation_starter.py
localstack/services/kinesis/kinesis_listener.py
localstack/services/sns/sns_listener.py
localstack/utils/cloudformation/template_deployer.py
localstack/utils/common.py
tests/integration/test_cloudformation.py
tests/integration/test_serverless.py
tests/unit/test_sns.py

Refactor CloudFormation dependency resolution mechanism - this fixes some issues with CDK templates that could not be deployed with the current logic.
This PR contains a couple of smaller changes, mostly:
* minor refactorings of the current logic
* enhanced CF deployment support for various resource types
* assigning default resource names where missing (prior to the deployment loop, to make it more stable)
The **main change** in this PR is to introduce an exception class `DependencyNotYetSatisfied` which is raised whenever a resource dependency can not (yet) be resolved (this can be an intermittent error, as the stack resources are deployed in multiple steps/iterations to resolve all dependencies). The resource deployment loop has been adapted to be able to deal with this type of …

Refactor CloudFormation dependency resolution mechanism

---

localstack/services/infra.py
localstack/services/s3/s3_starter.py
tests/unit/test_s3.py

the objective of this patch is to avoid the instance collection every time a new object is created, which can be the reason of the memory leaks mentioned in the issues #3143 and #3233 .
┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-327) by [Unito](https://www.unito.io/learn-more)

patching IntanceTrackerMeta to avoid memory leak

---

localstack/services/apigateway/apigateway_starter.py
tests/integration/test_api_gateway.py

This PR will fix response structure for Integration/IntegrationResponse
Improved Support for `APIGateway `in terraform
**Refractored:**
* `apigateway_models_Integration_init` for backward compatibility
* streamline patching pattern
**Fixed:**
* APIGateway `put_integration` response
* APIGateway `put_integration_response` response
**Test:**
* Extended test case for improved response structure
This PR will address issue mentioned in #1984 .
┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-322) by [Unito](https://www.unito.io/learn-more)

fix response structure for Integration and IntegrationResponse

---

localstack/services/edge.py

This should fix #3255.
I added a fallback for the edge-service, so that the service `EventBridge` will be mapped to `events`, because `EventBridge` will be used by the AWS Go SDK.
┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-333) by [Unito](https://www.unito.io/learn-more)

#3255: Fix EventBridge edge support for Go SDK

---

localstack/services/ssm/ssm_listener.py
tests/integration/test_ssm.py

Patched SSM so **GetRequests** requests can support having SecretsManager secres in it. Also, slightly modified the method so when an inexistent secret is requested a 400 is managed instead of having the 500 thrown.
**NOTE:** I'm not much acquainted with Python so sorry if I'm not doing some things the most recommended Python way
The patch works as expected when making requests through the aws-cli or HTTP request (with postman) like so:
1) Create the param and secret
```
aws --endpoint-url http://localstack:4566 secretsmanager create-secret --name test_secret --secret-string 'test_secret' && \
aws --endpoint-url http://localstack:4566 ssm put-parameter --name test_parameter --value 'test_parameter'
```
2) Get existent and non existent params and secrets
```
aws --endpoint-url …
```

SSM & SecretsManager - GetParameters integration (with caveat)

---

bin/supervisord.conf

WORKDIR is not enough, it can be overriden by k8s or docker or anything else really.
┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-336) by [Unito](https://www.unito.io/learn-more)

Tell supervisord where to run the command

---

localstack/services/awslambda/lambda_api.py
tests/integration/terraform/provider.tf
tests/integration/test_lambda.py
tests/unit/test_lambda.py

**Added:**
* GetFunctionConcurrency: Added Support for `GetFunctionConcurrency` api - [Reference](https://docs.aws.amazon.com/lambda/latest/dg/API_GetFunctionConcurrency.html)
* DeleteFunctionConcurrency: Added Support for `DeleteFunctionConcurrency` api - [Reference](https://docs.aws.amazon.com/lambda/latest/dg/API_DeleteFunctionConcurrency.html)
Test:
* Added Unit test cases for `GetFunctionConcurrency` and `DeleteFunctionConcurrency`
* Added Ingtegration test cases for `GetFunctionConcurrency` and `DeleteFunctionConcurrency`
This PR will also fix issue #3260.
┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-346) by [Unito](https://www.unito.io/learn-more)

Added support for lambda concurrency api

---

Dockerfile
requirements.txt

This is a fix for Centos 8 that solves: Service "ANY_SERVICE_HERE" not yet available, retrying...
#808
┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-353) by [Unito](https://www.unito.io/learn-more)

Centos 8 fix (Service "ANY_SERVICE_HERE" not yet available, retrying...)

---

localstack/services/awslambda/lambda_api.py
localstack/utils/aws/aws_models.py
localstack/utils/aws/aws_stack.py
tests/integration/terraform/provider.tf

This PR will implement lambda-code-signing-config.
**Added (API Implemented):**
- `create-code-signing-config`
- `delete-code-signing-config`
- `get-code-signing-config`
- `update-code-signing-config`
- `delete-function-code-signing-config`
- `get-function-code-signing-config`
- `put-function-code-signing-config`
**Note: Test cases not yet added because of the `older version of boto`.** 
Also it will fix issue reported in #3270.

feature: lambda code-singing-config support added

---

localstack/services/events/events_starter.py
tests/integration/test_events.py

Added content base filters in events. Also there some required changes in the pattern rule's format (**Only string or integer in pattern rule is not allowed. Instead, add pattern rule's values in a list structure**).
The test case has been added.
#2672
┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-335) by [Unito](https://www.unito.io/learn-more)

Add content base filters in events

---

localstack/services/apigateway/apigateway_starter.py
localstack/utils/common.py

**API Added:**
- update-rest-api: 
- [AWS CLI Documentation Ref.](https://docs.aws.amazon.com/cli/latest/reference/apigateway/update-rest-api.html)
- [AWS API Documentation Ref.](https://docs.aws.amazon.com/apigateway/api-reference/link-relation/restapi-update/)
**Issue Addressed**
- Issue #3261

feature: support for apigateway update-rest-api

---

localstack/services/cloudformation/cloudformation_listener.py
localstack/services/cloudformation/cloudformation_starter.py
localstack/services/cloudformation/service_models.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/templates/template23.yaml
tests/integration/test_cloudformation.py

* Handle physical resource id from Resource
* Handle FN::ImportValue
* Handle short form FN::Sub
* Add integration test for template with short form FN::Sub
Issue fixed:
#3251 CloudFormation YAML short form !Sub / Fn::Sub in dependent resource causes dependency resolution failure
#3184 CF template FN::ImportValue fails on parameter validation.

Fix issues when deploying CF template with FN::ImportValue short-form FN::Sub

---

localstack/services/cloudformation/cloudformation_starter.py
localstack/stepfunctions/models.py
tests/integration/templates/template23.yaml
tests/integration/templates/template24.yaml
tests/integration/test_cloudformation.py

* Handle FN::Sub in resource properties (stepfunctions' definition, lambda function name)
* Add integration test for template
Issue fixed:
#3293 CloudFormation template substitution using !sub not working in latest
#3294 CloudFormation - the use of intrinsic functions in AWS::Lambda::Function FunctionName...

Fix issue when deploying CF template with FN::Sub

---

.github/workflows/chart-release.yaml
README.md
chart/localstack/.helmignore
chart/localstack/Chart.yaml
chart/localstack/templates/NOTES.txt
chart/localstack/templates/_helpers.tpl
chart/localstack/templates/deployment.yaml
chart/localstack/templates/ingress.yaml
chart/localstack/templates/pvc.yaml
chart/localstack/templates/service.yaml
chart/localstack/templates/tests/test-connection.yaml
chart/localstack/values-production.yaml
chart/localstack/values.yaml

Using GitHub Actions to release the official helm chart
This PR is a starting point to introduce an official helm chart for locakstack,
I copied the helm chart from https://github.com/sidhuko/charts/pull/1 without any modification (hope it is fine with @sidhuko)
There are couple of tasks that need to be done before this can be merged:
- A `gh-pages` branch need to be created
- `GitHub Pages` need to be enabled in the setting
TODO (can be done in this PR or next PRs):
- A GitHub workflow to test the helm chart for PRs
Fixes #882

Release helm chart

---

localstack/services/kinesis/kinesis_listener.py

#3326 Records getting added in kinesis successfully but lambda was breaking due to encryptionType attribute

fix: kinesis put record(s) breaking .NET lambda

---

localstack/services/awslambda/lambda_api.py
tests/unit/test_lambda.py

With this PR localstack adds a new version of a lambda function when is being updated and the Publish flag is set to true. 
Also verifies if the SHA256 is different so it's not just adding more values with each update.
This PR should fix issue #3281

lambda function version corrected

---

localstack/services/edge.py
localstack/services/s3/s3_listener.py

Add gzip encoding of response payloads to edge service - based on the `Accept-Encoding` HTTP header.

Add gzip encoding of response payloads to edge service

---

localstack/services/s3/s3_listener.py
tests/integration/lambdas/lambda_triggered_by_sqs_download_s3_file.py
tests/integration/test_s3.py
tests/integration/test_sqs.py

Addresses the issue: https://github.com/localstack/localstack/issues/3160

Handle host name for in-memory routing

---

localstack/services/awslambda/lambda_executors.py

**Fixed:**
- Lambda concurrency issue with `LAMBDA_EXECUTOR=docker-reuse`
**Issue:**
- #3338 
- #1777

Use locking to run Lambdas via docker-reuse in sequence

---

localstack/config.py

Hardcode local hostname instead of using `$HOSTNAME` from the environment. This should fix several issues we've seen around connecting to local/loopback APIs (e.g., because local hostname cannot be resolved).

Hardcode local hostname instead of using $HOSTNAME from the environment

---

localstack/services/cloudformation/cloudformation_starter.py
tests/integration/templates/template26.yaml
tests/integration/test_cloudformation.py

* Patch cfn backend missing method (This patched has provided in moto-ext==1.3.15.45)
* Update integration test
Issue fixed:
#3375 CloudFormation - All deployed stacks have StackStatus: CREATE_FAILED

Fix issue when deploying cfn template related to cfn backend set_exports method

---

localstack/services/s3/s3_listener.py

#3347  skip checking content md5 upon create-multipart-request as it return uploadID which is used at the time of actual object upload.

md5 check on multipart upload

---

tests/integration/test_stepfunctions.py

Fix assertions for machine creation/deletion in StepFunction tests. This could potentially (hopefully) help fix some flaky tests that we've been experiencing recently.

Fix assertions for machine creation/deletion in StepFunction tests

---

Makefile
localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
tests/integration/test_lambda.py

Fix returning `LogResult` from synchronous Lambda invocations - addresses #1630

Fix returning LogResult from synchronous Lambda invocations

---

localstack/services/sns/sns_listener.py
tests/unit/test_sns.py

As discussed in #2165, the AWS .NET SDK has problems with null values in the response JSON.
So I edited the code to only add this fields if they are not null.

fixing .NET SDK error - SNS message format doesn't allow null values

---

localstack/services/cloudwatch/cloudwatch_listener.py
localstack/services/edge.py
tests/integration/test_cloudwatch.py

This PR adds the functionality to read GZIP encoded data in a PutMetricsData request for the CloudWatch service. 
It should fix the issue #3385

Gzip decoding

---

localstack/services/sns/sns_listener.py

SNS listener now passes along the Message Group ID if it exists to the SQS client.
This fixes issue #3414

message group id for  sqs fifo queues

---

.gitignore
localstack/services/cloudformation/cloudformation_api.py
tests/integration/templates/template27.yaml
tests/integration/test_cloudformation.py

This PR will fix the issue https://github.com/localstack/localstack/issues/3442 just opened. 
When we call the listExports method for cloudformation api the result is malformed. This cause issued in aws js sdk as it returns an empty array. The python sdk manages to parse it even if it is malformed, so you can't see the bug using the aws command line interface.

Fixing Cloudformation ListExport Result Malformation

---

localstack/utils/cloudformation/template_deployer.py
tests/integration/templates/template28.yaml
tests/integration/test_cloudformation.py

* Add handle for function GetAZs
Issues fixed:
#3331 CloudFormation - Pseudo parameter AWS::Region doesn't work in function Fn::GetAZs
#3333 CloudFormation - Sub Intrinsic Function doesn't support variable map

Fix issue when deploying cfn template contains Fn:Sub with variable map and Fn:GetAZs

---

localstack/utils/aws/lambda_destinations.py
tests/integration/test_lambda.py

- set the response payload for both success and failed invoications
- handle json and string responses from lambda
- use the correct lambda handler to raise error
- addresses https://github.com/localstack/localstack/issues/3373

Fix incorrect test case for destinations

---

localstack/services/ssm/ssm_listener.py
tests/integration/test_ssm.py

This PR stringify the secretsmanager response to mirror SSM behaviour when getting a parameter that references a secret.
[3496](https://github.com/localstack/localstack/issues/3496)

Fix: SSM wrong output when referencing secretsmanager

---

localstack/plugins.py
localstack/services/infra.py
localstack/services/ses/ses_listener.py
localstack/services/ses/ses_starter.py

With this patch, the ses-listener patches the xml error responses. Now the java -sdk can show the correct error messages.
this fixes the issue #3466

ses listener and xmlns for error responses

---

localstack/services/kinesis/kinesis_listener.py

Now the content of the records is correct when working decoding in CBOR mode.
This should fix (finally) issue #3208

blob object should be bytearray

---

localstack/services/cloudwatch/cloudwatch_listener.py
localstack/services/edge.py
tests/integration/test_cloudwatch.py

Add backdoor API to receive raw CloudWatch metrics - addresses #3508
Example:
```
$ curl http://localhost:4566/cloudwatch/metrics/raw
{'metrics': [{'ns': 'some/thing', 'n': 'someMetric', 'v': 23.0, 't': '2021-01-30T18:35:30.132Z', 'd': []}, {'ns': 'some/thing', 'n': 'someMetric', 'v': 18.0, 't': '2021-01-30T18:35:30.160Z', 'd': []}, {'ns': 'ug/thing', 'n': 'ug', 'v': 23.0, 't': '2021-01-30T18:35:30.186Z', 'd': []}]}
```

Add backdoor API to receive raw CloudWatch metrics

---

README.md
localstack/config.py
localstack/constants.py
localstack/utils/bootstrap.py

1) LS_LOG env. variable which allows log levels to be specified ('debug', 'info', 'warn', 'error', 'warning')
2) Currently overrides the DEBUG env. variable if LS_LOG is set

#3038 Option to log at different level (e.g. WARN or ERROR rather than INFO)

---

localstack/services/cloudwatch/cloudwatch_listener.py
localstack/services/cloudwatch/cloudwatch_starter.py

**fixed**
- added attribute `TreatMissingData` in Cloudwatch `PutMetricAlarm`
**Reference**
- [PutMetricAlarm](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricAlarm.html)

fixed missing attribute in cloudwatch

---

README.md

We have been developing [LocalStack .Net Client Library](https://github.com/localstack-dotnet/localstack-dotnet-client) for two years and updating it regularly. We thought it might be useful to other AWS and .NET users like us.

Add .NET Client Library info to README

---

localstack/services/firehose/firehose_api.py

@whummer I don't see this as fully completed PR and it's a starting point. 
There is a general issue with elasticsearch after it has got a dynamic port.  `connect_elasticsearch` used without any parameters and as result `endpoint` is defined as`http://localhost:0` and firehose is not able to put records. Firehose tries to connect on 9200 port while Elasticsearch is running on another port.
There is another issue in es_starter.py with in `check_elasticsearch`. This method also calls  `connect_elasticsearch`  with no inputs and fails with this error 
```
localstack_1    |   File "/opt/code/localstack/localstack/services/plugins.py", line 99, in check_infra
localstack_1    |     additional(expect_shutdown=expect_shutdown)
localstack_1    |   File …
```

Added missed endpoint and domain for es connect call from firehose

---

localstack/services/apigateway/apigateway_listener.py
tests/integration/test_api_gateway.py

The code to `validate_api_key` only compared the key in the request headers to one api key configured for the API Gateway. All usage plans were iterated over for the stage, however only the last found one was recorded. Similarly, all keys for the usage plan were iterated over, but only the last one was compared to the request.
This PR changes `validate_api_key` to create a list of usage plans, then iterate over each plan until an api key is found that matches the key in the request, or return False if no match is found.

Fix: API GW only validates API Keys against one previously configured key

---

localstack/services/cloudformation/cloudformation_api.py
localstack/services/cloudformation/deployment_utils.py
localstack/services/cloudformation/service_models.py
localstack/utils/cloudformation/template_deployer.py

**Fixed**
- Cloudformation stack status when using `ExecuteChangeSet` to 'CREATE_COMPLETE'. Which was causing `cloudformation deploy` command to fail.
**Refractored**
- Refractored `SSM::Parameters` from `template_deployer` to `service_models`
**Issue**
- [760](https://github.com/localstack/localstack/issues/760)

fix: cloudformation stack status when using execute-change

---

localstack/services/events/events_starter.py
tests/integration/test_events.py

Fixed case of `PutEvents` with no `Detail`. Fix  #3682

Fix:Events put events on No detail

---

localstack/services/kinesis/kinesis_listener.py
localstack/utils/aws/aws_responses.py

Now Localstack returns if a Stream Consumer really exists and also a new header was added to the binary messages.
With this changes, KCL can correctly register a Stream Consumer and read the binary messages without crashing.
Progress to fixing #3487

KinesisConsumerDescription and Header added to binary messages

---

localstack/services/edge.py
localstack/utils/common.py
tests/integration/test_sqs.py
tests/unit/test_edge.py

Fixes #3716 
Authorization GET Parameters are read and turned into an `Authorization` header.

Compute Auth Headers from Get Parameters (fixes #3716)

---

Makefile
README.md
localstack/config.py
localstack/services/awslambda/lambda_api.py
localstack/services/cloudformation/cloudformation_api.py
localstack/services/cloudformation/deployment_utils.py
localstack/services/cloudformation/service_models.py
localstack/utils/aws/aws_stack.py
localstack/utils/cli.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/test_cloudformation.py

Run CF deployments asynchronously in the background. This is required for large stacks with long-running deployment loops, to prevent network timeouts in the client connection.

Run CF deployments asynchronously in the background

---

localstack/services/edge.py
tests/integration/test_sqs.py
tests/unit/test_edge.py

Sorry for the double-PR in a day @whummer, and thanks for the help on the last one.
This PR fixes an issue where the Authorization parameters couldn't be sent as GET parameters. I meant to include in in the last PR, but well the test suite takes a bit to run and I stepped away :)

Fix 404 with presigned GET requests with querystring auth parameters and add test

---

tests/integration/templates/template27.yaml
tests/integration/test_cloudformation.py

Issue already fixed:
#2115 Region ignored when using ${AWS::Region} in template

Refactor cfn integration test: remove duplicated test

---

localstack/services/s3/s3_listener.py
tests/integration/files/s3.requests.txt

**fixed**
- Response for get-bucket-cors when the configuration is non existent
**issue**
- [3755](https://github.com/localstack/localstack/issues/3755)

fixed get-bucket-cors for no config exsist

---

localstack/services/s3/s3_listener.py

Fixed:
- Location Constraint returns `null` for selected region
- Valid Values: `af-south-1 | ap-east-1 | ap-northeast-1 | ap-northeast-2 | ap-northeast-3 | ap-south-1 | ap-southeast-1 | ap-southeast-2 | ca-central-1 | cn-north-1 | cn-northwest-1 | EU | eu-central-1 | eu-north-1 | eu-south-1 | eu-west-1 | eu-west-2 | eu-west-3 | me-south-1 | sa-east-1 | us-east-2 | us-gov-east-1 | us-gov-west-1 | us-west-1 | us-west-2`

fixed location constraint value for specific region

---

localstack/services/s3/s3_utils.py
tests/integration/test_s3.py

- presign authentication failing when key contains special char in the name
- presign authentication failing while multipart uploading  
- test cases for multipart upload and special char as a key name
#3713 
#3759

fix: key name with special char and multipart upload in presign url auth

---

localstack/services/s3/s3_listener.py

Reverts localstack/localstack#3750 - fixes a regression with Node.js AWS SDK that was introduced by this change.

Revert "fixed location constraint value for specific region"

---

localstack/services/s3/s3_listener.py

I found an error while using the lib, I got something like this from localstack logs:
```
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 671, in run
localstack_1  |     result = self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_1  |     return fn(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 607, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
localstack_1  | …
```

Fix policy expiration format for S3 signing

---

localstack/utils/aws/aws_stack.py

Changed addressing style to auto for the common default aws client of the s3 service.

addreesing style auto in default aws clients

---

localstack/services/apigateway/apigateway_listener.py
localstack/services/kinesis/kinesis_listener.py

Unless there's a good reason not to, it seems to work as intended

Support PutRecord kinesis endpoint in apigateway

---

localstack/services/s3/s3_listener.py

**Issue**
- #3732
**Fixed**
- allowed `x-id` query parameters to invoke the notification
- reused `bucket_name_in_host`

Fix s3 notification

---

localstack/services/s3/s3_listener.py

When using `aws-sdk-cpp::TransferManager`, I noiced there is a different in the behavior of `localstack` and production.
- `localstack`: When we do a `HeadObjectRequest` with `range` headers, `localstack` respects this header and return `416` if there is a mismatch in `range` and object's size.
- On the other hands, production doesn't return `416` even if there is mismatch. As long as the questioning object is accessible, it will return 200 along with other data.
For more informations, you could take a look at [`TransferManager::InitializePartsForDownload`](https://github.com/aws/aws-sdk-cpp/blob/3fe07dc617103886c3051bd7cd529456f2011dfe/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp#L718-L793), I've tested it with many different offsets and sizes, and the production server …

`HEAD` object should not return 416

---

localstack/services/s3/s3_listener.py

Removed **get_forward_url** as we are supporting case sensitive bucket/key names
Fix:
- localstack was lowering the case of URL/Path before sending to moto
**Isssues**
- #3726 
- #3756

removed the url modification when sending the request to moto

---

localstack/services/s3/s3_utils.py

**Fixed**
- Updated the s3 virtual host name regex to support `HOSTNAME_EXTERNAL` environment variable.
**Rendered Regex**
- `^(http(s)?://)?([^\.]+)\.s3((-website)|(-external-1))?[\.-](dualstack\.)?((localhost\.localstack\.cloud)|(localhost)|(([a-z]{2}-[a-z]+-[0-9]{1,}\.)?amazonaws\.com(.cn)?))(:[\d]{0,6})?$`
**Note**
- To use s3 with host based addressing the request must be sent with the host header with `s3.xxxx:xxx`
`(http(s))://(bucketname).<s3>.<hostname>(:port)`
- ( ) -> Optional
- <> -> Required

updated regex to support hostname_external

---

localstack/services/kinesis/kinesis_listener.py
tests/integration/test_kinesis.py

Fixes: #3820 
Changes:
* Update `StreamArn` to `StreamARN` to match records stored in `STREAM_CONSUMERS`.
* Fix `ConsumerArn` to `ConsumerARN` to get the ARN in the response.
* Test coverage for `DescribeStreamConsumer` calls.

Fix Kinesis DescribeStreamConsumer to return registered consumer

---

Makefile
bin/Dockerfile.base
localstack/constants.py
localstack/package.json
localstack/services/sns/sns_listener.py
tests/integration/test_sns.py

Closes #3669 
- adds propagation of xray tracing header from sns to sqs message
- adds relevant test case
- bumps elasticmq version to enable XRay propagation support in SQS itself (moto does not seem to support XRay propagation at all)

adds sns xray propagation to sqs

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

Fixes #3608 Regression: listObjects does not work with phpsdk
The AWS PHP SDK when used with Guzzle 6 is unable to parse the response
XML when it encounters a 'content-encoding: identity' HTTP header.
Replaces #3831

#3608 Regression: listObjects does not work with phpsdk

---

localstack/services/kinesis/kinesis_listener.py

This PR adds more attributes to the Subscribe To Shard Response, according to [This Doc](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_SubscribeToShard.html#API_SubscribeToShard_ResponseSyntax)
Addresses #3822

more attributes in subscribeToShard response

---

localstack/services/apigateway/apigateway_listener.py

Fixes #3908.
I've had some problems installing sasl on arch, so I haven't been able to reproduce this fix locally. I'd appreciate some help to validate this fix.

Fix integrations with no uri (mocks)

---

localstack/services/s3/s3_starter.py
localstack/utils/generic/dict_utils.py
tests/unit/utils/generic/test_dict_utils.py

As reported by @arciisine in https://github.com/localstack/localstack/issues/3931 AWS has introduced `x-id` query parameter in their requests (just to say, I couldn't find any documentation). This makes `DeleteObjects` request look like the following:
```
POST /?delete=&x-id=DeleteObjects
...
```
This request is bypassed by moto (since DeleteObjects is unsupported) and our `s3_response_is_delete_keys` since underlying `is_delete_keys` is making a full string check for `/?delete`, whereas the path now includes `x-id` query parameter.

fix(s3): Handle x-id for s3:DeleteObjects

---

localstack/services/apigateway/apigateway_listener.py
localstack/services/awslambda/lambda_api.py
tests/integration/lambdas/lambda_integration.py
tests/integration/test_lambda.py

Fix paths for apigw events
Here are samples of real events (tested scenarios):
/{proxy+}
```
request: ANY /api/v2/hello/world
event.path: /api/v2/hello/world
event.resource: /{proxy+}
event.requestContext.path: /<stage>/api/v2/hello/world
event.requestContext.resourcePath: /{proxy+}
```
/api/v2/{proxy+}
```
request: ANY /api/v2/hello/world
event.path: /api/v2/hello/world
event.resource: /api/v2/{proxy+}
event.requestContext.path: /<stage>/api/v2/hello/world
event.requestContext.resourcePath:  /api/v2/{proxy+}
```
/api/v2/hello/world (no proxy)
```
request: ANY /api/v2/hello/world
event.path: /api/v2/hello/world
event.resource: /api/v2/hello/world
event.requestContext.path: /<stage>/api/v2/hello/world
event.requestContext.resourcePath: /api/v2/hello/world
```
Related issue: …

fix(lambda): Fix apigw event paths

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

LocalStack was returning `cache-control: no-cache` if the header
wasn't set by the client, but this is a bug because s3 doesn't do
that. It simply omits it.

Remove default cache-control value

---

localstack/services/apigateway/apigateway_listener.py
localstack/services/apigateway/helpers.py

Missing domain name value when apigateway sends a request to lambda function.
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

Add domain name to the request context in apigateway proxy request to lambda function

---

localstack/services/awslambda/lambda_api.py
tests/integration/test_lambda.py

Addresses #3954 where it is not possible to fetch Lambda function's via ARN or partial ARN. Also minor test extension.

Fix: Fetch lambda using ARN or partial ARN

---

localstack/services/apigateway/helpers.py
tests/integration/test_api_gateway.py

Addresses #3964 where PATCH method is not included in `Access-Control-Allow-Methods` header

Fix: Fixing PATCH method missing on API GW CORS configuration

---

localstack/services/dynamodb/dynamodb_listener.py
tests/integration/test_dynamodb.py

Fix:Dynamodb-Empty response on no unprocessed items
https://github.com/localstack/localstack/issues/3968

Fix:Dynamodb-Empty response on no unprocessed items

---

localstack/services/kinesis/kinesis_listener.py

There are some situations where the decoding of a JSON kinesis get-records response returns the data in a bytearray object but stills need to be send as a base64 encoded string.
This PR makes sure that the kinesis get-records tests from localstack-java-utils pass without problem in both JSON and CBOR encoding.
I tested it with:
- cloud.localstack.KinesisConsumerTest
- cloud.localstack.awssdkv2.KinesisV2ConsumerTest
- cloud.localstack.awssdkv2.KinesisSchedulerTest

Kinesis data encoding accordingly

---

localstack/utils/common.py

Use current_thread instead of currentThread method that was deprecated in Python 3.10.

---

localstack/services/s3/s3_starter.py
tests/integration/test_s3.py

**Fixed**
- Copied object from multipart upload should have different tag
**Issues**
- [3729](https://github.com/localstack/localstack/issues/3729)

fixed etags for copy object from multipart

---

localstack/services/s3/s3_utils.py
tests/integration/test_s3.py

Added:
- Remove url parsing for Quart update
- Appending query params to request object in presign url
- Enabled the test case

fixed presigned url for nodejs

---

localstack/utils/aws/aws_stack.py

This fixes https://github.com/localstack/localstack/issues/4010

Set the INTERNAL_AWS_ACCESS_KEY_ID in the header when replaying a non HMAC request.

---

README.md
doc/external_services_integration/elasticsearch/HOWTO.md
doc/external_services_integration/elasticsearch/docker-compose.yml
doc/external_services_integration/kafka_self_managed_cluster/HOWTO.md
doc/external_services_integration/kafka_self_managed_cluster/docker-compose.yml

As some of our customers have been asking (#3534, #4023, #4041) it would be nice to add some documentation on how to integrate some external services to localstack, These guides aim to achieve this.

Feat: Adding docs for kafka and elasticsearch external services integration

---

localstack/services/sns/sns_listener.py

When an SQS message is using an HTTP endpoint, return an UnsubscribeURL on every message.

add UnsubscribeURL to HTTP SQS endpoints

---

localstack/services/edge.py

When using SES service from an AWS Client, the `api` is not identified by the `ProxyListenerEdge`, because in the Authorization headers it's marked as `email`.
```
localstack_main     | 2021-05-20T06:33:34:DEBUG:localstack.services.edge: IN(email): "POST /" - headers: {'Remote-Addr': '172.20.0.1', 'Accept-Encoding': 'gzip', 'Content-Length': '114147', 'Host': 'localhost', 'X-Amz-Date': '20210520T063334Z', 'X-Amz-Content-Sha256': 'a9c08cd9d528688a2d0557ed0337db1c8ed719b5019c1920bb928fd7f286aa36', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'Authorization': 'AWS4-HMAC-SHA256 Credential=AKIAJQZL3AQH4K743T7A/20210520/eu-central-1/email/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, …
```

add ses support on `email` acronym

---

localstack/services/s3/s3_utils.py

**Fixed**
- Considering edge port instead of hardcoded port 4566 in presign url calculation

minor fix for edge port in url presign calculation

---

Dockerfile
README.md
localstack/config.py
localstack/constants.py
localstack/services/infra.py
localstack/services/install.py
localstack/utils/bootstrap.py
requirements.txt

This PR adds the debugpy library to Localstack.
It provides more insight while debugging a running Localstack container.
To start the debugpy server the env variable DEVELOP must be true.
Also there are other env vars to setup debugpy explained in the README file.

debugpy integration

---

Dockerfile
Makefile
localstack/services/awslambda/lambda_api.py
localstack/services/cloudformation/service_models.py
localstack/services/ses/ses_starter.py
tests/integration/test_ses.py

When using loclstack for development an even for easier integration/local testing
of interaction with AWS services, a feature is missing to check if an e-mail
was sent correctly.
Issue #2514 was closed with a patch that dumped the e-mail contents to the
log output. However, in most cases, this is not reliably useable for testing,
as it would require to parse the log-stream of localstack.
This commit now adds a feature where a sent e-mail is persisted to the local
file system. It re-uses the specified data directory (DATA_DIR) and falls back
to the temp directory to save e-mails into an `ses` subdirectory. Each
successfully sent message is saved in a JSON file named after the message ID.
The contents are the Source, Subject, Body, Destinations (To, CCs, BCCs) as
well as the region. …

Save e-mail contents in easy, machine-readable format

---

Dockerfile
requirements.txt

Fixes #4108 where devs can't use the internal `awslocal` command line as the `localstack_client` library is missing, a temporary workaround for this is to just install it beforehand as specified [here](https://github.com/localstack/localstack/issues/4108#issuecomment-855826709).
One guess is that the `localstack-client` library got old in our `requirements.txt` (should be `1.20`), that is why updating it, as you can see it is not even inside the app container:
```
$ docker exec -ti localstack_main bash
bash-5.0# pip freeze
appdirs==1.4.4
awscli-local==0.14
certifi==2021.5.30
chardet==4.0.0
colorama==0.4.3
distlib==0.3.2
docutils==0.15.2
filelock==3.0.12
importlib-metadata==4.5.0
jmespath==0.10.0
pyasn1==0.4.8
python-dateutil==2.8.1
PyYAML==5.4.1
requests==2.25.1
rsa==4.7.2
six==1.16.0 …
```

Fix: Updating localstack-client libraries to latest

---

localstack/services/s3/s3_utils.py

Due to changes in https://github.com/localstack/localstack/commit/3fe01cf6699a4fb71153b582715b4ec21560e4e1 `S3_SKIP_SIGNATURE_VALIDATION` flag is not working anymore, here is the proposed fix

Fix S3 S3_SKIP_SIGNATURE_VALIDATION

---

localstack/services/awslambda/lambda_api.py

Fixes #4079 where datetime format on `aws lambda put-function-event-invoke-config`, previous it was:
`2021-05-28T16:02:30.018Z`
Now:
`2021-06-07T02:21:46.871370+00:00`
As it is a very specific fix, I am just adding it to lambda, but if you think it is worth adding it to utils/common let me know.
```
$ awslocal lambda put-function-event-invoke-config --function-name SampleFunction --maximum-event-age-in-seconds 3600 --maximum-retry-attempts 0
{
"LastModified": "2021-06-07T02:21:46.871370+00:00",
"FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:SampleFunction",
"MaximumRetryAttempts": 0,
"MaximumEventAgeInSeconds": 3600,
"DestinationConfig": {
"OnSuccess": {
"Destination": "None"
},
"OnFailure": {
"Destination": "None"
}
}
}
```

Fix: Fixing datetime format for put-function-event-invoke-config call

---

localstack/services/awslambda/lambda_api.py
tests/unit/test_lambda.py

The lambda configuration update function did behave differently from other endpoints, and differently from AWS.
This breaks chalice-local (related to #4084).
Pull request adds test and aligns the endpoint with AWS and other lambda localstack endpoints.

Update Lambda Configuration Update 

---

localstack/services/awslambda/lambda_api.py

With this PR the lambda enpoint ignores the trailing slash in the corresponding routes, so the requests with both `http://localstack:4566/2015-03-31/event-source-mappings/` or `http://localstack:4566/2015-03-31/event-source-mappings` are accepted.
Addresses #4124

Ignore trailing slash in event-source-map route

---

localstack/config.py
localstack/services/infra.py
localstack/services/plugins.py
localstack/services/s3/s3_starter.py
localstack/utils/common.py

This PR refactors the shutdown procedure and allows a shutdown without a call to `exit`
The major changes are:
* a dedicated `wait_for_infra_shutdown` method that was extracted from `check_infra` and now waits in parallel for services to shut down
* a flag `FORCE_SHUTDOWN` that is true per default, and circumvents `wait_for_infra_shutdown` but rather calls `sys.exit` immediately in the TERM/INT signal handler (as previously)
* replaced the `sleep_forever` call in `start_infra` with a proper threading flag that now returns correctly after `stop_infra` has been called
* minor related refactoring and unused code removal

Refactor shutdown procedure

---

README.md
localstack/config.py
localstack/services/kinesis/kinesis_listener.py
localstack/services/kinesis/kinesis_starter.py
tests/integration/test_cloudformation.py
tests/integration/test_dynamodb.py
tests/integration/test_kinesis.py
tests/unit/test_kinesis.py

Add initial integration of kinesis-mock - addresses #4137.
This is only a first PoC - we still need to make a deeper evaluation of the tradeoffs regarding missing/supported features (e.g., persistence support), parity with AWS (e.g., API coverage, multi-region support, etc), and performance (e.g., JVM vs Node.js process; disk space of the required binaries in the Docker image), to select the best default implementation option for Kinesis in the future.
Creating to transfer ownership of https://github.com/localstack/localstack/pull/4139

Add initial draft integration of kinesis-mock

---

localstack/services/dynamodbstreams/dynamodbstreams_api.py
localstack/services/s3/s3_listener.py
localstack/services/s3/s3_utils.py
localstack/utils/common.py
requirements.txt
tests/integration/test_s3.py
tests/unit/test_common.py
tests/unit/test_misc.py
tests/unit/test_s3.py

This PR fixes an issue in common.mktime where the unixtime would be calculated from GMT rather than the timezone of the datetime object being passed. i also simplified the calculation of millseconds unixtime, based on [this stackoverflow post](https://stackoverflow.com/a/8160307/804840)
this was apparently the root cause for issues surrounding expiry calculations, for example `is_url_already_expired` in `s3_listener.py`
/cc @macnev2013

fix timezone issues in timestamp calculation and datetime comparisons

---

localstack/services/kinesis/kinesis_starter.py

This PR fixes a build issue that was caused by the latest release of kinesis-mock: https://github.com/etspaceman/kinesis-mock/releases/tag/0.1.0
i pinned the version to a specific tag that we know had worked before.

update kinesis_starter.py to pin kinesis mock version to 0.0.16

---

localstack/services/install.py
localstack/services/kinesis/kinesis_starter.py

This PR moves the install procedure of kinesis-mock from `kinesis_starter.py` into `installs.py` and makes it a bit more robust.

Refactor kinesis-mock install procedure

---

localstack/services/generic_proxy.py
localstack/services/s3/s3_listener.py
tests/integration/test_notifications.py
tests/integration/test_s3.py

This PR fixes the issue described in https://github.com/localstack/localstack-terraform-test/issues/7
Overview:
* refactored parts of `s3_listener.py` related to the put/get notification handling
* changed the put-bucket-notification behavior to make the filter rule names title case (like AWS does)
* added a `_validate_filter_rules` method that throws an exception when it finds filter rules names that aren't allowed (only `suffix` and `prefix` are allowed
* added exception handling in `generic_proxy.py` that renders an `HTTPException` into a `requests.Response` object (this depends on the latest moto-ext changes)

Fix s3 bucket notification FilterRule name validation

---

localstack/utils/analytics/profiler.py

Start and endtime is already in milliseconds, no need to multiply by 1000 here. 
We basically output nanoseconds currently.

Fix profiler log_duration unit

---

README.md
localstack/config.py
localstack/services/kinesis/kinesis_starter.py

Adds a KINESIS_INITIALIZE_STREAMS environment variable, which allows kinesis-mock to be initialized with streams that are already created. This is a common pattern for a lot of users, so it makes sense to add here.

Add KINESIS_INITIALIZE_STREAMS configuration

---

localstack/services/install.py

An [issue](https://github.com/etspaceman/kinesis-mock/issues/128) was raised in Kinesis Mock in which M1 Macbooks were getting a segfault. This is due to the binary file for MacOS being compiled for AMD64.
This PR will detect ARM machines and ensure that they fallback to the JAR file. 
Unfortunately Kinesis Mock will not be able to build M1 compliant binary executables until GitHub Actions supports a virtual environment for this, as GraalVM requires this for linking the libraries properly:
https://github.com/actions/virtual-environments/issues/2187

Detect ARM systems for kinesis-mock installation

---

.circleci/config.yml
Makefile
localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/services/awslambda/lambda_utils.py
tests/integration/test_integration.py
tests/integration/test_lambda.py
tests/unit/test_common.py

this PR will create a more streamlined circleci workflow as per #4169. just opened it so i can start running builds 
things left to do:
- (postponed) aggregate coverage data
- (postponed)  use pip cache with pyenv as per circleci documentation

Improve CircleCI workflow

---

localstack/services/apigateway/apigateway_listener.py
tests/integration/lambdas/lambda_integration.py
tests/integration/test_api_gateway.py

Resolves issue #4126
- added tests (and did some refactoring)
- note: **I seem to have added the first PEP 484 type annotations in Localstack;** is there any reason the rest of the codebase doesn't really use it?

Respect isBase64Encoded flag with Lambda integrations in API Gateway.

---

localstack/services/awslambda/lambda_api.py
localstack/services/generic_proxy.py
localstack/utils/common.py
localstack/utils/kinesis/kinesis_util.py
tests/integration/test_api_gateway.py
tests/integration/test_integration.py

This PR fixes a couple of deprecation warnings of using `imp` and `getargspec`.

fix deprecation warnings

---

tests/integration/serverless/package.json

this PR fixues the current build failures happening in `tests/integration/test_serverless.py`, which seem to have to do with the latest serverless release 2.48.1

pin serverless version to 2.48.0

---

tests/integration/test_terraform.py

Changes terraform version check to a regex match.
`terraform -version` can also show out-of-date notices like this:
```
Your version of Terraform is out of date! The latest version
is 1.0.1. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0
```
This PR matches directly to the version string, so the check passes even when terraform displays this message.

add regex matching to check_terraform_version

---

.circleci/config.yml
.coveragerc
.coveralls.yml
Dockerfile
Makefile
requirements.txt

Update coveralls config

---

README.md
tests/integration/serverless/package.json
tests/unit/test_apigateway.py
tests/unit/test_cloudwatch.py
tests/unit/test_common.py
tests/unit/test_edge.py
tests/unit/test_firehose.py
tests/unit/test_kinesis.py
tests/unit/test_lambda.py
tests/unit/test_misc.py
tests/unit/test_s3.py
tests/unit/test_sns.py
tests/unit/test_sqs.py
tests/unit/test_tagging.py
tests/unit/utils/generic/test_dict_utils.py

refactor(tests): Invert asserts in unit test #4197

---

.circleci/config.yml
.coveralls.yml

Remove coveralls token information from repo. Config is now fully over CI environment variables

remove superfluous coveralls config, now managed via CI env

---

localstack/services/cloudformation/service_models.py
localstack/services/install.py
localstack/services/kinesis/kinesis_starter.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/test_kinesis.py

This PR introduces a workaround for the issue that localstack startup fails with `DATA_DIR` and kinesis-mock provider

add workaround for kinesis-mock persistence startup failure

---

localstack/services/install.py

I think the recent change in the base image made pip not accessible from the command line.
This PR  makes the installation process of **debugpy** to be done through the pip module.

Fix installation of debugpy

---

localstack/dashboard/api.py
localstack/services/awslambda/lambda_api.py
localstack/services/cloudformation/cloudformation_api.py
localstack/services/dynamodbstreams/dynamodbstreams_api.py
localstack/services/es/es_api.py
localstack/services/firehose/firehose_api.py
localstack/services/generic_proxy.py

The starting or not of certain services based on Flask, makes the logs inconsistent, with this PR the quieting of those logs are mostly depended on the DEBUG variable.
I think we should consider removing completly the `quiet` param since just quieting one service, quiets all the other Flask APi's, because they share the **werkzeug** logger.
This PR  addresses #4162

Fix the showing of Flask API Logs according to which service is started

---

localstack/services/events/events_starter.py

Certain event fields could be empty strings, but the current filter does not allow that.
For example, 'source' _could_ be empty, and the eventpattern could allow that, but the filter would not permit that.

EventPattern matching does not allow matched events to be empty

---

tests/unit/test_common.py

fixes an issue where the tests wouldn't produce the expected result in docker

fix test command because date does not resolve nanoseconds in docker

---

localstack/services/generic_proxy.py

The JavaScript AWS SDK v3 requires the added headers in the browser, CORS errors otherwise.

Add CORS headers needed for AWS SDK v3

---

localstack/utils/cloudformation/template_deployer.py

When for example creating a stack in CDK with an s3 bucket that has static hosting enabled (e.g. implicitly when specifying an index document) and a cloudfront distribution, the distribution tries to reference the s3 bucket attribute WebsiteURL. This PR adds support for this attribute and returns the buckets HTTP URL.
Relevant AWS docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
Example with minimal CDK stack contents:
```typescript
export class CloudFrontStack extends cdk.Stack {
constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
super(scope, id, props);
const bucket = new s3.Bucket(this, 'bucket', {
websiteIndexDocument: 'index.html',
});
const dist = new cloudfront.Distribution(this, 'distribution', {
defaultBehavior: { …
```

Support s3 cloudformation Fn::GetAtt WebsiteURL

---

.pre-commit-config.yaml
Makefile
requirements.txt

This PR adds a pre-commit config to automatically run black/flake8 on commit. 
`pip install -r requirements.txt`
`make init-precommit` or `pre-commit install` will add the hook to `./.git/hooks`
To test it simply change a python file in `tests/` to be incompatible with the back format (e.g. use `'` quotes for a string) and try to commit the changes. It should fail the commit and automatically format the file for you.

Use pre-commit to automatically lint/format files

---

localstack/constants.py
localstack/services/infra.py
localstack/utils/persistence.py
tests/unit/utils/test_persistence.py

this PR introduces a new file `startup_info.json` into the `DATA_DIR`. Each time localstack is started with this data dir, the file is amended with a record that contains: the timestamp when it was started, the localstack version, the localstack_ext version, and whether the pro license key was activated.
it will look something like this:
```json
[{"timestamp": "2021-07-13T13:01:39.980737", "localstack_version": "0.12.15", "localstack_ext_version": "0.12.12.4", "pro_activated": false}]
```

add feature to save localstack version info into data dir

---

localstack/services/iam/iam_starter.py
tests/integration/test_iam.py

Fixes #4291 
The right response for a non existent policy should be raise an `IAMNotFoundException` instead of 500 (not implemented). A little monkey patching solves this.
Example hitting AWS for real:
```
aws --profile localstack iam delete-policy --policy-arn arn:aws:iam::000000000000:policy/non-existent-policy
An error occurred (NoSuchEntity) when calling the DeletePolicy operation: Policy arn:aws:iam::000000000000:policy/non-existent-policy was not found.
```

Fix: Adding IAM exception response when calling DeletePolicy on non existent policy

---

localstack/services/install.py

See https://github.com/etspaceman/kinesis-mock/releases/tag/0.1.4
0.1.4 fixes a bug in the UpdateShardCount API.

Update Kinesis-Mock to 0.1.4

---

localstack/services/awslambda/lambda_executors.py

Apigateway sends event with datetime object, which does not play with json.dumps().
Closes #4307

Javascript local executor does not work with certain events

---

tests/integration/test_acm.py

Adding integration tests for #4313.
Please only merge after https://github.com/localstack/moto/pull/31
Adds an ARN check to the certificate import integration test.

Fix: Extend ACM ARN integration test when importing certificates

---

localstack/services/awslambda/lambda_api.py
tests/integration/terraform/event_source_mapping.tf
tests/integration/test_terraform.py
tests/unit/test_lambda.py

So after much delving into the Terraform AWS provider, AWS Go SDK, and the AWS API docs themselves, I think I've identified the core issue. The error that is cropping up occurs when the AWS Go SDK runs the [GetEventSourceMapping](https://github.com/aws/aws-sdk-go/blob/e54742b5910e84b907c8a555b265c20c143b6b95/service/lambda/api.go#L1861) operation against the AWS API. Diving through the internals of the Go SDK we arrive at the function that [sends the actual request](https://github.com/aws/aws-sdk-go/blob/e54742b5910e84b907c8a555b265c20c143b6b95/aws/request/request.go#L589-L620) to AWS. The line of code which is failing is at [611](https://github.com/aws/aws-sdk-go/blob/e54742b5910e84b907c8a555b265c20c143b6b95/aws/request/request.go#L611) since the error logging matches the [code …

Potential bugfix for #4295

---

tests/integration/fixtures.py

Additional structure around adding type hints for our clients will be in a future PR.
This PR replaces the botostubs in the test fixtures for the clients with boto3-stubs.
Run `python -m pip install 'boto3-stubs[all]'` to install boto3-stubs for all AWS services.
The `TYPE_CHECKING` variable guards the type imports because we don't want to include the type libraries in the packaged production code.
about `TYPE_CHECKING`: 
> A special constant that is assumed to be True by 3rd party static type checkers. It is False at runtime.

replace botostubs with boto3-stubs

---

localstack/services/install.py
localstack/services/kinesis/kinesis_starter.py
localstack/services/plugins.py
localstack/utils/bootstrap.py
localstack/utils/common.py

This PR fixes #4340 
* we noticed that, if docker is running on quemu (for example when running localstack in docker on an M1 with arm64 chip), the amd64 binary will be (correctly) selected, but fails due to a segmentation fault. as a workaround, this PR introduces a `KINESIS_MOCK_FORCE_JAVA` flag to force the use of a jar file
* use the `result_future` from `FuncThread` in the `ShellFuncThread` to transport the return code of the process
* this allows us to check in the `kinesis_start` whether the process has terminated, and if so, we short circuit the health check to avoid the unhelpful urllib exceptions.
the last two points give yet another nudge to a more generalized and event-driven service manager

improve kinesis startup routine

---

.circleci/config.yml

This PR adds a build step to the CI pipeline, specifically the job that tests the lambda docker executors, that also runs the tests for the docker client. these are not skipped in the Dockerfile, since `docker` as a command is not available during docker build. Thanks for @dfangl for the hint!

add CI step to test docker client

---

localstack/services/cloudformation/cloudformation_api.py
localstack/services/cloudwatch/cloudwatch_listener.py
localstack/utils/aws/aws_responses.py
tests/unit/utils/aws/test_aws_responses.py

Background: Some AWS API endpoints use member tags to wrap list instances in XML (see sample response here: https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DescribeChangeSet.html)
Some of the AWS API XML responses need a bit more custom serialization logic that xmltodict.unparse doesn't support.
I've also noticed that a lot of the current "member" wrapping was usually only applied on the top level of the responses. We also need a more flexible way to handle empty tags for some endpoints which might require changes to this xml serialization (more customization) in the future as well.

replace unparse with custom xml serializer for aws responses

---

README.md
localstack/config.py

This PR fixes the docker detection on hosts with only cgroup unified hierachy enabled.
Thanks @dominikschubert and @thrau for helping to fix this.
Similar issue and solution as here: https://github.com/GoogleContainerTools/kaniko/issues/1592
Systemd also uses this mechanism: https://github.com/systemd/systemd/blob/6604fb0207ee10e8dc05d67f6fe45de0b193b5c4/src/basic/virt.c#L523-L548
Option for overriding the check with a true value, to be able to handle the case all the detection mechanisms fail.

Fix docker detection on hosts with cgroup v2 (unified hierachy)

---

localstack/services/events/events_listener.py

Work Done
--- 
Remove proxy of: 
- `AWSEvents.ListTagsForResource`
- `AWSEvents.TagResource`
- `AWSEvents.UntagResource`
This allows the moto events backend to resolve the operations instead. Using its own tagging service. 
Check this PR: localstack/moto#38
I've checked the sources where these tags are used, and it seems that there are no consumers in localstack that access this directly. Still this is open to discussion and any feedback is welcome!

refactor(events): Allow EventBus tag operations to be forwarded to moto

---

README.md

As seen in #4360 , there is some confusion about the Web UI, since it has been remove, but the Readme still contains a section about it.
This PR removes the regarding sections in the Readme, to prevent further problems.

Remove WEB UI documentation in Readme

---

localstack/services/awslambda/lambda_api.py
localstack/services/infra.py
localstack/utils/config_listener.py
tests/integration/test_config_endpoint.py
tests/unit/test_misc.py

Adds the possibility to subscribe to config changes via the _config_ endpoint, for services where direct dependencies to the config values is not feasable.
Fixes #4363 
Adds the possibility for further services to enable live changes of the config. Could be useful for testing etc.

Add possibility to subscribe to config changes from services

---

localstack/utils/aws/aws_stack.py
tests/unit/utils/aws/test_aws_stack.py

See https://github.com/localstack/localstack/pull/4259
This PR removes the erroneous line that prevents the AWS credential environment variables being made available to dockerized Lambdas, which then prevents them from accessing other LocalStack services.
An additional commit will, with the guidance of @dominikschubert, add tests to verify correct behavior.

Remove shadowing env parameter

---

tests/integration/test_ec2.py

* Add tests for #4373 
* Tests won't pass until https://github.com/spulec/moto/pull/4096 is merged
Extending integration tests to match route table associations right state.

Feat: Adding integration test for route table association

---

localstack/services/apigateway/apigateway_listener.py

Minor change, the first group has to be non capturing, to work on line 256 correctly (and for pro).

Fix HOST_REGEX_EXECUTE_API regex

---

localstack/services/cloudformation/cloudformation_api.py
localstack/utils/aws/aws_responses.py
localstack/utils/aws/aws_stack.py
localstack/utils/cloudformation/template_deployer.py
localstack/utils/cloudformation/template_preparer.py
localstack/utils/common.py
localstack/utils/generic/wait_utils.py
tests/integration/cloudformation/test_cloudformation_changesets.py
tests/integration/cloudformation/test_cloudformation_stacks.py
tests/integration/fixtures.py
tests/integration/templates/dynamicparameter_ssm_string.yaml
tests/integration/templates/sns_topic_simple.yaml
tests/integration/templates/ssm_parameter_def.yaml
tests/integration/test_cloudformation.py
tests/integration/util.py
tests/unit/utils/test_common.py

Adds support for SSM parameter resolution for CloudFormation. 
There are still some issues with the flow for parameter initialization which will need a bit more refactoring in the future but for now it adds the SSM string parameter support without rewriting too much of the core CFn logic.
Some other changes:
- Started adding new tests in a new cloudformation test subdir for integration tests since we'll have to add more CFn tests here in the near future. The exiting Unittest tests will be moved there in the near future as well and split up where necessary.
- Added new fixtures for cleanup (might make sense to encapsulate them in a utils fixture to avoid too many parameters in the unit tests)
- Minor type hint additions
- Support for change set types ("CREATE"/"UPDATE") and corresponding …

Support resovling SSM parameter values in CloudFormation

---

localstack/services/awslambda/lambda_api.py

Cleanup of a lambda should happen regardless of the parameters to the way function code is set.

Add lambda cleanup in any case if function code is updated

---

README.md
localstack/services/apigateway/apigateway_starter.py
localstack/services/apigateway/helpers.py
tests/integration/test_api_gateway.py

Add ability to specify custom IDs for API GW REST APIs via tags. This has been requested by some of our users, to simplify the dev&test loop if the API resources are frequently re-deployed.

Add ability to specify custom IDs for API GW REST APIs via tags

---

localstack/services/kms/kms_starter.py

Introduce `KMS_PROVIDER` environment variable to configure the KMS provider, switch from [`local-kms`](https://github.com/nsmithuk/local-kms) to `moto` as default provider. 
Main reasons for switching are twofold:
1. Support for multiple regions in parallel (currently `local-kms` only supports a single region via `KMS_REGION`)
2. Slightly more light-weight (no need to manage a separate external process)
We'll see how it goes regarding full parity for the `encrypt`/`decrypt` API methods - we can still switch back in case there are any issues.

Introduce KMS_PROVIDER env variable, switch to moto as default KMS provider

---

Dockerfile
docker-compose.yml
localstack/config.py
localstack/constants.py
localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/services/edge.py
localstack/services/events/scheduler.py
localstack/services/generic_proxy.py
localstack/services/install.py
localstack/utils/analytics/event_publisher.py
localstack/utils/async_utils.py
localstack/utils/bootstrap.py
localstack/utils/cli.py
localstack/utils/common.py
localstack/utils/docker.py
localstack/utils/kinesis/kinesis_connector.py
localstack/utils/kinesis/kinesis_util.py
localstack/utils/run.py
localstack/utils/server/http2_server.py
localstack/utils/server/multiserver.py
tests/integration/docker/conftest.py
tests/integration/docker/test_docker.py
tests/integration/test_lambda.py
tests/unit/test_common.py
tests/unit/test_misc.py

This PR replaces run() calls throughout the code base with calls of the docker client, to reduce possible vulnerability to command injection.
To prevent issues with circular imports. the run() method and FuncThread() class had to be moved from bootstrap.py to a separate package.

Rework docker usage in LocalStack to make use of the docker client

---

Dockerfile
README.md
localstack/config.py
localstack/plugins.py
localstack/services/apigateway/apigateway_listener.py
localstack/services/apigateway/helpers.py
localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/utils/aws/aws_stack.py
localstack/utils/aws/request_context.py
localstack/utils/common.py
tests/integration/lambdas/lambda_integration.py
tests/integration/test_integration.py
tests/integration/test_lambda.py
tests/integration/test_multiregion.py

This PR adds support for multi-region request handling.
Note: This may be a potentially breaking change for some users - however, controlling the request region from the client is more in line with the behavior in real AWS.
The current request region is tracked in a thread-local variable (`THREAD_LOCAL`), so that invocation chains are automatically using the correct region in the `Authorization` header (e.g., if the client is calling an API method which then calls another API as part of handling the request).
TODOs:

Add support for multi-region request handling

---

localstack/services/cloudformation/service_models.py

When you're deploying an `AWS::IAM::User` with the UserName property defined isn't taken, uses the physical resource id instead of.
Also, the console it's printing: `localstack_1  | 2021-08-12T02:15:09:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type IAM::User when resolving references of resource HeveaUser: {'Type': 'AWS::IAM::User', 'LogicalResourceId': 'CustomUsername', 'Properties': {'UserName': 'custom_username'}}`
The current result it's:
```console
> aws iam list-users
{
"Users": [
{
"Path": "/",
"UserName": "CustomUsername",
"UserId": "ohy0nq0xlr17v8i72b1e",
"Arn": "arn:aws:iam::000000000000:user/CustomUsername",
"CreateDate": "2021-08-12T02:15:08.897Z"
}
]
}
```

Fix: IAM User with custom username isn't created with property

---

localstack/services/cloudformation/service_models.py

For some reason, the managed policies were returning role RNAs, instead of policy, this PR corrects that small error

Fix: solve issue with wrong arn generation in managedpolicy

---

localstack/services/plugins.py
requirements.txt

Add basic interface for `StateSerializer` to be used in persistence mechanism.
This is the first PR in a series of changes aiming to establish a flexible, composable `ServicePlugin` component model that will allow us to encapsulate the entire lifecycle of service plugins in a more clean way.
Currently, the changes in this PR are mostly related to the interface of `StateSerializer` - implementations are added elsewhere, and more details will follow soon.

Add basic interface for StateSerializer to be used in persistence mechanism

---

localstack/services/cloudformation/service_models.py
localstack/utils/cloudformation/template_deployer.py
localstack/utils/common.py
tests/integration/cloudformation/test_cloudformation_resource_sns.py
tests/integration/templates/sns_topic_fifo_dedup.yaml

When creating a deduplicated FIFO SNS topic via cloudformation, the attributes were previously passed as booleans whereas it botocore expects strings here. They are now passed down as "true"/"false"

Fix: SNS FIFO topic creation via cloudformation

---

.coveragerc
.flake8
.pre-commit-config.yaml
Dockerfile
Makefile
bin/Dockerfile.base
pyproject.toml
requirements.txt

This PR moves .flake8 and .coveragerc into pyproject.toml
* Use pflake8 wrapper
* Use coverage[toml] extra
* The makefile line "pip install coverage[toml]" can be removed once the docker base image has been deployed

Consolidate .coveragerc and .flake8 config int pyproject.toml

---

localstack/utils/common.py
tests/unit/test_common.py

This PR adds a test class with example tests for basic file operations implemented in `common.py`

add unit tests for file operations

---

doc/feature_coverage.md
localstack/services/awslambda/lambda_executors.py

Currently the Feature Coverage misses this option.
Also, we should print some kind of warning if someone tries to use an ImageUri with LocalStack, and not fail only with an obscure error message.
Fixes #4452

Document Custom Image support for Lambdas

---

localstack/utils/docker.py
requirements.txt
tests/integration/docker/test_docker.py

Fixes #4515 
If a non-default network is assigned to the container queried, it will return an empty string instead of a correct IP.
This PR fixes this behaviour by returning the IP of the first assigned network (can lead to problems if LocalStack is assigned multiple networks for different purposes, but the fix provides a similar behavior to the command line client)

Fix getting IP addresses of docker containers with non-default networks

---

localstack/services/infra.py
localstack/utils/common.py
localstack/utils/run.py
tests/unit/utils/test_common.py

Disable shell mode in `run(..)` utility function if `cmd` is passed as a list - see description in the code comment.
/cc @thrau @dfangl

Disable shell mode in run(..) util if cmd is passed as a list

---

README.md

Found out while debugging #4492 there is no clear documentation for providers (except kinesis), adding those to our `README` as a separate section. Also Moved `KINESIS_PROVIDER` there. as well

Fix: Adding providers sections to README.md

---

localstack/services/cloudformation/models/apigateway.py
localstack/services/cloudformation/models/awslambda.py
localstack/services/cloudformation/models/dynamodb.py
localstack/services/cloudformation/models/elasticsearch.py
localstack/services/cloudformation/models/iam.py
localstack/services/cloudformation/models/kinesisfirehose.py
localstack/services/cloudformation/models/s3.py
localstack/services/cloudformation/models/stepfunctions.py
localstack/utils/cloudformation/cfn_utils.py
localstack/utils/cloudformation/template_deployer.py

Part of the service model refactoring effort. Moves the rest of the RESOURCE_TO_FUNCTION in the template_deployer into the respective service models.
One part I'm not 100% certain about is the change in the last commit. I've dropped/removed the get_role_arn call which itself depends on resolve_refs_recursively. I would've assumed the parameters should already have gone through a resolve_refs_recursively call by this point? @whummer  Maybe you can provide a bit more insight here.  The original get_arn_role code was added in 3684fcfd66baa387e03f6b2d9d30585a4ab0130a

Move rest of RESOURCE_TO_FUNCTION into service models

---

Dockerfile
localstack/services/cloudformation/cloudformation_api.py
localstack/services/cloudformation/models/ec2.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/test_cloudformation.py

~Add temporary debug logs to investigate flaky EC2 CloudFormation test.~
Fix template deployer and tests to retrieve updated PhysicalResourceId for EC2::Instance

Fix template deployer and tests to retrieve updated PhysicalResourceId for EC2::Instance

---

.circleci/config.yml
Dockerfile
Makefile
README.md
localstack/services/install.py
localstack/utils/bootstrap.py
requirements.txt
setup.py

This PR prepares the build environment for the setuptools configuration we have introduced in other projects, where we group dependencies using setup.py extras.
* reorganize `requirements.txt` to group dependencies into "extra" blocks
* use `setup.py` to parse the requirements into extras
* refactor `Makefile` to install with `pip install -e .`
* refactor `Dockerfile` to use the new make commands and uninstall test dependencies
* disables several dependencies from requirements.txt
* makes the image smaller  (:pinching_hand:)

Restructure python requirements and Dockerfile

---

.github/workflows/pro-integration.yml

This Action runs the LocalStack integration tests against a Pro Instance, to check if any problems arise and reports them.
This should provide more confidence that LocalStack changes do not brick any features in Pro or vice versa.
To be merged after #4485

Run LocalStack tests against LocalStack Pro in Github Action

---

tests/integration/fixtures.py
tests/integration/test_lambda.py

This is a quick fix, as this test runs only if glibc >= 2.32 is present on the system, which might not be the case outside of the docker/alpine image.

Run golang local test only if executed in Alpine

---

localstack/services/cloudformation/models/stepfunctions.py
localstack/utils/generic/wait_utils.py
tests/integration/cloudformation/test_cloudformation_stepfunctions.py
tests/integration/fixtures.py
tests/integration/templates/stepfunctions_statemachine_substitutions.yaml
tests/unit/test_cloudformation.py

Adds support for  the "DefinitionSubstitutions" property in  for Cloudformation/SAM StateMachine resources. This property is used to inject dynamic values (e.g. ARNs resolved by cloudformation or other results from intrinsic functions) into the statemachine definition.
Context: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
Closes #4533

add support for DefinitionSubstitutions in AWS::StepFunctions::StateMachine

---

README.md
docker-compose.yml
localstack/utils/bootstrap.py

Currently, the example docker-compose file uses TMPDIR incorrectly. If one would use this environment variable not to describe the actual TMPDIR (example /tmp), but the localstack-specific TMPDIR (most likely /tmp/localstack), it would produce inconsistent behavior.
The docker-compose.yml is updated to correctly use the TMPDIR value, and a warning is now displayed (should be discussed) if the HOST_TMP_FOLDER and the TMP_FOLDER of localstack (by default both /tmp/localstack) mismatch, to warn of possible configuration errors.

Correctly document and use TMPDIR and HOST_TMP_FOLDER in docker-compose

---

localstack/services/cloudformation/models/sqs.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/cloudformation/test_cloudformation_sqs.py
tests/integration/templates/sqs_with_queuepolicy.yaml

Adds support for the [AWS::SQS::QueuePolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-policy.html) resource.

Add CloudFormation support for AWS::SQS::QueuePolicy

---

localstack/services/cloudformation/models/events.py
tests/integration/cloudformation/test_cloudformation_events.py
tests/integration/fixtures.py
tests/integration/templates/eventbridge_policy.yaml
tests/integration/templates/eventbridge_policy_singlepolicy.yaml

Adds support for the [AWS::Events::EventBusPolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbuspolicy.html) resource.
Second part of the test is commented out for now since this is a general issue of our cloudformation engine right now that will be handled separately.

Add CloudFormation support for AWS::Events::EventBusPolicy

---

localstack/services/sns/sns_listener.py
tests/integration/test_sns.py

AWS behavior is to only pass sns message attributes as sqs message attributes if `raw_message_delivery` is enabled.
PR #3887 introduces this behavior, which is not identical to AWS.
Demo SQS Message if raw_message_delivery is not enabled on AWS:
```
{
"Messages": [
{
"MessageId": "cb98bce2-f11f-4bac-8870-0605ada8cb91",
"ReceiptHandle": "AQEBSvvZb/WZACLr3onUPhHEyGLrtmmzA8e8wK0w8A+UykenUK7v2rxk6qy4MAfVKfr6ywmxjuKNuaLmjDtjt1f7xUR6llpad6Iy8dpShvooPsszYvGYzYFjp3f61oF8VZfMmzklM5Z6CtQN6Vr5NmG+/FZn2hRVo4s54Oy00GvVcj1bm8tOt/am4CwLKTzsD2hXa/lXIQ9Sl+QPGSM2rOBmqKqUQ9bET8vPsx1xdt9Ag7nSGlCBkW1/AUrlkZPPGb+/YtoqbU7St0iKbKLNv1WZt7JxSrAq0VNEAFOzF8sbweyHpe/NIpn4BELwLDFNB4T8ahw8mmoBr2WVJhbvDz7imiXA8uri4fsqGuJPHzIugKO+GhlZ3GSPpExpsyZF4+lGcv/oVgaiKi7NuV6Ord6yGA==",
"MD5OfBody": …
```

Fix raw message delivery attribute for sns/sqs subscriptions

---

README.md
localstack/config.py
localstack/constants.py
localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/services/edge.py
localstack/services/sqs/sqs_listener.py
localstack/utils/aws/aws_responses.py
localstack/utils/bootstrap.py
localstack/utils/common.py
tests/unit/test_moto.py

Distinguish polling and reactive mode in Lambda `EventSourceListener`. This can be used to enhance the performance of, e.g., the SQS event source listener. However, it is still required to delete messages from the queue after the listener has consumed them (hence polling is still enabled as default mode for SQS).
In the near future, we may enhance/replace this with a centralized event bus, allowing the event source listeners to subscribe to updates directly.

Distinguish polling and reactive mode in EventSourceListener

---

README.md
localstack/services/apigateway/apigateway_listener.py
tests/integration/test_api_gateway.py

Support `<apiId>.execute-api.*` hostnames for API Gateway invocation URLs. 
This allows users to use the more convenient format:
```
http://<APIGATEWAY_ID>.execute-api.localhost.localstack.cloud:4566/<stage>/<path>
```
... in addition to:
```
http://localhost:4566/restapis/<APIGATEWAY_ID>/<stage>/_user_request_/<path>
```

Support <apiId>.execute-api.* hostnames for API Gateway invocation URLs

---

localstack/utils/docker.py
tests/unit/test_dockerclient.py

This PR improves the parsing of volume flags in LAMBDA_DOCKER_FLAGS and BATCH_DOCKER_FLAGS, so windows paths can be sent to the docker daemon (which should work with docker desktop for windows: https://docs.docker.com/desktop/windows/troubleshoot/#path-conversion-on-windows)
Prior logic just separates by colons `:`, which is inadequate for windows paths.

Improve parsing logic for LAMBDA_DOCKER_FLAGS volumes

---

localstack/services/dynamodb/dynamodb_listener.py
tests/integration/test_dynamodb.py

Fixes #4581.
* Fixing missing `SSEDescription` and `TableId` property on both `CreateTable` and `DescribeTable` output
* Adding tests to fit these requirements.
* Some minor fixes like redundant conditionals

Fix: DynamoDB output missing SSEDescription key and TableId

---

localstack/services/cloudformation/models/apigateway.py

Fixing #4529  -   ApiKeyRequired value was not getting passed to API gateway.
https://github.com/localstack/localstack/issues/4529

Fix: ApiKeyRequired in API Gateway not working from cloud formation

---

localstack/services/infra.py

importing `localstack.services.infra` takes over 4 seconds on my machine, mostly because of the `cloudformation_api` (3.4 seconds).
but we don't necessarly need `cloudformation_api` (and others) when we import the `infra` module.

move api imports in infra.py to respective start methods

---

localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/services/awslambda/lambda_utils.py
localstack/utils/aws/aws_models.py
localstack/utils/run.py
tests/integration/test_lambda.py

Follow-up of #4623 :
* Refactor Lambda executor methods to use `InvocationContext` as input param
* Add more type hints to Lambda executors

Refactor Lambda executor methods to use InvocationContext as input param

---

localstack/services/cloudformation/models/s3.py
localstack/services/s3/s3_listener.py
localstack/services/s3/s3_utils.py

This PR fixes an issue, where this line: https://github.com/localstack/localstack/blob/5ed4699e4803b111ac62ab986513d0ea40ea7d81/localstack/services/generic_proxy.py#L385-L386
would lead to a complete import of the cloudformation API.
This lead to the first HTTP request to the edge server taking over 3 seconds.
Related to this todo: https://github.com/localstack/localstack/blob/5ed4699e4803b111ac62ab986513d0ea40ea7d81/localstack/services/s3/s3_listener.py#L1033-L1035
Generally I think it's better the cloudformation service depends on other services (like in this instance, now the `s3_utils` provided by `services.s3`) rather than the other way around.

move normalize_bucket_name to s3_utils

---

localstack/utils/aws/aws_stack.py

This PR addresses issue #4158.
The problem derives from the function `lambda_function_or_layer(...)` considering the : (Colon) in the entity_name parameter as an error when in reality it can refer to an alias of the function.
With this PR, the function now also searches for a version of the function using the alias.

Consider alias in lambda_function_or_layer.

---

.github/workflows/pro-integration.yml
tests/integration/docker/test_docker.py
tests/integration/test_api_gateway.py

Some tests make assumptions that no longer hold, depending on the environment and whether Pro is enabled or not, that is changed with this PR.
Also I remove the disabled retries, maybe that makes some tests more resilient.

Make some integration tests more lenient to environment changes

---

localstack/services/cloudformation/cloudformation_api.py
tests/integration/cloudformation/test_cloudformation_stacks.py
tests/integration/fixtures.py

Addresses #4626
* fix CFN `list_stack_resources()` for stacks with deleted resources
* extend tests to cover this case

Fix CFN list_stack_resources() for stacks with deleted resources

---

docker-compose.yml

* Update `HOST_TMP_FOLDER` to avoid slash duplications (`$TMPDIR` already comes with a trailing slash)
* Remove surrounding quotes since they are getting passed (at least on Mac) as part of the `$HOST_TMP_FOLDER` var, resulting in paths like `"a/b/c"/d` which leads to mounting errors
Please let me know if these changes may lead to any negative side effects on platforms other than Mac.

chore(compose): update sample compose file

---

localstack/services/sqs/sqs_listener.py

Correct the way the response data is read so that the `xmlns` data that comes back from elasticmq doesn't cause an error here.
Fixes #4656

Fix for #4656

---

localstack/utils/docker.py
tests/integration/docker/test_docker.py

Currently, it is not possible to inspect docker networks, which is useful for various cli commands.
This PR introduces this possibility in both docker client implementations, and adds tests for them.

Add docker client methods to inspect networks

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

Hi.
When we execute `aws s3api copy-object` command, AWS publishes `ObjectCreated:Copy` event.
Currently, localstack publishes `ObjectCreated:Put`.
This PR fixes it.
Regards.

Add support for s3:ObjectCreated:Copy event

---

localstack/services/awslambda/lambda_api.py
tests/integration/serverless/handler.js
tests/integration/serverless/serverless.yml
tests/unit/test_lambda.py

Given situation we have for example two lambdas to deploy. One named getUsers and getUser. When e.g. serverless framework deploys those functions in that order, it fails to deploy getUser because getUsers's arn includes string "getUser".
I just removed the partial arn matching because it was the cause for the problem we faced. Not sure though if it's too naive assumption.

Fix deploying lambdas with similar names

---

localstack/contrib/thundra.py
localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/services/awslambda/lambda_utils.py
localstack/utils/aws/aws_stack.py
localstack/utils/aws/dead_letter_queue.py
tests/unit/test_lambda.py

Allow Lambda plugins to return invocation results directly, streamlining the code, and removing code duplication around invocation forwarding in the presence of `LAMBDA_FORWARD_URL`.
Introduces a `LambdaInvocationForwarderPlugin` which is in charge of forwarding the Lambda invocations. In that process, we are able to remove some of the duplicate error handling code in `lambda_api.py` and `lambda_executors.py`.
There is one `TODO` left in the code - currently we're returning the first result received from a Lambda executor. Technically, there could be multiple execution plugins trying to intercept the invocation and returning a result - we need a better conflict resolution mechanism if that situation comes up in the future (currently a `WARNING` message is being logged should that …

Allow Lambda plugins to return invocation results directly

---

localstack/services/cloudformation/deployment_utils.py
localstack/services/cloudformation/models/apigateway.py
localstack/services/cloudformation/models/awslambda.py
localstack/services/cloudformation/models/cloudformation.py
localstack/services/cloudformation/models/cloudwatch.py
localstack/services/cloudformation/models/dynamodb.py
localstack/services/cloudformation/models/ec2.py
localstack/services/cloudformation/models/events.py
localstack/services/cloudformation/models/iam.py
localstack/services/cloudformation/models/kms.py
localstack/services/cloudformation/models/logs.py
localstack/services/cloudformation/models/redshift.py
localstack/services/cloudformation/models/s3.py
localstack/services/cloudformation/models/secretsmanager.py
localstack/services/cloudformation/models/sns.py
localstack/services/cloudformation/models/sqs.py
localstack/services/cloudformation/models/stepfunctions.py
localstack/services/cloudformation/service_models.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/cloudformation/test_cloudformation_s3.py
tests/integration/templates/s3_bucket_autoname.yaml
tests/integration/test_cloudformation.py

Moves the default values (mostly name generation) to the service models and adjusts/extends the tests where necessary.
The only thing that should be changed on the user's side should be some of the auto-generated Names that now conform more to what CloudFormation would produce.

Move defaults from template_deployer to service models

---

localstack/services/cloudformation/models/ec2.py
localstack/services/cloudformation/models/iam.py
localstack/services/cloudformation/models/s3.py
localstack/utils/cloudformation/template_deployer.py

Moves some delete patching from the `template_deployer.py` to the respective service models.
The patches for `AWS::EC2::Subnet` and `AWS::EC2::RouteTable` were removed since they didn't seem to affect any tests and either didn't make sense in the context or should be handled differently (**if** these issues resurface)

Move delete patches in template deployer to service models

---

tests/integration/test_api_gateway.py
tests/unit/test_lambda.py

Similar to https://github.com/localstack/localstack/pull/4213 . The aliases have been removed in Python 3.11 https://docs.python.org/3/library/unittest.html#deprecated-aliases . Regex to check the cases.
```
rg -t py 'assertEquals|assertNotEquals|assertAlmostEquals|assertNotAlmostEquals|assertRegexpMatches|assertNotRegexpMatches|assertRaisesRegexp|failUnlessEqual|failIfEqual|failUnlessAlmostEqual|failUnless|failUnlessRaises|failIf'
```

Use assertEqual instead of assertEquals for Python 3.11 compatibility.

---

localstack/services/cloudformation/models/awslambda.py
localstack/services/cloudformation/models/kms.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/cloudformation/test_cloudformation_kms.py
tests/integration/templates/kms_key_disabled.yaml

Removes the `fix_resource_props_for_sdk_deployment` from the template deployer and moves the code into the corresponding service models.
Also adds support for the `EnableKeyRotation` and `Enabled` Properties on `AWS::KMS::Key`.

remove fix_resource_props_for_sdk_deployment

---

localstack/services/es/cluster.py

`serving.Server` was inspired by the `ElasticsearchCluster` implementation, and pulled up as part of #4793. this PR uses the new abstract for the `ElasticsearchCluster` implementation.

refactor elasticsearch cluster to use serving.Server

---

localstack/services/cloudformation/models/ssm.py
tests/integration/cloudformation/test_cloudformation_ssm.py
tests/integration/templates/ssm_parameter_defaultname.yaml

Minor fix for the AWS::SSM::Parameter cloudformation resource. Assigns a default name for parameters. Interestingly this generated name is a bit different from the usual AWS scheme of stack-logicalid-random in this case.

Add default for Name in AWS::SSM::Parameter

---

localstack/aws/scaffold.py
tests/unit/aws/test_scaffold.py

There were a few corner cases in APIs that caused the scaffold script to generate invalid code for several services. This PR fixes those remaining issues, specifically surrounding:
* Illegal names (e.g., keywords, containing illegal characters, or starting with numeric characters)
* Circular type references
I added representative services to the `test_generated_code_compiles` as parameters instead of keep the list of all AWS services (which takes about 3 minutes to test through). For reference, this test will try to generate and compile all AWS services:
```python
import pytest
from click.testing import CliRunner
from localstack.aws.scaffold import generate
from localstack.aws.spec import list_services
@pytest.mark.parametrize("service", [service.service_name for service in …
```

Fix scaffolding for remaining AWS services

---

localstack/services/awslambda/lambda_api.py
localstack/services/cloudformation/models/awslambda.py
tests/integration/test_lambda.py

Support version qualifiers for managing Lambda policy statements.
This issue surfaced when replicating this Terraform user scenario which involves Lambda functions with multiple versions/qualifiers: https://github.com/lefnire/gnothi/tree/terraform/terraform

Support version qualifiers for managing Lambda policy statements

---

localstack/services/es/es_api.py

updates the global variable in the es_api.py to the version we set as default a while ago

fix elasticsearch default version in es_api.py

---

localstack/services/dynamodb/dynamodb_starter.py
localstack/services/dynamodb/server.py
localstack/utils/serving.py

This PR adds encapsulation for the dynamodb process into a `serving.Server` subclass, and adds a factory using environment variables to enable #4836

refactor dynamodb to use serving.Server and additional parameters

---

localstack/services/s3/s3_listener.py
localstack/utils/common.py

Following the suggestions from the pull request #4809 ,found that there is already a function that extracts the region from the arn in the suggested lib.
Changes:
- delete the duplicated function
- use of `aws_stack.extract_region_from_arn`

Use previous function to extract region from arn

---

localstack/services/apigateway/apigateway_listener.py
tests/integration/test_api_gateway.py

According to #4818, the object `request_context` inside the event parameter sent to a lambda triggered by a HTTP event should have a `requestId` attribute. 
Changes:
- Add the requestId parameter to the object sent.
- Add the assertion of the parameter in the corresponding test.

RequestId attribute added to request_context

---

localstack/aws/api/core.py
localstack/aws/protocol/parser.py
localstack/aws/skeleton.py
tests/unit/aws/protocol/test_parser.py

This PR fixes a few issues blocking the pilot SQS implementation that are mostly related to dispatching requests.
* sets the attributes of `RequestContext` to None (to avoid attribute errors at runtime)
* skeleton re-uses the parsed operation/request from the RequestContext if it exists (in preparation for new handler framework)
* adds a `ServiceOperation` that encapsulates the unique identifier of an operation `service_name, operation_name` (in preparation for service request routing)
* `ServiceRequestDispatcher` initializes the required default values (boto clients may remove empty lists or dict from the request entirely, but the APIs expect a value)

fix issues in aws service framework dispatching

---

localstack/services/infra.py
localstack/services/plugins.py
localstack/utils/common.py

This PR adds the concept of a `ServiceLifecycleHook` that encapsulates functionality executed during the lifecycle of a `Service`, and can be injected into a `Service`.
This is a preparation for the AWS service framework, where a lifecycle hook can be used to call certain methods of a service when it is initialized or started up. In the future, we can use this abstraction to inject state into services.

add lifecycle hook abstraction for services

---

localstack/constants.py
tests/integration/test_lambda.py

Issue was due to type erasure and creation of bridge functions in Java.
Fixes #4512.
To be released after artifacts of localstack/localstack-java-utils#79 are published.

Fix local execution of java lambdas if handler method is implementing RequestHandler interface

---

localstack/services/cloudformation/cloudformation_starter.py
localstack/services/cloudformation/models/secretsmanager.py
localstack/utils/aws/aws_stack.py
localstack/utils/cloudformation/template_deployer.py
tests/integration/cloudformation/test_cloudformation_secretsmanager.py

There were some issues with the AWS::SecretsManager::Secret  and the related cloudformation test. 
Removes the Username reference from the test template since this isn't actually defined and correctly fails when trying to deploy on AWS. The test now works both against AWS and LocalStack.
Also removes some presumably legacy code and unnecessary physical-id-generating fallbacks that led to some issues/race conditions when deploying the secret where the output resolved to the wrong ARN in up to 50% of test runs.

Fix AWS::SecretsManager::Secret ARN/Physical ID handling and tests

---

localstack/config.py
localstack/utils/analytics/event_publisher.py
localstack/utils/common.py
tests/integration/test_integration.py
tests/unit/test_common.py

This PR introduces the option to add permissions when saving files, especially important for config files.
Also an experiment to make a flaky test more stable (and in the same time mark as xfail, to evaluate during some time in the CI).

Add option to add permissions for file

---

localstack/constants.py
localstack/services/es/cluster.py
localstack/services/es/es_api.py
localstack/services/es/versions.py
localstack/services/install.py
requirements.txt

This PR adds support for older (and generally more) elasticsearch versions. I've refactored a bit of the version and URL fetching logic to make it less static (removed the `ELASTICSEARCH_URL` constants and replaced it with a function).
I've tested the creation of a cluster with ES 5.5 locally, and at least starting/stopping and the health endpoints work. The default version is still respected (set to 7.10.0)

add support for more elasticsearch versions

---

localstack/services/sqs/sqs_starter.py

As indicated by the latest comment in #2626 message attribute bodies are now wrapped inside a CDATA tag (as of moto/moto#4337). This does not match the behaviour of AWS which uses html encoding. This behaviour is handled fine by some XML parsers (such as the one used by boto - hence the passing tests) but it causes issues for some SDKs, the .Net one in particular.
This PR removes the CDATA wrapper and relies on the existing escaping call to handle special characters (essentially reverting localstack behaviour back to before the moto change). 
I have not added any tests as I wasn't sure if they were possible when using the boto library, it only exposes the decoded attribute values.

Remove moto's CDATA wrapper from sqs message attr StringValue

---

localstack/services/es/cluster.py
localstack/services/es/es_api.py
localstack/services/generic_proxy.py
localstack/services/infra.py
localstack/services/install.py
tests/integration/test_elasticsearch.py
tests/unit/services/test_generic_proxy.py

This PR adds support for custom elasticsearch endpoints that can be routed through the edge proxy as described here:
* #4861
The newly introduced `UrlMatchingForwarder` allows limited URL rewriting, and facilitates both host and path-based URL matching and forwarding rules.
For example, you can define: `http://localhost:4566/my-cluster-endpoint => http://localhost:12356/`, and `http://localhost:4566/my-cluster-endpoint/foo/bar` will be routed to `http://localhost:12356/foo/bar`, which is what we need to route requests through the edge proxy to a backend like elasticsearch. The `UrlMatchingForwarder` supports other patterns as well (see the test for it)
To test the elasticsearch feature run:
```
awslocal es create-elasticsearch-domain \ …
```

implement custom endpoint routing for elasticsearch clusters

---

localstack/services/cloudformation/deploy.html
localstack/services/edge.py
localstack/utils/common.py

Add simple UI for deploying CloudFormation stacks from public template URLs. Inspired from the "1-click deploy" feature in the AWS console that allows to point to an existing CFN template URL, fill out the required parameters, and trigger the deployment from the browser.
The app is implemented as a standalone React app, with embedded babel runtime compiler. (Deliberately kept simple, to avoid having a separate build step for this app).
The app is accessible under `http://localhost:4566/_/deploy`, and we can either pass in `templateURL` as a query parameter, or enter the template URL (e.g., https://s3.eu-central-1.amazonaws.com/cloudformation-templates-eu-central-1/DynamoDB_Secondary_Indexes.template) on the start page:
-----
-----
In the next step we download the template URL and extract …

Add simple UI for deploying CloudFormation stacks from public template URLs

---

localstack/utils/docker_utils.py
tests/unit/test_common.py
tests/unit/test_dockerclient.py

this PR fixes a bug that causes starting localstack to fail to startup when specifying a port mapping from a range of host ports to a single container port EG `-p 9230-9231:9230`.  This turns out to be essential for being able to debug simultaneous nodejs lambda containers.  I am hoping to share the nodejs integration of localstack as described [here](https://github.com/localstack/localstack/issues/4443) but i discovered it was broken when trying to run on the newest version.
Specifying a host port range did work in version (0.12.16) but fails with the newest version of localstack.  To reproduce this you can pass a port range such as the example above into the `LAMBDA_DOCKER_FLAGS` variable of a localstack dockerfile.  
I have unit tested this (small) change but I was not able to build …

support ranges of host ports to be mapped to a container port

---

localstack/config.py
localstack/services/es/cluster.py
localstack/services/es/cluster_manager.py
localstack/services/es/es_api.py
localstack/services/es/versions.py
localstack/services/generic_proxy.py
tests/integration/conftest.py
tests/integration/fixtures.py
tests/integration/test_elasticsearch.py
tests/unit/services/es/test_cluster_manager.py

this PR adds one-cluster-per-domain support #4865 as well as the (necessary) domain and path-based endpoint creation.
the value of `ES_ENDPOINT_STRATEGY` governs how endpoints are created for a domain:
* `domain`: `<domain-name>.<region>.es.localhost.localstack.cloud:4566`
* `path`: `localhost:4566/es/<region>/<domain-name>`
* `off`: `localhost:4571` (only works with single cluster)
specifying a custom endpoint like `localhost:4566/foo/bar` will overwrite the behavior and simply make the elasticsearch cluster routable through that endpoint.
a major breaking change is that the localstack ES api now behaves like the AWS api, and does not send a fully-qualified URL in the `Endpoint` field of the `CreateElasticsearchDomain` request. (`localhost:4571` instead of `http://localhost:4571`) …

implement one cluster per domain support for elasticsearch

---

localstack/services/cloudformation/deploy.html

Adds basic formatting to the Cloudformation Stack deployment UI from #4868 
Just thought since the purpose is mostly to visualize the template, having proper formatting, makes it much easier to read for the user.

Format JSON stack template for better readability in UI

---

localstack/services/iam/iam_listener.py
localstack/utils/aws/aws_responses.py

After testing #4831, it's shown that the iam client of the AWS SDK for NodeJs needs the boolean values to be in lowercase not truncated like many other SDKs.
Changes:
- Transform to lowercase the boolean values of the xml content when User-Agent is `aws-sdk-js`

iam response booleans to lowercase

---

localstack/constants.py
localstack/services/edge.py
localstack/services/infra.py
localstack/services/internal.py
localstack/services/routing.py
tests/integration/dashboard/test_graph.py
tests/unit/services/test_internal.py
tests/unit/services/test_routing.py
tests/unit/test_edge.py

This PR adds a tiny framework for routing REST calls to resource classes through the edge proxy, and uses that framework to route internal `/_localstack` calls. It's inspired by the Falcon framework that encapsulates request handlers into classes and `on_<verb>` methods.
Resources can be added with `get_internal_apis().add_route('/my/route', MyResource())` where `MyResource` is a class that  exposes optional `on_get(request: Request)`, `on_post`, `on_put`, ... methods.
We can now also think about adding internal routes through the plugin mechanism.

implement generic approach for routing internal REST resources

---

localstack/utils/docker_utils.py
tests/integration/docker_utils/test_docker.py

For this, we now let the docker sdk handle the parsing of the image name provided.
Also adds test for that particular usecase.
Fixes #4876

Allow pulling of image digests in docker client

---

localstack/services/apigateway/helpers.py
tests/integration/test_api_gateway.py

URLs are encoded by clients and when trying to `get-base-path-mapping` with the `(none)` type localstack fails to match the url since it is encoded `%28none%29`. 
This PR right now decodes the urls being passed into the handle_base_path_mappings. However, it might be worth considering putting this at a higher level to make sure all URLs are decoded.
Fixes #4891

Handle (none) base-path-mappings in API Gateway

---

localstack/services/ssm/ssm_listener.py
tests/integration/fixtures.py
tests/integration/test_ssm.py

Depends on https://github.com/spulec/moto/pull/4542
Our custom patch didn't support paging and because moto has since implemented part of this, I've added the label filtering there making our custom patch unnecessary. Should only be merged after the corresponding moto change is in our fork.
Closes #4607

Remove custom parameter by label filtering

---

localstack/services/apigateway/apigateway_listener.py
localstack/utils/aws/templating.py
localstack/utils/common.py
tests/integration/test_api_gateway.py
tests/unit/test_apigateway.py

Extend `escapeJavaScript(..)` velocity template function and add more tests for it. This function is required for API GW request/response mapping templates.
Partial fix for #4719

Extend escapeJavaScript(..) velocity template function and add more tests for it

---

localstack/services/cloudformation/models/ec2.py
tests/integration/templates/template36.yaml
tests/integration/test_cloudformation.py

The check against current stack was breaking multi route tables creation from the cloudformation template.

Fix cloudformation not creating multi route tables

---

localstack/services/sns/sns_listener.py
tests/unit/test_sns.py

Adds support for `{"exists": false}` filters to SNS filters that were added to SNS in April 2021.
https://aws.amazon.com/about-aws/whats-new/2021/04/amazon-sns-grows-the-set-of-message-filtering-operators/
Closes #4379

Add support for {"exists": false} filter on SNS

---

README.md

While reading documentation recently, I discovered a few typos in the README.md file. This PR corrects what I found.
Note: Given that this is only documentation edits, I didn't think it worthwhile to configure the dev environment for tests or linting, so those haven't been run.

Correcting typos in the README file

---

localstack/aws/api/core.py
localstack/aws/protocol/serializer.py
localstack/aws/proxy.py
tests/unit/aws/protocol/test_serializer.py
tests/unit/aws/test_skeleton.py

This PR changes the `HttpResponse` object in the ASF, which used to be a simple TypedDict, into a werkzeug Response object, which is convenient to use, and is also wsgi compliant.

use werkzeug Response object in asf

---

localstack/aws/api/core.py
localstack/aws/protocol/parser.py
localstack/aws/proxy.py
tests/unit/aws/protocol/test_parser.py
tests/unit/aws/test_skeleton.py

This PR replaces the asf `HttpRequest` typed dict with  a modified version of `werkzeug.sansio.Request` that creates a good adapter between WSGI and localstack. Our `HttpRequest`is a drop-in replacement for werkzeug's WSGI request wrapper, so we can program against the same interface, but doesn't need the underlying WSGI IO (which is necessary when creating `HttpRequest` objects from within the edge proxy).

use werkzeug Request object in asf

---

localstack/services/iam/iam_listener.py

Continuation of #4887. 
Changes:
- The conversion of booleans from the IAM service responses to lowercase is done for all clients now.

Apply convertion for all clients

---

localstack/services/install.py
tests/integration/test_lambda.py

Addresses the comment in https://github.com/localstack/localstack/pull/4754#pullrequestreview-806142105
~~currently we have no way to test this though.~~
for full compatibility we also have to

fix arch check in install_go_lambda_runtime

---

localstack/services/s3/s3_listener.py
localstack/services/sts/sts_listener.py
localstack/utils/aws/aws_responses.py
localstack/utils/common.py

STS responses contain `Content-Type: text/html` header, but AWS returns `text/xml`. 
Some applications (e.g. Hashicorp Vault) rely on `text/xml` and don't work properly.

Fix STS response content type

---

.github/dependabot.yml
Dockerfile

With the recent refactoring of how we build the docker images (https://github.com/localstack/localstack/pull/4754), we do not squash the image anymore.
However, the base image (`python:3.8-slim-buster`) is updated quite frequently. Therefore, we don't really benefit from the layer caching (both the local cache when pulling as well as the remote cache when building), since the whole cache is invalidated with an update of the base image.
This commit explicitly pins the docker base images by referencing them by their manifest-list digest:
```
$ docker buildx imagetools inspect docker.io/library/python:3.8.12-slim-buster
Name:      docker.io/library/python:3.8.12-slim-buster
...
Digest:    sha256:d328c165606db4773f8242972ae82c2f7312478a5071090a768d0e9fc63fab51
...
```
(It needs to be the …

pin docker base images, enable dependabot to update once a week

---

localstack/constants.py

https://docs.python.org/3/library/venv.html
> When a virtual environment is active, the VIRTUAL_ENV environment variable
> is set to the path of the virtual environment. This can be used to check
> if one is running inside a virtual environment.
I use a different directory for my virtual environment, and by coincidence, I use `.venv` file for project-based settings: https://github.com/naspeh/dotfiles/blob/eaf47f55f2e4b7f40e94f178fbe7a29f6c3b9421/env/zshrc#L77-L89
I set `export VENV_DIR=../env/` for `Makefile`, but we have this hardcoded `.venv` in `localstack.constants` that caused some issues while I was bootstrapping the project and running tests.  As you can see from docs, `VIRTUAL_ENV` is a good way to check the virtual environment. I keep existing logic as a fallback.
It is supposed …

Use VIRTUAL_ENV env var for LOCALSTACK_VENV_FOLDER constant

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

While investigating https://github.com/localstack/localstack/issues/4639 found this.
```sh
awslocal s3api delete-objects --bucket test-non-existing --delete '{"Objects":[{"Key":"test.txt"}]}' 
2021-11-18T07:51:59.155:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/test-non-existing?delete: 'NoneType' object has no attribute 'get' Traceback (most recent call last):
File "/opt/localstack/localstack/localstack/utils/server/http2_server.py", line 159, in index
result = await run_sync(handler, request, data)
File "/opt/localstack/localstack/localstack/utils/async_utils.py", line 86, in run_sync
return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
File "/opt/localstack/localstack/localstack/utils/run.py", …
```

s3: fix deleting objects from non-existing bucket

---

.dockerignore
Dockerfile
Makefile

Re-arrange some layers in the Dockerfile to decrease the image size and increase the number of cache hits.
- Move the installation of awscli and awscli-local a bit up. These packages should only be updated if the requirements file changes.
- Avoid adding the infra folder multiple times (in the builder and in the final stage).
- Avoid adding the infra folder in the builder. It's non-reproducible and creates a cache-miss with every build.

optimize docker layers

---

localstack/services/cloudformation/models/ec2.py
tests/integration/templates/template37.yaml
tests/integration/test_cloudformation.py

Subnet Route Table association were limited to one per route table, this will add a check for subnet id.
Similar fix as for route table.

Fix cloudformation not creating multi route table associations

---

localstack/services/s3/s3_utils.py
tests/integration/test_s3.py

also, apply the fix from #3947 to virtual host addressing part
this is deduplication for
- `test_presigned_url_signature_authentication`
- `test_presigned_url_signature_authentication_virtual_host_addressing`
I will address this further with https://github.com/localstack/localstack/issues/4952.
----
Inspired by https://github.com/localstack/localstack/blob/62c495a41b04df323a69cdd7240cbd80df280b34/tests/integration/test_s3.py#L2195-L2195
How I made the comparison:
- unified some variables in both functions
- created two files with content from `run_presigned_url_signature_authentication` and `run_presigned_url_signature_authentication_virtual_host_addressing`
- compared files using `vimdiff`
- extracted common parts into one method
One difference I found: …

s3: merge tests for presigned url signature authentication

---

README.md

Adding the `DISABLE_EVENTS` parameter to the README.

Adding DISABLE_EVENTS to README.md

---

.circleci/config.yml
localstack/cli/localstack.py
localstack/utils/bootstrap.py
localstack/utils/common.py
localstack/utils/docker_utils.py
localstack/utils/kinesis/kinesis_connector.py
localstack/utils/run.py
requirements.txt
tests/bootstrap/__init__.py
tests/bootstrap/test_cli.py
tests/bootstrap/test_localstack_container.py
tests/unit/utils/test_common.py

This PR adds the following CLI commands and the necessary restructuring to make them possible:
*  `localstack start --detached`: starts the localstack container in the background
* `localstack wait` blocks until localstack is running (the ready marker has been printed)
* `localstack logs --follow` tails the log output of localstack
The most noteworthy changes and improvements:
* The most fundamental change is that, in the `start_infra_in_docker` routine, the terminal output no longer comes directly from the `docker run` command itself, but is forwarded to a logfile in the TMP folder that is then tailed using a new uiltity called `FileListener` (that is platform independent, but needs to be tested on Windows). that log is then printed to stdout asynchronously, while waiting on the docker …

restructure localstack container bootstrapping and add CLI commands

---

localstack/services/edge.py

small change that avoids requiring stdin for can_use_sudo

make can_use_sudo use non-interactive mode

---

Dockerfile

With the new Docker image, we implemented a workaround for Kinesis by using `kinesalite` instead of `kinesis-mock` on arm64 (due to #4358).
However, with the native docker image (and with it the native java runtime) the usage of `kinesis-mock` should be fine again.
This PR removes the workaround to use `kinesalite`. By default `kinesis-mock` is then used for all architectures again.

revert from kinesalite (workaround)  back to kinesis-mock for arm64

---

localstack/utils/aws/aws_stack.py
tests/integration/test_s3.py

Related issue: https://github.com/localstack/localstack/issues/4297
The bug was introduced by https://github.com/localstack/localstack/pull/4033
An error was like this (reproduced in the test):
```
tests/unit/utils/test_persistence.py:89: AssertionError
-------------------------------------------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------------------------------------------
ERROR    werkzeug:_internal.py:225 Error on request:
File "/opt/localstack/env/lib/python3.9/site-packages/werkzeug/serving.py", line 319, in run_wsgi
execute(self.server.app)
File "/opt/localstack/env/lib/python3.9/site-packages/werkzeug/serving.py", line 308, in …
```

s3: fix replay for Authorization header from version 2

---

localstack/services/cloudwatch/cloudwatch_starter.py
requirements.txt
tests/integration/test_cloudwatch.py

* bump moto-ext to latest version
* remove obsolete patch for CloudWatch metrics filtering
* fix tests and re-enable commented out assertions

Fix tests and remove obsolete patch for CloudWatch metrics filtering

---

localstack/utils/cloudformation/template_deployer.py
tests/integration/cloudformation/test_cloudformation_apigateway.py
tests/integration/fixtures.py
tests/integration/templates/apigateway-url-output.yaml

API Gateway endpoints generated via CloudFormation are patched to return values compatible with localstack
Example of CDK-generated output for API Gateway v2 uri
```yaml
Outputs:
ApiV2UrlOutput:
Value:
Fn::Join:
- ""
- - https://
- Ref: apigatewayE40D7439
- .execute-api.
- Ref: AWS::Region
- "."
- Ref: AWS::URLSuffix
- /
```

Patch cfn stack outputs for apigateway for localstack compatibility

---

localstack/services/s3/s3_listener.py
localstack/utils/common.py
tests/integration/test_s3.py

The Rust AWS SDK has extra xmlns attributes on child elements that cause localstack to misparse valid bucket notification configurations. I've described the issue more thoroughly here: https://github.com/awslabs/aws-sdk-rust/issues/301
I'm not really sure whose bug this is, to be honest. On the one hand localstack seems to choke on perfectly valid XML; on the other hand, sticking an `xmlns` attribute on every single element, like the Rust SDK does, is pretty weird. 
In any case, this PR fixes the issue on localstack's side, if that's deemed the right approach.

Strip extra xmlns attributes in PutBucketNotification requests

---

localstack/utils/bootstrap.py
tests/bootstrap/test_cli.py

this PR fixes the issue that custom flags were not added correctly to the list of additional flags. adds a bootstrap test to verify that the container has the exposed ports (we should write more like these!)

fix docker flags parsing in configure_container

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

Related issue: https://github.com/localstack/localstack/issues/4398
The `test_cors_with_single_origin_error` test against AWS:
```sh
$ TEST_TARGET=AWS_CLOUD pytest -vs -k test_cors_with_single_origin_error
============================================================================================================= test session starts ==============================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.4, py-1.11.0, pluggy-0.13.1 -- /opt/localstack/env/bin/python3
cachedir: .pytest_cache
rootdir: /opt/localstack/localstack
plugins: httpserver-1.0.2, rerunfailures-10.0
collected 1054 items / 1053 deselected / 1 selected
tests/integration/test_s3.py::test_cors_with_single_origin_error PASSED
```
Console log: …

s3: handle OPTIONS request with "Access-Control-Request-Method" properly

---

tests/integration/test_s3.py

Skip replay tests introduced by #4985 for `Pro` integration tests, as we skip `replay` in `Pro` because of the different implementation of persistency.
Because of these lines in `localstack-ext`: https://github.com/localstack/localstack-ext/blob/833b345a9ecbd0f84bcbba6199d21be0cc34e7c6/localstack_ext/utils/persistence.py#L146-L148
We get this error
```
resp = persistence.replay_command(payload)
>       assert resp.status_code == 200
E       AttributeError: 'NoneType' object has no attribute 'status_code'
```
Failed runs:
- https://github.com/localstack/localstack/runs/4290802930?check_suite_focus=true

s3: fix replay tests for CI

---

localstack/services/s3/s3_listener.py
tests/integration/test_s3.py

Followup for #4994
Also, add additional checks in the related test. I should add these checks in the original PR (related comment as well: https://github.com/localstack/localstack/pull/2565/files#r446286581)

s3: explicitly handle OPTIONS request with "Access-Control-Request-Method" header 

---

localstack/services/sns/sns_listener.py
tests/integration/test_logs.py
tests/integration/test_sns.py

Simple implementation of the [SNS delivery logs ](https://aws.amazon.com/premiumsupport/knowledge-center/monitor-sns-texts-cloudwatch/) requested in the issue #4036. 
Changes:
- Every time a message is being sent, a log in the CloudWatch service is created.
- Creation of a test for the creation of the LogGroup for the topic.
NOTES:
1.  The logs created are most approximate for the http/https and sms protocols.
2.  In contrary to AWS, the user doesn't need to create an IAM rol neither to set attributes for the topic for the logs to be created.

Feature: SNS delivery logs

---

Makefile
bin/docker-entrypoint.sh
localstack/cli/localstack.py
localstack/plugins.py
localstack/runtime/hooks.py
localstack/services/infra.py
localstack/services/install.py
localstack/utils/bootstrap.py
localstack/utils/docker_utils.py

This PR replaces the old plugin loading mechanism methods `load_plugins` and `register_localstack_plugins`, with the new plugin-based hook system.
* Add the `hook_spec` and `HookManager` concepts built around [function plugins](https://github.com/localstack/localstack-plugin-loader/#functions-as-plugins) (into a new `runtime` module in preparation for more infra -> runtime refactoring)
* Add four types of hooks (can be extended in the future for more fine-grained control over the startup proceedure)
* `configure_localstack_container` gets handed the `LocalstackContainer` object to add port mappings, volume binds, ... or anything else to the container that's about to run localstack
* `install` called in `install.py::install_components` that is called when the infra is started, or …

add plugin-based hooks for bootstrapping and infra startup

---

localstack/services/kinesis/kinesis_starter.py
localstack/services/stepfunctions/stepfunctions_starter.py

Restarting 
This PR prevents kinesis or stepfunctions from throwing an exception on restart when not eagerly loaded.

implement check before restarting kinesis and stepfunction

---

bin/docker-entrypoint.sh
localstack/config.py
localstack/constants.py
localstack/contrib/thundra.py
localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/services/cloudformation/deployment_utils.py
localstack/services/dynamodb/server.py
localstack/services/es/cluster.py
localstack/services/events/events_listener.py
localstack/services/generic_proxy.py
localstack/services/infra.py
localstack/services/install.py
localstack/services/kinesis/kinesis_starter.py
localstack/services/kms/kms_starter.py
localstack/services/ses/ses_starter.py
localstack/services/sqs/elasticmq.py
localstack/utils/analytics/event_publisher.py
localstack/utils/analytics/metadata.py
localstack/utils/bootstrap.py
localstack/utils/docker_utils.py
localstack/utils/persistence.py
tests/bootstrap/test_cli.py
tests/integration/test_ses.py
tests/unit/cli/test_lpm.py
tests/unit/utils/test_persistence.py

this PR introduces a `Directories` object within the config that holds the localstack directories that we defined as follows:
* `infra`:  static infra (pre-seeded packages)
* `var`: variable data (shared between host and container that should persist between reboots, e.g., lazy-loaded packages, ssl cert, decryption key, ...) -> changes semantic to "static" in offline image
* `shared_tmp`: shared temp folder (shared between host and container, for things like temp lambda code files. needs to be available to e.g., lambda containers)
* `tmp`: temp folder (ephemeral data, can be mounted from the host, but doesn't have to be)
* `data`: data dir (has to be persistent on the host, shared with the container)
* `config`: ~/.localstack/ (host configuration directory with, for, e.g., pre-configured …

add Directories config object

---

localstack/cli/localstack.py
localstack/config.py
tests/unit/cli/test_cli.py

Adds a CLI command that lets you output the configuration variables given the current environment. this will be useful to debug custom configurations lying around in `~/.localstack/config.env`. part of #5014
supports different output formats (table (left), plain (right), dict, json)

add cli command to show current config

---

localstack/cli/localstack.py
localstack/config.py
localstack/utils/bootstrap.py
requirements.txt
tests/unit/test_config.py

This PR adds the `~/.localstack` config directory and introduces configuration profiles. A profile is a set of environment variables stored in an `.env` file in the localstack config directory.
```
% tree ~/.localstack 
/home/thomas/.localstack
├── default.env
├── dev.env
└── pro.env
```
for example:
```
% cat ~/.localstack/dev.env
DEBUG=1
DEVELOP=1
```
you can load a profile by either setting the env variable `CONFIG_PROFILE=<profile>` or the `--profile=<profile>` CLI flag when using the CLI.
For example `python -m localstack.cli.main --profile=dev start --host` will load the `dev.env` profile file if it exist.
behavior:
* if no profile is specified, the `default.env` is loaded (if it exists)
* explicitly defined environment variables will always overwrite the profile. 
you can use …

add .localstack config directory and config profiles

---

localstack/services/sqs/sqs_starter.py
localstack/utils/patch.py
tests/unit/utils/test_patch.py

This PR adds a patch utility module that could potentially clean up some code that does monkey patching.
The typical pattern is:
```python
def patch_dothings():
return orig()
orig = mymodule.dothings
mymodule.dothings = patch_dothings
```
this can now be replaced with
```python
@patch(mymodule.dothings)
def patch_dothings(orig):
return orig()
```
or 
```python
def patch_dothings(orig):
return orig()
Patch.function(mymodule.dothings, patch_dothings).apply()
```
class functions/methods can also be patched!
i also changed the `sqs_starter.py` to use the patch utility to try it out.

add patch utility

---

localstack/services/awslambda/lambda_executors.py

When setting the `LAMBDA_CONTAINER_REGISTRY` environment variable in order to use [arm64 compatible lambda images](https://github.com/mLupine/docker-lambda) if using node 14.x as your lambda runtime it is not possible to use the custom endpoint as it is overridden by the temporary fix to use `localstack/lambda-js`.
This change ensures that the temporary fix images are only used when a custom registry is not provided.

Fix: only use hard-coded custom docker images when a custom registry is not provided

---

localstack/config.py

This PR replaces the lookup of /etc/hostname with the `socket.gethostname()` method.
Also, a check is introduced if a hostname is detected (in case it might be empty).
One could argue for `platform.node()` instead of `socket.gethostname()` since it caches its value, but the safer option in my opinion is `socker.gethostname()` if, for some reason, the hostname would change (also it is not called that often so performance is critical).
Fixes #5028

Get hostname by using gethostname() method instead of reading /etc/hostname

---

localstack/utils/testutil.py

Due to the bug fixed by this PR http://git.savannah.gnu.org/gitweb/?p=coreutils.git;a=commitdiff;h=v8.24-111-g1118f32
this log message can appear if tail is executed in the context of lambda execution.
This PR filters that message, until we can update the tail command in the lambda docker images.

Filter warnings about tail unrecognized file system from test logs

---

.circleci/config.yml
localstack/services/install.py
tests/integration/test_lambda.py

Currently, the Java Lambda integration tests download an external jar file which is then used to run tests within the Java lambda runtime. Previously, the jar file was downloaded on demand in the setup class of the test. This causes problems when you want to run the tests in a network restricted environment.
This PR moves the installation of the test-jar to the `install.py` where it is installed with the `make init-testlibs` call (just like the kinesis client).

download test-jar for Lambda integration tests with `make init-testlibs`

---

localstack/config.py
localstack/services/generic_proxy.py
localstack/services/install.py

This allows us to redirect the var libs folder to static libs if we want to prevent an override by a host mount.
Therefore, this variable should ONLY be set inside the container and only be referenced in this context.

Allow redirection of var libs to static libs inside the container / move dependencies to correct folders

---

localstack/services/edge.py
tests/integration/test_api_gateway.py

Reported here: https://github.com/localstack/localstack/issues/5041
By intention, updating the existing test without refactoring it to `pytest`, I think refactoring to `pytest` could be done in separate PR.

fix forwarding API Gateway invocation URLs when Signature param passed

---

localstack/utils/common.py
tests/unit/test_misc.py
tests/unit/utils/test_common.py

* Add timeout parameter to `download(..)` util function. Preparation to make the startup more resilient to timeouts (e.g., SSL cert).
* Also contains some minor refactoring/fixes for old tests

Add timeout parameter to download(..) util function

---

localstack/services/awslambda/lambda_api.py
localstack/services/events/events_listener.py
localstack/services/logs/logs_listener.py
localstack/utils/testutil.py
tests/integration/test_events.py

* minor refactoring of EventBridge utils
* pull out `list_all_log_events()` util to make it reusable from other places
* fix location of `EVENTS_TMP_DIR` (was previously writing to CWD, instead of /tmp)

Minor refactoring of EventBridge utils, fix location of EVENTS_TMP_DIR

---

localstack/services/edge.py
localstack/services/es/cluster.py
localstack/services/generic_proxy.py
localstack/services/infra.py

Add flag to check port availability in `start_proxy_server(..)` to avoid test flakes.
Attempt to fix `test_download_with_timeout()` which recently started flaking. The test starts up a proxy server with a download listener, and we need to wait for the port to be available before making HTTP requests. This should also be useful for other tests that are using `start_proxy_server()` to start up a temporary server.
Using the default value `check_port=True` primarily for use in our tests. Explicitly setting `check_port=False` in `edge.py`/`infra.py` to preserve the existing logic of health/port checks in the service startups (and avoid introducing additional startup delay).

Add flag to check port availability in start_proxy_server(..) to avoid test flakes

---

localstack/services/events/events_listener.py
localstack/services/events/events_starter.py

Clean up obsolete patches for event_rules in EventBridge API. Logic for event rules CRUD operations already covered upstream in `moto`.

Clean up obsolete patches for event_rules in EventBridge API

---

MANIFEST.in
localstack/services/events/events_listener.py
localstack/services/events/events_starter.py
localstack/services/providers.py
localstack/services/route53/route53_starter.py
requirements.txt
tests/integration/test_route53.py

* add initial integration of Route53Resolver API and simple smoke test. Partially addresses #5048 . More features will follow soon. /cc @macnev2013 
* add minor fix and error handling in `_dump_events_to_files()` util function
* cleanup obsolete/unused MANIFEST entries
* migrate Route53 tests from `unittest`->`pytest`

Add initial integration of Route53Resolver API

---

localstack/services/install.py
localstack/utils/bootstrap.py

Add SIGINT signal handler to enable clean shutdown across MacOS/Linux. (See details in the code comment.)
Addresses #5069
Tested under MacOS using:
* `localstack start` -> `kill -INT <pid>`
* `localstack start` -> CTRL-C
* `npm run localstack` -> `kill -INT <pid>`
* `npm run localstack` -> CTRL-C

Add SIGINT signal handler to enable clean shutdown across different operating systems

---

.github/renovate.json

This PR adjusts the config of RenovateBot such that the PR titles are more aligned with our usual structure.
A PR title (and also the commit) would afterwards look like this:
"update Docker base image (python:3.8.12-slim-buster) digest to 95db858"
This change was tested in a personal repo: https://github.com/alexrashed/renovate-tests/pull/2
After this PR is merged, the changes can be applied to the first PR created by RenovateBot (https://github.com/localstack/localstack/pull/5080) by checking the "retry" checkbox.

adjust renovatebot config to align PR/commit titles

---

localstack/services/apigateway/apigateway_listener.py

Fix: Make lambda requestContext.requestTime return a formatted string

---

requirements.txt

workaround for #5047, see comment here for an explanation: https://github.com/localstack/localstack/issues/5047#issuecomment-986949852

exclude elasticsearch >=7.14.0 client versions for opensearch compatibility

---

localstack/services/cloudwatch/cloudwatch_starter.py
localstack/services/logs/logs_listener.py
tests/integration/fixtures.py
tests/integration/test_logs.py
tests/unit/test_logs.py

Removes filter behavior which isn't in [documented in the official docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html). In the community edition the change in the PR amounts to filters selecting all logs all the time. Proper filtering for the JSON filters will be added to Pro. 
Loosely related to #4826

Publish logs per metric and remove faulty metric filter behavior

---

Makefile
localstack/services/edge.py
localstack/services/events/events_listener.py
localstack/services/generic_proxy.py
localstack/services/messages.py
localstack/services/routing.py
localstack/services/s3/s3_listener.py
localstack/services/ses/ses_listener.py
localstack/services/sqs/sqs_listener.py
localstack/utils/persistence.py
tests/integration/test_edge.py

Refactor handler chain and introduce `MessageModifyingProxyListener` base class to enable updates of requests/responses.
The main use case is to allow us to apply patches to forwarded requests and returned responses (e.g., ARN region replacements). Currently (prior to this change), `ProxyListener.forward_request` only allows us to return `requests.Request` or `requests.Response` objects, which result in a `break` in the processing loops and do not allow for cumulative handler updates in the handler chain. 
* introduce `MessageModifyingProxyListener` base class to enable updates of requests/responses
* update the order in which DEFAULT_LISTENERS are applied - running _before_ main proxy listener for inbound requests, and _after_ main proxy listener for outbound …

Refactor handler chain and add MessageModifyingProxyListener to enable updates of requests/responses

---

tests/integration/test_logs.py

Fixing `red` pipeline
Failing CI runs:
- https://github.com/localstack/localstack/runs/4463072505?check_suite_focus=true
- https://github.com/localstack/localstack/runs/4468215486?check_suite_focus=true

skip "TestCloudWatchLogs.test_metric_filters" failing against pro

---

tests/conftest.py
tests/integration/docker_utils/test_docker.py
tests/integration/lambdas/lambda_integration.py
tests/integration/test_elasticsearch.py
tests/integration/test_kinesis.py
tests/integration/test_lambda.py
tests/integration/test_s3.py
tests/integration/test_serverless.py
tests/integration/test_terraform.py
tests/unit/aws/test_scaffold.py
tests/unit/cli/test_cli.py
tests/unit/cli/test_lpm.py
tests/unit/services/es/test_cluster_manager.py
tests/unit/test_lambda.py

This PR adds a new pytest flag `--offline` ([according to the official pytest docs](https://docs.pytest.org/en/latest/example/simple.html#control-skipping-of-tests-according-to-command-line-option)). This flag indicates that the tests are executed in a network-restricted environment.
Since some of the tests explicitly download additional infrastructure, or communicate to external services via the host network, some tests have been marked with `@pytest.mark.skip_offline`. These tests are skipped in case the `--offline` option is set when executing the tests with pytest.

add "--offline" pytest flag, skip "online-only" tests, fix some tests

---

localstack/services/sns/sns_listener.py
tests/integration/fixtures.py
tests/integration/test_sns.py

Currently, empty SNS messages are permitted, this diverges from AWS behavior.
This PR introduces a check if the message is empty, and adds a test to check if an empty message is successfully rejected.
Also a TODO was acted upon to add a sns_create_topic fixture to create multiple topics if necessary.
Test also passes against AWS.
Fixes #5096

Reject empty SNS messages

---

localstack/services/kms/kms_listener.py
tests/integration/test_kms.py

This PR addresses #5046 where is described that Terraform gets stuck while creating a KMS Key with KeyUsage=SIGN_VERIFY.
Moto returns a status code 400 when trying to describe this type of key due to Localstack directly handling them.
Changes:
- The creation of this type of key returns a more complete response.
- Before returning a 400 response for the "describeKey" action, the Proxy searches for the keyId in the key_pairs dictionary.
- Add the key_pairs objects to the response when listing the keys. 
- The kms proxy allows local-kms to handle SIGN_VERIFY keys.
- Added tests for listing and describing SIGN_VERIFY keys .

Listing of sign keys

---

localstack/services/cloudformation/models/ec2.py
tests/integration/templates/template28.yaml
tests/integration/test_cloudformation.py

Fix CloudFormation updates for `EC2::Instance` with empty SecurityGroups property.
Addresses #4528
Verified that the test fails prior to this change, and now passes.

Fix CloudFormation updates for EC2::Instance with empty SecurityGroups property

---

localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_utils.py
localstack/utils/testutil.py

Minor refactoring of Lambda API for better extensibility. Introduces a `store_and_get_lambda_code_archive(..)` function which is the central entry point to store the Lambda archive locally. 
Also adds a few type hints and moves a few util functions to `lambda_utils.py`- otherwise, no functional changes besides the code refactoring.

Minor refactoring of Lambda API for better extensibility

---

localstack/services/s3/s3_utils.py
tests/integration/test_sqs.py

There’s no need to calculate the length of an iterable to fetch the last element of the iterable. We can provide a negative index `-1` to it directly to get the last element. In this way, we don't have to iterate over the sequence using `len` to get the last index when our purpose is only to get the last element.

perf: Use negative index `-1` to get the last element of the sequence

---

localstack/config.py
localstack/services/awslambda/lambda_utils.py
localstack/utils/docker_utils.py

Followup for my `podman` exploration: #5116
Set of possible fixes required for running `localstack` inside `podman`.
~Still need to find a proper fix for working `LAMBDA_EXECUTOR=docker`, see this conversation: https://github.com/localstack/localstack/pull/5116#discussion_r769509702~
`LAMBDA_EXECUTOR=docker` should work with `podman` as well with the fix for `get_main_endpoint_from_container`

small fixes for the possibility to run localstack inside podman

---

localstack/utils/docker_utils.py
tests/integration/docker_utils/test_docker.py

When inspecting a not-pulled image (like a lambda image on first execution), we currently do not pull the image before inspecting it (for getting current entrypoint, etc.).
This PR adds a flag for this behavior. If `pull` is true, it will automatically pull before if necessary (default), otherwise it will not.
The image will only be pulled if not already existent.

Automatically pull images on image inspection

---

.github/renovate.json

Unfortunately, the (previously working) configuration which limits the python docker base image (digest) updates to patch versions does not seem to work anymore.
This fix disables minor and major updates globally and removes the python-package specific configuration.

fix RenovateBot config by globally disabling minor and major updates

---

localstack/services/internal.py
tests/unit/services/test_internal.py

Just adds the version of the running localstack instance to its /health endpoint
Response for `http://localhost:4566/health`
```json
{
"services": {
"acm": "available",
"apigateway": "available",
"cloudformation": "available",
"cloudwatch": "available",
"config": "available",
"dynamodb": "available",
"dynamodbstreams": "available",
"ec2": "available",
"es": "available",
"events": "available",
"firehose": "available",
"iam": "available",
"kinesis": "available",
"kms": "available",
"lambda": "available",
"logs": "available",
"redshift": "available",
"resource-groups": "available",
"resourcegroupstaggingapi": "available",
"route53": "available",
"route53resolver": "available",
"s3": "available",
"secretsmanager": "available",
"ses": "available",
"sns": "available",
"sqs": "available",
"ssm": …
```

add version to internal health http endpoint

---

localstack/utils/common.py
localstack/utils/run.py

This PR removes the subprocess call to `uname` to find out the platform (which is unnecessary, since we have python `platform.system()`)
i also moved the `is_windows` logic to the run package with the others so it's consistent.

remove uname command for system check for windows compatibility

---

docker-compose.yml

The example `docker-compose.yml` in the root dir of this repo uses the [env variable default syntax of Docker Compose](https://docs.docker.com/compose/environment-variables/#configure-compose-using-environment-variables).
However, a space is added before the closing bracket:
```
SERVICES=${SERVICES- }
```
This means that the default is not an empty string, but a string with a single white-space character.
This can cause issues in certain cases (`os.environ.get("<var>")` returns `True` for a single-whitespace string instead of `False` for an empty string).
This PR changes the default variables in the `docker-compose.yml` such that they are actually empty.

fix single-space env default in docker-compose

---

localstack/services/awslambda/lambda_api.py
localstack/utils/generic/singleton_utils.py

Minor refactoring: Pull out subtypes instance manager into separate `SubtypesInstanceManager` utility class for reusability. This class is now used as base class for `EventSourceListener`, and is also being used elsewhere (in -ext).

Pull out subtypes instance manager into separate util class for reusability

---

.circleci/config.yml
localstack/aws/api/sqs/__init__.py
localstack/services/apigateway/apigateway_listener.py
localstack/services/providers.py
localstack/services/sqs/provider.py
tests/integration/test_edge.py
tests/integration/test_events.py
tests/integration/test_s3.py
tests/integration/test_sqs.py
tests/unit/test_sqs.py

Cleaned up version of #4983 (rebased to current master to remove all the unmerged ASF handler code unrelated to the SQS implementation)
@thrau's contributions;
- initial implementation of the provider
@baermat's contributions:
- implement dead letter queue behaviour via maxReceiveCount
- enable both StandardQueue and FifoQueue behaviour
- implement behaviour according to the tests against the old listener, such as .fifo for fifo queue names, no illegal unicode chars, etc
- add and enhance tests
- add md5 generation for attributes

implement custom sqs provider with ASF

---

localstack/services/plugins.py
localstack/services/sqs/sqs_starter.py

Currently, the condition on line plugins.py:516 does not match the adding-service in line plugins.py:273. Once, as key, the name is added, in the other case, at the assertion if the service is already present, the whole class is the key.
This leads to a possible race condition where two ServiceContainers exist, for the same Service, with different states and different locks, and can lead to multiple starts of a service (as in #5160 with SQS).
This, until now, did not surface since most services can be created multiple time without too-serious issues, but the patch utility decorator introduced in #5024 does not allow this anymore and will fail the whole service (the second service fails, but already replaced the first at this point).
To make startup of sqs clearer, I removed one of the …

Fix race condition where services could startup multiple times

---

localstack/config.py

Fixes #5193 .
Allows the PROVIDER_OVERRIDE variable to be passed to the CLI-started docker container. Also, service names are lowercase and contain dashes, so a mapping is introduced to transform e.g. `PROVIDER_OVERRIDE_RESOURCE_GROUPS` to `resource-groups`.

Allow provider overrides to be passed to docker container

---

localstack/services/sns/sns_listener.py
tests/integration/test_sns.py

Addresses #5132 
Changes:
- SNS Listener avoids subscribing a FIFO Queue to a standard SNS Topic.
- SNS Listener validates that MessageGroupId is set for messages to a FIFO SNS Topic.
- Added a test to confirm the delivery of a message to a FIFO Queue from a FIFO topic.

Correct validations for fifo queues

---

localstack/services/install.py
localstack/services/stepfunctions/stepfunctions_listener.py
localstack/services/stepfunctions/stepfunctions_starter.py
tests/integration/test_stepfunctions.py

- adds an integration test for multiple regions and nested state machine execution (currently needs the new patch in the artifacts repo and only works with PRO enabled until the aspectj support is moved here)
- removes the region patching from the stepfunctions listener since this is now done in the stepfunctions backend

Rework sfn region patching

---

localstack/services/firehose/firehose_api.py
localstack/services/generic_proxy.py
localstack/utils/aws/aws_stack.py
requirements.txt
tests/integration/fixtures.py
tests/integration/test_firehose.py

After the rework in #4866 , it seems like the elasticsearch connector for firehose was not adapted correctly. (it always used the localhost:4571 endpoint instead of the newly introduced ones).
This PR fixes this behavior and introduces a integration test to test kinesis-firehose-elasticsearch integration to prevent future regression.
Also this PR introduces the AllDocuments S3 backup strategy for ElasticSearch destinations, basic functionality tested with the same test. This backup strategy uses the unprocessed (no lambdas etc) records to backup them into S3. This feature should be seen as incomplete, as it might differ from AWS in terms of buffering multiple records into one file etc.
There is also a small change in the UrlMatchingForwarder, since in host mode, the edge proxy can drop …

Fix firehose - ElasticSearch integration, allow S3Backup AllDocuments with ElasticSearchDestination

---

Dockerfile
Makefile

For versions of TimescaleDB > 2.4 a newer version of PostgreSQL is required. To avoid a chained change that would require testing in all the services that use PostgreSQL, I pushed to the latest version of TImescaleDB that is supported in PostgreSQL 11 (our current version).
This PR updates TimescaleDB to version **2.3.1**
1. Pull this branch and run,
```
make docker-build
```
2. Then run the built container with your API key.
```
docker run --rm --name localstack_main -v /tmp/localstack:/tmp/localstack -e SERVICES=timestream -e LOCALSTACK_API_KEY=$LOCALSTACK_API_KEY -p 4566:4566 -e DEBUG=1 localstack/localstack-full
```
3. Run the following commands against timestream, the last command should return the inserted values.
```
awslocal timestream-write create-database --database-name …
```

Update timescaledb to version 2.3.1

---

localstack/config.py
localstack/constants.py
localstack/services/iam/iam_starter.py
localstack/services/sts/sts_starter.py
tests/integration/fixtures.py
tests/integration/test_sts.py

* add ability to customize default IAM/STS user - similar to `TEST_AWS_ACCOUNT_ID`, this now allows to specify `TEST_IAM_USER_ID` and `TEST_IAM_USER_NAME` to customize the default user id/name
* small fix for IAM issue reported in #5196
* refactor config values - trying to group configs by service and into logical units (this is just a first step toward config refactoring, more will follow..)
* migrate to using `@patch` decorator for IAM patches
* convert STS tests from `unittest`->`pytest`
Follow-up items:

Add ability to customize default IAM/STS user

---

localstack/utils/cloudformation/template_deployer.py
tests/integration/cloudformation/test_cloudformation_dynamic_parameters.py
tests/integration/templates/resolve_secretsmanager.yaml
tests/integration/templates/resolve_secretsmanager_full.yaml
tests/integration/templates/resolve_ssm.yaml
tests/integration/templates/resolve_ssm_secure.yaml
tests/integration/templates/resolve_ssm_withversion.yaml

Adds support for dynamic references in CloudFormation such as:
```yaml
Properties:
TopicName: "{{resolve:secretsmanager:mytopicname}}"
```
See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html
Addresses #5195

Support for dynamic references in CloudFormation

---

tests/integration/test_sns.py

This PR is an extension of #5175.
Changes: 
- Addition of a negative test that validates the correct parameters for a Fifo SNS message publication and the FIFO queue subscription.
- Migration of all the tests from the file `/tests/integration/test_sns.py` to the pytest format of assertions.

Addition of a SNS validation negative test and test_sns.py migration

---

localstack/utils/http_utils.py
tests/integration/test_api_gateway.py
tests/unit/utils/test_http_utils.py

This PR fixes https://github.com/localstack/localstack/issues/4532
AWS documentation is not super clear regarding the header casing. For the lambda integration, only some headers are lowercased, for example the headers starting with 'accept'.
This PR leaves headers untouched unless they are "accept" headers.

only lowercase 'accept' headers #4532

---

localstack/services/apigateway/apigateway_listener.py
localstack/utils/http_utils.py
tests/integration/test_api_gateway.py
tests/unit/test_apigateway.py
tests/unit/test_http_utils.py

Fixes https://github.com/localstack/localstack/issues/5125
Using HTTP_PROXY integration using proxy resources should include all sub-resources and query parameters. This PR adds the query parameters to the resolved uri.

fix issue not passing parameters to HTTP integration (#5125)

---

localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/services/awslambda/lambda_utils.py
localstack/utils/common.py
localstack/utils/docker_utils.py
tests/integration/docker_utils/test_docker.py
tests/integration/test_lambda.py

This PR will work towards a automatic docker network detection for lambdas, so `LAMBDA_DOCKER_NETWORK` should only need to be set on very specific edge cases, and not in the normal docker-compose case.
This PR introduces a new behavior:
- per default, Lambda containers will be spawned connected to the same network as LocalStack itself. If there are multiple applicable, it will take the first in the list of `docker container inspect`.
- In host mode, the endpoint detection will fallback to `172.17.0.1`, which is accepted since host mode is not supported. In host mode, lambdas will be spawned as well in host mode with all the disadvantages that brings. Use `LAMBDA_DOCKER_NETWORK=bridge` to force the "old" behavior in host mode (still not officially supported)
- If LocalStack is connected to …

Automatic docker network detection for lambdas

---

localstack/services/apigateway/helpers.py
tests/unit/test_apigateway.py

Fix #5122.
This PR extends the current route matching implementation for cases where there is more than one match for `{proxy+}` resources.

Fix API gateway proxy resources #5122

---

localstack/constants.py
localstack/services/sns/sns_listener.py
localstack/utils/server/proxy_server.py
tests/unit/test_proxy.py

* Add support for gzipped responses in SSL proxy via Accept-Encoding headers
* Minor refactorings: 
* add/restructure type hints in SNSBackend
* remove obsolete `six` imports

Add support for gzipped responses in SSL proxy via Accept-Encoding headers

---

localstack/services/awslambda/lambda_executors.py
localstack/services/awslambda/lambda_utils.py
localstack/services/cloudformation/models/sns.py
tests/integration/cloudformation/test_cloudformation_changesets.py
tests/integration/cloudformation/test_cloudformation_integration.py
tests/integration/cloudformation/utils.py
tests/integration/templates/integration_events_sns_sqs_lambda.yaml

Minor changes to fix CloudFormation deployment of SNS::TopicPolicy (`fetch_state(..)` method currently still missing, which can lead to failed deployments). /cc @dominikschubert

Fix CloudFormation deployment of SNS::TopicPolicy

---

tests/integration/test_sqs.py

Add test case for SQS DLQ chaining - addresses #5225
This currently fails against the default SQS provider (moto), but works against the SQS ASF provider (setting `PROVIDER_OVERRIDE_SQS=asf`). This is great! 🎉  - and yet another reason to make ASF the default provider soon-ish 👍 :)

Add test case for SQS DLQ chaining

---

localstack/services/firehose/firehose_api.py

This PR addresses the issue https://github.com/localstack/localstack/issues/4224 and provides a fix for the edge case of the s3 prefix being empty on s3 upload by the firehose service.

Handling edge case of empty prefix for firehose s3 upload properly

---

.gitignore
localstack/services/install.py
tests/integration/terraform/apigateway.tf
tests/integration/terraform/versions.tf
tests/integration/test_terraform.py

Update Terraform version, AWS provider version, and API Gateway module version in integration tests.
I started looking into this as part of my investigation into https://github.com/localstack/localstack/issues/5197. The root of the issue seems to have been with AWS provider `3.70.0`. Our tests failed to detect this compatibility issue because they are using outdated dependencies.

update versions of terraform, aws provider, and API gateway module

---

localstack/config.py
localstack/services/awslambda/lambda_starter.py
localstack/utils/bootstrap.py

Add config for host path to fix mounting of libs_dir - resolves the `TODO` that's currently in the code. This resolves the current behavior where libs (e.g., Azure specs) are re-downloaded on every `localstack start` (as the `var_libs` volume mount gets removed from the dict and is not being added to `docker run ...` in certain situations).
PR also contains a minor increase in the timeout for the Lambda API (from 5 to 10 secs), to help debug a customer issue.

Add config for host path to fix mounting of libs_dir

---

localstack/aws/proxy.py
localstack/aws/skeleton.py
tests/unit/aws/test_proxy.py

This PR adds code utilities and mechanisms to migrate services to the new ASF as described in #5222 
* adds the `AsfWithFallbackListener` and `AsfWithPersistingFallbackListener` as described in #5222 
* SNS example can be found in the [asf-migration-sns](https://github.com/localstack/localstack/tree/asf-migration-sns) branch in da433bdd8b571e43e67ca214438d4a32f41e85ac. however, this would currently break the pro SNS provider that needs to be updated.

add utilities for migrating services to ASF

---

localstack/services/edge.py
localstack/services/infra.py
localstack/utils/common.py
tests/unit/test_common.py

* minor refactoring in selecting proxy listener in `edge.py` for better extensibility. 
* move `hooks.on_infra_start.run()` to allow startup hooks to patch `do_start_infra` itself (which is currently not working and breaking some features in -ext)
* migrate some tests from `unittest`->`pytest`

Minor refactoring in selecting proxy listener in edge.py for better extensibility

---

localstack/services/apigateway/apigateway_listener.py
localstack/services/apigateway/helpers.py

Fixes https://github.com/localstack/localstack/issues/5226
This PR splits the pattern matching into two loops to force precedence. Another issue found was the call to get the stage, for some reason, the API deployment with terraform doesn't set up a "local" stage. For those cases, we ignore the stage variables.

Match the most specific path

---

localstack/services/edge.py
tests/integration/test_s3.py

This PR addresses issue #5111. Even thought the user found out the solution to the problem, this [documentation](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_anonymous.html) shows that it should be possible to access an S3 bucket or an S3 key with anonymous credentials (only if the policy allows it but i don't think that's necessary) 
Changes:
- Redirect the GET or HEAD requests to S3 if there is an URI.
- Test to assert access to key with anonymous credentials.

Allow use of anonymous credentials to get an S3 object or bucket

---

localstack/runtime/hooks.py
localstack/services/awslambda/lambda_api.py
localstack/services/awslambda/lambda_executors.py
localstack/utils/bootstrap.py
localstack/utils/docker_utils.py
tests/integration/docker_utils/test_docker.py
tests/integration/test_lambda.py

This change allows us to hook into the Lambda execution and perform modifications to the container configuration before execution.
At various points of the code base, it is now possible to hook into the execution if needed, and modify its parameters.
In addition to introducing a ContainerConfiguration and LambdaContainerConfiguration class used for this purpose, there was also some cleanup of leftover logic:
* If LAMBDA_REMOTE_DOCKER was true, multiple copies into the container could take place, potentially slowing down the first invocation unnecessarily.
* Removed leftovers of `six` in lambda code
* Remove logic for using `run` instead of `create` and `start` if `LAMBDA_REMOTE_DOCKER=false`, since this code adds complexity and is basically identical anyway.
* Especially if …

Refactor lambda executors to allow modification of the container execution with hooks

---

localstack/services/cloudformation/models/ec2.py
localstack/services/ec2/ec2_starter.py
localstack/services/logs/logs_listener.py
requirements.txt
tests/integration/test_cloudformation.py
tests/integration/test_ec2.py

Apply fixes for recent upstream moto changes. In particular, the creation of model backends has changed, as well as the logic around default/main associations in route tables [here](https://github.com/spulec/moto/pull/4726). 
Changes were not yet fully verified against AWS, but parity of the EC2 changes has been verified against AWS as  per [this PR comment]([here](https://github.com/spulec/moto/pull/4726)).

Apply fixes for recent upstream moto changes

---

localstack/services/cloudformation/models/ec2.py
localstack/services/events/scheduler.py
localstack/services/iam/iam_starter.py
localstack/utils/patch.py
tests/unit/utils/test_patch.py

Minor fixes in patch for bound methods of class instances. This resolves an issue where patches cannot be re-applied to bound methods as they are reloaded from persistence. 
The change slightly modifies the interface of patched methods (adding `self` as a required parameter), but that is actually a fair assumption for bound methods, which are always executing in the context of a `self` instance. (Still need to verify in which places we need to update the patch targets - so far only spotted `iam_backend_detach_role_policy` and `put_subscription_filter` in this codebase.)

Minor fixes in patch for bound methods of class instances
