- localstack-core/localstack/dns/server.py
To allow us to introduce namespace packages downstream like `localstack.pro.core` or `localstack.pro.aws`, we need to first make `localstack` itself a namespace package.
- With the removal of `localstack/__init__.py`, `localstack` will become an [implicit namespace package](https://packaging.python.org/en/latest/guides/packaging-namespace-packages)
> Make localstack an implicit namespace package

- localstack-core/localstack/utils/container_utils/container_client.py
In my original PR #11095 I forgot to forward the `log_config` from the container configuration to the actual docker create call in the `create_container_from_config` method, I only added it to `run_container_from_config`.
This PR fixes this mistake, but cannot be merged until some adaptions in `-ext` take place, due to a naming conflict in the ECS TaskContainerConfiguration.
* Forward `log_config` parameter in `create_container_from_config` method
> Add missing log_config passing in create_container_from_config method

- localstack-core/localstack/services/cloudformation/provider_utils.py
- localstack-core/localstack/services/events/resource_providers/aws_events_rule.py
- tests/unit/services/cloudformation/test_provider_utils.py
Recently we had a report for another casing mismatch between the definition of the CloudFormation resource properties (as defined in the corresponding resource schema) and the downstream service API. This is quite tedious to hunt down on a case-by-case basis, so I thought I'd introduce a util that takes care of this recursively for the whole request kwargs.
The reported issue specifically affected `AWS::Events::Rule` and  the downstream `Events.PutTargets` API call when using the `AwsVpcConfiguration` key. On the API side this is actually `awsvpcConfiguration` which lead to an exception being raised on the `client.put_targets` call.
- Resource providers now have another util at their disposal. `convert_request_kwargs` can be used to recursively fix issues mapping from the resource …
> Add generic botocore-model-based conversion util for CFn resource providers

- tests/aws/services/es/test_es.py
- tests/aws/services/es/test_es.validation.json
In an effort to have complete information on which tests are validated to be in parity with AWS the es service is still missing.
This PR adds that missing information, with one test working on AWS, one test testing specific localstack functionality and the rest not conforming to AWS (because of a discrepancy in the create_domain endpoint).
Note that the entire test suite is still marked as flaky.
> Add AWS validation information for es service

- localstack-core/localstack/services/stepfunctions/asl/eval/environment.py
- localstack-core/localstack/services/stepfunctions/asl/eval/test_state/environment.py
- localstack-core/localstack/services/stepfunctions/asl/static_analyser/express_static_analyser.py
- localstack-core/localstack/services/stepfunctions/backend/execution.py
- localstack-core/localstack/services/stepfunctions/backend/execution_worker.py
- localstack-core/localstack/services/stepfunctions/backend/test_state/execution.py
- localstack-core/localstack/services/stepfunctions/backend/test_state/execution_worker.py
- localstack-core/localstack/services/stepfunctions/provider.py
- localstack-core/localstack/testing/pytest/stepfunctions/fixtures.py
- localstack-core/localstack/testing/pytest/stepfunctions/utils.py
- localstack-core/localstack/testing/snapshots/transformer_utility.py
- localstack-core/localstack/utils/aws/arns.py
- tests/aws/services/stepfunctions/v2/base/test_base.py
- tests/aws/services/stepfunctions/v2/base/test_base.snapshot.json
- tests/aws/services/stepfunctions/v2/base/test_base.validation.json
- tests/aws/services/stepfunctions/v2/express/test_express_async.py
- tests/aws/services/stepfunctions/v2/express/test_express_async.snapshot.json
- tests/aws/services/stepfunctions/v2/express/test_express_async.validation.json
- tests/aws/services/stepfunctions/v2/express/test_express_sync.py
- tests/aws/services/stepfunctions/v2/express/test_express_sync.snapshot.json
- tests/aws/services/stepfunctions/v2/express/test_express_sync.validation.json
- tests/aws/services/stepfunctions/v2/test_sfn_api.py
- tests/aws/services/stepfunctions/v2/test_sfn_api.snapshot.json
- tests/aws/services/stepfunctions/v2/test_sfn_api.validation.json
- tests/aws/services/stepfunctions/v2/test_sfn_api_express.py
- tests/aws/services/stepfunctions/v2/test_sfn_api_express.snapshot.json
- tests/aws/services/stepfunctions/v2/test_sfn_api_express.validation.json
- tests/aws/services/stepfunctions/v2/test_sfn_api_versioning.py
- tests/aws/services/stepfunctions/v2/test_sfn_api_versioning.snapshot.json
- tests/aws/services/stepfunctions/v2/test_sfn_api_versioning.validation.json
Currently, the StepFunctions v2 provider and interpreter offer no support for [Express Workflows](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-standard-vs-express.html). This PR addresses this by adding base support for Express Workflows.
- Added execution flavour logic to execution components, now STANDARD or EXPRESS
- Added sync execution components: Execution and ExecutionWorker
- Added static analyser to fail state machine creation that includes illegal callbacks or activities
- Added several validation exceptions concerning limitations of Express workflows
- Added support for [StartSyncExecution api action](https://docs.aws.amazon.com/cli/latest/reference/stepfunctions/start-sync-execution.html)
- Added several supporting utils for express testing
- Added base …
> [SFN] Base Support for Express Workflows

- localstack-core/localstack/services/opensearch/versions.py
- tests/aws/cdk_templates/Bookstore/BookstoreStack.json
- tests/aws/scenario/bookstore/test_bookstore.py
- tests/aws/scenario/bookstore/test_bookstore.snapshot.json
- tests/aws/scenario/bookstore/test_bookstore.validation.json
- tests/aws/services/opensearch/test_opensearch.py
- tests/aws/services/opensearch/test_opensearch.snapshot.json
- tests/aws/services/opensearch/test_opensearch.validation.json
The Bookstore tests show flaky behavior, which was supposed to be mitigated by ...
That PR fixed the usage of the cache for OpenSearch installation.
However, it can still lead to issues, because the version used for OpenSearch in the Bookstore test is not the default version and thus needs to be downloaded extra. This might again lead to rate limiting issues.
- This PR upgrades the Bookstore test to use the current default version of OpenSearch (2.11). 
- To facilitate that, it also fixes the responses given by the compatible version check in the new version and skips some of the new keys that are in the response
- For the fix of the version output, two of the opensearch tests were converted to snapshot tests and validated against AWS. This will make changes like these easier in the …
> Upgrade Bookstore test to OpenSearch 2.11 and revalidate

- .github/workflows/tests-pro-integration.yml
- localstack-core/localstack/cli/localstack.py
- localstack-core/localstack/config.py
- localstack-core/localstack/dev/kubernetes/__main__.py
- localstack-core/localstack/dev/run/__main__.py
- localstack-core/localstack/dev/run/configurators.py
- localstack-core/localstack/dev/run/paths.py
- localstack-core/localstack/services/cloudformation/resource_provider.py
- localstack-core/localstack/services/cloudformation/scaffolding/__main__.py
- localstack-core/localstack/services/cloudformation/scaffolding/templates/plugin_template.py.j2
- localstack-core/localstack/services/lambda_/invocation/lambda_models.py
- localstack-core/localstack/state/inspect.py
- localstack-core/localstack/utils/analytics/metadata.py
After migrating `localstack/localstack` to implicit namespace packaging with https://github.com/localstack/localstack/pull/11190, we are now moving towards namespace packages for our Pro code, which comes with some necessary adjustments of any imports from Pro: `localstack_ext` becomes `localstack.pro.core`.
This PR prepares the adjustment of the imports and should be merged as soon as the first dev package with the new namespace packaging in the `localstack_ext` distribution is out.
- Adjusts the imports of `localstack_ext` modules.
> migrate imports from localstack_ext to localstack.pro.core

- localstack-core/localstack/services/resource_groups/resource_providers/aws_resourcegroups_group.py
- tests/aws/services/cloudformation/resources/test_resource_groups.py
- tests/aws/services/cloudformation/resources/test_resource_groups.snapshot.json
- tests/aws/services/cloudformation/resources/test_resource_groups.validation.json
- tests/aws/templates/resource_group_defaults.yml
As mentioned in the issue #11175 the resource provider for AWS::ResourceGroups::Group is supposed to handle a Group definition without a Query if the Type is CLOUDFORMATION_STACK_1_0. 
- Replace auto generation of the Name attribute as it's a required attribute.
- Add default query
- New CFn test that replicates the issue
> fix defaults for ResourceGroups::Group provider

- localstack-core/localstack/dev/run/configurators.py
- localstack-core/localstack/dev/run/paths.py
We noticed a small regression in the `localstack.dev.run` script after the recent changes in localstack-pro. Specifically, the mounting of the pro code was not working, and failing with this message:
```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/dominik/work/localstack/tempytemp/localstack-ext/localstack-pro-core/localstack/pro/core" to rootfs at "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core": mkdir /var/lib/docker/btrfs/subvolumes/2c1e6f4ca78e70ae380670fccfc47cd8cf355be1c962348c2d00e92f29d21701/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro: read-only …
```
> Fix mounting of pro code in localstack.dev.run

- localstack-core/localstack/aws/protocol/parser.py
- tests/aws/services/kinesis/test_kinesis.py
- tests/aws/services/kinesis/test_kinesis.validation.json
- tests/unit/aws/protocol/test_parser.py
> fix: kinesis CBOR blob handling

- .circleci/config.yml
- localstack-core/localstack/services/cloudwatch/provider_v2.py
- localstack-core/localstack/services/providers.py
- tests/aws/services/cloudformation/resources/test_cloudwatch.py
- tests/aws/services/cloudformation/resources/test_cloudwatch.snapshot.json
- tests/aws/services/cloudformation/resources/test_cloudwatch.validation.json
- tests/aws/services/cloudwatch/test_cloudwatch.py
We introduced the cloudwatch v2 provider a few months ago. 
There hasn't been a lot adoption yet, but the new provider was able to resolve some reported issues already. 
Moving forward, the new provider should be the default, so we also get more feedback and can fix potential oversights and issues only in the new provider.
* switch the `default` provider to use v2
* adapt the `old_provider` check for the test-skips
* adapt the circleci config to run the test suite also for v1
* fix some parameters for the composite alarm (revealed by a cloudformation test)
* re-create snapshot for cloudformation test and adapt transformers
* add the state-visitor pattern to v2 provider to fix persistence issue with cloudpods
> Switch default provider for cloudwatch

- localstack-core/localstack/config.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/router.py
We're planning to advertise the new implementation of API Gateway "Next Gen" in the next release.
However, we will need all our implementation of API Gateway (with upstream) to be on the same page, and to not try to register the same routes with different implementations. 
This PR makes sure we override the different versions of APIGW to use the new implementation if the flag is set.
Also sneaked a small refactor we've talked with @cloutierMat in order to be easier to override behavior. 
- update `apigatewayv2` and `apigatewaymanagementapi` to also use `next_gen` if set. 
- small refactor for the endpoint
> force all APIGW providers to use NextGen if main one is set

- pyproject.toml
This PR: https://github.com/localstack/localstack/pull/10890 wrongly sets the default value for `log_cli` to true, as discussed we want to keep ci logs cleaner this is why the decision has been made to set the default value to false, which is fix with the current PR.
> Fix: Set ci logs to default value

- .circleci/config.yml
Now that we have a set of stable feature for the apigw Next Gen and all tests are now green :partying_face: . We are adding a new pipeline for apigw to help ensure we don't introduce any regression as we keep working on new features and extend the work to apigwv2.
PR #11198 enabled all tests and links to run https://app.circleci.com/jobs/github/localstack/localstack/227232 that was executed with the flag enabled.
A new pipeline for circle-ci that sets `PROVIDER_OVERRIDE_APIGATEWAY=next_gen`
> apigw next gen add circle ci pipeline

- localstack-core/localstack/services/apigateway/next_gen/execute_api/context.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/api_key_validation.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_request.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_response.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/method_request.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/parse.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/header_utils.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/http.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/parameters_mapping.py
- tests/unit/services/apigateway/test_handler_api_key_validation.py
- tests/unit/services/apigateway/test_handler_integration_request.py
- tests/unit/services/apigateway/test_handler_method_request.py
- tests/unit/services/apigateway/test_handler_request.py
- tests/unit/services/apigateway/test_parameters_mapping.py
As discussed with @bentsku, to simplify the usage of headers through the invocation, we will only keep the Werzeug headers as part of the context. We were mostly using the `raw_headers` through the handlers anyway, so it makes sense to only keep them in the context.
This is also in preparation to a refactor that will move some of the duplicate code in the integration handlers to the integration request handler.
- `InvocationContext` gets rid of `raw_headers` and `multi_value_headers`. The value of header is what used to be known as `raw_headers`
- `IntegrationRequest` type for `headers` is now a Werkzeug `Headers`
- Various fixes through the handlers to fully support the new types
> Apigw ng refactor headers to werkzeug headers

- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_request.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/http.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/parameters_mapping.py
- localstack-core/localstack/services/lambda_/urlrouter.py
- tests/aws/services/apigateway/test_apigateway_http.py
- tests/aws/services/apigateway/test_apigateway_http.snapshot.json
- tests/aws/services/apigateway/test_apigateway_http.validation.json
- tests/aws/services/apigateway/test_apigateway_lambda.py
- tests/aws/services/apigateway/test_apigateway_lambda.snapshot.json
- tests/aws/services/apigateway/test_apigateway_lambda.validation.json
- tests/aws/services/lambda_/test_lambda.py
- tests/aws/services/lambda_/test_lambda.snapshot.json
- tests/aws/services/lambda_/test_lambda.validation.json
- tests/unit/services/apigateway/test_parameters_mapping.py
~This PR is based on #11227 and #11226.~
As part of the header remapping work, it has been shown by @cloutierMat that `HTTP_PROXY` integration still supported Request Parameters Mappings, which isn't exactly documented.
To properly support this (and also Private API in the future), it made sense to always create an `IntegrationRequest` object to attach to the context so that the PROXY integration can use it: they don't need to render their own URI. 
I've also sneaked a little fix to a bug put into light by our tests: Lambda URL did not support multi value query string parameters. I've simplified the logic there and also wrote a specific test for it. 
- refactor IntegrationRequest handler to always create an IntegrationRequest and attach it to the context
- refactor `AWS_PROXY` and …
> APIGW NG Refactor IntegrationRequest for Proxy Integration

- Dockerfile
- Dockerfile.s3
- Makefile
We recently switched to namespace packages in this repo (with https://github.com/localstack/localstack/pull/11190) as well as in downstream repos, and we are currently trying to upgrade the CLI according to the new import paths with https://github.com/localstack/localstack-cli/pull/27.
During this upgrade, we stumbled upon an issue with the generated `SOURCES.txt` containing an absolute path (which kills the Windows PyInstaller build of the CLI), and could potentially impact Windows users installing the python package with the CLI install.
It turns out that this issue is somehow caused by `plux entrypoints`. More info can be found in https://github.com/localstack/plux/issues/23.
- Temporarily replaces `plux entrypoints` with `setup plugins egg_info` to avoid the absolute path in …
> fix SOURCES.txt by avoiding plux entrypoints command

- localstack-core/localstack/services/events/v1/provider.py
- pyproject.toml
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
This PR bumps moto-ext to 5.0.11.post1
Contains:
- https://github.com/getmoto/moto/pull/7831 (closes https://github.com/localstack/localstack/issues/8985)
> Bump moto-ext to 5.0.11.post1

- localstack-core/localstack/services/ec2/resource_providers/aws_ec2_securitygroup.py
- tests/aws/services/cloudformation/resources/test_ec2.py
- tests/aws/services/cloudformation/resources/test_ec2.snapshot.json
- tests/aws/services/cloudformation/resources/test_ec2.validation.json
- tests/aws/templates/ec2_vpc_securitygroup.yml
As described in AWS documentation:
> When you pass the logical ID of this resource to the intrinsic Ref function, Ref returns the ID of the security group if you specified the VpcId property. Otherwise, it returns the name of the security group. If you omit the VpcId property and need the ID of the VPC, use Fn::GetAtt instead.
[source](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-securitygroup.html#aws-resource-ec2-securitygroup-return-values-ref)
Closes #11120
Implement different behaviour as described in the above quote.
> Fix: CFn security group id

- tests/unit/test_edge.py
One of the unit test modules is a bit flaky sometimes: `test_edge.py`
One of the tests in the module for example [failed in this run](https://app.circleci.com/pipelines/github/localstack/localstack/26926/workflows/6adbf07e-ef0e-4857-aed3-ca7f2fc9e56c/jobs/230023).
I suspect that this is caused by a race condition: The proxy server might not be up when the connection is being established.
This PR tries to fix this by explicitly waiting for the proxy to be up before trying to establish a connection.
- Use `wait_is_up` on proxy server before trying to establish a connection to address potential race condition / flakiness.
> fix flaky test_edge.py by explicitly waiting for proxy

- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/parse.py
- tests/unit/services/apigateway/test_handler_request.py
While implement more changes, I've spotted an issue with the `_user_request_` format style, there was a bad assumption from my side that the stage was before the path, but for some reason the format is very different. 
- fix removing the stage from the path when using `_user_request_` style format
> APIGW NG fix _user_request_ format parsing

- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_response.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/resource_router.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py
- localstack-core/localstack/services/apigateway/next_gen/provider.py
- tests/aws/services/apigateway/test_apigateway_common.py
- tests/aws/services/apigateway/test_apigateway_common.snapshot.json
- tests/aws/services/apigateway/test_apigateway_common.validation.json
- tests/unit/services/apigateway/test_handler_request.py
There was a TODO left regarding the Exception to be raised when we have a routing error. This one of the bad one in APIGW, where it will raise a 403 exception when you're trying to send a request to something you haven't defined. 
From the documentation:
> The gateway response for a missing authentication token error, including the cases when the client attempts to invoke an unsupported API method or resource.
In some raised exceptions, I've also forgot to add log statements to help the user to understand why it is raising an exception.
- implement the `MissingAuthenticationToken` exception when we have a routing exception
- write an AWS validated test
- add missing log statements
> APIGW NG add routing exceptions

- localstack-core/localstack/services/apigateway/next_gen/execute_api/context.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/response_enricher.py
- tests/unit/services/apigateway/test_handler_response_enricher.py
Following #11237 and a last minute change + the new handling for routing with #11251, the default value for `context.integration` was not set. This PR handles the case where we fail early in the chain and the integration is not set yet
- update the default value
- add a unit test to catch the regression
> fix APIGW NG response enricher handler

- localstack-core/localstack/services/lambda_/urlrouter.py
The Lambda URL router typing had a small issue with `kwargs`, where it was using a mapping for it instead of one type (we could also use a `TypedDict` with `Unpack`, see https://typing.readthedocs.io/en/latest/spec/callables.html#unpack-kwargs). 
See also the discussion here: https://github.com/localstack/localstack/pull/11069#discussion_r1650648611 and the related Python PEP484: https://peps.python.org/pep-0484/#arbitrary-argument-lists-and-default-argument-values
- modify the typing used to the `kwargs` argument 
(This is related to https://github.com/localstack/localstack/pull/11245#issuecomment-2244657232)
> fix typing of kwargs for lambda URL router

- tests/aws/services/firehose/test_firehose.py
`test_kinesis_firehose_elasticsearch_s3_backup` was flaky for quite a while.
According to our internal test analytics, in some pipelines this test has a failure rate of ~16 % over the last 30 days.
- Skips `test_kinesis_firehose_elasticsearch_s3_backup` to stabilize the pipeline.
> skip flaky firehose test

- localstack-core/localstack/services/ssm/provider.py
- localstack-core/localstack/utils/aws/arns.py
- tests/aws/services/ssm/test_ssm.py
- tests/aws/services/ssm/test_ssm.snapshot.json
- tests/aws/services/ssm/test_ssm.validation.json
As shown in the issue #11048. The SSM service allows the usage of ARN's as Names in the GetParameter action. 
- Extend the name validation function to detect if it's an ARN and extract the parameter name if it is.
- New AWS validated test that confirms the behavior.
> allow SSM::GetParameter action to use ARNs instead of only names

- localstack-core/localstack/services/dynamodb/provider.py
- localstack-core/localstack/utils/files.py
- tests/aws/services/dynamodb/test_dynamodb.py
In our TTL feature, we use a `Scan` operation to look for the expired keys to be deleted.
An expression with a reserved keyword (e.g., `ttl` might lead to errors).
This issue was raised in #11186.
- Use expression attribute names (see [docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ExpressionAttributeNames.html)) in the `Scan` operation to avoid the mentioned issue.
> fix: ttl with a reserved keyword as attribute

- localstack-core/localstack/testing/testselection/matching.py
Previously, a change in a `conftest.py` file would select all tests with our test selection. 
This PR aims to introduce a new concept to our matcher for the test selection, where we would set the directory where a `conftest.py` is modified: `pytest` will select that folder and run all tests inside of it. 
It is a bit hard to test, I'm currently opening a PR targeting this one, because triggering a pipeline run manually seems to skip the test selection all together, it makes sense. 
Copying the result of the test run:
```
Checking for confirming to opt-in guards
Number of changed files detected: 1
tests/aws/services/apigateway/conftest.py
Number of affected test determined: 2
tests/aws/services/apigateway/
tests/aws/services/stepfunctions/
Writing test selection to …
```
> add new folder Matcher in test selection for conftest.py

- localstack-core/localstack/services/transcribe/provider.py
- tests/aws/conftest.py
- tests/aws/services/transcribe/test_transcribe.py
While running the pipeline to check for the release, `test_transcribe_happy_path` flaked again. It is also marked flaky on CircleCI. 
See failures: 
- https://app.circleci.com/pipelines/github/localstack/localstack/26973/workflows/543f0989-034b-4f92-bfbb-584da606b29b/jobs/230534/tests
- https://app.circleci.com/pipelines/github/localstack/localstack/26997/workflows/4031f23f-ef93-4557-b000-588789e68c6a/jobs/230767
- https://app.circleci.com/pipelines/github/localstack/localstack/26997/workflows/4031f23f-ef93-4557-b000-588789e68c6a/jobs/230769
We're using the same logic as in opensearch tests, where a check in the global AWS `conftest.py` checks if there are any tests in the test collection that would match the test parent (test file or test class), and if there is, we already trigger the …
> fix flaky transcribe tests by pre-downloading dependencies

- localstack-core/localstack/services/cloudwatch/cloudwatch_database_helper.py
- tests/aws/services/cloudwatch/test_cloudwatch.py
- tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json
- tests/aws/services/cloudwatch/test_cloudwatch.validation.json
We had a report stating that issues with the new CloudWatch provider. I was able to reproduce the issue and added a test for it - the issue relates to multiple dimensions.
* Added test
* fixed the logic for multiple dimension selection
> fix cloudwatch get_metric_data for multiple dimensions

- localstack-core/localstack/aws/protocol/op_router.py
- localstack-core/localstack/aws/protocol/routing.py
- localstack-core/localstack/http/router.py
- localstack-core/localstack/services/apigateway/helpers.py
- localstack-core/localstack/services/apigateway/integration.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/parse.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/resource_router.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/router.py
- localstack-core/localstack/services/apigateway/router_asf.py
- localstack-core/localstack/services/edge.py
- tests/aws/services/apigateway/test_apigateway_lambda.py
- tests/aws/services/apigateway/test_apigateway_lambda.snapshot.json
- tests/aws/services/apigateway/test_apigateway_lambda.validation.json
- tests/unit/aws/protocol/test_op_router.py
- tests/unit/http_/test_router.py
- tests/unit/test_apigateway.py
As reported in #11253, our Edge Router had issue with `path` parameter starting with multiple slashes, as it would return a redirect which we shouldn't do. 
This PR introduces a new converter in the default `ROUTER`, which is the one we already use internally for the OP Router for AWS, and also internally for the new generation APIGW. 
This PR introduces the change and uses the new converter for APIGW routes, and fixes the behavior around it, with added integration test cases. 
- migrate the `GreedyPathConverter` to `edge.py` as we need to use it in our default router, and refactor its usages
- add new tests for the router with the greedy path converter
- fix APIGW NG behavior with the new greedy path 
- fix the legacy APIGW, which was a bit more tricky, I'll run tests from upstream as …
> fix APIGW path converter with prepended multiple slashes

- Dockerfile
- Dockerfile.s3
While working on https://github.com/localstack/localstack/pull/11276, I stumbled over some warnings of Docker when building the images (over and over again):
```
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format
```
- Fixes deprecations in our `Dockerfile`s:
- Have the same casing for `FROM` as for `AS`
- Use `ENV <name>=<key>` instead of `ENV <name> <key>`
> fix warnings for Dockerfiles

- localstack-core/localstack/config.py
Lambda won't work in host mode on macOS without setting `LAMBDA_DEV_PORT_EXPOSE=1` (introduced in https://github.com/localstack/localstack/pull/7367), which is a bad developer experience.
So far, we opted for explicit configuration developer documentation [here](https://github.com/localstack/localstack/blob/master/docs/development-environment-setup/README.md#lambda) to unblock developers on macOS in host mode.
Several contributors hit this issue, and it was suggested that we set it by default if we detect LocalStack running in host mode on macOS. The Lambda service owners also discussed this in the last Lambda Service Owner Sync (2024-07-15).
* [Unify helper utils for common operating systems](https://github.com/localstack/localstack/commit/d087e5bd64a9b728173053c10c845deadff78a8e)
* …
> Change default for LAMBDA_DEV_PORT_EXPOSE on macOS in host mode

- localstack-core/localstack/aws/client.py
- tests/aws/services/kinesis/test_kinesis.py
- tests/aws/services/kinesis/test_kinesis.snapshot.json
- tests/aws/services/kinesis/test_kinesis.validation.json
- tests/aws/services/lambda_/functions/common/kinesis_sdkv2/README.md
- tests/aws/services/lambda_/functions/common/kinesis_sdkv2/java17/Makefile
- tests/aws/services/lambda_/functions/common/kinesis_sdkv2/java17/src/build.gradle
- tests/aws/services/lambda_/functions/common/kinesis_sdkv2/java17/src/src/main/java/kinesis/Handler.java
Kinesis is the only service (afaik) which supports CBOR as `Content-Type` as well as `Accept-Type`.
- Support for CBOR was initially added to ASF when Kinesis was migrated to ASF with #6166.
- Unfortunately, AWS Kinesis breaks the CBOR specs when it comes to datetime fields, which was initially addressed with #6791.
- Initially, we thought the spec is just broken when it comes to the serializer / server-side encoding, but it's also for requests being sent. Fixing (or breaking?) the datetime parsing / server-side decoding was implemented in #11071.
- After quite some time, it turned out that the CBOR implementation still causes issues with the AWS Java SDK, which were addressed with #11133.
- This PR implemented a more thorough support for CBOR, but unfortunately added a small regression. …
> fix Kinesis CBOR date encoding for AWS SDK v2

- bin/release-helper.sh
With https://github.com/localstack/localstack/pull/11275 we have seen that the release helper currently does not properly add the `version.py` to the git commits for the release / version increments.
This PR addresses this issue by:
- Setting sane defaults for bash settings in the `release-helper.sh` (`set -euo pipefail`, `shopt -s nullglob`) and for variable default assignments (use `:-` instead of `:` in order to also use defaults for empty but set variables).
- Also explicitly enables `globstar` tto fix the issue that the glob does not detect files in subdirectories properly.
Tested with the following script which basically shows our release workflow:
```bash
make install
unset VERSION_PY
unset VERSION_FILE
unset DEPENDENCY_FILE
bin/release-helper.sh set-ver 0.0.0
pip install -e . …
```
> fix version.py glob after source package move

- localstack-core/localstack/packages/ffmpeg.py
As a follow up to PR: https://github.com/localstack/localstack/pull/11261, we decided to upgrade the `ffmpeg` package version. Currently we use an old release version `4.4.1`, for more information check out: https://www.johnvansickle.com/ffmpeg/old-releases.
Upgrade the package to the latest release: `7.0.1`.
> upgrade ffmpeg to use version 7.0.1

- localstack-core/localstack/services/events/models.py
- localstack-core/localstack/services/events/provider.py
- localstack-core/localstack/services/events/target.py
- localstack-core/localstack/services/events/utils.py
To receive incoming events in their final form (after all transformers have been applied) a new proxy function is introduced in TargetSender. 
This proxy function is patched with the extension EventStduio in this PR: https://github.com/localstack/localstack-extension-event-studio/pull/26
In addition, the PR also introduces event-bus-name as a new field for the Event, required by the extension.
- add proxy_send_event in TargetSender
- add additional field `event-bus-name` to Event
> Feature/EventStudio: patch put events

- localstack-core/localstack/services/apigateway/next_gen/execute_api/helpers.py
Follow up from #10912 and this comment: https://github.com/localstack/localstack/pull/10912#discussion_r1698667973
- use `get_partition` in the ARN construction of the source ARN for an APIGW invocation
> fix ARN construction for APIGW NG get_source_arn

- localstack-core/localstack/services/s3/presigned_url.py
It got reported in our Slack community channel that there was an issue with pre-signed URL and the S3 image. 
This is a regression introduced by #10265, to allow users to use credentials created by LocalStack to pre-signed URL. However, this introduced a dependency on `moto` which the tests did not catch. 
I'm still a bit surprised how it hasn't been caught, but I think our current setup to run the tests inside the docker container might make so that `moto` is installed inside it. At some point we should revisit the setup to have the tests run outside the container and against the built image (almost there!).
Trying to access a pre-signed URL in the S3 image raises the following exception:
```python
localstack-test  | 2024-08-01T14:01:07.994  INFO --- [et.reactor-0] localstack.request.aws …
```
> fix S3 pre-signed issue importing moto in S3 image

- localstack-core/localstack/services/ses/provider.py
- tests/aws/services/ses/test_ses.py
- tests/aws/services/ses/test_ses.snapshot.json
- tests/aws/services/ses/test_ses.validation.json
AWS SES supports a special tag for sent emails that start with the prefix `ses:`. This is despite the character `:` not allowed in standard tag values.
https://docs.aws.amazon.com/ses/latest/dg/monitor-using-event-publishing.html#event-publishing-fine-grained-feedback
This PR implements this special case in LocalStack. The snapshot tests are also updated.
Closes: https://github.com/localstack/localstack/issues/11243
> SES: Add support for feedback campaign tags

- localstack-core/localstack/services/events/event_bus.py
- tests/aws/services/cloudformation/resources/test_secretsmanager.validation.json
- tests/aws/services/events/conftest.py
- tests/aws/templates/secretsmanager_secret_policy.yml
With #10912 we introduced some fixes regarding returning proper ARNs in non-default partitions.
However, some have been missed, uncovered due to recently modified or added tests.
* Use proper partition placeholders in tests or use the correct partition for manually generated ARNs in tests
* Events returns the correct partition in the generated ARN for root account principal ARNs on `put_permission` calls.
More fixes for events and resourcegroups are in getmoto/moto#7913
> Fixes for proper ARN generation / testing

- localstack-core/localstack/services/events/target.py
This PR in EventStudio: https://github.com/localstack/localstack-extension-event-studio/pull/30 additionally collects events before transformers are applied, therefore there is no need to keep the additional field `event-bus-name` for later steps.
- remove the additional field `event-bus-name` before input path or input transformers are applied
> Fix/EventStudio: Remove event bus field before transformers

- localstack-core/localstack/state/core.py
- tests/unit/state/test_core.py
Rework of the `AssetDirectory` to use `pathlib.Path` instead of `str`.
- use `pathlib.Path` to internally represent a path for `AssetDirectory`
> Rework AssetDirectory to use pathlib.Path

- localstack-core/localstack/utils/analytics/metadata.py
- tests/unit/utils/analytics/test_metadata.py
With adding a new edition of LocalStack we need to add its marker to the analytics events
- Generalizes the parsing of markers to give out `xyz` for any `.xyz-version` file in the static libs (`/usr/lib/localstack`)
> Simplify publishing analytics of new LocalStack editions

- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/test_lambda.py
- tests/aws/services/lambda_/test_lambda.snapshot.json
- tests/aws/services/lambda_/test_lambda.validation.json
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_api.validation.json
- This PR is a followup to https://github.com/localstack/localstack/pull/11103 that adds support for including an alias when constructing a custom predictble URL
- Including an existing `alias` in the `Qualifier` parameter when running a [CreateFunctionUrlConfig](https://docs.aws.amazon.com/lambda/latest/api/API_CreateFunctionUrlConfig.html) will create a compound custom URL in the form `<custom-id-value>-<qualifier-or-alias>`.
- Remove comment from previous PR outlining noting to add this functionality.
- Ran all `only_localstack` tests in the `TestLambdaUrl` suite.
- Tested against local instance using `awslocal`.
> Add aliasing support for custom predictable Lambda URLs

- tests/aws/services/lambda_/test_lambda_api.py
- Test case introduced in #11272 is flaky since `RevisionID` values are UUIDs and therefore not suited for comparison.
- Compare the [`LastModified` (in ISO-8601 format) response values](https://docs.aws.amazon.com/lambda/latest/api/API_UpdateFunctionCode.html#lambda-UpdateFunctionCode-response-LastModified) to assert that the second `UpdateFunctionCode` request occurs after the first.
> fix Lambda custom aliased URL flaky test

- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/test_lambda.py
- tests/aws/services/lambda_/test_lambda.snapshot.json
- tests/aws/services/lambda_/test_lambda.validation.json
Records the AWS behaviour when a Lambda URL is created for an aliased version of a Lambda function; and then the alias is deleted post-creation of the URL.
The current behaviour is that the Lambda URL will remain. I believe a parity test for this edge-case is nesessary since the ARN of the function URL still points to the alias.
- Single new test-case added called `test_lambda_url_persists_after_alias_delete` to test the above flow.
> Add test for deleting an alias associated with a Lambda URL

- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/gateway_exception.py
- tests/unit/services/apigateway/test_handler_exception.py
While testing against the real AWS, it seems the `AccessDenied` exception is special, and the `message` field in the default JSON response is capitalized, even though the default template for the `ACCESS_DENIED` GatewayResponse is the same as all others: `{"message":$context.error.messageString}`, so the CRUD layer is once again wrong for the default values. 
- add a special case until we handle the `responseTemplate` where we will override the default value for `AccessDenied `
- add a unit test to prevent regression
> add APIGW NG workaround for AccessDenied exception

- localstack-core/localstack/services/cloudformation/engine/template_deployer.py
- tests/aws/services/cloudformation/test_template_engine.py
- tests/aws/services/cloudformation/test_template_engine.validation.json
- tests/aws/templates/sub_number_type.yml
Whenever we use `!Sub` for `Type: Number` param in cfn templates it fails with the following error message: 
```
DEBUG --- [functhread91] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "lm-test": sequence item 0: expected str instance, int found Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1102, in _run
self.do_apply_changes_in_loop(changes, stack)
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1392, in do_apply_changes_in_loop
should_deploy = self.prepare_should_deploy_change(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> add support for `Number` type param in `!Sub` in cfn templates

- localstack-core/localstack/config.py
- localstack-core/localstack/services/lambda_/invocation/execution_environment.py
- localstack-core/localstack/services/lambda_/invocation/executor_endpoint.py
- localstack-core/localstack/utils/debug_mode.py
- localstack-core/localstack/utils/lambda_debug_mode.py
The debugging of Lambda functions is currently hampered by the need to manually manage or disable execution timeouts, which often do not provide enough time to connect a remote debugger and perform the necessary evaluations. This issue is particularly relevant for services like Lambda and API Gateway. By default, Lambda limits execution to three seconds, though it can be configured for up to 15 minutes, while API Gateway can impose its own timeout on integrations.
To enhance the developer experience when debugging Lambda functions, this pull request (PR) proposes introducing a "Debug Mode." This mode would signal to the system that the deployment is in a debugging phase, allowing any provider to adjust relevant settings, such as timeouts, accordingly. The changes also suggest setting a …
> Lambda DevX, Introducing Lambda Debug Mode

- localstack-core/localstack/services/apigateway/helpers.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/helpers.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/http.py
- localstack-core/localstack/services/apigateway/resource_providers/aws_apigateway_stage.py
- tests/aws/files/openapi.spec.stage-variables.json
- tests/aws/services/apigateway/test_apigateway_import.py
- tests/aws/services/apigateway/test_apigateway_import.snapshot.json
- tests/aws/services/apigateway/test_apigateway_import.validation.json
- tests/aws/services/cloudformation/resources/test_apigateway.py
- tests/aws/services/cloudformation/resources/test_apigateway.snapshot.json
- tests/aws/services/cloudformation/resources/test_apigateway.validation.json
- tests/aws/templates/apigateway_integration_from_s3.yml
As reported by a user, we had an issue with stage variables when declared via CloudFormation. 
Setting a stage variable to be `TestCasing` would save it as `testCasing`. As stage variables are case sensitive, this is quite an issue. 
I've tracked down the issue to be because we would call `keys_to_lower` on the parameters, which would change the casing.
In the meantime, I've added more tests around stage variables and their casing without CFN, and more validation about what the user was encoutering (the stage variable wouldn't be found, which would create an HTTP integration URI to not have a host). 
I've also found a small issue with how we would import OpenAPI/Swagger files for the method used for the integration for HTTP/HTTP_PROXY.
Resources:
- …
> fix APIGW CFN Stage with Stage Variables casing

- localstack-core/localstack/aws/connect.py
- localstack-core/localstack/services/apigateway/integration.py
- localstack-core/localstack/services/apigateway/provider.py
- localstack-core/localstack/services/firehose/provider.py
Until recently, we did not provide a proper region to various clients around LocalStack.
This worked somewhat well, especially with global services like IAM/STS.
However, with the recent advancement in partition support, the proper region has to be provided for those clients as well.
* Provide correct regions for various internal clients
> Provide regions to various inter-service communication clients

- localstack-core/localstack/services/ec2/resource_providers/aws_ec2_keypair.py
- tests/aws/services/cloudformation/resources/test_ec2.py
- tests/aws/services/cloudformation/resources/test_ec2.snapshot.json
- tests/aws/services/cloudformation/resources/test_ec2.validation.json
- tests/aws/templates/ec2_import_keypair.yaml
While exploring EC2 CloudFormation resources (via CDK) I found that when providing `PublicKeyMaterial` that the deployment failed, since this is not a valid parameter to `create_ssh_key`.
In this case, we should use `import_ssh_key`.
* If `PublicKeyMaterial` is present in incoming resource definition, call `import_ssh_key` instead of `create_ssh_key`
* Add test to capture both behaviours
> CFn: support importing existing EC2 SSH keys

- tests/aws/services/apigateway/test_apigateway_import.py
Recently updated test `test_import_with_stage_variables` [broke the multi account pipeline](https://app.circleci.com/pipelines/github/localstack/localstack/27318/workflows/6163beb5-f542-4d1c-836e-7385d6ffe7bc/jobs/234706) because we used a lambda URL function in a non default region which doesn't have certificates. We however need HTTPS by default in the OpenAPI file because AWS does not accept HTTP only requests to lambda URL. 
There was a condition to replace the https scheme by http when running against LocalStack, but I've done a small mistake and did not assign the result 😅 
Anyway, this now works, you can validate the fix by running the same test with `TEST_AWS_REGION_NAME=ap-northeast-1` and see it is fixed.
- assign the result of the `str.replace`
> fix test_import_with_stage_variables for multi account

- localstack-core/localstack/services/cloudformation/resource_provider.py
Follow-up to https://github.com/localstack/localstack/pull/11178
Resource properties are now automatically converted for any boto calls issues through the clients in resource providers are now automatically corrected according to the operation model.
- The internal client factory used when creating resource providers now automatically registers a botocore hook that  performs parameter conversion according to the operation model on all requests.
This PR still keeps the old utils around, so in most cases this is purely a fall back, which at least shouldn't break any existing functionality. Follow-up PRs will handle the refactoring of the util usage & cleaning up the utils.
I've also already tested refactoring the covered utils into NO-OPs. Both Community and -ext need minor adjustments to …
> Automatically convert props in resource provider botocore calls

- localstack-core/localstack/services/lambda_/event_source_listeners/utils.py
- localstack-core/localstack/services/lambda_/event_source_mapping/esm_config_factory.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/dynamodb_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/kinesis_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/sqs_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.validation.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.py
- tests/aws/services/lambda_/functions/kinesis_log.py
A lot of filtering tests are currently failing for ESM v2 because JSON content detection is not implemented. The filtering behavior and content detection heuristics depend on the event source and might differ for ESM and Pipes.
Implement conditional (i.e., only applies of filter contains data) decoding and re-encoding to make filtering tests pass in ESM v2. It's an ugly hack for now 😬 
The decoding and re-encoding is a hacky idea inspired by:
* `localstack-core/localstack/services/lambda_/event_source_listeners/sqs_event_source_listener.py`
* `localstack.services.lambda_.event_source_listeners.kinesis_event_source_listener.KinesisEventSourceListener._filter_records`
DynamoDB doesn't implement any of these hacks because the `dynamodb` data field is just taken "as is": …
> Event filtering JSON detection for ESM v2 and Pipes

- localstack-core/localstack/aws/api/s3/__init__.py
- localstack-core/localstack/aws/spec-patches.json
- localstack-core/localstack/services/s3/models.py
- localstack-core/localstack/services/s3/provider.py
- localstack-core/localstack/services/s3/validation.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/aws/services/s3/test_s3.validation.json
As reported in #11356, we did not support SSE-C for S3. This PR implements it, we still don't encrypt the files locally, but this is irrelevant for the usage, as AWS decrypts objects on the fly, and for now we don't really have a use-case for it.
I've implemented it following the documentation page: https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html
And tried to think of most use-cases, as this is needed for the object-store Rust crate (see https://github.com/apache/arrow-rs/pull/6230) . 
I haven't implemented it for the pre-signed POST yet, this can be done in a follow-up. 
- implement SSE-C parameter validation for `PutObject`, `GetObject`, `HeadObject`, `GetObjectAttributes`, `CopyObject`, `CreateMultipartUpload` and `UploadPart`. 
- add some …
> implement SSE-C encryption for S3

- localstack-core/localstack/services/apigateway/models.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/router.py
- localstack-core/localstack/services/apigateway/next_gen/provider.py
As discussed with @bentsku, we are changing the structure of internals and actives deployment dict in the store. This will facilitate access to the resources when only the api id is known. Notably when entirely deleting a rest api.
Also fixed in this PR. When deleting a rest api, we were not deleting it's deployment from the store, leading to memory leaks.
> Apigw ng refactor deployment store

- localstack-core/localstack/services/sqs/provider.py
- tests/aws/services/sqs/test_sqs.py
- tests/aws/services/sqs/test_sqs.snapshot.json
- tests/aws/services/sqs/test_sqs.validation.json
Handle the case where setting a `RedrivePolicy` attribute to an empty string removes the `RedrivePolicy` from an SQS queue's attribute map. This should be identical to how LocalStack handles an empty `Policy` attribute.
Currently, this behavior is causing Terraform deletions to initially fail. Terraform attempts to remove a queue's `aws_sqs_queue_redrive_policy` resource by setting the `RedrivePolicy` attribute value to an empty string. However, LocalStack was not removing this empty value, leading to the failure.
- Setting an SQS queue's `RedrivePolicy` to an empty string now deletes it from the internal `QueueAttributeMap`
- Added a test for this case at `TestSqsProvider::test_set_empty_redrive_policy`
- Validated with Terraform & CLI against LocalStack and AWS
> Fix SQS handling of empty Redrive Policy attribute

- localstack-core/localstack/services/ec2/resource_providers/aws_ec2_securitygroup.py
- tests/aws/services/cloudformation/resource_providers/ec2/test_ec2.py
- tests/aws/services/cloudformation/resource_providers/ec2/test_ec2.snapshot.json
- tests/aws/services/cloudformation/resource_providers/ec2/test_ec2.validation.json
This PR adds the default tags that CFn adds to a Security group. Fixes #11119.
- tags generation in the Create method of the resource provider
- extended a previous test for security group tags.
> add support for default tags AWS::EC2::SecurityGroup

- localstack-core/localstack/services/sns/provider.py
- localstack-core/localstack/services/sns/resource_providers/aws_sns_topic.py
- tests/aws/services/cloudformation/resources/test_sns.py
- tests/aws/services/cloudformation/resources/test_sns.snapshot.json
- tests/aws/services/cloudformation/resources/test_sns.validation.json
With this PR now an user can define an ArchivePolicy attribute without the stack deployment crashing. Fixes #11289
- Resource provider now converts the dict into a json string as the service requires
-  The service provider now returns the attribute if it exists in the model
- A bit of refactoring in the Create Method op.
- new cdk test
> add support for ArchivePolicy in AWS::SNS::Topic

- .github/workflows/asf-updates.yml
- pyproject.toml
- requirements-base-runtime.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
`botocore` recently performed a minor version bump to `1.35`, and so did the `boto3-stubs`.
It turns out that the upgrade of the exact pin of `boto3-stubs` breaks the ASF update because:
- `boto3-stubs` is explicitly set to `1.35.2` (the latest version as of today):
https://github.com/localstack/localstack/blob/c3cd60f70b49ce0486ca9c9b8b3d7bd270cf61c3/.github/workflows/asf-updates.yml#L79
- Afterwards, we explicitly upgrade the package version in the `requirements-typehint.txt`:
https://github.com/localstack/localstack/blob/c3cd60f70b49ce0486ca9c9b8b3d7bd270cf61c3/.github/workflows/asf-updates.yml#L87C97-L87C106
- This failed in the last attempts:
- https://github.com/localstack/localstack/actions/runs/10447444855
- https://github.com/localstack/localstack/actions/runs/10487561864
``` …
```
> fix ASF upgrades by upgrading botocore pins and dependency locks

- localstack-core/localstack/testing/pytest/container.py
When using `TEST_CONTAINER_MOUNT_SOURCES`, this includes mounting dependencies as well as the sources, which may not be what we want.
Specifically when the host OS is different to the container OS (e.g. macOS host, Linux container) and dependences include compiled code, the container fails to start.
Add a new flag to choose whether we mount dependencies into the container compared to the sources.
> Add new flag for mounting dependencies into the container

- localstack-core/localstack/services/lambda_/packages.py
In the most recent update of the lambda runtime init, we included the latest upstream changes, and updated the go version to version 1.22, which should fix the CVE https://avd.aquasec.com/nvd/2024/cve-2024-24790/ .
For more information see localstack/lambda-runtime-init#35.
* Update lambda runtime init to `v0.1.29`
> Update lambda init binary to v0.1.29-pre

- localstack-core/localstack/services/apigateway/provider.py
- tests/aws/services/apigateway/test_apigateway_api.py
- tests/aws/services/apigateway/test_apigateway_api.snapshot.json
- tests/aws/services/apigateway/test_apigateway_api.validation.json
As reported in our Slack Community channel with https://localstack-community.slack.com/archives/CMAFN2KSP/p1724147479425329, we raised a bad error when using the wrong `httpMethod` with `PutIntegrationResponse`. This PR adds better exception handling for `PutIntegration` and `PutIntegrationResponse`
`api error InternalError: exception while calling apigateway.PutIntegrationResponse: 'dict' object has no attribute 'method_integration'`
- add test for bad resourceId and bad httpMethod for those 2 operations
- improve the exceptions in the provider
> APIGW: add better validation for PutIntegration and PutIntegrationResponse

- localstack-core/localstack/aws/api/s3/__init__.py
- localstack-core/localstack/aws/spec-patches.json
- localstack-core/localstack/services/s3/models.py
- localstack-core/localstack/services/s3/provider.py
- tests/aws/services/s3/test_s3_api.py
- tests/aws/services/s3/test_s3_api.snapshot.json
- tests/aws/services/s3/test_s3_api.validation.json
AWS just [released yesterday Conditional Writes for S3](https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-s3-conditional-writes/), which is a pretty big thing (and nice!)
This PR implements the behavior as documented in https://docs.aws.amazon.com/AmazonS3/latest/userguide/conditional-requests.html and tested with snapshots. 
- implement behavior in PutObject: use the lock to be sure only the first write to succeed and block others, making them raise an exception once they acquire the lock if the object exists
- implement behavior in CompleteMultipartObject: from the documentation it seems that if an object exists when completing you should raise a Precondition error, and if something existed before but got deleted, you need to raise a Conflict. Did that by attaching the original …
> implement IfNoneMatch for PutObject and CompleteMultipartUpload

- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_sqs.py
- localstack-core/localstack/testing/snapshots/transformer_utility.py
- tests/aws/services/stepfunctions/templates/services/services_templates.py
- tests/aws/services/stepfunctions/templates/services/statemachines/sqs_send_msg_attributes.json5
- tests/aws/services/stepfunctions/v2/services/test_sqs_task_service.py
- tests/aws/services/stepfunctions/v2/services/test_sqs_task_service.snapshot.json
- tests/aws/services/stepfunctions/v2/services/test_sqs_task_service.validation.json
- The Step Functions' SQS provider did not fully support the `MessageAttributes` field during a `SendMessage` since the initial implementation used the incorrect field name provided by the AWS docs. 
- This PR fixes the fieldname and adds a parity test to ensure a `MessageAttributes` JSON object and `Md5OfMessageAttributes` hash is correctly returned.
- Raised by https://github.com/localstack/localstack/issues/11109
- Renames `"MessageAttribute" => "MessageAttributes"`
- Normalises field `"MD5OfMessageAttributes" => "Md5OfMessageAttributes"` to ensure PascalCase for SFN output
- Add new stepfunction template for SQS message with attributes
- New parity test `test_send_message_attributes`
- Manually validated the original issue input now passes following these changes …
> Add MessageAttributes to SQS messages when executed via Step Function

- localstack-core/localstack/services/s3/provider.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/aws/services/s3/test_s3.validation.json
As reported in #11389, we did not copy the source object tags when the `TaggingDirective` was set to `COPY` or nothing, which default to `COPY`. 
This was due to a small oversight, we were using the parsed version id to create the tag key, but if you don't specify a version id, you get the current object (top of the stack, the one that was last added). Instead of using the parsed version id, we now use the source object version id directly. 
- use the source object version id to create the object unique key for the tags
- add a new test regarding versioned bucket and tagging directive to confirm the change: it first copy an object without specifying the version id (to get the current one), then does the same against a specific version id which isn't current
_fixes #11389_
> fix CopyObject not copying tag of current object

- localstack-core/localstack/services/cloudwatch/provider.py
CloudWatch has the `/_aws/cloudwatch/metrics/raw` endpoint that returns the raw metrics. It was noticed that the [v1](https://github.com/localstack/localstack/blame/0063912ad5e984692e83e615a7b38021bc15e9c2/localstack-core/localstack/services/cloudwatch/provider.py#L345C9-L370) and [v2](https://github.com/localstack/localstack/blob/0063912ad5e984692e83e615a7b38021bc15e9c2/localstack-core/localstack/services/cloudwatch/cloudwatch_database_helper.py#L424-L454) providers do not have the same API response spec. To be specific, the `account` and `region` fields were missing in the v1 provider.
In order to keep the spec consistent and simplify #11025, this PR adds the missing fields to the v1 provider response.
> CloudWatch: Add missing response fields

- localstack-core/localstack/services/lambda_/api_utils.py
- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/aws/services/lambda_/test_lambda_api.validation.json
Current validation checks for Lambda function names did not account for some invalid regex combinations as well as length limits for `FunctionName` differing between request types. This will add tests ensuring a wider range of invalid `FunctionName` and `Qualfier` combinations are caught.
The Lambda Provider:
- Remove validation checks from `create_function` in favour of `api_utils.get_name_and_qualifier`
- Use improved qualifier validation and better account for invalid qualifier edge-case for `DeleteFunction`
The API utils `api_utils.py`:
- Conduct name validations in the `get_name_and_qualifier` -- which is ubiquitously used across the Lambda provider and should enact these checks.
- Account for operation type when running `validate_function_name` (accounting specifically for …
> Lambda: improve function name and qualifier validation

- localstack-core/localstack/services/cloudwatch/cloudwatch_database_helper.py
- localstack-core/localstack/services/cloudwatch/provider_v2.py
- tests/aws/services/cloudwatch/test_cloudwatch.py
- tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json
- tests/aws/services/cloudwatch/test_cloudwatch.validation.json
When requesting `get-metric-statistics` LocalStack didn't have any checks on the amount of datapoints. 
Therefore, it would accept large queries, e.g. with a timeframe of over a year and a period of 1 second, which would mean that the data is aggregated for each second in that timeframe. 
AWS only accepts up to 1440 datapoints, and raises an error if those are exceeded.
As LocalStack was running queries in a loop, with a lock on the database, it basically made the cloudwatch provider unresponsive for any other requests (as the lock wasn't released).
In this PR we are trying to address two issues:
1) don't allow more than 1440 datapoints in one request (also being in parity with AWS)
2) refactor the database locks that we currently have in place: by keeping sql queries to a limited amount, …
> cloudwatch: check amount of datapoints, refactor database-locks

- localstack-core/localstack/utils/diagnose.py
- tests/unit/utils/test_diagnose.py
Currently, when using the new `LOCALSTACK_AUTH_TOKEN`s instead of `LOCALSTACK_API_KEY`, the diagnostic endpoint will pull the `localstack/localstack` image instead of inspecting the current image, most likely `localstack/localstack-pro`.
To avoid issues like this, we should always inspect the docker image returned when inspecting the own container.
If no docker socket is available, we cannot inspect the image anyway, and if there is, we should be able to check the current container for the image. This way we always match the right image, no matter if an api key or auth token is set.
Note that there is a patch to the `is_api_key_configured` method in `localstack.utils.bootstrap` from -ext, but it is only applied on the host within the CLI, and is therefore ineffective within the container. …
> Use the correct image for diagnostic endpoint

- tests/aws/services/events/test_events.py
- tests/aws/services/events/test_events.snapshot.json
- tests/aws/services/events/test_events.validation.json
Some tests are only relevant for the v1 provider, since they are covered in separate tests or the functionality is not supported in v2 provider. 
They will be removed once the v1 provider is removed.
Some of these tests are not validated and it is not worth the effort to validate them, to clearly indicate that they are not to be validated the marker `localstack_only` with an explanation is added.
> Refactor/Events: add localstack_only test markers for v1 only tests

- localstack-core/localstack/services/cloudformation/engine/template_deployer.py
- localstack-core/localstack/services/cloudformation/resource_provider.py
CDK shows a nice progress indicator when deploying a stack, however our implementation does not do this. This is because we don't emit `*_IN_PROGRESS` events.
https://github.com/user-attachments/assets/beccc4ae-7a7f-4569-80af-7ae0a8814edc
- Emit `*_IN_PROGRESS` events on resource operations
- Move the instanciation of the resource provider to outside the `ResourceProviderExecutor` 
- this was needed because on update we need to provider the physical resource id of the resource, and our handy `extract_physical_resource_id_from_model_with_schema` function requires the schema
_Running a CDK deploy with SQS queue and SSM parameter with artificial sleep for the SQS queue shows the in-progress event_
https://github.com/user-attachments/assets/13b9d3db-929d-4a5e-9f5b-c274b0477560
> CFn: show CDK stack events

- localstack-core/localstack/services/cloudformation/engine/template_deployer.py
With https://github.com/localstack/localstack/pull/11406 we added support for `*_IN_PROGRESS` events however we broke custom resource support in -ext.
The issue is that we perform a custom type mapping in -ext that we do not do in this repository. This means that the tests passed in isolation, but the -ext pipeline broke.
- Map the resource type with `get_resource_type`, which is overridden in -ext to support custom resources
- Trigger a manual -ext pipeline against this branch name
- manual CI run is 🟢 apart from unrelated issue likely caused by our recent code restructuring
> Fix CFn bug when loading custom resources

- localstack-core/localstack/constants.py
- localstack-core/localstack/utils/ssl.py
With recent certificate issues, we need to change to a new endpoint where certificates are served from.
Also, to alleviate load on that endpoint, we should cache it for 24 hours, instead of 6 hours.
* Download certificate from new endpoint
* Increase caching duration for the certificate to 24h
> Modify certificate download URL to new endpoint

- localstack-core/localstack/config.py
- localstack-core/localstack/plugins.py
Manually deleting the cached certificate could be a cumbersome operation for customers.
We should have a way to make this easier.
- Introduce a `REMOVE_SSL_CERT` env var.
- Added a hook that removes the cached certificate at startup.
> env var to delete the cached cert at startup

- localstack-core/localstack/services/kms/models.py
- localstack-core/localstack/services/kms/provider.py
- tests/aws/services/kms/test_kms.py
Localstack can generate a KMS RSA_4096 key and export the public key. This key material can encrypt a payload on the client side using RSA OAEP. However, the KMS decrypt operation fails with the below message even when passing in the key id.
operation error KMS: Decrypt, https response error StatusCode: 400, RequestID: 9f9efecf-6e08-447d-aef0-6c49dff32ed1, InvalidCiphertextException: LocalStack is unable to deserialize the ciphertext blob. Perhaps the blob didn't come from LocalStack
I brought this up as an issue, and @sannya-singal indicated that while this is an expected limitation, it could be changed. It wasn't exactly clear what exactly was on the backlog, I've tried to change it to do what I at least have noticed.
https://github.com/localstack/localstack/issues/11313
Instead of …
> Init KMS support for offline encryption with RSA key

- localstack-core/localstack/config.py
We have seen the OpenAPI validation create issues with snapshot persistence.
With this PR we make the request for validation opt-in (was by default) upon further investigation.
- `OPENAPI_VALIDATE_REQUEST` is now switched off by default.
> make OPENAPI_VALIDATE_REQUEST opt-in

- .circleci/config.yml
- .github/workflows/asf-updates.yml
- .github/workflows/tests-bin.yml
- .github/workflows/tests-s3-image.yml
- bin/docker-helper.sh
- bin/release-helper.sh
- tests/bin/test.docker-helper.bats
- tests/bin/test.release-helper.bats
With the introduction of `setuptools_scm` our helper scripts started to depend on it. First, we added an automatic install of this dependency. However, unknowing users of those scripts might then install those dependencies into their global python environment which they might not want.
Decoupling the installation from the script execution will solve this.
- Change check for installation of setuptools_scm to use `pip show`,  so that both `setuptools-scm` and `setuptools_scm` can be detected (at some version, they switched the naming)
- Display an ERROR when the package is missing instead of quietly installing it in the active environment
- Change the workflows that use the helper script to install the newest versions of `setuptools` and `setuptools-scm` to avoid version incompatibilities.
> Replace auto-install of setuptools_scm with error in helper scripts

- localstack-core/localstack/services/sns/provider.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
- tests/aws/services/sns/test_sns.validation.json
As reported by #11115, we did not take into account the `MessageAttributes` while calculating the max message size. This was a shortcut taken at the time, but we can now properly fix it. The implementation is inspired by SQS as reported in the GitHub issue.
The documentation specifies: https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html
> All parts of the message attribute, including name, type, and value, are included in the message size restriction, which is 256 KB.
I've taken the opportunity to also validate the max message size for `PublishBatch` as well, as it was easy to do so. 
- take into account `MessageAttributes` when calculating the message size following the documentation, and validated the assumption
- add message size validation for `PublishBatch`
- …
> fix SNS Publish and PublishBatch message size calculation and restriction

- localstack-core/localstack/services/s3/provider.py
- localstack-core/localstack/services/s3/utils.py
- tests/aws/services/s3/test_s3_api.py
- tests/aws/services/s3/test_s3_api.snapshot.json
- tests/aws/services/s3/test_s3_api.validation.json
As reported in #11450, the format of our `VersionId` did not closely follow AWS, most importantly we sent an invalid XML character, leading to issue in `DeleteObject`. 
Looking at AWS documentation, AWS is pretty vague about the format, probably to have some leeway in doing changes in the future (I have a vague memory the length changing over time).
> Version IDs are Unicode, UTF-8 encoded, URL-ready, opaque strings that are no more than 1,024 bytes long. The following is an example:
>
> 3sL4kqtJlcpXroDTDmJ+rmSpXd3dIbrHY+MTRCxf3vjVBH40Nr8X8gdRQBpUMLUo
However, the documentation format isn't really right, as it contains the `+` character which actual `VersionId` cannot contain.
I've generated a list of 100 VersionId in AWS to validate my assumptions, see the detail under. …
> fix S3 VersionId format

- localstack-core/localstack/services/acm/provider.py
This PR simplifies (a little) the moto patch we have in the ACM provider concerning the `DescribeCertificate` operation.
Internally, `moto` [uses](https://github.com/getmoto/moto/blob/fb51925d2be3a14d96abc12349be3ad332d18dc1/moto/acm/responses.py#L129-L136) the patched method to implement `ListCerficates`. This response for this operation contains an `InUse` key that `moto` was not returning. 
Therefore, to have the key in LocalStack we were patching the `describe` method to have it landed in `ListCertificates`.
We fixed this in the upstream PR: https://github.com/getmoto/moto/pull/8054
- Simplify `moto` patch.
> Simplify ACM patch

- localstack-core/localstack/services/s3/notifications.py
- localstack-core/localstack/services/s3/provider.py
- tests/aws/services/s3/conftest.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3_api.py
- tests/aws/services/s3/test_s3_list_operations.py
- tests/aws/services/s3/test_s3_notifications_eventbridge.py
- tests/aws/services/s3/test_s3_notifications_eventbridge.snapshot.json
- tests/aws/services/s3/test_s3_notifications_eventbridge.validation.json
- tests/aws/services/s3/test_s3_notifications_sqs.py
- tests/aws/services/s3/test_s3_notifications_sqs.snapshot.json
- tests/aws/services/s3/test_s3_notifications_sqs.validation.json
As reported in #11448, we did not add the `version-id` field in EventBridge S3 notifications, even though we did for other services.
This PR fixes that, and as the request was about bucket versioning, I made sure that we handled correctly `DeleteMarker`. 
(Quick primer on how versioning works in S3 and Delete Markers: https://docs.aws.amazon.com/AmazonS3/latest/userguide/versioning-workflows.html) 
It adds a test for EventBridge and SQS, with a flow adding 2 objects on the same key, then deleting the "top most" key to create a delete marker, then deleting a specific object version.
It then suspend versioning, delete a delete marker to verify behavior, and add a new object on top with a `null` version to check. 
Improved parity along the way for a few fields. 
- implement logic around …
> fix S3 VersionId EventBridge and fix DeleteMarker notification

- localstack-core/localstack/services/cloudwatch/provider_v2.py
- localstack-core/localstack/utils/aws/arns.py
- tests/aws/services/cloudwatch/test_cloudwatch.py
- tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json
- tests/aws/services/cloudwatch/test_cloudwatch.validation.json
Fixes https://github.com/localstack/localstack/issues/11391
The parsing of alarm-names does not work correctly when the alarm-name contains a colon `:` which is apparently a valid name for alarms.
Also checked the same for dashboard-names where this pattern is not allowed. (Only adding the fix for the default provider v2.)
* fixed creation of `AlarmArn` which was the root cause (it would not parse the pattern and instead just return the alarm-name as it contains a colon)
* adapted one testcase to use alarm-name with a colon to make sure this is valid on AWS and passes on LocalStack
* added validation for Dashboard name and added test
> fix parsing issue for cloudwatch alarm names

- localstack-core/localstack/utils/http.py
- localstack-core/localstack/utils/ssl.py
Sometimes the download process is very noisy. In particular it logs every megabyte which could be a lot of log spam for large files.
* Add flag to the `download` function to disable logging debug messages
> Support quiet downloads

- localstack-core/localstack/services/lambda_/api_utils.py
- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/aws/services/lambda_/test_lambda_api.validation.json
This PR aims to fix support for self managed kafka event sources.
Lambda function event source mapping usually has a `EventSourceArn` as a AWS resource arn, but Kafka sources can be [self managed](https://docs.aws.amazon.com/lambda/latest/dg/with-kafka.html) in which case this value is not present in the request. 
- Prevent `KeyError` by removing direct access to the key where necessary
- Added CRUD support for Kafka event source
- Added tests
> lambda fix create self managed event source

- localstack-core/localstack/services/logs/provider.py
- tests/aws/services/logs/test_logs.py
- tests/aws/services/logs/test_logs.snapshot.json
- tests/aws/services/logs/test_logs.validation.json
Fixes https://github.com/localstack/localstack/issues/9226, which returned the wrong error message.
The issue originates in moto, that doesn't provide the correct error message. To avoid another iteration of moto-upgrade, adding a small patch in LocalStack to return the correct exception message.
* added patch for moto
* added test to validate the error message is the same as on AWS
> fix error message if logs-stream doesn't exist

- localstack-core/localstack/packages/terraform.py
PR addresses #11473, specifically:
1) The pinned version in the terraform package is [>2 years old](https://github.com/hashicorp/terraform/releases/tag/v1.1.3)
2) Allowing users to specify the version of terraform they need installed simplifies IaC and helps eliminate skew on the user side of things (i.e. users wouldn't be forced to maintain two sets of terraform files because localstack is locked to `v1.1.3`)
1) Updates the pinned version to the latest non-BSL version of terraform
- note: the current pinned version of terraform (`v1.1.3`) uses the same license as the newly pinned version (`v1.5.7`)
- ref:
- [v1.1.3](https://github.com/hashicorp/terraform/blob/v1.1.3/LICENSE)
- [v1.5.7](https://github.com/hashicorp/terraform/blob/v1.5.7/LICENSE)
- …
> feat: make packaged terraform version user-configurable

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_event_processor.py
- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker_factory.py
- localstack-core/localstack/services/lambda_/event_source_mapping/event_processor.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pipe_utils.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/dynamodb_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/kinesis_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/senders/lambda_sender.py
- tests/aws/services/lambda_/event_source_mapping/conftest.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.validation.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.validation.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.validation.json
- tests/aws/services/lambda_/event_source_mapping/utils.py
Different failure context payloads in ESM and pipes require that we accommodate for both scenarios. This PR makes the context generation an abstract method that classes implementing the `EventsProcessor` interface will have to define.
- Add abstract `generate_event_failure_context` to `EventsProcessor` interface.
- Define `generate_event_failure_context` for ESM, returning a `requestContext` and `responseContext` on failure.
- Add error context field to `BatchFailureError` exception.
- Pass and use error contexts for `requestContext` and `responseContext` generation via `SenderError`, `PartialFailureSenderError`, and `BatchFailureError`.
- Correct timestamp formatting for DynamoDB (without milliseconds) and Kinesis (with miliseconds).
- Added several inline `TODOs` for future …
> ESM-v2: Fix failure destination context difference between ESM and Pipes

- localstack-core/localstack/services/events/target.py
- tests/aws/cdk_templates/EventsTests/stack-events-target-stepfunctions.json
- tests/aws/services/events/test_events_targets.py
- tests/aws/services/events/test_events_targets.validation.json
For some reason the integration between EventsBridge and StepFunctions service was not being used. With this PR the integration is used with certain changes so the execution name of the machine uses the event ID as it happens in AWS.
- Enable integration
- Add Event ID to Execution Name
- New CDK test that asserts the integration. It basically combines EventBridge, StepFunctions and SQS. The test consists on putting an event in to the bus. A rule will execute the state machine with the event as input. And the machine will send the message to an SQS Queue.
> enable integration between EventsBridge and Stepfunctions

- tests/aws/serverless/package.json
- tests/aws/serverless/serverless.yml
- tests/aws/test_serverless.py
- tests/aws/test_serverless.validation.json
This is part of the initiative of removing the `markers.aws.unknown` from the tests.
The `test_serverless.py` is running a few tests using the `serverless` plugin. 
In the future, we should move these tests to the [serverless repo](https://github.com/localstack/serverless-localstack), but we still need to setup a suitable framework, ideally also allowing running snapshot tests (this is out of scope of this PR).
There is one test left that needs fixing `test_apigateway_deployed` where the assertion doesn't hold for AWS. 
* added scripts to the `package.json` to run deployment against AWS
* fixed some definitions in the `serverless.yml`
* bucket-name
* added deletion-policy to make sure the stack is properly cleaned-up
* adapted the test cases to use the proper function/queue/bucket names
* …
> fixup and validate test_serverless.py

- localstack-core/localstack/services/lambda_/event_source_mapping/senders/lambda_sender.py
- The PR to support failure destination contexts introduced a small bug where we incorrectly reference an unbound variable. https://github.com/localstack/localstack/pull/11433
- Remove incorrect + unbound reference to `function_error` in batch error payload
- Remove `executedVersion` from batch error payload
> ESM-v2: Remove reference to unbound variable

- localstack-core/localstack/services/lambda_/event_source_mapping/pipe_loggers/pipe_logger.py
Small rework of `PipesLogger's` message filtering to strip invalid fields from logs. This means we don't have to implement any pipes/esm specific checks when generating and passing around error payloads.
Fields derived from downstream snapshots and [this article](https://aws.amazon.com/blogs/compute/introducing-logging-support-for-amazon-eventbridge-pipes/).
- Uses hardcoded log-fields to filter out irrelevant data from being logged. 
- Backwards compatible changes so shoudn't break anything. Nevertheless, this was tested against pipes suite in pro on my local.
> ESM-v2: Filter irrelevant fields before logging with PipesLogger

- localstack-core/localstack/aws/spec-patches.json
While working on the apigw v2 provider, another update route was discovered that returns `201` instead of `200` as per the specs.
- Updating spec for apigatewayv2 `UpdatedRoute` operation
> APIGW: patch UpdateRoute spec

- localstack-core/localstack/services/lambda_/invocation/lambda_models.py
- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/aws/services/lambda_/test_lambda_api.validation.json
This feature introduces AWS Lambda Recursive Loop Detection APIs into LocalStack, The purpose of this PR is to implement the CRUD layer, specifically the API to configure the feature, without addressing the actual behavior of the loop detection.
* Added support for two key API functions: GetFunctionRecursionConfig and PutFunctionRecursionConfig.
* Updated the Function data model to include the RecursiveLoop attribute.
Parity tests were written to verify the behavior of the newly implemented APIs (GetFunctionRecursionConfig and PutFunctionRecursionConfig).
- [ Implement the actual behavior of Lambda Recursive Loop Detection in a future update. The current PR only covers the CRUD operations. ]
> Feature/lambda: Add recursion get-put API functions

- .github/workflows/marker-report.yml
Fixes: https://github.com/localstack/localstack/pull/11485 
In favor of: https://github.com/localstack/localstack-ext/pull/3441
As proposed by Steffy in the `-ext` PR: This PR tries to fix this issue by explicitly checking for `true` value.
> fixup if-evaluation for 'Create GH issue from template'

- docs/development-environment-setup/README.md
- tests/aws/services/events/test_events_targets.py
We are missing instructions on disabling the DNS server in host mode leading to undocumented errors for new contributors.
* Add instructions on how to disable the DNS server in host mode
* Update and clarify outdated TODO comments about missing EventBridge target tests
> Add DNS server host mode advice

- localstack-core/localstack/aws/handlers/validation.py
- localstack-core/localstack/plugins.py
- tests/unit/aws/handlers/openapi.py
This PR is a small improvement over https://github.com/localstack/localstack/pull/11452.
- Added a plux plugin which is responsible for loading a spec given a certain path;
- The validator can work now on multiple specs. For instance, pro would have its spec and plugin and the validation will be performed against all the specs the plugin manager can find.
> introduce plugins to load openapi specs

- localstack-core/localstack/services/apigateway/next_gen/execute_api/gateway_response.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/gateway_exception.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_response.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py
Fixing leftover APIGW NextGen tasks. Realized special case for `execute-api` style `AWS` integration `uri`, where we don't need to pass an authorization header, as those requests aren't signed by default and would fail with a bad service name. 
Also fixed some error handling related to Lambda, seemingly the `AWS` Lambda integration follows specific rules (as it already does with the `selectionPattern` specific behavior. 
- only add mocked headers if the request targets a service operation
- remove the default exception message for `AuthorizerConfigurationError`
- add specific error handling for `AWS` lambda integration that is very specific to this one integration, not returning the `AccessDeniedError` unlike all other like `dynamodb`, `kinesis` and `sns`
- remove the `asynchronous` logic …
> APIGW NG: fix leftover REST issues

- localstack-core/localstack/services/events/provider.py
- localstack-core/localstack/services/events/target.py
For EventStudio we introduced thread.local based propagation of trace_context, thus the context is not needed in the patched functions anymore.
Furthermore, a copy of a event is sent to target_sender since the same base event can be sent to multiple targets and modification further down the chain can happen. 
Also we handle capturing of transformation steps also inside the extension now, so the proxy_send_event is also no longer needed.
- remove context input to patched methods
- decompose process_events
- add function to process single event from input events
- add proxy to capture event if no rule is attached
- add function to process individual rule
> Feature/Eventstudio/Events: use thread local for trace_context propagation

- docs/development-environment-setup/README.md
PR https://github.com/localstack/localstack/pull/11502 added helpful advice for when developers are asked for their sudo password during startup. This suggests to disable the DNS server with `DNS_ADDRESS=0`. We don't recommend disabling the DNS server where possible, so more context to this statement is required.
* Add sub-item for the advice explaining the context to the advice
* Add a callout indicating that it should not be the standard configuration
> Add more context about disabling DNS server

- localstack-core/localstack/services/cloudformation/resource_provider.py
- tests/aws/services/cloudformation/api/test_nested_stacks.py
- tests/aws/services/cloudformation/api/test_nested_stacks.snapshot.json
- tests/aws/services/cloudformation/api/test_nested_stacks.validation.json
- tests/aws/templates/cfn_failed_nested_stack_child.yml
- tests/aws/templates/cfn_failed_nested_stack_parent.yml
Addresses #10826. The resource_provider class only stores the new model properties if the create operation is successful. This can cause issues where a nested stack reaches a failed status after being in a pending state. The Id property is never stored, and if the delete method is called, the property required for deletion cannot be found.
- Now the resource_provider stores the model properties 
- New aws validated test based on issue triaged.
> fix deletion of failed nested stack in CFn

- Dockerfile
During a CVE scan we noticed these vulnerabilities and this PR attempts to fix them by upgrading the corresponding package (`libexpat1`), used for XML parsing.
- CVE-2024-45490
- CVE-2024-45491
- CVE-2024-45492
Installs the upgraded version of `libexpat1` via `apt-get`. Currently this will resolve to `2.5.0-1+deb12u1` which includes the fix for the above mentioned CVEs.
> Fix libexpat1 CVEs from our debian bookworm base image

- localstack-core/localstack/services/lambda_/packages.py
Update the lambda init version, to be compiled with go 1.22.7, which fixes several HIGH severity CVEs inside the go stdlib.
No other changes done in the init.
* Update lambda runtime init to v0.1.30-pre, compiled with the newest patch version of go 1.22.
> Update lambda init version

- localstack-core/localstack/utils/files.py
I have a use case where I want to create temporary files inside a certain specified directory. This PR tries to extend the files utility functions so that temporary files and dirs can be created inside desired directories.
- Added optional argument `dir` to the `new_tmp_file`, `new_tmp_dir` methods that defaults to `None` so that the default value can take place in that case.
> minor: add ability to create tmp files inside specified dirs

- localstack-core/localstack/openapi.yaml
The end goal of our OpenAPI spec is to generate SDKs from them.
Having `operationIds` and `tags` for each path help generate better code. In particular:
- `operationId` is used for naming the generated functions;
- `tags` are used to organize the code into modules.
- adding `operationId` and `tags` to all paths.
> Add tags and operationId properties to all OpenAPI paths

- localstack-core/localstack/services/ec2/provider.py
- tests/aws/services/ec2/test_ec2.py
- tests/aws/services/ec2/test_ec2.snapshot.json
- tests/aws/services/ec2/test_ec2.validation.json
As reported in #10773, we had an issue since migrating S3 to LocalStack, as moto was directly accessing the bucket in memory to verify its existence.
It needs a fair amount of patching and overriding in the provider, but this seems like the safest bet. 
- add 2 AWS validated tests, one positive and one negative
- implement `CreateFlowLogs` in the provider, and intercepted the request to remove the `s3` destination to avoid patching the whole method in `moto`
- we now remove `s3` in order to pass the validation in `moto`, pre-validate ourselves, and put back the `s3` value after
- we also validate the existence of the bucket, removing subfolders if there are any
_fixes #10773_
> fix EC2 FlowLogs with S3 destination

- localstack-core/localstack/aws/handlers/cors.py
During the implementation of the invoke function feature in the web app, lambda `invoke` call with `"LogType": "Tail"` option was setting a header `x-amz-log-type` causing a CORS error because this header is not in the CORS allowed headers list
This PR adds the `x-amz-log-type` header to the list so the CORS error goes away
> fix(cors): append lambda logs header in the CORS headers list

- localstack-core/localstack/services/apigateway/provider.py
- pyproject.toml
- requirements-basic.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
- tests/aws/services/cloudformation/resources/test_apigateway.snapshot.json
- tests/aws/services/cloudformation/resources/test_apigateway.validation.json
This PR bumps moto-ext to 5.0.15.post2
Contains:
- https://github.com/getmoto/moto/pull/8086 (closes https://github.com/localstack/localstack/issues/11445)
- https://github.com/getmoto/moto/pull/8142
> Bump moto-ext to 5.0.15.post2

- localstack-core/localstack/aws/handlers/cors.py
- localstack-core/localstack/services/apigateway/helpers.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/parse.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/router.py
- tests/aws/services/apigateway/apigateway_fixtures.py
- tests/aws/services/apigateway/test_apigateway_basic.py
- tests/unit/services/apigateway/test_handler_request.py
In LocalStack API Gateway, we currently have a specific path-style format to call `execute-api`: `http(s)://<your-domain>:<port>/restapis/<api_id>/<stage>/_user_request_/<your-path>`.
The actual AWS format is this, with the host: `http(s)://<api-id>.execute-api.<domain>/<stage>/<your-path>`
There are multiple problems with our current "path style" format:
- it has `restapis` in the name but is shared with HTTP and WebSockets API in APIGW v2
- for HTTP APIs, <stage> can be optional. That format does not work with that case
- there is the custom _user_request_ between  <stage> and <your-path> , which looks weird and necessitate to re-organize the parts for the user
This PR introduces a new path format for API Gateway, available with the "Next Gen" provider: …
> APIGW NG: introduce new unified path style

- localstack-core/localstack/services/secretsmanager/provider.py
- tests/aws/services/secretsmanager/test_secretsmanager.py
- tests/aws/services/secretsmanager/test_secretsmanager.snapshot.json
- tests/aws/services/secretsmanager/test_secretsmanager.validation.json
With this PR I am trying to fix the bug mentioned on this issue : https://github.com/localstack/localstack/issues/11319
I have fetched request from different SDK and HTTP Api, it seems the behaviour is return decoded value when requested from SDK. So added the change, to make the SecretBinary decoded all time.
1. Added a test to fetch a secret when the SecretBinary should not be decoded
2. Added a test to fetch secret as http api request, where the SecretBinary should be decoded.
> Fix: Make secret value decoded for specific usecases

- localstack-core/localstack/services/cloudformation/engine/template_deployer.py
- tests/aws/services/cloudformation/api/test_reference_resolving.py
- tests/aws/templates/cfn_ref_unsupported.yml
Addresses #11362. LocalStack already allows the deployment of templates with unsupported resource types. (Check `CFN_IGNORE_UNSUPPORTED_RESOURCE_TYPES` in [docs](https://docs.localstack.cloud/references/configuration/)). With these changes any reference to these types returns a mock value.
- Before raising DependencyNotYetSatisfied the template deployer check if the resource type is supported
- New `only_localstack` test.
> allow reference unsupported cfn resources

- localstack-core/localstack/aws/handlers/validation.py
When [we introduced](https://github.com/localstack/localstack/pull/11025) the validation for the internal endpoints based on the OpenAPI specs, we made sure the correspondent plugins and specs wouldn't be loaded if at least one between `OPENAPI_VALIDATE_REQUEST` or `OPENAPI_VALIDATE_RESPONSE`.
The idea was to avoid this step, when unnecessary.
However, this is an issue if we turn these config variables when the container is already started, and the chain initialized.
In such a case, the calls to the validators fail because the instance variable `open_apis` hasn't been initialized (I came across this while writing some tests).
To support the later activation of the validation at runtime, we slightly reworked the loading logic.
- We use the same old logic when instantiating the validator …
> rework conditional loading of the OAS plugins

- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
- localstack-core/localstack/testing/aws/lambda_utils.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.validation.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.validation.json
This PR enables and tests SNS as a failure destination DLQ in Localstack ESM v2 for Kinesis and DynamoDBStreams events, where AWS event source mapping supports adding either an SQS queue or SNS topic as a failure destination.
See snippet [AWS::Lambda::EventSourceMapping OnFailure docs:](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-eventsourcemapping-onfailure.html)
> To retain records of failed invocations from [Kinesis and DynamoDB event sources](https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventsourcemapping.html#event-source-mapping-destinations), you can configure an Amazon SNS topic or Amazon SQS queue as the destination.
- Allows for an SNS topic ARN to be selected as an `OnFailure.Destination` for `StreamPoller` type pollers …
> ESM-v2: Add SNS as a failure destination for Kinesis and DynamoDB

- tests/aws/templates/apigw-awsintegration-request-parameters.yaml
This PR fixes this issue: https://github.com/localstack/localstack/runs/30611307634
It seems we've had an APIGW test with a CFN template with a hardcoded role name set to `MyRole`, which most probably triggered a resource conflict issue
- remove the role name attribute so that it is auto generated
> fix APIGW test with hardcoded role name in CFN template

- pyproject.toml
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
This PR bumps moto-ext to 5.0.15.post4. This is the final bump ahead of v3.8 release.
Contains:
- https://github.com/getmoto/moto/pull/8163
- https://github.com/getmoto/moto/pull/8167
> Bump moto-ext to 5.0.15.post4

- localstack-core/localstack/aws/handlers/cors.py
After the implementation of https://github.com/localstack/localstack/pull/11577, CORS header was gone from lambda invocation implementation in the web app but a new problem came up where lambda invocation response was not returning full payload. The response should be returning 
```
export interface InvocationResponse {
StatusCode?: Integer;
FunctionError?: String;
LogResult?: String;
Payload?: _Blob;
ExecutedVersion?: Version;
}
```
but it was returning:
```
export interface InvocationResponse {
StatusCode?: Integer;
Payload?: _Blob;
}
```
After some debugging, I found out the data was being returned in the response headers but not in the response. 
This PR adds the required headers to the expose headers list so we get back the full payload.
> fix(cors): append lambda invocation headers in the expose headers list

- localstack-core/localstack/services/apigateway/resource_providers/aws_apigateway_usageplan.py
- localstack-core/localstack/services/lambda_/resource_providers/aws_lambda_codesigningconfig.py
With the previous template deployer implementation (supersceded in #10849) we iterated over the resources, and it was sometimes the case that we could not resolve a `Ref` (or `GetAtt` etc.) because the dependant resource had not been deployed yet.
However, with #10849 we deploy resources in the correct order, so we should not need to handle this case any more.
I added breakpoints in every position we raise a `DependencyNotYetSatisfied` exception, and uncovered the errors fixed in this PR.
* Update `AWS::ApiGateway::UsagePlan` to correctly return the updated state from the `update` method
* Update `AWS::Lambda::CodeSigningConfig` to set the `CodeSigningConfigId` property
Note: this PR is not a complete fix, as we likely don't have test coverage of everything.
Closes #11560
> CFn: fix unresolvable refs

- localstack-core/localstack/aws/protocol/service_router.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/router.py
- tests/aws/services/apigateway/test_apigateway_common.py
Due to legacy code when we didn't have the ASF framework and Edge routes, we would assign the service model for any "data plane" kind of routes (`execute-api`) for APIGW for example. 
Nowadays, if we have a service set in the context, and we did not match an edge route, we will forward the invocation to the skeleton/provider. This can lead to weird issues and confuse users with this kind of error:
```python
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 63, in __call__
return self.parse_and_enrich(context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> remove assigning a ServiceModel for `execute-api` APIGW routes

- tests/integration/test_security.py
Follow up from #11604, I've missed this one as we did not run the CI with the flag applied: 
Here's the failed run: https://app.circleci.com/pipelines/github/localstack/localstack/28439/workflows/ee18ae42-968c-4eda-96bf-fbae9ad40952/jobs/248146/tests
- remove the special check for NextGen and always assert it is `404`
> fix APIGW NG test_cors_apigw_not_applied

- localstack-core/localstack/services/lambda_/resource_providers/aws_lambda_function.py
- tests/aws/services/cloudformation/resources/test_lambda.py
- tests/aws/services/cloudformation/resources/test_lambda.validation.json
- tests/aws/templates/cfn_lambda_with_tags.yml
In #11459 we find that tags are not propagated to lambda functions when deployed via CloudFormation.
This superscedes #11529.
Closes #11459 
* Propagate the tags from the CFn resource payload to the `create_function` call.
* Add integration test capturing this
Note: the test is not a snapshot test because CFn adds default tags which we have to ignore, and the tags contain `:` characters, which the jsonpath-based snapshot library does not cope with.
> CFn: propagate lambda tags to function

- localstack-core/localstack/http/resources/swagger/endpoints.py
With https://github.com/localstack/localstack/pull/11509 we started serving the SwaggerUI within LocalStack.
The Web UI is initialized with an OpenAPI spec, also served via LocalStack. However, the resolved URL always had a `http` protocol. This caused a mix-content issue (see below) when accessing the swagger URL (`localhost.localstack.cloud:4566/_localstack/swagger`) with `https`.
See the image below:
- We now build the spec URL with the correct protocol based on the protocol of the request itself.
> fix: mixed-content for the SwaggerUI

- tests/aws/services/cloudformation/resources/test_lambda.py
- tests/aws/services/cloudformation/resources/test_lambda.snapshot.json
- tests/aws/services/cloudformation/resources/test_lambda.validation.json
PR #11588 implemented tag propagation for Lambda Functions using CFn. The test added was validated, but not snapshot tested because I did not know how to handle the automatic CloudFormation tags when matching snapshots.
A [very useful comment](https://github.com/localstack/localstack/pull/11588#issuecomment-2385454876) pointed out how to achieve this, so this PR upgrades the test to use snapshot validation of the created resource.
Thanks @bentsku!
* Capture the `get_function` response in a snapshot, and correctly skip matching the CFn tags
> CFn: improve lambda tag matching

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_config_factory.py
- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker.py
- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker_factory.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/senders/lambda_sender.py
- localstack-core/localstack/services/lambda_/hooks.py
- localstack-core/localstack/services/lambda_/provider.py
This PR allows for hooks to be defined downstream that can be used for defining an event source mapping. This hooks approach is currently due to the contraints of the factory pattern that `EsmWorkerFactory` and `EsmConfigFactory` currently employ.
- Include `create_event_source_poller` and `set_event_source_config_defaults` pollers for creation of ESM workers and config defined downstream, respectively.
- The base `Poller` class, `EsmWorkerFactory`, and `EsmConfigFactory` now handle when a `source_arn` is not defined.
> ESM-v2: Create hooks for downstream poller creation

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/poller.py
Allows for a `Poller` to optionally close some internal components after the `poll_events` loop has exited.
- Add a no-op `close()` method to the `Poller` base class.
> ESM-v2: Add optional close function to Poller

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker.py
- localstack-core/localstack/services/lambda_/provider.py
This PR aims to add persistence support to Event Source Mapping V2. 
- Add to the Lambda provider's `on_after_state_load` method.
- Poll whether the mapped Lambda is in a ready state (`Active/Failed`). Log a warning if not ready and proceed.
- If ESM is in a disabled/disabling state on re-load, then set the `enabled` flag of the ESM worker to false. Otherwise, create the ESM as normal.
- Left a TODO about polling for a ready event source.
- Downstream persistence tests for Lambda should pass.
> ESM-v2: Add persistence to Lambda event source mapping

- localstack-core/localstack/services/events/target.py
- tests/aws/services/events/test_events_targets.py
- tests/aws/services/events/test_events_targets.snapshot.json
- tests/aws/services/events/test_events_targets.validation.json
- tests/aws/services/lambda_/functions/lambda_echo_json_body.py
This PR introduces basic support for the Amazon EventBridge API Gateway target within LocalStack's new EventBridge v2 implementation. The primary goal is to enable the successful delivery of events from an EventBridge bus to an API Gateway endpoint, ensuring parity with AWS's behavior through comprehensive testing.
- **Implementation of `ApiGatewayTargetSender` Class:**
- Parses the API Gateway ARN to extract `api_id`, `stage_name`, `http_method`, and `resource_path`.
- Dynamically replaces wildcards (`*`) in the resource path with provided `PathParameterValues`, allowing flexible URL construction.
- Constructs the API Gateway endpoint URL using `config.internal_service_url()` and sets the appropriate `Host` header for proper routing within LocalStack.
- Utilizes the Python `requests` …
> Eventbridge apig lambda parity test

- localstack-core/localstack/services/ec2/patches.py
- tests/aws/services/ec2/test_ec2.py
When running:
```bash
awslocal ec2 create-vpc --cidr-block 10.0.0.0/16 --tag-specifications "ResourceType=vpc,Tags=[{Key=_custom_id_,Value=vpc-lsdefault}]"
awslocal ec2 describe-vpcs
awslocal ec2 create-subnet --vpc-id vpc-lsdefault --cidr-block 10.0.0.0/16 --tag-specifications "ResourceType=subnet,Tags=[{Key=_custom_id_,Value=mysubnet}]" 
```
The following error would be returned:
```python
2024-09-05T15:06:51.529  INFO --- [et.reactor-0] localstack.request.aws     : AWS ec2.CreateSubnet => 500 (InternalError)
2024-09-05T15:06:52.721 ERROR --- [et.reactor-0] l.aws.handlers.logging     : exception during call chain
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
handler(self, self.context, …
```
> Fix creating subnet with custom ID for VPC with custom ID throwing 500 internal server error

- .circleci/config.yml
- localstack-core/localstack/config.py
- localstack-core/localstack/deprecations.py
- localstack-core/localstack/services/lambda_/event_source_mapping/esm_config_factory.py
- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker.py
- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/scenario/bookstore/test_bookstore.py
- tests/aws/services/cloudformation/resources/test_lambda.py
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_destinations.py
- tests/aws/services/lambda_/test_lambda_destinations.snapshot.json
- tests/aws/services/lambda_/test_lambda_destinations.validation.json
Depends on ext PR with Kafa poller: https://github.com/localstack/localstack-ext/pull/3486
Lambda ESM v2 comes with many improvements we want to make available to all customers by default.
This prepares the path for the removal of ESM v1 (including some old Lambda v1 code tied to ESM v1) upon v4.0.
* Switch feature flag default to ESM `v2`
* Add deprecation warning for ESM v1
* Switch optional CI to guard against v1 regressions
* Full ext test run (to guard against regressions of Kafka poller and Pipes):
* Before Kafka PR merged v1: https://github.com/localstack/localstack-ext/actions/runs/11142542431
* Before Kafka PR merged v2: https://github.com/localstack/localstack-ext/actions/runs/11145321396
* After Kafka PR merged v3: https://github.com/localstack/localstack-ext/actions/runs/111473 …
> Switch Lambda Event Source Mapping default implementation to v2

- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
- tests/aws/scenario/bookstore/test_bookstore.py
We currently wait 1 extra second after each iteration over all shards, since the poll_events method just returns at the end of the iterator.
Instead, we should just directly restart with the first shard in our shard list, without sleeping another second.
For single shard operations, like dynamodb streams, this effectively doubles the performance, and puts it on par with the old ESM implementation again.
* Improve stream poller performance for lambda ESM v2 (the new default)
> Fix streaming poller performance for low shard counts in ESM v2

- localstack-core/localstack/aws/handlers/validation.py
- localstack-core/localstack/plugins.py
We figured out, from our [CLI smoke tests](https://github.com/localstack/localstack-cli/actions/runs/11163193747/job/31029543533), that having the OAS base plugin in the handler would cause CLI import errors, this one not-installing runtime dependencies (e.g., `rolo`).
- Moving the plugin definition in `plugins.py`.
> Moving OASPlugin definition

- localstack-core/localstack/services/cloudformation/provider.py
- localstack-core/localstack/services/cloudformation/stores.py
- tests/aws/services/cloudformation/api/test_changesets.py
- tests/aws/services/cloudformation/api/test_changesets.validation.json
As reported in https://github.com/localstack/localstack/issues/11333, performing a deployment of a previously deleted stack fails with the error message:
```
InvalidChangeSetStatus: ChangeSet [arn:aws:cloudformation:us-east-1:000000000000:changeSet/cdk-deploy-change-set/87846077] cannot be executed in its current status of [CREATE_COMPLETE]
```
This is because we don't filter out deleted changesets when looking for a changeset, and therefore assume the changeset already exists and incorrectly fail. Also this only happens when specifying changeset _names_, which CDK does.
This PR superscedes https://github.com/localstack/localstack/pull/11384, however @migraf wrote the initial implementation.
Closes #11333
- Fetch only active changesets
- Add validated test that performs the …
> Fix: CFn repeated deployments breaking

- localstack-core/localstack/services/sns/models.py
- localstack-core/localstack/services/sns/provider.py
- localstack-core/localstack/services/sns/publisher.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
- tests/aws/services/sns/test_sns.validation.json
As reported with #11617, we did not properly use the configured Content-Type when sending `Notification` message type. 
I've tried to implement some CRUD validation around `Topic` attributes, but it needs a lot of it, and everything lives in moto. Either we move away from it as most of it is mocked only and implement it in LocalStack, or we need to implement the feature there.
The fix/feature implemented here should be pretty solid, the only issue is that we can accept any format and users might not understand straight away why it doesn't work when the `DeliveryPolicy` they passed would fail when trying to set it, against AWS. 
This page explains it pretty well: https://docs.aws.amazon.com/sns/latest/dg/sns-message-delivery-retries.html#creating-delivery-policy
- for `http` and `https` …
> SNS: implement Content-Type logic for http/https target

- tests/aws/services/events/test_events_targets.py
- tests/aws/services/events/test_events_targets.snapshot.json
- tests/aws/services/events/test_events_targets.validation.json
When running a new test in Events v2 with APIGW NG enabled, I've encountered test failures due to bad replacement in the snapshots (it would replace the `HTTP` value across the whole snapshot string, leading to very weird error in `ResponseMetadata`), see the run here: https://app.circleci.com/pipelines/github/localstack/localstack/28547/workflows/b21fae5b-918f-4356-8a18-51b324914127/jobs/249483
I've refactored the snapshot logic a bit in order to delete less information from it, for us to be able to validate some assumptions in the `requestContext`, and have a clear idea of what is wrong/need to be fixed in the snapshot via the `skip_verify`. 
It showed that `events` will send specific headers to APIGW, like `X-Amz-Source-Arn` and `X-Amz-Source-Account` which might be used by the user's …
> fix Events v2 APIGW target test and update snapshots

- localstack-core/localstack/services/stepfunctions/asl/component/common/catch/catcher_decl.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state.py
- tests/aws/services/stepfunctions/templates/errorhandling/error_handling_templates.py
- tests/aws/services/stepfunctions/templates/errorhandling/statemachines/task_service_lambda_invoke_catch_all_output_path.json5
- tests/aws/services/stepfunctions/v2/error_handling/test_task_service_lambda.py
- tests/aws/services/stepfunctions/v2/error_handling/test_task_service_lambda.snapshot.json
- tests/aws/services/stepfunctions/v2/error_handling/test_task_service_lambda.validation.json
When an error in a state is successfully handled by a catch block, the error object containing the error message and cause string is directly passed as the state's output. This means that if the user defines output reduction logic, such as ResultPath and OutputPath, these are not applied. However, the current implementation of the SFN v2 interpreter mistakenly applies these reductions, which can lead to JsonPath errors and disrupt the state machine's logic, as seen in issue #11494.
These changes type the output handling for successful catch blocks so these can be detected and bypass output reductions.
- Typed CatcherDecl outputs to be CatcherOutput objects
- Add bypass logic in the state's evaluation of the output
- Added relevant snapshot tests which test the use of OutputPath and …
> [SFN] No Output Reductions for Successful Catch Blocks

- localstack-core/localstack/config.py
- localstack-core/localstack/runtime/runtime.py
When loading multiple components in the python path and launching localstack, we currently just select the first component that was found. 
When working in a repository which has multiple exclusive components, however, this means that we need to manually remove one of the components from the python path to specify which component we want to run exactly.
Ideally, in a development environment we'd just want to set some configuration value in a run configuration to select the correct component.
/cc @dfangl 
This PR adds a configuration value to manually select a single runtime components set to start: `RUNTIME_COMPONENTS`
Without setting it, the old behavior remains, i.e., all components are loaded and the first is chosen.
When specifying a value, however, that one gets loaded and chosen.
In …
> Add configuration value for manually selecting runtime components

- localstack-core/localstack/services/cloudformation/engine/template_deployer.py
- Currently CFn will inproperly format account id to int `0` instead of keeping it `000000000000` string
- Removed casting of account_id to int
- Running `cdklocal boostrap` with IAM enabled and then trying to deploy a stack will cause IAM to crash
> Fix: CFn improperly formats account_id causing IAM engine to fail when using cdk

- localstack-core/localstack/services/lambda_/api_utils.py
- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker.py
- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.py
This PR addresses some regressions in ESM v2 parity when compared with ESM v1.
- `UpdateEventSourceMapping` requests now work -- where an update request will re-create a new ESM from scratch and overwrite the previous version with its new state.
- `validate_event_source_mapping` has been extended to include `UpdateEventSourceMapping` requests
The following regressions have been remedied with the new changes:
- `test_event_source_mapping_default_batch_size`
-  `test_sqs_event_source_mapping_update`
ext test runs:
* [95b6b2e](https://github.com/localstack/localstack/pull/11637/commits/95b6b2eb44115a30564f8c6e594648b06231d232) https://github.com/localstack/localstack-ext/actions/runs/11183454628
* [c3265f8](https://github.com/localstack/localstack/pull/11637/commits/c3265f87db3c1fd9a3aa7007a6 …
> ESMv2: Fix UpdateEventSourceMapping request and batch size check for SQS

- localstack-core/localstack/aws/connect.py
We have the need for a boto client that bypasses the LocalStack DNS server. This client needs to be able to reach out to AWS (given valid user credentials).
* Add new `ExternalBypassDnsClientFactory` client factory that ignores the LocalStack DNS server
* Subclass/specialise a few classes required to support a custom HTTP(s) connection factory
* The custom connection factory creates instances of a custom connection type, which temporarily replaces the host name connect to with the IP address of the same hostname, resolved _outside of LocalStack_.
* This replacement is done temporarily in the case of HTTPS because otherwise the certificate returned by AWS would not be valid for the IP address of the server
> Add client factory to bypass LocalStack DNS server

- localstack-core/localstack/packages/core.py
As mentioned in https://github.com/localstack/localstack/issues/11639, I have noticed that `python -m localstack.cli.lpm install` is leaving behind the downloaded package archives. This results in those files ending up in the published Docker image.
```
$ docker run --entrypoint bash -it localstack/localstack:3.8.0
root@40c78125f557:/opt/code/localstack# ls -lah /tmp/localstack
total 184M
drwxrwxrwx 1 root root  116 Oct  3 19:57 .
drwxrwxrwt 1 root root   50 Oct  3 19:57 ..
-rw-r--r-- 1 root root    0 Oct  3 17:38 .marker
-rw-r--r-- 1 root root 184M Oct  3 19:57 OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.24_8.tar.gz
drwxr-xr-x 1 root root    0 Oct  3 19:57 state
```
This PR solves the issue by removing the archive after extracting a package. This should result in a 184 MB reduction of the …
> Remove downloaded package archives after extracting them

- localstack-core/localstack/services/kinesis/packages.py
@etspaceman just [released a new version](https://github.com/etspaceman/kinesis-mock/releases/tag/v0.4.7) of `kinesis-mock` which basically only contains dependency updates (see release notes [here](https://github.com/etspaceman/kinesis-mock/releases/tag/v0.4.7)).
We should still make sure that we always stay up to date with this great piece of open-source software!
This PR just bumps the version, similar to these PRs (linked to cross-link them together):
- https://github.com/localstack/localstack/pull/7224
- https://github.com/localstack/localstack/pull/7346
- https://github.com/localstack/localstack/pull/7375
- https://github.com/localstack/localstack/pull/7546
- https://github.com/localstack/localstack/pull/7577
- https://github.com/localstack/localstack/pull/7748
- …
> upgrade kinesis-mock from 0.4.6 to 0.4.7

- localstack-core/localstack/aws/connect.py
With #11581, we introduced the option to bypass our own DNS for certain AWS clients.
However, importing the DNS server from the connect.py module leads to issues for older python versions in the CLI, as the CLI needs to be able to import connect.py, and the DNS server uses syntax only supported in later python versions.
* Using python versions 3.8 and 3.9, using the CLI should be possible again without issues (this was never actually published, so it only affected development versions)
> Move dns server import inside resolving function to avoid import in CLI

- localstack-core/localstack/services/moto.py
- tests/aws/test_moto.py
As reported by #11652, we have an issue forwarding requests to `moto` when those have a full URI in the HTTP request, as explained in #8962.
(Example HTTP request: `POST http://sns.eu-central-1.amazonaws.com/ HTTP/1.1` instead of the usual `POST / HTTP/1.1`)
This PR uses the helper created with the above PR to get the request path to send towards the moto dispatcher, so that we only get the `path` part of the request. It only changes the logic to get the actual endpoint to call, as we were already using that helper to forward the request to moto. The logic change is very minimal. 
Looking at it, I believe this is an issue in how Werkzeug handles those requests, putting the full `RAW_URI` in the `path` and not doing sanitization beforehand, as we've seen with …
> fix proxied requests forwarding to Moto

- Makefile
Duplicate Flags: In the `upgrade-pinned-dependencies` target, `--strip-extras` is specified twice in the `pip-compile` commands:
```bash
$(VENV_RUN); pip-compile --strip-extras --upgrade --strip-extras -o requirements-basic.txt pyproject.toml
```
> Remove duplicate --strip-extras flag in dependency pinning target

- tests/aws/services/cloudformation/resources/test_lambda.py
`test_cfn_lambda_sqs_source` has been failing intermittently due to a race in ESMv2.
This PR skips this test for now.
cc: @gregfurman
> Skip test_cfn_lambda_sqs_source

- localstack-core/localstack/packages/api.py
- localstack-core/localstack/packages/java.py
- localstack-core/localstack/utils/kinesis/kinesis_connector.py
https://github.com/localstack/localstack-ext/pull/3419 removed the global default JRE installation. This caused certain tests to start failing for aarch64.
This PR sets the `LD_LIBRARY_PATH` env var with Java libs and adds it to the `JavaInstallerMixin`.
Generally it is advisable to set `java.library.path` on the JVM's command line. But this approach should be a global fix. Besides this used to be set in the Dockerfile in the era of global JRE.
This was detected with following failure:
```
FAILED tests/aws/services/qldb/test_qldb.py::TestQLDB::test_stream_journal - Exception: Timeout when waiting for KCL initialization.
```
Tested passing with following CI run:
https://github.com/localstack/localstack-ext/actions/runs/11272853744/job/31350949612 :green_circle:
> Add LD_LIBRARY_PATH to JavaInstallerMixin

- localstack-core/localstack/utils/testutil.py
We started experiencing BigData test suite OOM failures in the CI since 9th October 3PM CET. Investigations revealed that there was a memory leak in boto3 `DownloadFileObj` and `DownloadFile` but only when running in the same pytest process as LocalStack.
There are some untested hypothesis around why this is happening. These operations are implemented in S3 Transfer library (which can fall back to awscrt). This also uses a thread pool executor, is Pytest interfering somehow?
For now, the workaround is to use S3 `GetObject`. There is a slight performance impact, but since the affected code is a testutil and used in the test suite. There will be no impact on LocalStack.
Possibly related to:
- https://github.com/boto/boto3/issues/4132
> Fix memory leak caused by S3 DownloadFileObj

- localstack-core/localstack/utils/aws/client_types.py
We need `dms` as a new Service Principal. 
Also, I've update the class of the `ServicePrincipal` to `StrEnum`
- add DMS 
- use `StrEnum` instead of subclassing `str`, as done in #11176
> add DMS ServicePrincipal

- localstack-core/localstack/utils/aws/client_types.py
This PR reverts switching `ServicePrincipal` base class from `str` to `StrEnum`, as this is not available before 3.11, and this is in the import path of the CLI.
> ImportError: cannot import name 'StrEnum' from 'enum' 
- revert `StrEnum` change
> revert StrEnum for Python compatibility

- tests/aws/services/lambda_/event_source_mapping/conftest.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.validation.json
- tests/aws/services/lambda_/functions/provided_bootstrap_empty
This PR tests how behaviou when a target Lambda function of an Event Source Mapping handles a Lambda runtime where nothing is returned by a Lambda invocation.
- Adds a new parity test `test_kinesis_empty_provided` to snapshot how an ESM handles a Lambda runtime that does not send any data to the invocation API. 
- This uses a custom `bootstrap`, that sends empty response to the runtime API on invocation
- Custom `bootstrap` resides in `tests/aws/services/lambda_/functions/provided_bootstrap_empty`
- Skips new `EventSourceMappingArn` this field for tests where parity snapshots are not yet updated.
- Changes transformer settings in ESM's `conftest.py` to better cater for this case of multiple UUIDs being snapshot.
> ESM v2: Test Lambda runtime where provided bootstrap returns nothing

- localstack-core/localstack/services/apigateway/legacy/provider.py
- tests/aws/services/apigateway/test_apigateway_basic.py
- tests/aws/services/apigateway/test_apigateway_common.py
- tests/aws/services/apigateway/test_apigateway_extended.py
- tests/aws/services/apigateway/test_apigateway_extended.snapshot.json
- tests/aws/services/apigateway/test_apigateway_extended.validation.json
Based on #11659 to not have conflicts.
As there was a small regression with #11659, I've improved the existing test and added one regarding UsagePlanKeys, and improved the logic in the provider. 
Seems like current test failure is due to targeting another branch, I'll see when the bump is merged. 
- improve existing API keys tests
- add new test for UsagePlanKeys
- fix provider behavior
> APIGW: improve parity for GetApiKeys and GetUsagePlanKeys

- localstack-core/localstack/services/stepfunctions/asl/component/program/program.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/execute_state.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/inline_iteration_component.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/state_map.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_parallel/branch_worker.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_parallel/state_parallel.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_callback.py
- localstack-core/localstack/services/stepfunctions/asl/component/test_state/program/test_state_program.py
- localstack-core/localstack/services/stepfunctions/backend/execution_worker.py
I recently noticed that LocalStack is unable to terminate responsively to user input when Step Functions workflows are evaluating callback tasks. Upon closer inspection, I found that some daemon threads were not properly configured. I also took the opportunity to introduce more conservative behaviour for certain infinite threads, explicitly syncing their lifetimes to that of the state machine. This last change could also improve the responsiveness of stop API actions.
- Ensure proper configuration of daemon threads and TMP_THREADS where relevant
- Modify infinite loops to terminate when the associated state machine halts
> [SFN] Improve responsiveness on shutdown

- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_request.py
- localstack-core/localstack/services/cloudformation/engine/transformers.py
- localstack-core/localstack/services/cloudwatch/alarm_scheduler.py
- localstack-core/localstack/services/dynamodb/provider.py
- localstack-core/localstack/services/events/provider.py
- localstack-core/localstack/services/secretsmanager/provider.py
- localstack-core/localstack/services/sqs/provider.py
- localstack-core/localstack/services/stepfunctions/resource_providers/aws_stepfunctions_statemachine.py
- localstack-core/localstack/services/stores.py
- localstack-core/localstack/utils/aws/message_forwarding.py
- tests/aws/services/dynamodb/test_dynamodb.py
While looking over some performance improvements for SQS, I've stumbled into a key existence checks like that `if key in dict.keys()`. 
Calling `dict.keys()` will create a dict view of the dict keys. In itself, this is not terrible, but it has a bit of a cost performance. 
Giving it a small benchmark:
<details><summary>Small benchmarking code</summary>
<p>
```python
import timeit
test_dict = {f"key{k}": k for k in range(1000)}
last_key = list(test_dict)[-1]
def check_in_keys():
p = last_key in test_dict.keys()
def check_in_dict():
p = last_key in test_dict
def check_not_in_keys():
p = last_key not in test_dict.keys()
def check_not_in_dict():
p = last_key not in test_dict
```
</p>
</details> 
Give the following results for a dictionary with 1000 entries:
- Check `in dict.keys()`: 0.04537 …
> remove key-existence checks against dict.keys() calls

- tests/aws/services/secretsmanager/test_secretsmanager.py
- tests/aws/services/secretsmanager/test_secretsmanager.snapshot.json
- tests/aws/services/secretsmanager/test_secretsmanager.validation.json
AWS allows force-deleting secrets which are already marked for deletion.
However, this is currently blocked in moto.
This PR contains an AWS validated test for this exact behavior.
The actual change to the behavior is in getmoto/moto#8223.
* LocalStack now allows force-deletion of secrets already marked for deletion
> Test force deletion of secrets already marked for deletion

- tests/aws/services/cloudformation/engine/test_mappings.py
- tests/aws/templates/mappings/mapping-ref-map-key.yaml
With the support to add the region ref in mappings inside the conditions for cloudformation in the PR:#11671 the test `tests.aws.services.cloudformation.engine.test_mappings.TestCloudFormationMappings.test_mapping_ref_map_key` was updated to use `AWS::Region`, but when the test runs against non-default region it would fail because of the missing mapping in the template with the following error: 
`localstack.services.cloudformation.engine.errors.TemplateError: Invalid reference: 'ap-southeast-2' could not be found in the 'MyMap' mapping: '['*********']'`
Related workflow: https://app.circleci.com/pipelines/github/localstack/localstack/28846/workflows/dc1a47d0-eaf1-46a7-8149-fc987e80351b/jobs/253009/parallel-runs/2
This PR adds mappings for the non-default regions currently being used to …
> cfn: fix failing `test_mapping_ref_map_key` for multi-account/region

- localstack-core/localstack/services/apigateway/helpers.py
- localstack-core/localstack/services/apigateway/patches.py
- localstack-core/localstack/services/cloudformation/engine/entities.py
- localstack-core/localstack/services/secretsmanager/provider.py
- localstack-core/localstack/testing/pytest/fixtures.py
- localstack-core/localstack/utils/id_generator.py
- tests/aws/services/apigateway/test_apigateway_custom_ids.py
- tests/aws/services/cloudformation/api/test_stacks.py
- tests/aws/services/secretsmanager/test_secretsmanager.py
- tests/unit/utils/test_id_generator.py
As we are starting to build the replicator, we need a mechanism to create resources with custom ids. This pr introduces a set of resource agnostic utils that can be used to handle custom id registration and id generation.
By providing a simple decorator that will return a custom id if one was registered or the result of the decorated function if none are found.
- Added utils around id generator
- Added a sample for Cfn to see what implementation can look like for a service with an LS backend
- Added a sample for secrets manager to see what implementation can look like for a service with a Moto Backend
> Replicator user defined id generator

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_config_factory.py
- localstack-core/localstack/services/lambda_/provider.py
- localstack-core/localstack/utils/aws/arns.py
- tests/aws/services/cloudformation/resources/test_lambda.py
- tests/aws/services/cloudformation/resources/test_lambda.snapshot.json
- tests/aws/services/cloudformation/resources/test_lambda.validation.json
- tests/aws/services/lambda_/event_source_mapping/conftest.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.validation.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.validation.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.validation.json
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/aws/services/lambda_/test_lambda_api.validation.json
This PR introduces increases parity with AWS by includng a new field in ESM responses.
- Add new `EventSourceMappingArn` field to config:
- Skips this field for tests where parity snapshots are not yet updated and for appropriate ESM v1 cases.
- Changes transformer settings in ESM's `conftest.py` to better cater for this case of multiple UUIDs being snapshot.
> ESM v2: Add EventSourceMappingArn field

- bin/localstack-supervisor
In order to start LocalStack from different main methods, we have to make the command the localstack supervisor starts configurable.
This will allow us to be more flexible in the way we start LocalStack.
* Add `LOCALSTACK_SUPERVISOR_COMMAND` to change the command executed by the supervisor to start LocalStack (the main entrypoint).
> Allow adaptation of the localstack run command in the supervisor

- localstack-core/localstack/openapi.yaml
- localstack-core/localstack/services/sqs/provider.py
- tests/aws/services/sqs/test_sqs_backdoor.py
As we introduced specs for the developer endpoints, we want to make sure they match the actual implementation.
For this purpose, we can activate request and response verification in our handler chain and test our endpoint against the OpenAPI spec.
This PR activates the validation for the SQS dev endpoints.
- Enable the validation for the `TestSqsDeveloperEndpoints` suite;
- Minor changes to the spec to let the suite pass;
🔈  I'd ask the service owners to check if this PR is already comprehensive and eventually, if not, please help me fill all possible gaps.
> Validate SQS dev endpoints

- docs/development-environment-setup/README.md
Contributors might get confused by our current documentation stating Python 3.11+ is needed as Python 3.12 does not have full support at this time. 
For dev environments we already have a checked in `.python-version` file in the top level, which would get picked up by any python version manager (e.g., pyenv).
This can already serve as the single source of truth for this.
- Remove direct reference to a Python version and instead point to use pyenv
- If contributors don't want to use pyenv they can also now just quickly have a look at the `.python-version` and handle the version themselves.
> Add note recommending pyenv in dev environment docs

- pyproject.toml
With `setuptools==75.2.0` (more specifically with https://github.com/pypa/setuptools/pull/4647), `setuptools` is now explicitly removing the egg-info dir when building source distributions which is causing issues with `plux` (since it needs to add the entry points detected at build time).
This issue needs to be addressed in `plux`, until then we limit the version of `setuptools` in the `build-sytem.requires` to circumvent this issue for now.
- Set an upper limit to the `setuptools` version used when building source distributions of `localstack-core` to avoid the incompatibility of the latest release of `plux` (`1.11.0`) with the latest release of `setuptools` (`75.2.0`)
> fix source distro installation by limiting setuptools version

- .github/workflows/update_openapi_spec.yml
- .pre-commit-config.yaml
We are building a separate repo to store LocalStack's OpenAPI specs.
This workflow is triggered when the spec changes and it dispatches a workflow on the destination repo that generates a new `latest` spec.
See https://github.com/localstack/localstack-ext/pull/3554 for more context.
> Add workflow to dispatch the update of the OpenAPI spec

- localstack-core/localstack/services/apigateway/next_gen/execute_api/router.py
- localstack-core/localstack/services/apigateway/next_gen/provider.py
As reported in #11696, we've had an issue with APIGW NG persistence. We need to store the actual full store variable (container) instead of some of its dict attributes, as those could be overwritten (replacing a nested dict value with another dict, thus losing the "sync" and reference). 
- store the full account bundle instead of the store, and create a property to access the store itself
> APIGW NG: fix storing store attribute instead of full store

- localstack-core/localstack/services/cloudformation/engine/template_utils.py
- tests/aws/services/cloudformation/engine/test_mappings.py
- tests/aws/services/cloudformation/engine/test_mappings.validation.json
- tests/aws/templates/mappings/mapping-aws-ref-map-key.yaml
- tests/aws/templates/mappings/mapping-ref-map-key.yaml
This PRs addresses the changes requested in #11671
- refactoring of the reference search
- restore previous test and add a new one more focused on the refere
- new test that asserts that Map name, top level key and second level key can be AWS:: refs
> refactor ref keys in conditional mappings and test

- localstack-core/localstack/testing/scenario/provisioning.py
This PR aims to fix the S3 bucket cleaning when a stack contains more than one buckets (with objects in it). According to my theory due to late binding in the lambda function, the `cleanup_s3_bucket` is not able to get the reference to the actual variable.
- updated the cleanup of s3 buckets in the cdc provisioner function.
> fixed s3 deletion from stack in cdk

- localstack-core/localstack/testing/scenario/cdk_lambda_helper.py
**Motivation**
This PR addresses two main issues:
1. **Fixing Typos**
- Corrects typographical errors in the function arguments.
2. **Resolving the Directory Copying Bug**
- Previously, when providing a path to a directory in `load_nodejs_lambda_to_s3` for copying into the lambda folder, the directory was not copied.
- With this change, supplying a directory path to `load_nodejs_lambda_to_s3` will correctly copy the entire directory into the lambda function environment.
**Additional Information**
This bug was discovered while working on [localstack/localstack-ext#3527](https://github.com/localstack/localstack-ext/issues/3527), where we are generating a frontend build using this lambda function.
**Changes Made**
- **Typos Fixed**
- Corrected errors in function argument names.
- **Enhanced …
> fix lambda function extra resources upload in s3

- pyproject.toml
- requirements-basic.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
This PR bumps moto-ext to 5.0.17.post2
Contains:
- https://github.com/getmoto/moto/pull/8231 @cloutierMat 
- https://github.com/getmoto/moto/pull/8157 @dfangl 
- https://github.com/getmoto/moto/pull/8230 @cloutierMat 
- https://github.com/getmoto/moto/pull/8233 @viren-nadkarni
> Bump moto-ext to 5.0.17.post2

- pyproject.toml
With https://github.com/localstack/localstack/pull/11715, we added a version limit for `setuptools` in `build-system.requres` in the `pyproject.toml` to mitigate an issue with `plux`.
This issue has been resolved with the latest release of `plux` (`1.12`), specifically with https://github.com/localstack/plux/pull/26.
- Reverts the limit of `setuptools` in `build-system.requres` in the `pyproject.toml` introduced in https://github.com/localstack/localstack/pull/11715.
- Bumps the minimum version of `plux`.
> remove setuptools limit in build-system.requires

- localstack-core/localstack/testing/testselection/matching.py
- tests/unit/testing/testselection/test_matching.py
This PR aims to expand on the functionality of the `Matcher` for tests selection. The changes included will allow us to use the `directory` method to add an argument for which directory should be executed.
We can now enter the following rule to explicitly target test folders when files in `my_feature` modules are changed.
```
Matchers.glob("localstack/my_feature/**").directory(
paths=["tests/integration/my_feature"]
)
```
> improve tests selection

- localstack-core/localstack/packages/java.py
This PR fixes a bug in the Java installer where it downloaded and installed the Linux JRE even on Mac hosts.
With this change, any Java application using Java 11+ will run correctly when LS runs in host mode on Mac.
Eclipse Temurin [does not support](https://adoptium.net/en-GB/supported-platforms/) Java 8 aarch64 for Mac, so some components (notably Big Data) will continue to be non-functional.
Other changes:
- Omit Thai locale generation. This will further slightly reduce the disk footprint
- Update the pinned fallback JRE versions to the latest
> Fix Java installer on Mac hosts

- localstack-core/localstack/services/cloudformation/engine/template_deployer.py
- tests/aws/services/cloudformation/engine/test_references.py
- tests/aws/services/cloudformation/engine/test_references.snapshot.json
- tests/aws/services/cloudformation/engine/test_references.validation.json
- tests/aws/templates/cfn_number_in_sub.yml
A customer had an issue when they used a non-string `Parameter` value, e.g.:
```yaml
Parameters:
MyValue:
Type: Number
Default: 5
```
When this parameter is used within a `Fn::Sub` expression:
```
Value:
Fn::Sub: "my value is ${MyValue}"
```
it causes an error: `Could not resolve {'Ref': 'MyValue'} to terminal value type`. This is because we raise an error if any `Ref` type that we resolve does not eventually resolve to a string. This is limited however, as the parameter value is a number, but really the error should be related to if the ref cannot be resolved beyond a structured type, e.g. `dict`, `list` or `tuple`.
> [!WARNING]  
> The _true_ fix probably involves casting all parameters to strings, but using the `Type` for _something_... Not quite sure yet at this stage. This PR however …
> Fix: Cfn: non-string parameter values

- .circleci/config.yml
As we are planning to remove the S3 legacy implementation, we can already remove the S3 CI job, as I'd like to setup a job for the DynamoDB(Streams) v2 provider, and the CI service-specific job landscape is getting crowded.
- remove the S3 legacy CI job
> remove S3 legacy CI job

- pyproject.toml
- requirements-basic.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
This PR bumps moto-ext to 5.0.18.post1
Contains:
- https://github.com/getmoto/moto/pull/8260
- https://github.com/getmoto/moto/pull/8235
closes https://github.com/localstack/localstack/issues/9337
> Bump moto-ext to 5.0.18.post1

- localstack-core/localstack/services/lambda_/api_utils.py
- localstack-core/localstack/services/lambda_/invocation/lambda_models.py
- localstack-core/localstack/services/lambda_/invocation/models.py
- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/aws/services/lambda_/test_lambda_api.validation.json
- This PR adds tagging functionality to the Lambda provider that leverages the TaggingService. In addition, we add tagging functionality for event source mapping. 
- Fixes https://github.com/localstack/localstack/issues/11739
- Extended `TestLambdaTag` suite to include tagging tests for Event Source Mappings
- Refactored/reworked the internal `tag_resource`, `list_tags`, and `untag_resource` Lambda provider functions to use a provider-wde TaggingService. This allows for tagging of Lambda Event Source Mapping or Lambda Function resources (with support for CSC but this is not yet implemented).
- Manually verified event source mapping creation with Terraform, using the [terraform-aws-lambda/event-source-mapping](https://github.com/terraform-aws-modules/terraform-aws-lambda/tree/master/example …
> add: TaggingService functionality to Lambda Provider

- localstack-core/localstack/services/apigateway/helpers.py
- tests/aws/services/apigateway/test_apigateway_common.py
- tests/aws/services/apigateway/test_apigateway_common.snapshot.json
- tests/aws/services/apigateway/test_apigateway_common.validation.json
The same issue as  #9631 was reported in #11755. I've implemented 2 tests to validate the behavior, and the main issue is that we were not properly replacing the `$ref` in lists, leading to the `jsonschema` library directly trying to reach the link. We could probably also remove the custom model resolving, and do a regex sub on the `https://apigateway.amazonaws.com` string and replace by the LocalStack edge, but still not sure it would work, as the first reported issue still had problems resolving it.
- fix the logic to also resolve `$ref` inside JSON arrays
- add 2 tests related to `$ref` resolving, one regular and one with `oneOf` property
_fixes #11755 and fixes #9631_
> fix APIGW oneOf and add APIGW test for Model $ref resolving

- localstack-core/localstack/testing/pytest/fixtures.py
- tests/aws/services/sqs/test_sqs.py
- tests/aws/services/sqs/test_sqs_move_task.py
- tests/aws/services/sqs/utils.py
Collecting SQS messages is a common task in LocalStack testing and we don't have a re-usable fixture (across LS and LS-ext) yet. The fixture is used in a LS-ext PR for testing Pipes persistence.
* Convert SQS helper util into re-usable fixture `sqs_collect_messages`
When should we use fixtures and when util/helper methods (passing in an aws_client)?
> Convert SQS test util into re-usable fixture sqs_collect_messages

- localstack-core/localstack/services/apigateway/next_gen/execute_api/gateway.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/__init__.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/cors.py
We currently have special logic in `localstack/aws/handlers/cors.py`, special for S3 and API Gateway who can self manage their CORS behavior.
In order to guess that we are going to target an edge route, we currently have custom logic in `should_enforce_self_managed_service`, which uses some heuristic to guess it and let the CORS handler do its thing. 
However, this does not catch every API Gateway routes, especially the ones related to custom domains. It would be good to move most of the CORS related logic for those "self-managed" services inside the service itself, like we have done for S3: meaning that if the config flag to disable it is enabled, we should let the service apply the global LocalStack CORS logic in its own way (as they most probably already have logic in place for it). …
> APIGW NG: add LocalStack-only CORS handling for REST API

- localstack-core/localstack/services/s3/provider.py
- tests/aws/services/s3/test_s3_api.py
- tests/aws/services/s3/test_s3_api.snapshot.json
- tests/aws/services/s3/test_s3_api.validation.json
Raised from a support issue with a Crossplane integration. 
We would raise `InvalidBucketState: An Object Lock configuration is present on this bucket, so the versioning state cannot be changed` when setting up a bucket with both versioning and ObjectLock enabled. I've adapted a test case to reproduce this case, where enabling versioning on a bucket that already has it enabled via`ObjectLockEnabledForBucket` set to `True`, does not trigger an exception because it's effectively a null operation.
- adapt a test to reproduce the exception
- modify the logic so that we only block changing the status to `Suspended`
> fix S3 enabling versioning with a ObjectLockEnabledForBucket bucket

- localstack-core/localstack/config.py
- localstack-core/localstack/services/providers.py
This PR makes the APIGW NextProvider to be the default used. 
This PR also compiles all PRs done related to this work.
- make the NextGen provider default
- #10982
- #11043
- #11051
- #11057
- #11062
- #11065
- #11085
- #11096
- #11099
- #11107
- #11111
- #11114
- #11121
- #11129
- #11135
- #11138 
- #11140
- #11142
- #11143
- #11144
- #11148
- #11167
- #11183
- #11196
- #11198
- #11199
- #11219 
- #11226
- #11227
- #11234
- #11237 
- #11250
- #11251
- #11256
- #11257
- #11268
- #11317
- #11327
- #11344
- #11349
- #11350
- #11372
- #11401
- #11413
- #11518
- #11569
- #11702
- #11633
Once this PR is merged:
> make next-gen APIGW provider default

- localstack-core/localstack/testing/snapshots/transformer_utility.py
- tests/aws/services/iam/test_iam.py
- tests/aws/services/iam/test_iam.snapshot.json
- tests/aws/services/iam/test_iam.validation.json
During investigation of an IAM issue, I noticed our IAM implementation not returning exactly the same policies as submitted.
This happens, when parts of the policy are already urlencoded, and the response removes this encoding, returning the actual value.
This behavior however does not match AWS, which does return the policies as they were submitted.
A fix for this behavior is in getmoto/moto#8157, this PR only contains AWS validated tests for this behavior. The tests will fail, as long as the PR in moto is not merged and moto updated in LocalStack.
* Add AWS validated tests to verify the policies being unchanged, even if they contain urlencoded parts
> Add tests to test urlencoded IAM policies

- .circleci/config.yml
Follow up from #11035, this PR removes the APIGW NG CI step now that it is default.
- remove the APIGW NG CI job
> remove APIGW NextGen CI job

- .circleci/config.yml
We can remove the CI step earlier to minimize the changes in the PR removing the legacy StepFunctions provider (https://github.com/localstack/localstack/pull/11733) and mitigate merge conflicts.
Learned from the S3 example by @bentsku https://github.com/localstack/localstack/pull/11743
* remove the legacy StepFunction CI job
> Remove legacy StepFunctions CI job

- localstack-core/localstack/services/apigateway/helpers.py
- tests/aws/files/openapi.cognito-auth.json
- tests/aws/services/apigateway/test_apigateway_import.py
- tests/aws/services/apigateway/test_apigateway_import.snapshot.json
- tests/aws/services/apigateway/test_apigateway_import.validation.json
We got a report that import an API with the following configuration would fail with a cryptic error:
```python
localstack-test  | 2024-11-04T16:17:31.927  WARN --- [et.reactor-0] l.s.a.n.e.h.gateway_except : Non Gateway Exception raised: 'NoneType' object has no attribute 'startswith'
```
When the OpenAPI spec had the following:
```yaml
components:
securitySchemes:
EndpointAuthorizer:
type: apiKey
name: Authorization
in: header
x-amazon-apigateway-authtype: cognito_user_pools
x-amazon-apigateway-authorizer:
type: cognito_user_pools
providerARNs:
- arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPool}
```
This was because we did not populate the `identitySource` of the Authorizer when the authorizer type was `cognito_user_pools`. 
As a note: we greatly improve …
> APIGW: fix importing API with Cognito Authorizer

- localstack-core/localstack/services/apigateway/legacy/provider.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/helpers.py
- tests/aws/services/apigateway/test_apigateway_integrations.py
- tests/aws/services/apigateway/test_apigateway_integrations.validation.json
We got a report in our Slack Community channel about the legacy implementation. While switching to NextGen, another issue happened. This setup is from an exported OpenAPI spec from an AWS REST API. 
```python
2024-11-05T10:59:03.146  WARN --- [et.reactor-0] localstack.deprecations    : /restapis/<api_id>/<stage>/_user_request_ is deprecated (since 3.8.0) and will be removed in upcoming releases of LocalStack! Use /_aws/execute-api/<api_id>/<stage> instead.
2024-11-05T10:59:03.146935385Z 2024-11-05T10:59:03.146 DEBUG --- [et.reactor-0] l.s.a.n.execute_api.router : APIGW v1 Endpoint called
[...removed]
2024-11-05T10:59:03.165331385Z 2024-11-05T10:59:03.162  WARN --- [et.reactor-0] l.s.a.n.e.h.gateway_except : Non Gateway Exception raised: 'NoneType' object has no attribute 'replace' …
```
> APIGW: fix MOCK integration with no URI and path parameters

- localstack-core/localstack/utils/id_generator.py
- tests/unit/utils/test_id_generator.py
Adding a context manager to allow for a streamlined usage of the id manager where a resource unsets after use.
> Add context manager to id generator

- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_request.py
- tests/aws/services/apigateway/test_apigateway_integrations.py
- tests/aws/services/apigateway/test_apigateway_integrations.snapshot.json
- tests/aws/services/apigateway/test_apigateway_integrations.validation.json
As reported in our Community Slack, having a similar flow as the one added in this test in a VTL template did not work currently. 
The idea is to get some data from the incoming request, maybe transform it and set it in the `context.requestOverride`. 
Then, the response template can access it and transform it/do conditional logic on it. 
As we don't want to directly mutate the passed context, we deep copy it before sending it down for rendering (as we don't fully control the rendering logic and what is protected or not). 
We then need to attach the `requestOverride` data back to the context so that it is available in the `context` in the response template to execute logic on it. 
- attach back the `requestOverride` to the context variables
- add a pretty complex test checking logic to …
> APIGW: fix requestOverride not being present in responseTemplates

- localstack-core/localstack/aws/api/s3/__init__.py
- localstack-core/localstack/aws/spec-patches.json
- localstack-core/localstack/services/s3/provider.py
- localstack-core/localstack/services/s3/utils.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/aws/services/s3/test_s3.validation.json
As reported and re-opened in #2562, we've had a regression compared to 0.11 (yes!), as some behavior was untested and not caught during early migrations to ASF (S3 v2) and now v3. 
We did not make a difference between `InvalidDigest` and `BadDigest` (Invalid is raised when the given b64 encoded checksum is not a proper b64 encoded checksum, and Bad when the checksum does not match the item). 
Part of the MD5 behavior was re-added with #9064.
- update the logic when comparing the ContentMD5
- check that the ContentMD5 is a proper b64-encoded MD5 hash
- add test for `UploadPart` MD5 behavior: funny enough, error messages are not the same between `PutObject` and `UploadPart` (not using the same values)
_fixes #2562_
> implement S3 MD5 checksum check for UploadPart and improve logic

- Dockerfile
We currently install `virtualenv` into its own layer for the only purpose to create a virtual environment.
However, we can do that just as easily with `python -m venv .venv`. Virtualenv is a nice tool, but its features do not seem to be needed in our docker build.
This change reduces the layers by 1, and should decrease the image size a tad, and we get one less unpinned dependency.
The change should not have any impact on our users, but users might depend on "virtualenv" being installed in init scripts (although unlikely), so I would like to release it with 4.0 as breaking change.
* Remove virtualenv installation from docker build
> Remove virtualenv dependency from docker build

- localstack-core/localstack/services/lambda_/resource_providers/aws_lambda_eventsourcemapping.py
- tests/aws/services/lambda_/event_source_mapping/test_cfn_resource.py
- tests/aws/services/lambda_/event_source_mapping/test_cfn_resource.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_cfn_resource.validation.json
- tests/aws/templates/event_source_mapping_tags.yml
Event Source Mappings are supported via CloudFormation, however two things are currently broken:
1. When assigning tags, the following error is received:
```
Invalid type for parameter Tags, value: [{'Key': 'component', 'Value': 'value'}], type: <class 'list'>, valid types: <class 'dict'>
```
This means that the tag format supported by CloudFormation is not directly compatible with the tag format used by `boto3`.
2. When performing `!GetAtt <ESM>.EventSourceMappingArn` the value returned is `None`
* Translate tags from one format to another
* Set the `EventSourceMappingArn` property to handle the `GetAtt` case
> Fix: CFn: support tags with ESMs

- localstack-core/localstack/config.py
- localstack-core/localstack/runtime/analytics.py
Currently, we only use the CONTAINER_RUNTIME environment variable in pro.
However, it makes sense to have this variable a global override, including for the lambda runtime executor.
For this, we need to move this variable to community.
* Update tracked variables
* Introduce CONTAINER_RUNTIME as environment variable in the open source project and make `LAMBDA_RUNTIME_EXECUTOR` fall back on it.
> Introduce CONTAINER_RUNTIME environment variable to control all container runtimes

- .github/workflows/tests-pro-integration.yml
- localstack-core/localstack/dev/kubernetes/__main__.py
- localstack-core/localstack/dev/run/__main__.py
- localstack-core/localstack/testing/pytest/container.py
- localstack-core/localstack/utils/bootstrap.py
- tests/bootstrap/test_container_configurators.py
- tests/unit/cli/test_cli.py
With the upcoming release of LocalStack v4, we will push the deprecation of `LOCALSTACK_API_KEY` in favor of `LOCALSTACK_AUTH_TOKEN`.
This PR prepares this deprecation by migrating all usages of the API key in favor of the auth token.
This change does _not_ introduce any deprecation message yet. 
- Use `LOCALSTACK_AUTH_TOKEN` instead of `LOCALSTACK_API_KEY` wherever possible.
- Avoid directing users to set a `LOCALSTACK_API_KEY` in case no credentials are set.
/cc @Pive01 @SimonWallner
> migrate to LOCALSTACK_AUTH_TOKEN

- Dockerfile
Recently the NodeJS installation failed when building the Docker image with the following error:
```
#8 6.843 + cat+ uniq
#8 6.844  SHASUMS256.txt
#8 6.845 + sort
#8 6.846 + grep -o node-v.*-linux-x64
#8 6.847 + LATEST_VERSION_FILENAME=
#8 6.847 + rm SHASUMS256.txt
#8 6.848 + curl -fsSLO --compressed https://nodejs.org/dist/latest-v18.x/.tar.xz
#8 6.985 curl: (22) The requested URL returned error: 404
```
Here are some examples of failing pipelines:
- https://app.circleci.com/pipelines/github/localstack/localstack/29286/workflows/5000bdc4-af1d-4692-9180-100563d38e56
- https://app.circleci.com/pipelines/github/localstack/localstack/29286/workflows/2172c4b8-a5da-4123-96d9-7984fb97c0b6
- https://app.circleci.com/pipelines/github/localstack/localstack/29292/workflows/3c1bd969-bbf4-45ec-b01c-3b …
> fix node installation in Dockerfile

- localstack-core/localstack/cli/localstack.py
Besides LocalStack releases, CLI is also released with semantic versioning.
This can be confusing to users, see relevant discussions[[1](https://localstack-cloud.slack.com/archives/C060ZRAULEL/p1725464854452179?thread_ts=1725445367.911869&cid=C060ZRAULEL)][[2](https://localstack-cloud.slack.com/archives/C02N36URU1G/p1725467328964489)][[3](https://localstack-cloud.slack.com/archives/C02N36URU1G/p1725556984925929)][...]. 
Cc @SimonWallner @HarshCasper @dfangl @inothnagel @whummer 
The CLI _version_ command outputs a semantic number, but does not specify if this is referring to LocalStack or CLI.
This will add LocalStack CLI as a prefix before the version number and style the message to be more subtle and different from the rest of the output, so that the version command is more explicit and …
> Add CLI version command prefix

- docs/localstack-concepts/README.md
#11819  &  OCD!
I was reading the documentation and I found some broken links. I think they need some love and it will help new joiners.
- Updates 5 links to localstack resources that are out of date since the refactoring. 
| Before  | After  |
|--------|--------|
| <img width="1468" alt="Screenshot 2024-11-09 at 23 12 32" src="https://github.com/user-attachments/assets/9c7138fb-9c0e-4341-9911-64d27adde8c7">|<img width="1451" alt="Screenshot 2024-11-09 at 23 14 42" src="https://github.com/user-attachments/assets/e6408fd3-ac84-4f54-bff3-ff9a9161af8f">|
> Update broken links in localstack-concepts/Readme.md

- localstack-core/localstack/services/dynamodb/server.py
This PR is a follow-up of https://github.com/localstack/localstack/pull/11789.
@HarshCasper [noticed](https://localstack-cloud.slack.com/archives/C037N93TF16/p1731003971136279) a bunch of logs like the following when loading a DDB state in a container without an initialized DDB provider (i.e., start LS and immediately load):
```
2024-11-08T16:47:39.854 DEBUG --- [functhread27] l.services.dynamodb.server : Initializing DynamoDB Local with the following configuration:
2024-11-08T16:47:39.854 DEBUG --- [functhread27] l.services.dynamodb.server : Port:	37097
2024-11-08T16:47:39.854 DEBUG --- [functhread27] l.services.dynamodb.server : InMemory:	false
2024-11-08T16:47:39.854 DEBUG --- [functhread27] l.services.dynamodb.server : Version:	2.5.3
2024-11-08T16:47:39.854 DEBUG --- [functhread27] …
```
> Idempotent start of the DynamoDB server

- localstack-core/localstack/runtime/init.py
> [!IMPORTANT]
> This is a breaking change designated for LocalStack v4.0.0
The old implementation of multi-accounts in LocalStack used environment variables that determined the account/region of the sandbox. This impacted various other features, most notably the init hooks where we used to inherit the same environment variables when running the startup script. The startup scripts could be written without the need for explicit AWS credentials.
Since then, LocalStack moved to a multi-accounts implementation based on the request context. It no longer requires a global env var setting of account/region. But to maintain backward compatibility with existing init hook startup scripts, we started setting default account/region values in its environment.
With LocalStack v4, the default AWS …
> Init hooks: Remove default AWS credentials

- localstack-core/localstack/packages/java.py
- localstack-core/localstack/services/events/event_ruler.py
In https://github.com/localstack/localstack/pull/11139 we started using Temurin builds for Java. All Java applications were explicitly configured to use these JREs, not OS ones.
On Mac OS, it was discovered that Jpype was failing to start, and this was affecting LocalStack development on Mac OS.
Mac builds of Temurin have a different directory structure. Furthermore the shared library usage is also different. On Linux, it is simply `libjvm.so`. On Darwin, there is a passthrough interface, the so-called [Java launcher interface](https://nachtimwald.com/2017/06/17/calling-java-from-c/) aka `libjli.dylib`, which invokes the JVM.
This PR ensures that the Java installer accounts for these differences.
> Fix Java shared library path for darwin

- localstack-core/localstack/services/s3/models.py
- localstack-core/localstack/services/s3/provider.py
When implementing new features in S3 since `3.0.0`, we've taken extra care to not break persistence by using `getattr` around store attributes and have additional conditionals in place. 
As we're approaching a major release, I've collected the TODO related to this and removed the `getattr` blocks to simplify the logic. If people loaded earlier state and then saved it again after using it with a version with those calls, the state should not be broken anyway. 
- remove TODOs and `getattr` around store operations, as v4 is probably going to break persistence in multiple ways with all the provider changes.
> remove S3 persistence workaround

- localstack-core/localstack/services/events/target.py
- tests/aws/services/events/conftest.py
- tests/aws/services/events/test_events_targets.py
- tests/aws/services/events/test_events_targets.snapshot.json
- tests/aws/services/events/test_events_targets.validation.json
This PR adds parity tests for eventbridge logs target. 
None in code. 
```
PROVIDER_OVERRIDE_EVENTS=v2 DEBUG=1 make test TEST_PATH=tests/aws/services/events/test_events_targets.py::TestEventsTargetCloudWatchLogs::test_put_events_with_target_cloudwatch_logs
```
> Parity test for Eventbridge logs target

- docs/testing/integration-tests/README.md
- docs/testing/parity-testing/README.md
We had a dead link from the parity testing docs to the integration test docs, which is fixed now.
Also, we are still using the old version of boto client fixtures as examples. While the examples are only illustrative, we should still use the correct ones if possible.
* Fix broken link
* Replace usage of `sqs_client` and `lambda_client` fixtures with the `aws_client` fixture
> Fix testing links and update aws client fixtures in contributing docs

- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
Bumping airspeed version to 0.6.7
https://github.com/localstack/airspeed/pull/20
- Fixing issue with matching `double` type.
- Adding mechanism to bypass silent behavior of `$util` functions.
> Bump airspeed-ext to 0.6.7

- localstack-core/localstack/services/dynamodb/server.py
With #11789 fixing previous issues we've introduced with DynamoDB Streams v2 implementation, a call to `mkdir` was introduced.
However, when `DYNAMODB_IN_MEMORY=1` is set, we set `self.db_path` to `None` leading to this exception:
```python
2024-11-14T12:47:05.847 ERROR --- [et.reactor-3] localstack.utils.functions : error calling function on_before_start
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/functions.py", line 42, in call_safe
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/dynamodb/v2/provider.py", line 378, in on_before_start
self.server.start_dynamodb()
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/u …
```
> DynamoDB: fix mkdir call with None when DYNAMODB_IN_MEMORY=1

- localstack-core/localstack/services/dynamodb/provider.py
- localstack-core/localstack/services/dynamodbstreams/dynamodbstreams_api.py
Decompose function that processes dynamodb records so each individual record can be collected as an event by EventStudio before they are sent to the kinesis stream
Decompose function that submits process records to background process to be able to patch it in EventStudio and submit it with the parent thread context
> Feature/DynamoDBStreams: decompose process records

- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py
- tests/aws/services/apigateway/test_apigateway_lambda.py
- tests/aws/services/apigateway/test_apigateway_lambda.snapshot.json
- tests/aws/services/apigateway/test_apigateway_lambda.validation.json
We got a report in our Community Slack regarding too strict lambda payload response validation for the `AWS_PROXY` integration:
```python
2024-11-15T05:30:24.755  WARN --- [et.reactor-1] l.s.a.n.e.integrations.aws : Lambda output should follow the next JSON format: { "isBase64Encoded": true|false, "statusCode": httpStatusCode, "headers": { "headerName": "headerValue", ... },"body": "..."} but was: b'{"statusCode":200,"headers":null,"multiValueHeaders":{"Content-Type":["application/json"],"X-Request-Id":["fcc51e39-0a54-45c6-88f7-c1d81b5f7075"]},"body":"''
2024-11-15T05:30:24.755 DEBUG --- [et.reactor-1] l.s.a.n.e.integrations.aws : Execution failed due to configuration error: Malformed Lambda proxy response
```
It seems we were too strict, and didn't have this validated by tests. I've …
> fix APIGW AWS_PROXY lambda response validation

- localstack-core/localstack/services/sns/provider.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
- tests/aws/services/sns/test_sns.validation.json
As reported with #11817, we've had an issue in our validation of SNS attributes, with the order of the validation, and that directly accessed the `DataType` field. 
Validation is now updated with more test cases.
- add few test cases for Publish and PublishBatch
- fix the behavior and change validation order
_fixes #11817_
> fix SNS empty MessageAttributes validation

- localstack-core/localstack/runtime/analytics.py
Bedrock is an upcoming new pro service which needs tracking in our analytics
- add tracking for the pre-warming configuration to check how many people want to have their ollama container started on localstack startup
- add tracking for the default model used in ollama so that we know for which models to optimize our implementations
> Add Bedrock configuration values to analytics

- localstack-core/localstack/utils/analytics/usage.py
While looking to implement the usage analytics for the API Gateway service, I've noticed three things:
- we were not sending usage analytics anymore since #11202, as we removed the code to send it, but didn't register the hook back
- the usage counters were still counting even though analytics would be disabled, and would only skip sending the data over
- the usage counters are using lists that are growing unbounded, possibly using large amount of memory for very long lasting sessions (we're aware of 20+ hours sessions)
This PR mainly does 2 things:
- re-register the hook so that we send analytics over
- it does not count if analytics is disabled
- refactor the counter a bit to avoid growing a list, instead keeping the "set" entries and counting with `itertools.count` which is thread safe …
> fix usage analytics to properly register and not count if disabled

- localstack-core/localstack/cli/localstack.py
This PR marks the new CLI command "ephemeral" (which will be introduced with 4.0) as "advanced".
- Add `ephemeral` to advanced CLI features
> add ephemeral cli commands to advanced features

- localstack-core/localstack/runtime/analytics.py
With the new replicator feature we should track its usage via our analytics.
* Include `ENABLE_REPLICATOR` in the envars we track with analytics
> Track replicator usage in analytics

- pyproject.toml
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
This PR bumps moto-ext to 5.0.20.post1
> Bump moto-ext to 5.0.20.post1

- localstack-core/localstack/services/events/provider.py
- localstack-core/localstack/services/events/v1/provider.py
- localstack-core/localstack/services/lambda_/event_source_listeners/utils.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/poller.py
- localstack-core/localstack/utils/event_matcher.py
- tests/aws/services/events/test_archive_and_replay.py
- tests/unit/utils/test_event_matcher.py
This PR adds support for a Python-based event rule engine as an alternative to the Java implementation. 
This addresses installation issues some users face with the Java event ruler (GH-11299), particularly 
in environments with proxy setups or SSL certificate issues.
- Created new utility `event_matcher.py` to centralize event matching logic
- Supports both string (EventBridge) and dict (ESM/Pipes) inputs
- Maintains Java engine as default but allows configuration via EVENT_RULE_ENGINE
- Updated references in:
- events/provider.py
- events/v1/provider.py
- lambda_/event_source_mapping/pollers/poller.py
- Added unit test
1. Run the new test suite:
```bash
pytest tests/unit/utils/test_event_matcher.py
> Added EVENT_RULE_ENGINE flag based opt-in

- localstack-core/localstack/services/apigateway/next_gen/execute_api/gateway.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/__init__.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/analytics.py
As part of our effort to improve our analytics, this PR implements usage counters for API Gateway.
We can now properly have usage data on APIGW invocations, with the integration type (`AWS_PROXY`, `MOCK` etc), and in case of the `AWS` integration, the service the integration is targeting (`dynamodb`, `sqs` etc..)
- implement APIGW NextGen handler for analytics
> add analytics to APIGW NextGen REST API handler chain

- .github/workflows/tests-cli.yml
- localstack-core/localstack/services/s3/models.py
- localstack-core/localstack/services/s3/storage/ephemeral.py
- localstack-core/localstack/services/s3/utils.py
- localstack-core/localstack/services/s3/validation.py
- pyproject.toml
- tests/aws/services/events/test_events_patterns.py
- tests/aws/services/s3/test_s3.py
- tests/unit/test_common.py
- tests/unit/test_docker_utils.py
- tests/unit/test_s3.py
With v4 we will be dropping the support for Python 3.8 in our LocalStack CLI.
It reached its [End Of Life on the 7th of October 2024](https://peps.python.org/pep-0569/#lifespan) and does not get _any_ updates anymore (not even security).
Similar to https://github.com/localstack/localstack/pull/9148, this PR bumps the minimum version in the `pyproject.toml` (+ in the ruff config), and removes 3.8 from the CLI test build matrix and adds 3.13 instead.
> drop support for Python 3.8 in the LocalStack CLI

- localstack-core/localstack/deprecations.py
- localstack-core/localstack/runtime/analytics.py
This PR adds the following environment config options to analytics collection:
- `EC2_VM_MANAGER`: To understand which VM managers are commonly used in EC2 (e.g. Docker, Libvirt, etc.)
- `DYNAMODB_IN_MEMORY`: To understand usage of in-memory mode for DDB
- `DYNAMODB_REMOVE_EXPIRED_ITEMS`: To track the usage of DDB TTL expired item removal
- `ALLOW_NONSTANDARD_REGIONS`: To increase our understanding of multi-region usage
- `OUTBOUND_HTTP_PROXY` and `OUTBOUND_HTTPS_PROXY`: To help improve proxy support
Also the following defunct config options are marked as such:
- `PERSIST_ALL`: see localstack/localstack-ext#2144
> Update analytics tracked env vars

- localstack-core/localstack/services/lambda_/api_utils.py
- localstack-core/localstack/services/lambda_/provider.py
- localstack-core/localstack/services/lambda_/runtimes.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/aws/services/lambda_/test_lambda_api.validation.json
- tests/aws/services/lambda_/test_lambda_common.py
- tests/aws/services/lambda_/test_lambda_common.snapshot.json
- tests/aws/services/lambda_/test_lambda_common.validation.json
- tests/aws/services/lambda_/test_lambda_runtimes.snapshot.json
- tests/aws/services/lambda_/test_lambda_runtimes.validation.json
AWS just announced support for the new Python 3.13 Lambda runtime on Nov 14th (4 days ago) and we want to support it quickly.
https://aws.amazon.com/blogs/compute/python-3-13-runtime-now-available-in-aws-lambda/
* Add support for the new Lambda runtime Python 3.13
* Remove the dynamic Lambda runtime deprecation upgrade recommendation that AWS recently removed replacing it with a static message
* Add LocalStack debug message with the upgrade recommendation (we can also consider dropping it)
* Update snapshots
> Add Python 3.13 Lambda runtime

- localstack-core/localstack/services/events/event_ruler.py
- pyproject.toml
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
Currently, jpype1 only installs SIGINT signal handlers if `interrupt=False`. With https://github.com/localstack/jpype/pull/1, we (very crudely) added support for SIGTERM as well.
We should aim to upstream this changes ASAP, but for the 4.0 release, this should suffice to get proper shutdown handling in LocalStack even if a library is loaded using jpype.
* Use jpype-ext, published with the changes here: https://github.com/localstack/jpype/pull/1
* Set `interrupt=False` when starting jpype
> Use jpype-ext and set jpype interrupt=False

- localstack-core/localstack/services/events/provider.py
- localstack-core/localstack/services/lambda_/invocation/event_manager.py
- localstack-core/localstack/utils/aws/message_forwarding.py
- tests/aws/cdk_templates/LambdaDestinationEventbridge/EventbridgeStack.json
- tests/aws/services/apigateway/test_apigateway_eventbridge.validation.json
- tests/aws/services/cloudformation/resources/test_events.py
- tests/aws/services/cloudformation/resources/test_events.validation.json
- tests/aws/services/events/test_events.py
- tests/aws/services/events/test_events.snapshot.json
- tests/aws/services/events/test_events.validation.json
- tests/aws/services/lambda_/test_lambda_destinations.py
- tests/aws/services/lambda_/test_lambda_destinations.snapshot.json
- tests/aws/services/lambda_/test_lambda_destinations.validation.json
Addressing a few issues we observed with the new EventBridge v2 provider and the existing test suite.
- `test_cfn_handle_events_rule` ... invalid legacy test => removed
- `test_cfn_handle_events_rule_without_name` ... invalid legacy test => removed
- `test_apigateway_to_eventbridge` ... fixed by not just ignoring the event if there's no rule configured
- validated test added for missing detail type => `test_put_event_without_detail_type`
- `test_eventbus_policy_statement` & `test_eventbus_policies` ... fixed via the `json.dumps` on the policy
- `test_invoke_lambda_eventbridge` ... fixed by using the proper `"detail-type"` for the event sent to EventBridge in Lambda EventBridge destinations. Adapted the behavior test to surface the raw event payload and remove the intermediate SQS queue
> Fix validated events test for v2 provider 

- tests/aws/services/cloudformation/resources/test_lambda.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.py
- tests/unit/utils/test_event_matcher.py
We can't start both the JPype-based java rule engine as well as other JPype-based features in the same run, so we can't parametrize on this. If really necessary it would need to be added as a separate pipeline/test run.
- Skip unit tests that would use the java rule engine
- Conditionally skip tests instead of monkeypatching java rule engine in integration tests
> Prevent usage of java rule engine in tests

- localstack-core/localstack/config.py
- localstack-core/localstack/utils/bootstrap.py
- tests/bootstrap/test_container_configurators.py
As announced in https://github.com/localstack/localstack/issues/11803, with LocalStack 4.0 we are deprecating the usage of non-prefixed environment variables in the CLI:
> The LocalStack CLI is closely integrated with the runtime and needs to be able to determine which environment variables it should pass from the user's environment to the Docker container. This requirement restricts the CLI’s compatibility with new environment variables introduced in later LocalStack versions, often leading to issues that are challenging to debug. Using a well-known prefix (`LOCALSTACK_`) will enable forwards-compatibility for newer configuration options. To enhance flexibility, users are encouraged to use a variable prefix (`LOCALSTACK_`) for more straightforward management of environment variables …
> deprecate env vars without prefix in CLI

- localstack-core/localstack/aws/api/s3/__init__.py
- localstack-core/localstack/services/s3/exceptions.py
- localstack-core/localstack/services/s3/provider.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/aws/services/s3/test_s3.validation.json
Closes #11826
Implement the ExpectedBucketOwner parameter and its behavior in 3 S3 operations: 
- PutBucketPolicy
- GetBucketPolicy 
- DeleteBucketPolicy. 
This parameter is currently ignored in LocalStack S3.
> ExpectedBucketOwner for S3 bucket policy operations

- localstack-core/localstack/runtime/analytics.py
Paths might contain sensitive information, so we had better only track its presence.
Switch to presence detection rather than tracking the path value.
Could such a switch cause data analytics/quality challenges in Tinybird @ackdav ?
> Switch Lambda debug path analytics to presense

- .circleci/config.yml
- localstack-core/localstack/deprecations.py
- localstack-core/localstack/services/events/event_bus.py
- localstack-core/localstack/services/events/scheduler.py
- localstack-core/localstack/services/events/target.py
- localstack-core/localstack/services/providers.py
- tests/aws/services/events/helper_functions.py
- tests/aws/services/events/test_events.py
- tests/aws/services/events/test_events.snapshot.json
- tests/aws/services/events/test_events.validation.json
Depends on https://github.com/localstack/localstack/pull/11852
Upon v4, we plan to switch EventBridge's default provider from the current default v1 using a moto-fallback to the new LocalStack-native v2 provider. The new v2 provider offers better internal API integrations, API coverage, and generally improved AWS parity, especially for behavior.
Why minor?
We tend to ship new providers serving as drop-in replacements as minor and EventBridge v2 can be considered a drop-in replacement (i.e., a better LocalStack-native version of v1 without regressions requiring user changes).
* Switch default provider from v1 to v2
* Add `legacy` as a possible fallback config in line with other service deprecations such as APIGatewayv2 (see PR change …
> Make EventBridge v2 provider default

- localstack-core/localstack/utils/analytics/usage.py
When we create usage trackers, empty payloads are always generated, they'd look like this: `{'cognito:endpoints': {}}`. Sending empty data payloads is not helpful and causes unnecessary data usage, so this PR removes those.
* empty payloads are now removed when calling `aggregate` on usage set statistics
> fix usage aggregation to not send empty payloads

- localstack-core/localstack/services/lambda_/usage.py
- localstack-core/localstack/utils/analytics/usage.py
Follow up from #11848, with more changes to our counters.
This PR implements a simpler `UsageCounter` which does not need aggregation, as it only counts. 
To keep the current already implemented logic, which is more resembling the `timing` metric types of `statsd`, I've renamed it to `TimingStats` (naming TBD, it could also be NumericStats or anything?). 
The new `UsageCounter` is very memory efficient, and it relies on `itertools.count` which is thread safe in CPython, removing the need for an external locking mechanism. 
Statsd metrics types:
https://github.com/statsd/statsd/blob/master/docs/metric_types.md
- refactor our counters to have a very simpler counter and more complex one with aggregations for more complex use cases
- modify the usage in lambda so that it uses the simple …
> Split analytics UsageCounter and TimingStats

- localstack-core/localstack/services/sns/provider.py
- localstack-core/localstack/services/sns/usage.py
As part of our effort to improve our analytics, this PR implements usage counters for SNS internal routes.
We can now properly have usage data on SNS internal routes invocations, to understand their usage better. 
Usage is separated on what the internal route is targeting, be it Platform Endpoint messages, SMS messages or Subscription Tokens (useful for example for email subscriptions). 
- implement analytics for SNS internal routes via a base class + decorator on routes
> add analytics for SNS internal routes

- localstack-core/localstack/services/apigateway/legacy/templates.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/template_mapping.py
- localstack-core/localstack/utils/aws/templating.py
- tests/aws/services/apigateway/test_apigateway_basic.py
- tests/aws/services/apigateway/test_apigateway_kinesis.py
- tests/aws/services/apigateway/test_apigateway_kinesis.snapshot.json
- tests/aws/services/apigateway/test_apigateway_kinesis.validation.json
While investigating the issue reported by #11843, I noticed that the default returned value of unfound variables differs between apigateway and appsync. We had this patch working for apigateway, but it would unfortunately fail some appsync functions that are expecting to receive a null value.
- Augmented the signature of `prepare_namespace` to allow setting a `source`.
- Patch only if the source is apigateway
- Reimplemented the template used by the previous test reffered in the comment
_fixes #11843_
> fix vtl resolver patch

- localstack-core/localstack/services/events/provider.py
- tests/aws/services/events/test_events.py
- tests/aws/services/events/test_events.snapshot.json
- tests/aws/services/events/test_events.validation.json
Fixes EventBridge PutEvents response so it correctly returns event IDs only once per event, regardless of how many rules or targets match. Currently, the response includes duplicate EventIds for each matching target, which doesn't match AWS behavior and can cause issues when clients try to track events by their IDs.
Related issue: https://github.com/localstack/localstack/issues/11597
- Modified `_process_entries` and related methods in events provider to track and return event IDs only once
- Refactored event processing logic to maintain a single event result per input event
- Added test case to verify the fix and prevent regressions
1. Create an EventBridge rule with multiple targets
2. Send an event that matches the rule
3. Verify that:
- PutEvents response contains each EventId only …
> Put events fix for multiple targets

- localstack-core/localstack/packages/java.py
This PR resolves the issue with Java home retrieval on macOS. For the temurin Java distribution, the Java home directory on macOS resides in <install-dir>/Contents/Home. This discrepancy caused errors in big data services when running in host mode.
Updated the logic for Java home retrieval on macOS to accommodate the temurin distribution structure.
> fix java home for macos

- localstack-core/localstack/services/events/models.py
- localstack-core/localstack/services/events/provider.py
- localstack-core/localstack/services/events/target.py
- localstack-core/localstack/services/events/target_helper.py
- localstack-core/localstack/services/secretsmanager/provider.py
- localstack-core/localstack/testing/snapshots/transformer_utility.py
- tests/aws/services/events/conftest.py
- tests/aws/services/events/test_events.py
- tests/aws/services/events/test_events.snapshot.json
- tests/aws/services/events/test_events.validation.json
In the current v2 provider, we do not support eventbridge API destinations.
As we do want this in 4.0.1, and I am unsure if we should do such a big code change, I staggered the commits in terms of escalating changes / complexity.
93822dd has the minimal changes necessary to make the feature work, we could cherry pick that into a separate PR.
After this commit, we increasingly increase parity, with more snapshots, creation of eventbridge secrets, bypass of secretmanager name assertions (since official EventBridge secrets contain a `!` in the name).
It might be too much for a release tomorrow, but I will let the reviewers judge that.
* Allow persistence for connections and api destinations by moving them into the store (very simply, without dataclasses as for other models)
* Detect API …
> Enable EventBridge API destinations and connections

- localstack-core/localstack/services/events/archive.py
- localstack-core/localstack/services/events/provider.py
Currently, ArchiveServices have quite some side effects in its constructor.
This prevents us from avoiding those side effects when we want to restore those services from data in the store (for cloudpods or persistence).
With this PR, we split out the logic out of the constructor, to allow instantiation without side effects.
* Remove boto calls from the ArchiveService constructor
* Refactor a bit to manually trigger rule/target registration
> Refactor EventBridge ArchiveServices to allow restoration without side effects

- localstack-core/localstack/services/events/provider.py
- localstack-core/localstack/services/events/utils.py
- tests/aws/services/events/test_events.py
- tests/aws/services/events/test_events.validation.json
`put_targets` does not validate invalid inputs for `target_id`, which is a regression compared to EventBridge v1.
* Add validation exceptions for `put_targets`
> Fix put_targets validation regressions

- tests/unit/services/stepfunctions/test_arguments.py
- tests/unit/services/stepfunctions/test_query_language_parsing.py
Temporarily disabling (read: commenting out) affected unit tests.
There's an invalid import in there that we need to take a look at later. @MEPalma @gregfurman
> Disable selected StepFunctions unit tests due to broken imports

- localstack-core/localstack/services/stepfunctions/provider.py
The ASF provider signature check unit test was failing for the `test_state` method in the StepFunctions provider.
This PR addresses the issue by making sure the signatures are aligned
> Fix provider signature for StepFunctions TestState operation

- localstack-core/localstack/services/stepfunctions/asl/jsonata/jsonata.py
Started seeing issues regarding JVM in the latest container:
```
...
instance.set(factory())
^^^^^^^^^
File "/opt/code/localstack/localstack-core/localstack/services/stepfunctions/asl/jsonata/jsonata.py", line 64, in get
return _JSONataJVMBridge()
^^^^^^^^^^^^^^^^^^^
File "/opt/code/localstack/localstack-core/localstack/services/stepfunctions/asl/jsonata/jsonata.py", line 50, in __init__
jvm_path = jpype.getDefaultJVMPath()
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jpype/_jvmfinder.py", line 70, in getDefaultJVMPath
return finder.get_jvm_path()
^^^^^^^^^^^^^^^^^^^^^
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jpype/_jvmfinder.py", line 204, in get_jvm_path
raise JVMNotFoundException("No JVM shared library file ({0}) "
``` …
> Fix JVM startup for StepFunctions

- localstack-core/localstack/services/lambda_/runtimes.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/aws/services/lambda_/test_lambda_api.validation.json
- tests/aws/services/lambda_/test_lambda_common.snapshot.json
- tests/aws/services/lambda_/test_lambda_common.validation.json
- tests/aws/services/lambda_/test_lambda_runtimes.snapshot.json
- tests/aws/services/lambda_/test_lambda_runtimes.validation.json
AWS recently added the nodejs22.x runtime: https://aws.amazon.com/blogs/compute/node-js-22-runtime-now-available-in-aws-lambda/
We want to support this inside LocalStack as well.
Fixes #11901
* Creation of nodejs22.x lambdas is now available
* Update snapshot tests to keep parity with AWS
> Add nodejs22.x AWS Lambda runtime

- localstack-core/localstack/services/iam/iam_patches.py
- localstack-core/localstack/services/iam/provider.py
- localstack-core/localstack/services/sts/provider.py
- tests/aws/services/iam/test_iam.py
Currently, if we are using STS (especially the assume-role and assume-role-with-web-identity operations) without ever having loaded IAM (e.g. by referencing a non-existent role in a service like AWS Lambda), we do not have the patches applied patching the access key id format.
This leads to access key ids starting with an `A` and not a `L`, which leads to the credentials being ignored, unless `PARITY_AWS_ACCESS_KEY_ID=1` is set.
IAM and STS are coupled tightly in moto, which is why the patching of IAM affects STS access key ids.
* Prevent IAM patches from loading multiple times
* Apply IAM patches when STS is loaded
> Apply IAM patches when loading STS to avoid wrong access key formats

- localstack-core/localstack/services/apigateway/helpers.py
- tests/aws/files/openapi.cognito-auth.json
- tests/aws/services/apigateway/test_apigateway_import.py
- tests/aws/services/apigateway/test_apigateway_import.snapshot.json
- tests/aws/services/apigateway/test_apigateway_import.validation.json
Our current implementation of the OpenApi import did not add authorization scopes when creating a method with an authorizer. This was not an issue with Legacy apigw, as we did not handle the scopes properly.
Authorization scopes can be added to Cognito authorizers. They directly impact whether the api accepts an Identity token or an Access Token see [docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html). As Next Gen provider does enforce this, providing a greater compatibility with aws, user's configs would fail to authorize a request when an Access token is used to authenticate.
- Get the scopes from the default authorizer or the method if specified
- Added tests
> Apigw fix openapi identity sources

- localstack-core/localstack/services/stepfunctions/provider.py
- tests/aws/services/stepfunctions/v2/test_sfn_api_activities.py
- tests/aws/services/stepfunctions/v2/test_sfn_api_activities.snapshot.json
- tests/aws/services/stepfunctions/v2/test_sfn_api_activities.validation.json
Currently, the SFN v2 provider applies faulty activity arn and name validation logics, which can result is `InvalidName` exceptions during activity creation and especially during `DescribeActivity` api actions. This is espiecially true for activity names that contain punctuations,  as described in https://github.com/localstack/localstack/issues/11916. This is due to the activity arn validation not being aligned with AWS SFN and the activity name validation (used on creation). These changes address both issues and add positive and negative snapshot tests for the creation deletion and description of activity names and arns.
- positive and negative activity name/arn tests
- updated activity arn validation rule
- updated activity name validation logic to check for maximum name lenght
> [SFN] Activity Name and Arn Validation Logic

- localstack-core/localstack/packages/java.py
This is a follow up PR to https://github.com/localstack/localstack/pull/11888#issuecomment-2490739229. @maxhoheiser [reported a bug](https://github.com/localstack/localstack/pull/11888#issuecomment-2490739229) where java lib path was not properly generated.
Thanks @maxhoheiser for reporting.
- Updated java lib path for macos to not include `/Contents/Home` since it's already included in the java home.
> fixed java lib path for macos

- localstack-core/localstack/utils/patch.py
- tests/unit/utils/test_patch.py
Our `patch` decorator easily allows us to patch a class method and extend its behavior.
However, it does not support the case where a given type does not implement a function and we want to add it.
Patch now would support the following use case:
```python
@patch(MyClass)
def new_method(self, *args):
...
c = MyClass()
c.new_method()
```
If the class already implements a method with the given name, the patch won't have any effect.
Like our current implementation, a patch can be easily undone:
```python
new_method.patch.undo()
c.new_method() # raises AttributeError
```
- Extending `patch` to support the use case of adding a new function to a class type;
- Unit tests to verify the behavior of the new use case.
> Extend patch decorator to add methods to class types

- localstack-core/localstack/runtime/analytics.py
- localstack-core/localstack/services/events/plugins.py
- tests/aws/services/events/test_events_patterns.py
Supersedes https://github.com/localstack/localstack/pull/11807
We are missing analytics tracking for the event ruler and a plugins.py to make the package installable (if we decide to ship it). Currently, we don't see the need for shipping it as the Java-based event ruler is opt-in.
* Add env var tracking for `EVENT_RULE_ENGINE`
* Make `event-ruler` package installable (in case we need to ship it to unblock users facing dynamic installation issues)
> Add analytics for event rule engine

- localstack-core/localstack/services/events/provider.py
Re-introduce rule error analytics accidentally removed in https://github.com/localstack/localstack/pull/11880 (likely during rebasing with conflicts)
> Re-introduce error analytics for EventBridge rule error

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_event_processor.py
- localstack-core/localstack/services/lambda_/event_source_mapping/senders/lambda_sender.py
- localstack-core/localstack/services/lambda_/event_source_mapping/senders/sender.py
- localstack-core/localstack/services/lambda_/usage.py
- localstack-core/localstack/utils/analytics/usage.py
- tests/unit/utils/analytics/test_usage.py
Add usage analytics for Lambda ESM to learn more about potential errors we should tackle and usage of different event sources.
* Add usage analytics for `invocation` (successful ones) and `error` (unexpected error; i.e., LS bug)
* Add unit test for existing set counter (also serves to exemplify usage)
> Add lambda ESM analytics

- localstack-core/localstack/utils/bootstrap.py
- tests/bootstrap/test_container_configurators.py
With https://github.com/localstack/localstack/pull/11810 we deprecated the forwarding of not-explicitly-prefixed environment variables from the system environment to the runtime environment.
However, this is definitely a change which will take quite a while to reach all our users.
In order to get an idea where we are, this PR adds a simple analytics log which tracks the environment variables (only those marked as "known" by the CLI and only the name and not the content) which are affected by this deprecation.
- Add a simple analytics log message to the deprecation check to help us gain knowledge on the adoption of env var prefix.
> analytics for non-prefixed env var forwarding in CLI

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_event_processor.py
It seems #11883 has broken downstream dependencies, related to Kafka not having the same format (sending a dict when the signature is `list[dict]`). Tests are failing and are not validated against AWS, so I suppose we're supposed to be able to accept `dict` directly to `process_events_batch` as `input_events`. 
- add more safety around trying to access `first_event`
> fix ESM analytics

- localstack-core/localstack/openapi.yaml
- localstack-core/localstack/services/ses/models.py
This PR fixes a minor gap in our SES OpenAPI specs.
In particular, the `htlm_part` property in the response to `GET /_aws/ses` can be `null`. 
This issue was detected by @HarshCasper when using the SDK generated from the spec (as the generated Pydantic model does not expect a null value).
- Change `html_part` to nullable in the specs.
> Handle null value in SES OpenAPI spec

- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_lambda.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/state_task_lambda.py
- tests/aws/services/stepfunctions/templates/errorhandling/error_handling_templates.py
- tests/aws/services/stepfunctions/templates/errorhandling/lambdafunctions/raise_custom_exception.py
- tests/aws/services/stepfunctions/templates/errorhandling/statemachines/task_lambda_invoke_catch_tbd.json5
- tests/aws/services/stepfunctions/templates/errorhandling/statemachines/task_service_lambda_invoke_catch_tbd.json5
- tests/aws/services/stepfunctions/v2/error_handling/test_task_lambda.py
- tests/aws/services/stepfunctions/v2/error_handling/test_task_lambda.snapshot.json
- tests/aws/services/stepfunctions/v2/error_handling/test_task_lambda.validation.json
- tests/aws/services/stepfunctions/v2/error_handling/test_task_service_lambda.py
- tests/aws/services/stepfunctions/v2/error_handling/test_task_service_lambda.snapshot.json
- tests/aws/services/stepfunctions/v2/error_handling/test_task_service_lambda.validation.json
Currently, the SFN v2 interpreter incorrectly assigns the error name "Exception" to Lambda task failures that result in a LambdaFunctionErrorException, rather than utilising the exception's errorType value. This limitation prevents users from catching or retrying Lambda task failures using custom exception values, as reported in [this issue](https://github.com/localstack/localstack/issues/11943). These changes address the error name computation, correcting the behaviour, and introduce relevant tests for both legacy Lambda invocations and service task Lambda invocations.
- revised error name computation for legacy task lambda states
- revised error name computation for service task lambda states
- added related snapshot tests
> StepFunctions: Fix ErrorName Value for Lambda Task Errors

- localstack-core/localstack/aws/api/events/__init__.py
- localstack-core/localstack/services/events/utils.py
- tests/aws/services/events/test_events.py
- tests/aws/services/events/test_events.snapshot.json
- tests/aws/services/events/test_events.validation.json
Found through an issue: https://github.com/localstack/localstack/issues/11630
When using EventBridge v2, events containing datetime fields fail to be delivered due to JSON serialization error: `Object of type datetime is not JSON serializable`. This affects events with explicit Time fields as well as automatically generated timestamps.
- Added `format_event_time` function to properly format datetime objects to ISO8601 strings
- Updated `format_event` to use the formatted time string
- Added test to verify datetime serialization and delivery behavior matches AWS
The fix ensures proper datetime handling in events while maintaining AWS parity by formatting all time values to ISO8601 strings (YYYY-MM-DDThh:mm:ssZ).
> Added test and fix for wrong time format and serialization in events v2

- localstack-core/localstack/services/stepfunctions/asl/static_analyser/usage_metrics_static_analyser.py
- localstack-core/localstack/services/stepfunctions/provider.py
- localstack-core/localstack/services/stepfunctions/usage.py
- tests/aws/services/stepfunctions/v2/evaluate_jsonata/test_base_evaluate_expressions.py
- tests/unit/services/stepfunctions/test_usage_metrics_static_analyser.py
This PR adds analytics  the SFN provider to help ascertain usage of the new JSONata and Variable workflows. 
- Add a static analyser that will check for:
-  Any variable sampling or assigning of variables
- The query language being used by the state machine definition
- Metrics have been added that will record whether a sfn uses JSONata or variable workflows, respectively. 
- Added unit tests to ensure the static analysis is correct.
> [SFN] Add usage analytics for Variable Workflow and JSONata features

- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/sqs_poller.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.validation.json
- tests/aws/services/lambda_/functions/lambda_event_source_mapping_send_message.py
- tests/aws/services/lambda_/test_lambda.py
This PR fixes CRUD issue where an SQS ESM's batch size exceeding 10 elements raises an exception on polling.
- Fixes bug when creating an SQS mapping that prevented a `BatchSize` of greater than `10` elements.
- Added snapshot tests for varying batch sizes.
> [ESM] Fix polling of SQS queue when batch size exceeds 10

- localstack-core/localstack/config.py
- localstack-core/localstack/deprecations.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/poller.py
Depends on https://github.com/localstack/localstack/pull/11960
The Java-based event ruler is deprecated because our latest Python-native implementation introduced in 4.0.3 is faster, achieves great AWS parity, and fixes compatibility issues with the StepFunctions JSONata feature.
* Deprecate `EVENT_RULE_ENGINE` config used for opt-into the Java-based event ruler
* Remove unused `POLL_INTERVAL_SEC`
We now have a comprehensive test suite and can be confident that (almost) all cases are covered.
> Add deprecation for Java-based event ruler

- localstack-core/localstack/openapi.yaml
This PR is a follow-up fix for https://github.com/localstack/localstack/pull/11954.
It turns out that our code generator needs the change in this PR to output the right Pydantic model, i.e.,
```python
class SesSentEmailBody(BaseModel):
"""
SesSentEmailBody
""" # noqa: E501
html_part: Optional[StrictStr] = None
text_part: StrictStr
```
Setting the type to `null` did not lead to the wanted generated code (i.e., `html_part` won't be optional).
- Minor fix of the specs;
> fix: follow-up for null value in SES response

- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/mock.py
- tests/aws/services/apigateway/test_apigateway_integrations.py
- tests/aws/services/apigateway/test_apigateway_integrations.snapshot.json
- tests/aws/services/apigateway/test_apigateway_integrations.validation.json
- tests/unit/services/apigateway/test_mock_integration.py
When deploying a CDK stack with an APIGW REST API with "automatic" CORS management by APIGW, CDK will create an OPTIONS `method` with a MOCK integration. The problem is that this integration has a request template equal to `"application/json": "{statusCode: 200}"`, which is invalid JSON. 
From the documentation, nothing lets you think that invalid JSON would be accepted, as it needs the `statusCode` field. 
But it does, they don't JSON parse but use a custom token parser that we're tried to test the limit off. We're settling now on this basic implementation which still has flaws, but cover quite some ground already, as shown by the unit tests. We also updated an integration test to specifically cover the request template CDK was using. 
This custom parser will only be executed if the MOCK …
> APIGW: fix parsing invalid JSON template in MOCK integration

- .github/workflows/tests-pro-integration.yml
This PR fixes the [Community Integration Tests against Pro](https://github.com/localstack/localstack/actions/workflows/tests-pro-integration.yml) which are meant to inform us about changes that break our downstream project early.
This pipeline failed with the recent upgrade of the GitHub Runner to Ubuntu 24.04.
- Removes the installation of `postgres` and related tools because they should not be necessary when running the Community Tests against Pro, and if they are needed they should be installed on demand by the respective package installer.
> fix postgres install in pro test pipeline

- localstack-core/localstack/services/sns/filter.py
- tests/aws/services/events/event_pattern_templates/exists_list_empty_NEG.json5
- tests/aws/services/events/test_events_patterns.snapshot.json
- tests/aws/services/events/test_events_patterns.validation.json
- tests/aws/services/sns/test_sns_filter_policy.py
- tests/aws/services/sns/test_sns_filter_policy.snapshot.json
- tests/aws/services/sns/test_sns_filter_policy.validation.json
- tests/unit/test_sns.py
When implementing the EventRuleEngine with #11960, I've implemented different and new behaviors from SNS, and some felt like we just missed them in SNS and were better covered by the event test suite. 
This PR implements the [`cidr` operator](https://docs.aws.amazon.com/sns/latest/dg/string-value-matching.html#string-address-matching), and a missed edge case where one of the field of the payload is an empty array. Also adds a bit of validation around empty list passed to operators. 
Sorry @maxhoheiser and @joe4dev, I've sneaked in a new test case for the EventRuleEngine here as I wanted to verify a very edge case behavior in both engine when the value is an empty array, making the field not exists, which is an edge case we're also having, which is somewhat funny. I didn't want to open a …
> SNS: improve SNS Filter Policy engine and implement `cidr` operator

- .github/workflows/asf-updates.yml
This PR upgrades the version of `mad9000/actions-find-and-replace-string`.
This action is somehow not updated by dependabot, which is why we are doing it manually to avoid issues in the future (GitHub is has deprecated Node 16 support a long time ago):
- Upgrades `mad9000/actions-find-and-replace-string` to version 5
> upgrade outdated github action in ASF update workflow

- localstack-core/localstack/services/events/event_rule_engine.py
- tests/aws/services/events/event_pattern_templates/content_ip_address_bad_ip_EXC.json5
- tests/aws/services/events/event_pattern_templates/content_ip_address_bad_mask_EXC.json5
- tests/aws/services/events/event_pattern_templates/content_ip_address_type_EXC.json5
- tests/aws/services/events/event_pattern_templates/content_ip_address_v6.json5
- tests/aws/services/events/event_pattern_templates/content_ip_address_v6_NEG.json5
- tests/aws/services/events/event_pattern_templates/content_ip_address_v6_bad_ip_EXC.json5
- tests/aws/services/events/test_events_patterns.snapshot.json
- tests/aws/services/events/test_events_patterns.validation.json
After backporting `cidr` back to SNS, @cloutierMat made a really solid point in his review: 
https://github.com/localstack/localstack/pull/11979#discussion_r1868383162
After improving it for SNS, I'm backporting it back again to `events`
- add `cidr` support for IPv6, and better validation
> Events: EventRuleEngine: improve `cidr` to support ipv6 and better validation

- tests/aws/services/sns/test_sns_filter_policy.py
- tests/aws/services/sns/test_sns_filter_policy.snapshot.json
- tests/aws/services/sns/test_sns_filter_policy.validation.json
New tests implemented with #11979 had quite the flaw, which was hardcoded region values in the event, even if not relevant to the test itself. 
This PR removes the region values. 
- remove the region values in the test and make sort the snapshot as the queue is not FIFO
> fix SNS test with region replacement

- localstack-core/localstack/services/events/resource_providers/aws_events_rule.py
- tests/aws/services/cloudformation/resources/test_events.py
- tests/aws/services/cloudformation/resources/test_events.snapshot.json
- tests/aws/services/cloudformation/resources/test_events.validation.json
- tests/aws/templates/events_rule_pattern.yml
Adresses #11537. This PR extends the list of attributes that need to be converted in a EventPattern inside the resource provider for AWS::Events::Rule
Operations added are found in this [AWS doc](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-pattern-operators.htm)
- simple addition of operations to the list of atts to be converted
- new aws validated test.
> fix transformation for matching operations in aws::events::rule

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker_factory.py
We need to handle the case where a synchronous Lambda invocation runs for an extended period of time -- ensuring the TCP socket remains open and alive.
See https://github.com/boto/boto3/issues/2424
- Adds defaults for `connect_timeout`, `read_timeout`, `tcp_keepalive`, and `retries` in the client for the ESM lambda sender 
- Since a Lambda can run for 900s, we will only throw an exception once this timeout is reached.
- In addition, we specify `tcp_keepalive=True` which ensures the TCP connection does not drop prior to timeout.
> [ESM] Handle Lambda TCP socket connection timeouts

- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/aws/services/lambda_/test_lambda_api.validation.json
Although the AWS docs indicates we can use a [`DestinationConfig` object's `OnSuccess`](https://docs.aws.amazon.com/lambda/latest/api/API_DestinationConfig.html#lambda-Type-DestinationConfig-OnSuccess) in ESM, this is actually not supported. This PR adds a parity test and raises an exception for the aforementioned case.
- Added parity test with raised exception
- Raise exception in LS on ESM validation
> [ESM] Raise exception when setting DestinationConfig.OnSuccess

- localstack-core/localstack/testing/pytest/fixtures.py
- tests/aws/services/opensearch/test_opensearch.py
- tests/aws/services/opensearch/test_opensearch.snapshot.json
- tests/aws/services/opensearch/test_opensearch.validation.json
This PR introduces a parity test case to verify that the "opensearch-sql" plugin is installed on newly created domains and functions as expected.
- Added test_sql_plugin test
- Modified _wait_for_cluster fixture to better adapt with AWS behavior
Part of the code from the test_sql_plugin test is reusable and could serve as a replacement for some of the existing fixtures used in tests marked with needs_fixing, once those tests are addressed.
> added sql plugin validated test

- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_events.py
- tests/aws/services/stepfunctions/v2/services/test_events_task_service.py
- tests/aws/services/stepfunctions/v2/services/test_events_task_service.snapshot.json
- tests/aws/services/stepfunctions/v2/services/test_events_task_service.validation.json
This PR fixes the construction of EventsBridge PUT failures -- as well as recording them to the execution history. Relies on changes in https://github.com/localstack/localstack/pull/11990
- Remove skips on events tests.
- Adds another test to ensure we can handle the mixed case where some entries are malformed and some are valid.
- Pass the PUT response as the cause of the failure event when constructing failed events.
> [SFN] Correctly record failed EventsBridge PUT requests

- localstack-core/localstack/services/events/target.py
- localstack-core/localstack/testing/pytest/fixtures.py
- tests/aws/services/events/conftest.py
- tests/aws/services/events/test_archive_and_replay.py
- tests/aws/services/events/test_events.py
- tests/aws/services/events/test_events_inputs.py
- tests/aws/services/events/test_events_patterns.py
- tests/aws/services/events/test_events_schedule.py
- tests/aws/services/events/test_events_targets.py
- tests/aws/services/ssm/test_ssm.py
This PR adds the ability to extend the TargetSenderFactory by targets defined in localstack-pro.
Furthermore, it makes testing fixtures available to localstack-pro
Since ECS is a pro feature, the aws validated test can be found in the companion branch.
> Feature/Eventbridge v2: Support extending available targets

- localstack-core/localstack/services/stepfunctions/asl/component/intrinsic/function/statesfunction/string_operations/string_split.py
- tests/aws/services/stepfunctions/v2/intrinsic_functions/test_string_operations.py
- tests/aws/services/stepfunctions/v2/intrinsic_functions/test_string_operations.snapshot.json
- tests/aws/services/stepfunctions/v2/intrinsic_functions/test_string_operations.validation.json
The `StringSplit` function allows to split on any of the character provided by the second argument. The current code was manually escaping each character, appending `\\` to it. While allowing for the most common special characters delimiter, the unfortunate side effect is that digits and letters would be incorrectly escaped.
- update the `StringSplit` function to use `re.escape` instead for a safe escaping experience
- perform the `join` directly on the list comprehension for a small performance upgrade
> fix StringSplit regex escape

- localstack-core/localstack/config.py
- localstack-core/localstack/services/sns/publisher.py
- tests/aws/services/sns/test_sns.py
As reported by #11850, some SDK will verify the `SigningCertURL` field host part even if not validating the messages. 
This PR introduces a config flag to allow the user to set the host of the `SigningCertURL` to pass those regex pattern, even if the host is then non-resolvable, it should at least unblock the user, as they confirmed this would be sufficient for their use case. 
- add a config flag `SNS_CERT_URL_HOST` to allow the user the set the host to an arbitrary value
- create a test to validate SNS is properly using that value
_fixes #11850_
> make SNS `SigningCertURL` configurable even if not resolvable

- localstack-core/localstack/services/events/event_rule_engine.py
- localstack-core/localstack/services/events/provider.py
- tests/aws/services/events/event_pattern_templates/numeric-int-float.json5
- tests/aws/services/events/event_pattern_templates/numeric-null_NEG.json5
- tests/aws/services/events/event_pattern_templates/numeric-string_NEG.json5
- tests/aws/services/events/event_pattern_templates/or-numeric-anything-but.json5
- tests/aws/services/events/event_pattern_templates/or-numeric-anything-but_NEG.json5
- tests/aws/services/events/test_events_patterns.py
- tests/aws/services/events/test_events_patterns.snapshot.json
- tests/aws/services/events/test_events_patterns.validation.json
As reported in #11992, there might have been issue with the new engine rule engine.
I could only reproduce the `test_dynamodb_event_filter[numeric_filter]` failure, which was due to our bad handling of `numeric` logic with string values. 
While validating the fix and the handling of the new EventRuleEngine for `test_sqs_event_filter[this is a test string]`, the behavior was right, but the validation for `TestEventPattern` was wrong. 
I've also validated that `test_dynamodb_event_filter[numeric_filter]` now works with the fix 👍 
Then, when validating the DynamoDB fix, I've tried to copy-paste the input event from ESM, but it failed when calling `TestEventPattern` because the event was not following the right format, so I've added it in the provider to also validate this, as specified by …
> Events: fix `numeric` operator string handling and provider validation for TestEventPattern

- localstack-core/localstack/services/lambda_/provider.py
- localstack-core/localstack/services/lambda_/runtimes.py
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/aws/services/lambda_/test_lambda_api.validation.json
Recently, AWS announced support for additional runtimes for using SnapStart: https://aws.amazon.com/blogs/aws/aws-lambda-snapstart-for-python-and-net-functions-is-now-generally-available/
However, while investigating this change, it seems that over the API the feature is available for all runtimes, not just the announced ones.
Whether this is a temporary error, or a hint that additional runtimes could get supported in the future, I removed the runtime validation for snapstart creation and updates, and added aws-validated tests for all runtimes to show it is indeed possible to create them.
I did some more investigation, and it seems like SnapStart is even (somewhat) functioning, at least an initial initialization of the function potentially takes place (if you misconfigure the function, it …
> Allow usage of additional runtimes with the Lambda SnapStart feature enabled

- localstack-core/localstack/services/cloudwatch/alarm_scheduler.py
- localstack-core/localstack/services/cloudwatch/models.py
- localstack-core/localstack/services/cloudwatch/provider_v2.py
- tests/aws/services/cloudwatch/test_cloudwatch.py
- tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json
- tests/aws/services/cloudwatch/test_cloudwatch.validation.json
Add basic support for [composite alarms](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Create_Composite_Alarm.html) evaluation in Cloudwatch. Currently composite alarms can be saved but there is no evaluation for them, therefore there is no way to get them triggered.
Composite alarm rules will be evaluated now whenever a metric alarm state is changed.
This PR adds limited support for alarm rules:
- Alarms can be referred to by ARNs only (no alarm names support yet)
- It is assumed that only OR logic is applied for all child alarms
- Suppression logic for child alarms is not implemented
- Composite alarm actions only support a message to an SNS topic
- Only metric alarms can be child alarms, nesting of a composite ones is not supported yet
Example of supported rule: …
> Cloudwatch: add basic composite alarm support

- docs/testing/integration-tests/README.md
- localstack-core/localstack/testing/pytest/in_memory_localstack.py
To enable testing for the replicator, we need a mechanism by which we can start a localstack instance when running test against AWS. This change will allow us to spawn an instance while respecting the devs configuration without having to re:invent the wheel.
- Look at env `TEST_FORCE_LOCALSTACK_START` to create instance even if `is_aws_cloud()` is true
> enable localstack instance creation override for testing

- pyproject.toml
- requirements-dev.txt
- requirements-runtime.txt
- requirements-typehint.txt
This PR bumps moto-ext to 5.0.22.post1
Contains:
- https://github.com/getmoto/moto/pull/8338
- https://github.com/getmoto/moto/pull/8335 
closes: https://github.com/localstack/localstack/issues/11635
> Bump moto-ext to 5.0.22.post1

- tests/aws/services/apigateway/test_apigateway_import.py
- tests/aws/services/apigateway/test_apigateway_import.snapshot.json
- tests/aws/services/apigateway/test_apigateway_import.validation.json
As reported by our pipeline here: https://app.circleci.com/pipelines/github/localstack/localstack/30176/workflows/23745dcd-aaf8-4add-84f5-ae041d88e5a0
We had a failure when the run was using the `us-west-1` region, and the automatic snapshot replacement would replace that value with the `<region>` placeholder. 
However, this hardcoded can be kept as is, because it is an actual available endpoint in AWS, and we can't be sure it's available in all regions. The workaround for this is to transform the value with a higher priority that the regular `<region>` transformer, to be sure we always replace the value in the snapshots. 
- add a transformer with higher priority of the external AWS APIGW endpoint
> fix APIGW test with hardcoded region

- localstack-core/localstack/utils/kinesis/kclipy_helper.py
- pyproject.toml
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
- tests/aws/test_integration.py
With https://github.com/localstack/localstack/pull/11829 and https://github.com/localstack/localstack/pull/11245 we introduced some dependency limits which we need to remove to get up-to-date again.
- Remove the pin on `cryptography` and `amazon_kclpy`.
- Upgrade the client config for `amazon_kclpy` to enable "v2 compatibility mode" (to minimize the amount of necessary changes in this PR while fixing the failing tests).
- Extend the timeout for `test_firehose_kinesis_to_s3` as it was already flaky before.
- Migrate the usage of KCL to v3 (since this PR just enables the v2 compat mode).
> upgrade cryptography and amazon-kclpy

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_config_factory.py
- localstack-core/localstack/services/lambda_/provider.py
- localstack-core/localstack/utils/event_matcher.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.py
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/aws/services/lambda_/test_lambda_api.validation.json
Following the introduction of the new python-based filtering engine for events, we can unskip several tests and improve validations of filter criteria when creating/updating ESMs.
- Unskips failing filter criteria tests.
- Adds `validate_event_pattern` to `event_matcher.py`.
- Adds `test_create_event_filter_criteria_validation` to ESM lifecycle tests.
- Fixes parity issue that includes an empty filter criteria object in returned ESM config.
> [ESM] Validate filter criteria and unskip tests

- localstack-core/localstack/testing/snapshots/transformer_utility.py
- tests/aws/services/apigateway/test_apigateway_integrations.snapshot.json
- tests/aws/services/apigateway/test_apigateway_integrations.validation.json
@dfangl encountered a flake in an APIGW test which was quite unlikely, due to a port field (usually `443`) being present in a UUID and breaking the snapshot replacement. 
https://app.circleci.com/pipelines/github/localstack/localstack/30209/workflows/d7b445e5-43ba-4686-8d83-73a0c370d721/jobs/267451/tests
side-note: the content length changing between snapshots might mean we should transform it, it runs against AWS again when run but might change over time. We can always look into it in a follow up
- do not reference replace the forwarded port field as it is not really important to do so, and update the snapshots that are concerned
> fix APIGW transformers to not do value replacement on port

- localstack-core/localstack/services/apigateway/next_gen/execute_api/parameters_mapping.py
- tests/aws/services/apigateway/test_apigateway_api.py
- tests/aws/services/apigateway/test_apigateway_api.snapshot.json
- tests/aws/services/apigateway/test_apigateway_api.validation.json
We've got a report from a user with this stack trace:
```python
2024-12-11 15:56:52   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/next_gen/execute_api/parameters_mapping.py", line 59, in map_integration_request
2024-12-11 15:56:52     if request_mapping.startswith("method.request."):
2024-12-11 15:56:52        ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-11 15:56:52 AttributeError: 'bool' object has no attribute 'startswith'
```
However, it seems the only way we can get to those conditions is by specifying an invalid `requestParameters` object with boolean values. It seems AWS does not accept that, but as we are lacking way to reproduce and to be sure we are not going too far with provider validation, this PR only skips the error for now. 
We need as …
> APIGW: ParameterMapping skip if invalid input

- localstack-core/localstack/services/apigateway/helpers.py
- localstack-core/localstack/services/apigateway/legacy/provider.py
- tests/aws/files/openapi-basepath-url.yaml
- tests/aws/services/apigateway/test_apigateway_import.py
- tests/aws/services/apigateway/test_apigateway_import.snapshot.json
- tests/aws/services/apigateway/test_apigateway_import.validation.json
As reported by a user, if a YAML OpenApi specs passes a Boolean value for request parameter mapping, we would fail the invocation for that integration. 
While the value is invalid, AWS doesn't fail and instead just ignores the parameter when importing the api and adds a warning to the response.
- Make sure that a boolean value cannot be added as an integration request parameters mapping
- adds warnings to the response of the import.
If the flags `failsOnWarning` is provided, we should instead revert the changes when encountering a warning. But this is something we will need to tackle in a follow up as it would require much bigger changes to the import and put endpoints and the helpers method
> apigw fix openapi request parameters

- .github/dependabot.yml
- .github/workflows/asf-updates.yml
This PR adds @silv-io as default reviewer for PRs created with our ASF Update workflows, as well as for PRs created by Dependabot.
- Change config of ASF update action and dependabot to add @silv-io as default-reviewer to all PRs created by these automations.
> add silv-io as default reviewer for upgrade PRs

- localstack-core/localstack/testing/pytest/fixtures.py
The `echo_http_server_post` has different behavior between AWS and LocalStack (where it will direct the request against `https://httpbin.org/post` in AWS and a local http server in LocalStack, but at this url: `http://localhost:<port>//post`).
This PR fixes the format for them to both return the `/post` path. 
I'll run a downstream test on this to verify everything is right. 
- don't add a slash when there's already one returned by `http server.url_for("/")`.
> fix `echo_http_server_post` returning double slash path

- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/job.py
- tests/aws/services/stepfunctions/templates/scenarios/scenarios_templates.py
- tests/aws/services/stepfunctions/templates/scenarios/statemachines/map_state_nested_config_distributed.json5
- tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.py
- tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.snapshot.json
- tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.validation.json
Currently, the SFN v2 is unable to evaluate nested MapRun states, resulting in pickling runtime errors https://github.com/localstack/localstack/issues/9809. This was due to an unecessary deep copy of the map run program, which contains unserialisable objects such as locks. The deep copy is not considered necessary as EvalComponents are stateless by design, and can therefore be shared by multiple runtimes. These changes address such issue and add a relevant snapshot test.
- remove unecessary program copy
- added a snapshot test for nested map runs
> StepFunctions: Fix Evaluation of Nested Map Runs

- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service.py
- tests/aws/services/stepfunctions/v2/services/test_aws_sdk_task_service.py
- tests/aws/services/stepfunctions/v2/services/test_aws_sdk_task_service.snapshot.json
- tests/aws/services/stepfunctions/v2/services/test_aws_sdk_task_service.validation.json
The SFN v2 interpreter incorporates custom logic to convert SFN request parameter objects to ensure compatibility with boto requests, and vice versa. However, this logic currently misencodes JSON strings, occasionally resulting in corrupted JSON objects being sent to the target service https://github.com/localstack/localstack/issues/12030. These changes rectify this issue.
- Fix json object encoding separators and ensure strings are also converted to json string literals
- Updated s3 service integration tests to sample the resulting value for multiple json types
> StepFunctions: Fix Boto Request Encoding

- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/dynamodb_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
Doing a `GetRecords` operation against DynamoDB-local can raise an (undocumented) `Invalid ShardId in ShardIterator` exception. Since we poll a stream in ESM, encountering this sharding issue should necessitate a re-initialise of the shards we are polling.
- Check whether ResourceNotFound exception is of type `Invalid ShardId in ShardIterator`, and trigger a re-sharding if encountered.
> [ESM] Handle DynamoDB-local Invalid ShardID exception

- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.validation.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.validation.json
With @bentsku's new Python-based event filtering engine, we should be able to unskip tests that previously relied on the Java engine but were skipped to avoid JPype conflicts with StepFunctions JSONata.
* Unskip event filtering ESM tests
> Unskip fixed event filtering tests

- tests/aws/services/cloudformation/resources/test_lambda.py
- tests/aws/services/cloudformation/resources/test_lambda.validation.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.validation.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.validation.json
With the many Lambda and ESM v2 improvements, we can unskip tests and enable snapshot validations.
* Unskip supported Lambda and ESM tests
> Unskip supported Lambda and ESM tests

- localstack-core/localstack/services/dynamodb/provider.py
- localstack-core/localstack/services/dynamodb/v2/provider.py
- tests/aws/services/dynamodb/test_dynamodb.py
- tests/aws/services/dynamodb/test_dynamodb.snapshot.json
- tests/aws/services/dynamodb/test_dynamodb.validation.json
This PR resolves the issue: https://github.com/localstack/localstack/issues/11781
Description of issue: The output from the UpdateTable command does not include the SSEDescription for a table which was created with it.
As described by the previous comment on line 781 of localstack-core\localstack\services\dynamodb\provider.py, **DynamoDBLocal cannot change certain table parameters**, including SSEDescription and replica.
As a result, the return value of update_table is a **table returned by DynamoDBLocal, which does not contain these parameters**.
After DynamoDBLocal makes changes to the table, use get_table_schema to **retrieve the entire schema definition of the table, which includes the original and changed parameters.** 
Change return value such that the update_table function returns …
> Bug fix: Dynamodb update_table missing table entries in output

- localstack-core/localstack/services/dynamodb/provider.py
- localstack-core/localstack/services/dynamodb/v2/provider.py
- tests/aws/services/dynamodb/test_dynamodb.py
- tests/aws/services/dynamodb/test_dynamodb.snapshot.json
- tests/aws/services/dynamodb/test_dynamodb.validation.json
This PR fixes a regression caused by https://github.com/localstack/localstack/pull/11938 which would cause an empty list to be returned when no replicas are configured ([reference test run](https://app.circleci.com/pipelines/github/localstack/localstack/30313/workflows/a3d53cf9-5726-4dbb-8fee-5b90a7b60cf5/jobs/268546/tests)). The behaviour is AWS validated by the tests in the reference run.
Randomised MA/MR tests: https://app.circleci.com/pipelines/github/localstack/localstack/30321/workflows/ade8da0d-d52a-453e-8c4f-efc418e5d8c3
> DynamoDB: Fix empty replicas list in response

- pyproject.toml
Fixes https://github.com/localstack/localstack/issues/11703.
As described in the issue, we should update the minimum requirement for the `cbor` library, as we depend on some code which was introduced with `cbor2==5.5.0`.
- Update the minimum version for `cbor`. No other changes are necessary, since in our dependency lock files we already pin the latest version (`5.6.5`).
> bump minimum version of cbor

- localstack-core/localstack/aws/connect.py
It seems our tests broke due to maybe some change in how AWS was returning their DNS records, and it seems we return the full chain of resolution.
When doing the following request:
`request = dns.message.make_query(hostname, "A")`
We would get a full answer containing `CNAME` records:
`[<DNS sts.amazonaws.com. IN CNAME RRset: [<reg.sts-ge.amazonaws.com.>]>, <DNS reg.sts-ge.amazonaws.com. IN CNAME RRset: [<use1-default-r.sts-ge.amazonaws.com.>]>, <DNS use1-default-r.sts-ge.amazonaws.com. IN CNAME RRset: [<sts-global-default.us-east-1.amazonaws.com.>]>, <DNS sts-global-default.us-east-1.amazonaws.com. IN A RRset: [<209.54.177.164>]>]`
Which then lead to an issue when trying to access the `address` field:
`AttributeError: 'CNAME' object has no attribute 'address'`
I've introduced a filter …
> fix client factory for bypassing DNS server

- localstack-core/localstack/services/lambda_/provider.py
- localstack-core/localstack/services/lambda_/resource_providers/aws_lambda_layerversion.py
- localstack-core/localstack/services/lambda_/resource_providers/aws_lambda_layerversion.schema.json
- tests/aws/services/cloudformation/resources/test_lambda.py
- tests/aws/services/cloudformation/resources/test_lambda.snapshot.json
- tests/aws/services/cloudformation/resources/test_lambda.validation.json
- tests/aws/templates/lambda_layer_version.yml
Implementation of the `read` and `list` operations for lambda layer versions.
The cloudformation schema were out of date so they were also updated as part of this pr.
- Fix a bug in `get_layer_versions` where `store.layers.get(layer_name, {}).layer_versions.get(layer_version)` would fail when the lambda layer did not exists
- Updated the Primary Identifier from `Id` to `LayerVersionArn` with a validated test
- Implementation of `read` and `list`
> Cfn support layer version read list

- localstack-core/localstack/services/sqs/models.py
- tests/aws/services/sqs/test_sqs.py
- tests/aws/services/sqs/test_sqs.snapshot.json
- tests/aws/services/sqs/test_sqs.validation.json
Raising a fix for an open issue in SQS flow of Localstack.
Fixes #11576 
There was a bug in Localstack SQS put message in Standard SQS flow. Principally, standard SQS put calls do not support messagegroupid parameter to be passed. Current implementation of localstack allows "" ie empty string to be passed as messagegroupid while publishing to localstack, whereas same api request to actual AWS sqs throws an exception. Added an additional check in code which checks messagegroupid should not be any string ( having values or empty ) in case of standard sqs put message. If the parameter is an instance of the string, throw exception
> fix(11576): fixing bug in standardqueue put message

- localstack-core/localstack/http/resources/swagger/endpoints.py
The swagger endpoint is not functioning properly when used from an ephemeral instance (see [#1573](https://github.com/localstack/localstack-web/pull/1573) for more context).
We are relying on the `external_service_url` function to compute the path for the `openapi.yaml` file. This function uses the default 4566 port, leading to a fetch error.
- Consider the special case of ephemeral instances when building the `openapi.yaml` path.
> Fix swagger endpoint from ephemeral instance

- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/item_reader/resource_eval/resource_eval_s3.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/result_writer/resource_eval/resource_eval_s3.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/credentials.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/lambda_eval_utils.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_api_gateway.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_aws_sdk.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_batch.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_callback.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_dynamodb.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_ecs.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_events.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_glue.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_lambda.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_sfn.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_sns.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_sqs.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_unsupported.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/state_task.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/state_task_lambda.py
- localstack-core/localstack/services/stepfunctions/asl/utils/boto_client.py
Currently, the SFN v2 interpreter creates boto clients for service integrations using user credentials if no explicit credentials are provided. This causes IAM policy checks to succeed incorrectly event when `ENFORCE_IAM=1` is set, as the checks were based on the user's permissions rather than those of the state machine's assumed role https://github.com/localstack/localstack/issues/11927. This fix ensures boto clients are created with the assumed role credentials of the state machine.
- In Task states, `Credentials` values are always computed and defaulted to the state machine role arn if not manual override is given
- Boto clients are created through assume role logic, using the role arn in the credentials
- Related minor refactoring to improve readability (mainly around renaming …
> StepFunctions: Ensure Service Integrations Assume State Machine Role Credentials

- localstack-core/localstack/services/dynamodb/provider.py
- localstack-core/localstack/services/dynamodb/v2/provider.py
- tests/aws/services/dynamodb/test_dynamodb.py
- tests/aws/services/dynamodb/test_dynamodb.snapshot.json
- tests/aws/services/dynamodb/test_dynamodb.validation.json
We got a report from a customer mentioning that an empty parameter list in an execute statement command does not raise any error against LocalStack when using the JS client.
For instance, the following snippet would raise a `ValidationException` error against AWS, but not against LocalStack.
```js
const params = {
Statement: "SELECT * FROM Table", 
Parameters: []
};
const command = new ExecuteStatementCommand(params);
await client.send(command)
```
- Adding a check for an empty parameter list;
- Adding a snapshot test.
> DDB: parity fix for JS clients

- localstack-core/localstack/dev/run/__main__.py
- localstack-core/localstack/dev/run/configurators.py
- localstack-core/localstack/dev/run/paths.py
When using `python -m localstack.dev.run`, local code checkouts if present are mounted into the container. This may cause confusion if the local project checkout is old and incompatible with the version of LocalStack in the container. 
In particular, we rely heavily on our fork of `moto` which changes semi-frequently. This can cause semi-regular breakages which are difficult to debug.
I think mounting non-core packages should be opt-in to reduce surprises, and should be straightforward and self-documenting to help discoverability.
* Add new argument `-l/--local-packages` which can be used to specify which packages are mounted (if found)
* Define which packages are available in a declarative way so additional packages can be easier to add in the future
* Ensure the help string includes the …
> LDR: selectable local mounts

- localstack-core/localstack/services/lambda_/provider.py
- localstack-core/localstack/services/lambda_/provider_utils.py
- tests/aws/services/lambda_/test_lambda_api.py
As we are making progress with the replicator, we need to implement deterministic id generation for lambda layers in order to control the created version.
- When defining the next version for a lambda layer, we will first verify if a static version was set. Defaulting to standard behavior
- added test
> lambda layer enable deterministic layer version creation

- .github/ISSUE_TEMPLATE/config.yml
- DOCKER.md
- README.md
The Discuss forum is being deprecated.
Removes references to the Discuss forum and redirects the users to the changelog documentation.
> remove references to the discuss forum

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker_factory.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/dynamodb_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/kinesis_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
- localstack-core/localstack/testing/aws/lambda_utils.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.validation.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.validation.json
Currently, LocalStack only supports configuring an Amazon SNS topic or Amazon SQS queue as failure destinations. With [the recent announcement of Amazon S3 as a failed-event destination](https://aws.amazon.com/about-aws/whats-new/2024/11/aws-lambda-s3-failed-event-destination-stream-event-sources/), we should include this additional failure destination.
> Add s3 as ESM failure destination for Kinesis and DynamoDB stream sources

- MANIFEST.in
The source package currently includes all tests, which makes it quite big (10MB). This happens because its inclusions/exclusions are not managed in `pyproject.toml` but in the older `MANIFEST.in`. 
Our `MANIFEST.in` also contains some outdated paths in there.
- Add exclusions for the tests in the source distribution
- Update/Remove outdated paths in MANIFEST.in
```
drwxr-xr-x@    - silvio staff  7 Jan 12:17 localstack_core-4.0.4.dev85
.rw-r--r--@ 2.4M silvio staff  7 Jan 12:18 localstack_core-4.0.4.dev85-py3-none-any.whl
.rw-r--r--@  10M silvio staff  7 Jan 12:17 localstack_core-4.0.4.dev85.tar.gz
drwxr-xr-x@    - silvio staff  7 Jan 12:20 localstack_core-4.0.4.dev86
.rw-r--r--@ 2.4M silvio staff  7 Jan 12:20 localstack_core-4.0.4.dev86-py3-none-any.whl
.rw-r--r--@ 4.3M silvio staff  7 …
```
> Add tests to source package exclusions in MANIFEST.in

- localstack-core/localstack/utils/container_utils/container_client.py
- localstack-core/localstack/utils/container_utils/docker_cmd_client.py
- localstack-core/localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
The Docker SDK supports passing the container entrypoint as a list, but we currently don't. This does not match the Docker API, nor the ECS API.
Support either the list form as well as the string form.
> Docker client: support lists for entrypoints

- pyproject.toml
- requirements-basic.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
- tests/aws/services/cloudformation/resource_providers/ec2/test_ec2.snapshot.json
- tests/aws/services/cloudformation/resource_providers/ec2/test_ec2.validation.json
This PR bumps moto-ext to 5.0.26.post1
Contains:
- https://github.com/getmoto/moto/pull/8393
- https://github.com/getmoto/moto/pull/8295
> Bump moto-ext to 5.0.26.post1

- localstack-core/localstack/services/kms/models.py
- tests/aws/services/kms/test_kms.py
- tests/aws/services/kms/test_kms.snapshot.json
- tests/aws/services/kms/test_kms.validation.json
There is an issue https://github.com/localstack/localstack/issues/11905 to address a bug with KMS DerivedSharedSecret that reports that does not work symmetrically.
`cryptography` library is not correctly used to generate the derive shared secret in the function https://github.com/localstack/localstack/blob/61535b7d970493d9bb6740a03d698d075dd0a3b9/localstack-core/localstack/services/kms/models.py#L368-L388
Currently the HKDF derive function uses directly the public key to generate the derive shared secret. However it is required to add additional steps to fix the bug and get the expected result.
The public key must be transformed from DER encoded data to EllipticCurvePublicKey. A shared secret is then obtained using the exchange function, and finally, the HKDF derive function is used. …
> fix KMS DeriveSharedSecret

- localstack-core/localstack/services/stepfunctions/asl/component/common/jsonata/jsonata_template_binding.py
- localstack-core/localstack/services/stepfunctions/asl/component/common/path/input_path.py
- localstack-core/localstack/services/stepfunctions/asl/component/common/path/output_path.py
- localstack-core/localstack/services/stepfunctions/asl/component/common/payload/payloadvalue/payloadbinding/payload_binding.py
- localstack-core/localstack/services/stepfunctions/asl/component/common/string/string_expression.py
- localstack-core/localstack/services/stepfunctions/asl/component/common/timeouts/heartbeat.py
- localstack-core/localstack/services/stepfunctions/asl/component/common/timeouts/timeout.py
- localstack-core/localstack/services/stepfunctions/asl/component/eval_component.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_wait/wait_function/seconds_path.py
- localstack-core/localstack/services/stepfunctions/asl/eval/environment.py
- localstack-core/localstack/services/stepfunctions/asl/eval/program_state.py
- localstack-core/localstack/services/stepfunctions/asl/utils/json_path.py
- localstack-core/localstack/testing/pytest/stepfunctions/fixtures.py
- localstack-core/localstack/testing/pytest/stepfunctions/utils.py
- tests/aws/services/stepfunctions/templates/scenarios/scenarios_templates.py
- tests/aws/services/stepfunctions/templates/scenarios/statemachines/invalid_jsonpath_in_causepath.json5
- tests/aws/services/stepfunctions/templates/scenarios/statemachines/invalid_jsonpath_in_errorpath.json5
- tests/aws/services/stepfunctions/templates/scenarios/statemachines/invalid_jsonpath_in_heartbeatsecondspath.json5
- tests/aws/services/stepfunctions/templates/scenarios/statemachines/invalid_jsonpath_in_inputpath.json5
- tests/aws/services/stepfunctions/templates/scenarios/statemachines/invalid_jsonpath_in_outputpath.json5
- tests/aws/services/stepfunctions/templates/scenarios/statemachines/invalid_jsonpath_in_string_expr_contextpath.json5
- tests/aws/services/stepfunctions/templates/scenarios/statemachines/invalid_jsonpath_in_string_expr_jsonpath.json5
- tests/aws/services/stepfunctions/templates/scenarios/statemachines/invalid_jsonpath_in_timeoutsecondspath.json5
- tests/aws/services/stepfunctions/v2/logs/test_logs.py
- tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.py
- tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.snapshot.json
- tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.validation.json
- tests/unit/services/stepfunctions/test_jsonata_payload.py
Errors occurring during JSONPath operations are currently not reported accurately https://github.com/localstack/localstack/issues/11951. Additionally, error messages lack consistency across different JSONPath operations, such as those involving JSON templates and fields like `InputPath`, `OutputPath`, `HeartbeatSecondsPath`, etc.. Assembling these error messages is non-trivial, as it requires including the relevant field name. This update introduces logic to enhance the clarity and consistency of these error messages, as well as adding tests. A limitation of these changes are the execution history produced in the case of errors with `TimeoutSecondsPath` and `HeartbeatSecondsPath`, as these appear to be computed at a state level. However, the error messages are still corrcetly formatted …
> StepFunctions: Better Error Messages For JSONPath Operations

- localstack-core/localstack/services/dynamodb/server.py
There have been several reports of JRE crashing with SIGILL on Apple Silicon M4. This crash is specific to JRE 17+ when running in a Docker container (i.e. when [prctl](https://manpages.ubuntu.com/manpages/jammy/en/man2/prctl.2.html) is not available) on aarch64.
In LocalStack, the bug affects DynamoDB Local.
This PR adds the suggested workaround of disabling Scalable Vector Extensions (SVE) in JRE.
SVE disable option is passed to the JVM only when supported, otherwise it complains about unsupported VM option and exits.
Due to lack of an M4 machine, it is not tested whether this resolves the issue.
See https://bugs.openjdk.org/browse/JDK-8345296
Might close - https://github.com/localstack/localstack/issues/12054
> DynamoDB: Disable Scalable Vector Extensions in JRE

- localstack-core/localstack/services/dynamodb/provider.py
- localstack-core/localstack/services/dynamodb/utils.py
- localstack-core/localstack/services/dynamodb/v2/provider.py
- tests/aws/services/dynamodb/test_dynamodb.py
- tests/aws/services/dynamodb/test_dynamodb.snapshot.json
- tests/aws/services/dynamodb/test_dynamodb.validation.json
As reported in #12014, we've had a regression in our handling of GlobalSecondaryIndexes, probably due to the update of DDB-local from v1 to v2. 
This really broke some users setup with Terraform, causing it to try to redeploy and fail. 
I confirmed that with this fix, deploying the Terraform file and trying to applying it again do not fail anymore. 
_fixes #12014_
- add test regarding the behavior of `GlobalSecondaryIndexes` depending on the `BillingMode`
- fix the parity of both `CreateTable` and `DescribeTable` by adding the missing fields to the responses
> DynamoDB: fix GlobalSecondaryIndexes parity in Create and DescribeTable

- localstack-core/localstack/services/ssm/provider.py
- tests/aws/services/ssm/test_ssm.py
- tests/aws/services/ssm/test_ssm.snapshot.json
- tests/aws/services/ssm/test_ssm.validation.json
SSM does not properly return parameters stored when querying it by ARN, if the parameter has a path.
We have some logic to "normalize" the parameter name before passing the call to moto, and this logic is flawed when using an ARN to get the parameter, as the normalized name only contains the last segment of the path.
* SSM now properly handles ARNs in its `get_parameter` and `get_parameters` operations, if the parameter contains a path.
> Fix SSM parameter handling with paths and queries by ARN

- localstack-core/localstack/utils/container_utils/container_client.py
- tests/integration/docker_utils/test_docker.py
Adds a utility method to create a file in the docker container, by just passing the content of the file. I find myself reusing the same approach quite often, so IMO it would be much nicer to have it available as a utility.
When running this inside a container, the file will be created by the `root` user. If the target container runs it's process as a custom (non-root) user, it may not have access to files created by `root`. 
The additional `chmod_mode` argument can be used to ensure the file is available to the custom user. (We could presumably also `chown` the file to the same effect, but I only used `chmod` so far to make files available in this scenario.)
> Docker Utils: Utility method to create file in container

- localstack-core/localstack/services/ses/provider.py
- pyproject.toml
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
This PR bumps moto-ext to 5.0.26.post2
Contains:
- https://github.com/getmoto/moto/pull/8478 @maxhoheiser 
This bump will break SES cloud pods.
> Bump moto-ext to 5.0.26.post2

- tests/aws/services/kms/test_kms.py
- tests/aws/services/kms/test_kms.snapshot.json
- tests/aws/services/kms/test_kms.validation.json
The AWS-validated snapshot KMS tests for tagging and untagging keys are currently missing. We need to add these tests, collect their responses, and verify them against LocalStack.
- AWS-validated tests for tagging and untagging keys have been added for the KMS service.
> Add tests for KMS resource tagging and untagging

- localstack-core/localstack/services/events/event_rule_engine.py
- tests/aws/services/events/event_pattern_templates/empty_prefix.json5
https://github.com/localstack/localstack/issues/12148
I was using this pattern to match all events:
https://stackoverflow.com/questions/62406933/aws-eventbridge-pattern-to-capture-all-events
It works in AWS and in localstack before 4.0.3.
The new rule engine was using truthiness via `condition.get('prefix')` to determine if a condition was a prefix condition.
That assumes a prefix pattern of `''` isn't actually a prefix pattern.
This change instead checks for `None` to determine the condition type and gets empty prefixes to match again.
Added a new JSON test case for this
> Match an empty prefix

- localstack-core/localstack/services/route53resolver/provider.py
- tests/aws/services/route53resolver/test_route53resolver.py
- tests/aws/services/route53resolver/test_route53resolver.snapshot.json
- tests/aws/services/route53resolver/test_route53resolver.validation.json
Implement priority and action filtering for the `ListFirewallRules` operation in Route 53 Resolver
Added functionality to filter by `action` and `priority` for the Route53Resolver operation ListFirewallRules.
Additionally fixed a bug during which: listing a firewall-rule-group for which no rules were created resulted in a ResourceNotFoundException. This was because the store object for firewall-rules was only created when the 1st rule was added.
This change lifts creating a store space for firewall-rules at the firewall-rule-group creation.
Parity tests were included for:
- test listing firewall rules for a non-existing rule-group.
- test listing firewall rules for empty rule-group
- test listing all rules in the rule-group
- test listing rules filtered by priority
- test listing rules …
> Feature: filtering for ListFirewallRules in Route53Resolver 

- localstack-core/localstack/services/events/rule.py
- localstack-core/localstack/services/events/utils.py
- tests/aws/services/events/test_events_schedule.py
- tests/aws/services/events/test_events_schedule.snapshot.json
- tests/aws/services/events/test_events_schedule.validation.json
A user [reported](https://www.notion.so/localstack/Jon-Brasted-EventBridge-Scheduler-not-triggering-SNS-Lambda-execution-in-LocalStack-181fc2a2343181e08a74ffc8e6db99f9) an inconsistent behaviour for events schedule-expression parameter validation between LS and AWS. 
This caused the user to waste some time, since on LS the request succeeded, while it should have failed.
*Previous result:*
```
awslocal events put-rule \
--name my-scheduled-rule \
--schedule-expression 'cron(7 20 * * 1-7 *)'
{
"RuleArn": "arn:aws:events:us-east-1:000000000000:rule/my-scheduled-rule"
}
```
*Expected result:*
```
aws events put-rule \
--name my-scheduled-rule \
--schedule-expression 'cron(7 20 * * 1-7 *)'
An error occurred (ValidationException) when calling the PutRule operation: Parameter ScheduleExpression …
```
> Fix events cron regex for schedule-expression param validation

- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_aws_sdk.py
- tests/aws/services/stepfunctions/templates/errorhandling/error_handling_templates.py
- tests/aws/services/stepfunctions/templates/errorhandling/statemachines/aws_sdk_task_error_s3_no_such_key.json5
- tests/aws/services/stepfunctions/v2/error_handling/test_aws_sdk.py
- tests/aws/services/stepfunctions/v2/error_handling/test_aws_sdk.snapshot.json
- tests/aws/services/stepfunctions/v2/error_handling/test_aws_sdk.validation.json
This PR addresses an issue in the Step Functions AWS-SDK integration where, upon integration failure, the error name is incorrectly cast to a fixed StatesError. This behavior prevents workflows from catching specific error types and implementing retry logic tailored to particular failures in the AWS-SDK integration: https://github.com/localstack/localstack/issues/12139
- aws-sdk error decoration logic uses the computed exception name
- added relevant snapshot test
> StepFunctions: AWS-SDK Integration Retain Specific Error Names

- localstack-core/localstack/services/kms/exceptions.py
- localstack-core/localstack/services/kms/models.py
- localstack-core/localstack/services/kms/utils.py
- tests/aws/services/kms/test_kms.py
- tests/aws/services/kms/test_kms.snapshot.json
- tests/aws/services/kms/test_kms.validation.json
Implement validation for tags in the KMS service with the following rules:
- Duplicate tag keys are not permitted
- A maximum of 50 tags can be applied
- Enforce a limit on the length of tag keys and tag values
- Tag keys cannot use the reserved `aws:` prefix
- Added new test cases for invalid tag keys and values, excessive tag counts (over 50 tags), overly long tag keys and values, and duplicate tag keys.
- Introduced a new method for tag validation and updated the add_tags method.
> Add validation for tags in kms service

- tests/aws/services/cloudformation/resources/test_events.py
- tests/aws/services/cloudformation/resources/test_events.snapshot.json
- tests/aws/services/cloudformation/resources/test_events.validation.json
- tests/aws/services/events/test_events_schedule.py
- tests/aws/services/events/test_events_schedule.snapshot.json
- tests/aws/services/events/test_events_schedule.validation.json
- tests/aws/templates/events_rule_without_targets.yaml
After merging this [PR](https://github.com/localstack/localstack/pull/12156) on eventbridge schedule validation, this integration test broke the pipeline: `test_event_rule_creation_without_target`.
That PR actually brought more parity with AWS and broke an existing test that shouldn't have passed.
Now the test is aws_validated 🚀 
- Fixed a cron schedule: in `events_rule_without_targets`.yaml. ` 'cron(0 1 * * * *)' `-->  `'cron(0 1 * * ? *)'`
- Test snapshot tested and aws validated.
> Fix legacy test that broke pipeline after eventbridge cron update

- localstack-core/localstack/services/s3/provider.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/aws/services/s3/test_s3.validation.json
Follow up from #12145, where we had to updates all S3 snapshots. A few parity issues popped up, and this aims to fix them. 
Seems like the error message for SSE-C related exception changes to be more explicit. This PR fixes that.
I've also updated the message for `HeadObject`, but it seems the message is not serialized/parsed by Boto3. It cannot really hurt anyway 🤷 
- update the error message for SSE-C related exception
- add a test case for #12136, where I cannot reproduce the user issue, as a `HeadObject` request with no `SSECustomerKeyMD5` will trigger an error in AWS too
> S3: fix SSE-C parity error message

- localstack-core/localstack/services/cloudformation/engine/template_deployer.py
- tests/aws/services/cloudformation/test_template_engine.py
- tests/aws/services/cloudformation/test_template_engine.snapshot.json
- tests/aws/services/cloudformation/test_template_engine.validation.json
- tests/aws/templates/engine/join_no_value.yml
This PR fixes an issue encountered by a customer when using AWS::NoValue within a Fn::Join in CFn template
Make  the template deployer ignore the AWS::NoValue when calculaing theh Fn:join result
- new aws validated test.
> fix cfn template join with noValue

- localstack-core/localstack/services/apigateway/helpers.py
- tests/aws/files/openapi-method-int.spec.yaml
- tests/aws/services/apigateway/test_apigateway_import.py
- tests/aws/services/apigateway/test_apigateway_import.snapshot.json
- tests/aws/services/apigateway/test_apigateway_import.validation.json
We got a report that importing a specific OpenAPI file in API Gateway v1 would result in a type error in OpenTOFU:
> deserialization failed, failed to decode response body with invalid JSON, expected StatusCode to be of type string, got json.Number instead
This is because we were not casting as string the status code for the Method status code, and the IntegrationResponse.
When importing an API, we do so by creating the resources "in memory" directly and not via API calls, as this was how on the implementation was. This particular piece of code needs to be reworked fully, but this is out of scope of this PR.
- add a test reproducing a similar exception
- cast imported status codes to string
> APIGW: fix OpenAPI import StatusCode string casting

- localstack-core/localstack/aws/protocol/parser.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/aws/services/s3/test_s3.validation.json
We've got a reported in our Community Slack channel about issue with trailing slashes, especially with short key name (single characters). The trailing slashes would be missing:
```bash
awslocal s3api put-object --bucket sample-bucket2 --key "u/" --content-type "application/x-directory"
awslocal s3api list-objects-v2 --bucket sample-bucket2
...
{
"Key": "u",
"LastModified": "2025-01-22T11:46:17.000Z",
"ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
"Size": 0,
"StorageClass": "STANDARD"
},
...
```
I wrote a test for it and I had a hunch it came from our custom logic to parse URI parameters. We had custom logic for S3 because our router strips trailing slashes by default. We would check if the key name is in the path, and then split on the key and check if the leftover characters in the …
> S3: fix trailing slash logic

- tests/aws/services/stepfunctions/v2/evaluate_jsonata/test_base_evaluate_expressions.py
The test `test_base_task_from_input` seems particularly flaky on the branch/PR https://github.com/localstack/localstack/pull/12158 (3x): https://app.circleci.com/insights/github/localstack/localstack/workflows/full-run/tests?branch=remove-jpype-event-ruler
CircleCI marked it as flaky in general (1x): https://app.circleci.com/insights/github/localstack/localstack/workflows/full-run/tests
Anisa also noticed the flaky test yesterday ([internal Slack](https://localstack-cloud.slack.com/archives/C02N36URU1G/p1737566483599709?thread_ts=1737547934.204389&cid=C02N36URU1G)).
Skip flaky test case following our best practice [R01](https://github.com/localstack/localstack/blob/master/docs/testing/README.md#r01)
> Skip flaky StepFunction timeout test

- localstack-core/localstack/services/kinesis/packages.py
@etspaceman released a new patch version of `kinesis-mock` yesterday: [`0.4.8`](https://github.com/etspaceman/kinesis-mock/releases/tag/v0.4.8)
This PR upgrades `kinesis-mock` from `0.4.7` to `0.4.8`.
See https://github.com/localstack/localstack/pull/11646 for the last upgrade.
- Changes the default version of the `kinesis-mock` package from `0.4.7` to `0.4.8`.
> update kinesis-mock from 0.4.7 to 0.4.8

- localstack-core/localstack/services/s3/provider.py
- tests/aws/services/s3/test_s3.py
Following this discussion here: https://github.com/localstack/localstack/issues/9782#issuecomment-2595044611
We mishandled how the `aws-chunked` `Content-Enconding` header was saved on the object. If given, S3 should remove the header, [this was confirmed](https://github.com/aws/aws-sdk-java-v2/issues/5769#issuecomment-2594242699) by people at Amazon working on the SDK themselves.
- remove the `aws-chunked` value in the object `ContentEncoding`
> S3: fix ContentEncoding with aws-chunked

- pyproject.toml
Currently cbor is listed as required for >= 5.2
https://github.com/localstack/localstack/commit/b612563c223423fb808f7117ba4eb0043a49f7f1 relies on the existence of `cbor2._decoder` which appears first in cbor 5.5 https://github.com/agronholm/cbor2/tree/5.5.0/cbor2 notice its absence here
https://github.com/agronholm/cbor2/tree/5.4.6/cbor2
https://github.com/localstack/localstack/issues/11703
more accurately reflects requirements
> Update cbor 2 requirement to 5.5

- localstack-core/localstack/services/scheduler/provider.py
- tests/aws/services/scheduler/test_scheduler.py
- tests/aws/services/scheduler/test_scheduler.snapshot.json
- tests/aws/services/scheduler/test_scheduler.validation.json
Customer reported an issue for scheduler validation of schedule_expression  https://github.com/localstack/localstack/issues/9284.
The scheduler relies fully on moto for now, and validation is not implemented for `schedule_expression`.
Schedule_expression should support `at`, `cron` and `rate`.
Patched the `create_schedule` method in order to validate `schedule_expression` .
Reused some REGEX rules from events service.
> Fix: validate schedule_expression for EventBridge Scheduler

- localstack-core/localstack/utils/container_utils/container_client.py
- localstack-core/localstack/utils/container_utils/docker_cmd_client.py
- localstack-core/localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
When launching sidecar containers we sometimes need ways of monitoring their resource usage (e.g., to detect memory exhaustions in an ollama container).
This is available through the docker stats command. Our container client implementation does not surface that command yet. 
The container client (and its docker sdk and cli client implementations) now has a new `container_stats` method.
This method unifies the output of both cli and sdk output to resemble the CLI output.
There's a new test which sanity checks the parsing of the outputs into the TypedDict.
> Add docker stats functionality to docker clients

- localstack-core/localstack/services/s3/checksums.py
- localstack-core/localstack/services/s3/models.py
- localstack-core/localstack/services/s3/provider.py
- localstack-core/localstack/services/s3/utils.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/aws/services/s3/test_s3.validation.json
- tests/aws/services/s3/test_s3_list_operations.py
- tests/unit/services/s3/test_s3_checksum.py
- tests/unit/test_s3.py
This PR implements the new data integrity checks for Multipart Upload (shortened MPU), namely the ability to set the `FULL_OBJECT` checksum type for a MPU, allowing the user to not keep track of individual checksum parts to calculate the final one, but instead send the full object checksum to S3. This can be done thanks to `CRC*` type checksums, which can linearize, meaning you can get the full object checksum from the individual parts' checksums (via a somewhat complicated function). 
The PR looks big (3k lines), but 70% of it is snapshots, because I had to cover a lot of different cases, operations' responses, and there was a lot of ground to cover that wasn't previously covered. 
There is a lot of additional validation and default values to check (different relationship between …
> S3: implement new data integrity for MultipartUpload

- localstack-core/localstack/services/sns/models.py
- localstack-core/localstack/services/sns/provider.py
- localstack-core/localstack/services/sns/publisher.py
- tests/aws/services/sns/conftest.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
- tests/aws/services/sns/test_sns.validation.json
As reported by #12179, we were not calculating the message signature correctly for `UnsubscribeConfirmation` message for HTTP/HTTPS subscriptions.
I've created an `StrEnum` to avoid this kind of typo in the future.
I had also been talking about creating a Lambda URL fixture to allow forwarding received message to an HTTP endpoint to an SQS queue, so this was a good occasion to do it. 
This can be used as example for other services as well, the fixture could probably live in the global fixture file, once we see we can reuse it, as it can be dependent on what the HTTP endpoint needs to return. 
But I'm thinking of making this fixture to do more SNS related things, like being able to return different status code to enable retries and such, or auto-approve the subscription, so we could …
> SNS : fix Message Signature typo and add Lambda URL fixture

- localstack-core/localstack/utils/container_utils/docker_cmd_client.py
As described in this issue:
https://github.com/localstack/localstack/issues/12201
localstack fails to log under podman.  Before this PR, starting logstack when using podman will reach the following error:
```
⠼ Starting LocalStack container2025-01-28T19:11:00.121 DEBUG --- [-log-printer] localstack.utils.run       : Executing command: ['docker', 'logs', '261b4f90dcc37e74bce5b97cf390a7b935fc2d1e0d12ecd41c8df632b7587e76', '--follow']          
────────────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ───────────────────────────────────────────────────────────────────────────────────
Error: no container with name or ID "--follow" found: no such container  
```
and logging will stop.
technically localstack will start, but …
> adjust --follow arg positioning to be compatible with docker and podman

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker.py
- localstack-core/localstack/services/lambda_/provider.py
ESM workers were not being explicitly shut down when LocalStack was being closed. This PR fixes this by explicilty closing all workers on the `on_before_stop` hook prior to the Lambda service.
- Loop over all ESM workers and signal them for graceful shutdown in `on_before_stop`
- Add a `stop_for_shutdown` method that signals to close the `poller_loop`
> fix: Explicitly stop ESM workers on LocalStack shutdown

- localstack-core/localstack/services/cloudformation/provider.py
- tests/aws/services/cloudformation/api/test_stacks.py
- tests/aws/services/cloudformation/api/test_stacks.snapshot.json
- tests/aws/services/cloudformation/api/test_stacks.validation.json
- tests/aws/services/cloudformation/api/test_templates.py
- tests/aws/templates/sns_topic_simple.yaml
This PR adds make the CFn provider return the correct exception type in case the `DescribeStackResource` is called for a resource that doesn't exist. The Serverless-cli tool would do this before re-deploying a stack and the users would be confuse about the LocalStack logs. 
- Raise and return ValidationException when a resource doesn't exists
- new aws validated test.
> raise validationException if resource does not exist in CFn

- pyproject.toml
- requirements-basic.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
This PR bumps moto-ext to 5.0.28.post1
Contains:
- https://github.com/getmoto/moto/pull/8531
https://github.com/localstack/localstack-ext/actions/runs/13073190885
> Bump moto-ext to 5.0.28.post1

- localstack-core/localstack/services/s3/models.py
- localstack-core/localstack/services/s3/provider.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/aws/services/s3/test_s3.validation.json
As a follow up from #12145, there was a new field introduced for operation related to S3 Buckets `LifecycleConfiguration`.
This fix allows us to now validate and return the field as well, even though we do not support Lifecycle transitions, some IaC providers might expect us to return it. 
This is what the field is for:
> In September 2024 Amazon S3 updated the default transition behavior for small objects, as follows:
>
> - Updated default transition behavior — Starting September 2024, the default behavior prevents objects smaller than 128 KB from being transitioned to any storage class.
> - Previous default transition behavior — Before September 2024, the default behavior allowed objects smaller than 128 KB to be transitioned only to the S3 Glacier and S3 Glacier Deep Archive storage …
> S3: implement TransitionDefaultMinimumObjectSize for Lifecycle Configuration

- localstack-core/localstack/services/apigateway/next_gen/execute_api/helpers.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py
- tests/aws/services/apigateway/test_apigateway_lambda.py
- tests/aws/services/apigateway/test_apigateway_lambda.validation.json
As reported in #12115, we did not support returning binary responses from `AWS_PROXY` integration. In the previous implementation of API Gateway, we were returning binary responses but in the wrong way: if the `isBase64Encoded` was set to `True` in the response, we decode it and send binary data. 
However, it has a deep link to the `binaryMediaTypes` configuration of the REST API. Only if the client sends an `Accept` header that matches the `binaryMediaTypes` then the `AWS_PROXY` will respond with binary data. 
This PR was quite frustrating, as it took me hours to implement the test and all the different cases, and I hit some caching issues, things failing in one run and not another, I had to deploy to different stages to be sure I wasn't hitting some weird issues. 
And the implementation …
> APIGW: add Binary Media support for response in `AWS_PROXY`

- localstack-core/localstack/services/sqs/models.py
- localstack-core/localstack/services/sqs/provider.py
- localstack-core/localstack/services/sqs/queue.py
- tests/aws/services/sqs/test_sqs.py
- tests/aws/services/sqs/test_sqs.snapshot.json
- tests/aws/services/sqs/test_sqs.validation.json
Blocking calls in the SQS provider's internal queue implementation cause LocalStack shutdown to hang, and in some cases time-out. 
This PR allows for these blocking `Queue.get` calls to exit early if LocalStack is shutting down and the `do_shutdown` method is called.
- Add an `InterruptibleQueue` class that overwrites a `Queue` implementations `get` method to leverage a shutdown `Threading.Event`.
- `InterruptibleQueue` also has a `do_shutdown` method that a queue to be shutdown early if it is currently undergoing a blocking call.
- Add queue closing to the SQS provider's `on_before_stop` lifecycle hook (which happens after persistence) to ensure no hanging threads prevent LS from shutting down.
> [SQS] Stop blocking Queue.get() call on LocalStack shutdown

- localstack-core/localstack/dev/kubernetes/__main__.py
- localstack-core/localstack/plugins.py
With recent refactorings to namespace packaging (#11190 ) and usage of setuptools_scm (#11355) the kubernetes dev run script broke.
It still mounted pro source code into `site-packages/localstack-ext` and not inside the `localstack` namespace package, and the entrypoint mounts did not take into account the new versioning scheme.
A main culprit was the implicit behavior of taking parts of the path from the host and using them inside the container, as this prevented mounting the pro source code in the `localstack/pro` directory.
Changing this required some refactoring.
* The mount points are now generated in a separate method, and into a defined data structure. This provides more flexibility, as previous behavior was very implicit (taking the last part of the path on the host for mounting …
> Fix kubernetes dev run script

- localstack-core/localstack/services/apigateway/legacy/provider.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_request.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_response.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/resource_router.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py
- tests/aws/services/apigateway/test_apigateway_s3.py
- tests/aws/services/apigateway/test_apigateway_s3.snapshot.json
- tests/aws/services/apigateway/test_apigateway_s3.validation.json
- tests/unit/services/apigateway/test_handler_integration_request.py
- tests/unit/services/apigateway/test_handler_integration_response.py
Follow up from #12199, is reviewable ~but will come out of draft once the base is merged to avoid the rebase review madness~.
This PR implements the full Binary media support for REST APIs. The AWS documentation will do a much better job explaining what this means exactly, but in big line, it allows you to define some behavior in how your payload in being pass through to your integration: it can be pass as is, converted to a safe UTF-8 string, or base64 decoded or encoded. 
There are precise tables on the behavior, but I tend to not trust the documentation so much, so I took it upon myself to write AWS validated tests, which was to be honest, quite a pain again 😅 
The behavior in itself is not too complicated, it is mapping some table to if conditions (which might be simplified, if you …
> APIGW: binary support for non-proxy integration

- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/sqs_poller.py
Currently, event hooks used to override the number of SQS messages to delete/receive use static parameters from the `SqsPoller` class to determine override values. Since boto clients in the same session can be re-used, this approach could possibly cause data races if multiple clients register against the same event source with different `BatchSize` parameters.
Instead, this PR introduces event hooks that allow the override parameter to be dynamically passed in to each boto call (and injected into the headers) instead of trying to retrieve this information from the static ESM values.
- Remove header injection implementation that relied on retrieving static values from the `SqsPoller.sqs_queue_parameters`.
- Introduce a `sqs_override_max_message_count` parameter to `ReceiveMessage` and …
> [ESM] Dynamically set SQS message override count

- localstack-core/localstack/utils/analytics/metadata.py
- tests/unit/utils/analytics/conftest.py
This PR adds `product` and `edition` to the session's `ClientMetadata`. Given LocalStack's growing number of products, the distinction will help distinguish where a session is coming from. 
Both `product` and `edition` can be overwritten by environment variables to cover cases where a runtime is not necessarily given or correct (e.g. when packaging an extension).
- adds `product` and `edition` to the session's `ClientMetadata`
- adds `mock_runtime` fixture. Analytics unit tests rely on client metadata - but `get_current_runtime()` [throws an error](https://github.com/localstack/localstack/blob/873d150c009f4bc6acaee6a4c48a57ab53c66f0e/localstack-core/localstack/runtime/current.py#L20) when not having an initialized runtime.
> add product and edition to session analytics

- localstack-core/localstack/services/sqs/provider.py
- localstack-core/localstack/services/sqs/queue.py
Under high volumes of SQS receive/send/delete calls, the internal SQS `ThreadPoolExecutors` can execute tasks long after a service has completed their shutdown/stop lifecycle hooks.
That is, when we try stop the SQS service, **currently running** and **future pending** tasks are not cleared from the executor pool -- potentially being executed long after the service signalled to have stopped.
This PR ensures that all **enqueued** tasks are cancelled on shutdown.
- Changed the `CloudWatchDispatcher.shutdown` and `MessageMoveTaskManager.close` methods to cancel all pending/future tasks that are currently enqueued for execution.
> [SQS] Cancel pending and future tasks on shutdown

- localstack-core/localstack/services/sqs/constants.py
- localstack-core/localstack/services/sqs/models.py
- localstack-core/localstack/services/sqs/provider.py
- tests/aws/services/sqs/test_sqs.py
- tests/aws/services/sqs/test_sqs.snapshot.json
- tests/aws/services/sqs/test_sqs.validation.json
- tests/aws/services/sqs/test_sqs_backdoor.py
This PR allows the `WaitTimeSeconds` parameter to be overridden via a custom header. Useful for increasing the amount of time an [SQS long polling request ](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-short-and-long-polling.html#sqs-long-polling) can collect for prior to returning.
- New constant `HEADER_LOCALSTACK_SQS_OVERRIDE_WAIT_TIME_SECONDS` with `x-localstack-sqs-override-wait-time-seconds`.
- Add support for replacing value of `WaitTimeSeconds` parameter with value of `x-localstack-sqs-override-wait-time-seconds` header.
> [SQS] Add custom header for overriding WaitTimeSeconds

- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_glue.py
Recent changes in the Step Functions interpreter limited the execution of service integration to the set of the officially supported ones https://github.com/localstack/localstack/pull/12223. This exposed the lack of such checks for the Glue optimized service integration. These changes add such [specification for Glue](https://docs.aws.amazon.com/step-functions/latest/dg/connect-glue.html).
- Add the list of supported api parameter bindings for Glue's optimized service integration.
> Step Functions: Add Supported Integrations For Glue

- localstack-core/localstack/services/sqs/provider.py
There are still some hanging threads on SQS shutdown due to:
- Cleanup fixtures deleting SQS queues lifecycle hooks are able to shut them down
- CloudWatch metric dispatcher does not guard against new `submit` jobs when executor is shutdown
- Shutdown internal SQS queue resource upon deletion.
- Prevent dispatching new CW jobs when `ThreadPoolExecutor` object is closed (causing a `RuntimeException`)
> [SQS] Improve shutdown capabilities of SqsProvider

- tests/aws/services/transcribe/test_transcribe.py
We have seen a bunch of flaky runs with the Transcribe tests in the past, and it seems that we still see issues.
This PR skips the last test which actually performs an actual transcription task. This should definitely be addressed fairly soon, but for the sake of the stability of our pipelines we are right now actively skipping all flaky tests.
/cc @sannya-singal 
- Skips the last `transcribe` service integration tests which actually perform transcriptions.
> skip flaky transcribe tests

- localstack-core/localstack/services/s3/provider.py
- localstack-core/localstack/services/s3/utils.py
- tests/aws/services/s3/test_s3_list_operations.py
- tests/aws/services/s3/test_s3_list_operations.snapshot.json
- tests/aws/services/s3/test_s3_list_operations.validation.json
As reported with #12255, we've had an issue with `ListObjectVersions` and deletion.
The failing scenario is reproduced in the added test, but it can be summarized like that:
The list operation, when paginated and arriving at the max amount it can return, will return a `VersionIdMarker`, representing the last marker it returned (newer operations of S3 return the next one, which is a bit smarter). 
If you happen to delete this version, AWS will return the next value in line after this now deleted marker. Not sure exactly how they do it, if they encode the data in the version id, or keep track of deleted versions. I've tried to reverse engineer the VersionId base64 encoding, but didn't really get anything and didn't try very hard.
We didn't have anything to compare against as those values …
> fix ListObjectVersions pagination when version id marker is deleted

- localstack-core/localstack/services/s3/provider.py
- localstack-core/localstack/services/s3/utils.py
- tests/aws/services/s3/test_s3_list_operations.py
- tests/aws/services/s3/test_s3_list_operations.validation.json
- tests/unit/services/s3/test_s3.py
Follow up from #12259, I've introduced flakiness in the tests and bad behavior (also reported). I saw the failed run here: https://github.com/localstack/localstack/actions/runs/13314341024/job/37184566141 and realized my mistake instantly 🤦‍♂️ 
I incorrectly assumed the b64 encoded data could be sorted lexicographically, but this was wrong. The increasing values are cycling from upper case, lower case, digits, back to upper case. However, there is one comparison that fails: `z` to `0`. 
This is because if we look at the proper Unicode code point for the characters, we go from `y`, `z`, `0`, `1` to -> `49`,  `48`, `122`, `121`. So we break the order at this one character. (if they had started with digits, things would have been fine 😝)
I've introduced a small utility function to properly …
> fix ListObjectVersions pagination comparison

- docs/testing/integration-tests/README.md
While reading the [Integration tests README](https://github.com/localstack/localstack/blob/master/docs/testing/integration-tests/README.md) file and testing the example command `TEST_PATH="tests/integration/docker/test_docker.py::TestDockerClient" make test` locally I found out that it fails because the path is not correct.
https://github.com/localstack/localstack/blob/master/docs/testing/integration-tests/README.md#running-individual-tests
Updated the integration individual tests example command with the corrected path to run the test.
> fix readme run integration individual tests cmd

- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
This PR leverages the backoff util to ensure, when retrying, we wait between retries so as to not spam the processing loop.
Companion PR to https://github.com/localstack/localstack/pull/12264
- Checks `has_record_expired` every iteration to allow for an expired record to break processing.
- Use `backoff`utility, in conjunction with a `threading.Event`, to exponentially back-off between processing retries.
> [ESM] Add backoff between Stream Poller retries

- pyproject.toml
- requirements-basic.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
This PR bumps moto-ext to 5.0.28.post6
>[!IMPORTANT]
> This release of moto-ext excludes commits related to the ongoing RDS refactoring because it breaks the RDS provider in Ext.
Contains:
- https://github.com/getmoto/moto/pull/8556
Closes https://github.com/localstack/localstack/issues/11522
- https://github.com/getmoto/moto/pull/8563
- https://github.com/getmoto/moto/pull/8570
Closes https://github.com/localstack/localstack/issues/11765
- https://github.com/getmoto/moto/pull/8575
- https://github.com/getmoto/moto/pull/8610
> Bump moto-ext to 5.0.28.post6

- localstack-core/localstack/services/lambda_/api_utils.py
- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/aws/services/lambda_/test_lambda_api.validation.json
While working with Lambda and during a support case, I realized we didn't handle the case when the SubnetIds would be invalid. 
While this PR does not implement complet behavior (we only validate the first subnet id in the list), it at least makes sure that we don't return `InternalException`. 
This was the error:
```python
File "<>/localstack/localstack-core/localstack/services/lambda_/provider.py", line 1007, in create_function
vpc_config=self._build_vpc_config(
^^^^^^^^^^^^^^^^^^^^^^^
File "<>/localstack/localstack-core/localstack/services/lambda_/provider.py", line 491, in _build_vpc_config
vpc_id=self._resolve_vpc_id(account_id, region_name, subnet_ids[0]),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<>/localstack/localstack-core/localstack/services/lambda_/prov …
```
> Lamba: fix unhandled error when SubnetIds is invalid

- localstack-core/localstack/services/sns/executor.py
- localstack-core/localstack/services/sns/publisher.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
- tests/aws/services/sns/test_sns.validation.json
We've got a report with #12276 that SNS FIFO ordering wasn't guaranteed between subscriptions of the same topic (usually first messages are unordered, then they get ordered). 
This PR introduces a "partitioned" thread pool executor: each "topic" (it can be anything, it is not scoped only to SNS), will have its own worker. This allows the guarantee that the work executed on that topic is sequential. 
But you can have multiple workers, and each will have some topics assigned to them. 
The user also added a very good reproducer in Rust: https://github.com/dkales/fifo-example, verifying that ordering is the same across all queues, and it now works all the time. 
<details><summary>Some more context</summary>
<p>
This was something we were aware of with @thrau and had discussed already a long …
> fix SNS FIFO ordering

- localstack-core/localstack/services/opensearch/cluster.py
- localstack-core/localstack/services/opensearch/packages.py
In https://github.com/localstack/localstack/pull/11462, we changed the ElasticSearch/OpenSearch installers to use the [bundled JRE](https://www.elastic.co/guide/en/elasticsearch/reference/current/install-elasticsearch.html#jvm-version). However, based on https://github.com/localstack/localstack/issues/12231, it was identified that ElasticSearch 5.x and 6.x builds [do not](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/zip-targz.html) have a bundled JRE and instead require a separate JRE installation.
This PR introduces a specialised package installer for ElasticSearch 5.x and 6.x which manages the Java dependency through standardised approach.
Tested manually locally. On the CI, automated tests run only against the latest versions, which was also why this went undetected. …
> ElasticSearch: Fix missing JRE in 5.x and 6.x

- tests/aws/services/lambda_/test_lambda.py
- tests/aws/services/lambda_/test_lambda.snapshot.json
- tests/aws/services/lambda_/test_lambda.validation.json
With recent updates to `public.ecr.aws/lambda/python:3.12` it seems AWS ships a newer Lambda RIC client with those images than they use in AWS.
This leads to a disparity between the stacktrace returned by aws, and the one in LS.
As the stack trace line numbers are not really important to get _exactly_ right, for me that is a reasonable compromise for now (other option would be pinning the images).
For now I have skipped the stack trace check - we should check in the future to unskip it once AWS incorporates the changes in their environment as well.
* Update the test to python 3.13 (sadly this also has the change, but it is good to keep anyway)
* Skip snapshot verify on the stackTrace
> Fix failing lambda error reporting test

- localstack-core/localstack/services/cloudformation/engine/template_deployer.py
As discovered by a customer. CFn should remove the AWS::NoValue from list of references when pasing such list as as an Attribute Value for a resource definition.
Example. In the following code, CFn should remove the AWS::NoValue from the list of RouteTableIds before attempting to create the resource.
```yaml
S3VpcEndpoint:
Type: AWS::EC2::VPCEndpoint
Properties:
RouteTableIds:
- Fn::If:
- cNewVpc
- Ref: PrivateSubnet1RouteTable
- Ref: AWS::NoValue
- Fn::If:
- cNewVpc
- Ref: PrivateSubnet2RouteTable
- Ref: AWS::NoValue
``` 
The previous solution (#12163) only managed to fix this for `Fn::Join` list parameter. With the new changes, the fix is applied to any referenced list.
- Temployer utils removes the AWS::NoValue from the lists.
- The Fn:Join procces now uses the cleaned result instead …
> refactoring of removal of AWS::NoValue in reference list for CFn

- localstack-core/localstack/config.py
- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/sqs_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
As a part of performance improvements to ESM, this PR introduces backoff in poll-frequency when an event source either returns no records or raises an exception on data retrieval.
By delaying polling on empty data sources and errors, we expect to reduce load on the LocalStack gateway and make more resources available for successful processing events.
- Small refactor of `poll_events` to better facilitate changing the poll-frequency duration to include backoff.
- New `EmptyPollResultsException` that is raised when a poll request to an event source returns no data. This is used to signal a poll-miss scenario and allows us to decrease poller frequency for empty resources.
- Add an `empty_boff` that returns backoff (up to 10s) when an event source does not return any data (i.e a …
> [ESM] Add backoff between poll events calls

- localstack-core/localstack/utils/aws/client_types.py
We are missing a service principal definition for `edgelambda.amazonaws.com` used at Lambda@Edge https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-permissions.html
* Add `edgelambda` to the list of service principals
> Add Lambda@Edge service principal

- localstack-core/localstack/utils/tagging.py
- tests/unit/test_tagging.py
We use the `TaggingService` abstraction as a service-neutral way to maintain resource tags. Its helper functions can use the common tag shape used by Botocore specs, which is:
```
'Tags': [
{
'Key': ...,
'Value': ...,
}
]
```
This is used by variety of services including [s3](https://docs.aws.amazon.com/AmazonS3/latest/API/API_control_Tag.html), [kinesisanalytics](https://docs.aws.amazon.com/managed-flink/latest/apiv2/API_Tag.html), [elasticache](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_Tag.html), and others.
However some services use the same shape but different capitalisation for the field names, most notably [codepipeline](https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_Tag.html), which looks like:
```
'Tags': [
{
'key': ...,
'value': ..., …
```
> TaggingService: Allow key value field names to be overridden

- localstack-core/localstack/services/lambda_/packages.py
The current lambda runtime init contains a vulnerability classified as `high` (CVE-2024-45338).
For more information see localstack/lambda-runtime-init#37
* No functional changes
> Fix vulnerabilities in lambda runtime init

- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.validation.json
This PR fixes a flaky test with SQS + ESM when the `ReportBatchItemFailures` is set.
The duration to poll for an event was too short, meaning re-queued messages had not properly exceeded their [visibility timeout](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html) -- meaning nothing was re-queued while polling was happening and that the assertion for a non-empty `ReceiveMessage` operation failed, resulting in a test failure.
- Fixes `test_report_batch_item_failures`, ensuring the visibility timeout of the SQS queue is greater than the invocation timeout of the target lambda.
- Test repeated against LocalStack and AWS x5 to ensure no flakiness.
> [ESM] Fix flaky SQS ReportBatchItemFailures test with proper visiblity timeouts

- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/sqs_poller.py
This fixes an issue that causes our SQS poller to always trigger exponential backoff between poller calls instead of only when a response is empty or exception is raised. Currently, this bug is slowing down performance and should be merged ASAP.
GitHub's automatic rebase (which did not raise a merge conflict) caused our `if-else` conditional to change into a `for-else`. Since the `else` block was where we raised a backoff exception, this has caused our poller to _always_ raise an exception and signals the ESM worker to constantly back-off.
See: 
https://github.com/localstack/localstack/blob/ceb6140362a2dcabd2e687344a399ccbeba6dab9/localstack-core/localstack/services/lambda_/event_source_mapping/pollers/sqs_poller.py#L196
And:
https://github.com/localstack/localstack/blob/8859590c9974262a22 …
> [ESM] Fix constantly triggering SQS back-off

- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_dynamodbstreams.validation.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_kinesis.validation.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.py
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.snapshot.json
- tests/aws/services/lambda_/event_source_mapping/test_lambda_integration_sqs.validation.json
This PR allows for the ESM to validate the existence of different event source resources
- Adds check for sqs existence in the event source validation
- Adds check for kinesis streams existence in the event source validation
- Adds check for dynamodb streams existence in the event source validation
- Created the `test_esm_with_not_existing_sqs_queue` test inside the `test_lambda_integration_sqs.py` tests
> [ESM] Validate event sources existence

- tests/aws/test_integration.py
This non-aws validated test seems flaky: https://github.com/localstack/localstack/actions/runs/13634627127/job/38110211627#step:22:7603
```
FAILED ../../localstack/tests/aws/test_integration.py::test_kinesis_lambda_forward_chain - botocore.errorfactory.ResourceInUseException: An error occurred (ResourceInUseException) when calling the PutRecord operation: Stream arn:aws:kinesis:us-east-1:000000000000:stream/test-stream-82a63827 is not currently ACTIVE or UPDATING.
```
Locally, I'm getting another assertion error:
```
>           raise Exception("Expected object not found: %s in list %s" % (expected_object, all_objects))
E           Exception: Expected object not found: {'test_data': 'forward_chain_data_ad49f8c0 with \'quotes\\"'} in list []
```
A workaround could be waiter for the stream …
> Skip flaky Kinesis Lambda test

- localstack-core/localstack/services/apigateway/legacy/provider.py
- tests/aws/services/apigateway/test_apigateway_api.snapshot.json
- tests/aws/services/apigateway/test_apigateway_api.validation.json
- tests/aws/services/apigateway/test_apigateway_lambda.py
- tests/aws/services/apigateway/test_apigateway_lambda.snapshot.json
- tests/aws/services/apigateway/test_apigateway_lambda.validation.json
We've got a report from a user with an unhandled error in the invocation logic:
```python
localstack | File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/next_gen/execute_api/helpers.py", line 114, in get_lambda_function_arn_from_invocation_uri
localstack | return uri.split("functions/")[1].removesuffix("/invocations")
localstack | ~~~~~~~~~~~~~~~~~~~~~~~^^^
localstack | IndexError: list index out of range
```
This is probably because the Integration URI passed was directly a Lambda ARN, and it needs to be an API Gateway invocation ARN:
Correct format:
`arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:HelloWorld/invocations`
Incorrect format: …
> APIGW: add validation for AWS ARN in PutIntegration

- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/aws/services/lambda_/test_lambda_api.validation.json
Adds validations for an ESM stream's `StartingPosition` parameter.
- Extends the `dynamodbstreams` test `test_create_event_source_validation` to include some invalid/incompatible params
- Adds a `test_create_event_source_validation_kinesis` to test for kinesis parameter validations.
> [ESM] Fix validation of StartingPosition streams parameter

- localstack-core/localstack/services/apigateway/resource_providers/aws_apigateway_domainname.py
A customer provided a template where they used `RegionalDomainName` and `RegionalHostedZoneId`, but these values are not populated correctly in the APIGW CFn resource provider
Populate these two fields from the response if possible, but fall back to the distribution values if not present
A CFn test is implemented in the private repository as creating domain names is a Pro feature
> CFn: populate APIGW regional* properties

- Dockerfile
- localstack-core/localstack/aws/protocol/service_router.py
- localstack-core/localstack/aws/spec.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py
- localstack-core/localstack/services/s3/cors.py
- localstack-core/localstack/services/s3/presigned_url.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_aws_sdk.py
- tests/unit/aws/test_service_router.py
With the release of LocalStack 4.1.0, we had issues with the smoke tests of the binary build of our CLI.
It turned out that the initial loading of the service catalog took more than 2 seconds (which is the default connection timeout of `localstack wait`). https://github.com/localstack/localstack-cli/pull/33 introduced a workaround for this, by triggering the service catalog cache creation with a call prior to the `localstack wait` command.
However, this issue has a user impact, as this cache will always be created when localstack is started with a new `botocore` version (even if the localstack volume dir is properly configured).
In fact, this was already discussed with @thrau when he introduced the cache in the first place (https://github.com/localstack/localstack/pull/6672).
This PR …
> add service catalog cache loading from static var

- Dockerfile.s3
https://github.com/localstack/localstack/pull/12314 introduced a docker-build-time generation of the service catalog cache.
Unfortunately, I forgot about the `Dockerfile` for the S3 image.
- Adds a small step to generate the service catalog cache at docker build time for the S3-only `Dockerfile`.
> add build time service catalog cache generation to s3 image

- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/distributed_iteration_component.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/inline_iteration_component.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/itemprocessor/distributed_item_processor.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/itemprocessor/inline_item_processor.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/iteration_component.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/iterator/distributed_iterator.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/iterator/inline_iterator.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/state_map.py
- tests/aws/services/stepfunctions/templates/scenarios/scenarios_templates.py
- tests/aws/services/stepfunctions/templates/scenarios/statemachines/map_state_nested_config_distributed_no_max_concurrency.json5
- tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.py
- tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.snapshot.json
- tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.validation.json
Currently, the Step Functions v2 interpreter encounters issues when evaluating nested MapRun calls distributed across multiple MapRuns https://github.com/localstack/localstack/issues/12335. This arises from two main issues: certain map run components inappropriately use member variables to share state, and the worker number management is shared across multiple map runs, causing no workers to start for jobs beyond the first job in nested scenarios.
This pull request addresses the anti-pattern of stateful objects in the map run logic by making them stateless. Additionally, it corrects the creation of workers so they are appropriately initiated for all nested map runs.
Added a relevant snapshot test to verify the correct functioning of distributed nested map runs without maximum concurrency …
> Step Functions: Improve Nested Map Run Stability

- localstack-core/localstack/constants.py
- localstack-core/localstack/services/transcribe/provider.py
- tests/aws/services/transcribe/test_transcribe.py
Fix flaky pipeline runs: 
- https://app.circleci.com/pipelines/github/localstack/localstack/31132/workflows/352699b7-785d-4672-a966-a5f073e5a6e6/jobs/277165/tests 
- https://app.circleci.com/pipelines/github/localstack/localstack/31131/workflows/2aaa3688-b9ae-4db9-b661-ba4693df7531/jobs/277148/tests
by making the downloading of vosk models more robust. 
This PR: 
- adds provision to download the models from the vosk server and if it fails, it fallbacks to download the models from the [Hugging Face](https://huggingface.co/localstack/vosk-models). 
- removes skipping the flaky tests: `test_transcribe_happy_path`, `test_transcribe_supported_media_formats` and `test_transcribe_start_job`. 
Successful pipeline runs: https://app.circleci.com/pipelines/github/localstack/localstack?branch=test-tra …
> fix flaky transcribe tests

- Dockerfile
Running the localstack/localstack docker with a different --workdir makes it "unhealthy". Ex: `docker run -it --workdir /opt localstack/localstack:stable`
Changes the docker healthcheck to use absolute path when executing the binary
> Makes docker healthcheck more robust

- Dockerfile.s3
https://github.com/localstack/localstack/pull/12344 changed the health check in the `Dockerfile` of the main image to be independent of the working directory (since some tools might be changing the workdir).
Unfortunately during the review, I forgot about the S3 image, which is covered in this PR.
- Changes the `HEALTHCHECK` directive in the `Dockerfile.s3` to be independent of the working directory.
> migrate healthcheck enhancements to S3 image

- localstack-core/localstack/aws/app.py
This PR moves our ServiceNameParser to be executed after our Edge Router.
Note: this will break upstream until #11801 and its companion are merged, so should be reviewed together. 
For historical reasons, we needed the service name for our security handling (we talk about CORS, but it is not about CORS, CORS is a "response" part, this is about our CRSF/firewall? security where we reject a request if not in our allowed hosts).
It however lead to some issues because every route would be considered as an S3 request, as our service name could not parse the request.
As S3 now properly manages its own CORS via a special handler executed very early in the request chain, we already know before the service name parser if an S3 request that needs to have its CORS managed is an S3 request or not via …
> move parse_service_name after serve_edge_router_rules

- tests/aws/services/cloudformation/resources/test_redshift.py
- tests/aws/services/redshift/test_redshift.py
Redshift in LocalStack Pro now fails when it cannot install a database (fail fast).
This breaks two RedShift CloudFormation tests, when not executed against LocalStack in the Docker container.
This PR adds markers to avoid the execution of these tests if executed outside of Docker.
- Add `only_in_docker` marker to:
- `test_redshift_cluster (tests.aws.services.cloudformation.resources.test_redshift)`
- `test_create_clusters (tests.aws.services.redshift.test_redshift.TestRedshift)`
> fix redshift tests if not in docker

- docker-compose-pro.yml
- docker-compose.yml
The `version` top-level element in docker compose files is obsolete in docker compose v2 (https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete).
It will print a warning when used, like this:
```
WARN[0000] /path/to/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```
It is only used for docker compose v1, which stopped receiving updates and is considered EOL since July 2023 (https://docs.docker.com/compose/releases/migrate/).
It was marked deprecated already in 2021 (https://github.com/compose-spec/compose-spec/commit/85d1bcfc07462fbfc645882a4ca1901012075cf6).
It should also be supported by later docker compose v1 versions (1.27.0+), after the compose format merging …
> Remove version attribute from docker compose files

- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
A follow-up PR to https://github.com/localstack/localstack/issues/12281 that correctly initialises the exponential backoff object.
- Fixes incorrectly passing the `attempt` counter to the boff object. Instead, the `MaximumRetryAttempts` attribute of the ESM config is used.
> [ESM] Correctly enable exponential backoff inside stream poller

- localstack-core/localstack/services/stepfunctions/backend/alias.py
- localstack-core/localstack/services/stepfunctions/backend/execution.py
- localstack-core/localstack/services/stepfunctions/backend/state_machine.py
- localstack-core/localstack/services/stepfunctions/backend/store.py
- localstack-core/localstack/services/stepfunctions/provider.py
- localstack-core/localstack/testing/pytest/stepfunctions/fixtures.py
- localstack-core/localstack/testing/pytest/stepfunctions/utils.py
- tests/aws/services/stepfunctions/v2/test_sfn_api_aliasing.py
- tests/aws/services/stepfunctions/v2/test_sfn_api_aliasing.snapshot.json
- tests/aws/services/stepfunctions/v2/test_sfn_api_aliasing.validation.json
These changes introduce initial support for [AWS Step Functions aliasing](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-state-machine-alias.html) features.
Future work on aliasing: CloudFormation support; paging in ListStateMachineAliases 
- Added a new object representation for State Machine aliases, including logic for sampling and handling alias-specific attributes.
- Store updates: extended the Step Functions provider’s store to manage and track aliases
- API actions: CreateStateMachineAlias, DescribeStateMachineAlias, ListStateMachineAliases (no pagination support yet), UpdateStateMachineAlias, DeleteStateMachineAlias
- Complexity considerations: these changes focus on allowing creation and execution api actions of aliases to be optimized for constant time complexity; …
> Step Functions: Support for Aliasing

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
Shards were not being reset when a DynamoDBPoller encountered a `TrimmedDataAccessException` exception, placing the StreamPoller into an unrecoverable state instead of re-initialising and proceeding. 
In addition, when shard/iterator initialisation failed, the subsequent `current_shard_tuple` was set to `None`, failing to be unpacked into the `self.poll_events_from_shard(*current_shard_tuple)` and raising a type exception.
- Always propogate an exception from a `StreamPoller::get_records` call to the worker loop -- allowing for back-off between retries.
- Raise an exception when shard and iterator initialisation fails.
> [ESM] Reset shards in StreamPoller for DDB Local errors

- localstack-core/localstack/services/cloudwatch/provider_v2.py
- localstack-core/localstack/utils/analytics/usage.py
- localstack-core/localstack/utils/container_utils/container_client.py
- localstack-core/localstack/utils/functions.py
- pyproject.toml
- tests/aws/services/events/test_events.py
- tests/aws/services/route53resolver/test_route53resolver.py
As in dependent repositories, we have an issue with the ASF updates since the latest `ruff` update. The definition of the Python 3.9 target version in linting/formatting leads to syntax errors when enabling preview features like we do in the ASF update action.
To fix that, we need to define our versions correctly depending on if the code runs in the CLI or in the runtime (container)
- Set target version to `py311` matching our `.python-version`
- Set `per-file-target-version` to `py39` for all code accessed in the CLI matching our minimum required version
- Apply changes that are made necessary by upgrading the target version to `py311`
- Make code that can be reached by the CLI `py39` compatible (remove match statement from `usage.py`)
> Use per-file-target-version to define Python 3.9 for CLI code

- localstack-core/localstack/services/cloudformation/provider_utils.py
- tests/unit/services/cloudformation/test_provider_utils.py
This PR adds an utility to convert LowerCamelCase to PascalCase keys in a dictionary. Usefull for read methods in resource providers
- new utility for resource providers
> add resource provider utility to convert LowerCamelCase to Pascal

- tests/aws/services/cloudformation/api/test_changesets.py
- tests/aws/services/cloudformation/api/test_changesets.snapshot.json
- tests/aws/services/cloudformation/api/test_changesets.validation.json
- tests/aws/services/events/test_archive_and_replay.py
- tests/aws/services/events/test_archive_and_replay.snapshot.json
- tests/aws/services/events/test_archive_and_replay.validation.json
- tests/aws/services/events/test_events.py
- tests/aws/services/events/test_events.snapshot.json
- tests/aws/services/events/test_events.validation.json
- tests/aws/services/events/test_events_inputs.py
- tests/aws/services/events/test_events_inputs.snapshot.json
- tests/aws/services/events/test_events_inputs.validation.json
- tests/aws/services/events/test_events_schedule.py
- tests/aws/services/events/test_events_schedule.snapshot.json
- tests/aws/services/events/test_events_schedule.validation.json
- tests/aws/services/events/test_events_tags.py
- tests/aws/services/events/test_events_tags.snapshot.json
- tests/aws/services/events/test_events_tags.validation.json
As we fixed a snapshot leading to a test failure in https://github.com/localstack/localstack/pull/12367, I thought it was worth briefly going all over the repository and doing the same.
- Improve snapshots by matching the response instead of the exception info object.
> chore: improve remaining tests snapshots

- localstack-core/localstack/services/stepfunctions/asl/parse/test_state/preprocessor.py
We are getting some linter warning in the TestState preprocessor for Step Functions due to the misuse of `# noqa`.
The changes move the noqa motivations to their separate comments.
> Fix Invalid noqa Usage in Step Functions TestState Preprocessor

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_describer.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_visitor.py
In an effort to address the current limitations in the handling of stack updates and the ChangeSet workflow (describe, update, etc.), as well as other workflows such as stack creation, deletion, and rollback, this pull request introduces a new design approach to representing operations on stack templates. This design enables:
- Implementation of updates to stack templates, and creation/deletion operations.
- Logic that computes update graphs for different template versions.
- A visitor pattern for extension logic to operate on these update graphs.
- The ability to derive detailed ChangeSet descriptions via the new design model.
- ChangeSetModel: A POC class that, given one or two CloudFormation templates, produces an update graph. This graph can represent both template versions, and it …
> Cloud Formation: [POC] Modeling Stack Operations and Evaluating ChangeSet Descriptions

- localstack-core/localstack/services/cloudformation/v2/provider.py
- localstack-core/localstack/services/providers.py
In order to make improvements to the CFn engine, we have decided to add a new provider to update the functionality. It is useful to be able to update the provider methods for specific operations (typically around change sets) to change the template preprocessing etc.
Add a new provider under the name `engine-v2`. This can be enabled with `PROVIDER_OVERRIDE_CLOUDFORMATION=engine-v2`. There is no implementation for now.
> CFn updates: create new v2 provider for new engine

- localstack-core/localstack/services/iam/iam_patches.py
- localstack-core/localstack/services/iam/provider.py
- localstack-core/localstack/testing/snapshots/transformer_utility.py
- tests/aws/conftest.py
- tests/aws/services/iam/test_iam.py
- tests/aws/services/iam/test_iam.snapshot.json
- tests/aws/services/iam/test_iam.validation.json
IAM users can have service specific credentials assigned to them, they can be used for AWS CodeCommit (https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_ssh-keys.html) and Amazon Keyspaces (for Apache Cassandra) (https://docs.aws.amazon.com/keyspaces/latest/devguide/programmatic.credentials.ssc.html).
For now, we need to have an implementation of the CRUD part of this functionality.
This initally depended on localstack/localstack-snapshot#10, but the last commit removes that dependency to avoid this PR being blocked by it.
* LocalStack now supports service specific credential create, list, update, reset and delete operations.
> Implement IAM service specific credentials CRUD

- localstack-core/localstack/services/apigateway/legacy/provider.py
- tests/aws/services/apigateway/test_apigateway_api.py
- tests/aws/services/apigateway/test_apigateway_api.snapshot.json
- tests/aws/services/apigateway/test_apigateway_api.validation.json
As reported by https://github.com/localstack/localstack/issues/12115#issuecomment-2715763423, we had an issue with binary media types and CDK, which led to finding out Moto was not considering `binaryMediaTypes` in the `CreateRestAPI` operation
- add `binaryMediaTypes` to the REST API model
> fix APIGW binary media types

- localstack-core/localstack/services/sns/analytics.py
- localstack-core/localstack/services/sns/provider.py
- localstack-core/localstack/services/sns/usage.py
This PR replaces the analytics Counter used for tracking usage of internal SNS APIs. 
- replace the previous `UsageSetCounter` with the new `Counter` with labels
- rename the `usage.py` file in `analytics.py`
> SNS: migrate to new Counter type for analytics

- localstack-core/localstack/services/apigateway/next_gen/execute_api/template_mapping.py
- localstack-core/localstack/testing/pytest/fixtures.py
- tests/aws/services/apigateway/test_apigateway_common.py
- tests/aws/services/apigateway/test_apigateway_common.snapshot.json
- tests/aws/services/apigateway/test_apigateway_common.validation.json
When using VTL template for apigateway, AWS generally returns a java object string representation `{foo=bar}`. But when accessing a list through `$input.path('$')`, it returns a valid json string, even if there are dict inside. A nested list inside a dict will cause the encapsulated object to be json encoded as well `{list=[{"foo":"bar"}]}`.
This pr implements java representation for result of `$input.path` and proper list formatting. Follow ups will be required to implement the Java formatting over more results in the VTL template.
- Introduces `JavaDictFormatter` to return Java like object
- Implements `InputPathDictFormatter` and `InputPathListFormatter` to manage string formatting of children of `$input.path`
- Add tests
> Fix apigw input path formatting

- localstack-core/localstack/utils/analytics/metrics.py
@bentsku noticed this behavior while working on this [PR](https://github.com/localstack/localstack/pull/12383), thanks for the heads-up! 🚀 
Before this change, the classes `_CounterMetric` and `_LabeledCounterMetric` were "protected", which made it inappropriate to use them directly for static typing. This caused type hinting issues, particularly in cases where a Counter instance was assigned to a class attribute: 
```python
class TestClass:
counter: Counter
def __init__(self, counter: Counter):
self.counter = counter or Counter(name="test", labels=["l1"])
self.counter.labels(l1="test_value").increment()
```
The `CounterMetric` and `LabeledCounterMetric` classes have been made public, allowing clients to use them directly for typing. The use of TypeVar and …
> make counter classes public

- localstack-core/localstack/services/stepfunctions/asl/jsonata/jsonata.py
The current implementation starts the JVM during module import, which interferes with unrelated processes like generating entrypoints—especially on Windows machines, where it may break the entrypoint generation process entirely. This PR defers the startup of the JVM until the JSONata evaluation feature is actually needed first, ensuring that other processes remain unaffected by premature JVM initialization.
- Delay JVM instantiation until the first JSONata evaluation call, then cache the function reference to ensure fast, persistent access throughout the application’s runtime.
\* Known Limitation: The first invocation in a state with tight timeouts might trigger a timeout error in the evaluation of the state machine due to the JVM installation overhead. This edge case is rare, does not …
> Step Functions: Lazy Initialization of JVM for JSONata Evaluation 

- localstack-core/localstack/services/events/event_rule_engine.py
- tests/aws/services/events/test_events_patterns.py
- tests/aws/services/events/test_events_patterns.snapshot.json
- tests/aws/services/events/test_events_patterns.validation.json
- tests/aws/services/events/test_payloads/large_complex_payload.json
- tests/unit/services/events/test_event_ruler.py
As reported by #12390, when evaluate large payload for `PutEvents`, LocalStack would fail. I could reproduce the issue and saw LocalStack consumes as much as 20GB of memory while trying to evaluate the payload given by the user.
This payload was very complex, with lots of nested dictionaries and list. List are "exploding" the complexity, creating "or" conditions and new "branches" to evaluate. 
This is because we're using recursion to evaluate EventPattern against payload, and we would try to get the event payload in a flat shape to be able to be evaluated against the Pattern (due to how AWS treats the `.` notation). 
I've added some conditions checks to only evaluate the payload when relevant to the Event Pattern, and to not evaluate "branches" of the payload. This fixes the issue and …
> events: fix Event Ruler to not evaluate the full payload

- localstack-core/localstack/services/sns/filter.py
- tests/aws/services/sns/test_payloads/complex_payload.json
- tests/aws/services/sns/test_sns_filter_policy.py
- tests/aws/services/sns/test_sns_filter_policy.snapshot.json
- tests/aws/services/sns/test_sns_filter_policy.validation.json
- tests/unit/services/sns/test_sns.py
Follow up from #12394. I'm porting the fix to SNS as well as it suffered from the same issue.
Complex payload would explode in complexity, and we were evaluating them in their entirety instead of only evaluate what is needed evaluate the policy itself. AWS is doing the same thing.
- only evaluate the payload if relevant to the filter policy
- add AWS validated integration test for it and adapt unit tests
> SNS: fix Filter Policy engine to not evaluate full complex payload

- localstack-core/localstack/services/stepfunctions/asl/static_analyser/usage_metrics_static_analyser.py
- localstack-core/localstack/services/stepfunctions/usage.py
- tests/unit/services/stepfunctions/test_usage_metrics_static_analyser.py
This PR migrates our step functions usage metrics to the new Counter standards. It increases transparency by accurately reflecting the query language usage within each state machine. Previously, JSONata was always counted as used—even when combined with JSONPath. Since interleaved usage of both modes is critical for testing the shared memory model and understanding user reliance on this mechanism, the updated metrics now provide a clearer picture.
-  Migrated step functions usage metrics to the new Counter standards
- Consolidated tracking of language features into a single Counter per state machine on creation
- Updated query language detection logic to differentiate between exclusive and interleaved usage of JSONPath and JSONata
> Step Functions: Migrate Usage Metrics to New Counter Standards

- tests/aws/services/dynamodb/test_dynamodb.py
Skips a flaky DDB Streams test: `test_dynamodb_stream_records_with_update_item`
We've been seeing this test flake intermittently for a while now, and just happened today again:
https://app.circleci.com/pipelines/github/localstack/localstack/31682/workflows/bf8c139e-1007-4aaa-a6ed-a30970d79c25/jobs/282982
- skip `test_dynamodb_stream_records_with_update_item`
> DDBStreams: skip flaky test

- localstack-core/localstack/services/cloudformation/engine/entities.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_describer.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_visitor.py
- localstack-core/localstack/services/cloudformation/v2/provider.py
- tests/unit/services/cloudformation/test_change_set_describe_details.py
With the recent changes in https://github.com/localstack/localstack/pull/12355, we introduced a new design pattern for representing CloudFormation templates. However, that design did not account for deeper intra-template relationships, preventing accurate detection of indirect resource changes driven by dependencies or intrinsic functions. This PR addresses those limitations by introducing logic to traverse and resolve template elements and intrinsic functions, ensuring that updates and dependencies are correctly captured. It also resolves issues comparing null or empty template versions.
- Add logic to lazily traverse template files during update graph construction, capturing indirect changes driven by dependencies and intrinsic function evaluations.
- Introduce a pattern for resolving …
> Cloud Formation: [POC] Update Graph with Template Traversal & Intrinsic Function Resolution

- localstack-core/localstack/services/cloudformation/resource_provider.py
- localstack-core/localstack/services/cloudformation/usage.py
We are standardising on our metrics counters. This PR updates CloudFormation to use the new API rather than our own (non-standardised) `UsageSetCounter` API.
- Use the new counters
1. Start LocalStack with `DISABLE_EVENTS=0`
2. Deploy the following template with `awslocal cloudformation deploy --template-file <filename> --stack-name mystack`:
```yaml
Resources:
MyParameter:
Type: AWS::SSM::Parameter
Properties:
Type: String
Value: my-parameter
NonSupportedResource:
Type: AWS::Logs::ResourcePolicy
Properties:
PolicyName: "MyResourcePolicy"
PolicyDocument: "{ \"Version\": \"2012-10-17\", \"Statement\": [ { \"Sid\": \"Route53LogsToCloudWatchLogs\", \"Effect\": \"Allow\", \"Principal\": { \"Service\": [ \"route53.amazonaws.com\" ] }, \"Action\":\"logs:PutLogEvents\", \"Resource\": \"logArn\" …
```
> CFn: switch to new usage counters

- localstack-core/localstack/runtime/analytics.py
I'm often seeing customers configuring the `LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT`, potentially working around slow cold starts or runtime startup errors. Getting analytics helps to decide whether/how we should adjust the default value.
* [Track Lambda runtime environment timeout](https://github.com/localstack/localstack/commit/4e0166f0454399f679c761033b530253ad314c4e)
> Track Lambda runtime environment timeout

- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/analytics.py
This PR replaces the analytics Counter used for tracking usage of `execute-api` routes for API Gateway REST APIs.
- replace the previous UsageSetCounter with the new Counter with labels
To test the changes:
- run a LocalStack in host mode with this branch checked out
- run the `tests.aws.services.apigateway.test_apigateway_http.test_http_integration_method` integration test with `TEST_SKIP_LOCALSTACK_START=1` set, to avoid trying to start LocalStack with the test
shutdown LocalStack
- I've tried without sending the events but only printing the collected metrics and this is what I got:
```json
{
"metrics": [
{
"namespace": "apigateway",
"name": "rest_api_execute",
"value": 3,
"type": "counter",
"label_1_value": "HTTP",
"label_1": "invocation_type"
},
{
"namespace": "apigateway",
"name": …
```
> APIGW: migrate to new Counter type for REST API analytics

- pyproject.toml
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
This PR bumps moto-ext to 5.1.1.post1
> [!NOTE]
> Like the previous bump #12245, this release of Moto-Ext omits RDS refactor commits, along with the new response serialisation https://github.com/getmoto/moto/pull/8679
Contains:
- https://github.com/getmoto/moto/pull/8660
> Bump moto-ext to 5.1.1.post1

- localstack-core/localstack/services/events/analytics.py
- localstack-core/localstack/services/events/provider.py
- localstack-core/localstack/services/events/usage.py
This PR replaces the analytics Counter used for tracking usage of Event rule invocations. We merge both Counter for success and failure into one, and use the new labels instead. 
- merge the 2 counters into one with more labels
To test the changes:
- run a LocalStack in host mode with this branch checked out
- run the `tests.aws.services.events.test_events_targets.TestEventsTargetSqs.test_put_events_with_target_sqs` integration test with `TEST_SKIP_LOCALSTACK_START=1` set, to avoid trying to start LocalStack with the test
- shutdown LocalStack
I've tried without sending the events but only printing the collected metrics and this is what I got:
```json
{
"metrics": [
{
"namespace": "events",
"name": "rule_invocations",
"value": 1,
"type": "counter",
"label_1_value": "success", …
```
> Events: migrate to new Counter type for Event Rule invocation analytics

- localstack-core/localstack/services/apigateway/next_gen/execute_api/template_mapping.py
- localstack-core/localstack/testing/pytest/fixtures.py
- tests/aws/services/apigateway/test_apigateway_common.py
- tests/aws/services/apigateway/test_apigateway_common.snapshot.json
- tests/aws/services/apigateway/test_apigateway_common.validation.json
- tests/aws/services/apigateway/test_apigateway_sqs.py
- tests/aws/services/apigateway/test_apigateway_sqs.snapshot.json
- tests/aws/services/apigateway/test_apigateway_sqs.validation.json
- tests/unit/services/apigateway/test_template_mapping.py
We broke an upstream integration test following #12322, because API Gateway would forward an empty body to the SQS integration, and SQS disallows that.
This is because API Gateway will replace an empty body with `{}` when using `$input.body` in a VTL template.
I've added a few tests validating the assumption, and @dfangl added the SQS regression test to make sure we don't break upstream anymore. He also added some changes in the retry mechanism for deleting REST APIs, and I've updated it to use the Boto config in both creation and deletion of REST APIs. 
note: I've also tried with a request template set with `text/html` and the empty body is still `{}` so it's not dependent on the content-type. 
- return a `{}` string if the body is empty for `$input.body` (so that it can be passed to …
> APIGW: fix rendering of $input.body when empty

- localstack-core/localstack/config.py
- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
In order to address performance shortcomings, we should allow for a user to configure their poller frequency as well as their maximum backoff on error/empty polls.
- `StreamPollers` no longer back-off when a `GetRecords` call is empty
- `StreamPollers` back-off when no shards have been initialised.
- More debug logs have been added to show shard count.
- Adds the following config varibales:
- `LAMBDA_EVENT_SOURCE_MAPPING_POLL_INTERVAL_SEC` -> set all poller's per-second frequency.
- `LAMBDA_EVENT_SOURCE_MAPPING_MAX_BACKOFF_ON_ERROR_SEC` -> set maximum backoff on poller exception.
- `LAMBDA_EVENT_SOURCE_MAPPING_MAX_BACKOFF_ON_EMPTY_POLL_SEC` -> set maximum backoff on empty polls.
> [ESM] Add configurable poll frequency and log shard info

- localstack-core/localstack/state/inspect.py
Our persistence framework works by serializing and deserializing LocalStack's store and Moto's equivalent. These attributes are stored in a predictable module with a predictable name.
We used to log every time we were not able to load an attribute.
This log message has always been very confusing since it happens quite often even in perfectly fine circumstances (most notably, when a service only has a community implementation).
- Remove the log message when an attribute can't be found in the expected location.
> Better logging for ReflectionStateLocator

- localstack-core/localstack/runtime/analytics.py
- localstack-core/localstack/services/lambda_/invocation/counting_service.py
- localstack-core/localstack/services/lambda_/invocation/lambda_service.py
- localstack-core/localstack/services/lambda_/invocation/version_manager.py
- localstack-core/localstack/services/lambda_/lambda_utils.py
CloudFront Lambda@Edge requires some changes in Lambda to be able to re-use the existing Lambda infrastructure.
* Make the Lambda `Function` object optional in `counting_service::get_invocation_lease` such that we can re-use the counting service for Lambda@Edge, and skip reserved and provisioned concurrency
* Track version state in the version manager (i.e., fix unused self.state field)
* Refactor version manager such that the optional `function` is only used for the counting service
> Make Lambda reusable for CloudFront Lambda@Edge

- localstack-core/localstack/utils/batch_policy.py
- tests/unit/utils/test_batch_policy.py
Multiple services require data to be batched before further processing. Where batches can be collected based on:
- The number of records observed/collected (Batch count)
- A specified time-interval (Batch window)
- The number of underlying bytes collected (Batch size)
- Some other artibrary condition (i.e when a certain attribute is encountered then create a new batch)
To solve this problem, the new batcher utility class aims to standardize how we collect and return data needing to be batched. This has the following benefits:
- Standardizes a batching approach that can be re-used across multiple components
- Extendability allows us future versions to define custom batch policies that can be triggered on artibrary data.
- Adds a new `Batcher` utility that allows us to define a batch policy …
> [Utils] Add a batch policy utility

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker_factory.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
In order to reduce pressure on the LocalStack internal gateway, events being collected by ESM/Pipes pollers should be properly collected and and sent onto a target as a batch.
- Uses new `Batcher` utility that allows us to collect and batch records based on an ESM's `MaximumBatchingWindowInSeconds` and `BatchSize` configuration.
- Adds a `shard_batcher` dictionary to the `StreamPoller` that implements a batcher for each shard -- removing those batchers that do not correspond to shards each poll_event iteration.
We ran some performance tests comparing baseline LocalStack with implemented **Batching** and **Parallelised** invocations.
- Proper batching was implemented such that we only invoke a function when a `BatchSize` is met or a `MaximumBatchingWindowInSeconds` is reached
- Polling of …
> [ESM] Support Stream Poller batching

- localstack-core/localstack/services/kinesis/packages.py
@etspaceman released a new patch version of `kinesis-mock` yesterday: [`0.4.9`](https://github.com/etspaceman/kinesis-mock/releases/tag/v0.4.9)
This PR upgrades `kinesis-mock` from `0.4.8` to `0.4.9`.
See https://github.com/localstack/localstack/pull/12178 for the last upgrade.
- Changes the default version of the `kinesis-mock` package from `0.4.8` to `0.4.9`.
> update kinesis-mock from 0.4.8 to 0.4.9

- localstack-core/localstack/services/stepfunctions/resource_providers/aws_stepfunctions_statemachine.py
- tests/aws/services/cloudformation/resources/test_stepfunctions.py
- tests/aws/services/cloudformation/resources/test_stepfunctions.snapshot.json
- tests/aws/services/cloudformation/resources/test_stepfunctions.validation.json
- tests/aws/templates/statemachine_machine_logging_configuration.yml
This PR fixes a limitation in the CloudFormation resource provider for AWS Step Functions where the LoggingConfiguration parameters are not passed through during Create and Delete actions https://github.com/localstack/localstack/issues/11374. These changes address such limitation and add a related positive snapshot test.
> CloudFormation: Fix LoggingConfiguration Parameter Handling in StepFunctions Resource Provider

- localstack-core/localstack/testing/pytest/fixtures.py
- tests/aws/services/lambda_/functions/lambda_notifier.py
- tests/aws/services/lambda_/test_lambda.py
- tests/aws/services/lambda_/test_lambda.snapshot.json
- tests/aws/services/lambda_/test_lambda.validation.json
- tests/conftest.py
The test `test_reserved_concurrency_async_queue` is currently skipped due to flakiness.
* Add `aws_client_no_retry` fixture and use it in the testcase
* Re-design test case to use SQS-based notifications instead of unpredictable sleep
* Add `requests_id`-based assertions
Temporarily using a botocore configuration with increased retries makes the retry problem reproducible causing the test to fail. This shows that we need an `aws_client_no_retry` to mitigate potential flakiness and reduce unnecessary retries.
To reproduce:
1. Ensure that retries are not disabled by configuration: `TEST_DISABLE_RETRIES_AND_TIMEOUTS=0`
2. Use the following config:
```py
retry_delay_config = botocore.config.Config(retries={"max_attempts": 10})
retry_delay_client = aws_client_factory(config=retry_delay_config) …
```
> Fix flaky lambda test event retry reserved concurrency

- tests/aws/services/cloudformation/api/test_changesets.py
- tests/aws/services/cloudformation/api/test_changesets.snapshot.json
- tests/aws/services/cloudformation/api/test_changesets.validation.json
We are currently working on a new deployment engine for CloudFormation. We want to have some easy to use end to end tests that capture information about the deploy and update process (using Change Sets) to guide our implementation.
- Add a testing framework for capturing lots of useful information about the deployment process
- Add a helper function for capturing per-resource update steps
- Add some initial tests and findings from executing the tests
- tests are skipped if not using the new provider so the change does not impact the current provider
> CFn: add tests for capturing change set process

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_describer.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_visitor.py
- tests/unit/services/cloudformation/test_change_set_describe_details.py
…indinmap
Currently, the POC Update Graph approach to modeling CloudFormation templates does not support CloudFormation Mappings. In addition, intrinsic functions that depend on mapping lookups (Fn::FindInMap) is also unsupported in the modeling layer, which restricted the accuracy of the update graph and impacted downstream processes relying on this data. This PR introduces initial support for Mappings and Fn::FindInMap modeling, ensuring that such constructs are correctly parsed, modeled, and propagated through the update graph. The changes also add support for change set describe workflows involving maps. Relevant initial unit tests have been included to validate these enhancements.
- Added support for modeling CloudFormation Mappings within the Update Graph
- Implemented modeling …
> CloudFormation: [POC] Support Update Graph Modeling of Mappings and FindInMap

- pyproject.toml
With [PEP 639](https://peps.python.org/pep-0639/), the latest setuptools (>= 77.0) throws a warning when building projects with a deprecated license-format. This PR updates the format to the latest recommended format, removing all warnings.
The [Python Packaging docs](https://packaging.python.org/en/latest/specifications/core-metadata/#classifier-multiple-use) now also explicitly states that this is the recommended format:
| The use of License :: classifiers is deprecated as of Metadata 2.4, use License-Expression instead. See [PEP 639](https://peps.python.org/pep-0639/#deprecate-license-classifiers).
> Admin: Improve license metadata

- localstack-core/localstack/services/sqs/models.py
- localstack-core/localstack/services/sqs/utils.py
- tests/aws/services/sqs/test_sqs.py
- tests/aws/services/sqs/test_sqs.snapshot.json
- tests/aws/services/sqs/test_sqs.validation.json
As per title. FIFO messages should not be deleted if the provided receipt handle has expired, tests against AWS failed consistently. Reversely, the same test succeeded consistently on standard queues, making fifo specific code necessary.
fixes https://github.com/localstack/localstack/issues/12278
- adds tests to confirm the issue
- adds new methods to decouple some of the extraction steps for the receipt handle to access time-related information
- adds `_pre_delete_checks` hook when removing messages, because this behaviour is fifo specific, and a complete remodel of the delete method to separate standard and fifo behaviour to make this cleaner was out of scope for this PR.
> Deleting a FIFO message with an expired receipt handle should raise an error

- localstack-core/localstack/services/lambda_/provider.py
- localstack-core/localstack/services/lambda_/runtimes.py
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/aws/services/lambda_/test_lambda_api.validation.json
- tests/aws/services/lambda_/test_lambda_common.snapshot.json
- tests/aws/services/lambda_/test_lambda_common.validation.json
AWS announced support for Ruby 3.4 Lambda runtime on March 27th and we want to support it quickly.
https://aws.amazon.com/about-aws/whats-new/2025/03/aws-lambda-support-ruby-3-4/
- Added support for the new Lambda runtime Ruby 3.4
- Updated snapshots
- Reverted some of the (temporary?) changes introduced in this PR for `test_snapstart_lifecycle`  and `test_snapstart_update_function_configuration`: https://github.com/localstack/localstack/pull/12006/ because AWS seems to not support snapstart enabled functions for many runtimes anymore (they seems to temporarily allow them 🤷🏼 ).
**`botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: nodejs22.x is not supported for SnapStart enabled functions.`**
> Lambda: Added Ruby 3.4 Runtime

- localstack-core/localstack/services/lambda_/invocation/assignment.py
- localstack-core/localstack/services/lambda_/invocation/execution_environment.py
- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/test_lambda.py
We recently discovered that a race condition is possible, killing in-progress invocations of lambda functions if the environment is scheduled for removal due to inactivity at the same time.
This will lead to different errors (depending on the phase of the execution), and has to be fixed.
Also, the error messages we return to the caller in case of internal errors during invocations do not convey the actual error - making it harder to trace the error, especially for internal calls.
Here we fix this, to clearly communicate the error to the caller.
Old error message:
```
Internal error while executing lambda
```
New error message (containing request id and function name + qualifier):
```
[fd2d870e-827c-44a2-b365-2eb7efc38e86] Internal error while executing lambda test-function-28f7fd59:None. …
```
> Fix lambda timeout race condition

- localstack-core/localstack/services/lambda_/invocation/logs.py
- tests/aws/services/lambda_/functions/lambda_cloudwatch_logs.py
- tests/aws/services/lambda_/test_lambda.py
- tests/aws/services/lambda_/test_lambda_runtimes.py
- tests/aws/services/lambda_/test_lambda_runtimes.snapshot.json
- tests/aws/services/lambda_/test_lambda_runtimes.validation.json
With #10294 we had to revert increased performance for lambda cloudwatch logs, reduced requests necessary for every log storage from 3 to (on average) 1.
The root cause for this revert was the `.splitlines()` method used to split the logs, as it also splits on several other characters, like a carriage return, unlike the old log method.
Since the runtime interface clients patch the loggers (e.g. here: https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/blob/2ea9a34b5c1b15621df132eb2d377ac54b330c8f/src/LogPatch.js#L82-L88), we need to leave carriage returns as is for now.
In the long term, to further increase logging parity, we need to:
1. Properly log the `INIT_START` message (this should allow for proper snapshotting of logs as well then, as the count should align)
2. Use …
> Reapply reduce requests necessary for log publishing from lambda to cloudwatch logs

- localstack-core/localstack/services/ec2/patches.py
- tests/aws/services/ec2/test_ec2.py
#11853 introduced a regression whereby the structure of the tags dict was altered before passing through to moto.  This was reported in #12377 and is fixed by this PR.
Whilst fixing this PR, I noticed that the tags were also lost when creating a subnet, SG or VPC with a custom ID.
* Pass the original tags dict through to moto on subnet creation, rather than the modified one.
* Because tags are not stored within the subnet, VPC or SG objects within moto, but instead in a separate tags dict, the tags needed to be reindexed in that dict when using a custom id.
> Fix subnet tags going missing

- localstack-core/localstack/services/kms/models.py
- tests/aws/services/kms/test_kms.py
- tests/aws/services/kms/test_kms.snapshot.json
- tests/aws/services/kms/test_kms.validation.json
When using an RSA key to sign with PSS algorithm, currently the salt length is set to be `MAX_LENGTH`, which is not in accordance with the ones required by RFC 4055 making making it difficult to verify such signatures across platforms: https://datatracker.ietf.org/doc/html/rfc4055#section-3.3. 
Closes https://github.com/localstack/localstack/issues/9602
This PR: 
- sets the salt length appropriately for the signing algorithm being used.
- adds an AWS validated test to validate the changes to sign with an aws client and verify the signature using `cryptography` library.
> KMS: fix RSA PSS signing issue for salt length

- localstack-core/localstack/utils/docker_utils.py
Minor improvements around the logging when checking if a port is available.
An ealier version of this PR also changed the image to use `bash` instead, but some benchmarks showed that using a smaller image does not improve the performance. This method always takes around `35ms`, regardless of the exact image used.
For reference, this was the original description:
~To check if a certain port is available, we currently start a second LocalStack instance with those ports reserved, and check if it fails. Starting LocalStack is quite resource-intensive - using a smaller image (like `bash`) is much faster. (This is especially important when calling this method multiple times in parallel.)~
> Docker: Improve error messages around port-bound check

- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/dynamodb_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/kinesis_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
We do not currently cater for the case of a next shard iterator value not being present in a `GetRecords` response. According to the [AWS doc](https://docs.aws.amazon.com/streams/latest/dev/troubleshooting-consumers.html#getrecords-returns-empty):
> In a production scenario, the only time the continuous loop should be exited is when the NextShardIterator value is `NULL`. When NextShardIterator is `NULL`, it means that the current shard has been closed and the ShardIteratorvalue would otherwise point past the last record.
In addition, DynamoDB Local can occasionally not return a `NextShardIterator` in its response. This seems to occur when trying to read from a closed shard or when using an expired iterator. Hence, an exception is raised since the StreamPoller always expects this field in …
> [ESM] Re-initialize shards when NextShardIterator value is empty

- pyproject.toml
Followup to #12455 
I originally made this same change in Moto, but PyPi actually rejects this `License-Expression` with the following error:
> ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
'License-Expression :: OSI Approved :: Apache Software License' is not 
a valid classifier. See https://packaging.python.org/specifications/core-metadata for more information.
The reason: even though PEP 639 talks about the _License-Expression_ field, that is actually a Core Metadata field. And a [Core Metadata field](https://packaging.python.org/en/latest/glossary/#term-Core-Metadata-Field) is described as:
> A single key-value pair (or sequence of such with the same name, for multiple-use fields) defined in the [Core …
> Admin: Update License

- localstack-core/localstack/dev/run/configurators.py
- localstack-core/localstack/services/lambda_/invocation/docker_runtime_executor.py
- localstack-core/localstack/utils/analytics/metadata.py
- localstack-core/localstack/utils/bootstrap.py
- localstack-core/localstack/utils/container_utils/container_client.py
- localstack-core/localstack/utils/container_utils/docker_cmd_client.py
- tests/bootstrap/test_container_configurators.py
- tests/bootstrap/test_init.py
- tests/unit/test_docker_utils.py
- tests/unit/utils/test_bootstrap.py
This PR refactors the usage of `get_host_path_for_path_in_docker`. 
This utility is very specific, assuming:
1. The volume dir is mounted as bind mount
2. We are using docker (or something API compatible, like podman) for spawning containers
To overcome these restrictions in the long term, I added a new type of mount for our container clients, the `VolumeDirMount`.
This mount should convey the intent to make the contents of a subpath of `/var/lib/localstack` (as path inside the LS container) available to the target container - however this happens.
This shifts the responsibility for this from the services to the docker client - which can then decide how it is achieved.
Currently this will continue to be `get_host_path_for_path_in_docker`, but in the future support for named volumes and …
> Add new volume dir mount option, rename VolumeBind to BindMount

- localstack-core/localstack/services/lambda_/resource_providers/aws_lambda_function.py
- localstack-core/localstack/services/lambda_/resource_providers/aws_lambda_function.schema.json
- tests/aws/services/cloudformation/resources/test_lambda.py
- tests/aws/services/cloudformation/resources/test_lambda.snapshot.json
- tests/aws/services/cloudformation/resources/test_lambda.validation.json
- tests/aws/templates/cfn_lambda_logging_config.yaml
Customer reported in https://github.com/localstack/localstack/issues/12424 that `LoggingConfig` is not set properly via Cloudformation.
- Added `LoggingConfig` param in `LambdaFunctionProvider` _kwargs_ used to  create and update lambda in: `lambda_/resource_providers/aws_lambda_function.schema.json`
- Updated schema specification (& manually tackled custom logic) via [scaffolding](https://www.notion.so/localstack/Writing-a-Resource-Provider-d83bbd2d17ec4bff90d193f232a4e945): `python -m localstack.services.cloudformation.scaffolding generate --resource-type "AWS::Lambda::Function" ...`
- Added aws validated test `test_lambda_logging_config`
> CFn: Add Lambda Function LoggingConfig

- localstack-core/localstack/services/kms/models.py
- localstack-core/localstack/services/kms/provider.py
- tests/aws/services/kms/test_kms.py
- tests/aws/services/kms/test_kms.snapshot.json
- tests/aws/services/kms/test_kms.validation.json
Add ability to decrypt data that was encrypted before the rotation event by preserving the history of the key material on `RotateKeyOnDemand`. 
Closes: https://github.com/localstack/localstack/issues/10723
Store all the previous crypto keys with a maximum of 10 times per KMS key (checkout the [AWS Documentation](https://docs.aws.amazon.com/kms/latest/APIReference/API_RotateKeyOnDemand.html)) to ensure the decryption of the data that was encrypted before the rotation of the key.
Validate the implementation using AWS validated snapshot tests.
> KMS: add ability to decrypt data with all rotated keys

- localstack-core/localstack/services/kms/models.py
- tests/aws/services/kms/test_kms.py
This PR fixes an issue where custom key material provided via the `_custom_key_material_` tag during kms `create-key` for ECC keys is ignored.
Closes https://github.com/localstack/localstack/issues/11678
Enables `_custom_key_material_` for ECC keys and verifies the implementation using a test with `ECC_SECG_P256K1` key specification.
> KMS: enable `_custom_key_material_` for ECC keys

- pyproject.toml
- requirements-dev.txt
- requirements-test.txt
- requirements-typehint.txt
- tests/aws/services/events/test_events_targets.py
- tests/conftest.py
In the past we were facing issues with our integration tests timing out due to shutdowns being blocked. It turns out that some of the `pytest-httpserver` threads were not properly shut down. @bentsku fixed this by patching the `HTTPServer` class to spawn a deamon thread to make sure that it cannot block the shutdown of the interpreter with https://github.com/localstack/localstack/pull/10052.
This patch broke with the latest release, as the `start` method was modified (which is why we did not upgrade to the latest version 1.1.2, but introduced an upper limit with https://github.com/localstack/localstack/pull/12303/commits/01a97ba1fa8619da6266815f88c542f7ea952011).
This PR updates the patch and updates the dependency declaration for `pytest-httpserver`. I also filed …
> unpin pytest-httpserver, fix patches

- localstack-core/localstack/services/stepfunctions/asl/utils/boto_client.py
To temporarily reduce the impact of transient network instability in concurrent Lambda executions, this PR increases the total number of retry attempts for the boto client from 1 to 5. Due to occasional “connection refused” errors, the previous setting would immediately trigger retry workflows in the state machine. This could significantly increase the runtime of the program if large backoff rates or wait settings were used in case of failures https://github.com/localstack/localstack/issues/12399. This change does not affect the semantics of evaluation. Catch and Retry blocks still function as intended, but it makes the state machine slightly more resilient against non-service errors such as transient connection failures.
- increase the total_max_attempts of service integrations
> Step Functions: Increase Retry Attempts on Service Integrations for Resilience Against Transient Network Errors

- localstack-core/localstack/testing/pytest/fixtures.py
- localstack-core/localstack/utils/aws/arns.py
- tests/aws/services/ses/test_ses.py
Companion PR for https://github.com/localstack/localstack-ext/pull/4318. Simply adds an arn utility method and moves a fixture.
- Implementing `ses_identity_arn`;
- Moving the `setup_sender_email_address` fixture.
> SES: add ARN utility for SES identity

- localstack-core/localstack/services/apigateway/helpers.py
- localstack-core/localstack/services/apigateway/legacy/provider.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/test_invoke.py
- localstack-core/localstack/services/apigateway/next_gen/provider.py
- tests/aws/services/apigateway/apigateway_fixtures.py
- tests/aws/services/apigateway/conftest.py
- tests/aws/services/apigateway/test_apigateway_api.py
- tests/aws/services/apigateway/test_apigateway_basic.py
- tests/aws/services/apigateway/test_apigateway_basic.snapshot.json
- tests/aws/services/apigateway/test_apigateway_basic.validation.json
The `TestInvokeMethod` operation was still relying on the legacy invocation logic of API Gateway. This PR migrates it to not rely on old code anymore and use the new handler chain, create one and invoke it. 
I've also improved the test, it is now fully transformed and can run against AWS with snapshot validation enabled. 
Also took the opportunity to remove some old "fixtures" doing nothing. 
- implement new TestInvokeOperation for the NextGen provider
- create new file keeping all of this together (might be better organized to be honest... but it's also not very important at the moment? should it have better encapsulation?)
- adapt the existing test to allow better parity
- clean up some old APIGW "fixtures"
> APIGW: migrate TestInvokeMethod to NextGen

- localstack-core/localstack/services/cloudformation/engine/quirks.py
While implement AVP resource providers, it appeared that we needed to add custom composites refs for some of its resources.
The values are... quite random. Both `Policy` and `IdentitySource` follow the "own resource id"|"policyStoreId" but `PolicyTemplate` is reversed, and has "PolicyStoreId"|"own resource id" order 🤷 
- add `AWS::VerifiedPermissions::IdentitySource`, `AWS::VerifiedPermissions::Policy`, `AWS::VerifiedPermissions::PolicyTemplate` to the list of quirks
> add AVP to list of CFN composite quirks

- localstack-core/localstack/services/sts/models.py
- localstack-core/localstack/services/sts/provider.py
- tests/aws/services/sts/test_sts.py
- tests/aws/services/sts/test_sts.snapshot.json
- tests/aws/services/sts/test_sts.validation.json
This PR adds IAM transitive session tagging support for the STS `assume_role` operation.
By now storing both session tags, and transitive session tags in the session store, we can make use of them for IAM enforcement.
The session tag store for a session will now include both new tags and transitive tags from the assuming session.
This leads to proper aggregation of transitive tags over role chaining operations.
* Store transitive session tags when creating new sessions
* Introduce some input validation for tags and transitive tags
> Support IAM transitive session tagging

- localstack-core/localstack/cli/localstack.py
- localstack-core/localstack/cli/main.py
- localstack-core/localstack/cli/profiles.py
- tests/unit/cli/test_profiles.py
We've had feedback that mandating the `--profile` option be specified at the top level, before any actions, is overly restrictive and causes headaches when wrapping the CLI in custom developer tools.  The following currently works:
```bash
localstack --profile=custom start
```
but the following:
```bash
localstack start --profile=custom
```
fails with:
> Usage: localstack start [OPTIONS]
> Try 'localstack start -h' for help.
> 
> Error: No such option: --profile
`--profile` can now be specified at any point.  This is achieved by removing any occurrences of  `--profile` options from the command line arguments (`sys.argv`) before click gets invoked.
The profile option was already being read and used before click was invoked, and click performed no further processing of it.  The only …
> Add profile as an option to every click command

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- tests/aws/services/cloudformation/v2/test_change_set_conditions.py
- tests/aws/services/cloudformation/v2/test_change_set_conditions.snapshot.json
- tests/aws/services/cloudformation/v2/test_change_set_conditions.validation.json
- tests/aws/services/cloudformation/v2/test_change_set_mappings.py
- tests/aws/services/cloudformation/v2/test_change_set_mappings.snapshot.json
- tests/aws/services/cloudformation/v2/test_change_set_mappings.validation.json
This PR introduces foundational boundary tests for computing update graphs and pre-processing CloudFormation template updates that involve changes to Mappings and Conditions. Additionally, it enhances the resource pre-processing logic to more accurately handle the addition and removal of both positive and negative conditions across updates.
- base boundary tests for updates with Mappings and Conditions changes
- improve the preprocessing of resources by handling the introduction or removal of conditions
> CloudFormation Engine v2: Base Mappings and Conditions tests for Update Graph and PreProc

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_describer.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_executor.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- tests/aws/services/cloudformation/api/test_changesets.py
This PR resolves several issues in the Engine V2 provider related to template delta handling and reference evaluation. Specifically, it addresses:
- Misinterpretation of deltas in templates where property definitions are empty or missing
- Faulty comparison logic in preprocessor delta conditions, where the absence of a condition was incorrectly treated as a match
- Limited handling of reference evaluation when a physical ID changes during updates
- Additional minor issues and inconsistencies
- Fixed misinterpretation of deltas in templates with empty/missing properties
- Corrected logic for comparing preprocessor delta conditions
- Improved handling of Ref evaluation across physical ID changes
- Fixed the lack of describe and execution pruning for unchanged resources
- Addressed various …
> CloudFormation Engine V2: Improve delta computation of properties, conditional resolution, and physical resources ref

- pyproject.toml
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
- tests/aws/services/cloudformation/resources/test_ec2.py
- tests/aws/services/cloudformation/resources/test_ec2.snapshot.json
- tests/aws/services/cloudformation/resources/test_ec2.validation.json
This PR bumps moto-ext to 5.1.3.post1.
> [!NOTE]
> The last few moto-ext bumps were heavily cherry picked to omit certain incompatible changes. The affected components have been fixed, so this release brings everything up-to-date with Moto upstream.
```
FAILED tests/aws/services/cloudformation/resources/test_customresources.py::test_customresource_lambda_backed - AssertionError: assert 'custom-data' == 'unknown'
FAILED tests/aws/services/cloudformation/resources/test_customresources.py::test_customresource_sns_backed - AssertionError: assert 'custom-data' == 'unknown'
FAILED tests/aws/services/cloudformation/resources/test_customresources.py::test_update_custom_resource - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
> Bump moto-ext to 5.1.3.post1

- localstack-core/localstack/services/cloudformation/engine/template_deployer.py
- localstack-core/localstack/services/cloudformation/resource_provider.py
Changes from #12511 broke custom resources plugin loading in upstream repo.
- Bring back usage of the method
> revert removal of get_resource_type method

- localstack-core/localstack/utils/container_utils/docker_cmd_client.py
The [existing PR](https://github.com/localstack/localstack/pull/12236) seems to be waiting on a small change, so to speed up the process I made the change here.
[Related Bug report](https://github.com/localstack/localstack/issues/12084)
When invoking _transform_container_labels, I added a check to veryify is the supplied parameter is already a Dict, which is the default in Podman. if so return the Dict, otherwise split the string and transform it into a Dict as usual.
semver: patch
> apply fix for podman container labels dict

- localstack-core/localstack/services/apigateway/next_gen/provider.py
- tests/aws/services/apigateway/test_apigateway_api.py
When setting a custom id for a REST API and using the `_custom_id_` tag, using an hyphen will make the API fail because the routing won't work, as the regex explicitly doesn't match hyphens: `<regex('[^-]+'):api_id>`, to avoid matching on the `-vpce` part. 
It would fail silently, because it wouldn't be able to find the API. 
We now validate the custom id to not allow `-` character in it. 
Note: maybe another solution would be to adapt the regex to allow hyphens, but didn't want to take the risk to change it, and this has been the behavior since this has been introduced. 
- add validation and adapt existing test
> APIGW: validate REST API custom id tag

- localstack-core/localstack/services/kms/exceptions.py
- localstack-core/localstack/services/kms/models.py
- localstack-core/localstack/services/kms/provider.py
- localstack-core/localstack/services/kms/utils.py
- tests/aws/services/kms/test_kms.py
- tests/aws/services/kms/test_kms.snapshot.json
- tests/aws/services/kms/test_kms.validation.json
- tests/unit/services/kms/test_kms.py
I am adding support for the _dry_run_ parameter to the **GenerateDataKeyPair** and **GenerateDataKeyPairWithoutPlaintext** operations to align with AWS behavior and enhance validation capabilities. 
Reference: [AWS KMS Dry Run Documentation](https://docs.aws.amazon.com/kms/latest/developerguide/testing-permissions.html)
Before these changes, the **GenerateDataKeyPair** and **GenerateDataKeyPairWithoutPlaintext** operations in KMS did not take the _dry_run_ parameter into account. This PR updates both operations to properly respect the _dry_run_ flag, aligning their behavior with AWS expectations.
Since IAM permission checks are not yet implemented in KMS, the primary purpose of this functionality is to determine whether a request would succeed (in which case a **DryRunOperationException** …
> Add dry_run support to GenerateDataKeyPair/GenerateDataKeyPairWithoutPlaintext.

- localstack-core/localstack/aws/api/ec2/__init__.py
- localstack-core/localstack/aws/api/events/__init__.py
- localstack-core/localstack/aws/api/resource_groups/__init__.py
- localstack-core/localstack/services/events/provider.py
- localstack-core/localstack/services/events/v1/provider.py
- pyproject.toml
- requirements-base-runtime.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
With the latest release of `awscli==1.39.0` / `botocore==1.38.0` / `boto3==1.38.0` the [ASF update action started to fail with dependency resolution issues](https://github.com/localstack/localstack/actions/runs/14612933999):
```
ERROR: Cannot install boto3==1.38.0, botocore==1.38.0, localstack-core (pyproject.toml), moto-ext and moto-ext[all]==5.1.3.post1 because these package versions have conflicting dependencies.
```
It turns out that this is due to the fact that there was an update of a transitive dependency of `awscli`: `docutils` was upgraded to version `0.19.0`. This does not work with the way how we currently update the package as it does not consider transitive dependencies of `awscli`:
https://github.com/localstack/localstack/blob/77f30dcd2ed68017e4972d81d5f69a86bcab2b5f/.github/ …
> Manually update ASF APIs and all dependencies

- localstack-core/localstack/services/apigateway/next_gen/execute_api/router.py
- localstack-core/localstack/services/apigateway/next_gen/provider.py
- tests/aws/services/apigateway/test_apigateway_api.py
- tests/aws/services/apigateway/test_apigateway_common.py
Follow-up from #12539, sorry for back and forth on this.
A failure on our upstream pipeline put into light the fact that the `-` character would still work when using "path based routing" for the API.
In order to not break existing users' setup, I'm removing the previous restriction, and instead updating the regex to allow for dashes in the REST API id, as this is actually a simple fix (making the quantifier be lazy to not match the next regex group). 
- add a `only_localstack` test showing that the routing works with hyphen
- remove previous restriction
> APIGW: fix Host regex to allow hyphen and remove restriction

- localstack-core/localstack/utils/coverage_docs.py
- tests/unit/aws/test_skeleton.py
- tests/unit/utils/test_coverage_docs.py
By refining our coverage error messages to explicitly distinguish between license-plan restrictions and missing LocalStack emulation, developers immediately know whether they need to upgrade or await feature support. This is especially valuable for integrated services like Step Functions, where missing or unlicensed services defined in the state machines can result in evaluation failure.
- Error for service action limitations rewritten from 
```API action <action-name> for service <service-name> not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/coverage_s3/ for further information```
to
```The API action <action-name> for service <service-name> is either not available in your current license plan or has not yet been emulated by LocalStack. …
```
> Clarify coverage error messages to distinguish license and emulation limits

- localstack-core/localstack/testing/pytest/stepfunctions/utils.py
The Step Functions v2 integration suite currently comprises ~900 tests that all poll for state-machine completion. Because we use identical polling logic, without any environment-specific callbacks, for both AWS and LocalStack, every test incurs the same wait time regardless of backend. 
In practice, LocalStack completes executions far more quickly than AWS, so these uniform delays become needless overhead when running tests locally. As the test count continues to grow (especially with the addition of many fast mock-response tests), overall runtime will only climb higher, slowing down feedback for developers.
With these changes I cut the sampling wait periods down to `0.2` seconds for LocalStack runs, which trims the overall test suite runtime by about 1.5 folds locally.
- Reduce sampling …
> Step Functions: Decrease LocalStack Sampling Delays to Speed Up Tests Suite

- CODEOWNERS
This PR adds myself and @silv-io to Codeowners of `.circleci` and `.github`. This change will help us to ensure that we do not miss any changes in CI/CD pipelines during migration from CircleCI. Once the migration from CircleCI is complete, we'll determine whether our role as code owners is still necessary.
Also discussed here: https://github.com/localstack/localstack/pull/12556#issuecomment-2829601201
- Added myself and @silv-io to Codeowners of `.circleci` and `.github`
> Added new codeowners for CircleCI and GithubActions

- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
- localstack-core/localstack/services/lambda_/invocation/version_manager.py
We currently do not log any details about unhandled exceptions or BatchFailureError in the stream poller, which makes debugging hard.
Context: the exception details might be logged as error further down the invocation chain, for example in `localstack.services.lambda_.event_source_mapping.esm_event_processor.EsmEventProcessor.process_events_batch` starting with `Unhandled exception while processing Lambda event source mapping ...`
One of the challenges is that ESM and Pipes share infrastructure and require different metadata logging, but the poller is at the top level in the invocation chain. We would need to raise a decorated error to provide sufficient context for meaningful top-level error logging without such duplication.
* Add `exc_info` for debug logs
* Bump log level to error for …
> Improve stream poller exception logging

- localstack-core/localstack/services/events/provider.py
- localstack-core/localstack/services/events/utils.py
To capture the internal step that transforms the event in EventStudio we utilize a proxy `_proxy_capture_input_event`. In EventStudio we extract the region and account_id from the actual transformed event, but for cross region / cross account event bus to event bus communication, the region and account id in the transformed event is preserved from the region and account of the original "sender" event bus.
- adding account_id and region as additional input to `_proxy_capture_input_event`
> feat: add current region and account as input to _proxy_capture_input_event

- tests/aws/services/stepfunctions/v2/mocking/test_base_scenarios.py
The mocked integration test at `aws.services.stepfunctions.v2.mocking.test_base_scenarios.TestBaseScenarios.test_lambda_invoke` introduced in e8b8794e37a025948b42f3b3f8aadd4958b7c97b is not compatible with multi-region test runs; these changes resolve this incompatibility.
- Insert the test environment's region name into this mock ARN to maintain snapshot compatibility across multi-region tests
- multi-region job: https://app.circleci.com/pipelines/github/localstack/localstack/32466/workflows/6925f6bc-dc15-48fa-b047-8767394e3f13
> Step Functions: Fix Mock Test for Multi-Region

- localstack-core/localstack/services/apigateway/analytics.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/__init__.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/analytics.py
When migrating to GH Actions, we've seen this strange issue pop up in API Gateway:
```python
2025-04-29T18:02:37.1793745Z 2025-04-29T18:02:37.177 ERROR --- [PoolThread-twisted.internet.reactor-2] plux.runtime.manager       : error loading plugin PluginSpec(localstack.aws.provider.apigateway:default = <function apigateway at 0xff2981162e80>)
2025-04-29T18:02:37.1794844Z Traceback (most recent call last):
2025-04-29T18:02:37.1805344Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/plux/runtime/manager.py", line 348, in _load_plugin
2025-04-29T18:02:37.1806131Z     result = plugin.load(*args, **kwargs)
2025-04-29T18:02:37.1806453Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-04-29T18:02:37.1807069Z   File "/opt/code/localstack/localstack-core/localstack/services/plugins.py", …
```
> refactor Counter usage in APIGW

- .pre-commit-config.yaml
- pyproject.toml
- requirements-base-runtime.txt
- requirements-basic.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
We repeatedly run into issues of kclpy wheels not being able to build inside of our pipelines (in the Docker build). This is because kclpy needs to download JARs from maven and there is no built wheel including those JARs available in PyPI. 
However, we can just create and publish that wheel once ourselves and then use our own published package/wheel instead - therefore not relying on maven anymore.
- Switch from `amazon-kclpy` to `kclpy-ext`, which we build and publish in the https://github.com/localstack/amazon-kinesis-client-python repo. 
The existing kinesis test suite should handle this sufficiently. After all, this should be the exact same package, just with a pre-built wheel available
<!--
> Switch to using `kclpy-ext`

- localstack-core/localstack/services/events/api_destination.py
- localstack-core/localstack/services/events/connection.py
Following some issues to recreate internal services that hold state as those are re-creating their own ID every time you re-instantiate them, leading to issue in the persistence mechanism. 
These class methods allow to recreate them and override the internal state they set. 
- add 2 class methods to recreate internal services for Events
> Events: add classmethod to recreate services

- localstack-core/localstack/services/apigateway/exporter.py
- localstack-core/localstack/services/apigateway/helpers.py
- tests/aws/files/pets.json
- tests/aws/services/apigateway/test_apigateway_basic.py
- tests/aws/services/apigateway/test_apigateway_extended.py
- tests/aws/services/apigateway/test_apigateway_extended.snapshot.json
- tests/aws/services/apigateway/test_apigateway_extended.validation.json
- tests/aws/services/apigateway/test_apigateway_import.py
- tests/aws/services/apigateway/test_apigateway_import.snapshot.json
- tests/aws/services/apigateway/test_apigateway_import.validation.json
- tests/aws/services/cloudformation/resources/test_apigateway.py
- tests/aws/services/cloudformation/resources/test_apigateway.snapshot.json
- tests/aws/services/cloudformation/resources/test_apigateway.validation.json
- tests/aws/templates/apigateway.json
- tests/aws/templates/apigateway_integration_from_s3.yml
We've recently received a report that binary support for APIGW wasn't working when deploying a REST API through CloudFormation and using the `Body` attribute to use an OpenAPI spec file to define the API. 
The OpenAPI spec file didn't define binary media types via the `x-amazon-apigateway-binary-media-types`, but it did with the [CloudFormation parameter `BinaryMediaTypes`](https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-binarymediatypes).
After testing against AWS, it seems the behavior is defined by the `merge` mode when calling `PutRestApi` for an existing API, and it will be merged by default with the custom extension when using CloudFormation. 
- update support for binary media types when used with the …
> APIGW: fix binaryMediaTypes when importing/updating REST APIs

- localstack-core/localstack/services/lambda_/invocation/counting_service.py
- tests/aws/services/lambda_/test_lambda.py
- tests/aws/services/lambda_/test_lambda.snapshot.json
- tests/aws/services/lambda_/test_lambda.validation.json
Currently, when setting provisioned concurrency on a lambda alias pointing to a version, and then invoking it, there will still be another container spawned up on demand.
This happens due to an error in the lookup of the provisioned concurrency config in the counting service, which issues leases for environments.
* Provisioned concurrency environments of a config set on an alias should now work as expected
> Fix provisioned concurrency set on Lambda alias

- localstack-core/localstack/packages/api.py
- tests/aws/conftest.py
Currently, we import the `localstack.testing.scenario.provisioning` module on every pytest run, which in turns imports the aws_cdk python bindings.
This leads to a heavy increase in startup time, especially when debugging (tested in Pycharm).
By deferring the import to the first fixture usage, instead of on all imports, that increased delay will only happen for tests actually requesting the fixture, instead of all tests.
For unrelated tests, this can reduce the start time of the test (on my system):
* When debugging, from 46 to 7 seconds
* Without debugging, from 7 to 1 seconds
CI runtime should only marginally be affected, only if test selection selects tests without a single usage of the infra provisioner.
I also fixed the mypy precommit errors happening on my system, by ignoring the …
> Defer CDK imports in infra provisioning

- .github/workflows/aws-tests-mamr.yml
- .github/workflows/aws-tests.yml
The `aws-main.yml` workflow was failing due to missing secrets input in `aws-tests.yml`; this has been fixed. I also noticed the MA/MR tests lack secrets definition for the reusable workflow `aws-tests.yml` and added them
- Added secrets input to the `workflow_call` event to enable passing Docker pull secrets into `aws-tests.yml`
- Added docker pull secrets to the MA/MR tests because it reuses `aws-tests.yml` workflow
> Added secrets definition for docker pull action in aws-tests and aws-mamr tests

- localstack-core/localstack/services/lambda_/resource_providers/aws_lambda_version.py
- localstack-core/localstack/services/lambda_/resource_providers/lambda_alias.py
- tests/aws/services/cloudformation/resources/test_lambda.py
- tests/aws/services/cloudformation/resources/test_lambda.snapshot.json
- tests/aws/services/cloudformation/resources/test_lambda.validation.json
- tests/aws/services/lambda_/test_lambda.py
- tests/aws/templates/cfn_lambda_alias.yml
- tests/aws/templates/cfn_lambda_version_provisioned_concurrency.yaml
Depends on https://github.com/localstack/localstack/pull/12592
Testing for a support issue revealed an auxiliary issue that provisioned concurrency is not implemented for the CloudFormation resource [AWS::Lambda::Version](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-version.html).
* Add support for provisioned concurrency config in the Lambda version CloudFormation resource provider
* Add aws-validated test case `test_lambda_version_provisioned_concurrency`. I opted for creating a separate test case for provisioned concurrency to ensure both paths work independently, especially given that provisioned concurrency includes different waiters (takes much longer). Feel free to suggest if combining them would be better.
* Improve test case …
> Add CloudFormation Lambda Version Provisioned Concurrency

- localstack-core/localstack/services/transcribe/provider.py
- localstack-core/localstack/testing/aws/asf_utils.py
The API currently marks everything as required, and optional args are configured as:
```python
arg: ArgType = None
```
which is obviously incorrect.
Implementations should be allowed to do this correctly:
```
arg: ArgType | None = None
```
But in order for that to work, we need to change the `test_asf_providers.py`. That test verifies that the signature is exactly the same. This PR makes the test assertions more flexible, so that an argument type of `X | None` is considered equal to `X`.
- Make the comparison function more flexible to ignore None-types in argument types
- Add some more specific error messages when the comparison fails
- Changes the argument types in the Transcribe provider to verify that new assertions work
Some manual testing was done to verify that the new assertions …
> ASF: Ignore optional-ness when comparing argument types

- localstack-core/localstack/testing/pytest/fixtures.py
While working on [snapshotted tests](https://github.com/localstack/localstack-ext/pull/4480), I wanted to have the possibility to pass to `ec2_create_security_group` an IP protocol for the ingress permissions.
I also noticed that this fixture [is also duplicated](https://github.com/localstack/localstack-ext/blob/f6f2977e2d316782b0ab4afa6458e8176af9a840/localstack-pro-core/tests/aws/services/elb/test_elb.py#L106-L145) in the ELB test (I removed it in the linked PR);
- Adding the `ip_protocol` to the fixture's factory function;
- Added docstrings;
> Improve security group fixture for EC2

- .github/workflows/aws-main.yml
This PR is part of initiative to migrate from CircleCI to GithubActions. This job combines coverage data, pushes them to coveralls, generates coverage diff and uploads it to artifacts
- Combine and upload coverage results 
- Push coverage results to coveralls
- Create coverage diff and upload to artifacts
- Tested this workflow with artifacts from another passed workflow here: https://github.com/k-a-il/localstack/actions/runs/14993589117
- Upload to coveralls from testing repository: https://coveralls.io/jobs/164913085
- Full run workflow with report job (in progress): https://github.com/k-a-il/localstack/actions/runs/14993888745
> Add Github Action job to publish test results to coveralls and uploading test results to artifacts

- tests/aws/services/dynamodb/test_dynamodb.py
- tests/aws/services/dynamodb/test_dynamodb.snapshot.json
- tests/aws/services/dynamodb/test_dynamodb.validation.json
Global tables in DynamoDB get a separate DynamoDB Stream, one for each regional replica of the table.
In LocalStack, we implement global tables by redirecting the DDB calls to the original region. A similar approach is not extended to the associated streams. Therefore, we don't have such streams associated with the regional replicas.
- Adding a (failing, therefore skipped) validated test that exposes the issue.
> DDB Global Tables: add failing test to expose the missing stream on replicas

- localstack-core/localstack/services/s3/presigned_url.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.validation.json
We've got a report in our Community Slack that we were not enforcing the `IfNoneMatch` parameter with pre-signed URLs. After a quick investigation, it showed that boto3 was disregarding those parameters during the signing process, leading to us ignoring them and not passing them down to our parser; thus them not being enforced. 
This issue shows that Boto3 is not even passing those to the query string parameters of the pre-signed URL: https://github.com/boto/boto3/issues/4367
- add a new field in the pre-signed URL code to manually pick those values from the query string to pass it back to the headers, for them to be enforced
- add a test directly using `botocore` because as reported in the boto GH issue, using botocore allows you to properly create a pre-signed URL with the …
> S3: fix IfMatch/IfNoneMatch in pre-signed URLs

- .github/workflows/aws-main.yml
- .github/workflows/aws-tests.yml
To not swarm the tinybird workspace with branch executions, we restrict the tinybird reporting to `master` only. 
I messed up by not re-activating it before merging in #12610 - sorry 😅 
- Re-add guard for sending data to tinybird only on master
> Restrict tinybird reporting to master branch only

- localstack-core/localstack/config.py
- localstack-core/localstack/services/kinesis/kinesis_mock_server.py
- localstack-core/localstack/services/kinesis/packages.py
- localstack-core/localstack/services/kinesis/plugins.py
- tests/aws/services/kinesis/test_kinesis.py
- tests/unit/cli/test_lpm.py
We've observed the `NodeJS` build of kinesis mock to encounter performance issues at higher volumes of requests -- namely with larger payload sizes.
This PR adds the original Scala build as an alternative engine for our Kinesis server behind the `KINESIS_MOCK_PROVIDER_ENGINE` flag.
- Relevant upstream issue: https://github.com/etspaceman/kinesis-mock/issues/1082
- Ext run with flag enabled: https://github.com/localstack/localstack-ext/actions/runs/14646658785
- Splits up the `KinesisMockServer` to include a `KinesisMockScalaServer` and `KinesisMockNodeServer`
- `KinesisMockPackage` can now either use the `KinesisMockScalaPackageInstaller` (downloads from GitHub) or `KinesisMockNodePackageInstaller` (downloads from NPM)
- Adds a `KINESIS_MOCK_PROVIDER_ENGINE` flag for switching to Scala …
>  [Kinesis] add Scala kinesis-mock build behind feature flag 

- .github/workflows/aws-main.yml
- .github/workflows/aws-tests-mamr.yml
- .github/workflows/aws-tests.yml
This PR introduces conditions to GitHub Actions steps and jobs to skip Docker login, Docker push, and pushing to Tinybird for forked repositories outside the LocalStack organization. This will allow contributors to run tests in forked repositories without needing to define secrets or modifying the testing workflows.
- Check that repository is `localstack/localstack` in docker and tinybird push steps, if not - skip these steps.
- Check that organization owner is `localstack` in docker pull steps, if not - skip these steps. Checking organization owner because we plan to re-use `aws-tests.yml` workflow in another LocalStack repository in the future.
- Tested on this branch ✅ 
- Tested in forked repo ✅  : https://github.com/k-a-il/localstack/actions/runs/15114565967/job/42483019964
> GithubActions: skip tinybird, docker push and docker login in forks

- localstack-core/localstack/services/events/provider.py
- tests/aws/services/events/test_events.py
- tests/aws/services/events/test_events.snapshot.json
- tests/aws/services/events/test_events.validation.json
I'm raising this PR to increase LocalStack's coverage of AWS APIs. Currently ListRuleNamesByTarget is not implemented.
It fixes issue #12631 .
This PR makes it so that instead of returning `NotImplementedError`, LocalStack will start returning the actual list of EventBus rules for a given target.
The changes are covered by snapshot/parity tests.
The happy path can also be tested manually by spinning up LocalStack and following these steps:
```bash
awslocal sqs create-queue --queue-name test-sqs-queue
QUEUE_ARN=$(awslocal sqs get-queue-attributes \
--queue-url http://sqs.eu-west-2.localhost.localstack.cloud:4566/000000000000/test-sqs-queue \
--attribute-names QueueArn \
--query 'Attributes.QueueArn' \
--output text)
awslocal events create-event-bus --name test-event-bus
awslocal events …
```
> Feature: implement list rule names by target

- .github/workflows/aws-main.yml
Acceptance tests executed on `master` are currently sent as `tests_full` to tinybird, which is wrong. The reason is a faulty name selection for the workflow push action which does not consider push events.
- Adapt the workflow push action to use the same logic as the call to the tests
> Fix acceptance test workflow name for Tinybird workflow push

- .github/workflows/aws-main.yml
- .github/workflows/aws-tests-mamr.yml
This is one of the final steps of moving towards the new GHA pipelines. It activates the new main pipeline to run against all PRs. 
After a week of stability, the old CircleCI pipelines will be disabled
- Add pull request trigger for main pipeline
- Remove the docs from the triggers
> Activate new GHA pipeline on PRs

- localstack-core/localstack/packages/ffmpeg.py
The current `ffmpeg` installer in LocalStack downloads binaries from [johnvansickle.com](https://johnvansickle.com/ffmpeg/), a privately hosted site that has exhibited timeout issues, likely due to bandwidth limitations or rate throttling.
To address this, we are switching to [BtbN/FFmpeg-Builds](https://github.com/BtbN/FFmpeg-Builds) — a well-maintained, GitHub-hosted source for `ffmpeg` binaries with:
- Actively maintained nightly and tagged releases
- LGPL-compliant builds suitable for LocalStack’s hybrid licensing model
- Uses the latest build of a specific major version and replaces `ffmpeg` download URL with BtbN-hosted static LGPL `7.1` builds. 
- Resolves architecture dynamically based on the host (e.g., linux64, linuxarm64)
- Updates the structure handling to match BtbN’s layout …
> ffmpeg: Update build source to use BtbN GitHub Releases

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_executor.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_visitor.py
- tests/aws/services/cloudformation/v2/ported_from_v1/resources/test_apigateway.py
- tests/aws/services/cloudformation/v2/test_change_set_depends_on.py
- tests/aws/services/cloudformation/v2/test_change_set_depends_on.snapshot.json
- tests/aws/services/cloudformation/v2/test_change_set_depends_on.validation.json
- tests/aws/services/cloudformation/v2/test_change_set_fn_get_attr.py
- tests/aws/services/cloudformation/v2/test_change_set_fn_join.py
- tests/aws/services/cloudformation/v2/test_change_set_mappings.py
- tests/aws/services/cloudformation/v2/test_change_set_parameters.py
- tests/aws/services/cloudformation/v2/test_change_set_ref.py
- tests/aws/services/cloudformation/v2/test_change_set_values.py
The introduction of the CloudFormation v2 engine laid the foundation for a redesigned engine capable of accurately determining update requirements between CloudFormation deployments, while also enabling parallel execution during updates. However, the current implementation still lacks support for [DependsOn blocks](https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html)
Future efforts should add validation checks and cyclic reference detections.
- Add support for DependsOn blocks (modeling,  describing, and executing)
- Add base ChangeSet lifecycle test
- Un-skip v1 test for apigateway
> CloudFormation V2 Engine: Support for DependsOn Blocks

- localstack-core/localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/test_lambda.py
- tests/aws/services/lambda_/test_lambda.snapshot.json
- tests/aws/services/lambda_/test_lambda.validation.json
This PR fixes a bug reported by a user. The issue was that when a Lambda function was created in Localstack using Terraform, the `reserved_concurrent_executions` value always reset to -1 in tfstate after apply.
While trying to reproduce the issue, I saw that the `reserved_concurrent_executions` value was saved correctly in the created lambda, but  `reserved_concurrent_executions` wasn’t returned in the [`AWSLambda::GetFunction` response.](https://docs.aws.amazon.com/lambda/latest/api/API_GetFunction.html) Because the response didn’t include the value, [Terraform set the value to default -1 ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#reserved_concurrent_executions-1) and saved that in the tfstate file.
Added code to return the function's …
> Include reserved_concurrent_executions in get_function response

- pyproject.toml
- requirements-basic.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
This PR bumps moto-ext to 5.1.4.post2
Contains:
- https://github.com/getmoto/moto/pull/8894
- https://github.com/getmoto/moto/pull/8879
- https://github.com/getmoto/moto/pull/8856
> Bump moto-ext to 5.1.4.post2

- localstack-core/localstack/services/ec2/provider.py
- tests/aws/services/ec2/test_ec2.py
- tests/aws/services/ec2/test_ec2.snapshot.json
- tests/aws/services/ec2/test_ec2.validation.json
Customer reported some issue trying to run a tf script where they were getting this error: `Error: no matching EC2 Availability Zone found`.
The reason for that is that this operation implementation in the ec2 provider.py filters doesn't work against moto, resulting into an empty list.
More context in the notion [ticket](https://www.notion.so/localstack/Oleg-Tyaglo-No-matching-EC2-Availability-Zone-found-1fcfc2a23431817abe14c63939ee03f7?d=173fc2a234318207919e83a394a8a046).
Change how filters are passed for the call done to moto.
Added aws validated tests.
`test_describe_availability_zones_filter_with_zone_names` fails against LS with the old code, and passes now.
> EC2: fix describe-availability-zones filtering

- .github/workflows/aws-main.yml
- .github/workflows/aws-tests.yml
Thanks to [this PR](https://github.com/localstack/localstack/pull/12683), it was discovered that the order of path filters for push and pull_request triggers was incorrect. As a result, the `aws-main.yml` workflow was not triggered when `aws-tests.yml` was updated in the PR.
- Fix path ordering not to trigger a workflow for all `.github` files except files in the `actions` folder, `aws_main.yml`, and `aws_tests.yml`
> GH Actions: fix order of path filters for push and pull-request events

- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
Currently, if an ESMs `MaximumBatchingWindowInSeconds` is `0` AND no records are collected, a shard iterator never moves forward. This PR ensures that we will always update a shard's iterator value given a successful `GetRecords` call.
Note, that any failures during processing should be handled by the internal retrier loop resulting in retrying the batch until successful or being discarded/sent to a DLQ. We should not be relying on the shard iterator value in order to keep track since these values are ephemeral and prone to expiry (i.e if a lambda processes for longer than 300s).
- Ensure we always update a shard iterator following a succesful `GetRecords` call.
> fix(esm/kinesis): Always store NextShardIterator from GetRecords

- pyproject.toml
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
This PR bumps moto-ext to 5.1.5.post1 in preparation for LocalStack 4.5.0.
Contains:
- https://github.com/getmoto/moto/pull/8917
- https://github.com/getmoto/moto/pull/8933 @dfangl
> Bump moto-ext to 5.1.5.post1

- localstack-core/localstack/cli/profiles.py
#12500 added top level handling of profiles before they get to the click parsing. However, this inadvertently also caught the help option parsing. This leads to a shortened help message on `-h` like this:
```
usage: localstack [-h] [--profile PROFILE]
options:
-h, --help         show this help message and exit
--profile PROFILE
```
By disabling help message parsing in the preceding argparse, we pass that flag to click again and receive our full help output.
- Disable help parsing in argparse so that it is handled by click again
> Stop handling help parsing with argparse

- localstack-core/localstack/cli/localstack.py
Following up from a [relevant discussion](https://localstack-cloud.slack.com/archives/C0550DW38CT/p1748416788025209), this is an attempt to add a CLI option for selecting a stack (image, emulator).
1. The command to start LocalStack for Snowflake is quite verbose by using the IMAGE_NAME environment variable. 
2. Selecting a different image version also required the IMAGE_NAME variable, see [relevant docs](https://docs.localstack.cloud/references/configuration/#core).
```sh
IMAGE_NAME=localstack/snowflake:latest localstack start
IMAGE_NAME=localstack/localstack-pro:4.1 localstack start
```
See also [relevant discussion](https://localstack-cloud.slack.com/archives/C06CV9US815/p1744792391948849) for more context.
This will add **--stack** and **-s** as a shorthand for selecting the image and …
> Add stack option for CLI start command

- localstack-core/localstack/services/sns/provider.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
- tests/aws/services/sns/test_sns.validation.json
We've got a report with #12670 that we didn't support cross-region subscribe calls. It seems it is not allowed by AWS, but we didn't have test coverage over it. 
This PR adds more AWS validated tests testing cross-region behavior for operations that would allow cross-account access, as well as a cross-region delivery scenario. 
- add tests around cross-region access in SNS
- add test for `DeleteTopic` idempotency
- fix behavior in provider, to raise proper error message in case of cross-region access
> SNS: validate cross-region behavior

- .github/workflows/aws-main.yml
Because docker image and lambda artifacts use a lot of Github storage space, we try to keep only the ones we actually need. I added a cleanup job a while ago, but it only runs if the `push` job succeeds. Since the `push` job was skipped, the `cleanup` job was skipped too. 
This PR changes when the cleanup runs — now it will delete docker-image and lambda artifacts every time, except if earlier workflow jobs failed or were cancelled (this will allow to rerun failed jobs without needing to rerun the whole pipeline to regenerate the docker image or lambda artifacts)
- Changed condition of `cleanup` job
> Change cleanup job condition in main pipeline in Github Actions

- localstack-core/localstack/utils/analytics/metrics.py
- tests/unit/utils/analytics/test_metrics.py
- After reviewing label usage over the past few months, we found that no existing metric uses more than 5 labels.
- Limiting counters to 6 labels help to avoid overly complex metrics that try to capture too many different aspects.
- Fewer labels simplify analytics query and makes dashboards easier to build/read.
- A limit of 6 is sufficiently high for current needs, but this threshold can be revisited in the future if necessary.
> refactor: reduce max number of allowed labels in counters from 8 to 6 [DAT-146]

- .github/workflows/aws-main.yml
- .github/workflows/aws-tests.yml
The GHA workflow only runs ARM tests on master and the dependency upgrade PRs, or when `input.forceARMTests` is set to true. However, we do not have that input. This PR adds that
- Add `forceARMTests` input to both the main pipeline as well as the test sub-pipeline
- Fix minor typo in Acceptance test job name
Test run with force ARM tests:
https://github.com/localstack/localstack/actions/runs/15441275724
> Add missing switch for forcing ARM tests on workflow dispatch

- .github/workflows/aws-tests.yml
While looking at a failed ARM workflow run, I've noticed that arm64 workflow summaries don't work. The reason is a wrong determination of the architecture that is to be reported.
For simplicity, the matrix for determining the architecture remained the same between workflow run and publishing. The error happened in choosing only AMD to actually run the publishing job. To determine the architecture that should be published, however, we checked the architecture of the runner - which would only be AMD. 
Because amd64 and arm64 look so similar we didn't spot this in the initial PR.
To fix this, we can simplify the matrix a bit and just iterate over the actual values `amd64` and `arm64`. 
- change matrix to iterate over `amd64` and `arm64` and use the matrix value directly for downloading and …
> Fix Workflow summaries for ARM workflows

- localstack-core/localstack/services/events/provider.py
- tests/aws/services/events/test_events_schedule.py
- tests/aws/services/events/test_events_schedule.validation.json
As reported in #12714, we would trigger scheduled rules when a call to `PutEvents` would be done (in this issue, the call would be internal from `SSM.PutParameter`. 
We need to skip triggering scheduled rules when processing entries. 
I validated that the user shared sample now works with this fix. 
- add a skip when processing rules
- add a test validating that AWS does not trigger the scheduled rules when calling `PutEvents`
> Events: fix PutEvents triggering Scheduled rules

- .github/workflows/aws-main.yml
The DockerHub user secrets were wrongly assumed to contain `PUSH` in them, compared to the `PULL` tokens. However, a look at the s3 image pipeline shows that this is not the case.
Also, the twine credentials are missing in the dev release publishing step.
- Adapt to use correct secret names
- Adapt to use twine username and password for dev release publish
> Fix publishing credentials

- localstack-core/localstack/services/transcribe/models.py
- localstack-core/localstack/services/transcribe/packages.py
- localstack-core/localstack/services/transcribe/plugins.py
- localstack-core/localstack/services/transcribe/provider.py
- localstack-core/localstack/testing/aws/asf_utils.py
- localstack-core/mypy.ini
Part of a broader push to enforce typing support everywhere (see #12532). One of the areas that I wanted to focus next on was adding correct types to the `BaseStore`/`AccountRegionBundle`/etc, because it is such a fundamental concept that all emulators would benefit from improved type support.
However, before improving types there, it makes sense to first ensure that the usage of `BaseStore` is typed and validated. Only then can we be improve the types in `BaseStore` and be sure they are correct.
Hence this PR: enforcing type checks in one of the smaller services, for the sole purpose of checking that `BaseStore` is used/typed correctly.
- Optional API arguments (`param: X | None = None`) were added in #12614 
- Proper types for `context.account_id`/`region_name` were set in #12617 
An …
> Transcribe: Enable MyPy

- localstack-core/localstack/services/firehose/provider.py
This PR adds small fixes for issues reported by @kostas-localstack internally.
1.- The operation allows the user to attempt to create a second DeliveryStream with a name already in use.
2.- The `DirectPut` is the default value for `DeliveryStreamType` when is not defined.
3.- When creating a DeliveryStream with Kinesis as destination and it fails. The resource is still created.
- Add assertion that the name is not in use before attempting to create a DeliveryStream.
- Add `DirectPut` as default value.
- Move the storage of the resource to the end of the operation.
> add small fixes/improvements to Firehose.CreateDeliveryStream

- localstack-core/localstack/config.py
- localstack-core/localstack/utils/container_utils/container_client.py
- localstack-core/localstack/utils/container_utils/docker_cmd_client.py
- localstack-core/localstack/utils/container_utils/docker_sdk_client.py
Some customers work in airgapped environments, and require customisation of the Docker image registries used. This PR enables a flexible method for adding customisation to the Docker image pulling strategy.
* Introduce the `RegistryResolverStrategy` protocol to support custom image resolving
* Add an implementation `HardCodedResolver` which is a no-op
* Use this resolver when pulling images, or creating containers
> Docker registry customisation

- localstack-core/localstack/services/s3/provider.py
- localstack-core/localstack/services/s3/storage/ephemeral.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/aws/services/s3/test_s3.validation.json
- tests/aws/services/s3/test_s3_api.snapshot.json
- tests/aws/services/s3/test_s3_api.validation.json
We've got a report in our Community Slack with a small sample (as represented by the new test) where Checksum handling did not work well with the `UploadPartCopy` operation: https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html
This was due because we simply did not handle checksums as this was not implemented in our previous implementation. 
We now properly handle checksums when copying an object into a part, via our storage engine. 
This was the error when calling `ListParts`: 
```python
An error occurred (InternalError) when calling the ListParts operation (reached max retries: 4): exception while calling s3.ListParts: 'NoneType' object has no attribute 'upper'
```
- add new test covering the case of multipart uploads with checksum and UploadPartCopy
- fix the …
> S3: fix Checksum handling in UploadPartCopy

- .github/dependabot.yml
- CODEOWNERS
It has been announced in a [blog post](https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/) and via automated comments that the `reviewers` config in Dependabot is deprecated and that users should switch to a `CODEOWNERS` config instead.
This PR performs this migration.
- Removes the deprecated `reviewers` section in the dependabot config.
- Explicitly sets me and @silv-io as reviewers for all Dockerfiles (i.e. the dependabot base image updates).
> migrate from depenadbot reviewers to codeowners

- .github/workflows/aws-tests.yml
- .github/workflows/update-test-durations.yml
While switching from CircleCI to GitHub Actions, I saw that the test durations file hadn’t been updated in about a year. Since then, we’ve added a lot of new tests. This pull request adds a workflow that downloads test durations from the latest scheduled run on the master branch, combines them, and creates a PR with the updated test durations file. New workflow is scheduled to run every month.
- Added a workflow to download and merge the test durations file, and create a pull request with the updates
Tested in a forked repostiory.
- PR created automatically: https://github.com/k-a-il/localstack/pull/5
- Merged test durations uploaded as [artifact](https://github.com/k-a-il/localstack/actions/runs/15628284152)
> Update test durations automatically based on latest durations from master

- tests/aws/services/lambda_/test_lambda_common.py
- tests/aws/services/lambda_/test_lambda_common.snapshot.json
- tests/aws/services/lambda_/test_lambda_common.validation.json
Ruby transparent endpoint injection tests fail due to a change in the `RUBYLIB` variable. The official AWS Docker images do not match what we observe in AWS Lambda.
* Ignore internal (not documented in Lambda [environment variables](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html)) `RUBYLIB` variable changed by AWS
> Fix failing Ruby tests due to internal RUBYLIB variable changed by AWS

- localstack-core/localstack/services/cloudwatch/provider_v2.py
This PR fixes an issue that occurs when the CW Provider is restared and the user tries to write some metrics into the service with the "clean" state. 
The cause of this issue is that the reset operation removes the directory `/tmp/localstack/state/cloudwatch` and the DB files inside it. After the reset operation, the provider doesn't start a new DB file. So any operation that comes after failes.
- Make sure that a Database is started after a reset operation
- the persistence feature is not available in this repository so a test cannot be added.
> fix issue with CloudWatch after state reset

- localstack-core/localstack/services/s3/models.py
- localstack-core/localstack/services/s3/provider.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/aws/services/s3/test_s3.validation.json
- tests/aws/services/s3/test_s3_list_operations.py
- tests/aws/services/s3/test_s3_list_operations.snapshot.json
- tests/aws/services/s3/test_s3_list_operations.validation.json
As reported by #12757, we dit not return the full `ObjectParts` response in S3. 
The behavior is different if the checksum specified when creating the Multipart Upload with `CreateMultipartUpload` is of type `COMPOSITE` or `FULL_OBJECT`. When it is `COMPOSITE`, any call to `GetObjectAttributes` with the `ObjectParts` attribute specified should act like a `ListParts` call. 
There was a TODO left about it, and this PR implements it. 
It needed a change in API as we were not saving the metadata related to the Parts used to create the end object (we only store the data necessary to support `PartNumber` in `GetObject`, via the `get_part_range` function). This minor change in API is properly covered defensively to avoid issues when using this functionality (`GetObject` with the `PartNumber` …
> S3: implement ObjectParts in GetObjectAttributes

- localstack-core/localstack/services/stepfunctions/backend/execution.py
- localstack-core/localstack/services/stepfunctions/provider.py
- localstack-core/localstack/testing/pytest/stepfunctions/utils.py
- tests/aws/services/stepfunctions/v2/mocking/test_base_scenarios.py
- tests/aws/services/stepfunctions/v2/mocking/test_base_scenarios.snapshot.json
- tests/aws/services/stepfunctions/v2/mocking/test_base_scenarios.validation.json
Extend the Step Functions mocking capability to support `StartSyncExecution`, enabling consistent testing across both Standard and Express state machines https://github.com/localstack/localstack/issues/12711
- Apply mock config (`LOCALSTACK_SFN_MOCK_CONFIG`) when starting a state machine via `StartSyncExecution`
- New parity test `tests/aws/services/stepfunctions/v2/mocking/test_base_scenarios.py::TestBaseScenarios::test_lambda_service_invoke` to verify that the mocked service integration mechanism also works when using `StartSyncExecution`
1. Create an express state machine
2. Create a mock config to mock the state machine response
3. Start localstack with the mock configuration
4. Start the state machine synchronously with `start-execution`
5. Verify that the execution response is the …
> Step Functions: Mock feature for StartSyncExecution

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_executor.py
- localstack-core/localstack/services/cloudformation/v2/entities.py
- localstack-core/localstack/services/cloudformation/v2/provider.py
- localstack-core/localstack/testing/pytest/cloudformation/fixtures.py
- tests/aws/services/cloudformation/v2/test_change_sets.py
- tests/aws/services/cloudformation/v2/test_change_sets.snapshot.json
- tests/aws/services/cloudformation/v2/test_change_sets.validation.json
This PR enables the new CloudFormation engine to emit and store stack resource events, aligning its behavior more closely with AWS for parity testing and improving visibility into stack changes.
- The new engine now emits CloudFormation resource-level events.
- These events are stored and exposed via describe_stack_events.
- Updated the logic to include intermediate states (e.g., *_IN_PROGRESS) and filter out unsupported ones (e.g., DELETE_*) for now.
- Unskipped snapshot tests that were previously skipped due to missing event support.
- Normalized event output to avoid duplicates in test comparisons. 
- Verified event ordering by timestamp to ensure consistent results across runs.
> add resource events to CFn v2

- localstack-core/localstack/utils/bootstrap.py
Fixes a small typo when warning a user about non-prefixed envars being forwarded to LocalStack container.
- Changes `... to be forwarded form ...` => `... to be forwarded from ...`
> chore(utils): Fix typo when forwarding envars to container

- localstack-core/localstack/services/iam/provider.py
- pyproject.toml
- requirements-basic.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
- tests/aws/services/cloudformation/api/test_nested_stacks.py
- tests/aws/services/cloudformation/resource_providers/iam/aws_iam_user/test_parity.py
- tests/aws/services/iam/test_iam.py
- tests/aws/services/iam/test_iam.snapshot.json
- tests/aws/services/iam/test_iam.validation.json
- tests/aws/services/sts/test_sts.py
This PR bumps moto-ext to 5.1.6.post2
Contains:
- https://github.com/getmoto/moto/pull/8960
Moto response serialiser is being reworked upstream where now the tags field in IAM resources is always returned. AWS does not return this field if no tags are set. This is causing snapshot tests to fail, because of which this PR marks the tags attribute to be skipped. This is expected to be resolved in future Moto releases. See https://github.com/getmoto/moto/pull/8997.
> Bump moto-ext to 5.1.6.post2

- localstack-core/localstack/services/s3/provider.py
- tests/aws/services/s3/test_s3_api.py
- tests/aws/services/s3/test_s3_api.snapshot.json
- tests/aws/services/s3/test_s3_api.validation.json
We got a report with #12783 that we did not support `IfMatch` header for `DeleteObject`. This is because this is only supported for Directory Bucket (S3 Express One Zone), which we don't support yet (requested at #12184). 
In the reported issue, the bucket was not created as a Directory Bucket, which would raise an exception in S3 when trying to use preconditions headers for `DeleteObject`. 
This PR adds that parity + a log message to indicate that directory buckets are not yet supported by LocalStack, to avoid users not understanding why such feature would just fail silently. 
- add test for DeleteObject preconditions when the bucket is not a directory bucket
- add the same validation in the provider
It seems AWS is adding more feature again only to Directory Buckets, as seen by #12785 …
> S3: add error for DeleteObject preconditions for regular buckets

- localstack-core/localstack/services/s3/provider.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/aws/services/s3/test_s3.validation.json
- tests/aws/services/s3/test_s3_api.py
- tests/aws/services/s3/test_s3_api.snapshot.json
- tests/aws/services/s3/test_s3_api.validation.json
We got a report from a user that setting the Object Lock Mode to `COMPLIANCE` did not work. This ended up being a user misunderstanding about the behavior of Versioned buckets adding delete markers on top of versions, same as this post: https://repost.aws/questions/QUyamFMI7QQy2zmIkF_0IxwQ/s3-object-lock-in-compliance-mode-file-uploaded-thru-cli-file-properties-shows-compliance-mode-i-can-still-delete-it
However, while looking at the issue, I realized we didn't consider the `COMPLIANCE` value when trying to reduce or remove the effective locking on the object via `PutObjectRetention`, which this PR fixes.
I've also added validation around the `Mode` value
I've also added validation for the Lock Mode in operation where it is possible to pass it, like `PutObject` and …
> S3: add validation around Retention Mode & consider COMPLIANCE when updating

- localstack-core/localstack/aws/api/apigateway/__init__.py
- localstack-core/localstack/services/apigateway/legacy/provider.py
- tests/aws/services/apigateway/test_apigateway_api.py
- tests/aws/services/apigateway/test_apigateway_api.snapshot.json
- tests/aws/services/apigateway/test_apigateway_api.validation.json
Add negative test coverage for the `IntegrationResponse` operation in API Gateway v1, to ensure LocalStack properly mimics AWS behavior when invalid inputs are provided. This improves parity and robustness of the emulated service.
- Added **negative test coverage** for `PutIntegrationResponse` and `GetIntegrationResponse` operations:
- `test_integration_response_wrong_api`
- `test_integration_response_wrong_resource`
- `test_integration_response_wrong_method`
- `test_integration_response_wrong_invalid_statuscode`
- `test_integration_response_invalid_responsetemplates` (skipped for now due to LocalStack/AWS parity gap)
- `test_integration_response_invalid_integration`
- `test_integration_response_wrong_status_code`
- Updated `put_integration_response` and `get_integration_response` in …
> APIGW: add negative tests for IntegrationResponse and improve error handling in PutIntegrationResponse and GetIntegrationResponse

- localstack-core/localstack/services/sqs/provider.py
- tests/aws/services/sqs/test_sqs.py
- tests/aws/services/sqs/test_sqs.snapshot.json
- tests/aws/services/sqs/test_sqs.validation.json
While reading about SQS and X-Ray, I had a hunch we didn't implement the automatic passing of X-Ray headers to the Attributes. 
See https://docs.aws.amazon.com/xray/latest/devguide/xray-services-sqs.html
It might have been the case in the past, due to this following function:
https://github.com/localstack/localstack/blob/5b0180cbf277936f83334c7a61e1f63f18e9c01e/localstack-core/localstack/utils/aws/aws_responses.py#L189-L196
But this was lacking now.
I've added a test to verify the behavior in AWS. 
- add automatic propagation from incoming request headers to `AWSTraceHeader` Attribute
> SQS: add automatic propagation of AWSTraceHeader attribute when sending message

- localstack-core/localstack/services/sts/models.py
- localstack-core/localstack/services/sts/provider.py
This PR contains no behavioral changes, just some refactoring of the STS session storage.
Instead of storing tags exclusively, I adapted naming and added additional properties to the session storage.
This will allow us to store more information per session, which is needed for advanced IAM functionality downstream.
* Rename SessionTagConfig to SessionConfig to reflect storage of other attributes of a session
* Some renames in local variables
* Add `iam_context` field to allow storage of iam context variables
> Update STS session storage model to be more flexible

- localstack-core/localstack/extensions/api/aws.py
- localstack-core/localstack/extensions/api/extension.py
With #9194, we introduced the concept of Finalizers. 
Those are not yet available in Extensions.
This PR adds that 😄 
note: naming can be updated, but all the methods ending with `_handlers` were accessing a `Composite*Handler`, but the finalizers are defined as `CompositeFinalizer` with no handler in the name, so I followed the same convention. 
- update the signature of the Extension base class
> Update Extension API

- localstack-core/localstack/services/s3/cors.py
- tests/aws/services/s3/test_s3_cors.py
As reported by #12854, we had an issue in S3 with GZIP handling when disabling S3 CORS. 
This is because the GZIP handler depends on the service name being set in the context. However, we were only attaching the S3 service name if S3 CORS was not disabled.
This is a consequence of the ServiceNameParser being moved further down the chain with #11800
As a quick fix and bandaid, I've moved the logic around to *always* try to determine if it's an S3 request, even if S3 CORS is disabled.
However, we're muddling a bit the responsibility of the "CORS" handler with a mini service name parser. I'd suggest to get this first PR as a quick fix for the issue, because the first part will always need to be executed anyway.
As a follow-up, we could either split this in 2 handlers: one "S3 Detection" and …
> S3: fix CORS handler + GZIP handling

- .github/workflows/aws-main.yml
- .github/workflows/aws-tests-mamr.yml
- .github/workflows/aws-tests.yml
We use an empty commit + a version tag to mark the release of new versions in PyPI and DockerHub. The empty commit triggered the run in CircleCI
Since switching to GitHub Actions for our CI, the empty commit does not do that anymore because of the path specifiers. However, we can use tag pushes instead to trigger the CI + push jobs.
[In a separate repo](https://github.com/silv-io/gha-trigger-testing/actions/runs/16269110767/job/45931870915), I've checked how this would behave:
Having both `tags` and `paths` patterns in a workflow does not interfere with each other. That means that pushed tags will trigger the CI regardless of which files were changed in the commit that the tag points to. 
Furthermore, a tag push event still has the same name of `push` in `github.event_name`, so we don't …
> Add tag push trigger to main workflow

- tests/aws/scenario/note_taking/test_note_taking.py
- tests/aws/scenario/note_taking/test_note_taking.snapshot.json
- tests/aws/scenario/note_taking/test_note_taking.validation.json
- tests/aws/services/cloudformation/api/test_transformers.snapshot.json
- tests/aws/services/cloudformation/api/test_transformers.validation.json
- tests/aws/services/cloudformation/resources/test_apigateway.py
- tests/aws/services/cloudformation/resources/test_apigateway.snapshot.json
- tests/aws/services/cloudformation/resources/test_apigateway.validation.json
- tests/aws/services/cloudformation/resources/test_sam.snapshot.json
- tests/aws/services/cloudformation/resources/test_sam.validation.json
- tests/aws/services/cloudformation/v2/ported_from_v1/api/test_transformers.snapshot.json
- tests/aws/services/cloudformation/v2/ported_from_v1/api/test_transformers.validation.json
- tests/aws/services/cloudformation/v2/ported_from_v1/resources/test_apigateway.py
- tests/aws/services/cloudformation/v2/ported_from_v1/resources/test_apigateway.snapshot.json
- tests/aws/services/cloudformation/v2/ported_from_v1/resources/test_apigateway.validation.json
- tests/aws/services/cloudformation/v2/ported_from_v1/resources/test_sam.snapshot.json
- tests/aws/services/cloudformation/v2/ported_from_v1/resources/test_sam.validation.json
Follow up from #12826, we took extra care with @ArthurAkh to make sure we would not break upstream pipelines, but the test selection did not trigger on CloudFormation and Scenario tests, making us miss some outdated snapshots (https://github.com/localstack/localstack/runs/46031151305)
This PR regenerated those outdated snapshots
- regenerate CFN / Scenario tests related to APIGW
- update snapshot skip related to DynamoDB
> APIGW: update CFN related snapshots

- localstack-core/localstack/services/kms/provider.py
- tests/aws/services/kms/test_kms.py
- tests/aws/services/kms/test_kms.snapshot.json
- tests/aws/services/kms/test_kms.validation.json
User reported a issue https://github.com/localstack/localstack/issues/12530 that causes a attribute error in Localstack. The error doesn't guide or provide clue to user on the problem. User is trying to decrypt the ciphertext blob by providing KeyId using Lambda function.
This PR fixes how LocalStack handles corrupted blobs during decryption when KeyId is provided by user. The fix ensures LocalStack's response matches AWS behavior.
Localstack will mimic AWS behavior i.e. it will generate same response that AWS would generate. It will help user to validate the blob text that need to be decrypted using Localstack.
Add a snaphshot test case in existing test method test_encrypt_decrypt_encryption_context() because AWS response is same. Newl response from AWS is added to …
> KMS #12530: Error handling for invalid blob  issue

- localstack-core/localstack/services/dynamodb/packages.py
- tests/aws/services/dynamodb/test_dynamodb.py
Last Friday, we had to skip a LocalStack only test (see https://github.com/localstack/localstack/pull/12874) that suddenly started to fail.
We realized that the last version of DynamoDB local (see [announcement](https://aws.amazon.com/about-aws/whats-new/2025/07/amazon-dynamodb-major-version-release-version-3-0-0/)) now migrated to the SDK for Java 2.x.
Therefore, our custom transformation done in [here](https://github.com/localstack/localstack-artifacts/blob/21999d534d78ff740e8bcf1c4eab98b628f5187a/dynamodb-local-patch/src/main/java/cloud/localstack/ClassRewriter.java#L15) was not applicable anymore.
(see https://github.com/localstack/localstack-artifacts/pull/44 for more context)
- This test re-enables the skipped test.
- All the fix is actually done in [this …
> DynamoDB: Bump DDB Local to v3

- localstack-core/localstack/services/stepfunctions/asl/jsonata/jsonata.py
- tests/aws/services/stepfunctions/templates/evaluatejsonata/evaluate_jsonata_templates.py
- tests/aws/services/stepfunctions/templates/evaluatejsonata/statemachines/base_pass.json5
- tests/aws/services/stepfunctions/v2/evaluate_jsonata/test_base_evaluate_expressions.py
- tests/aws/services/stepfunctions/v2/evaluate_jsonata/test_base_evaluate_expressions.snapshot.json
- tests/aws/services/stepfunctions/v2/evaluate_jsonata/test_base_evaluate_expressions.validation.json
Currently, the SFN v2 interpreter’s logic for extracting variable references from JSONata expressions can misinterpret dollar signs inside quoted strings or regex literals as variable markers. That leads to spurious validation errors at runtime reporting illegal uses of “$” even when they occur only within "/…/" or "…", ’…’ literals.
- Updates the variable-reference regex to first consume any JSONata regex literals (`/…/`) and string literals (`"…"` or `'…'`), including support for escaped slashes and escaped quotes
- Retains the original rules for matching `$$`, `$identifier(.prop…)*` and lone `$`, but only after skipping over consumed literals
- Ensures that only actual variable references are returned by findall
- Add related positive and negative snapshot tests
> Step Functions: variable-reference parsing to skip string and regex literals

- localstack-core/localstack/services/ec2/resource_providers/aws_ec2_vpcgatewayattachment.py
- tests/aws/services/cloudformation/resources/test_ec2.py
- tests/aws/services/cloudformation/resources/test_ec2.snapshot.json
- tests/aws/services/cloudformation/resources/test_ec2.validation.json
- tests/aws/templates/vpc_gateway_attachment.yml
We don't currently set the physical resource id when creating a VPC gateway attachment. This means the new CFn provider fails to deploy the resource.
* Correctly set the physical resource id for either the vpn gateway id  or internet gateway id, whichever is provided
* Validate that the physical resource id is set
> CFn: correctly set physical resource id for VpnGatewayAttachment

- localstack-core/localstack/services/cloudformation/v2/provider.py
- tests/aws/services/cloudformation/v2/ported_from_v1/api/test_changesets.py
When creating a stack with transforms, the `CAPABILITY_AUTO_EXPAND` capability is required. This is not currently validated with the new engine
* Validate auto expand capability on create and update stacks
> CFNv2: support validation of CAPABILITY_AUTO_EXPAND

- localstack-core/localstack/services/cloudformation/v2/entities.py
- localstack-core/localstack/services/cloudformation/v2/provider.py
- tests/aws/services/cloudformation/v2/ported_from_v1/api/test_stacks.py
- tests/aws/services/cloudformation/v2/ported_from_v1/api/test_update_stack.py
- tests/aws/services/cloudformation/v2/ported_from_v1/test_template_engine.py
The new provider does not support the `GetTemplate` operation. This PR implements an initial version.
* Store a copy of the original (parsed but not transformed) template on the stack
* Implement the provider method basically copying the v1 implementation
* Unskip 3 tests
> CFNv2: Implement get_template

- localstack-core/localstack/runtime/analytics.py
Tracking the `ACTIVATE_PRO` will enable us to identify sessions that use the pro image with an invalid token and fall back to the community image.
**Context:**
Some users set an invalid token using the pro image and set the `ACTIVATE_PRO=0` variable.
Without this, it appears that someone started a session with an invalid token using the pro image, which is misleading, as they would fall back to the community in this situation.
Adds `ACTIVATE_PRO` to the list of tracked environment variables that are sent to the analytics backend, so that it's ingested into TinyBird.
> feat: add the pro activation to the tracked environment variables

- localstack-core/localstack/packages/core.py
- localstack-core/localstack/packages/java.py
Ensure requests done with the GitHub Installer can resolve when an HTTP Proxy is used and configured via OUTBOUND_HTTP_PROXY / OUTBOUND_HTTPS_PROXY
Identified and tested with LocalStack pro by trying to install the EKS module via LPM.
Added 2nd / similar change (setting proxy on outbound request)  - the impact in java.py appears more limited/non-breaking and impacts a check to help identify latest/specific jdk version to use.
Confirmed and validated 2nd change via LPM module install of non-default java version
> bug fix: add missing proxies to the http request for the GitHub Installer

- localstack-core/localstack/services/kms/provider.py
- tests/aws/services/kms/test_kms.py
- tests/aws/services/kms/test_kms.snapshot.json
- tests/aws/services/kms/test_kms.validation.json
This PR adds support for the wrapping algorithm `RSA_AES_KEY_WRAP_SHA_256` in the `ImportKeyMaterial`, which raises:
`KMSInvalidStateException: An error occurred (KMSInvalidStateException) when calling the ImportKeyMaterial operation: Unsupported padding, requested wrapping algorithm:'RSA_AES_KEY_WRAP_SHA_256'`
This algorithm is defined by AWS as a hybrid encryption scheme, that combines encrypting the key material with an AES symmetric key that is generated, and encrypting the AES symmetric key with the public wrapping key and the `RSAES_OAEP_SHA_256` wrapping algorithm.
- Added support for `RSA_AES_KEY_WRAP_SHA_256` in the `import_key_material` method.
- Refactored decryption of wrapped key material into a new, centralized helper: `_decrypt_wrapped_key_material(...) ` now handles both …
> KMS: Add support for `RSA_AES_KEY_WRAP_SHA_256` in import key material

- localstack-core/localstack/services/kms/provider.py
- tests/aws/services/kms/test_kms.py
After the launch of [this feature](https://aws.amazon.com/blogs/security/how-to-use-on-demand-rotation-for-aws-kms-imported-keys/), AWS introduced support for on demand rotation of imported keys i.e. keys with `Origin` set to `EXTERNAL`. 
At the moment, LocalStack does not support this feature and we return a `400` error with `UnsupportedOperationException` even though the request itself is valid.
Raise appropriate error response with error code `501` when rotation of keys is done with imported keys. 
Please note, this PR does not aim to fix existing tests and other logic in the code which revolves around assuming that external keys are unsupported, this should be tackled in a separate PR.
> KMS: return `NotImplementedError` for rotation of imported keys

- .github/workflows/aws-main.yml
With #12923 we fixed the coverage upload, and with #12924 we tried to fix the issue of reporting partial results.
Unfortunately, debugging job level conditionals in GitHub actions is notoriously hard / [there isn't really a way to get proper debug information](https://github.com/orgs/community/discussions/20640) on how the conditions are evaluated.
- Fixes the conditional for uploading the coverage report by switching to "not explicitly true" for the test selection and aceptancfe tests and considering the push event.
- Fixes a conditional to forward the `enableTestSelection` correctly on the workflow call.
> fix partial coverage reporting

- .github/workflows/asf-updates.yml
- Makefile
A few days ago, `pip-tools==7.5.0` [has been released](https://github.com/jazzband/pip-tools/releases/tag/v7.5.0).
With our [weekly ASF update action](https://github.com/localstack/localstack/actions/runs/16714602516/job/47305613559), we are now facing an issue which was introduced by this version: https://github.com/jazzband/pip-tools/issues/2215
Immediately on the first call of `pip-compile` in this workflow the execution fails with the following trace:
```
File "/home/runner/work/localstack/localstack/.venv/bin/pip-compile", line 7, in <module>
sys.exit(cli())
^^^^^
File "/home/runner/work/localstack/localstack/.venv/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> mitigate issues with pip-tools 7.5.0 with dependency limit

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_transform.py
- localstack-core/localstack/services/cloudformation/v2/provider.py
- localstack-core/localstack/testing/pytest/cloudformation/fixtures.py
- tests/aws/services/cloudformation/api/test_transformers.py
- tests/aws/services/cloudformation/test_change_set_fn_transform.py
- tests/aws/services/cloudformation/test_change_set_fn_transform.snapshot.json
- tests/aws/services/cloudformation/test_change_set_fn_transform.validation.json
- tests/aws/services/cloudformation/test_template_engine.py
- tests/aws/templates/macros/add_standard_tags.py
This PR adds a collection of tests to validate the behavior of intrinsic transformation in a template. The tests are due to be unskipped when the feature is implemented in another PR.
-  New AWS validated tests to confirm that the function works with change sets.
> add testing for Fn::Transform in CFn v2

- localstack-core/localstack/services/lambda_/resource_providers/aws_lambda_url.py
- localstack-core/localstack/services/lambda_/urlrouter.py
- tests/aws/services/lambda_/functions/lambda_response_streaming.js
- tests/aws/services/lambda_/test_lambda.py
- tests/aws/services/lambda_/test_lambda.snapshot.json
- tests/aws/services/lambda_/test_lambda.validation.json
This Pr implements the capability to handle LambdaURL invocations of type StreamResponse [See here for more info](https://docs.aws.amazon.com/lambda/latest/dg/configuration-response-streaming.html)
- AWS::Lambda::Url  accepts the InvokeMode parameter to create a LambdaUrl
- UrlRouter can handle results with streaming separator
- UrlRouter can handle results with simple strings
- New AWS validated test
> support ResponseStream mode for functionUrl

- localstack-core/localstack/testing/pytest/fixtures.py
- tests/aws/services/events/conftest.py
- tests/aws/services/events/test_archive_and_replay.py
- tests/aws/services/events/test_events.py
- tests/aws/services/events/test_events_inputs.py
- tests/aws/services/events/test_events_patterns.py
- tests/aws/services/events/test_events_schedule.py
- tests/aws/services/events/test_events_targets.py
This PR moves several fixtures from eventbridge conftest to the globally defined fixtures to make them available in pro.
- move `create_role_event_bus_source_to_bus_target`
- move `get_primary_secondary_client`
- allow for custom aws client for `sqs_as_events_target` required if sqs is in separate region / account
- return queue_name for `sqs_as_events_target`
> Eventstudio: Move fixtures to make them available in Pro

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- localstack-core/localstack/services/cloudformation/engine/v2/resolving.py
- tests/aws/services/cloudformation/test_template_engine.py
The V2 engine does not currently support resolving dynamic parameter values, e.g.
```
{{resolve:secretsmanager:secret-id:secret-string:json-key:version-stage:version-id}}
```
* Duplicate the existing resolving functionality into its own module
* Replace/resolve dynamic references when visiting node properties in the preprocessor
* Unskip ssm and secretsmanager resolving tests in template engine tests
> CFNv2: support resolve:ssm: and resolve:secretsmanager: strings

- localstack-core/localstack/services/kms/models.py
- tests/aws/services/kms/test_kms.py
- tests/aws/services/kms/test_kms.snapshot.json
- tests/aws/services/kms/test_kms.validation.json
Fix key import for all HMAC key specs `HMAC_224`, `HMAC_256`, `HMAC_384`, `HMAC_512`. Previously, importing `EXTERNAL` origin HMAC keys failed with the following error: 
`An error occurred (InternalError) when calling the ImportKeyMaterial operation (reached max retries: 2): exception while calling kms.ImportKeyMaterial: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [<OpenSSLError(code=109052072, lib=13, reason=168, reason_text=wrong tag)>, <OpenSSLError(code=109576458, lib=13, reason=524554, reason_text=nested asn1 error)>])`
The key material gets loaded correctly and accepts raw key material for all HMAC specs and not just …
> KMS: fix HMAC key import and add validated tests for HMAC and ECC key specs

- localstack-core/localstack/utils/archives.py
Python wheels are considered valid `.zip` archives and can be extracted using the same functionality. This change allows us to extend the `ArchiveDownloadAndExtractInstaller` to download and unzip python wheels.
- Python `.whl` files are unzipped when doing a `download_and_extract` whereas previously an exception was raised.
> add(utils/archives): Support .whl files in download_and_extract

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_executor.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_validator.py
- localstack-core/localstack/services/cloudformation/resource_provider.py
- localstack-core/localstack/services/cloudformation/v2/provider.py
- tests/aws/services/cloudformation/api/test_stacks.py
- tests/aws/services/cloudformation/engine/test_mappings.py
- tests/aws/services/cloudformation/engine/test_mappings.snapshot.json
- tests/aws/services/cloudformation/engine/test_mappings.validation.json
- tests/aws/services/cloudformation/engine/test_references.py
- tests/aws/services/cloudformation/test_template_engine.py
At time of writing, the CFNV2:Validation errors were the biggest class of errors in the new provider's test suite. This PR attempts to tackle (or at least reassign them) to make the biggest push towards parity.
Since we have made the validator a subclass of the preprocessor, we can now raise `ValidationError`s in the preprocessor which will be turned into proper service exceptions. This is the natural place to put this functionality, but it now can be driven during `CreateChangeSet|CreateStack|UpdateStack` i.e. synchronously 
* Hide most logged exceptions from the logs unless `CFN_VERBOSE_ERRORS=1`
* Move the validation of the logical resource ids to the preprocessor
* Improve parity of error messages with looking up missing keys from mappings
* The validator now inherits from the …
> CFNV2: remove/rescope CFNV2:Validation errors

- localstack-core/localstack/services/cloudformation/v2/provider.py
- tests/aws/services/cloudformation/api/test_changesets.py
We still have one outstanding parity test for `delete_change_set`. This PR fixes that.
We don't need to have special handling for finding the change set in the provider since `find_change_set_v2` handles this case for us.
> CFNV2: fix delete change set

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
I merged a PR (#12980) without rebasing on top of #12955, and so introduced an error that was not caught in each individual PR. My PR added stricter validations of types when looking up values in maps, and the test involved looking up values in maps. The return type for the lookup was an array which was not included in my allowlist of valid types. As such a `ValidationError` is thrown when it should not be.
Fix the test to include `NodeArray` and `NodeObject` types as well as `TerminalValue`. Note: the secondary level key is visited, so if it is itself a nested intrinsic function (if that's even possible in CFn) then the value is subsequently resolved.
> CFNV2: fix select in mapping test

- localstack-core/localstack/aws/connect.py
- localstack-core/localstack/aws/skeleton.py
- localstack-core/localstack/services/cloudformation/deployment_utils.py
- localstack-core/localstack/services/cloudformation/provider_utils.py
- pyproject.toml
- tests/integration/services/test_internal.py
- tests/unit/aws/test_skeleton.py
- tests/unit/services/cloudformation/test_deployment_utils.py
Following up on our efforts for a better linting (e.g., #12953 and [#5018](https://github.com/localstack/localstack-pro/pull/5018)), this PR re-enables the rule E721 and adjusts the code to be compliant.
> Re-enabling ruff rule E721

- .github/workflows/aws-tests.yml
With https://github.com/localstack/localstack/pull/12995 Dependabot proposed updating the `download-artifacts` action.
Unfortunately, the release notes were not fully correct (see https://github.com/actions/download-artifact/issues/419), and the dependabot integration has limited permissions which is why I ignored the errors on the reporting step (which is exactly the step that broke due to the change).
This PR fixes this issue by broadening the file pattern for the picking up the unit tests (such that it fits both formats).
- Fix picking up the unit test results after upgrading `actions/download-artifact`
> fix unit test reporting

- .github/workflows/aws-tests-s3-image.yml
We are currently seeing issues in the s3 pipeline after #12995 updated the checkout action, which requires node24. Example run: https://github.com/localstack/localstack/actions/runs/16937609832/job/47997914093?pr=13003
This node version is not available in the buildjet runners, failing the pipeline.
* Use github actions runner instead of buildjet for s3 image pipeline
* Correct pipeline trigger paths for s3 image pipeline, to trigger if the workflow file is edited. This is likely why this issue failed to be discovered in #12995
> Remove buildjet from s3 image arm pipeline

- localstack-core/localstack/services/lambda_/invocation/version_manager.py
The current Lambda version manager invocation logic for LDM does not handle cases correctly when an LDM configuration is removed during invocation. These changes improve the process to ensure such scenarios are handled more gracefully.
- Handle canceled errors during LDM invokes
> Improve handling of LDM shutdowns during invocations

- localstack-core/localstack/utils/net.py
- tests/unit/utils/test_net_utils.py
This PR aims to fix `PortRange.subrange` to return an instance of a subclass instead of harcoding `PortRange`.
While working on Elasticache and MemoryDb in container, I realised it was not possible to create more than 1 Redis/Valkey container at once. This was due to `PortRange` not validating that the port is available on the host. Using `_DockerPortRange` would fix the issue, however the `subrange` method would return an instance of `PortRange` instead of `_DockerPortRange`.
- use `self.__class__` to retrieve the instance's class
- Add simple unit test
> fix port subrange from subclass

- localstack-core/localstack/aws/handlers/internal_requests.py
- localstack-core/localstack/aws/spec.py
- localstack-core/localstack/services/apigateway/legacy/invocations.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/method_request.py
- localstack-core/localstack/services/cloudformation/engine/template_deployer.py
- localstack-core/localstack/services/cloudformation/provider.py
- localstack-core/localstack/services/cloudwatch/alarm_scheduler.py
- localstack-core/localstack/services/dynamodb/server.py
- localstack-core/localstack/services/firehose/provider.py
- localstack-core/localstack/services/lambda_/invocation/lambda_service.py
- localstack-core/localstack/services/lambda_/provider.py
- localstack-core/localstack/services/opensearch/provider.py
- localstack-core/localstack/services/plugins.py
- localstack-core/localstack/services/s3/notifications.py
- localstack-core/localstack/services/s3/website_hosting.py
- localstack-core/localstack/services/ses/provider.py
- localstack-core/localstack/services/sns/executor.py
- localstack-core/localstack/services/sns/publisher.py
- localstack-core/localstack/services/sqs/provider.py
- localstack-core/localstack/services/sqs/query_api.py
- localstack-core/localstack/services/stepfunctions/backend/execution.py
- localstack-core/localstack/services/transcribe/provider.py
- localstack-core/localstack/utils/analytics/metadata.py
- localstack-core/localstack/utils/http.py
- localstack-core/localstack/utils/net.py
As a part of the initiative for improving Localstack error messages and stack traces, this PR aims to ensure that stack traces are logged when debug mode is enabled. Currently, in some use cases stack traces are logged without checking if debug mode is enabled or not. This causes excessive log noise even when `DEBUG=0`. 
This PR cleans up logging across different use cases to ensure that stack traces are only logged when debug mode is enabled.
> Log stack traces only in debug mode

- pyproject.toml
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
With the addition of jpype1 last year, we had the issue that jpype would not pass control back to the python process on SIGTERM, but only on SIGINT.
This lead to issues with shutdown, which we fixed in our fork `jpype1-ext`. However, we have since contributed this fix upstream, and jpype1 1.6.0 should have this fix in by default, which was released recently.
With the effort to use python 3.13 as well, this provides a good opportunity to switch back, as `jpype1` provides wheels for python3.13, while `jpype1-ext` currently does not (it would be fairly easy to add, but unnecessary as we want to deprecate the fork anyway).
* Move from `jpype1-ext` to `jpype`
* General dependency updates that came in with `make upgrade-pinned-dependencies`
> Migrate from jpype1-ext to jpype1

- localstack-core/localstack/services/sns/provider.py
- localstack-core/localstack/services/sns/publisher.py
- localstack-core/localstack/services/sqs/models.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
- tests/aws/services/sns/test_sns.validation.json
- tests/aws/services/sqs/test_sqs.py
- tests/aws/services/sqs/test_sqs.snapshot.json
- tests/aws/services/sqs/test_sqs.validation.json
Related to #13008 -> https://aws.amazon.com/about-aws/whats-new/2025/07/amazon-sns-standard-topics-sqs-fair-queues/
Since adding support for SQS Fair Queues, we can now pass a `MessageGroupId` to non-FIFO topic.
This PR implements that behavior in SNS, removing the previously raised exception, and properly passing the attribute. 
This also fixes the behavior in SQS itself following #12930, because we were not adding the `MessageGroupId` to the `Attributes` of the received Message, as this only done for FIFO queue. I've updated the SQS test to verify this
- remove raising an exception for non-FIFO topics
- remove the check for FIFO topic before passing the attribute as kwarg to `SQS.SendMessage`
- fix the behavior in SQS to return the `MessageGroupId` as `Attributes` of the message
- …
> SNS: support passing `MessageGroupId` to non-FIFO topic

- localstack-core/localstack/aws/protocol/parser.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.validation.json
- tests/unit/aws/protocol/test_parser.py
We got a report with #12999 that sending a `GetObjectAttributes` request would fail depending on the order of the fields being passed.
While debugging and printing out low level HTTP request on the Java side, I realized that Java was sending the request with multiple headers for the same key, like some others SDK (Go in particular)
```
GET /test-key?attributes= HTTP/1.1
[...]
Amz-Sdk-Invocation-Id: 5cb65548-6947-4436-b731-ee6d618bc91c
Amz-Sdk-Request: attempt=1; max=3
Authorization: ---
X-Amz-Date: 20220316T000334Z
X-Amz-Object-Attributes: Checksum
X-Amz-Object-Attributes: ObjectParts
```
When receiving headers that way, our web server will return them as a list of values, accessible via `Headers.getlist()`.
Because the parser was calling `Headers.get()`, it would only get the first …
> S3/ASF parser: fix parsing header `list` shape type with multivalue headers

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_describer.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_executor.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- tests/aws/services/cloudformation/resources/test_apigateway.py
- tests/aws/services/cloudformation/resources/test_secretsmanager.py
- tests/aws/services/cloudformation/resources/test_sns.py
- tests/aws/services/cloudformation/resources/test_sns.validation.json
- tests/aws/services/cloudformation/resources/test_stepfunctions.py
- tests/aws/services/cloudformation/test_template_engine.py
One remaining case where we replace API Gateway urls with LocalStack URLs remains.
Note: this is needed for APIGWv1 because the URL is not an output of the API so we have to adjust it in CFn :( 
> [!NOTE]
> This forms a stack on top of #13011  
* Handle URL replacements in Join and Sub
> CFNV2: finish URL replacements for API Gateway

- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/resource_router.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/test_invoke.py
- tests/aws/services/apigateway/conftest.py
- tests/aws/services/apigateway/test_apigateway_api.py
- tests/aws/services/apigateway/test_apigateway_api.snapshot.json
- tests/aws/services/apigateway/test_apigateway_api.validation.json
- tests/aws/services/apigateway/test_apigateway_basic.py
- tests/aws/services/apigateway/test_apigateway_basic.snapshot.json
- tests/aws/services/apigateway/test_apigateway_basic.validation.json
We got a report that the `TestInvokeMethod` would not work when the `pathWithQueryString` was not provided. After testing in AWS, it showed that this parameter was not required and this was an assumption that stayed from the previous implementation. 
This PR implements more tests around this parameter and the behavior of AWS when it is not provided. 
It also showed AWS is not sending the same `log` response when the integration is of type `MOCK`. 
I took the opportunity to refactor a bit the utilities we have around `TestInvokeMethod`, because it is quite tricky to snapshot match as it returns a big string with newlines that we would like to snapshot match more precisely. 
- fix the behavior of `TestInvokeMethod` when `pathWithQueryString` is not provided: it will fallback to the …
> APIGW: fix TestInvokeMethod path logic

- localstack-core/localstack/services/cloudformation/engine/transformers.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_transform.py
- tests/aws/services/cloudformation/api/test_transformers.py
We need to support the language extensions transform to match parity with the V1 provider. We start by implementing the `Fn::Length` transform to demonstrate general integration with the v1 implementation. We will implement `Fn::ForEach` in a follow up as this is a more complex change.
* Separate local and global transforms in the `ChangeSetModelTransformer.transform` method
* **TEMPORARILY** repurpose `resolve_refs_recursively` to enable the feature, with the knowledge that the requirements for transforms are much lower, and we can potentially re-purpose the `ChangeSetVisitor` or similar to re-write this usage after the new provider is released
* This allows us to repurpose the v1 implementation of the language extensions macro which we know is in parity with AWS and has been validated …
> CFNV2: Implement Fn::Length for language extensions

- Makefile
- bin/docker-helper.sh
The `PLATFORM` argument doesn't work for cross-arch builds (e.g., on ARM macs) because without the `--platform` argument, Docker buildkit simply picks the native arguments. In the current implementation, `make PLATFORM=amd64 docker-build` results in arm64 image being built on my M1 MacBook.
* Make `PLATFORM` configurable in the `Makefile`
* Use explicit `linux/$PLATFORM` flag for the Docker build
`make PLATFORM=amd64 docker-build`
> Fix cross-arch Docker build

- localstack-core/localstack/utils/docker_utils.py
The port checking utility retries upon not being able to find a bindable because we always return `False` upon exception. If Docker (or container client) is not available, retries (without backoff) won't help (unless it's a temporary issue; e.g., Docker starting).
Raise `DockerNotAvailable` exception for client code to better distinguish error cases.
⚠️ Breaking change: The current behavior is to return `False`
Stop Docker and try feature that uses `container_ports_can_be_bound`
This change might affect the localstack-pro and K8 pipelines, which must succeed before proceeding.
Both pipelines are 🟢🟢
> Raise DockerNotAvailable exception if port checking is impossible

- .github/dependabot.yml
- .github/workflows/asf-updates.yml
- .github/workflows/update-test-durations.yml
- .github/workflows/upgrade-python-dependencies.yml
With #13035 we are now enforcing that a label has to be added to PRs which indicates if the changes of the PR should be reflected in the documentation.
This PR adds this label to automatically to PRs created by our GitHub workflows.
- Modify our GitHub workflows such that workflows which create PRs add the `skip-docs` label:
- [ASF Updates](https://github.com/localstack/localstack/actions/workflows/asf-updates.yml) like https://github.com/localstack/localstack/pull/13053
- [Test Duration Updates](https://github.com/localstack/localstack/actions/workflows/update-test-durations.yml) like https://github.com/localstack/localstack/pull/13014
- [Upgrade Python Dependencies](https://github.com/localstack/localstack/actions/workflows/upgrade-python-dependencies.yml) like …
> add skip-docs label to automatically generated PRs

- localstack-core/localstack/services/cloudformation/provider.py
- localstack-core/localstack/services/cloudformation/v2/provider.py
- pyproject.toml
- tests/aws/services/apigateway/test_apigateway_basic.py
- tests/aws/services/cloudformation/api/test_changesets.py
- tests/aws/services/cloudformation/api/test_changesets.validation.json
- tests/aws/services/kms/test_kms.py
- tests/aws/services/lambda_/test_lambda_developer_tools.py
- tests/aws/services/route53/test_route53.py
- tests/aws/services/ssm/test_ssm.py
- tests/unit/services/apigateway/test_handler_integration_request.py
- tests/unit/services/apigateway/test_handler_integration_response.py
- tests/unit/services/kms/test_kms.py
- tests/unit/services/s3/test_s3.py
- tests/unit/utils/test_id_generator.py
- tests/unit/utils/test_objects.py
After https://github.com/localstack/localstack/pull/12953, we started to enable all the ignored `ruff` rules.
With this PR, we re-enable [B017](https://docs.astral.sh/ruff/rules/assert-raises-exception/) and fix the code accordingly.
- Enable B017;
- Format the code.
>  Enable B017 ruff linting rule

- localstack-core/localstack/services/sqs/provider.py
- pyproject.toml
- tests/integration/aws/test_app.py
- tests/unit/http_/test_asgi.py
- tests/unit/http_/test_hypercorn.py
- tests/unit/state/test_pickle.py
https://github.com/localstack/localstack/pull/12953 introduced the `pyupgrade` rules to our `ruff` linter.
However, a few rules have been ignored. This PR enabled [UP028](https://docs.astral.sh/ruff/rules/yield-in-for-loop/) and fixes the code accordingly.
> Ruff linter: enable rule UP028

- .github/workflows/aws-tests.yml
- localstack-core/localstack/services/cloudwatch/provider.py
https://github.com/localstack/localstack/pull/12964 broke a cloudwatch v1 test, which is only executed if respective code is changed.
The following pipelines failed:
- https://github.com/localstack/localstack/actions/runs/17226243111/job/48871812433
- https://github.com/localstack/localstack/actions/runs/17225273361/job/48869379653
The issue was caused by a change in `moto`'s `cloudwatch` implementation, specifically the `Alarm` class, which led to serialization issues:
```
..
File "/home/runner/work/localstack/localstack/localstack-core/localstack/services/cloudwatch/provider.py", line 263, in create_message_response_update_state_sns
return json.dumps(response)
^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/json/__init__.py", line 231, in dumps
return …
```
> fix cloudwatch v1 timestamp serialization after moto upgrade

- tests/aws/services/cloudformation/resources/test_lambda.snapshot.json
- tests/aws/services/cloudformation/resources/test_lambda.validation.json
- tests/aws/services/cloudformation/resources/test_sqs.snapshot.json
- tests/aws/services/cloudformation/resources/test_sqs.validation.json
- tests/aws/services/cloudformation/test_template_engine.snapshot.json
- tests/aws/services/cloudformation/test_template_engine.validation.json
With #12957, the SQS maximum message size was changed to 1 MiB.
However, some snapshots were missed due to the test selection not taking into account cloudformation tests, which fails our pipelines.
* Update snapshots for failing SQS cloudformation tests
> Fix SQS tests failing due to missing snapshot update after #12957

- localstack-core/localstack/config.py
- localstack-core/localstack/state/codecs.py
- localstack-core/localstack/state/pickle.py
- localstack-core/localstack/testing/pytest/fixtures.py
- pyproject.toml
- requirements-base-runtime.txt
- requirements-basic.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
- tests/unit/state/test_pickle.py
Follow up on https://github.com/localstack/localstack/pull/13063.
As we are moving on with `avro` based serialization, we are removing the `jsonpickle` encoder/decoder.
> Remove jsonpickle serializer

- localstack-core/localstack/state/core.py
- localstack-core/localstack/state/pickle.py
Currently our decoders serve as adapter only to dill pickle. Because they type information is stored in the pickle, you can de-serialize a pickle and get the correct type without having to specify it at deserialization. Unfortunately this process breaks down when you've moved or renamed a class that you want to deserialize into.
So to be able to de-couple code and data serialization, and separate reader/writer schema, we need the decoder to be type-aware. The Encoder has to be type aware for certain operations as well, for example if we pass a TypedDict to encode, we won't know which type to encode since python doesn't retain type information for typed dicts. So this is just to make the encoding API a more flexible.
* state Encoder and Decoder APIs now optionally take a expected_type …
> extend the Encoder/Decoder state API to be type-aware

- localstack-core/localstack/utils/tagging.py
This PR improves the type hints for the `TaggingService` constructor by making explicit the nullability of the arguments.
`py-avro-schema` would raise an error with the existing implementation since the arguments were not nullable (i.e., not `str | None`) and `None` would not be a good default for a string.
In cases like this, `mypy` would raise an error: `error: Incompatible default for argument "val" (default has type "None", argument has type "str")  [assignment]`).
> Fix typing for the tagging service

- bin/docker-helper.sh
- tests/bin/test.docker-helper.bats
The `docker-helper.sh build` command fails with cryptic Docker buildx errors when executed directly without the `PLATFORM` environment variable set. Users get confusing error messages like:
`ERROR: failed to build: "" is an invalid component of "linux/": platform specifier component must match "^[A-Za-z0-9_.-]+$": invalid argument`
This happens because the `cmd-build()` function doesn't validate that the required `PLATFORM` environment variable is set, unlike other commands (`save`, `load`, `push`) which already have proper validation through the `_enforce_platform()` function.
While `make docker-build` works correctly (since the Makefile sets `PLATFORM`), developers running the script directly encounter these unclear errors without understanding what went wrong.
- Added …
> Fix:  add PLATFORM validation to docker-helper.sh build command

- localstack-core/localstack/utils/container_utils/container_client.py
- localstack-core/localstack/utils/container_utils/docker_cmd_client.py
- localstack-core/localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
If an image specifies a `VOLUME ["/tmp"]` command, this results in the creation of an anonymous volume.
When you delete a container, this volume is not deleted automatically - this has be explicitly configured via `docker container rm --volumes`
This PR adds support for that argument, plus a test to verify that an anonymous volume is created and deleted after using this argument.
> Docker: Support remove_container(volume=True)

- localstack-core/localstack/services/stores.py
- tests/unit/test_stores.py
`BaseStore` annotates the service name as `_service_name`, but we are dynamically adding `service_name`.
See https://github.com/localstack/localstack-pro/pull/5186#discussion_r2318454469
Updates unit tests
> Fix misnamed service_name attribute in stores

- .github/workflows/aws-tests.yml
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- localstack-core/localstack/services/cloudformation/resource_provider.py
While performing the last minute fixes for the Pro resources in #13045 we found that the v2 community tests were not being run. This meant that some bugs slipped in to the new provider undetected. This was only picked up in #13098.
* Correct the test changes determination to include the service code as well as the tests
* Undo a couple of fixes from #13045 that are no longer needed
* Handle the case where during modelling `try_load_resource_provider` is called with a `Nothing` value
> CFNV2: fix community issues after attempted pro fixes

- localstack-core/localstack/services/s3/provider.py
- localstack-core/localstack/services/s3/utils.py
- tests/aws/services/s3/test_s3_api.py
- tests/aws/services/s3/test_s3_api.snapshot.json
- tests/aws/services/s3/test_s3_api.validation.json
Resolves #13106 
- Improve our parity with S3's `UploadPartCopy` functionality. This was achieved by adding support for the following conditionals: `CopySourceIfMatch`, `CopySourceIfModifiedSince`, `CopySourceIfNoneMatch` and `CopySourceIfUnmodifiedSince`
- Updated the `S3Provider.upload_part_copy` method to handle the above mentioned conditions.
- Created a utility which handles which precondition is raised when the method fails.
- Added parity testing for the different possible failures and paths for combinations of the different conditions. 
- Note: Not every combination is accounted for, I mainly prioritised single condition usage as well as specific cases outlined in the documentation https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html
- This was tested using …
> Support Additional Parameters for S3 UploadPartCopy

- localstack-core/localstack/services/kms/provider.py
- localstack-core/localstack/testing/snapshots/transformer_utility.py
- tests/aws/services/kms/test_kms.py
- tests/aws/services/kms/test_kms.snapshot.json
- tests/aws/services/kms/test_kms.validation.json
This PR addresses an issue where LocalStack's KMS service was not enforcing AWS KMS behavior regarding multi-region key replication. According to AWS documentation, only [multi-region primary keys](https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html#multi-region-concepts) can be used as sources for replication, but LocalStack was allowing both primary and replica keys to be replicated.
- **Improved method in `replicate_key` in `KmsProvider`**: Added validation to check that the source key is a multi-region primary key before allowing replication
- **Error handling**: Localstack now returns the exact AWS error message: `UnsupportedOperationException`
- Added `test_replicate_replica_key_should_fail()` test which verifies that attempting to replicate a …
> KMS: AWS-compliant validation for multi-region key replication

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_validator.py
- tests/aws/services/cloudformation/api/test_changesets.py
- tests/aws/services/cloudformation/api/test_changesets.snapshot.json
- tests/aws/services/cloudformation/api/test_changesets.validation.json
While investigating issues from the telemetry, I found that an `AWS::NoValue` was being turned into a `Nothing` which itself was being looked up as a key in a dictionary (the conditions).
```python
foo = Nothing
bar = {}
print(foo in bar)
```
This does not work because `Nothing` is not hashable, so cannot be used as a dictionary key.
The reason for this is that in #13000 I incorrectly set any `NoValue` to `Nothing` during the modelling phase, however this caused the above issue. 
* Remove incorrect setting of `arguments.value` to `Nothing`
* Add test that exercises the bug found, specifically checking for `AWS::NoValue` in an update operation
> CFn: fix modelling issue with AWS::NoValue

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- tests/aws/services/cloudformation/test_change_set_fn_select.py
- tests/aws/services/cloudformation/test_change_set_fn_select.snapshot.json
- tests/aws/services/cloudformation/test_change_set_fn_select.validation.json
A user experienced the following issue when deploying their stack:
```
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py", line 853, in _compute_fn_select
selection = values[index]
```
We already have validation of index, but guess what: it was an off-by-one error!
> [!NOTE]
> This was actually during template _modelling_ and was not a result of an error on their part. In the transformer we try to call the preprocessor's method (in case any child intrinsic functions only access parameter values) and ignore any exceptions and continue visiting. However in this case the bad index check was raising an `IndexError` rather than the specific `RuntimeError` that we already catch.
> We should still be more strict …
> CFn: better validation of select construct

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_transform.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_validator.py
- localstack-core/localstack/services/ecr/resource_providers/aws_ecr_repository.py
- tests/aws/services/cloudformation/test_change_set_fn_select.py
- tests/aws/services/cloudformation/test_change_set_fn_select.snapshot.json
- tests/aws/services/cloudformation/test_change_set_fn_select.validation.json
A previous PR #13136 broke template deployment in the Pro repsitory. The issue was that while visiting the template for CreateChangeSet in the transformer, we were not handling the case where the nested intrinsic function calls would not return `None` but would still return a semi-valid transformed value. In particular, the inner intrinsic would return the visited arguments (say `["Resource", "Attribute"]` from a `GetAtt` call. The arguments to select may be something like:
```
Fn::Select: [4, [":", ["Resource", "Attribute"]]]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    the result of visiting `Fn::Join` arguments
^^^^^^^^^^^^^^^^^^^^^^^^      the result of visiting `Fn::GetAtt` arguments
^                                      index still out of range
```
This problem is really highlighting that …
> CFn: fix invalid behaviour for nested intrinsic calls

- localstack-core/localstack/constants.py
- localstack-core/localstack/services/es/provider.py
- localstack-core/localstack/services/opensearch/cluster.py
- localstack-core/localstack/services/opensearch/packages.py
- localstack-core/localstack/services/opensearch/provider.py
- localstack-core/localstack/services/opensearch/versions.py
- tests/aws/cdk_templates/Bookstore/BookstoreStack.json
- tests/aws/scenario/bookstore/test_bookstore.py
- tests/aws/scenario/bookstore/test_bookstore.snapshot.json
- tests/aws/scenario/bookstore/test_bookstore.validation.json
- tests/aws/services/es/test_es.py
- tests/aws/services/opensearch/test_opensearch.py
- tests/aws/services/opensearch/test_opensearch.snapshot.json
- tests/aws/services/opensearch/test_opensearch.validation.json
The LocalStack emulation of OpenSearch is a bit behind in terms of which OpenSearch version the service supports.
This PR updates the service such that it is on-par with AWS again.
Associated docs PR: https://github.com/localstack/localstack-docs/pull/190
- Add new versions for OpenSearch:
- 2.15
- 2.17
- 2.19
- 3.1
- Set the new default version for OpenSearch domains (if no version is set) to 3.1
> opensearch: add new versions

- localstack-core/localstack/aws/protocol/parser.py
- localstack-core/localstack/aws/protocol/serializer.py
- localstack-core/localstack/aws/spec.py
- tests/aws/services/kinesis/test_kinesis.validation.json
- tests/unit/aws/protocol/test_parser.py
- tests/unit/aws/protocol/test_serializer.py
This PR is part of a bigger initiative to implement support for the [new Smithy Protocol](https://smithy.io/2.0/additional-specs/protocols/smithy-rpc-v2.html) `smithy-rpc-v2-cbor`, as well as the new Botocore multi-protocol support for single services (before, a service could only define one protocol).
This PR is stacked on top of #13103. 
This PR properly implements the `smithy-rpc-v2-cbor` protocol and adds support for it. 
Currently, no service that LocalStack supports implements this protocol, but we can still our unit tests to validate the serialization/deserialization works. 
The logic is based on Botocore's own serializer and parser, with some adaptations due to the client/server difference. 
One of the main feature of RPC v2-based protocol is its routing, following the …
> ASF: implement RPC V2 CBOR parser and serializer

- localstack-core/localstack/aws/handlers/service.py
- localstack-core/localstack/utils/catalog/catalog.py
- localstack-core/localstack/utils/catalog/catalog_loader.py
- localstack-core/localstack/utils/catalog/common.py
- localstack-core/localstack/utils/catalog/plugins.py
- tests/unit/utils/test_catalog.py
This PR introduces a plugin AWS license catalog which will be used to customize error messages for unimplemented AWS services or operations.
Downloading and loading of the license catalog is not implemented in this PR and will be completed in the next PR.
- Add new license catalog plugin
> IaC: Add AWS operations and CFN resources catalog

- localstack-core/localstack/services/ses/provider.py
- pyproject.toml
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
- tests/aws/services/ses/test_ses.snapshot.json
- tests/aws/services/ses/test_ses.validation.json
With https://github.com/localstack/moto/pull/78, we introduced a new workflow in `localstack/moto` which should automatically - on a weekly schedule - sync-rebase and release our fork of `moto` (pushing `moto-ext` to pypi).
In order to implement this continuous integration of changes in `moto` here in LocalStack, we now should now make sure that updates to `moto(-ext)` get included regularly.
This is why this PR removes the pin to a specific version in the requirements of `localstack-core` and bumps the version of `moto-ext` to the latest release (the first one which has been created fully automatically).
This bump will cause some issues (since there was quite a distance), but afterwards we are hoping that the more frequent integration decreases the pain there. Basically this means …
> unpin moto-ext, upgrade to 5.1.12.post22

- localstack-core/localstack/dev/kubernetes/__main__.py
- localstack-core/localstack/dev/run/paths.py
With https://github.com/localstack/localstack/pull/13037 we upgraded to Python 3.13.
Unfortunately, we have some dev tooling which contains some direct path handling to the venv which we missed to update.
This PR cleans that up. As far as I can tell, there are no other references to `python3.11` anymore in the codebase.
- Updates venv paths in `localstack-core/localstack/dev/` for Python 3.13.
> update old references to venv paths

- localstack-core/localstack/aws/api/core.py
- localstack-core/localstack/aws/handlers/service.py
- localstack-core/localstack/aws/protocol/parser.py
- localstack-core/localstack/aws/protocol/serializer.py
- localstack-core/localstack/aws/protocol/service_router.py
- localstack-core/localstack/aws/skeleton.py
- localstack-core/localstack/aws/spec.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py
- localstack-core/localstack/services/sqs/query_api.py
- tests/unit/aws/test_service_router.py
This PR is part of a bigger initiative (see #13028) to implement support for the [new Smithy Protocol](https://smithy.io/2.0/additional-specs/protocols/smithy-rpc-v2.html) smithy-rpc-v2-cbor, as well as the new Botocore multi-protocol support for single services (before, a service could only define one protocol).
This PR implements a new protocol detection for services who support multiple protocols. It sets the `protocol` as a first class citizen in our handler chain, allowing us to use the detected protocol to create our parser and serializer. 
The protocol detection is done by following the different specs as defined at https://smithy.io/2.0/aws/protocols/ and https://smithy.io/2.0/additional-specs/protocols
We have extensive testing of the protocol determination by upgrading our …
> ASF: implement multi-protocol support

- tests/aws/services/cloudwatch/test_cloudwatch.py
- tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json
- tests/aws/services/cloudwatch/test_cloudwatch.validation.json
Follow up from #13173 
It added snapshots for a few tests, but I missed that one region was hardcoded in some field.
This PR updates it to use the region from the client for proper transformation. 
- update test to use `region_name` instead of hardcoded value
> CloudWatch: fix MA/MR for new snapshot test `test_put_metric_alarm_escape_character`

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- localstack-core/localstack/services/cloudformation/engine/v2/resolving.py
- tests/aws/services/cloudformation/test_template_engine.py
- tests/aws/services/cloudformation/test_template_engine.snapshot.json
- tests/aws/services/cloudformation/test_template_engine.validation.json
- tests/aws/templates/resolve_ssm.yaml
- tests/unit/services/cloudformation/test_cloudformation.py
From #13169 we have an example of dynamic resolving where the name of the SSM parameter is built up from an `Fn::Sub` call, e.g.
```yaml
Value: !Sub "abc:{{resolve:ssm:${ParameterName}}}"
```
This means the `!Sub` intrinsic should be invoked before the SSM parameter is resolved.
We now 
* perform better matching of whether a parameter is present
* handle failure to resolve the parameter and assume that we will come back to it later
Also: 
* add a unit test for the regex matching
* update an exisitng test to include this use case
Closes #13169
> CFn: handle resolving parameter names constructed in intrinsics

- localstack-core/localstack/services/cloudformation/engine/v2/resolving.py
- This PR fixes an issue in the pipeline caused by `perform_dynamic_reference_lookup` returning a number in certain occasions. 
- convert returning type to string as the type annotation suggests
> CFN: fix for dynamic ref when value is a number

- tests/aws/services/ses/test_ses.py
- tests/aws/services/ses/test_ses.snapshot.json
- tests/aws/services/ses/test_ses.validation.json
As reported in #12722, `describe_configuration_set` is missing SNS event destinations.
This is addressed in https://github.com/getmoto/moto/pull/9023 and this PR complements the parity enhancement with a snapshot test.
Only tests.
- Snapshot test to validate the destinations are there when setting them for a configuration set.
- Wait until https://github.com/getmoto/moto/pull/9023 is merged and cascaded to Localstack. Otherwise this test fails.
> SES: add snapshot test for describe_configuration_set with SNS destinations

- localstack-core/localstack/services/sqs/models.py
- tests/aws/services/sqs/test_sqs.py
- tests/aws/services/sqs/test_sqs.snapshot.json
- tests/aws/services/sqs/test_sqs.validation.json
We had an open issue in our internal issue tracker that was arguing that `ApproximateNumberOfMessagesNotVisible` was broken because of the same reason of #13196. Turns out it works fine! This just adds aws validated tests to demonstrate that it does.
* No functional changes, just adding tests after an investigation
> add sqs tests for ApproximateNumberOfMessagesNotVisible queue attribute

- localstack-core/localstack/services/kinesis/models.py
- localstack-core/localstack/services/kinesis/provider.py
- tests/aws/services/kinesis/test_kinesis.py
- tests/aws/services/kinesis/test_kinesis.snapshot.json
- tests/aws/services/kinesis/test_kinesis.validation.json
The mock server does not implement resource policy operations, but the provider redirects to it, generating an AccessDenied exception. see [the original bug](https://github.com/localstack/localstack/issues/12488
) for details.
The PR implements the resource policy crud operations and provides snapshot integration tests tested against AWS.
See the original bug for details #12488. You can test with terraform:
```terraform
terraform {
required_providers {
aws = {
source  = "hashicorp/aws"
version = "~> 5.0"
}
}
required_version = ">= 1.0"
}
resource "aws_kinesis_stream" "kinesis_stream" {
name             = "my-kinesis-stream"
shard_count      = 1
retention_period = 24
}
data "aws_iam_policy_document" "kinesis_data_stream_policy" {
statement {
actions = [
"kinesis:PutRecord", …
```
> feat(kinesis): implement resource policies CRUD operations (#12488)

- .github/workflows/pr-enforce-pr-labels.yml
With https://github.com/localstack/localstack/pull/13189 a little bit of copy-pasta slipped through.
It still references the branch used when working on the workflow with https://github.com/localstack/meta/pull/31.
This PR fixes this reference.
- Fix the reference to the notes label check workflow.
- Remove the `notes-labels` branch in the meta repository which was created temporarily to mitigate the workflow execution issues until this PR is merged.
> fix pr-enforce-pr-labels workflow reference

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- localstack-core/localstack/services/cloudformation/v2/provider.py
- tests/aws/services/cloudformation/test_template_engine.py
- tests/aws/services/cloudformation/test_template_engine.validation.json
- tests/aws/templates/resolve_secretsmanager_with_backslashes.yaml
When dynamic references (like `{{resolve:secretsmanager:secret-id:secret-string:json-key::}}`) return backslashes, they are currently not handled correctly. Mainly, they are interpreted by `re.sub`, and used to escape characters (or reference sections of the regex match).
The [python documentation](https://docs.python.org/3/library/re.html#re.sub) says this about this topic:
> repl can be a string or a function; if it is a string, any backslash escapes in it are processed. That is, \n is converted to a single newline character, \r is converted to a carriage return, and so forth. Unknown escapes of ASCII letters are reserved for future use and treated as errors. Other unknown escapes such as \& are left alone. Backreferences, such as \6, are replaced with the substring matched by group 6 …
> Cfn: Fix backslash processing for dynamic replacement values

- localstack-core/localstack/utils/catalog/catalog.py
- localstack-core/localstack/utils/catalog/common.py
- tests/unit/utils/test_catalog.py
This is a companion branch, the changes in this PR are primarily needed for the pro catalog.
The logic to retrieve CloudFormation resources available at runtime has been moved to `CatalogPlugin`, renamed private methods for better readability, added new state `CloudFormationResourcesSupportAtRuntime.NOT_IMPLEMENTED`
- Moved logic to obtain CloudFormation resources available at runtime to `CatalogPlugin`
- Renamed method `get_aws_services_at_runtime` 
- Added new argument `is_pro_resource` to the `get_cloudformation_resource_status`, this logic is needed in pro catalog
> IaC: Update CatalogPlugin class and common catalog plugins logic

- tests/aws/services/cloudformation/resources/test_apigateway.py
Fix failing tests from https://github.com/localstack/localstack-pro/pull/5371
* Adds a marker in `test_cfn_apigateway_swagger_import` as it uses pytest http marker
> Skip test test_cfn_apigateway_swagger_import when running in K8s

- localstack-core/localstack/aws/protocol/serializer.py
- tests/aws/services/cloudwatch/test_cloudwatch.py
- tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json
- tests/aws/services/cloudwatch/test_cloudwatch.validation.json
- tests/unit/aws/protocol/test_serializer.py
Even though [RFC 7230] states that header field names should be considered case insensitive, some clients to not conform to this specification.
Especially, the fluent bit cloudwatch client will assert the `x-amzn-RequestId` header - case sensitive.
To support this client, we need to return the correct casing for this response header.
This change not only changes the header (and has an AWS validated test to confirms it), but also adds the header to the `query` protocol, something I confirmed for cloudwatch in the test, and manually for EC2.
* Add `x-amzn-RequestId` header for `query` protocol services
* Correct casing for `x-amzn-RequestId` header for `json` and `cbor` (based) protocols
> Correct casing for x-amzn-RequestId header

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_describer.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- localstack-core/localstack/services/cloudformation/v2/provider.py
- localstack-core/localstack/utils/numbers.py
- tests/aws/services/cloudformation/resources/test_logs.py
- tests/aws/services/cloudformation/resources/test_logs.snapshot.json
- tests/aws/services/cloudformation/resources/test_logs.validation.json
- tests/aws/services/cloudformation/test_change_set_parameters.py
- tests/aws/services/cloudformation/test_change_set_parameters.snapshot.json
- tests/aws/services/cloudformation/test_change_set_parameters.validation.json
- tests/aws/templates/logs_group.yml
- tests/unit/test_common.py
A customer raised an issue with deploying their stack which contains a `Number` Parameter type. Specifically they were using it in a condition:
```yaml
Parameters:
Foo:
Type: Number
Conditions:
ShouldFrobble:
Fn::Equals:
- !Ref Foo
- 1
Resources:
MyConditionalResource:
Condition: ShouldFrobble
```
When supplied with the input `[{"ParameterKey": "Value", "ParameterValue": "1"}]` (all parameter values passed in are strings) the `1` was treated as a string, then compared to the integer `1` (i.e. `"1" == 1`), which is falsy and as such the condition evaluates to `False`.
TBD
> CFn: fix number parameter types

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_preproc.py
- tests/aws/services/cloudformation/engine/test_conditions.py
- tests/aws/services/cloudformation/engine/test_conditions.snapshot.json
- tests/aws/services/cloudformation/engine/test_conditions.validation.json
- tests/aws/templates/references_to_conditions.yml
When a template resource which is disabled by a condition references another resource that's disabled by a condition, the CFn engine currently incorrectly raises a `ValidationError` in the transformer, validator and executor. This is not in parity with AWS. See the `references_to_conditions.yml` template for an example.
* Skip resources and outputs in `visit_node_resources`/`visit_node_outputs` entirely in the preproc so we don't even evaluate the resource block during template preprocessing time
* Add test capturing this behaviour
> CFn: correctly skip conditionally disabled resources

- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
- tests/aws/services/sns/test_sns.validation.json
As per title. `test_create_topic_in_multiple_regions` was not very cleanly written in regards to multiple regions used. Additionally, the snapshots weren't transformed properly, causing flakes in the pipeline.
Context for the flakes: I am unsure what exactly triggers this, but essentially what happened was that only one region was transformed in the snapshots. And for the pipeline, it was "the other" region that was transformed, causing a mismatch.
MA/MR pipeline run can be found [here](https://github.com/localstack/localstack/actions/runs/18339463990)
- rewrite `test_create_topic_in_multiple_regions`
> SNS: Fix multi-region test

- localstack-core/localstack/services/apigateway/legacy/provider.py
- tests/aws/services/apigateway/test_apigateway_api.py
- tests/aws/services/apigateway/test_apigateway_api.snapshot.json
- tests/aws/services/apigateway/test_apigateway_api.validation.json
This has been reported with #13218
We are forwarding calls to `PutIntegration` to moto, but it doesn't save the `connectionId` parameter when the integration is of type `VPC_LINK`. 
The linked issue is a bigger one, as LocalStack does not support NLB yet, so we technically don't fully support APIGW Private Integration with VPC Links, as it requires a link to the NLB via `targetArns`, but are not validating this as of now. 
See https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-api-with-vpclink-cli.html
- attach the `connectionId` to the moto model to be able to retrieve in `get_integration`
- add validated test
> APIGW: fix Integration connectionId not being returned
