localstack/localstack

.gitignore, localstack/dashboard/infra.py, localstack/dashboard/web/package.json, localstack/utils/common.py
Fix missing imports in UI code
=> Fix missing imports in UI code

Makefile, README.md, localstack/constants.py, localstack/mock/infra.py, localstack/utils/common.py, localstack/utils/kinesis/kinesis_connector.py, localstack/utils/kinesis/kinesis_util.py, setup.py, tests/test_integration.py
Fix #1 : Speed up installation time by lazy loading libraries.
=> Speed up installation time by lazy-loading libraries

README.md, localstack/utils/common.py, localstack/utils/kinesis/kinesis_connector.py, setup.py
This PR adds auto-checkpointing for records received from KCL via MultiLangDaemon.
=> Improve KCL checkpointing

Dockerfile, Makefile, README.md, localstack/mock/infra.py, setup.py
Fix #23 - Add Dockerfile, push public Docker image. Update `README`
=> Make LocalStack available via Docker

README.md, docker-compose.yml
Added docker-compose.yml for another option for running localstack
=> docker-compose file

localstack/services/sns/sns_listener.py
Fixes issue described in https://github.com/localstack/localstack/issues/144
=> added 'x-amz-sns-message-type' header to SNS messages

.github/PULL_REQUEST_TEMPLATE.md, .travis.yml, Makefile, localstack/dashboard/infra.py, localstack/ext/java/src/main/java/com/atlassian/localstack/LambdaExecutor.java, localstack/ext/java/src/test/java/com/atlassian/localstack/sample/LambdaHandler.java, localstack/services/awslambda/lambda_api.py, localstack/utils/common.py, localstack/utils/testutil.py, tests/integration/lambdas/lambda_integration.js, tests/integration/lambdas/lambda_integration.py, tests/integration/test_integration.py, tests/integration/test_lambda.py, tests/integration/test_web_ui.py
Configure Travis to build the Docker image
=> Configure Travis build

Makefile
=> Minor CI fix

localstack/services/generic_proxy.py
I use S3 and DynamoDB on localstack.
Thank you for commit 985a840 which I am needed.
But still CORS error occured as following.
So I added `Access-Control-Allow-Headers` and It worked well.
Best regards.
=> Add CORS headers, `Access-Control-Allow-Headers` to proxy

localstack/services/generic_proxy.py
Related to PR #160 (I created).
In addition, add headers needed on delete operations to `Access-Control-Allow-Headers`
=> Add CORS headers, `Access-Control-Allow-Methods` to proxy

.travis.yml, Makefile
=> Skip docker push on PR branch

LICENSE.txt, Makefile, README.md, localstack/constants.py, localstack/services/firehose/firehose_api.py, localstack/services/infra.py, localstack/services/install.py, localstack/utils/aws/aws_stack.py, localstack/utils/common.py, localstack/utils/testutil.py, requirements.txt, setup.py
* refactor configuration
* make base installation more light-weight
* lazy loading of libraries
=> refactor installation and make it more light-weight

.gitignore, Dockerfile, Makefile, localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/com/atlassian/localstack/LocalstackTestRunner.java, localstack/ext/java/src/main/java/com/atlassian/localstack/TestUtils.java, localstack/ext/java/src/test/java/com/atlassian/localstack/BasicFunctionalityTest.java, localstack/ext/java/src/test/java/com/atlassian/localstack/S3HttpsConnectionTest.java, localstack/ext/java/src/test/java/com/atlassian/localstack/SQSMessagingTest.java, localstack/ext/java/src/test/java/com/atlassian/localstack/sample/S3Sample.java, localstack/services/awslambda/lambda_api.py, localstack/services/install.py
Extend and integrate Java tests in CI
=> Extend and integrate Java tests in CI

Makefile, README.md, doc/contributor_license_agreement/README.md, doc/end_user_license_agreement/README.md, doc/roadmap/README.md, localstack/constants.py, localstack/services/infra.py, localstack/utils/analytics/event_publisher.py, localstack/utils/common.py
* add initial version of usage data collector (analytics events)
* release new version 0.7.0
* update READMEs and license agreements
=> Release version 0.7.0

localstack/utils/cloudformation/template_deployer.py
Fix table name for DynamoDB CloudFormation deployment.
=> Fix table name for DynamoDB CloudFormation deployment

.gitignore, Makefile, localstack/services/generic_proxy.py, localstack/services/s3/s3_listener.py
Fix S3 API to GET bucket notifications. Fix https://github.com/localstack/localstack/issues/169
=> Fix S3 API to GET bucket notifications

Dockerfile, Makefile, README.md, localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/cloud/localstack/LambdaContext.java, localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java, localstack/ext/java/src/main/java/cloud/localstack/LocalstackTestRunner.java, localstack/ext/java/src/main/java/cloud/localstack/TestUtils.java, localstack/ext/java/src/test/java/cloud/localstack/BasicFunctionalityTest.java, localstack/ext/java/src/test/java/cloud/localstack/S3HttpsConnectionTest.java, localstack/ext/java/src/test/java/cloud/localstack/SQSMessagingTest.java, localstack/ext/java/src/test/java/cloud/localstack/sample/LambdaHandler.java, localstack/ext/java/src/test/java/cloud/localstack/sample/S3Sample.java
Release Java artifacts to Maven Central. See updated `README` for instructions
=> Release Java artifacts to Maven Central

docker-compose.yml, localstack/services/dynamodb/dynamodb_listener.py
Create DDB stream on UpdateTable. Fixes https://github.com/localstack/localstack/issues/192
=> Create DDB stream on UpdateTable

localstack/utils/analytics/event_publisher.py
=> Add CI info to events

Makefile, localstack/services/s3/s3_listener.py
=> Fix S3 file access from Spark

Dockerfile, Makefile, bin/Dockerfile.base, localstack/dashboard/web/css/style.css, localstack/dashboard/web/index.html, localstack/dashboard/web/package.json, localstack/dashboard/web/views/infra.html, localstack/ext/java/pom.xml, localstack/services/awslambda/lambda_api.py, localstack/services/install.py, localstack/utils/testutil.py, tests/integration/test_lambda.py
* optimize size of Docker image (down to 1.05GB from 1.45GB)
* remove AUI dependency
=> Optimize size of Docker image

bin/localstack, localstack/config.py
Fix DATA_DIR config when running in Docker (see https://github.com/localstack/localstack/issues/204)
=> Fix DATA_DIR config when running in Docker

Makefile, README.md, localstack/constants.py, localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/CaseInsensitiveComparator.java, localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/CyclicGraphDetector.java, localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/EnvVars.java, localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/Platform.java, localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/ProcessKiller.java, localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/ProcessTree.java, localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/ProcessTreeRemoting.java, localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/QuotedStringTokenizer.java, localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/Util.java, localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/VariableResolver.java, localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/VersionNumber.java, localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/jna/GNUCLibrary.java, localstack/ext/java/src/test/java/cloud/localstack/S3HttpsConnectionTest.java, localstack/services/awslambda/lambda_api.py, localstack/services/install.py
Fix Maven dependencies
* add process_tree_killer files to repo
* remove dependency to `process-tree-killer`
=> Fix Maven dependencies; release version 0.7.2

localstack/services/generic_proxy.py
Daemonize threads in GenericProxy. See https://github.com/localstack/localstack/issues/209
=> Daemonize threads in GenericProxy

README.md, localstack/services/awslambda/lambda_api.py, localstack/services/dynamodbstreams/dynamodbstreams_api.py, localstack/services/es/es_api.py, localstack/services/firehose/firehose_api.py, localstack/services/generic_proxy.py, localstack/services/infra.py
* refactor code to start flask services
* remove some dead code
=> Refactor code to start flask services

localstack/constants.py, localstack/plugins.py, localstack/services/apigateway/apigateway_listener.py, localstack/services/awslambda/lambda_api.py, localstack/services/cloudformation/cloudformation_listener.py, localstack/services/dynamodb/dynamodb_listener.py, localstack/services/generic_proxy.py, localstack/services/infra.py, localstack/services/kinesis/kinesis_listener.py, localstack/services/s3/s3_listener.py, localstack/services/sns/sns_listener.py, localstack/utils/analytics/event_publisher.py, tests/integration/__init__.py, tests/integration/test_api_gateway.py
Refactor proxy code, extract listeners into subclasses of `ProxyListener`
=> Refactor proxy code and extract listeners into classes

bin/localstack, localstack/ext/java/src/test/java/cloud/localstack/BasicFunctionalityTest.java, localstack/services/awslambda/lambda_api.py, localstack/services/es/es_api.py, localstack/services/infra.py, localstack/utils/common.py, requirements.txt
* fix SQS names containing a dot character (see https://github.com/localstack/localstack/issues/232)
* refactor plugin loading
* extend tests
=> Fix SQS names containing a dot character; extend tests

Makefile, bin/localstack, localstack/constants.py, localstack/dashboard/infra.py, localstack/services/infra.py, localstack/services/install.py, localstack/utils/common.py, requirements.txt, tests/integration/test_lambda.py, tests/unit/test_misc.py
Fix issue with incomplete parallel downloads
=> Fix issue with incomplete downloads during installation

README.md, localstack/config.py
Ignore http_proxy environment variable
=> Ignore http_proxy environment variable

Dockerfile, Makefile, README.md, localstack/constants.py, localstack/services/install.py
Don't install kclpy libs by default
=> Don't install kclpy libs by default

localstack/services/awslambda/lambda_api.py, localstack/services/firehose/firehose_api.py, localstack/utils/aws/aws_responses.py
* add API to delete firehose streams
* refactor error logging code
=> Add API to delete firehose streams

README.md, localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/cloud/localstack/LocalstackTestRunner.java, localstack/services/infra.py
Improve error logging and installation for Java/JUnit. See #250
=> Improve error logging and installation for Java/JUnit

localstack/dashboard/infra.py, localstack/dashboard/web/css/style.css, localstack/dashboard/web/index.html, localstack/dashboard/web/js/app.js, localstack/dashboard/web/package.json, localstack/dashboard/web/views/infra.details.html
* fix lambda code viewer in UI
* cleanup npm dependencies
=> Fix lambda code viewer in UI

localstack/services/s3/s3_listener.py, tests/integration/test_notifications.py
Filter notifications by bucket key prefix/suffix (see #245).
=> Filter notifications by bucket key prefix/suffix

Dockerfile
Re-install npm libs when building Docker image
=> Re-install npm libs when building Docker image

localstack/services/s3/s3_listener.py
Fix issue with S3 notification path
=> Fix issue with S3 notification path

localstack/services/apigateway/apigateway_listener.py, localstack/services/awslambda/lambda_api.py, localstack/utils/aws/aws_stack.py, tests/integration/lambdas/lambda_environment.py, tests/integration/lambdas/lambda_integration.py, tests/integration/test_api_gateway.py
Add test for AWS_PROXY Lambda integration. This test was previously commented out. A few changes in the logic had to be made to get the test passing.
=> Add test for AWS_PROXY Lambda integration

localstack/services/s3/s3_listener.py
Add missing S3 event notification attributes. See #246
=> Add S3 event notification attributes

.travis.yml, localstack/services/awslambda/lambda_api.py
Add python 2.x tests to CI configuration (fix #273)
=> Add python 2.x tests to CI configuration

localstack/dashboard/infra.py, localstack/services/s3/s3_listener.py, requirements.txt
* bump moto version to 1.1.1
* minor fix in S3 CLI call
=> Bump moto version

README.md, localstack/config.py, localstack/services/awslambda/lambda_api.py
=> Expose $LOCALSTACK_HOSTNAME

localstack/plugins.py, localstack/services/infra.py, localstack/services/install.py, localstack/services/kinesis/kinesis_starter.py, localstack/services/sqs/sqs_listener.py, localstack/services/sqs/sqs_starter.py
Replace moto SQS with ElasticMQ.
=> Use ElasticMQ for SQS

README.md, localstack/config.py, localstack/services/dynamodb/dynamodb_starter.py, localstack/services/es/es_starter.py, localstack/services/generic_proxy.py, localstack/services/infra.py, localstack/services/kinesis/kinesis_starter.py, localstack/services/sqs/sqs_starter.py
Add configuration overrides for service backend URLs. (see #258)
=> Add configuration overrides for service backend URLs

localstack/utils/aws/aws_models.py
http://docs.python-guide.org/en/latest/writing/gotchas
Also simplify with dict.get() with default value and list comprehension.
=> Avoid mutable default arguements

localstack/utils/aws/aws_models.py, tests/integration/test_cloudformation.py
Fix undefined names reported by flake8 (fix #290, #291)
=> Fix undefined names reported by flake8

Makefile, README.md, localstack/config.py, localstack/services/sqs/sqs_listener.py
Expose services on a custom external host name (see #238).
=> Expose services on a custom external host name

localstack/services/apigateway/apigateway_listener.py, localstack/utils/aws/aws_stack.py, localstack/utils/common.py, requirements.txt, tests/integration/lambdas/lambda_integration.py, tests/integration/test_api_gateway.py, tests/unit/test_apigateway.py
Add a test case, extend functionality for API Gateway path parameters. This PR builds on the changes in #251 . 
@KamuelaFranco I've pulled your branch, rebased onto master, and squashed your commits into a single one. Then I added another commit with a few changes on top of it - this way we ensure that your contribution is preserved in this PR.
Can you please check out this branch and give it a try? Thanks
=> Add test case, extend functionality for API Gateway path parameters

Makefile
Push tagged Docker image only if version has changed. (See #308)
=> Push tagged Docker image only if version has changed

README.md, localstack/constants.py, requirements.txt
=> Release version 0.8.0

localstack/services/awslambda/lambda_api.py
Added known function details to `create-function` response.
Sample call:
aws --endpoint-url http://localhost:4574 lambda create-function --runtime python3.6 --role Nobody --handler lambda.score_plan --function-name 'WOMP' --zip-file fileb://lambda.zip --description 'the-desc' --timeout 30 --memory-size 128 --publish --dead-letter-config TargetArn=the-dlc
Sample output:
```
{
"FunctionName": "WOMP",
"FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:WOMP",
"Runtime": "python3.6",
"Role": "Nobody",
"Handler": "lambda.score_plan",
"Description": "the-desc",
"Timeout": 30,
"MemorySize": 128,
"VpcConfig": {
"SubnetIds": [
null
],
"SecurityGroupIds": [
null
]
},
"DeadLetterConfig": {
"TargetArn": "the-dlc"
},
"Environment": {
"Variables": {},
"Error": {}
},
"TracingConfig": {}
}
``` …
=> Added Lambda function details to create-function response

README.md, localstack/constants.py, localstack/plugins.py, localstack/services/infra.py, tests/integration/test_ssm.py
Have added lines for running SSM via moto. Opinions on this?
Also haven't included tests as its running via moto so really moto should test SSM right? But I can add some if needed.
=> Added support for running SSM via moto

localstack/services/awslambda/lambda_api.py, tests/unit/test_lambda.py
UUID should be capitalized.
+ Tests
=> Fix lambda's "delete-event-source-mapping"

localstack/services/awslambda/lambda_api.py, localstack/services/sqs/sqs_listener.py
* Fix regex to replace SQS queue URL hostnames (see #324)
* Properly clean up Lambda resources on error during creation (see #319)
=> Fix regex to replace SQS queue URL hostnames

localstack/services/sns/sns_listener.py, tests/unit/test_sns_listener.py
The Unsubscribe action now removes the subscription from SNS_SUBSCRIPTIONS.
To make it more testable I've pulled out the functions related to the subscriptions model - e.g. do_unsubscribe() and do_subscribe() into individual functions
=> Handle "Unsubscribe" action in SNS

localstack/ext/java/src/test/java/cloud/localstack/S3UploadTest.java
Add test for S3 upload (see #359)
=> Add test for S3 upload

localstack/services/awslambda/lambda_api.py, localstack/services/dynamodb/dynamodb_listener.py, localstack/utils/aws/aws_models.py, tests/unit/test_lambda.py
Also allow the invocation of versions and aliases by placing the function in the versions dictionary of LambdaFunction
=> Implement aliases in lambda API

Makefile, localstack/constants.py, localstack/dashboard/api.py, localstack/dashboard/infra.py, localstack/services/awslambda/lambda_api.py, localstack/services/dynamodb/dynamodb_listener.py, localstack/services/dynamodb/dynamodb_starter.py, localstack/services/es/es_api.py, localstack/services/es/es_starter.py, localstack/services/firehose/firehose_api.py, localstack/services/generic_proxy.py, localstack/services/kinesis/kinesis_listener.py, localstack/services/kinesis/kinesis_starter.py, localstack/services/s3/s3_listener.py, localstack/services/sns/sns_listener.py, localstack/services/sqs/sqs_starter.py, localstack/utils/aws/aws_models.py, localstack/utils/aws/aws_stack.py, localstack/utils/common.py, localstack/utils/kinesis/kclipy_helper.py, localstack/utils/testutil.py, requirements.txt, tests/integration/__init__.py, tests/integration/lambdas/lambda_environment.py, tests/integration/lambdas/lambda_integration.py, tests/integration/test_api_gateway.py, tests/integration/test_cloudformation.py, tests/integration/test_integration.py, tests/integration/test_lambda.py, tests/unit/test_lambda.py
Configure linter to enforce single quotes
=> Configure linter to enforce single quotes

localstack/config.py, localstack/services/awslambda/lambda_api.py, localstack/utils/common.py
Fix config for connecting to LocalStack from Docker, based on docker.for.mac.localhost host name
=> Fix config for connecting to LocalStack from Docker

localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java, localstack/ext/java/src/test/java/cloud/localstack/BasicFunctionalityTest.java, localstack/ext/java/src/test/java/cloud/localstack/LocalTestUtil.java, localstack/ext/java/src/test/java/cloud/localstack/sample/KinesisLambdaHandler.java, localstack/services/infra.py, localstack/services/install.py, tests/integration/test_lambda.py
Return raw data instead of b64 encoded strings for Java Lambda Kinesis records. (see #356)
=> Return raw data for Kinesis Lambda functions

README.md, localstack/constants.py, localstack/services/infra.py
Fix path to moto_server command. Possible solution for #368
=> Fix path to moto_server command

localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java, localstack/ext/java/src/test/java/cloud/localstack/sample/LambdaHandler.java, localstack/ext/java/src/test/java/cloud/localstack/sample/LambdaStreamHandler.java, localstack/services/install.py, requirements.txt, tests/integration/test_lambda.py
Here's an attempt to add SNSEvent and RequestStreamHandler support to lambda.
More events can be added later.
=> Lambda handler and events support  - Issue #344

localstack/services/sns/sns_listener.py
This PR supersedes #358 - add a minor refactoring and lint fix.
=> Adding subject to the SNS request for http requests

localstack/services/awslambda/lambda_api.py, localstack/services/sns/sns_listener.py, localstack/utils/cloudwatch/cloudwatch_util.py, tests/integration/test_integration.py, tests/integration/test_lambda.py
The changes in this PR are copied over from #375 . Minor modifications have been made to get the tests running.
=> Execute lambdas asynchronously if the source is a topic

localstack/services/s3/s3_listener.py, localstack/utils/cloudformation/template_deployer.py, requirements.txt, tests/integration/test_notifications.py, tests/integration/test_s3.py
* Fix S3 bucket policy response (see #382 )
* Bump to latest version of `moto`
=> Fix S3 bucket policy response

localstack/services/awslambda/lambda_api.py
Updated existing PR #322 to get the tests passing.
=> Add get_function_configuration to Lambda API

.travis.yml, Dockerfile, localstack/utils/aws/aws_stack.py
Set default region in `aws_stack.py`. This fixes an error that we've recently seen here: #350
=> Set default region in aws_stack.py

localstack/services/dynamodb/dynamodb_listener.py
Fix region name in DynamoDB TableARN. Currently we return the region "ddblocal" which is hardcoded in DynamoDBLocal. We use a simple search/replace regex to fill in the configured local region (e.g., `us-east-1`). See #323
=> Fix region in DynamoDB TableARN

.travis.yml, Makefile, localstack/services/apigateway/apigateway_listener.py, localstack/services/cloudformation/cloudformation_listener.py, localstack/services/dynamodb/dynamodb_listener.py, localstack/services/generic_proxy.py, localstack/services/kinesis/kinesis_listener.py, localstack/services/s3/s3_listener.py, localstack/services/sns/sns_listener.py, localstack/services/sqs/sqs_listener.py, localstack/utils/common.py, tests/integration/test_api_gateway.py
This PR addresses issue #359
* fix chunked encoding for S3 uploads
* refactor `GenericProxyHandler` class
=> Fix chunked encoding for S3 uploads; refactor GenericProxyHandler class

localstack/services/apigateway/apigateway_listener.py, tests/integration/test_api_gateway.py
Return CORS headers on API Gateway `OPTIONS` requests. Addresses #399
=> Return CORS headers on API Gateway OPTIONS requests

localstack/services/s3/s3_listener.py, tests/integration/test_notifications.py, tests/integration/test_s3.py
Fix S3 bucket notification configuration with single Event type specified. Addresses #396
=> Fix S3 bucket notification configuration with single Event type

localstack/services/s3/s3_listener.py, tests/integration/test_notifications.py
Fix s3 bucket notification configuration for single event filter. Addresses #396
=> Fix s3 bucket notification configuration for single event filter

README.md, localstack/constants.py, localstack/services/s3/s3_listener.py
* fix bug with single S3 CORS rule (fixes #434)
* release v0.8.2
=> Fix bug with single S3 CORS rule

localstack/dashboard/infra.py, localstack/services/cloudformation/cloudformation_listener.py
* Return CloudFormation 400 errors on stack creation (#325)
* Minor fix for UI (#395)
=> Return CloudFormation 400 errors on stack creation

localstack/services/dynamodb/dynamodb_listener.py, localstack/services/dynamodbstreams/dynamodbstreams_api.py
Fix DDB streams sequence numbers. Addresses #323
=> Fix DDB streams sequence numbers

localstack/ext/java/src/test/java/cloud/localstack/BasicFunctionalityTest.java, localstack/ext/java/src/test/java/cloud/localstack/sample/S3Sample.java
Integrate additional Java tests
=> Integrate additional Java tests

localstack/services/s3/s3_listener.py
Fix newline stripping for S3 chunked encoding (addresses #455)
=> Fix newline stripping for S3 chunked encoding

localstack/services/dynamodb/dynamodb_listener.py, tests/integration/test_dynamodb.py, tests/integration/test_integration.py
Fix handling of non-ascii content in DynamoDB items (addresses #464)
=> Fix handling of non-ascii content in DynamoDB items

.dockerignore, localstack/services/generic_proxy.py
Fix proxy handling of requests with missing content-length header
=> Fix proxy handling of requests with missing content-length header

Makefile, localstack/services/dynamodb/dynamodb_listener.py, localstack/services/dynamodb/dynamodb_starter.py, localstack/services/s3/s3_starter.py, localstack/utils/aws/aws_responses.py, localstack/utils/common.py, tests/integration/lambdas/lambda_integration.py, tests/integration/test_integration.py
Fix DynamoDB stream events for UPDATE operations (addresses #323)
=> Fix DynamoDB stream events for UPDATE operations

.travis.yml, README.md, bin/Dockerfile.base, localstack/constants.py, localstack/services/awslambda/lambda_api.py, localstack/services/install.py
* optimize base Docker image size
* Release v0.8.3
=> Release v0.8.3

.travis.yml, README.md, localstack/services/apigateway/apigateway_listener.py, localstack/services/awslambda/lambda_api.py, localstack/services/awslambda/lambda_executors.py, localstack/services/dynamodb/dynamodb_listener.py, localstack/utils/aws/aws_models.py, tests/integration/test_lambda.py, tests/unit/test_lambda.py
This is a slightly revised version of PR #427 , originally submitted by vangorra
=> Implementation of docker container reuse and expiration

localstack/ext/java/src/main/java/cloud/localstack/DockerTestUtils.java, localstack/ext/java/src/main/java/cloud/localstack/LocalstackTestRunner.java, localstack/ext/java/src/main/java/cloud/localstack/ServiceName.java, localstack/ext/java/src/main/java/cloud/localstack/TestUtils.java, localstack/ext/java/src/main/java/cloud/localstack/docker/Container.java, localstack/ext/java/src/main/java/cloud/localstack/docker/DockerExe.java, localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDockerTestRunner.java, localstack/ext/java/src/main/java/cloud/localstack/docker/PortMapping.java, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/EC2HostNameResolver.java, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/IHostNameResolver.java, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerProperties.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/Command.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/ExecCommand.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/LogCommand.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/PortCommand.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/PullCommand.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/RegexStream.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/RunCommand.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/StopCommand.java, localstack/ext/java/src/test/java/cloud/localstack/docker/BasicDockerFunctionalityTest.java
I couldn't get the existing JUnit Test Runner to work on Windows, so I created a new test runner that leverages the localstack docker image.
The only dependency is to have docker installed so this should play nice on all environments. 
The TestRunner will automatically pull the localstack image, start up a container, wait for it to be ready, and shut down the container after the suite is completed.
=> Docker JUnit Test Runner

localstack/services/apigateway/apigateway_listener.py, localstack/services/sns/sns_listener.py
=> Fix #511: Invalid timestamp format in CreateRestApi response

Makefile, README.md, bin/Dockerfile.base, localstack/services/sns/sns_listener.py
* Fix SQS endpoint URL for SNS notifications. Addresses #510 
* Small fix in `Dockerfile` for base image
=> Fix SQS endpoint URL for SNS notifications

README.md, localstack/constants.py, localstack/ext/java/pom.xml
=> Release new version of Maven library

README.md, localstack/constants.py, localstack/ext/java/pom.xml, localstack/services/install.py, requirements.txt
Bumo moto version to latest master
=> Bumo moto version

.travis.yml, README.md, localstack/constants.py, requirements.txt
* fix pipenv dependency issue (#488)
* release v0.8.4
=> Fix pipenv dependency issue

localstack/constants.py, localstack/ext/java/pom.xml
Release new version of Java libs (include changes of fix #535 )
=> Release new version of Java libs

localstack/config.py, localstack/services/awslambda/lambda_executors.py, localstack/services/dynamodb/dynamodb_listener.py, localstack/services/s3/multipart_content.py, localstack/services/s3/s3_listener.py, tests/integration/lambdas/lambda_integration.py, tests/integration/test_integration.py, tests/unit/test_s3.py
* Fix DDB streams event type (INSERT/MODIFY) - addresses #522
* Improve logging for Lambda functions - addresses #519
* Minor fixes and refactoring (break out multipart content handling into separate file)
=> Fix DDB streams event type (INSERT/MODIFY)

localstack/services/cloudformation/cloudformation_listener.py, localstack/services/s3/s3_listener.py, localstack/utils/common.py, requirements.txt
* Implement CF Fn::GetAZs function (in bumped moto version)
* Fix error message for create_stack on existing stack name
=> Implement CF Fn::GetAZs function

localstack/services/awslambda/lambda_api.py, localstack/services/dynamodb/dynamodb_listener.py, localstack/services/install.py, localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
* fix getting single DDB item by key
* improve DDB logging
* fix content-type for S3 responses
=> Fix getting single DDB item by key; improve DDB logging

localstack/services/s3/s3_listener.py
- call s3 lambda notifications asyncronously
- send notifications when files are uploaded via POST method
=>     S3 lambda/notification fixes 

docker-compose.yml, localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
* Fix S3 ExposePorts configuration to return specific headers. Addresses #520 
* Configure docker-compose to use web port defined in `$PORT_WEB_UI`
=> Fix S3 ExposePorts configuration to return specific headers

Makefile
=> Adding elasticmq to make clean

localstack/ext/java/src/main/java/cloud/localstack/docker/Container.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/RunCommand.java, localstack/ext/java/src/test/java/cloud/localstack/docker/ContainerTest.java
Fix for issue where environment variables are not loaded in the container using the Java module (https://github.com/localstack/localstack/issues/575)
=> Fix for 575

localstack/services/firehose/firehose_api.py
Currently Firehose doesn't have any testing so I'm not sure on how to test this new feature. But any feedback is appreciated.
We have a system where we need to stream all of our dynamodb records straight into elastic search via FIrehose.
=> Implement basic Firehose -> ES destination

README.md, localstack/ext/java/src/main/java/cloud/localstack/LocalstackTestRunner.java, localstack/ext/java/src/main/java/cloud/localstack/docker/Container.java, localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDockerTestRunner.java, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/DefaultEnvironmentVariableProvider.java, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/IEnvironmentVariableProvider.java, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalHostNameResolver.java, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerProperties.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/RunCommand.java, localstack/ext/java/src/test/java/cloud/localstack/docker/BasicDockerFunctionalityTest.java, localstack/ext/java/src/test/java/cloud/localstack/docker/ContainerTest.java
Minor change to an existing PR (https://github.com/localstack/localstack/pull/586) to get the Java integration tests passing. /cc @ABevier
=> Enhance docker test runner [updated PR]

bin/Dockerfile.base, localstack/services/awslambda/lambda_api.py, localstack/services/generic_proxy.py, localstack/utils/aws/aws_models.py, requirements.txt, tests/unit/test_lambda.py
* Add timeout to Lambda config (addresses #584)
* Refactor Lambda API code
* Reduce log verbosity on broken pipe (addresses #585)
* Update pip dependencies (addresses #563)
=> Add timeout to Lambda config

localstack/dashboard/web/package.json, requirements.txt
* Bump version of psutil (addresses #563)
* Bump jquery version to fix a security vulnerability
=> Bump version of psutil

README.md, localstack/constants.py, localstack/services/s3/s3_listener.py
=> Fix s3 notifications

README.md
Based on this comment: https://github.com/localstack/localstack/issues/77#issuecomment-299697723
And I tested it, too :+1:
=> Say S3 supports persistent uploads with DATA_DIR

localstack/services/dynamodb/dynamodb_listener.py
Adds the OldImage data so that when a listener of the dynamodb stream receives a deletion event, he's able to inspect the data that was deleted.
Apologies from the lack of tests, I'm not proficient in python and could not find a test I could easily mirror to test this fix. It was however working with my team's own integration tests.
=> Added "oldImage" data to dynamo events reflecting deletions

localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerProperties.java
Adding inheritance capabilities to the LocalstackDockerProperties annotation.
=> Adding inheritance capabilities to the LocalstackDockerProperties

localstack/services/s3/s3_listener.py, localstack/utils/common.py, requirements.txt, tests/unit/test_s3.py
* Fix S3 content-type headers (#618)
* Fix bucket notification config and add more unit tests (addresses #614)
* Flush temporary file to disk to fix issue for Java Lambdas
=> Fix S3 content-type headers and bucket notification config

README.md
Documenting problem reported on https://github.com/localstack/localstack/issues/248
=> Added installation code for Mac OS X Sierra

localstack/utils/cloudformation/template_deployer.py
Potential vulnerability risks were detected in your dependencies and used functions.
Some vulnerabilities have been replaced by safe alternatives. 
*config.py:148:8:* exec
* Reason: Could execute vulnerable and untrusted code.
* Severity: warning
*config.py:151:8:* exec
* Reason: Could execute vulnerable and untrusted code.
* Severity: warning
*infra.py:99:12:* exec
* Reason: Could execute vulnerable and untrusted code.
* Severity: warning
*dynamodbstreams_api.py:136:32:* hashlib.sha1
* Reason: Attacks can find collisions in the full version of SHA-1.
* Replacement: hashlib.sha512()
* Severity: critical
*common.py:228:8:* hashlib.md5
* Reason: Can be cracked by brute-force attack and suffers from extensive vulnerabilities.
* Replacement: hashlib.sha512()
* Severity: critical …
=> Vulnerabilities

localstack/package.json
Proposal for Kinesalite version upgrade to fix getShardIterator problem.
=> #687 Upgrading Kinesalite version to last one

localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java, localstack/ext/java/src/main/java/cloud/localstack/LocalstackTestRunner.java, localstack/ext/java/src/main/java/org/ow2/proactive/process_tree_killer/ProcessTree.java, localstack/ext/java/src/test/java/cloud/localstack/sample/LambdaStreamHandler.java
Closes #689 by using the same relocations as Amazon
=> Fix Java Lambda Classpath

README.md, localstack/constants.py, localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java
Release version 0.1.12 of Maven dependencies
=> Release version 0.1.12 of Maven dependencies

localstack/services/awslambda/lambda_api.py, localstack/services/es/es_starter.py, localstack/services/install.py, localstack/utils/kinesis/kinesis_connector.py
Addresses #663 . Fix shell commands for Windows installation
=> Fix shell commands for Windows installation

README.md, localstack/constants.py, localstack/services/generic_proxy.py, localstack/utils/persistence.py
* Release version 0.8.6
* Minor fixes for #639 and #676
=> Release version 0.8.6

Makefile, requirements.txt
Downgrade pip version to fix issues with 10.0.0
=> Downgrade pip version to fix issues with 10.0.0

localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/cloud/localstack/LambdaContext.java
Closes #713 
Updated aws-java-sdk-* jars 
Updated aws-lambda-* jars
Added missing common-logging jar
=> Review of the localstack-utils java classpath 

localstack/services/awslambda/lambda_api.py
My first pull request, and I couldn't properly build the entire thing because I'm on Windows 10 at the moment and the setup for development (i.e. make) does not work in WSL. So apologies if this is not as complete as it should be.  Comments/requests for further work are welcome.  Thank you.
=> Adds eventSourceARN and eventID to Kinesis records for Lambda

localstack/services/generic_proxy.py, localstack/services/kinesis/kinesis_listener.py, localstack/services/s3/s3_listener.py, requirements.txt, tests/integration/test_s3.py
* Fix kinesis error injection (#619)
* Add support for S3 content md5 checks (#612)
* Fix S3 host header to enforce path-style addressing and support different network scenarios (#613)
=> Fix kinesis error injection; fix S3 content md5 checks and host header

bin/Dockerfile.base, localstack/constants.py
Simple change to bump the elasticmq version
=> Bump elasticmq version to 0.13.10

README.md, localstack/constants.py
* Release version `0.8.7`
* Release version `0.1.14` of Java libs
=> Release version 0.8.7

requirements.txt
See:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18342
=> Upgrade pyYAML, fix CVE-2017-18342

requirements.txt
See https://github.com/boto/boto3/issues/1017
=> upgrade boto3 - fix cwe-200

tests/integration/test_lambda.py
Fix broken lambda tests. Seems to have been introduced by 13f94d920b1cf0ccc5c1750dab27c3158637c6d3
=> Fix broken lambda tests

localstack/services/firehose/firehose_api.py
Fixes #761, and formatting of object path.
=> Fix Firehose Bucket Destination Configuration

README.md
@whummer 
Updated troubleshooting section. This was pending since I faced https://github.com/localstack/localstack/issues/227 issue.
=> updated troubleshooting section

README.md, localstack/utils/testutil.py
=> implemented TODO changes from testutil.py

localstack/services/firehose/firehose_api.py, localstack/utils/kinesis/kinesis_connector.py, localstack/utils/kinesis/kinesis_util.py, tests/integration/test_integration.py
=> Firehose kinesis source

localstack/services/generic_proxy.py, tests/integration/test_s3.py
* Initial fix submitted here: https://github.com/localstack/localstack/pull/859
* Adds integration test to excercise downloading gzip file.
@t0rr3sp3dr0
=> Issue #722: Fix S3 download of gzip

localstack/services/cloudformation/cloudformation_listener.py
=> fix CloudFormation error message

Makefile, localstack/config.py, localstack/dashboard/web/package.json, localstack/services/sns/sns_listener.py, localstack/utils/aws/aws_stack.py, requirements.txt
* Check region header in SNS header
* Fix security vulnerabilities in dependencies
* Update Docker host address
=> Check region header in SNS header

localstack/ext/java/src/test/java/cloud/localstack/BasicFunctionalityTest.java, localstack/ext/java/src/test/java/cloud/localstack/sample/KinesisLambdaHandler.java, localstack/services/awslambda/lambda_api.py, localstack/services/dynamodb/dynamodb_listener.py, localstack/utils/common.py
Fix extraction of Java Lambda archives. Should fix the broken build in #937
=> Fix extraction of Java Lambda archives

README.md, localstack/constants.py, localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/cloud/localstack/DockerTestUtils.java, localstack/ext/java/src/main/java/cloud/localstack/Localstack.java, localstack/ext/java/src/main/java/cloud/localstack/ServiceName.java, localstack/ext/java/src/main/java/cloud/localstack/TestUtils.java, localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java, localstack/plugins.py, localstack/services/infra.py, requirements.txt, tests/integration/test_secretsmanager.py
* Add Secrets Manager support
* Integration test to create and retrieve secret
* PR open to add this to the python-client https://github.com/localstack/localstack-python-client/pull/11
=> Secret Manager Support for AWS services

README.md
=> Show How to Disable SSL Cert Checking in README

localstack/services/sns/sns_listener.py
Fix #992 by checking the topic ARN is not None in SNS forwarding function
=> Fix issue #992

README.md, localstack/config.py, localstack/services/awslambda/lambda_executors.py, tests/integration/test_lambda.py
=> Support --network switch when running lambda code

localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
* Updated check to send notifications to see if a multipart upload has been completed
* Added spec to upload a file larger than 64MB, which is the default threshold to break up file uploads
=> Notifications for multipart uploads (localstack#503)

localstack/services/apigateway/apigateway_listener.py, localstack/services/apigateway/helpers.py
In https://github.com/localstack/localstack/pull/997 I needed to reuse in tests some of the helper methods defined in **apigateway_listener** In this PR I continued extracting the rest to the **helpers** module.
=> apigateway_listener refactoring

localstack/dashboard/web/js/app.js
=> fix #1024 incorrect swagger.json url

README.md, bin/Dockerfile.base, localstack/constants.py, localstack/services/dynamodb/dynamodb_starter.py, localstack/services/infra.py, localstack/utils/cloudwatch/cloudwatch_util.py, localstack/utils/common.py, requirements.txt, tests/integration/test_integration.py
* use upstream moto
* update dependencies (fix #1066)
* fix error logging on startup (addresses #1046)
=> Release version 0.8.9; use upstream moto

README.md, localstack/constants.py, requirements.txt
* Addresses #1033 - Add kclpy to pip package
* Fixes #1073 (update badge links in README)
=> Add kclpy to pip dependencies

README.md, localstack/constants.py, localstack/ext/java/pom.xml, localstack/services/infra.py
=> Release v 0.1.16 of java libs

README.md, localstack/config.py, localstack/plugins.py, localstack/services/infra.py
Add support for STS. Fixes #975 
This also fixes support for serverless-localstack - the example here runs successfully with the changes in this PR: https://github.com/temyers/serverless-localstack
=> Add support for STS

README.md, localstack/constants.py, localstack/plugins.py, localstack/services/awslambda/lambda_executors.py, localstack/services/infra.py, localstack/services/install.py, localstack/services/stepfunctions/stepfunctions_starter.py, requirements.txt, tests/integration/test_cloudformation.py, tests/integration/test_lambda.py, tests/integration/test_stepfunction.py
Fixes #412 - Add initial support for AWS Step Functions.
=> Add initial support for AWS Step Functions

Dockerfile
Avoid surprises like
https://github.com/localstack/localstack/issues/1136
=> Move aws and awslocal to global install

Dockerfile, README.md, bin/docker-entrypoint.sh, bin/supervisord.conf, docker-compose.yml, localstack/plugins.py, localstack/services/awslambda/lambda_api.py, localstack/services/cloudformation/cloudformation_listener.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/services/infra.py, localstack/services/stepfunctions/stepfunctions_listener.py, localstack/utils/cloudformation/template_deployer.py
* Add IAM service stub
* Fix AttributeError in moto's CloudFormation describe_stack_resource
* Refactor/optimize Dockerfile
=> Add IAM and fix CloudFormation integration

README.md
Removed explicit cocker reference.
=> Change cocker to docker

localstack/ext/java/src/test/java/cloud/localstack/S3UploadTest.java
Issue is outlined in
https://github.com/localstack/localstack/issues/869
and
https://github.com/localstack/localstack/issues/538
(Specifically
https://github.com/localstack/localstack/issues/538#issuecomment-424379644)
One of the external symptoms of the bug is that S3 interactions for
objects that are only the null string (zero length objects) throw
an error like
`Client calculated content hash (contentMD5: 1B2M2Y8AsgTpgAmY7PhCfg== in base 64) didn't match hash (etag: ...`
which is telling because the `contentMD5` value is the base64 encoded
value for the md5 of null string. The correct etag value should be
`d41d8cd98f00b204e9800998ecf8427e`.
On multiple executions of the test case the etag generated by the S3
server is different so there is some non deterministic value being put
into …
=> Add failing test to show S3 md5 null string issue

.travis.yml, README.md, localstack/constants.py, localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerProperties.java, localstack/services/awslambda/lambda_api.py, localstack/services/infra.py
* Release version 0.9.0
* Add `DOCKER_FLAGS` config variable
* Update docs for Serverless integration
=> Release version 0.9.0

localstack/constants.py, localstack/ext/java/src/test/java/cloud/localstack/docker/ContainerTest.java
* Bump version in config
* Avoid pulling image if not necessary
=> Bump version; avoid pulling image if not necessary

Makefile, localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java, localstack/ext/java/src/main/java/cloud/localstack/Localstack.java, localstack/ext/java/src/main/java/cloud/localstack/TestUtils.java, localstack/ext/java/src/test/java/cloud/localstack/BasicFunctionalityTest.java, localstack/ext/java/src/test/java/cloud/localstack/LocalTestUtil.java, localstack/ext/java/src/test/java/cloud/localstack/sample/SQSLambdaHandler.java, localstack/ext/java/src/test/java/cloud/localstack/sample/SQSLambdaHandlerSSL.java, localstack/ext/java/src/test/resources/SqsEvent.json, localstack/services/sqs/sqs_listener.py
Add the ability for events triggered by SQS to be deserialized properly into SQSEvents before sending to the lambda.
=> Add SQS event deserializing for Lambda

localstack/services/awslambda/lambda_api.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/common.py
* Fix lambda response (make sure we return proper JSON or strings)
* Fix DynamoDB stream spec when creating streams using CloudFormation
=> Fix lambda response and CF DynamoDB stream spec

.travis.yml, README.md, localstack/plugins.py, localstack/services/awslambda/lambda_executors.py, localstack/services/infra.py, localstack/utils/aws/aws_stack.py, localstack/utils/common.py, requirements.txt, tests/integration/lambdas/lambda_integration.py, tests/integration/test_lambda.py
* Add initial support for CloudWatch Logs
* Extend Lambda API to forward invocation logs to CW Logs
* Add assertions to Lambda test to make sure the logs were actually extracted and forwarded
=> Add initial support for CloudWatch Logs

localstack/utils/aws/aws_stack.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/common.py
* fix a bug on Python versions where `str` class has no `encode` method
* make an HTTP call to determine whether a service is actually available
=> Fix str.encode for output capture

localstack/services/infra.py, localstack/services/s3/s3_listener.py, localstack/utils/common.py, tests/integration/test_s3.py
Addresses #398 - return correct location for S3 multipart uploads, including cases where `HOSTNAME_EXTERNAL` is specified.
=> Return correct location for S3 multipart uploads

localstack/services/infra.py, localstack/utils/common.py
Addresses #1119 - Fix using correct SSL cert
=> Fix using correct SSL cert

bin/localstack, localstack/services/install.py, localstack/services/sqs/sqs_starter.py, localstack/utils/cli.py, localstack/utils/common.py
* fix memory usage for Java processes, specifically Elasticsearch and SQS
* add CLI command to ssh/exec into the LocalStack container
=> fix memory usage for java processes

Dockerfile, Makefile, localstack/services/sns/sns_listener.py, localstack/services/sqs/sqs_listener.py, localstack/utils/aws/aws_stack.py, localstack/utils/common.py, localstack/utils/kinesis/kinesis_connector.py, requirements.txt, tests/integration/test_integration.py, tests/integration/test_sns.py
Addresses #1109 - Fix unicode encoding for SNS messages
=> Fix unicode encoding for SNS messages

.travis.yml, Makefile, bin/Dockerfile.base, bin/docker-entrypoint.sh, localstack/config.py, localstack/services/awslambda/lambda_executors.py, localstack/utils/kinesis/kinesis_connector.py, requirements.txt
Fix exposing LOCALSTACK_HOSTNAME
=> Fix exposing LOCALSTACK_HOSTNAME

localstack/ext/java/src/main/java/cloud/localstack/TestUtils.java, localstack/ext/java/src/test/java/cloud/localstack/SNSMessagingTest.java, localstack/ext/java/src/test/java/cloud/localstack/SQSMessagingTest.java, localstack/ext/java/src/test/java/cloud/localstack/utils/PromiseAsyncHandler.java
I added a few methods for async clients java api and a test for SNS too.
Not sure if I missed something, but, waiting for a feedback so I can improve this PR.
=> Added methods for async clients

.travis.yml, Makefile, README.md, localstack/config.py, localstack/services/awslambda/lambda_api.py, localstack/utils/aws/aws_stack.py, localstack/utils/common.py, localstack/utils/testutil.py, tests/integration/test_dynamodb.py, tests/integration/test_error_injection.py, tests/integration/test_integration.py, tests/integration/test_lambda.py
Enable request forwarding for non-existing Lambdas
=> Enable request forwarding for non-existing Lambdas

localstack/ext/java/src/main/java/cloud/localstack/DockerTestUtils.java, localstack/ext/java/src/main/java/cloud/localstack/Localstack.java, localstack/ext/java/src/main/java/cloud/localstack/ServiceName.java, localstack/ext/java/src/main/java/cloud/localstack/TestUtils.java, localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java
=> add StepFunctions client and endpoint configuration in utils

localstack/plugins.py, localstack/services/infra.py, localstack/services/s3/s3_listener.py, localstack/services/s3/s3_starter.py, tests/integration/test_s3.py
Addresses #1185 - fix large downloads for S3
=> Fix large downloads for S3

README.md, localstack/constants.py, localstack/services/generic_proxy.py, localstack/services/infra.py, localstack/services/kinesis/kinesis_listener.py
Addresses #346 - Add API endpoint for dynamically updating config variables
=> Add API endpoint for dynamically updating config variables

localstack/services/cloudformation/cloudformation_starter.py, localstack/services/s3/s3_listener.py, localstack/utils/aws/aws_stack.py, localstack/utils/cloudformation/template_deployer.py
* Fix CloudFormation update for ApiGateway::Method
* Fix LocationConstraint issue for S3 bucket creation
=> Fix CloudFormation update for ApiGateway::Method

localstack/services/generic_proxy.py, tests/integration/test_lambda.py
Should fix #954.  Fix closing of connection in proxy.
=> Fix closing of connection in proxy

README.md, localstack/constants.py, localstack/ext/java/pom.xml
* Release version `0.9.1`
* Update Java libs to version `0.1.19`
=> Release version 0.9.1

bin/Dockerfile.base
'8.201.08-r0' is not found. updated it.
=> fix: update java alpine version

localstack/services/awslambda/lambda_api.py, localstack/services/sqs/sqs_listener.py, tests/integration/test_sqs.py, tests/unit/test_sqs_listener.py
This fixes this issue: https://github.com/localstack/localstack/issues/1215
Python isn't my primary language, so I'm absolutely open to ways to make this better.  Additionally, I wasn't sure where a good place to put a test for this would be.  
=> Adds message attributes processing for Lambda functions triggered from SQS

localstack/services/awslambda/lambda_api.py, localstack/utils/aws/aws_models.py, localstack/utils/testutil.py, tests/unit/test_lambda.py
This is a fix for: [#1116](https://github.com/localstack/localstack/issues/1116)
add support for:
* list-tags
* tag-resource
* untag-resource
in lambda
=> add ListTags TagResource UntagResourc to Lambda

localstack/services/sns/sns_listener.py, tests/integration/test_sns.py, tests/unit/test_sns_listener.py
Hi again, this is the PR fixing : #1235 (refer to this for more context).
I tested this on my project and It works as expected.
=> Allow attributes to be preserved when calling Subscribe on SNS

localstack/dashboard/web/package.json
Update jquery to fix a potential security vulnerability reported by Github.
=> Update jquery to fix security vulnerability

Dockerfile, README.md, bin/Dockerfile.base, bin/supervisord.conf, localstack/constants.py, localstack/package.json, localstack/services/es/es_starter.py, localstack/services/infra.py, localstack/services/install.py, localstack/services/s3/s3_listener.py, localstack/utils/common.py
* update Docker image from Python 2 to 3
* run container process as non-root user
* should fix an issue where the Elasticsearch process failed to start up properly.
=> Update to Python 3 in Dockerfile

localstack/ext/java/src/main/java/cloud/localstack/docker/Container.java, localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerAnnotationProcessor.java, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerConfiguration.java, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerProperties.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/PullCommand.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/RunCommand.java, localstack/ext/java/src/test/java/cloud/localstack/docker/ContainerTest.java
=> Added optional imageTag annotation attribute

Dockerfile, README.md, localstack/constants.py, localstack/ext/java/pom.xml
Release v0.1.21 of Java libs, with latest changes from #1301
=> Release v0.1.21 of Java libs

Dockerfile, LICENSE.txt, Makefile, bin/localstack, bin/supervisord.conf, localstack/services/generic_proxy.py, localstack/services/infra.py
Fix permissions of docker.sock - related to #1306
=> fix permissions of docker.sock

bin/localstack, localstack/services/awslambda/lambda_executors.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/services/infra.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/test_lambda.py
* minor fix in CloudFormation ARNs and properties
* canonicalize API names when running in Docker
* set container name to `localstack_main`
* fix tests on master
=> Fix CloudFormation ARNs and properties

README.md, localstack/constants.py
=> Release version 0.9.4

README.md, localstack/constants.py, localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java, tests/integration/test_lambda.py
Supersedes #1255 . Preserve logic and existing test with uppercase event keys
=> [updated] Fix the key case so that it matches the event 

localstack/services/s3/s3_listener.py, tests/unit/test_s3.py
This commit adds a `Last-Modified` header on a S3Proxy response.
If the content has a XML with a `<LastModified>` field, it uses that field. Else, it uses currentDate.
I used this personally to fix an incompatibility with [minio-go](https://github.com/minio/minio-go) library, which requires a `Last-Modified` header ([api-get-object.go:626](https://github.com/minio/minio-go/blob/da91b3bbdca31aef023d51f3ac74cec0e02b23ac/api-get-object.go)), and fails if it is not set. 
As adding a header is an easy-fix and will not break anything, I followed that path.
It works for me, and I though it might be useful for someone else.
=> set Last-Modified header - s3 proxy

README.md
=> Improve documentation around @LocalstackDockerProperties

localstack/services/iam/iam_listener.py
Fix CreateDate returned by IAM - (partially) addresses #1366
=> Fix CreateDate returned by IAM

localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
Fix response body for presigned URL S3 PUT requests. Addresses #1317
=> Fix response body for presigned URL S3 PUT requests

Makefile, README.md, localstack/constants.py, localstack/ext/java/src/test/resources/SqsEvent.json, localstack/services/awslambda/lambda_api.py, localstack/services/cloudformation/cloudformation_listener.py, localstack/services/sns/sns_listener.py, localstack/utils/aws/aws_stack.py, localstack/utils/common.py
* Fix account IDs for cloudformation and SNS - addresses #1300
* Release v0.9.5
=> Fix account IDs for cloudformation and SNS

Makefile
Fix command to push Docker image
=> Fix command to push Docker image

Dockerfile, localstack/config.py
* fix Docker bridge IP configuration
* print a warning if we're not running in Docker but using Docker based LAMBDA_EXECUTOR (addresses #1359)
=> Fix Docker bridge IP configuration

localstack/constants.py, localstack/dashboard/infra.py, localstack/utils/analytics/event_publisher.py, localstack/utils/testutil.py, tests/integration/test_api_gateway.py, tests/integration/test_dynamodb.py, tests/integration/test_integration.py, tests/integration/test_lambda.py
Debug and fix failing build in CI.
https://travis-ci.org/localstack/localstack/builds/551967379?utm_source=github_status&utm_medium=notification
```
CalledProcessError: Command '{ test `which aws` || . .venv/bin/activate; }; aws --no-verify-ssl --endpoint-url="https://localhost:4574" lambda list-event-source-mappings --function-name test_lambda_env' returned non-zero exit status 139
```
=> Fix failing build in CI

README.md
First of all, thanks for making localstack happen. It's a great product, I use it on most of my projects.
It would greatly help the adoption of this project if developers have more visibility into each service. Managing the data in localstack is super useful for development.
Therefore, we build [Commandeer](https://getcommandeer.com) which works with localstack out of the box. Scanning for localstack is also a part of our onboarding.
This PR is just to start a conversation about a potential collaboration between Commandeer and Locastack. Let me know if you see more opportunities to collaborate.
=> Add some more UI clients to readme

localstack/services/kinesis/kinesis_listener.py
=> Kinesis throttling to return correct response code

localstack/services/apigateway/apigateway_listener.py, localstack/services/sns/sns_listener.py, localstack/services/stepfunctions/stepfunctions_listener.py, localstack/utils/analytics/event_publisher.py, localstack/utils/aws/aws_stack.py
* add API events
* only store events if API key has been specified
=> Add API events

README.md, localstack/config.py, localstack/dashboard/web/package.json, localstack/services/awslambda/lambda_executors.py, localstack/services/infra.py, localstack/services/s3/s3_listener.py
* Customize docker command
* Minor fix in S3 listener
=> Customize docker command

localstack/services/cloudformation/cloudformation_listener.py, localstack/utils/common.py, tests/integration/test_cloudformation.py
Fix CF describe-stack-events, add simple test.
=> Fix CF describe-stack-events

localstack/services/sns/sns_listener.py, tests/integration/test_sns.py
=> Implement basic tagging for SNS service

localstack/config.py, localstack/services/awslambda/lambda_api.py, localstack/utils/aws/aws_models.py, localstack/utils/common.py
* Minor fixes to lambda executor
* Change default executor from `local` to `docker` (as specified in the docs)
=> Minor fixes to lambda executor

localstack/dashboard/api.py
Quick grammar fix for the `localstack web` command - adding a missing word here.
=> localstack web - quick grammar fix

localstack/constants.py, localstack/services/install.py, localstack/utils/bootstrap.py, requirements.txt, setup.py
=> Minor patch in install script

localstack/services/kinesis/kinesis_listener.py
=> kinesis: check if 'Records' is present

localstack/services/awslambda/lambda_executors.py, localstack/services/generic_proxy.py, requirements.txt
Attempting to fix logging for asynchronous lambdas, based on #1424 
This supersedes the previous PR #1424 by @trestini - we'll make sure to preserve that commit when merging.
=> Fix logging issue with lambda asynchronous calls

localstack/services/dynamodb/dynamodb_listener.py
Without this, KCLv1 for java throws exceptions.
=> dynamodb: respond with proper error messages

Makefile, localstack/utils/cloudformation/template_deployer.py, requirements.txt, tests/integration/templates/template1.yaml, tests/integration/test_cloudformation.py
Add basic support for Ref in cloudformation templates
=> Add basic support for Ref in cloudformation templates

README.md, localstack/constants.py, localstack/services/infra.py, localstack/utils/common.py, localstack/utils/server/multiserver.py, requirements.txt
=> Cache API server processes

localstack/utils/bootstrap.py, localstack/utils/common.py
=> Fix permissions for cache files

Dockerfile, localstack/services/sns/sns_listener.py, localstack/utils/common.py, requirements.txt
=> Add OS version checks

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/aws/aws_stack.py, localstack/utils/server/multiserver.py
Fix incorrect region for API GW resources created via Cloud Formation
=> Fix incorrect region for API GW resources created via CF

localstack/services/apigateway/apigateway_listener.py, localstack/services/awslambda/lambda_api.py, localstack/services/awslambda/lambda_executors.py, localstack/utils/aws/aws_responses.py, localstack/utils/aws/aws_stack.py, localstack/utils/bootstrap.py, localstack/utils/cloudformation/template_deployer.py
* refactor Lambda API
* minor extensions to CloudFormation impl
=> Refactor Lambda API

localstack/ext/java/pom.xml
=> maven-compiler-plugin 3.8.1

localstack/ext/java/pom.xml
=> AWS SDK 1.11.615

.travis.yml, README.md, localstack/services/awslambda/lambda_api.py, localstack/utils/common.py, tests/integration/test_lambda.py
Add test for uploading Java Lambda as JAR in ZIP
Fixes #385
=> Fix uploading of Java Lambda as JAR in ZIP

localstack/services/cloudformation/cloudformation_starter.py, localstack/services/cloudformation/service_models.py, localstack/utils/aws/aws_stack.py, localstack/utils/cloudformation/template_deployer.py
Fix CloudFormation deployment of StepFunction activities
Fixes #1435
=> Fix CloudFormation deployment of StepFunction activities

localstack/services/apigateway/apigateway_listener.py, localstack/services/cloudformation/cloudformation_starter.py
Fix dynamodb table ARN for cloudformation
Addresses #438
=> Fix dynamodb table ARN for cloudformation

bin/Dockerfile.base, localstack/config.py, localstack/services/awslambda/lambda_api.py
Fix lambda deployment in CloudFormation - addresses #1477
=> Fix lambda deployment in cloudformation

README.md, localstack/config.py, localstack/utils/bootstrap.py
Make service port number configurable via env vars.
=> Make service port number configurable via env vars

localstack/utils/bootstrap.py, localstack/utils/cli.py
=> Fix shell cli command

localstack/utils/bootstrap.py, localstack/utils/cli.py, localstack/utils/common.py, tests/integration/test_lambda.py
* Refactor utils to make run() available in bootstrap
* Fix docker shell access
=> Refactor utils and fix docker shell access

localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
As found in #538, when there is an S3 copy the MD5 header should not be checked. With this change was able to use `s3a` with Localstack otherwise fails to copy file during writing.
For reference here is the standalone test project: https://github.com/risdenk/s3a-localstack
=> S3 skip checking MD5 on copy

localstack/constants.py, localstack/services/infra.py, localstack/services/install.py, localstack/utils/cloudformation/template_deployer.py
* Exclude `ingest-geoip` ES module to optimize size
* Minor refactorings
=> Exclude ingest-geoip ES module to optimize image size

localstack/services/dynamodb/dynamodb_listener.py
This PR will fix the response for dynamodbstreams request as described in the issue.
=> fix stream arn in dynamodb streams response (#1513)

localstack/services/cloudformation/cloudformation_starter.py, localstack/services/generic_proxy.py, localstack/services/infra.py, localstack/utils/common.py
Allow proxy listener to define custom backend per request
=> Allow proxy listener to define custom backend per request

localstack/services/sqs/sqs_listener.py, requirements.txt, tests/integration/test_sqs.py
Support custom SQS queue attributes.
Fixes #804
=> Support custom SQS queue attributes

localstack/dashboard/web/index.html, localstack/dashboard/web/views/infra.graph.js
Fix rendering of resources in web UI
Fixes #1392
=> Fix rendering of resources in web UI

localstack/services/awslambda/lambda_api.py, localstack/services/s3/s3_listener.py
Add mock responses for S3 encryption and replication
=> Add mock responses for S3 encryption and replication

localstack/config.py, localstack/dashboard/api.py, localstack/services/infra.py, localstack/utils/bootstrap.py, localstack/utils/server/multiserver.py
* Add API for service status
* Allow starting services at runtime
=> Add API for service status; allow starting services at runtime

localstack/config.py, localstack/constants.py, localstack/dashboard/infra.py, localstack/services/apigateway/helpers.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/services/dynamodb/dynamodb_listener.py, localstack/services/es/es_api.py, localstack/services/infra.py, localstack/services/s3/s3_listener.py, localstack/services/stepfunctions/stepfunctions_starter.py, localstack/utils/aws/aws_stack.py, localstack/utils/bootstrap.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/kinesis/kclipy_helper.py, localstack/utils/kinesis/kinesis_connector.py, localstack/utils/testutil.py, tests/integration/test_api_gateway.py
Allow specifying data types for CF attributes.
=> Allow specifying data types for CF attributes

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py
Fix ARN when looking up cloudformation resources.
Should fix #1416
=> Fix ARN when looking up cloudformation resources

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/common.py
* Allow specifying functions for CF resource params
* Make `boto_client` parameter optional in CF
=> Allow specifying functions for CF resource params

localstack/services/cloudformation/cloudformation_starter.py, localstack/services/infra.py, tests/integration/templates/template2.yaml, tests/integration/test_cloudformation.py
Fix SQS queue physical ID in CloudFormation.
Should fix #1535
=> Fix SQS queue physical ID in CloudFormation

Makefile, localstack/config.py, localstack/services/awslambda/lambda_executors.py, localstack/services/generic_proxy.py, localstack/utils/testutil.py, requirements.txt
* Fix Lambda docker command and imports
* Replace `subprocess32-ext` with `subprocess32`
=> Fix Lambda docker command and imports

README.md, localstack/constants.py, localstack/utils/cloudformation/template_deployer.py
* release v0.10.3
* minor fix for CF boolean values
=> Release v0.10.3; fix CF boolean values

Makefile, localstack/config.py, localstack/dashboard/api.py, localstack/dashboard/infra.py, localstack/services/infra.py, localstack/utils/bootstrap.py, localstack/utils/common.py, localstack/utils/server/multiserver.py
* Expose Web UI via SSL
* Add CORS config to moto server
=> Expose Web UI via SSL

localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
This adds support for signed requests that include response header overrides.
Fixes #1203
=> Honor signed header requests

localstack/services/dynamodbstreams/dynamodbstreams_api.py
=> fix crash while requesting describe-stream (#1588)

localstack/config.py, localstack/constants.py, localstack/services/dynamodb/dynamodb_listener.py, localstack/services/dynamodbstreams/dynamodbstreams_api.py, localstack/services/s3/s3_listener.py, localstack/utils/bootstrap.py, localstack/utils/common.py, requirements.txt, tests/integration/test_lambda.py, tests/integration/test_s3.py
* Add checks for open UDP ports
* Fix S3 chunked encoding uploads (addresses #1571)
=> Add checks for open UDP ports; fix S3 chunked encoding uploads

Makefile, localstack/ext/java/pom.xml, localstack/ext/java/src/main/java/cloud/localstack/Localstack.java, localstack/ext/java/src/main/java/cloud/localstack/TestUtils.java, localstack/ext/java/src/main/java/cloud/localstack/docker/Container.java, localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java, localstack/ext/java/src/test/java/cloud/localstack/BasicFunctionalityTest.java, localstack/ext/java/src/test/java/cloud/localstack/LocalTestUtil.java, localstack/services/awslambda/lambda_api.py, localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
* fix s3 upload signature (addresses #1611)
* fix Java tests
=> Fix s3 upload signature; fix Java tests

localstack/config.py
Fixes issue https://github.com/localstack/localstack/issues/1609
=> Restore the MAC TMP folder setup location

localstack/ext/java/pom.xml
=> JUnit 5.5.2

bin/Dockerfile.base
=> Maven 3.6.2

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/common.py
* fix S3 location constraint for CF (fixes #1622)
* fix CF `StreamArn` attribute (fixes #1620)
=> Fix S3 location constraint for CF; fix CF StreamArn attribute

bin/localstack.bat, localstack/constants.py, localstack/services/infra.py, localstack/utils/bootstrap.py, localstack/utils/common.py, setup.py
Add bat script and support running under Windows
=> Add bat script and support running under Windows

localstack/services/cloudformation/cloudformation_listener.py, localstack/services/install.py
minor fix required for installation of plugins (setting `LOCALSTACK_INFRA_PROCESS` env variable when installing dependencies)
=> minor: Fix installation of plugins

localstack/services/generic_proxy.py, localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
=> Support presigned URL upload notifications and another CORS header

localstack/utils/bootstrap.py, localstack/utils/cli.py, localstack/utils/common.py, requirements.txt
Add util method to get Docker container names
=> Add util method to get Docker container names

localstack/services/awslambda/lambda_executors.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py
* fix cloudformation deployment of Lambdas (enable Stack update/delete operations)
* make creation of Lambdas log groups resilient to "already exists" errors (should fix #1642)
=> Fix cloudformation deployment and log groups for Lambdas

localstack/services/apigateway/apigateway_listener.py, localstack/utils/bootstrap.py
* Minor refactoring to extract API GW invocation into separate function
* Fix pip installation which currently breaks CI builds
=> Extract API GW invocation into separate function

localstack/services/sns/sns_listener.py, tests/unit/test_sns_listener.py
Fixes https://github.com/localstack/localstack/issues/933
=> SNS: Only create one subscription per topic per endpoint

localstack/services/apigateway/apigateway_listener.py, localstack/services/apigateway/helpers.py, localstack/utils/aws/aws_responses.py
Refactor util functions for response mappings
=> Refactor util functions for response mappings

localstack/constants.py, localstack/ext/java/src/test/java/cloud/localstack/SQSMessagingTest.java
Fix: https://github.com/localstack/localstack/issues/1619
See: https://github.com/softwaremill/elasticmq/pull/294
=> Use elasticmq 0.15.2 to support that include message that has multi-byte characters in the attributes

localstack/services/awslambda/lambda_api.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/services/cloudformation/service_models.py, localstack/utils/aws/aws_stack.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/common.py, tests/integration/templates/template1.yaml, tests/integration/test_cloudformation.py
* add CF support for SNS subscriptions (fixes #1191)
* fix CF parsing of `!Ref` and `!GetAtt`
=> Add CF support for SNS subscriptions

bin/Dockerfile.base, localstack/constants.py, localstack/dashboard/web/css/style.css, localstack/dashboard/web/index.html, localstack/dashboard/web/views/infra.html, localstack/services/cloudformation/cloudformation_starter.py, localstack/services/install.py, localstack/utils/cloudformation/template_deployer.py
* Fix DynamoDB local libs (currently breaking builds on `master`)
* Minor update to dashboard - add deprecation notice
* Small fix in CloudFormation update for Lambda function code
=> Fix DynamoDB local libs

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py
Minor fix in CF deployment - was breaking Serverless lambda deployment
=> Minor fix in CF deployment

bin/Dockerfile.base, localstack/services/install.py
Disable forced reinstallation of DDB libs - install in base Docker image instead.
=> Disable forced reinstallation of DDB libs

localstack/services/generic_proxy.py, localstack/services/sns/sns_listener.py, tests/integration/test_lambda.py, tests/integration/test_sns.py, tests/unit/test_sns_listener.py
=> Send SNS confirmation message for HTTP(S) subscriptions

localstack/services/s3/s3_listener.py, localstack/services/sns/sns_listener.py, tests/integration/test_sns.py
* Fix SNS x-amz-sns-message-type (fixes #881)
* Fix S3 content type (fixes #854)
=> Fix SNS x-amz-sns-message-type; fix S3 content type

.travis.yml, localstack/services/awslambda/lambda_api.py, localstack/services/s3/s3_listener.py, localstack/utils/aws/aws_stack.py
* fix mapping of Lambda versions and ARNs for different regions
* make S3 doctype comparison case insensitive - fix #854
=> Fix mapping of Lambda versions and ARNs

.travis.yml, localstack/utils/cloudformation/template_deployer.py
* Add CF support for Events::Rule
* Fix hanging tests in Travis-CI
=> Add CF support for Events::Rule

localstack/utils/cloudformation/template_deployer.py, requirements.txt, tests/integration/test_lambda.py
* fix regression with CF resource creation - fixes #1677, fixes #1682
* add simple test for lambda env vars - fixes #681
=> Fix regression with CF resource creation

localstack/services/generic_proxy.py, localstack/utils/common.py
* Fix duplicate CORS headers (fixes #1612)
* Fix passing of path in `recurse_object` util function
=> Fix duplicate CORS headers

localstack/services/apigateway/apigateway_listener.py, localstack/services/awslambda/lambda_executors.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/services/cloudformation/service_models.py, localstack/services/generic_proxy.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/templates/template1.yaml, tests/integration/test_cloudformation.py
* Add CloudFormation support for `ApiGateway::GatewayResponse` (fixes #1675)
* Fix error handling on duplicate creation of log groups (should fix #1686)
=> add CloudFormation support for ApiGateway::GatewayResponse

localstack/services/awslambda/lambda_api.py, localstack/services/iam/iam_listener.py, tests/integration/test_lambda.py
Support adding lambda policies - fixes #1260
=> Support adding lambda policies

localstack/services/awslambda/lambda_executors.py, localstack/services/cloudformation/cloudformation_starter.py, requirements.txt
* Fix default region for CF
* Fix error in Lambda log creation
=> Fix default region for CF; fix error in Lambda log creation

localstack/services/cloudformation/cloudformation_starter.py
Avoid duplicate resource creation in CloudFormation
=> Avoid duplicate resource creation in CloudFormation

localstack/services/cloudformation/cloudformation_starter.py
Fix CF Lambda SQS event source mapping - should fix #1288
=> Fix CF Lambda SQS event source mapping

localstack/services/s3/s3_starter.py, tests/integration/test_s3.py
This reproduces #1629. Maybe I'll go and try fixing it myself, but anyone is welcome to have a pop...
=> Fix #1629: Increase maximum file size for S3 to 2GB

tests/integration/test_sqs.py
Add simple test for SQS dead letter queue
=> Add simple test for SQS dead letter queue

localstack/services/cloudformation/cloudformation_starter.py, tests/integration/test_cloudformation.py
Skip CF deployment if resource already exists - fix #1700
=> Skip CF deployment if resource already exists

localstack/plugins.py, localstack/services/awslambda/lambda_api.py, localstack/services/iam/iam_starter.py, localstack/services/infra.py, tests/integration/test_lambda.py
Add API to remove lambda permissions - should fix #1707
=> Add API to remove lambda permissions

localstack/services/awslambda/lambda_api.py, localstack/services/stepfunctions/stepfunctions_listener.py, localstack/utils/testutil.py, tests/integration/test_lambda.py
Fix lookup of Python Lambda handler in sub directories.
=> Fix lookup of Python Lambda handler in sub directories

localstack/services/awslambda/lambda_executors.py
Added mount flags if DOCKER_REMOTE="false" for LAMBDA_EXECUTOR="docker-reuse" to prevent expensive copying on each invocation
=> Allow docker-reuse to mount volumes

localstack/services/s3/s3_listener.py, tests/integration/test_notifications.py
Fix S3 notifications to support multiple QueueConfigurations - fixes #450
=> Fix S3 notifications to support multiple QueueConfigurations

localstack/services/s3/s3_listener.py, localstack/utils/bootstrap.py
Fix notification triggers on S3 presigned URL upload - should fix #1668
=> Fix notification triggers on S3 presigned URL upload

localstack/services/awslambda/lambda_api.py, tests/integration/test_lambda.py
* Fix return type of Lambda GetPolicy - fixes #1717
* Return valid response in update_function_configuration - fixes #1710
=> Fix return type of Lambda GetPolicy

localstack/utils/common.py, tests/integration/test_sqs.py
* Add test case for deleting SQS messages - addresses #468
* Set self-signed certificate CN to `localhost` - addresses #451
=> Add test case for deleting SQS messages

localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
Fix passing of metadata on S3 presigned URL put - addresses #544
=> Fix passing of metadata on S3 presigned URL put

localstack/package.json, localstack/services/kinesis/kinesis_listener.py, tests/integration/test_kclpy.py, tests/unit/test_kinesis.py
Fixes #1553
Uses kinesalite `3.2.0` with implemented `DescribeStreamSummary` method
=> Use DescribeStreamSummary from kinesalite

localstack/services/dynamodb/dynamodb_listener.py, localstack/services/s3/s3_starter.py, localstack/utils/aws/aws_stack.py
Fix ACL for multi-part uploads - fixes #1733
=> Fix ACL for multi-part uploads

Dockerfile
=> Update PYTHONPATH for Python 3.7

localstack/services/apigateway/apigateway_listener.py, localstack/services/es/es_starter.py, localstack/services/kinesis/kinesis_listener.py, localstack/services/sns/sns_listener.py, tests/integration/test_api_gateway.py, tests/integration/test_sns.py, tests/unit/test_sns_listener.py
* Fix SNS FilterPolicy configuration - fixes #684
* Add kinesis/ListStreams API gateway integration - fixes #666
* Don't delete ES data if DATA_DIR is configured
=> Fix SNS FilterPolicy configuration; add kinesis/ListStreams API Gateway integration

localstack/services/cloudformation/cloudformation_listener.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/common.py, requirements.txt, tests/integration/test_cloudformation.py
Add SAM transformer to support cloudformation deployment for SAM resource. Should fix #632
=> Add SAM transformer to support cloudformation deployment for SAM resource

localstack/config.py
Populate env variable names `CONFIG_ENV_VARS` in `populate_configs` function in config.py
=> Populate env variable names in config

localstack/services/awslambda/lambda_executors.py, localstack/services/dynamodb/dynamodb_listener.py, localstack/utils/common.py, requirements.txt
* Fix DynamoDB error for Put on non-existing table - should fix #789
* Add `requests` as basic lib - should fix #1761
* Fix UTC timestamps
* Fix Lambda dotnetcore execution issues related to recent changes in lambci: https://github.com/lambci/docker-lambda/pull/218
=> Fix DynamoDB error for Put on non-existing table; fix Lambda dotnetcore execution

localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java
Dockerfile has been updated to python 3.7 under commit https://github.com/localstack/localstack/commit/5d492fcab14e57b70a12195fce5edae49562531b
=> Updated python path to 3.7 to match Dockerfile

README.md, localstack/services/apigateway/apigateway_listener.py, localstack/services/infra.py, localstack/utils/common.py, tests/integration/test_api_gateway.py
* fix permission issue for cert files - addresses #1743
* fix non-JSON content types for API gateway - addresses #871
* add priority flag to support plugin overriding
=> Fix permission issue for cert files; fix non-JSON content types for API Gateway

localstack/services/dynamodb/dynamodb_listener.py
Fix DYNAMODB_ERROR_PROBABILITY error injection - fixes #849
=> Fix DYNAMODB_ERROR_PROBABILITY error injection

localstack/services/awslambda/lambda_executors.py, localstack/services/cloudformation/cloudformation_listener.py, requirements.txt
Minor fixes
* Print stdout for Lambda errors - fixes #816
* Clean up dependencies in `requirements.txt`
=> Minor fixes

localstack/plugins.py, localstack/services/s3/s3_listener.py, localstack/services/sqs/sqs_listener.py, localstack/services/sqs/sqs_starter.py, tests/integration/lambdas/lambda_integration.py, tests/integration/test_lambda.py, tests/integration/test_notifications.py, tests/integration/test_s3.py
* fix S3 bucket name validation - addresses #998
* fix SQS startup health check - addresses #966
=> Fix S3 bucket name validation; fix SQS startup health check

localstack/config.py, localstack/services/generic_proxy.py, localstack/services/s3/s3_listener.py, localstack/services/sns/sns_listener.py, tests/integration/test_s3.py
Auto-convert uppercase characters in bucket names. Addresses https://github.com/localstack/serverless-localstack/issues/58
=> Auto-convert uppercase characters in bucket names

localstack/services/s3/s3_listener.py, localstack/services/s3/s3_starter.py, tests/integration/test_s3.py
* Fix object ACLs for multipart uploads - fixes #1170
* Avoid modifying XML files stored in S3 - fixes #1037
=> Fix object ACLs for multipart uploads

localstack/config.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py
* Minor fix for CF deployment of step functions
* Fix DOCKER_HOST_FROM_CONTAINER configuration when running locally, outside of Docker
* Fix issue with CF `describe_stack_events`
=> Minor fix for CF deployment of step functions

.travis.yml, localstack/services/generic_proxy.py, tests/unit/test_kinesis.py, tests/unit/test_misc.py
Enhance proxy to transparently accept both HTTP/HTTPS - addresses #1245
=> Enhance proxy to transparently accept both HTTP/HTTPS

localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
Fix S3 bucket name checks (and improve error reporting) for domain based addressing - see #1292
=> Fix S3 bucket name checks for domain based addressing

localstack/utils/common.py
=> Fix check for Alpine Linux

localstack/services/apigateway/apigateway_listener.py, localstack/services/apigateway/helpers.py, localstack/utils/aws/aws_stack.py, tests/integration/templates/template1.yaml, tests/integration/test_cloudformation.py
* Fix API to retrieve list of API Gateway authorizers 
* Add test for stack name in CloudFormation resource names
=> Add test for stack name in cloudformation resource names

localstack/services/awslambda/lambda_api.py, tests/unit/test_lambda.py
* Add missing Lambdas attribute to fix terraform deployment - should fix #1822
=> Fix terraform deployment for Lambdas

localstack/utils/common.py
Update certificate generation to satisfy new requirements in MacOS Catalina - see https://support.apple.com/en-us/HT210176
=> Update certificate generation to new requirements in MacOS Catalina

README.md, localstack/config.py, localstack/services/awslambda/lambda_api.py, localstack/services/awslambda/lambda_executors.py, localstack/services/s3/s3_listener.py, tests/integration/lambdas/lambda_environment.py, tests/integration/test_stepfunction.py
* Add LAMBDA_REMOVE_CONTAINERS config - fixes #1851
* Enhance StepFunctions tests - addresses #1854
=> Add LAMBDA_REMOVE_CONTAINERS config; enhance StepFunctions tests

localstack/services/s3/s3_listener.py, localstack/utils/aws/aws_stack.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/testutil.py, tests/integration/templates/template1.yaml
Minor fixes for CF, S3, and test utils
=> Minor fixes for CF, S3, and test utils

localstack/services/apigateway/apigateway_listener.py, localstack/utils/persistence.py
Minor fixes in persistence file creation logic - default to `create=True` when getting the path to the persistence file.
=> Minor fixes in persistence file creation logic

localstack/services/cloudformation/cloudformation_starter.py, localstack/services/sns/sns_listener.py, tests/integration/templates/template1.yaml, tests/integration/test_cloudformation.py
* Fix tags on SNS topic creation
* Support CloudFormation `Fn::GetAtt` for Arn prop for S3 buckets - fixes #1549
=> Fix tags on SNS topic creation; fix CloudFormation Arn prop for S3 buckets

localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
Fix content type for S3 Range requests - fixes #1259
=> Fix content type for S3 Range requests

localstack/services/cloudformation/cloudformation_listener.py
Fix status code checks for S3 TemplateURLs - #1884
=> Fix status code checks for S3 TemplateURLs

localstack/services/awslambda/lambda_api.py, localstack/services/awslambda/lambda_executors.py, localstack/services/sqs/sqs_listener.py, localstack/utils/aws/aws_models.py, localstack/utils/aws/dead_letter_queue.py, localstack/utils/testutil.py, tests/integration/lambdas/lambda_integration.py, tests/integration/test_api_gateway.py, tests/integration/test_lambda.py, tests/integration/test_sqs.py
Support dead letter queues for Lambdas and SQS queues - fixes #988, fixes #1886
=> Support dead letter queues for Lambdas and SQS queues

localstack/ext/java/src/test/java/cloud/localstack/S3FeaturesTest.java, localstack/services/dynamodb/dynamodb_listener.py
* Fix routes for DynamoDB shell - fixes #1803
* Add Java test for S3 presigned object upload - fixes #1396
=> Fix routes for DynamoDB shell; add Java test for S3 presigned object upload

localstack/ext/java/src/main/java/cloud/localstack/docker/DockerExe.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/PullCommand.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/RunCommand.java
Increase Java docker timeout for image pulls - fixes #1456
=> Increase Java docker timeout for image pulls

Makefile, requirements.txt
* Remove dev dependencies from prod package - fixes #1323
=> Remove dev dependencies from pip package

localstack/services/sns/sns_listener.py
=> Added more SNS related headers

localstack/services/cloudformation/cloudformation_starter.py
Return CF stack events for deleted stacks - should fix https://github.com/localstack/serverless-localstack/issues/35
=> Return CF stack events for deleted stacks

localstack/services/sqs/sqs_listener.py, localstack/utils/aws/aws_stack.py, tests/integration/test_sqs.py
* Add simple test for SQS change_message_visibility - addresses #1902
* Fix position of code snippets that implement TagQueue/ListQueueTags
=> Add test for SQS change_message_visibility

.gitignore, localstack/package.json, localstack/services/events/events_listener.py, localstack/services/install.py, localstack/utils/common.py, localstack/utils/tagging.py, tests/integration/test_events.py, tests/unit/test_tagging.py, tests/unit/utils/test_tagging.py
adds localstack.utils.TaggingService, implements TaggingService for CloudWatch Events
=> adds tagging support for events (closes #1907)

localstack/services/stepfunctions/stepfunctions_starter.py, localstack/utils/common.py
Extract command to start SFN into separate function.
=> Extract command to start SFN into separate function

localstack/services/firehose/firehose_api.py, localstack/utils/testutil.py, tests/integration/test_integration.py
Fix S3 path layout for Firehose streams - fixes #1554
=> Fix S3 path layout for Firehose streams

localstack/services/cloudformation/cloudformation_starter.py, localstack/services/cloudformation/service_models.py, localstack/services/es/es_starter.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/test_cloudformation.py
Add support for nested CloudFormation stacks - fixes #1566
=> Add support for nested CloudFormation stacks

localstack/services/awslambda/lambda_executors.py, localstack/utils/aws/aws_stack.py, localstack/utils/cloudwatch/cloudwatch_util.py, localstack/utils/common.py
* Refactor util function for storing CloudWatch logs - create a reusable `store_cloudwatch_logs` function
* Create simple `Boto3Session` class that wraps boto3 sessions with local endpoint URLs
=> Refactor util function for storing CloudWatch logs

localstack/ext/java/src/test/java/cloud/localstack/sample/S3Sample.java, localstack/services/generic_proxy.py
Fix detection of absolute URLs in proxy paths
=> Fix detection of absolute URLs in proxy paths

localstack/services/generic_proxy.py
=> Fix regression in proxy path url handling

localstack/services/awslambda/lambda_executors.py, localstack/utils/common.py
* Fix Lambda Docker image for Python 3.8
* Fix overwrite flag for unzip function
=> Fix Lambda Docker image for Python 3.8; fix unzip overwrite flag

localstack/ext/java/src/main/java/cloud/localstack/docker/Container.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/ListImagesCommand.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/PullCommand.java
Pull non-existing Docker image from JUnit runner - fixes #1599 .
=> Pull non-existing Docker image from JUnit runner

localstack/ext/java/src/main/java/cloud/localstack/Localstack.java, localstack/ext/java/src/main/java/cloud/localstack/docker/Container.java, localstack/ext/java/src/main/java/cloud/localstack/docker/DockerExe.java, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerAnnotationProcessor.java, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerConfiguration.java, localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerProperties.java, localstack/ext/java/src/main/java/cloud/localstack/docker/command/RunCommand.java, localstack/ext/java/src/test/java/cloud/localstack/SQSMessagingTest.java, localstack/services/awslambda/lambda_executors.py, tests/integration/test_sqs.py
* Add `ignoreDockerRunErrors` attribute to `@LocalstackDockerProperties`, which allows to run the tests with an already running Docker container.
* Add test for SQS message attributes - addresses #1857
=> Add ignoreDockerRunErrors JUnit Docker attribute; add test for SQS msg attrs

localstack/utils/cloudformation/template_deployer.py, tests/integration/templates/template1.yaml, tests/integration/test_cloudformation.py
Fix creation of SNS subscription attributes via CloudFormation - fixes #1829
=> Fix creation of SNS subscription attributes via CloudFormation

localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
Fix underscores in S3 object metadata keys - fixes #1790
=> Fix underscores in S3 object metadata keys

localstack/services/cloudformation/cloudformation_starter.py
Include latest Lambda regions from boto3 - fixes #1961
=> Include latest Lambda regions from boto3

localstack/services/s3/s3_listener.py, localstack/services/s3/s3_starter.py, tests/integration/test_s3.py
Fix forward URL prototol for S3 proxy; add test for S3 range header - should fix #1952
=> fix forward URL prototol for S3 proxy; add test for S3 range header

localstack/services/awslambda/lambda_api.py, localstack/services/awslambda/lambda_executors.py
Fix classpath and configurations for Java 11 Lambdas - fixes #1985, fixes #1979
=> Fix classpath and configurations for Java 11 Lambdas

localstack/ext/java/src/test/java/cloud/localstack/S3FeaturesTest.java, localstack/services/s3/s3_listener.py, localstack/utils/cloudformation/template_deployer.py
Fix S3 ETag hashes for multipart uploads - fixes #1978
=> Fix S3 ETag hashes for multipart uploads

README.md, docker-compose.yml
=> Minor updates to the documentation to included all services in the docker-compose configuration

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py
Fix CloudFormation resource dependency resolution - should fix #1909
=> Fix CloudFormation resource dependency resolution

localstack/constants.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/common.py, requirements.txt
* resolve CloudFormation attributes starting with lower case
* bump moto version
* ensure `dependencies` is a list when resolving CF resource dependencies
=> Minor: resolve CloudFormation attributes starting with lower case

localstack/config.py, localstack/services/es/es_api.py, localstack/services/generic_proxy.py, localstack/services/infra.py, localstack/services/s3/s3_listener.py, localstack/utils/bootstrap.py, localstack/utils/persistence.py
* Refactor persistence logic
* Use single file for persistence
* Add `response` to list of arguments for persisting API calls
=> Refactor persistence logic; use single file for persistence

localstack/constants.py
Hi,
Now that the PR https://github.com/softwaremill/elasticmq/pull/333 is merged, a new version of ElasticMQ is available fixing an issue with tagging on SQS queue creation.
This PR change the version.
Thanks
=> Update elasticmq in order to fix sqs tag on creation

localstack/services/generic_proxy.py, localstack/services/s3/s3_listener.py, localstack/services/sqs/sqs_listener.py
Fix regex for replacement of S3 ETag hashes - fixes #2015
=> Fix regex for replacement of S3 ETag hashes

Makefile
=> Add windows support to the MakeFile

localstack/utils/cloudformation/template_deployer.py
Fix resolution of CloudFormation stack parameters
=> Fix resolution of CF stack parameters

localstack/services/sns/sns_listener.py, tests/integration/test_sns.py
=> #1939 tag listing updated to remove duplicate tags

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py
* Fix CloudFormation dependency resolution loop
* Run CloudFormation deployment in background and update stack status accordingly
=> Fix CloudFormation dependency resolution loop; async stack deployment

localstack/services/cloudformation/cloudformation_starter.py, tests/integration/templates/template2.yaml, tests/integration/test_cloudformation.py
Add ExportName to CloudFormation stack outputs - fixes #1408
=> Add ExportName to CloudFormation stack outputs

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/common.py, tests/integration/test_cloudformation.py
Fix CloudFormation support for IAM::Role
=> Fix CloudFormation support for IAM::Role

localstack/services/sns/sns_listener.py, localstack/utils/aws/aws_responses.py, localstack/utils/bootstrap.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/persistence.py, localstack/utils/server/multiserver.py
* Remove None strings from SNS results
* Refactor resolution of CF resource name placeholders
=> Remove None strings from SNS results; refactor resolution of CF resource name placeholders

localstack/services/cloudformation/cloudformation_starter.py, localstack/services/es/es_api.py, localstack/services/firehose/firehose_api.py
* Fix persistence for ES API
* Fix kwargs for `update_destination` - fixes #2020
=> Fix persistence for ES API, fix kwargs for update_destination

Makefile, localstack/services/cloudformation/cloudformation_starter.py
* Patch Kinesis Stream get_cfn_attribute(..) method in moto
=> Fix kinesis steam get cfn attribute

localstack/ext/java/pom.xml
=> testcontainers 1.12.5

bin/Dockerfile.base, localstack/services/cloudformation/cloudformation_listener.py, requirements.txt
minor: fix base image maven version and add sasl libs
=> minor: fix base image maven version and add sasl libs

Makefile, localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
=> Fix s3 notification event object size

localstack/services/dynamodb/dynamodb_listener.py
* I found that ConsumedCapacity already returned by our DynamoDB Local
* Just a small update to cover Query action
=> Fix issue #1108

README.md, localstack/dashboard/api.py, localstack/plugins.py, localstack/services/es/es_api.py, localstack/services/infra.py, localstack/services/plugins.py, localstack/utils/bootstrap.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/common.py, tests/unit/test_misc.py
* Add basic /health check endpoint - addresses #2072 
* Fix parsing of `Version` date string in CloudFormation - fixes #2022
=> Add basic /health check endpoint

localstack/services/firehose/firehose_api.py, localstack/services/sqs/sqs_listener.py, tests/integration/test_sqs.py
=> Sqs max receive count

localstack/services/cloudformation/cloudformation_starter.py
Update exports on CF stack update - should fix #2041
=> Update exports on CF stack update

localstack/services/awslambda/lambda_api.py, localstack/services/awslambda/lambda_executors.py, tests/integration/test_lambda.py
Fix handler lookup for "provided" Lambda runtime - addresses #1848
=> Fix handler lookup for "provided" Lambda runtime

localstack/services/cloudformation/cloudformation_listener.py, localstack/services/dynamodb/dynamodb_listener.py
* Fix returned attributes on ReturnValues=ALL_OLD for DynamoDB PutItem - addresses #2049
* Fix CreationTime for CloudFormation stacks - fixes #2099
=> Fix returned attributes on ReturnValues=ALL_OLD for DynamoDB PutItem

localstack/services/awslambda/lambda_executors.py, localstack/utils/cloudformation/template_deployer.py
* Configure nodejs Lambdas to skip SSL verification
* Add CloudFormation support for S3::BucketPolicy - fixes #1877
=> Configure nodejs Lambdas to skip SSL verification

localstack/services/sns/sns_listener.py, tests/integration/test_sns.py, tests/unit/test_sns.py
Fix issue #2001 
* Re-trigger CI
=> Fix sns subscription confirmation message

localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
=> Fix notifications for s3 uploads made with presigned post requests

localstack/plugins.py, localstack/utils/bootstrap.py
Optimize plugin loading to speed up boot time
=> Optimize plugin loading to speed up boot time

localstack/plugins.py, localstack/services/ec2/ec2_starter.py, localstack/services/events/events_listener.py, localstack/services/infra.py
Fix deployment of EC2 subnets with CidrIpv6 - addresses #1846
=> Fix deployment of EC2 subnets with CidrIpv6

localstack/services/awslambda/lambda_api.py
* Set default batch size event source = 10
* Create multiple events according to the batch size
Fixes #1131
=> Make Lambda batch size configurable for Kinesis event source mappings

bin/Dockerfile.base, localstack/services/infra.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/templates/template1.yaml, tests/integration/test_cloudformation.py
Fix creation of SQS tags via CloudFormation - fixes #1723
=> Fix creation of SQS tags via CloudFormation

localstack/services/awslambda/lambda_api.py, localstack/services/awslambda/lambda_executors.py, localstack/utils/cloudwatch/cloudwatch_util.py
Fix forwarding of Lambda output into CloudWatch Logs
=> Fix forwarding of Lambda output into CloudWatch Logs

localstack/plugins.py, localstack/services/events/events_starter.py, tests/integration/test_events.py
* Add event_start.py: apply patches for moto
* Update plugins loader
* Add integration tests
Addresses #2101
=> Fix empty response for PutTargets in CloudWatch Events

bin/Dockerfile.base
ref: https://github.com/localstack/localstack/pull/2135#issuecomment-596216153
=> Update elasticmq 0.15.5 in localstack/java-maven-node-python

bin/Dockerfile.base, localstack/config.py, localstack/services/s3/s3_starter.py, localstack/utils/analytics/event_publisher.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/templates/template1.yaml, tests/integration/test_cloudformation.py
Support S3 bucket notifications in CF deployments - fixes #1910
=> Support S3 bucket notifications in CF deployments

localstack/services/awslambda/lambda_api.py
=> #2039 replacing hardcoded 'ReceiptHandle' for now

localstack/services/cloudformation/cloudformation_listener.py, localstack/services/s3/s3_starter.py, localstack/utils/cloudformation/template_deployer.py
Normalize S3 bucket names for CloudFormation deployments
=> Normalize S3 bucket names for CloudFormation deployments

localstack/utils/cloudformation/template_deployer.py, tests/integration/test_cloudformation.py
Support passing of parameters to nested CF stacks - fixes #2111
=> Support passing of parameters to nested CF stacks

localstack/plugins.py, localstack/services/apigateway/apigateway_listener.py, localstack/services/apigateway/apigateway_starter.py
* Error when query a method that doesn't exists
* Can't delete method via API
* Failed when destroying with terraform
=> Fixed some apigateway API issues by patching moto

README.md, localstack/utils/common.py, localstack/utils/testutil.py, tests/integration/test_api_gateway.py, tests/integration/test_integration.py, tests/integration/test_lambda.py, tests/integration/test_sns.py, tests/integration/test_sqs.py
* Refactor test utils for Lambda creation
* Refactor SSL cert creation
=> Refactor test utils for Lambda creation; refactor SSL cert creation

localstack/services/secretsmanager/secretsmanager_starter.py, tests/integration/test_secretsmanager.py
* Add integration test to confirm that 'CreatedDate' is a datetime object
* Rename moto patched function
=> #1070 get secrets Manager Value parsing time error

localstack/services/sqs/sqs_listener.py, tests/integration/test_sqs.py
=> Implemented list-dead-letter-source-queues API

localstack/utils/persistence.py
fixed a typo introduced in #2011
=> do replay each api

tests/integration/test_s3.py
* Add integration test for get_object call
=> #2146 Not getting ETag for GetObject call

localstack/services/sns/sns_listener.py, tests/integration/test_integration.py, tests/integration/test_sns.py
* Update sns listener: handle empty subject
* Add integration test: publish with empty subject
=> #597 SNS.publish() not compatible with the AWS API.

localstack/services/awslambda/lambda_api.py, localstack/services/s3/s3_listener.py, localstack/services/sns/sns_listener.py, localstack/utils/common.py, tests/unit/test_sns.py
=> Change timstamp formatting to output milliseconds instead of micro

.github/ISSUE_TEMPLATE.md, README.md, localstack/services/cloudformation/cloudformation_listener.py, localstack/utils/cloudformation/template_deployer.py
* Fix download of CloudWatch templates from S3 for custom hostnames - addresses #2154
* Add Github issue template
* Update patch for CF `CreationTime` - fixes #2178
=> Fix download of CloudWatch templates from S3 for custom hostnames

localstack/services/cloudformation/cloudformation_listener.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/aws/aws_models.py
* fix CF dependency resolution for stack update
* fix downloading of CF template from S3 with custom hostname - should fix #2154
=> fix CF dependency resolution for stack update; fix downloading of S3 CF templates

README.md, localstack/utils/cloudformation/template_deployer.py
Add CloudFormation deployment of API Gateway MethodResponses - addresses https://github.com/localstack/serverless-localstack/issues/82
=> Add CloudFormation deployment of API Gateway MethodResponses

localstack/services/apigateway/apigateway_starter.py, tests/integration/test_api_gateway.py
* Patch get_integration method (error on getting an integration which was deleted)
* Add integration tests
=> #1935 Terraform API Gateway + Lambda Integration 500 Internal Server

bin/Dockerfile.base, localstack/constants.py, localstack/services/es/es_api.py, localstack/services/install.py, localstack/utils/common.py, requirements.txt
Update Elasticsearch to 7.1 - supersedes #2086
=> Update Elasticsearch to 7.1

localstack/services/cloudformation/cloudformation_starter.py, localstack/services/cloudformation/service_models.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/templates/template1.yaml, tests/integration/test_cloudformation.py
Add CloudFormation support for SSM::Parameter
=> Add CloudFormation support for SSM::Parameter

localstack/services/cloudformation/cloudformation_listener.py, localstack/services/cloudformation/cloudformation_starter.py, tests/integration/test_cloudformation.py
* Path describe_change_set on moto's cloudformation
* Update forward request for changeSet's requests
* Add integration tests for cloudformation deploy API
=> #760 Fix cfn deploy changeset error

tests/integration/test_s3.py
Add test for S3 list_object_versions with EncodingType parameter
=> Add test for S3 list_object_versions with EncodingType parameter

localstack/services/awslambda/lambda_api.py, tests/unit/test_lambda.py
=> Added AWS Response Element. Fix terraform deployment for Lambdas

localstack/services/awslambda/lambda_executors.py, tests/unit/test_lambda.py
This is to fix the bug reported in: https://github.com/localstack/localstack/issues/2204
=> set debug_java_port

localstack/services/awslambda/lambda_api.py, localstack/services/sqs/sqs_listener.py, localstack/utils/testutil.py, tests/integration/test_lambda.py, tests/integration/test_sqs.py, tests/unit/test_sqs.py
=> NotImplemented: Receive message attributes on receive_message API

bin/supervisord.conf
Reverts localstack/localstack#2192 . Fixes #2206
=> Revert "fix supervisor warning when running in docker"

localstack/services/dynamodb/dynamodb_listener.py, tests/integration/test_dynamodb.py
* Add handle for resource's tags
* Update integration tests
=> Implement tagging for DynamoDB tables

localstack/services/sns/sns_listener.py
=> Add debug logs for publishing SNS message

tests/integration/test_secretsmanager.py
#981  Secrets Manager response CreatedDate Invalid Format
#1002 Secretsmanager crashing at list / update operations
#1079 Multiple secrets in secrets manager
=> Update Secretsmanager integration tests, confirm that some issues already fixed

tests/integration/test_s3.py
Add tests for S3 uploads with special content and large size - fixes #1417
=> Add tests for S3 uploads with special content and large size

tests/integration/test_sqs.py
Add test for sending SQS message to FIFO queue with DelaySeconds - fixes  #1503
=> Add test for sending SQS message to FIFO queue with DelaySeconds

localstack/utils/testutil.py, tests/integration/test_sqs.py
* Add integration test: lambda invoked by sqs message with delay time
=> #1207 SQS event source does not honor delay-seconds

localstack/utils/aws/aws_stack.py, tests/unit/test_apigateway.py
Add missing API Gateway template util functions - https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#util-template-reference
=> Add API Gateway template util functions

tests/integration/test_cloudformation.py
#1328 Deleting and recreating the stack with same name gives me 409 conflict error
#2189 CloudFormation does not properly handle deleted resources.
=> Add tests to delete and re-create CloudFormation resources

localstack/services/logs/logs_listener.py, tests/integration/test_logs.py
* Fix logs listener: patch response from moto
Fixes #1343
=> Fix content-type header for CloudWatch logs responses

localstack/services/cloudformation/cloudformation_starter.py, localstack/services/cloudformation/service_models.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/test_cloudformation.py
* Add support for Log Group resource
=> Add CloudFormation support for AWS::Logs::LogGroup

localstack/services/iam/iam_listener.py, localstack/services/iam/iam_starter.py, tests/integration/test_iam.py
* Patched moto functions
Fixes #1673
=> Add support for tags on IAM CreateUser calls

localstack/services/sns/sns_listener.py, tests/integration/test_sns.py, tests/unit/test_sns.py
Fixed data type conversions in sns message attributes
=> Fix data type conversions in SNS->SQS message attributes

README.md
=> Included awscli & credentials installation details #2234

localstack/services/iam/iam_starter.py
=> Fix XML response template to properly return IAM user tags

README.md, localstack/services/edge.py
* Add README docs for IMAGE_NAME
* Ensure root user for privileged ports on edge API
=> Add README docs for IMAGE_NAME; ensure sudo for privileged ports on edge API

localstack/services/awslambda/lambda_api.py, tests/integration/test_lambda.py, tests/unit/test_lambda.py
* Update lambda_api
* Add integration test: lambda add event source mapping with batch size
=> #1720 Invalid default BatchSize for EventSourceMapping with SQS Queue

localstack/services/es/es_api.py, tests/integration/test_elasticsearch.py
Fix mapping of Elasticsearch domain versions. Addresses #2242
=> Fix mapping of Elasticsearch domain versions

docker-compose.yml
Exposed the edge port 4566 to start from docker-compose #2253
=> Exposed the edge port 4566 to start from docker-compose #2253

README.md, docker-compose.yml, localstack/services/infra.py, localstack/utils/bootstrap.py
Update docs and add checks for HOST_TMP_FOLDER when running in Docker - addresses #2239
=> Update docs and add checks for HOST_TMP_FOLDER when running in Docker

Dockerfile
Exposing edge port in Dockerfile #2275
=> Exposing edge port in Dockerfile #2275

localstack/utils/bootstrap.py, tests/unit/test_misc.py
Fix Docker port mapping conflicts by avoiding overlaps - fixes #2272
=> Fix Docker port mapping conflicts by avoiding overlaps

localstack/services/cloudformation/cloudformation_starter.py, localstack/services/cloudformation/service_models.py, localstack/services/es/es_starter.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/test_cloudformation.py
Added basic cloudformation support for ElasticSearch::Domain, SecretsManager::Secret and KinesisFirehose::DeliveryStream
=> Cloudformation support for ElasticSearch, SecretsManager, KinesisFirehose

localstack/services/es/es_api.py, localstack/utils/aws/aws_stack.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/tagging.py, tests/integration/test_cloudformation.py
Fix tagging support for Elasticsearch domains
=> Fix tagging support for ES domains

localstack/services/cloudformation/cloudformation_starter.py, tests/integration/test_cloudformation.py
Added missed cloudformation getatt for KinesisFirehose::DeliveryStream and Elasticsearch::Domain
=> Cloudformation getatt for Firehose and ES Domain

localstack/services/sns/sns_listener.py, tests/integration/test_sns.py
Enhancement Added exists operator support for SNS FILTER POLICY 
https://github.com/localstack/localstack/issues/1703
=> #1703 Enhancement Added exists operator support for SNS FILTER POLICY

Dockerfile, README.md, bin/Dockerfile.base, bin/localstack, localstack/config.py, localstack/constants.py, localstack/services/es/es_api.py, localstack/services/es/es_starter.py, localstack/services/generic_proxy.py, localstack/services/install.py, localstack/services/sns/sns_listener.py, localstack/utils/bootstrap.py, localstack/utils/cli.py, localstack/utils/common.py
Lazily install and allow selection of specific Elasticsearch versions
=> Lazily install and allow selection of specific Elasticsearch versions

.gitignore, localstack/utils/cloudformation/template_deployer.py, requirements.txt, tests/integration/serverless/handler.js, tests/integration/serverless/package.json, tests/integration/serverless/serverless.yml, tests/integration/test_serverless.py
* Add simple test for serverless deployment
* Fix CF deployment of `Logs::LogGroup`
=> Add simple test for serverless deployment; fix CF deployment of Logs::LogGroup

localstack/services/dynamodb/dynamodb_listener.py, tests/integration/test_dynamodb.py
Fixed dbynamo db return values param behaviour 
https://github.com/localstack/localstack/issues/2121
=> Fix dynamodb return-values param behaviour

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/test_cloudformation.py
Support IAM Role in Cloudformation without RoleName - supersedes #2304
=> Support IAM Role in Cloudformation without RoleName

tests/integration/test_elasticsearch.py
Fix test for ES domain endpoint assertion
=> Fix test for ES domain endpoint

tests/integration/lambdas/lambda_send_message.py, tests/integration/test_lambda.py
* Add test lambda for sending message to sqs inside lambda
Issue fixed:
#1437 i am facing a problem while sending message to SQS queue from lambda function
=> Test send message to sqs from lambda

localstack/services/s3/s3_listener.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/test_cloudformation.py
* Handle notification configuration when deleting bucket
* Remove unused code
Issue fixed:
#1752 CloudFormation - S3 notification configuration not created
=> Test cfn handle S3 bucket notification configuration

.dockerignore, localstack/services/iam/iam_listener.py, tests/integration/test_iam.py
Fix response content for IAM error messages - addresses #2231
=> Fix response content for IAM error messages

README.md
Added info for Dev packages installation & testing
=> Added info for Dev packages installation & testing

localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
#1859 Added missing headers in the s3 get object response.
=> Fix  #1859 Adding s3 get object response headers

tests/integration/lambdas/lambda_put_item.py, tests/integration/test_lambda.py
* Add sample lambda that make put_item to dynamodb table
Issue fixed:
#1333 Lambda function cannot make DynamoDB calls
=> Test Dynamodb put_item in Lambda

localstack/services/cloudformation/cloudformation_starter.py, localstack/services/dynamodb/dynamodb_starter.py, localstack/services/infra.py, localstack/services/kinesis/kinesis_starter.py, localstack/services/kms/kms_starter.py, localstack/services/sqs/sqs_starter.py, localstack/services/stepfunctions/stepfunctions_starter.py
=> Update log messages with new edge port (#2291)

localstack/services/edge.py, tests/integration/test_lambda.py, tests/unit/test_sns.py
Fix edge request forwarding for public S3 URLs - fixes #2329
=> Fix edge request forwarding for public S3 URLs

localstack/services/cloudformation/cloudformation_starter.py, localstack/services/cloudformation/service_models.py, localstack/services/sns/sns_listener.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/common.py, localstack/utils/server/multiserver.py, tests/integration/test_s3.py
Fix default RoleName in CF dependent IAM roles
=> Fix default RoleName in CF dependent IAM roles

localstack/services/cloudformation/cloudformation_starter.py
Resolve CloudFormation refs when updating resource IDs
=> Resolve CloudFormation refs when updating resource IDs

localstack/services/events/events_listener.py, localstack/services/events/events_starter.py, tests/integration/test_events.py
* Patch moto's functions of events service
* Refactor events integration test
Issue fixed:
#2101 events put-targets does not respond
=> Implement events put_events with target sqs

localstack/services/awslambda/lambda_executors.py
=> Fixed Windows malformed path issue

.travis.yml, Makefile
Extract `.coverage` file from created Docker image in CI - should fix #2346
=> Extract .coverage file from Docker image to fix coverage report in CI

localstack/services/awslambda/lambda_api.py, localstack/services/events/events_listener.py, localstack/services/events/events_starter.py, tests/integration/test_events.py
* Add handle for target lambda
Fixed last comment in:
#1429 Add basic EventBridge (CloudWatch Events) support (https://github.com/localstack/localstack/pull/1429)
=> Implement events put_events with target lambda

localstack/services/apigateway/apigateway_listener.py, localstack/services/generic_proxy.py, localstack/utils/aws/aws_responses.py, tests/integration/lambdas/lambda_integration.py, tests/integration/test_api_gateway.py
#1637 FIX extracting multi value headers to headers
=> 1637 FIX extracting multi value headers to headers

localstack/services/s3/s3_listener.py
#2290 Fix s3 get object fails with header Content-MD5
=> Fix s3 get object fails with header Content-MD5

tests/unit/test_common.py
=> Included some UTC

localstack/services/awslambda/lambda_api.py, localstack/services/awslambda/lambda_executors.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/services/events/events_listener.py, localstack/services/events/events_starter.py, localstack/services/events/scheduler.py, localstack/utils/testutil.py, requirements.txt, tests/integration/test_events.py, tests/integration/test_integration.py, tests/integration/test_lambda.py
Add support for Lambdas triggered by scheduled event rules.
=> Add support for Lambdas triggered by scheduled event rules

tests/integration/lambdas/lambda_start_execution.py, tests/integration/test_lambda.py
Issue fixed:
#1594 Unable to invoke services through boto3 from latest. Works fine on 0.10.2
=> Test start stepsfunction execution in lambda

tests/integration/test_sts.py
#1409 
Adding test case for sts get_federation_token
=> #1409 TestCase Adding test cases for sts get_federation_token

localstack/services/cloudformation/service_models.py, localstack/services/sqs/sqs_listener.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/test_cloudformation.py
Issue fixed:
#2338 Can't create FIFO queue with cloudformation
=> Test cloudformation handle sqs attributes

localstack/services/cloudformation/service_models.py, localstack/services/generic_proxy.py
* Fix regression about Connection keep-alive header - fixes #2375
* Fix Arn attribute for LogGroup in CF - fixes #2372
=> Fix regression about Connection keep-alive header; fix Arn attribute for LogGroup in CF

Makefile, localstack/utils/persistence.py
* Fix creation/squashing of light image
* Skip persistence API call replay if an API is disabled
=> Fix creation/squashing of light image; skip persistence replay if an API is disabled

README.md, localstack/utils/common.py
Fix health check for HTTPS endpoints with self-signed certificates - fixes #2387
=> Fix health check for HTTPS endpoints with self-signed certs

tests/integration/test_sqs.py
Tests Adding test case for sqs Get Queue attributes #1992
=> Tests Adding test case for sqs Queue attributes #1992

localstack/services/apigateway/apigateway_starter.py
moto Integration Fix (api gateway put integration response)
=> moto Integration Fix (api gateway put integration response)

tests/integration/test_cloudwatch.py
* Put metric data
* List metrics
* Get metric statistics
Fixes #712 - cloudwatch internal server errors
=> Add integration test for CW metric data

tests/integration/test_sns.py
* Publish message to topic
* Publish message after subscribe topic
Issue fixed:
#1956 SNS subscribe to topic throws 502 when invoked via Java AWS client
=> Add integration test SNS

tests/integration/test_ec2.py, tests/integration/test_s3.py
Adding test case to create vpc end point #1450 , put/get bucket versioning #2051
=> Tests - Added tests for EC2 Create-Vpc-endPoints,S3 put/get bucket versioning #2051

localstack/services/awslambda/lambda_api.py, localstack/utils/aws/aws_stack.py, tests/integration/test_lambda.py
Enhancement Adding not existent lambda name in response headers. Fixes #1971
=> Enhancement Adding not existent lambda name in response headers

.travis.yml, Makefile, localstack/services/apigateway/apigateway_starter.py, localstack/utils/bootstrap.py
* Optimize travis build for light image - avoid image squashing on every PR build
* Clean up some obsolete code
* Fix loading order of plugin modules
=> Optimize travis build for light image

localstack/services/apigateway/apigateway_listener.py, tests/integration/test_api_gateway.py
Enhancement adding API_gateway Dynamodb integration #1546
=> Enhancement adding API_gateway Dynamodb integration #1546

localstack/dashboard/infra.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/services/generic_proxy.py, localstack/utils/analytics/profiler.py, localstack/utils/common.py
Fix lint issues caused by recent flake8 upgrade - e.g., see this build: https://travis-ci.org/github/localstack/localstack/builds/685811570
=> Fix lint issues caused by flake8 upgrade

localstack/services/cloudformation/cloudformation_listener.py
Fix mapping of CloudFormation account IDs - should fix the issue in #2437
=> Fix mapping of CloudFormation account IDs

localstack/services/s3/s3_listener.py, tests/unit/test_s3.py
=> Included bucket check

localstack/services/awslambda/lambda_api.py, localstack/utils/aws/aws_models.py, tests/integration/test_lambda.py, tests/unit/test_lambda.py
* Update lambda model, lambda_api
Issue fixed:
#2398 Lambda model missing or not preserving attributes
=> Update lambda model to handle missing attributes: kms_key_arn, vpc_config

README.md, bin/docker-entrypoint.sh, bin/localstack, localstack/services/dynamodb/dynamodb_listener.py, localstack/services/edge.py, localstack/services/infra.py, localstack/utils/aws/aws_stack.py, localstack/utils/bootstrap.py, localstack/utils/cli.py, localstack/utils/common.py, localstack/utils/kinesis/kinesis_connector.py, localstack/utils/server/multiserver.py, requirements.txt
* Refactor CLI and infra startup
* Use random port for multiserver
* Remove subprocess32 dependency
=> Refactor CLI and infra startup; use random port for multiserver; remove subprocess32

localstack/utils/common.py
=> CodeCommit Support functions 

localstack/services/sqs/sqs_listener.py, localstack/utils/aws/aws_responses.py, tests/integration/test_sqs.py
Fix : Error handling on sqs send empty message batch #1658
=> Fix : Error handling on sqs send empty message batch

localstack/services/ec2/ec2_starter.py, tests/integration/test_ec2.py
* Patch moto's APIs
Issue fixed:
#2435 EC2 Reserved Instances - 500 error
=> Mock simple response for EC2 Reserved Instance APIs

localstack/services/awslambda/lambda_api.py, localstack/services/sns/sns_listener.py
Included the missing attributes for Lambda SNS Notification.
=> Fix SNS Notification message format (#2165)

localstack/config.py, localstack/services/awslambda/lambda_executors.py
This is a PR to fix the issue describe in Issue #2472
=> Fixed Windows pathing issue with lambda volume mounting

localstack/services/events/events_listener.py, tests/integration/test_events.py
* Update event listener
Issue fixed:
#2460 EventBridge Unsupported Events rule target ARN
=> Add handle schedule expression for http endpoint subscriber

.travis.yml, Dockerfile
* Add Letsencrypt CA certificate to cert store in Docker image
* Remove Python 2 tests in CI
=> Add Letsencrypt CA certificate to cert store

localstack/services/iam/iam_starter.py, tests/integration/test_iam.py
* Patch moto IAM implementation
* Fix lint error
Issue fixed:
#1674 IAM SimulatePrincipalPolicy returns XML error
=> Implement IAM SimulatePrincipalPolicy

localstack/services/sns/sns_listener.py, tests/integration/test_sns.py
CreateTopic with different tags diverging from aws #2405
=> Fix SNS  CreateTopic with different tags diverging from aws

localstack/services/edge.py, tests/integration/test_edge.py
Fix edge routes for S3 HTTP requests - should fix #2442
=> Fix edge routes for S3 HTTP requests

localstack/services/edge.py
Add edge port heuristics for SQS client requests - should fix #2478
=> Add edge port heuristics for SQS client requests

localstack/services/apigateway/apigateway_listener.py, tests/integration/lambdas/lambda_integration.py, tests/integration/test_api_gateway.py
=> Fix: ApiGateway Delete method Response

Dockerfile, localstack/services/edge.py, localstack/utils/common.py
Fix edge routing for SQS queue URLs
=> Fix edge routing for SQS queue URLs

localstack/services/edge.py, localstack/services/s3/s3_listener.py, localstack/utils/common.py
Add edge route for S3 HEAD requests - should fix #2506
=> Add edge route for S3 HEAD requests

localstack/services/cloudformation/cloudformation_starter.py
Fix initialization of CF resource map for recent moto updates
=> Fix initialization of CF resource map for recent moto updates

tests/integration/test_sns.py
Added test for Binary Message attribute for messages into sqs via sns
#2432
=> Test: Binary Message attribute test for messages into sqs via sns

localstack/services/generic_proxy.py, localstack/services/infra.py, localstack/utils/common.py
Refactor proxy listener logic into separate function
=> Refactor proxy listener forwarding logic into separate function

localstack/services/apigateway/apigateway_listener.py, tests/integration/test_api_gateway.py
Fix: Api Gateway validation of api-key-required
#2488
=> Fix: Api Gateway validation of api-key-required

localstack/services/apigateway/apigateway_listener.py, tests/integration/test_api_gateway.py
Adding API-Key validation support in api-gateway method invocation
=> Enhancement : Adding API-Key validation support in api-gateway method invocation

README.md, localstack/services/sns/sns_listener.py
Add persistence for SNS with PersistingProxyListener.
https://github.com/localstack/localstack/issues/2463
=> Persistence SNS

localstack/services/events/events_starter.py, localstack/utils/aws/aws_stack.py, tests/integration/test_events.py
=> added event target firehose functionality

localstack/config.py, localstack/services/awslambda/lambda_api.py, localstack/services/generic_proxy.py, localstack/services/s3/s3_listener.py, localstack/utils/common.py, localstack/utils/http_utils.py, localstack/utils/server/http2_server.py, tests/unit/test_misc.py
Fix chunked encoding in S3 responses for compatibility with AWS PHP SDK - fixes #2535
=> Fix chunked encoding in S3 responses

tests/integration/test_dynamodb.py
Add test for multiple updates in DDB update expressions - addresses #2529
=> Add test for multiple updates in DDB update expressions

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/server/http2_server.py, requirements.txt
Minor CF refactoring; enhance error logging for SSL cert errors
=> Minor CF refactoring; enhance error logging for SSL cert errors

localstack/services/s3/s3_listener.py, localstack/services/s3/s3_starter.py, localstack/utils/bootstrap.py, localstack/utils/server/http2_server.py, tests/integration/test_s3.py
* Fix S3 method rename from get_key to get_object
* Fix timestamps for S3 buckets
=> Fix S3 method rename from get_key to get_object

localstack/services/infra.py, localstack/utils/async_utils.py, localstack/utils/common.py, localstack/utils/server/http2_server.py
* Refactor async utils into separate file
* Cleanup thread pool on shutdown
=> Refactor async utils into separate file

localstack/services/apigateway/apigateway_listener.py, localstack/services/awslambda/lambda_api.py, tests/integration/test_api_gateway.py
aws proxy resource method call deviation from aws
#2210
=> aws proxy resource method call deviation from aws

localstack/services/edge.py
Fix edge routing for DynamoDB Streams - fixes #2543
=> Fix edge routing for DynamoDB Streams

localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
S3:FIX - fix cors policy with one origin
#2564
=> S3:FIX - fix cors policy with one origin

localstack/services/awslambda/lambda_api.py, localstack/services/awslambda/lambda_executors.py, localstack/utils/server/http2_server.py
Minor: pass HTTP_PROXY to Lambda if configured
=> Minor: pass HTTP_PROXY to Lambda if configured

localstack/services/awslambda/lambda_api.py, tests/integration/test_sqs.py
Convert SQS->Lambda message attributes to lower case - addresses #2255
=> Convert SQS->Lambda message attributes to lower case

localstack/services/awslambda/lambda_api.py, localstack/services/dynamodbstreams/dynamodbstreams_api.py, localstack/services/edge.py, localstack/utils/common.py, tests/integration/test_dynamodb.py, tests/integration/test_sqs.py
* Fix edge mapping for CloudWatch - fixes #2571
* Fix DynamoDB shard IDs - addresses #2569
=> Fix edge mapping for CloudWatch; fix DynamoDB shard IDs

localstack/utils/common.py
Store SSL certs to random tmp files in case of permission issues - addresses #2574
=> Store SSL certs to random tmp files in case of permission issues

localstack/services/awslambda/lambda_api.py, localstack/services/awslambda/lambda_executors.py, tests/integration/test_lambda.py, tests/unit/test_lambda.py
Return proper response details on Lambda invocation error - addresses #2572
=> Return proper response details on Lambda invocation error

localstack/services/s3/s3_listener.py
Fix S3 bucket creation date for Java SDK v2
=> Fix S3 bucket creation date for Java SDK v2

localstack/services/edge.py, localstack/services/sqs/sqs_listener.py
Encode account ID in SQS queue URL - addresses #2518
=> Encode account ID in SQS queue URL

README.md, localstack/services/plugins.py, localstack/services/s3/s3_listener.py
Fix error responses for S3 Content-MD5 header - addresses #2562
=> Fix error responses for S3 Content-MD5 header

localstack/services/cloudformation/cloudformation_starter.py, tests/integration/test_cloudformation.py
Support conditional CloudFormation deployment based on AccountId - addresses #2083
=> Support conditional CloudFormation deployment based on AccountId

localstack/config.py, localstack/constants.py, localstack/utils/cloudformation/template_deployer.py
Fix default value for S3 LocationConstraint in CF
=> Fix default value for S3 LocationConstraint in CF

localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
Fix:S3-Invalid range Error
#2587
=> Fix:S3-Invalid range Error

localstack/services/kinesis/kinesis_listener.py
Closes #2545 
Added missing optional [Record](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_Record.html) values to kinesis listener responses. As referenced in #940 and verified in [Kinesalite](https://github.com/mhart/kinesalite), encryption is not supported, so the value has been left as `NONE` by default.
=> Add optional Record values to kinesis stream listener response (#2545)

localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
Fix handling of S3 LocationConstraint on bucket creation
=> Fix handling of S3 LocationConstraint on bucket creation

localstack/services/sqs/sqs_listener.py, localstack/utils/bootstrap.py
Determine proper external port in SQS URLs
=> Determine proper external port in SQS URLs

localstack/services/iam/iam_starter.py, tests/integration/test_cloudformation.py
* Patch moto method to handle policy document
* Update integration test for cfn deploy
Issue fixed:
#2528 cloudformation deploy doesn't create the stack resources
=> Fix cloudformation deploy issue with IAM role resource

localstack/services/awslambda/lambda_executors.py
API gateway Using JSON Safe for failure of byte type.
=> Api gateway Using Json Safe for failure of byte type.

tests/integration/test_cloudformation.py
Test CloudFormation -Delete Stack
=> Test CloudFormation -Delete Stack

localstack/services/edge.py, localstack/services/generic_proxy.py, localstack/services/sqs/sqs_listener.py, localstack/utils/common.py, tests/integration/test_sqs.py
Fix direct access to queue URLs with new SQS backend - addresses #2612
=> Fix direct access to queue URLs with new SQS backend

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/test_cloudformation.py
* Fix TypeError issue when create stack for SNS
* Fix issue No Output on deploying stack
Issue fixed:
#2568 Cloudformation create-stack for SNS with yaml causes TypeError
=> Fix cloudformation deploy issue with SNS resource

tests/integration/test_dynamodb.py
Tests : Dynamodb tests for empty string & Binary values.
#2443
=> Tests : Dynamodb tests for empty string & Binary values.

README.md, localstack/dashboard/api.py, localstack/services/edge.py, localstack/services/plugins.py
Move `/health` check endpoint to edge port - addresses #2534
=> Move /health check endpoint to edge port

localstack/services/awslambda/lambda_api.py, tests/unit/test_lambda.py
Add thread synchronization to Lambda config initialization - addresses #2579
=> Add thread synchronization to Lambda config initialization

localstack/services/awslambda/lambda_executors.py, localstack/services/dynamodb/dynamodb_listener.py, localstack/services/s3/s3_listener.py, localstack/utils/common.py, tests/integration/test_dynamodb.py, tests/integration/test_route53.py, tests/integration/test_s3.py, tests/unit/test_lambda.py
* Add support for DynamoDB Global Tables - addresses #1834
* Extend classpath for Java Lambdas
* Fix Content-MD5 base64 checks - addresses #2562
=> Add support for DynamoDB Global Tables

localstack/services/awslambda/lambda_executors.py, localstack/services/cloudformation/cloudformation_starter.py
Fix error handling for Lambda event source mappings in CloudFormation - addresses #2617
=> Fix error handling for Lambda event source mappings in CloudFormation

localstack/services/dynamodbstreams/dynamodbstreams_api.py, tests/integration/test_dynamodb.py
Fix: dynamodbStreams get_shardId_Iterator
#2616
=> Fix: dynamodbStreams get_shardId_Iterator

localstack/services/dynamodb/dynamodb_listener.py, tests/integration/test_dynamodb.py
Fix:Duplicate dynamodb creation error.
#2629
=> Fix:Duplicate dynamodb creation error.

localstack/services/sns/sns_listener.py
Fix SNS message subscription notifications with FilterPolicy configured
=> Fix SNS message subscription notifications with FilterPolicy configured

localstack/services/events/events_listener.py, tests/integration/test_events.py
- Update event listener
- Update integration test
Issue Fixed:
#2620 Add SQS as target in EventBridge
=> Add SQS as target in EventBridge #2620

localstack/services/awslambda/lambda_executors.py, localstack/services/edge.py, localstack/services/sqs/sqs_starter.py, localstack/utils/common.py, localstack/utils/server/http2_server.py, tests/integration/test_sqs.py
* Fix HTML escaping of SQS message attributes - addresses #2626
* add access to the DynamoDB shell via the edge port - addresses #2619
=> Fix HTML escaping of SQS message attributes

localstack/services/iam/iam_starter.py, tests/integration/test_api_gateway.py, tests/integration/test_iam.py, tests/integration/test_integration.py
* Update list_roles patch
Issue fixed:
#2647 Possible regression error with IAM Role Policy Document
=> Fix the issue creating role corrupts the AssumeRolePolicyDocument of an existing role

localstack/services/awslambda/lambda_api.py, tests/integration/test_lambda.py
Fix : Add multiple permissions to same lambda function.
#2661
=> Fix : Add multiple permissions to same lambda function.

localstack/config.py, localstack/services/awslambda/lambda_executors.py, localstack/services/edge.py, localstack/services/sqs/sqs_listener.py, localstack/utils/kinesis/kinesis_connector.py
* Minor refactoring of logic to determe http/https prototol
* Skip setting `HOSTNAME` in Lambda container environment
=> Minor refactoring of logic to determe http/https prototol

localstack/services/edge.py, localstack/services/generic_proxy.py, tests/integration/test_s3.py
Return raw response in edge proxy to fix gzip encoded S3 content - addresses #2582
=> Return raw response in edge proxy to fix gzip encoded S3 content

localstack/services/dynamodb/dynamodb_listener.py, tests/integration/test_dynamodb.py
DynamoDB : Duplicate table Error change.
#2629
=> DynamoDB : Duplicate table Error change.

localstack/services/edge.py, localstack/utils/cloudwatch/cloudwatch_util.py, localstack/utils/server/http2_server.py, tests/integration/test_events.py
* Fix error/warning messages for terminated SSL connections
* Add S3 edge route for `--no-sign-request` CLI requests
=> Minor: Fix error/warning messages for terminated SSL connections

tests/integration/test_sqs.py
Add test for SQS DLQ when maxReceiveCount is reached - addresses #2107
=> Add test for SQS DLQ when maxReceiveCount is reached

localstack/services/generic_proxy.py, localstack/services/infra.py, localstack/utils/analytics/event_publisher.py, localstack/utils/testutil.py
Add utility function to detect local test execution context
=> [minor] Add utility function to detect local test execution context

localstack/utils/cloudwatch/cloudwatch_util.py, localstack/utils/testutil.py, tests/integration/test_sqs.py
* Enhance parsing of Lambda log lines into CloudWatch Logs
* Add simple test to add message with group ID / deduplication ID to SQS FIFO queue - addresses #2705
=> Enhance parsing of Lambda log lines into CloudWatch Logs

Makefile, README.md, localstack/constants.py, localstack/utils/bootstrap.py, localstack/utils/cli.py
Build and push localstack-full image in CI, make light image the default. (The `localstack/localstack-light` image may get removed in a future version)
=> Build and push localstack-full image in CI, make light image the default

tests/integration/test_sqs.py
- Add integration tests
Issue fixed:
Can't queue multiple messages on SQS within a single message group #2710
=> Add integration tests SQS FIFO queue send and receive multiple messages

localstack/services/apigateway/apigateway_listener.py, localstack/services/awslambda/lambda_api.py, localstack/utils/aws/aws_stack.py, localstack/utils/aws/templating.py, setup.py, tests/unit/test_apigateway.py, tests/unit/test_templating.py
Add basic string functions in VLT templates - addresses #2714 #2717 #2719
=> Add basic string functions in VLT templates

tests/integration/test_sqs.py
- Add integration test tag and untag SQS queue
Issue fixed:
SQS Action TagQueue is not working with moto as provider #2690
=> Add integration test tag and untag SQS queue

localstack/config.py
=> fix(config): debug env

localstack/utils/bootstrap.py, tests/unit/test_common.py
Refactor logic and add tests for command line ports parsing
=> Refactor logic and add tests for command line ports parsing

localstack/utils/persistence.py
Minor fix for UTF-8 encoding in persistence
=> Minor fix for UTF-8 encoding in persistence

README.md, localstack/services/plugins.py
Fix /health endpoint for SSL enabled service configuration - addresses #2742
=> Fix /health endpoint for SSL enabled service configuration

localstack/utils/bootstrap.py, localstack/utils/server/http2_server.py, tests/unit/test_common.py
* Fix SSL context creation error for multiple threads - addresses #2676 
* Fix overlapping port mapping, add additional unit test
=> Fix SSL context creation error for multiple threads; fix overlapping port mapping

README.md, localstack/services/apigateway/apigateway_listener.py, localstack/services/edge.py, localstack/utils/server/http2_server.py
Add edge route and update README for API Gateway execution path pattern
=> Add edge route and update README for API Gateway execution path pattern

README.md
Update README with details about Web UI - addresses #2749
=> Update README with details about Web UI

README.md, localstack/plugins.py, localstack/services/infra.py, localstack/utils/aws/dead_letter_queue.py, tests/integration/test_acm.py, tests/integration/test_api_gateway.py
Add initial support for ACM API - addresses #2320
=> Add initial support for ACM API

localstack/services/iam/iam_starter.py, tests/integration/test_cloudformation.py, tests/integration/test_iam.py
FIX:IAM: Adding support to pathPrefix in list_users method
#2767
=> FIX:IAM: Adding support to pathPrefix in list_users method

localstack/services/install.py, localstack/services/sqs/sqs_listener.py, localstack/services/sqs/sqs_starter.py, localstack/utils/cloudformation/template_deployer.py
Fix SQS attribute handling; enhance CF support for SNS::Subscription
=> Fix SQS attribute handling; enhance CF support for SNS::Subscription

tests/integration/test_s3.py
Fix content-type in presigned URLs in S3 tests
=> Fix content-type in presigned URLs in S3 tests

localstack/services/apigateway/apigateway_listener.py
Fix API key checks for API GW paths with path params - addresses #2488
=> Fix API key checks for API GW paths with path params

tests/integration/test_ec2.py
This bug was fixed in moto repository
- Add integration tests to verify issue
Issue fixed:
https://github.com/localstack/localstack/issues/2761
=> VPN Gateway attachment.vpc-id filter needs incorporated #2761

localstack/services/apigateway/apigateway_listener.py, tests/integration/test_api_gateway.py
Enhance implementation and tests for API GW HTTP/HTTP_PROXY support
=> Enhance implementation and tests for API GW HTTP/HTTP_PROXY support

localstack/services/s3/s3_listener.py, tests/integration/lambdas/lambda_triggered_by_s3.py, tests/integration/test_s3.py
* Fix etag value on event message
Issue fixed:
#2776 Lambda not getting invoked from S3 bucket notification
=> Test s3 notification with lambda and dynamodb

localstack/config.py, localstack/services/generic_proxy.py, localstack/utils/bootstrap.py
* Fix CORS issue in proxy response headers
* Minor refactoring in bootstrap.py
=> [minor] Refactor proxy CORS headers

localstack/services/awslambda/lambda_api.py, localstack/services/awslambda/lambda_executors.py, requirements.txt, tests/integration/lambdas/lambda_integration.js, tests/integration/lambdas/lambda_integration.py, tests/integration/test_lambda.py
Fix:Lambda - Fixed client-context attribute inside lambda invoke
https://github.com/localstack/localstack/issues/2758
=> Fix:Lambda - Fixed client-context attribute inside lambda invoke

.travis.yml, localstack/services/infra.py, localstack/utils/async_utils.py, localstack/utils/bootstrap.py, localstack/utils/common.py, requirements.txt
Add debug output for cleanup methods on shutdown
=> Add debug output for cleanup methods on shutdown

localstack/utils/server/http2_server.py
Add retries to fix intermittent SSL cert generation errors.
The error is coming from the PEM SSL lib (native code) in Alpine Docker containers, and appears to happen intermittently (seems unrelated to multithreading, as the code is already synchronized). Retrying seems to fix the issue (hopefully):
```
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 85, in worker_serve
ssl_context = config.create_ssl_context()
File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 64, in create_ssl_context
SSL_CONTEXTS[key] = create_ssl_context_orig(self, *args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/config.py", line 141, in create_ssl_context
context.load_cert_chain(certfile=self.certfile, …
```
=> Add retries to fix intermittent SSL cert generation errors

localstack/services/awslambda/lambda_api.py, localstack/services/cloudformation/cloudformation_listener.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/services/cloudformation/service_models.py, localstack/services/s3/s3_starter.py, tests/integration/test_cloudformation.py, tests/integration/test_sqs.py
CloudFormation updates to fix recent moto upgrade
=> CloudFormation updates to fix recent moto upgrade 

localstack/services/ec2/ec2_starter.py
Remove unsed patch for vpc_conns region response.
Issue link:
https://github.com/localstack/localstack/issues/2147
=> Remove unused patch for vpc_conns region

tests/integration/test_cloudformation.py
- Issue was fixed in the lasted version
- Add integration to verify bug
Issue fixed:
https://github.com/localstack/localstack/issues/2431
=> Add integration test to verify bug #2431

localstack/services/sqs/sqs_listener.py, tests/integration/test_sqs.py
**Fix:**
- SQS implementation is changed to moto.
- Retry mechanism added for sqs
- Dot net lambda exection issue fixed for case sensative system
=> fix: sqs_backend changed, sqs test

localstack/services/sns/sns_listener.py, tests/integration/test_sns.py
Add support for platform endpoints in SNS subscriptions - addresses #874
=> Add support for platform endpoints in SNS subscriptions

README.md, localstack/services/apigateway/apigateway_listener.py, localstack/utils/aws/aws_responses.py, localstack/utils/aws/templating.py, tests/integration/lambdas/lambda_integration.py, tests/integration/test_api_gateway.py
Add support for custom Lambda integration in API Gateway - addresses #1080
=> Add support for custom Lambda integration in API GW 

localstack/services/awslambda/lambda_executors.py, tests/integration/test_lambda.py
adding base64 encoding for client context
#2758
=> Fix : lambda client context adding base64 encoding for client context

localstack/services/sns/sns_listener.py, tests/integration/test_sns.py
Added support for the sms protocol in sns to publish a message. Also added test case for the same
=> integration of the sms as a info log in sns

localstack/plugins.py, localstack/services/s3/s3_listener.py
Fix:S3-HOSTNAME_EXTERNAL key name extraction.
#2812
=> Fix:S3-HOSTNAME_EXTERNAL key name extraction.

README.md, localstack/config.py, localstack/utils/analytics/event_publisher.py, localstack/utils/async_utils.py, localstack/utils/aws/aws_stack.py, localstack/utils/bootstrap.py, localstack/utils/common.py, tests/unit/test_misc.py
Increase max threads in thread pool to improve concurrency - addresses #2825
=> Increase max threads in thread pool to improve concurrency

tests/integration/test_secretsmanager.py
- Add integration test to verify bug fixed: SSM labels are not supported
Issue fixed:
https://github.com/localstack/localstack/issues/2779
=> Add integration test to verify bug #2779 fixed

localstack/utils/cloudformation/template_deployer.py, tests/integration/test_cloudformation.py
=> Allow CloudFormation to delete lambda functions.

localstack/services/s3/s3_listener.py
=> fix-list-objects-delimiter-none cut out None from Delimiter tag

localstack/services/dynamodb/dynamodb_starter.py, localstack/utils/common.py, tests/unit/test_common.py
Adjust timestamp format for JSON-safe object conversion
=> Adjust timestamp format for JSON-safe object conversion

localstack/services/s3/s3_listener.py
=> ret-304-if-etag-is-if-none-match return 304 if If-None-Match == ETag

localstack/services/apigateway/apigateway_starter.py, localstack/services/awslambda/lambda_executors.py, localstack/utils/async_utils.py, localstack/utils/aws/aws_stack.py, localstack/utils/bootstrap.py, localstack/utils/common.py, tests/integration/test_api_gateway.py
* Add adaptive, unbounded thread pool to avoid deadlocks on concurrent requests - addresses #2873
* Minor refactorings
=> Add adaptive, unbounded thread pool to avoid deadlocks on concurrent requests

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/serverless/serverless.yml
Fix CF/Serverless deployment for APIGW APIs with missing root resource
=> Fix CF/Serverless deployment for ApiGw APIs with missing root resource

localstack/services/awslambda/lambda_executors.py
Issue fixed: 
https://github.com/localstack/localstack/issues/1892
=> Enhance checking port is available so lambda client can run on that port

README.md, localstack/config.py, localstack/services/awslambda/lambda_executors.py, localstack/utils/bootstrap.py, localstack/utils/cli.py
=> Allow the main docker container name to specified

localstack/services/apigateway/apigateway_listener.py, localstack/services/apigateway/apigateway_starter.py, localstack/services/apigateway/helpers.py, localstack/services/awslambda/lambda_api.py, localstack/services/cloudformation/cloudformation_listener.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/test_cloudformation.py
Minor fixes for CloudFormation API Gateway deployments
=> Minor fixes for CloudFormation API Gateway deployments

localstack/services/s3/s3_listener.py
=> s3_compress_response gzip response when client supports

README.md, bin/Dockerfile.base, localstack/config.py, localstack/services/apigateway/apigateway_listener.py, localstack/services/apigateway/helpers.py
Minor refactoring in API Gateway path handling and CORS responses
=> Minor refactoring in API Gateway path handling and CORS responses

localstack/services/edge.py
Fix edge route for /graph endpoint
=> Fix edge route for /graph endpoint

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/bootstrap.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/serverless/package.json, tests/integration/serverless/serverless.yml, tests/integration/test_cloudformation.py
Minor fix for recent CloudFormation upstream change
=> Minor fix for CloudFormation upstream change

localstack/plugins.py, localstack/services/ec2/ec2_listener.py, localstack/services/firehose/firehose_api.py, localstack/utils/aws/aws_stack.py, localstack/utils/bootstrap.py, localstack/utils/testutil.py
Fix S3 creationTimestamp format; refactor logic to forward requests to S3_BACKEND
=> Fix EC2 creationTimestamp format; refactor logic to forward requests to S3_BACKEND

localstack/services/dynamodb/dynamodb_listener.py
=> Use paginator for dynamodb list tables

localstack/config.py, localstack/services/awslambda/lambda_api.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/services/edge.py, localstack/services/firehose/firehose_api.py, localstack/services/sqs/sqs_listener.py, localstack/utils/aws/aws_responses.py, localstack/utils/common.py
Minor refactoring of util functions for AWS responses
=> Minor refactoring of util functions for AWS responses

localstack/services/firehose/firehose_api.py
=> firehose-s3-put-batch Firehose keeps batched records together for s3

Dockerfile, Makefile, localstack/services/install.py
Minor refactoring of installation logic
=> Minor refactoring of installation logic

localstack/services/edge.py, localstack/utils/bootstrap.py, localstack/utils/server/http2_server.py
Fix error response for requests to non-started APIs
=> Fix error response for requests to non-activated APIs

localstack/constants.py, localstack/services/awslambda/lambda_api.py, localstack/services/cloudformation/cloudformation_starter.py, localstack/services/dynamodb/dynamodb_starter.py, localstack/services/es/es_starter.py, localstack/services/infra.py, localstack/services/kinesis/kinesis_starter.py, localstack/services/kms/kms_starter.py, localstack/services/sqs/sqs_starter.py, localstack/services/stepfunctions/stepfunctions_starter.py, localstack/utils/common.py
Refactor startup logs to print correct ports in output
=> Refactor startup logs to print correct ports in output

localstack/services/apigateway/apigateway_listener.py, localstack/services/apigateway/helpers.py, localstack/services/awslambda/lambda_api.py, localstack/services/awslambda/lambda_executors.py, localstack/utils/bootstrap.py, localstack/utils/testutil.py, tests/integration/test_api_gateway.py, tests/integration/test_lambda.py
Refactor API Gateway utils and test code
=> Refactor API Gateway utils and test code

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/common.py, tests/integration/test_lambda.py
Refactor CF logic for API GW resources and empty values
=> Refactor CF logic for API GW resources and empty values

tests/integration/lambdas/lambda_environment.py, tests/integration/test_stepfunctions.py
* Add integration test with map state machine, input and output.
* Update lambda function to handle dynamic value to relace text in dict
only if map key is present.
=> Integration test to verify map state machines using lambda functions.

tests/integration/test_stepfunctions.py
=> Move test input/output to test method defination.

bin/Dockerfile.base, localstack/constants.py, localstack/services/es/es_api.py
=> Add Elasticsearch 7.7, make it default

localstack/services/awslambda/lambda_api.py, localstack/services/edge.py, localstack/utils/aws/templating.py, localstack/utils/common.py, tests/unit/test_common.py
Add small util function to extract JSONPath expressions
=> Add util function to extract JSONPath expressions

localstack/config.py, localstack/services/dynamodb/dynamodb_listener.py, tests/integration/test_error_injection.py
* Separate read and write error injection.
* Add integration test cases for the same.
* Separate env variables for read ad write.
=> More fine-grained DynamoDB error injection.

localstack/constants.py, localstack/package.json, localstack/services/kinesis/kinesis_listener.py, requirements.txt
With my last PR on [Kinesalite](https://github.com/mhart/kinesalite/pull/104) and this new function. Kinesa_Proxy is be able to handle CBOR Requests.
=> kinesis proxy cbor support

localstack/dashboard/api.py, localstack/dashboard/infra.py, localstack/services/edge.py, localstack/services/generic_proxy.py, requirements.txt
* Fix issue with blocking sockets in HTTP2 server
* Minor refactoring of /graph endpoint
=> Fix issue with blocking sockets in HTTP2 server; minor refactoring of /graph endpoint

localstack/services/edge.py
minor fix - edge s3 head returning variable fixed
=> fixed edge s3 head returning variables

localstack/services/ec2/ec2_listener.py, localstack/utils/aws/aws_responses.py
Fix XML root tag for S3 error responses
=> Fix XML root tag for S3 error responses

tests/integration/terraform/provider.tf, tests/integration/terraform/s3.tf, tests/integration/terraform/sqs.tf, tests/integration/test_terraform.py
Added:
- initial terraform files for sqs
- s3 variable name fixed
=> initial support for sqs tf test; s3 minor variable change

localstack/utils/bootstrap.py, localstack/utils/cloudwatch/cloudwatch_util.py, tests/integration/test_stepfunctions.py
When trying to create Choice State Machines, the "IsPresent" key wasn't valid, created an integration test to test that.
=> Test: testing of creating Choice State Machines

localstack/services/awslambda/lambda_executors.py, localstack/utils/bootstrap.py, tests/integration/test_stepfunctions.py
* Refactor StepFunctions integration tests
* Pass $EDGE_PORT to Lambdas (addresses #3119)
=> Refactor StepFunctions tests; pass $EDGE_PORT to Lambdas

localstack/services/s3/s3_listener.py
this pr will fix empty response handling with gzip header.
=> fixed s3 cors with terraform

tests/integration/terraform/s3.tf, tests/integration/test_terraform.py
added expanded s3 test cases:
- support for cors policy s3
=> s3 cors tf integration

localstack/utils/aws/aws_responses.py
Fix service names and NS URLs for XML service responses
=> Fix service names and NS URLs for XML service responses

localstack/plugins.py, localstack/services/cloudwatch/cloudwatch_listener.py, localstack/services/cloudwatch/cloudwatch_starter.py, localstack/services/infra.py, localstack/utils/common.py, tests/unit/test_cloudwatch.py
* Add cloudwatch starter and listener to fix date format.
* Add unittest to test cloudwatch listener.
#3062 
=> Fix date format in cloudwatch response.

localstack/utils/cloudformation/template_deployer.py, localstack/utils/tagging.py
Add CloudFormation support for Lambda::Permission
=> Add CloudFormation support for Lambda::Permission

doc/developer_guides/README.md
Updated documentation for setting up development environment
=> Updated Developer Documentation

localstack/services/apigateway/apigateway_listener.py, localstack/utils/server/http2_server.py
Add utility function to create Lambda event request context for API GW
=> Add utility function to create Lambda event request context for API GW

README.md, localstack/services/edge.py, localstack/utils/server/http2_server.py, tests/integration/test_logs.py, tests/integration/test_s3.py
Fix Content-Length for edge responses
=> Fix Content-Length for edge responses

localstack/services/cloudformation/cloudformation_listener.py, localstack/services/sqs/sqs_starter.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/templates/deploy_template_1.yaml, tests/integration/templates/deploy_template_2.yaml, tests/integration/templates/deploy_template_3.yaml, tests/integration/templates/deploy_template_4.yaml, tests/integration/templates/template21.json, tests/integration/templates/template4.yaml, tests/integration/templates/template5.yaml, tests/integration/templates/template6.yaml, tests/integration/templates/template7.json, tests/integration/templates/update_lambda_template.json, tests/integration/templates/valid_template.json, tests/integration/test_cloudformation.py
* refactor test templates using files
* handle non-zero ReceiveMessageWaitTimeSeconds property on SQS
* implement Cloudformation validate_template API
Issue fixed:
#3004 Cannot create SQS queue a non zero ReceiveMessageWaitTimeSeconds property via CloudFormation
#2696 LocalStack:Cloudformation Issue
=> Refactor cloudformation integration tests

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py
Use distinct values for missing CloudFormations resource props
=> Use distinct values for missing CloudFormations resource props

Dockerfile, tests/integration/terraform/apigateway.tf, tests/integration/terraform/iam.tf, tests/integration/terraform/lambda.tf, tests/integration/terraform/provider.tf, tests/integration/test_terraform.py
**Test Added:**
- test cases for api-gateway v1 using module
- terraform refractoring
=> test: apigateway terraform testcases added

localstack/services/sqs/sqs_listener.py, tests/integration/test_sqs.py
https://github.com/localstack/localstack/issues/3151
=> add carriage return to SQS message payload validation regex

localstack/services/generic_proxy.py, localstack/services/s3/s3_listener.py, tests/integration/test_s3.py
CORS headers issue has been solved. Now the response of the S3 object call will contain the require CORS headers if CORS configurations are being enabled. If the CORS configurations of the bucket are not enabled then it will add * as an allowed origin and add all valid methods and headers in the response headers. #2168
=> Feature s3 cors

localstack/services/edge.py, tests/integration/test_sts.py
=> Fix: assumeRoleWithWebIdentity STS not working.

localstack/services/apigateway/apigateway_starter.py
This PR fixed the issue mentioned in #1984 .
`timeoutInMillis` variable was missing in the response in `CreateIntegrations` api when the timout is specified.
=> Fixed timeoutInMillis attribute missing from API Gateway integrations

localstack/services/iam/iam_starter.py, localstack/utils/aws/aws_stack.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/templates/asset/index.js, tests/integration/templates/cdktemplate.json, tests/integration/test_cloudformation.py
* handle IAM::Policy resource on cloudformation
* fix issue on deleting IAM::Policy
Issue fixed:
#2757 CloudFormation: Read timeout
┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-324) by [Unito](https://www.unito.io/learn-more)
=> Add integration test: deploy CDK template

localstack/plugins.py, localstack/services/infra.py, localstack/services/route53/route53_listener.py, tests/integration/test_route53.py
**Feature Added:**
* `GetChange `API for route53 [(Reference)](https://docs.aws.amazon.com/Route53/latest/APIReference/API_GetChange.html)
This PR will implements the feature requested by #1860 and #3221 .
┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-325) by [Unito](https://www.unito.io/learn-more)
=> Added support for route53 get-change

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/cloudformation/template_deployer.py, localstack/utils/common.py, localstack/utils/server/http2_server.py, tests/integration/test_cloudformation.py
Enhance CF logic to load state of existing resources
┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-339) by [Unito](https://www.unito.io/learn-more)
=> Enhance CF logic to load state of existing resources

localstack/plugins.py, localstack/services/infra.py, localstack/services/route53/route53_starter.py, tests/integration/terraform/provider.tf, tests/integration/terraform/route53.tf, tests/integration/test_terraform.py
minor refractoring - route53
Added: route53 terraform test case support
┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-344) by [Unito](https://www.unito.io/learn-more)
=> Added route53 terraform test case support

localstack/utils/common.py
* Added a check to enable enterprises that utilize self signed certificates for their proxied connections
Note that no test was added since this expected functionality for Requests.
┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-351) by [Unito](https://www.unito.io/learn-more)
=> Added REQUESTS_CA_BUNDLE to the Download Common

localstack/services/awslambda/lambda_api.py, tests/integration/test_lambda.py
**Added (test cases):**
- Test added for:
- Create config
- Delete config
- Get config
- UpdateConfig
- PutFunctionConfig
- GetFunctionConfig
- DeleteFunctionConfig
Fixed status code for `get-config` api
=> test: added test cases for code lambda signing config

localstack/services/awslambda/lambda_api.py
**Fixed API:**
- Lambda UpdateFunctionConfig. [Ref](https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html)
Added support for `MemorySize` `Role` `KMSKeyArn` `VpcConfig` `Description` attributes
`Issue Fixed:`
#3282
=> fixed lambda update-function-config

doc/developer_guides/README.md
=> docs: fix markdown syntax

README.md
=> minor: fix typo in README.md

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/common.py
Fix passing of stack parameters/resources to CF changeset
=> Fix passing of stack parameters/resources to CF changeset

localstack/services/edge.py, tests/integration/test_sts.py
This pull request configure missing forwarding rule to AWS STS for AssumeRoleWithSAML action from edge custom_rules mapping.
Closes #3317
=> Configure missing forwarding rule to AWS STS for AssumeRoleWithSAML action

localstack/services/secretsmanager/secretsmanager_listener.py, localstack/utils/aws/aws_responses.py
#3323 fixed account id in response
=> fix: use default localstack account ID

localstack/services/apigateway/apigateway_listener.py, localstack/utils/aws/templating.py, tests/integration/test_api_gateway.py
Created StepFunctions integration in the API gateway with or without velocity template.
Also added Test Cases for the same.
Fix for: #1451
=> Added: integration for the sfn in apigw and test cases

localstack/services/cloudformation/cloudformation_starter.py, localstack/stepfunctions/models.py, localstack/utils/cloudformation/template_deployer.py
* Handle StateMachine resource
Issue fixed:
#3249 StepFunctions: Unable to parse and update resource
=> Fix issue when updating CF template with StateMachine

localstack/services/awslambda/lambda_executors.py
Fix passing events to provided Lambda runtimes (Rust) - addresses #3264
=> Fix passing events to provided Lambda runtimes (Rust)

tests/integration/test_sqs.py
=> Made helper method readable and configurable

localstack/services/plugins.py, localstack/utils/cloudformation/template_deployer.py, tests/integration/templates/template24.yaml, tests/integration/test_cloudformation.py
Fix resolving refs when querying CF resource deployment  state - addresses #3294
=> Fix resolving refs when querying CF resource deployment state

localstack/services/cloudformation/cloudformation_starter.py, localstack/utils/aws/aws_stack.py, tests/integration/templates/template26.yaml, tests/integration/test_cloudformation.py
Fix issue with fn in output export name
Issue fixed:
#3249 StepFunctions: Unable to parse and update resource
#3301 CloudFormation - Unable to use intrinsic functions in output export name
=> Fix issue on updating state machine with fn in definition string
