localstack/localstack

- localstack/services/cloudformation/cloudformation_starter.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/test_cloudformation.py
Refactor and enhance CF resolution of placeholders in Sub expressions
> Refactor and enhance CF resolution of placeholders in Sub expressions

- localstack/services/awslambda/lambda_executors.py
> Fix fragile docker entrypoint lookup

- Dockerfile
- localstack/utils/cloudformation/template_deployer.py
Extract Ref attribute for CloudFormation Sub attributes with "${resource}" syntax
> Extract Ref attribute for CloudFormation "Sub" attributes with "${resource}" syntax

- localstack/services/dynamodb/dynamodb_starter.py
> Fix dynamodb service not available with DATA_DIR

- localstack/services/ses/ses_starter.py
> log content of outgoing emails

- localstack/services/apigateway/apigateway_starter.py
- tests/integration/terraform/apigw.tf
- tests/integration/test_terraform.py
* Patched moto apigateway method
* Update integration test with terraform
Issue fixed:
#3325 API Gateway IAM Policy not escaped properly
> Fix issue when deploying terraform template with policy in apigateway

- localstack/services/awslambda/lambda_executors.py
Pass environment variables to Lambdas with "provided" runtime - fixes https://github.com/localstack/localstack/pull/3344#issuecomment-751499200
> Pass environment variables to Lambdas with "provided" runtime

- localstack/utils/cloudformation/template_deployer.py
Adds ability to get an AppSync DataSource's physical id.
> feat: resolve datasource arn

- localstack/services/cloudformation/service_models.py
- localstack/services/s3/s3_listener.py
- localstack/utils/cloudformation/template_deployer.py
- localstack/utils/common.py
- tests/integration/test_stepfunctions.py
Refactor CF implementation to use resource model classes
> Refactor CF implementation to use resource model classes

- localstack/services/awslambda/lambda_api.py
- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
Refactor CloudFormation to use model classes (cont'd)
> Refactor CloudFormation to use model classes (cont'd)

- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
CF refactoring: add method to configure deploy templates in resource class
> CF refactoring: add method to configure deploy templates in resource class

- localstack/services/cloudformation/cloudformation_api.py
- localstack/services/cloudformation/service_models.py
- localstack/services/s3/s3_listener.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/test_cloudformation.py
* add support for CF functions select/split/base64
* minor CF refactoring to fix issues that surfaced when testing with CDK
> Add support for CF functions select/split/base64; minor CF refactoring for use with CDK

- localstack/services/s3/s3_listener.py
- tests/integration/test_s3.py
Support S3 key names containing hashes (#)
> Support S3 key names containing hashes (#)

- localstack/services/cloudformation/cloudformation_api.py
- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/test_s3.py
Recursively return all outputs for nested CloudFormation stacks
> Recursively return all outputs for nested CloudFormation stacks

- localstack/services/cloudformation/cloudformation_api.py
- localstack/services/cloudformation/cloudformation_listener.py
- localstack/services/cloudformation/cloudformation_starter.py
- localstack/utils/cloudformation/template_deployer.py
- localstack/utils/cloudformation/template_preparer.py
- localstack/utils/common.py
- tests/integration/test_cloudformation.py
- tests/unit/test_common.py
Fix yaml to JSON parsing of CF templates; minor CF refactoring
> Fix yaml to JSON parsing of CF templates; minor CF refactoring

- localstack/services/awslambda/lambda_api.py
- localstack/services/awslambda/lambda_executors.py
- localstack/services/dynamodb/dynamodb_listener.py
- localstack/services/dynamodbstreams/dynamodbstreams_api.py
- tests/integration/test_lambda.py
- tests/performance/test_dynamodb_performance.py
* Enhance DynamoDB performance by skipping item lookups if no streams enabled - addresses #1205 
* Fix returning log output on Lambda errors - addresses #1630
> Enhance DynamoDB performance by skipping item lookups if no streams enabled

- Dockerfile
- localstack/services/edge.py
Add missing edge route mapping for SNS ConfirmSubscription - addresses #3431
> Add missing edge route mapping for SNS ConfirmSubscription

- localstack/services/secretsmanager/secretsmanager_listener.py
Addresses https://github.com/localstack/localstack/issues/3426
> Add persistence for secrets manager

- bin/docker-entrypoint.sh
This PR adds signal trap support for the docker-entrypoint.sh file.  Because we are spinning up supervisord to then load localstack, when Docker sends a sigterm to the container it only sends it to PID 1 which means that signal is never reaching supervisord. Docker will eventually kill off all of the processes, however, depending on the environment and configuration this time can take from a few seconds to a few minutes. Trapping the SIGTERM signal in the docker-entrypoint allows us to then send that signal to supervisord and in turn allows for a clean shutdown of all services and a clean exit of the container.
This change has been tested in a kubernetes environment and resulted in the container consistently terminating 1-2 minutes faster than without it.
> Adding in signal trap support to the docker-entrypoint

- localstack/services/cloudformation/cloudformation_api.py
- localstack/services/cloudformation/service_models.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/aws/templating.py
- localstack/utils/cloudformation/template_deployer.py
- localstack/utils/common.py
- tests/integration/test_cloudformation.py
- tests/unit/test_templating.py
Fix infinite recursion when loading stack exports that reference other imports.
> Fix infinite recursion when loading stack exports that reference other imports

- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
- requirements.txt
- tests/integration/test_cloudformation.py
Minor fixes for CF resource updates for IAM roles and SFN state machines
> Minor fixes for CF resource updates for IAM roles and SFN state machines

- bin/docker-entrypoint.sh
- localstack/services/apigateway/apigateway_listener.py
- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
* Fix removal of deleted resources from CF stack template
* Add SET_TERM_HANDLER config for Docker entrypoint signal trap
> Fix removal of deleted resources from CF stack template; add SET_TERM_HANDLER config for Docker entrypoint

- localstack/services/ssm/ssm_listener.py
Change in dates format to long so the response can be interpreted by SDKs (tested in Java AWS SDK v2)
You can test using the Java SDK v2 with this snippet:
```
import software.amazon.awssdk.services.ssm.*;
import software.amazon.awssdk.services.ssm.model.*;
import java.net.URI;
public class App 
{
public static void main( String[] args ) {
SsmClient client = SsmClient.builder().endpointOverride(URI.create("http://localstack:4566")).build();
GetParametersResponse response = client.getParameters(GetParametersRequest.builder().names("/aws/reference/secretsmanager/test_secret", "/aws/reference/secretsmanager/no_secret","test_parameter", "no_parameter").build());
System.out.println( response );
}
}
```
The console prints the following:
``` …
```
> SSM & SecretsManager - Changed date format for SDK compatibility

- localstack/services/sqs/sqs_listener.py
**fixed**
- return response for sqs redrive policy
**issue**
- [3427](https://github.com/localstack/localstack/issues/3427)
> fixed redrive policy consistancy

- localstack/services/events/events_listener.py
- localstack/utils/aws/aws_stack.py
- tests/integration/test_events.py
- addresses https://github.com/localstack/localstack/issues/3402
> Use SQS parameter message group id for sqs targets in events rule.

- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/templates/cdk_template_with_kms.json
- tests/integration/test_cloudformation.py
* Add cfn support for KMS:Key resource type
Issue fixed:
#3362 Unknown resource type "KMS::Key" in resource deployment map
> Fix issue when deploying cfn template with kms

- localstack/services/cloudformation/cloudformation_api.py
- localstack/services/cloudformation/service_models.py
- localstack/utils/aws/aws_stack.py
**Added**
- Support for tags in cloudformation
**Fixed**
- [3476](https://github.com/localstack/localstack/issues/3476)
> Support for tags in cloudformation

- localstack/services/iam/iam_starter.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/templates/template28.yaml
- tests/integration/test_cloudformation.py
* Fix issue with IAM::InstanceProfile
* Update integration test
Issues fixed:
#3375 CloudFormation - All deployed stacks have StackStatus: CREATE_FAILED
> Fix issue when deploying cfn template contains IAM::InstanceProfile

- localstack/services/dynamodb/dynamodb_listener.py
- tests/integration/test_dynamodb.py
- addresses https://github.com/localstack/localstack/issues/3467
> Delete dynamodb streams only if table exists

- localstack/services/cloudformation/cloudformation_api.py
- localstack/services/cloudformation/service_models.py
- localstack/services/edge.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/templates/template28.yaml
- tests/integration/templates/template29.yaml
- tests/integration/templates/template30.yaml
- tests/integration/test_cloudformation.py
* Add support for EC2:Instance
* Fix issue with Fn:FindInMap
Issues fixed:
#2379 Can't update stack (aws cloudformation)
> Fix issue when updating cfn stack contains EC2:Instance

- localstack/services/logs/logs_starter.py
**Fixed:**
- Fixed cloudwatch log subscription lambda function invocation.
> fixed lambda trigger from log events

- localstack/services/cloudformation/deployment_utils.py
- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/test_cloudformation.py
- tests/integration/test_cloudwatch.py
Enhance CloudFormation logic for managed and inline IAM policies
> Enhance CloudFormation logic for managed and inline IAM policies 

- README.md
- localstack/services/cloudformation/deployment_utils.py
- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/templates/apigateway_integration.json
Enhance CloudFormation support for API Gateway resources
> Enhance CloudFormation support for API Gateway resources

- localstack/services/cloudformation/service_models.py
- localstack/services/iam/iam_starter.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/test_cloudformation.py
* EC2::SecurityGroup
* IAM::InstanceProfile
> Add CFN support for missing resource types

- localstack/services/logs/logs_starter.py
- localstack/utils/aws/aws_stack.py
**Added:**
- added lambda, kinesis, firehose invocation on put-log-event
- implemented put-subscription api
- added util function for retriving service name from arn
**Support Case Ref:**
- [Using CloudWatch Logs Subscription Filters](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html)
> support for cloudwatch logs subscription filter

- localstack/services/awslambda/lambda_api.py
- addresses https://github.com/localstack/localstack/issues/3485
> Convert payload from lambda fallback to json

- localstack/services/apigateway/apigateway_listener.py
Refactor API Gateway invocation logic for better extensibility (extract `invoke_rest_api_integration(..)` into separate function)
> Minor refactoring of API Gateway invocation logic for better extensibility

- localstack/services/sns/sns_listener.py
- Subscribe
- Unsubscribe
- ConfirmSubscription
> Remove persistence for sns apis

- localstack/services/logs/logs_starter.py
- tests/integration/test_logs.py
**Improved**
- test_put_subscription_filter_lambda
**Added:**
- test_put_subscription_filter_firehose
- test_put_subscription_filter_kinesis
> test cases added for cloudwatch logs subscription

- localstack/services/route53/route53_listener.py
- tests/integration/test_route53.py
Support associate_vpc for Route53
> Support associate_vpc for Route53

- localstack/services/s3/s3_listener.py
- tests/integration/test_s3.py
- addresses https://github.com/localstack/localstack/issues/3555
> Handle non existent key for range header requests

- localstack/services/cloudformation/cloudformation_api.py
- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
**added**
- sns subscription delete method
**fixed**
- cloudformation stack deletion will only mark stack as deleted
**Issue**
- [3495](https://github.com/localstack/localstack/issues/3495)
> added sns subscription delete method

- localstack/services/s3/s3_listener.py
- tests/integration/test_s3.py
- addresses https://github.com/localstack/localstack/issues/3563
> Handle empty marker in list objects

- localstack/plugins.py
- localstack/services/swf/swf_listener.py
- localstack/services/swf/swf_starter.py
- tests/integration/test_swf.py
Integrate moto swf support:
https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md#swf
Possibly satisfy this issue:
https://github.com/localstack/localstack/issues/116
> Add swf support from moto

- localstack/services/s3/s3_listener.py
- addresses https://github.com/localstack/localstack/issues/3595
> Update S3 Event version

- localstack/services/events/events_starter.py
- tests/integration/test_events.py
Fix: added event handler
https://github.com/localstack/localstack/issues/3352
> Fix: added event handler

- localstack/dashboard/infra.py
- localstack/utils/aws/aws_stack.py
- addresses https://github.com/localstack/localstack/issues/3562
> Fix setting of default region from environment variables

- localstack/services/cloudformation/service_models.py
- localstack/services/generic_proxy.py
- localstack/services/kinesis/kinesis_listener.py
- localstack/utils/aws/aws_responses.py
- localstack/utils/server/http2_server.py
- tests/integration/serverless/serverless.yml
- tests/integration/templates/template1.yaml
- tests/integration/test_cloudformation.py
- tests/integration/test_kinesis.py
Initial support for Kinesis consumers and SubscribeToShard via HTTP2 push events. Addresses #3611 #893
> Initial support for Kinesis consumers and SubscribeToShard via HTTP2 push events

- localstack/services/awslambda/lambda_executors.py
- localstack/utils/aws/aws_models.py
- localstack/utils/aws/aws_stack.py
> Add the function's region as default region

- localstack/services/events/events_listener.py
- localstack/services/events/scheduler.py
- tests/integration/test_events.py
- addresses https://github.com/localstack/localstack/issues/3616
> support for disable cloudwatch rule

- .dockerignore
- Dockerfile
- Makefile
- localstack/services/awslambda/lambda_api.py
- localstack/services/install.py
- localstack/services/stepfunctions/stepfunctions_listener.py
- tests/integration/lambdas/lambda_echo.py
- tests/integration/test_stepfunctions.py
Add support and tests for StepFunctions intrinsic functions - addresses #3629
> Add support and tests for StepFunctions intrinsic functions

- localstack/services/awslambda/lambda_api.py
- localstack/services/cloudformation/service_models.py
- localstack/utils/aws/aws_models.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/serverless/package.json
- tests/integration/serverless/serverless.yml
- tests/integration/test_serverless.py
Add CloudFormation support for Lambda::EventInvokeConfig - addresses #3648
> Add CloudFormation support for Lambda::EventInvokeConfig

- localstack/services/sns/sns_listener.py
This "fix" addresses the regression introduced by PR #3435 (as documented by issue #3486) when publishing from SNS to SQS and using ElasticMQ as SQS backend. While the SQS backend has been switched out to moto by default, it is still possible to set ElasticMQ as a SQS backend, making SNS publication to SQS unusable when using ElasticMQ as SQS backend. Until ElasticMQ is completely phased out (which would almost make localstack unusable for us, considering the performance issues we've experienced using moto), it should still be possible to send from SNS to SQS.
I didn't really find a precedent for mocking env vars or constants (which would seem necessary for `SQS_PROVIDER` or `SQS_BACKEND_IMPL`), so I didn't add specific tests. If anyone has pointers for adding tests, I would be happy to …
> Fix: Do not send MessageGroupId to SQS when using ElasticMQ

- localstack/services/s3/s3_listener.py
- tests/integration/test_s3.py
Fix:Delete lifecycle configuration
https://github.com/localstack/localstack/issues/3639
> Fix:Delete lifecycle configuration

- localstack/services/events/events_starter.py
- localstack/utils/aws/aws_stack.py
- tests/integration/test_events.py
Refactor tests and logic for EventBridge targets - addresses #3628
> Refactor tests and logic for EventBridge targets

- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/templates/template31.yaml
- tests/integration/test_cloudformation.py
Issue fixed:
#3612 Failed to create event bus using cloudformation on localstack
> Add CFN support for resource type: Events::EventBus

- Dockerfile
- Makefile
- localstack/config.py
- localstack/services/infra.py
- localstack/utils/bootstrap.py
- localstack/utils/cli.py
- print the localstack version
- print the build date
- print the build commit id
- print the container id if localstack is running within docker
> Add log for buildinfo when localstack starts

- localstack/services/cloudformation/cloudformation_starter.py
- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/templates/apigateway.json
- tests/integration/templates/statemachine_test.json
- tests/integration/test_cloudformation.py
* Fix Resource Condition issue
* Add integration tests
Issue fixed:
#3661 Cloudformation - StateMachine dependencies cause exception
#3668 Cloudformation - References to AWS::ApiGateway::RestApi cause exception
> Add CFN support for resource types: StepFunctions::Activity, ApiGateway::Model

- localstack/services/apigateway/apigateway_listener.py
Fixes https://github.com/localstack/localstack/issues/3676
> Fix resource path being used in API Gateway

- localstack/services/edge.py
Fix:Events changed condition to indetify service
Related to #3256  and #3255
> Fix:Events changed condition to indetify service

- localstack/services/apigateway/apigateway_listener.py
- localstack/services/awslambda/lambda_api.py
- localstack/services/cloudformation/cloudformation_api.py
- localstack/utils/aws/aws_models.py
- localstack/utils/cloudformation/template_deployer.py
- localstack/utils/common.py
- localstack/utils/server/http2_server.py
- tests/unit/test_lambda.py
Fix extracting list of changes in CloudFormation change sets. Partial fix for https://github.com/localstack/localstack-pro-samples/issues/37
> Fix extracting list of changes in CloudFormation change sets

- localstack/config.py
Added mechanism to check whether localstack instance is running inside the docker or on the host. It also will support cgroup v2.
Fix for #3675
> FIX: localstack is running inside the docker config flag

- localstack/constants.py
- localstack/services/edge.py
- localstack/services/s3/s3_listener.py
- localstack/services/s3/s3_starter.py
- localstack/services/s3/s3_utils.py
- localstack/utils/aws/aws_stack.py
- tests/integration/lambdas/lambda_integration.py
- tests/integration/templates/template24.yaml
- tests/integration/test_notifications.py
- tests/integration/test_s3.py
- tests/unit/test_s3.py
**added**
- support for virutal host based routing in s3
**Note: This is a test PR.**
> Support virtual host based addressing for S3 requests

- localstack/services/s3/s3_listener.py
- localstack/services/s3/s3_utils.py
- tests/integration/test_s3.py
- Added support for virtual addressing style presign url signature authentication.
- Added Test Cases
- Restructured the presign url authentication. Moved mechanism to s3_utils.
- Improved the path style presign url signature authenticase test case. Decrease amount of the time being taken to complete the test.
> Support of signature authentication for virtual styled presign url

- localstack/services/s3/s3_listener.py
- tests/integration/test_s3.py
minor s3 refactoring - following pr [3690](https://github.com/localstack/localstack/pull/3690)
> minor s3 refactoring 

- tests/integration/templates/template32.yaml
- tests/integration/test_cloudformation.py
Issue already fixed:
#2199 Cloudformation gives ValidationError on export names
> Test: CFN template with exports

- localstack/services/ec2/ec2_starter.py
- localstack/services/edge.py
Fix EC2 responses for compatibility with TF VPC module.
Addresses https://github.com/hashicorp/terraform-provider-aws/issues/18187
> Fix EC2 responses for compatibility with TF VPC module

- localstack/services/apigateway/apigateway_starter.py
- tests/integration/files/pets.json
- tests/integration/test_api_gateway.py
Update integration test
Issue fixed:
#171 Implement import-rest-api for API Gateway
> Implement: APIGateway import_rest_api method

- localstack/services/s3/s3_listener.py
- tests/integration/test_s3.py
- Follow up PR for #3781 .
- Enabled `test_s3_static_website_hosting`
> fixed path in static website hosting

- localstack/services/kinesis/kinesis_listener.py
Now he the kinesis functions that deal with consumer actions support CBOR encoded data and responses.
Also encodes to base64 the data of the records send to a consumer through the SubscribeToShard Event
With this, the Kinesis Scheduler completely Works in JSON mode and make this test(localstack/localstack-java-utils#47) pass.
> Kinesis consumer cbor messages and encoding for SubscribeToShard

- localstack/services/s3/s3_listener.py
- S3 create bucket headers contains `Location` header in the response
- Removed unused code/comment
> added location header on s3 creation

- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/templates/template33.yaml
- tests/integration/test_cloudformation.py
Issue fixed:
#3728 Unable to extract attribute "PhysicalResourceId" from "EC2::Route"
> Add CFN support: EC2::VPC, EC2::RouteTable, EC2::Route

- .gitignore
- localstack/services/awslambda/lambda_api.py
Adding aws_request_id to LambdaContext. This is in response to this issue that I have encountered: 
https://github.com/localstack/localstack/issues/3806 
Glad to implement any feedback in response to it!
> add new guid as aws_request_id in LambdaContext

- localstack/services/dynamodb/dynamodb_listener.py
**Fixed**
- return statement in `prepare_transact_write_item_records`
**Issues**
- #3801
> fixed transactWrite update opertion

- localstack/services/awslambda/lambda_api.py
With this PR the Data send to the LAMBDA_FALLBACK_URL  is encoded to JSON again.
Addresses #3498 and #3584
> re-encode data to fallback url

- localstack/constants.py
- localstack/services/awslambda/lambda_api.py
- localstack/services/edge.py
- localstack/services/generic_proxy.py
- localstack/services/infra.py
- localstack/services/s3/s3_listener.py
- localstack/services/s3/s3_utils.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/cloudformation/template_preparer.py
- localstack/utils/server/http2_server.py
- tests/integration/test_api_gateway.py
- tests/integration/test_edge.py
- tests/integration/test_events.py
- tests/unit/test_cloudformation.py
Refactor logic for proxy listener; fix edge forward headers
> Refactor logic for proxy listener; fix edge forward headers

- localstack/dashboard/infra.py
- localstack/utils/aws/aws_models.py
- localstack/utils/common.py
Replacing `dashboard/infra.py` AWS CLI custom commands in favour of boto3 calls
> Feat: Replacing AWS CLI commands for boto3 calls

- .travis.yml
- Makefile
Move CI build commands into Makefile for easier migration
> Move CI build commands into Makefile for easier migration

- .circleci/config.yml
- localstack/services/infra.py
- localstack/services/install.py
- requirements.txt
- tests/integration/test_lambda.py
Add Circle-CI project setup - using Circle as a fallback/replacement for Travis, which has become a bit unreliable recently.
> Add Circle-CI project setup

- localstack/services/s3/s3_starter.py
Issue fixed:
#2782 Specific status code needed for Cyberduck compatibility
> Fix compatibility with Cyberduck

- localstack/services/firehose/firehose_api.py
- localstack/services/install.py
- localstack/utils/common.py
- tests/integration/test_firehose.py
- tests/unit/test_firehose.py
> Fix issue 3384 - Added HttpEndpointDestination support to firehose

- Makefile
Fix config to push Docker image from Circle-CI. (Adding debug info for now..)
> Fix config to push Docker image from Circle-CI

- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/templates/template34.yaml
- tests/integration/test_cloudformation.py
Issue fixed:
#3808 CloudFormation: Missing Support for KMS::Alias
> Add CFN support: KMS::Alias

- Makefile
- localstack/config.py
- localstack/services/cloudformation/cloudformation_api.py
- localstack/services/cloudformation/cloudformation_starter.py
- localstack/services/cloudformation/service_models.py
- localstack/services/dynamodb/dynamodb_listener.py
- localstack/services/s3/s3_utils.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/cloudformation/template_deployer.py
- localstack/utils/cloudformation/template_preparer.py
- localstack/utils/common.py
- localstack/utils/testutil.py
- tests/integration/test_dynamodb.py
- tests/unit/test_s3.py
Refactor logic for CF stack instances; enhance CF model for KMS::Key
> Refactor logic for CF stack instances; enhance CF model for KMS::Key

- localstack/services/sns/sns_listener.py
- tests/unit/test_sns.py
Recreating PR #3596 - to trigger new CI build on CircleCI.
> Support json message structure with raw delivery

- localstack/services/cloudformation/cloudformation_api.py
- Fix CloudFormation state filter #3878 
- Add support for multi-value filtering (as specified in the [API docs for CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_ListStacks.html)) 
I've created a small script for setting up the scenarios
[main.txt](https://github.com/localstack/localstack/files/6338536/main.txt)
&nbsp;
Run `localstack` with the `cloudformation` service enabled:
```
localstack start --host
```
Once `localstack` is up, on the attached script run:
```python3
step1() # Creates the stacks 1,2,3 and 4
```
Then run:
```python3
step2() # Updates the stacks 3 and 4
```
Wait a few seconds and then run:     
```python3
step3() # Deletes the stack 4
```
On this step you should be able to run: 
```
aws --region us-east-1 …
```
> Fix CloudFormation stack status filter #3878 

- localstack/services/s3/s3_starter.py
**Issues**
- #3713
**Added**
- Added support for tags in multipart upload
> fixed tags in multipart upload

- localstack/services/apigateway/apigateway_listener.py
- localstack/utils/aws/templating.py
- localstack/utils/cloudformation/template_deployer.py
This PR adds the requestTemplates parameter to the put_integration request and fixes the render velocity template.
Addresses #3777
> fix statemachine integration def and execution

- localstack/config.py
- localstack/services/s3/s3_utils.py
**Added**
- Support for skip s3 presign url validation
> added s3 skip validation parameter

- localstack/plugins.py
- localstack/services/edge.py
- localstack/services/resourcegroups/rg_listener.py
- localstack/services/resourcegroups/rg_starter.py
- tests/integration/test_resourcegroups.py
Added support for resource -groups
https://github.com/localstack/localstack/issues/3979
> Added support for resource-groups

- localstack/services/generic_proxy.py
This is a temporary fix for https://github.com/localstack/localstack/issues/3924 until Mock integrations are implemented for ApiGateway.
For lambda responses some of the headers may be written to [multiValueHeaders](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html#multi-value-headers). Since we are not checking if some of them are already there, they are written again in regular `headers` which results in duplicated headers sent to users (default one + one from lambda).
Is it fine to reset `multiValueHeaders` from the response, or it's critical to preserve it?
> fix(proxy): Doubled response headers

- tests/integration/lambdas/lambda_s3_integration.js
- tests/integration/test_s3.py
**Added**
- Test case to generate presigned url in nodejs sdk with async library
- Test case for x-id headers
> added test case forr presign url

- localstack/services/es/es_api.py
- tests/integration/test_elasticsearch.py
Fixes #4023, adding ES cluster config option and leaving defaults out.
> Fix: Adding ElasticsearchClusterConfig parameter option

- localstack/services/secretsmanager/secretsmanager_listener.py
- localstack/services/secretsmanager/secretsmanager_starter.py
- tests/integration/test_secretsmanager.py
Fix:secret ARN fix
Addresses #4014
> Fix:secret ARN fix

- localstack/services/s3/s3_utils.py
- tests/integration/test_s3.py
**Added**
- Added multiple presigned url calculations with different port combination to add more flexibility.
> added port combination/permutations in presigned url

- localstack/services/s3/s3_utils.py
- tests/integration/test_s3.py
**Fixed**
- [3971](https://github.com/localstack/localstack/issues/3971)
- [3972](https://github.com/localstack/localstack/issues/3972)
**Added**
- Added support for AWS_SESSION_TOKEN (support for `X-Amz-Security-Token` in presigned url)
> added support for session_token

- tests/integration/test_s3.py
**Added**
- Added test case for bucket with existing name
- When creating bucket in default region it will not throw any excption
- if creating bucket in non default region it witl throw  exception as `BucketAlreadyExsists`
**Issues**
- [ISSUE - 3540](https://github.com/localstack/localstack/issues/3540)
- [PR - 3570](https://github.com/localstack/localstack/pull/3570)
> added test case for creating bucket with existing bucket name

- localstack/services/s3/s3_listener.py
- tests/integration/test_s3.py
**Added:**
- GetBucketRequestPayment
- PutBucketRequestPayment
**Property**
- Payer: valid values - 'Requester'|'BucketOwner'
**Related Issue**
- #4071
> added feature bucket request payer

- localstack/services/sns/sns_listener.py
(Re-creating PR #4101 to trigger PR build.)
> With this PR the SNS service delivers the messages to the subscribers of a topic in an async way.
> Addresses #3670
> Parallelize SNS message delivery for improved performance

- localstack/services/edge.py
This PR introduces a guard to `ensure_can_use_sudo` that fails if we can't read from stdin (which is necessary to read the sudo password, but not possible if we run it from an IDE like pycharm). it now fails gracefully and outputs an error output that the edge router can't be run on the privileged port.
> fix start_edge to gracefully fail when stdin for sudo is not available

- localstack/services/apigateway/apigateway_starter.py
- localstack/services/apigateway/helpers.py
Refactor PATCH operations for API Gateway models
> Refactor PATCH operations for API Gateway models

- localstack/services/awslambda/lambda_executors.py
- tests/integration/test_lambda.py
Fix passing payload via stdin for large Lambda events using docker-reuse
> Fix passing payload via stdin for large Lambda events using docker-reuse

- localstack/services/apigateway/apigateway_listener.py
- localstack/utils/aws/aws_responses.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/test_api_gateway.py
Pull request fixes error with cloud formation, when creating a apigateway-s3 integration.
It also adds preliminary support for apigateway-s3 integration for GET requests.
Fixes #4062 .
> Implement ApiGateway - S3 integration for GET requests

- localstack/services/kinesis/kinesis_starter.py
Fix per https://github.com/localstack/localstack/pull/4175
> Update kinesis-mock to 0.1.0

- localstack/services/apigateway/apigateway_starter.py
- localstack/services/ec2/ec2_starter.py
- localstack/services/s3/s3_starter.py
- tests/integration/test_api_gateway.py
Fix API GW imports from OpenAPI specs, minor fixes for TF compatibility
> Fix nested routes for API GW imports from OpenAPI specs, minor fixes for TF compatibility

- localstack/services/apigateway/apigateway_listener.py
- localstack/services/apigateway/helpers.py
* Add support for API Gateway client certificates (covered by TF integration tests)
* Minor refactoring to eliminate duplicate `PATH_REGEX_*` constants
> Add support for API Gateway client certificates (tf-compat)

- localstack/services/events/events_starter.py
Fix event details
https://github.com/localstack/localstack/issues/4198
> Fix event details

- README.md
> minor: update README.md

- tests/integration/test_error_injection.py
this PR refactors the test methods in https://github.com/localstack/localstack/blob/master/tests/integration/test_error_injection.py  into a unittest.TestCase class.
> refactor test_error_injection.py into a unittest.TestCase class

- localstack/services/kinesis/kinesis_listener.py
- tests/unit/test_kinesis.py
And fix error throughput error response for PutRecords
I can not dedicate more time to add more tests to the codebase and this PR does fix 2 issues, feel free to take over and complete/split the PR or close it if you think it is against the rules.
> Add support for cbor kinesis error messages

- localstack/config.py
- localstack/services/sqs/sqs_starter.py
- localstack/utils/common.py
- tests/unit/test_common.py
This PR eliminates some dead code from common.py, simplifies several functions/removes python 2.7 support, and fixes a few IDE warnings.
> minor refactoring in common.py

- localstack/services/kinesis/kinesis_starter.py
> Bump kinesis-mock to 0.1.3

- localstack/services/install.py
- localstack/services/kinesis/kinesis_starter.py
removes the workaround and fixes #4227
> remove kinesis-mock workaround and upgrade to 0.1.3

- localstack/services/awslambda/lambda_api.py
- localstack/services/awslambda/lambda_executors.py
Re-creating PR #4239 one more time, to trigger the CI builds
> Support for local runtime of node lambda

- localstack/utils/aws/aws_stack.py
Implements enhancement from #4274
Adds default headers AWS sends when invoking the API destination target and fixes the api destination ARN structure.
Corresponding ARN fixes are available in the moto-ext release 2.0.3.37
> Add default headers when calling API destination target and fix ARN

- requirements.txt
Pin version of "requests" library to fix import errors in Lambda tests
> Pin version of "requests" library to fix import errors in Lambda tests

- localstack/services/awslambda/lambda_executors.py
Use `JAVA_TOOL_OPTIONS` to apply `LAMBDA_JAVA_OPTS` in Java Lambdas, and remove unused/deprecated code.
This removes old code which was using our own Java Lambda executor to apply JVM options. The Lambda Docker images now support `LAMBDA_JAVA_OPTS` for JVM flags, which is a much easier and cleaner approach.
> Use JAVA_TOOL_OPTIONS to apply LAMBDA_JAVA_OPTS in Java Lambdas, remove unused/deprecated code

- .circleci/config.yml
- .coveragerc
- .gitignore
- Makefile
- tests/integration/test_sns.py
This PR updates the circleci workflow to aggregate coverage statistics from other build steps and combines them in a fan-in step that does the coveralls reporting.
> update CI workflow to aggregate coverage report

- .circleci/config.yml
adding CI slack notifications. important stuff!
> add circleci notifications

- localstack/utils/common.py
- tests/unit/test_common.py
- tests/unit/test_config.py
* adds several unit tests for common.py and config.py
* fixes one error found by the tests
> add unit tests for common and config

- Makefile
- tests/integration/test_lambda.py
Refactor and re-enable a previously disabled test.
> Test Lambda invocation destinations

- localstack/dashboard/infra.py
- localstack/services/edge.py
- localstack/utils/aws/aws_models.py
- localstack/utils/aws/aws_stack.py
- tests/conftest.py
- tests/integration/conftest.py
- tests/integration/dashboard/test_graph.py
- tests/integration/fixtures.py
- tests/integration/test_s3.py
This PR adds tests for the dashboard graph backend code and several improvements (like correct edges between bucket notifications)
> Improve infra graph code and add tests

- localstack/services/ses/ses_starter.py
- tests/integration/test_ses.py
Similar to https://github.com/localstack/localstack/pull/4098 I needed to check if an email was sent correctly but relied upon templated emails which the above PR did not address.
I have essentially duplicated the work done in the above PR but amended it slightly for the send_templated_email use case i.e. sending a templated email will dump said email into the DATA_DIR in an ses subdirectory using the id of the sent email as filename.
The contents of the JSON file are:
- Source
- Template
- TemplateData
- Destinations
e.g.
```
{
"Source": "user@example.com",
"Template": ["hello-world"],
"TemplateData": ["{\"A key\": \"A value\"}"],
"Destinations": {
"ToAddresses": ["success@example.com"],
"CcAddresses": [],
"BccAddresses": []
},
"Region": "us-east-1"
}
```
* NOTE: I am not a Python …
> Save templated e-mail contents in easy, machine-readable format

- localstack/utils/docker.py
- tests/integration/docker/test_docker.py
The rm_env_file method was completely unused, and is now modified and used after each docker invocation.
Also a test for docker pull is added.
> Add test for docker client, remove env_files after use in docker

- localstack/services/install.py
> Kinesis Mock 0.1.6

- localstack/constants.py
- localstack/services/awslambda/lambda_executors.py
- localstack/services/install.py
> Introduce Thundra Java agent integration

- README.md
> [WIP] Add Thundra integration into docs

- localstack/services/awslambda/lambda_api.py
- localstack/services/awslambda/lambda_executors.py
- tests/integration/fixtures.py
- tests/integration/lambdas/lambda_parallel.py
- tests/integration/test_lambda.py
When this PR is merged, Lambdas will not be executed in parallel if the ParallelizationFactor does not allow it, when triggered from Kinesis.
> Add restrictions based on ParallelizationFactor in Lambda Kinesis Event processing

- localstack/constants.py
- localstack/services/awslambda/lambda_executors.py
- localstack/services/install.py
> Download Thundra agent into temp folder and mounted into Docker from there

- localstack/services/awslambda/lambda_executors.py
> Disabled CDS on Java8 because it cannot be in conjunction with `javaagent` VM argument

- localstack/services/install.py
Release notes: https://github.com/etspaceman/kinesis-mock/releases/tag/0.1.8
> Kinesis Mock 0.1.8

- localstack/utils/cloudformation/template_deployer.py
Currently, we're only supporting the basic fiends in IAM user in cloudformation, this PR enables the full compatibility with IAM users, adding the logic about the following missing properties:
- Groups
- LoginProfile
- ManagedPolicyArns
- Policies
Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-user.html
> Feat: add full iam user compatibility on cloudformation

- README.md
- localstack/config.py
- localstack/utils/bootstrap.py
- localstack/utils/docker.py
- localstack/utils/run.py
- tests/integration/docker/conftest.py
- tests/integration/docker/test_docker.py
- tests/unit/test_common.py
- tests/unit/test_dockerclient.py
> Add a docker client using the docker SDK

- localstack/services/s3/s3_listener.py
- localstack/services/s3/s3_starter.py
- tests/unit/test_s3.py
* Fix removing x-amz-content-sha256 header after removing chunk signatures
* Minor fixes to accommodate recent moto upstream changes
> Fix removing x-amz-content-sha256 header after stripping off chunk signatures

- Dockerfile
- localstack/services/cloudformation/models/ec2.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/test_cloudformation.py
Minor fix in call to EC2 modify_instance_attribute - required to accommodate recent change in `moto`.
> Minor fix in call to EC2 modify_instance_attribute

- localstack/services/dynamodb/dynamodb_starter.py
- localstack/services/kinesis/kinesis_starter.py
Adds a restart method for kinesis, which is required for the corresponding MR in the pro version
> Kinesis state injection

- tests/integration/test_support.py
Add missing integration tests with AWS support service.
> Feat: Adding support service integration tests

- README.md
- localstack/utils/docker.py
- tests/integration/docker/test_docker.py
- tests/unit/test_dockerclient.py
Adds the support for add-host, as requested by some users.
> Add --add-host as additional allowed argument for LAMBDA_DOCKER_FLAGS

- localstack/constants.py
- localstack/services/apigateway/apigateway_listener.py
- localstack/services/stepfunctions/stepfunctions_utils.py
- localstack/utils/aws/aws_responses.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/common.py
- tests/integration/test_api_gateway.py
* Add support for synchronous invocations of StepFunctions via API GW
* Refactor/extend SFN integration tests
> Add support for synchronous invocations of StepFunctions via API GW

- localstack/services/awslambda/lambda_api.py
- localstack/services/awslambda/lambda_executors.py
- localstack/utils/testutil.py
* Add plug points for code/config initializations in LambdaExecutorPlugin
* Streamline parameters for `set_function_code(..)` functions - replacing individual args with single `LambdaFunction` arg
* Refactor `testutil.py` to deploy large Lambda zip files automatically via S3 (avoiding `RequestEntityTooLargeException`)
> Add plug points for code/config initializations in LambdaExecutorPlugin

- localstack/config.py
Closes https://github.com/localstack/localstack/issues/4545
> Aggregate valid regions accross all available partitions

- README.md
> Explained `LAMBDA_CODE_EXTRACT_TIME` configuration option in the docs

- localstack/services/edge.py
- localstack/services/route53/route53_listener.py
- localstack/utils/testutil.py
- tests/integration/lambdas/custom-runtime/function.sh
- tests/integration/test_dynamodb.py
- tests/integration/test_lambda.py
- tests/integration/test_route53.py
Main goal is to use this PR to fix test failures if testing against Pro (where test adaptions are necessary).
> Rework some integration tests to make them more robust

- README.md
- localstack/services/install.py
> Kinesis Mock 0.2.0

- localstack/services/cloudformation/models/awslambda.py
- localstack/utils/cloudformation/template_deployer.py
* Add ability to specify SelfManagedEventSource for CFN Lambda::EventSourceMapping
* Minor refactoring in logic to fetch resource state
> Add ability to specify SelfManagedEventSource for CFN Lambda::EventSourceMapping

- localstack/services/cloudformation/models/apigateway.py
* add cfn model for `AWS::ApiGateway::DomainName`
* add cfn model for `AWS::ApiGateway::BasePathMapping`
Linked issues: LSP-97
> chore(cfn): add domain and basepath mapping

- localstack/services/awslambda/lambda_api.py
- localstack/services/cloudformation/models/apigateway.py
- localstack/services/dynamodb/dynamodb_listener.py
Minor code restructuring - add extensible class abstraction for Lambda event source listeners. This will allow us to plug in additional event source listeners elsewhere...
> Add extensible class abstraction for Lambda event source listeners

- localstack/services/awslambda/lambda_executors.py
As requested in the review of #4310 , the necessary env variables for the local execution of the lambda function, are passed down through the func_details object.
> HOTFIX for Golang Lambda local execution

- tests/integration/test_sqs.py
Relates to #4470 and [change to moto](https://github.com/spulec/moto/pull/4287)
> Add test for deletion behavior of visibility-changed messages

- localstack/services/awslambda/lambda_api.py
- localstack/utils/testutil.py
- tests/integration/cloudformation/test_cloudformation_apigateway.py
- tests/integration/templates/apigw-awsintegration-request-parameters.yaml
- tests/integration/test_lambda.py
- tests/integration/test_logs.py
* fix code updates for lambdas executed in docker containers (an issue when lambda code is not updated after redeployment)
* add basic tests to test `AWS::ApiGateway::DomainName` and `AWS::ApiGateway::BasePathMapping` models
> fix(lambda): fix code updates for docker executor

- localstack/utils/common.py
- localstack/utils/server/proxy_server.py
- requirements.txt
- tests/unit/test_proxy.py
* Add/re-enable util function for creating simple SSL proxy servers. (useful to proxy and intercept SSL calls for some APIs..)
* Minor refactoring and more type hints in common utils.
> Add/re-enable util function for creating simple SSL proxy servers

- localstack/services/dynamodbstreams/dynamodbstreams_api.py
- localstack/services/es/es_api.py
- localstack/services/firehose/firehose_api.py
- localstack/services/generic_proxy.py
* refactor DDBStreams/ES/Firehose APIs to use RegionBackend classes
* add `reset()` method for region `RegionBackend` base class
> Refactor DDBStreams/ES/Firehose APIs to use RegionBackend classes

- localstack/services/kms/kms_listener.py
- tests/integration/fixtures.py
- tests/integration/test_kms.py
> Add provisional handling of grant operations in KMS

- localstack/services/dynamodb/dynamodb_listener.py
- tests/integration/terraform/dynamodb.tf
- tests/integration/terraform/provider.tf
- tests/integration/test_terraform.py
> Fix case where sse is set to false in dynamodb table terraform definition

- localstack/utils/aws/lambda_destinations.py
Resolve lambda function destination config issue by adding an additional check before sending event to the target.
Fixes #4408.
> resolve lambda function destination config issue

- tests/integration/test_sqs.py
Tests to complement the recent fixes in localstack/moto
> add sqs tests to see whether send messages doesn't overwrite attributes

- localstack/utils/aws/request_context.py
> Add helper function for region mocking

- localstack/services/es/cluster.py
- localstack/utils/serving.py
There were some issues with re-starting a terminated ElasticsearchCluster instance. This PR introduces some changes to `serving.Server` making it easier to debug and also deletes lock files of the ElasticsearchCluster before re-starting.
> refactor serving.Server to fix ElasticsearchCuster

- localstack/services/awslambda/lambda_api.py
- localstack/services/ssm/ssm_listener.py
- localstack/utils/aws/aws_responses.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/cloudwatch/cloudwatch_util.py
- tests/integration/test_lambda.py
* fix error response returned when attempting to delete non-existing Lambda
* minor refactoring of Lambda tests from `unittest` -> `pytest`
> Fix error response when attempting to delete non-existing Lambda

- localstack/services/apigateway/apigateway_listener.py
- localstack/services/apigateway/helpers.py
- localstack/services/awslambda/lambda_api.py
- tests/integration/lambdas/lambda_echo.py
- tests/integration/lambdas/lambda_handler.js
- tests/integration/test_api_gateway.py
Add test-invoke-method to API-GW - copy of PR #3553, rebased onto latest `master`.. /cc @monty16597
> Add test-invoke-method to API-GW (copy of PR 3553)

- localstack/services/dynamodb/dynamodb_starter.py
PR should fix restarting of ddb. As discussed with @thrau
> fix restarting of ddb

- localstack/services/apigateway/apigateway_listener.py
- localstack/services/apigateway/helpers.py
Minor refactoring of API Gateway for easier extraction of resource/method details from invocation context
> refactor API GW logic for easier extraction of resource/method details from invocation context

- Dockerfile
- bin/Dockerfile.base
- tests/integration/terraform/provider.tf
- tests/integration/test_terraform.py
Upgrade Terraform version in base image to fix and re-enable TF tests.
> Upgrade Terraform version in base image to fix and re-enable TF tests 

- localstack/services/cloudformation/models/ssm.py
- tests/integration/cloudformation/test_cloudformation_ssm.py
- tests/integration/fixtures.py
Adds delete support for the AWS::SSM::Parameter resource
> add delete support for AWS::SSM::Parameter

- localstack/config.py
Draft PR to see whether the CI build stays green with lazy loading as default
> make lazy service loading the default behavior

- localstack/services/cloudformation/models/logs.py
- tests/integration/cloudformation/test_cloudformation_logs.py
- tests/integration/templates/logs_group_and_stream.yaml
New AWS::Logs::LogStream resource.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-logstream.html
> Add support for CFN resource AWS::Logs::LogStream

- localstack/services/apigateway/helpers.py
- localstack/utils/aws/aws_stack.py
- tests/unit/utils/aws/test_aws_stack.py
Uses the the  botocore ArnParser utility to parse ARNs. Hopefully fixing the regression in #4894
> fix arn parsing in aws_stack

- localstack/services/awslambda/lambda_executors.py
- localstack/utils/aws/dead_letter_queue.py
- localstack/utils/bootstrap.py
- localstack/utils/common.py
- tests/integration/lambdas/lambda_integration.py
- tests/integration/test_lambda.py
- tests/unit/test_sqs.py
Support "stay open" mode for Lambda invocations.
Based on #4906 . Recreated the PR, to trigger the CI builds, and added a few minor fixes.
Replaces #4185
Closes #4123
> Support "stay open" mode for Lambda invocations (updated PR)

- localstack/services/s3/s3_listener.py
With https://github.com/spulec/moto/pull/4201 being released (quite a while ago), we can remove related fix from `localstack`.
I have tested this manually with the repo provided in #4743.
Also, I removed [the related handler from `moto`](https://github.com/spulec/moto/blob/60d9667da26e91c69232d3366039b0e8da823339/moto/s3/responses.py#L1274-L1280):
```py
if (
request.headers.get("x-amz-content-sha256", None)
== "STREAMING-AWS4-HMAC-SHA256-PAYLOAD"
):
#body = self._handle_v4_chunk_signatures(
#)
pass
```
And ran [this test](https://github.com/localstack/localstack/blob/1b690097c00ad8c163b2056c0e43b00a5fc7c29e/tests/integration/test_s3.py#L651-L651
)
```sh
$ pytest -v --tb=native -k test_s3_put_object_chunked_newlines
....
tests/integration/test_s3.py::TestS3::test_s3_put_object_chunked_newli …
```
> s3: remove fix for V4 chuck signatures

- localstack/utils/bootstrap.py
Just some minor cleanup I did while looking through bootstrap.py to better understand what it does
> minor cleanup and dead code removal in bootstrap.py

- localstack/services/edge.py
- localstack/services/s3/s3_utils.py
- localstack/utils/common.py
- localstack/utils/docker_utils.py
- localstack/utils/testutil.py
- tests/integration/test_s3.py
- tests/unit/test_s3.py
* minor refactoring of test utils
* add new util function `get_key_from_s3_url(..)`
* migrate some S3 tests from unittest->pytest
> Minor refactoring of test utils; migrate S3 tests from unittest->pytest

- localstack/services/stepfunctions/stepfunctions_listener.py
- localstack/services/stepfunctions/stepfunctions_starter.py
- tests/integration/test_stepfunctions.py
Fixes mult-region for stepfunctions in community by moving the corresponding pro code here.
Test refactoring will be added in another PR later this week.
> move stepfunction multi-region to community

- localstack/services/dynamodb/dynamodb_listener.py
Fix "localhost" region in requests headers for compatibility with NoSQL Workbench
The [AWS NoSQL Workbench](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/workbench.html) currently hardcodes "localhost" as the request region, which makes it hard for our users to create DynamoDB tables which are then accessible in the Workbench. This PR patches the incoming request headers and injects the local default region (e.g., us-east-1), to replace the "localhost" region.
> Fix "localhost" region in requests headers for compatibility with NoSQL Workbench

- localstack/services/cloudformation/models/awslambda.py
Add missing attributes for CFN Lambda::Function resources. Addresses #5005 . Manually verified that the schema of the CFN attributes corresponds to the boto3 API call parameters. (Tests still to be updated/extended - some attributes not supported in Community, hence covered elsewhere.)
> Add missing attributes for CFN Lambda::Function resources

- localstack/config.py
- localstack/utils/analytics/metadata.py
- localstack/utils/common.py
- tests/unit/utils/test_common.py
part of the effort to remove the `~/.localstack` file
* #5014
> refactor machine id cache

- localstack/utils/analytics/event_publisher.py
removes old code that was used for analytics logging. was referencing `load_config_file` blocking #5014
> remove dead logging code

- localstack/utils/common.py
- requirements.txt
- setup.py
- tests/unit/utils/test_common.py
* upgrade pyopenssl version to fix recent OpenSSL issue
* slightly refactor SSL cert generation and add tests
* minor fix for `on_stop` handler with Tailer
> Upgrade pyopenssl version to fix OpenSSL issue; slightly refactor SSL cert generation and add tests

- localstack/services/kms/kms_listener.py
- tests/integration/test_kms.py
Add support for signatures in KMS API - addresses #4992
> Add support for signatures in KMS API

- localstack/cli/lpm.py
- tests/unit/cli/test_lpm.py
With this PR, the newly introduced LocalStack Package Manager now returns a non-zero exit code in case any of the package installations failed. This allows a robust usage of the `lpm` in scripts (since it now correctly indicates failures).
> fix(lpm): return non-zero exit code if package installation fails

- localstack/services/infra.py
Update preload_services() startup hook to properly initialize and restore persistence
> Update preload_services() startup hook to initialize and restore persistence

- localstack/services/infra.py
- localstack/services/kinesis/kinesis_starter.py
- localstack/utils/common.py
Add logging to `is_port_open(..)` to debug startup port issues
> Add logging to is_port_open(..) to debug startup port issues

- localstack/services/cloudformation/models/sns.py
For sufficiently large cloud formation stacks (those with > 100 SNS topics) the default pagination of 100 was causing any  additional topics to not be created resulting in an index out of range error on line 15 of `models/sns.py` due to the topic not being found in the array. This PR ensures all topics are gathered prior to performing a lookup by topic name.
> Fixes sns topic truncation when topic count exceeds 100

- tests/integration/test_api_gateway.py
- tests/integration/test_lambda.py
- tests/integration/test_s3.py
- tests/integration/test_security.py
just a little cleanup in tests
> use unittest.mock.patch.object for override config params

- localstack/services/infra.py
- localstack/services/install.py
- localstack/services/stepfunctions/stepfunctions_starter.py
- localstack/utils/common.py
- localstack/utils/run.py
Slightly refactor StepFunctions install logic for better extensibility, reduced duplication.
> Slightly refactor StepFunctions install logic for better extensibility

- localstack/services/install.py
Reverse order of install scripts to fix Docker build.
> Reverse order of install scripts to fix Docker build

- Makefile
This PR is aim to fix the #5032 issue.
> #5032 Add minor version docker image versioning

- localstack/services/apigateway/helpers.py
- localstack/services/awslambda/lambda_api.py
- localstack/services/awslambda/lambda_executors.py
- localstack/services/cloudformation/models/iam.py
- localstack/services/sns/sns_listener.py
- requirements.txt
Minor fixes in SNS and API Gateway to accommodate recent upstream changes in moto
> Minor fixes in SNS, API Gateway after recent upstream changes

- localstack/services/logs/logs_listener.py
This PR introduces a patch for moto's `LogStream.filter_log_events` which currently does not support filter patterns: see https://github.com/localstack/moto/blob/eb93f8347e44f89ff8b4de036fe28ea6df4e1fac/moto/logs/models.py#L247-L259
With this patch, localstack-ext should automatically inject our filter pattern matching engine through `logs_listener.get_pattern_matcher`
needs testing once the localstack-ext PR is merged /cc @silv-io
> patch LogStream.filter_log_events to use get_pattern_matcher

- localstack/services/generic_proxy.py
- tests/integration/test_edge.py
Fix updating of HTTP method in message handler chain to avoid None methods. Fixes an issue with `None` HTTP methods in the handler chain - this has recently surfaced in our pipeline after the changes in #5086. /cc @dfangl @alexrashed @naspeh
> Fix updating of HTTP method in message handler chain to avoid None methods

- tests/integration/test_s3.py
The first run should be `red` and then I will update `moto-ext` with a related fix https://github.com/spulec/moto/pull/4666
Related issue: https://github.com/localstack/localstack/issues/5068
> compatibility checks for S3 copy object with metadata

- localstack/services/route53/route53_listener.py
- tests/integration/test_route53.py
Fix association of VPCs in Route53 HostedZone responses. Addresses #4312
> Fix association of VPCs in Route53 HostedZone responses

- tests/integration/terraform/versions.tf
ignore me
just triggering CI build
> WIP: fix terraform test

- localstack/services/cloudformation/models/sns.py
- localstack/services/sqs/sqs_listener.py
- localstack/utils/cloudformation/template_deployer.py
- localstack/utils/common.py
- localstack/utils/run.py
- tests/integration/docker_utils/test_docker.py
This PR improves code readability by replacing `dict` call with comprehension. Although there is nothing syntactically wrong with the current code but can be simplified more. Dictionary comprehension is more performant because we do not need to create another transient list.
> perf: Replace `dict` call with comprehension

- localstack/aws/protocol/parser.py
- localstack/aws/scaffold.py
- localstack/aws/skeleton.py
- localstack/config.py
- localstack/dashboard/infra.py
- localstack/services/dynamodb/server.py
- localstack/services/es/cluster_manager.py
- localstack/services/es/es_api.py
- localstack/services/install.py
- localstack/services/internal.py
- localstack/services/plugins.py
- localstack/services/routing.py
- localstack/utils/analytics/client.py
- localstack/utils/analytics/publisher.py
- localstack/utils/bootstrap.py
- localstack/utils/docker_utils.py
- localstack/utils/patch.py
- localstack/utils/persistence.py
- tests/integration/docker_utils/test_docker.py
- tests/integration/fixtures.py
- tests/integration/test_ses.py
- tests/unit/aws/test_skeleton.py
- tests/unit/services/test_routing.py
- tests/unit/test_common.py
- tests/unit/test_lambda.py
- tests/unit/utils/test_common.py
> perf: Replace function calls to literal syntax

- localstack/dashboard/infra.py
- localstack/services/apigateway/apigateway_listener.py
- localstack/services/apigateway/apigateway_starter.py
- localstack/services/awslambda/lambda_api.py
- localstack/services/cloudformation/cloudformation_api.py
- localstack/services/dynamodb/dynamodb_listener.py
- localstack/services/infra.py
- localstack/services/s3/s3_listener.py
- localstack/utils/aws/aws_responses.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/aws/templating.py
- localstack/utils/common.py
- localstack/utils/kinesis/kclipy_helper.py
- localstack/utils/kinesis/kinesis_connector.py
- localstack/utils/testutil.py
- tests/integration/test_api_gateway.py
- tests/integration/test_lambda.py
- tests/integration/test_s3.py
- tests/unit/test_lambda.py
This is dangerous because a mutable default value retains its mutated state on subsequent calls.
[http://pylint-messages.wikidot.com/messages:w0102](http://pylint-messages.wikidot.com/messages:w0102)
> fix: Dangerous default argument

- localstack/config.py
- localstack/services/cloudformation/models/apigateway.py
- localstack/services/events/events_starter.py
- localstack/services/firehose/firehose_api.py
- localstack/services/generic_proxy.py
- localstack/services/plugins.py
- localstack/services/s3/s3_listener.py
- localstack/services/s3/s3_utils.py
- localstack/utils/aws/aws_responses.py
- localstack/utils/common.py
- tests/integration/cloudformation/test_cloudformation_changesets.py
- tests/integration/cloudformation/test_cloudformation_stacks.py
- tests/integration/test_secretsmanager.py
The built-in function being used does not require comprehension and can work directly with a generator expression.
> perf: Remove unnecessary comprehension

- localstack/config.py
- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
Branch to make External Hostnames available for the new asf SQS provider available
> fix external host setting for sqs

- localstack/utils/common.py
- tests/unit/test_common.py
> fix acronym handling in camel_to_snake_case

- localstack/services/sns/sns_listener.py
- tests/integration/test_sns.py
Added a check for supported protocols when subscribing to a sns topic.
> SNS - added check for supported protocols at the subscription

- localstack/services/sns/sns_listener.py
> SNS - added support for email-json

- localstack/constants.py
- localstack/services/install.py
- localstack/services/kms/kms_starter.py
> Support multi arch for local-kms provider (#5233)

- localstack/services/cloudformation/cloudformation_api.py
- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
Cleanup CloudFormation logic and remove old/obsolete code and references to `moto`.
> Cleanup CloudFormation logic and remove old/obsolete code

- localstack/services/sns/sns_listener.py
**Description**
When using `elasticmq` as `SQS_PROVIDER` messages created from an SNS subscription to an SQS fifo queue fail due to missing required `MessageGroupId` and `MessageDeduplicationId` params. 
**Reproduce**
```sh
awslocal sqs create-queue --queue-name test.fifo --attributes "FifoQueue=true,ContentBasedDeduplication=false"
awslocal sns create-topic --name test.fifo --attributes "FifoTopic=true,ContentBasedDeduplication=false"
awslocal sns subscribe --protocol sqs --notification-endpoint "http://localhost:4566/000000000000/test.fifo" --topic-arn "arn:aws:sns:eu-central-1:000000000000:test.fifo"
```
```sh
awslocal sns publish --topic-arn "arn:aws:sns:eu-central-1:000000000000:test.fifo" --message "test" --message-group-id "1234" --message-deduplication-id "1234"
```
> Set MessageGroupId and MessageDeduplicationId on SQS message from SNS subscription

- localstack/services/awslambda/lambda_api.py
- tests/integration/cloudformation/test_cloudformation_stepfunctions.py
- tests/integration/templates/sfn_nested_sync2.json
Small follow-up adding a test for https://github.com/localstack/localstack-artifacts/pull/6
> Test sync:2 nested statemachine invoke integration

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
- always create SQS queue-urls dynamically based on host information
- unify queue indexing
> change SQS queue-url generation

- localstack/services/generic_proxy.py
- localstack/utils/aws/request_context.py
This refactor was included in the APIGateway ASF migration, just moved into his own PR.
> remove monkey patching and circular dependency

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
This PR refactors the queue URL resolving as discussed here: https://github.com/localstack/localstack/pull/5317#discussion_r788940482 and also potentially fixes an issue where the host_url would have a trailing slash, creating invalid queue URLs
> refactor sqs queue resolving and url rendering

- localstack/utils/aws/aws_stack.py
Clean up `aws_stack` utils, remove obsolete/unused global boto3 resources (`CUSTOM_BOTO3_SESSION`), avoid unnecessary (and unsynchronized!) modifification of `os.environ`.
Should fix the CI preflight test issues we've been seeing recently, e.g.: https://app.circleci.com/pipelines/github/localstack/localstack/3785/workflows/36f12a57-0e97-49aa-8e23-0b8b755586c8/jobs/16536/tests#failed-test-0
> Clean up aws_stack utils, remove obsolete global cached boto3 resources

- tests/integration/cloudformation/test_cloudformation_acm.py
- tests/integration/cloudformation/test_cloudformation_s3.py
- tests/integration/fixtures.py
Follow-up PR to #5355  adding the mentioned features to the fixture and applying it to the s3 cloudformation tests.
> Extend cloudformation deploy test fixture

- localstack/services/install.py
- localstack/services/kinesis/kinesalite_server.py
- localstack/services/kinesis/kinesis_mock_server.py
- localstack/services/kinesis/kinesis_starter.py
- localstack/services/kinesis/server.py
This PR refactors the `kinesis mock` and `kinesalite` starters to make use of the `Server` class abstraction as per https://github.com/localstack/localstack/issues/5265.
> Kinesis refactor server abstraction 5265

- localstack/services/apigateway/apigateway_listener.py
- localstack/utils/common.py
- tests/unit/test_apigateway.py
Fixes https://github.com/localstack/localstack/issues/4719
@whummer  It took a turner after our conversation yesterday, but after reading back the customer issue, went through the AWS and terraform documentation I think this is the proper fix and I have a better understanding on some differences between what the documentation states and the actual implementation in AWS.
> Fix issue rendering VTL templates by flatten the input

- localstack/services/route53/route53_listener.py
- localstack/services/route53/route53_starter.py
- localstack/services/s3/s3_starter.py
- requirements.txt
- tests/integration/test_route53.py
Bump `moto-ext` to latest version 3.0.0.
> Bump moto-ext to latest version

- localstack/utils/docker_utils.py
- tests/unit/test_dockerclient.py
Current Docker Client implementation does not respect some shortcomings of docker on Windows
Fixes #5347
Fixes #5348
> Fix docker client ctx manager and json issues on windows

- localstack/utils/common.py
> Add util function for deletion of None-values from dicts

- localstack/services/cloudformation/models/stepfunctions.py
- tests/integration/templates/stepfunctions_statemachine_substitutions.yaml
This PR addresses #5392.
Changes:
- Fix typo in CFN model for StateMachine type.
> Fix parameter for StateMachine type in CFN model

- .github/workflows/pro-integration.yml
- localstack/services/firehose/provider.py
- localstack/utils/aws/aws_stack.py
- requirements.txt
- tests/integration/conftest.py
- tests/integration/test_firehose.py
Just like the title says.
Resolves https://github.com/localstack/localstack/issues/5357
> add opensearch destination to firehose

- tests/integration/fixtures.py
- tests/integration/test_ec2.py
Simple EC2 test refactoring for pytest that came up during other test related work.
> Refactor ec2 integration tests to pytest

- localstack/services/cloudformation/cloudformation_api.py
I accidentally closed [Added change_set_id check for CDK #5398](https://github.com/localstack/localstack/pull/5398).
Submitting this PR in its place - apologies for the chaos.
> Removed CDK User-Agent check and replaced with generic class method

- README.md
- doc/third-party-software-tools/README.md
This PR:
- [Remove announcements from README.md](https://github.com/localstack/localstack/commit/bf2a2aa77c9c713d172186dc2ee412d073960637)
- [Add third party software tools doc](https://github.com/localstack/localstack/commit/e70aedd612118f4f701c289ee4ad85c0e4dcbc28)
> Refactor third party software tools docs + Remove Announcements 

- localstack/services/cloudformation/cloudformation_api.py
- localstack/utils/cloudformation/template_deployer.py
Minor refactoring - add default entries in CFN template dict to avoid `KeyError` - addresses #5447
/cc @dominikschubert
> Add default entries in CFN template dict to avoid KeyError

- localstack/aws/api/cloudwatch/__init__.py
- localstack/services/cloudwatch/cloudwatch_listener.py
- localstack/services/cloudwatch/provider.py
- localstack/services/providers.py
This PR migrates Cloudwatch to ASF
> Migrate Cloudwatch to ASF

- tests/integration/test_sqs.py
very small change added while comparing sqs to backup to find the cause of backup's problems
It feels kind of overkill to open a PR for this, but I wasn't quite sure how to go about it. It didn't fit the branch where I was at all and I didn't want to "sneak it in"
> adjust sqs-test for minor sanity check

- localstack/services/apigateway/apigateway_listener.py
> fix v2 path-base style without stages

- localstack/utils/docker_utils.py
- tests/integration/docker_utils/conftest.py
- tests/integration/docker_utils/test_docker.py
Updates the Docker wrapper to allow:
- Creating images from containers
- Removing images
Includes integration tests.
> Add the ability to create Docker images from running containers

- localstack/aws/protocol/serializer.py
- localstack/config.py
- localstack/dashboard/infra.py
- localstack/services/s3/s3_listener.py
- localstack/services/sns/sns_listener.py
- localstack/utils/aws/aws_models.py
- localstack/utils/common.py
- localstack/utils/kinesis/kclipy_helper.py
- localstack/utils/persistence.py
- localstack/utils/testutil.py
- requirements.txt
- tests/integration/test_s3.py
* remove `six` from dependencies 🧹 
* ( make `docker` a runtime (non-CLI) dependency (fixing dependency conflict with aws-sam-cli-local) /cc @dfangl ) - **update:** removed, to be done in a follow-up PR
> Remove `six` library from dependencies

- localstack/services/apigateway/helpers.py
- tests/integration/awslambda/test_lambda_integration.py
- tests/integration/test_api_gateway.py
> rename function name

- localstack/aws/api/redshift/__init__.py
- localstack/services/providers.py
- localstack/services/redshift/provider.py
- tests/integration/fixtures.py
- tests/integration/test_redshift.py
Migrate Redshift API to ASF, using moto fallback dispatcher.
> Migrate Redshift API to ASF

- localstack/utils/aws/aws_stack.py
- localstack/utils/testutil.py
Add region name parameter to helper functions to be able to test multi-region scenarios
> test region support

- localstack/services/moto.py
- tests/integration/test_moto.py
This adds a new moto migration utility that allows us to modify the request before it's serialized and sent to moto.
/cc @alexrashed @steffyP
> add method to call moto with a modified request

- localstack/services/apigateway/apigateway_listener.py
- localstack/services/apigateway/context.py
- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/integration.py
This PR adds support for ApiGateway SNS integration and refactor some common domain classes into different modules.
Fix https://github.com/localstack/localstack/issues/5498
> ApiGateway SNS integration

- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
Adds a helper to pause containers to the Docker client.
Includes integration tests.
> Add the ability to pause containers

- requirements.txt
Bump version of moto-ext to 3.0.4
> Bump version of moto-ext to 3.0.4

- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
Add ability to build images using Docker client (both Cmd and Sdk client).
> Add ability to build images using Docker client

- localstack/services/cloudformation/models/__init__.py
- localstack/services/cloudformation/models/ecr.py
- localstack/utils/aws/aws_stack.py
- tests/integration/cloudformation/test_cloudformation_cdk.py
- tests/integration/templates/cdk_bootstrap_v10.yaml
Adds the CDK modern bootstrap template as an integration test because LocalStack should also be able to bootstrap successfully in Community Edition.
A mock ECR repository is added here to make this work. 
**!!! DO NOT MERGE !!!** before the corresponding PRO PR is merged
> Add integration test for cdk bootstrap template v10

- localstack/services/secretsmanager/secretsmanager_starter.py
- tests/integration/test_secretsmanager.py
> [SecretsManager] AWS test scenarios about Issue #5299 and Pytest migration

- .github/workflows/welcome-first-time-contributors.yml
This PR:
- Adds a GHA workflow to track first-time pull requests and issue creators
- Directs issue creators towards Slack workspace and Pro support bot 
- Directs issue creators and pull request creators to community guidelines, code of conduct and develop guide
> CI: Add a GHA workflow to track first-time pull request and issue creators

- localstack/http/router.py
- localstack/services/edge.py
- tests/unit/http/test_router.py
I've been trying to introduce a new `BaseConverter` to match an arbitrary regex for custom endpoints. Need some direction from @thrau 😇
> Introducing a custom converter for regex

- Makefile
- localstack/services/install.py
- localstack/utils/archives.py
* minor change to allow extracting `.tgz` archives via `download_and_extract` utility.
* add a few more commands to Pro smoke tests
> Add ability to extract tgz archives via utils

- localstack/services/awslambda/lambda_starter.py
- tests/unit/test_apigateway.py
This PR addresses the changes suggested in #5503.
> Recommended changes for Lambda Patch

- localstack/services/moto.py
- setup.cfg
Bump moto-ext to latest version 3.0.5 (should hopefully fix builds on `master`).
> Bump moto-ext to 3.0.5

- localstack/services/moto.py
- tests/integration/test_moto.py
This PR fixes two issues with `call_moto` identified in #5644 blocking the migration of route53 #5639
* when boto tries to parse responses where [the location of shape member is in the header](https://github.com/boto/botocore/blob/a32e002555af61ef40f9d8622ecba75d9d99c742/botocore/data/route53/2013-04-01/service-2.json#L1611-L1615), `call_moto` would previously fail, because it [passes werkzeug `Header` objects down to boto](https://github.com/localstack/localstack/blob/1f0c03e4a14843fe4133f04c425d504e6be06bde/localstack/services/moto.py#L49-L50), which would then cause exceptions because they don't behave the same way as dictionaries ([as expected by boto](https://github.com/boto/botocore/blob/a32e002555af61ef40f9d8622ecba75d9d99c742/botocore/utils.py#L752-L757))
* getting the moto …
> fix moto dispatching for trailing slashes and response headers

- localstack/services/apigateway/apigateway_listener.py
This PR adds to the regex support for the stage "$default" in the path.
Address https://github.com/localstack/localstack/issues/5657
> handle default stage in the regex path

- setup.cfg
trying to fix the master CI build
> pin airspeed version to 0.5.18

- localstack/services/apigateway/apigateway_starter.py
- localstack/services/apigateway/integration.py
- localstack/services/awslambda/lambda_api.py
- localstack/utils/aws/templating.py
- setup.cfg
- tests/unit/test_apigateway.py
Pins airspeed version that contains the `define` directive implemented
> pin airspeed version and remove patch code

- localstack/services/kms/provider.py
- localstack/services/secretsmanager/provider.py
- localstack/utils/crypto.py
- setup.cfg
- tests/integration/test_kms.py
- tests/integration/test_secretsmanager.py
Add ability to import keys into KMS. Addresses #5702
> Add ability to import keys into KMS

- localstack/services/logs/provider.py
FilterPattern for log subscription were not applied, when using e.g.
```
logs_client.put_subscription_filter(
logGroupName=logs_log_group,
filterName=subscription_filter_name,
filterPattern="{ ($.first = \"*\") && ($.second = \"*\") }",
destinationArn=kinesis_arn,
roleArn=role_arn,
)
```
This PR applies the defined `filterPattern`, so only relevant logs are forwarded. 
**Limitations:** 
- only supported when using LocalStack Pro
- currently only json-pattern-matcher are supported
> apply filterpattern for log subscription

- .pre-commit-config.yaml
- localstack/services/dynamodb/utils.py
- localstack/utils/server/proxy_server.py
- setup.cfg
Upgrade black to fix issue with click addressed here: https://github.com/psf/black/issues/2964
> Upgrade black

- localstack/services/es/provider.py
- localstack/services/opensearch/provider.py
- tests/integration/test_es.py
- tests/integration/test_opensearch.py
> Add UpdateDomainConfig for OpenSearch and Elasticsearch

- localstack/services/s3/s3_listener.py
- tests/integration/test_s3.py
Add newline after XML preamble in S3 responses for Serverless compatibility. 
Instead of this:
```
<?xml version="1.0" encoding="UTF-8"?><LocationConstraint ...
```
We need to return:
```
<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint ...
```
Tested against real AWS.
This is required because moto is generally collapsing all S3 XML responses: https://github.com/spulec/moto/blob/3718cde444b3e0117072c29b087237e1787c3a66/moto/core/responses.py#L102-L104 . Without this change, newer versions of Serverless are failing with:
```
Serverless: [AWS cloudformation 400 1.645s 0 retries] describeStacks({ StackName: 'sls-test-local' })
Serverless: Ensuring that deployment bucket exists
Serverless: [AWS s3 200 0.022s 0 retries] getBucketLocation({ Bucket: 'localstack-websockets-serverless' …
```
> Add newline after XML preamble in S3 responses for Serverless compatibility

- localstack/services/s3/s3_listener.py
- localstack/services/s3/s3_utils.py
- tests/integration/test_s3.py
Fix S3 download of XML documents with preamble - fixes a regression introduced in https://github.com/localstack/localstack/pull/5795
> Fix S3 download of XML documents with preamble

- localstack/config.py
> Added DYNAMODB_SHARE_DB to conf

- localstack/services/cloudformation/models/kms.py
- tests/integration/templates/template34.yaml
- tests/integration/test_cloudformation.py
Minor fix: add !Ref support for `KMS::Alias` CloudFormation resources
> Add !Ref support for KMS::Alias CloudFormation resources

- localstack/services/edge.py
- localstack/utils/urls.py
This PR improves the API detection for host-based URLs and consequently makes CORS behaviour consistent. 
Fixes https://github.com/localstack/localstack/issues/5835
> fix api detection to apply custom rules and normalize CORS behaviour

- localstack/services/sns/sns_listener.py
- tests/integration/test_sns.py
This PR addresses issue #5846. Where it is stated that SNS should send a confirmation message when unsubscribing an HTTP subscription. 
Changes:
- The sns sends the confirmation if detects that the un-subscription is HTTP/HTTPS
- Test extension to validate messge.
> Sns unsubscribe should send a confirmation

- localstack/services/sqs/sqs_listener.py
- tests/integration/test_sqs.py
> add optional .fifo suffix to sqs queue url matcher

- tests/integration/test_dynamodb.py
Adds a test to verify issue #5736. It tests the PartiQL integration for the MISSING function in DynamoDB.
> Test MISSING Function with PartiQL

- .github/workflows/pro-integration.yml
- setup.cfg
> Bump moto-ext to 3.1.6.1

- localstack/services/dynamodb/provider.py
- tests/integration/test_dynamodb.py
> Fix DynamoDB TransactGetItems action

- localstack/services/dynamodb/provider.py
- tests/integration/test_dynamodb.py
Once more, as discussed in https://github.com/localstack/localstack/pull/5909
> Fix BatchExecuteStatement action in DynamoDB

- localstack/services/apigateway/apigateway_listener.py
- localstack/services/apigateway/helpers.py
- tests/unit/test_apigateway.py
Move helper functions to the `helpers` module
> move functions to helper module

- localstack/services/awslambda/lambda_api.py
- localstack/services/cloudformation/models/awslambda.py
Minor patches to fix lambda responses when creating an image with PackageType Image
> Fix lambda package type and code response

- tests/integration/test_api_gateway.py
This PR addresses the changes suggested by @calvernaz in #5871.
Changes:
- Test extension.
> Apigateway import test extension

- localstack/services/sts/provider.py
This PR moves the xml->json conversion from the `return_response` ProxyListener method into the generic `request` method. This removes the need to modify the `requests` library `Response` object, which could lead to faulty content-length headers in the new ASF gateway (which assumes headers are already correctly set).
> simplify StsAwsApiListener JSON response modification

- localstack/http/request.py
- tests/unit/http/test_request.py
This PR changes the way `localstack.http.Request` builds the headers. It now restores the originally passed headers instead of those from werkzeug's `EnvironHeaders`, which does header encoding according to the WSGI spec. 
see these issues for a discussion on the topic:
* https://github.com/pallets/werkzeug/issues/940
* https://github.com/localstack/localstack/issues/459
> allow http.Request object to retain dashes and key casing

- .github/images/survey.svg
- README.md
> chore: add user survey over README

- localstack/services/dynamodbstreams/dynamodbstreams_api.py
- localstack/services/dynamodbstreams/provider.py
Likely leftovers from ASF migration
> DynamoDB Streams - code removal

- localstack/services/cloudformation/models/events.py
- setup.cfg
- tests/integration/test_events.py
Bump version of moto-ext to 3.1.8.
> Bump version of moto-ext to 3.1.8

- .github/workflows/stale-bot.yml
This PR:
- Adds a stale bot to manage issues
Please make sure to install this [GitHub App](https://github.com/marketplace/stale) to the organization before merging this PR.
> chore: add a stale bot to manage issues

- .github/workflows/cla.yml
> fix: fix cla bot

- localstack/services/awslambda/event_source_listeners/dynamodb_event_source_listener.py
- localstack/services/awslambda/event_source_listeners/event_source_listener.py
- localstack/services/awslambda/event_source_listeners/kinesis_event_source_listener.py
- localstack/services/awslambda/event_source_listeners/sqs_event_source_listener.py
- localstack/services/awslambda/event_source_listeners/stream_event_source_listener.py
- localstack/services/sqs/sqs_listener.py
This PR removes "reactive mode" from the EventSourceListener class as it appears to be unused. More info here:
https://github.com/localstack/localstack/issues/5986
> remove unused 'reactive mode' event source listener code

- tests/integration/test_cloudformation.py
- tests/integration/test_sns.py
This PR introduce concurrency control for two tests that [started failing/flaking](https://app.circleci.com/pipelines/github/localstack/localstack/5973/workflows/ddd64c56-1f61-4bfe-900a-b069bf9a28bf/jobs/33718/tests#failed-test-0) after the ASF migration.
> fix concurrency issues of cfn and sns tests

- localstack/services/cloudformation/provider.py
- tests/integration/cloudformation/test_cloudformation_cdk.py
- tests/integration/cloudformation/test_cloudformation_stacks.py
- tests/integration/templates/cdk_bootstrap_v11.yaml
- tests/integration/templates/cdk_bootstrap_v12.yaml
- tests/integration/templates/cfn_reuse_param.yaml
Hotfix for an issue blocking our internal pipeline.
Also adds integration tests for CDK bootstrap templates v11 and v12 as well as an AWS validated test for more complicated CloudFormation behavior regarding conditional Resources/Outputs when updating stacks. This will mostly be useful later on when reworking parts of CloudFormation.
> Provide hotfix for CFn parameter updates and further CFn tests

- localstack/services/dynamodb/provider.py
- tests/integration/test_dynamodb.py
We were facing an error while dumping a dictionary with binary data. It should fix #6011. Added a test with the reported usage.
> Fix bytes size calculation with binary items

- localstack/aws/scaffold.py
This PR fixes some issues with the docs generation of ASF's scaffold:
- Sanitizes the results of the ASF Scaffold's doc creation by replacing invalid escape sequences.
- Changes the execution order of autoflake and black (format with black after manipulating the code with autoflake).
> fix ASF docs by sanitizing pandoc results

- localstack/services/cloudformation/deploy.html
- localstack/services/internal.py
This PR adds
- a fix/simplification in the CloudformationUi resource to use the request object correctly.
- a visual enhancement in the final page
> simplify cloudformation ui resource

- setup.cfg
Bump moto-ext dependency to version 3.1.9
> Bump moto-ext to 3.1.9

- .github/labeler.yml
- .github/workflows/label-pull-requests.yml
This PR:
- Adds PR size labeler action
- Adds service-specific & area-specific labels action for PRs
> ci: add labeler action

- localstack/aws/api/core.py
- localstack/services/apigateway/patches.py
- localstack/services/apigateway/provider.py
- tests/integration/test_apigateway.py
This PR removes the patch for the delete integration operation.
> remove delete integration patch

- tests/integration/test_apigateway.py
> migrate apigateway unittest tests to pytest

- localstack/aws/protocol/parser.py
- tests/unit/aws/protocol/test_parser.py
**WIP**
I've added a test for #4391
> sqs tag map parsing

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
Fixes #6044
Also removed a duplicate test
> add empty-string validation for sqs user queue attributes

- localstack/aws/protocol/validate.py
- localstack/services/sqs/query_api.py
- localstack/testing/pytest/fixtures.py
- localstack/utils/aws/client.py
- tests/integration/test_sqs.py
- tests/integration/test_validate.py
- tests/unit/aws/protocol/test_parser.py
- tests/unit/aws/protocol/test_parser_validate.py
This PR adds a first version of a server-side request validation framework for ASF based on `botocore.validate`. I think this should be seen as a prototype more than a final implementation. We should maybe discuss whether it would be better to have this as part of the `ProtocolParserError` hierarchy, and whether to do the validation inside the parsing, or if not, how we properly separate concerns (first parsing, then validating).
* Added several extensions to `botocore.validate` to make the API a bit more high-level (it can now raise exceptions).
* Added several different test suites to demonstrate the behavior
* Added some examples for how to test on server-side parameter validation in general (`tests/integration/test_validate.py`) that are validated against AWS.
* Changed the …
> add ASF prototype for server-side parameter validation

- tests/integration/awslambda/test_lambda_integration.py
This PR performs a small change to `test_lambda_integration#test_deletion_event_source_mapping_with_dynamodb`.
The test previously did not cleanup the created event source mapping.
This results in the `StreamEventSourceListener` continuing to monitor the resource.
If the resource cannot be accessed, it continues to do so and logs exceptions every second, ultimately polluting the logs and running out of urllib3 connections.
This is just a fix for the test, such that it properly removes the event source mapping after the test is done.
However, we might think about a more sophisticated error handling in the `StreamEventSourceListener` (maybe introducing a backoff-strategy, or stopping the monitoring if the resource cannot be found / 404). /cc @steffyP @SwatsonCodes
> fix cleanup of event source mapping test

- localstack/services/s3/s3_listener.py
- tests/integration/conftest.py
- tests/integration/s3/test_s3_notifications_sqs.py
- tests/integration/test_terraform.py
Adds support for s3 object tagging notifications as reported/requested in https://github.com/localstack/localstack/issues/6089
> Draft: Add object tagging notification support

- localstack/services/cloudformation/models/iam.py
- localstack/testing/pytest/fixtures.py
- tests/integration/cloudformation/test_cloudformation_iam.py
- tests/integration/cloudformation/test_cloudformation_iam.snapshot.json
Adds default name for `AWS::IAM::User` resources
> Add default UserName for AWS::IAM::User

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/provider.py
- setup.cfg
- tests/integration/files/petstore-swagger.json
- tests/integration/test_apigateway.py
- tests/integration/test_apigateway_api.py
This PR adds basic support to export OpenAPI, swagger and oas3, features for REST APIs.
/cc @whummer confirm dependency is declared correctly.
> Feature apigateway rest swagger export

- tests/integration/cloudformation/test_cloudformation_stepfunctions.py
- tests/integration/templates/sfn_retry_catch.yaml
The stack used in this test is based on the information provided in #6132
> Add test for catch/retry mechanism in StepFunctions

- localstack/services/apigateway/patches.py
- localstack/services/infra.py
- setup.cfg
- tests/integration/test_apigateway.py
- tests/integration/test_ssm.py
Bump `moto-ext` to version 3.1.10.
> Bump moto-ext to version 3.1.10

- localstack/services/dynamodb/provider.py
- tests/integration/test_dynamodb.py
This should fix #6141. We had a similar issue in #6027
> TransactWriteItem for binary data

- localstack/services/apigateway/context.py
- localstack/services/apigateway/invocations.py
> minor fix to allow authorization context permeate into lambda event

- localstack/aws/protocol/op_router.py
- localstack/aws/protocol/parser.py
- localstack/aws/protocol/service_router.py
- tests/integration/s3/test_s3.py
- tests/integration/test_s3.py
- tests/unit/aws/protocol/test_parser.py
This PR adds several fixes from the #5243 branch that either fix or adapt S3 behavior for it.
> prepare s3 for ASF gateway

- tests/integration/test_sns.py
#5395 is no longer valid. Thanks @dominikschubert
> test: invalidates #5395

- localstack/config.py
Disables the edge proxy by default in favor of #5243
> use asf gateway as default

- tests/integration/test_sns.py
This PR fixes the sns test `test_redrive_policy_http_subscription` which was still flaky. after digging a bit deeper, as indicated by the failed test logs, sometimes a "SubscriptionNotification" event would arrive at the DLQ. This is because sometimes the subscription notification would be posted to the HTTP endpoint successfully, and sometimes the HTTP endpoint would be closed before SNS could subscribe, which then caused the notification to be forwarded to the DLQ.
This PR creates a guard s.t. the subscription notification is always consumed from the HTTP endpoint before continuing.
> fix test_redrive_policy_http_subscription to correctly consume subscription notification

- localstack/services/opensearch/provider.py
- tests/integration/test_opensearch.py
This PR adds a server-side check to avoid creating domains with invalid names. 
From the spec:
```json
"DomainName":{
"type":"string",
"documentation":"<p>The name of an domain. Domain names are unique across the domains owned by an account within an AWS region. Domain names start with a letter or number and can contain the following characters: a-z (lowercase), 0-9, and - (hyphen). </p>",
"max":28,
"min":3,
"pattern":"[a-z][a-z0-9\\-]+"
},
```
I did not replicate the AWS message, since it is generated by a server-side validation framework (which we should introduce at some point using #6088)
The real AWS message is (left as future work ;-))
```
An error occurred (ValidationException) when calling the CreateDomain operation: 1 validation error detected: Value '1234' at 'domainName' failed …
```
> fix domain name validation in opensearch CreateDomain operation

- localstack/services/apigateway/context.py
- localstack/services/apigateway/integration.py
Add websocket route property to API context for better control over matching routes
> add websocket route to ApiInvocationContext

- README.md
> chore: remove banner image

- localstack/services/apigateway/context.py
Initialises invocation context websocket route.
> Initialize ws route

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
Add list_dead_letter_source_queues method for sqs. This is the last missing API method for sqs.
> add dlq-list-sources

- localstack/services/apigateway/provider.py
- tests/integration/test_apigateway_api.py
GetApiKeys currently has no mechanism for filtering the response by name, as not implemented in moto
This PR fixes the behavior, and introduces the use of a paginated list for the response as well.
As verified against AWS (see AWS validated test), name_query now serves as a filter by prefix.
> Add filtering for names provided with name_query for GetApiKeys method

- .github/workflows/dockerhub-description.yml
> CI: Add a GHA to keep DockerHub description in sync

- .github/workflows/pro-integration.yml
> CI: add paths and concurrency to pro integration workflow

- CODEOWNERS
As discussed with @bentsku, we are making him the SNS service owner
> update CODEOWNERS to make bentsku the SNS owner

- .github/images/v1-release.svg
- README.md
> docs: add v1 release banner

- localstack/constants.py
this PR updates the analytics API to v1 which was deployed and tested today
> set analytics api version to v1

- localstack/services/kms/provider.py
> Fixes #6405 Kms import key material ignores requested wrapping algo

- .github/images/v1-release.svg
- README.md
> docs: change v1 banner

- localstack/utils/container_utils/docker_cmd_client.py
> fix podman compatibility for list_containers in container utils

- localstack/utils/aws/aws_stack.py
> fix type hint compatibility in aws_stack.py

- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
Adds utility method to restart a Docker container.
> Utility to restart Docker containers

- setup.cfg
> bump moto-ext version to 3.1.13

- localstack/services/cloudwatch/alarm_scheduler.py
- localstack/services/cloudwatch/provider.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/test_cloudwatch.py
- tests/integration/test_cloudwatch.snapshot.json
- tests/unit/test_cloudwatch.py
* added `enable-alarm-actions` and `disable-alarm-actions` 
*  fix for https://github.com/localstack/localstack/issues/5562
* added snapshot test
* fixed and improved some return values in cloudwatch to match AWS responses
> added cloudwatch enable/disable actions

- localstack/utils/aws/aws_responses.py
- tests/unit/utils/aws/test_aws_responses.py
> fix MixedCase Boolean conversion when tranforming to XML

- tests/integration/apigateway_fixtures.py
- tests/integration/files/lambda_simple.js
- tests/integration/files/openapi.spec.json
- tests/integration/test_apigateway.py
- tests/integration/test_apigateway_api.py
Migrate tests from Pro version to community.
> move tests out to community

- localstack/services/apigateway/helpers.py
Remove unnecessary region lookup
> remove region lookup

- localstack/aws/scaffold.py
This PR parallelizes calls to `generate_code` when using the `upgrade` command of the scaffold script. This significantly speeds up the process of upgrading, which otherwise takes forever on your local machine. The default number of processes for `Pool` is `os.cpu_count()`.
> use multiprocessing for scaffold.upgrade

- tests/unit/test_templating.py
Add a small unit test for Velocity `map.put` function inside `$util.qr(..)` (quiet return). Addresses #5988
> Minor: add unit test for Velocity map.put function inside $util.qr

- localstack/services/dynamodb/models.py
- localstack/services/dynamodb/provider.py
- localstack/services/dynamodb/utils.py
It should depend from https://github.com/localstack/localstack-ext/pull/835 and goes on pair with https://github.com/localstack/localstack-ext/pull/892.
> Using Stores in DynamoDB

- localstack/services/ec2/provider.py
- tests/terraform/terraform-tests.yaml
TF_Tests:
- Added subnet test cases
> added subnet test cases

- tests/integration/awslambda/test_lambda_sqs_integration.snapshot.json
Fix failing tests, caused by https://github.com/localstack/localstack/pull/6598
> re-create snapshot-json to fix ordering

- Dockerfile
Referencing this issue : https://github.com/localstack/localstack/issues/6287
Added a check to initialise `destinations = []` if destinations is None
> Fix Error when Destinations are not specified (AWS SES)

- tests/integration/awslambda/functions/lambda_triggered_by_s3.py
- tests/integration/s3/test_s3_notifications_lambda.py
This PR adds a test to validate issue #5554. Also it contains a re-factorization of the previous test and the AWS validation.
> Added test for S3 notification with a presigned request

- localstack/services/apigateway/patches.py
- tests/integration/apigateway_fixtures.py
- tests/integration/test_apigateway.py
> fix patch deployment model

- localstack/services/stores.py
Adds re-entrant lock for write operations to Stores to prevent races.
Should resolve https://github.com/localstack/localstack/issues/6682
> Prevent race condition for Store write operations

- .github/workflows/terraform-tests.yml
- localstack/services/route53resolver/models.py
- localstack/services/route53resolver/provider.py
- localstack/services/route53resolver/utils.py
- localstack/utils/aws/aws_stack.py
- tests/terraform/run.sh
- tests/terraform/terraform-tests.yaml
API Added
- createResolverQueryLogConfig
- getResolverQueryLogConfig
- deleteResolverQueryLogConfig
- listResolverQueryLogConfigs
- associateResolverQueryLogConfig
- disassociateResolverQueryLogConfig
- getResolverQueryLogConfigAssociation
- listResolverQueryLogConfigAssociations
- getFirewallConfig
- listFirewallConfigs
- updateFirewallConfig
> added apis for route53resovler

- localstack/aws/handlers/cors.py
This PR fixes a small issue in the CORS handling where service-handled CORS response headers are modified by the global `CorsResponseEnricher` (even though for these requests the CORS handling should be entirely managed by the service).
It changes the `CorsResponseEnricher` such that it only removes empty CORS response headers in case the request's CORS handling is service-managed.
> fix CORS response enriching for service-managed CORS

- .circleci/config.yml
- scripts/capture_notimplemented_responses.py
- scripts/metric_aggregator.py
Creates the artifacts required for the [Docs Update Bot](https://github.com/localstack/docs/pull/231)
* adds new steps to the CircleCI and runs `capture_not_implemented_responses.py` for community and pro version
* some fixes and adaptions in related scripts, cherry-picked commits from https://github.com/localstack/localstack/pull/6453 (/cc @dominikschubert)
> add capture_not_implemented to CircleCI

- scripts/metric_aggregator.py
Fix for the _coverage_docs_utility_ script that is run in the docs-repo.
> fix for coverage_docs_utility

- localstack/services/install.py
This PR updates the SFN patch URL to the newest commit of the local patch; see [#12](https://github.com/localstack/localstack-artifacts/pull/12).
> StepFunctions patch for LoggingConfigurations

- localstack/services/redshift/provider.py
- tests/integration/test_redshift.py
Fix returning CIDR IP range for Redshift cluster security groups. Addresses #6718
> Fix returning CIDR IP range for Redshift cluster security groups

- localstack/aws/handlers/service_plugin.py
- localstack/utils/threads.py
- tests/unit/utils/test_threads.py
Adds a synchronised dictionary and serialises access per service instead of a "global" lock.
> fine-grained service locks

- localstack/services/awslambda/lambda_api.py
- localstack/services/cloudformation/models/awslambda.py
- tests/integration/cloudformation/test_cloudformation_lambda.py
- tests/integration/cloudformation/test_cloudformation_lambda.snapshot.json
- tests/integration/templates/lambda_url.yaml
Test is already validated but there's still an issue with lambda URL invokes returning dict/JSON objects.
> Add support for AWS::Lambda::Url

- setup.cfg
Pins hypercorn to 0.13.2 until #6778 is merged
> pin hypercorn to 0.13.2

- localstack/testing/snapshots/prototype.py
- tests/unit/utils/testing/test_snapshots.py
Add the possibility to have dot in fields in path marked as skipped for snapshot testing.
Having a response looking like this:
```json
"_AttributesDict": {
"access_logs.s3.bucket": "",
"access_logs.s3.enabled": "false"
}
```
If you want to skip verification of the field `access_logs.s3.enabled`, you would have a path looking like: `"$.._AttributesDict.'access_logs.s3.enabled'"`, escaping the `.`. See jsonpath library (https://github.com/h2non/jsonpath-ng)
I added a way to rebuild the full path nodes list using the jsonpath-ng library instead of splitting on `.`
Also added a test to validate the behaviour
> Fix dot in field name in skip_verification_path for snapshots

- setup.cfg
this pr upgrades moto to get the latest moto-ext changes from @bentsku  into the image.
> upgrade moto-ext to 4.0.1.post2

- localstack/services/ec2/provider.py
- tests/terraform/terraform-tests.yaml
- fixed response attributes in create and describe transit gateways
- transit gateway deletion status updated
- deleting transit gateway doesn't delete transit gateway right away
- TODO: need to create a clone to cleanup resources after 'n' hours ::::: @thrau
> fixed basic route table test cases

- localstack/services/cloudformation/models/iam.py
- tests/integration/cloudformation/test_cloudformation_iam.py
- tests/integration/cloudformation/test_cloudformation_iam.snapshot.json
- tests/integration/templates/iam_access_key.yaml
Thist PR addresses issue #6425.
> CFN support for Iam Access key model

- localstack/services/cloudformation/models/kinesis.py
- localstack/services/cloudformation/models/s3.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/cloudformation/test_cloudformation_kinesis.py
- tests/integration/cloudformation/test_cloudformation_kinesis.snapshot.json
- tests/integration/serverless/serverless.yml
This PR adds addresses #6696. With these changes  outputs of a Stream model are correct.
>  Fix CFN:Kinesis:Stream reference and attributes values.

- localstack/testing/pytest/fixtures.py
Unifies config overrides in the `_client` fixture that returns either a "local" or AWS-targeting boto client.
Configs are now properly merging when needed. 
Example usage:
```python
def test_whatever(create_boto_client):
client = create_boto_client("lambda", additional_config=Config(parameter_validation=False))
```
> Add custom config to boto test clients

- tests/integration/test_transcribe.py
Test is flaky and times out: https://github.com/localstack/localstack/pull/6822#issuecomment-1237387338
cc: @ackdav, @dominikschubert
> Increase AWS Transcribe test timeout

- localstack/services/cloudformation/models/kinesis.py
- tests/integration/cloudformation/test_cloudformation_kinesis.py
- tests/integration/cloudformation/test_cloudformation_kinesis.snapshot.json
The physical id for a Kinesis Stream Resource must be the name of the stream.
> Kinesis Stream Resource physical id must be the name

- localstack/services/stores.py
Closes https://github.com/localstack/localstack-ext/issues/950
> Add generic hint support for store bundles

- localstack/aws/handlers/cors.py
- localstack/constants.py
- localstack/services/apigateway/invocations.py
- localstack/services/generic_proxy.py
Fixes https://github.com/localstack/localstack/issues/6707
> Fix handle authorization header

- localstack/aws/api/core.py
- localstack/aws/chain.py
- localstack/http/dispatcher.py
- localstack/http/response.py
This PR adds some API docs for constructs that are exposed as public API through the extensions API.
> add more api doc for public facing APIs

- localstack/utils/collections.py
- tests/unit/utils/test_collections.py
Adding a flag to filter empty values in `select_from_typed_dict`
> Add filter in select_from_typed_dict

- .github/workflows/terraform-tests.yml
- localstack/services/dynamodb/provider.py
- localstack/services/kms/models.py
- localstack/services/kms/provider.py
- localstack/services/providers.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_kms.py
- tests/terraform/terraform-tests.yaml
Moves all the KMS logic from moto to LocalStack. Performs some remodeling of the data while at it.
It is going to be pain to read through the change, as it is extensive. I would recommend forgetting the diff and just read through the code itself as if it was written from scratch. It kinda was.
Out of 30 present tests, 27 pass (validated) against AWS.
> Migrate kms to LocalStack.

- localstack/services/kms/models.py
- localstack/services/kms/provider.py
- tests/integration/test_kms.py
The main part is adding key state constraints for KMS operations, e.g. making KMS to throw an exception if there is an attempt to use a disabled key for encryption etc.
Also some cleanups - removal of the deprecated KmsBackend and some other junk.
> [KMS] Adding key state constraints for operations.

- CONTRIBUTING.md
I guess the previous link is outdated
> correct the link for CLA.md

- localstack/services/s3/s3_starter.py
This PR is a bandaid for an issue between the old s3 provider and ASF. The issue is related to s3-website requests and the response parser in the ASF handler chain.
When calling something like `curl http://web-ui-test.s3-website.localhost.localstack.cloud:4566`, the ASF parser will interpret the request as a `ListObjects` operation because the parser doesn't know that s3-website requests are treated specially. It simply returns the content of the configured index file. Consequently, the service response parser fails and spams the logs, because it attempts to parse the response as a `ListObjectOutput`.
As a solution, we add a service response modifier that unsets the operation from the context before continuing handling the response.
To reproduce the issue with the current provider: …
> fix response parsing for s3 website requests

- Dockerfile
This addresses https://github.com/localstack/localstack/issues/6881
> Unable to build localstack with make docker-build

- localstack/services/cloudformation/models/apigateway.py
- localstack/services/cloudformation/models/awslambda.py
- localstack/services/cloudformation/models/dynamodb.py
- localstack/services/cloudformation/models/ec2.py
- localstack/services/cloudformation/models/elasticsearch.py
- localstack/services/cloudformation/models/iam.py
- localstack/services/cloudformation/models/s3.py
- localstack/services/cloudformation/models/stepfunctions.py
- localstack/utils/cloudformation/template_deployer.py
Work in progress to make the template_deployer.py leaner.
> Template logic for updates and attrs moved to resource classes

- localstack/services/ses/provider.py
- tests/integration/test_ses.py
Fix https://github.com/localstack/localstack/issues/6934
@viren-nadkarni May you please guide me to improve? This is my first PR for hacktoberfest. I'm not sure if I've done it correctly. Thank you and I hope you have a wonderful day.
> implement SES CloneReceiptRuleSet

- .circleci/config.yml
- localstack/services/awslambda/api_utils.py
- localstack/services/awslambda/event_source_listeners/adapters.py
- localstack/services/awslambda/event_source_listeners/event_source_listener.py
- localstack/services/awslambda/event_source_listeners/sqs_event_source_listener.py
- localstack/services/awslambda/event_source_listeners/stream_event_source_listener.py
- localstack/services/awslambda/invocation/lambda_models.py
- localstack/services/awslambda/invocation/models.py
- localstack/services/awslambda/invocation/version_manager.py
- localstack/services/awslambda/lambda_api.py
- localstack/services/awslambda/lambda_executors.py
- localstack/services/awslambda/lambda_utils.py
- localstack/services/awslambda/provider.py
- localstack/utils/aws/dead_letter_queue.py
- tests/integration/awslambda/test_lambda_integration_sqs.py
More or less as shortcut to get parity with the old provider by re-using most of the event source mapping / DLQ constructs.
Changes:
> Add SQS integration support for new Lambda provider

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
> SQS check max entries in batch request

- localstack/services/s3/s3_listener.py
After working on CORS for the new S3 provider, we realised that S3 would allow all origins by default if CORS was configured for the bucket. This fix cleans up all CORS headers returned by moto, then checks if CORS is configured for the bucket.
(Before, the headers would be cleaned up only if the bucket had CORS configured).
The new logic is:
1. After the response is returned from moto, clean up all CORS related headers
2. If CORS is configured for the bucket, append the specific matched CORS rule headers.
3. If CORS is not configured, append the default CORS headers of LocalStack (which you can extend with config variables).
We worked on this fix in tandem with @dfangl
This might create some issues with customers accessing S3 from websites. The quickest fix to this issue is to add the …
> fix S3 CORS allowing all by default

- localstack/services/cloudformation/models/sqs.py
- tests/integration/cloudformation/resources/test_cdk.py
- tests/integration/cloudformation/resources/test_cdk.snapshot.json
- tests/integration/templates/cfn_cdk_sample_app.yaml
WIP: currently broken when deploying
Addresses #7122
> Add test for the newest generated cdk sample-app

- tests/integration/cloudformation/api/test_drift_detection.py
- tests/integration/cloudformation/api/test_drift_detection.snapshot.json
- tests/integration/cloudformation/api/test_nested_stacks.py
- tests/integration/cloudformation/api/test_stacks.py
- tests/integration/cloudformation/api/test_stacks.snapshot.json
- tests/integration/cloudformation/test_engine.py
- tests/integration/templates/cfn_function_export.yml
- tests/integration/templates/cfn_function_import.yml
- tests/integration/templates/lambda_simple.yml
- tests/integration/templates/lambda_url.yaml
- tests/integration/templates/sns_topic_parameter.yml
- tests/integration/templates/sns_topic_simple.yaml
> More CFn features tests

- tests/integration/s3/test_s3_notifications_lambda.py
Attempts to fix a flaky test by increasing timeouts.
> Fix flaky s3/dynamodb test

- localstack/services/kinesis/packages.py
See https://github.com/etspaceman/kinesis-mock/releases/tag/0.2.6
> Update KINESIS_MOCK_VERSION to 0.2.6

- localstack/services/s3/s3_listener.py
- tests/integration/s3/test_s3.py
Fix https://github.com/localstack/localstack/issues/6553
> Bugfix: Fix S3 internalError when try to get an object

- doc/third-party-software-tools/README.md
- localstack/services/kinesis/kinesis_starter.py
- tests/integration/awslambda/test_lambda_integration_kinesis.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3_cors.py
- tests/integration/test_logs.py
- tests/unit/conftest.py
- tests/unit/test_apigateway.py
Fix internal usages of deprecation mentioned in: #7257
> Fix internal usage of deprecations

- localstack/testing/pytest/fixtures.py
- localstack/utils/testutil.py
- tests/integration/cloudformation/api/test_update_stack.py
- tests/integration/cloudformation/api/test_update_stack.snapshot.json
- tests/integration/templates/iam_policy.yml
- tests/integration/templates/sns_topic_parameter.yml
> Add Tests for CFn update stack operation

- localstack/services/visitors.py
For APIGW v2, we slightly deviate from the usual pattern of the module and attribute naming for the stores.
I figured this issue out while testing the save and load of the `ecs-app` Cloud Pod.
> APIGW2 special module naming

- localstack/services/awslambda/provider.py
- tests/integration/awslambda/conftest.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/awslambda/test_lambda_api.py
- tests/integration/awslambda/test_lambda_api.snapshot.json
This PR adds a test for getting Lambda account settings (focusing on total code size) and fixes/completes its implementation.
> Fix lambda account settings

- localstack/services/ses/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_ses.py
- tests/integration/test_ses.snapshot.json
This fixes an incorrect merge on my part 🤦
> #7128 cleanup

- localstack/services/dynamodb/utils.py
- localstack/utils/aws/aws_stack.py
- tests/integration/test_dynamodb.py
- tests/integration/test_dynamodb.snapshot.json
This PR fixes an encoding issue that occurred when updating an item.
Issue #7146 contains a nicely detailed account of the issue and how to reproduce it.
Fixes: #7146
> fix DDBstreams encoding after update

- docker-compose-pro.yml
- docker-compose.yml
Based on a discussion, this PR proposes two separate files:
- `docker-compose.yml` for community users
- `docker-compose-pro.yml` for licensed users
This PR would also involve a documentation change (which I will take care off).
> create a docker-compose pro for licensed users

- localstack/aws/mocking.py
- tests/unit/aws/test_mocking.py
Added some simple tests for generating mocked requests/responses to make sure we have basic test coverage.
> add some basic tests for localstack.aws.mocking

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
> SQS - Added check for invalid batch entry id

- localstack/services/apigateway/helpers.py
- tests/integration/test_apigateway_api.py
Rebased PR.
Closes https://github.com/localstack/localstack/pull/7339
> Fix apigateway exportType oas3 => oas30

- localstack/services/cloudformation/models/ec2.py
Changes
- Move patch of `AWS::EC2::SecurityGroup` here
> CFn refactoring pt.2

- localstack/services/ses/provider.py
Fixes https://github.com/localstack/localstack/issues/7310
> SES: Use all address fields when emitting notifications

- localstack/services/transcribe/provider.py
<https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-transcribe-speech-text-languages-swedish-vietnamese/>
> Transcribe: Add support for Vietnamese

- localstack/services/ses/models.py
- localstack/services/ses/provider.py
- tests/integration/test_ses.py
Closes https://github.com/localstack/localstack/issues/7236
> SES: Debug endpoint response schema

- CONTRIBUTING.md
Updated contribution guidelines. Polished some of the formulations and added a point to add issues before submitting PRs.
> refine contribution guidelines in CONTRIBUTING.md

- localstack/services/firehose/provider.py
Updates the firehose provider implementation to the API updates in #7281.
> update firehose provider api

- .github/workflows/cli-tests.yml
- README.md
Make sure we support Python 3.11
> Ensure we support Python 3.11 for the CLI

- localstack/services/awslambda/urlrouter.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/awslambda/test_lambda.snapshot.json
Adds multiple lambda responses to check how AWS converts these when calling via URL
> Cover additional Lambda URL response handling cases

- localstack/services/edge.py
While working on migrating away from ProxyListeners, I tried to test the behaviour of migrated services. It happens that S3 was completely broken with `LEGACY_EDGE_PROXY=1`, which would break CloudTrail tests, because the default account id in moto is `123456789012` and we would use `000000000000` while trying to access moto backends, which would lead to resource not existing. 
As we don't test the old edge proxy anymore, I didn't add test but it's easily reproducible locally. 
```bash
$ LEGACY_EDGE_PROXY=1 localstack start
$ awslocal s3 mb s3://test-bucket
make_bucket: test-bucket
$ awslocal s3 cp ./Makefile s3://test-bucket/makefile                    
upload: ./Makefile to s3://test-bucket/makefile                 
$ awslocal s3api get-object --bucket test-bucket --key makefile …
```
> fix passing account id to moto in legacy edge proxy

- localstack/aws/protocol/serializer.py
- tests/unit/aws/protocol/test_serializer.py
This PR addresses an issue with the streaming body serialization in ASF.
Previously, the event streaming serialization has only been tested with Kinesis (since it was the only implemented example).
With the ASF S3 provider, a new streamed operation has been implemented (S3's SelectObjectContent).
Unfortunately, the serialization did not work correctly for the specific operation due to two small bugs:
- The streaming event name differs here from the shape name (in contrast to the Kinesis API), which broke an assumption previously made. This is fixed by using the correct name of the shape member (instead of the name of the shape itself).
- The streaming serialization caused issues with non-JSON serializations (S3 is `rest-xml`) due to a missing event payload member lookup.
Thanks to …
> fix S3 ASF event stream serialization

- localstack/services/awslambda/provider.py
Follow up of https://github.com/localstack/localstack/pull/7482
Fixes Daniel's naming comment.
> Fix naming from Lambda revisions PR

- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/patches.py
Integration support for APIGateway V1 and AppSync.
Also fixed a bug in the apigateway PATCH request from CDK.
refer to this - https://aswinkumar4018.medium.com/aws-api-gateway-as-a-proxy-to-appsync-5d4dcd609a2c
> Feature: Integration between API Gateway V1 and AppSync

- localstack/services/kinesis/packages.py
See https://github.com/etspaceman/kinesis-mock/releases/tag/0.3.4 and https://github.com/etspaceman/kinesis-mock/releases/tag/0.3.3
> Update Kinesis Mock to 0.3.4

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/models/iam.py
- localstack/services/cloudformation/models/sns.py
- localstack/services/cloudformation/service_models.py
This makes the template deployer stop relying in a list of resource and checks if the resource  model implements the update_resource method
> refactor list of updatable resources

- localstack/services/ec2/models.py
- localstack/services/ec2/provider.py
- localstack/services/route53resolver/provider.py
- localstack/services/route53resolver/utils.py
- tests/integration/test_ec2.py
This PRs solves #7608 (thanks to @whummer for the pickling magic). Introduces a simple integration test that tries to pickle a backend following the creation of some state. Over time, we might think about spreading this pattern to other services.
> Patching EC2 subnets for pickling

- localstack/services/cloudformation/models/ec2.py
- tests/integration/cloudformation/resources/test_ec2.py
- tests/integration/cloudformation/resources/test_ec2.snapshot.json
- tests/integration/templates/internet_gateway.yml
The Ref of the resource model is fixed now. This PR addresses #7665.
Changes:
-  Resource model implements the resource handler to store the InternetGatewayId as PhysicalResourceId
-  The resource model now uses the InternetGatewayId to fetch the state
- Test to validate the changes.
> fix internet gateway attrs

- localstack/testing/pytest/fixtures.py
- tests/integration/apigateway_fixtures.py
- tests/integration/conftest.py
- tests/integration/test_apigateway.py
This PR started by just adding the fixture to the testing package, but end up adding more baggage to it.
> add rest api fixture

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/integration.py
- localstack/services/apigateway/invocations.py
- localstack/testing/pytest/fixtures.py
- localstack/utils/objects.py
- tests/unit/test_apigateway.py
Improve support for request parameters.
Terraform Sample - https://github.com/localstack/localstack-terraform-samples/tree/master/apigateway-appsync-integration
Links to: https://github.com/localstack/localstack/pull/7729
> Improve support for request integration parameters

- localstack/services/events/provider.py
- tests/integration/test_events.py
- tests/integration/test_events.snapshot.json
This PR adds the validation for the Targets Ids in the Put Target Operation. Addresses #7567
Changes:
- validation
- tests
> fix event target id validation

- localstack/services/kinesis/packages.py
See bugfix in https://github.com/etspaceman/kinesis-mock/releases/tag/0.3.7 and https://github.com/etspaceman/kinesis-mock/releases/tag/0.3.9
> Update Kinesis Mock to 0.3.10

- localstack/services/cloudformation/models/apigateway.py
- tests/integration/cloudformation/resources/test_apigateway.py
- tests/integration/cloudformation/resources/test_apigateway.snapshot.json
Enhance CloudFormation parity for policy of API Gateway REST APIs . Addresses #7773
> Enhance CloudFormation parity for policy of API Gateway REST APIs

- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR contains AWS validated test case for the issue mentioned in #5025.
> test: list object version with prefix and delimiters

- localstack/utils/platform.py
This PR adds a CPU arch standardisation helper for reusability.
> Refactor machine arch name helper

- localstack/runtime/analytics.py
This adds some basic logging of information about the container. Currently it extracts the image variant if available (community, pro, full, ...), and includes a heuristic whether the docker socket is mounted into the container.
We can extend this as needed.
> add logging for basic container information

- localstack/services/stepfunctions/provider.py
- localstack/services/stepfunctions/stepfunctions_starter.py
Adding the persistence plugin hooks to the StepFunctions provider.
> Added hooks to the SFN provider

- localstack/services/dynamodb/provider.py
Closes https://github.com/localstack/localstack/issues/7597
Supersedes https://github.com/localstack/localstack/pull/7598
> DynamoDB: Fix unprocessed item not added to response

- localstack/testing/snapshots/transformer_utility.py
Add Apigateway V2 transformers
> add apigatewayv2 transformers

- localstack/services/apigateway/provider.py
- tests/integration/apigateway/test_apigateway_api.py
- tests/integration/apigateway/test_apigateway_api.snapshot.json
- tests/integration/apigateway/test_apigateway_basic.py
For `RequestValidator` API in apigateway : 
- Wrote create, list, delete, update, invalid operations, etc. test cases 
- Resolved issues for json patching, invalid messages, conflicts in responses, etc. 
- Fix existing test case- `test_request_validator`
> Added test cases and fixed issues for RequestValidator apigateway

- localstack/services/plugins.py
Follow up of https://github.com/localstack/localstack-ext/pull/1500
> Removing state serializer interfaces

- localstack/aws/api/apigateway/__init__.py
- localstack/services/apigateway/provider.py
- tests/integration/apigateway/test_apigateway_api.py
- tests/integration/apigateway/test_apigateway_api.snapshot.json
For `DocumentationPart` API in apigateway : 
- Wrote create, list, delete, update, invalid operations, etc. test cases 
- Resolved issues for json patching, invalid messages, conflicts in responses, etc.
> Added test cases and fixed issues for DocumentationPart apigateway

- tests/integration/awslambda/test_lambda_common.py
Community tests in PRO were still failing. We'll split these properly into separate PRO and Community tests instead of relying on the tests being executed as "community tests in PRO".
The corresponding tests in PRO will be added a bit later since we need to port the multiruntime lambda fixture first. This should unblock the pipeline though.
> Remove pro check and conditional client config for endpoint tests

- localstack/services/apigateway/integration.py
- localstack/services/apigateway/templates.py
- setup.cfg
Minor fix to handle template expressions for WebSockets API for the simplest case, non VTL expressions.
https://docs.aws.amazon.com/apigateway/latest/developerguide/websocket-api-data-transformations.html#apigateway-websocket-api-template-selection-expressions
Handles https://github.com/localstack/localstack/issues/7737
> Fix websocket template expression

- localstack/services/awslambda/invocation/executor_endpoint.py
- localstack/services/awslambda/packages.py
Depends on https://github.com/localstack/lambda-runtime-init/pull/17
> Log reported runtime init error

- README.md
> update readme to release 2.0

- localstack/testing/pytest/fixtures.py
> small fixture fix

- localstack/services/transcribe/provider.py
- localstack/testing/pytest/fixtures.py
Fixes https://github.com/localstack/localstack/issues/8044
> Transcribe: Return TranscriptionJob in StartTranscriptionJob response

- CODEOWNERS
Update Lambda code owners as discussed with @dominikschubert
> Update Lambda code owners

- localstack/aws/handlers/service.py
- localstack/aws/skeleton.py
- localstack/utils/aws/request_context.py
- tests/integration/aws/test_app.py
- tests/unit/aws/handlers/service.py
- tests/unit/aws/test_skeleton.py
> Display custom error message for NotImplementedErrors

- localstack/services/s3/provider.py
When debugging a user issue in Community Slack (#8073), we've come across an issue where the SDK would not add the `content-length` header for `CreateBucket` operation targeting `us-east-1`, as the body would be empty. Moto would reject the request (see the issue here: https://github.com/getmoto/moto/issues/6179) and the check seems it should not concern `CreateBucket`.
As a bandaid fix, we can manually add the `content-length` header to the request if it's missing.
You can test the fix by running `curl -XPUT http://localhost:4566/testbucket`, which recreate the request made by the user in the first place, with no `content-length`:
```python
2023-04-05T12:52:04.111867997Z 2023-04-05T12:52:04.111  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.CreateBucket => 411 (411); …
```
> implement content-length fix for CreateBucket

- localstack/services/cloudformation/models/iam.py
- tests/integration/cloudformation/resources/test_iam.py
- tests/integration/cloudformation/resources/test_iam.snapshot.json
- tests/integration/templates/iam_policy_role.yaml
- tests/integration/templates/iam_policy_role_updated.yaml
Update policy PR for issue #7963
> Cfn::IAM::Policy update

- localstack/services/firehose/provider.py
- localstack/services/sns/publisher.py
> sns firehose client update

- localstack/aws/serving/asgi.py
- localstack/constants.py
- localstack/http/asgi.py
- localstack/services/secretsmanager/provider.py
- localstack/services/sns/models.py
- localstack/services/sns/provider.py
- localstack/services/sqs/provider.py
- localstack/services/sqs/utils.py
- setup.cfg
- tests/integration/secretsmanager/test_secretsmanager.py
- tests/integration/secretsmanager/test_secretsmanager.snapshot.json
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
- tests/integration/test_sqs.py
- tests/integration/test_sqs_backdoor.py
- tests/unit/http_/conftest.py
- tests/unit/http_/test_asgi.py
- tests/unit/test_sns.py
- tests/unit/test_sqs.py
PR for release/v2.1 branch
Checklist:
> v2.1 release PR

- localstack/services/dynamodb/utils.py
- tests/unit/test_dynamodb.py
This is a utils extracted and modified from `botocore`, to allow simple transformation of python types into DDB types accepted by the SDK. This was used in my hackathon project for an IoT feature, and I'm extracting it now in community following @viren-nadkarni advice.
Also added a unit test that showed the first implementation was wrong in some aspects. 
also see https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html
> add dynamodb utils to transform python values into DDB types

- localstack/deprecations.py
- localstack/services/awslambda/invocation/docker_runtime_executor.py
- localstack/services/awslambda/invocation/lambda_service.py
- localstack/services/awslambda/plugins.py
Follow-up on https://github.com/localstack/docs/pull/607
> chore: update lambda doc links

- localstack/services/transcribe/provider.py
- tests/integration/test_transcribe.py
- tests/integration/test_transcribe.snapshot.json
Added fix and test case if transcription job name is same in `StartTranscriptionJob`
> Add same transcription job name case

- localstack/services/events/provider.py
- localstack/utils/aws/message_forwarding.py
This PR updates the Kinesis Firehose client for EventBridge Integration
> update firehose client for eventbridge

- localstack/utils/aws/message_forwarding.py
This PR updates the Cloudwatch Logs client in the EventBridge message publisher
> update cloudwatch logs client in message publisher

- localstack/services/dynamodb/provider.py
- localstack/services/dynamodbstreams/dynamodbstreams_api.py
Add visit to the `dynamodbstreams` store in the DDB provider.
It should address #6321 (persistence test [here](https://github.com/localstack/localstack-ext/pull/1704)).
> Add ddbstreams stores visit in DDB provider

- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR adds test to check the behaviour and the fix of https://github.com/getmoto/moto/pull/6295
This PR builds on #8326 
This will confirm the fix for #8183
> add test for S3 LegalHold when targeting object version

- .github/workflows/tests-pro-integration.yml
This PR fixes our pipeline which tests our integration from Community with Pro.
Thanks @viren-nadkarni for the fix in our pro pipelines, I just migrated the change to this pipeline.
> fix postgres installation in test pipeline

- localstack/testing/pytest/fixtures.py
Minor extension to our IAM test fixtures, allow to pass in a boto3 client, to facilitate multi-region tests.
This requirement came up while working on a test in the upstream -ext repo, where resources should be targeting non-default regions.
> [minor] Allow passing boto3 client to IAM fixtures to facilitate multi-region tests

- localstack/services/awslambda/invocation/runtime_environment.py
- localstack/utils/container_utils/docker_sdk_client.py
Adds additional debugging information to identify issues leading to raised errors when creating a runtime environment for a lambda function.
> Add logging of exceptions during Lambda runtime environment create

- localstack/utils/aws/client_types.py
Adds SSOAdminClient to list of client types
> add mypy client type for sso-admin

- setup.cfg
Bring in S3 cross-account support https://github.com/getmoto/moto/pull/6333
cc: @macnev2013
> Bump moto-ext to 4.1.10.post2

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/models/ec2.py
- localstack/services/cloudformation/models/iam.py
- localstack/services/cloudformation/service_models.py
> Remove get_physical_resource_id from CFn GenericBaseModel

- localstack/config.py
- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/engine/types.py
- localstack/services/cloudformation/models/events.py
- localstack/services/cloudformation/resource_provider.py
- localstack/services/opensearch/resource_providers/domain.py
- localstack/services/ssm/resource_providers/aws_ssm_parameter.schema.json
- localstack/services/ssm/resource_providers/parameter.py
- tests/integration/cloudformation/resource_providers/opensearch/test_domain.py
- tests/integration/cloudformation/resource_providers/ssm/test_parameter.py
- tests/integration/cloudformation/resource_providers/ssm/test_parameter.snapshot.json
- tests/integration/cloudformation/resources/test_ssm.py
- tests/integration/templates/resource_providers/opensearch/domain.yaml
- tests/integration/templates/resource_providers/ssm/parameter.yaml
This PR adds an adaptor for the `GenericBaseModel` resource providers, which is invoked when a new resource provider is not found. It creates two "new style" resource providers: SSM parameter and OpenSearch Domain.
This behaviour is hidden behind a new feature flag `CFN_RESOURCE_PROVIDERS_V2` which must be enabled to opt-in to the new behaviour.
Providers are enabled by setting `CFN_RESOURCE_PROVIDERS_V2=1` and ensuring that you have re-build the entrypoints list with `make entrypoints`. Then new providers are used in preference to old ones.
> CFn: Integrate new resource provider deploy system

- localstack/services/cloudformation/engine/template_deployer.py
It als now uses the `get_resource_type` method from the resource provider which will now be patched by -ext for correct resource lookup
> Remove unused methods from template deployer

- localstack/services/cloudformation/resource_provider.py
Fixes a failure in -ext right now where custom resources are broken since we can't derive a proper client from it automatically based on the type name. 
With this change we delay trying to build a boto client into another branch  (basically `not callable(func.get("function"))`) where we actually would have to build the client or fail otherwise. This allows resources that don't even use an auto-derived boto client to still work.
> Delay boto client lookup for custom handler functions like in custom resources

- localstack/services/acm/provider.py
We have already the same custom pickling approach implemented [here](https://github.com/localstack/localstack-plugin-persistence/blob/main/localstack_persistence/pickling/reducers/services/acm.py). This is redundant.
> Removing duplicate pickling logic for ACM

- localstack/utils/aws/message_forwarding.py
this small PR updates the events client in utility message_publisher.py
> replace events client in message publisher

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/integration.py
- localstack/services/apigateway/provider.py
- tests/integration/apigateway/test_apigateway_api.py
- tests/integration/apigateway/test_apigateway_api.snapshot.json
- Adds log, latency and multiValueHeaders to the response for the "Test Invoke Request"
- Add snapshot test.
> invoke test method and status code

- setup.cfg
Routine moto bump
Ext test suite is :green_circle:
> Bump moto-ext to 4.1.12.post1

- localstack/utils/analytics/metadata.py
This PR uses the docker socket (if available) to determine a machine id and the system. This gives us information about the host rather than only about the container. The machine ids are now also prefixed so we can determine how they were generated. Note that we always hash any real machine IDs for privacy purposes.
* `gen_` generated by localstack
* `dkr_` docker daemon id
* `sys_` machine id from the system file `/etc/machine-id`
Moreover, the PR uses the `LOCALSTACK_AUTH_TOKEN` as `api_key` field if available in preparation for our new licensing scheme.
> use docker system info for client metadata if possible

- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
- Added test cases for `if-match` and `if-none-match` headers
https://github.com/localstack/localstack/issues/5345
> added test case for if-match headers for s3

- localstack/config.py
Prerequisite to implement https://github.com/localstack/localstack-plugin-persistence/issues/22.
> Add config var for snapshot flush interval

- localstack/services/awslambda/api_utils.py
- localstack/services/awslambda/invocation/lambda_models.py
- localstack/services/awslambda/provider.py
- tests/integration/awslambda/test_lambda_api.py
- tests/integration/awslambda/test_lambda_api.snapshot.json
- tests/integration/cloudformation/api/test_stacks.py
- tests/integration/templates/cfn_parameter_list_type.yaml
> Add basic CRUD support for Lambda VpcConfig

- localstack/services/s3/provider.py
- localstack/services/s3/provider_stream.py
Follow up from #8704, the detection of `aws-chunked` encoding was changed to follow the S3 specs, it appears however that the SDK are not following it. Reverse back to the previous detection using `x-amz-content-sha256`. 
Related comment: https://github.com/localstack/localstack/pull/8704#discussion_r1265118283
Fixes #8703
> fix detection of S3 aws-chunked encoding

- localstack/services/cloudformation/models/ssm.py
- tests/integration/cloudformation/resources/test_ssm.snapshot.json
- tests/integration/templates/ssm_maintenance_window.yml
Work for some errors not catched when deploying an SSM PatchBaseline and MaintenanceWindowTasks.
> fix issues with SSM Patchbaseline

- README.md
Changes the current release to 2.2.0, and adds a link to the discuss post describing the awesome changes :rocket:
> Update Readme for 2.2.0 release

- localstack/services/cloudformation/engine/yaml_parser.py
- tests/integration/cloudformation/engine/test_conditions.py
- tests/integration/templates/conditions/conditional-in-conditional.yml
This PR allows a Conditional ref another Conditional.
> fix support for conditional refering to another conditional

- localstack/aws/api/scheduler/__init__.py
- localstack/services/providers.py
- localstack/services/scheduler/provider.py
- tests/integration/test_scheduler.py
This is one of the most requested AWS service.
EventBridge Scheduler has a relatively simple API with only about [a dozen operations](https://docs.aws.amazon.com/scheduler/latest/APIReference/API_Operations.html). For now, this PR creates a basic Moto dispatcher provider, but there's scope to add emulated functionality.
See https://discuss.localstack.cloud/t/support-for-eventbridge-scheduler/283
Closes https://github.com/localstack/localstack/issues/7268
> Introducing EventBridge Scheduler

- README.md
Small fix to update the twitter bade to link the new twitter account.
I just stumbled across it and created a PR (otherwise I would forget about it again) 😛
> fix twitter handle in readme

- localstack/services/s3/provider_stream.py
We overlooked the read/write issue for S3, only locking for position in the stream but not modification of the underlying stream during iteration while returning responses.
We can make use of the already installed dependency `readerwriterlock` (https://github.com/elarivie/pyReaderWriterLock) with a nice explanation of the problem: https://wikipedia.org/wiki/Readers–writers_problem
Basically, when a thread is currently returning a S3 Object, it will read chunk by chunk from a stream. We want multiple threads to be able to read the same stream, so we can't fully lock around the iteration. But we want to lock writing at the time of the iteration, so that the underlying stream is not being modified while a "reader" is currently iterating and returning the object. 
Edit: I tried to remove the …
> implement read/write lock for s3 stream

- localstack/services/s3/provider_stream.py
There has been so CI failures for the streaming provider lately regarding releasing of un-acquired locks, but all of them were used with context managers, which means they had to be acquired at some point?
I think the[ documentation of the library](https://github.com/elarivie/pyReaderWriterLock) was a bit misleading, having to generate a lock every time you need one seems quite weird, but it seems it's how the library is supposed to be used and that's why it was failing, my mistake.
> fix S3 streaming usage of readwrite lock

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
- tests/aws/s3/test_s3.py
This PR builds on #8786, and finishes to introduce basic operations.
- CreateMultipartUpload
- UploadPart
- UploadPartCopy
- CompleteMultipartUpload
- AbortMultipartUpload
- ListParts
- ListMultipartUploads
> implement S3 native multiparts operations

- localstack/services/s3/cors.py
- localstack/services/s3/provider.py
- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
- localstack/services/s3/validation.py
- tests/aws/s3/test_s3_cors.py
This PR implements CORS for the new S3 native provider. This is basically just to make it compatible between both provider.
> implement S3 native CORS

- localstack/services/kinesis/kinesis_mock_server.py
Fix for #8895 
Sets INITIALIZE_STREAMS for the kinesis-mock
Description of how to test the changes
> Set INITIALIZE_STREAMS for Kinesis Mock

- localstack/http/asgi.py
- tests/unit/http_/test_asgi.py
During the implementation of the new S3 provider, we noticed that `Response.close` is never called on the werkzeug response, and therefore not propagated to other underlying objects. The test I added worked when serving it directly through the werkzeug server, and I found it's calling close [here](https://github.com/pallets/werkzeug/blob/47c6bd568efd0870d413c27be316c2b4eee74486/src/werkzeug/serving.py#L360-L361), where `application_iter` is the `Response` object.
We actually had no analogous call in our ASGI/WSGI bridge, so this PR adds that.
* Encapsulate the sync/async iterable wrapper into a class and propagate any calls to `aclose` to the underlying `close` method.
I was briefly worried that this may break [`test_chunked_transfer_encoding_client_timeout`](https://github.com/localstack/ …
> fix close call propagation of response in asgi/wsgi bridge

- .github/workflows/tests-pro-integration.yml
Currently the community tests against pro are failing because a postgres dependency has been updated in the pipeline.
This test updates the dependency
Update postgres requirement to `postgresql-14=14.9-0ubuntu0*`
Link to actions run where the packages install successfully: https://github.com/localstack/localstack/actions/runs/5901796175/job/16008610290?pr=8936#step:9:114
> Update postgres dependency in pipeline

- tests/aws/services/stepfunctions/conftest.py
Speeds up build by skipping local checks for StepFunction's role assume.
Skip SFN can assume role check in create state machine iam role fixture.
> [SFN] Skip local iam role assume check

- localstack/services/sqs/models.py
- localstack/services/sqs/provider.py
- localstack/services/sqs/utils.py
- tests/aws/services/sqs/test_sqs.py
- tests/aws/services/sqs/test_sqs.snapshot.json
> Validate required fields in Fifo batch messages

- tests/aws/services/s3/test_s3.snapshot.json
From the last report, it seemed some S3 snapshots were not refreshed. I think this was due to my rebasing, I must have failed some conflicts and kept the old date. 
Refreshed the missing snapshots, only the dates are changed, it feels a bit silly but at least we're sure it works!
> refresh missing S3 snapshot

- localstack/utils/bootstrap.py
We should not be running the container in privileged mode if we don't need to.
Do not run the LocalStack container in privileged mode (from the CLI at least).
> Don't run in privileged mode

- localstack/services/logs/provider.py
- localstack/services/s3/legacy/s3_starter.py
- localstack/services/s3/provider.py
- localstack/services/s3/provider_stream.py
- localstack/services/s3/utils.py
- localstack/services/secretsmanager/provider.py
- setup.cfg
- tests/aws/services/s3/test_s3.py
- tests/aws/services/secretsmanager/test_secretsmanager.py
Bring in the latest Moto changes.
Stop using the `clean_key_name` that was removed in https://github.com/getmoto/moto/pull/6602/
> Bump moto-ext to 4.2.0.post1

- tests/aws/services/stepfunctions/utils.py
Flaky test `TestLoanBrokerScenario.test_stepfunctions_input_recipient_list[step_function_input0-SUCCEEDED]` failing with `ExecutionDoesNotExist` while running `stepfunctions_client.get_execution_history`
* indicating that the execution cannot be found yet, even though it was started before. 
* added try-except block to catch `ExecutionDoesNotExist` in the helper `_await_on_execution_events`
> fix flaky stepfunction test

- Dockerfile
The following message appears in build logs when the relevant layer is not cached:
```
#9 7.850 Processing triggers for libc-bin (2.31-13+deb11u6) ...
#9 8.320
#9 8.320 ================================================================================
#9 8.320 ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#9 8.320 ================================================================================
#9 8.320
#9 8.320                            SCRIPT DEPRECATION WARNING
#9 8.320
#9 8.320
#9 8.320   This script, located at https://deb.nodesource.com/setup_X, used to
#9 8.320   install Node.js is deprecated now and will eventually be made inactive.
#9 8.320
#9 8.320   Please visit the NodeSource distributions Github and follow the
#9 8.320   instructions to …
```
> Update nodejs install step

- localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service.py
- localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_sns.py
- tests/aws/services/stepfunctions/templates/services/services_templates.py
- tests/aws/services/stepfunctions/templates/services/statemachines/sns_publish.json5
- tests/aws/services/stepfunctions/templates/services/statemachines/sns_publish_message_attributes.json5
- tests/aws/services/stepfunctions/v2/services/test_sns_task_service.py
- tests/aws/services/stepfunctions/v2/services/test_sns_task_service.snapshot.json
Adds support for SNS optimised integration.
Added optimised service task resolver for SNS.
> [SFN] Add support for SNS

- localstack/testing/scenario/provisioning.py
Some improvements for the provisioning.
* add optional parameter `delete_bucket` for the `cleanup_s3_bucket` helper
* don't assume stack-name exists for `get_stack_outputs`
> cdk provisioning improvements for testing

- localstack/services/ec2/provider.py
issue #9089 
adds zone type to zones response
> add zone type to az response

- localstack/utils/bootstrap.py
GATEWAY_LISTEN is propagated to the container in its default form (127.0.0.1:4566) if not specified on the command line. This overrides any customisations that the Pro container configuration has performed (in particular, adding port 443 to GATEWAY_LISTEN).
* Update the configurators to ensure that GATEWAY_LISTEN is taken from the configuration
> Ensure GATEWAY_LISTEN is taken from the configuration

- localstack/services/stepfunctions/asl/component/state/state_execution/state_task/state_task.py
- localstack/services/stepfunctions/asl/component/state/state_execution/state_task/state_task_lambda.py
- tests/aws/services/stepfunctions/templates/services/services_templates.py
- tests/aws/services/stepfunctions/templates/services/statemachines/lambda_input_parameters_filter.json5
- tests/aws/services/stepfunctions/v2/services/test_lambda_task.py
- tests/aws/services/stepfunctions/v2/services/test_lambda_task.snapshot.json
Resolves issue for which lambda resource task would forward extra incorrect arguments if these were specified in Parameters declaration. 
The issue is resolved by filtering by the supported parameters of the lambda invoke api action.
> [SFN] Parameters filtering for lambda resource tasks

- README.md
Changes the current release to 2.3.0.
> Update readme for v2.3.0

- localstack/services/lambda_/provider.py
Addresses https://github.com/localstack/localstack/issues/8347
Restores provisioned concurrency using the version manager of each function. This also fixes persistence reloading issues because listing provisioned concurrency relies on the correct state in the version manager.
See ext PR https://github.com/localstack/localstack-ext/pull/2155
Related to functional concurrency test: `tests.aws.services.lambda_.test_lambda.TestLambdaConcurrency.test_provisioned_concurrency`
> Fix persistence for provisioned concurrency

- tests/aws/services/transcribe/test_transcribe.snapshot.json
Update snapshot as per the snapshot age tracker for `transcribe` service. 
This PR updates the snapshot tests.
> transcibe: update snapshots

- localstack/utils/aws/templating.py
- setup.cfg
Move patches for airspeed upstream and bump airspeed version
Update the new airspeed release.
> move airspeed patches

- localstack/utils/aws/aws_stack.py
We introduced a new internal Boto client library `localstack.aws.connect_to`. Subsequently the codebase was refactored to use this new client library and the old library in `localstack.utils.aws.aws_stack` was marked obsolete.
This PR removes these deprecated methods as they are no longer used in either codebases.
Ext Integration Tests passing :heavy_check_mark: # 2735 
- https://github.com/localstack/localstack/pull/8636
- https://github.com/localstack/localstack/pull/8748
- https://github.com/localstack/localstack/pull/8858
- https://github.com/localstack/localstack/pull/9120
> Remove the deprecated internal boto client library

- setup.cfg
Fixes https://github.com/localstack/localstack/issues/8921
cc: @giograno 
Ext Integration Tests pass :heavy_check_mark: # 2765
> Bump moto-ext to 4.2.6.post1

- localstack/services/lambda_/provider.py
Lambda has trouble resolving VPCs during VPC config construction when requests are made from a non-default account ID.
This PR ensures that Lambda looks for VPCs in the same account/region as the requestor when building VPC config.
> Lambda: Fix VPC resolution in non-default accounts

- setup.cfg
Brings in:
- https://github.com/getmoto/moto/pull/6933 @bentsku 
- https://github.com/getmoto/moto/pull/6930
Ext Integration Tests passing :heavy_check_mark:  # 2912
> Bump moto-ext to 4.2.6.post2

- localstack/services/cloudwatch/provider_v2.py
> Tag Operations for Cloudwatch v2 provider

- localstack/services/stepfunctions/asl/component/state/state_wait/wait_function/wait_function.py
Currently the reentrant wait function used by the interpreter for StepFunctions v2 incorrectly keeps track of the time elapsed between wait intervals. This PR addresses such issues.
Simplified reentrant wait function, changed time tracking to use local epochs instead of date seconds.
> [SFN] Fix reentrant wait function 

- localstack/services/opensearch/provider.py
- tests/aws/services/opensearch/test_opensearch.py
Fixes #9556
This PR makes `CreateDomain`/`DescribeDomain`/`DescribeDomainConfig` responses include the `DomainEndpointOptions` from the request that created the domain, instead of returning a hard-coded response with `"CustomEndpointEnabled": false`. This also makes custom endpoints work for domains that were loaded from persisted state.
I also brought the `CreateDomain` request validation more into line with real AWS, in that it now requires `CustomEndpoint` to be set if and only if `CustomEndpointEnabled` is true. The previous behaviour was to silently ignore the request's custom endpoint config when only one of these params was given/enabled. This means that, while the new validation is more similar to AWS, it is technically a breaking change.
AWS actually also requires …
> Correct `DomainEndpointOptions` in opensearch/elasticsearch responses and persisted state

- localstack/services/cloudformation/resource_provider.py
PR required to enable AWS::RDS::DBCluster resource provider
> add resource provider for AWS::RDS::DBCluster

- localstack/services/ec2/provider.py
- localstack/services/sns/provider.py
- setup.cfg
- tests/aws/services/sns/test_sns.py
This is the final moto-ext bump ahead of LocalStack v3.0.0 release.
Brings in:
- https://github.com/getmoto/moto/pull/7003
- https://github.com/getmoto/moto/pull/7004
> Bump moto-ext to 4.2.7.post1

- localstack/services/ssm/provider.py
This will fix #9681
`events` should not be mandatory for `ssm`. There's still another service dependency for `ssm` which is `secretsmanager`, but this one looks like it is mandatory when used.
- check if `events` is enabled before trying to emit events related to `ssm`
> skip emitting events in SSM if not enabled

- localstack/services/cloudwatch/models.py
- localstack/services/cloudwatch/provider_v2.py
- localstack/utils/aws/arns.py
- tests/aws/services/cloudwatch/test_cloudwatch.py
- tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json
Add the operations related to `Dashboard` for cloudwatch v2 provider
The test should pass with  Cloudwatch v2 pipeline
> CW V2 Dashboard CRD operations

- .circleci/config.yml
- localstack/services/cloudwatch/models.py
- localstack/services/cloudwatch/provider_v2.py
- localstack/services/providers.py
- tests/aws/services/cloudwatch/test_cloudwatch.py
- tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json
This ports the set_alarm_state and disable_alarm_actions functions to our new v2 provider
- fix delete_alarms
- add set_alarm_state
- add disable_alarm_actions
- add enable_alarm_actions
> Add set_alarm_state, enable/disable_alarm_actions to v2 provider

- Dockerfile
We should make sure the global awscli install is the same version as the one we have in our virtual environment. 
Pin the `awscli` version to be the same as the one is installed. We should make sure to update it with the botocore update.
> pin global awscli install in Dockerfile

- localstack/services/route53/resource_providers/aws_route53_recordset.py
Fixes issues in AWS::Route53::RecordSet when adding alias records (e.g. pointing to ALB load balancer)
- Fixed handling of alias records in `AWS::Route53::RecordSet`. Also fixed the deletion of the resource, since this was incorrectly assuming that certain fields existed which doesn't necessarily have to be true.
- Fixed missing physical resource id of `AWS::Route53::RecordSet`
Test has been added to -ext since it uses an ALB for the alias record.
> Fix alias resource records & add missing id in AWS::Route53::RecordSet

- localstack/services/cloudformation/provider.py
- localstack/state/inspect.py
This PR removes some unnecessary code in the `ReflectionStateLocator` class that we used to visit the backends of a few services. Some cases were just not needed. For others, I implemented the `accept_state_visitor` in the provider.
- Removed special backend visits based on the service name;
- Implemented `accept_state_visitor` for the CloudFormation provider.
Did run the persistence tests in a [companion branch](https://github.com/localstack/localstack-ext/actions/runs/7237832798/job/19718068069) to make sure it did not break anything.
> remove code in state locator

- localstack/services/kinesis/packages.py
https://github.com/etspaceman/kinesis-mock/releases/tag/v0.4.5
Solves https://github.com/localstack/localstack/pull/9884
Bumps kinesis-mock to 0.4.5
> Bump Kinesis Mock to 0.4.5

- localstack/services/sqs/provider.py
- tests/aws/services/sqs/test_sqs.py
- tests/aws/services/sqs/test_sqs.snapshot.json
- tests/aws/services/sqs/test_sqs.validation.json
Fixed https://github.com/localstack/localstack/issues/9678
Updated max fifo_id len from 127 to 128 characters
> Updates deduplication ID and group ID max length to 128

- tests/aws/services/lambda_/functions/lambda_sleep.py
- tests/aws/services/lambda_/test_lambda_integration_sqs.py
- tests/aws/services/lambda_/test_lambda_integration_sqs.validation.json
Adds an integration test covering  #7036
> Add integration test for SQS FIFO event source order/parallelism

- localstack/services/cloudwatch/provider_v2.py
This PR integrates recent v1 CW changes into the new v2 Provider
This PR ensures that the following v1 changes are reflected in the new v2 provider
- https://github.com/localstack/localstack/pull/9641/files#diff-23bd8190ec59c94fb372da30e2453223f10581711317648b7792fd76ba6c8cb0
- https://github.com/localstack/localstack/pull/9799
- https://github.com/localstack/localstack/pull/9878
- https://github.com/localstack/localstack/pull/9985
- https://github.com/localstack/localstack/pull/9978
> Integrate recent v1 CW changes into new v2 provider

- localstack/services/apigateway/integration.py
The user issue was related to a call to the "$disconnect" route and not triggering the SQS backend integration. The problem is we didn't support WS+SQS integration until now. This PR fixes that.
> fix support calling sqs from api ws gw on disconnect endpoint

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/router_asf.py
PR for issue: https://github.com/localstack/localstack/issues/10015
These are needed change to expose properly the source IP address to the context.
Expose the source IP address and insert it into the auth context.
> fix source ip value for the lambda event request

- localstack/services/cloudwatch/models.py
- localstack/services/cloudwatch/provider_v2.py
- localstack/services/providers.py
Removing moto fallback for cloudwatch v2 provider, and cleaning up some variables in `models.py`
> cleanup store + remove moto fallback

- localstack/dev/run/__main__.py
When using `localstack.dev.run`, the terminal would not return from raw mode after the container completed its execution. This would leave the terminal in a raw state where the enter key needed to be pressed multiple times to return to the shell.
Use `console.status` as a context manager to ensure proper shutdown of `rich`'s terminal handling, returning to ["cooked mode"](https://en.wikipedia.org/wiki/Terminal_mode) on completion.
*Note: the diff is confusing, but I changed the call site of `console.status` to be a context manager and indented the rest of the `run` function until the `status.stop` was called.*
> Dev mode: return correctly from raw mode

- README.md
> Update README with 3.1.0 version

- setup.cfg
Upgrade rolo to 0.3.x, which includes a thread safety fix for the router.
* Use rolo 0.3.0
> upgrade rolo to 0.3.x

- scripts/gather_outdated_snapshots.py
This PR adjusts our script to check the age of snapshot towards checking validations instead
As per description
- changes naming
- most importantly, changes the files to check
> add script to track validations instead of snapshots

- localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_sns.py
- tests/aws/services/stepfunctions/templates/callbacks/callback_templates.py
- tests/aws/services/stepfunctions/templates/callbacks/statemachines/sns_publish_wait_for_task_token.json5
- tests/aws/services/stepfunctions/v2/callback/test_callback.py
- tests/aws/services/stepfunctions/v2/callback/test_callback.snapshot.json
- tests/aws/services/stepfunctions/v2/callback/test_callback.validation.json
- tests/aws/services/stepfunctions/v2/services/test_sns_task_service.py
- tests/aws/services/stepfunctions/v2/services/test_sns_task_service.snapshot.json
- tests/aws/services/stepfunctions/v2/services/test_sns_task_service.validation.json
Currently, the StepFunctions v2 interpreter lacks support for automatic stringification of message arguments in the SNS Optimised Integration. This limitation can lead to unintended behaviour in publish calls. This PR addresses such lacking support and adds relevant validated snapshot tests for SNS integrations, including a callback scenario.
- Added automatic stringification of message arguments in the optimised SNS service integrations
- Added relevant snapshot tests
> [SFN] SNS Optimised Integration: Automatic Stringification of Message Arguments

- localstack/constants.py
- localstack/services/opensearch/versions.py
- tests/aws/scenario/bookstore/test_bookstore.py
- tests/aws/scenario/bookstore/test_bookstore.snapshot.json
- tests/aws/scenario/bookstore/test_bookstore.validation.json
- tests/aws/services/es/test_es.py
- tests/aws/services/opensearch/test_opensearch.py
Fixes — https://discuss.localstack.cloud/t/opensearch-cdklocal-deploy-failed/674
> add opensearch 2.11

- localstack/services/lambda_/invocation/logs.py
We currently make 3 requests to CloudWatch logs for every lambda invocation:
1. `CreateLogGroup` (will fail for all but the first invoke for that function)
2. `CreateLogStream` (will fail for all but the first invoke for that execution environment)
3. `PutLogEvents`
We can drastically reduce the calls, and also load on the gateway, if we only execute the first two calls if `PutLogEvents` fails.
If it fails, it equals to 4 calls (failed `PutLogEvents`, then `CreateLogGroup`, then `CreateLogStream`), but then only one call for every invocation (for the same environment) afterwards.
Compared to 3 calls for every single invocation right now. There is also a lot of logic in `store_cloudwatch_logs` which is not necessary anymore with the new lambda provider.
* Change logic to ask for …
> Reduce requests necessary for lambda log publishing to cloudwatch logs

- requirements-base-runtime.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
- setup.cfg
Bump for the upcoming v3.2.0 release.
Brings in:
- https://github.com/getmoto/moto/pull/7281
Ext Integration Tests # 4921 :green_circle: passing
Closes: https://github.com/localstack/localstack/issues/10122
> Bump moto-ext to 5.0.2.post1

- localstack/services/lambda_/invocation/logs.py
Reverts localstack/localstack#10234
> Revert "Reduce requests necessary for lambda log publishing to cloudwatch logs"

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/integration.py
Adds support to Kinesis-PutRecord.
Adds Kinesis backend integration support for integration subtype operation "Kinesis-PutRecord"
Snapshot parity testing
> HTTP IntegrationSubtype support for Kinesis-PutRecord 

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/integration.py
- localstack/services/apigateway/invocations.py
- tests/aws/services/apigateway/test_apigateway_basic.py
- tests/aws/services/apigateway/test_apigateway_basic.snapshot.json
- tests/aws/services/apigateway/test_apigateway_basic.validation.json
Add support to websockets and SNS backend
- HTTP backend integration refactor to call Lambda integration. Logic is now consolidated into the Lambda integration itself.
Description of how to test the changes
-->
> add support to websockets and sns backend

- tests/aws/cdk_templates/FirehoseScenario/FirehoseStack.json
- tests/aws/scenario/kinesis_firehose/conftest.py
- tests/aws/scenario/kinesis_firehose/test_kinesis_firehose.py
- tests/aws/scenario/kinesis_firehose/test_kinesis_firehose.snapshot.json
- tests/aws/scenario/kinesis_firehose/test_kinesis_firehose.validation.json
To further close gaps between LocalStack and AWS more scenario tests focusing on combining multiple services are required, with these two requirements:
1. close gaps in existing integration tests for streaming services: 🎯goal: focus on integration tests on services that are a. frequently used & b. not well covered currently
2. implement standard scenarios of service workflows used by our customers & on AWS in general: 🎯goal: represent the most common behavior LocalStack is used for to guarantee that this works for code changes
Scenarios meeting both requirements should be ranked in order to focus on the most relevant ones first. These 4 ranking criteria are proposed: 
1. how much are the involved services used by customers
2. how many integration tests exist covering the scenario
1. how …
> Feature: Scenario Tests: Firehose central scenario test

- localstack/utils/bootstrap.py
With this PR we add `timestream` to the list of composite APIs.
> add timestream to the list of composite apis

- localstack/services/kinesis/packages.py
Just a dependency updates release. See https://github.com/etspaceman/kinesis-mock/releases/tag/v0.4.6
> Update kinesis-mock to 0.4.6

- localstack/dev/run/configurators.py
- localstack/dev/run/paths.py
When debugging a nasty bug (#10003), I would like to sprinkle some print statement in rolo, and logging the actual data returned from the exception, to see if it's an S3 issue or not, and which one is failing exactly.
Add rolo to the list of local project to mount
> add rolo to dev script

- localstack/contrib/__init__.py
`contrib` was originally conceived for third-party integrations maintained by other contributors, but this has since been superseded by the extension mechanism.
* remove `localstack.contrib` package
> remove contrib package

- localstack/services/dynamodbstreams/provider.py
With #10462 we used an explicit endpoint override for dynamodbstreams, but only for writing into the stream.
We need the same client when reading the stream as well, this was an oversight by me. This PR fixes that.
* Use the custom streams client in the dynamodbstreams provider as well
> Adapt dynamodbstreams clients in the provider as well

- tests/aws/services/cloudformation/resources/test_lambda.py
Community tests were broken caused after merging https://github.com/localstack/localstack/pull/10418. 
This PR fixes lint, caused by latest changes added to rules in https://github.com/localstack/localstack/pull/10471
> fix: broken pipeline after merging #10418

- tests/aws/services/events/test_events_inputs.py
- tests/aws/services/events/test_events_integrations.py
The recent PR: https://github.com/localstack/localstack/pull/10160 had two files that were not properly formated, that caused the pre-flight tests in master to fail. 
Formatting with ruff
> Fix: Events: Refactor tests fix string formatting errors

- localstack/services/lambda_/invocation/version_manager.py
- localstack/utils/aws/request_context.py
- localstack/utils/http.py
> chore: remove repetitive words

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/provider.py
- tests/aws/services/cloudformation/api/test_update_stack.py
- tests/aws/services/cloudformation/api/test_update_stack.snapshot.json
- tests/aws/services/cloudformation/api/test_update_stack.validation.json
CFn get-template after change-set execution is not showing the right template.
- Update template-body when change-set is applied
- Added aws validated test cases.
> Add update template_body

- localstack/testing/scenario/cdk_lambda_helper.py
This pull request introduces a new feature for CDK Tests that enables developers to supply a custom Dockerfile for the automatic creation of an ECR image.
- new utility
- testing is done in another pr
> add cdk infra setup for ecr images

- localstack/services/sns/publisher.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
- tests/aws/services/sns/test_sns.validation.json
- tests/unit/test_sns.py
This is somewhat a follow up from #10594. The previous PR only handled arrays when they were the "last leaf" of the object.
However, SNS filtering can handle arrays wherever in the payload, as shown by this blog post: https://aws.amazon.com/blogs/compute/introducing-payload-based-message-filtering-for-amazon-sns/
So SNS can handle anything that has arrays, and it just basically add them to a list of "OR" values.
- separate the flattening of the policy and the payload, because they follow different rules. The policy will include only dict until the last leaf. The payload can be whatever JSON. 
- I've reworked the flattening to create a new entry for each value in a list, because AWS consider every entry as an "or" condition, and will accept the payload if any value in any list matches the …
> fix SNS filtering when payload contains arrays

- localstack/services/apigateway/helpers.py
- localstack/services/lambda_/invocation/docker_runtime_executor.py
- localstack/services/lambda_/invocation/execution_environment.py
- localstack/services/route53/resource_providers/aws_route53_recordset.py
- localstack/services/sns/provider.py
- localstack/services/stepfunctions/asl/component/state/state.py
- tests/unit/aws/protocol/test_serializer.py
fix some typos in comments
fix some typos in comments
No need.
> chore: fix some typos in comments

- localstack/services/dynamodb/provider.py
- tests/aws/services/dynamodb/test_dynamodb.py
The TTL feature does not properly work when a table has a `RANGE` key. This was a limitation of the initial implementation.
The issue has been raised in #10660.
- Implemented the deletion of expired items when the table contains a `RANGE` key.
- Extended the existing test to verify the correct behavior.
> Fix TTL for tables with RANGE keys

- tests/aws/services/cloudformation/resources/test_sam.py
- tests/aws/services/cloudformation/resources/test_sam.validation.json
- tests/aws/templates/sam_sqs_template.yml
Based on https://github.com/localstack/localstack/issues/7734, capture a lambda function being invoked by an SQS message via a SAM template.
* Include new test for SAM template
* Validate test against AWS
Closes https://github.com/localstack/localstack/issues/7734
> Capture example lambda triggered by SQS event

- localstack/services/firehose/provider.py
The operation `list_delivery_streams` returns unwanted keys for multiple destination descriptions.  
Destination descriptions are loaded from the store and backend, and can contain keys that are not defined by the respective return types and thus not expected to be returned, e.g. `RedshiftDestinationDescription` contains a Password parameter.
As observed in different CI runs, this can lead to unnecessary log messages:
```
Response object RedshiftDestinationDescription contains a member which is not specified: Password
AWS firehose.DescribeDeliveryStream => 200
POST localhost:4566/
```
This pr drops parameters in all supported destinations that are not defined by the respective return type definitions.
> Fix: Firehose: Drop keys in destinations description not in respective return types

- pyproject.toml
- requirements-base-runtime.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
Brings in:
- https://github.com/getmoto/moto/pull/7700
> Bump moto-ext to 5.0.7.post1

- localstack/logging/format.py
When we started to route ECR requests over our gateway, customers noticed that the entire image blob payload would be logged into the LocalStack logs if `LS_LOG=trace` or `trace-internal`.
This is caused by unconditional logging of the input and output payload in the http request logger.
Since the ECR blobs could get serveral hundred MBs up to multiple GBs big, this leads to severe performance degradation and massive issues in log file size.
We should avoid logging big binary payloads, as we do with the AWS request logger already.
* LocalStack will not log binary payloads of HTTP requests if they are bigger than 512 bytes, the current threshold for logging aws bytes payloads as well.
Example log entry in trace logging after the change (for ECR):
```
2024-05-21T15:42:13.190  INFO --- …
```
> Replace large bytes payloads in http request logging to avoid cluttering the logs

- localstack-core/localstack/services/cloudformation/resource_provider.py
During the migration to resource providers, the event information telling us which resources are being used and which resources are not implemented was removed. This means we no longer get an accurate picture of CFn resource usage.
* Emit both `resource_type` and `missing_resource_types` events at appropriate places
> Track cfn resource events

- tests/aws/services/redshift/test_redshift.py
- tests/aws/services/redshift/test_redshift.validation.json
Fixup and validate redshift test
> validate redshift test

- tests/aws/files/api_definition.yaml
- tests/aws/files/openapi-mock.json
- tests/aws/services/apigateway/apigateway_fixtures.py
- tests/aws/services/apigateway/test_apigateway_basic.py
- tests/aws/services/apigateway/test_apigateway_basic.snapshot.json
- tests/aws/services/apigateway/test_apigateway_basic.validation.json
- tests/aws/services/apigateway/test_apigateway_integrations.py
- tests/aws/services/apigateway/test_apigateway_integrations.snapshot.json
- tests/aws/services/apigateway/test_apigateway_integrations.validation.json
- tests/aws/services/apigateway/test_apigateway_lambda.py
- tests/aws/services/apigateway/test_apigateway_lambda.snapshot.json
- tests/aws/services/apigateway/test_apigateway_lambda.validation.json
- tests/aws/services/apigateway/test_apigateway_sqs.py
- tests/aws/services/apigateway/test_apigateway_sqs.snapshot.json
- tests/aws/services/apigateway/test_apigateway_sqs.validation.json
- tests/aws/services/lambda_/functions/apigw_502.js
- tests/aws/services/lambda_/test_lambda.py
> apigw validate test

- localstack-core/localstack/services/cloudformation/scaffolding/__main__.py
Fixed broken CFn resource generation introduced with new project structure changes
- Minor changes in paths that take into account locastack-core
> Fixed scaffolding generation for CFN resources

- localstack-core/localstack/utils/asyncio.py
It's know that ThreadPoolsExecutors don't care about daemon threads. They add all their threads to a global list which is then iterated and joined on `atexit`. We have a patch in pro that adds this functionality, and we also added it a while back for hypercorn, which now [lives in rolo](https://github.com/localstack/rolo/blob/b1c24d7bea94012fece1323dc6fd616e53f44485/rolo/gateway/asgi.py#L13-L20).
This PR adds the functionality as a re-usable class, and uses it to implement the `AdaptiveThreadPool`, which is the thing being patched by pro. This allows us to get rid of the patch, which will help #10942.
* `THREAD_POOL` will no longer join its threads on exit if the threads are daemon threads
> add DaemonAwareThreadPool for thread pools to block shutdown

- .github/workflows/tests-s3-image.yml
Follow up from #10960, the new docker helper needs the credentials to be set as specific environment variables
- add the credentials to the env
> fix S3 Image publishing - credentials for Dockerhub

- README.md
This PR updates the release banner for LocalStack 3.5 and update the CLI output
> update release banner in README [3.5]

- tests/aws/services/lambda_/test_lambda.py
- tests/aws/services/lambda_/test_lambda.snapshot.json
- tests/aws/services/lambda_/test_lambda.validation.json
This PR aims to improve test coverage of LS Cross account capabilities and fixes existing tests related to this
Majority of changes enabling this functionality was done in https://github.com/localstack/localstack/pull/10961
However there wasn't sufficient test coverage for it, which this PR aims to improve
> Added Lambda cross account tests

- localstack-core/localstack/services/apigateway/next_gen/execute_api/context.py
Start of the process to populate the context variables for template rendering.
> add APIGW NG context variables

- localstack-core/localstack/runtime/init.py
People have asked whether they can use CDK or terraform in init hooks. To implement something like this, you'd currently need to statically code a runner into the init hook system, however I wanted to encapsulate terraform file support for init hooks into an extension.
To that end, I introduced a new plugin namespace `localstack.init.runner`, made the `ScriptRunner` a plugin of that namespace, and updated the `InitScriptManager` to use a `PluginManager` instead. After introducing this Inversion of Control, I noticed that it's better to have the condition, whether a script runner should be used or not, also encapsulated in the `ScriptRunner`. So now the `ScriptRunner` decides whether it is used for a script or not. The default implementation still uses file suffixes to make that …
> add plugin namespace localstack.init.runner to make init script runners pluggable

- tests/aws/services/iam/test_iam.py
- tests/aws/services/iam/test_iam.snapshot.json
- tests/aws/services/iam/test_iam.validation.json
I was doing some work on IAM role issues with paths, and wrote this test during trying to reproduce the issue.
The issue was elsewere, but the tests are still useful.
* Add tests for the lifecycle of an IAM role with a path
> Add test for lifecycle of an IAM role with a path

- localstack-core/localstack/services/internal.py
It's currently not easily possible for ext or other modules to add plugin managers to the output list of `/_localstack/plugins`.
This internal refactoring creates a class-level list of plugin managers that can be extended using hooks or other discovery mechanisms. Specifically this is used by ext to add the `localstack.platform.plugin` namespace.
* the output `/_localstack/plugin` can now be extended by other components
* the init `ScriptRunners` introduced in #11098 are now listed correctly
* the `requires_license` output is now shown in the list of plugins, if the plugin has been initialized and the attribute is present
* PluginManagers that were in `/_localstack/plugins` are now imported a bit earlier (when the `PluginsResource` is created, not when it's called for the first time - …
> make /_localstack/plugin endpoint extendable

- localstack-core/localstack/utils/strings.py
- tests/unit/utils/test_strings.py
This PR adds a small utility to prepend `/` to a given string.
This is being moved from localstack-ext MWAA provider.
> Add utility to prepend a string with a slash

- docs/testing/README.md
- docs/testing/test-types/README.md
With #11049 we switched to only execute acceptance tests for pushes onto the `master` branch. Currently, however, the suite of acceptance tests is not very extensive. 
To facilitate (correct) growth here, we need guidance on what acceptance tests exactly are and what we expect of them.
This PR adds a new section to the contribution documentation, documenting the different types of tests we execute in our CI pipeline.
The main focus is documentation about acceptance tests, when they are executed, what is expected of them, and how new ones can be developed.
> Add documentation for different types of tests

- tests/aws/services/events/test_events_tags.py
- Use `is_old_provider` fixture
> Refactor/eventbridge_v2: Clean tagging tests

- localstack-core/localstack/config.py
- localstack-core/localstack/services/apigateway/helpers.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_response.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py
- tests/aws/services/apigateway/test_apigateway_basic.py
- tests/aws/test_multiregion.py
Fix the last following tests in order to be able to enable a new CI step to test the next gen APIGW invocation logic. 
```
FAILED tests/aws/scenario/note_taking/test_note_taking.py::TestNoteTakingScenario::test_notes_rest_api
FAILED tests/aws/services/stepfunctions/v2/services/test_apigetway_task_service.py::TestTaskApiGateway::test_invoke_base
FAILED tests/aws/services/stepfunctions/v2/services/test_apigetway_task_service.py::TestTaskApiGateway::test_invoke_with_body_post[None]
FAILED tests/aws/services/stepfunctions/v2/services/test_apigetway_task_service.py::TestTaskApiGateway::test_invoke_with_body_post[]
FAILED tests/aws/services/stepfunctions/v2/services/test_apigetway_task_service.py::TestTaskApiGateway::test_invoke_with_body_post[HelloWorld]
FAILED …
```
> APIGW NG fix last tests

- localstack-core/localstack/services/apigateway/next_gen/execute_api/context.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/gateway.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/gateway_response.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/gateway_exception.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_request.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_response.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/method_response.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/core.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/http.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/mock.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/parameters_mapping.py
- tests/unit/services/apigateway/test_handler_integration_response.py
- tests/unit/services/apigateway/test_mock_integration.py
- tests/unit/services/apigateway/test_parameters_mapping.py
This PR refactors our usage of the handler chain: we would make use of response handlers to mutate the response in place, and that defeated the extensibility. 
Also, exception handlers were affected by the response handlers and it did not make a lot of sense regarding the architecture of APIGW. 
Now, all handlers are request handlers, passing data around in the context. Only the last handler is responsible for serializing the response.
We could arguably already serialize the response in the `_PROXY` integrations, but we will most probably add additional serialization logic in the Method Response handler regarding remapped headers.
This will also enable us to create response handlers which will extend the behavior, for example read all data from the context (which is mostly added and not …
> APIGW NG refactor handlers

- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_api_gateway.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_aws_sdk.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_callback.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_dynamodb.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_ecs.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_events.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_glue.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_lambda.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_sfn.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_sns.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_sqs.py
- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_unsupported.py
- localstack-core/localstack/services/stepfunctions/asl/eval/callback/callback.py
- tests/aws/services/stepfunctions/templates/callbacks/callback_templates.py
- tests/aws/services/stepfunctions/templates/callbacks/statemachines/sfn_start_execution_sync_with_task_token.json5
- tests/aws/services/stepfunctions/templates/services/services_templates.py
- tests/aws/services/stepfunctions/templates/services/statemachines/sqs_send_msg_and_wait.json5
- tests/aws/services/stepfunctions/v2/callback/test_callback.py
- tests/aws/services/stepfunctions/v2/callback/test_callback.snapshot.json
- tests/aws/services/stepfunctions/v2/callback/test_callback.validation.json
AWS Step Functions allows for the manual interruption of [sync](https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html#connect-sync) and [sync2](https://docs.aws.amazon.com/step-functions/latest/dg/connect-stepfunctions.html) integration patterns via manual notification using the task's `TaskToken`; workflows otherwise reserved for `waitForTokenTask` [integrations](https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html#connect-wait-token). 
This means that not only can `$$.Task.Token` context value be accessed in `sync` and `sync2` workflows that also support `waitForTaskToken`; but that also `sync(2)` workflows needs to listen for callbacks on that task token.
Such scenario is currently not supported by the StepFunctions v2 interpreter, which …
> [SFN] Support for Sync Interrupts via Task Token

- CODEOWNERS
- localstack-core/localstack/aws/api/pipes/__init__.py
- localstack-core/localstack/services/lambda_/event_source_mapping/event_processor.py
- localstack-core/localstack/services/lambda_/event_source_mapping/noops_event_processor.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pipe_loggers/noops_pipe_logger.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pipe_loggers/pipe_logger.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pipe_utils.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/dynamodb_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/kinesis_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/sqs_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
- localstack-core/localstack/services/lambda_/event_source_mapping/senders/lambda_sender.py
- localstack-core/localstack/services/lambda_/event_source_mapping/senders/sender.py
- localstack-core/localstack/services/lambda_/event_source_mapping/senders/sender_utils.py
Lambda Event Source Mapping v2 (ESM) and EventBridge Pipes are going to share parts of the implementation (in particular pollers). Therefore, we need to move the shared infrastructure from LocalStack pro into community.
Move shared code for Pipes and ESM into community, in particular:
- Pipes ASF API: `localstack-pro-core/localstack_ext/aws/api/pipes/**init**.py` (see detailed internal discussion in #sig-localstack 01.07.2024 regarding moving Pipes API specs into community)
- Pollers: `localstack-pro-core/localstack_ext/services/pipes/pollers`
- all (currently no ext-specific ones)
- Senders: `localstack-pro-core/localstack_ext/services/pipes/senders/`
- `sender.py`
- `lambda_sender.py`
- EventProcessor interface:
- `localstack-pro-core/localstack_ext/services/pipes/event_processor.py`
- …
> Move shared Pipes infrastructure to Lambda ESM

- localstack-core/localstack/services/apigateway/resource_providers/aws_apigateway_method.py
The issue #11164 mentions that the APIGW::Method resource is not able to deploy when a boolean parameter is passed from a parent stack due to being converted into a string. This is the correct behavior but it shows that our Resource provider is missing  another value type transformation. Instead of just adding it. I refactore the code into using the new utility for parameters and type conversions introduced in #11178.
- Removed almost all the manual parameter selections and the type transformations
- pipeline should be green
> refactor AWS::APIGW::Method resource provider

- localstack-core/localstack/http/dispatcher.py
- localstack-core/localstack/http/router.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/router.py
- pyproject.toml
- requirements-base-runtime.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
Upgrading to rolo 0.7.0 which includes support + fix on top of 0.6.0 for pydantic.
There was a bit of code refactoring for 0.7, which may cause breakage. Will follow up with rolo patch releases to fix.
* pydantic models can now be used in routes
> upgrade rolo to 0.7.0

- README.md
This PR updates the release banner for LocalStack 3.6 and updates the CLI output
> update release banner in README [3.6]

- localstack-core/localstack/services/apigateway/next_gen/execute_api/context.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/gateway.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/__init__.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/router.py
As needed upstream, to allow greater flexibility, we would need a handler to modify the request after it has been parsed. 
We also need a small refactor in order to be able to act on the context from the `Endpoint`. 
We can merge this after the 3.6 release as it will break upstream dependencies. 
- add a composite handler
- refactor the endpoint
> add APIGW NG composite handler

- requirements-base-runtime.txt
- requirements-basic.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
Manual upgrade of pinned libs to force the inclusion of the newer rolo version
- pinned libs upgrade
> Upgrade pinned Python dependencies

- localstack-core/localstack/services/cloudformation/engine/parameters.py
- localstack-core/localstack/services/cloudformation/engine/template_deployer.py
- localstack-core/localstack/services/cloudformation/engine/transformers.py
- localstack-core/localstack/services/cloudformation/resource_provider.py
Client errors are often obtuse and don't show the resource that failed.
- Wrap all internal client calls with logging to explain more
-  wrap resource provider action with extra logging to provide more context
> CFn: better context on boto client errors

- .github/workflows/tests-pro-integration.yml
Fixing pipeline broken due to another patch update to postgresql package for ubuntu 
- update to `14.13-0ubuntu0*`
> fix postgresql in ci

- localstack-core/localstack/aws/spec-patches.json
Updating spec for apigwv2, as the aws endpoint returns 201 and the spec specifies 200 for this call.
> Apigw ng http deployment

- localstack-core/localstack/services/apigateway/next_gen/execute_api/parameters_mapping.py
Improve re-usability of the helper method by expanding it's typing to accept all dict.
> Updated parameter mapper typing

- localstack-core/localstack/services/apigateway/next_gen/execute_api/parameters_mapping.py
Updated signature of `_retrieve_parameter_from_variables_and_static` to improve it's re-usability. Also added a check to prevent `_retrieve_parameter_from_context_variables` from returning a dict.
> apigw ng request parameter handler

- localstack-core/localstack/aws/spec-patches.json
We need to patch the spec to return the 201 status code for the `UpdateApi` operation. 
Note: it might be worth it to do a full pass on all update operations to find the others and do only one PR
Follow up from #11401
- update the patch specs for apigwv2
> APIGW NG: update UpdateApi status code

- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/stream_poller.py
The `shardId` of DynamoDB Streams events is incorrectly being set (when sending failed records to a failure destination config) since the `shard_id` extraction from `eventID` assumes the Kinesis format:
```python
shard_id = first_record["eventID"].split(":")[0] 
```
See [AWS ESM Kinesis example](https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html#services-kinesis-event-example):
```
"eventID": "shardId-<timestamp>:<sequence-number>"
```
See [AWS ESM DynamoDB Streams example](https://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html#events-sample-dynamodb):
```
"eventID": "<uuid>"
```
Note: This unblocks the failing CI in https://github.com/localstack/localstack/pull/11505
- Pass the `shard_id` of the current shard iteration instead of relying on extracting this value from a …
> fix: Extraction of shard ID in ESMv2 StreamPoller

- localstack-core/localstack/services/apigateway/provider.py
- localstack-core/localstack/services/apigateway/resource_providers/aws_apigateway_usageplan.py
- tests/aws/services/apigateway/test_apigateway_common.py
- tests/aws/services/cloudformation/resources/test_apigateway.py
- tests/aws/services/cloudformation/resources/test_apigateway.snapshot.json
- tests/aws/services/cloudformation/resources/test_apigateway.validation.json
- tests/aws/templates/apigateway_usage_plan.yml
Fix for the issue #11510 
- Fixed Tags update in **ApiGatewayV1 UsagePlan**
- **UsagePlan** tags are updated correctly
- not sure if the test is working / testing the change. Has not been able to perform cross-check on my environment.
> fix APIGW CFN UsagePlan update operation with Tags

- localstack-core/localstack/config.py
- localstack-core/localstack/constants.py
- localstack-core/localstack/deprecations.py
- scripts/build_common_test_functions.sh
I've removed the typos in the code and updated some comments in the code to understand the code much better.
> fix typos and grammar in some core python files

- localstack-core/localstack/services/events/provider.py
EventStudio open the black box eventbridge as an event router represents, therefore it is highly beneficial to surface internal steps that can be the cause for mismatches between expected behavior and actual behavior e.g. no rule matches the message. 
Therefore log messages are added at these specific instances.
> Feature/Events: Add internal log messages

- README.md
Update README after 3.8. release.
> Update README with v3.8

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker_factory.py
Addresses IAM regressions raised in new ESM v2.
- Change the service principal from Pipes to Lambda.
> ESM-v2: fix IAM service principal

- localstack-core/localstack/services/cloudformation/engine/template_utils.py
- tests/aws/services/cloudformation/engine/test_mappings.validation.json
- tests/aws/templates/mappings/mapping-ref-map-key.yaml
This PR adds support for AWS References inside a Mapping inside a Conditional of a CFn template
- Extend resolving function
- Extend previous test
> add support for region ref in mappings inside condition CFn

- docs/development-environment-setup/README.md
Make it easier to contribute to LocalStack 🚀 
* Add a tip about pre-commit hooks to catch errors earlier.
> Add hint about pre-commit hooks to dev tips

- localstack-core/localstack/deprecations.py
Fix typo in dynamic deprecation message
> Fix typo in dynamic ESM deprecation warning

- .circleci/config.yml
As we've created a new implementation of DynamoDB relying on DynamoDB-local for the DynamoDB Streams implementation with #11688, we should ideally test this in CI to catch any possible regression.
- add a CI job to test the v2 implementation of DynamoDB and DynamoDB Streams
> add DynamoDB v2 CI job

- localstack-core/localstack/services/sns/publisher.py
In EventStudio we want to trace outgoing SNS notifications, when the are pushed to subscribers via the `PublishDispatcher.publish_to_topic`.
To optimize performance the publishing to subscribers is executed in subthreads.
For tracing to work we need to make the trace_context available in the sub-thread where need to wrap the `notifier.publish` function with the current `thrading.local` context.
Therfore, we need to decompose the execution in the subthread into a separate function.
> Feature/SNS: Decompose publish to topic

- localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_api_gateway.py
- tests/aws/services/stepfunctions/templates/services/services_templates.py
- tests/aws/services/stepfunctions/templates/services/statemachines/api_gateway_invoke_with_headers.json5
- tests/aws/services/stepfunctions/v2/services/test_apigetway_task_service.py
- tests/aws/services/stepfunctions/v2/services/test_apigetway_task_service.snapshot.json
- tests/aws/services/stepfunctions/v2/services/test_apigetway_task_service.validation.json
Fix [Issue:11628](https://github.com/localstack/localstack/issues/11628) and show off
- Cast list type header values to string before using for SFN - ApiGW integration
- Add parity test for these header value types
- Run the tests
-  Follow the `Steps To Reproduce` mentioned [on this issue](https://github.com/localstack/localstack/issues/11628)
> Fix bug: Support list header value on Step Functions ApiGateway:Invoke integration

- localstack-core/localstack/services/dynamodb/server.py
This PR fixes DynamoDB provider hanging up when performing state reset using POST `/_localstack/state/reset`.
This bug was caused in the underlying `Server` abstraction, where the `threading.Event` that track the runtime state where not correctly updated.
This was not a problem earlier because fresh server objects were being created after state resets. The DynamoDB server object was recently made a singleton in https://github.com/localstack/localstack/pull/11688
> DynamoDB: Fix hangup when resetting state

- localstack-core/localstack/openapi.yaml
- tests/aws/services/sns/test_sns.py
After introducing OpenAPI specs for our internal endpoints, we are now introducing stricter validations in our test pipeline.
This PR enables the validation of the requests and responses for the developer endpoints in the SNS test suite.
It also adds minor changes to the specs to reflect the actual implementation and make the suite green.
- Enable Open API validation for the SNS tests;
- Minor adaptations to the spec.
> Validate SNS developer endpoints

- localstack-core/localstack/utils/analytics/usage.py
Follow up from #11848, following the refactor and quick tests / copy-paste from scratch files, I've removed the registration of the counters 😬 
Note: can also be added to #11854 if approved. 
- put back the registration
> re-add usage analytics collector_registry registration

- localstack-core/localstack/services/events/event_bus.py
- localstack-core/localstack/services/events/models.py
- localstack-core/localstack/services/events/provider.py
- localstack-core/localstack/services/events/rule.py
EventBridge v2 does not yet support persistence. This PR restructures the community provider and fixes a small store typo for correct store discovery.
* Restructure EventBridge v2 provider service creations for persistence
* Fix typo in stores model
> Add restructurings to fix events persistence in v2

- README.md
We released LocalStack v4 yesterday. This PR just updates the README.md accordingly.
@HarshCasper: Feel free to just take over this PR, and push any changes you feel appropriate. :)
- Just updates the announcement on the top of the README and the version in the sample command output.
> update README for v4

- localstack-core/localstack/services/events/provider.py
Re-introduce EventBridge analytics removed by accident in https://github.com/localstack/localstack/pull/11880/
> Re-introduce EventBridge invoke analytics

- tests/aws/services/stepfunctions/v2/assign/test_assign_reference_variables.py
- tests/aws/services/stepfunctions/v2/intrinsic_functions/test_json_manipulation_jsonata.py
During the last merge we unfortunately introduced some formatting/linting issues. 
These issues are addressed here.
> Fix formatting for new sfn features

- localstack-core/localstack/dns/server.py
Apologies. Was a bit too trigger happy and really didn't think that it would create a linting issue somewhere completely unrelated.
- Fixes linting issues in `server.py` for whatever reason
> Fix linting issue after namespace package fix

- localstack-core/localstack/services/providers.py
Removed cloudcontrol provider for community as we moved it in pro
Removed cloudcontrol  from the list of community providers
> fix(providers): Removed cloudcontrol provider

- localstack-core/localstack/services/events/provider.py
- tests/aws/services/events/test_events.py
The current EventBridge connection validation in LocalStack lacks error handling and doesn't fully align with AWS specifications. This leads to:
1. Incomplete validation feedback - errors are reported individually rather than collectively
2. Inconsistent error messaging compared to AWS
3. Early termination on first validation error instead of reporting all validation issues
4. Potential confusion for users due to different validation behavior from AWS
This PR enhances the EventBridge connection validation mechanism to more closely mirror AWS behavior:
- Modified validation methods to collect and return multiple errors simultaneously
- Implemented comprehensive validation for connection names:
* Length constraints (1-64 characters)
* Character set validation (alphanumeric, periods, …
> Events create connection test fix

- requirements-base-runtime.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
Updating rolo to contain the https://github.com/localstack/rolo/pull/25 fix for the EventStudio. 
- update rolo to 0.7.4
> update rolo to 0.7.4

- tests/aws/services/scheduler/conftest.py
- tests/aws/services/scheduler/test_scheduler.py
- tests/aws/services/scheduler/test_scheduler.snapshot.json
- tests/aws/services/scheduler/test_scheduler.validation.json
Hi😀
I checked the EventBridge Scheduler API coverage and found that some APIs were not marked in the "Internal Test Suite". So I wanted to contribute by adding tests.
- https://docs.localstack.cloud/references/coverage/coverage_scheduler/
In this Pull Request, I’ve added a test for the EventBridge Scheduler `TagResource` API and `UntagResource` API to improve coverage.
It's a bit hard to understand, but the `TagResource` API and `UntagResource` API are not for EventBridge Scheduler, It's specifically for EventBridge Scheduler Group.
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/scheduler/client/tag_resource.html
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/scheduler/client/untag_resource.html
The tests passed in my local …
> Add test for EventBridge Scheduler TagResource API and UntagResource API

- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/mock.py
- tests/unit/services/apigateway/test_mock_integration.py
In an attempt to move fast to fix the issue, with @bentsku. we created #11967.
The naming was done hastily and we will attempt to clean it up a little in this pr.
- clean up naming
- simplify logic
- adding a few tests
> apigw clean up the invalid json parser

- localstack-core/localstack/services/events/usage.py
- localstack-core/localstack/services/lambda_/usage.py
Wrong and/or unclear usage counter description
* Clarify usage counter descriptions
> Clarify usage counter descriptions

- localstack-core/localstack/cli/localstack.py
As we are moving towards enabling a preview version of the replicator, we need to add it to the "Advanced" section of the cli.
> add replicator to Advanced section

- tests/cli/test_cli.py
I added type annotations to the `container_exists` function to improve type safety, facilitate static type checking, and improve developer experience.  
While the code's external behavior remains unchanged, these changes improve the readability and maintainability of the code.
> Improve type safety of `container_exists`

- README.md
- docs/development-environment-setup/README.md
- localstack-core/localstack/dev/run/configurators.py
- localstack-core/localstack/utils/bootstrap.py
- localstack-core/localstack/utils/container_networking.py
- localstack-core/localstack/utils/run.py
- tests/integration/docker_utils/test_docker.py
- tests/unit/utils/analytics/test_metadata.py
> Fix MacOS -> macOS

- localstack-core/localstack/services/iam/iam_patches.py
This PR allows the setting of a CustomId for IAM Roles. /cc @cloutierMat 
- Check if the specific tag exists and then set the role Id after its creation.
This is done in another repository.
> allow setting of customId for IAM Roles

- localstack-core/localstack/services/cloudformation/engine/parameters.py
Improve error message
Provide the name of the parameter without a value
Not tested - I do not know how to run tests
semver: patch
> Improve error message for a missing parameter value - provide its name

- Dockerfile
- Dockerfile.s3
Fix issue: https://github.com/localstack/localstack/issues/11259
Relaxed time constraints in healthcheck
> Relax healthcheck time constraints

- localstack-core/localstack/services/sns/provider.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
- tests/aws/services/sns/test_sns.validation.json
As reported in #12174, we did not raise an exception if the topic did not exist
- add a test for raising an exception if the topic did not exist
- raise the exception
_fixes #12174_
> SNS: fix Subscribe non existent topic exception

- localstack-core/localstack/services/ec2/resource_providers/aws_ec2_instance.py
We got a report from a support case that trying to deploy an EC2 instance with CDK and a basic stack would fail with a `KeyError`:
```python
2025-01-10 08:31:51 localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/ec2/resource_providers/aws_ec2_instance.py", line 255, in create
2025-01-10 08:31:51 localstack-main  |     model["PublicIp"] = instance["PublicIpAddress"]
2025-01-10 08:31:51 localstack-main  |                         ~~~~~~~~^^^^^^^^^^^^^^^^^^^
2025-01-10 08:31:51 localstack-main  | KeyError: 'PublicIpAddress'
```
<details><summary>The Stack:</summary>
<p>
```python
from aws_cdk import (
Stack,
aws_ec2 as ec2,
CfnOutput,
)
from constructs import Construct
class CdkStack(Stack):
def __init__(self, scope: Construct, construct_id: …
```
> CFN/EC2: fix KeyError for EC2:Instance PublicIpAddress

- docs/testing/integration-tests/README.md
> Fix wrong dash symbol in README

- README.md
To be merged after the blog is released
> add 4.1 blog to README

- docs/development-environment-setup/README.md
Update dev setup guide with info about type hinting enablement.
Optional note in installing python dependencies step.
> Add info about how to enable type hints for testing to dev setup guide

- README.md
ADHD. 😅 
This will update the CLI output in the README to include the web app URL added in https://github.com/localstack/localstack/pull/12016.
> Update README CLI output

- localstack-core/localstack/services/lambda_/event_source_mapping/pollers/sqs_poller.py
Provides default configuration values to the SqsPoller in the event that configuration is not set via the `PipeSourceSqsQueueParameters` dictionary.
- The following defaults have been added to the `SqsPoller`
- batch size defaults to `10`
- batch window defaults to `0` -- which is short polling by default. Note: batch windows are not yet implemented in the SqsPoller so this value doesn't get used anywhere.
> [ESM] Provide SqsPoller with default parameters

- localstack-core/localstack/services/iam/resource_providers/aws_iam_role.py
This PR implements the READ method to the IAM::Role resource provider
- method implementation
- testing done in another repository
> add read method to IAM::Role resource provider

- localstack-core/localstack/logging/format.py
- tests/unit/logging_/test_format.py
This pr introduces a logging filter that can be used to mask sensitive values in our http logger. As we log every incoming HTTP request raw body, we can user this filter to find sensitive keys in a json string and mask their value.
- Base class to allow for value masking
- Test including an example subclass
> Logging mask credentials

- localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/parse.py
- localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py
As we got a report in #12295, we had an issue if our path handling when working with API Gateway Custom Domains and REST APIs.
This PR is a small fix to manage the Lambda Input payload `path` value, which is quite frankly weird, even for AWS.
See this comment: https://github.com/localstack/localstack/issues/12295#issuecomment-2673084002
- No mapping, no custom domain
- `path`: `/your-path` -> stage is stripped
- `requestContext.path`: `/<stage>/your-path`
- Mapping configured with no basePath and no stage:
- `path`: `/<stage>/your-path` -> stage is not stripped
- `requestContext.path`: `/<stage>/your-path`
- Mapping configured with basePath and no stage
- `path`: `/<basePath>/<stage>/example/v1` -> nothing is stripped
- `requestContext.path`: `/<basePath>/<stage>/example/v1`
- Mapping …
> APIGW: fix AWS_PROXY payload with Custom Domains

- tests/aws/services/ec2/test_ec2.py
- tests/aws/services/ec2/test_ec2.snapshot.json
- tests/aws/services/ec2/test_ec2.validation.json
Adding test for the relevant moto change https://github.com/getmoto/moto/pull/8556
> Add test for EBS volume creation without size

- localstack-core/localstack/services/lambda_/event_source_mapping/esm_worker.py
Removes an unnecessary log on shutdown with event source mappings.
- Adds a flag to check if shutdown was graceful before logging an invalid state error.
> [ESM] Remove warning when worker shutdown is graceful

- localstack-core/localstack/testing/scenario/cdk_lambda_helper.py
When building docker images for our tests, it is sometimes useful to be able to include external files into the image. The current way the `generate_ecr_from_dockerfile` utility function works is to copy the Dockerfile into a temporary location, however this does not allow the Docker context to access these other files.
For example, with the following file:
```docker
FROM python:3.12-alpine
COPY app.py /app.py
CMD ["python", "/app.py"]
```
and directory layout:
```
image-path/
Dockerfile
app.py
```
will not build because the `Dockerfile` is copied to a temporary location and built from there.
Add a new flag: `build_in_place` which defaults to `False` (to maintain current default behaviour) which does not copy the Dockerfile away from its original position.
Note: this _may_ induce lots of …
> Util: support building in place for ECR docker images

- localstack-core/localstack/services/lambda_/provider.py
Follow up from #12297, we did not pass the `QueueUrl` to `GetQueueAttributes` but rather the `QueueArn`. This actually still worked somehow because SQS took it as the `QueueName` and was able to resolve it. 
However, when working with cross-account, this did not work because we were not able to resolve to the right account id. 
I thought of doing an internal `connect_to().sqs.get_queue_url(QueueName=name, QueueOwnerAwsAccountId=queue_account)`, to get the proper `QueueUrl`, but if the queue did not exist, it would have raised without triggering an IAM check for `GetQueueAttributes`, so the IAM parity would not be there... so I resolved to build a dummy value instead, as it is not very important and we only need SQS to be able to parse it. 
Upstream run: ✅  13658265278
- build a dummy …
> ESM: fix CreateESM SQS validation

- localstack-core/localstack/aws/protocol/service_router.py
Following #11800, we can remove rules that were in place so that edge router match would be assigned to a service and not to S3 (preventing CORS to be applied). 
Those rules are not relevant anymore, and would not get matched as the edge routes would skip the service name parsing all together.
Edit: we will not change the current logic to fallback to S3, as it could potentially break some use-case. This PR only cleans up the other legacy rules for now, and S3 will be tackled in a follow up. 
~There's a small hack in place to fallback to S3 requests, something suggested by Alex at the time, because right now the "legacy rules" were using some heuristics to try to guess if the request was S3. Now, by using the OP router, we can be somewhat sure if a request is a S3 request or does not fit …
> cleanup ServiceNameParser rules

- localstack-core/localstack/services/ec2/resource_providers/aws_ec2_securitygroup.py
This pr adds tags to cloudformation read result on security groups.
> add tags to cfn read security groups

- .github/workflows/tests-bin.yml
- .github/workflows/tests-cli.yml
- .github/workflows/tests-pro-integration.yml
Sometimes, Pull Requests are open against branches other than master (eg [stacked PRs](https://graphite.dev/blog/stacked-prs)) 
In this case the tests don't currently run against in CI.
Allow the CI tests to run on all PRs.
> Run tests on PRs against all branches

- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_describer.py
- localstack-core/localstack/services/cloudformation/engine/v2/change_set_model_visitor.py
- tests/unit/services/cloudformation/test_change_set_describe_details.py
\* Depends on https://github.com/localstack/localstack/pull/12405
Currently, the POC Update Graph approach to modeling CloudFormation templates does not support CloudFormation Conditions. This gap prevents condition-driven workflows from being accurately tracked or updated within the existing logic. In addition, there is no support for certain intrinsic functions (such as Fn::If, Fn::Not, and Fn::Equals). Furthermore, the modeling layer does not currently handle scenarios where changes in a template result in a new subtype or intrinsic function (for example, switching from one intrinsic function to a different one). This limitation meant that strict type changes to certain template bindings was not supported. Finally, caching mechanisms within the describer visitor are needed. A number of …
> Cloud Formation: [POC] Support for Update Graph Modeling of: Conditions, Intrinsic Functions, and Type Divergences

- .github/workflows/create_artifact_with_features_files.yml
This GH action will add a GH action which based on schedule produces artifacts with all `features.yml` files (also known as feature catalog files) found in the repository. This GH action re-uses this [GH workflow](https://github.com/localstack/meta/pull/17). 
This GitHub Action will be disabled until mid-May, when we start with writing feature files for other services
- Adds a new workflow which generates an artifact with `features.yml` files
> Scheduled GitHub Action to generate artifacts with feature catalog files

- .github/workflows/pr-validate-features-files.yml
This PR adds a new github action workflow which reuses a workflow introduced in [the PR ](https://github.com/localstack/meta/pull/15) in the `localstack/meta` repository. A new workflow validates files containing descriptions of AWS services (aka. feature catalog YAML files). 
Once this workflow is merged, it will provide the following functionality:
- Check that the `features.yml` file is present alongside the provider file (`provider.py`) whenever a file within the specific service is changed
- Validate any updated `features.yml` files against the JSON schema defined in the `localstack/meta` repository.
> Added github action to validate feature catalog files

- tests/aws/services/transcribe/test_transcribe.py
Skip flaky tests in transcribe in order to ensure pipeline stability. 
Follow up changes: https://github.com/localstack/localstack/pull/12479.
> skip flaky tests in transcribe

- .github/actions/build-image/action.yml
Adds a GitHub Action for building the community Docker image, as part of the CircleCI to GitHub Actions migration
- Added new file `build-image/action.yml`
> Added GH action to build community image

- localstack-core/localstack/services/lambda_/invocation/version_manager.py
Currently, if the lambda environment, for currently unknown reasons, does not post logs to LS for an invocation, we error the invocation while trying to print logs.
We should avoid failing the entire invocation, but clearly log a warning, and ideally log the container execution logs as well, to be able to determine the root cause of the missing logs.
* Prevent invocation from failing when we cannot print logs to the console
* Add additional logging to allow investigation of the root cause in the future
> Add error handling if lambda logs are not received from the environment

- localstack-core/localstack/services/lambda_/packages.py
This PR updates the lambda runtime init to the latest version.
Changes are non-user facing only, updated go version and some fixed vulnerabilities.
* No user facing behavioral changes
> Update lambda runtime init

- tests/integration/docker_utils/test_docker.py
I missed fixing one of the flaky tests in the `TestDockerClient` class in the PR #12625 that was merged today. Like `test_is_container_running`, test `test_running_container_names` fails due to a race condition:
```
FAILED tests/integration/docker_utils/test_docker.py::TestDockerClient::test_running_container_names[SdkDockerClient] - AssertionError: assert 'lst_test_4337619e' not in ['lst_test_4337619e', 'sleepy_tu']
```
We need to wait until the container is fully stopped. I also added a retry to the container start step, just to be safe.
- Added function `_assert_container_state` which is used in `test_running_container_names` and `test_is_container_running`
- Added retries to `test_running_container_names`
Tested here (transcribe tests are failing but it is not connected to changes in …
> Added retries to the container state check in TestDocker

- README.md
Update CLI launch instructions with the latest Localstack version.
> Update launch instructions in README.md for 4.5.0

- tests/aws/services/apigateway/test_apigateway_integrations.py
- tests/aws/services/apigateway/test_apigateway_integrations.snapshot.json
- tests/aws/services/apigateway/test_apigateway_integrations.validation.json
Follow up to https://github.com/localstack/airspeed/pull/22 and #12621. Adding tests to validate bracket assignment in vtl template.
> Apigw add tests fot vtl bracket assignment

- localstack-core/localstack/services/apigateway/legacy/provider.py
- tests/aws/services/apigateway/test_apigateway_api.py
- tests/aws/services/apigateway/test_apigateway_api.snapshot.json
- tests/aws/services/apigateway/test_apigateway_api.validation.json
Adding lifecycle test coverage for the IntegrationResponse resource in API Gateway v1.
Adding a "test_lifecycle_integration_response", and adding a small fix in provider.py.
> APIGW: add IntegrationResponse test and fix UpdateIntegrationResponse

- localstack-core/localstack/services/cloudformation/v2/entities.py
- localstack-core/localstack/services/cloudformation/v2/provider.py
- template.yml
- tests/aws/services/cloudformation/v2/ported_from_v1/api/test_changesets.py
- tests/aws/services/cloudformation/v2/ported_from_v1/api/test_stacks.py
- tests/aws/services/cloudformation/v2/ported_from_v1/api/test_templates.py
- tests/aws/services/cloudformation/v2/ported_from_v1/resources/test_stack_sets.py
- tests/aws/services/cloudformation/v2/ported_from_v1/test_template_engine.py
Building on https://github.com/localstack/localstack/pull/12779, implement update_stack
> CFNv2: implement update stack

- localstack-core/localstack/services/dynamodb/provider.py
- localstack-core/localstack/services/dynamodb/server.py
Closes PNX-36.
In LocalStack, whenever we persist the state of a service, we generally perform a few operations:
- Pickle the service's store or the `moto` counterpart.
- If the service uses a 3rd party service (e.g., a Postgres database), we save its state in `/var/lib/localstack/state/<service_name>`. To achieve this step, we usually implement some saving logic (e.g., call a `dump` method) in the `on_before_state_save` hook.
When a service restarts from persistence, it first deserializes its store and then restarts its service from whatever state was dumped in the `/var/lib/localstack/state` folder.
DynamoDB is a particular case, as it keeps a copy of its database in the `/var/lib/localstack/state/dynamodb` all the time and has no `dump` capability. While this works well with cloud pods …
> DynamoDB: fix persistence on manual save

- localstack-core/localstack/services/cloudformation/v2/provider.py
- tests/aws/services/cloudformation/v2/test_list_stacks.py
- tests/aws/services/cloudformation/v2/test_list_stacks.snapshot.json
- tests/aws/services/cloudformation/v2/test_list_stacks.validation.json
The old provider's implementation of `list_stacks` is actually untested, but the implementation is required for the new provider anyway.
* Add validated test for list_stacks
* Implement the list_stacks operation
> CFnV2: implement list-stacks

- CODEOWNERS
Given my role change, I'm no longer needed to review changes in code owners, so I'm removing myself from it!
> remove thrau from CODEOWNERS codeowners

- localstack-core/localstack/config.py
- localstack-core/localstack/state/pickle.py
- localstack-core/localstack/testing/pytest/fixtures.py
- pyproject.toml
- requirements-base-runtime.txt
- requirements-basic.txt
- requirements-dev.txt
- requirements-runtime.txt
- requirements-test.txt
- requirements-typehint.txt
- tests/unit/state/test_pickle.py
This PR introduces a new pair of encoder/decoder based on [`jsonpickle`](https://github.com/jsonpickle/jsonpickle).
This is the first step towards a better serialization backend that avoids tight coupling to the code and focuses on serializing data instead.
`jsonpickle` is well suited for this since:
- It serializes instance variables using standard JSON and includes class metadata (e.g., fully qualified class names) to enable rehydration;
- If the original class is no longer importable (e.g., refactoring), `jsonpickle` fails gracefully instead of raising an exception. This allows us to implement custom recovery or migration strategies
- It supports extensibility via custom handlers, enabling fine-grained control over serialization for specific types, similar to pickle’s `__reduce__` and …
> Introduce jsonpickle serialization backend
