- localstack/services/dynamodbstreams/dynamodbstreams_api.py
- localstack/services/install.py
- tests/integration/test_kinesis.py
This PR mappes the ExpiredIteratorException from the boto3 kinesis getrecords call to the identically named exception for DynamoDBstreams.
This results in clients like the [DynamoDB Streams Kinesis Adapter](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.KCLAdapter.html) to correctly map the exception back to kinesis and request a new shard iterator if needed.
This is a first hotfix for the issues with expiring shard iterators for dynamodbstreams.
Future iterations should contain a 15 minutes shard expiration time instead of the current 5 minutes forced by the kinesis-mock backend.
Also, this PR bumps kinesis-mock to version 0.2.2, to fix issue https://github.com/etspaceman/kinesis-mock/issues/260 and achieve more parity with AWS, and reducing the occurrence of …
> Add handling for DynamoDB stream iterator expiration, bump kinesis-mock to 0.2.2

- localstack/services/cloudformation/models/iam.py
- localstack/services/cloudformation/models/s3.py
- localstack/services/cloudformation/models/sqs.py
- localstack/services/infra.py
Minor fixes:
* Remove obsolete moto imports in CloudFormation resource classes /cc @dominikschubert 
* Fix/refactor some patches with the new decorator
> Remove obsolete moto imports in CloudFormation resource classes

- localstack/services/awslambda/lambda_executors.py
Tiny change that should fix an issue we're currently seeing in our CI builds (if node.js Lambda handlers are returning `undefined` instead of a Thenable):
```
TypeError: Cannot read property 'then' of undefined
at [eval]:1:1082
at Script.runInThisContext (vm.js:134:12)
at Object.runInThisContext (vm.js:310:38)
at internal/process/execution.js:81:19
at [eval]-wrapper:6:22
at evalScript (internal/process/execution.js:80:60)
at internal/main/eval_string.js:27:3   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1370, in _execute
```
(On a side note, the way we're passing the args to the node process could be problematic from a security PoV. This entire logic may become obsolete once we move to the new Lambda executor - yet worthwhile fixing for now)
> Minor fix in printing result for local node.js Lambda executor

- localstack/services/cloudwatch/cloudwatch_starter.py
- tests/integration/test_cloudwatch.py
Since the PR spulec/moto#4732 is merged in upstream, the patch we are using now can be removed .
The `TODO` in the patch were addressed (while fixing the issue #5000)  in the merged PR in the upstream. 
Added Integration test to verify, only the unique metrics(unique combinations of name, namespace and dimensions)  are returned.
> Remove obsolete patch in cloudwatch

- localstack/aws/protocol/parser.py
- tests/unit/aws/protocol/test_parser.py
This PR fixes problems with the ASF parser, in particular regarding rest-json protocols.
1. If a Header field is set, but the header is not present, the payload attribute was not defined. This is fixed now.
2. If the service definition specifies a payload, but part of the necessary data is also present in other shapes (like an uri shape), they were not parsed. This is also fixed now.
Also added a little test that checks the behavior we experienced.
> ASF rest-json parser fixes

- localstack/services/sqs/provider.py
This PR enables http calls directly against the queue URL. Some SDKs (like the dotnet AWS SDK) may create `POST` request to the Queue URL (i.e., call `http://localhost:4566/000000000000/test-queue/`). In that case, the `QueueURL` attribute of the request body will be empty, instead it will be encoded as the URL. This is not picked up by the ASF parser, because it is a special feature of SQS.
> fix ASF SQS provider to allow direct calls to queue URLs

- docker-compose.yml
- localstack/config.py
- localstack/utils/common.py
- tests/unit/test_common.py
This PR provides a utility (`common#external_service_ports`) to reserve ports for external services (like elasticsearch clusters, external databases,...) for a short period of time.
It can check for a specific port (within a configured range) or otherwise tries to find the first free non-reserved port within the configured range.
It is important to check that a given specific port is within the configured range, since localstack is by default started within its Docker container (where the configured port range needs to be published).
This change itself does not break anything, however as soon as the external ports are used, the docker-compose files (or other means of creating the docker container other than using the CLI) of non-pro users might need to be adjusted (such that they also …
> add utility to manage / reserve ports for external services

- localstack/services/dynamodb/dynamodb_listener.py
- tests/unit/test_dynamodb.py
Minor fix in DynamoDB region for NoSQL Workbench. 
Report from a customer: Interestingly, the request `Authorization` headers seem to be coming through with two different "region" specifiers - "localhost" and "local":
```
20220119/localhost/dynamodb
...
20220119/local/dynamodb
...
```
> Minor fix in DynamoDB region for NoSQL Workbench

- localstack/aws/protocol/parser.py
- tests/unit/aws/protocol/test_parser.py
Minor fix in request parsing to match path parameters with slashes. This surfaced during migration of the QLDB service to ASF, where boto3 is making the following request:
```
GET /tags/arn:aws:qldb:eu-central-1:000000000000:ledger/c-c67c827a
```
... for the following botocore `requestUri`:
```
/tags/{resourceArn}
```
In this change, the assumption is currently that only trailing path parameters may contain slashes (e.g., `/my/path/{param}`). however this is not yet fully tested against AWS - i.e., haven't yet discovered a case where a parameter in the middle of a path (e.g., `/my/path/{param}/test`) may contain slashes as well. To be discussed/verified @thrau @alexrashed 
The PR also contains a minor change to raise an explicit `RequestParserError` and avoid `TypeError: StopIteration` …
> Minor fix in request parsing to match path parameters with slashes

- Dockerfile
- requirements.txt
- Make sure that the Docker layers are invalidated when the package version changes in `localstack/__init__py`.
- Align the required version of `localstack-ext` with `localstack`.
> invalidate builder stage in dockerfile on package version changes

- localstack/services/sqs/provider.py
This change makes sure the QueueURL does not contain a potential query parameter. Fix for this comment here: https://github.com/localstack/localstack/pull/5315#issuecomment-1016966136
was too hasty merging the PR ;-)
> use base_url instead of url for determining SQS queue URL

- localstack/aws/protocol/serializer.py
- tests/integration/test_sqs.py
- tests/unit/aws/protocol/test_serializer.py
attempts a fix for #5297 by
* escaping strings using HTML encoding
* adding XML declarations (not complete yet, just for errors)
* adds Content-Encoding: text/xml headers
> fix ASF xml response encoding

- localstack/services/awslambda/lambda_api.py
- localstack/services/awslambda/lambda_executors.py
- localstack/services/install.py
- tests/integration/test_stepfunctions.py
Lazily creates a utility lambda when encountering a lambda invoke call to the `localstack-internal-awssdk` function.
This is used in tandem with https://github.com/localstack/localstack-artifacts/pull/5 to patch in `aws-sdk` support for the stepfunctions api as a temporary workaround until the image at https://hub.docker.com/r/amazon/aws-stepfunctions-local is updated with the corresponding features.
> Introduce lazily-created localstack-internal-awssdk utility lambda function

- localstack/services/apigateway/apigateway_listener.py
Fix for https://github.com/localstack/localstack/issues/5105
If no route is specified ($default), we need to capture method key 'X-AMAZON-APIGATEWAY-ANY-METHOD'
> Capture X-AMAZON-APIGATEWAY-ANY-METHOD for default routes

- localstack/utils/cloudformation/template_deployer.py
Adds a hint that the resource might be available in PRO and the corresponding URL to look this up.
> Provide better log warning when cloudformation resource can't be found

- localstack/aws/protocol/parser.py
- tests/unit/aws/protocol/test_parser.py
Minor fix for request parser to enable `X-Amz-Target` strings that contain multiple dots. (surfaced during migration of CloudTrail API)
> Fix request parser to enable X-Amz-Target strings with multiple dots

- localstack/services/sns/sns_listener.py
- tests/integration/test_sns.py
Addresses #5057 
Follow up to #5215
Extended  SNS `PublishBatch` API to support FIFO Topics and common API specific exceptions.
> Extend SNS publish batch support for FIFO topics 

- localstack/services/kinesis/kinesis_listener.py
- tests/integration/test_kinesis.py
This PR should fix https://github.com/localstack/localstack/issues/4095. It took me a little while to figure out what was causing boto to throw a base64 decode error when retrieving records from Kinesis, but ultimately I identified two problems:
* The Kinesis tests make faulty assumptions about how kinesis/boto handle record encoding/decoding
* The `subscribe_to_shard` function has a special case for re-encoding records when talking to a Java client, but in fact this should happen always.
According to the [Kinesis docs](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecordsRequestEntry.html), Kinesis expects records to consist of base64 encoded data when you `PUT` them to the API. However, boto takes care of this for you behind the scenes: it automatically base64 encodes …
> fix expectations around kinesis record encoding

- localstack/utils/aws/aws_stack.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/test_cloudformation.py
- tests/integration/test_cloudwatch.py
- tests/unit/test_cloudformation.py
Small fix in CloudFormation to recursively resolve string placeholders. 
Fixes the following error which occurs when bootstrapping CDK stacks that contain a placeholder like `arn:aws:...:parameter${CdkBootstrapVersion}` where the name of the SSM parameter itself refers to another stack parameter, e.g., `/cdk-bootstrap/${Qualifier}/version`: 
```
File "/Users/whummer/code/localstack-ext/.venv/lib/python3.8/site-packages/localstack/utils/cloudformation/template_deployer.py", line 740, in resolve_placeholders_in_string
result = re.sub(regex, _replace, result)
File "/Users/whummer/.pyenv/versions/3.8.2/lib/python3.8/re.py", line 208, in sub
return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 1: expected str instance, dict found
```
Potential regression after the …
> Small fix in CFN to recursively resolve string placeholders

- localstack/aws/protocol/parser.py
- tests/unit/aws/protocol/test_parser.py
The REST protocols in ASF (`rest-xml` and `rest-json`) determine the operation a request is targeting based on the incoming request's URI and HTTP method.
With https://github.com/localstack/localstack/pull/5314, we broadened the regular expression used to find the requested operation such that parameters can contain slashes.
This introduced a small regression where "overlapping" request URIs could cause issues with the operation lookup.
For example in OpenSearch's specification, the following two operations have overlapping request URIs:
```
"DescribeDomain":{
"name":"DescribeDomain",
"http":{
"method":"GET",
"requestUri":"/2021-01-01/opensearch/domain/{DomainName}"
},
..."
},
"DescribeDomainConfig":{
"name":"DescribeDomainConfig",
"http":{
"method":"GET", …
```
> fix ASF REST operation lookup with conflicting path params

- localstack/services/sns/sns_listener.py
While using SNS Http Subscription, even though the request has been sent to correct destination, inside localstack`s log we`re receiving error while getting responses body through `requests` lib.
> SNS HTTP Subscription - 'Response' object has no attribute 'get_data'

- localstack/services/cloudformation/models/certificatemanager.py
- tests/integration/cloudformation/test_cloudformation_acm.py
- tests/integration/cloudformation/utils.py
- tests/integration/fixtures.py
* Fix DomainValidationOptions property in ACM Certificate CFN deployment
* Introduce `deploy_cfn_template` fixture that simplifies creating CFN tests and helps reduce the boilerplate a bit
> Fix DomainValidationOptions property in ACM Certificate CFN deployment

- localstack/services/awslambda/lambda_executors.py
Currently, we set this value to '{}' even if not applicable.
With this fix, we prevent this from being set, as many runtimes have problems with it (ruby RIC, rust...).
/cc @calvernaz
> Do not set AWS_LAMBDA_COGNITO_IDENTITY if cognito identity is empty

- localstack/utils/docker_utils.py
- tests/integration/docker_utils/test_docker.py
When connecting a container to a non-default network with an alias, it will be reachable by that alias in that network (additionally to its name). This behavior is helpful when integrating LocalStack into third party services.
This functionality will be needed for integrations between EKS/ECR, and might come in handy in the future as well.
This PR introduces two new methods in the ContainerClient:
* connect_container_to_network
* disconnect_container_from_network
Also, the usage of this methods is tested by querying the docker client, and using the aliases for inter-container communication in simple test cases.
> Allow container client to connect/disconnect containers to/from a network

- localstack/services/kinesis/kinesis_starter.py
attempt to fix failure in `localstack-ext` by correcting reference to kinesis listener instance
> try to fix localstack-ext by correctly restarting kinesis

- localstack/aws/api/sqs/__init__.py
- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
~ASF apparently is generated against cli v1, how to deal with this discrepancy?
For now, add v2 attributes similar to v1 ones so LocalStack accepts them.~
Turns out that the api simply needed re-generating
resolves #5322
> handle SSE for sqs

- localstack/config.py
- localstack/services/sqs/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sqs.py
Fix accessing external SQS port for intra-service communication. The port should only be reported in the queue URL to the outside world, but should not be used for internal service-to-service communication. Addresses #5337
> Fix accessing external SQS port for intra-service communication

- localstack/services/cloudformation/cloudformation_api.py
The `find_change_set` function call within the `get_template` function had its parameters mistakenly inverted. This caused a GetTemplate request which had both a **stack-name** and **change-set-name** to fail.
I changed the positional parameters to named parameters because I'm unsure if there are other areas of localstack which also call `find_change_set` and didn't want to risk breaking them with this change.
**Note**: I'm quite new to localstack and CDK so I'm not sure how to build automated tests yet. Hopefully my textual description and screenshot are sufficient to evaluate this PR?
1. Before fix
1. Install CDK 2.9.0 && cdklocal
2. `mkdir my-first-cdk && cd my-first-cdk`
3. `cdklocal init sample-app --language python`
4. Bootstrap CDK
5. `cdklocal deploy`
6. Comment out …
> Changed postional vars to named

- localstack/utils/aws/message_forwarding.py
- tests/integration/test_events.py
This PR addresses issue #5229. where the user describes that the EventBridge service discards the requests parameters set up in the `connection` resource for the `api destinations`.
Changes:
- Before the service sends a request to the `api destination,` it integrates the parameters described in the connection resource (query, body, header and auth parameters).
- If the connection resource describes  OAuth credentials, the service will try to obtain the token.
- The test that validates the delivery of the events also validates the 3 different types of auth parameters that could be set in a `connection` resource.
> Addition of connection parameters to api destinations (EventBridge)

- localstack/services/sns/sns_listener.py
- tests/integration/test_sns.py
Fixes #5305 
Changes
1.  More defensive approach when accessing the optional `subject` attribute value.
2. Extended the existing test to verify the behaviour.
> Fix : SNS PublishBatch optional subject atttribute

- localstack/services/install.py
- localstack/services/stepfunctions/stepfunctions_starter.py
- tests/integration/cloudformation/test_cloudformation_stepfunctions.py
- tests/integration/fixtures.py
- tests/integration/templates/sfn_apigateway.yaml
- tests/integration/templates/sfn_apigateway_two_integrations.yaml
Corresponds to this PR: https://github.com/localstack/localstack-artifacts/pull/8
This PR simply enables this behavior and adds some tests for both URL schemes we support for local APIs.
Related issue/comment: https://github.com/localstack/localstack/issues/3815#issuecomment-993304614
> Enable invocation of local API URLs via stepfunctions

- .github/workflows/pro-integration.yml
- localstack/services/awslambda/lambda_executors.py
- localstack/services/install.py
- localstack/services/stepfunctions/stepfunctions_starter.py
- tests/integration/test_events.py
PR #5389 introduced a regression by disabling the automatic setting of LOCALSTACK_HOSTNAME, which the local lambda executor relied on.
This PR will, as a first step to get builds green again, inject the endpoint again into the environment variables of the process.
> Fixing integration tests against pro

- localstack/services/cloudformation/cloudformation_api.py
- localstack/services/cloudformation/models/iam.py
- localstack/services/cloudformation/service_models.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/conftest.py
- tests/integration/test_cloudformation.py
- tests/unit/test_cloudformation.py
* Fix passing `Conditions` on stack updates - TODO should be covered by a test
* Refactor CFN function arguments - removing the redundant `stack_name` and `resources`, using single `stack` parameter instead. This is only a first iteration, which should hopefully make future refactorings a bit easier..
Requires a change in -ext to be released in tandem.
> Fix passing Conditions on stack updates, refactor CFN func args

- Dockerfile
- docker-compose.yml
- Removes the explicit download of the LetsEncrypt CA (LetsEncrypt R3 is already contained in the python base image).
- Removes the elasticsearch port from docker-compose and the exposed port list in the Dockerfile (ElasticSearch and OpenSearch are now using the external service port range).
- Exposes the external service port range in the Dockerfile / the resulting docker image.
- Describes the different bound ports in the example `docker-compose.yml`.
> update exposed ports and example docker-compose

- localstack/aws/protocol/parser.py
This PR fixes an uncapped recursion bug which occurs when parsing API parameters which are delivered via HTTP Headers
> Fix uncapped recursion bug in parser

- localstack/config.py
- localstack/services/awslambda/lambda_executors.py
- localstack/utils/aws/aws_models.py
- tests/unit/test_lambda.py
This PR makes the output truncation configurable, providing a default that keeps backwards compatibility.
The new introduced variable is called `LAMBDA_TRUNCATE_STDOUT`
> make lambda output truncation configurable

- .circleci/config.yml
- localstack/services/install.py
- localstack/services/opensearch/versions.py
- tests/integration/conftest.py
- tests/integration/test_es.py
- tests/integration/test_opensearch.py
This PR will separate the jobs for building the container and testing the container, allowing for future test parallelism and reduced per-job runtime.
Also, the ARM tests now run without any emulation of AMD64, ElasticSearch uses again the statically bundled version in the -full image, some test cleanups in ES/opensearch tests and installing the correct architecture of ES if installed dynamically.
> CircleCI workflow revamp

- localstack/aws/protocol/serializer.py
- tests/unit/aws/protocol/test_serializer.py
implements `header`, `headers`, `statusCode` and `payload` serialization and  for `json-rest` protocol in the ASF serializer.
* i renamed `_serialize_payload`, which was the abstract entry point for serialization, into `_serialize_response`, to indicate that it can handle traits outside the payload
* the method is kinda generic, but can't be re-used yet because it relies on the special `_serialize` method of the `JSONResponseSerializer`, which parses shapes into a dict that can later be used as basis to serialize the request.
* i added two small features to the `_botocore_serializer_integration_test`:
1. it now returns the parsed response so we can assert header fields
2. i added a `_skip_assert` sentinel object to skip the internal assert for cases where the response dict may contain …
> implement location trait serialization for json rest protocol

- tests/integration/test_opensearch.py
Currently, the integration test which tests the SingletonClusterManager (which is managing the cluster if the `OPENSEARCH_ENDPOINT_STRATEGY=port` and `OPENSEARCH_MULTI_CLUSTER=false`) does not wait for the cluster to be up or tests if the cluster can be reached.
Since the cluster is not yet started, it cannot be properly shut down (Server#do_shutdown raises an exception which is swallowed by #call_safe).
This PR fixes the cleanup by extending the test to wait for the cluster to be up and testing if the cluster really is reachable.
/cc @dfangl
> fix opensearch cluster shutdown in tests

- localstack/aws/protocol/parser.py
- tests/unit/aws/protocol/test_parser.py
When migrating CloudFront to ASF, I noticed that the provider always gets `None` arguments.
This seems related to some problem in the parser.
When a payload is specified in the output shape, the payload itself is actually parsed correctly (line 592-593) but then the entire dictionary is set to `None` while parsing the rest of the shape.
To get along with the migration, I simply added a `return` after line 594 to temporary fix the problem.
This do not fix the issue when there is no payload (see `test_parse_cloudfront_with_botocore`).
https://github.com/localstack/localstack/blob/75f7e3034bd27e1c9a46a70ededcc06bbe2bd5c5/localstack/aws/protocol/parser.py#L591-L598
> fix asf xml-rest parser location- and payload-trait handling

- localstack/services/route53/route53_listener.py
- requirements.txt
- tests/integration/test_route53.py
Bump version of moto-ext to 3.0.1. Pinning the version for now, to avoid instabilities with upgrades in the future.
> Bump version of moto-ext to 3.0.1

- .github/workflows/rh-support.yml
- Dockerfile.rh
- Makefile
- bin/localstack
- bin/supervisord.conf
- localstack/services/infra.py
- requirements.txt
This PR contains changes to smoke-test LocalStack against RedHat / rpm based operating systems:
- Add a `Dockerfile.rh` which is based on  `redhat/ubi8` in order to build LocalStack on a RedHat / rpm based system.
- This Dockerfile - in contrast to the default Dockerfile - does _not_ add the latest source code to the image, but installs the latest packages from PyPi. This means that the image may _not_ contain the latest changes in the repo.
- Add a new GitHub action (`smoke-tests-against-redhat`) to build the image and perform the CI smoke tests.
- Removes the deprecated `infra` make target (since there is no code in the RedHat Docker image).
> add Dockerfile and GitHub action to smoke-test RedHat compatibility

- localstack/services/cloudwatch/cloudwatch_starter.py
- tests/integration/test_cloudwatch.py
This PR enables the triggering of actions that are set on alarms, when calling `set_alarm_state`.
Limitations: 
- Currently only SNS is supported as action. 
- Metrics are not yet evaluated, only the `set_alarm_state` will change the state of an alarm and therefore trigger actions.
> Cloudwatch implement set_alarm_state

- localstack/services/edge.py
This should fix an issue (`Unable to find forwarding rule for host`) where the forwarding rule is not found when using the AWS SDK v2 in java to call STS assumeRole.
> fix edge route mapping for STS AssumeRole

- localstack/utils/common.py
- tests/unit/test_common.py
This PR adds a helper class for handling paging and filtering in AWS services in a unified way. This is useful for avoiding boilerplate code in ASF implementations of services.
An example usage would be: 
```python
[...]
paginated_list = PaginatedList(EntityRegion.get().entity.values())
page, next_token = paginated_list.get_page(
next_page_token,
lambda entity: entity[Id],
page_size=max_results,
filter_function= lambda entity: entity["Name"] != "BAD"
)
[...]
```
> Add PaginatedList for paginating and filtering response lists

- tests/integration/fixtures.py
- tests/integration/test_sqs.py
Currently, the create_lambda_function fixture depends on the kwargs["func_name"] being set, but that is not set by sqs tests.
Therefore, we have 240s waiting times which are not necessary at all, which can fail the tests due to job execution timeouts.
This should shave off 6-9 min off our test times.
Also the function signature has changed, to prevent this in the future.
> Fix increase in testing time due to missing kwargs in sqs test

- localstack/config.py
- tests/unit/test_config.py
Embarrassingly, the current implementation uses lstrip, which is the completely wrong method for the purpose. (shame on me)
This PR changes the stripping of the provider override to a substring operation (removeprefix is sadly only available in python3.9 and upward), instead of the currently completely wrong lstrip.
Also, some unit tests are added to test the behavior of the ProviderConfig class in general.
> Fix service provider configuration override

- localstack/services/cloudformation/deployment_utils.py
- localstack/services/cloudformation/models/elasticsearch.py
- tests/integration/test_cloudformation.py
- tests/unit/test_cloudformation.py
* fix replacement of `AWS::NoValue` in dict values
* add default props for `Elasticsearch::Domain` CloudFormation resources
> Fix replacement of AWS::NoValue, add default props for Elasticsearch::Domain resources

- localstack/aws/protocol/parser.py
- localstack/aws/protocol/serializer.py
- localstack/aws/scaffold.py
- localstack/services/install.py
- tests/unit/aws/protocol/test_parser.py
- tests/unit/aws/protocol/test_serializer.py
This PR contains a set of fixes for the ASF parser, serializer, and scaffold:
- (misc) remove an unexpected CLI dependency on ASF/werkzeug due to a module import in `install.py`.
- (scaffold) fix issues with minifying generated APIs when parameters or types are called `type`.
- (parser) fix invalid blob payload decoding
- (parser) fix greedy URI path param handling
- (parser) fix uri location decoding
- (parser) fix empty payload handling
- (serializer) fix None list/structure/map serializations
The fixes have been verified by newly written or adapted unit tests, as well as with the ASF parser challenger executed in the pipeline of PR #5411.
Since each commit contains explicitly one fix, it might make sense to avoid squashing these commits (for the sake of traceability).
> fix some ASF parser, serializer, and scaffold issues

- localstack/services/cloudformation/models/stepfunctions.py
Add support for `DefinitionS3Location` in StepFunctions CloudFormation model. Resolves a user issue - logic tested locally, running `samlocal deploy` with this template:
```
Transform: "AWS::Serverless-2016-10-31"
Resources:
StateMachine:
Type: AWS::Serverless::StateMachine
Properties:
Name: MyStateMachine
DefinitionUri: template.json
Role: testrole
DefinitionSubstitutions:
MyLambdaArn: test
```
> Add support for DefinitionS3Location in StepFunctions CFn model

- localstack/services/edge.py
- localstack/services/infra.py
- localstack/services/opensearch/cluster.py
- localstack/services/opensearch/cluster_manager.py
- localstack/services/plugins.py
- tests/integration/test_es.py
I guess when a service is in a STOPPED state it should also try to start it again (and wait in case it is currently stopping). 
Also prevents the kinesis restart error spam during test execution.
> Allow service restart in ServiceContainer from STOPPED state

- localstack/utils/persistence.py
- tests/unit/utils/test_persistence.py
minor change to remove the deprecated use of `loclastack_ext.constants.VERSION`
> remove deprecated use of localstack version constant

- localstack/aws/api/core.py
- localstack/aws/skeleton.py
- localstack/services/cloudwatch/cloudwatch_listener.py
- localstack/services/cloudwatch/provider.py
- localstack/services/edge.py
- localstack/services/moto.py
- localstack/services/providers.py
- tests/integration/test_moto.py
This PR adds a simple API and the underlying machinery to dispatch ASF requests to moto without an HTTP roundtrip. IThe API facilitates migration of services to ASF that rely heavily on moto by providing three basic request patterns. The PR also demonstrates a simple migration of CloudWatch. 
The three patterns are:
* Proxy an HTTP request to moto
* Call moto to receive an AWS response dictionary
* Wrap an ASF provider to route all non-implemented methods to moto 
Forwards a request to moto and forego parsing of the response, and instead just returns the HttpResponse
```python
def proxy_moto(context: RequestContext) -> HttpResponse:
```
In an ASF provider, this method can be useful if you want do something on the low-level http response rather than the higher-level AWS response dict. To …
> implement in-memory request dispatching to moto

- localstack/utils/cloudwatch/cloudwatch_util.py
Simply adds an optional boolean flag to check if the cw store logs utils should create the log group if it doesn't exist, since auto-creating this isn't always desired. (e.g. when `awslogs-create-group` is set to false in a task definition)
> make autocreating log groups in cw utils optional

- localstack/aws/protocol/parser.py
- localstack/aws/protocol/serializer.py
- tests/unit/aws/protocol/test_parser.py
- tests/unit/aws/protocol/test_serializer.py
This PR contains fixes for the following issues detected in the current ASF protocol implementation:
- fix parsing lists from the query string
- fix the operation detection for specifications which a query parameter in the request URI pattern
- fix rest-xml serialization for operation specs which do not define an output shape
- fixes https://github.com/localstack/localstack/pull/5477
- fix the location and payload handling for rest-xml
The fixes turned out to cause quite a restructuring of the serializer, but the new structure is more aligned with botocore's implementation and the features of the different protocols.
> fix another set of ASF parser and serializer issues

- localstack/utils/aws/templating.py
- localstack/utils/common.py
- localstack/utils/generic/number_utils.py
- localstack/utils/generic/wait_utils.py
- localstack/utils/net_utils.py
- tests/unit/utils/analytics/test_metadata.py
- tests/unit/utils/test_net_utils.py
Add `resolve_hostname(..)` util function, refactor some utils into sub-modules.
Currently still leaving the imports in `common.py` to keep them accessible from other places - left a `TODO` to refactor the imports in the remaining codebase, so we can later remove the imports from `common.py`
> Add resolve_hostname(..) util function, refactor some utils into sub-modules

- localstack/services/apigateway/apigateway_listener.py
This PR passes the region name parameter to the method `helpers.get_rest_api_paths` after the region lookup being removed from the patching phase.
> Get rest api paths region from invocation

- localstack/services/apigateway/apigateway_listener.py
- tests/integration/test_api_gateway.py
This PR adds s3 integration using the action name. We already support `arn:aws:apigateway:us-west-2:s3:path/{bucket}/{key}` scheme and this PR adds support to `arn:aws:apigateway:us-west-2:s3:action/GetObject&Bucket={bucket}&Key={key}`
Resolve https://github.com/localstack/localstack/issues/5508
> apigateway s3 integration using action name

- localstack/utils/generic/wait_utils.py
The wait_utlis.py has an unconditional import to typing_extensions, which is only a dependency for python versions < 3.8 currently.
This leads to errors (most notably in the CLI) when trying to use this module.
This PR fixes this behavior by introducing a check for the python version, to use the typing import instead of the typing_extensions import for versions that support it.
> Fix CLI/runtime dependency issue with typing_extensions

- .github/renovate.json
This PR adds the `Dockerfile.rh` to the `ignoredPaths` in the config of RenovateBot.
After this PR is merged, Renovate should close the PR it created to pin the sha on the base image automatically (https://github.com/localstack/localstack/pull/5533).
> update renovatebot config to ignore Dockerfile.rh

- localstack/services/awslambda/lambda_starter.py
- localstack/services/logs/logs_listener.py
- tests/integration/test_secretsmanager.py
This PR addresses issue #5279. That shows the SecretManager service from Moto crashing due to trying to invoking a Lambda function that doesn't exist inside Moto.AWSLambda.
Changes:
- Patch Moto.awslambda.models.LambdaBackend.get_function, to search lambdas from Localstack. 
- Patch Moto.awslambda.models.LambdaFunction.Invoke to allow the execution of a Localstack Lambda function.
- Test of the secret_rotate method with a LambdaFunction
- Deletion of a similar patch that the Logs Service used to apply.
> Fix: Patch Moto Lambda Backend to access Localstack Lambdas

- localstack/services/sqs/sqs_listener.py
- tests/integration/test_sqs.py
Small PR that checks a fifo queue creation. AWS requires both the name of the queue ending with `.fifo` and the attribute `{FifoQueue: true}` to be present. 
An error should be raised if the attribute is not present and the name ends with `.fifo` (normal queues do not allow the `.` char). The ASF provider already implements this check.
> Adding error check while creating sqs fifo queues

- localstack/aws/protocol/serializer.py
- localstack/aws/skeleton.py
- tests/unit/aws/protocol/test_serializer.py
In instances where the result of API calls needs to split up into body and header fields, the result given by the handlers is edited in place. This can lead to unwanted mutations which affect the service state. By using a deep copy of the result for serialization this can easily be avoided.
> Add deep copy of handler results to avoid unwanted mutations

- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
Add ability to tag and push images using our Docker clients (helps in removing the dependency to `docker` binary in our tests).
The test contains a few examples of invalid pushes (access denied, connection refused), however no actual successful pushes are added, to avoid spamming the registry with data. (We could consider spinning up a local registry at some point, but seemed too much overhead at this stage.)
> Add ability to tag and push images using Docker client

- localstack/services/infra.py
- localstack/services/internal.py
- localstack/utils/diagnose.py
- tests/integration/utils/test_diagnose.py
This PR adds an enpoint `/_localstack/daignose` that prints various diagnostic data about localstack that will help with user support. Here is some example output: [diagnostics.txt](https://github.com/localstack/localstack/files/8111599/diagnostics.txt)
To test, first check out the branch, and run `bin/docker-run.sh make infra` in localstack-ext.  Then call `curl localhost:4566/_localstack/diagnose`
> add endpoint to output diagnostics data

- localstack/config.py
- localstack/services/generic_proxy.py
Simply pulls out the environment variable into a config var. This will then be used in localstack-ext as well to skip the SSL cert downloading. This is a prerequisite for #5502
> add config variable for SKIP_SSL_CERT_DOWNLOAD

- localstack/services/cloudwatch/provider.py
- tests/integration/test_cloudwatch.py
This PR fixes an encoding issue for the `AlarmDescription` set with the `put-metric-alarm` for cloudwatch.
https://github.com/localstack/localstack/issues/5489
> fix encoding problem for AlarmDescription in put-metric-alarm

- localstack/utils/aws/templating.py
- requirements.txt
This PR upgrades `airspeed` to the latest version and removes previous custom patches.
> upgrade airspeed dependency and remove custom patches

- requirements.txt
[flake8-black](https://github.com/peterjc/flake8-black) just released a new version ([0.2.5](https://github.com/peterjc/flake8-black/releases/tag/v0.2.5)) which is not compatible with our pinned black version.
This PR pins the version of flake8-black to avoid these issues.
In the future, we might switch to the newest version of both libraries (f.e. we could enable the preview feature of black to ease upgrades to the next major version of black).
> fix linting issues by pinning flake8-black

- localstack/aws/protocol/parser.py
- localstack/aws/protocol/serializer.py
- localstack/services/sqs/provider.py
- tests/unit/aws/protocol/test_parser.py
- tests/unit/aws/protocol/test_serializer.py
After https://github.com/localstack/localstack/pull/5488, https://github.com/localstack/localstack/pull/5470, and https://github.com/localstack/localstack/pull/5512, this is the fourth round of fixes for the parsers and serializers of ASF.
- fix EC2 serialization when root node is empty
- Fixes the serialization of empty EC2 responses.
- fix json protocol datetime serialization
- Fixes the datetime serialization for JSON body parameters (by avoiding an unnecessary rounding).
- fix rest-xml protocol header datetime serialization
- The datetime serialization of header fields according to RFC822.
- fix query protocol parsing of non-flattened list of maps
- Non-flattened list prefixes are defined by their member's name. Only as a fallback "member." …
> fix ASF parser and serializer issues - round 4

- .git-blame-ignore-revs
- localstack/services/moto.py
- tests/integration/test_moto.py
* addresses what we are seeing in #5456 
```
localstack  | 2022-02-25T17:20:57.061:ERROR:localstack.aws.protocol.serializer: Response object contains a member which is not specified: ResponseMetadata
localstack  | Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/localstack/aws/protocol/serializer.py", line 903, in _serialize_type_structure
localstack  |     member_shape = members[member_key]
localstack  | KeyError: 'ResponseMetadata'
localstack  | {
localstack  |     "Version": 1
localstack  | }
```
since `response` contained the `ResponseMetadata` object as expected, from the botocore response parser, the subsequent ASF serialization process of `call_moto` calls would raise this error if you didn't explicitly remove the attribute. the regular way was to do th …
> add flag to call_moto to exclude the ResponseMetadata

- localstack/services/apigateway/apigateway_listener.py
- localstack/services/apigateway/helpers.py
Add support to MOCK response templates to apigateway. We need to apply the same mechanics to all integrations, however this PR only handles for MOCK integrations.
Fixes https://github.com/localstack/localstack/issues/5546
> add support to mock response templates

- Dockerfile
Unfortunately, the last update of the Docker base image hashes broke the tests due to an issue in `xmltodict` in combination with a new version of `Expat` which landed in Debian last week: 
- https://github.com/libexpat/libexpat/issues/572
- https://github.com/martinblech/xmltodict/issues/289
This issue causes an STS test failure in the following lines in moto: [moto/sts/models.py#L100-L105](https://github.com/spulec/moto/blob/14a69c752477c385d3c80429c719af0aa1cb9d5e/moto/sts/models.py#L100-L105)
This PR reverts the [last change of Renovate](https://github.com/localstack/localstack/commit/a4f3a17a4c50124bb37333578ece0ff9d2cc5fdc) to fix the issue until a fix in `xmltodict` has been pushed.
> revert Python base image hash to circumvent xmltodict issues

- localstack/aws/scaffold.py
- requirements.txt
Currently the ASF scaffold only formats the file with black. Often there still is the problem that the imports are unsorted or contain packages which are unused (notably datetime). By adding autoflake and isort to the formatting section of scaffold these problems and future problems adding new imports are resolved.
> Add optimizing and sorting of imports to scaffold

- .gitignore
- localstack/utils/aws/templating.py
- tests/unit/test_templating.py
* add support for `#define` function in API Gateway velocity templates. Addresses https://github.com/localstack/localstack/issues/5587
* migrate tests to `pytest`
> Add support for #define function in API Gateway velocity templates

- Dockerfile
- Makefile
- pyproject.toml
- requirements.txt
This is in preparation for using the new plugin discovery mechanism introduced with plux 1.3.0, and also to phase out localstack-plugin-loader in favor of plux
> migrate from localstack-plugin-loader to plux

- localstack/cli/localstack.py
Apparently we lost python 3.7 compatibility when we updated the `localstack status` command. The culprit was the `TypedDict` import, see discussion here: https://github.com/localstack/plux/issues/1
> fix python 3.7 compatibility with TypedDict for cli

- localstack/aws/protocol/parser.py
- localstack/aws/protocol/serializer.py
- localstack/aws/proxy.py
- localstack/aws/scaffold.py
- tests/unit/aws/protocol/test_parser.py
- tests/unit/aws/protocol/test_serializer.py
- tests/unit/aws/test_scaffold.py
After https://github.com/localstack/localstack/pull/5488, https://github.com/localstack/localstack/pull/5470, https://github.com/localstack/localstack/pull/5512, and https://github.com/localstack/localstack/pull/5567, this is the fifth round of fixes for the scaffold, parsers, and serializers of ASF.
- fix error handling in parser and serializer
- Introduces a clear exception handling for the parsers and the serializers. They either raise an exception which clearly states that the input data is invalid (a protocol error) or that an unknown error occurred.
- fix formatting of generated code in scaffold
- Fixes the code which is generated by the scaffold such that it passes our linting.
- Adds "Optional" to the list of keywords to fix generated APIs …
> fix ASF parser and serializer issues - round 5

- localstack/services/apigateway/integration.py
- localstack/services/opensearch/cluster.py
This PR is a fix for the recently introduce persistence changes in ext. The `data_root` would be empty, despite the fact that `PERSIST_ALL` is set to `True`. The `if data_root not None` check would not capture that, so we introduce a falsyness check instead of a `not None`.
The apigateway change is just a minor fix that removes a warning when generating the plugins.
> fix opensearch pro integration

- localstack/config.py
- localstack/runtime/events.py
- localstack/services/edge.py
- localstack/services/events/events_listener.py
- localstack/services/infra.py
- localstack/services/internal.py
- localstack/utils/analytics/event_publisher.py
- localstack/utils/analytics/metadata.py
- localstack/utils/analytics/publisher.py
- localstack/utils/asyncio.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/common.py
- localstack/utils/run.py
- localstack/utils/testutil.py
- tests/integration/conftest.py
This PR removes the boto3 dependency of config.py, and removes the dependency to `common.INFRA_READY`, as well as a dependency from various packages to `utils.testutil`.
This is in preparation for the standalone cli package, to remove the runtime dependency to boto
> refactor config imports

- localstack/config.py
- localstack/constants.py
- localstack/contrib/thundra.py
- localstack/services/awslambda/lambda_api.py
- localstack/services/awslambda/lambda_starter.py
- localstack/services/awslambda/lambda_utils.py
- localstack/services/infra.py
- localstack/services/install.py
This PR is a follow up to #5615 that targets the CLI startup performance. Particularly it addresses two things in config and constants (two modules that are *always* imported):
* `config.py`: checking whether docker is available was done via a `docker ps` subprocess call. that takes about ~250ms on my machine. replacing that with `shutil.which('docker')` reduces that to only 10ms.
* `constants.py`: the patching of `MOTO_ACCOUNT_ID` requires importing moto. however the CLI doesn't really need moto unless we start the infra in host mode. that takes another ~300ms, which we can skip in certain circumstances. so i added a simple env var switch for now.R
> improve cli startup performance

- localstack/services/generic_proxy.py
- localstack/utils/server/http2_server.py
- tests/unit/utils/test_http2_server.py
Add ability to specify request timeout and max content length for HTTP server. Preparation for a fix for #5598
> Add ability to specify timeout and max content length for HTTP server

- localstack/cli/localstack.py
Adds a 2 second timeout to `localstack status services` to avoid long wait times in windows.
> add timeout to status services cli command

- localstack/services/awslambda/lambda_api.py
- localstack/services/awslambda/lambda_executors.py
- tests/integration/test_stepfunctions.py
Fixes #4651
Should now correctly return a json response when an uncaught exception is thrown during the handler execution.
> Fixes error responses from lambda when handler throws an exception

- localstack/services/awslambda/lambda_api.py
Minor fix in extracting error details from Lambda responses. Addresses:
```
...
File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1831, in invoke_function
result = run_lambda(
File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 817, in run_lambda
response = json.loads(e.result)
File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```
> Minor fix in extracting error details from Lambda responses

- localstack/services/apigateway/apigateway_listener.py
- localstack/services/apigateway/context.py
- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/integration.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/aws/templating.py
- localstack/utils/objects.py
- tests/unit/test_apigateway.py
- tests/unit/test_templating.py
- tests/unit/utils/test_common.py
This PR is mostly an effort to normalise request templates and response templates:
* Adds two new classes to handle templating, `RequestTemplates` and `ResponseTemplates`. Adds some logging similar to AWS transformations and creates the namespace only with `variables`.
* Adds a new class `VtlTemplate` and nests two existing classes `VelocityUtil` and `VelocityInput`. Fixes the namespace creation that will make it possible to handle AWS template mapping features. 
Yet to finish on another PR:
- Migrate all integrations (SNS, etc..) to the new request/response templates. Lacking testing on those integrations made me think that we should increase coverage before making these changes.
Fixes https://github.com/localstack/localstack/issues/5587
Relates with …
> Refactor request and response templates.

- localstack/services/apigateway/apigateway_listener.py
- localstack/services/apigateway/context.py
- localstack/services/awslambda/lambda_api.py
Minor fixes for API Gateway Lambda request context.
* fix initializing dict instead of set in invocation context
* removed obsolete `event_context` parameter which is no longer used (and in fact overwrites the request `context` with Cognito identity information passed in Pro)
This is a follow-up for #5618 - aiming to get this merged once the tests are passing, to restore a 🟢 pipeline.
> Minor fixes for API Gateway Lambda request context

- localstack/services/s3/s3_listener.py
- tests/integration/test_s3.py
This PR addresses issue #5579. 
Changes:
- Removed leading slash from S3 key.
> Fix redirect to index file in S3 website

- localstack/services/cloudformation/cloudformation_api.py
- localstack/services/cloudformation/models/cloudformation.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/cloudformation/test_cloudformation_nestedstacks.py
- tests/integration/templates/nested-stack-output-refs.nested.yaml
- tests/integration/templates/nested-stack-output-refs.yaml
Fixes an issue in CloudFormation nested stacks where it couldn't resolve outputs from nested stacks in the parent stack. 
Outputs from nested stacks were also merged into the parent stack for some reason which has been removed again to be in parity with AWS.
/cc @alexrashed
> Fix nested stack outputs in CloudFormation

- localstack/utils/patch.py
- tests/unit/utils/test_patch.py
Minor update in patch decorator to allow multiple/composite patches of methods. This covers a case that has come up recently, as we're now patching certain service methods twice (from community, and pro code base).
> Minor update in patch decorator to allow multiple/composite patches of methods

- localstack/services/cloudformation/models/ec2.py
- tests/integration/cloudformation/test_cloudformation_ec2.py
- tests/integration/fixtures.py
- tests/integration/templates/ec2_vpc_default_sg.yaml
- tests/integration/test_ec2.py
- tests/integration/test_rgsa.py
- tests/integration/test_route53.py
VPCs come with a default security group and a default network ACL. 
This PR adds the corresponding support for using CloudFormation GetAtt/Ref.
> Add GetAtt support for AWS::EC2::VPC DefaultSecurityGroup and DefaultNetworkAcl

- localstack/utils/objects.py
- tests/unit/utils/test_objects.py
Minor change to lazily load subclasses for instance manager. This is required to discover subtypes if new plugins are dynamically loaded (imported) at runtime.
> Lazily load subclasses for subtypes instance manager

- localstack/aws/protocol/parser.py
- tests/unit/aws/protocol/test_parser.py
This PR fixes a small issue in ASF's `QueryRequestParser` for operations without a specified input shape.
- `RequestParser#_parse_shape` now returns `None` if the input shape is not given.
- The `QueryRequestParser` then returns an empty dictionary (i.e. no args for the operation).
/cc @giograno (thanks for the report)
> fix query request parser for operations without input shape

- localstack/services/dynamodb/dynamodb_listener.py
- tests/integration/test_dynamodb.py
[related bug](https://github.com/localstack/localstack/issues/5656)
since time.time() returns a float where the left side is in seconds and the right side is the number of microseconds, down casting to an int removes the microseconds and maintains the seconds.
conversion from epoch to datetime is still working and tests show that the microseconds are now 0
> Rounding ApproximateCreationDateTime to seconds

- localstack/utils/cloudformation/template_deployer.py
- tests/integration/cloudformation/test_cloudformation_cognito.py
- tests/integration/fixtures.py
- tests/integration/templates/cognito_identity_pool_role_attachement.yaml
This PR adds support for `Cognito::IdentityPoolRoleAttachment.RoleMappings`.
In CloudFormation the `RoleMappings` field can contain a field `IdentityProvider`, which is not support by the boto client. Instead it's used as a key.
Further Information here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-identitypoolroleattachment-rolemapping.html
related bug: #5669
> add Cognito::IdentityPoolRoleAttachment in cloudformation

- localstack/services/cloudformation/models/sqs.py
- tests/integration/cloudformation/test_cloudformation_sqs.py
- tests/integration/templates/sqs_fifo_autogenerate_name.yaml
A recent fix in moto lead to issues for customers using FIFO queues because we didn't account for the required FIFO queue suffix `.fifo` when auto-creating the names with CloudFormation.
Fixes #5692
> Fix name autogeneration for SQS fifo queues

- localstack/services/cloudformation/models/__init__.py
- localstack/services/cloudformation/models/cdk.py
- tests/integration/cloudformation/test_cloudformation_cdk.py
- tests/integration/cloudformation/test_cloudformation_s3.py
- tests/integration/fixtures.py
- tests/integration/templates/cdk_init_template.yaml
Just a small dummy Cloudformation resource for the AWS::CDK::Metadata resource type that is by default added to every stack deployed via CDK.
> Add support for AWS::CDK::Metadata

- localstack/services/s3/s3_starter.py
Changes introduced in https://github.com/spulec/moto/pull/4929 and https://github.com/localstack/moto/commit/eed32a5f72fbdc0d33c4876d1b5439dfd1efd5d8 break the S3 provider.
```
...
File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
return new(target, *args, **kwargs)
File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 163, in convert_to_flask_response_call
return fn(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 127, in __call__
result = self.callback(request, request.url, dict(request.headers))
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 261, in _wrapper
response = f(*args, **kwargs)
File …
```
> Fix S3 moto invocations

- localstack/services/apigateway/apigateway_listener.py
- localstack/services/apigateway/context.py
Sources the `domainName` and `domainPrefix` from invocation context setup downstream.
Addresses https://github.com/localstack/localstack/issues/5603
> sources domain and domain prefix from invocation context

- localstack/services/awslambda/lambda_api.py
- localstack/services/edge.py
- localstack/services/generic_proxy.py
- localstack/services/sts/sts_listener.py
- tests/integration/test_edge.py
- tests/integration/test_sts.py
Minor fixes for issues that were discovered during testing the integration with [Mulesoft AnyConnect](https://www.mulesoft.com/platform/cloud-connectors) and when testing against AWS:
1. Support "Accept" header to switch response format. Currently supports only XML->JSON conversion - this will be more nicely generalized once we have the new Gateway in place. /cc @thrau @alexrashed 
2. Fix Flask app routes in Lambda API, to avoid returning 308 redirects for trailing slashes. This can ultimately cause invalid redirects and connection errors in our [edge proxy forwarding](https://github.com/localstack/localstack/blob/ae986b92e74e9d00f13c5a8162867dd94e42c5b2/localstack/services/generic_proxy.py#L661-L668). (as flask is internally using `werkzeug` to [construct the redirect …
> Support "Accept" header to switch response format; fix Flask app routes for Lambda API

- localstack/services/acm/provider.py
- tests/integration/fixtures.py
- tests/integration/test_acm.py
Fixes the `DomainValidationOptions` for ACM's `DescribeCertificate` operation.
The previous implementation did not use the existing array of the cert in the CertBundle, but tried to resolve a non-existing attribute, which in the end wasn't set (since the `addenda` would only be used for non-existing keys in the result).
This fix is necessary to fix the ACM waiter on `certificate-validation`, which can be executed with awscli / awscli-local:
```
$ awslocal awslocal acm request-certificate --domain-name test-domain.localhost.localstack.cloud
{
"CertificateArn": "arn:aws:acm:us-east-1:000000000000:certificate/1547a44e-8ff9-4ee3-92f3-7e0f2bcf9b74"
}
$ awslocal acm wait certificate-validated --certificate-arn "arn:aws:acm:us-east-1:000000000000:certificate/1547a44e-8ff9-4ee3-92f3-7e0f2bcf9b74" …
```
> fix ACM DomainValidationOptions to support waiters

- localstack/services/cloudformation/models/route53.py
- tests/integration/cloudformation/test_cloudformation_route53.py
- tests/integration/templates/route53_recordset_without_resource_records.yaml
Fixes a small regression which was introduced with https://github.com/localstack/localstack/pull/5695 where _CloudFormation_ deployments fail if the template contains _Route53_ `RecordSets` which do not have `ResourceRecords` set ([even though these are optional](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html)).
> fix CloudFormation Route53 deployment without ResourceRecords

- tests/integration/test_ec2.py
An EC2 test for terminate instance fails with: 
```
if http.status_code >= 300:
error_code = parsed_response.get("Error", {}).get("Code")
error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.exceptions.ClientError: An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id 'ami-d3adb33f' does not exist
/home/runner/work/localstack/localstack/localstack-ext/.venv/lib/python3.8/site-packages/botocore/client.py:725: ClientError
```
Reason for failure: The CI runs this test against the pro edition. The Docker EC2 provider expects a valid AMI ID corresponding to a Docker image.
This test is removed as redundant because:
- The functionality is tested in -ext …
> Remove redundant EC2 test

- localstack/services/apigateway/apigateway_listener.py
This PR fixes a scenario where the lambda response has a `404` as a status code (check https://github.com/localstack/localstack/issues/5689 for details) and it was entering this unrelated code path. Moving the deserialization code under the respective code path avoids decoding a binary response
Test example https://github.com/localstack/troubleshooting-issues/tree/main/issue_5689
Addresses https://github.com/localstack/localstack/issues/5689
> fix eager deserialization for for 404 responses that come from lambda

- localstack/services/ec2/provider.py
- tests/integration/terraform/ec2.tf
- tests/integration/test_terraform.py
Fix Terraform creation of EC2 Security Groups with default egress.
Prior to this change, the following TF script:
```
resource "aws_security_group" "tls_allow" {
name        = "tls_allow"
vpc_id      = "vpc-..."
ingress {
description      = "TLS traffic"
from_port        = 443
to_port          = 443
protocol         = "tcp"
cidr_blocks      = ["8.0.0.0/24"]
}
egress {
from_port        = 0
to_port          = 0
protocol         = "-1"
cidr_blocks      = ["0.0.0.0/0"]
}
tags = {
Name = "allow_tls"
}
}
```
... would fail with the following error:
```
2022-03-22T16:46:54.176+0100 [INFO]  provider.terraform-provider-aws_v3.75.0_x5: 2022/03/22 16:46:54 [DEBUG] [aws-sdk-go] DEBUG: Validate Response ec2/RevokeSecurityGroupEgress failed, attempt 0/25, error InvalidPermission.NotFound: The specified …
```
> Fix Terraform creation of EC2 Security Groups with default egress

- setup.cfg
Our test pipelines recently broke due to the following error:
```
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/test_apigateway.py:10: in <module>
from localstack.services.apigateway import apigateway_listener
localstack/services/apigateway/apigateway_listener.py:24: in <module>
from localstack.services.apigateway import helpers
localstack/services/apigateway/helpers.py:22: in <module>
from localstack.services.generic_proxy import RegionBackend
localstack/services/generic_proxy.py:48: in <module>
from localstack.utils.server import http2_server
localstack/utils/server/http2_server.py:16: in <module>
from quart import Quart
.venv/lib/python3.8/site-packages/quart/__init__.py:3: in <module> …
```
> fix broken transitive imports of quart from jinja

- localstack/utils/container_utils/docker_cmd_client.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/docker_utils/conftest.py
- tests/integration/test_cloudformation.py
- tests/integration/test_es.py
- tests/integration/test_firehose.py
- tests/integration/test_opensearch.py
- tests/unit/utils/test_net_utils.py
This PR adds the mark "skip_offline" to a set of tests which do need internet access when being executed.
In addition it fixes the check for the `CmdDockerClient` (which raises a `FileNotFoundError` if the binary is not available).
> skip "online-only" tests, fix some tests

- localstack/services/kms/provider.py
This pull request fixes the EC curves used for the NIST key specs to be in line with what you get from AWS.
For reference: [AWS docs on EC key specs](https://docs.aws.amazon.com/kms/latest/developerguide/symm-asymm-choose.html#key-spec-ecc)
The `ECC_SECG_P256K1` key spec uses the correct curve.
> KMS: Fix EC curves for NIST key spec

- localstack/services/sns/sns_listener.py
- tests/integration/test_sns.py
This PR addresses issue #5746. Seems to be that depending on the type of message publication, the SNS client sends the MessageGroupId as a string or a List of strings. 
Changes:
- Code addition that considers the different format.
- Test extension.
> Fix MessageGroupId for publish batch to SQS fifo queue

- localstack/utils/collections.py
Example: len(list) = 2, pagesize = 1
First run: start_index = 0, nextToken = token_generator( list[ start_index + pagesize = 0 + 1])
Second run: start_index = 1, nextToken = token_generator( list[ start_index + pagesize = 1 + 1]) -> list[2], -> out of bounds
> fix off-by-one error for nextToken generation

- .circleci/config.yml
Temporarily disable failing Lambda tests related to 204 response encoding. Putting this in as a quick fix to unblock `master` until we have final clarity on https://github.com/localstack/localstack/pull/5773
> Temporarily disable failing Lambda tests related to 204 response encoding

- .circleci/config.yml
- localstack/utils/server/http2_server.py
- setup.cfg
Avoid returning `Transfer-Encoding` headers for HTTP 204 responses. Should fix the currently failing build on `master`.
Currently seeing connection/protocol errors like below:
```
except (HTTPException, SocketError) as e:
>               raise ProtocolError("Connection broken: %r" % e, e)
E               urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
.venv/lib/python3.8/site-packages/urllib3/response.py:458: ProtocolError
```
The issue is that `Transfer-Encoding` is being returned from some of the Flask APIs (Lambda DELETE operations that return a 204 status), which newer versions of `urllib3` cannot handle.
Was doing a quick search across recent changes in …
> fix Transfer-Encoding "chunked" on empty responses

- localstack/services/awslambda/lambda_executors.py
This PR fixes a regression which happened with #5391 
removing the line which converts log outputs to string causes an error when concatenating in L662
> Reintroduce log output str casting

- Makefile
- setup.cfg
Skip installing -ext `runtime` dependencies in CI tests - attempt to fix broken build on `master`. 
We're currently running `make install-test` in the CI builds, and the `pip install -e ".[cli,runtime,test]"` command transitively pulls in the `runtime` extras from dependent packages, which we want to avoid. 
The particular reason why the builds are failing right now is because an upstream dependency has been added to the `runtime` extra which depends on `thriftpy2`, which in turn requires `gcc` to build the native extensions.
> Skip installing -ext runtime dependencies in CI tests

- localstack/services/s3/s3_listener.py
- tests/integration/serverless/serverless.yml
- tests/integration/test_s3.py
- tests/integration/test_serverless.py
This PR addresses issue #5748. Even thought I didn't found any official documentation, it's common knowledge that `LocationConstraint` should be `None` when is set to us-east-1. And the fix put in place to avoid return None, returns the requests region, instead of Null or the correct one.
Changes:
- Removing of **get-bucket-location** response fixing.
- Test to validate the correct responses in both cases: default and non-default
> LocationConstraint should be None for us-east-1

- localstack/services/providers.py
70958beb42bbf3d686dbf4453618618b6705879a swapped `local-kms` for `kms-local` as the expected `KMS_PROVIDER` environment variable value.
This commit puts that back.
Fixes #5792.
Hat tip to mathi in Slack for [noticing this](https://localstack-community.slack.com/archives/CLRFWBFC3/p1648835936348719).
> Fix `KMS_PROVIDER=kms-local` back to `local-kms`

- localstack/services/awslambda/lambda_utils.py
- localstack/services/cloudformation/deployment_utils.py
- localstack/services/cloudformation/models/apigateway.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/templates/apigateway_integration.json
- tests/unit/test_cloudformation.py
Minor fixes for data types handling in CloudFormation deployer - surfaced when working on changes for #5674
* fix request types for ApiGateway::UsagePlan parameters
* fix logic for using `!Sub` with numeric substitution values (ensure we return `str` for the regex replacer)
> Minor fixes for data types handling in CloudFormation deployer

- localstack/services/awslambda/lambda_api.py
- tests/integration/awslambda/test_lambda.py
This PR addresses issue #5762. It shows that Localstack completely deletes a function policy when the user tries to delete only one of its statements. 
Changes:
- Extension of the method **remove_permision** to fix issue.
- Test added.
> Deletion of individual statments of a function policy

- localstack/services/dynamodbstreams/dynamodbstreams_api.py
- localstack/services/dynamodbstreams/provider.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/testutil.py
- tests/integration/awslambda/functions/lambda_integration.py
- tests/integration/awslambda/functions/lambda_put_item.py
- tests/integration/awslambda/functions/lambda_send_message.py
- tests/integration/awslambda/functions/lambda_start_execution.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/awslambda/test_lambda_integration.py
- tests/integration/fixtures.py
- tests/integration/test_kinesis.py
Tests against Lambda should be able to run against AWS too, to prevent many false assertions.
This refactoring will do that, by fixing wrong assertions and adding permissions as well as retries.
This is a preparation work for better and more complete lambda tests.
> Rework Lambda Integration tests to work against AWS as well as LocalStack

- localstack/services/dynamodb/dynamodb_listener.py
- tests/integration/test_dynamodb.py
Fixes an issue where the following exception was being thrown for a valid query:
```
One or more parameter values were invalid: Select type ALL_ATTRIBUTES is not supported for 
global secondary index id-index because its projection type is not ALL
```
The exception is thrown if the table has additional global secondary indexes (besides the one being queried) that do not have a projection type of ALL.
> fix dynamodb index query validation

- tests/integration/secretsmanager/functions/lambda_rotate_secret.py
- tests/integration/test_dynamodb.py
This PR fixes two flaky tests:
* `test_rotate_secret_with_lambda_2` sporadically failed on a feature branch with message `Error executing Lambda function {"errorType": "NoRegionError", "errorMessage": "You must specify a region."`
* `test_dynamodb_stream_records_with_update_item`flaky on several branches: added a retry, as it seems like the second record might not be ready
> Fix flaky tests: test_dynamodb_stream_records_with_update_item, test_rotate_secret_with_lambda_2

- bin/localstack.bat
Fixed an issue with running localstack on Windows when the primary user name has a space in it.
I ran into this issue myself, and decided to fix it.
> Fixed issue with spaces in Windows user names

- localstack/aws/protocol/router.py
- tests/unit/aws/protocol/test_parser.py
With the introduction of the `RestServiceOperationRouter` in ASF (https://github.com/localstack/localstack/pull/5827), we introduced a small regression.
The operation detection did not work correctly anymore for mandatory query parameters - defined in the requestUri of the operation specification - without a value.
For example, the operation detection did not work for CloudFront's `CreateDistributionWithTags` (where it mistakenly detects `CreateDistribution`):
- CreateDistributionWithTags: `/2020-05-31/distribution?WithTags`
- CreateDistribution: `/2014-05-31/distribution`
This PR contains a fix which ensures that an empty query arg in the requestUri is still considered for the operation detection.
> fix ASF operation routing (empty query args, deprecated ops)

- localstack/services/cloudformation/models/s3.py
- tests/integration/cloudformation/test_cloudformation_s3.py
- tests/integration/templates/s3_versioned_bucket.yaml
Adds support for bucket versioning to the AWS::S3::Bucket CloudFormation model.
e.g.
```yaml
Resources:
Bucket83908E77:
Type: AWS::S3::Bucket
Properties:
VersioningConfiguration:
Status: Enabled
```
> add cloudformation support for s3 bucket versioning

- localstack/services/apigateway/apigateway_listener.py
- localstack/services/apigateway/context.py
This PR adds the authorizer object to the lambda event and encapsulates a new property into the invocation context to represent the authorization type (lambda, iam, jwt)
Fixes #5130
> adds authorizer object to lambda event

- Makefile
Add a few additional `awslocal` CLI commands for CI smoke tests. These tests are to assert that the service providers are basically functioning and available.
> Add additional awslocal commands for CI smoke tests

- localstack/services/dynamodb/provider.py
- tests/integration/test_dynamodb.py
The error was probably due to different access keys used across different requests.
Should fix #5843
> Fix ResourceNotFoundException for BatchGetItem operation

- localstack/services/dynamodb/provider.py
- tests/integration/test_dynamodb.py
This is a fix for https://github.com/localstack/localstack/issues/5831:
Recently, we added a fix for Global Secondary Index usage https://github.com/localstack/localstack/pull/5799, which would raise an Exception if the index is not found in the `GlobalSecondaryIndexes`.
However, the index might be in `LocalSecondaryIndexes`. For this we should not require an additional check for the projection type, as [it states in the docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#API_Query_RequestSyntax):
> If you query or scan a local secondary index and request only attributes that are projected into that index, the operation will read only the index and not the table. If any of the requested attributes are not projected into the local secondary index, DynamoDB …
> fix queries for local secondary index on dynamodb

- Dockerfile
Pretty self-explanatory, see bug #5821
> Fix #5821 - ElasticMQ always downloaded due to incorrect cache path in Dockerfile

- localstack/services/events/events_listener.py
- localstack/services/events/events_starter.py
- localstack/utils/aws/message_forwarding.py
- localstack/utils/http.py
- tests/integration/test_events.py
Continuation of issue #5229, where apparently I missed the integration of the HttpParameters of the Put Target request.
Changes:
- Fixing of Basic mode Auth header, now it is base64 encoded. 
- Correction of the Basic mode auth test, now the test only expects the correct way.
- The HttpParametes of the PutTarget request are now integrated
- The event to send is replaced for Input parameter if it is defined in the Put target request. As this doc [indicates](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutTargets.html).
- The test for api-destinations now considers the new changes.
> Target HttpParameters and Input support and basic auth fix for Events service

- localstack/utils/aws/message_forwarding.py
- tests/integration/test_events.py
This PR addresses #5729. Where the user reports an error on the extraction of the oauth credentials parameters for an API destination.
Changes:
- Fixing of the OauthHttpParameters values.
- Test extension to validate changes.
Note: The test extension change probably overlaps with the test correction of #5738 so one of the PR should be rebased after the other one is merged.
> fix extraction of oauth_http_parameters for api destinations

- localstack/services/secretsmanager/provider.py
- tests/integration/secretsmanager/test_secretsmanager.py
This resolves bug https://github.com/localstack/localstack/issues/5872
The issue was caused by localstack patching the constructor of motos FakeSecret class, but not passing along the positional arguments. The call to delete_secret then fails here:
https://github.com/spulec/moto/blob/master/moto/secretsmanager/models.py#L701
(See the stack-trace posted on the bug ticket for details)
> Return successfully when attempting to delete a non-existent secret

- localstack/services/cloudformation/models/dynamodb.py
- localstack/services/dynamodb/provider.py
- tests/integration/test_dynamodb.py
As reported in #4982, when a table is created with `PAY_PER_REQUEST` billing mode and a provisioned throughput is specified as well, we should return a `ValidationException`.
> Error message for PAY_PER_REQUEST billing mode

- localstack/services/install.py
Upgrade kinesis-mock to [0.2.4](https://github.com/etspaceman/kinesis-mock/releases/tag/0.2.4) to fix tag validation excluding characters
> Increment kinesis-mock version to 0.2.4 for validation fix

- localstack/services/install.py
- tests/integration/test_dynamodb.py
Apply DynamoDB patch to enable more than 20 Global Secondary Indexes (GSIs) on table creation - addresses #5672 . The patched class is maintained in the [localstack-artifacts repo](https://github.com/localstack/localstack-artifacts/tree/master/dynamodb-local-patch/com/amazonaws/services/dynamodbv2/local/shared/access/api/cp).
> Add DynamoDB patch to enable more than 20 GSIs on tables

- localstack/cli/localstack.py
- localstack/utils/bootstrap.py
- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
This PR changes the `localstack wait` and `localstack logs` command to use the docker logs stream instead of the logfile created by `localstack start`. This allows `wait` and `logs` to be used when localstack was started with docker or docker-compose manually. it also allows invocations like `MAIN_CONTAINER_NAME=my_localstack_container localstack wait` which were previously not possible.
To that end, we needed a way to stream docker logs (`docker logs --follow`). The `CancellableStream` is inspired by what the docker SDK client returns.
Example code: listen and print the log stream for 5 seconds then close the stream. This would look pretty much the same with the docker python SDK, just had to make it work for the `CmdDockerClient` (wrapping `Popen`)
```python
docker = SdkDockerClient() …
```
> update localstack wait command to use docker logs stream

- localstack/services/awslambda/lambda_utils.py
- tests/unit/services/awslambda/test_lambda_utils.py
Fixes for get_handler_file_from_name, fixing incorrectly returning '.js' from '.build/handler.execute' (Typescript).
Revisiting #1774 / #1775
Also appears related to both #5485 and #3969 with '.webpack/service/first.hello'
This appears to have either regressed or not been fixed, due to `handler_name.split(delimiter)[0]` will return '.js' from '.build/handler.execute' instead of '.build/handler.js'
Have added in a few tests to with my assumptions on how it's currently working.
Please do let me know if any of these assumptions are incorrect, or anything else for that matter and I'll update the PR.
Thanks,
Matt
> get_handler_file_from_name when path contains periods

- localstack/services/dynamodb/provider.py
- localstack/services/events/events_starter.py
- localstack/services/generic_proxy.py
- tests/conftest.py
- tests/integration/fixtures.py
- tests/integration/test_events.py
* support nested EventBridge patterns - addresses https://github.com/localstack/localstack/issues/5701
* start refactoring the integration tests, to reduce duplication - note: there is still an opportunity to do more unification, currently there are very similar tests duplicated for the different target types (SQS, SNS, Kinesis, EventBridge, ..)
* improve parity with AWS - two of the integration tests have already been executed and verified with `TEST_TARGET=AWS_CLOUD` - marked with `@pytest.mark.aws_validated`
* migrate tests to `pytest`
* Note: the change in the `events_starter.py`, in particular in `filter_event_based_on_event_format(..)` will affect the ASF migration in https://github.com/localstack/localstack/pull/5844 (will need to be migrated to that PR once merged). /cc @MEPalma
> Support nested EventBridge patterns, improve parity with AWS

- localstack/http/request.py
- localstack/services/moto.py
- tests/unit/aws/protocol/test_parser.py
- tests/unit/http/test_request.py
This PR reworks our HTTP Request object to better re-use werkzeug's Request object. Instead of replicating the methods and mocking out IO, we now create a fake `WSGIEnvironment`, which is what underlies a werkzeug Request. This way we can re-use all of werkzeug's request parsing methods (e.g., parsing form data).
What needs to be in the `WSGIEnvironment` dictionary was determined partly from [the wsgi docs](https://wsgi.readthedocs.io/en/latest/definitions.html#standard-environ-keys), partly from the [werkzeug code](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/wrappers/request.py), and partly from inspecting a flask request.
* Supersedes #5875
> rework localstack.http.Request object to use a dummy WSGi environment

- localstack/utils/scheduler.py
- tests/unit/utils/test_scheduler.py
This PR adds a scheduler utility that can be used to schedule tasks in an event-loop based manner, potentially without threads, which can be helpful to implement things like alarm evaluations in cloudwatch.
> add task scheduler utility

- localstack/utils/aws/aws_stack.py
- tests/integration/test_s3.py
Minor refactoring in utils to create S3 buckets with location constraints. Buckets now need to be created with the correct region / location constraint (for parity with AWS). 
We can use the `create_s3_bucket(..)` util function to simplify this task and streamline creation of buckets across the codebase. Intended to be used in places where we need to create temporary buckets for other services, e.g., in the case of CloudFormation, to avoid these exceptions:
```
localstack_main |     s3_client.create_bucket(Bucket=CUSTOM_RESOURCES_RESULTS_BUCKET)                                                                                                                                                                          
localstack_main |   File …
```
> Refactor util to create S3 buckets with location constraints

- localstack/http/request.py
- tests/unit/aws/protocol/test_parser.py
- tests/unit/http/test_request.py
This adds the commits that sprung from the reviews of #5876 that didn't make it into the PR because I force pushed from my old history on my laptop :clown_face:
> add headers to dummy WSGI environment

- localstack/http/dispatcher.py
- localstack/services/infra.py
- localstack/services/internal.py
- localstack/utils/bootstrap.py
fixes #5906 
Currently, backdoor API to restart the process provided on `/health` endpoint does not work.
This patch fixes some errors to work correctly.
> Fix backdoor API provided on health endpoint

- setup.cfg
Minor: Bump version of awscli for compabilibity with poetry - should fix https://github.com/localstack/localstack/issues/5520
Was able to replicate locally. With the following `pyproject.toml` config:
```
[tool.poetry]
name = "test"
version = "0.1"
description = "test"
authors = []
[tool.poetry.dependencies]
python=">=3.7,<4.0"
```
... the following command installs the runtime dependencies successfully:
```
poetry add "localstack[runtime]"
```
> Minor: Bump version of awscli for compabilibity with poetry

- bin/docker-entrypoint.sh
fixes https://github.com/localstack/localstack/issues/5901
`/health` endpoint handler retrieve request data for PUT request from `request.data`.
https://github.com/localstack/localstack/blob/v0.14.2/localstack/services/internal.py#L63
To using `request.data`, the user must specify a content type correctly but the curl command that is executed in `docker-entrypoint.sh` to store feature states does not specify content type header so that `request.data` always becomes empty.
> specify content type header with curl PUT request in docker-entrypoint.sh

- localstack/utils/server/http2_server.py
- localstack/utils/server/proxy_server.py
- tests/unit/test_proxy.py
Minor fix to ensure that `/static/...` paths are properly served by the proxy. 
Turns out that the Quart HTTP server by default attempts to serve `/static` paths from the local filesystem (see `static_folder="static"` in the [Quart initializer](https://github.com/pgjones/quart/blob/638a8e02493441f6c15cf19266d1ae80a2d984d1/src/quart/app.py#L215)). This was causing 404 errors whenever we were requesting `/static/...` paths through the edge proxy (and other proxy listeners). In this PR we explicitly set `static_folder=None` to disable this behavior.
The PR also contains some minor changes to reduce log verbosity (removing `print` statements) which surfaced during testing.
Part of this may become obsolete with the new Gateway, still good to have it covered by a test for now. /cc @thrau
> Minor fix to ensure that /static/ paths are properly served by the proxy

- localstack/services/ses/provider.py
- tests/integration/test_ses.py
Presently Localstack only records the body of `Text` emails, and does not support `Html` emails.
In the [AWS SES v2 API spec](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html) HTML formatted emails are sent using this part of the message:
```json
{
"Content": { 
"Simple": { 
"Body": { 
"Html": { 
"Charset": "string",
"Data": "string"
},
... rest removed for brevity ....
```
This PR stores anything send in the `Html` part of the body into the JSON files stored in `/ses` in a field called `HtmlBody`.
> Add SES HTML body to match v2 API spec

- localstack/utils/strings.py
- tests/unit/test_common.py
Add small utility for base64 decoding which handles different edge cases:
* missing padding in input string
* ability to deal with [URL safe encoding](https://datatracker.ietf.org/doc/html/rfc4648#section-5) (using `-`/`_` instead of  `+`/`/`)
(Moving this here from an upstream repo, so it becomes more widely accessible to the codebase).
> Add small utility for base64 URL safe decoding

- localstack/services/dynamodb/provider.py
- tests/integration/test_dynamodb.py
`TableClass` was not managed for the CRUD operations in DynamoDB. This PR should fix #5916
> Handling TableClass in DynamoDB

- localstack/http/adapters.py
- localstack/http/request.py
- tests/integration/test_s3.py
- tests/unit/aws/protocol/test_parser.py
When creating a werkzeug `Request` object from the WSGI environment, werkzeug does the "WSGI decoding dance" [here](https://github.com/pallets/werkzeug/blob/c7ae2fea4fb229ffd71187c2b665874c91b96277/src/werkzeug/wrappers/request.py#L109-L114):
```python
root_path=_wsgi_decoding_dance(
environ.get("PATH_INFO") or "", self.charset, self.encoding_errors
),
```
where the `_wsgi_decoding_dance` method does this: `return s.encode("latin1").decode('utf-8', errors)`
meaning werkzeug expects the WSGI environment to contain `latin-1` encoded path. so 
* `'/my-testbucket/Ā_'` (quoted as `'/my-testbucket/%C4%80_'`) is expected to be `/my-testbucket/Ä\x80_`  in `environ['PATH_INFO']` so the path can be restored as such from the request. previously we would pass the utf-8 encoded path directly into …
> fix localstack.http.Request path encoding

- localstack/services/apigateway/integration.py
- localstack/services/awslambda/lambda_executors.py
- localstack/services/cloudformation/cloudformation_api.py
- localstack/services/edge.py
- localstack/services/events/scheduler.py
- localstack/services/generic_proxy.py
- localstack/services/plugins.py
- localstack/utils/aws/aws_models.py
- localstack/utils/aws/aws_responses.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/aws/request_context.py
- localstack/utils/aws/templating.py
- localstack/utils/cloudformation/template_deployer.py
- localstack/utils/cloudformation/template_preparer.py
- localstack/utils/container_utils/container_client.py
- localstack/utils/json.py
- localstack/utils/kinesis/kinesis_connector.py
- localstack/utils/objects.py
- localstack/utils/run.py
- localstack/utils/tagging.py
- tests/integration/awslambda/test_lambda_size_lims.py
Cleaning up a bit.
This PR removes explicit object inheritance. Not needed since we dropped Python 2 support quite a long time ago now.
> Remove explicit object inheritance

- .circleci/config.yml
- localstack/services/generic_proxy.py
- localstack/utils/net.py
- localstack/utils/server/http2_server.py
- localstack/utils/testutil.py
- tests/unit/utils/test_http2_server.py
As seen here (https://pgjones.gitlab.io/hypercorn/how_to_guides/binds.html#multiple-binds), hypercorn supports multiple binds for a single server.
Our current tooling, however, does not allow passing multiple bind_addresses.
This PR introduces the possibility to allow multiple addresses in start_proxy_server and in run_server, to be passed to hypercorn.
To minimize the impact, a single string will still be accepted in start_proxy_server (run_server does not seem to be called from anything but tests and this method), however we should move towards using lists to specify them.
This should help with different problems regarding ipv6 support in host mode (for starting in docker we need to modify the default values in docker-compose and localstack cli as well - separate PR).
It is necessary to …
> Allow multiple bind addresses to be passed to hypercorn

- localstack/services/cloudwatch/alarm_schedule_util.py
- localstack/services/cloudwatch/alarm_scheduler.py
- localstack/services/cloudwatch/provider.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/cloudwatch/cloudwatch_util.py
- tests/integration/test_cloudwatch.py
- tests/unit/test_cloudwatch.py
This PR refers to https://github.com/localstack/localstack/issues/5446 and implements basic cloudwatch metric-alarm evaluation:
supports metric-alarm with the following characteristics:
- "Statistic": Maximum, SampleCount, Sum, Minimum, Average
- "ComparisonOperator": GreaterThanOrEqualToThreshold, GreaterThanThreshold, LessThanThreshold, LessThanOrEqualToThreshold
- "[Alarm|OK|InsufficentData]Actions": SNS Topic
Note: in order to correctly filter for Dimensions, [this PR in Moto](https://github.com/spulec/moto/pull/5041) is required.
> add metric-alarm evaluation to Cloudwatch

- localstack/aws/protocol/op_router.py
- tests/unit/aws/protocol/test_op_router.py
- tests/unit/aws/protocol/test_parser.py
This PR fixes the `RestServiceOperationRouter` for operations which contain request URI path params with dashes (`-`).
The issue has been described in #5944.
I cherry-picked the tests from #5945 (in order to have @thrau as a reviewer - which wouldn't be possible when continuing on the existing PR).
This fix introduces a temporary replacement of forbidden characters with a substitution, as well as the reverse operation after the matching has been done. This is necessary since - after a match has been found - the parser assumes the arg keys to be equal to the path params in the request URI of the specs.
I did not introduce a state machine as suggested in https://github.com/localstack/localstack/issues/5944#issuecomment-1111450334, since the regex replacement function seems quite elegant. It …
> fix invalid characters in asf rest-protocol operation router

- localstack/services/internal.py
- tests/unit/services/test_internal.py
Minor fix: Return `text/html` Content-Type for local CloudFormation UI (http://localhost:4566/_localstack/cloudformation/deploy), to ensure it gets properly rendered by browsers.
> [minor] Fix text/html Content-Type for local CloudFormation UI

- setup.cfg
A new bugfix release of Werkzeug has just been released: https://github.com/pallets/werkzeug/releases/tag/2.1.2
It fixes the issue with the Transfer-Encoding ([pallets/werkzeug#2375](https://github.com/pallets/werkzeug/issues/2375)) introduced with 2.1.0, which led us to set an upper version boundary to the Werkzeug dependency (#5773).
The new release contains a fix for the issue, which allows us to remove the upper version boundary.
> remove Werkzeug pin after bugfix release

- localstack/aws/protocol/parser.py
- tests/unit/aws/protocol/test_parser.py
This fixes an issue where invoking `awslocal s3 ls` would incorrectly create an s3 `ListObjects` command with the bucket name `localhost:4566` (instead of `ListBuckets`) and subsequently setting the `path` of the request object to `/localhost:4566`.
> extend s3 virtual host addressing rules exemptions

- localstack/http/request.py
- tests/unit/http/test_request.py
This PR fixes two issues:
* `get_raw_path` would return different results depending on whether it is a WSGI or an ASGI request. This would lead to inconsistent behavior and rules not matching when using the asgi->wsgi bridge here:
https://github.com/localstack/localstack/blob/01cb58478ee3a2329b86b0d88fbb12695ce1c3a6/localstack/aws/protocol/op_router.py#L252-L253
* the dummy WSGI environment now correctly adds the query string to the `RAW_URI` environment (which seems redundant since we're removing it in `get_raw_path` now, but this is to conform to the spec.
Here's what the relevant parts of the underlying environ/scope look like for "GET /foo/b r?bar=ze 69"
wsgi environ (via werkzeug)
```python
{
'PATH_INFO': '/foo/b r'
'QUERY_STRING': 'bar=ze%2069'
'REQUEST_URI': …
```
> fix get_raw_path to unify wsgi/asgi specs

- localstack/services/dynamodb/provider.py
- tests/integration/test_dynamodb.py
Ensure that `eventID` is contained in DynamoDB stream records - addresses #5957 , fixes a regression that was likely introduced in the DynamoDB ASF migration in #5796
> Ensure eventID is contained in DDB stream records

- localstack/services/firehose/provider.py
- tests/integration/test_integration.py
This PR addresses #5936 where is shown that Localstack crashes when trying to store a record in a Firehose stream that is using ExtendedS3DestinationConfiguration.
Changes:
- Small change to avoid the crashing.
- Test added.
Note: The test added is exactly the same as the one for the standard S3 configuration, but it could be used in test the other advance parameters when Localstack supports them.
> Fix Firehose.PutRecord to extended s3

- localstack/services/sqs/sqs_listener.py
This PR addresses issue #5888 where the user asks for a Warning log when creating a FIFO Queue without sending the correct attribute.
> Feature log for fifo queue creating

- localstack/aws/protocol/op_router.py
- tests/integration/fixtures.py
- tests/integration/test_s3.py
- tests/unit/aws/protocol/test_op_router.py
- tests/unit/aws/protocol/test_parser.py
This PR changes the way path rules of requestUri patterns, e.g., `{Key+}`, are matched. It adds tests for the behavior at multiple levels.
Background: S3 keys can contain slashes, which are encoded in the path, and the slashes should be matched by the path rule.
/test-bucket-5a51ca7e//foo/bar
-------------------^ -------^
bucket                key
The default `path` rule regex is `[^/].*?`, I changed that to `.*?`, so it matches slashes as well.
This will work even when matching paths where there is a static suffix. For example, these rules exist and will work:
* workspaces-web GetTrustStoreCertificate: `/trustStores/{trustStoreArn+}/certificate`
Moreover, when the routing Map has `merge_slashes=True` set, werkzeug detects multiple consecutive slashes and then attempts to redirect. So we …
> fix op router when matching keys with slashes

- localstack/cli/localstack.py
- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- setup.cfg
This PR adds a `localstack update` command, which provides a convenient way to update LocalStack components.
`localstack update all`: Updates all components, in essence execute all the commands below
`localstack update localstack-cli`: Update the LocalStack cli packages, in essence `localstack` and `localstack-ext`.
`localstack update docker-images`: Update all LocalStack-used container images (main image, lambda images, bigdata)
We look at the images by prefix. So basically, all images currently available to the daemon will be listed, then filtered by prefix (currently `localstack/`, `lambci/lambda:`, `mlupin/docker-lambda:`), and afterwards we will try pulling each image, and checking if it has updated to be displayed on the UI side.
This means, no image will be pulled if it is not …
> Add localstack update command

- localstack/services/cloudformation/provider.py
Hotfix for a regression that prevented AWS CDK from bootstrapping since the DescribeStacks response couldn't be parsed successfully.
Fixes https://github.com/localstack/aws-cdk-local/issues/68
> Fix ValidationError for CloudFormation.DescribeStacks

- localstack/services/secretsmanager/provider.py
- tests/integration/secretsmanager/test_secretsmanager.py
This PR fixes an issue where the ASF gateway would not serialize boto exceptions correctly, because it doesn't know about moto exceptions. Because the tests were using the custom `sm_client` fixture, and i was too lazy to refactor the tests, i simply wrapped the fixture with our `secretsmanager_client` to run the affected test against AWS.
> fix secretsmanager to use ASF instead of moto exceptions

- localstack/aws/protocol/op_router.py
- tests/unit/aws/protocol/test_op_router.py
- tests/unit/aws/protocol/test_parser.py
This PR fixes the HTTP HEAD method detection in the ASF operation router for service with a `rest-*` protocol.
A new inheritance layer has been introduced (`_StrictMethodRule`) which reverts assumptions made by Werkzeug's rule, specifically the automatic adding of `HEAD` to the list of methods if the `methods` param contains `GET` ([werkzeug/routing.py#L723-L724](https://github.com/pallets/werkzeug/blob/bb21bf90b0b121e3ed45b9950b823e4b43a81fd8/src/werkzeug/routing.py#L723-L724)).
> fix HTTP HEAD method operation detection in ASF

- .circleci/config.yml
- .github/workflows/pro-integration.yml
- Dockerfile
- setup.cfg
This PR makes couple of significant changes to the build pipeline in order to fully support python3.10 features over the build pipeline:
* Usage of machine executors throughout the pipeline: In contrast to the current state, we now use machine executors for all steps of the pipeline, instead of just the steps needing docker. This is necessary due to the passing of the virtual environment from the install steps to later steps, and the difference in pathing between machine (using pyenv) and docker (installing in /usr/bin) images. Alternative would have been rebuilding the venv every time or trying to fix the venv paths for every job, which just begs for errors to occur.
* Update of machine images: In order to use python 3.10.3 throughout the pipeline (and 3.10.4 in the docker image), I …
> Upgrade python version to 3.10

- localstack/aws/protocol/op_router.py
- tests/unit/aws/protocol/test_op_router.py
This PR disables strict slash matching (ignore trailing slashes) for the operation router.
I'm 96% confident this change is safe ;-)
I also added the host to the matcher since it helps with debugging when getting redirect errors.
It then prints: `werkzeug.routing.RequestRedirect: 308 Permanent Redirect: http://127.0.0.1/2015-03-31/functions/`
I ran into the problem when debugging this test: https://github.com/localstack/localstack/blob/abbb7a8866ca3cafb0b3ca2f60ca26acebad3b44/tests/integration/test_edge.py#L290-L301
The test is calling `GET /2015-03-31/functions`, which would not match the `ListFunctions` rule in botocore, whose requestUri is [`/2015-03-31/functions/`](https://github.com/boto/botocore/blob/801faeec62d325a337bd5b39cce8d2c189774e12/botocore/data/lambda/2015-03-31/service-2.j …
> disable strict slashes for ASF REST operation router

- localstack/http/__init__.py
- localstack/http/asgi.py
- localstack/http/dispatcher.py
- localstack/http/hypercorn.py
- tests/unit/http/test_asgi.py
- tests/unit/http/test_request.py
This PR adds an ASGI to WSGI bridge to serve WSGI applications through ASGI servers like Hypercorn. This serves as a basis for #5243 that is built around werkzeug's `Request` object which wraps and underlying `WSGIEnvironment`. This gives us all the benefits of the ASGI HTTP/2 server, while also maximally re-using Werkzeug's synchronous server code.
Here's an example server highlighting the integration:
```python
import werkzeug
import hypercorn
from localstack.http.asgi import ASGIAdapter
from localstack.http.hypercorn import HypercornServer
@werkzeug.Request.application
def wsgi_app(request: werkzeug.Request) -> werkzeug.Response:
return werkzeug.Response("ok", 200)
def main():
config = hypercorn.Config()
config.bind = "localhost:4566"
asgi_app = ASGIAdapter(wsgi_app)
server = …
```
> add ASGI to WSGI bridge and hypercorn server abstraction

- localstack/utils/patch.py
- tests/unit/test_cloudwatch.py
This fixes a regression that I introduced (sorry!) with the patch utility. The `Patch.function` expects the method signatures by default to take as first argument the method that is patched. The method signature of `mock_metric_alarm_details`, etc, were not updated correctly. The `alarm_scheduler.calculate_alarm_state("helloworld")` call would then raise a TypeError, which i was only able to uncover by wrapping a try/except block:
No idea where the exception is lost, but potentially worth looking into at some point.
> fix test_cloudwatch.py mock patches

- bin/docker-entrypoint.sh
- localstack/utils/bootstrap.py
Currently, passing signals from the LS docker container init process (= docker-entrypoint.sh) to supervisord (which will in turn pass it to the LocalStack process itself), is disabled per default, unless you set `SET_TERM_HANDLER=1`.
This results in long shutdown times for docker-compose, as well as leftover containers started by LS (like lambda containers etc.), since docker-compose will kill containers after 10s if they do not end themselves in that timeframe.
This behavior is not seen in LS CLI, since we set the term handler variable explicitely there.
This PR inverts this behavior, signal handling is enabled per default, unless `DISABLE_TERM_HANDLER=1` is set, for users who, for any reason, would like to use the "old" behavior.
The `SET_TERM_HANDLER` variable setting in CLI is still …
> Enable signal handlers per default for LocalStack inside a docker container

- localstack/services/apigateway/integration.py
- localstack/utils/aws/templating.py
- tests/unit/test_templating.py
* Add support for `#return` macros in VTL templates - addresses #5988 . This requires a patch in `airspeed`, which over time we should contribute upstream.
* Clean up and unify templating code. A large portion of of the PR is actually just moving things around, cleaning up duplicate code, etc. The key change is to separate a (somewhat) generic `VtlTemplate` (which can also be used by AppSync and other services), and a derived `ApiGatewayVtlTemplate` which adds extensions that are relevant in an API GW context. Was taking care of backwards compatibility, and should be reasonably well covered by tests.
> Add support for #return macros in VTL templates

- tests/integration/fixtures.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3_notifications_lambda.py
- tests/integration/s3/test_s3_notifications_sns.py
- tests/integration/s3/test_s3_notifications_sqs.py
- tests/integration/test_s3.py
This PR is an initial effort to refactor the s3 tests.
Rough rundown of changes:
* move s3 tests into separate package (`tests/integration/s3`)
* separate tests that have integrations with other services (in this PR: s3 notifications), may be interesting for the case @viren-nadkarni ran in to related to s3->eventbridge notifications
* completely revamped the notification tests using polling mechanisms (to make them work against AWS)
* use pytest and factory fixture pattern correctly
* -> allowed me to run all refactored tests against AWS (except the lambda notification test, i was too lazy to create the policies ;-))
* removed a few redundant tests
I did not refactor all of them, it was just too much work for one pass. But I hope this can give a template for how to proceed.
> refactor initial set of s3 tests

- localstack/http/asgi.py
- tests/unit/http/test_asgi.py
- tests/unit/http/test_request.py
This PR fixes an encoding issue that arises from ASGI using normal utf-8 encoding for paths, whereas werkzeug expects latin-1 encoded paths.
This was already implemented for the `dummy_wsgi_environment`, but not for the wsgi/asgi bridge. Added tests for both cases.
> fix http path encoding in asgi/wsgi adapter

- .circleci/config.yml
- Makefile
- pyproject.toml
This PR sets the default loglevel of pytest to debug, meaning that logs will automatically be output to the CLI. The consequence is that, when running `DEBUG=1 make test`, you will automatically get logs in your terminal.
> configure pytest to log DEBUG to cli by default

- localstack/utils/collections.py
- tests/unit/utils/test_collections.py
Added a small utility to filter dictionary based on the keys declared in a given `TypedDict`. 
This could come in handy for many providers when we explicitly lists the needed attribute and was asked by @MEPalma to facilitate the writing of some tests.
> Added utility to filter a dictionary based on a TypedDict keys

- .github/workflows/chart-release.yaml
- .github/workflows/rh-support.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- .github/workflows/cla.yml
The new CLA assistant's allowlist does not work for the RenovateBot PRs (as you can see in https://github.com/localstack/localstack/pull/6029).
This PR changes the allowlist entry from "renovate" to "renovate-bot" (which is the GitHub username used for the commit - https://github.com/localstack/localstack/pull/6029/commits/ec615f88106c3628f5881715aa1ee5f041480d7d).
> fix CLA assistant allowlist

- localstack/aws/protocol/op_router.py
- localstack/aws/protocol/parser.py
- tests/unit/aws/protocol/test_parser.py
This PR fixes an issue where S3 virtual host addressing would not work correctly, because werkzeug caches properties (like various variants of the URL and path) based on the `path` attribute. Simply setting it doesn't work reliably, we also have to delete the related cached properties. This is an unfortunate limitation of #5876.
For now I see this a workaround. Moving forward we need to answer the question whether we really want incoming requests to be mutable.
> add workaround for s3 virtual host addressing

- localstack/aws/protocol/parser.py
- tests/integration/s3/test_s3.py
- tests/unit/aws/protocol/test_parser.py
This PR fixes an issue where the parser would raise ProtocolErrors when receiving GET requests with a body. This was uncovered while running S3 tests that send GET bodies that are by default ignored by AWS (I verified it against AWS).
Basically we try body parsing, but if fails and it is a `GET` or `HEAD` request, we ignore the error. I also introduced a flag to control it so we can disable it for rest-json and enable it for rest-xml (which seems to be the behavior in AWS), or specific service protocols should we come across different behavior.
Whether sending a body with a GET request is allowed in HTTP is debated here: https://stackoverflow.com/a/983458/804840. TL;DR, the spec says
> the message-body SHOULD be ignored when handling the request.
AWS does things differently of course.
AWS …
> ignore GET and HEAD request body for rest-xml protocol

- localstack/services/plugins.py
This comes in handy when trying to access the `PersistenceLifeCycle` while iterating over the active provider for Cloud Pods.
> Explicit persistence hook argument for a Service

- pyproject.toml
- tests/integration/conftest.py
Currently, in test runs, after pytest exits an error message will show, namely `RuntimeError: cannot schedule new futures after interpreter shutdown`. This is due to the main thread of pytest exiting without waiting for LocalStack to finish, and LocalStack needing new futures for shutdown.
We now wait (for 10 seconds) for LocalStack to terminate correctly. If it does, no error will be shown. If it takes longer, we will print an error message (regarding LocalStack not yet shut down), and exit nevertheless. The tests will still be a success and exit code of pytest will still be 0 in this case (to minimize flaky test runs due to this change).
I introduced timestamps for logging in tests, to debug performance issues, hung threads etc better.
> Fix shutdown error in pytest by waiting for LS to finish correctly

- localstack/services/apigateway/integration.py
- localstack/utils/aws/templating.py
- tests/unit/test_apigateway.py
- tests/unit/test_templating.py
Small enhancements for Velocity rendering, continuation of fixes for #5988 :
* add proper support for map functions `put`/`putAll`
* add `quiet`/`qr` util function to suppress output from function results
* minor refactoring, pulling out `VelocityUtil` base functionality into common base class
> Add map, quiet return functions for VTL template rendering

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/integration.py
- localstack/services/apigateway/invocations.py
- tests/integration/files/swagger.json
- tests/integration/test_apigateway.py
- tests/integration/test_apigateway_api.py
This PR adds support for authorisers included in the OpenAPI specification. The method needs to be refactored further into a class that handles different versions of the spec and makes it easy to add new functionality not supported in the current implementation.
> Apigateway OpenAPI import support for authorizers

- localstack/services/awslambda/lambda_api.py
Fixes https://github.com/localstack/localstack/issues/6022
The lambda failed to source `stageVariables` from the event because it was being suppressed by the event construction.
> don't suppress stage variables from lambda event

- localstack/services/apigateway/helpers.py
- tests/integration/test_apigateway.py
- tests/unit/templates/openapi.swagger.json
This PR assures that the same authoriser used in the API is not created multiple times.
> fix multiple authorizer creation

- .circleci/config.yml
- localstack/services/dynamodb/provider.py
- localstack/utils/aws/aws_stack.py
- tests/integration/test_error_injection.py
* Fix DynamoDB error injection - return proper `ProvisionedThroughputExceededException` error message to the client, instead of a 500 error. This was an oversight in the DynamoDB ASF migration. Addresses #6056
This change also enables us to remove the custom `forward_request(..)` logic in the DynamoDB listener.
* Refactor and re-enable the error injection tests - they are now executed by default as part of the integration test suite. (disabling botocore retries ensures that the tests are executing fast)
* The PR also contains a tiny fix to avoid `AttributeError` in `describe_kinesis_streaming_destination(..)` - addresses #6031
> Fix DynamoDB error injection and re-enable tests

- localstack/services/edge.py
- localstack/services/generic_proxy.py
- localstack/services/infra.py
- localstack/utils/archives.py
- tests/integration/test_edge.py
- tests/unit/test_common.py
- tests/unit/test_proxy.py
Minor fixes for issues that surfaced during testing in local dev/host mode:
* When using the HTTPS forwarding server on port 443 (using `EDGE_FORWARD_URL`), we need to forward the requests using the raw path of the HTTP request (otherwise request parsing fails downstream, e.g., for URL-encoded ARNs passed in request paths). Issue can be replicated, e.g., with this command (after starting LS in Pro host mode): `awslocal kafka --endpoint-url https://localhost.localstack.cloud get-bootstrap-brokers --cluster-arn arn:aws:kafka:us-east-1:000000000000:cluster/test`. The existing `get_raw_path(..)` http utility comes in handy here. Added a small test for it as well. 
* Prefer using the native `unzip` command (if available) over the built-in Python ` zipfile` utils. Some versions of Node.js / …
> Minor fixes in edge forwarder and zip utils for dev/host mode

- localstack/http/request.py
- localstack/services/edge.py
- localstack/services/generic_proxy.py
- tests/conftest.py
- tests/integration/conftest.py
- tests/integration/test_edge.py
This PR fixes an issue initially addressed with https://github.com/localstack/localstack/pull/6059 (which was later closed in favor of https://github.com/localstack/localstack/pull/6065).
Unfortunately, https://github.com/localstack/localstack/pull/6065 does not fix the issue described in https://github.com/localstack/localstack/pull/6059.
- It changes the path and query parameter handling for the handler chain such that the generic proxy uses the url-encoded path and query parameters within its proxy handler chain.
- It partly reverts https://github.com/localstack/localstack/pull/6065, since the proxy listener gets the encoded path and query parts now. /cc @whummer 
- Fixes a small issue with the pytest plugin config (moves pytest plugins to the …
> fix request encoding in generic proxy listener chain and forwarding

- localstack/services/apigateway/patches.py
- localstack/services/apigateway/provider.py
- localstack/utils/strings.py
- tests/integration/test_apigateway.py
Small PR to move the `import_rest_api` operation to the ASF handler. Doing that, we can remove our internal monkey patching.
> move import_rest_api patch into ASF handler

- localstack/services/ses/provider.py
- tests/integration/test_ses.py
Localstack has a feature which saves all SES email to memory and filesystem for later inspection. This PR unifies the format for these email and makes it consistent with LocalStack Pro.
> Unify SES logging format

- localstack/services/cloudformation/models/iam.py
Minor fix for CFn deletion of `IAM::Role` resources.
Should fix the following issue that can happen on stack teardown:
```
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 880, in execute_resource_action
result = func["function"](resource_id, resources, resource_type, func, stack_name)
File "/opt/code/localstack/localstack/services/cloudformation/models/iam.py", line 279, in _pre_delete
for policy in iam_client.list_attached_role_policies(RoleName=role_name).get(
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 508, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 911, in _make_api_call
raise …
```
> Minor fix for CFn deletion of IAM::Role resources

- localstack/services/dynamodb/provider.py
- localstack/services/generic_proxy.py
- tests/unit/conftest.py
- tests/unit/test_generic_proxy.py
- Adjusts the `ArnPartitionRewriteListener` such that it updates potential `Content-Length` and CRC checksum headers.
- Slightly adjusts the DynamoDB ARN rewriting such that it is partition-agnostic.
- Hardens the `ArnPartitionRewriteListener` unit test such that it explicitly sets the default region to `None` (which otherwise could cause issues if the test is executed in an environment where the default region is set).
> fix ARN rewriting for DynamoDB ASF provider

- localstack/services/generic_proxy.py
- localstack/utils/aws/aws_stack.py
- tests/unit/test_generic_proxy.py
- Fix the ARN partition rewriting for incoming requests (https://github.com/localstack/localstack/pull/6075 excluded the incoming internal requests from being rewritten - which cased a regression).
- Cleanup of `lambda_function_or_layer_arn` and making it partition-agnostic.
> fix ARN rewriting for incoming requests, fix lambda arn creation

- tests/integration/test_sqs.py
Previously the pro tests would raise an error here because it would not be using the correct port.
```
>       assert queue_url == f"{host}/{account_id}/{queue_name}"
E       AssertionError: assert 'http://local...ueue-aa52fd71' == 'http://local...ueue-aa52fd71'
E         - http://localhost:443/000000000000/test-queue-aa52fd71
E         ?                   ^^
E         + http://localhost:4566/000000000000/test-queue-aa52fd71
E         ?                   ^^^
```
> fix test_get_queue_url_contains_request_host for pro integration

- localstack/utils/collections.py
- localstack/utils/container_networking.py
- localstack/utils/container_utils/container_client.py
Types not available in python3.7 without typing_extensions: TypedDict, Protocol
These types will now be imported depending on the current runtime version, either from typing or typing extensions (as done in other places in the code).
Also, lru_cache takes a userfunction as argument since 3.8, so for 3.7 compatibility we need to call it as function for the default parameters to work.
Fixes #6083
> Fix CLI usage with python 3.7

- localstack/services/cloudformation/provider.py
- localstack/testing/pytest/fixtures.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/cloudformation/test_cloudformation_changesets.py
- tests/integration/cloudformation/test_cloudformation_stacks.py
Currently, cloudformation does not respect already created resources when creating new changesets.
It will however fail on executing these changesets when there are no updates necessary.
Like AWS, the correct way to handle this is setting the correct status after creating a changeset, setting it to FAILED when there are no updates available.
Also, execution of these failed changesets should be prevented if the changeset is in a failed state.
> Handle Cloudformations empty stack updates by changing the changeset status

- localstack/aws/protocol/serializer.py
- localstack/aws/scaffold.py
- localstack/http/adapters.py
- localstack/utils/aws/aws_responses.py
- tests/unit/aws/protocol/test_serializer.py
- tests/unit/aws/test_scaffold.py
This PR adds initial support for event streaming to the ASF scaffold (for the generated APIs) as well as the serializer based on the HTTP1.1 feature of chunked `Transfer-Encoding`.
The scaffold generates `TypedDicts` with the event member of type `Iterator[<MemberShape>]`.
The serializer in turn serializes these events such that a generator is returned in the serialized `Response`.
This allows fully-typed service implementations for the streaming responses where all the encoding is done transparently in the serializer. Here's a dummy implementation of Kinesis' SubscribeToShard operation using the features introduced in this PR:
```
class KinesisProvider(KinesisApi):
def subscribe_to_shard(
self,
context: RequestContext,
consumer_arn: ConsumerARN,
shard_id: ShardId,
starting_position: …
```
> add initial support for streaming in ASF scaffold and serializer

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
- tests/unit/aws/protocol/test_serializer.py
This PR properly implements the `MessageAttributeNames` and `MessageAttributes` filter for the `ReceiveMessage` operation. The behavior is described here: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Client.receive_message
* moved the filtering of both user message attributes and system message attributes into their own functions
* added snapshot tests for both for different cases
* extended the serializer test (i initially thought it was a serializer error, but our implementation just wasn't correct)
should potentially fix #5248
> fix message attribute filter for SQS ReceiveMessage

- localstack/aws/protocol/parser.py
- localstack/aws/protocol/serializer.py
- localstack/aws/protocol/service_router.py
- localstack/http/response.py
- localstack/services/edge.py
- localstack/services/sqs/query_api.py
- localstack/utils/aws/aws_stack.py
- tests/integration/test_security.py
- tests/integration/test_sqs.py
- tests/unit/aws/protocol/test_parser.py
- tests/unit/aws/protocol/test_parser_validate.py
- tests/unit/aws/protocol/test_serializer.py
This PR contains the following changes (each encapsulated in a different commit):
- https://github.com/localstack/localstack/commit/c5ae9212613f849713588ca0d80befdbecc3955d Removes the warning in the ASF service router in case no service could be detected (the warning caused lots of false-positives)
- https://github.com/localstack/localstack/commit/75ecc7d7c934bf269b28a8b0b6caa829d7a3fde8 Moves the service-router import to the top-level imports (as discussed in https://github.com/localstack/localstack/pull/5734#discussion_r859524921 /cc @whummer)
- https://github.com/localstack/localstack/commit/f430c5314bf2e4e5b1dde2831bf87bffa96f0564 Adjusts the parser and serializer to use the features of Werkzeug's request class.
- https://github.com/localstack/localstack/commit/ccff61db809bbfa3458bc93 …
> ASF protocol cleanup / small enhancements

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
This PR fixes #5293 by raising the correct error messages when using an SQS receipt handle to either delete a message, or change the visibility of a message.
AWS raises `InvalidParameterValue` if a receipt handle is used that was previously issued but is no longer valid for the given queue. Previously we were raising `ReceiptHandleIsInvalid` which seems to happen only when receipt handles have a value that is not a real receipt handle. This seems to indicate some kind of internal format that receipt handles have. Since they seem to be base64 encoded values of some sort.
We now encode the queue ARN into the receipt handle (as well as some randomness to make it look like a random base64 encoded string), and base64 encode that. That allows us to later check whether a) the receipt handle is a …
> improve SQS receipt handle error parity

- localstack/services/events/provider.py
- tests/integration/test_events.py
This PR addresses issue #5943 where is shown that Localstack doesn't validate the name parameter when creating a new Connection for the Events service, which could lead to several problems. 
Changes:
-  Validation for the Name parameter and the AuthorizationType.
- Test addition.
> Validations for Events.CreateConnection

- localstack/services/dynamodb/server.py
DynamoDBLocal can start in [two different modes](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html). If a `dbPath` is set, DynamoDB writes its database files in that directory.
If not, it runs in `inMemory`mode with a transient state (which is what we currently do if persistence is not enabled).
Before, we were interested in having files on disk only when `DATA_DIR` was set. However, now that Pods are independent from persistence, we have a similar need. Therefore, we would just set a temporary directory to dump the database files.
As a future optimization we can investigate whether is possible to run start DynamoDBLocal `inMemory` and only ask for its content on the fly.
@whummer this is basically what we briefly discussed before. Could there …
> Slight refactoring to allow customizing DynamoDB server startup

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
This PR fixes #6107
We did not correctly pass the message parameters relevant for fifo queues down to the dead letter queue (which also has to be a FIFO queue when the original queue is a FIFO queue)
> fix SQS dead letter queue delivery for fifo queues

- localstack/services/sqs/provider.py
- localstack/services/sqs/query_api.py
- tests/integration/test_sqs.py
This PR fixes an issue in the ReceiveMessage long-polling behavior. Previously we would potentially wait several cycles of `WaitTimeSeconds` when it was specified together with `MaxNumberOfMessages`, and `MaxNumberOfMessages > qsize`. This lead to pretty severe slowdowns of message receiving when these values were set together.
We now only wait (correctly) at most one get-cycle, and then turn the blocking behavior off.
Moreover, we now respect the queue's default `ReceiveMessageWaitTimeSeconds` attribute value.
Issues that are potentially fixed:
* #5824
* #6093 
* #5178
> fix SQS ReceiveMessage blocking behavior when MaxNumberOfMessages is set

- localstack/services/apigateway/provider.py
Fixes a bug I've been facing when trying to deploy API Gateways with Schema validation in Localstack with Serverless-Localstack
Serverles used with:
plugins:
- serverless-offline
- serverless-localstack
> Typo API Gateway Provider validateRequestPparameters

- localstack/services/generic_proxy.py
This PR aims to fix blocking of the whole event loop for the lookahead for the SSL duplex socket.
Currently, the method is_ssl_socket will block until the first 5 bytes can be read - if the client does not provide these bytes, the eventloop will block and refuse any connections for the time being.
This PR fixes this by executing the method in an executor, and waiting for the result in the eventloop, therefore keeping it responsive.
Thanks @thrau for the tip!
Should fix #5499 .
> Use asyncio run_in_executor to prevent is_ssl_socket check from blocking

- localstack/services/sqs/provider.py
- localstack/services/sqs/query_api.py
- tests/integration/test_sqs.py
This PR fixes three issues in the query API
* for endpoint strategy `path`, the queue URLs were not generated correctly, they did not have the `http://` prefix
* for endpoint strategy `domain`, the routing did not work because the host matching regex was matching a different scheme i had tried (`sqs.<region>.localhost...`), not the one we then implemented (`(<region>.)queue.localhost....`)
*  i reverted my decision from here https://github.com/localstack/localstack/issues/6102#issuecomment-1133909611 and added the old behavior which was breaking other people's code.
Should fix:
- #6132
> fix sqs query-api endpoint strategy routing

- localstack/services/iam/provider.py
- localstack/utils/cloudformation/template_preparer.py
- tests/integration/cloudformation/test_cloudformation_sam.py
- tests/integration/templates/sam_function-policies.yaml
Fixes the initial problem encountered in #6143 which turned out to be a bit of a rabbit hole.
The SAM translator now properly loads a map of all managed policies (Name => ARN) since cloudformation expects full policy ARNs while SAM allows specifying only the policy name. I've introduced a SAM template & a corresponding test to validate this.
@whummer Note this also reverts the changes introduced in cedc908e7cd1d13037c8d09c098ee09d0f348c5c since they were breaking parity with AWS (e.g. in `iam_client.list_policies` calls that would always return `aws-us-gov` ARNs besides regular ones which broke loading policies via the samtranslator). There were no tests introduced in the linked commit so I'm not sure if this is breaking something. Technically the partition rewriter should take care of …
> Fix references to AWS managed policies in SAM templates

- localstack/aws/forwarder.py
- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
Fixes #6146 (simply does a rounding the timestamp before adding it as string to the attributes that are returned)
also sneakily added a change to `localstack.aws.forwarder` to avoid nested (and unnecessary) exceptions stack traces. /cc @whummer
> fix SQS ApproximateFirstReceiveTimestamp type

- localstack/services/cloudformation/models/apigateway.py
- tests/integration/cloudformation/test_cloudformation_apigateway.py
- tests/integration/templates/apigw-awsintegration-request-parameters.yaml
This PR addresses issue #5926. Where is shown that when deploying a CFN template with a APIGW.DomainName that uses Tags, Localstack Crashes.
Changes: 
- CFN APIGW.DomainName model correction.
- Test refactorization.
- The template file now uses parameters and uses tags.
> Fix cfn apigw domain tags

- localstack/utils/aws/message_forwarding.py
- tests/integration/test_events.py
This PR addresses issue #5878, where is shown that the Connection query parameters and header parameters have a higher priority than the Target query and header parameters.
Changes:
- Fixing of error.
- Test extended and refactored.
> Fix event message parameters priority

- localstack/services/dynamodb/server.py
- localstack/services/plugins.py
Minor changes to the abstraction used to retrieve the state of a service.
Mainly renaming and variable keyword arguments to give us some rooms to support different level-of-depth of persistence.
This abstract class will be implemented by `BackendStateLifecycleBase` that handles services that use `BackendDict` and `RegionBackend`. `BackendStateExternalLifecycle` will be a specialization for services with external assets.
```mermaid
classDiagram
BackendStateLifecycle <|-- BackendStateLifecycleBase
BackendStateLifecycleBase <|-- BackendStateExternalLifecycle
```
Note: `StateLifecycle` can be removed after ext changes are merged.
> Introduce BackendStateLifecycle abstraction

- localstack/config.py
- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
This PR adds a feature flag for enabling the behavior requested in
-  #5801
AWS does not allow creating a queue with the same name for 60 seconds after it was deleted. See the [`DeleteQueue` API Reference](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_DeleteQueue.html). By starting localstack with `SQS_DELAY_RECENTLY_DELETED=1`, localstack will behave in the same way, but it is turned off by default.
The reason for adding the feature flag was that, localstack is often used in testing scenarios where test suites may depend on having a queue with the same name be deleted and created frequently.
> add SQS feature flag to raise QueueDeletedRecently errors

- Dockerfile.rh
With the code moving fast to python3.10, the build pipeline for redhat fails under python3.8.
Install python3.10 from source to enable python3.10 features in the redhat image. To be removed after redhat publishes an official python3.10 package.
After trying pyenv, it became clear that it is slightly easier to just install the sourcecode itself. Pyenv would not have taken less work to setup, but would need more stages regarding environment variables etc (since we cannot assume .bashrc is sourced, we would need to setup everything manually in the image).
In the end it seemed easier (and smaller regarding image size) to install python directly than use pyenv.
> Update redhat image to python 3.10

- localstack/testing/pytest/filters.py
- tests/conftest.py
Example usage: `pytest --filter-fixtures "snapshot,aws_validated" will select all tests that have *either* fixture
> add option to select test cases by fixture usage

- localstack/services/cloudformation/models/events.py
- tests/integration/cloudformation/test_cloudformation_events.py
- tests/integration/templates/events_rule_without_targets.yaml
This PR addresses issue #6033, where is shown that LocalStack CFN throws an error when trying to create a Rule that was defined without Targets. When testing against AWS, shows that it should work without problems. 
Changes:
- CFN Events Rule put_targets function is optional now.
- Test to validate changes.
- Template of a Rule without Targets.
> Fix CFN Events create rule without targets

- localstack/aws/protocol/service_router.py
- localstack/services/apigateway/provider_asf.py
- localstack/services/providers.py
- tests/integration/test_apigateway.py
This PR implements apigateway's execute-api functionality through the edge router mechanism, which makes the custom proxy listener obsolete and unblocks the complete migration to the ASF gateway.
Note that this is only a first version for the community version. We will need to do some unification for our pro extensions and add routing for custom domains. Maybe it would be useful to consolidate some of the `UrlParts` code into the `ApigatewayRouter`. In any case this is a second step.
The major change are:
* introducing the `ApigatewayRouter`, which registers, for each newly added rest API, routing rules into the underlying `Router` (which currently is the `edge.ROUTER` singleton, but can now easily be exchanged). Beyond that it uses the familiar `invoke_rest_api_from_request` abstraction. …
> add apigateway restapi dispatcher to edge router

- localstack/services/sns/provider.py
- localstack/testing/pytest/fixtures.py
- localstack/utils/aws/dead_letter_queue.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
- tests/integration/test_sqs.py
There was an issue when delivering to a SQS DLQ after failing to deliver an SNS notification. The format wasn't properly handled, and we passed the event directly down to the SQS client.
As notified in #5604, the format of the message received from the DLQ after failing to deliver a message with SNS wasn't the same than AWS.
The issue was tracked down to the message formatting of an event to a SNS notification being done in a `try...except` block. When an Exception would rise, we would pass down the raw data to the SQS client, which would then `json.dumps` it directly as a `MessageBody`. 
We need to move the creation of the message body outside the `try...except` block, and pass that message down to the SQS client delivering to the DLQ.
A minor issue arising from this fix is a change to …
> Fix SNS format when delivering to a DLQ

- localstack/utils/bootstrap.py
- localstack/utils/container_utils/docker_cmd_client.py
Currently, if something unexpected goes wrong with the docker run command when starting localstack, we get no feedback to the user what exactly went wrong, the CLI will just terminate.
Unexpected failures will now return the error message as returned from the docker daemon, instead of silently exiting.
Also, I added explicit exception chaining for the CmdDockerClient.
> Add error handling for localstack container startup in CLI

- setup.cfg
Pins the opensearch-py version to 1.1.0, as the lastest version 2.0.0 was just released and seem to have some breaking changes.
> pin opensearch-py to version 1.1.0

- localstack/services/cloudformation/models/s3.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_cloudformation.py
Issue coming from support. 
The problem came from the fact that we consider a resource as not created if it does not have notification configs attached. 
This causes a `BucketAlreadyOwnedByYou` error outside `us-east-1`. 
I changed the deploy template with a function that explicitly checks if the bucket exists and, if not, proceeds to create it.
Feedback are welcome, quite a newbie here on CloudFormation.
> Added explicit check for a bucket when deploying a stack

- localstack/config.py
- localstack/services/kinesis/kinesalite_server.py
- localstack/services/kinesis/kinesis_mock_server.py
- localstack/services/kinesis/kinesis_starter.py
Similar to https://github.com/localstack/localstack/pull/6135, added ax explicit argument to set the persistence path for Kinesis. In addition, added a new config variable to set the persistence interval (mostly to speed up testing).
> Kinesis - option for persistence path

- localstack/services/apigateway/provider.py
- tests/integration/test_apigateway.py
This PR fixes the `delete_rest_api` method, which would previously raise internal errors (propagating moto `KeyError` from here: https://github.com/spulec/moto/blob/34a98d2c205ed311a867083b3ee17c18fb8ebb48/moto/apigateway/models.py#L1368-L1370).
I noticed these errors when running the CloudFormation tests which were trying to retry apparently already deleted rest apis. Should maybe investigate this more.
> fix apigateway delete_rest_api method

- .github/workflows/stale-bot.yml
Added two more labels to `exempt-issue-labels`:
* `feature-request-approved ` used for features that have been approved by the LS team
* `bug-confirmed` used for bugs that have been approved by the LS team
> add two more labels to 'exempt-issue-labels' for the stale-bot

- localstack/http/asgi.py
- localstack/http/hypercorn.py
- tests/unit/http_/test_asgi.py
- tests/unit/http_/test_dispatcher.py
This PR fixes the HypercornServer to allow multiple instances of the server. It's mostly a documentation change, and i also adapted the tests to show it it has to be used together with the ASGI adapter.
I also added a few tests to increase the coverage of the handler dispatcher of the router API.
> fix HypercornServer API and test to allow multiple instances

- localstack/services/dynamodbstreams/dynamodbstreams_api.py
- localstack/services/dynamodbstreams/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_dynamodb.py
This PR implements (or start using) the ExclusiveStartShardId parameter for DynamoDB streams `describe_stream` operation. 
#6158 very well described and gave a detailed explanation of ExclusiveStartShardId not being used.
AWS docs for DescribeStream operation:
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_DescribeStream.html
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_StreamDescription.html
The `shardId`s coming from Kinesis were formatted to look like DynamoDB streams, auto generated with a timestamp every time the function was called. We had to implement a way to store those DynamoDB `shardId`s to be able to filter them if the function was called a second time. (Otherwise the shardId always looked "recent").
Kinesis returns the …
> implement ExclusiveStartShardId for DynamoDB Streams describe_stream

- localstack/services/providers.py
This PR makes the provider introduced in #6040 the default.
This PR also serves as a demo of how we can do graceful migration paths for minor releases.
> make asf apigateway provider the default

- localstack/services/route53/provider.py
- Terraform was showing empty response when using `get-health-check` api
- Fixed response of `get-health-check`
> fixed: route53 get-health-check response

- localstack/services/dynamodb/provider.py
- localstack/services/dynamodbstreams/dynamodbstreams_api.py
- tests/integration/test_dynamodb.py
This PR adds concurrency control around the get and increment operation of the ddbstreams sequence number. 
The test `test_dynamodb_stream_records_with_update_item` was flaking frequently with sequence numbers not being correct. My suspicion is that it is caused by a race condition in the critical section of incrementing the sequence number, but not 100% sure, but hope this fixes it :crossed_fingers:
> fix concurrency of dynamodbstreams sequence number

- localstack/services/cloudformation/models/__init__.py
- localstack/services/cloudformation/models/opensearch.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/templates/opensearch_domain.yaml
- tests/integration/test_opensearch.py
This PR adds the `Domain` resource for OpenSearch in CloudFormation. It functions the same as the Elasticsearch Domain (except some differences in parameters). 
I chose the code duplication because the OpenSearch Resource might diverge in the future.
Fixes #6163
> Add `AWS::OpenSearchService::Domain`

- localstack/config.py
Removed the Literal import from typing as it was added starting at Python 3.8, causing import errors. 
This fixes #6157
> Fix CLI remove Literal type for 3.6 and 3.7 compatibility

- .circleci/config.yml
We deprecated the elasticmq SQS provider in the v0.14.3 release, so we can also stop testing it to start phasing it out.
it was also causing problems in a recent build on master.
> remove itest-sqs-provider test from CI pipeline

- localstack/aws/app.py
- localstack/aws/chain.py
- localstack/aws/handlers/__init__.py
- tests/unit/aws/test_chain.py
This PR adds a new type of handler that can contain multiple handlers. It's a simple nested handler chain. One specific instances, the `serve_custom_service_request_handlers`, will be used to hook things like the IAM policy enforcer into the chain without modifying the gateway request handlers directly.
The implementation is a compromise. Building a full nested handler chain is not as straight forward because it's not always clear how the control flow behavior (terminated, stopped, exception handlers, ...) should propagate to the outer handler chain. So i decided to keep it simple for now.
I added some unit tests using mocks that verify that the control flow behavior is executed correctly.
> add composite handler for asf handler chain

- localstack/testing/pytest/fixture_conflicts.py
- tests/conftest.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/test_iam.py
I feel it's generally bad design that pytest allows multiple fixture definitons with the same name to exist. In our case this is never used intentionally and only lead to hard to debug issues in the past, so I've blocked this by default now. 
The default behavior can be reverted to by specifying `--ignore-fixture-conflicts`.
cc @baermat
> Exit pytest when encountering duplicate fixture names by default

- localstack/testing/snapshots/prototype.py
- localstack/testing/snapshots/transformer.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/cloudformation/test_cloudformation_sam.py
- tests/integration/cloudformation/test_cloudformation_sam.snapshot.json
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
- tests/integration/s3/test_s3_notifications_sns.py
- tests/integration/s3/test_s3_notifications_sns.snapshot.json
- tests/integration/s3/test_s3_notifications_sqs.py
- tests/integration/s3/test_s3_notifications_sqs.snapshot.json
- tests/integration/test_logs.py
- tests/integration/test_logs.snapshot.json
Use snapshot verification for more s3 and cloudformation tests, that have already been marked as `aws_validated`
> Add snapshot tests for s3 and cloudformation iam

- localstack/services/plugins.py
Changes the StateSerializer API to use the werkzeug request object.
> refactor state serializer api to use werkzeug request

- localstack/aws/app.py
- localstack/aws/chain.py
- localstack/aws/handlers/__init__.py
- tests/unit/aws/test_chain.py
Building on #6240, this PR adds a similar mechanism for response handlers (also a compromise until we have a well-defined nested handler chain mechanism).
It is used in localstack-ext to plug in response handlers (like the state serializers) into the response handler chain.
> add pluggable response handler for asf handler chain

- localstack/utils/server/proxy_server.py
Currently, if we set client certs (or the fix_encoding variable), our ssl proxy (which should be a normal tcp proxy) uses an http server for its forwarding.
This can lead to problems, if the requests routed through this are not only http (protocol switch to a websocket for example, for `kubectl exec`).
As long as "fix_encoding" is not set, we will now use a straightforward tcp proxy, terminating the ssl connection at the proxy, and starting a new one with the target, even if client certs are specified.
> Allow TCP proxying with client certs without h11

- localstack/services/apigateway/helpers.py
- tests/integration/files/swagger.yaml
- tests/integration/test_apigateway.py
This PR will make sure `requestParameters` included in the openapi document, are included in the method resource model.
> minor fix to include request parameters while importing openapi

- localstack/http/router.py
- localstack/services/apigateway/provider_asf.py
- localstack/services/apigateway/router_asf.py
With #6040, a new provider for API Gateway has been introduced, which uses native ASF features for the routing instead of the legacy proxy listener. It registered a route for each created API in API Gateway.
This PR refactors the new routing approach a bit such that it only registers a handful of parameterized routes.
This has the following benefits:
- The `ApigatewayRouter` now correctly returns an HTTP 404 if a request targets a non-existing API.
- The `ApigatewayRouter` now already parses all the path and host parameters (`stage`, `api_id`, `path`).
- These aren't used yet, but these should essentially replace all the regex parsing in `helpers.py#set_api_id_stage_invocation_path`.
- These should be introduced with a bigger refactoring of the API Gateway infrastructure.
- The …
> refactor API Gateway ASF provier / routing

- localstack/services/s3/s3_starter.py
This PR fixes a wrong HTTP status on the InvalidObjectState error implementation.
I reported a wrong status code for the InvalidObjectState error on #6242.
The reported error comes from the [moto](https://github.com/spulec/moto) library. However, there is an implementation in the localstack code that needs to be also fixed.
> Fix HTTP status for InvalidObjectState error code

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
The Lambda endpoint subscription to a SNS topic is not auto confirmed for now even for same AWS account for the endpoint and topic.
The issue encountered by the user is that Terraform then timeout because the subscription attributes contain `"PendingConfirmation"="true"` indefinitely.
Add a small change to auto confirm Lambda subscriptions to a SNS topic like for SQS (they have the same behaviour). This will need to be revisited for multi-account, as stated on AWS documentation for the `Subscribe` action.
https://docs.aws.amazon.com/sns/latest/api/API_Subscribe.html
> Fix: auto confirm SNS subscription for lambda endpoint

- localstack/services/edge.py
This PR enforces the usage of the legacy edge proxy when being used purely as a forwarder (since this is not yet supported in the new ASF gateway).
> fix ASF gateway forwarding

- localstack/aws/protocol/parser.py
This PR adds overwrite/restore logic to the `VirtualHostRewriter` for the `RAW_URI` attribute to the request environment. we need to modify this value because we are accessing it directly from the environment via `get_raw_path`.
This fixes two of the failing tests that surfaced with the ASF gateway.
> fix s3 VirtualHostRewriter to also restore RAW_URI

- localstack/services/apigateway/router_asf.py
This PR fixes two regressions in the ASF apigateway provider that were (probably) introduced by #6267
* One relates to header casing (the casing is expected to be title-cased, but is then transformed again via `canonicalize_api_names` for lambda calls)
* One protects `invoke_rest_api` from a null pointer
> fix ASF integration of to_invocation_context

- localstack/utils/aws/aws_stack.py
- tests/integration/test_apigateway_api.py
This PR fixes following failing tests in `v1` branch:
```
FAILED tests/integration/test_s3.py::TestS3::test_presigned_url_signature_authentication
FAILED tests/integration/test_s3.py::TestS3::test_presigned_url_signature_authentication_virtual_host_addressing
FAILED tests/integration/test_apigateway_api.py::test_put_integration_validation
```
> fix access key id auth header extraction for different signature versions

- localstack/services/s3/s3_listener.py
- tests/integration/s3/test_s3.py
- tests/integration/test_s3.py
Improve parity of `EncodingType`, `Delimiter` and `Marker` elements in S3 list_objects responses. This issue surfaced when running some tests with Athena queries that are querying data from S3 - tested against AWS (with `TEST_TARGET=AWS_CLOUD`). Currently still patching the `response` directly - applying this patch should get a bit nicer once we've migrated S3 to ASF. 👍
> Improve parity of EncodingType and Delimiter in S3 list_objects response

- localstack/utils/collections.py
- tests/unit/utils/test_collections.py
Add simple hashable dict util class `HashableJsonDict`. This can be useful for adding dicts to, e.g., hash sets. It implements the `__hash__` function by computing the canonical JSON (which is unique and deterministic for JSON structures). Hence, this utility also only works for dicts that can be JSON encoded (as the name implies).
> Add simple hashable dict util class

- localstack/aws/protocol/service_router.py
- tests/unit/aws/test_service_router.py
- Fixes an issue with the service detection for services which have conflicts with other services, specifically for `timestream-write` and `timestream-query`.
- Creates a dynamic, parameterized test - based on a prototype of @thrau - which checks every single service and operation.
- Some tests are skipped because there are conflicts in the service specs which force us to handle these differently (f.e. `rds`, `neptune`, and `docdb`). These special cases cannot be covered by such a generalized test.
- Unsupported services which cause problems are currently marked as `xfail`. This is quite debatable because this introduces 936 tests where their failure is ignored.
- The whole test run takes about 20 seconds (which is quite a lot for the unit tests), …
> fix detection of timestream requests in service router

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
This PR addresses issue #6238. With these changes if a message is published to an Endpoint for a GCM Platform Application, LocalStack will use the [GCM Http protocol](https://firebase.google.com/docs/cloud-messaging/http-server-ref?hl=en) to send the message.
Changes:
- Integration of GCM protocol.
- Test that validates that LocalStack is trying to use the protocol.
Note:
- For the test to expect a response with `status_code == 200` it will need a real service key and a token.
> GCM support for SNS

- .circleci/config.yml
- setup.cfg
- tests/unit/aws/test_service_router.py
The latest version of cryptography ([37.0.3](https://pypi.org/project/cryptography/37.0.3/)) causes issues in our CircleCI environment.
This PR is an attempt to fix these issues pinning the version of cryptography to the previous version (`37.0.2`).
In addition it also limits the log output of the service router unit tests introduced in https://github.com/localstack/localstack/pull/6311.
> fix crypto unit tests

- localstack/aws/protocol/service_router.py
- tests/unit/aws/test_service_router.py
This PR adds RDS routing to the community version of the service name parser using the same mechanism introduced in #6311 
I also added a small optimization to avoid checking custom endpoint path rules if the path is `/` (for which there aren't any custom path rules). while doing that, i saw that the code in block 3. is actually nonsense, specifically the `if path.startswith(endpointPrefix)`, since the endpointPrefix pertains to the host, not the path. i'll do that in a follow-up PR.
> add rds docdb and neptune to the list of known API conflicts

- localstack/aws/protocol/service_router.py
- tests/unit/aws/test_service_router.py
This PR fixes an error in the service router that has not surfaced yet because we don't use the feature. it relates to matching services based on the endpointPrefix described in the spec, which is part of the host, and not the path how it was implemented.
I added a small test that we can extend in a future iteration when the feature is used.
This actually gives us a way to disambiguate services like chime, where we can tell the user to set `awslocal --endpoint-url http://identity-chime.localhost.localstack.cloud` if they want to use the service.
> fix aws service router to match endpointPrefixes on the host

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/integration.py
- localstack/services/apigateway/invocations.py
- tests/integration/files/openapi-mock.json
- tests/integration/test_apigateway.py
This PR makes sure the import API includes the response templates and extracts the MOCK Integration into his own class.
Fixes the use case described [here](https://github.com/nulib/localstack-api-gateway) for the MOCK backend integration.
> fix mock integration invocations

- localstack/services/s3/s3_listener.py
- localstack/services/s3/s3_utils.py
- tests/integration/s3/test_s3.py
- tests/integration/test_cloudformation.py
Attach additional attributes to S3 bucket objects instead of using global dicts.
This fixes an issue that has surfaced while investigating a user issue related to persistence state that gets lost after restarting the instance. The root cause is that we're currently only persisting the FakeBucket objects themselves, but _not_ any additional attributes attached to the `s3_backend` moto object.
* Remove the existing global state dicts like `S3_NOTIFICATIONS`, `BUCKET_CORS`, etc.
* Introduce a `BackendState` util class that performs lookup and initialization of additional attributes. The attributes are attached to the `FakeBucket` moto backend objects directly
* Minor fix that strips query params from `extract_bucket_name(..)` function - this was discovered during testing …
> Attach additional attributes to S3 bucket objects instead of using global dicts

- localstack/aws/proxy.py
Handles situations where the access key is not set in the request.
```
2022-06-22T13:57:36.536:ERROR:localstack.aws.handlers.logging: exception during call chain
File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
File "/opt/code/localstack/localstack/aws/handlers/service.py", line 120, in __call__
handler(chain, context, response)
File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 69, in __call__
result = self.forward_request(
File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 129, in forward_request
return do_forward_request(
File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
return new(target, *args, **kwargs)
File …
```
> Default access key for legacy gateway

- localstack/services/apigateway/router_asf.py
This PR only contains a small change in the ASF API Gateway router (which is not enabled yet in master) introduced with https://github.com/localstack/localstack/pull/6267.
It ensures that a single instance of the router only registers its dynamic routes once.
This allows a router instance to be shared among multiple providers or be called by a single provider multiple times while ensuring that the HTTP router isn't spammed with duplicate routes.
> fix multi-registration of shared ASF API GW router

- localstack/services/apigateway/helpers.py
Small fix against OpenAPI 2.0 authorizers definitions that are not AWS extensions.
This PR requires a fix done in moto [upstream](https://github.com/spulec/moto/pull/5224)
> fix to skip openapi authorizers that are not extensions

- localstack/services/kms/provider.py
- localstack/testing/pytest/fixtures.py
- localstack/utils/aws/aws_stack.py
- tests/integration/test_kms.py
When using the moto-backed handler, listing aliases does not consider the key-id. This PR adds that functionality.
Addresses #6193
> Add handling of KMS ListAliases call with KeyId

- localstack/utils/container_utils/container_client.py
Fixes recently introduced regression by relying on python3.10 isinstance support for union types.
Fixes #6334
> Add workaround for union isinstance in PortMappings for python lower 3.10

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/patches.py
- localstack/services/awslambda/lambda_api.py
- tests/integration/files/api_definition.yaml
- tests/integration/test_apigateway.py
- tests/unit/test_apigateway.py
Currently, in Localstack, an API Gateway setup with a backend Lambda integration had no option to invoke the lambda [asynchronously](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-integration-async.html). To invoke a lambda asynchronously through API Gateway we need to set up the integration to pass the header `X-Amz-Invocation-Type` with `"'Event'"` value to the lambda runtime.
The integration configuration setup looks like the following,
```
request_parameters = {
"integration.request.header.X-Amz-Invocation-Type" = "'Event'"
}
```
Before we invoke the lambda executor we parse the request parameters and add the headers included in the configuration.
The next iteration will improve upon this feature by sourcing method request parameters and pass them to …
> add support for apigateway lambda asynchronous invocations

- localstack/services/cloudformation/provider.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/cloudformation/test_cloudformation_stacks.py
- tests/integration/templates/simple_api.yaml
This PR  addresses issue #6038. Due to some difficulties with Commandeer while triaging, I couldn't exactly find out why it still displays a stack with the state "DELETE_COMPLETE", my best guess is that it uses the timestamp attributes `["CreationTime", "DeletionTime", "LastUpdatedTime"]` to determine if the stack should be shown but Localstack does not return the "DeletionTime" or the "LastUpdatedTime".
Changes:
- Set the DeletionTime and LastUpdatedTime attributes accordingly.
- Test to validate the return of the attributes when calling the cfn describe stack function.
> CFN Stack timestamps attributes

- localstack/services/install.py
- localstack/services/stepfunctions/stepfunctions_starter.py
- localstack/utils/run.py
This small PR:
- adds the possibility to pass a custom persistence directory for stepfunctions (needed by Cloud Pods when `DATA_DIR` is not set);
- slightly check for killing the pid.
> Option for persistence path to stepfunctions

- localstack/services/apigateway/router_asf.py
- tests/integration/conftest.py
- tests/integration/test_apigateway_integrations.py
This PR fixes a recently introduced test #6289 when running with the `asf` apigateway provider.
The error originated from not converting lambda responses correctly into werkzeug Response objects (which was expecting strings but receiving dicts to convert to JSON).
FYI: there's at least one instance where content-length is set to '1' because a a dictionary is passed to `update_content_length`, although it expects a string/bytes value here: https://github.com/localstack/localstack/blob/d37917610da1dc95156f84aba5a353dda0104eac/localstack/services/apigateway/invocations.py#L388-L392
setting content-length manually leads to all sorts of problems and isn't necessary anymore as we move to werkzeug, which handles content-length itself. @calvernaz we should touch base to make sure we're using the …
> fix asf apigateway lambda response conversion

- localstack/services/edge.py
This PR fixes an issue that would prevent the ASF gateway from starting with SSL mode enabled.
In the edge proxy we were completely ignoring the `use_ssl` attribute, doing some really strange things:
* first we were ignoring it and setting it to false by default: https://github.com/localstack/localstack/blob/d37917610da1dc95156f84aba5a353dda0104eac/localstack/services/edge.py#L437-L440
* then we were ignoring it again, and setting it to true by default: https://github.com/localstack/localstack/blob/d37917610da1dc95156f84aba5a353dda0104eac/localstack/services/edge.py#L366-L369
* but we're never actually setting it in the first place, because here it's set to true by default and never set explicitly when calling `start_component` https://github.com/localstack/localstack/blob/d37917610da1dc95 …
> fix passing down of use_ssl when starting edge

- localstack/services/s3/s3_listener.py
- tests/integration/s3/test_s3.py
This PR fixes ASF compatibility with the recently introduced changes in #6325. The exception wasn't actually raised, should have seen that in the review.
I also moved the new test into `TestS3` which is the class grouping the basic API calls.
> fix S3 BackendState to raise ASF NoSuchBucket exception

- localstack/services/s3/s3_starter.py
- tests/integration/s3/test_s3.py
- tests/integration/test_s3.py
This PR follows up on #6344 which i didn't test completely against v1. There's a patch that changes moto to call an `s3_listener` method, which can raise a `NoSuchBucket` error, which moto doesn't know how to handle, so we have to translate back to a moto `MissingBucket` exception.
I also migrated the affected test and refactored them to correctly be under `TestS3` class.
It fixes the [failing s3 tests](https://app.circleci.com/pipelines/github/localstack/localstack/7096/workflows/642ef431-5b37-4d04-b0b8-515945ca9f6c/jobs/42907/tests#failed-test) in the v1 integration
> fix s3 delete_bucket compatibility with ASF gateway

- localstack/services/apigateway/invocations.py
This PR fixes a compatibility issue with the ASF API Gateway implementation, where async responses would render to `"{}"` rather than `""`.
The `LambdaResponse` content field would be an empty dictionary, and with the old edge proxy we're setting that to `""` in a very generalized way: https://github.com/localstack/localstack/blob/0ae805df648e1a8c5824cddf5abbd1200acd2532/localstack/utils/server/http2_server.py#L207
we don't manipulate response bodies in the same way without knowing anything about their content types in the ASF gateway, so this PR makes sure the LambdaResponse content is set to `""` before it even leaves the apigateway provider.
> fix apigw LambdaResponse with async invocation to return empty body

- Dockerfile
With https://github.com/localstack/localstack/pull/6297, a Docker-native `HEALTHCHECK` has been introduced.
Docker shows the log output of the command when inspecting the container (this is also contained in our diagnose endpoint data).
For the health check, the CLI's `status services` command is used, which by default prints a nicely formatted table.
This table obviously is quite unreadable in the logs (because it's basically just a bunch of unicode characters):
```
{
"Status": "healthy",
"FailingStreak": 0,
"Log": [
{
"Start": "2022-06-24T09:55:41.209356566+02:00",
"End": "2022-06-24T09:55:41.915356053+02:00",
"ExitCode": 0,
"Output": "┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓\n┃ Service                  ┃ Status      ┃\n┡━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩\n│ acm …
```
> fix docker inspect health check log output

- localstack/aws/serving/wsgi.py
- localstack/services/apigateway/router_asf.py
This PR changes the handling of the headers when using the new HTTP gateway with API GW:
- It uses the raw headers in the ASGI/WSGI bridge to preserve the casing of the HTTP headers in the WSGI environment.
- It removes the title casing in the ASF API GW implementation (which was a workaround for the header casing).
- It adds the `x-localstack-edge` header in the ASF API GW implementation (which is used to parse the domain).
> fix ASF API GW / ASF HTTP gateway headers

- localstack/services/s3/s3_listener.py
The S3 event structure described in https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html states that Records.s3.configurationId is the `"ID found in the bucket notification configuration"`. 
The notification configuration is available in the enclosing context, so it can be added (as requested by user in support channel)
> Add notification configuration id to event message

- localstack/services/generic_proxy.py
This PR fixes an issue where `copy.deepcopy` would fail on a backend that looks like this:
```python
class MyProviderState(RegionBackend):
distributions: Dict[str, Distribution]
def __init__(self):
self.distributions = {}
@classmethod
def get_current_request_region(cls):
return "global"
```
calling `copy.deepcopy(MyProviderState.__dict__)` would fail here, because the dict of the class will contain the classmethod `get_current_request_region` as a method descriptor, which cannot be pickled by `deepcopy`, resulting in exceptions.
```
{
'__module__': '__main__',
'__annotations__': {
'distributions': typing.Dict[str, ...]
},
'__init__': <function MyProviderState.__init__ at 0x7f7483ce9ea0>,
'get_current_request_region': <classmethod(<function MyProviderState.get_current_request_region at …
```
> fix pickling in multi-account region backend

- .github/workflows/pro-integration.yml
- .github/workflows/rebase-release-prs.yml
- .github/workflows/rebase-release-targeting-prs.yml
This PR adds convenience features to our GitHub workflows concerning the handling of our release branch PR (#6272) as well as  PRs targeting the release branch.
In order to keep the branches up to date, two workflows are added:
- `rebase-release-prs.yml` / `Rebase release PRs`
- This workflow is triggered by every push into master and rebases our release branches.
- It tries to rebase the Release PRs (f.e. #6272) upon the latest commit.
- i.e. For every push to master the release branches for which PRs exist are tried to be rebased upon the latest commit.
- Currently, the list of branches to rebase is hard-coded. The used action currently cannot handle a more elaborate head branch pattern.
- `rebase-release-targeting-prs.yml` / `Rebase PRs targeting release branches`
- This workflow is …
> add convenience GitHub workflows for release branches

- localstack/services/dynamodb/provider.py
Addresses #6364. 
It simply extends the usage of `_get_size_bytes()` to all the instances where it's necessary to compute the `SizeBytes`. 
In particular, LOC 553 is the responsible for the mentioned issue.
> Fix SizeBytes calculation for non serializable items

- Dockerfile
Add second pip install with `--no-deps` to ensure latest dev releases are properly installed and not overwritten in the Docker image.
This is an attempt to ensure we're installing the latest dev releases, which are currently being overwritten by the transitive dependency localstack-ext(`0.14.5.devX`)->localstack(`>=0.14.3.2` -> resolves to `0.14.4`). 
Theoretically, we could end up in a situation where some of the other transitive dependencies (any non plux/localstack/-ext libraries) no longer match with the shallow install of -ext, although arguably this would be an unlikely corner case. To be discussed..
> Add pip install to ensure latest dev releases are not overwritten

- .github/workflows/cla.yml
- .github/workflows/stale-bot.yml
- .github/workflows/welcome-first-time-contributors.yml
This PR changes the token for the following actions:
- CLA Assistant
- Triage Stale issues
- Welcome First Time Contributors ✨
Previously, the comments by this actions looked as follows:
- CLA Assistant
- Triage Stale issues
- Welcome First Time Contributors ✨ 
Instead of the default token, they now use the `PRO_ACCESS_TOKEN`, a Personal Access Token of @localstack-bot.
This should change the appearance of the three actions in PRs and issues from @github-actions to @localstack-bot.
> fix GitHub action user (use PAT of @localstack-bot)

- localstack/services/awslambda/lambda_executors.py
- localstack/services/awslambda/lambda_starter.py
- localstack/services/infra.py
The method `get_host_path_for_path_in_docker` had a serious problem:
It would replace `/var/lib/localstack/tmp` instead of `/var/lib/localstack` in the path.
Therefore, the LS container path `/var/lib/localstack/tmp/zipfile.aaaaaaaa` (where the lambda code is located in the container) got mapped to `/tmp/localstack/zipfile.aaaaaaaa` instead of `/tmp/localstack/tmp/zipfile.aaaaaaaaa` (which would be the actual location).
This also resulted in an immediate failure in pro, since it tried to replace `/var/lib/localstack/tmp/(.*)` on `/var/lib/localstack/tmp`, which cannot work (due to missing trailing slash).
This PR fixes the behavior, introduces a function docstring which documents the expected behavior of the function, and logs a warning if the replacement should be unsuccessful.
Also …
> Fix host path replacement for lambda volume mounts

- Dockerfile
In our CI environment, we currently see issues with newly introduced dependencies in our extensions (f.e. builds for [#6376](https://app.circleci.com/pipelines/github/localstack/localstack/7209/workflows/d4fbaba1-4bb5-4bba-bfd1-5926ab610d68)).
Therefore this PR ensures that also the runtime dependencies of `localstack-ext` are updated at the end.
The current issues (and the "flaky" looks of it) are caused by the Docker layer caching in combination with our dev releases:
- `localstack` defines `localstack-ext[runtime]>=0.14.5.dev,<0.14.6`
- This includes the latest dev releases (due to the `.dev` suffix).
- If there are no changes to the layers before `make install-runtime` is called in the `Dockerfile` but a new ext dev release (not contained in the cache yet) defines a new dependency, it …
> fix CI dep issues for newly introduced ext runtime deps

- localstack/aws/handlers/auth.py
Fixes an issue where `access_key_id` could be None when parsing non-AWS requests.
> fix None check in AccountIdEnricher

- localstack/testing/pytest/fixtures.py
- localstack/utils/aws/aws_stack.py
- tests/integration/test_dynamodb.py
Minor fixes to mark DynamoDB test with binary data as `aws_validated`. The starting point for this investigation was the PR https://github.com/localstack/localstack/pull/6371 .
* Remove deprecated `sleep_after=2` argument in the `create_dynamodb_table(..)` utility, instead add a `wait_for_active=True` parameter, which is required for parity testing against AWS (waiting for the table to become available)
* Changed the default DynamoDB test table `BillingMode` from `PROVISIONED` to `PAY_PER_REQUEST` - this is to avoid situations where we accidentally create (and don't clean up) `PROVISIONED` tables in AWS - they can become **really** expensive.. :)
* Remove obsolete/deprecated `env=..` parameter (this is totally outdated, and should get removed from the entire codebase …
> Minor fixes to mark DynamoDB test with binary data as aws_validated

- localstack/services/sns/provider.py
- tests/integration/test_notifications.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
- tests/unit/test_sns.py
This PR fixes `MessageAttributes` for SNS, and add parity with AWS.
A user encounter issue while trying to cast `MessageAttributes` with aws-sdk in Java I believe, inside a lambda.
The fields of our `MessageAttributes` were wrong: `"DataType"` and `"{type}Value"` where it should have been `"Type"` and `"Value"` for a message sent to a Lambda.
I've done a round of check to fix `MessageAttributes` format where it was needed, and I checked those against AWS by rewriting some tests to be `aws_validated`.
https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html
Some behaviour has changed, as where `MessageAttributes` is located depends on `RawMessageDelivery` (SNS adds metadata or not to the message, and encapsulates the message inside a `"Body"` field).
When `RawMessageDelivery` …
> fix SNS MessageAttributes parity with AWS

- localstack/aws/protocol/serializer.py
- tests/integration/test_opensearch.py
- tests/unit/aws/protocol/test_serializer.py
This PR fixes a small issue in the ASF error serialization for (rest-)json protocols with (misbehaving) clients.
The specs ([json 1.0](https://awslabs.github.io/smithy/1.0/spec/aws/aws-json-1_0-protocol.html#operation-error-serialization), [json 1.1](https://awslabs.github.io/smithy/1.0/spec/aws/aws-json-1_1-protocol.html#operation-error-serialization), [rest-json](https://awslabs.github.io/smithy/1.0/spec/aws/aws-restjson1-protocol.html)) define that an error may either have a JSON member `__type` _or_ a JSON member `code` _or_ a header field `X-Amzn-Errortype` indicating the error code shape.
This PR adds the header field in addition to the `__type` member in order to avoid service-specific serializer configurations and in order to increase the support among different clients / …
> fix missing (rest-)json error type header field

- localstack/http/asgi.py
- localstack/http/client.py
- localstack/http/dispatcher.py
- localstack/http/proxy.py
- localstack/http/request.py
- tests/unit/http_/conftest.py
- tests/unit/http_/test_asgi.py
- tests/unit/http_/test_proxy.py
This PR extends our HTTP server framework with proxy components. This will need a second iteration, as some of the components still have a bit of a naive implementation, and also the problem around IO and `restore_payload` are still not resolved.
The central new APIs are `HttpClient` and `Proxy`.
`HttpClient` is a client that can take Werkzeug's server-side `Request` object and actually perform the request as a client, and it returns a Werkzeug `Response`, which can be seamlessly handed down stream in the handler pipeline.
Currently there is only a very simple implementation using the [requests](https://github.com/psf/requests) library. The major limitation is that it relies on `restore_payload` to get the incoming request's data, which will always consume and reconstruct the HTTP request …
> implement HTTP proxy framework

- localstack/services/dynamodb/provider.py
- localstack/services/dynamodbstreams/dynamodbstreams_api.py
- localstack/utils/json.py
- tests/integration/test_dynamodb.py
- tests/integration/test_kinesis.py
This PR addresses #6364 where the user reported error messages in the logs while trying to stream the DDB changes to Kinesis. This was due to errors in serializing bytes content. 
Introduced a new encoder for binary content (less broad than the `CustomEncoder` we already have) and introduced/refactored some tests.
> DynamoDB streaming binary content

- Dockerfile
- bin/supervisord.conf
- localstack/aws/chain.py
- localstack/cli/main.py
- localstack/config.py
- localstack/extensions/__init__.py
- localstack/extensions/api/__init__.py
- localstack/extensions/api/aws.py
- localstack/extensions/api/extension.py
- localstack/extensions/api/http.py
- localstack/extensions/api/runtime.py
- localstack/extensions/api/services.py
- localstack/http/asgi.py
- localstack/runtime/hooks.py
- localstack/services/edge.py
- localstack/services/internal.py
- localstack/services/motoserver.py
- localstack/services/opensearch/provider.py
- localstack/utils/analytics/metadata.py
- localstack/utils/common.py
- localstack/utils/objects.py
- localstack/utils/venv.py
- tests/unit/utils/test_objects.py
This PR introduces the extensions API and a simple mechanism to manage python dependencies through the container in a virtual environment stored on the host.
* Circular venv from `/var/lib/localstack/lib/extensions/python_venv` <-> `/opt/code/localstack/.venv ` (paths don't have to exist, python site will ignore them.
* three cli commands `localstack extensions` `init | install | uninstall` (which are basically just: create venv, pip install, pip uninstall)
* internal cli to perform the operations when inside the container
* expose parts of our internal API via `localstack.extensions.api`
* added several [PEP 224](https://peps.python.org/pep-0224/)-style attribute docs for special variables exposed through the extensions API.
Example use: …
> implement localstack python extensions framework

- docker-compose.yml
- localstack/utils/bootstrap.py
Currently, we have some legacy configuration in the docker-compose file, which are replaced (in v1 or before) by automatic detection.
This includes:
* network_mode: bridge : This configuration is not necessary anymore, as we detect the docker network automatically using the get_main_container_network utility. Also it leads to problems when we use host aliases or want to use docker dns capabilities.
* HOST_TMP_FOLDER: this is also automatically detected now, where necessary (lambda code mounting), by inspecting the LS docker container and finding the appropriate path.
As v1 is needing configuration changes anyway, we should sneak those in as well.
> Remove deprecated docker-compose defaults

- .dockerignore
- Dockerfile
This PR updates the `.dockerignore` file to match the current layout of the local build environment. I also clarified the documentation in the Dockerfile to better explain what's going on and that the `.dockerignore` file is relevant to the line.
I also added glob patterns for `node_modules` and `.terraform` folders in the integration tests, and some other local artifacts, which can be useful when you build the docker image locally and previously executed the test suite.
Alternatively we could include the entire .filesystem/usr/lib/localstack directory from the host
> update .dockerignore to new filesystem hierarchy

- setup.cfg
Add test dependency to `deepdiff`. This library is being used in the `testing.snapshots` package, and we are currently depending on it transitively via -ext. This dependency is going to be removed upstream, hence adding it here directly.
> minor: Add test dependency to deepdiff

- localstack/services/plugins.py
Fixes #6361
This PR introduces a fallback logic to the currently configured default provider, if the configured provider of a service cannot be found.
While quite straightforward, this approach has a significant caveat: If Pro services are activated, it will still fallback to the community service in case the configuration provided is wrong.
We could solve this (possibly in another PR), for example by providing some kind of ordering logic to the ProviderConfig class, to be able to register provider overrides with some kind of priority, and therefore iterate over them in case one provider is not actually available. Thoughts @thrau ?
> Add fallback to default provider if configured provider is not available

- localstack/services/apigateway/integration.py
- localstack/services/apigateway/invocations.py
- tests/integration/awslambda/functions/apigw_502.js
- tests/integration/awslambda/functions/apigw_integration.js
- tests/integration/awslambda/functions/lambda_handler.js
- tests/integration/awslambda/functions/lambda_integration.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/awslambda/test_lambda_integration.py
- tests/integration/test_apigateway.py
This PR addresses issue #6134, where an user mentions that the ApiGW-Lambda integration returns `content-type: text/html` regardless of what the Lambda returns, which is not the case, but another user mentioned that the integration by default should return `content-type: application/json`. While triaging this, I also discovered that AWS does a validation on the lambda response and returns a 502 if it doesn't follow a [format](https://aws.amazon.com/premiumsupport/knowledge-center/malformed-502-api-gateway).
Changes:
- Add a test to make sure that APIGW-Lambda integration returns the headers correctly.
- The validation for the Lambda response and return a 502 error if it doesn't pass.
- Test of the integration 502 error.
- The integration by default returns a `content-type: …
> APIGW Lambda integration validations

- tests/integration/test_events.py
This small PR addresses the last comment made on #5878. 
Changes:
- Test refactor for more clarity and more validations
> Refactor Events test

- setup.cfg
With https://github.com/localstack/localstack/pull/6318, we had to pin the version of cryptography in order to fix our unit tests in Circle CI.
A new version of cryptography (built on OpenSSL 3.0.5), which contains security updates as well as a fix for the issue which broke our CI, [has been released a few hours ago](https://pypi.org/project/cryptography/37.0.4/). This PR removes the pin and therefore updates cryptography to the newly released version.
Thanks to @dfangl for making me aware of the new release.
> fix cryptography updates / remove pin

- localstack/services/providers.py
- localstack/services/route53/provider.py
- localstack/services/route53resolver/models.py
- localstack/services/route53resolver/provider.py
- localstack/utils/aws/aws_stack.py
- localstack/utils/strings.py
- tests/terraform/terraform-tests.yaml
- TestAccRoute53ResolverFirewallRuleGroup
- TestAccRoute53ResolverFirewallRuleGroup_basic
- TestAccRoute53ResolverFirewallRuleGroup_disappears
- TestAccRoute53ResolverFirewallRuleGroup_tags
- TestAccRoute53ResolverFirewallRule
- TestAccRoute53ResolverFirewallRule_basic
- TestAccRoute53ResolverFirewallRule_block
- TestAccRoute53ResolverFirewallRule_blockOverride
- TestAccRoute53ResolverFirewallRule_disappears
- TestAccRoute53ResolverFirewallDomainList
- TestAccRoute53ResolverFirewallDomainList_basic
- TestAccRoute53ResolverFirewallDomainList_domains
- TestAccRoute53ResolverFirewallDomainList_disappears
- TestAccRoute53ResolverFirewallDomainList_tags
**FirewallRuleGroup**
- create_firewall_rule_group
- delete_firewall_rule_group
- get_firewall_rule_group
- list_firewall_rule_groups …
> added support for firewall rule groups

- localstack/aws/api/core.py
- localstack/aws/app.py
- localstack/aws/handlers/__init__.py
- localstack/aws/handlers/analytics.py
- localstack/aws/handlers/service.py
- localstack/aws/skeleton.py
- tests/unit/aws/handlers/analytics.py
- tests/unit/aws/handlers/service.py
This PR addresses an issue that is emerging because some advanced handlers require access to the AWS response dictionary, but since we don't always have access to that (e.g. when we forward to moto or other backends) we need to parse it.
* Added a common interface of attributes to `ServiceException`. In the future we would set those values directly from the scaffold
* Added two fields the the `RequestContext` that hold the parsed response and optionally the exception
* If the response is already set when reaching the handler (e.g., because the skeleton set the value directly to what came out of the provider), then be happy and do nothing
* When the exception is set, we check that the attributes are set (this is a workaround, see future work)
* Otherwise try to parse the HTTP response
* If …
> add response parser to handler chain

- localstack/services/awslambda/lambda_api.py
- localstack/services/awslambda/lambda_executors.py
This PR adds some log output, to capture the reason for startup failures reported in #4973 and cleanup errors reported in #6312.
It will now log when:
* Containers should get cleaned up, this helps checking why the cleanup does not work
* Lambda throws an exception while starting (they are currently silenced by the functhread flask runs in)
> add logs for lambda executor startup failure and removing containers on shutdown

- localstack/aws/serving/wsgi.py
- localstack/http/asgi.py
In #6354 we introduced a `.raw_items()` call to the headers object coming from the ASGI/WSGI bridge. We are serving through hypercorn, which uses the h2 protocol library for HTTP2, and h11 for HTTP 1.1. In the case of h11, the headers in the ASGI scope are a `h11._headers.Headers` object, which had the `raw_items` method. In the case of HTTP2, h2 was already passing a list of raw headers. I introduced a switch to check that.
Thanks for @whummer for the clear replication instructions:
```bash
curl 'https://localhost.localstack.cloud:4566/' -X OPTIONS -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Access-Control-Request-Method: POST' -H …
```
> fix asgi header extraction for h11 and h2

- localstack/aws/api/core.py
- localstack/aws/handlers/logging.py
- localstack/aws/proxy.py
- localstack/aws/skeleton.py
- localstack/config.py
- localstack/services/iam/provider.py
- localstack/services/sts/provider.py
- localstack/testing/aws/util.py
- localstack/testing/pytest/fixtures.py
- setup.cfg
- tests/integration/test_iam.py
- tests/integration/test_sts.py
This changes are needed to support advanced policy evaluation as part of our efforts to improve IAM policy enforcement.
It contains several breaking changes, which is the reason for the PR target being v1.
* The default principal you are assumed to be when using localstack with invalid (not registered with IAM/sts) credentials is the root principal, not the (invalid) principal `arn:aws:sts::000000000000:user/localstack`. This might change client code for some users, which is why this PR targets v1.
* Deprecate feature to customize the before-mentioned invalid user using TEST_IAM_USER_NAME/ID. Since it was never part of the documentation, the impacted user base should be minimal, still a breaking change. Reason for removal is little benefit, while introducing a inconsistency (you "are" a …
> Setting LS default user to root, support user permission boundary

- localstack/constants.py
- localstack/services/install.py
- pyproject.toml
- setup.cfg
Install sqlite native libs for DynamoDB on OSX arm64. This is required to get up and running in local dev mode using M1 MacBooks.
/cc @pandomic would be great if you could also take a quick look and see if that works on your M1.. 👍 
Also adds a few linter exclusions for `.filesystem` in anticipation of the `v1` merge. (Just ran into a few linter errors with Lambdas inside `.filesystem/var/lib/localstack/tmp/...`). Could also raise it against `v1` branch, but can't harm to have them in here already now..
> Install sqlite native libs for DynamoDB on OSX arm64 (M1)

- .github/workflows/terraform-tests.yml
These keys will prefix match - therefore the cache will not be invalidated _ever_. 
This might have an impact on the currently failing terraform tests on v1.
As seen here: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key the cache keys will fall back to prefix matching.
Since we want to invalidate caches if setup.cfg or go.sum changes, we need to remove the restore keys here.
> remove terraform restore cache keys

- localstack/aws/client.py
- localstack/aws/handlers/service.py
- tests/unit/aws/handlers/service.py
This PR fixes an issue/limitation of the `parse_response` operation in our aws client module.
The problem was that we were not really implementing the parsing logic of botocore correctly, in particular when streaming binary responses are expected, like in `s3.GetObject`, which caused a problem here: https://github.com/boto/botocore/blob/ae44d1de241c13626d05a9301cf62e460833c950/botocore/parsers.py#L910-L914
In boto, when you call `s3_client.get_object(...)`, the `Body` attribute of the response (i.e., the payload), will not actually be bytes, but a readable `io` object. This PR introduces the same behavior for the `parse_response` method.
I modeled the implementation after the version in boto core https://github.com/boto/botocore/blob/ae44d1de241c13626d05a9301cf62e460833c950/botocore/endpoi …
> fix parse_response to handle streaming responses

- localstack/testing/pytest/fixtures.py
- tests/integration/test_kms.py
Validating KMS tests against AWS:
The remaining tests have some implementation issues regarding the usage of correct ciphers with algorithms etc. /cc @whummer
> Validate KMS tests and fix issues

- localstack/aws/app.py
- localstack/aws/client.py
- localstack/aws/handlers/analytics.py
- localstack/aws/handlers/logging.py
- localstack/aws/serving/asgi.py
- localstack/aws/serving/edge.py
- localstack/aws/serving/wsgi.py
- localstack/config.py
- localstack/logging/format.py
- localstack/logging/setup.py
- localstack/utils/bootstrap.py
- tests/unit/logging/test_format.py
This PR overhauls log formatting and restructures the setup routine of the logs a bit
* move logging related code into it's own module `localstack.logging`
* change log output format to spring-inspired format
* to that end i had to introduce a couple of new constructs (see `format.py`)
Not super happy with the `LS_LOG=trace|trace-internal` solution. But I did my best to use what was already there and not introduce additional/different configuration.
* there are two modes of logging: trace and normal log
* internal calls are only logged if `LS_LOG=trace|trace-interal`
* internal calls are only logged as trace when `LS_LOG=trace-internal`
* in trace mode, AWS requests are logged visually similar like they are without tracing  (`AWS sqs.ListQueues => 200`), but we add in the same line the …
> add new log output formatting and asf trace logging

- localstack/aws/app.py
- localstack/aws/handlers/logging.py
- localstack/cli/localstack.py
- localstack/logging/setup.py
This PR fixes logging for the CLI. We were using a feature of python 3.8 for the runtime logging (the `force=True` flag of `basicConfig`) which was essential to the setup process, so i simplified the logging configuration for the CLI to make it work for python 3.7.
i also cleaned up a couple of things that were left over from #6424 
tested locally with pyenv and python 3.7 as well as 3.10
> fix logging for CLI

- localstack/logging/setup.py
This PR fixes a python 3.7 compat issue with the CLI that would raise a syntax error:
```
thomas@om /tmp/test37 % python -m localstack.cli.main --debug start --host
error importing entrypoint EntryPoint(name='login', value='localstack_ext.cli.localstack:LoginCliPlugin', group='localstack.plugins.cli'): cannot import name 'Literal' from 'typing' (/home/thomas/.pyenv/versions/3.7.13/lib/python3.7/typing.py)
error importing entrypoint EntryPoint(name='pro', value='localstack_ext.cli.localstack:ProCliPlugin', group='localstack.plugins.cli'): cannot import name 'Literal' from 'typing' (/home/thomas/.pyenv/versions/3.7.13/lib/python3.7/typing.py)
File "/home/thomas/.pyenv/versions/3.7.13/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", …
```
> fix python 3.7 compat of setup_hypercorn_logger for cli

- localstack/aws/protocol/parser.py
- tests/integration/s3/test_s3.py
- tests/unit/aws/protocol/test_parser.py
This PR fixes an issue with the ASF parser, where it didn't consider list-encoded types in header locations. See my comment in #6422, fix should be fairly self-explanatory.
I also added an integration test, but the feature is not implemented in moto yet, so cannot fix the issue right away.
We previously made the assumption that shapes with the location "header" are only ever primitive types. However, "ObjectAttributes" in "s3.GetObjectAttributes" is a list shape which has the location "header".
The header arrives as, e.g., `x-amz-object-attributes: ObjectSize,StorageClass`.
I briefly verified that it's the only one. Here's the list of all shape members with location "header" that are not strings:
```
appconfig CreateHostedConfigurationVersion LatestVersionNumber Integer integer
ebs …
```
> fix aws header list parsing

- README.md
- setup.cfg
Just some minor readme and setup.cfg changes:
* remove mention of python 3.6 as compatible (and remove dataclasses import) - python3.6 is EOL since Dec 2021.
* update copyright year
* update version in CLI example
> Remove python 3.6 compatibility mention from README, minor readme updates

- localstack/services/moto.py
- tests/integration/test_moto.py
- tests/unit/test_moto.py
This PR fixes an issue with the moto fallback dispatching of for operations which are not implemented.
Previously, the dispatcher raised Werkzeug's `NotFound` exception, which was interpreted as an internal error (resulting in a 500 error):
```
awslocal route53 update-traffic-policy-instance --id 123 --ttl 123 --traffic-policy-id 123 --traffic-policy-version 123
An error occurred (InternalError) when calling the UpdateTrafficPolicyInstance operation (reached max retries: 4): exception while calling route53.UpdateTrafficPolicyInstance: Traceback (most recent call last):
...
File ".../localstack/services/moto.py", line 142, in get_dispatcher
endpoint, _ = matcher.match(path_info=path)
File ".../.venv/lib/python3.10/site-packages/werkzeug/routing.py", line 2047, in match
raise NotFound() …
```
> fix moto fallback dispatching on 404 errors

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
This PR fixes #6327. There was an oopsie in the deduplication code, where we are not using the message dedup id that we calculated earlier. in the case described in the issue `message_deduplication_id` would be `None`, which is used as key.
> fix content based message deduplication with sqs fifo queues

- localstack/services/dynamodb/provider.py
- tests/integration/test_dynamodb.py
`fix_return_consumed_capacity` was added for issue #2049.
This seems to be the cause of issue #6437 and it doesn't solve the problem for issue #2049 from what I can tell.
If `ReturnValues` are not specified it always forces `ReturnConsumedCapacity` as `TOTAL`.
Steps to try reproduce #2049 without success:
```bash
awslocal dynamodb create-table \
--table-name "put-item-response" \
--billing-mode "PAY_PER_REQUEST" \
--attribute-definitions \
AttributeName=pkey,AttributeType=S \
--key-schema \
AttributeName=pkey,KeyType=HASH \
--region eu-west-1
awslocal dynamodb put-item \
--table-name "put-item-response" \
--item '{"pkey":{"S":"test"}}' \
--return-values "ALL_OLD"
awslocal dynamodb put-item \
--table-name "put-item-response" \
--item '{"pkey":{"S":"test"},"val":{"S":"foo"}}' \ …
```
> remove `fix_return_consumed_capacity`, fixes #6437

- .github/workflows/pro-integration.yml
- localstack/services/apigateway/integration.py
- tests/integration/test_apigateway.py
The authorizer event object is not prefixed with the authorizer type like it is for V2. This PR removes the integration prefix (authorizer-type) from the object.
> fix authorizer object for rest api

- localstack/services/route53resolver/models.py
- localstack/services/route53resolver/provider.py
- localstack/services/route53resolver/utils.py
- localstack/utils/aws/aws_stack.py
- tests/terraform/terraform-tests.yaml
- associate_firewall_rule_group
- disassociate_firewall_rule_group
- get_firewall_rule_group_association
- update_firewall_rule_group_association
- Isolated retrieval in models
- Added utils file
**TestAccRoute53ResolverFirewallRuleGroupAssociation**
(this test will be included in - `TestAccRoute53ResolverFirewallRuleGroup` for tf Pipeline)
- route53resolver:TestAccRoute53ResolverFirewallRuleGroupAssociation_basic
- route53resolver:TestAccRoute53ResolverFirewallRuleGroupAssociation_name
- route53resolver:TestAccRoute53ResolverFirewallRuleGroupAssociation_mutationProtection
- route53resolver:TestAccRoute53ResolverFirewallRuleGroupAssociation_priority
- route53resolver:TestAccRoute53ResolverFirewallRuleGroupAssociation_disappears
- …
> added support for route53resolver group association

- localstack/services/awslambda/lambda_executors.py
- localstack/utils/docker_utils.py
- tests/unit/test_lambda.py
1. Currently, since we use a regex replacement, the backslashes in Windows paths (as returned by docker for our mount detection - used for mounting the same paths into the lambda docker containers) will fail the method and therefore lambda execution.
2. A quick fix for #6458 - we currently use docker sdk if available, no matter the version installed
1. use regular string logic instead of regex to avoid escaping backslashes, added tests for path replacements for multiple formats / cases
2.  do not use docker sdk even if it is installed on the host - version mismatch have bad consequences (due to AWS sam often an older version of the docker sdk is installed, which will start pulling all tags instead of latest)
> Fix volume dir path replacement for windows paths, use docker cmd client if not in docker

- localstack/utils/files.py
Currently, we do not expand the path variable `%LOCALAPPDATA%`. Since we do not run the docker command in a shell, it does not take kindly to this path, and will essentially fail on windows.
This PR manually expands the path variable before setting the path into docker, and therefore solving the issue (as long as it is expandable, which I _hope_ is always the case on windows).
> Fix windows volume mount path for CLI localstack start

- localstack/utils/archives.py
- localstack/utils/testutil.py
This PR simply moves some zipping utilities into `localstack.utils.archives` (from `testutils`) for a two-fold reason: i) it is a better fitting module; ii) it avoids runtime imports from the CLI.
> Moving zip utilities

- localstack/testing/pytest/fixtures.py
Some AWS APIs only allow certificates from specific regions. See https://github.com/Miserlou/Zappa/issues/1945.
This change makes it possible to supply region name to the fixture to have a certificate created in that region.
> Changing ACM certificate fixture to handle regions as input parameters.

- localstack/cli/localstack.py
Fixes https://github.com/localstack/localstack/issues/5820
> fix: print conserved docker logs if container is not running

- localstack/aws/client.py
- localstack/aws/protocol/parser.py
- tests/unit/aws/protocol/test_parser.py
This PR addresses the handling of CBOR encoded messages.
It contains two fixes:
- ASF's  `BaseJSONRequestParser`: Proper binary decoding for CBOR (since the binary data is not base64 encoded).
- `botocore`: Adds support for basic CBOR decoding to `botocore` (which doesn't support CBOR at all).
- When using the botocore parser (in `client.py`) we configure the JSON parser to properly handle CBOR datetime and blobs.
Fixes #6492
> fix ASF / botocore CBOR decoding

- Dockerfile
- localstack/constants.py
- localstack/services/install.py
Upgrade JAR file versions in the Docker image to resolve some recent security vulnerabilities. Security scan results are taken from aquascan.com, which was used to analyze the Docker image.
* Introduce `update_jar_manifest(..)` util function that can be used to update the content of a MANIFEST file within a JAR archive (re-using the existing code we already had, but making it a bit more reusable)
* replace `jackson-databind-2.12.3.jar` -> `jackson-databind-2.13.3.jar`
* remove `maven` as one of the build steps in the `Dockerfile` - one of the CVEs reported is related to `/usr/share/maven/lib/maven-shared-utils-3.2.1.jar` in the image, and after the installation via `make init` is completed, it should technically no longer be required. (additionally, it saves us ~11MB …
> Upgrade JAR files to resolve some recent security vulnerabilities

- localstack/services/install.py
- setup.cfg
- tests/unit/test_lambda.py
Pin `quart` version to `0.17` to fix recent change in request context stack.
The `_*_ctx_stack` globals have been removed in `0.18` - see this commit for rationale/background: https://github.com/pallets/quart/commit/b2b614b336d99071a05a8525d4d0e18b9a1d66ec
Seems easy enough to pin the version for now, but we should also keep an eye on developments in flask (looks like `_request_ctx_stack` will be [removed there soon](https://github.com/pallets/flask/blob/cbebdae698272eeea2739988ccce54b1f14a1a67/src/flask/__init__.py#L64-L68) as well).
---
Update: Also pinning werkzeug to version `2.1.2` for now, as the latest released version `2.2.0` seems to have changed the logic of URL Map routing - our routes with `strict_slashes=False` in the Lambda API are now failing when sending a request with a …
> Pin quart and werkzeug versions to fix recent changes in req ctx stack, URL Map

- localstack/logging/setup.py
- pyproject.toml
Currently, due to the force deletion of all registered log handlers, we take the possibility of pytest to capture log entries. This behavior was introduced with #6424 .
Due to the -s selector in most circleci tests, this does not affect the community tests as much as the pro tests.
This PR fixes this behavior and adjusts the test logs to (almost) match our usual log.
> Fix pytest log capture for integration tests

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/patches.py
- localstack/services/cloudformation/models/apigateway.py
- localstack/testing/pytest/fixtures.py
- localstack/utils/aws/aws_stack.py
- tests/integration/apigateway_fixtures.py
- tests/integration/cloudformation/test_cloudformation_apigateway.py
- tests/integration/files/swagger.json
- tests/integration/files/swagger.yaml
- tests/integration/test_apigateway.py
- tests/integration/test_apigateway_integrations.py
Fix OpenAPI spec imports of REST APIs with base paths.
This surfaced while debugging a user issue, using a SAM template - if `basePath: /base` is defined in the template, then we were previously incorrectly performing a lookup of the absolute path within `paths`, whereas we should perform lookup with the relative path (stripping off the `basePath` prefix).
> Fix Swagger spec imports of REST APIs with base paths

- localstack/services/install.py
Skip upgrading JAR file if local version already matches.
In #6496 we introduced changes to upgrade some JAR files to the latest version (to fix security vulnerabilities). However, we're now re-downloading the JAR files on startup, even if the correct version already exists locally. With this PR, we check the local version, and then only selectively download libs if needed.
> Minor: Skip upgrading JAR file if local version already matches

- localstack/aws/client.py
- localstack/aws/protocol/serializer.py
- tests/unit/aws/protocol/test_serializer.py
- tests/unit/aws/test_client.py
The EC2 protocol is quite similar to the query protocol, but one difference is that the root element of error responses is a `Response` node:
```xml
<Response>
<Errors>
<Error>
<Code>InvalidInstanceID.Malformed</Code>
<Message>Invalid id: "1343124"</Message>
</Error>
</Errors>
<RequestID>12345</RequestID>
</Response>
```
This PR fixes a small issue concerning the EC2 protocol error serialization, where the `Errors` node was the root node.
In addition, it fixes a small issue with our client where the `Error` member of a parsed botocore response would be added to an ASF `ServiceException`.
Fixes #6528.
> fix EC2 ASF error serialization and botocore parsing

- localstack/services/ses/provider.py
A small change to log the time of SES message dispatch request.
This will be displayed on SES resource manager.
> Add timestamp to SES retrospection messages

- localstack/testing/pytest/snapshot.py
- localstack/testing/snapshots/prototype.py
- localstack/testing/snapshots/transformer.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/s3/test_s3.py
This PR enables snapshot-verify by default:
- tests that use the `snapshot` fixture will be verified
- these features were already available:
- test cases can be skipped by using the marker `pytest.mark.skip_snapshot_verify`
- test cases can be marked to skip certain json-pathes only, by using the `paths` argument, e.g. `pytest.mark.skip_snapshot_verify(paths=["$..EncodingType"])`
- added option to skip snapshot verification entirely by setting parameter `--snapshot-skip-all`
- fixed failing snapshot tests
- added flag `SNAPSHOT_DEBUG` to enable debug logs for transformation steps
> run tests with snapshot verify by default

- localstack/services/install.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_kinesis.py
This PR fixes a small bug in Kinesis, where a request to `CreateStream` would fail if the `shardCount` is not set (which should be optional).
It actually only contains an update of kinesis-mock to the new release (containing https://github.com/etspaceman/kinesis-mock/pull/339) and an integration test.
> fix Kinesis CreateStream without shardCount

- localstack/aws/protocol/parser.py
- localstack/aws/protocol/serializer.py
- localstack/services/s3/s3_listener.py
- tests/unit/aws/protocol/test_serializer.py
- 08f2ac0ddb9fe231d3e1f47fc1f0a5109e5b6c08 Removes unused methods in the parser (obsolete with #5827) and removes the "experimental" warning in the docs of the parser.
- ab7bb394b1b67b40982313b6d53057cef2ffc571:
- Removes the "experimental" warning in the docs on the serializer.
- Extracts the S3-specific handling to a specific subclass (since we already have service specific serializers).
- Fixes the structure of the S3 error responses (addresses parts of #6544).
- Adds a TODO to implement a feature to serialize non-modeled error members (f.e. `NoSuchBucket#BucketName` is not specified but sent by AWS and parsed by botocore).
> fix structure of S3 ASF serialized errors

- tests/integration/awslambda/test_lambda_api.py
- tests/integration/cloudformation/test_cloudformation_changesets.py
- tests/integration/cloudformation/test_cloudformation_logs.py
- tests/integration/cloudformation/test_cloudformation_logs.snapshot.json
* adds snapshot test (was discussed in detail during the workshop, including different approaches how to solve)
* updated comments for `test_basic_invoke` (also discussed during the workshop)
* removes `snapshot` fixture from a test that does not use it
> add snapshot examples

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
Fix a small bug where we would allow duplicates when tagging a SNS resource.
I stumbled onto another issue: when snapshot-matching the Exception raised by duplicated key, a `message` field would be added to the body of the response with Localstack, which is not present in AWS.
Example: 
```diff
"duplicate-key-error": {
"Error": {
"Type": "Sender",
"Code": "InvalidParameter",
"Message": "Invalid parameter: Duplicated keys are not allowed."
},
+       "message": "Invalid parameter: Duplicated keys are not allowed."
"ResponseMetadata": {
"HTTPHeaders": {},
"HTTPStatusCode": 400
}
}
```
The `message` field is not present in the recorded message. 
cc\ @alexrashed @thrau 
Sneaked a small change in a test concerning a fake ARN which would raise the wrong Exception in AWS. Validated more tests …
> fix sns duplicated tags + validate against AWS

- localstack/services/ssm/provider.py
- tests/integration/test_ssm.py
This PR marks the tests in `test_ssm.py` as `aws_validated`, and adds minor refactorings to achieve parity with the logic in real AWS. Addresses https://github.com/localstack/localstack/issues/6551
> Enhance parity for SSM logic and integration tests

- localstack/services/sqs/provider.py
- localstack/testing/pytest/snapshot.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
This PR adds tests for updating queue attributes, and server-side encryption attributes. I also removed a test that was not working against AWS and redundant, since it is covered implicitly by the QueryAPI tests. I also ran the entire test suite against AWS and marked the ones that worked.
> add sqs snapshot tests for queue attributes and SSE

- localstack/config.py
- localstack/services/awslambda/lambda_api.py
- localstack/utils/aws/aws_models.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/awslambda/test_lambda_api.py
- tests/integration/awslambda/test_lambda_size_lims.py
- tests/integration/awslambda/test_lambda_whitebox.py
- tests/unit/test_lambda.py
On some machines, lambda extraction might take significantly longer than 25s. Lambdas executed afterwards end up in an inconsistent state, where parts of the lambda code might be missing.
Nevertheless these functions have an "Active" state, which should not be the case.
The lambda states will - with this PR - correctly represent current internal state. During extraction, they will therefore be marked as "Pending", if the extraction fails for some reason, it will be set to "Failed", and once it completes, it will be set to "Active". A lambda not in "Active" state cannot be executed. This is on par with AWS behavior. For smaller lambdas, the "Active" state should be reached within a couple milliseconds. Problematic will be the "bigger" lambdas on macos bind mounts (see #6567), where the …
> Make lambda states reflect internal state

- localstack/aws/api/cloudwatch/__init__.py
- localstack/aws/api/ec2/__init__.py
- localstack/aws/api/kms/__init__.py
- localstack/aws/api/lambda_/__init__.py
- localstack/aws/protocol/serializer.py
- localstack/aws/scaffold.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_dynamodb.py
- tests/integration/test_sns.py
- tests/unit/aws/protocol/test_serializer.py
This PR addresses an issue with the error serialization mentioned in #6571.
After some digging, it turns out that there are several XML-services (`rest-xml`, `query`) which define default members in their error shapes (f.e. cloudfront, route53, cloudwatch, iam,...). These default members are _not_ added to the root node, while non-default members are.
For JSON-services (`json`, `rest-json`), there is no sub-element for the error metadata. All members are added to the root node. Here, defined default members in the spec can modify the casing (f.e. `Message` in DynamoDB's `TransactionCanceledException`).
The following changes are contained in this PR:
- Enhance the error serialization for error shapes which define additional members which "conflict" with the default error fields (like …
> fix error serialization for default error members

- localstack/services/logs/provider.py
This PR refactors the constructor of `LogsAwsApiListener` for easier subclassing (in pro).
> refactored LogsAwsApiListener for subclassing

- .circleci/config.yml
- localstack/aws/api/apigateway/__init__.py
- localstack/aws/api/config/__init__.py
- localstack/aws/api/es/__init__.py
- localstack/aws/api/lambda_/__init__.py
- localstack/aws/api/opensearch/__init__.py
- localstack/aws/handlers/metric_handler.py
- localstack/aws/protocol/parser.py
- localstack/aws/protocol/serializer.py
- localstack/aws/scaffold.py
- localstack/http/request.py
- localstack/http/response.py
- localstack/services/apigateway/provider.py
- localstack/services/awslambda/provider.py
- tests/integration/test_moto.py
- tests/unit/aws/protocol/test_parser.py
- tests/unit/aws/protocol/test_serializer.py
This PR updates ASF to correctly handle smithy [streaming](https://awslabs.github.io/smithy/1.0/spec/core/stream-traits.html) types. This is one of the last big changes to ASF, and will unblock the S3 migration.
The changes include:
* updated scaffold to generate streaming types (see details)
* re-generated community APIs
* updated serializer and parser to deal with streaming types
* added several tests on different layers
* update lambda and API gateway providers /cc @dfangl @dominikschubert
* changed the `MetricHandler` a bit (see details below) /cc @steffyP 
After several discussions with @alexrashed, we decided *not* to make the service-level shapes the streaming types, but to only type hint the members of request/response objects.
* For _Requests_, which are set by the server, we …
> add streaming types to ASF scaffold and APIs

- localstack/services/cloudformation/provider.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/cloudformation/test_cloudformation_stacks.py
- tests/integration/cloudformation/test_cloudformation_stacks.snapshot.json
Enhance parity for basic CloudFormation stack attributes. The starting point for this change was issue #3300 , which reported that the stack description is stored incorrectly (with invalid escaping of special characters). This has been fixed in the meantime and is no longer an issue with the ASF request parser. 👍 
Adding a snapshot test for this functionality revealed a few more gaps in the basic attributes we're storing for CloudFormation stack attributes. These gaps are addressed in the PR, and matched against the snapshot result accordingly.
> Enhance parity for basic CloudFormation stack attributes

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
This is a first PR to extend with complete snapshot validation of all AWS validated tests.
31/43 tests are AWS validated (1 more coming with snapshots)
10 are only Localstack (related to SMS and http endpoints)
1 is skipped
Some validation was added, especially concerning FIFO topics. The behaviour is not implemented (it differs a bit from SQS, and is managed at the topic level), there is no feature request for it yet. 
Added a `call_moto` call to the `unsubscribe` operation, it would make Moto not synced concerning subscriptions with our own backend
> refactor sns tests and fifo topic validations

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
This PR re-works the way message delaying works in the provider, and enables the calculation of `ApproximateNumberOfMessagesDelayed`
Previously we were simply spawning a timer for the delayed message that would put the message in the queue after the delay. I've introduced a structure that works analogously to the `inflight` messages for a queue, and re-purposed the `InflightUpdateWorker` to also queue all the delayed messages. I used the `Scheduler` utility for that to create a fixed-rate schedule for updating queues, that way the schedule doesn't drift if there are many messages in the inflight or delayed set and it takes longer to queue them
- fixes #6416
> rework SQS message delaying to calculate approximate number of messages delayed

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
This PR corrects the behavior of `change_visibility_timeout`, which previously had not the correct effect on `message.is_visible`, which we are calculating like this:
```python
if time.time() >= (self.last_received + self.visibility_timeout):
return True
```
So clearly updating only the `visibility_timeout` had no effect. We had to reset the entire visibility timer as defined by the AWS docs linked in the original issue.
**update**: i refactored the logic to use a dedicated `visibility_deadline` value that is calculated differently depending on whether the visibility timeout is updated or the message is received.
- Fixes #6454
> fix SQS ChangeVisibilityTimeout operation

- localstack/services/stores.py
Previously, resetting store bundles would leave empty store instances.
By using `clear()`, it leaves a cleaner states for persistence/cloudpods.
> Resetting store bundles must clear all keys

- localstack/services/secretsmanager/provider.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/secretsmanager/test_secretsmanager.py
- tests/integration/secretsmanager/test_secretsmanager.snapshot.json
Related to: https://github.com/localstack/localstack/issues/6530
- Updates the `SecretsManager`'s `CreateSecret` routine to raise an `InvalidRequestException` whenever a secret sharing its `SecretId` with another secret staged for deletion is received.
- Updates the arn tagging strategy to ensure creation of new secrets with past secret ids leads to new generation of new arn parts
Achieved by:
- carried out parity checks against AWS about this scenario
- added a patch to moto's SecretsManager backend, specifically to the `create_secret` function, now if condition is met this raises an `InvalidRequestException` with AWS message `AWS_INVALID_REQUEST_MESSAGE_CREATE_WITH_SCHEDULED_DELETION`
- added snapshot integration tests for the following scenario …
> [SecretsManager] Fixed raising of incorrect error message when creating a secret staged for deletion.

- localstack/services/cloudformation/models/kinesisfirehose.py
- localstack/services/firehose/provider.py
- localstack/testing/pytest/fixtures.py
- localstack/testing/pytest/snapshot.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/cloudformation/test_cloudformation_firehose.py
- tests/integration/cloudformation/test_cloudformation_firehose.snapshot.json
- tests/integration/templates/firehose_kinesis_as_source.yaml
- tests/integration/test_cloudformation.py
* return stream name for CFn Firehose stream Ref - addresses #6570
* add snapshot test for Firehose CFn test, move test to separate module inside `cloudformation` test package
* introduce `max_wait` parameter for stacks that take a long time to deploy in AWS (>60 secs)
* small fix around logic for `SNAPSHOT_UPDATE` (currently snapshots were not recorded if this env variable is not set)
> Return stream name for CFn Firehose stream Ref, add snapshot test

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
This PR corrects the behavior of `CreateQueue` to correctly raise `QueueAlreadyExists` exceptions when an attempt is made to create the queue with different attributes.
[According to the spec](https://github.com/boto/botocore/blob/f960a8d73c12d16b53e4d9eacdf515224acb08f6/botocore/data/sqs/2012-11-05/service-2.json#L1138), "Amazon SQS returns this error only if the request includes attributes whose values differ from those of the existing queue."
- fixes #5938
> fix create_queue to raise QueueAlreadyExists correctly

- localstack/cli/localstack.py
- tests/unit/cli/test_cli.py
removes the status command from the list of commands being logged
> remove publish_invocation decorator from localstack status commands

- localstack/services/awslambda/event_source_listeners/sqs_event_source_listener.py
- localstack/services/awslambda/lambda_executors.py
- localstack/testing/snapshots/transformer_utility.py
- localstack/utils/aws/dead_letter_queue.py
- localstack/utils/aws/message_forwarding.py
- tests/integration/awslambda/functions/lambda_sqs_integration.py
- tests/integration/awslambda/test_lambda_integration.py
- tests/integration/awslambda/test_lambda_sqs_integration.py
- tests/integration/awslambda/test_lambda_sqs_integration.snapshot.json
- tests/integration/test_sqs.py
This PR fixes how the SQS event source listener deals with DLQs and retry intervals.
There was some very old code left from #1973 that implemented logic that would, for SQS triggered lambdas, put messages into a DLQ manually. This logic is not needed since SQS puts messages into a DLQ automatically when it's being polled (which the event source listener does). I removed all of that code, since it is all handled implicitly in our SQS provider.
For testing I created two new tests that test the basic behavior (which replace the defunct test i removed), and retry with a DLQ (which was the original goal for #5283). The SQS event source mapping does not support `DestinationConfig`, meaning you can't make async lambdas triggered by SQS messages also send lambda results to SQS queues :shrug:. But …
> fix message retry in lambda SQS event source mapping

- localstack/testing/snapshots/prototype.py
- tests/integration/cloudformation/test_cloudformation_stacks.snapshot.json
- tests/integration/s3/test_s3_notifications_sns.snapshot.json
- tests/integration/test_sns.snapshot.json
- tests/unit/utils/testing/test_snapshots.py
Fix problem with reference-replacement for snapshots: match-object needs to be sorted to guarantee same outcome/replacement order (as tested/suggested by @bentsku).
> order input for snapshot-match to fix reference-replacement

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
This small PR fixes queue attribute validation for fifo queues when they get "created again" (=create_queue with the same attributes, including FifoQueue=true)
fixes #6620
> Fix fifo queue creation with attribute validation

- localstack/services/sns/provider.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/s3/test_s3_notifications_sns.py
- tests/integration/s3/test_s3_notifications_sns.snapshot.json
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
This PR adds the use of snapshots for every `aws_validated` test in the SNS test suite, following #6586
We skip some paths for now to be fixed in a later iteration. It is mostly fields not added (or added when it should not be) by Moto.
Also, it seems AWS doesn't add message signature for Fifo topics, so we will need to remove those fields. 
I added some exception messages fixes as well.
It contains a hacky fix that will be added in #6598 and will be removed then in order to guarantee the order of the fields.
> use snapshots for SNS tests

- localstack/testing/pytest/fixtures.py
- tests/integration/test_kms.py
KMS tests change:
- Adding a fixture for alias creation / cleanup.
- Adding a test to check that encrypt accepts all key representations: key ID, key ARN, alias, alias ARN.
Addresses https://github.com/localstack/localstack/issues/6471
> Adding a KMS test for encryption with different key formats.

- localstack/testing/snapshots/transformer.py
- tests/unit/utils/testing/test_snapshots.py
This PR fixes a problem with `KeyValueBasedTransformer`:
If `replace_reference` was set to False, it would replace the entire key.
Fix:
* now it replaces the returned value only (which can be a subset of the value), with the `replacement` string
* behaves similar to `replace_reference=True`
> fix KeyValueBasedTransformer

- localstack/services/awslambda/lambda_api.py
Addresses #6464
When using only community code, but setting the package type to image (which should work until it comes to invocation), the "Layer" key is not available in the "Configuration" dict, when running get-function.
This leads to a 500 error when running get-function.
This PR fixes this by using `pop` instead of `del`, which will not error on missing Keys.
> fix error in deleting lambda configuration keys

- localstack/services/install.py
Removed the databind patch for `databind-2.12.3.jar`:
* it was replaced with `databind-2.13.3.jar` to fix a known CVE
* latest `DynamoDBLocal` includes `jackson-databind-2.12.6.1.jar`
> removed databind patch for dynamodb

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
Even though DelaySeconds is not valid for fifo queues in a send_message operation, sending it with the value 0 is allowed.
fixes #6612
> fix delay seconds=0 for fifo queues

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
This PR fixes the scenario where we would delete an SNS subscription (we would actually only delete the logic/publish part but not the resource in moto, which could be listed) when its SQS endpoint was deleted. It would send a message to the DLQ once if configured then delete the subscription.
AWS does not do this, it keeps the subscription and you can even set a RedrivePolicy afterwards.
I wrote a new AWS validated and snapshotted test to validate the behaviour.
There was an old PR fixing this #6160, which had a lot of merge conflicts from all the changes since.
_fixes #5459_
> fix SNS subscription deleted when SQS endpoint was deleted

- localstack/services/stepfunctions/provider.py
- tests/integration/test_stepfunctions.py
Should address #6486. 
Passing an empty dictionary as `loggingConfiguration`, while being a valid AWS request, as shown in the ticker messes up with persistence. This PR adds the default configuration as the real AWS.
> Add default logging configuration for state machine

- localstack/testing/pytest/snapshot.py
- localstack/testing/snapshots/prototype.py
- localstack/testing/snapshots/report.py
Produces diff results that are a bit more readable and (if used with a proper terminal) prettier due to custom coloring.
/cc @steffyP
> Introduce colored output format for snapshot diffs in integration tests

- localstack/services/sns/provider.py
- localstack/utils/aws/dead_letter_queue.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
Fix #6639
This was discovered by accident while augmenting the snapshots, adding more attributes to the response before fixing another bug.
The format was wrong, we would add and even override `MessagesAttributes` with error coded one when AWS doesn't do it. The code to check if we send the attributes is a bit messy, there are check all over the place and the provider will need a good clean up/refactor.
> fix SNS msg attrs when sending to SQS DLQ

- .circleci/config.yml
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/cloudformation/test_cloudformation_stacks.py
Fix resolving CloudFormation intrinsic functions passed as list rather than dict.
This has surfaced when resolving a user issue using a CFn template that used an `ImportValue` with a slightly different format (which looks a bit odd, but works against AWS):
```
EventSourceArn: !ImportValue 
'Fn::Sub': ${Environment}-${Product}-ExportTaskQueueArn
```
Validated the behavior against AWS, added a test using a stack import that references an exported value from another stack.
> Fix resolving CFn intrinsic functions passed as list rather than dict

- localstack/services/dynamodb/utils.py
- tests/integration/test_dynamodb.py
This PR addresses #6290 and adds an integration test.
Sneak peek: in an upcoming PR I am embedding `dynamodb_wait_for_table_active` into the creation fixture (and validating many DynamoDB tests).
> Fixing BatchWriteItem with key element not matching the schema

- localstack/testing/pytest/fixtures.py
- tests/integration/test_dynamodb.py
This PR:
- embed the fixture used to wait for a table to be active into the fixtures we use to create DynamoDB tables; this unlocks the possibility of starting verifying DynamoDB tests against AWS;
- started verifying a bunch of integration tests against AWS (the easiest ones, for the moment; a second bunch will come);
Generally, for DynamoDB we have three different ways to create resources, i.e., tables, that we might think of standardizing.
- `dynamodb_create_table_with_parameters` fixture, where we simply pass a dictionary of parameters and create the table with the client's API;
- `dynamodb_create_table` fixture, with similar behavior to the one above but it then actually calls the `create_dynamodb_table` in `aws_stack.py`;
- via …
> Validate a bunch of DynamoDB tests against AWS

- tests/integration/awslambda/functions/lambda_sqs_integration.py
It seems [sometimes in CI](https://app.circleci.com/pipelines/github/localstack/localstack/8346/workflows/c7238f0e-0026-4870-8558-4046b08460b0/jobs/52075), not sure why, the region is not resolved correctly anymore, and the log is full of `You must specify a region` errors. Maybe some test side effects?
For the PR in question, I had originally added using a fallback region, but then removed it. [Here's the discussion](https://github.com/localstack/localstack/pull/6603#discussion_r940465391). So re-adding this fallback code now.
See an excerpt here:
```
tests/integration/awslambda/test_lambda_sqs_integration.py::test_redrive_policy_with_failing_lambda 
-------------------------------- live log call ---------------------------------
2022-08-13T14:44:07.040  INFO --- [   asgi_gw_0] …
```
> fix lambda_sqs_integration region resolution to avoid CI failures

- localstack/aws/protocol/service_router.py
- localstack/aws/spec.py
- tests/unit/aws/test_service_router.py
- tests/unit/aws/test_spec.py
This PR adds caching of the indexes created in the `ServiceCatalog`.
The `ServiceCatalog` is what powers the `ServiceNameParser` by providing indexes that allow fast lookup of service indicators to services (e.g., finding the service by its signing name or endpoint prefix). Creating the indexes involves loading all 300-something services, and iterating over all 11k-something operations. This takes around 1500 ms on my machine. This happens the first time an HTTP call is made that triggers the `ServiceNameParser`, making the first call take at least 1500ms.
@alexrashed raised some concerns in the past about shipping an index pre-built with the distribution, which was a valid point since that would involve an error-prone build step. So instead I opportunistically create the cache and store …
> add caching for service catalog indexes

- localstack/testing/snapshots/report.py
Previously just printed `{value}` but now does `{value!r}` which is equivalent to `{repr(value)}`.
This means we'll now properly see newlines etc. in strings and we can easier differentiate if something is an integer or a string.
> Use repr conversion when printing values in diff report

- tests/terraform/terraform-tests.yaml
This PR disables two Terraform S3 tests which seem to be flaky in order to stabilize the pipeline.
Here's an analysis of the last few runs:
- `TestAccS3BucketLogging_disappears`
- https://github.com/localstack/localstack/runs/7854756690?check_suite_focus=true
- https://github.com/localstack/localstack/runs/7845176146?check_suite_focus=true
- https://github.com/localstack/localstack/runs/7841962855?check_suite_focus=true
- https://github.com/localstack/localstack/runs/7810519201?check_suite_focus=true
- `TestAccS3BucketLogging_update`
- https://github.com/localstack/localstack/runs/7854756690?check_suite_focus=true
- https://github.com/localstack/localstack/runs/7851919499?check_suite_focus=true
- https://github.com/localstack/localstack/runs/7836059918?check_suite_focus=true
- …
> fix pipeline by disabling flaky TF S3 tests

- localstack/services/cloudformation/deployment_utils.py
- localstack/services/sqs/provider.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/cloudformation/test_cloudformation_engine.py
- tests/integration/cloudformation/test_cloudformation_engine.snapshot.json
Adds a more generalized way to cast parameter values (even nested now) when the first SDK call failed due to invalid parameter types.
Also found minor parity issues for FIFO queue default values along the way. /cc @baermat 
Fixes #5671
> Generalize parameter conversion fallback for SDK calls in CloudFormation

- .circleci/config.yml
Fix for the failing `metric_aggregator` script in the `report` step of CircleCI.
Running the script as module seems to work fine and makes PR https://github.com/localstack/localstack/pull/6680 obsolete.
> fix failing circle-ci step

- scripts/capture_notimplemented_responses.py
- scripts/coverage_docs_utility.py
This PR fixes two small issues in the parity coverage scripts:
- Add the newly added "FIS" service to the list of services
- Avoid assuming that a service exists in the coverage docs utils
> fix parity coverage scripts (add FIS, allow non-indexed services)

- localstack/services/awslambda/event_source_listeners/sqs_event_source_listener.py
- localstack/services/awslambda/lambda_api.py
- tests/integration/awslambda/functions/lambda_sqs_batch_item_failure.py
- tests/integration/awslambda/test_lambda_sqs_integration.py
- tests/integration/awslambda/test_lambda_sqs_integration.snapshot.json
This PR adds support for reporting batch item failures](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#services-sqs-batchfailurereporting) when using Lambda SQS event source mappings.
* Lambda changes: just for the API to accept and store the `FunctionResponseTypes` attribute
* `sqs_event_source_listener.py`: Just needed to add a control path for when `ReportBatchItemFailures` is set, in which the listener interprets the lambda `batchItemFailures` result according to the spec (see the "Success and failure conditions" in the docs I linked), and calls sqs delete batch with only the messages that should be deleted according to the result.
* Tests: The most complicated part of this PR are i think the tests, which also introduce a new lambda that can be configured to return …
> add support for ReportBatchItemFailures in Lambda SQS event source mappings 

- localstack/services/kms/provider.py
- tests/integration/test_kms.py
Addresses https://github.com/localstack/localstack/issues/6605
Currently GetPublicKey succeeds for KeyUsage=SIGN_VERIFY keys, but not for ENCRYPT_DECRYPT asymmetric ones, as
1) moto doesn't have GetPublicKey implemented;
2) we allow moto to deal with ENCRYPT_DECRYPT keys, not storing them ourselves.
This PR makes LocalStack save all keys apart from KeyUsage=ENCRYPT_DECRYPT  + KeySpec=SYMMETRIC_DEFAULT, which makes it possible for GetPublicKey to fetch those keys. We do not store ENCRYPT_DECRYPT  + SYMMETRIC_DEFAULT symmetric keys, as I still have to look into how they are supposed to be handled. But GetPublicKey  in AWS doesn't work for such keys either way.
> Making it possible for KMS GetPublicKey to get ENCRYPT_DECRYPT keys.

- localstack/services/cloudformation/provider.py
- localstack/testing/pytest/fixtures.py
- localstack/testing/snapshots/transformer_utility.py
- localstack/utils/cloudformation/template_deployer.py
- localstack/utils/cloudformation/template_preparer.py
- tests/integration/cloudformation/test_cloudformation_cdk.py
- tests/integration/cloudformation/test_cloudformation_changesets.py
- tests/integration/cloudformation/test_cloudformation_changesets.snapshot.json
- tests/integration/cloudformation/test_cloudformation_stacks.py
- tests/integration/cloudformation/test_cloudformation_stacks.snapshot.json
- tests/integration/templates/cdkmetadata.yaml
- tests/integration/templates/sns_topic_template.json
- tests/integration/templates/sns_topic_template.yaml
Previously  there was some weird behavior in CDK:
1. Deploy Stack A (new) => success
2. Deploy Stack A (no changes) => success (but still created a change set)
3. Deploy Stack A (no changes) => fail (resource not found)
4. go to 3
We didn't save the "raw" template string when creating a stack and therefore returned invalid data in `GetTemplate`. This is important because CDK uses it to compare the new template against and if they match, it won't even try to create a change set (by default, can be disabled with `deploy --force`)
> Fix CloudFormation GetTemplate response and multiple cdk deployments

- localstack/cli/localstack.py
this PR modifies the localstack CLI command to correctly set the `config.CONFIG_PROFILE` value to whatever is passed to `--profile`. previously we would only set the environment variable, but the config was already loaded before the env var was set.
> set CONFIG_PROFILE correctly into config variable with localstack CLI

- localstack/services/awslambda/lambda_api.py
- tests/integration/awslambda/test_lambda.py
Fixes a small issue where the function URL was returned as `http://<...>:{EDGE_PORT}` but since PRO by default sets the EDGE_PORT to 443, this lead to the tests misbehaving.
Still need to add HTTPS support for this at a later point but this should at least unblock the PRO tests in CI.
> Fix Lambda URL building

- localstack/services/sns/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_sns.py
This PR addresses issue #5602. Allows the SNS to deliver messages to Firehose subscriptions.
Must be merged after spulec/moto#5303 has been integrated. If it takes too long I guess I'll merge it into the Moto-ext fork.
> Feature: SNS msg delivery to Firehose endpoint

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
This PR fixes #6657
We only checked `ContentBasedDeduplication` settings in our tests for `publish_batch`.
We would not pass the `MessageDeduplicationId` to the SQS queue, thus launching this exception:
```python
2022-08-12T14:00:05.973  INFO --- [   asgi_gw_1] localstack.services.sns.provider : Unable to forward SNS message to SQS: An error occurred (InvalidParameterValue) when calling the SendMessage operation (reached max retries: 0): The Queue should either have ContentBasedDeduplication enabled or MessageDeduplicationId provided explicitly  Traceback (most recent call last):
File "/Users/benjaminsimon/Projects/localstack/localstack/localstack/services/sns/provider.py", line 984, in message_to_subscriber
sqs_client.send_message(
File …
```
> fix SNS publish_batch passing MessageDeduplicationId to SQS queue

- .github/workflows/cla.yml
Update CLA Github action to not lock PRs after merge. Currently, the default setting for the CLA bot is to lock threads after PRs are merged - meaning that it is not possible to interact with the PR in any way - no comments, no follow-up questions, no emoji upvotes! ;) , etc.
The main motivation for having `lock-pullrequest-aftermerge` as `true` by default is the following:
> It is highly recommended to lock the Pull Request after merging so that the Contributors won't be able to revoke their signature comments after merge
This should not be an issue, as we still have the paper trail of signatures in the `cla-signatures` branch. The benefit of being able to interact on PRs after merge arguably outweighs the potential risk of contributors revoking their signature (which I don't think is a …
> Update CLA Github action to not lock PR threads after merge

- localstack/services/sqs/provider.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
This PR corrects the way the `SequenceNumber` is generated and passed through to API call results. We now generate the sequence number once, and keep it in the message. I had to change the internal API to make `put` actually return the `SqsMessage` object which holds the sequence number, since we return the sequence number both in `SendMessage` and `ReceiveMessage`.
The sequence numbers are 20 digit numbers that are non-consecutive, but monotonically increasing. Other than that there seem to be no guarantees associated with the sequence numbers. So I simply used the unix timestamp (which is 10 digits, at least for the next 264 years), shifted it to be 20 digits, and then use that number as a basis.
I also refactored an unrelated test to use snapshot testing.
- Fixes #6674
> fix sqs fifo message sequence number generation

- localstack/config.py
- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
This PR fixes the SQS purge_queue operation.
* correctly delete inflight and delayed messages (as AWS does)
* I also added a feature flag `SQS_DELAY_PURGE_RETRY` to enable the behavior to raise `PurgeInProgress` errors within a 60 second internval, which is how AWS managed purge queue.
- Related to #6695
> fix sqs purge queue operation to match AWS behavior

- pyproject.toml
Remvoes localstack.extensions.api, which is just a set of import statements, from the coverage metrics. Extensions will be tested as part of pro
> remove extensions api from coverage collection

- localstack/services/dynamodb/provider.py
This PR improves the performance of dynamodb put_item, update_item, and delete_item operations. By removing the service request parameter to forward_request, the proxy avoids creating a new request context, which is a relatively expensive operation (it has to create a completely new HTTP request from the service request). It does not look like the request dictionaries are modified in any way before passing them to the dynamodb backend. So this looks safe.
related to #1205
> improve performance of dynamodb forward_request operations

- localstack/services/firehose/provider.py
- tests/integration/test_firehose.py
- tests/integration/test_iam.py
- tests/integration/test_integration.py
- tests/integration/test_kinesis.py
Currently, even if we delete the firehose delivery stream, we will not stop the kinesis listener (if kinesis is the source). This leads to a significant resource leak, while at the same time spamming our logs with `dynamodb.Scan` entries (see in [this circleci log](https://app.circleci.com/pipelines/github/localstack/localstack/8606/workflows/b1146cff-6a7d-48bc-b56b-da51547008ea/jobs/53885/parallel-runs/1?filterBy=ALL) for example):
```
2022-08-23T09:42:39.485  INFO --- [  asgi_gw_12] localstack.request.aws     : AWS dynamodb.Scan => 200
2022-08-23T09:42:39.528  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS dynamodb.Scan => 200
2022-08-23T09:42:39.530  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.Scan => 200
2022-08-23T09:42:39.532  INFO --- [  asgi_gw_13] …
```
> Correctly shutdown kinesis listener once firehose deliverystream is deleted

- localstack/services/apigateway/integration.py
- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/patches.py
- localstack/services/apigateway/provider.py
- tests/integration/apigateway_fixtures.py
- tests/integration/awslambda/functions/lambda_aws_proxy.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/test_apigateway.py
- tests/integration/test_apigateway_api.py
Adds more parity validations and fixes the AWS lambda integration invocation
* Fixes API responses status codes
* Separates AWS from AWS_TYPE lambda integration.
Fixes https://github.com/localstack/localstack/issues/6462
> fix apigateway aws lambda integration invocation

- localstack/services/ses/provider.py
- tests/integration/test_ses.py
Fixes an issue where raw emails were unfilterable from the retro endpoint. This was because the email source address was not being saved.
PR updates integration tests
Closes: https://github.com/localstack/localstack/issues/6725
> SES: Extract and save the source address for raw email messages

- localstack/services/opensearch/cluster.py
- localstack/services/opensearch/cluster_manager.py
- localstack/services/opensearch/provider.py
- tests/integration/test_opensearch.py
When running LocalStack (and therefore OpenSearch/Elasticsearch) in Docker, the search clusters were still bound to localhost in the container when using the port strategy. This caused them to be unreachable. This PR fixes that by addressing #6419
> Fix OpenSearch port strategy when running inside Docker

- .gitignore
- localstack/services/stores.py
- tests/unit/test_stores.py
Extend valid regions for Stores to include extended AWS partitions. Currently, store creation fails when creating them for a region within one of the extended AWS partitions, e.g., `us-gov-west-1`
> Extend valid regions for Stores to include extended AWS partitions

- localstack/aws/scaffold.py
- tests/unit/aws/test_scaffold.py
AWS just recently introduced some changes to the AWS Glue API which introduces a type called `Union` in the service specification. The scaffold didn't properly escape the keyword yet, which caused issues with our code generation (since it wouldn't pass our linting rules):
```
. .venv/bin/activate; python -m pflake8 --show-source
aws/api/glue/__init__.py:1[8]10:1: F811 redefinition of unused 'Union' from line 3
class Union(TypedDict, total=False):
^
```
This PR adds `Union` to the list of reserved keywords (which causes the scaffold to escape the type name with a trailing underscore: `Union_`).
In addition, I added a small fix to deactivate logging in the scaffold unit tests due to issues with stdout logs and Click in pytest.
> fix scaffold by handling Union as special keyword

- localstack/services/apigateway/integration.py
- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/templates.py
- tests/unit/test_apigateway.py
- tests/unit/test_templating.py
The support for stepfunctions integration currently is only supported for REST APIs. This PR wraps the logic related to invoking stepfunctions into a class that can be re-used by HTTP and Websockets API.
AWS` Services are also invoked using [integration subtypes](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-aws-services-reference.html). This PR enumerates those subtypes and will dispatch actions to the existing integrations.
> Add support stepfunctions integration

- .github/workflows/asf-updates.yml
- CODEOWNERS
This PR updates the `CODEOWNERS` file:
- Orders the service owners alphabetically.
- Adds missing service sections which have an owner (ACM / @alexrashed, Api Gateway / @calvernaz, Logs / @steffyP, Route53 / @giograno).
- Changed codeowner of IAM from @dominikschubert to @dfangl.
- Changed codeowner of CloudWatch from @silv-io to @steffyP.
- Adds the cloudformation models to some of the sections.
- Adds the generated API code (`localstack.aws.api.<service>`) to each section (i.e. codeowners will be added to ASF Update PRs automatically if anything changes for their service).
I changed this proactively once I realized that some parts are outdated. Please let me know if any of the sections should be set differently (as a comment or in a DM).
In addition, I added myself as a default reviewer …
> update CODEOWNERS, set default reviewer for ASF Update PRs

- localstack/services/iam/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/templates/statemachine_test.json
- tests/integration/test_cloudformation.py
- tests/integration/test_iam.py
- tests/integration/test_iam.snapshot.json
Addresses #6644
* fix IAM policy validation - we were adding a `["*"]` default value for `Resource` in the past (apparently to fix Serverless CFn deployments), which should be no longer required
* fix role `MaxSessionDuration` (set to 3600 by default in moto), which is not how AWS is behaving (i.g., AWS is not returning `MaxSessionDuration` for a role if it hasn't been specified)
* add snapshot test for `update_assume_role_policy`
* remove obsolete patch for `get_user` to include tags, which is fixed upstream in the meantime
* small fix for `test_cfn_statemachine_with_dependencies` with issues detected as part of parity-testing these changes
> Fix IAM policy validation and MaxSessionDuration of roles, remove obsolete patches

- localstack/aws/app.py
- localstack/aws/handlers/__init__.py
- localstack/aws/handlers/service.py
- localstack/services/dynamodb/provider.py
- localstack/services/dynamodb/utils.py
- localstack/services/providers.py
This PR
* adds service-specific response handlers that allow services to modify responses *before* it is parsed. this is useful for cases when you want a catch-all modification of responses as they are returned by a backend
* refactors the DynamoDBApiListener to make use of the new construct
* removes the obsolete "update table definitions" code (already handled in `create_table`, and it's the only operation that the if condition matches, i double checked against the specs)
ext should work, but needs to be refactored once this is merged to also remove the custom AwsApiListener
- part of #6668
> add service-specific response handler for dynamodb

- localstack/testing/pytest/snapshot.py
Minor fix for a bug that occurs when there are multiple `@pytest.mark.skip_snapshot_verify(condition=...)` markers.
If there's one where `condition` evaluates to True and it doesn't include a `paths` key, the affected snapshots should be skipped entirely, no matter in what order the marks are evaluated. Previously the paths were still added to the list and thus, not everything was skipped.
> A valid skip condition without paths should skip the whole snapshot

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
This PR fixes an issue that was introduced by the SQS patches from ext related to merging of SQS queues.
The issue was that `self.visible` was overwritten by the patch, while the attribute getter of `ApproximateNumberOfMessages` was set to `self.visible._qsize` (the function reference) _before_ `self.visible` was overwritten, causing `ApproximateNumberOfMessages` to always be 0 since it was referencing the old queue. The fix was to make a lambda out of it so we always resolve the current `self.visible`, allowing a later overwrite.
The PR also adds a `timeout` argument to the `poll_condition` calls in the SQS tests to avoid the build pipeline to block until the timeout.
> fix ext compatibility for mergable sqs queue

- localstack/services/s3/s3_listener.py
- localstack/testing/pytest/fixtures.py
- tests/integration/s3/test_s3_notifications_eventbridge.py
- tests/integration/s3/test_s3_notifications_eventbridge.snapshot.json
This PR addresses issue #5994. With these changes, the S3 Notifications can be send to the EventBridgeService.
> Add support for S3 notifications to EventBridge

- bin/docker-entrypoint.sh
- bin/localstack-start-docker-dev.sh
- localstack/config.py
- localstack/runtime/hooks.py
- localstack/runtime/init.py
- localstack/services/infra.py
- localstack/services/internal.py
- tests/integration/services/test_internal.py
- tests/unit/runtime/test_init.py
This PR adds pluggable initialization hooks to customize localstack with both shell and python scripts that are mounted into `/etc/localstack/init/<phase>.d`. It replaces the current `/docker-entrypoint-initaws.d`.
Currently the only way to run custom code to initialize localstack is `docker-entrypoint-initaws.d`. There are a surprising number of [issues mentioning it](https://github.com/localstack/localstack/issues?q=is%3Aissue+docker-entrypoint-initaws.d). To me this was conceptually disconnected from our lifecycle phases that we have in hooks, and this seemed to be an opportunity to improve the UX and to generalize the extensibility of localstack's lifecycle phases.
There are four lifecycle phases that one can hook into: `BOOT`, `START`, `READY`, `SHUTDOWN`. Each lifecycle phase has …
> add new pluggable initialization hooks

- localstack/services/kinesis/kinesis_listener.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/test_kinesis.py
- tests/integration/test_kinesis.snapshot.json
Fixes an issue where a SubscribeToShard is cut too early - now set to 5min. 
Additionally added aws validated test marks and a basic kinesis stream tags test.
test_subscribe_to_shard_timeout
Fixes: #5830
> Kinesis: SubscribeToShard session cut after 5min

- localstack/testing/pytest/fixtures.py
- tests/integration/apigateway_fixtures.py
- tests/integration/conftest.py
- tests/integration/test_apigateway.py
- tests/integration/test_apigateway_integrations.py
This PR adds a fixture for the REST API gateway that cleans up after creation. This will enable more tests that do AWS parity checks without leaving traces.
> improve fixtures

- .dockerignore
- Dockerfile
- Makefile
- localstack/services/install.py
This PR is the first step of the bigger installer refactoring. It changes the following
- Get rid of make init on the host: This is a major pain point and blocker because it pulls and runs a container image via docker, and therefore needs to be removed for any work to be continued. 
The make init command on the host is essentially a convenient but inefficient way to get to the necessary JAR files of a specific version we need for the stepfuntions implementation. They are necessary because we need a pinned version, which AWS does not provide.
This PR should not impact any actual customer facing localstack functionality. It only changes how the necessary JAR files are fetched: we now download the necessary stepfunctions jars from the specific **_layer_** from the wanted image without …
> refactor stepfunctions installer

- localstack/services/cloudformation/models/cdk.py
- localstack/services/cloudformation/models/ec2.py
- localstack/services/cloudformation/provider.py
- localstack/utils/cloudformation/template_deployer.py
- tests/integration/cloudformation/test_cloudformation_stacks.py
- tests/integration/cloudformation/test_cloudformation_stacks.snapshot.json
- tests/integration/templates/template36.yaml
- tests/integration/test_cloudformation.py
Add parity tests and add a number of smaller fixes in the logic for CloudFormation stack resource updates. Addresses #6155
The main issue with the sample shared by the user is that SAM deployment was hanging, as the stack/resource status was incorrectly reported as `CREATE_COMPLETE` instead of `UPDATE_COMPLETE`. This led to the discovery of a few more issues, which are now fixed, and covered by parity tests.
* properly set the status of stack resources as `CREATE_COMPLETE` or `UPDATE_COMPLETE`, depending on the operation and prior existence of resources within the stack
* add a parity/snapshot test for the point above (which is essentially what caused SAM/`samlocal` to hang when deploying the sample in #6155)
* ensure that `Parameter` instances are not being returned …
> Add parity tests and refactor logic for CFn stack resource updates

- localstack/aws/api/kinesis/__init__.py
- localstack/aws/forwarder.py
- localstack/aws/handlers/service.py
- localstack/aws/protocol/serializer.py
- localstack/aws/skeleton.py
- localstack/config.py
- localstack/constants.py
- localstack/services/kinesis/kinesis_starter.py
- localstack/services/kinesis/provider.py
- localstack/services/logs/provider.py
- localstack/services/moto.py
- localstack/services/providers.py
- localstack/services/sqs/query_api.py
- localstack/services/stepfunctions/provider.py
- localstack/services/sts/provider.py
- tests/integration/apigateway_fixtures.py
- tests/integration/test_apigateway.py
- tests/integration/test_apigateway_api.py
- tests/integration/test_kinesis.py
- tests/integration/test_moto.py
- tests/integration/test_s3control.py
- tests/unit/aws/handlers/service.py
- tests/unit/aws/protocol/test_serializer.py
This PR migrates Kinesis to ASF. It uses the new streaming support in ASF introduced with https://github.com/localstack/localstack/pull/6086 for `SubscribeToShard`.
In addition, the ASF infrastructure needed to be enhanced with a limited support for HTTP Content-Negotiation in some serializers. For example, the JSON protocols can switch their content to CBOR if requested in the client's request.
Since we now implement _more_ features than botocore's or moto's marshalling, this PR also needed to change the proxy handling to moto and other HTTP backends.
Now, all responses which have been forwarded to moto or any other backend using the fallback mechanism (i.e. the backend implements a specific ASF operation / API) are parsed (using botocore's parsers) and re-serialized (using our - …
> migrate Kinesis to ASF

- localstack/aws/forwarder.py
- localstack/aws/protocol/serializer.py
- localstack/logging/setup.py
- tests/integration/test_kinesis.py
In comparison to the typical JSON datetime format for AWS services (`unixtimestamp`, i.e. the float representation of the current unix timestamp seconds), for CBOR the `unixtimestampmillis` (basically the int representation of `unixtimestamp * 1000`) format is used.
- bdd1af3a0b691fc36695b3b40da2bc54f3fc414d: Fixes the CBOR datetime encoding.
- 4b16c7cbe8009f0f92a654baa3431b4cf7847ce8: Fixes an issue with the forwarding of invalid requests. It disables the validation in the botoclient when creating the request which will be forwarded (because the backend should take care of the request parameter validation).
- 3c0d807443bb07e9bfb8190fdb6258154aa1cb1f: Changes the loglevel of the serializer `DEBUG` logs to `TRACE` (since these are a bit verbose, but …
> fix CBOR datetime encoding

- localstack/aws/forwarder.py
- localstack/services/dynamodb/models.py
- localstack/services/dynamodb/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_dynamodb.py
This PR introduces initial support for DynamoDB global tables version 2019.
We simulate replicas as follows:
- We store information about the replicas in a cross-region attribute; this step is done when the user updates a table. The region for this call is going to the "original region" where the table effectively lives. De-facto, we have created a global table with this step.
- We can now call operations (only `PutItem` and `GetItem` at the moment) on the created global table from other regions. Before forwarding the call to DDB local, we inspect our cross-region attribute to see if this is a global table and if in the current regions there is a valid replica. If so, we change the context of the call and the credentials in the header to perform a call against the original region (where …
> POC of global tables version 2019

- localstack/aws/protocol/service_router.py
- tests/integration/test_security.py
Currently, our service parser interprets internal routes, such as `/health` and `/_localstack/...` as s3 service, which leads to an exemption from cors processing. This leads to localstack not allowing cors requests to /health or internal localstack domains.
```
curl https://localhost.localstack.cloud:4566/health -H "Origin: https://app.localstack.cloud" -v                                        <aws:AWS-daniel>
*   Trying 127.0.0.1:4566...
* Connected to localhost.localstack.cloud (127.0.0.1) port 4566 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS …
```
> fix service detection for internal service routes

- Dockerfile
Bump Node.js binary to version 18. This addresses a few security vulnerabilities (CVEs) that have been reported by scanners like Aquasec/[Trivy](https://github.com/aquasecurity/trivy), or the Docker built-in scanner by Snyk (incl     CVE-2022-32213, CVE-2022-32214, CVE-2022-32215). Current LTS version is v16, but versions 14/16/17 were unfortunately all exposing these CVEs in the scan results, hence the easiest is for us to go with the latest version, 18.
The main impact of this will be on the local Lambda executor mode (`LAMBDA_EXECUTOR=local`) - specifically, if users are depending on [Node.js APIs that have been deprecated](https://nodejs.org/api/deprecations.html) . Still planning to prepare a small docs PR to highlight this point to our customers - also, with the new Lambda provider, …
> Bump Node.js binary to version 18

- .circleci/config.yml
- localstack/services/awslambda/lambda_utils.py
- localstack/services/install.py
- tests/bootstrap/test_cli.py
- tests/integration/test_apigateway.py
Fix idempotence of DynamoDB/StepFunctions installer logic to ensure running as non-root. First step towards addressing #5396
Currently, there are a few issues (i.e., false positives) with the way how we're determining whether to replace the content of certain JAR manifest files. This results in issues when attempting to run the Docker container as a non-root user, as we're trying to overwrite the files owned by `root`.
(This will also require a small change in the upstream repo in -ext.)
Tested the changes manually/locally so far - also added a test skeleton / `TODO` for a CLI test that we can add in a follow-up PR, once the `latest` Docker image has been built and published with the latest changes. 👍 
---
Update: After consulting with @alexrashed , we can add a test already now that …
> Fix idempotence of DDB/SFN installer logic to enable running as non-root

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
This PR fixes #6784 
We did not check when calling `publish_batch` if the topic was valid or existing. Added the check + AWS validated test
> SNS - fix publish_batch to invalid topic

- .github/workflows/cli-tests.yml
- tests/bootstrap/test_cli.py
Remove xfail flag for test to run container as non-root. Follow-up / cleanup for PR #6785
Note: Had to add a `chmod` command to enable open permissions for the host directory that's mounted into `/var/lib/localstack/logs` - avoiding this error:
```
2022-09-01T17:45:57.270 ERROR --- [   Thread-12] localstack.utils.bootstrap : Error while starting LocalStack container: Docker process returned with errorcode 1
/usr/local/bin/docker-entrypoint.sh: line 73: /var/lib/localstack/logs/localstack_infra.log: Permission denied
```
I think it's a fair assumption that the user needs to take care of giving the Docker container user write access to the LocalStack internal filesystem. Additionally, we could also make the log file creation more resilient - adding a fallback to swallow permission errors …
> Remove xfail flag for test to run container as non-root

- localstack/utils/collections.py
- localstack/utils/net.py
- tests/unit/test_common.py
Add ability to set custom expiry for reserved ports in `PortRange` TTL cache. 
This surfaced while working on a fix for #6798 - some services need a bit more time to start up, so it will come in handy if we have a way to reserve service ports for an extended period of time (beyond the default 6 seconds).
* introduce a `CustomExpiryTTLCache` class that provides a `set_expiry(..)` method to set the expiry for a single key
* allow passing in an optional `duration` parameter to `reserve_port(..)`, to reserve a port for the given duration
* add a small test to assert the custom port reservation duration
> Add ability to set custom expiry for reserved ports in PortRange TTL cache

- localstack/aws/serving/asgi.py
This PR increases the number of concurrent requests that can be served when running the LocalStack gateway through hypercorn. There's no impact die normal usage, it's just the size of the thread pool used for spawning request handlers. Should fix #6792 but need to double check with the user.
> increase max number of http request threads

- scripts/capture_notimplemented_responses.py
- scripts/coverage_docs_utility.py
Latest automated Doc PR added the new service `transcribe` but information about implemented status is missing, as the script `capture_not_implemented_responses` is not aware of the service yet.
The services are now retrieved dynamically from the health endpoint. For community, we will not test against pro only endpoints, but this should be fine.
Tested a run of `coverage_docs_utility` with the new output files successfully.
> test dynamic evaluation of services

- CODEOWNERS
- localstack/testing/snapshots/transformer.py
- tests/unit/utils/testing/test_snapshots.py
Makes it easier to reliably compare lists via snapshots by sorting them via a transformer instead of having to manually sorting the object before calling `match`.
Usage: 
```python
snapshot.add_transformer(SortingTransformer("Aliases", lambda x: x["Name"]))
```
> Add sorting transformer for snapshots

- localstack/aws/api/s3/__init__.py
- localstack/services/providers.py
- localstack/services/s3/provider.py
This PR is part of #6827 and is the basis for migrating s3 to ASF.
It creates the new s3 ASF provider marked as `asf` as well as the scaffolded `s3` API. It sets the current s3 provider as `default`.
This should make no changes to the current implementation, and can only be used with `PROVIDER_OVERRIDE_S3=asf` (not stable at all for now!)
This is @steffyP works and I'm just making the PR 🎉
> add new s3 ASF provider

- localstack/services/apigateway/integration.py
- localstack/services/firehose/provider.py
- localstack/services/logs/provider.py
- localstack/services/sns/provider.py
- localstack/testing/pytest/fixtures.py
Sadly, with the refactoring of lambda invokes in the different services, one important thing was missed: the region of the lambda client has to match the region of the lambda invoked. Currently, it will fallback to the default region, which is us-east-1, if it is not executed directly in the context of a request for a different region. Even in the latter case, some services support invoking lambdas in different regions (apigateway for example), which would still not be possible then.
We now extract the region of the lambda arn before creating the call, and calling the lambda in the appropriate region.
> Extract region from function arn for inter service invokes

- pyproject.toml
This PR fixes the `coverage` config to:
- Properly exclude the generated ASF APIs and the extensions API (see https://github.com/localstack/localstack/pull/6715 and https://github.com/localstack/localstack/pull/6829).
- Remove the exclusion of `localstack/infra` and `localstack/node_modules`, since these directories are not used anymore (since https://github.com/localstack/localstack/pull/6302).
I verified the settings with the following commands locally:
```
TEST_PATH="tests/integration/test_sqs.py" make test-coverage
coverage combine
coverage html
```
**This PR will unfortunately lower the code coverage percentage quite a lot**, since the generated APIs had a high coverage:
- They only contain the method and type signatures where loading them is a coverage hit.
- They increase the total …
> fix coverage exclusions

- localstack/services/dynamodb/provider.py
- tests/integration/test_dynamodb.py
Fix region in DynamoDB store lookup to enable access from NoSQL Workbench: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/workbench.html
Fixes this error:
```
File ".../localstack/services/dynamodb/provider.py", line 288, in find_global_table_region
replicas = get_store().REPLICA_UPDATES.get(table_name)
File ".../localstack/services/dynamodb/provider.py", line 278, in get_store
return dynamodb_stores[_account_id][_region]
File ".../localstack/services/stores.py", line 166, in __getitem__
raise ValueError(
ValueError: 'localhost' is not a valid AWS region name for dynamodb
```
/cc @viren-nadkarni
> Fix region in DynamoDB store lookup to enable access from NoSQL Workbench

- localstack/services/cloudformation/models/s3.py
This is a preparation for ASF S3 migration. The [old provider, filters `LocationConstraint`](https://github.com/localstack/localstack/blob/master/localstack/services/s3/s3_listener.py#L1465-L1471) for `create-bucket`:
```
to_find1 = to_bytes("<LocationConstraint>us-east-1</LocationConstraint>")
to_find2 = to_bytes("<CreateBucketConfiguration")
if data and data.startswith(to_bytes("<")) and to_find1 in data and to_find2 in data:
modified_data = b""
```
With the new ASF S3 provider, we will have the same behavior as AWS:
`LocationConstraint` for bucket creation should only be included if the location is not the default location (e.g. not us-east-1). Otherwise it will thrown an `IllegalLocationConstraintException`.
[According to the …
> fix create-bucket: exclude LocationConstraint for us-east-1

- localstack/aws/serving/hypercorn.py
- localstack/http/asgi.py
- localstack/http/hypercorn.py
- localstack/services/awslambda/lambda_api.py
- localstack/utils/http.py
- setup.cfg
- tests/unit/aws/test_gateway.py
- tests/unit/http_/conftest.py
This PR fixes an import error that occurred with a change in hypercorn https://github.com/pgjones/hypercorn/commit/c2608a0ab1133a11a2a8eeb659388c8dd13bc9b1.
I renamed the affected imports and also added an explicit dependency to the latest hypercorn version.
Side note: Hypercorn now supports serving WSGI apps. Looks like the ASGI/WSGI bridge isn't as mature as ours yet, but looks promising! Maybe we can get rid of some code soon.
**Update**: Looks like hypercorn is now also lowercasing the raw headers. there seems to be no way to restore the original header casings, which, however, some cases rely on, such as #4532.
**Update**: specifically, it seems h11 is no longer returning a `h11.Headers` object #6413, and it's now just a tuple of lower-case header name and value. …
> upgrade hypercorn to 0.14.2

- etc/tf-patch/0001-endpoints.patch
With https://github.com/localstack/localstack/commit/3baefea6df1e590c426bd8458d6d2564f2dabf92, @macnev2013 introduced an automation which automatically executes a set of terraform tests (created by the terraform community) against localstack.
The testing infrastructure depends on a small patch which is applied on top of https://github.com/hashicorp/terraform-provider-aws. Unfortunately, the patch broke with https://github.com/hashicorp/terraform-provider-aws/commit/2b217fc97c080aa193516f1c2249a1ba3571154a.
This PR fixes the patch for now. In another iteration, we could make the testing infrastructure more resilient by:
- Maybe get the terraform team to allow configuring the endpoints when executing the tests (that would be awesome).
- Use a pinned version of the repo (i.e. a tag) which is …
> fix terraform AWS provider patch for terraform tests

- localstack/utils/bootstrap.py
- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- localstack/utils/docker_utils.py
- tests/bootstrap/test_cli.py
Extend CLI to run container from within Docker using SDK client. 
The starting point for this PR is a [Docker Extension](https://www.docker.com/products/extensions/) PoC for LocalStack - these extensions do not allow us to run native commands on the host, but only spawn Docker containers. Hence, in order to be able to reuse the full power of the CLI, this PR adds a few small adjustments to allow us to run the CLI (and `localstack start`) from within a Docker container.
Essentially, we'd like to be able to run this command:
```
docker run --rm -it --entrypoint= -v /var/run/docker.sock:/var/run/docker.sock localstack/localstack bin/localstack start -d
```
... which currently fails, because we're always using the `CmdDockerClient` (and `docker` is not available in the image):
```
File …
```
> Extend CLI to run container from within Docker using SDK client

- localstack/services/acm/provider.py
- localstack/services/route53resolver/models.py
- localstack/services/route53resolver/provider.py
- localstack/services/route53resolver/utils.py
- tests/terraform/get-tf-tests.py
- tests/terraform/run.sh
- tests/terraform/terraform-tests.yaml
This PR addresses issues with the terraform test pipeline discovered while working on https://github.com/localstack/localstack/pull/6853.
The `route53resolver` tests are currently timing out, but the pipeline does not fail.
```
2022-09-12T09:50:52.4625278Z === CONT  TestAccS3Bucket_Duplicate_UsEast1AltAccount
2022-09-12T09:51:01.1596683Z     bucket_test.go:400: Step 1/1, expected an error with pattern, no match on: Error running apply: exit status 1
2022-09-12T09:51:01.1597193Z         
2022-09-12T09:51:01.1598165Z         Error: creating Amazon S3 (Simple Storage) Bucket (tf-test-bucket-583879316476979402): bucket already exists
2022-09-12T09:51:01.1598545Z         
2022-09-12T09:51:01.1598878Z           with aws_s3_bucket.test, …
```
> fix pipeline failure on terraform test failure

- localstack/utils/cloudformation/template_deployer.py
Mostly related to usage with PRO. With the changes in 20e9c0e4dc75ac1c2822c2304db59a13335c3eaf users now started seeing warnings in the logs when deploying CloudFormation custom resources.
Example:
```
2022-09-13T21:27:20.254 WARNING --- [  Thread-120] localstack.utils.cloudformation.template_deployer : Unable to get client for "dynamodbu" API, skipping deployment: Unknown service: 'dynamodbu'. Valid service names are: accessanalyzer, account, acm, acm-pca, alexaforbusiness, amp, amplify, amplifybackend, amplifyuibuilder, apigateway, apigatewaymanagementapi, apigatewayv2, appconfig, appconfigdata, appflow, appintegrations, application-autoscaling, application-insights, applicationcostprofiler, appmesh, apprunner, appstream, appsync, athena, auditmanager, autoscaling, autoscaling-plans, …
```
> Fix client warnings in logs for custom resources

- localstack/testing/snapshots/prototype.py
- tests/integration/cloudformation/test_cloudformation_firehose.snapshot.json
Previously the `skip_snapshot_verify` marker was influencing how transformations are applied and would lead to hard to debug issues when for example the order of `<resource:num>` tokens were mixed up due to this.
> Remove snapshot paths *after* the transformations have been applied

- localstack/services/opensearch/cluster.py
- localstack/services/opensearch/cluster_manager.py
- tests/integration/test_opensearch.py
Unfortunately, we introduced an issue with https://github.com/localstack/localstack/pull/6783 for opensearch.
The domain creation failed when the opensearch installation was not yet present on the machine.
This was due to the directory resolve order: The installation directories have been resolved before they were available (because with the new installer, the installation target cannot be determined before the package is installed).
This PR addresses this issue by deferring the directory resolving to a later point, i.e. when actually starting the cluster (and when the package is ensured to be installed).
> fix opensearch cold-start domain creation

- localstack/services/dynamodb/provider.py
- localstack/services/dynamodb/utils.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/test_dynamodb.py
- tests/integration/test_dynamodb.snapshot.json
- Marked every dynamodb test with either only_localstack or aws_validated
- Added snapshots for each aws_validated test
- Corrected a few minor things to make snapshots validate (or added a skip_validate)
- Removed test_dynamodb_batch_write_item as it tests the same as test_batch_write_items 
In a second PR I will correct several only_localstack tests to make them aws validated...
> mark dynamodb tests and add snapshots

- localstack/services/awslambda/lambda_api.py
- localstack/services/awslambda/lambda_executors.py
- localstack/utils/run.py
- tests/integration/awslambda/functions/lambda_logging.py
- tests/integration/awslambda/functions/lambda_print.py
- tests/integration/awslambda/test_lambda_legacy.py
Some minor fixes for the local execution of python lambdas (and local executor in general)
* Actually spawns a new process now instead of calling `Process.run` which just executed the handler in the same process.
* Usage of the `logging` module now works in lambdas as expected
* Usage of print now should also work as expected
> Fix logging in local python lambdas

- Makefile
With a recent PRO PR, we have introduced a better parameter validation for rds create-db-cluster. Mainly, we have to specify an existing db cluster parameter group name (if specified).
Since the current pre release pro tests do not do this, the tests fail.
Remove the non-existent parameter group name, and let RDS create one for us.
> Fix prerelease smoke tests for RDS

- localstack/aws/spec-patches.json
- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
Buckets can be addressed either in path-style `s3.<region>.localhost.localstack.cloud:4566/mybucket` or virtual host-style `mybucket.<region>.localhost.localstack.cloud:4566`.
Path style (without region) is covered by moto.
* Added routes for vhost-style 
* Added more specific routes for buckets that contain dot(s) in the name -> this is a special case as it changes the domain
* put requests for such buckets will currently not work
* Added route to match path-style urls that contain a region
* currently only strips the region, and re-sends the request
Note: AWS works a bit differently (also compared to the old provider): if bucket is created with a location constraint and the path-style contains another region, it would respond with 301 (for any region other than `us-east-1`), or 307 (for …
> add rules for ASF S3 virtual host urls

- localstack/services/ses/provider.py
L112 in the SES Provider suggests that the Email source can have nil-values: 
```python
if filter_source in (msg["Source"], None, ""):
```
The included dictionary access causes a KeyError in this case. This PR changes that to a `.get()` call to avoid that.
> Fix SES email retrospective KeyError

- localstack/aws/handlers/cors.py
- localstack/services/apigateway/context.py
- tests/integration/test_apigateway.py
Add rule for execute-api and extend test coverage for API Gateway custom CORS. This is a follow-up from #6895 , where an additional switch for `../_user_request_/..` paths was introduced - we need to apply the same switch for `...execute-api...` domain names. (this should fix the tests upstream in ext)
Tried to cover the different cases with a parameterized integration test, which should cover the relevant combinations of settings (using a simple API GW MOCK integration).
> Add rule for execute-api and extend test coverage for API GW custom CORS

- localstack/services/plugins.py
In the old edge proxy, we assumed each proxy listener was assigned a port which pointed to the running backend (this was often just moto). A generic health check would check whether the port of the backend was available. For ASF services, this doesn't really make sense, so the port may be None in these cases. This PR adds a guard to avoid errors that would emerge sometimes when adding new services.
This is candidate code to be removed/reworked once we have the remaining proxy listeners (S3, Lambda) refactored.
Example:
```
--- Logging error ---
File "/home/thomas/.pyenv/versions/3.10.4/lib/python3.10/logging/__init__.py", line 1100, in emit
msg = self.format(record)
File "/home/thomas/.pyenv/versions/3.10.4/lib/python3.10/logging/__init__.py", line 943, …
```
> disable generic local_api_checker for new gateway

- localstack/aws/api/s3/__init__.py
- localstack/aws/protocol/serializer.py
- localstack/aws/spec-patches.json
- localstack/services/s3/models.py
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
- tests/unit/aws/protocol/test_serializer.py
This PR adds more operations to the S3 provider, and reorganised the tests by class, grouping them more coherently.
This will reduces the number of failing test and implement a lot of basic functionality, and fixes some current bugs at the same time. 
It is a bit hard to keep track of implemented operation and fixed exceptions, as a lot of fixes are done by moto patching. 
Implemented operations:
- `GetBucketRequestPayment`
- `PutBucketRequestPayment`
- `GetBucketLifecycleConfiguration` (had to reimplement it, moto is not validating correctly Transition actions, and will raise exceptions. Would need a bigger rewrite in moto. Needed for Terraform).
- `PutBucketLifecycleConfiguration`
- `DeleteBucketLifecycleConfiguration`
- fix object Expires parameter
- fix `GetObject` with range headers, …
> Implement more ASF S3 operations in provider

- Dockerfile
Adds `jdk.management.agent` to our JRE, as Apache MQ requires it.
Note - this adds significant size to our Dockerfile and is a temporary solution.
> Add dependency in Dockerfile for MQ

- localstack/runtime/init.py
- tests/integration/s3/test_s3.py
- tests/unit/runtime/test_init.py
Small fix to handle empty (`None`) values for `init` dir with legacy directories in non-Docker mode.
Addresses https://github.com/localstack/helm-charts/issues/60 
The issue can be replicated when deploying the Helm chart in a local k3d Kubernetes cluster. More easily, can also be replicated when using legacy directories in host mode:
```
LEGACY_DIRECTORIES=1 bin/localstack start --host
```
@thrau If you feel that there is a better fix , please feel free to push changes directly to the PR. 👍  This is more of a bandaid/quickfix now - but seems to be good enough, just to fix the symptom for now (and as we're going to phase out the legacy filesystem hierarchy at some point soon).
---
Side note: Interestingly, this cannot be replicated in the built-in Kubernetes that ships with Docker Desktop …
> Small fix to handle empty init dir with legacy directories in non-Docker mode

- localstack/aws/api/s3/__init__.py
- localstack/aws/protocol/serializer.py
- localstack/aws/spec-patches.json
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
No integration tests were really checking ACLs, so this one is not reducing tests failure as much.
- Implement Bucket ACL operations and validation in provider.
- ACL enforcement is not part of it, as it's not currently done in the current provider.
> Implement Bucket ACL operations in S3 provider

- localstack/utils/docker_utils.py
- localstack/utils/net.py
- tests/integration/docker_utils/test_docker.py
- tests/unit/test_common.py
Add utilities to check availability and reserve Docker container ports. This is a preparation for upcoming changes to address #6225 .
* add `container_port_can_be_bound(..)` utility to determine whether a (host) port can be bound by a container. The current approach is to simply spin up a temporary test container with the port mapping, to see if it can be started up properly. An alternative would be to query the Docker API for current containers and port allocations, but this approach seems simpler and more reliable for now.
* add `reserve_available_container_port(..)` utility that determines and reserves a (random) port that can be bound by new Docker containers to be created
* add `is_port_reserved(..)` method to `PortRange` class to determine whether a port is …
> Add utilities to check availability and reserve Docker container ports

- localstack/aws/client.py
- tests/unit/aws/test_client.py
This PR fixes a performance issue that occurred with AWS responses that have streaming bodies. The change exposes the underlying iterator of `Response` directly through the `_ResponseStream` wrapper, so invocations of the form `for item in stream` no longer go through the pointless `read_into` abstraction.
This issues surfaced with the new S3 provider, where `get_object` download would take exponentially longer the larger the body. When bodies are streamed, we wrap the response in a `_ResponseStream` object that exposes the response as a readable IO object
https://github.com/localstack/localstack/blob/68c507ed073da8d5c5bd626e4106e4a40b4daee0/localstack/aws/client.py#L150
The issue is that the `_ResponseStream` is invoked in the form `for item in stream`. Through the RawIOBase abstraction, …
> fix performance issue with ResponseStream wrapper

- localstack/services/s3/models.py
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR implement fixes to bugs that are also present in the current provider, coming from moto.
The VersionId would be present when it should not be, added logic to the versioning for that.
When `PutObject` would be used with a pre-signed URL signed with SigV2, the object would be instantly expired because moto merges headers and query string parameters, and the signature contains an `Expires` query parameter which would be treated as the `Expires` header. 
It also implement the Response{Headers} overriding behaviour.
> S3 ASF fix VersionId and Expires, implement ResponseHeaders override

- setup.cfg
pyOpenSSL 21.1.0 drops support for SSLv2 and SSLv3. This breaks pyftplib which is used in AWS Transfer tests. It is not possible to pin it in pyftplib as it uses pyOpenSSL as an indirect dependency (by not having an explicit dependency in setup).
Changelog: https://pypi.org/project/pyOpenSSL/
Failure: https://github.com/localstack/localstack-ext/actions/runs/3125572451/jobs/5071294179#step:17:1174
> Pin pyOpenSSL to 21.0.0

- setup.cfg
PyOpenSSL was pinned to 21.0.0 in #6936. However this introduced other unrelated regressions.
This PR now pins PyOpenSSL to 22.0.0, which is compatible with OpenSSL 1.1.1 and without the issue in #6936 
Previously failing ext test: https://github.com/localstack/localstack-ext/actions/runs/3133713131/jobs/5087396457#step:17:1157
> pin pyOpenSSL to 22.0.0

- localstack/services/awslambda/lambda_api.py
- localstack/services/dynamodb/utils.py
- localstack/testing/pytest/fixtures.py
- tests/integration/awslambda/test_lambda_legacy.py
- tests/integration/test_dynamodb.py
Minor fix for Lambda layer response parsing. Addresses https://github.com/localstack/serverless-localstack/issues/175
Currently, we're taking the incoming `Layers` parameter (which is a list of strings) in the `UpdateFunctionConfiguration` API method, and simply pass it through to the response - however, the response `Layers` attribute should be a list of dicts with the details. 
For now, simply removing `Layers` from the response - it is already being added separately upstream, so this should not break -ext functionality.
---
PR also sneaks in a small fix for `transact_write_items` that surfaced during testing, to raise the correct exception (ASF exception, instead of boto3 error), in order to avoid 500 errors. (Happy to create that as a separate PR, but seemed reasonably …
> Minor fix for Lambda layer response parsing

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
This PR adds validation to message attributes in SNS, which was allowing empty message attributes values, unlike AWS. This in turn would raises a `KeyError` while preparing the message in a thread. 
We now validate the message synchronously in the operation call to allow raising an Exception.
_fixes #6907_
> add message attributes validation for SNS

- Dockerfile
This PR fixes refs to an upstream dependency: https://github.com/carlossg/docker-maven
The files were removed from `master` and are causing build failures:
https://github.com/carlossg/docker-maven/commit/b0539da7612b617ecc19de057872e1469e2ac825
```
#6 [java-builder 1/3] FROM docker.io/library/python:3.10.7-slim-buster@sha256:7bb70ac0176d6a8bdabba60cd8ededd6494605f225365510f7ee5691a4004463
#6 DONE 0.0s
#7 https://raw.githubusercontent.com/carlossg/docker-maven/master/openjdk-11/settings-docker.xml
#7 ERROR: invalid response status 404
#8 importing cache manifest from localstack/localstack-light
#8 ...
#9 [auth] localstack/localstack-light:pull token for registry-1.docker.io
#9 DONE 0.0s
#8 importing cache manifest from localstack/localstack-light
#8 DONE 1.2s
#3 [internal] load metadata …
```
> Update docker-maven ref

- localstack/aws/protocol/serializer.py
- setup.cfg
Upgrades to the latest moto-ext which is based on https://github.com/spulec/moto/commit/76b127bba65771c1d3f279cd2c69309959b675d8 (already part of moto 4.0.6.dev)
I added a method to the serializer that was removed/renamed in moto to localstack.
/cc @ackdav: includes the fix for the organizations support case
> upgrade moto-ext to 4.0.5.post1

- localstack/packages/api.py
- localstack/packages/core.py
this PR addresses several issues that caused builds to hit github rate limits and then causing kinesis tests to fail/time out.
* decorators are not inherited when methods are overwritten. therefore adding `@lru_cache()` on the abstract method will not cache anything. 
* `_get_installer` creates a fresh version of the installer every time, so even then, caches in the installer wouldn't be used, so i added an `lru_cache()` around the high-level `get_installer` function to memoize installer instances.
/cc @viren-nadkarni @alexrashed
> add caching to package installers

- localstack/cli/localstack.py
I went to use localstack for the first time yesterday, installed it via homebrew, and ran `localstack start --host` as I didn't have docker running at the moment. Because homebrew is effectively the same as the "light" docker image, I got greeted with an unhelpful stacktrace and no indication of what went wrong:
```
$ localstack start --host
__                     _______ __             __
/ /   ____  _________ _/ / ___// /_____ ______/ /__
/ /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
/ /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
/_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|
💻 LocalStack CLI 1.1.0
[16:59:23] starting LocalStack in host mode 💻 …
```
> Display helpful message if --host fails

- bin/supervisord.conf
This is a fix for https://github.com/localstack/localstack/issues/6739. There is no breaking changes and the linting / format tests are passing.
> Fix the supervisord.conf file using a full path

- localstack/services/transcribe/provider.py
Transcribe tests have been causing issues because the SSL cert of  https://alphacephei.com has expired. This is blocking the CI pipeline, so i've disabled SSL verification for now. But we should keep an eye on this, and also check whether we should maybe host these assets ourselves somewhere.
/cc @viren-nadkarni
> disable verify_ssl for downloading vosk language models

- localstack/services/s3/models.py
- localstack/services/s3/notifications.py
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/s3/test_s3_notifications_eventbridge.py
- tests/integration/s3/test_s3_notifications_eventbridge.snapshot.json
- tests/integration/s3/test_s3_notifications_lambda.py
- tests/integration/s3/test_s3_notifications_lambda.snapshot.json
- tests/integration/s3/test_s3_notifications_sns.py
- tests/integration/s3/test_s3_notifications_sns.snapshot.json
- tests/integration/s3/test_s3_notifications_sqs.py
- tests/integration/s3/test_s3_notifications_sqs.snapshot.json
- tests/integration/test_notifications.py
This PR contains S3 bucket notifications for:
* SQS
* SNS
* Lambda (Cloudfunctions)
* Event Bridge
Following events are covered (also by existing tests):
- s3_ObjectCreated_Put
- s3_ObjectCreated_Copy
- s3_ObjectCreated_CompleteMultipartUpload
- s3_ObjectRemoved_Delete
- s3_ObjectTagging_Put
- s3_ObjectTagging_Delete
Other implementation:
- Filters
- verification for filters, destination configuration
- added tests, refactored existing tests
- `InvalidArgument` Error: marked a few TODOs here, because in [another PR](https://github.com/localstack/localstack/commit/34a71b4cbf3ba7c472ea55abfc560eb9a9889db0#diff-4b0f4fffc414ff51da92d57d0afdbedd29bfd8cb5683c57867fa2bf31e8753efR640) we already have a batch for that missing Exception
- xray-feature: no tests yet for lambda + SQS and not sure how …
> migrate S3 notifications to ASF

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/presigned_url.py
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
- tests/unit/test_s3.py
Pre-signed URLs are a feature of S3, allowing to use the client or the CLI to pre-sign a request with the credentials used by the client. The docs are quite extensive about it, and you see more about it here:
https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html
https://docs.aws.amazon.com/AmazonS3/latest/userguide/S3_Authentication2.html
You can sign the request with 2 types: `SigV2`, which is supposed to be deprecated by still used, and `SigV4`.
You effectively sign the request like you would in the headers normally, but pass it in the query parameters instead.
The LocalStack pre-signed URLs feature is checking if the signature of the request is valid (and does not authenticate the request).
We verify the signature by checking the request we received, …
> S3 ASF Presigned URL 

- .github/workflows/terraform-tests.yml
This PR downgrades terraform to 1.2.9 in the terraform tests. This is a wrokaround for an issue that started appearing with 1.3.0 https://github.com/hashicorp/terraform-provider-aws/issues/27049
@dominikschubert already did some initial detective work in https://github.com/localstack/localstack/pull/6954.
I remembered from working on https://github.com/localstack/localstack-terraform-test that the tests actually check the path for an existing terraform binary, and they will use that to deploy the test scripts. The github action seems to come with terraform 1.3.0, so I added an action to overwrite it with a pinned version, in this case 1.2.9, which seems to still work.
> pin terraform version to 1.2.9 for terraform-tests

- localstack/aws/proxy.py
- localstack/testing/aws/lambda_utils.py
- localstack/testing/pytest/fixtures.py
- localstack/utils/aws/aws_responses.py
- localstack/utils/generic/file_utils.py
- localstack/utils/generic/number_utils.py
- localstack/utils/generic/wait_utils.py
- localstack/utils/testutil.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/cloudformation/test_cloudformation_changesets.py
- tests/integration/cloudformation/test_cloudformation_events.py
- tests/integration/cloudformation/test_cloudformation_integration.py
- tests/integration/cloudformation/test_cloudformation_stacks.py
- tests/integration/cloudformation/test_cloudformation_stepfunctions.py
- tests/integration/test_integration.py
- tests/integration/test_stepfunctions.py
- tests/unit/aws/test_proxy.py
- tests/unit/utils/generic/test_file_utils.py
This PR cleans up some dead code, or simplifies existing code to remove util functions only used in few locations.
I also refactored some imports to get rid of the `utils.generic` package.
> clean up and remove dead code

- .github/workflows/cli-tests.yml
- setup.cfg
`importlib-metadata` recently had their 5.0 major version update, where they removed some "compatibility shims" (https://importlib-metadata.readthedocs.io/en/latest/history.html). I think it is, more concretely, https://github.com/python/importlib_metadata/issues/284 which lead to the incompatibility. 
This lead to stevedore returning an error, since it tries to access the entrypoints like a dict, and therefore in python 3.7 (3.8 and later use importlib.metadata directly) the CLI to start LS did not work anymore.
Since stevedore abandoned python3.7 with its latest version 4.0.0, the chances of a fix are slim (even though the dict-like access might be removed at some point), so for now a dependency pin has to suffice.
Pin the dependency of importlib-metadata to <5.0 for now. Since this …
> Pin importlib-metadata dependency to maintain CLI compatibility for python 3.7

- setup.cfg
- tests/integration/cloudformation/test_cloudformation_ec2.py
Upgrades moto to the latest version that was recently released.
* Had to fix one cfn ec2 test that started failing, apparently due to this change: https://github.com/spulec/moto/pull/5509 unfortunately I couldn't verify the behavior against AWS (stack would not deploy, did not figure out why)
> upgrade moto to 4.0.6.post1

- pyproject.toml
- tests/integration/awslambda/functions/lambda_integration.py
- tests/integration/awslambda/test_lambda_integration_sqs.py
- tests/integration/test_integration.py
test_integration.py has been notoriously flaky, which i think is in part because it is not resilient towards reruns. reruns almost never work, because tests don't clean up resources properly. [Here is an example](https://circleci.com/api/v1.1/project/github/localstack/localstack/64160/output/105/0?file=true&allocation-id=633a1249265c77718d64f868-0-build%2FW9WZCTDV) (search for `tests/integration/test_integration.py::TestIntegration::test_firehose_kinesis_to_s3 `).
This PR refactors the test to use our factory fixtures, and generated resource names where possible.
I also removed a flaky sqs test that has been skipped for a while, which is now in covered by `test_lambda_integration_sqs.py` (apart from the assert whether the lambda logs return the correct events, for which i created a TODO) …
> refactor test_integration.py to be more resilient towards reruns

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/models.py
- localstack/services/s3/provider.py
- localstack/services/s3/website_hosting.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR implement support for S3 website hosting with additional features than the current provider.
Most S3 website features are now implemented, including `RoutingRules`, configuration validation...
https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteHosting.html
Note: permission/ACLs are not enforced currently, and it can be added in another PR with a feature flag in the same vein as IAM.
> implement S3 ASF website hosting support

- tests/integration/cloudformation/test_cloudformation_opensearch.py
- tests/integration/cloudformation/test_cloudformation_opensearch.snapshot.json
- tests/integration/templates/opensearch_domain.yml
Test to validate Opensearch domain deployment through Cfn. Related to #6830
> Test added for CFn-Opensearch:Domain

- localstack/services/s3/website_hosting.py
Moto moved an util function to generate `RequestId`, we now have it directly in the serializer. S3 ASF website hosting made use of it, so change the import.
> fix s3 asf website moto import

- localstack/services/awslambda/lambda_api.py
- localstack/utils/aws/aws_stack.py
- tests/unit/test_lambda.py
Tie Lambda backend lookup to resource ARNs to avoid region mismatches.
The problem is that we're currently accessing `LambdaRegion.get()` in a few places, and the assumption is that the proper region is configured in the context (which is a conceptual flaw in the first place). This may not be the case, e.g., when restoring state from persistence/pods, where we iterate through the regions, and then restore the function code for each function in each region.
This is currently breaking our integration tests upstream (restoring Lambdas from pods/persistence) in platform. Example of an error we're seeing in the logs:
```
localstack_main | 2022-10-04T21:56:21.428  INFO --- [   asgi_gw_1] l.s.awslambda.persistence  : Unable to load user code for Lambda function …
```
> Tie Lambda backend lookup to resource ARNs to avoid region mismatches

- localstack/http/router.py
- tests/unit/http_/test_router.py
This PR fixes a bug where we wouldn't correctly add the `methods=["GET", ...]` parameter from a route to the underlying rule, and would therefore not route correctly if there were multiple methods with different HTTP methods on the same URL.
> fix http router to correctly add method constraints for route

- localstack/services/dynamodbstreams/dynamodbstreams_api.py
- localstack/services/dynamodbstreams/provider.py
- setup.cfg
- tests/integration/test_dynamodb.py
- tests/integration/test_dynamodb.snapshot.json
This PR solves an issue where `GetItem` of DynamoDB returns a differently encoded value than `GetRecords` of DynamoDBStreams. This is especially obvious when using binary data (a test case of `b"\x90"` already reveals the issue).
Adds test case `test_data_encoding_consistency`
Fixes: #6786, Fixes: #6700 
The test case is currently flaky, therefore I draft the PR for now. 
However, since a similary structured test case [here](https://github.com/localstack/localstack/blob/master/tests/integration/test_dynamodb.py#L1188) is also flaky, I highly suspect that the flakiness is not because of my solution, but because of the client.
> Fix DynamodbStreams binary data consistency

- localstack/aws/api/s3/__init__.py
- localstack/aws/protocol/serializer.py
- localstack/aws/spec-patches.json
- localstack/services/s3/presigned_url.py
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR implements S3 pre-signed POST support
Currently, the provider does not implement signature validation, but it is not a lot of work to implement, as only the policy is signed (a JSON string encoded in base64). It can be done in a follow up PR. 
To implement support for this operation, we needed to create an operation not defined in the specs, as the clients (like `Boto`) would never call directly to this URL. But it is implement server side, and documented. See https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html
Also, I had to make a small change to the serializer, but I'm not sure it should be generalised. I think 3XX status code are not supposed to return a body. So I skipped serializing the body in case the status code was >= 300 and < 400. 
It also came to light …
> implement S3 ASF pre-signed POST support

- localstack/services/apigateway/helpers.py
- tests/integration/apigateway_fixtures.py
- tests/integration/files/pets.json
- tests/integration/files/swagger.json
- tests/integration/test_apigateway.py
OpenAPI supports the "parameters" field that is applied to all methods of the path, however, we don't offer particular support for it.
This PR skips the "parameters" and others like, e.g "servers", "description", "summary", "$ref", from the OpenAPI spec to avoid errors. 
Fix downstream to enable the construction of the Method model with request parameters.
https://github.com/spulec/moto/pull/5425
Unblocks https://github.com/localstack/localstack/issues/6747
> Avoid import rest api from openapi skipping 'parameters'

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/models.py
- localstack/services/s3/notifications.py
- localstack/services/s3/presigned_url.py
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- tests/integration/cloudformation/test_cloudformation_legacy.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
- tests/integration/test_edge.py
This PR implements the last small fixes to get the tests green in community.
- Set the attributes stored in the `S3Store` to be `CrossRegionAttribute`, as a bucket can only be created in one region, and its configuration can be accessed from anywhere.
- Fix notifications in case of a S3 pre-signed POST request (a bit of an ugly fix)
- fix headers capitalization for S3 pre-signed URLs
- return `Location` header in `CompleteMultipartUpload` response
- fix tagging an object with an empty list
- implement `GetObjectAttributes` operation, which is not implemented at all in moto (a mix of `HeadObject` and `ListParts`
- fix non-caught exception when trying to get a deleted key in a versioned bucket
- disable tests for the ASF S3 provider in `test_edge.py` that were related to S3 and the old …
> S3 ASF test fixes

- localstack/services/s3/provider.py
- localstack/services/s3/virtual_host.py
- tests/integration/s3/test_s3.py
This PR moves the S3 ASF virtual host proxy (rewriting virtual host addressed bucket requests to path addressed ones).
It also refactors a bit, adding the handler inside a class, allowing to have the rewriting logic inside of it. Also added a bit of logic removing server added headers (by hypercorn), because they would be added twice (once after being proxied, then when returning the actual response). 
Added a small test to check that the headers are actually returned once, not sure it should be in s3 but maybe something along the testing the router or proxy, I'm not sure?
> move S3 ASF virtual host proxy and refactor

- localstack/http/router.py
- localstack/services/edge.py
- tests/unit/http_/test_router.py
This PR adds the RegexConverter, and a new PortConverter as default converters to the `Router`. I've changed my mind a bit since this PR https://github.com/localstack/localstack/pull/5574, and I think adding some default converters to the `Router` can add value on top of werkzeug's `Map`. (/cc @giograno)
The port converter can hopefully simplify some of our URL patterns.
> add default converters to Router

- localstack/packages/core.py
- localstack/services/kinesis/packages.py
- tests/unit/packages/test_core.py
This PR fixes the GitHub package installer's (and in particular the KinesisMock installer's) presence check for offline startups of LocalStack.
Previously, the path which is checked to test if the package is already installed was created by using the filename in the download URL. However, for GitHub assets, the download URL needs to be fetched from the release / tag data.
In order to allow offline startups, the GitHub installer has been slightly refactored such that it now uses the GitHub asset name (which can not use the release data anymore, but this wasn't needed in the first place).
This might cause minor conflicts with https://github.com/localstack/localstack/pull/6916.
Fixes https://github.com/localstack/localstack/issues/7000.
> fix offline GitHub package presence check

- localstack/http/asgi.py
- localstack/testing/pytest/detect_thread_leakage.py
- tests/conftest.py
- tests/integration/conftest.py
We currently have the problem with the interpreter not shutting down on several test runs, both in CircleCI and GitHub Actions.
It seems some threads are actively still making requests, since requests keep coming in.
* Add thread inspection output on the end of test executions, to check which threads are still running (and should not) after LocalStack is instructed to shutdown. Also, subprocesses spawned are enumerated and printed.
* Add informational log outputs to requests failing due to executor shutdown, to check what requests are actually coming in here, to potentially make assumptions about the caller.
> Add debug information to check CI failures

- localstack/services/cloudformation/models/apigateway.py
The missing tags property in Rest API creation causes custom API IDs to not work in CDK deployments. This PR fixes that.
> Add tags to GatewayRestApi resource creation

- localstack/runtime/shutdown.py
- localstack/services/awslambda/invocation/runtime_environment.py
- localstack/services/awslambda/lambda_executors.py
- localstack/services/events/provider.py
- localstack/services/events/scheduler.py
- localstack/services/infra.py
- localstack/services/providers.py
- localstack/utils/analytics/publisher.py
- localstack/utils/analytics/service_request_aggregator.py
This PR introduces a new option to hook into the infrastructure shutdown process.
The registered handlers will be called on infra shutdown, but before the python interpreter shutdown routine begins, giving a good alternative to `atexit` handlers, which can lead to problems with shutdown if they for example spawn non-daemonic threads.
The analytics still uses atexit, as it would need bigger refactoring to correctly differentiate between CLI and infra runs here.
* events job scheduler will now shutdown with the events service. If the interpreter hangs, at least most of the ASGI gateway error requests are related to this scheduler, and should be missing afterwards
* lambda local execution will no longer block if the process refuses to terminate / answer. This should solve a hanging thread I …
> Add infra shutdown handler / improve cleanup of processes and threads

- localstack/services/awslambda/event_source_listeners/sqs_event_source_listener.py
- localstack/services/awslambda/event_source_listeners/stream_event_source_listener.py
- localstack/services/awslambda/lambda_executors.py
- localstack/services/dynamodb/server.py
- localstack/services/edge.py
- localstack/services/events/scheduler.py
- localstack/services/generic_proxy.py
- localstack/services/infra.py
- localstack/services/kinesis/kinesalite_server.py
- localstack/services/kinesis/kinesis_mock_server.py
- localstack/services/opensearch/cluster.py
- localstack/services/opensearch/cluster_manager.py
- localstack/services/sns/provider.py
- localstack/services/sqs/legacy/elasticmq.py
- localstack/services/sqs/provider.py
- localstack/utils/analytics/publisher.py
- localstack/utils/asyncio.py
- localstack/utils/kinesis/kinesis_connector.py
- localstack/utils/kinesis/kinesis_util.py
- localstack/utils/run.py
- localstack/utils/server/http2_server.py
- localstack/utils/server/proxy_server.py
- localstack/utils/serving.py
- localstack/utils/tail.py
- localstack/utils/threads.py
Changes
* Thread utils now have optional name parameters that when set determine the resulting thread name to facilitate the identification of threads when debugging (e.g. when trying to find leaks)
* Semantic names have been added where appropriate. Might still need some adjustment in the future though and not all might be covered atm.
> Add semantic names to threads to simplify detection of thread leaks

- localstack/packages/api.py
- localstack/packages/core.py
- localstack/packages/terraform.py
- localstack/services/awslambda/invocation/runtime_executor.py
- localstack/services/awslambda/lambda_api.py
- localstack/services/awslambda/lambda_executors.py
- localstack/services/awslambda/packages.py
- localstack/services/awslambda/plugins.py
- localstack/services/cloudformation/packages.py
- localstack/services/cloudformation/plugins.py
- localstack/services/install.py
- localstack/services/kms/kms_starter.py
- localstack/services/kms/packages.py
- localstack/services/kms/plugins.py
- localstack/services/sqs/legacy/packages.py
- localstack/services/sqs/legacy/plugins.py
- localstack/services/stepfunctions/packages.py
- localstack/services/stepfunctions/plugins.py
- localstack/services/stepfunctions/stepfunctions_starter.py
- tests/integration/awslambda/test_lambda_legacy.py
- tests/integration/awslambda/test_lambda_runtimes.py
- tests/integration/test_terraform.py
- tests/unit/cli/test_lpm.py
This pr migrates the install routines of the following dependencies to the new architecture as introduced in #6783:
- awslambda-runtime
- awslambda-go-runtime
- cloudformation-libs
- elasticmq (legacy)
- kms-local
- lambda-java-libs
- stepfunctions-local
- terraform
This completes all the install routines currently installable via lpm.
> migrate installer routines to new architecture

- localstack/services/dynamodbstreams/dynamodbstreams_api.py
- localstack/services/dynamodbstreams/provider.py
- setup.cfg
This PR removes `bson` direct dependency and adds `pymongo` as a dependency that in turn brings a compatible transitive `bson` dependency.
> Remove bson dependency and use pymongo

- localstack/services/kms/models.py
- localstack/services/kms/provider.py
- tests/integration/test_kms.py
Addresses https://github.com/localstack/localstack/issues/6815
Sign/Verify operations in KMS have two modes. Users can supply
- either raw message - KMS then calculates a digest of that message internally and then signs/verifies that digest;
- or a digest prepared by a user - in this case the digest calculation inside of KMS is skipped, and the supplied digest is signed/verified directly.
Originally LocalStack was ignoring MessageType parameter. This PR adds logic to check the value of the MessageType parameter and to act accordingly.
AWS probably calculates different digests depending on the SigningAlgorithm parameter. While with this PR in LocalStack we are going to always use SHA256 digest. Not ideal, but currently there is little need to spend more effort into this.
> [KMS] Adding digests for KMS sign/verify.

- localstack/services/install.py
This PR fixes a small issue with those installers which have already been migrated to the new structure (introduced in https://github.com/localstack/localstack/pull/6783) and are installed at build time (via the `make init` command).
Unfortunately, these installers have been executed with the install target `VAR_LIBS` (the default - which is overwritten when a local filesystem is mounted) rather than with the `STATIC_LIBS` target (which is not overwritten when a var lib is mounted).
This can be verfied with the following commands:
```
$ docker pull localstack/localstack
$ docker run --entrypoint bash localstack/localstack 
total 172
drwxr-xr-x 11 root root   4096 Oct 17 15:23 .
drwxrwxrwx  6 root root   4096 Oct 17 15:23 ..
drwxr-xr-x  4 root root   4096 Oct 17 15:23 apt-libs
drwxr-xr-x …
```
> fix static infrastructure installer target

- localstack/services/iam/provider.py
Adapting the patch to match the signature of the `IAMBackend`. We experienced a `TypeError: apply_patches.<locals>.add_attributes() takes 4 positional arguments but 5 were given` when trying to reset the IAM status. Thanks to @whummer for noticing the problem.
> Update patch for IAM backend

- localstack/aws/accounts.py
- tests/integration/test_sts.py
Currently, we do not extract the account id from iam/sts access keys on requests, which leads to problems with the multi account feature when using iam access keys.
After the changes in https://github.com/spulec/moto/pull/5501 , we can now use this to extract the account id stateless from the access key id.
* Extract account id for access key id if it matches the correct format. A lot of warnings/fallbacks if it gets an malformed one.
* Add two tests testing access keys generated by iam / sts and the sts get caller identity feature, which in the end depends on our account id extraction.
> Extract account id from access key id for each request

- localstack/packages/debugpy.py
- localstack/services/infra.py
- localstack/services/install.py
This PR migrates the debugpy install routine to the new architecture introduced in https://github.com/localstack/localstack/pull/6783.
Note: the check if it is already installed seems kinda hacky (at least the part to determine the "root" localstack directory). Critique is very much appreciated
> Migrate debugpy installer

- tests/integration/awslambda/functions/lambda_s3_integration.js
- tests/integration/s3/test_s3.py
Not super happy with the general install setup there but this should fix the immediate issue of the pipeline failing atm.
* Add missing `@aws-sdk/util-endpoints` dependency
* Merge the different npm installs
* Adjust endpoint since it seems to expect a string there now instead of an object.
> Fix test_s3_lambda_integration test

- localstack/aws/accounts.py
- tests/integration/test_sts.py
Reverting for now since users are experiencing issues with their setups. 
We should probably re-introduce this (or in a modified way) in a proper release.
> Revert "Extract account id from access key id for each request (#7045)"

- .github/workflows/rh-support.yml
- Dockerfile.rh
This PR tries to revive our RedHat Dockerfile example located in `Dockerfile.rh`.
The workflow has been deactivated due to several issues over the time (python upgrades, filesystem changes, certain non-redhat compatible installers,...).
With our new installer structure (introduced in https://github.com/localstack/localstack/pull/6783), these issues can now be addressed.
This PR also changes the trigger of the pipeline from being executed on every master build to be executed on a schedule (every week) since it only tests the latest dev releases against each other (and therefore doesn't directly test the latest commit on the master).
Unfortunately, the pipeline can't really be tested (since it had no workflow trigger before). I tested the steps locally though.
> update RedHat example Dockerfile

- localstack/packages/api.py
This PR moves the installation steps behind a mutex lock to avoid race conditions if the installer is invoked multiple times.
We rely on the LRU-cached `get_installer()` method to return the same installer instance for a given version to ensure the same lock is utilised.
> Add mutex locks to installers

- localstack/aws/api/s3/__init__.py
- localstack/aws/protocol/parser.py
- localstack/aws/spec-patches.json
- localstack/http/client.py
- localstack/services/s3/notifications.py
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- localstack/services/s3/website_hosting.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
- tests/integration/s3/test_s3_notifications_sqs.py
- tests/integration/s3/test_s3_notifications_sqs.snapshot.json
- tests/unit/test_s3.py
This PR contains several fixes for S3 ASF that were detected by the terraform test suite:
- Website Hosting: fix handling for empty `ReplaceKeyPrefixWith` for redirect-routing rule (in that case it should remove the the `KeyPrefixEquals` from the original url and then do the redirect)
- Bucket name with slashes: fix parsing issue; preserve name for keys that end with slash
- Patch to change casing of `content-lanugage` , `content-disposition` and `cache-control` to be picked up by parser
- Patch for bucket-key-enbled header `x-amz-server-side-encryption-bucket-key-enabled` which is returned as camel-case by moto, but should be lowercase to be picked up by the parser
- fix resetting of `content-length` for HEAD requests that are forwarded using the `Proxy` for vhost-style requests.
- fix …
> S3 asf fixes detected by Terraform test suite

- setup.cfg
[boto/botocore](https://github.com/boto/botocore) recently changed the endpoint detection: https://github.com/boto/botocore/commit/357d5a81311b9c63286423b64d54ff3d6b99534b
These changes (which are contained in [`boto3==1.25.0`](https://github.com/boto/boto3/releases/tag/1.25.0) / [`botocore==1.2.8`](https://github.com/boto/botocore/releases/tag/1.28.0)) break some of the internal APIs we are using for testing and for our forwarding API (because the endpoint parameter became mandatory), and have impact on the routing (due to changes with the endpoints).
This PR provides a quick-fix by pinning to the previous versions.
The root cause / adjustment to the new versions will be addressed https://github.com/localstack/localstack/pull/7086.
> pin boto(core) version 

- .gitignore
- localstack/services/apigateway/context.py
- localstack/utils/aws/templating.py
- tests/unit/test_templating.py
This PR patches the `VariableExpression` parse method from airspeed to support variables with dashes (`$request.header.X-User`)
This change was tested in airspeed test set and broke only one test because `-` need spacing to be correctly interpreted. The failing test is the same include in this change set.
https://velocity.apache.org/engine/devel/vtl-reference.html#variables
> add patch to parse VariableExpression

- .circleci/config.yml
This PR is a workaround for current problems with the build pipeline in CircleCI, for example here: https://app.circleci.com/pipelines/github/localstack/localstack/10408/workflows/b393d654-3e68-4fd3-9b30-0bceed6828ac/jobs/69777
The (CircleCI internal) Docker Layer Cache Teardown fails with the following error:
```
running command: fstrim [-v /var/lib/docker]
fstrim: /var/lib/docker: FITRIM ioctl failed: Structure needs cleaning
failed with error exit status 1: 16.997204ms
Error saving DLC after 18.144823504s: exit status 1
```
Since [DLC caches cannot be destroyed manually](https://support.circleci.com/hc/en-us/articles/4407580027675-Docker-Layer-Caching-FAQ), we need to disable the feature for at least 3 days (or until CircleCI fixes issues on their end if it's not only related to our …
> fix pipeline by disabling CircleCI Docker Layer Cache

- localstack/cli/lpm.py
- localstack/packages/__init__.py
- localstack/packages/api.py
- localstack/packages/debugpy.py
- localstack/packages/plugins.py
- localstack/services/awslambda/plugins.py
- localstack/services/cloudformation/deployment_utils.py
- localstack/services/cloudformation/models/awslambda.py
- localstack/services/cloudformation/plugins.py
- localstack/services/dynamodb/plugins.py
- localstack/services/es/plugins.py
- localstack/services/install.py
- localstack/services/kinesis/plugins.py
- localstack/services/kms/plugins.py
- localstack/services/opensearch/plugins.py
- localstack/services/sqs/legacy/packages.py
- localstack/services/sqs/legacy/plugins.py
- localstack/services/stepfunctions/plugins.py
- tests/unit/cli/test_lpm.py
- tests/unit/packages/test_api.py
This PR migrates LPM to use a new plugin mechanism based on the package abstraction introduced in https://github.com/localstack/localstack/pull/6783.
It basically replaces the (pluggable) `InstallerRepository` classes with **fine-grained package plugins** where each entrypoint delivers a single package. The package plugins can have a scope (f.e. `community` or `ext`), which directly relates to the former `InstallerRepository` namespace.
A package can easily be defined as follows:
```python
@package(name="dynamodb-local")
def dynamodb_local_package() -> Package:
from localstack.services.dynamodb.packages import dynamodblocal_package
return dynamodblocal_package
```
The local import is necessary to avoid loading all installers (and their code) when discovering / listing the packages.
The …
> refactor lpm plugin mechanism

- localstack/services/kms/provider.py
- tests/integration/test_kms.py
- tests/integration/test_kms.snapshot.json
To increase Localstack coverage for [KMS](https://docs.localstack.cloud/localstack/coverage/#kms), this is a request to add `GenerateRandom` implementation. 
AWS Docs : [AWS APIReference/API_GenerateRandom](https://docs.aws.amazon.com/kms/latest/APIReference/API_GenerateRandom.html)
Moto example: [localstack/moto/kms/responses.py#L588-L605](https://github.com/localstack/moto/blob/localstack/moto/kms/responses.py#L588-L605)
Success case
```bash
$ awslocal kms generate-random --number-of-bytes 32
{
"Plaintext": "gIOXDaGrFBmWRKIlqalIaAJDVX9CBWWi0JRLxzJLLGE="
}
$ echo gIOXDaGrFBmWRKIlqalIaAJDVX9CBWWi0JRLxzJLLGE= | base64 --decode | wc -c
32
```
Validations 
```bash
$ awslocal kms generate-random --number-of-bytes 0
Parameter validation failed:
Invalid value for parameter NumberOfBytes, value: …
```
> [KMS] Add support for generate random

- localstack/config.py
- localstack/services/generic_proxy.py
- tests/unit/services/test_generic_proxy.py
Adds a config environment variable which allows to define a path to a custom server certificate.
This setting is introduced as a simple "redirect". This means that if the cert cannot be found at the given path, the remote cert will be downloaded to the given path.
> add config variable to define custom SSL cert path

- localstack/services/cloudformation/models/dynamodb.py
- tests/integration/cloudformation/resources/test_dynamodb.py
- tests/integration/cloudformation/resources/test_dynamodb.snapshot.json
- tests/integration/templates/dynamodb_table_defaults.yml
Related to #7050. The problem is that the resource model of the table generates the table name only when the resource is created, but the table name (also used as Ref) can be referenced before that.
The fix to the situation is to create the default name at the proper time so it can be used (referenced) before its creation.
> DynamoDB Table CFn-model proper default table name

- tests/integration/s3/test_s3.py
The CI just broke because of CORS headers for S3 requests with an allowed origin in LocalStack, a test was snapshotting all headers, which fails because AWS doesn't return CORS headers if not configured (but we need to for the web app and such). 
\cc @steffyP
> fix skip snapshot for s3 test

- localstack/cli/lpm.py
- localstack/packages/api.py
- tests/unit/packages/test_api.py
This PR enhances the lock handling for the new package installers such that `PackageInstallers` can define custom locks used for the installers. This can be useful when multiple installers need to be synchronized with each other.
It also changes the parallelization approach in LPM from process-based to thread-based parallelization (in order to ensure that the thread-based locks are respected).
See also:
- Package abstraction introduced in https://github.com/localstack/localstack/pull/6783
- Initial lock handling introduced in https://github.com/localstack/localstack/pull/7053
> allow package installers to define custom locks

- localstack/services/dynamodb/server.py
- localstack/utils/bootstrap.py
DynamoDB provider went into an inconsistent state when `PERSISTENCE=1` and API key was not set. 
Only the DBLocal data was being persisted and Store data was not.
See #7118
> Prevent inconsistent persistence states for DynamoDB

- localstack/config.py
This PR modifies the internally used config for `LEGACY_S3_PROVIDER` and checks if the provider is not "asf" neither "asf_pro".
> check provider is asf_pro for S3 legacy config

- localstack/aws/protocol/parser.py
- localstack/services/s3/provider.py
- localstack/services/s3/virtual_host.py
- tests/integration/s3/test_s3.py
- tests/unit/aws/protocol/test_parser.py
This PR deactivates the `VirtualHostRewriter` if the ASF provider for S3 is activated.
S3 virtual host routes are registered `on_infra_ready` to ensure the hosts are resolved correctly, even if s3 is not yet loaded (this requirement was revealed by the terraform test suite).
> deactivate VirtualHostRewriter for s3 ASF

- localstack/services/dynamodb/server.py
Following up on the discussion in https://github.com/localstack/localstack/pull/7123. Went on with option 1 since pods always fetch from a well-known directory (we do not have to implement the logic for random assets dir).
> DDB - clean DB path when persistence is not set

- .circleci/config.yml
- localstack/services/dynamodb/server.py
This is a follow-up from #7174 and #7123 . Unfortunately, one control path (if `clean_db_path=False` is passed explicitly) was still not being considered properly, leading to cloud pods testing issues upstream. This should be fixed in this PR now - also added a docstring to clarify the parameters for the `create_dynamodb_server(..)` function.
> Fix override for cleaning DynamoDB state file

- localstack/constants.py
- localstack/services/opensearch/versions.py
- tests/integration/test_es.py
- tests/integration/test_opensearch.py
This PR adds two new versions to the OpenSearch and ElasticSearch service:
- `OpenSearch_1.2` (added in [April](https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-opensearch-supports-version-1-2/))
- `OpenSearch_1.3` (added in [July](https://aws.amazon.com/about-aws/whats-new/2022/07/amazon-opensearch-service-supports-version-1-3/))
This PR also changes the default version of OpenSearch to 1.3 (since it is already the default version when creating a new domain in AWS without specifying any version).
> add OpenSearch 1.2 and 1.3, change default to OpenSearch 1.3

- localstack/services/awslambda/packages.py
- tests/integration/awslambda/functions/lambda_timeout_env.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/awslambda/test_lambda.snapshot.json
Implementing lambda timeouts, to achieve parity with AWS behavior.
This implementation only affects the new, ASF - based lambda provider.
* Added test making assertions about the execution environment and infrastructure after a timeout
* Update aws lambda init binary to 0.1.6-pre.
Most actual changes for this functionality happened in https://github.com/localstack/lambda-runtime-init/pull/6 .
> Add support for lambda timeouts

- localstack/runtime/init.py
- tests/unit/runtime/test_init.py
Use `exec` passing in the globals from the interpreter rather than the globals from the function.
This fixes the issue with running a python init script that access a global variable. In essence, calling `exec` inside a class method evaluates that code from the context of that class, rather than the interpreter. "Global" variables in the users' script are stored in `locals()` when run from inside a function (as per in `PythonScriptRunner.run`) rather than in `globals()`. This means that when the variable is accessed inside the users' function, it is looked up from the `locals()` store rather than the `globals()` and is therefore not found.
See #7135
> fix python init script execution

- localstack/aws/api/s3/__init__.py
- localstack/aws/app.py
- localstack/aws/handlers/__init__.py
- localstack/aws/handlers/cors.py
- localstack/aws/protocol/serializer.py
- localstack/aws/spec-patches.json
- localstack/services/s3/cors.py
- localstack/services/s3/models.py
- localstack/services/s3/provider.py
- localstack/services/s3/s3_listener.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
- tests/integration/s3/test_s3_cors.py
- tests/integration/s3/test_s3_cors.snapshot.json
- tests/unit/aws/protocol/test_serializer.py
This implements S3 CORS for the new provider.
Current issues with CORS is that we depend on the service name parser to correctly handle CORS depending on the service (S3 and API GW can both manage their own CORS rules). 
We make use of the handler chain, with a very early handler which "pre-parse" the request with a simplified way to determine if the request would be directed towards S3. If it does, we then handle CORS based on the configured rules if there are, otherwise default to the LocalStack behaviour for CORS.
Here's a simplified flow chart for how we handle CORS.
(The top right box will actually differ depending on the previous path, but to simplify the chart, it is drawn as one path only).
> implement ASF S3 CORS

- .circleci/config.yml
This PR adds a new parallel step to our CircleCI workflow to test the S3 ASF provider on every build.
It depends on https://github.com/localstack/localstack/pull/7081 (fixes the remaining tests for the new S3 ASF provider).
It should be reverted once the new S3 provider is default (such that the legacy provider is tested).
Finally, the tests should be removed when the legacy providers are removed.
> add S3 ASF test job to CircleCI workflow

- localstack/services/cloudwatch/provider.py
- localstack/services/sqs/models.py
- localstack/services/sqs/provider.py
- localstack/testing/snapshots/prototype.py
- localstack/utils/cloudwatch/cloudwatch_util.py
- tests/integration/test_cloudwatch.py
- tests/integration/test_cloudwatch.snapshot.json
This PR addresses issue #7131 by sending SQS metrics to cloudwatch.
The metrics are defined in the [AWS docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-available-cloudwatch-metrics.html).
Limitations:
* `ApproximateAgeOfOldestMessage` is currently not considered
* Other `Approximate[...]` metrics are scheduled to be send every minute (on AWS the timeframe might be longer, but for LocalStack it probably makes sense to make the metrics available sooner)
> send SQS metrics to cloudwatch

- localstack/utils/cloudformation/template_deployer.py
- tests/integration/cloudformation/test_engine.py
- tests/integration/templates/resolve_secretsmanager_partial.yaml
The dynamic reference for a secret in the SecretsManager includes an optional json-key, version-stage and version-id at the end of the ARN. This changes fixes parsing those optional parts to not raise a ValueError when unpacking missing values.
Fixes #7192
> Fix parsing optional parts when resolving a secret

- Dockerfile
Add `java.security.*` modules to JRE - these modules are required to run certain components like Spark/Hadoop inside the main container.
This change adds apprx. ~8-10MB (uncompressed) to the image. Build before (1711803587 bytes): 
```
localstack/localstack                                                   latest                                                                       ab65bfe50469   5 minutes ago       1.71GB
```
Build after (1719584564 bytes):
```
REPOSITORY                                                                   TAG                                                                          IMAGE ID       CREATED          SIZE
localstack/localstack                                                   latest …
```
> Add JRE java.security modules to enable bigdata libs

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
This PR fixes a regression introduced in #6938 and reported by many users in #7109, the validation of SNS message attributes data types was a bit too strict. A user (@rafaelpontezup, thanks again for the pointer!) in the reported issue made a very good summary of the issue:
> The interesting thing is that SQS supports optional custom data type labels with the format .custom-data-type. [Its documentation says](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-metadata.html#sqs-message-attributes):
> Custom – To create a custom data type, append a custom-type label to any data type. For example:
> Number.byte, Number.short, Number.int, and Number.float can help distinguish between number types.
Binary.gif and Binary.png can help distinguish between file …
> allow SNS message attributes data type with dot suffixes

- localstack/services/s3/presigned_url.py
- tests/integration/s3/test_s3.py
Follow-up PR to #7070
While migrating the tests, it came to light that port permutation while checking for SigV4 signature was not working.
For context, while validating the signature, we check the host value. But with LocalStack, you can access S3 from different ports (edge port, 443, 80 or not port at all for example in the browser). So we permute ports to try for different `host` value if the first received one is incorrect.
This also comes with a significant refactor, as we would create a lot of resource for every permutation which needed to be created only once.
> S3 ASF fix pre-signed ports permutation

- .pre-commit-config.yaml
The flake8 gitlab mirror has been deleted. This patch updates the pre-commit hook url to point to the github repo.
https://www.youtube.com/watch?v=1FIgj9Q5e6A
> fix: update flake8 git url

- setup.cfg
This PR pins flake8 dependencies, the critical one is flake8-isort, where the recent 5.0.1 release caused some breakage with the flake8 isort integration.
> pin flake8 dependencies

- setup.cfg
We are currently pinning requests < 2.26, because lambda tests failed over 1 year ago.
This PR tries to remove this pin to check test failures.
CircleCI will probably not pick up the changes immediately due to the -ext pin, though.
Fixes #7078
> remove requests version pin

- localstack/services/awslambda/api_utils.py
- localstack/services/awslambda/provider.py
- localstack/services/awslambda/urlrouter.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/awslambda/test_lambda.snapshot.json
- tests/integration/cloudformation/resources/test_lambda.py
Mostly C&P of existing code with the intention of decoupling it from the legacy provider since going forward changes should be focused on the ASF provider anyway and some of the mapping concepts don't apply anymore. 
Also:
- Now supports a correct response for unhandled exceptions and added a corresponding test.
- Added a router class that follows the design of  the router for the apigateway ASF provider.
> Port Lambda URL invocation support to ASF provider

- .github/workflows/pro-integration.yml
The issue was initially observed when the access token expired: https://github.com/localstack/localstack/actions/runs/3530759350/jobs/5923109632#step:3:70
> Fix error logging in companion ref detection

- localstack/services/ses/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_ses.py
- tests/integration/test_ses.snapshot.json
Configure SES to emit SNS messages when configured. This is supported in AWS but not currently implemented in Localstack.
This PR builds on #7214.
Note: support for other `Send*Email` methods follows in PRs:
* #7229
* #7228
#7184
> Fix: SES not emitting SNS messages

- localstack/services/opensearch/provider.py
- tests/unit/test_opensearch.py
When creating an OpenSearch domain in a different region than the default one, the startup monitor failed (since it selected the wrong store, and in turn did not find the domain to change the status for). As a result, the `Processing` status is never set to `false` (indicating that the domain creation was successful / has finished).
This PR addresses this issue by:
- Explicitly setting the region when using `OpensearchProvider.get_store` outside of a request-scoped thread (i.e. the startup monitor thread).
- Raising an `AssertionError` in case `OpensearchProvider.get_store` does not get an explicit region nor is run in a request-scoped thread (i.e. `get_region_from_request_context` returns `None`).
> fix opensearch multiregion support

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/patches.py
- tests/integration/test_apigateway.py
This PR fixes the API id lookup by ignoring case sensitivity.
The issue reported above manifestastes because our router match transforms the API id into lowercase, which would fail when compared with the string used on the `_custom_id_` tag.
Resolves https://github.com/localstack/localstack/issues/7160
> Fix custom id lookup

- localstack/services/opensearch/cluster_manager.py
- localstack/utils/aws/aws_stack.py
This PR fixes two small issues with the connectivity to elasticsearch:
- Fixes the bind host configuration for elasticsearch instances when using the endpoint strategy `PORT`.
- Migrates a fix by @silv-io in #6638 for opensearch to elasticsearch.
- Fixes a small issue with the connectivity from firehose to elasticsearch when using a strategy which does not expose an HTTPS endpoint (i.e. when using the endpoint strategy `PORT` or providing a custom endpoint).
> fix elasticsearch bind host and firehose connectivity

- localstack/services/ses/provider.py
- tests/integration/test_ses.py
- tests/integration/test_ses.snapshot.json
The message id was not being emitted as part of the payload. This was required by the issue creator to link the notification with the specific email.
https://github.com/localstack/localstack/issues/7184#issuecomment-1327213316
> fix #7184: include message id in SNS payload

- localstack/services/visitors.py
- localstack/testing/pytest/fixtures.py
- tests/unit/test_stores.py
- tests/unit/test_visitors.py
First POC of a visitor pattern we can use to retrieve the backends (meaning, an `AccountRegionBundle` and/or a `BackendDict`) of a service.
This is going to be used in the Cloud Pods code to replace `lookup_utils` and `get_backends` (see companion [PR](https://github.com/localstack/localstack-ext/pull/1124)).
> Visitor pattern to collect service backends

- localstack/services/ses/provider.py
- localstack/testing/pytest/fixtures.py
Proper management of SES resources require deletion of AWS resources. Deletion of configuration sets and configuration set event destinations were not supported by localstack.
*Note: these resources are not implemented in `moto` either, so we have to implement the logic in request handlers. We manipulate the `moto` state within the handlers since `moto` does not do it for us 😂*
These changes are well tested as part of #7207 and that PR must be merged first.
> feat: support deletion of configuration set and configuration set event destinations

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/patches.py
- localstack/services/apigateway/templates.py
- localstack/services/moto.py
- localstack/services/s3/provider.py
- localstack/services/s3/s3_starter.py
- localstack/services/visitors.py
- localstack/testing/pytest/fixtures.py
- localstack/utils/patch.py
- setup.cfg
- tests/integration/test_apigateway.py
Upgrades moto-ext to 4.0.10.post1, which builds on the recent 4.0.10 release
Adapted our patches/imports affected by
* https://github.com/spulec/moto/pull/5122
* https://github.com/spulec/moto/pull/5613
* https://github.com/spulec/moto/pull/5654
* https://github.com/spulec/moto/pull/5570
> upgrade moto-ext to 4.0.10.post1

- Dockerfile
- Makefile
- bin/docker-entrypoint.sh
To be merged after https://github.com/localstack/localstack/pull/7249
> Deprecate `localstack-light` and `localstack-full`

- localstack/testing/pytest/fixtures.py
Minor fix for the `deploy_cfn_template` test fixture.
I've noticed that it sometimes was leaking stacks when testing against AWS since it only added the stack id to its internal cleanup state when it was successfully deployed. A timeout would then cause the deployment to fail (it didn't wait for the completion), so the ID was missing from the cleanups even though on AWS it was still in progress, finished a bit later and then was never cleaned up.
> Fix cfn stack leak in test fixture

- localstack/services/cloudwatch/provider.py
- tests/integration/test_cloudwatch.py
- tests/integration/test_cloudwatch.snapshot.json
This PR relates to an [upstream PR in moto](https://github.com/spulec/moto/pull/5658). The PR in moto fixes issue #7154, and adds support for using `values` lists for `put-metric-data`.
* adds snapshot test to verify parity with AWS
* fix small parity issue, by removing empty `ExtendedStatistics` from moto-result if it is empty
> add snapshot test for cloudwatch put-metric-data with values list

- localstack/constants.py
- localstack/services/dynamodb/provider.py
- localstack/services/dynamodb/utils.py
- tests/integration/test_multi_accounts.py
- tests/unit/test_dynamodb.py
This PR fixes additional issues with DynamoDB multi-accounts implementation.
1. The regex for `Credentials` field in `Authorization` header can now accept `-` and `_` characters. See https://github.com/localstack/localstack/issues/7233. We modify this header before forwarding the request to DynamoDB Local to achieve namespacing.
2. Update helpers to explictly take account and region to correctly perfrom global table operations. In DynamoDB, global tables are tables that are replicated across multiple regions. In LS, instead of actually replicating the table, we modify the request context to point to the original region. This means that Boto clients must also be created with the region where the table exists, and not necessarily the region from the request.
Update integration test to …
> Bugfix: DynamoDB BatchWriteItems in multi-accounts

- localstack/services/awslambda/api_utils.py
- localstack/services/awslambda/hooks.py
- localstack/services/awslambda/invocation/docker_runtime_executor.py
- localstack/services/awslambda/invocation/lambda_models.py
- localstack/services/awslambda/invocation/lambda_service.py
- localstack/services/awslambda/provider.py
- localstack/testing/pytest/fixtures.py
- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/awslambda/test_lambda_api.py
- tests/integration/awslambda/test_lambda_api.snapshot.json
Current implementation of the new lambda provider is missing relevant features regarding ImageUri CRUD.
Even though container image execution is a LocalStack Pro feature, the basic CRUD functionality should be in community, on the one hand to prevent tools which use them from throwing errors based on invalid API responses, and for the other to make a implementation easier for pro.
* Added lambda image / imageconfig crud
* add tests
* Move deployment package specific code behind guards, so they are only executed if needed
* Add hooks to hook into from pro, to support container images and layers
> Implement Lambda ASF container image CRUD and docker runtime executor hooks

- localstack/utils/cloudformation/template_deployer.py
- tests/integration/cloudformation/api/test_stacks.py
- tests/integration/cloudformation/api/test_stacks.snapshot.json
- tests/integration/templates/stack_update_1.yaml
- tests/integration/templates/stack_update_2.yaml
- tests/integration/templates/stack_update_3.yaml
This PR fixes an issue with updating updated stacks. After deploying a stack three (!!) times, the stack status would go through
1. `CREATE_COMPLETE`
2. `UPDATE_COMPLETE`
3. `CREATE_COMPLETE`
which is not correct. This impacted AWS SAM since it would be waiting for `UPDATE_COMPLETE` for an update operation, and would hang/timeout. With this change, the stack status is correctly returned to `cloudformation.describe_stacks` as `UPDATE_COMPLETE`.
Closes #6155
> fix: correct status when updating an updated stack

- tests/integration/test_cloudwatch.py
Currently, on master, tests are failing due to the put_metric_alarm_escape_character test failing.
Since it describes all alarms in the describe_alarms check, and just takes the first, it is very possible a leftover alarm from another test failing this one.
* use cleanups fixture for cleanup of this alarm
* filter describe alarms so the first returned alarm should always be the just-created one.
> fix cloudwatch tests by filtering alarm names

- localstack/services/plugins.py
More context here: https://github.com/localstack/localstack-ext/pull/1191. Adds a hook to the state lifecycle to be triggered when a new state is loaded into the provider via Cloud Pods. The logic executed with this trigger often requires method proper of the provider.
> Added after inject hook

- localstack/services/cloudformation/models/elasticsearch.py
- localstack/services/cloudformation/models/opensearch.py
- localstack/utils/collections.py
- tests/integration/cloudformation/resources/test_elasticsearch.py
- tests/integration/templates/opensearch_domain.yml
- tests/unit/utils/test_collections.py
CloudFormation templates are defines in JSON or YAML. Both have type support for primitive types like string or integer.
However, AWS CloudFormation is not too strict about the types of the different fields, f.e. `ClusterConfig.InstanceCount` can be defined as string instead of integer in `AWS::OpenSearchService::Domain`.
This PR introduces a new utility which performs a best-effort TypedDict conversion.
It can be used with the TypedDicts generated by ASF, and will try to recursively convert the members of a given dict to the types of the members of a specific TypedDict.
`convert_to_typed_dict` is then used in the cloudformation models for elasticsearch and opensearch to fix the described type differences.
Fixes #7282
> fix opensearch / elasticsearch cf tempalte type conversions

- localstack/services/apigateway/patches.py
- tests/integration/apigateway_fixtures.py
- tests/integration/test_apigateway.py
The custom patch wasn't adapted to reflect the recent uptake of the new moto model. The fix makes sure we access the correct property from the model.
- Sample https://github.com/localstack/localstack-terraform-samples/tree/master/apigateway-rest-cors
Resolves https://github.com/localstack/localstack/issues/7278
> Fix stage model patch operations

- localstack/services/dynamodb/provider.py
This PR removes the last subclass of `AwsApiListener`.
Addresses #6668.
> remove unused DynamoDB-specific AwsApiListener

- localstack/config.py
- localstack/services/awslambda/invocation/docker_runtime_executor.py
- tests/unit/services/awslambda/test_image_resolver.py
Adds a `RuntimeImageResolver` class and a corresponding new config variable `LAMBDA_RUNTIME_IMAGE_MAPPING`
Copied doc from the class:
> Resolves Lambda runtimes to corresponding docker images
> The default behavior resolves based on a prefix (including the repository) and a suffix (per runtime).
> 
> This can be customized via the LAMBDA_RUNTIME_IMAGE_MAPPING config in 2 distinct ways:
> 
>   Option A: use a pattern string for the config variable that includes the "<runtime>" string
>       e.g. "myrepo/lambda:<runtime>-custom" would resolve the runtime "python3.9" to "myrepo/lambda:python3.9-custom"
> 
>   Option B: use a JSON dict string for the config variable, mapping the runtime to the full image name & tag
>       e.g. {"python3.9": "myrepo/lambda:python3.9-custom", "python3.8": …
> Add option to customize images used for lambda execution

- localstack/cli/localstack.py
- localstack/cli/main.py
- localstack/cli/profiles.py
This PR introduces a pre-processing of CLI flags to make sure config profiles are loaded correctly. Previously, config profiles beyond `default.env` did not work at all, because `localstack.config` (and subsequently the config profiles) was loaded *before* the CLI was created and `--profile=...` was parsed. This is a fundamental issue with our current import paths.
Tested locally, and we should put proper bootstrap tests on the roadmap for when we rework the pipeline.
> fix --profile flag of CLI so config profiles are loaded correctly

- localstack/services/cloudformation/models/dynamodb.py
- tests/integration/templates/deploy_template_3.yaml
Addresses #7007 by removing the `ContributorInsightsSpecification` key (we do not currently implement the related APIs in DynamoDB) while building the global secondary indexes.
> Fix deploy of DDB with ContributorInsightsSpecification

- localstack/services/awslambda/invocation/lambda_models.py
- localstack/services/awslambda/provider.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/awslambda/test_lambda.snapshot.json
Quick cleanup following #7284 :
1. Added basic parity tests covering the basic CRUD (put = create/update) scenario for function concurrency
2. Re-use `get_account_settings` instead of relying on outdated duplicated code
> Lambda: remove duplicate code for account usage

- localstack/utils/bootstrap.py
`HOST_TMP_FOLDER` has been deprecated with 1.0.0, but the CLI still sets the environment variable to avoid breaking the usage of the legacy directory mode (where this env var is still be used).
Version 1.3.0 introduced proper deprecation warnings when deprecated environment variables are used (see #7197).
This caused the following deprecation warning on every startup of localstack with the CLI:
```
WARN --- [  MainThread] localstack.deprecations    : HOST_TMP_FOLDER is deprecated (since 1.0.0) and will be removed in upcoming releases of LocalStack! Please remove this environment variable.
```
This PR changes the container configuration by the CLI such that by default (if the legacy directory mode is not set), the `HOST_TMP_FOLDER` is also not set. It is only set if the legacy directory …
> only set HOST_TMP_FOLDER (deprecated) for legacy directories

- localstack/services/sqs/provider.py
This PR enables us to call sqs.receive_message with `max_number_of_messages -1` to receive all messages of the queue.
> return all messages for sqs queue in case max_number_of_message equals -1

- localstack/config.py
- localstack/deprecations.py
- tests/unit/conftest.py
Whenever we start localstack we're greeting with this warning message:
```
WARN --- [  MainThread] localstack.deprecations    : DEFAULT_REGION is deprecated (since 0.12.7) and will be removed in upcoming releases of LocalStack! LocalStack now has full multi-region support. Please remove this environment variable.
```
This happens even if we don't have the environment variable `DEFAULT_REGION` set.
This is because in `localstack/config.py` the check for the environment variable has a side effect of creating it if the environment variable is not set!
Later on the detection `log_deprecation_warnings()` checks kick-in and detect that the environment variable is set and issue the warning.
With this commit we're avoiding creating the environment variable.
See …
> prevent DEFAULT_REGION's deprecation message to always show

- .circleci/config.yml
- localstack/constants.py
- localstack/services/awslambda/invocation/docker_runtime_executor.py
- localstack/services/awslambda/invocation/lambda_models.py
- localstack/services/awslambda/invocation/lambda_service.py
- localstack/services/awslambda/lambda_api.py
- localstack/services/awslambda/packages.py
- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- tests/integration/awslambda/functions/hot-reloading/nodejs/handler.mjs
- tests/integration/awslambda/functions/hot-reloading/python/handler.py
- tests/integration/awslambda/test_lambda_developer_tools.py
For efficient lambda development, we have to provide an easy solution to hot reload lambda functions, especially those of interpreted languages (like python and nodejs).
However, we want to make it available for all managed runtimes.
It should also only reset the environments if a change is detected, to prevent unnecessary initializations.
* Change of the default hot-reloading bucket marker, from `__local__` to `hot-reload`. The current provider will continue to support the `__local__` marker for now, the new one will only support the new one. Would move the deprecation to 1.4 and the removal to 2.0.
* Add hot-reloading support
* Allow VolumeBind objects to be used directly in docker client, and add option for read only mounts (necessary for hot reloading)
* Add test for hot reloading …
> Add hot reloading for new lambda provider

- localstack/services/stepfunctions/packages.py
Bump `stepfunctions-local` package to version 1.12.0
> Bump stepfunctions-local package to version 1.12.0

- localstack/config.py
- localstack/services/kinesis/kinesis_mock_server.py
- localstack/services/kinesis/packages.py
See https://github.com/etspaceman/kinesis-mock/releases/tag/0.3.0
This adds the UpdateStreamMode API, as well as updates to a few other request/response bodies with information from the stream mode. 
Also see https://docs.aws.amazon.com/kinesis/latest/APIReference/API_UpdateStreamMode.html
> Update Kinesis Mock to 0.3.0

- localstack/utils/crypto.py
Small fix to check that the content of the downloaded SSL cert file is non-empty, to make the startup more reliable. Discovered this issue during a time of bad network connectivity, where the SSL cert file was created on disk, but the download failed and hence the file had empty content.
```
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 585, in create_ssl_cert
return generate_ssl_cert(cert_pem_file, serial_number=serial_number)
File "/opt/code/localstack/localstack/utils/sync.py", line 101, in _wrapper
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/crypto.py", line 70, in generate_ssl_cert
cert_file_name, key_file_name = store_cert_key_files(target_file_tmp)
File "/opt/code/localstack/localstack/utils/crypto.py", line 50, in …
```
> [minor] Check SSL cert file content to make startup more reliable

- localstack/services/awslambda/invocation/docker_runtime_executor.py
- localstack/services/awslambda/packages.py
- tests/integration/awslambda/test_lambda_developer_tools.py
We want to be able to watch arbitrary paths to allow hot reload, for more advanced features, like layer hot reloading.
* Update LRI to v0.1.8-pre to get support for specifying arbitrary paths to be watched for changes (and reloading after a change)
* Skip the whole test class instead of just a test, as it seems to fit better for the functionality
Depends on localstack/lambda-runtime-init#8
> Allow more flexibility for lambda hot-reloading paths

- localstack/config.py
- localstack/services/cloudformation/service_models.py
Changed the scope of the PR to only disabling the calls to resolve_refs_recursively in `GenericResourceModel`. It can be re-enabled via a feature flag if someone experiences any issues.
> Disable resolve_refs_recursively in GenericResourceModel by default

- localstack/services/stepfunctions/provider.py
- setup.cfg
- tests/integration/test_stepfunctions.py
Add lock for StepFunction creation to prevent concurrency issues. This issue surfaced while deploying a Terraform script with N number of copies of the same state machine, which then resulted in the following error:
```
botocore.errorfactory.InvalidDefinition: An error occurred (InvalidDefinition) when calling the
CreateStateMachine operation: Invalid State Machine Definition: ''DUPLICATE_STATE_NAME: Duplicate State name:
MissingValue at /States/MissingValue', 'DUPLICATE_STATE_NAME: Duplicate State name: Add at /States/Add''
```
Added a simple test that creates a number of state machines in parallel.
> Add lock for StepFunction creation to prevent concurrency issues

- tests/integration/test_ses.py
The messages were previously sorted before comparing with the snapshot, but something got lost in a failed merge commit in the past and missed. This PR adds the missing message sorting before comparing with the snapshot to prevent flaky test runs.
- fix: sort messages before comparing with raw email
- refactor: extract sorting function
> Fix missing message sort in SES tests

- localstack/cli/profiles.py
For Python 3.7 compatibility, we need to remove the walrus operator from `cli/profiles.py`. This seems to have evaded our CLI tests as it is imported and called outside of the `cli` creation.
> remove walrus operator from profiles.py

- localstack/http/asgi.py
- tests/integration/s3/test_s3.py
- tests/unit/http_/test_asgi.py
This PR adds a band-aid for the issue described in https://github.com/pallets/werkzeug/issues/2558.
It should fix/address (cc @bentsku @pinzon)
* #6588
* #7247
* #7256
The problem manifested mostly in S3 pre-signed POST, where the combination of payloads larger than the buffer size in werkzeug's [MultiPartParser](https://github.com/pallets/werkzeug/blob/eef696b15c5e9fc20ed718f6685a3f21f2fbc3b8/src/werkzeug/formparser.py#L348) would force chunking, and further down the line would cause the issue described in the upstream issue report I linked.
I added a unit test, which created the following traceback:
```
File "/home/thomas/workspace/localstack/localstack/tests/unit/http_/test_asgi.py", line 222, in app
for k, file_storage in request.files.items():
File …
```
> fix asgi/wsgi werkzeug compatibility for multi-part uploads

- tests/integration/test_terraform.py
Marks two notoriously flaky tests as xfail to avoid having to restart the CI all the time.
There seem to be a few other apigw related flakes still detected by CircleCI: https://app.circleci.com/insights/github/localstack/localstack/workflows/main/tests?branch=master 
/cc @calvernaz
> Mark flaky terraform tests as xfail

- localstack/services/awslambda/event_source_listeners/dynamodb_event_source_listener.py
- localstack/services/awslambda/event_source_listeners/kinesis_event_source_listener.py
- tests/integration/awslambda/test_lambda_integration_dynamodbstreams.py
- tests/integration/awslambda/test_lambda_integration_kinesis.py
LS multiplies the timestamps for `ApproximateCreationDateTime` (dynamodb) and `approximateArrivalTimestamp` (kinesis) by 1000, so it is provided in milliseconds.
This is, however, not what AWS does, there the value is a posix timestamp, so in seconds. For kinesis, it has millisecond precision, but the integer part still represents seconds.
So basically, the correct formats would be:
kinesis:            `1671562498.449` (currently `1671562498449.0`)
dynamodb:     `1671562498.0` (currently `1671562498000`)
Also, the encryptionType should not be present in the kinesis records of the lambda event. This is basically a repetition of #3346 .
Kinesis provides a hint here: https://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetRecords.html . It says the value has `millisecond precision`, …
> Fix stream event source dates for kinesis and dynamodb streams

- localstack/services/awslambda/packages.py
With #6603 we removed the `"sqs": True` part of sqs payloads.
While this is correct in terms of parity, this broke the lambda-java-utils (https://github.com/localstack/localstack-java-utils) library we use for local lambda execution, which depended on that attribute.
* The new version of localstack-java-utils uses an attribute which is supposed to be in the payload to determine SQS events, which fixes the execution of these handlers in LocalStack.
It is not a good fix, since we should not rely on the data layout for this, but it fixes the regression.
Fixes #6995
Relevant localstack-java-utils PR: localstack/localstack-java-utils#98
> Update lambda java lib to 0.2.22

- localstack/services/stepfunctions/packages.py
Until we have the new stepfunctions implementation ready we're stuck on 1.7.9 since we want to avoid adding additional 300MB+ to our final image size. 
Fortunately the reverted PR was not affecting anything yet since we're not actively using the version string to get the respective files from the image. 
To update the code used for the stepfunctions execution one needs to update the `SFN_IMAGE_LAYER_DIGEST` (see related comment in `localstack/services/stepfunctions/packages.py`).
> Revert stepfunctions package change #7347

- localstack/services/ses/provider.py
- tests/integration/test_ses.py
- tests/integration/test_ses.snapshot.json
This PR adds support for propagating custom tags when sending emails through to SNS.
Note: as per discussion with the reporter, we are focusing on custom tags at this stage. If required we will add the aws-added tags in a follow up PR.
Closes #7323
> SES: publish custom email tags

- localstack/services/awslambda/invocation/docker_runtime_executor.py
- tests/integration/awslambda/test_lambda_developer_tools.py
We already got multiple requests (e.g. https://discuss.localstack.cloud/t/nodejs-remote-debugging-with-provider-override-lambda-asf/185/2) for the flag to be supported again, as it is used in multiple debugging setups.
* Allow lambda docker flags to be present again
* Add test to developer tools which verifies the correct usage (of at least the environment flag)
> Support lambda docker flags in the asf provider

- localstack/utils/aws/message_forwarding.py
- tests/integration/test_events.py
- tests/integration/test_events.snapshot.json
This issue arose in a support ticket.
When passing a message from the `default` event bus of EventBridge to a custom one with a rule, we would first `json.loads` the event `Details` then pass it down the chain for it to be sent again through `put_events` if the target was an event bus. However, we would not `json.dumps` it again after it being decoded, so we would try to send a `dict` in the `put_event Entries` parameter, which would raise a silent exception. 
See here for the code decoding the JSON details before calling `localstack.services.events.provider.process_events` which calls `localstack.utils.aws.message_forwarding.send_event_to_target` where the fix is:
https://github.com/localstack/localstack/blob/05aa3907cd2166823ee2bb10d145227e8383115b/localstack/services/events/provider.py# …
> fix passing event from default eventbus to custom eventbus

- localstack/services/awslambda/api_utils.py
- localstack/services/cloudformation/engine/entities.py
- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/models/cloudformation.py
- localstack/services/cloudformation/models/iam.py
- localstack/services/cloudformation/provider.py
- localstack/services/cloudformation/stores.py
- tests/integration/cloudformation/resources/test_lambda.py
- tests/integration/cloudformation/resources/test_legacy.py
- tests/integration/templates/template28.yaml
- tests/unit/test_cloudformation.py
The goal here is to untangle the resources, methods, modules, etc. a bit and reduce complexity.
Removing circular dependencies here allows us to properly add types in the `template_deployer` to facilitate further refactoring efforts.
- Move Stack, StackChangeSet, StackSet, StackInstance from `provider.py` to separate file
- Remove dependencies from those moved classes to any other cfn modules. Fix circular dependencies
- Temporarily disable (commented out) `Stack.nested_stacks`. If the pipeline is green this will be removed in a follow-up PR.
- Stack outputs are resolved *once* after applying changes. `Stack.outputs_list` has been removed (functionality moved to `template_deployer.resolve_outputs` temporarily.
- Grouped stack set operations in `provider.py` and moved to the end of the …
> CFn refactoring pt.3

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
This PR removes the base64 decoding of binary message attributes in SQS, as the parser would already take care of this.
We can see a reproducible example in #7381 
The parser takes care of it here:
https://github.com/localstack/localstack/blob/162a21f993ba565b6b748e5ba491262d214a4550/localstack/aws/protocol/parser.py#L292-L293
And the type of the `BinaryValue` is defined in the specs as:
```json
"Binary":{"type":"blob"},
```
```json
"BinaryValue":{
"shape":"Binary",
"documentation":"<p>Binary type attributes can store any binary data, such as compressed data, encrypted data, or images.</p>"
}
```
Now that the SQS legacy provider has been deleted, we can safely assume all requests are "ASF parsed". 
_fixes #7381_
> remove base64 decoding of SQS Binary msg attributes already done by ASF parser

- localstack/config.py
- localstack/services/awslambda/invocation/docker_runtime_executor.py
- localstack/services/awslambda/invocation/executor_endpoint.py
Co-authored by @dominikschubert 
The new lambda provider requires bi-directional communication (host <=> lambda container), which breaks host mode in macOS because the lambda container is not reachable via IPv4 in bridge mode.
Hence, invoking any lambda fails while the lambda container waits for an invocation (i.e., during `"blocking the credentials service"`) after a connection timeout with the error `Connection to 172.17.0.2 timed out.`
Enable new lambda provider: `PROVIDER_OVERRIDE_LAMBDA=asf`
Relevant test case: `tests.integration.awslambda.test_lambda.TestLambdaFeatures.test_invocation_type_request_response`
> Docker Desktop can’t route traffic to Linux containers. However, if you’re a Windows user, you can ping the Windows containers. (Source: Docker [I cannot ping my …
> Add dev config flag for fixing lambda invoke on macOS in host mode

- localstack/services/cloudwatch/provider.py
Companion PR for [fix in moto upstream](https://github.com/spulec/moto/pull/5793#issuecomment-1362168672).
It can be merged before we update moto-ext: we now filter for a specific class, but the name of the class didn't change.
> use only MetricDatum to show in raw-endpoint for cloudwatch

- localstack/aws/forwarder.py
- localstack/aws/protocol/op_router.py
- setup.cfg
- tests/integration/test_moto.py
- tests/unit/aws/protocol/test_parser.py
- tests/unit/aws/test_service_router.py
[boto/botocore](https://github.com/boto/botocore) recently changed the endpoint detection: https://github.com/boto/botocore/commit/357d5a81311b9c63286423b64d54ff3d6b99534b
These changes (which are contained in [`botocore==1.28.0`](https://github.com/boto/botocore/releases/tag/1.28.0)) break some of the internal APIs we are using for testing and for our forwarding API (because the endpoint parameter became mandatory).
This PR aims at adjusting to these changes.
> fix internal botocore API usage

- localstack/services/apigateway/integration.py
- localstack/services/apigateway/templates.py
- localstack/utils/aws/templating.py
- tests/integration/test_apigateway.py
- tests/unit/test_apigateway.py
- tests/unit/test_templating.py
This PR tackles the escape javascript function used on VTL templates by not "double" encoding strings.
I also converted a new test to be AWS-validated.
For example,
```
#set( $body = $input.json("$") )
#define( $loop )
{
#foreach($e in $map.keySet())
#set( $k = $e )
#set( $v = $map.get($k))
// previously $k and $v weren't wrapped on double-quotes, because of the bug, however it's required (validated on AWS)
"$k": "$v"
#if( $foreach.hasNext ) , #end
#end
}
```
or issues like 
```
""proxy"":
""test""
```
It also organises the step functions integration tests using parameters to ensure APIs are deployed between changes. The previous tests was not working on AWS since an update to REST APIs needed to be deployed.
Resolves https://github.com/localstack/localstack/issues/7188
> VTL escape javascript 

- localstack/services/logs/models.py
- localstack/services/logs/provider.py
- tests/integration/test_logs.py
- tests/integration/test_logs.snapshot.json
This PR tackles the new API for resource tagging in cloudwatch logs, which was not yet implemented.
It is part of a fix for https://github.com/localstack/localstack/issues/7378.
The implementation relies on https://github.com/localstack/localstack/pull/7086 where the botocore/boto3 lib is upgraded.
The PR includes:
* new store for logs
* implementation of new resource-tagging APIs
* override old tagging APIs (previously handled by moto), for easier accessing of tags (both APIs should return the same output)
* snapshot test
**TODO**
> implement resource tag api for cloudwatch logs

- localstack/services/internal.py
- tests/unit/http_/test_dispatcher.py
HEAD query support was disabled as part of the refactoring in #4883.
It used to be supported by the following implementation.
```python
def handle(self, method, path, data) -> Optional[Dict]:
if method == "GET":
return self.get(path, data)
if method == "POST":
return self.post(path, data)
if method == "PUT":
return self.put(path, data)
return {}
```
When using LocalStack in a Docker environment, third-party tools like `wait-for-200` might be used to probe the readiness of the LocalStack service. And some of these tools use HEAD queries by default. In such environments, upgrading from an older version of LocalStack might break some pods accidentally and it's not straightforward to debug because you can only see the following output in your LocalStack logs:
```
2022-11-29T09:03:01.545 ERROR …
```
> Make /health support HEAD query again

- localstack/services/cloudformation/api_utils.py
- localstack/services/cloudformation/deployment_utils.py
- localstack/services/cloudformation/engine/entities.py
- localstack/services/cloudformation/engine/policy_loader.py
- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/engine/template_preparer.py
- localstack/services/cloudformation/models/apigateway.py
- localstack/services/cloudformation/models/dynamodb.py
- localstack/services/cloudformation/models/elasticsearch.py
- localstack/services/cloudformation/models/iam.py
- localstack/services/cloudformation/models/kinesisfirehose.py
- localstack/services/cloudformation/models/opensearch.py
- localstack/services/cloudformation/models/s3.py
- localstack/services/cloudformation/models/secretsmanager.py
- localstack/services/cloudformation/models/sqs.py
- localstack/services/cloudformation/models/ssm.py
- localstack/services/cloudformation/models/stepfunctions.py
- localstack/services/cloudformation/provider.py
- localstack/services/cloudformation/service_models.py
- tests/integration/cloudformation/resources/test_sqs.py
- tests/unit/test_cloudformation.py
- Remove `PLACEHOLDER_RESOURCE_NAME` and `GenericBaseModel.get_resource_name`
- Use full resource type names everywhere (e.g. `AWS::SQS::Queue` instead of `SQS::Queue`)
- Use `GenericBaseModel.logical_resource_id` instead of `GenericBaseModel.resource_id`
- Move non-engine utils to `api_utils.py` (like in lambda)
- Move policy loading to `policy_loader.py`
- Remove `nested_stacks` as mentioned in a previous PR
> CFn refactoring Pt.4

- localstack/config.py
- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
Adding a simple check for `MaxNumberOfMessages` in `ReceiveMessage`. It came up while having a look at #7397.
> SQS - MaxNumberOfMessages check

- .github/workflows/pro-integration.yml
- setup.cfg
- tests/integration/cloudformation/resources/test_legacy.py
This PR addresses issues with our dependency on pyOpenSSL / cryptography by removing the exact pin on `pyOpenSSL`.
[Recent ASF Update action runs](https://github.com/localstack/localstack/actions/runs/3820397617/jobs/6498675594) failed, but also the normal build pipeline will be affected:
```
File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/runpy.py", line 1[9](https://github.com/localstack/localstack/actions/runs/3820397617/jobs/6498675594#step:8:10)4, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/runner/work/localstack/localstack/localstack/aws/scaffold.py", line …
```
> upgrade pyopenssl to 23.0.0

- localstack/utils/analytics/client.py
- localstack/utils/analytics/publisher.py
This PR adds code to correctly reuse HTTP connections in the analytics client when possible.
Previously, every analytics event would create a new HTTP connection, leading to an excessive amount of new connections on the analytics endpoint. [`requests.Session` does keep-alive by default](https://requests.readthedocs.io/en/latest/user/advanced/?highlight=keep%20alive#keep-alive), so simply using the session object is enough to enable client-side keep alive. The default flush interval of the analytics client is 10 seconds, and it looks like connections are kept this long (or longer) by ELB.
I checked by setting the `urllib3` log level to DEBUG, and observed that fewer connections are created when sending analytics events. Here's what to look for in the log:
```
2022-12-31T01:53:20.000 DEBUG …
```
> add HTTP connection reuse for analytics client

- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
It seems we had a flaky test run here: [circleCI run](https://app.circleci.com/pipelines/github/localstack/localstack/11427/workflows/da8762f4-382a-4346-baf5-a57e5a5ffb4f/jobs/79436/tests)
We had an issue before where we would delete the subscription after failing to deliver. This test checks for this regression.
What we do is we create an SNS topic, set a subscription with an SQS queue, test that it works, then delete the queue.
It should then fail to publish. We then waited 1 second (now 3) before setting a `RedrivePolicy` with a dead letter queue to then try publishing again and see that it arrives in the DLQ. 
What happens apparently is that 1 second is not enough, and that the asynchronous publishing part took more than 1 second, which made the message arrive in the DLQ because it …
> fix SNS flaky test test_subscription_after_failure_to_deliver

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/provider.py
- tests/integration/cloudformation/api/test_stacks.py
- tests/integration/cloudformation/api/test_stacks.snapshot.json
Add support for the CloudFormation `update-termination-protection` API (this is a requirement that has come up recently with a CDK stack that relies on this functionality). The PR also adds a simple snapshot test.
> Add support for CloudFormation update-termination-protection

- localstack/services/apigateway/provider.py
Minor change to improve parity for API Gateway response shapes. Resolves ASF serializer warning messages like:
```
2023-01-03T19:31:47.160  WARN --- [   asgi_gw_0] l.aws.protocol.serializer  : Response object Authorizer contains a member which is not specified: _links
```
On a general note, it seems that we can simplify and remove the `to_response_json(..)` utility function - in the past, it seemed to be a requirement to include `"_links"` response elements (as per the API GW docs), but this attribute is not present in the standard responses returned by real AWS. Seems like we can get rid of it (as this is anyway already taken care of by the serializer)..? /cc @alexrashed @thrau
> minor: Improve parity for API Gateway response shapes

- localstack/services/cloudformation/deployment_utils.py
extend CFn deployment utility to add the ability to avoid transforming child parameters.
> extend cloudformation deployment utility

- localstack/utils/docker_utils.py
This PR adds the `remove=True` flag for `container_port_can_be_bound` because it was not cleaning up after testing if a port is free.
> remove container after running container_port_can_be_bound

- CODEOWNERS
This PR sets the current codeowners of S3 and SQS.
Primary owners s3: @bentsku 
Secondary: @macnev2013 
Secondary owner of SQS: @baermat
> update s3 and sqs codeowners

- setup.cfg
This new post release of Moto-ext contains 2 fix/features:
- https://github.com/localstack/moto/pull/62
- https://github.com/localstack/moto/pull/63
Allowing those 2 LocalStack PR to build on top:
- https://github.com/localstack/localstack/pull/7408
- https://github.com/localstack/localstack/pull/7409
Which will fix 2 bugs/feature requests. 
Note: I'll cherry pick this commit in the 2 PR to try running the CI pipeline, to check if everything is good.
> bump moto-ext to 4.0.12.post3

- localstack/services/s3/presigned_url.py
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/unit/test_s3.py
This PR fixes #7424 
The issue stems from the fact that the host header contains subdomains, which moto mistakes for a virtual host addressed request. 
Some patches were skipped while migrating S3 to ASF.
Thanks for the `S3VirtualHostProxyHandler`, those patches are now greatly simplified as we know for sure that requests forwarded to moto are path addressed in 100% of cases. And if they don't pass through, ASF could not parse them anyway. 
I've created a small test case which would fail before the fix.
> fix ASF S3 issue when host header has subdomains

- localstack/services/dynamodb/utils.py
- tests/unit/test_dynamodb.py
Added a fallback to dynamodb get_key_schema() when the KeySchema information is not present in the Memory Store.
The `table_definition` object that is being used in memory is only filled in by the `create_table` and `update_table`, meaning that when LocalStack restarts, the object are not re-populated. This function will then always fail without this fallback.
Alternatively, this could be a part of the start up by querying all the tables on start up and populate the `table_definitions` dictionary, although I haven't had the time to figure out exactly where that logic would fit.
This PR aims to overcome the latest reports in https://github.com/localstack/localstack/issues/7118.
> Avoid DynamoDB "Unknown table" error in BatchItemWriter after LocalStack restart

- localstack/http/client.py
- localstack/http/proxy.py
- localstack/http/request.py
- tests/unit/http_/test_proxy.py
This PR updates `HttpClient` and `Proxy` to make it possible to re-use underlying HTTP client connections. By introducing session, we also need to introduce `close` at every level of abstraction. I also added the contextmanager pattern where possible. The added test demonstrates that the underlying session is used correctly.
> update httpclient and proxy to allow connection re-use

- tests/integration/awslambda/test_lambda.py
- tests/integration/awslambda/test_lambda.snapshot.json
Follow up from lambda permission PR https://github.com/localstack/localstack/pull/7336
Having an AWS-validated test case ready is useful for implementing actual permission policy logic.
> Add lambda permission behavior test

- tests/integration/awslambda/test_lambda_common.py
- tests/integration/awslambda/test_lambda_common.snapshot.json
Our new provider provides the option to use runtime wrapper scripts per default but it was never tested with a test.
Add test for supported al2 runtimes for creating and using a runtime wrapper script. The recommended way would be using a layer for this but without layer support the wrapper has to be shipped with the deployment archive.
Related to #7442.
> Add lambda runtime wrapper test for ASF provider
