localstack/localstack

- localstack/cli/localstack.py
- localstack/utils/bootstrap.py
Currently, we never properly create the directory specified by `config.VOLUME_DIR`. This can lead to permission errors, if docker creates this folder (and any missing parents) as root.
The default configuration for the CLI is one of these cases, where `~/config/localstack/volume` is created as root, which leads to `~/.config/localstack` not being writable as non root user which in turn leads to problems for `localstack status docker` (due to some cache files being written to that directory).
Try to `mkdir` the `VOLUME_DIR` directory (and its parents) instead of letting docker do so, failing non-fatally.
An error message will be printed, but the docker start is not prevented.
> Fix CLI cache permissions by creating volume dir before mounting

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/models/iam.py
- tests/integration/cloudformation/resources/test_iam.py
- tests/integration/cloudformation/resources/test_iam.snapshot.json
- tests/integration/templates/iam_access_key.yaml
Addresses #6861
Changes:
**Note:** at the moment it's not possible to track the changes in the Serial value to trigger a key rotation.
> add support for CFn IAM::AccessKey update

- CODEOWNERS
- localstack/services/stores.py
- localstack/testing/pytest/fixtures.py
- tests/unit/test_stores.py
This PR adds a new descriptor protocol to mark certain store attributes as cross-account. This will be used for resources like S3 bucket names, DNS names, etc. which must be unique across all region and all accounts.
This will also be useful for the new internal AWS client. For services that allow resource-level IAM policy attachment, it is possible to retrieve the resources by the ARN. The ARN uniquely identifies the resource -- it has the account ID and region as part of itself. This makes using the `CrossAccountAttribute` suited for such resources, and furthermore allows operations to support resource operations based on ARNs.
Closes localstack/localstack-ext#1132
> Cross-account attributes for Stores

- localstack/services/sns/models.py
- localstack/services/sns/provider.py
- localstack/services/sns/publisher.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
AWS recently added a new feature to SNS (around end of November 22), concerning the `FilterPolicy` of subscriptions.
Previously, when filtering messages going to be fanned out to subscribers, we could only filter on `MessageAttributes`. However, this was a limitation especially between their own integrations: S3 notifications for example. You don't have a say in how the event looks, and can't add message attributes.
They introduced the `FilterPolicyScope` subscription attribute, and you can now choose between `MessageAttributes` (the default) and `MessageBody`. This will require the body to be a parsable JSON string, but you can now filter based on the message body.
You can read more with examples here:
https://aws.amazon.com/blogs/compute/introducing-payload-based-message-filtering-for-am …
> add SNS FilterPolicyScope MessageBody

- localstack/deprecations.py
- localstack/services/edge.py
- localstack/utils/server/proxy_server.py
- tests/unit/test_edge.py
- tests/unit/test_proxy.py
This PR replaces the Legacy Edge Proxy `EDGE_PROXY_FORWARDING` with a new TCP proxy edge component.
Previously, if the `EDGE_PORT` is a privileged port (<1024), the legacy edge proxy has been started with elevated privileges and the `EDGE_FORWARD_URL` set to the non-privileged `EDGE_PORT_HTTP`. This short-circuits the edge proxy to just behave as a transparent proxy to the `EDGE_FORWARD_URL`.
In order to migrate to the new HTTP gateway (and away from any usage of the `ProxyListener` implementations), this proxy mechanism is replaced by a new "component" (alongside the "edge" and the "dns" component).
This component just performs a TCP-level forwarding to the port given in the `EDGE_FORWARD_URL` (to provide backwards-compatibility).
Related to: …
> replace legacy edge proxy forwarding with TCP proxy edge component

- localstack/services/apigateway/templates.py
Fixes an issue where the VTL template headers would be returned with a serialized python object instead of a dict. 
Note: werkzeug.datastructures.Headers object is dict casting compatible -
> fix: return headers correctly inside a VTL template in apigateway

- localstack/services/kms/models.py
- localstack/services/kms/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_kms.py
- tests/integration/test_kms.snapshot.json
While adding #7448, it came out that I could pass a KMS Key ARN with a different region to `DescribeKey` and it would still return the key with the same ID but from the request context region, disregarding the region contained in the ARN. I've added snapshotted test to validate behaviour and improve the parity a bit while fixing this behaviour. 
I'm not fond of using the `Store` `_region_name` and `_account_id` attributes, but with the current logic implemented in the store itself (and thus no access to the `RequestContext`), it makes it a bit difficult to change.
> add more validation when creating KMS keys and improve parity

- localstack/aws/protocol/parser.py
- tests/unit/aws/protocol/test_parser.py
This PR sets the default timestamp format when parsing query strings timestamps to "iso8601".
When analyzing the responses for the not/implemented coverage tests, I found that a parser issue occurs for `iot` and relates to the timestamp.
I tested the operation `ListAuditMitigationActionsTasks` with different timestamp formats (also using `awscli`) and it seems like it will [always be converted](https://github.com/boto/botocore/blob/develop/botocore/serialize.py#L597) to a date in [iso8601 format](https://github.com/boto/botocore/blob/develop/botocore/serialize.py#L430). 
The operation does not have a `timestampFormat`defined in its shape, and would default to unix-timestamp. But also the unix timestamp is converted in botocore before sending the request:
```
$ awslocal iot …
```
> change default timestamp format for querystring

- tests/integration/awslambda/test_lambda_whitebox.py
- tests/integration/cloudformation/test_cloudformation_ui.py
- tests/integration/test_apigateway.py
- tests/integration/test_events.py
- tests/integration/test_firehose.py
- tests/unit/services/test_internal.py
- tests/unit/utils/test_common.py
This PR is the start list of tests to migrate from using the `ProxyListener`.
This PR mostly refactors tests using the `ProxyListener`, to use pytest `httpserver` fixture instead.
We also had some tests validating the CloudFormation UI to help deploy a template, which is migrated into a `Resource` test and an integration test in the CloudFormation test module.
There still some usage of `ProxyListener` via `testutil#proxy_server` method, but it tests its internals and will be removed once we fully remove it.
- `testutil.py#proxy_server (test utils function)`
-  used in `TestRouterListener` which is migrated
- used in `TestAwsApiListener` which can be deleted
- used in `LocalstackResourceHandler` which is migrated
- `TestLocalstackResourceHandlerIntegration#test_fallthrough#RaiseError(ProxyL …
> remove ProxyListener in tests

- localstack/packages/api.py
Minor: Add package/version information in installer exception message. This can help with debugging if `NoSuchVersionException` instances are caught and printed in the logs. 👍
> Minor: Add package/version information in installer exception message

- localstack/config.py
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- localstack/testing/pytest/fixtures.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR introduces a validation issue reported in #7177 
However, I'll introduce this feature behind a feature flag to not slow down users not creating KMS keys while testing. It will need an entry in the docs once merged.
To enable this feature, the user needs to set `S3_SKIP_KMS_KEY_VALIDATION=0`. 
This PR will check the existence of the KMS key provided in `PutObject`, `CopyObject` and `CreateMultipartUpload` operations. A next step in a following PR would be to also validate it in `PutBucketEncryption` if it is done in AWS. 
This PR allowed us to uncover some bugs in KMS implementation of `DescribeKey`, see #7463, which might allow to reuse the error message of KMS. 
_fixes #7177_
edit: doc PR here: https://github.com/localstack/docs/pull/440
> add kms key validation in ASF S3 with feature flag

- localstack/services/cloudformation/provider.py
- localstack/services/visitors.py
Fixes https://github.com/localstack/localstack-ext/issues/1278.
CFN deviates from the standard pattern when it comes to the `AccountRegionBundle` module (normally, `localstack.services.<service>.models`; `localstack.services.cloudformation.stores` instead).
In addition, `GetTemplateSummaryOutput` was containing unspecified members. I filtered the result with the `select_from_typed_dict` utility function.
> CFN - special case for store location

- setup.cfg
Seems we're encountering errors in CI because a 3rd party release is broken at the moment: `amazon-kclpy`.
https://github.com/awslabs/amazon-kinesis-client-python/commit/2642ae73edd72cb2c0c70ca448294577a3702995
https://github.com/awslabs/amazon-kinesis-client-python/compare/v2.0.6...v2.1.0
Pinning the version to the previous release until it is fixed. 
Two failed build:
https://app.circleci.com/pipelines/github/localstack/localstack/11871/workflows/4346b802-95f8-4e54-a9c9-2cba836635fe/jobs/83637
https://app.circleci.com/pipelines/github/localstack/localstack/11869/workflows/f24b9c21-d3e1-41bc-823a-edd4ac4b88b7/jobs/83635
I could reproduce locally the issue as well.
```python
Failed to build amazon-kclpy
Installing collected packages: [...redacted, too long of a list]
Running setup.py …
```
> workaround: fix amazon_kclpy build failure by pinning previous version

- localstack/services/route53resolver/provider.py
- tests/integration/test_route53resolver.py
- tests/integration/test_route53resolver.snapshot.json
While checking the non-implemented coverage responses, I found a weird error for `list_firewall_domain_lists`:
```
exception while calling route53resolver.ListFirewallDomainLists: Traceback (most recent call last):
File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
File "/opt/code/localstack/localstack/aws/handlers/service.py", line 122, in __call__
handler(chain, context, response)
File "/opt/code/localstack/localstack/aws/handlers/service.py", line 92, in __call__
skeleton_response = self.skeleton.invoke(context)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
return self.dispatch_request(context, instance)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
result = …
```
> fix list_firewall_domain_lists

- localstack/services/apigateway/helpers.py
- tests/integration/test_apigateway.py
Minor: Pass `providerARNs` to API Gateway authorizer entity on OpenAPI import.
This resolves a customer issue where an API endpoint with Cognito authorizer - imported from OpenAPI/Swagger spec - could not be invoked because no user pools are associated with the API:
```
pool, user = self._lookup_user(invocation_context)
File "localstack-ext/localstack_ext/services/apigateway/authorizers.py", line 96, in _lookup_user
raise Exception(f"Unable to find user {username} in configured user pools: {providers}")
Exception: Unable to find user test in configured user pools: []
```
TODO: Probably still going to add a test for this functionality (upstream in -ext) - would make sense, given our current focus to increase the level of testing/parity. 👍
> Minor: Pass providerARNs to API GW authorizer on OpenAPI import

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This issue was brought up in #7492 
`CompleteMultipartUpload` would not raise an exception when the parts were not ordered in the `MultipartUpload.Parts` parameter. 
Added snapshotted test cases against AWS + the validation in the provider operation. 
_fixes #7492_
> add validation for multipart upload order

- localstack/services/cloudformation/engine/entities.py
- localstack/services/cloudformation/engine/template_deployer.py
- tests/integration/cloudformation/test_template_engine.py
- tests/integration/cloudformation/test_template_engine.snapshot.json
- tests/integration/templates/dynamicparameter_ssm_string.yaml
Fix resolving SSM stack parameters in CloudFormation `!Sub` references. This issue has surfaced in a user SAM template that used a `AWS::SSM::Parameter::Value<String>` stack reference in an ARN reference that was constructed via a `!Sub` (`Fn::Sub`) intrinsic function.
* update template deployer logic to allow resolving `AWS::SSM::Parameter::Value<String>` references in `!Sub` CloudFormation intrinsic functions
* encapsulate the resolution of `AWS::SSM::Parameter::Value<String>` stack parameters in a single `resolve_ssm_parameter_value(..)` utility function
* add a snapshot test to ensure parity with AWS
* a few minor refactorings, f-strings, etc
Overall, working on this PR has highlighted again that stack parameters are in a pretty bad state, unfortunately :/ (as we …
> Fix resolving CFn SSM stack parameters in !Sub references

- localstack/services/awslambda/invocation/lambda_models.py
- localstack/services/awslambda/invocation/lambda_service.py
- localstack/services/awslambda/invocation/version_manager.py
- localstack/services/awslambda/provider.py
- localstack/utils/testutil.py
- tests/integration/awslambda/test_lambda_api.py
- tests/integration/awslambda/test_lambda_api.snapshot.json
- tests/integration/cloudformation/resources/test_lambda.py
Test + implement revisions (i.e., RevisionId) for lambda in general (with versions, 
aliases, layers, etc). It seems that the revision id of permissions is 
the same as for qualified lambdas (i.e., VersionFunctionConfiguration).
- Follow-up from https://github.com/localstack/localstack/pull/7336
- Mentioned in skip_snapshot_verify and TODO comments at multiple places
- CloudFormation tests also mentions: “seems the revision id of the policy actually corresponds to the one of the function version”
- [CreateFunction](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html): **[RevisionId](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#API_CreateFunction_ResponseSyntax)** The latest updated revision of the function or alias.
- Non-matching revision id …
> Lambda revisions

- localstack/config.py
- localstack/services/cloudformation/models/apigateway.py
- localstack/services/cloudformation/models/awslambda.py
- localstack/services/cloudformation/models/certificatemanager.py
- localstack/services/cloudformation/models/cloudformation.py
- localstack/services/cloudformation/models/cloudwatch.py
- localstack/services/cloudformation/models/dynamodb.py
- localstack/services/cloudformation/models/ec2.py
- localstack/services/cloudformation/models/elasticsearch.py
- localstack/services/cloudformation/models/events.py
- localstack/services/cloudformation/models/iam.py
- localstack/services/cloudformation/models/kinesis.py
- localstack/services/cloudformation/models/kinesisfirehose.py
- localstack/services/cloudformation/models/logs.py
- localstack/services/cloudformation/models/opensearch.py
- localstack/services/cloudformation/models/redshift.py
- localstack/services/cloudformation/models/s3.py
- localstack/services/cloudformation/models/secretsmanager.py
- localstack/services/cloudformation/models/sns.py
- localstack/services/cloudformation/models/sqs.py
- localstack/services/cloudformation/models/ssm.py
- localstack/services/cloudformation/models/stepfunctions.py
- localstack/services/cloudformation/service_models.py
In #7149 (nearly a month ago) this has been disabled by default, since we had the hypothesis that it is actually redundant. We haven't had to make use of the fallback flag since, so it is safe to assume that we can finally remove it.
This PR now cleans up all the resource models by removing the corresponding calls as well as the implementation itself.
> Remove unused CFn resolving

- localstack/extensions/api/extension.py
Adds a method to the Extension interface to hook into the shutdown procedure of LocalStack.
> add on_platform_shutdown method to extension interface

- localstack/services/ssm/provider.py
- tests/integration/test_ssm.py
- Patched get and delete operations for `maintenance_window` from moto to handle `DoesNotExistException`.
- Tests inside `terraform-provider-aws/internal/service/ssm/maintenance_window_test.go` file were timing because of unhandled retrieval from dict exception in moto - which caused overall terraform test suite pipeline to timeout for SSM service.
- `awslocal ssm get-maintenance-window --window-id mw-00000000000000000`
> fixed: ssm maintenance_window get/delete with exception

- localstack/services/s3/notifications.py
- localstack/services/s3/s3_listener.py
- tests/integration/s3/test_s3_notifications_eventbridge.py
This issue comes from a support ticket.
The `request-id` for an S3 notification to EventBridge would hard coded, which prevented them to check for duplicate events.
Adds a simple fix + small test.
> randomly generate request-id for S3 notification events

- localstack/aws/forwarder.py
- localstack/services/apigateway/provider.py
- tests/integration/test_forwarder.py
- tests/integration/test_moto.py
moto currently does not implement API Gatway's "UpdateMethodResponse" operation (which is invoked with an HTTP PATCH request):
https://github.com/getmoto/moto/blob/173e1549c06e3bdea110bd5222ed09307867a923/moto/apigateway/responses.py#L222-L254
The raised exception in moto translates to a status code `500` ("Internal Server Error") in the HTTP response in the client, even though it should raise a `501` ("Not Implemented"). This slight difference can cause issues, f.e. with IaC tools like Terraform.
This PR introduces a new feature in the fallback dispatching logic (and therefore to the `MotoFallbackDispatcher`) which allows the primary provider to avoid a fallback, but actually raise the 501 to the client.
This is used in the API Gateway provider to define the `update_method_response` …
> fix APIGW UpdateMethodResponse error response code

- localstack/services/internal.py
- localstack/utils/config_listener.py
- tests/integration/test_config_endpoint.py
Relates to #7465
We're adding a migration path to `ConfigUpdateProxyListener(ProxyListener)`
It currently allows to update the config with a POST on `/?_config_`, and some services can set up listeners to react to the changes. 
This endpoint will be deprecated.
We can't remove the current ProxyListener and will log a deprecation message.
It currently match on `/?_config_`, a query string, which we cannot use the router to match. The new route is at `/_localstack/config-update` and make uses of `LocalstackResources`. 
\cc @thrau for the change in `LocalstackResources`
> create a new ConfigResource and deprecate /?_config_

- localstack/services/apigateway/integration.py
- tests/integration/test_apigateway.py
Adds support for stage variables. Stage variables can be used to render request mapping and request parameters.
Reference API - https://docs.aws.amazon.com/apigateway/latest/developerguide/aws-api-gateway-stage-variables-reference.html
Verified with https://github.com/localstack/localstack-terraform-samples/tree/master/apigateway-stage-variables
Implements https://github.com/localstack/localstack/issues/6928
TODO
> add apigateway stage variables support

- localstack/services/kinesis/packages.py
See https://github.com/etspaceman/kinesis-mock/releases
Specifically adds StreamARN parameter support for putRecord and putRecords. Needed for the KPL 0.15.x releases.
> Update Kinesis Mock to 0.3.2

- localstack/services/visitors.py
This PR adds tests an additional location for moto-backends that is used in `visitors.py` to determine cleanup locations.
Some services that have a name with an underscore, like `application_autoscaling` have a related moto-backend that does exclude the underscore.
Additionally, the service `ce` has a special location for the model, I also added it with this PR.
> add pattern for predicting moto-backend location

- localstack/aws/handlers/cors.py
- localstack/services/generic_proxy.py
- tests/integration/test_security.py
- tests/unit/test_cors.py
Extend allowed CORS origins to include `EDGE_PORT_HTTP` endpoint. This change ensures that the `http://localhost:4566` endpoint is in the `ALLOWED_CORS_ORIGINS` list (for Community + Pro users). 
The issue surfaced when deploying our [demo sample app](https://github.com/localstack/localstack-demo/pull/47) Web UI (HTML file) as an S3 website, and testing against LocalStack Pro: In the default Pro setup, we have `EDGE_PORT=443` and `EDGE_PORT_HTTP=4566`, and since we were previously configuring the allowed origins only via `config.EDGE_PORT`, it was not possible to access the LocalStack APIs from a website running under `http://localhost:4566` (only when using port 443).
Touching the CORS setup is always a bit finicky, but this change (1) should have no negative security side effects (we're …
> Extend allowed CORS origins to include EDGE_PORT_HTTP endpoint

- localstack/services/apigateway/integration.py
- tests/integration/test_apigateway.py
Issue #7124
https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-api-gateway.html
- https://github.com/localstack/localstack-terraform-samples/tree/master/apigateway-step-functions-integration
- https://github.com/localstack/localstack-terraform-samples/tree/master/apigatewayv2-step-functions-integration
- Passthrough templates, for cases where the input is not transformed via request templates (REST) or request parameters (HTTP)
> Improve support for ApiGW to StepFunctions service integration

- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/templates.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/apigateway/test_apigateway_kinesis.py
- tests/integration/apigateway/test_apigateway_kinesis.snapshot.json
- tests/integration/test_apigateway.py
This PR improves the integration response handling by checking if any of the status code returned by the integration is configured on API Gateway, such as:
- If there is a configuration for the status code returned by the integration, use the template (if it exists) to do the transformation
- Or if there are no configurations, return the response from the integration without transformation
- Or if there are configurations but not for the status code returned by the integration. This needs to be tested with responses for >= 400 vs 2xx
Includes snapshot testing for the kineses integration output. Tests for the API Gateway will be created at a different time with the focus on the API gateway control plane.
> improves response template handling

- localstack/aws/handlers/proxy.py
- localstack/aws/serving/edge.py
- localstack/http/hypercorn.py
- tests/unit/http_/test_hypercorn.py
This PR adds two new utility specializations of the `HypercornServer`:
- `GatewayServer` which simplifies serving a `localstack.aws.gatway.Gateway` as a `Server`.
- `ProxyServer` which serves a `Gateway` with only a `ProxyHandler`.
- The `ProxyHandler` is just a handler which forwards requests to an external system.
- This effectively means serving a HTTP/HTTPS mulitplexing proxy server.
Relates to: #7465
> add Gateway server abstraction

- localstack/services/acm/provider.py
This PR adds a patch to pickle the `CertBundle` models.
> Add patch for pickling acm certificate

- localstack/services/sns/publisher.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
This fixes an issue reported in #7529.
We've had wrong assumptions with SNS FIFO topics, we assumed that if they were set with `ContentBasedDeplication=true`, the subscribed SQS queue would have it set too, and would take care of the message deduplication. But it's actually wrong, as SNS will create a `MessageDeduplicationId` from the message content that will take precedence over the content of the SQS message, which makes sense, as we would pass a JSON encoded string from SNS to SQS, containing a timestamp, and that would defeat the purpose of the anti deduplication system.
This PR fixes this wrong assumption to be more in line with how AWS behaves, tested with snapshots. 
_fixes #7529_
> SNS FIFO topic: create MessageDeduplicationId if not provided

- localstack/aws/mocking.py
Fix for failing pipeline in `capture_not_implemented` script for pro. 
There is a new pattern `\\p{Alnum}]` used for some parameters in `sagemaker` that was not yet sanitized. 
Added additional logs to see those kind of errors quicker, e.g. in the output when the job fails.
> fix capture_not_implemented

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
An issue (#7562) has been reported when publishing to SNS FIFO topics with `TargetArn`: our validation was only for when `TopicArn` was set. For compatibility reasons, AWS allows users to use either `TargetArn` or `TopicArn` while publishing to an SNS topic. This moves the logic that used a bit later in the method to validate topics with either `TargetArn` or `TopicArn`.
_fixes #7562_
> fix validation when publishing to FIFO topic with TargetArn

- localstack/services/awslambda/invocation/docker_runtime_executor.py
- localstack/services/awslambda/packages.py
The copying of the lambda runtime init binary into the container fails, if `/var/rapid` does not exist beforehand. This does not appear in AWS provided lambda images, as the folder is already present there, but for custom images without this folder.
* Adapt the installer slightly, so the binary is stored under `<version>/<arch>/var/rapid/init`. With this, we can just copy the contents of `<version>/<arch>` to `/`, and it will create / copy all the necessary parent directories with it, circumventing that problem.
@alexrashed @baermat might be a unusual usage of the installers, tagging for reference
> Copy runtime init to container including parent folders

- localstack/services/awslambda/packages.py
Updates the init release for the ASF Lambda provider
Release notes: https://github.com/localstack/lambda-runtime-init/releases/tag/v0.1.11-pre
> Bump lambda init to v0.1.11-pre

- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
- tests/unit/test_dockerclient.py
Extend Docker client utilities (SDK-based as well as CLI-based Docker client) to accept `--label` flags in the additional flags. This is a requirement that recently came up for the [LocalStack Docker Desktop extension](https://github.com/localstack/localstack-docker-extension). /cc @HarshCasper @Pive01
The PR also contains slight refactoring of the `parse_additional_flags(..)` util function - returning a `DockerRunFlags` object, instead of a tuple with the result entries.
Tests have been extended to cover the new functionality.
> Extend Docker client to accept --label flag

- localstack/aws/protocol/service_router.py
This PR adds the internal `_pods` endpoint to our legacy cors checks, which essentially applies typical cors handling onto those routes.
Necessitated by the Pods Launchpad
> add internal pods endpoint to legacy cors check

- localstack/config.py
- localstack/services/awslambda/invocation/runtime_environment.py
- localstack/services/awslambda/invocation/version_manager.py
- By default an execution environment will now wait 10 minutes after the last invocation has been processed and stop itself afterwards. Each new invocation it receives resets this timer.
- The timeout is configurable via `LAMBDA_KEEPALIVE_MS`.
> Add keepalive period for removing unused execution environments

- localstack/services/cloudwatch/alarm_scheduler.py
When doing a reset of resources, the schedule cloudwatch alarms still assume that the alarms can be found.
Included a check which will ensure that the alarm exists.
This happens only if the backend is deleted, e.g. when running a cleanup process. I.e. when the api `delete_alarm` is used, the scheduler will be removed anyhow.
@giograno: I realized there is another `persistence` pattern for the Pro version, where we can do additional resets. 
However, the alarm-scheduler is part of the `CloudwatchProvider` and it seems tricky to do reset and I have a feeling this is a rare edge case anyhow.
Do you think it's fine to just keep the scheduler running, given that in normal setup, just deleting the backends (without restarting LocalStack) should not happen?
> Fix cloudwatch reset

- localstack/services/awslambda/lambda_api.py
- localstack/services/stepfunctions/packages.py
- tests/integration/test_stepfunctions.py
Add test for `aws-sdk:s3:deleteObject` custom SDK call tasks in StepFunctions. Depends on https://github.com/localstack/localstack-artifacts/pull/13
> Add test for aws-sdk:s3:deleteObject tasks in StepFunctions

- localstack/packages/core.py
- localstack/utils/archives.py
PR was motivated by failing downloads of ffmpeg where the Installer tries to extract the empty installer file instead of just re-trying to download the archive first. It also didn't log any meaningful exceptions in this case since it wasn't a `requests.exceptions.ReadTimeout`
* Downloads are retried up to 3 times
* Exception + retry attempt number are logged in case of a failure
* Extraction is not attempted on an empty "archive" file.
> Set download retries and log download exceptions for installer failures

- tests/integration/awslambda/test_lambda_common.py
- tests/integration/awslambda/test_lambda_common.snapshot.json
Fixes current CI failures caused by updates to the latest runtime images provided by AWS.
We could still work with some form of pinning but I feel like the stack trace is inherently too brittle for a full snapshot comparison.
> Ignore stack trace in lambda exception tests

- localstack/services/plugins.py
- localstack/services/providers.py
This PR adds a factory for creating `Service` instances for ASF providers.
Through the `MotoFallbackDispatcher` we lost the reference the original provider instance. Basically there was no way to use the `ServicePluginManager` to iterate over the provider instances. This is however necessary for the state visitor pattern to work correctly. Providers need to be able to implement the `accept_state_visitor` method, and some higher-order mechanism needs to collect all provider instances and call the method on them. Now this can be the `Service` instance, since the `Service` can delegate the call to the `_provider` attribute it now holds.
So basically what this will enable down the road is
```python
for service in SERVICE_PLUGINS:
service.accept_state_visitor(visitor)
```
It also creates a …
> add factory for ASF service providers

- localstack/services/opensearch/provider.py
This PR fixes an issue that would prevent opensearch persistence to restore clusters properly under certain conditions.
`OpensearchProvider.get_store()` relies on having a request context, but when we're restoring the cluster through `restore_backend_state`, we don't have that.
Conveniently, we have the account and the region information in the `DomainKey`, so we just use that.
> fix opensearch store access in create_cluster method

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- #7541 
- Patched `ListBucketsOutput` to `ListAllMyBucketsResult`.
- In boto spec definition of output from `ListBuckets` is `ListBucketsOutput` whereas AWS is returning  `ListAllMyBucketsResult`.
- `list_objects` contains `ListBucketResult` object whereas we are returning `ListObjectsOutput` 
```
Start localstack instance with env `PROVIDER_OVERRIDE_S3: "asf"`
```
Comparing the response from this commands will po
`list_bucket`
```
awslocal s3api list-buckets --profile ls --debug
```
```
aws s3api list-buckets --profile ls --debug
```
`list-objects`
```
awslocal s3 mb s3://test-bucket --profile ls --region us-east-1 --debug
awslocal s3api list-objects --bucket test-bucket --profile ls --region us-east-1 --debug
```
```
aws s3 mb s3://test-bucket --profile ls --region us-east-1 --debug …
```
> fix: rename list bucket/object reponse class

- localstack/config.py
- localstack/services/awslambda/provider.py
Introduces the option to mirror the previous "simplified" behavior where the `Lambda.CreateFunction` API call now blocks until the created function/version is in a non-transitional state (e.g. it will be either `Active` or `Failed`).
This feature is only available via an optional feature flag, since it technically breaks behavior parity with AWS.
Intended primarily for people getting started when only using CLI/SDKs and for easier friction-less migration paths from the old to the new provider.
> Add support for LAMBDA_SYNCHRONOUS_CREATE flag

- Dockerfile
This PR addresses issues with the latest version of npm:
- [node 18.14.0 has been released on 2023-02-02.](https://nodejs.org/fr/blog/release/v18.14.0/)
- This minor release of node upgrades the shipped npm version from version 8.19.3 to 9.3.1.
- npm v9 contains a breaking change: It will no longer attempt to modify the ownership of files it creates.
- https://github.com/npm/cli/pull/5704
This PR ensures that all files created in the LPM step of the Docker build are in fact owned by the `localstack` user / group.
Fixes #7620
> fix npm ownership issues

- localstack/http/__init__.py
- localstack/http/dispatcher.py
- localstack/http/resource.py
- localstack/http/response.py
- localstack/http/router.py
- localstack/services/internal.py
- localstack/services/ses/provider.py
- localstack/services/sns/provider.py
- localstack/services/sqs/provider.py
- localstack/services/sqs/query_api.py
- localstack/utils/config_listener.py
- tests/integration/services/test_internal.py
- tests/integration/test_config_endpoint.py
- tests/unit/http_/test_dispatcher.py
- tests/unit/http_/test_resource.py
- tests/unit/http_/test_router.py
The main goal of this PR is to enable the migration of `/_pods` endpoints into the `/_localstack` namespace, without having to refactor the current pods endpoints into what I'll call the "resource class pattern" (classes with `on_<http-method>` functions).
Previously, a Router needed the special `resource_dispatcher` to make the resource class pattern work, meaning it was not possible to mix the use of `@route` endpoints with the resoure class pattern. The changes in this PR get rid of the special `resource_dispatcher` all together. The way we should think about this is that, dispatchers are responsible for *how* functions are called (i.e., how the request parameters are unpacked into the method call), and rules are responsible for *which* functions are called. So instead of having the …
> refactor router to enable resource class pattern via rules

- localstack/http/client.py
- localstack/http/proxy.py
- localstack/services/s3/virtual_host.py
- tests/unit/http_/conftest.py
- tests/unit/http_/test_hypercorn.py
- tests/unit/http_/test_proxy.py
- tests/unit/logging_/__init__.py
This PR fixes several issues with our proxy framework, namely:
- **Forwarding of streamed requests (HTTP 1.1 streaming using `Transfer-Encoding: chunked`):**
- Incoming streamed requests have the header `Transfer-Encoding: chunked` and no `Content-Length` header.
- The forwarding currently does not support forwarding the stream itself, therefore it loads the data in memory and sends the request (just as the legacy gateway did), but it did not reset the `Transfer-Encoding` header or set the `Content-Length`.
- **Preserving the `Host` header of the origin client:**
- The `SimpleRequestsClient` solely used the `Host` header to determine the host part of the target URL.
- The proxy has to preserve the `Host` header because it might be used by backend services to build URLs which should be …
> fix streaming and header handling for proxies

- localstack/config.py
This healthcheck inside the image times out after 5 seconds (https://github.com/localstack/localstack/blob/434b9eb2daaf27a5dda6e1c6f75e56d7958fe3f8/Dockerfile#L268)
The ping command used to determine bridge IP has a timeout of 10 secs on each IP (2 of them) that it attempts.
Net result is that if localstack is running in a docker daemon that doesn't respond to the first IP that gets pinged then the service is going to be marked as unhealthy.
This PR sets a timeout of 2 secs on each ping so that it will still allow the healthcheck command to finish even when the bridge IP determination logic couldn't find docker daemon. Because if and when the IP is valid... it doesn't take that long so if it hasn't worked by 2 secs then it's unlikely going to work by 10 secs.
> Avoid triggering healthcheck failure which times out after 5s

- localstack/services/ses/provider.py
- tests/integration/test_ses.py
This PR migrates the internal endpoint to retrieve emails sent by SES from `/_localstack/ses` to `/_aws/ses`.
The old endpoint is still routed, but on each invocation a deprecation warning is logged.
This PR is based on https://github.com/localstack/localstack/pull/7614 (since it refactors the resource routing quite a lot).
> migrate internal SES endpoint

- localstack/services/cloudformation/engine/template_preparer.py
- localstack/services/cloudformation/engine/yaml_parser.py
- tests/integration/cloudformation/api/test_nested_stacks.py
- tests/integration/cloudformation/api/test_nested_stacks.snapshot.json
- tests/integration/cloudformation/api/test_stacks.py
- tests/integration/cloudformation/api/test_update_stack.py
- tests/integration/cloudformation/test_template_engine.py
- tests/integration/templates/nested-stack-outputref/root.yaml
- tests/integration/templates/nested-stack-outputref/sub1.yaml
- tests/integration/templates/nested-stack-outputref/sub2.yaml
- tests/integration/templates/simple_api.update.yaml
- tests/integration/templates/sns_topic_parameter.update.yml
- tests/unit/test_misc.py
The previous YAML parsing had an issue with parsing this: `!GetAtt Sub1.Outputs.OutputA` which led to the parameter being passed empty.
This also touched code that I recently refactored and I continued there to refactor the yaml parsing a bit to be cleaner & more robust. This also only uses the yaml module now without other external libs.
- Rewrote YAML parsing of cloudformation templates which also now includes a fix for !GetAtt short hand parsing
- Added validated parity test for a simple reproduction sample with snapshots
- Fixed a unit test that had an invalid assertion. (This was already broken on master but didn't evaluate to false because yaml loader was globally patched when the cloudformation module was loaded in other tests)
> Fix !GetAtt with Outputs from Nested Stacks

- localstack/http/router.py
- tests/unit/http_/test_router.py
This PR refactors the `route` decorator, as well as the `_RuleAttriburtes` handling a bit, such that the `route` decorator can be used multiple times on a single function / endpoint.
> allow using route decorator multiple times on single endpoint

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/patches.py
- localstack/services/apigateway/provider.py
- tests/integration/apigateway/test_apigateway_api.py
- tests/integration/apigateway/test_apigateway_api.snapshot.json
- tests/integration/test_apigateway.py
- tests/integration/test_apigateway_api.py
This PR introduces and migrates some current API Gateway tests to a new file structure, and those are AWS validated. The focus of this PR is the `RestAPI` resource. 
The end goal is to remove most of the moto patches contained in `localstack/services/apigateway/patches.py` if those can be part of the ASF provider (some makes sense to stay, as they directly interact with the moto backend and would be harder to implement, those will be migrate to use `@patch`), and to improve parity on basic CRUD operations of the provider.
> work on APIGW parity for RestAPI resource, remove patches

- localstack/services/s3/presigned_url.py
- tests/integration/s3/test_s3.py
While working on a support case, I've seen an Exception raises while trying to check a pre-signed URL with the new S3 ASF provider. The logic was inverted and we trying to replace a string with `None` parameter, which failed. 
This PR fixes the issue and removes an old xfail for this specific case that was fixed a while ago. I've added a new case for when we don't have the port (which was actually failing for the new provider). 
Also added a fix for the CI failure ([see here the run](https://app.circleci.com/pipelines/github/localstack/localstack/12466/workflows/18f7ea07-662a-4d7c-8862-9e5d3491a3c2/jobs/89244)), it seems the host header was wrong for the signature calculation, weird that nothing picked it up before.
> fix S3 ASF pre-signed port permutation logic

- localstack/aws/protocol/serializer.py
- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
While working on different support tickets, it appeared Serverless had an issue saying that the deployment bucket would not be in the same region as the lambda, while it was. By debugging Serverless adding `console.log` statement around, I've realized we were missing a newline return after the XML preamble, which was added in the old S3 provider for some responses (especially `LocationConstraint`). 
I've added it to the serializer, and in the `GetBucketLocation` as well, as it's a bit specific: it does not have the usual root tag, so I've declared it as a `payload` as a workaround. Problem is, we don't parse the response from moto, we pass its response "as-is", so we need to add the newline manually. It's a bit of an odd case, so I suppose we should not modify the serializer for something …
> add newline after XML preamble for S3 (fix serverless issue)

- localstack/services/ec2/models.py
Changes introduced in https://github.com/localstack/localstack/pull/7629/ caused failures in the persistence test suite:
```
2023-02-08T18:11:42.280 DEBUG --- [   asgi_gw_0] l.utils.persistence        : Unable to read pickled persistence file /home/viren/repo/localstack/.filesystem/var/lib/localstack/state/api_states/ec2/backend.state: 'Subnet' object has no attribute 'cidr'
```
During unpickling, the `__init__()` is not called which meant that `self.cidr` did not exist. This prevented the persisted state from being restored.
This PR fixes this so that `cidr` from the state is used to create `_subnet_ip_generator`.
> EC2: Fix attribute not initialised in Subnet instance during unpickling

- localstack/config.py
- localstack/services/providers.py
`PROVIDER_OVERRIDE_S3=v2` is now equivalent to setting `PROVIDER_OVERRIDE_S3=asf`
> Add v2 service provider "alias" for S3

- localstack/services/apigateway/helpers.py
For REST APIs defined with OpenAPI, [`x-amazon-apigateway-any-method`](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-any-method.html) is used as catch-all placeholder
This change addresses the following failing tests:
```
2023-02-09T00:11:50.6643127Z FAILED ../localstack/tests/integration/test_apigateway.py::TestAPIGateway::test_create_rest_api_with_custom_id[path_based_url]
2023-02-09T00:11:50.6643884Z FAILED ../localstack/tests/integration/test_apigateway.py::TestAPIGateway::test_create_rest_api_with_custom_id[host_based_url]
2023-02-09T00:11:50.6644620Z FAILED ../localstack/tests/integration/test_apigateway.py::TestAPIGateway::test_api_gateway_lambda_asynchronous_invocation
2023-02-09T00:11:50.6645333Z FAILED …
```
> APIGW: catchall using x-amazon-apigateway-any-method

- .pre-commit-config.yaml
- localstack/testing/pytest/fixtures.py
- setup.cfg
Our current flake8 version seemed to have problems with python 3.10 dict structural decomposition. In -ext, the following code:
```
match something:
case {"AWS": a_variable}:
print(a_variable)
```
Raised a name not found error to a_variable, as it could not detect the assignment.
* Update flake8 to 6.0.0
* Update isort to 5.12.0
* Update all flake8 dependencies to their current version
* Update flake8 + isort in the precommit hooks (this is the reason why isort has to be updated, the older version could not be installed anymore with poetry, issue: https://github.com/PyCQA/isort/issues/2077
Not sure if we want to leave the version ranges that open for now. Any opinions? A breaking change should at least be a quick fix and instantly detectable.
superseding #7208
> Update flake8 and isort dependencies

- localstack/config.py
- localstack/http/proxy.py
- localstack/services/es/provider.py
- localstack/services/opensearch/cluster.py
- localstack/services/opensearch/cluster_manager.py
- localstack/services/opensearch/packages.py
- localstack/services/opensearch/provider.py
- tests/integration/test_opensearch.py
This PR extends the OpenSearch and ElasticSearch service such that it supports enabling the security plugin for OpenSearch domains.
This first iteration supports the internal user database, there is no integration with IAM yet (might be implemented in later iterations, based on user feedback). Currently, only OpenSearch domains are supported. ElasticSearch domains are currently not supported (neither via the OpenSearch nor the ElasticSearch service).
A secured OpenSearch domain can be spawned with this example CLI input:
```json
{
"DomainName": "secure-domain",
"ClusterConfig": {
"InstanceType": "r5.large.search",
"InstanceCount": 1,
"DedicatedMasterEnabled": false,
"ZoneAwarenessEnabled": false,
"WarmEnabled": false
},
"EBSOptions": {
"EBSEnabled": true,
"VolumeType": "gp2", …
```
> add OpenSearch SecurityPlugin configuration

- setup.cfg
A new version was published recently ([2.1.1](https://pypi.org/project/amazon-kclpy/#history)).
The tests previously worked fine, but let's see if this will make it more stable again :thinking:
> Avoid installing amazon_kclpy>=2.1.0

- localstack/services/cloudformation/models/route53.py
- tests/integration/cloudformation/resources/test_route53.py
- tests/integration/templates/route53_hostedzoneid_template.yaml
The TTL should be accepted either as a string or int.
Changes:
- Convert attribute to integer if it's a string
- Altered one test to validate the behavior
- mark the test as AWS validated
> Fix CFn Route53 Record Set TTL

- localstack/services/awslambda/lambda_starter.py
- localstack/services/providers.py
This PR adds a `ServiceLifecycleHook` for the legacy lambda provider. This is to properly register lambda function URLs when persistence restores the service state, and will help in pro to unify persistence behavior into lifecycle hooks.
For community this has to significant effects other than the routes being registered a bit earlier now.
> use lifecycle hook for registering lambda function URL routes

- localstack/aws/handlers/partition_rewriter.py
- localstack/http/client.py
- localstack/http/proxy.py
- localstack/http/request.py
- localstack/http/router.py
- tests/unit/http_/test_proxy.py
- tests/unit/test_partition_rewriter.py
This PR addresses several encoding issues:
- `get_raw_base_url` now avoids multi-encoding by avoiding the usage of `werkzeug.sansio.utils.get_current_url`.
- `SimpleRequestsClient` now avoids multi-encoding by avoiding the usage of `werkzeug.sansio.utils.get_current_url`.
- `Proxy` uses the encoded path of the given request (instead of the decoded one) if no `forward_path` is given.
- `Router` now matches on the encoded path (instead of the decoded one).
- This is a quite fundamental change, but it is necessary, because otherwise the encoding information is lost for parsed path parameters (f.e. when using `/<path:path>`).
- `ArnPartitionRewriteHandler` now uses the correct forward path (the modified one, instead of the original one).
- `ArnPartitionRewriteHandler` does not decode string …
> fix encoding issues in router, proxy, partition rewriting

- localstack/services/sns/provider.py
- localstack/services/sns/publisher.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
After reading the report from #7662, I could not understand how this could happen when we were filtering the messages before passing the context to worker to send the message. If after filtering there were no messages to send, we would not pass the task to the executor, so no empty message entries could be passed to SQS.
However, after reading the publishing code again for `PublishBatch`, it showed that I was setting the filtered messages (messages are filtered on a subscriber basis) on the global context (used by all subscribers). It created 2 issues:
- First, if in the order of subscription, we have a subscription with a filter then one without filter, we would filter the message and set them in the global context, so the next subscription in line would not have any messages in its …
> fix SNS PublishBatch modifying batch context for all subscribers after filtering

- localstack/services/awslambda/invocation/docker_runtime_executor.py
It's quite hard to find the container you're looking for when just looking at the list of running/exited containers right now since we just assign the randomly generated executor ID as a container name and one has to actually check the container metadata/config to find out which lambda is being executed in it.
Resolves #7635
- Changed default container name from generic executor ID (e.g. `ffa532cb281182ee92052ff97e1f37c4`) to the following pattern: `<main-container-name>-lambda-<function-name>-<excecutor-id>`
- example: `localstack-main-lambda-processing-ffa532cb281182ee92052ff97e1f37c4`
We could make this more generic in the future by providing a config variable we'll use to format this
e.g. `LAMBDA_DOCKER_CONTAINER_NAME_GENERATOR="<main-container-name>-lambda-<region>-<function-name>-<ru …
> Use more informative container names for spawned Lambda containers

- localstack/services/plugins.py
- localstack/state/__init__.py
- localstack/state/core.py
- localstack/state/inspect.py
- tests/unit/persistence/test_inspect.py
This PR includes some minor refactoring (mostly moving and renaming) of code related to persistence, state, and the visitors.
* Introduce `localstack.state` for the state API (which are the base abstractions for disk-based persistence and pods)
* Extracted a comprehensive `StateLifecyleHook` that will be used in the future
* Made `ServiceLifecycleHook` extend from that
* let `Service` implement the `accept_state_visitor` (pre-requisite for follow-up code)
* Removed unused `BackendStateLifecycle` (now `StateLifecycleHook` as originally intended)
> refactor state visitor code and lifecycle hooks

- setup.cfg
The integration with coveralls.io is broken for a while.
After [CircleCI's incident in January](https://circleci.com/blog/jan-4-2023-incident-report/) we rotated all secrets (including the coveralls token).
The token has been updated. With this PR we also upgrade to the latest version to keep up to date.
> fix coveralls integration

- localstack/cli/localstack.py
Previously we generated a list of all images which also included images such as `localstack/localstack:<none>`, i.e. dangling images without tags assigned.
- Filter list of all images and removes any image names ending with `:<none>` before trying to update them.
- Add new new image prefix to check for updates in images used by the lambda v2 provider (`public.ecr.aws/lambda`)
Closes #7156
> Ignore dangling images in localstack update

- localstack/config.py
- localstack/utils/docker_utils.py
- tests/integration/docker_utils/test_docker.py
Closes #7681
Now allows overriding the default image that is used internally in ECS to verify we can open ports with a docker container. Previously this was statically set to `localstack/localstack` and some users might not have access to that image in their environment.
I've noticed we are also using the DOCKER_IMAGE_NAME (`localstack/localstack`) in other places as well.
Should we maybe make these constants configurable as well? :thinking:
> Allow configuration of docker image used for port checks

- localstack/testing/pytest/detect_thread_leakage.py
We've seen github actions executions fail (especially in pro), although all tests pass. This seems to be because pytest exits the interpreter with 1, because exceptions are raised in the `pytest_unconfigure` hook. This PR is just a pragmatic fix to avoid this.
here's the relevant github actions log from one of the runs. Note the  `2023-02-15T20:22:40.1435412Z ##[error]Process completed with exit code 1.` which i traced back to be the pytest runner.
```
2023-02-15T20:21:39.5009797Z Traceback (most recent call last):
2023-02-15T20:21:39.5259267Z   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/psutil/_pslinux.py", line 1645, in wrapper
2023-02-15T20:21:39.5265044Z     return fun(self, *args, **kwargs)
2023-02-15T20:21:39.5266101Z   File …
```
> guard process information pytest_unconfigure hook from exceptions

- localstack/aws/app.py
- localstack/cli/localstack.py
- localstack/constants.py
- localstack/http/hypercorn.py
- localstack/services/awslambda/lambda_api.py
- localstack/services/edge.py
- localstack/services/generic_proxy.py
- localstack/services/opensearch/packages.py
- localstack/testing/pytest/fixtures.py
- localstack/utils/analytics/metadata.py
- localstack/utils/http.py
- localstack/utils/server/proxy_server.py
- localstack/utils/ssl.py
- tests/integration/awslambda/test_lambda_legacy.py
- tests/unit/utils/test_ssl.py
This PR tries to decrease the coupling to our LocalStack Pro extensions.
It can only merged together with its companion PR.
The changes are separated in different commits:
- _remove DNS startup from community:_
- This commit removes the DNS startup from the `edge.py`. It will be started as a Pro plugin (infra start hook) instead.
/cc @dfangl 
- _refactor SSL cert handling:_
- Moves the SSL cert handling to community, since it is used and supported by community since the HTTP/HTTPS multiplexing is used (https://github.com/localstack/localstack/pull/1823).
/cc @whummer 
- _unify, move, document ext imports:_
- Documents, moves, and unifies remaining (for now tolerated) ext imports.
- _migrate serve_flask_app to only remaining using module:_
- A somewhat unrelated refactoring, moving a …
> refactor community ext imports

- localstack/services/ec2/provider.py
- tests/integration/test_ec2.py
Adds support for the `route.destination-cidr-block` filter in `EC2.DescribeRouteTables`
See: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRouteTables.html
Can be removed once https://github.com/getmoto/moto/pull/5932/files is merged upstream and we have updated our fork.
> Add support for route.destination-cidr-block filter in DescribeRouteTables

- localstack/services/awslambda/invocation/docker_runtime_executor.py
- localstack/services/awslambda/provider.py
- localstack/testing/aws/lambda_utils.py
- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- setup.cfg
- tests/bootstrap/test_cli.py
- tests/integration/awslambda/functions/lambda_introspect.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/awslambda/test_lambda.snapshot.json
- tests/integration/awslambda/test_lambda_api.py
- tests/integration/awslambda/test_lambda_api.snapshot.json
- tests/unit/test_dockerclient.py
This PR adds support for additional Docker flags and fixes ARM issues with lambda.
* Bump docker dependency version (required for supporting platform flag)
* Add user and platform flags to docker clients (SdkDockerClient and CmdDockerClient). Set platform flag based on the architecture of the lambda function
* Test ARM create function exceptions and enable ARM functions
* Respect new provider override flags (`v2`) in lambda tests
* https://github.com/localstack/localstack/issues/7637
* Resolves this issue by adding basic support for ARM Lambdas (more testing planned)
* https://github.com/localstack/localstack/pull/6724#issuecomment-1227314083
* Enables workaround `LAMBDA_DOCKER_FLAGS=--user nobody`
* https://github.com/localstack/localstack/issues/4921
* Shared ARM layers: …
> Fix docker runtime executor flags

- .github/workflows/pro-integration.yml
- localstack/packages/core.py
We're often running into rate-limits in the `GitHubReleaseInstaller` which calls the GitHub Rest API to get a list of artifacts for a given release. This is by default capped at **60 calls per hour** (per IP) for **unauthenticated** calls and any further calls currently lead to pipeline failures.
In CircleCI we're now using a custom secret (`GITHUB_API_TOKEN` which is a personal access token from @localstack-bot without any permissions). This increases the rate-limit to **5_000 calls per hour** (independent of IP)
In GitHub we're now using the intrinsic `GITHUB_TOKEN` secret. This increases the rate-limit to **1_000 calls per hour** 
(independent of IP). If we ever need a higher limit in GitHub we can also use the token, but as long as it's not necessary I feel using `GITHUB_TOKEN` is …
> Use token in GitHubReleaseInstaller for increased rate-limits

- localstack/utils/docker_utils.py
- tests/integration/docker_utils/test_docker.py
Currently, we do not allow checking privileged ports to be bound by LS. This leads to a problem with a hostport configuration in ECS for privileged ports - even if they are free.
Also, we are checking for each port we check on the host, if the port is free in the container as well. We should not do this, as we might want to use ports bound inside LS on the host as well.
* Introduce separate port ranges for ports returned by `reserve_available_container_port` and ports which can be reserved on request. Per default, the former only returns non-privileged ports, while the whole port range can be reserved on explicit request for a port
* Add additional option to override the port range for reserving available ports. This can be used to further limit the random port range, for example for ECS: …
> Allow container port binding for privileged ports

- localstack/services/cloudformation/engine/entities.py
- tests/integration/cloudformation/api/test_stacks.py
- tests/integration/cloudformation/api/test_stacks.snapshot.json
With this change the CFn Api returns the correct resource type in the stack events. Important for cli tools that rely in the stack events for progress indicators.
> fix cfn stack events resource types

- localstack/services/cloudformation/engine/template_deployer.py
@steffyP  found an issue with stack deletion when deleting a stack that contains resources with dependencies
https://github.com/localstack/localstack/issues/7703#issuecomment-1436728012
- Add retry loop around deletion of stack resources and only try to delete stack resources that are not already in a `DELETE_COMPLETE` state.
The loop is similar to the core deployment loop we already have. This retry now allows that first an independent resource is deleted and the dependent one is retried up to 10 times which is usually enough for the old one to be deleted as well.
There are of course still a few issues but they are quite out of scope like doing this asynchronously and not primarily  relying on the loop, but instead using the resource graph.
> Add retry cycles for deleting stack resources

- tests/bootstrap/test_cli.py
Re-enables a Docker CLI test that depends on the not-immediately-updated `localstack/localstack` image from Dockerhub.
Follow up from https://github.com/localstack/localstack/pull/7675
`tests.bootstrap.test_cli.TestCliContainerLifecycle.test_start_cli_within_container` depends on the latest [localstack/localstack](https://github.com/localstack/localstack/blob/ce0f939c228448eb0b4aedcd7ea6110c132243e2/tests/bootstrap/test_cli.py#L185) image from DockerHub. The test could not pass because bumping the PyPi `docker` version added an incompatibility. Specifically, a `platform` flag required for fixing ARM compatibility in lambda.
See internal [demo](https://www.notion.so/localstack/Releasing-a-change-with-conflicting-circular-dependency-8ca299173c5140bdb766b0a0512bd2d3?pvs=4)
> Re-enable cli container lifecycle test

- localstack/config.py
This seemed to misbehave previously because we sometimes mutate/set environment variables during startup.
Setting `PERISTENCE=1` will still log the deprecation warning for `DATA_DIR` even though it hasn't been explicitly set.
- Remove manual setting of `DATA_DIR` env variable when `PERSISTENCE=1`
- <s>Copy the environment directly after we finish loading any profiles. This copy is then used in when determining deprecations instead of using the current environment.</s> Talked with @alexrashed about this and we decided against this for now. Instead removed the line that was causing the specifically observed issue with the environment variable `DATA_DIR` being set manually as a fallback.
@thrau & @giograno  Do you remember why this was added? What are the potential regressions we'd be …
> Check original environment copy for deprecations

- localstack/services/apigateway/integration.py
- localstack/services/apigateway/router_asf.py
- localstack/services/apigateway/templates.py
- tests/integration/test_apigateway.py
- tests/unit/test_templating.py
This PR accomplishes two things:
1) making sure literal booleans are correctly parsed on our VTL templates. Why `ast.literal_eval` and not `json.loads`? Imagine the following case:
```
tpl = '{"key": True}' 
json.loads(tpl)
ast.literal_eval(tpl)
```
2) routes with trailing slashes are correctly handled inside APIGW router, it uses the `strict_slashes` where it's needed.
There is a comprehensive test upstream for the templating and routing issue.
> Fix apigateway authorizer path suffix

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/engine/template_preparer.py
- localstack/services/cloudformation/engine/transformers.py
- localstack/services/cloudformation/models/apigateway.py
- localstack/services/cloudformation/models/ec2.py
- localstack/services/cloudformation/models/stepfunctions.py
- localstack/services/cloudformation/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/cloudformation/api/test_transformers.py
- tests/integration/cloudformation/api/test_transformers.snapshot.json
- tests/integration/cloudformation/resources/test_ec2.py
Add initial support for CFn `Fn:Transform` intrinsic functions. This requirement came up while playing around with a more complex AWS sample app using a SAM / CloudFormation template: https://workshop.serverlesscoffee.com
For reference - part of the SAM template in the sample is a construct like this:
```
RESTApConfigService:
Type: AWS::Serverless::Api
Properties:
StageName: Prod
DefinitionBody:
'Fn::Transform':
Name: 'AWS::Include'
Parameters:
Location: '../backends/2-config-service/RestAPIs/api.yaml'
```
(the `Location` parameter is replaced with an `s3://...` URL by SAM upon deployment)
> Add initial support for CFn Fn:Transform intrinsic functions

- scripts/gather_outdated_snapshots.py
This adds a scripts that enables to gather which snapshots are older than a given date. The data is gathered within a JSON object
The data includes at the moment:
- The provided date to check the snapshot date against
- The number of outdated snapshots
- The name/node-ids of the outdated snapshots as list
- If invoked via cli, the names in a whitespace-separated string instead of a list, to make automated execution via pytest possible if wanted
> Gather outdated snapshots

- localstack/services/apigateway/router_asf.py
- tests/integration/test_apigateway_integrations.py
- tests/integration/test_apigateway_integrations.snapshot.json
This PR fixes an rest api parity issue related to encoding paths in URL.
Given the following invocation URL against a rest api (e.g., with `{proxy+}` integration and a lambda function as backend):
`GET https://{restapi_id}.execute-api.{region}.amazonaws.com/{stage_name}/user/test%2Balias@gmail.com/plus/test+alias@gmail.com?email=test%2Balias@gmail.com`
* `path`: `"/{stage_name}/user/test+alias@gmail.com/plus/test+alias@gmail.com?email=test%2Balias@gmail.com"`
* `queryStringParameters.email`: `test+alias@gmail.com`
The base `path` should not decode URL encoded characters such as `%2B => +` and looks like this in AWS: `/user/test%2Balias@gmail.com/plus/test+alias@gmail.com`
Instead of relying on decoded `request.path` or `request.full_path` from Werkzeug, we need to compose the invocation …
> Fix apigateway path encoding

- localstack/services/apigateway/context.py
- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/integration.py
- localstack/utils/aws/aws_responses.py
Refactor authorizer info in API Gateway invocation context. Companion to upstream PR.
The main changes in this PR is to rename the `auth_info` attribute and unify it with `auth_context` in the API GW invocation context
The PR also adds a few type hints across the codebase.
> Refactor authorizer info in API Gateway invocation context

- localstack/services/apigateway/integration.py
- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/patches.py
- localstack/services/apigateway/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/apigateway/conftest.py
- tests/integration/apigateway/test_apigateway_dynamodb.py
- tests/integration/apigateway/test_apigateway_dynamodb.snapshot.json
- tests/integration/apigateway/test_apigateway_kinesis.py
- tests/integration/test_apigateway.py
- tests/integration/test_apigateway_api.py
Enhance parity for API Gateway DynamoDB integrations. Follow-up from https://github.com/localstack/localstack/pull/7572
The PR also contains a few refactorings, starting to pull more of the service-specific integrations as classes into `integrations.py`
* pull out logic for Kinesis/DDB integrations into separate `KinesisIntegration` and `DynamoDBIntegration`
* add snapshot test for DDB integration
* introduce a couple more `@patch` decorators for API GW patches
* add `BadRequestException` for incorrect use of `AWS_PROXY` integration (AWS parity)
* extract generic `create_rest_api_with_integration` fixture that can used for DDB&Kinesis integration tests (and other integrations in the future)
> Enhance parity for API Gateway DynamoDB integrations

- localstack/services/apigateway/integration.py
- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/templates.py
- localstack/utils/collections.py
- tests/integration/apigateway/test_apigateway_dynamodb.py
- tests/integration/apigateway/test_apigateway_dynamodb.snapshot.json
- tests/integration/test_apigateway.py
- tests/unit/test_apigateway.py
Enable generic actions and further enhance parity for DynamoDB API GW integration. Follow-up from #7753 
So far, we had support for `dynamodb:action/PutItem` and `dynamodb:action/Query` DynamoDB integrations. While working on deploying a more complex [AWS sample app](https://github.com/aws-samples/serverless-coffee-workshop) against LocalStack, the requirements for further integration operations came up (incl. `dynamodb:action/Scan`, among others). 
* make the DynamoDB integration generic - accepting any type of valid `dynamodb:action/*` integration action that can be executed against DynamoDB
* add snapshot test for additional DynamoDB integrations (incl. `PutItem`, `Scan`)
* refactor additional `invocations.py` into separate backend classes in `integrations.py`
/cc …
> Enable generic actions and enhance parity for DynamoDB API GW integration

- localstack/services/dynamodb/provider.py
- tests/integration/test_dynamodb.py
- tests/integration/test_dynamodb.snapshot.json
This PR enables a minimal implementation for the `UpdateContinuousBackups` and `DescribeContinuousBackups` actions.
The feature of continuous backup is actually not implemented. We only return the minimum needed to achieve Terraform parity for https://github.com/localstack/localstack/issues/7569.
> Minimal implementation for continuous backup

- localstack/services/awslambda/provider.py
- tests/integration/awslambda/test_lambda_api.py
- tests/integration/awslambda/test_lambda_api.snapshot.json
This PR makes the **CreateEventSourceMapping** operation validate the **StartingPosition** parameter. Addresses #7548
Changes:
- validation
- snapshoted test
> validate StartingPosition during CreateEventSourceMapping operation

- localstack/services/apigateway/models.py
- localstack/services/apigateway/patches.py
- localstack/services/apigateway/provider.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/apigateway/test_apigateway_api.py
- tests/integration/apigateway/test_apigateway_api.snapshot.json
Work on APIGW Resource parity, improve UpdateResource parity (patch operations validation), remove moto patches to move them into provider directly (we still manipulates moto entities directly as its tightly integrated, but extend moto with our own store), and fix deleting child resources when deleting a resource that was used as a parent.
Example:
`/` -> `/pets` -> `/pets/dogs` 
We delete `/pets`, `/pets/dogs` should be deleted as well because it declared `/pets` to be its parent.
We do this by mapping children IDs when they are created with a parent ID. When deleting a resource, we check if it is in the parent list, and then recursively delete resources. 
note: I might delete the fixture for creating resource in a following PR, as we clean up all related resources when deleting the …
> improve parity for APIGW Resource

- tests/integration/awslambda/test_lambda_common.py
Greenify pipeline: Fixes a suddenly failing test case for the new lambda provider `tests.integration.awslambda.test_lambda_common.TestLambdaRuntimesCommon.test_introspection_invoke[nodejs18.x]`
https://app.circleci.com/pipelines/github/localstack/localstack/12943/workflows/a0a0ec66-a580-472f-8ae7-66a573f3a2d6/jobs/93952
Quickfix skips snapshot validation for the environment variable `NODE_EXTRA_CA_CERTS` (only occurs for nodjs18 runtime)
> Skip lambda nodejs18 extra cert snapshot verify

- localstack/services/awslambda/api_utils.py
- localstack/services/awslambda/invocation/lambda_models.py
- localstack/services/awslambda/provider.py
- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/awslambda/functions/common/echo/go/Makefile
- tests/integration/awslambda/functions/common/echo/provided/Makefile
- tests/integration/awslambda/functions/common/endpointinjection/go/Makefile
- tests/integration/awslambda/functions/common/endpointinjection/provided/Makefile
- tests/integration/awslambda/functions/common/introspection/go/Makefile
- tests/integration/awslambda/functions/common/introspection/provided/Makefile
- tests/integration/awslambda/functions/common/uncaughtexception/go/Makefile
- tests/integration/awslambda/functions/common/uncaughtexception/provided/Makefile
- tests/integration/awslambda/test_lambda.py
- tests/integration/awslambda/test_lambda.snapshot.json
- tests/integration/awslambda/test_lambda_api.py
- tests/integration/awslambda/test_lambda_api.snapshot.json
- tests/integration/awslambda/test_lambda_common.py
- tests/integration/awslambda/test_lambda_common.snapshot.json
- tests/integration/awslambda/test_lambda_destinations.snapshot.json
- tests/integration/awslambda/test_lambda_integration_dynamodbstreams.py
- tests/integration/awslambda/test_lambda_integration_dynamodbstreams.snapshot.json
- tests/integration/awslambda/test_lambda_integration_kinesis.snapshot.json
- tests/integration/awslambda/test_lambda_integration_sqs.snapshot.json
- tests/integration/awslambda/test_lambda_runtimes.py
- tests/integration/awslambda/test_lambda_runtimes.snapshot.json
- tests/integration/cloudformation/resources/test_lambda.py
- tests/integration/cloudformation/resources/test_lambda.snapshot.json
* Add support for [runtime management controls](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html) at API level
* Add support for [SnapStart](https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html) at API level
* Add snapshot tests for SnapStart API
* Update all lambda-related snapshot tests due to model updates (only for `aws_validated` tests)
* Add platform flag to docker clients for `build_image`
* Fix Lambda tests on ARM hosts. This enables running Lambda tests on ARM hosts.
* Conditionally skip the concurrency tests if the AWS account has too low limits (improve error messages).
* Runtime management controls use a hard-coded sha256 value (`8eeff65f6809a3ce81507fe733fe09b835899b99481ba22fd75b5a7338290ec1`) instead of inspecting the Docker image.
* Rust builds on …
> Add lambda model and api updates

- localstack/services/cloudformation/models/route53.py
Alias records, for example, should explicitly not have a TTL set, as it's derived from the TTL of the target.
> Catch Route53 Record Sets without TTL

- localstack/services/sns/provider.py
- localstack/services/sns/publisher.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
This PR fixes #7768, a regression introduced by remove a call to `json_safe` on the payload.
However, there was no payload to get here, because the lambda invocation is asynchronous. The parity was wrong here, and it's nice to be able to introduce additional behaviour in SNS.
I've introduced a test by retrieving CloudWatch logs for this particular scenario and improved parity.
We would still need to check parity for all other "Publisher" (SQS, Kinesis, HTTP and Platform application endpoint), to see how they store their logs. See https://docs.aws.amazon.com/sns/latest/dg/sns-topic-attributes.html
We will also need to add a conditional on storing the logs, as they should be enabled first. 
Note: I'll introduce a scenario fixture regarding setting up the logs for Success/Failure in SNS when …
> fix SNS storing lambda invocation logs + improve parity

- localstack/services/apigateway/provider.py
- tests/integration/apigateway/test_apigateway_api.py
- tests/integration/apigateway/test_apigateway_api.snapshot.json
When moving on to implement resource methods validation/removing patches, I've seen this page of the docs:
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-method-settings-method-request.html#api-gateway-proxy-resource
So I followed it to implement more validations on the previous PR #7738
Stumbled unto an interesting issue in the docs:
> An API can have more than one proxy resource. For example, the following proxy resources are allowed within an API.
```
/{proxy+}
/parent/{proxy+}
/parent/{child}/{proxy+}
```
But it's not actually allowed, as the 2 last paths have a variable part, which will throw an exception. Implemented all the validations around this example in the docs. 
Based on #7738
\cc @whummer
> improve apigw parity work for Resource proxy path

- .github/workflows/asf-updates.yml
- .github/workflows/pro-integration.yml
We have to keep the repositories updated or else we potentially get network errors.
Also because of the updated metadata we have to install a later version of postgres. This is unfortunate because it's now a moving target and likely to cause more breakages in the future, but leaving unpinned causes a dependency conflict with postgres-plpython3-14.
> Update apt repositories when installing system dependencies

- localstack/runtime/hooks.py
Adds a runtime hook used in pro and plugins that is only run when pro is activated. This makes it easier to hook in functionality that's conditionally after license activation.
> add runtime hook that runs on pro infra startup

- localstack/utils/run.py
This PR passes the `cwd` argument through the `ShellCommandThread` to the underlying `popen` command.
> add cwd parameter to ShellCommandThread

- localstack/config.py
- localstack/logging/setup.py
- localstack/services/dynamodb/provider.py
- localstack/services/kinesis/provider.py
- localstack/services/opensearch/provider.py
- localstack/services/redshift/provider.py
This PR uses the persistence API to integrate community services into the persistence lifecycle. It's "basic" because it doesn't fully add restore functionality for every services.
* added `accept_state_visitor` methods to community services that have an asset directory
* added the `SAVE_STRATEGY` variable used by the persistence plugin to the config
* I was able to add the restore functionality for opensearch (tested manually), but not for others. Those will be part of follow-up PRs once we have a good persistence testing setup.
* I also snuck in the two parameters to the opensearch `create_domain`  method that were missing after the last ASF API update /cc @alexrashed
> add persistence API integration for community services

- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
As reported in #7782, we did not check the state of the KMS key when validating it.
Note that we need to set `S3_SKIP_KMS_KEY_VALIDATION` to `0` if we want this validation to be active, as we don't validate the existence of the KMS key per default, and only in the new provider (`PROVIDER_OVERRIDE_S3=asf`). 
This PR implements the validation of the state and a AWS validated snapshot test, as well as a fix for the key format when returned (keyArn instead of just the keyId). 
_fixes #7782_
> add validation of KMS key state in S3

- tests/integration/stepfunctions/v2/scenarios/templates/path-based-on-data.yaml
- tests/integration/stepfunctions/v2/scenarios/templates/step-functions-calling-api-gateway.yaml
- tests/integration/stepfunctions/v2/scenarios/templates/wait-for-callback.yaml
- tests/integration/stepfunctions/v2/scenarios/test_sfn_scenarios.py
- tests/integration/stepfunctions/v2/scenarios/test_sfn_scenarios.snapshot.json
Adds tests based on workflow samples from [serverlessland.com](https://serverlessland.com/workflows?type=Standard&simplicity=1+-+Fundamental)
I've had to drop a lot of the samples since they were a poor fit (either too complicated or too simple and some of them didn't even properly allow testing all paths defined in the workflow definition). The rest were all simplified/fixed.
All tests are designed to be able to take a single CloudFormation template as an input with lambda code & workflow definitions being included in-line in the template.
> Add scenario tests with Fundamental level for Stepfunctions

- localstack/services/ses/provider.py
- tests/integration/test_ses.py
Resolves #7491 
Added the following endpoints:
- `DELETE _localstack/ses` requested by the issue
- `DELETE _localstack/ses?id=<message_id>` [requested in a comment](https://github.com/localstack/localstack/issues/7491#issuecomment-1414126917) 
- `GET       _localstack/ses?id=<message_id>` added to match the DELETE by id
> Add DELETE to the _localstack/ses/ endpoint

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/models.py
- localstack/services/apigateway/patches.py
- localstack/services/apigateway/provider.py
- tests/integration/apigateway/test_apigateway_api.py
- tests/integration/apigateway/test_apigateway_api.snapshot.json
- tests/integration/test_apigateway.py
This PR refactors the store of API Gateway to make use of dictionary for an easier look up of RestAPI sub-entities.
~~I've added utilities to support the use of both old restored stores and new, fresh stores, but it makes it a bit verbose.~~
This refactor will also help in the recent parity work, to move more data into our stores and add more validations.
I'm not sure how much breakage we can do with persistence, but if we can break, I'll remove the utils and just use the new store attributes directly, which will be much cleaner. If we can't break it yet, we can keep those utils to support restored state, and remove them before `v2`. I will be working on API Gateway until then, so I can undertake that effort then. 
Also cleaned up some methods that were not used anymore anywhere. 
\cc …
> apigateway - refactor store

- localstack/testing/pytest/detect_thread_leakage.py
Master build is currently red due to some threads not having the _target attribute, and the thread leakage detection therefore failing.
Check if a thread has the _target attribute before accessing it, otherwise just print `None`.
> Fix error with threads not having _target attributes

- localstack/services/dynamodb/provider.py
- localstack/services/dynamodb/server.py
This PR refactors the DynamoDB provider to use the new lifecycle hooks.
In addition, it refactors the singleton instance of the server into the provider itself. Due to these changes, the methods to start the server are not accessible at module level anymore. See related [ext PR](https://github.com/localstack/localstack-ext/pull/1435).
> DDB - persistence plugin and server rework

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/models/awslambda.py
- tests/integration/cloudformation/resources/test_lambda.py
- tests/integration/cloudformation/resources/test_lambda.snapshot.json
- tests/integration/templates/cfn_lambda_permission_multiple.yaml
A single lambda function can be associated with multiple `AWS::Lambda::Permission` resources. This was fundamentally incompatible with how the previous fetch_state "worked'. 
* Added a test for adding multiple AWS::Lambda::Permission resources for a single function
* Fixed `fetch_state` & physical resource id for `AWS::Lambda::Permission`
* Fixed overwriting `Code` properties in `AWS::Lambda::Function` which lead to unnecessary updates in certain cases
> Fix multiple AWS::Lambda::Permission for single function

- localstack/services/apigateway/helpers.py
- localstack/testing/pytest/fixtures.py
Fix to handle OpenAPI 3.0 security schemes object - https://swagger.io/specification/v3/#security-scheme-object
Terraform sample: https://github.com/localstack/localstack-terraform-samples/tree/master/apigateway-openapi-3.0-import
> fix openapi 3.0 security schemes import

- localstack/services/sqs/models.py
- tests/integration/test_sqs.py
This PR removes a duplicate slash when creating the queue url under the `path` endpoint strategy
> Remove extra slash in SQS path strategy

- localstack/services/sns/models.py
- localstack/services/sns/provider.py
- localstack/services/sns/publisher.py
- tests/integration/test_events.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
As we're currently working on persistence, I'd like to refactor the SNS store to facilitate lookup and have its data structures more aligned with how we are using them in the provider and to how AWS stores them.
Added some validations where I had questions on how AWS would behave.
> refactor SNS store to facilitate lookups

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/provider.py
- tests/integration/apigateway/test_apigateway_api.py
- tests/integration/apigateway/test_apigateway_api.snapshot.json
- tests/integration/files/openapi.spec.tf.json
A user reported an issue in the community slack channel that they could not use a Terraform module creating a RestAPI with API Gateway after 1.4.0.
Terraform was creating then updating the API, we would send a 200 status code but it would keep going (it felt like we were returning something unexpected or wrong). 
After running the user sampler and re-using the data sent by Terraform to create a snapshot AWS validated test, it seemed the version type we returned was an `int` when AWS returns a `str`. After fixing that, the user sample is running.
The snapshot test shows the lack of parity while importing an API, but some of it might be because of how we return the data, and should be fix in our parity effort. Anyway, it's a good indicator on where to focus some effort.
> fix APIGW import RestAPI version type mismatch

- localstack/services/kms/provider.py
- tests/integration/test_kms.py
- tests/integration/test_kms.snapshot.json
- tests/unit/test_kms.py
This PR is for the fix of issue #7494 
Initially, there was no validation on alias names done to create an alias. I have added the Alias name validation which would raise a ValidationException if the given alias name doesn't start with "alias/"
@bentsku You can review this.
> Fix: Alias name validator

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/patches.py
- localstack/services/apigateway/provider.py
- localstack/utils/json.py
- tests/integration/apigateway/test_apigateway_api.py
- tests/integration/apigateway/test_apigateway_api.snapshot.json
This PR reimplements the `Method` resource CRUD API, removing the patches from moto to integrate them in our provider. 
There was quite some validations on the json patch area, I will focus my time on resources where `Update*` is more often called, as those can be huge rabbit holes.
> apigw parity work resource method

- CODEOWNERS
- tests/integration/s3/test_s3.py
Just realised I wasn't tagged in a test modification in S3, so as seen with @alexrashed, updating it.
Also using a fixture in the s3 test to not leave a dangling S3 bucket.
> update s3 tests location in  CODEOWNERS

- localstack/services/events/provider.py
- tests/integration/test_events.py
Addresses #7847
Since scheduled events don't have a pattern and it defaults to a "{}" pattern, they were always unintentionally triggering the targets of the scheduled event rule when calling `put_events` (which should only consider pattern-based event rules).
To fix this we now ignore any rules that have a `scheduled_expression` set (which would otherwise default to None).
> ignore scheduled rules when processing put_events

- localstack/testing/snapshots/transformer.py
- tests/integration/awslambda/test_lambda_api.snapshot.json
- tests/unit/utils/testing/test_transformer.py
Encountered this issue when I was trying to replace a number that flaked between 0 and non-0
* Explicitly check for `None` with matched result
> Fix transformation of falsy values in KeyValueBasedTransformer

- localstack/services/apigateway/provider.py
- tests/integration/apigateway/test_apigateway_api.py
- tests/integration/apigateway/test_apigateway_api.snapshot.json
Follow up from #7749, it seems the validation was lacking and a bit too restrictive while updating Authorizers-related fields. I've added more AWS tests, this should solve our Pro pipeline (tested locally and it works).
> fix APIGW UpdateMethod authorizer validation

- localstack/services/apigateway/helpers.py
small fix to handle openapi `x-amazon-apigateway-authorizer` extension for authorizer type `TOKEN`.
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-authorizer.html
> Fix openapi authorization header for type token

- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/unit/test_dockerclient.py
Allows the `--privileged` flag to be passed in `additional_flags` when running Docker containers.
> Allow privileged mode to be passed as additional flag

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
As reported in #7861, our error message was not in parity with AWS (error thrown from moto). We now check before and raise an exception if the topic does not exist. Added a snapshot validated test.
It also shows we have a bit of work to do regarding `TopicAttributes`, regarding `DeliveryPolicy` which seems malformed.
_fixes #7861_
> fix NotFound exception for GetTopicAttributes

- localstack/services/kms/models.py
Fixes https://github.com/localstack/localstack/issues/7216
Return the public key in SubjectPublicKeyInfo format for both RSA and ECDSA keys, per the AWS documentation: https://docs.aws.amazon.com/cli/latest/reference/kms/get-public-key.html#output
> Return RSA public key in SPKI format

- localstack/services/cloudformation/engine/template_preparer.py
Currently, when trying to use the [global transform from SecretsManager](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-secretsmanager.html), the entire deployment crashes as it's assuming that we don't know that custom macro name. As the transform itself isn't entirely necessary for local development (as it's needed for secret rotation), we can currently just notify that it's not supported and continue deploying the remainder of the stack instead of crashing.
> Ignore AWS::SecretsManager-2020-07-03 transform

- localstack/services/s3/virtual_host.py
- tests/integration/s3/test_s3.py
While testing lambda transparent endpoint injection, @thrau came across the issue that we were too restrictive with our domain matching. This is also part of @simonrw #7774, and should simplify the logic concerning matching on external hostname. @whummer also came across the new provider issue at the same time today.
This PR is building on the new test Waldemar implemented, and add more scenarios where we should properly match the route. This should be merged right after #7868.
~The only question I have is: is `s3.localhost.localstack.cloud:{edge_port}` always resolvable from LocalStack? Or is it safer to target `localhost` when proxying the request to ourselves? I'd rather target `s3.localhost.localstack.cloud:{edge_port}` as the service parser will match more effectively against S3 than …
> improve S3 vhost matching on any domain

- localstack/services/motoserver.py
- localstack/services/s3/virtual_host.py
- tests/integration/s3/test_s3.py
Fix S3 routing in moto to allow upload of `favicon.ico` files.
This issue surfaces primarily for hostname-based bucket addressing for Pro users with DNS integration, if an S3 client is making a request to `<bucket>.s3.amazonaws.com` domains.
Moto defines the [following logic](https://github.com/getmoto/moto/blob/fe8d30ae6329878053a3ae980ed424c737fd8cec/moto/moto_server/werkzeug_app.py#L163-L164) to handle `/favicon.ico` paths as a special case:
```
if path_info.startswith("/moto-api") or path_info == "/favicon.ico":
host = "moto_api"
```
On a general note, I think we should verify if the routing to `<bucket>.s3.amazonaws.com` domains (i.e., defined via the `Host` HTTP header) is properly supported in the new S3 provider (for the different combinations of path-/host-based addressing). This …
> Fix S3 routing in moto to allow upload of favicon.ico files

- bin/docker-entrypoint.sh
This PR removes the legacy `/docker-entrypoint-initaws.d` in favor of the modern [Init hooks](https://docs.localstack.cloud/references/init-hooks/) according to our [deprecation notice of v1.3](https://github.com/localstack/localstack/issues/7257).
> remove legacy init scripts /docker-entrypoint-initaws.d

- localstack/services/providers.py
Since we currently have been advertising the newer provider implementations as `v2`, users might try to "revert" to the legacy provider by setting the `PROVIDER_OVERRIDE_<svc>` variable to `v1`. Unfortunately this will currently fail since they need to remove the variable completely.
This PR now introduces v1 aliases for the legacy (currently still default) providers with a `v2` provider, i.e. `lambda`, `s3` and `stepfunctions`
cc @bentsku @dfangl
> Add v1 provider aliases for legacy providers

- localstack/services/edge.py
- localstack/services/s3/s3_listener.py
- localstack/services/s3/s3_starter.py
- tests/integration/test_edge.py
This PR removes the immediate use of the `LEGACY_EDGE_PROXY` config flag. Dead code removal can happen at a later point.
> remove use of LEGACY_EDGE_PROXY

- localstack/aws/handlers/cors.py
- localstack/aws/protocol/service_router.py
- tests/integration/s3/test_s3_cors.py
Currently in the process of trying to create some sample concerning CORS configuration of S3, and making a small sample allowing people to create their own CORS rules for their bucket but still allowing the `app.localstack.cloud` / resource browser to access it, I've encountered an issue with the `ListBuckets` operation. 
S3 is a "self-managed" CORS service, as it can manage the CORS setting of its buckets. However, the `ListBuckets` operation is not configurable, and should be using the default CORS setting of LocalStack. I've added a check in our general CORS handler to not skip setting CORS headers if the operation is `ListBuckets`. 
While creating the test, I've also found that if you try to access `http://localhost:4566`, it should return `ListBuckets`, but our service name parser …
> add ListBuckets into general CORS handling

- localstack/services/cloudwatch/alarm_scheduler.py
- localstack/services/cloudwatch/provider.py
CloudWatch is using a scheduler, that should check if an alarm state should change periodically.
* The scheduler should be restarted and check all existing metric-alarms for the `on_*_load` scenario.
* The scheduler should also be restarted for the `on_*_reset` scenario
> fix scheduler start/stop for persistence

- localstack/services/kms/models.py
- localstack/services/kms/provider.py
- localstack/services/kms/utils.py
- tests/integration/test_kms.py
- tests/integration/test_kms.snapshot.json
This PR is based on investigation done by @paullallier in https://github.com/localstack/localstack/issues/6815#issuecomment-1458573903
LocalStack KMS Sign and Verify operations were double hashing the message payloads. This PR reworks these operations to rely on `cryptography` to perform hashing if required based on the value of `MessageType` argument.
The integration tests are also refactored to make the correct assertions.
Also checked that signatures produced by KMS:Sign can be correctly verified with OpenSSL (i.e. outside of the KMS:Verify operation).
```
$ cat msg.txt
hello world
$ awslocal kms create-key --key-spec RSA_4096 --key-usage SIGN_VERIFY
{
"KeyMetadata": {
"AWSAccountId": "000000000000",
"KeyId": "54ec6e0d-7356-4b08-897c-26eb7b134939",
"Arn": …
```
> KMS: Fix double hashing during sign/verify operations

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/provider.py
- tests/integration/apigateway/conftest.py
- tests/integration/apigateway/test_apigateway_common.py
- tests/integration/apigateway/test_apigateway_common.snapshot.json
- tests/unit/test_apigateway.py
We had a wrong assumption when using a `RequestValidator` and validating the body of a request. If a method did not have a `requestModel` set, we would reject the request. However, AWS uses the default `Empty` model. We now follow the same logic.
We also did not have validation for validators before, and would return an empty response if no validators existed with that ID. Now, in parity with AWS, it raises an exception instead of returning `None`.
However, that case should not happen because it's not possible to delete an existing `RequestValidator` if it's used by a `Method` in AWS. I'll try to implement this behaviour in following PR. 
We needed to change the code in `invocations.py` to reflect the change when checking if a request is valid.
note: created a `test_apigateway_common`, …
> fix validator and model check during invocation

- tests/integration/test_logs.py
- tests/integration/test_logs.snapshot.json
While adding persistence test for logs, I found that the validation for this test is actually misleading, as it didn't check the lambda-logs which should ensure the actual invocation
> fix validation in test for put-subscription-filter with lambda

- localstack/testing/snapshots/transformer.py
- tests/unit/utils/testing/test_transformer.py
Fixes a small edge case encountered when writing tests for xray with a SortingTransformer where SubSegments can be nested. The value of the detected entry is now also further transformed.
> Fix SortingTransformer for nested input

- localstack/testing/snapshots/prototype.py
When updating or creating new snapshots, an error when serializing the new snapshot previously lead to the complete removal of the file's content.
By moving `truncate` to after the JSON serialization, an error here will now simply leave the old state as it was instead of leaving behind an empty file.
> Fix deletion of file content on snapshot error

- localstack/aws/handlers/fallback.py
- tests/integration/aws/test_app.py
This PR adds logic to our fallback exception handler to render werkzeug HTTPException instances.
Previously, calling internal resources (or custom routes that would not be detected as s3 routes) with wrong methods would output:
```json
{
"error": "Unexpected exception",
"message": "405 Method Not Allowed: The method is not allowed for the requested URL.",
"type": "MethodNotAllowed"
}
```
because it interprets the `MethodNotAllowed` exception as unexpected exception. with this new logic that generalize capturing of werkzeug HTTP exceptions, you can actually raise HTTP exceptions from within handlers, and get proper exception messages:
```json
{
"error": "Method Not Allowed",
"message": "The method is not allowed for the requested URL."
}
```
Unfortunately, because the service name parser …
> add an exception handler to serialize werkzeug HTTPException

- localstack/services/apigateway/models.py
- localstack/services/apigateway/provider.py
- tests/integration/apigateway/test_apigateway_api.py
- tests/integration/apigateway/test_apigateway_api.snapshot.json
This PR implements the validation when deleting a `Model` resource: it will check if it's in use in any Method of the RestAPI, and it is, will reject the call. This allows us to not have any integration calling a non existing Model anymore. 
This logic will also be applied to `RequestValidator`, and maybe some other resources. We will extract the logic then into something more general when applying it to other resources.
> implement apigw Model validation if in use by a Method

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
Small fix that makes sure there's no exception when sns unsubscribe is called twice (which happens a decent amount of times in tests).
Logs had quite a few of these errors:
```
2023-03-17T16:38:29.4143947Z ------------------------------ live log teardown -------------------------------
2023-03-17T16:38:29.4144724Z 2023-03-17T16:38:29.412 ERROR --- [   asgi_gw_3] localstack.aws.handlers.logging : exception during call chain
2023-03-17T16:38:29.4146180Z Traceback (most recent call last):
2023-03-17T16:38:29.4146706Z   File "/home/runner/work/localstack/localstack/localstack/localstack/aws/chain.py", line 90, in handle
2023-03-17T16:38:29.4147135Z     handler(self, self.context, response)
2023-03-17T16:38:29.4147637Z   File "/home/runner/work/localstack/localstack/localstack/localstack/aws/ha …
```
> fix sns unsubscribe to be idempotent

- localstack/config.py
- localstack/services/awslambda/invocation/docker_runtime_executor.py
- localstack/testing/aws/lambda_utils.py
- localstack/utils/platform.py
- tests/integration/awslambda/test_lambda.py
Add an environment variable `LAMBDA_IGNORE_ARCHITECTURE` to ignore the architecture (i.e., x86_64 or arm64) of a Lambda function and let Docker select a matching image based on the host operating system and architecture.
* Improve performance by natively running cross-platform compatible lambda functions.
* Facilitate cross-platform testing with different test runners. We might need to introduce pytest markers to indicate compatibility restrictions (e.g., `amd64_only` and `arm64_only`).
* Use standardized `get_arch()` to match `aarch64` platform on Linux
* Move `is_arm_compatible()` to platform utils
* Make the `PULLED_IMAGES` cache platform-aware to prevent running into timeouts upon invocation
> Add lambda config to ignore architecture

- localstack/aws/protocol/service_router.py
- localstack/cli/localstack.py
- localstack/cli/main.py
- localstack/config.py
- localstack/constants.py
- localstack/utils/bootstrap.py
This PR adds a band-aid to a long-standing issue that `config.dirs` is used when running CLI commands.
This caused localstack to create the `.filesystem` directory in the Python path, which was originally just designed for executing host mode in developer environments, even when simply using the CLI.
```
% locate .filesystem     
/home/thomas/.pyenv/versions/3.10.9/lib/python3.10/site-packages/.filesystem
/home/thomas/workspace/localstack/localstack/.filesystem
/home/thomas/workspace/localstack/localstack-ext/.venv/lib/python3.10/site-packages/.filesystem
```
Because the CLI and the runtime share control paths, there are situations where values from `config.dirs` are used to  create directories or files, even though they may not make sense in the context of the CLI.
* `dirs.cache` is used …
> fix config.dirs usage in the CLI

- localstack/services/apigateway/invocations.py
- tests/integration/apigateway/test_apigateway_common.py
- tests/integration/apigateway/test_apigateway_common.snapshot.json
Following #7842, we were missing a step in the validation: if the request body was empty, we should consider the request body as an empty JSON object to allow the validation to take effect, and not throw an error for invalid JSON.
I've extended the existing test for the request validator integration to add the `GET` method, and test with a request with no request body.
> fix APIGW request validation with empty request body

- localstack/aws/app.py
- localstack/aws/trace.py
- localstack/config.py
This PR targets localstack developers and adds tracing functionality to debug the handler chain.
I think this can be useful for work that involves a lot of debugging in the HTTP framework (thinking APIGW, S3, CORS, Lambda, issues with request streaming, ...) :eyes: @bentsku @alexrashed @calvernaz @dfangl @dominikschubert 
You can enable this behavior by setting `DEBUG_HANDLER_CHAIN=1` 
By wrapping handlers and recording before/after state of the context, request, and response object, we can report in quite a detailed way what the handler did to the request/response.
This includes
* attributes set on the context, like the service or operation
* which headers where modified
* whether pesky get_data methods were called on request/response objects
I'm sure there are better/more generic ways …
> add tracing for handler chain

- localstack/services/kms/models.py
- localstack/services/kms/provider.py
- tests/integration/test_kms.py
This change addresses this issue https://github.com/localstack/localstack/issues/7910
Previously, due to the `grant_names` only mapping from grant name to grant ID, it was impossible to have more than one grant with the same name across keys. By including the key ID in the mapping, it becomes possible. 
I've added a unit test to demonstrate the fix works, and allows this grant to be created on both keys. 
If any extra test coverage would help, just point me in the right direction!
> 7910 support having a grant with the same name on different keys

- localstack/services/awslambda/invocation/lambda_models.py
- localstack/services/awslambda/invocation/lambda_service.py
- localstack/services/awslambda/invocation/models.py
- localstack/services/awslambda/invocation/version_manager.py
- localstack/services/awslambda/provider.py
Adds a first iteration on basic persistence for the new lambda v2 provider.
- Start loaded lambda function versions. => Detects lambdas that need to start by checking if they have a VersionManager assigned
- Start event source listeners (note: restoring a dynamodbstreams event source mapping is currently broken because the dynamodbstreams provider doesn't properly support persistence yet) => test skipped for now
- Implement state reset
- Implement restore for provisioned concurrency (Depends on https://github.com/localstack/localstack/pull/7881)
> Implement basic persistence for lambda v2

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/router_asf.py
- localstack/services/awslambda/lambda_utils.py
- localstack/services/ec2/provider.py
- localstack/testing/pytest/fixtures.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/apigateway/conftest.py
- tests/integration/apigateway/test_apigateway_integrations.py
- tests/integration/apigateway/test_apigateway_integrations.snapshot.json
Add support for VPC endpoints for private API Gateway REST APIs. See docs [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html).
These endpoints allow users to invoke REST APIs under the following endpoints:
```
http(s)://{rest-api-id}-{vpce-id}.execute-api.localhost.localstack.cloud:4566/{stage}
```
... in addition to the standard API GW invocation endpoints:
```
http(s)://{rest-api-id}.execute-api.localhost.localstack.cloud:4566/{stage}
```
A snapshot test has been added to cover the functionality.
More detailed description following soon..
> Add support for VPC endpoints for private API Gateway REST APIs

- localstack/services/awslambda/invocation/version_manager.py
- tests/integration/awslambda/test_lambda_api.py
- tests/integration/awslambda/test_lambda_api.snapshot.json
- tests/integration/awslambda/test_lambda_destinations.py
- tests/integration/awslambda/test_lambda_destinations.snapshot.json
By default Lambda should retry async event invocations `2` times. We didn't honor this and since max_retry_attempts was `None` this lead to an exception in the spawned thread and therefore was never actually retried.
Example:
```python
lambda_client.put_function_event_invoke_config(FunctionName=function_name, DestinationConfig={"OnSuccess": {"Destination": some_arn}})
```
> Fix lambda destination default retries

- bin/docker-entrypoint.sh
- localstack/__init__.py
- localstack/aws/protocol/service_router.py
- localstack/cli/localstack.py
- localstack/cli/main.py
- localstack/config.py
- localstack/constants.py
- localstack/services/awslambda/lambda_starter.py
- localstack/services/edge.py
- localstack/services/providers.py
- localstack/services/s3/s3_listener.py
- localstack/services/s3/s3_starter.py
- localstack/utils/bootstrap.py
- localstack/utils/docker_utils.py
- tests/bootstrap/test_cli.py
- tests/integration/aws/test_app.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
- tests/integration/test_edge.py
This PR should remain minimal in terms of code changes, and is mostly used for keeping track of the PRs regarding the new s3 provider going directly into master and for tracking test failure rates against the new provider.
The following PRs have been created to fully implement the new s3 provider:
* #6552
* #6629
* #6836
* #6829 
* #6812 
* #6839
* #6859
* #6868 
* #6875 
* #6846
* #6903 
* #6906
* #6908
* #6937 
* #6959
* #6980
* #6987
* #7001
* #7027
* #7065
* #7070
* #7081
* #7152
* #7173
> S3 migration - set s3 v2 provider as default

- localstack/config.py
- localstack/deprecations.py
- setup.cfg
- tests/unit/test_config.py
We are switching to using `LOCALSTACK_HOST` and `GATEWAY_LISTEN` to configure LocalStack.
These variables are split into two types: _cosmetic_ and _functional_. Cosmetic are purely used as hostnames in returned URLs or addresses by LocalStack. LocalStack does not use these variables to configure services.
_functional_ variables are used to configure the networking stack of LocalStack.
* `LOCALSTACK_HOST`: (cosmetic) this variable is interpolated into URLs and addresses. It has the form `<hostname>:<port>` and defaults to `localhost.localstack.cloud:4566`.
* `GATEWAY_LISTEN`: (functional) this configures the bind addresses of LocalStack. It has the form `<ip address>:<port>(,<ip address>:<port>)*` and defaults to `127.0.0.1:4566` on the host and `0.0.0.0:4566` in docker.
Since …
> Configure cosmetic and functional variables with LOCALSTACK_HOST and GATEWAY_LISTEN

- tests/bootstrap/conftest.py
- tests/bootstrap/test_cli.py
without setting `LOCALSTACK_CLI=1`, the config.dirs are not set to the CLI directories, but the the host-mode directories using `.filesystem`.
https://github.com/localstack/localstack/blob/a12e673130f5a5c77f6f9a2049d7bfe7bff960a4/localstack/config.py#L1096-L1103
we are setting `LOCALSTACK_CLI=1` here, but this is never called in the tests:
https://github.com/localstack/localstack/blob/a12e673130f5a5c77f6f9a2049d7bfe7bff960a4/localstack/cli/main.py#L4-L6
> add fix for CLI tests to properly set CLI context 

- localstack/config.py
- localstack/utils/docker_utils.py
- tests/integration/docker_utils/test_docker.py
Dynamically determine ports check Docker image to avoid duplicate image download.
Currently, the default image we're using for the port availability checks is `localstack/localstack` (unless configured manually via `PORTS_CHECK_DOCKER_IMAGE`). For Pro users (`localstack/localstack-pro`), this means that potentially an additional image would be downloaded at runtime. 
This hasn't been an issue so far (as the images were aliases), but is now becoming relevant for the upcoming image split in v2.
> Dynamically determine ports check Docker image to avoid duplicate download

- localstack/utils/bootstrap.py
Looks like something is still not quite right with the directories and the way they are initialized depending on the environment.
The log files from the CLI tests in master suggest that some directories are again not created properly. 
```
[Errno 2] No such file or directory: \'/var/lib/localstack/tmp/localstack_main_container.log\'\n
```
It's not clear to me why the file is `/var/lib/localstack/tmp/localstack_main_container.log` - it should not be `/var/lib/localstack` when starting the cli. need to investigate further and clean this up, but adding this band-aid for now.
log output from the test (very easy to read :grimacing: )
```
FAILED tests/bootstrap/test_cli.py::TestCliContainerLifecycle::test_start_cli_within_container - localstack.utils.container_utils.container_client.ContainerExc …
```
> re-add mkdirs call before starting localstack docker container

- tests/integration/awslambda/test_lambda_common.py
- tests/integration/stepfunctions/legacy/test_stepfunctions_legacy.py
Fixes community tests with PRO enabled.
- Skip transparent endpoint injection tests when PRO enabled (with lambda v2) and DNS is disabled
- Fix stepfunctions state machine to return correct payload structure.
> Fix test failures for community tests in PRO

- .circleci/config.yml
Adds a cache to the common functions to avoid building them every build.
Uses a file with a list of all hashes of hash-key-files as hash-key (so hashing the file full of hashes), as CircleCI does not support hashing multiple files (via a glob or something) sadly.
Reduces amd64 build time by about 10 minutes.
> Add cache for common functions

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/notifications.py
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
While looking at the tests run, I realised we were encountering issue when doing test cleanup. 
Trace:
```python
2023-03-23T21:22:27.7599773Z Traceback (most recent call last):
2023-03-23T21:22:27.7600672Z   File "/home/runner/work/localstack-ext/localstack-ext/localstack/localstack/aws/chain.py", line 90, in handle
2023-03-23T21:22:27.7601377Z     handler(self, self.context, response)
2023-03-23T21:22:27.7602178Z   File "/home/runner/work/localstack-ext/localstack-ext/localstack/localstack/aws/handlers/service.py", line 122, in __call__
2023-03-23T21:22:27.7602712Z     handler(chain, context, response)
2023-03-23T21:22:27.7603397Z   File "/home/runner/work/localstack-ext/localstack-ext/localstack/localstack/aws/handlers/service.py", line 92, in __call__
2023-03-23T21:22:27.7603934Z …
```
> add check for FakeDeleteMarker in case of versioned bucket

- tests/integration/s3/test_s3_cors.py
- tests/integration/test_firehose.py
Firehose tests with OpenSearch/ES have been really flaky and we're trying to get a deployment out. Let's see if this goes further
Trying to fix flakiness of the s3 CORS tests that make extensive use of virtual host addressing... could be some issue there?
> skip test_kinesis_firehose_opensearch_s3_backup + es equivalent + fix s3 flake

- localstack/services/providers.py
The intent here is to avoid bricking environments for users that are still setting `PROVIDER_OVERRIDE_S3=v2`. 
Default, `v2` and `asf` are then equivalent and will all start the v2 s3 provider.
> Add back s3 v2 provider alias

- localstack/services/dynamodb/provider.py
This PR fixes the restart of DynamoDB. 
I noticed this issue when working to re-enable the cloud pods tests. I likely introduced this regression in https://github.com/localstack/localstack/pull/7827.
In a nutshell, we were creating the assets directory in the `on_before_state_reset()` hook and deleting it when calling the visitor. This PR moves the creation to the server to the `on_after_state_reset()` hook.
One can simply test it by creating some resources and calling the endpoint with `curl -X POST http://localhost:4566/_localstack/state/reset`
> fix: dynamodb restart

- localstack/aws/handlers/cors.py
- localstack/services/s3/cors.py
- localstack/services/s3/provider.py
It seems we missed a scenario when creating the new CORS handling for S3:
If we do a `CreateBucket` request not targeting the S3 specific endpoint (like we do from the web app), we cannot know for sure that the request is targeting S3 (it is a simple `PUT` request with a path, nothing else), because the bucket does not exist yet. So, the pre-process handler does not add any headers, and the request is seen as "self-managed" by the default CORS enforcer / enricher because it targets S3, so nobody adds the right headers in the end. 
The solution for now is to let the handler chain execute before handing the request to the skeleton, and if the request is `CreateBucket` or `ListBuckets`, we will use the default LocalStack CORS handling to enrich the response with the right headers, only of …
> fix CORS issue for CreateBucket and ListBuckets

- localstack/services/plugins.py
- tests/unit/services/test_plugins.py
This PR fixes a race condition in the service plugin loading, where multiple concurrent calls to `service_manager.require(...)` could lead to Service plugins being instantiated more than once, and subsequently `on_after_init` being called multiple times, whose implementation often mutates global state.
We haven't seen this manifest yet, other an exception in the logs when running `tests/integration/test_terraform.py::TestTerraform::test_bucket_exists`:
```
2023-03-24T17:22:07.962 ERROR --- [   asgi_gw_5] localstack.utils.functions : error calling function on_after_init
File "/opt/code/localstack/localstack/utils/functions.py", line 41, in call_safe
return func(*args, **kwargs)
File "/opt/code/localstack/localstack/services/apigateway/provider.py", line …
```
> fix race condition in service plugin loading

- tests/unit/packages/test_api.py
Skipping this test for now since there seems to be a race condition in the test that sometimes triggers. Was also able to reproduce locally, but not reliably.
/cc @alexrashed
> skip test_package_installer_custom_lock to unblock CI pipeline

- localstack/services/awslambda/lambda_executors.py
Fixed issue, which is the same as in #1081 but for `LAMBDA_EXECUTOR: local`. Using local executor to avoid using DIND in Gitlab CI
> fixed too many arguments for local lambda executor

- CODEOWNERS
I've made in typo in #7845 and missed an `s` in `tests`, which made my fix useless. 😄
> fix typo in CODEOWNERS for S3

- localstack/utils/docker_utils.py
- localstack/utils/net.py
- localstack/utils/server/proxy_server.py
- tests/integration/docker_utils/test_docker.py
- tests/unit/utils/test_net_utils.py
Extend docker/net utils to allow port checks for UDP ports. Addresses an issue from a support channel where starting up the LS container fails due to UDP port 53 already being bound. 
This PR extends `container_ports_can_be_bound(..)` to allow us to make port availability checks also for UDP ports, which will allow us to selectively add the port bind for UDP port 53, based on availability.
Tried to make the changes minimally invasive, and backwards-compatible. Ports can be specified as an `int` (in which case we assume TCP as the default protocol), or as a `Port` instance that contains the protocol explicitly.
The existing `TestDockerPorts` test has been parameterized to also cover UDP ports, and a new simple test has been added to cover the UDP-based logic for `port_can_be_bound(..)`. …
> Extend docker/net utils to allow port checks for UDP ports

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/config.py
- localstack/services/s3/cors.py
- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
It seemed we had an issue with `ListObjectsV2` and Glue. Once again, the specs were not right about the root tag of the XML response of S3. However, the responses for `ListObjects` and `ListObjectsV2` are using the same root tag `ListBucketResult` so we must merge the two wrongly named "containers" in the specs into one for both operation. 
Also, I've realized that we merged this from our old S3 migration branch:
```python
if not os.environ.get("PROVIDER_OVERRIDE_S3"):
os.environ["PROVIDER_OVERRIDE_S3"] = "asf"
```
So, removing it. 
Also, thanks @silv-io for the hours long debugging session we've had to find this issue 😄
> add test for ListObjectsV2 + fix config flag

- localstack/config.py
- tests/unit/test_config.py
Currently, when explicitly setting `""` for provider overrides (e.g., `PROVIDER_OVERRIDE_S3=""`) the ServiceProviderConfig assumes that a provider with the name `""` (i.e. an empty string) is requested. This happens, e.g., in the `bin/test-in-docker.sh` script and leads to `NotImplementedError`s. 
Since we can safely assume that we won't create new provider variants with the explicit name of an empty string, we can ignore all falsey values for provider overrides and thus assume a selection of the default provider. 
This PR also adds a unit test to verify this new behavior.
/cc @bentsku
> Ignore empty provider overrides

- bin/docker-entrypoint.sh
Removes a small leftover from #7970: The `DISABLE_TERM_HANDLER` env variable handling in the `docker-entrypoint.sh`.
This feature seems to be a weird feature, LocalStack should just listen to all signals.
Docs PR: https://github.com/localstack/docs/pull/543
> remove DISABLE_TERM_HANDLER in docker entrypoint

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This is a follow up from #7545, a user reported an issue in our Community Slack. The test is AWS validated, and once again the specs were not compliant with what S3 really returns. 
We also reapply the logic that was in a patch previously set, moto would have raised an error if using some request parameters that were not implemented. It would raise a `NotImplemented` exception. The previous provider was swallowing the exception and letting it pass anyway without applying the parameters. We can keep the same behaviour for now and come back later and actually implement the right behaviour. 
related: #7981, https://github.com/localstack/docs/pull/539
\cc @steffyP
> fix response structure for S3 ListMultipartUploads

- localstack/aws/handlers/cors.py
- tests/unit/test_cors.py
This is a follow up from #7554, from an idea proposed by @whummer ([in this comment](https://github.com/localstack/localstack/pull/7554#discussion_r1086872025)) , with dynamic handling of CORS origin for web resource served by LocalStack.
This is not mergeable as is, as it still has some logging regarding performance, but I'd like to have some comments / opinions.
LocalStack is serving a resource meant to be accessed from the browser (CloudFront or S3 website).
But this resource needs to access LocalStack resources as well. Right now, the only way is to set the environment variables of LocalStack to allow the Origin (let’s say, `http://<bucket>.s3-website.localhost.localstack.cloud:4566`).
This PR adds a dynamic check of the origin, to validate if it follows some regex matching 2 service …
> add dynamic check of origin for CORS

- localstack/services/cloudformation/provider.py
Small fix in length check for CloudFormation `TemplateBody` - we should only check the length if the body is specified, not if the template is passed via `TemplateURL`. Addresses https://github.com/localstack/localstack/issues/7880 . 
The main use case is also to get a larger sample prepared for the Developer Hub: https://github.com/aws-samples/query-data-in-s3-with-amazon-athena-and-aws-sdk-for-dotnet
/cc @HarshCasper
> Fix length check for CloudFormation TemplateBody

- localstack/aws/connect.py
- localstack/config.py
- localstack/packages/api.py
- localstack/services/awslambda/invocation/version_manager.py
- localstack/services/sns/publisher.py
- localstack/utils/aws/client_types.py
- localstack/utils/aws/dead_letter_queue.py
- localstack/utils/aws/message_forwarding.py
- localstack/utils/cloudwatch/cloudwatch_util.py
- tests/integration/awslambda/test_lambda.py
- tests/unit/aws/test_connect.py
* Assuming a role and using a client with the returned credentials is a pattern we often need across the code base, especially for the use of service roles or service-linked roles. The new method provides a simple interface to do this in one call.
* To enforce IAM between some services, we need to use the new aws client, and also handle the exceptions (it should fail with a warning, but should not crash anything important if a request fails).
A new method for the aws client factories.
Usage:
```python
logs_client = connect_to
.with_assumed_role(role_arn="arn:aws:iam::000000000000:role/test-role", service_principal="lambda")
.logs
```
This call will assume the given role as the given service, and return a service level client factory, where various clients can be created using the returned …
> Add utility for creating a client assuming a role, migrate some inter-service communication to new client

- localstack/config.py
- localstack/services/stores.py
- tests/integration/test_stores.py
- tests/unit/test_stores.py
Introduces a new config option `ALLOW_NONSTANDARD_REGIONS` which disables strict validation of AWS regions.
Closes https://github.com/localstack/localstack/issues/7993
> Support non-standard AWS regions

- localstack/config.py
- localstack/utils/files.py
This PR adds a separate cache dir for the CLI. I saw errors in the log:
```
[16:16:34] starting LocalStack in Docker mode 🐳                                                                                                                                                  localstack.py:142
2023-03-29T16:16:34.656  WARN --- [  MainThread] localstack.utils.functions : error calling function save: [Errno 13] Permission denied: '/home/thomas/.cache/localstack/cli'
```
because `/home/thomas/.cache/localstack` is created by the container. So instead, we now have `/home/thomas/.cache/localstack-cli` which is managed by the cli and won't have permission errors.
> create separate cache directory for cli

- bin/localstack-supervisor
- localstack/services/infra.py
@dfangl noticed that SIGINT is not terminating localstack correctly in docker. this PR makes sure that SIGINT to the supervisor is translated into a SIGTERM to localstack. we tried to forward SIGINT but couldn't quite figure it out. left a todo in there for future daniel and thomas :P
We also now use SIGUSR1 instead of SIGHUP to restart LS, to avoid restarting when the shell is closed (it will now just be ignored. We could start terminating, we can discuss if this is expected).
/cc @alexrashed
> fix signal handling in localstack-supervisor

- Dockerfile
Currently we get a deprecation warning shown in docker because we set
EDGE_BIND_HOST and LOCALSTACK_HOST in the dockerfile. We default to these
values anyway so we don't need them in the Dockerfile any more.
> Remove unneeded defaults for envars

- localstack/config.py
- localstack/services/awslambda/packages.py
Adds the `LAMBDA_INIT_RELEASE_VERSION` config variable. This value will override the default version which was previously hard-coded in the lambda service. We still only really support a 1-1 mapping of localstack version to init version (always whatever is set as `LAMBDA_RUNTIME_DEFAULT_VERSION` at the time of the localstack release), but sometimes it's helpful to test an existing container with a newer released init version without updating localstack first.
> Add config option to override used lambda init version

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
No need to introduce this one anymore, same issue as always. Extending #7983
I think we need to create a small script to test every single S3 operations to check for the XML of the response, and not only what boto returns, or check the documentation of every operation. 
This addresses #8019 
Format in the docs:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectTagging.html#API_GetObjectTagging_ResponseElements
Format from botocore specs:
https://github.com/boto/botocore/blob/a77b1766b2e34a55b3c9d3aed89a8d2376a8eed6/botocore/data/s3/2006-03-01/service-2.json#L4920-L4935
> fix GetObjectTagging and GetBucketTagging format

- localstack/services/sns/publisher.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
- tests/unit/test_sns.py
This issue came up in the support channel, we were not handling OR conditions properly.
We now properly handle combination of OR and AND filters for the `MessageBody` scope. 
I've also added a unit test to properly test the new filter. 
See: https://docs.aws.amazon.com/sns/latest/dg/and-or-logic.html
> fix SNS Subscription Filter OR/AND combination on MessageBody

- tests/integration/test_stores.py
Since #7997, there were errors in tests as follows:
https://github.com/localstack/localstack/actions/runs/4567644230/jobs/8061685484#step:18:23986
```
File "/home/runner/work/localstack/localstack/localstack-ext/.venv/lib/python3.10/site-packages/moto/utilities/aws_headers.py", line 64, in _wrapper
response = f(*args, **kwargs)
File "/home/runner/work/localstack/localstack/localstack-ext/.venv/lib/python3.10/site-packages/moto/cloudwatch/responses.py", line 173, in put_metric_data
self.cloudwatch_backend.put_metric_data(namespace, metric_data)
File "/home/runner/work/localstack/localstack/localstack-ext/.venv/lib/python3.10/site-packages/moto/cloudwatch/responses.py", line 28, in cloudwatch_backend
return cloudwatch_backends[self.current_account][self.region]
File …
```
> Cleanup after non-standard region tests

- localstack/services/s3/presigned_url.py
This PR fixes the `AttributeError: 'NoneType' object has no attribute 'service_name'` error occurring when doing any pod operation after the initialization of the S3 provider.
I am simply adding a guard clause for `context.service` being None, similar to the other S3 handler for CORS (`s3_cors_request_handler`).
The error can be simply reproduced with:
```
awslocal s3 mb s3://localstack-bucket
localstack pod save file://my-pod
```
> Fix AttributeError for custom S3 handler

- localstack/services/sns/models.py
- localstack/services/sns/provider.py
- localstack/services/sns/publisher.py
- localstack/utils/aws/dead_letter_queue.py
- tests/integration/test_sns.py
This PR adds the ability to pass a failed message from a FIFO topic down to a FIFO queue. It was failing before because we would not pass the required attributes needed for a FIFO queue, namely `MessageGroupId` and optionally `MessageDeduplicationId`.
I've also removed some snapshot skipping by adding the `SequenceNumber` attributes to messages published on FIFO topics. Needed to add a field on `SnsMessage`, not very clean to pass the context there, but it feels like the only solution to be able to return that `SequenceNumber` to the `PublishBatch` operation response, it needs to be pre-defined before actually creating the message body. 
I already added the test for this behaviour, so I just removed the `xfail` mark.
> fix SNS FIFO DLQ + add SequenceNumber to FIFO

- localstack/aws/api/s3/__init__.py
- localstack/aws/protocol/serializer.py
- localstack/aws/spec-patches.json
- localstack/services/s3/provider.py
So following #8021, #7983 and #7545, I've investigated and made a list of all S3 operations with a different root node name than the specs. Basically, 41 of 44 operations returning an XML body do not follow the specs. Here's the list:
❌: wrong name, 🟠: fixed by patches, ✅: right from the specs
| | Operation | Spec shape | Root tag
|-|-|-|-|
| ❌| CompleteMultipartUpload | CompleteMultipartUploadOutput | CompleteMultipartUploadResult
| ❌| CopyObject | CopyObjectOutput | CopyObjectResult
| ❌| CreateMultipartUpload | CreateMultipartUploadOutput | InitiateMultipartUploadResult
| 🟠| DeleteObjects | DeleteObjectsOutput | DeleteResult
| ❌| GetBucketAccelerateConfiguration | GetBucketAccelerateConfigurationOutput | AccelerateConfiguration
| ❌| GetBucketAcl | GetBucketAclOutput | …
> fix S3 response xml root tag names

- localstack/aws/serving/asgi.py
- localstack/http/asgi.py
- tests/unit/http_/conftest.py
- tests/unit/http_/test_asgi.py
This PR adds simple support for the ASGI lifespan protocol for the ASGIAdapter. The change allows you to attach a listener to the ASGIAdapter that can react to lifespan protocol events. See https://asgi.readthedocs.io/en/latest/specs/lifespan.html
This is mostly to get rid of the warning messages that have bothered and mislead some users in issues like #8035
But in the future, we could potentially use this for improving startup/shutdown routines.
The failure case is a bit tedious to test with the fixtures we have, so I decided to skip it for now, since we don't really have a use case for it yet.
> add support for asgi lifespan protocol listener in asgi/wsgi bridge

- .github/workflows/cli-tests.yml
- .github/workflows/pro-integration.yml
We have a release branch `release/v2.1` which was not being tested.
Companion PR in ext: https://github.com/localstack/localstack-ext/pull/1573
> Configure CI on release branches

- localstack/services/s3/presigned_url.py
- tests/integration/s3/test_s3.py
This PR mostly add a test to verify behaviour raised in a community slack issue. The PHP SDK allows the user to specify a bucket with a slash in the name while generating a pre-signed URL. However, this is not allowed by AWS, and we would not raise the proper exception (and there was a small issue in our calculation, as we were using the sanitized path to create the `CanonicalRequest` used for the signature). 
I just added some proper exceptions in that case for the test to pass like it would against AWS.
> fix forward slash validation in S3 pre-signed url

- localstack/aws/connect.py
- localstack/testing/aws/util.py
- localstack/testing/pytest/fixtures.py
- tests/integration/conftest.py
Since PyCharm still can't properly detect the imported pytest plugins from localstack, we'll just duplicate the actual fixture definition across the two repos.
The core logic behind the client creation has been moved to `util.py` and is re-used across these client fixture definitions.
> Move test client creation logic into util package for re-use across repos

- localstack/testing/pytest/metric_collection.py
With the new coverage docs we also show which tests called certain operations.
The automated workflow update in the docs repo reveals that there is a subset of tests changing for every run. 
This is likely due to a wrong recording of the raw-metrics. 
The raw-metrics are recorded and written to a CSV in the teardown of the test case:
* each api call recorded will be considered to belong to that test
* the metrics-collection array will be reset after writing the records to the CSV
* but there might be other tear-down actions afterwards - which would then be considered being part of the next test
This PR adds the `trylast` flag to the `pytest_runtest_teardown` which could help making the recorded test metrics more stable.
> set 'trylast' for pytest-teardown that writes the collected metrics

- localstack/utils/aws/client_types.py
Noticed a few missing clients when migrating the tests in -ext
Adds types for the following clients:
- `dms`
- `efs`
- `elasticache`
- `fis`
- `kinesisanalytics`
- `kinesisanalyticsv2`
> Add missing client types for TypedServiceClientFactory

- localstack/services/kms/models.py
- localstack/services/kms/provider.py
- tests/integration/test_kms.py
- tests/integration/test_kms.snapshot.json
- Added support for key specs - HMAC_224, HMAC_256, HMAC_384 and HMAC_512
- Implemented `CreateKey` for hmac, `GenerateMac` and `VerifyMac`
- Write test cases for them 
Related issue #7736
> KMS HMAC support

- localstack/services/apigateway/provider.py
- tests/integration/apigateway/test_apigateway_api.py
- tests/integration/apigateway/test_apigateway_api.snapshot.json
As reported in https://github.com/localstack/localstack/issues/7975#issuecomment-1495698212, we have an issue while returning a `minimumCompressionSize` when set to an empty string. The docs states:
> To enable compression, apply a replace operation with the accompanying value property set to a non-negative integer between 0 and 10485760. To disable compression, apply a replace operation with the value property set to null or omit the value property.
https://docs.aws.amazon.com/apigateway/latest/api/patch-operations.html#UpdateRestApi-Patch
Apparently, an empty string works as well. I've added the validation + type casting of either `int` or `None` when disabled, but we're not actually enforcing this as a feature, only mocking this value, so no changes down the line.
If we updated the …
> fix APIGW RestAPI minimumCompressionSize

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
As reported in #8034, there would be an error down the line when trying to publish delivery logs when using `MessageStructure="json"`. It's because we would pass a `dict` instead of `str` to calculate the md5 hash of the body, because we didn't filter the fields of the received JSON message. In the docs, it's specified that if the field isn't a string, it will be ignored by AWS: https://docs.aws.amazon.com/sns/latest/api/API_Publish.html
This PR now properly filters the fields, and add some tests to validate the behaviour with AWS.
_fixes #8034_
> add SNS validation of JSON fields type for MessageStructure json

- Makefile
With the release of `localstack-core==2.0.0`, we had a slight hiccup where the entrypoints were missing in the distribution (hence the `2.0.0.post1` release on PyPi).
This PR adds some simple quality gates to avoid publishing distributions without entrypoints.
> add quality gate for entrypoints to make targets

- README.md
- localstack/aws/handlers/service.py
- localstack/aws/skeleton.py
- localstack/utils/aws/request_context.py
- localstack/utils/coverage_docs.py
- tests/unit/aws/test_skeleton.py
- tests/unit/utils/test_coverage_docs.py
This PR adjusts the links that are printed for `not implemented` errors. 
Instead of pointing to our general feature coverage https://docs.localstack.cloud/user-guide/aws/feature-coverage/ they now point to the specific service page of our docs, e.g. https://docs.localstack.cloud/references/coverage/coverage_sqs/ for `sqs`.
question: 
do all our services have a related page on the docs?
based on the fact that the docs are auto-generated, I'm assuming that the answer to the question is yes, hence allowing us to link directly to the coverage page of each service 🙂
> include link to service coverage page on not implemented error

- .github/workflows/cli-tests.yml
- .github/workflows/pro-integration.yml
I had thought from the `v[0-9]+` entry above that this filter pattern is
a regex, but it isn't. It's annoyingly close though. The effect is that
CI was _not_ being run against the `release/v2.1` branch.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
> Replace (incorrect) regex with filter pattern

- localstack/config.py
We currently don't detect containers running in containerd correctly. containerd does not set the same docker file or cgroup values as docker does/did.
This was triggered by a user issue: https://github.com/localstack/localstack/issues/8035
I was able to recreate this by running containerd on Linux, or adding a beta feature of Docker Desktop on macOS.
> Detect containerd containers

- localstack/services/kms/models.py
- localstack/services/kms/provider.py
- tests/integration/test_kms.py
- tests/integration/test_kms.snapshot.json
Until now, the DeleteImportedKeyMaterial operation was missing.
* Add, at least for External origin keys, some state handling. Keys with External origin are per default in `PendingImport` state (https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys-create-cmk.html). Encrypt/decrypt operation cannot be done while in this state (https://docs.aws.amazon.com/kms/latest/developerguide/key-state.html)
* Set ExpirationModel correctly
* When deleting the key material, set the state to PendingImport again, and remove the key. (Any operation with that key will fail as it will be none, but this should be guarded by the state handling).
> Add kms DeleteImportedKeyMaterial operation

- localstack/aws/protocol/service_router.py
- tests/unit/aws/test_service_router.py
This PR fixes the issue reported in #8090.
The flow is the following:
- request received as virtual host addressed : Host = `pictures.s3.localhost.localstack.cloud`
- the S3 CORS handler does its job correctly
- service name parser wrongly attributes this request to the service named `pi` because the host starts with `pi`
- the general CORS handler thinks it's not an S3 request and reject the request without taking into account S3 CORS config
Note that this issue could arise as well with any bucket name starting with an AWS service with an endpoint prefix, like `kmstest` or anything (you can play with the added test to see everything that would break). This did not affect functionality directly, as the request would be correctly routed to the right service in the end because it would be …
> fix wrong service mapping to s3 vhost bucket

- localstack/services/kms/provider.py
- tests/integration/test_kms.py
- tests/integration/test_kms.snapshot.json
- validate length of data to be encrypted 
- add test case to check this condition 
Related issue #8083
> fix: add check on plaintext size to kms encrypt operation 

- localstack/config.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
We have recently seen flaky tests (on a new test environment which uses private GitHub runners). These tests failed due to request timeout errors within the Docker SDK client.
Some research led to an issue report in `docker-py`: https://github.com/docker/docker-py/issues/2266
According to these reports, these issues might be associated with the Docker daemon on the machine, and that it sometimes can happen that spawning a container takes a long time (i.e. longer than the default timeout of 60 seconds).
Since the Docker client is quite essential, and maybe some users are also facing issues like this in high-load scenarios, this PR introduces a config variable which allows globally setting the default timeout (in seconds) for the Docker SDK client.
> add Docker SDK default timeout config

- localstack/services/kms/provider.py
- tests/integration/test_kms.py
- tests/integration/test_kms.snapshot.json
- Fixed error message for decrypt when the key id is different from the one used in encryption
- Added a test case to verify the changes
- Removed old AWS client for test case: `test_error_messaging_for_invalid_keys`
> fix invalid error message for decrypt with incorrect key

- localstack/config.py
- localstack/services/awslambda/invocation/executor_endpoint.py
- localstack/services/awslambda/invocation/lambda_service.py
- localstack/services/awslambda/lambda_utils.py
- localstack/services/awslambda/provider.py
Enterprise environments often use HTTP(S) proxies but LocalStack-internal AWS clients fail since boto3 migrated from requests to urllib3 and dropped support for `NO_PROXY` (https://github.com/boto/boto3/issues/3179).
This PR disables proxies for LocalStack-internal AWS calls and migrates Lambda (new provider) to the new AWS client (introduced in https://github.com/localstack/localstack/pull/7240).
The following minimal configuration now fails against LocalStack:
```
HTTP_PROXY=http://mycompany.us-east-1.mycorp.com:3587
NO_PROXY = .s3.localhost.localstack.cloud,127.0.0.1,*.localhost
```
For example when trying to create any Lambda function via `awslocal lambda create-function ...`, an exception occurs:
**Hint:** For testing the setup, use [mitmproxy](https://mitmproxy.org/) and …
> Disable HTTPS(S) proxies for internal calls

- localstack/config.py
Previously, if _any_ containerd container was running on the host, and LocalStack was started in host mode then it would detect the `containerd` string in the disk partitions, and return True. This is not a great default for host mode, as it binds LocalStack to 0.0.0.0.
This change searches through the `/proc/1/mountinfo` virtual file system looking for mount options that include `containerd`. This means that only the root mount point is considered, rather than any host mounts that correspond to other containers. After this update, while running a containerd container in the background and starting LocalStack in host mode, the docker status is correctly determined to be False, and LocalStack is bound to 127.0.0.1.
> Fix containerd detection for host mode

- localstack/services/kms/provider.py
- tests/integration/test_kms.py
- tests/integration/test_kms.snapshot.json
The issue was partially fixed here #8083, but I also need to check the context based on the key type, not only the max allowed plaintext size.
* Added method to validate the plaintext size based on the key type, all those extracted numbers are from [boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kms/client/encrypt.html)
* Add tests cases to the written function
> fix: Adding validation on kms plaintext based on the key type

- localstack/services/dynamodb/server.py
- localstack/services/stepfunctions/stepfunctions_starter.py
In the persistence test logs, we have a few errors calling the `on_before_state_load`. In these hooks, we usually try to stop a server before loading the state. However, we did not check for threads and processes not being `None` (which is the case when we just started the container).
The following issue was present for DDB and StepFunctions:
```
line 87, in stop_dynamodb
docker-run.sh: self._thread.auto_restart = False
docker-run.sh: AttributeError: 'NoneType' object has no attribute 'auto_restart'
line 97, in stop_stepfunctions
docker-run.sh: if PROCESS_THREAD or not PROCESS_THREAD.process:
docker-run.sh: AttributeError: 'NoneType' object has no attribute 'process'
```
Could be replicated by:
- starting LocalStack with `PERSISTENCE=1`;
- create a DDB table;
- restart again with …
> Fix server stop errors when restoring a snapshot

- localstack/services/awslambda/provider.py
- localstack/services/events/provider.py
- localstack/services/firehose/provider.py
- localstack/services/kinesis/provider.py
- localstack/services/route53resolver/provider.py
- localstack/testing/aws/asf_utils.py
- tests/unit/aws/api/test_asf_providers.py
One of the core foundations of ASF are the generated API classes based on the service specifications contained in the latest `botocore` package. These generated APIs are contained in the `localstack.aws.api` module and are updated on a weekly basis by the ["Update ASF APIs"](https://github.com/localstack/localstack/actions/workflows/asf-updates.yml) workflow.
Unfortunately, these updates can cause problems if the signature of the generated APIs change, but the corresponding provider method signatures - implementing the abstract generated API methods - are not adjusted.
This also caused issues with our parity metric collection in the past. /cc @steffyP 
For example, the latest run of the [Update ASF APIs last Monday](https://github.com/localstack/localstack/actions/runs/4654646951) created …
> fix ASF operation signature mismatches

- localstack/constants.py
- localstack/services/sqs/provider.py
- localstack/services/sqs/utils.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs_backdoor.py
- tests/unit/test_sqs.py
This PR makes SQS queues resolve based on the account ID and region in the queue URL.
Previously this was based on request context.
> SQS: Add cross-account support

- localstack/services/infra.py
- localstack/utils/bootstrap.py
infra calls make up about ~5% of our telemetry traffic. This PR removes them because
- I can't think of any usage in the current state
- lazy loading can be assumed, eager loading could be interesting but would ideally need slightly different calls
- less calls => better scaling
> remove infra analytics calls

- localstack/services/sns/models.py
- localstack/services/sns/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
- tests/unit/test_sns.py
As reported in #8118, there was an issue with confirming a subscription from a simple http client, because we would use the region from the context, which was using the default region of LocalStack (set from the auth handler `MissingAuthHeaderInjector`). However, we should use the region from the `TopicARN`. I've re-validated the tests against AWS with a local setup with https://localhost.run, and could validate different behaviours that were untested. This adds more parity into our HTTP subscriptions, and fix the linked issue. 
Also, I've sneaked a little store change to get the parity needed. This should not break persistence nor cloud pods as tokens are usually short lived, and it is more additive. We won't try to get a topic ARN anymore from this dict, so it would not create error per …
> fix ConfirmSubscription access to SNS store

- localstack/services/sns/publisher.py
This PR adds a small change to use the new AWS Internal Client.
It does not call `request_metadata` due to the Publisher being able to just send emails without needing an Identity Policy on the address.
> Replace SES Client In SNS Publisher

- tests/integration/cloudformation/resources/test_iam.py
#8074 just reintroduced usage of the old client fixture, so fixing this to unblock the pipeline.
> fix IAM client fixture

- localstack/services/sns/provider.py
- localstack/services/sns/publisher.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
This PR continues on #8029. I actually only fixed the DLQ behaviour for FIFO topics for `publish_batch` and not for a simple `publish`.
I've also refactored our way of passing argument to the SQS client in the publisher, to allow reuse between the regular SQS publisher and the batch one, also when sending it down the DLQ. 
I've also removed `create_sqs_message_attributes` as it was a remnant from the `ProxyListener`, and now ASF properly decodes and casts the `MessageBodyAttributeMap` into the right format. It might have been the issue for https://discuss.localstack.cloud/t/i-have-been-stuck-on-binascii-error-incorrect-padding-not-sure-if-it-is-an-error/297 but not sure yet, anyway, after testing, it was not used anymore.
There's a follow up PR building on this to test and implement …
> remove SNS create_sqs_message_attributes and add DLQ for Fifo topic

- localstack/http/client.py
- localstack/services/s3/virtual_host.py
- tests/integration/s3/test_s3.py
As reported in #8139, the new S3 provider will decode gzip encoded requests before returning the data.
This was due to our Proxy and more specifically our `SimpleHttpClient`, which uses `requests` under the hood. Requests automatically decode the response, and we need the raw data underneath. I've duplicated our http client to not do a drastic change and only use it in the virtual host part of S3, we can then see if it creates issues or not 😄
I didn't add unit tests as I believe it could be added on top of #8104, and don't want to create too many conflicts. 
About requests and decoding gzip:
https://docs.python-requests.org/en/latest/community/faq/#encoded-data
_fixes #8139_
> fix auto decoding of gzip for s3 vhost proxied requests

- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
Implement AWS validated tests for #6882.
The fix was worked on in moto here (https://github.com/localstack/moto/pull/65) but an issue with the tests prevented me for merging at the time. I will come back to this later on, but we can merge the added tests and skip for now.
> add tests for multipart SSE fields and S3 KMS BucketKeyEnabled

- localstack/services/awslambda/invocation/runtime_environment.py
- localstack/services/awslambda/packages.py
- tests/integration/awslambda/test_lambda.py
Ships a new Lambda init release: https://github.com/localstack/lambda-runtime-init/releases/tag/v0.1.17-pre
* Addresses a support case where the optional X-Ray daemon telemetry crashed the Lambda Docker container: https://github.com/localstack/lambda-runtime-init/pull/18
* Improves Lambda init logging: https://github.com/localstack/lambda-runtime-init/pull/19
> Fix lambda init xray telemetry initialization

- localstack/services/sqs/models.py
- tests/integration/test_sns.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
While working on #8144 and #8145 I've spotted 2 issues with deduplication on FIFO SQS queues.
First, it seemed we did not deduplicate deleted messages when the SQS documentation says they do.
See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagededuplicationid-property.html
While reading this, I've also realised that what I thought was a feature of SQS was actually a bug, and that we should deduplicate on the queue level and not the `MessageGroupId`. However, this means breaking persistence as we're changing the structure of the `FifoQueue` object. Is this acceptable for 2.1?
I've added 2 AWS validated tests, and #8144 is building on this PR.
> SQS fix deduplication at queue level and deleted messages

- localstack/services/sns/publisher.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
This is building on top of #8144 and #8146, and adds test and implement the deduplication for FIFO topics. Right now, we are just properly using the SQS deduplication features, but SNS one is a bit different regarding the `MessageGroupId`, see https://docs.aws.amazon.com/sns/latest/dg/fifo-message-dedup.html, the deduplication is at the topic level. 
We are also not storing the deduplication ID yet, so we cannot return the proper `MessageId` and `SequenceNumber` from the publishing call, which we should do.
> SNS test and add deduplication for FIFO topic

- localstack/services/cloudformation/engine/entities.py
Any deployment referencing this parameter type fails currently
Add `AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>` parameter type and use ssm to retrieve it (it is stored in SSM).
> Add EC2 image ssm parameter type

- localstack/services/cloudformation/engine/entities.py
- localstack/services/firehose/provider.py
- localstack/services/sns/models.py
- localstack/services/sns/publisher.py
- localstack/utils/aws/client_types.py
Currently, we completely ignore the roles provided with the sns subscription or firehose s3 records integration.
This PR uses the roles where provided. If it is not provided, we will just fallback to the service principal. This is to remain non-breaking, but we need to increase parity for this at a later point.
> Fix firehose / s3 client creation of clients with role

- .circleci/config.yml
- scripts/tinybird/retrieve_legacy_data_from_circleci.py
- scripts/tinybird/upload_raw_test_metrics_and_coverage.py
This PR refactors the script `upload_raw_test_metrics_and_coverage.py` so it can be used for uploading the results for the pro-version as well. 
The script will pick the meta-data (for the `tests_raw_builds.datasource`) using the ENVs that are set in the corresponding environment (CircleCI or Github).
> add github-envs for tinybird upload scripts

- localstack/http/asgi.py
This PR simplifies the implementation of the asgi/wsgi bridge fundamental `HTTPRequestEventStreamAdapter`.
The adapter exposes and underlying `ASGIReceiveCallable` as a synchronous IO stream which we later plug into the werkzeug request object. Previously we had separate implementations of `read`, `readline`, and `readlines`, and did not use any base abstraction. However, `RawIOBase` already provides generic implementations of these methods over `readinto`. So I removed all of the special implementations and replaced them with a generic `readinto` implementation.
The drawback is that the generic implementations are not optimized, and require a buffered reader to be used (for instance, `readline` will always call `readinto` with a buffer size of 1, which causes very poor performance).
> simplify implementation of HTTPRequestEventStreamAdapter

- localstack/services/acm/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_acm.py
- tests/integration/test_acm.snapshot.json
Enhance parity for ACM certificates issued for wildcard subdomains . Addresses https://github.com/localstack/localstack/issues/8156
With the changes in this PR, the following TF script deploys successfully (confirmed that it was hanging indefinitely before):
```
resource "aws_route53_zone" "this" {
name = "example.com"
}
module "acm" {
source  = "terraform-aws-modules/acm/aws"
version = "4.3.2"
domain_name         = "*.example.com"
wait_for_validation = true
zone_id             = aws_route53_zone.this.zone_id
}
data "aws_acm_certificate" "this" {
depends_on = [module.acm]
domain = "*.example.com"
}
```
The changes are covered by a snapshot test. Overall, the amount of patching we're performing in ACM is becoming a bit ridiculous ;) - probably a candidate for decoupling from moto in the …
> Enhance parity for ACM certificates for wildcard subdomains

- localstack/constants.py
- localstack/services/firehose/provider.py
- localstack/services/opensearch/versions.py
- tests/integration/test_es.py
- tests/integration/test_firehose.py
- tests/integration/test_opensearch.py
- It adds OpenSearch 2.5 to the list of supported OpenSearch versions.
- It changes the default version of OpenSearch from 2.3 to 2.5 (as it is currently for AWS).
- It removes a previous limitation of AWS Kinesis Data Firehose which was initially not compatible with OpenSearch 2+.
- This was previously stated in the upgrade docs but has now vanished: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/version-migration.html
- The docs of AWS Kinesis Data Firehose also don't show any limitations: https://docs.aws.amazon.com/firehose/latest/dev/create-destination.html#create-destination-elasticsearch
> add OpenSearch 2.5, remove Firehose limitation

- localstack/services/cloudformation/models/dynamodb.py
- tests/integration/cloudformation/resources/test_dynamodb.py
- tests/integration/cloudformation/resources/test_dynamodb.snapshot.json
- tests/integration/templates/dynamodb_billing_conditional.yml
Conditional attributes are not completely/correctly resolved during the execution of `add_defaults` method of a GenericBaeseModel. The current patch allows to have a DynamoDB table that has multiple conditional attributes to be deployed.
There's more work required to completely fix the issue but with these small changes the amplify-localstack plugin can finally deploy a API stack to LocalStack.
Changes:
> fix default ProvisionedThroughput in DynamoDB

- localstack/aws/protocol/serializer.py
- tests/integration/test_sqs.py
This PR slightly adjusts the special message encoding for SQS which has been introduced with #5298.
With #5298, an SQS specific serializer has been introduced which performs a special escaping logic for the node text content in the XML responses. This is only done by SQS, and since it's a very rare practice, it's not supported by any popular XML serialization libraries.
#8002 raised the issue that this behavior causes issues when these escaping sequences are used in the sent message itself.
A message `"&quot;&quot;"` sent would be received as `""""`.
This was due to the nature of the initial implementation:
- These special characters have been escaped before the ElementTree serialization was performed: `"&quot;&quot;"` ==> `&quot;&quot;&quot;&quot;`
- The escape sequence itself contains …
> fix invalid SQS message decoding

- localstack/services/cloudformation/api_utils.py
- localstack/services/cloudformation/provider.py
- tests/integration/cloudformation/api/test_stacks.py
- tests/integration/cloudformation/api/test_stacks.snapshot.json
This PR is for issue #8027. While creating the stack name, there was no validation done. This PR implements the validation functionality for the CreateStack operation.
> CFn: Implemented stack name validation

- localstack/aws/handlers/legacy.py
- localstack/aws/protocol/op_router.py
- localstack/http/adapters.py
- localstack/http/asgi.py
- localstack/http/router.py
- localstack/services/opensearch/cluster.py
- localstack/services/s3/virtual_host.py
- localstack/services/s3/website_hosting.py
- setup.cfg
- tests/integration/s3/test_s3.py
- tests/unit/aws/protocol/test_op_router.py
- tests/unit/http_/test_router.py
- tests/unit/services/s3/test_virtual_host.py
This PR upgrades werkzeug to 2.2.3, and the dependents flask and quart, that were pinned in https://github.com/localstack/localstack/pull/6514
The changes since werkzeug 2.1.2 had the following effects:
* groups in regex host matchers must be non-capturing, otherwise they break. this was a problem in opensearch and s3, and also the `PortConverter` regex. things like `(.*).` in rules matchers need to be changed to `(?:.*).`
* `_request_ctx_stack` used to set the request context for flask and quart was removed
* `/<path:path>` matchers no longer remove trailing slashes. previously `/foo/` and `/foo` would both lead to the `path` being passed to be `foo`, now it is `foo/` and `foo` respectively.
The PR does the following:
* adds several tests that cover the changed behavior
* fixes our …
> upgrade werkzeug to 2.2.3

- localstack/services/cloudformation/models/s3.py
- tests/integration/cloudformation/resources/test_s3.py
- tests/integration/cloudformation/resources/test_s3.snapshot.json
- tests/integration/templates/s3_cors_bucket.yaml
Follow up from #7866, we now allow optional parameters to not be present for a bucket CORS configuration. Validated against AWS.
fixes #8173
> fix CFn s3 CORS configuration for optional parameters

- localstack/services/awslambda/provider.py
- tests/integration/awslambda/test_lambda_api.py
- tests/integration/awslambda/test_lambda_api.snapshot.json
Publishing image versions from image lambdas is currently broken, as we access the wrong code object.
* Fix access to codesha256
* Add test for versioning image lambdas
* Add dependency of `test_image` fixture to `login_docker_client` fixture, to correctly login (login fixture was previously unused, it seems)
> Fix publishing versions if package type is image

- localstack/services/cloudformation/models/dynamodb.py
- tests/integration/cloudformation/resources/test_dynamodb.py
Follow up from #8160 to not raise a TypeError if the wrong parameters are passed to a DynamoDB Table in a cloudformation template. 
I am not sure how to add negative testing for CloudFormation, but I tried against AWS with `test_default_name_for_table` and not specifying a `ProvisionedThroughput` and it fails. 
See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-provisionedthroughput
> fix TypeError for get_ddb_provisioned_throughput

- setup.cfg
Right after upgrading to Werkzeug==2.2.3 with https://github.com/localstack/localstack/pull/8104, version 2.3 has been released: https://github.com/pallets/werkzeug/releases/tag/2.3.0
Unfortunately, the upgrade again causes some issues. These issues are addressed in https://github.com/localstack/localstack/pull/8200.
In the meantime, this PR avoids the upgrade to Werkzeug and Flask 2.3.0 by adding an upper version boundary in the `setup.cfg`.
> avoid Werkzeug and Flask upgrade to 2.3.0

- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
This fixes the _significant_ performance issues of lambda on MacOS / Docker Desktop systems.
The main issue behind it was the check if a directory in the container exists and whether it is a directory, which was naively implemented as `get_archive`, which downloads the complete target directory.
This was caused mainly (by me :D) due to the missing API operation in the upstream docker sdk client for python, which is missing the abstraction for the head operation described here: https://docs.docker.com/engine/api/v1.42/#tag/Container/operation/ContainerArchiveInfo
* Uses the head operation https://docs.docker.com/engine/api/v1.42/#tag/Container/operation/ContainerArchiveInfo to get the container archive info without downloading it. This needs some internal operations of the docker client, …
> Fix docker copy_to_container performance, especially on mac

- localstack/aws/protocol/parser.py
- tests/unit/aws/protocol/test_parser.py
Addresses #8174.
In a nutshell, the issue was caused by not re-adding a trailing backslash for keys with special quoted characters.
> fix: s3 parsing key with trailing backslash and reserved chars

- Dockerfile
- localstack/services/dynamodb/packages.py
With the release of 2.0, specifically with #7927, we completely refactored the way LocalStack is built.
Together with this change, the pre-installation of LPM packages has been removed in order to further decrease the Docker image size (and lazy-loading them on-demand when the respective service needs a specific package).
Unfortunately, some users are facing issues with DynamoDB, one of the most used services of LocalStack:
- #8192
- #8100
- #8058
- #8054
This only affects the Community Docker image, `localstack/localstack-pro` always contained DynamoDB (as well as other packages).
After some internal discussions, we came to the conclusion that it might be the best approach to:
- Pre-ship the LocalStack Community Docker image with all packages necessary to run the most used (top 15) …
> re-install DynamoDB in Dockerfile, use cache for archive download

- tests/unit/http_/test_hypercorn.py
This commit slightly adjusts the `server_context` fixture used in the unit tests to wait for the server to be actually up before yielding it. This should fix the - currently more frequently occurring - flaky unit tests, where tests are failing since the servers are not (yet) reachable (f.e. [`test_proxy_server_with_streamed_response` in this test run](https://app.circleci.com/pipelines/github/localstack/localstack/14451/workflows/64d763f8-7d92-4dd6-b354-c14c3bdbafdf/jobs/107646)).
The patch actually came from @simonrw (thanks!) who implemented the fix in a feature branch, I just want to get this on the master asap.
> fix flaky unit tests using server_context fixture

- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
We are currently seeing error messages in the community test pipeline in -ext which indicate an error when verifying the access denied error of a docker push.
```
-------------------------------- live log call ---------------------------------
2023-04-27T11:45:30.758 DEBUG --- [  MainThread] localstack.utils.container_utils.docker_cmd_client : Pushing image with cmd: ['docker', 'push', 'alpine']
2023-04-27T11:45:30.758 DEBUG --- [  MainThread] localstack.utils.run       : Executing command: ['docker', 'push', 'alpine']
ERROR: '['docker', 'push', 'alpine']': exit code 1; output: b'Using default tag: latest\nThe push refers to repository [docker.io/library/alpine]\nf1417ff83b31: Preparing\nf1417ff83b31: Retrying in 5 seconds\nf1417ff83b31: Retrying in 4 seconds\nf1417ff83b31: Retrying in 3 …
```
> Fix mapping of denied access in docker hub

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/engine/transformers.py
- localstack/services/cloudformation/models/apigateway.py
- localstack/services/cloudformation/models/ec2.py
- localstack/services/cloudformation/models/kinesis.py
- tests/unit/test_cloudformation.py
An initial iteration over the template_deployer with @simonrw where we tried to untangle a few of the usage of the `Stack` class in the template deployer. More to come in separate PRs
Changes
- Replace usage of `Stack` class through the template deployer (initial iteration)
- Remove defaults from function details (`get_deploy_templates`)
- Remove ability to use boto3 resources in favor of clients in `get_deploy_templates`
> Reduce stack usage in template_deployer

- localstack/services/awslambda/invocation/lambda_models.py
- localstack/testing/pytest/fixtures.py
- tests/integration/awslambda/conftest.py
- tests/integration/awslambda/test_lambda.py
- tests/integration/awslambda/test_lambda.snapshot.json
- tests/integration/awslambda/test_lambda_api.py
- tests/integration/awslambda/test_lambda_api.snapshot.json
- tests/integration/awslambda/test_lambda_common.snapshot.json
- tests/integration/awslambda/test_lambda_runtimes.snapshot.json
AWS Lambda recently released the java17 managed runtime.
https://aws.amazon.com/blogs/compute/java-17-runtime-now-available-on-aws-lambda/
We also aim to support it.
* Add java17 to supported runtimes
* Add java17 to snapshot supported runtimes https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html#snapstart-runtimes
* Add java17 to snapshot tests
* Add java17 to common runtime tests
* Add java17 to java specific runtime tests
* Use python3.10 as default runtime for test_lambda.py tests
I also regenerated a lot of snapshots.
Fixes #8219
> Add support for Lambda java17 runtime

- localstack/services/cloudformation/cfn_utils.py
- localstack/services/cloudformation/deployment_utils.py
- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/models/ec2.py
Changes
* Move CFn utils from template_deployer to util files
* Remove fallback to "ResourceType" when "Type" was not available (didn't see where this would occur anyway)
* Remove reference to canonical resource type since all now already in their canonical form
> Move CFn utils and remove redundant code

- localstack/services/apigateway/integration.py
- tests/integration/apigateway/test_apigateway_integrations.py
Our http integration tests often fail as they return a `504` status code. Since our gateway probably does not return that, it is reasonable to assume the upstream `httpbin.org/robots.txt` request does that.
Log of failed run:
```
tests/integration/apigateway/test_apigateway_integrations.py::test_put_integration_responses 
-------------------------------- live log call ---------------------------------
2023-05-03T11:02:27.604  INFO --- [   asgi_gw_7] localstack.request.aws     : AWS apigateway.CreateRestApi => 201
2023-05-03T11:02:27.612  INFO --- [   asgi_gw_9] localstack.request.aws     : AWS apigateway.GetResources => 200
2023-05-03T11:02:27.621  INFO --- [   asgi_gw_8] localstack.request.aws     : AWS apigateway.PutMethod => 201
2023-05-03T11:02:27.629  INFO --- [   asgi_gw_3] …
```
> Try to fix flaky http integration tests

- tests/integration/s3/test_s3_cors.py
Remove comments and reintroduce the usage of virtual host addressing in S3 CORS tests. These were in place because at some point, it seemed like it reduced test failures that were finally fixed with #8134
Also remove some commented out code.
> reintroduce vhost use in s3 cors tests

- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
This PR relates to / extends https://github.com/localstack/localstack/pull/8215.
We are currently seeing a new error message in the community test pipeline in -ext which indicate an error when verifying the access denied error of a docker push.
```
2023-05-04T08:32:39.397 DEBUG --- [  MainThread] localstack.utils.container_utils.docker_cmd_client : Pushing image with cmd: ['docker', 'push', 'alpine']
2023-05-04T08:32:39.397 DEBUG --- [  MainThread] localstack.utils.run       : Executing command: ['docker', 'push', 'alpine']
ERROR: '['docker', 'push', 'alpine']': exit code 1; output: b'Using default tag: latest\nThe push refers to repository [docker.io/library/alpine]\nf1417ff83b31: Preparing\nunauthorized: access token has insufficient scopes\n'
RERUN …
```
> fix mapping of insufficient scopes return value to access denied exception

- localstack/services/events/provider.py
- localstack/utils/aws/client_types.py
This PR makes the Events service provider pass the RuleArn to the send_event_to_target function. Now the function can put the correct value on the request metadata for the new internal clients. 
Changes:
> Add SourceArn for Events Message Publisher

- localstack/services/cloudformation/deployment_utils.py
- localstack/services/cloudformation/engine/template_deployer.py
Gain understanding by refactoring internals and add static types.
In particular, the `func_details` type was difficult to nail down. 
Remove `configure_resource_via_sdk` since it had two purposes. Instead, inline the two behaviours into
* a  function that resolves the function properties, and
* code that deploys the resource via the SDK.
> CloudFormation: add types and restructure

- localstack/services/cloudformation/engine/template_deployer.py
This PR is start to move all ref resolving to occur once before the deploy starts. This will help us split the behaviour of the template deployer up into phases.
> CFn: Shift ref resolution earlier

- localstack/config.py
- localstack/services/sqs/provider.py
Following up on issue #8142 where memory leaks have been reported when LocalStack runs for a longer period (hours/days).
The issue seems to be related to a PR #7182, resulting from a feature request. 
With the PR we also added reporting of `Approximate*` messages to provide AWS parity. On LocalStack those approximate messages are reported periodically, e.g. every minute.
This leads to more metrics being added to CloudWatch, even without any interaction.
We now added two config flags to prevent related issues:
* `SQS_CLOUDWATCH_METRICS_REPORT_INTERVAL` which allows to configure the interval of reporting of the `Approximate*` messages
* `SQS_DISABLE_CLOUDWATCH_METRICS` to disable metrics reporting completely for SQS
> add config to disable cloudwatch metrics for SQS

- localstack/config.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
Currently, if the Docker socket is not available at the start of LocalStack, the initialization of the `SdkDockerClient` fails and the client will not recover during the runtime of LocalStack.
This PR changes this behavior such that:
- The initialization is tried again if the client is accessed at runtime, but not already available (lazy init of the SDK client if it was unsuccessful before).
- Introduces a retry config `DOCKER_SDK_DEFAULT_RETRIES` which allows configuring the amount of retries when initializing the client.
This addresses https://github.com/localstack/helm-charts/issues/21.
> fix SdkDockerClient recovery if docker socket not available initially

- localstack/aws/protocol/parser.py
- localstack/http/router.py
- localstack/testing/pytest/snapshot.py
- localstack/testing/snapshots/transformer_utility.py
- setup.cfg
- tests/integration/test_events.py
- tests/integration/test_sns.py
Right after upgrading to `Werkzeug==2.2.3` with https://github.com/localstack/localstack/pull/8104, version `2.3` has been released: https://github.com/pallets/werkzeug/releases/tag/2.3.0
In the meantime, the current release is 2.3.4: https://github.com/pallets/werkzeug/releases/tag/2.3.4
This upgrade breaks a few tests, which will be fixed within this PR.
Steps:
- This seems to be an issue with our MotoServer bridge (which is only used in legacy code).
- This might be related to recent changes in dropping certain decoding steps in Werkzeug 2.3.0 (mentioned in the changeset https://werkzeug.palletsprojects.com/en/2.3.x/changes/).
- This seems to be fixed with https://github.com/getmoto/moto/pull/6266.
- The change will end up in localstack with …
> upgrade Werkzeug to 2.3.4

- localstack/services/cloudformation/service_models.py
Follow-up to #8257 
Now removes the now unused variables in the `service_models.py` file
> Remove REF_*_ATTRS from service models

- localstack/testing/pytest/fixtures.py
- tests/integration/cloudformation/resources/test_sns.py
If a stack fails to deploy, it currently shows a helpful "assertion failed: False" error message. This does not explain _why_ the stack failed to deploy.
This PR adds the following information to an exception thrown by the fixture:
* the output of `describe_stacks` on the stack, and
* the stack events as this often shows the actual source of the error.
```
E       AssertionError: assert False
E        +  where False = wait_until(<function is_change_set_finished.<locals>._is_change_set_finished.<locals>._inner at 0x7f789e8d1750>, _max_wait=(None or 60))
E        +    where <function is_change_set_finished.<locals>._is_change_set_finished.<locals>._inner at 0x7f789e8d1750> = <function is_change_set_finished.<locals>._is_change_set_finished at …
```
> Add more detail in cloudformation stack deploy failure

- localstack/services/awslambda/invocation/lambda_service.py
- localstack/services/awslambda/provider.py
- localstack/services/s3/notifications.py
- localstack/services/s3/provider.py
- localstack/utils/aws/arns.py
- localstack/utils/aws/client_types.py
- tests/integration/s3/test_s3_notifications_lambda.py
- tests/integration/s3/test_s3_notifications_lambda.snapshot.json
- tests/integration/s3/test_s3_notifications_sns.py
- tests/integration/s3/test_s3_notifications_sns.snapshot.json
- tests/integration/s3/test_s3_notifications_sqs.py
- tests/integration/s3/test_s3_notifications_sqs.snapshot.json
To allow the IAM enforcement of s3 notifications, we need to use the new clients for its requests, and properly send the `s3:TestEvent` for sns and sqs targets (https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-enable-disable-notification-intro.html). For lambda, it seems like no such event is sent, so it uses a dryrun invoke there (which needed to be fixed) to check if the invocation passes through.
* Fix lambda dryrun invocations
* Introduce a BucketVerificationContext to contain all data necessary for validation (in essence everything sent in the `s3:TestEvent` payload.
* Send `s3:TestEvent` payload (sns, sqs) / dry run invoke (lambda)
* Migrate to the new clients
* Some changes due to changed AWS error messages caused by snapshot update
> Migrate s3 notifications to new clients, send test events

- localstack/services/kms/provider.py
- tests/integration/test_kms.py
- tests/integration/test_kms.snapshot.json
#8253 introduced a regression for some methods the key arn in the `KeyId` field instead of the ID.
The API documentation for (at least one) of the operation clearly states it will return the ARN in that field: https://docs.aws.amazon.com/kms/latest/APIReference/API_GenerateDataKey.html#API_GenerateDataKey_ResponseSyntax
* Add snapshot validated tests for the generate_data_key* methods
* Fix the return value
This is mainly done because the `aws_encryption_sdk` depends on the format being an ARN, which breaks our -ext pipeline.
* Check more return values of `KeyId` to be the correct ones @viren-nadkarni
> Fix KeyId return value as ARN for "generate_data_key*" methods

- localstack/services/s3/provider.py
This PR would fix the case when the usr restore the state created with the legacy S3 provider (everything would be stored in moto). The assumption was that moto would raise an exception if the CORS configuration didn't exist. However, while restoring an older state, the data would exist in moto but not in our store, thus creating a value error when trying to access the `CORSRules` (`NoneType` etc etc).
This will properly raise the 404 exception if the state is not properly restored.
> fix GetBucketCORS if CORS does not exist in store

- localstack/services/events/provider.py
- tests/integration/test_events.py
- tests/integration/test_events.snapshot.json
This PR would fix #8261
AWS allows publishing an Event to a nonexistent custom EventBus, it will just accept it and not do anything with it, as the test demonstrates (we even try to describe the nonexistent custom EventBus and it raises an error)
> fix PutEvents non-existent custom EventBus

- localstack/services/dynamodb/provider.py
- localstack/services/dynamodb/server.py
This PR improves the performance of commonly used operations by eliminating a `ListTables` call to DDB Local.
Earlier, LocalStack would use this call to look up whether the table existed in DDB Local during the replication region resolution. It was originally added to suppress error messages produced by DDB Local.
This PR also changes to log level of all DDB Local logs to DEBUG.
Error message printed by DDB Local when operating on non-existent table:
```
2023-05-11T17:07:05.987 DEBUG --- [-functhread9] l.services.dynamodb.server : 17:07:05.974 [qtp1511574902-17] WARN  com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler - DynamoDBLocalServiceException exception occured
2023-05-11T17:07:05.987 DEBUG --- [-functhread9] l.services.dynamodb.server : …
```
> DynamoDB: Remove extraneous call during region resolution

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/models/ec2.py
Fixes a regression introduced in recent CFn refactorings. 
PRO overwrites get_resource_type to add support for custom resources, but we didn't use this in get_ref and other call sites, causing this to fail -ext tests.
> Fix CFn model class & attribute lookup

- localstack/config.py
- localstack/constants.py
- localstack/utils/bootstrap.py
- localstack/utils/diagnose.py
- localstack/utils/strings.py
- setup.cfg
- tests/unit/test_config.py
- tests/unit/utils/test_bootstrap.py
- It moves the dependency on `localstack_client` (and its transitive dependency `boto3` from `install` to the `runtime` extra).
- It also cleans up the dependencies a bit (moving `apispec` to `runtime`, removes an unnecessary version pin on `amazon_kclpy`).
- This effectively reduces the CLI dependencies (because the install dependencies currently are the CLI dependencies).
- It replaces the legacy `service:port` mapping from the `localstack-client` with an dynamically detected list of services based on the loaded plugins.
- This means that the `localstack-client` does not have to be changed and released when introducing a new service emulator in LocalStack.
- The ports from the `localstack-client` would only be used with the environment variable …
> remove install dependency on localstack_client

- localstack/services/kms/models.py
- localstack/services/kms/provider.py
- localstack/testing/snapshots/transformer_utility.py
- localstack/utils/crypto.py
- tests/integration/test_kms.py
- tests/integration/test_kms.snapshot.json
- Fix the return value of `Encrypt` operation 
- Add `EncryptionContext` as an additional authentication data during encryption and decryption 
- Add encryption tags 
- Change mode of encryption from `CBC` to `GCM`, since the previous encryption method lacked built-in authentication and tags. 
- Add snapshot tests for encrypt and decrypt operations
> Add encryption context to encrypt and decrypt operations in KMS

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- tests/integration/s3/test_s3.py
This PR fixes #8325 
This bug seemed really weird, as our response was exactly the same as AWS, format was the same.
However, after trying to debug the issue in Java, it seemed the `Owner` field was properly parsed by the SDK. 
After looking at the code of the SDK, it seemed the order of the XML tag was important for the way they populate each bucket with the owner. Basically, if the Owner tag is second, they first populate every bucket with an empty owner, even though the owner was properly parsed at the end. (I'll put the Java code snippet from the SDK at the end of the PR).
We keep the order from the specs when we serialize the response: we use and iterate over the shapes members.
In the specs, `Buckets` is first and `Owner` is second. The trick is to remove `Buckets` from the specs …
> fix ListBuckets tag order

- localstack/constants.py
- localstack/services/kms/packages.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
Fix extraction of container Image when using podman. We have some customers who are using podman (with Docker not being available), and one of the issues that has surfaced is that the `list_containers(..)` Docker SDK call fails when using podman.
The root cause is that certain versions of podman use a slightly different API response format for listing containers: https://github.com/containers/podman/issues/8329 . In particular, the `Image` attribute of containers is `"sha256:..."` for Docker, but it contains the actual image name/tag like `"myimage:mytag-123"` for podman.
A simple integration test is added which simulates the podman API response via a monkey patch. Without the fix in the PR, this test would fail, and the patch in `docker_sdk_client.py` makes the test pass (and should fix …
> Fix extraction of container Image when using podman

- localstack/services/sns/publisher.py
- tests/unit/test_sns.py
localstack currently fails to publish messages if there is a filter policy against a message attribute that contains 'true', 'false' or 'null',
As documented, a String.Array attribute [can contain](https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html#SNSMessageAttributes.DataTypes) strings, numbers, or the keywords 'true', 'false' or 'null'. Message attributes are also required to be [valid JSON strings](https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html) for use in filtering.
Parse String.Array values with `json.loads` instead of `ast.literal_eval` to solve these issues.
Resolves #8304
> Fix issue publishing messages with String.Array attibutes

- setup.cfg
Lot of work has been done on S3 `CopyObject` upstream, which is validated by 2 PRs adding tests:
- #8291
- #8216
(Those PR are already targeting this branch, and the CI is green, so confident the fixes are good 👍)
Another S3 PR will build on work that has been on checksum calculation to remove some parts from our provider.
-ext run: https://github.com/localstack/localstack-ext/actions/runs/5022174661
> bump moto to 4.1.9.post1

- localstack/services/kms/provider.py
Follow up on https://github.com/localstack/localstack/pull/8302
Fixes `Sign`, `Encrypt` and `Verify` responses so that the `KeyId` field contains the key ARN.
https://docs.aws.amazon.com/kms/latest/APIReference/API_Encrypt.html#API_Encrypt_ResponseElements
> KMS: response key ID field must contain key ARN

- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
~WIP: this is WIP PR, all these tests will/should fail as the functionality is not yet implemented in moto. Will depend on upstream changes, the PR is available here: https://github.com/getmoto/moto/pull/6264~
This PR builds on #8326
This will validate the fixes for #8172 
All the tests will pass once all these PR are merged and a new release of moto-ext is done. (tested locally).
Sorry for the big amount of tests added in only one PR, this was built incrementally and I did not want to multiply the drafts PR. All those tests are AWS validated and snapshotted, so we can be pretty confident it works fine. 
Moto PRs linked:
- https://github.com/getmoto/moto/pull/6264
- https://github.com/getmoto/moto/pull/6303
- https://github.com/getmoto/moto/pull/6308
- …
> add s3 CopyObject tests

- localstack/services/cloudformation/models/cloudformation.py
- localstack/services/cloudformation/models/ec2.py
- tests/integration/cloudformation/resources/test_cloudformation.py
- tests/integration/cloudformation/resources/test_cloudformation.snapshot.json
- tests/integration/templates/cfn_waitcondition.yaml
- tests/integration/templates/cfn_waitconditionhandle.yaml
Add a fix for the state fetching of `WaitConditionHandle`, and add a _stub_ implementation for `WaitCondition`s.
This stub means that anything referencing the wait condition will resolve correctly, but the template deployer won't actually wait until the condition is met. Since we are doing a re-write of CFn anyway, we should factor it into that project.
This PR also includes a bigfix for EC2 instances: the boto3 `run_instances` method requires `MaxCount` and `MinCount` to be passed, but these are not valid CloudFormation properties.
> CFn: Stub WaitCondition resource

- Dockerfile
This PR changes the Python base image type from `slim-buster` to `slim-bullseye`, effectively upgrading the Docker base image's operating system from Debian Buster to Debian Bullseye.
This is basically an updated version of https://github.com/localstack/localstack/pull/7876 (Thanks to @Mins).
> upgrade debian base image from buster to bullseye

- localstack/http/hypercorn.py
This is a quick band-aid for the failing unit test in main:
```
=================================== FAILURES ===================================
_____________________________ test_gateway_server ______________________________
def test_gateway_server():
def echo_request_handler(_: HandlerChain, context: RequestContext, response: Response):
response.set_response(context.request.data)
response.status_code = 200
response.headers = context.request.headers
gateway = Gateway()
gateway.request_handlers.append(echo_request_handler)
port = get_free_tcp_port()
server = GatewayServer(gateway, port, "127.0.0.1", use_ssl=True)
>       with server_context(server):
tests/unit/http_/test_hypercorn.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
> fix failing test related to shutdown method of hypercorn server

- .github/workflows/tests-podman.yml
- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/apigateway/conftest.py
- tests/integration/conftest.py
- tests/integration/docker_utils/conftest.py
- tests/integration/docker_utils/test_docker.py
Enhance support for targeting Podman API with our Docker client. Running on Podman has been increasingly requested by some customers recently, and during testing we've identified some gaps and discrepancies between the Docker API and Podman API responses (see also previous PR #8333). 
This PR aims to be a starting point to address Podman support more systematically, and also have it covered by tests (we can reuse our excellent Docker client test suite for that purpose). Some/most of the existing Docker client tests are already working against Podman, and a new test marker `@skip_for_podman` has been introduced to temporarily skip failing tests for now. The goal would be to make all test pass over time, and then remove the `@skip_for_podman` marker.
The initial idea was to create a derived …
> Enhance support for Podman API in Docker client

- localstack/services/kms/models.py
Issue: `test_encrypt_via_aws_encryption_sdk` in localstack-ext repo invokes `aws_encryption_sdk` which internally updates encryption context param value by the method `_generate_signing_key_and_update_encryption_context` which is done after the actual encryption. Now, when we decrypt this cipher text, we have an additional reserved key-value pair of `encryption_context` by the name `aws-crypto-public-key` which was missing during encryption.
The PR removes the check of any such reserved key-value pair during decryption as no such value is passed for authentication in encryption.
> KMS: Remove the reserved key value pair from aad

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- tests/integration/s3/test_s3.py
This PR fixes the order of XML tags for `ListObjects` and `ListObjectsV2`.
This issue surfaced with #8359, where the Java SDK `TransferManager` would fail with a bucket name equal to `null`. After investigating, this utils is making use of the `ListObjects` API, and indeed, every object in `ObjectListing` `ObjectSummary` would have a bucket name equal to `null`, even though the response would properly return the `Name` field with the bucket name.
And once again, the tag order was important, I think this time from the reflection class `ObjectListing`, the way they cast an XML response into a class makes the order important, as they must first parse the bucket name to properly set it to each object in `Contents`. 
If these issues are getting more common, we might need to implement something …
> update ListObjects(V2) tag order for Java SDK

- localstack/services/sqs/provider.py
- localstack/services/sqs/query_api.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_sqs.py
This PR fixes the account resolution for operations to the SQS QueryAPI. Previously, we were not parsing authorization headers to allow account access outside the default `000000000000` account. This meant that, if you tried to perform an operation on, say, `http://localhost:4566/123456789012/my-queue`, then after proxying the call to the SQS Provider, `context.account_id` would return `000000000000` instead.
Moreover, in the `delete_queue` implementation in the backend, we were not using the account/region from the parsed queue URL, but instead using that of the context. Technically cross-account delete is not allowed, so it would be fine, but it made sense to fix that and add a defensive piece of code to warn the user that they're potentially doing something that's not allowed.
The …
> fix account resolution in SQS QueryAPI operations

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/provider.py
- tests/integration/cloudformation/api/test_changesets.py
- tests/integration/cloudformation/api/test_get_template_summary.snapshot.json
- tests/integration/cloudformation/resources/test_stack_sets.py
- tests/integration/cloudformation/resources/test_stack_sets.snapshot.json
- tests/integration/templates/sns_topic_simple.yaml
* fix "CreateStackInstances" operation where repetitive calls were resulting in 500 errors. Few runs against AWS have shown that AWS returns an OperationId in any case. This can be also reproduced with `aws copilot`
* update `StackSet` id format to match the one in AWS
* implement `DeleteStackInstances` operation to complete the parity test
* update template metadata on changeset execution
* Include template metadata into `GetTemplateSummary` response
https://github.com/localstack/localstack/issues/8255
> fix stack set instance creation, add deletion

- bin/release-helper.sh
This PR contains a very small fix which allows using `set-dep-ver` in `bin/release-helper.sh` with `requirements.txt` files (instead of just `setup.cfg`). It just changes the regex such that the spaces at the beginning of the file are optional (`\s*`) instead of "at least once" (`\s+`).
> fix release helper script for requirements.txt files

- tests/integration/test_sqs.py
This is a minor change for a test that has been flaking. The reason is that potentially not enough time has passed between the delay and receiving the messages. Since we changed the behavior of `receive_message` in combination with `MaxNumberOfMessages` and `WaitTimeSeconds` there's a chance that fewer messages than 3 will be returned, although we are asking for 3.
So now, we do a hard sleep with an extra second to give the messages enough time to arrive in the queue. since this is a FIFO queue, we should receive all three messages in the `receive_message` call if they are in the queue.
> make test_fifo_queue_send_message_with_delay_on_queue_works more robust

- localstack/services/secretsmanager/provider.py
- tests/integration/secretsmanager/test_secretsmanager.py
- tests/integration/secretsmanager/test_secretsmanager.snapshot.json
For `ClientRequestToken` in the following operations (CreateSecret, UpdateSecret, RotateSecret, PutSecretValue), there's a specific note in the documentation:
https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/create-secret.html#options
> If you use the AWS CLI or one of the AWS SDKs to call this operation, then you can leave this parameter empty. The CLI or SDK generates a random UUID for you and includes it as the value for this parameter in the request. If you don't use the SDK and instead generate a raw HTTP request to the Secrets Manager service endpoint, then you must generate a ClientRequestToken yourself for the new version and include the value in the request.
As we tested with boto, we never tried to run a request without it against AWS (just mocked locally with …
> add ClientRequestToken validation for SecretsManager

- localstack/services/awslambda/event_source_listeners/adapters.py
- tests/integration/awslambda/test_lambda_integration_dynamodbstreams.py
- tests/integration/awslambda/test_lambda_integration_dynamodbstreams.snapshot.json
Should address #8199.
We reuse the same encoder from the DDB provider. 
Nit: we don't do base 64 encoding in DynamoDB. Therefore, I temporarily skipped the validation for `"$..Records..dynamodb.NewImage.binary_key.B"`.
> fix: Lambda integration with DDB binary items

- localstack/services/s3/models.py
- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR adds support for S3 Analytics Configurations.
The API was not throwing `Not Implemented` error but the feature was not implemented.
- get_bucket_analytics_configuration
- put_bucket_analytics_configuration
- list_bucket_analytics_configurations
- delete_bucket_analytics_configuration
- TestAccS3BucketAnalyticsConfiguration_basic
- TestAccS3BucketAnalyticsConfiguration_removed
- TestAccS3BucketAnalyticsConfiguration_updateBasic
- TestAccS3BucketAnalyticsConfiguration_WithFilter_empty
- TestAccS3BucketAnalyticsConfiguration_WithStorageClassAnalysis_empty
- TestAccS3BucketAnalyticsConfiguration_WithStorageClassAnalysis_default
- TestAccS3BucketAnalyticsConfiguration_WithStorageClassAnalysis_full
- TestAccS3BucketAnalyticsConfiguration_WithFilter_singleTag
- …
> Added support for s3 analytics configuration

- localstack/services/cloudformation/models/kms.py
- localstack/services/cloudformation/provider.py
- localstack/services/cloudformation/stores.py
- tests/integration/cloudformation/resources/test_kms.py
- tests/integration/cloudformation/resources/test_kms.snapshot.json
- tests/integration/templates/template34.yaml
Small change to fix extraction of `Arn` attribute in KMS Key CloudFormation resources.
The starting point for this change was an issue with the [`copilotlocal`](https://github.com/localstack/copilot-cli-local) CLI, which was raising seg faults:
```
$ copilotlocal app init
...
$ copilotlocal env init
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102ebd0ec]
goroutine 1 [running]:
github.com/aws/copilot-cli/internal/pkg/deploy/cloudformation/stack.ToAppRegionalResources(0x14000139438)
github.com/aws/copilot-cli/internal/pkg/deploy/cloudformation/stack/app.go:237 +0xdc
...
```
The root cause for this that the stack outputs of the stack created by Copilot contains an output without `OutputValue` …
> [minor] Fix extraction of Arn in KMS Key CloudFormation resource

- localstack/services/s3/models.py
- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR adds support for S3 intelligent tier configuration mocking.
- get-bucket-intelligent-tiering-configuration
- put-bucket-intelligent-tiering-configuration
- delete-bucket-intelligent-tiering-configuration
- list-bucket-intelligent-tiering-configurations
- TestAccS3BucketIntelligentTieringConfiguration_basic
- TestAccS3BucketIntelligentTieringConfiguration_disappears
- TestAccS3BucketIntelligentTieringConfiguration_Filter
> added support for intelligent tier in s3

- localstack/services/sns/models.py
- localstack/services/sns/provider.py
- tests/integration/test_sns.py
This PR adds cross-account access support for SNS topics.
This is allowed for following operations:
- GetTopicAttributes
- SetTopicAttributes
- AddPermission
- RemovePermission
- Publish
- Subscribe
- ListSubscriptionsByTopic
- DeleteTopic
Depends on [getmoto/moto#6330](https://github.com/getmoto/moto/pull/6330)
> SNS: Implement cross-account access

- localstack/cli/localstack.py
- localstack/config.py
- localstack/utils/bootstrap.py
- tests/bootstrap/test_cli.py
This PR adds small enhancements to the bootstrap logic, to enable CLI startup (`localstack start`) from within Docker containers in different environments.
The starting point for this change is a Github Codespaces workspace that we're currently preparing for the AWS Builders Day workshop: https://github.com/localstack/localstack-workshop/blob/main/.devcontainer/devcontainer.json . The Codespaces environment is itself running in a Docker container (devcontainer), and with the current version of the CLI we're receiving this error:
```
$ localstack start
...
File "/tmp/venv/lib/python3.10/site-packages/localstack/cli/localstack.py", line 168, in cmd_start
bootstrap.start_infra_in_docker()
File "/tmp/venv/lib/python3.10/site-packages/localstack/utils/bootstrap.py", line 591, in …
```
> Enhance bootstrap logic to allow CLI startup from within Docker

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This issue has been reported in #8392, moto would raise an `InternalError` when trying to complete a multipart upload that wasn't initiated, because it was directly accessing the `multiparts` bucket dict field with the `upload_id` as the key, which would raise a `KeyError`. It had the same issue in `upload_part`, but this was correct in `abort_multipart_upload`.
Added AWS validated tests, and fixed it in the provider for a quick fix. Ultimately, this should be fixed upstream.
_fixes #8392_
> fix s3 complete_multipart and upload_part internal error 

- localstack/services/sqs/constants.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
Fixes #8397. Looks like we mistakenly considered `ContentBasedDeduplication` to be an intrinsic property, but I added a couple of tests that show it can be updated and checked correctly when calling `CreateQueue` with different values of it.
> fix SQS SetQueueAttributes when seting ContentBasedDeduplication

- localstack/config.py
- localstack/services/cloudformation/engine/template_deployer.py
There is currently lots of exception handling in and around the template deployer within CloudFormation. This makes it more complex to understand what goes wrong with stack deployments.
This change adds a config variable to present exceptions either:
* fully, raising the exception up, or
* logging at `exception` level the message, exception and traceback, instead of logging at a lower level (often debug) with a possibly less-than-helpful error message.
This feature can be enabled with the `CFN_VERBOSE_ERRORS` configuration variable/environment variable.
> CFn: optional verbose errors

- .circleci/config.yml
- pyproject.toml
Capture additional contexts using pytest and coverage, allowing us to answer the question:
**Which tests execute this line of code?**
`coverage.py` can record "dynamic contexts", which annotate coverage "spans" with metadata. One supported type of context is "test context", meaning that each coverage "span" gets annotated by the test name that ran it.
Using this, `python -m coverage html --show-contexts` adds annotations to the output HTML page indicating which tests executed which lines of code.
This is unbelievably useful when trying to execute a specific function. If there's test coverage, then simply executing relevant tests runs the code of interest. I'm finding this powerful for investigating our CloudFormation implementation, since I can quickly go from the code block to test and …
> Capture additional coverage context

- localstack/cli/localstack.py
- localstack/cli/profiles.py
- localstack/config.py
- tests/unit/cli/test_profiles.py
This PR fixes a small issue in the CLI which we overlooked in #7329.
This linked PR fixes the CLI profile detection (by manually parsing the `profile` argument and setting the `CONFIG_PROFILE` environment variable). This works perfectly fine when using the `--profile=<profile-name>` notation, but there was a small issue when using the `--profile <profile-name>` notation.
It also adds another line to the banner which indicates the loaded profile (if a profile was loaded, otherwise the line is not shown):
```
$ .venv/bin/python -m localstack.cli.main --profile pro start 
__                     _______ __             __
/ /   ____  _________ _/ / ___// /_____ ______/ /__
/ /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
/ /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,< …
```
> fix cli profile handling, add profile indicator to banner

- localstack/cli/localstack.py
- tests/unit/cli/test_cli.py
This PR fixes a confusing error message when using the `localstack update` command to update the CLI (either with `all` or `localstack-cli`) when using our LocalStack CLI frozen binaries built with PyInstaller ([localstack/localstack-cli](https://github.com/localstack/localstack-cli)):
```
$ localstack update localstack-cli
─────────── Updating LocalStack CLI ───────────
⠦ Updating LocalStack CLI...Usage: localstack [OPTIONS] COMMAND [ARGS]...
Try 'localstack --help' for help.
Error: No such option: -m
✖ LocalStack CLI update failed
```
With this PR we explicitly detect that we are running in a frozen environment, print a warning and exit with a non-zero exit code:
```
$ localstack update all
✖ The LocalStack CLI can only update itself if installed via PIP. Please follow the instructions …
```
> show error on frozen attempt to update localstack-cli

- localstack/utils/container_utils/container_client.py
- localstack/utils/net.py
- tests/unit/test_misc.py
This PR addresses https://github.com/localstack/localstack/issues/5758.
It fixes several issues concerning the protocol handling in the `PortMapping` class, which was introduced in #6314.
Previously, the existence checks when adding new mappings were not considering the protocol. The fixes in this PR now allow adding both, a UDP and TCP port mapping which has the same range. This in turn fixes an issue in the LocalStack Pro CLI where the DNS TCP port was added to the port mapping, but the UDP port was suppressed.
/cc @whummer
> fix multi-protocol port mapping

- localstack/constants.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
This PR adds tests for cross-account support to S3 for following operations:
- GetObject
- PutObject
- ListObjects
The actual implementation was done in Moto in below linked PRs. This also introduces a shared namespace for buckets.
Depends on:
- https://github.com/getmoto/moto/pull/6333
- https://github.com/localstack/localstack/pull/8410
cc: @dfangl
> S3: Implement cross-account access

- .github/workflows/tests-pro-integration.yml
It seems like we have issue with the integration tests against our pro extensions due to a conflict with packages being installed on the CI system before running the tests.
This seems to be related to the package repos on the GitHub runners (it does not happen on other, private runners).
Unfortunately, apt is not automatically resolving the conflict by downgrading postgres to a matching version without explicitly stating it.
I cancelled the circle pipeline runs, because this only touches the GitHub workflow.
I'm happy for any feedback, this apt call caused quite a lot of issues in the past.
> fix package incompatibilities in pipeline

- localstack/services/awslambda/lambda_executors.py
- tests/integration/awslambda/test_lambda_whitebox.py
fix: https://github.com/localstack/localstack/issues/7940
This PR allows for correct handling of lambda runs that output more than 4000 bytes, including multibyte characters.
> Dont abort when failed to decode logs that contains multibyte characters

- localstack/services/sns/models.py
- localstack/services/sns/provider.py
- localstack/services/sqs/provider.py
- localstack/utils/aws/arns.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
- tests/integration/test_sqs.py
We've had a report that cross account publishing didn't work as expected, especially with queues from another account.
This PR does not add any enforcement of cross account access, but now allow SNS to publish to a queue in another account.
The fix consists of properly passing `QueueOwnerAWSAccountId` using the account id present in the queue URL to the `get_queue_url` call. Also, `GetQueueUrl` now properly uses this account id to retrieve the proper store.
~Also modified the SNS store attributes to be cross-account, as those are needed in the publisher, and an account can publish to another account's topic.~
Now removed that part, and properly parsed the ARN of the topic in the necessary operation to properly use the account id from the arn to then pass the store to the publisher, and …
> fix SNS cross account SQS publish + SQS get_queue_url

- localstack/services/sqs/query_api.py
- tests/integration/test_sqs.py
Uses the new `connect_to` construct instead of `aws_stack` to connect to SQS in the SQS Query API. I'd like to use this later to try out #7396  /cc @viren-nadkarni @dfangl 
I also removed a couple of deprecated tests.
> update SQS QueryAPI to use new aws client factory

- localstack/services/awslambda/invocation/lambda_service.py
Be consistent with linked documentation and use `awslocal` instead of `aws` CLI for LocalStack hint logging.
> Use awslocal in LocalStack hint logs

- localstack/cli/localstack.py
- tests/unit/cli/test_cli.py
This PR adds a new shell command to support the configuration of auto-completion for the LocalStack CLI.
It uses the Click-feature for Shell completion: https://click.palletsprojects.com/en/8.1.x/shell-completion/
Unfortunately, the configuration is a bit cumbersome:
> In order for completion to be used, the user needs to register a special function with their shell. The script is different for every shell, and Click will output it when called with _{PROG_NAME}_COMPLETE set to {shell}_source. {PROG_NAME} is the executable name in uppercase with dashes replaced by underscores. The built-in shells are bash, zsh, and fish.
This is where the new `completion` command comes in. It basically just simplifies printing the shell completion code for a given shell. This completion code can then - …
> add new CLI command to simplify shell completion

- localstack/utils/container_networking.py
This PR extends the endpoint detection (i.e. detecting the IP address of LocalStack) in host mode (outside of docker) for other systems than Linux.
This is a draft PR, and I would love to get further input and feedback!
/cc @dfangl @dominikschubert @joe4dev @simonrw
> fix MacOS host mode docker host IP detection

- localstack/services/awslambda/packages.py
Update lambda init version to https://github.com/localstack/lambda-runtime-init/releases/tag/v0.1.18-pre
This will remove some confusing exception logging where raised exceptions during a function invocation were also logged in the same way that an init error was logged.
> Update lambda init to v0.1.18-pre

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/provider.py
- localstack/services/cloudformation/models/apigateway.py
- tests/integration/cloudformation/resources/test_apigateway.py
- tests/integration/cloudformation/resources/test_apigateway.snapshot.json
- tests/integration/templates/apigateway_integration_from_s3.yml
Depends on #8371 
Implementing the `BodyS3Location` property to `AWS::ApiGateway::RestApi` as requested by a customer.
This property allows Cloudformation to directly fetch the "Body" property from an S3 bucket.
However, I am not sure how to do negative testing with Cloudformation, so for now any S3 exception is going to bubble up? 
Small note: I've also removed a line from the API Gateway importer because it was erasing tags after updating a RestAPI, which is not the default mode anymore. 
Resource:
https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-s3location.html
> add BodyS3Location property to AWS::ApiGateway::RestApi

- localstack/services/cloudformation/models/s3.py
- tests/integration/cloudformation/resources/test_s3.py
- tests/integration/cloudformation/resources/test_s3.snapshot.json
- tests/integration/templates/s3_bucket_website_config.yaml
This PR adds support for bucket website configuration when creating a S3 bucket using cloudformation.
Missing feature was revealed by an AWS sample.
> add support for CFN and s3 bucket website configuration

- localstack/services/dynamodbstreams/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/test_dynamodb.py
- tests/integration/test_dynamodb.snapshot.json
As seen here: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_GetShardIterator.html, the shard iterator for dynamodbstreams differs from the kinesis one in one important aspect, namely the prefix of the stream arn followed by `|<int>|` and then an iterator in a similar format like kinesis data streams.
* Add tests specifically asserting on the sharditerator format
* Fix shard iterator format
It is quite unclear to me, and I did not find any information on that, what the integer between the pipes `|<int>|` is supposed to represent. I got the values 1 and 2 back from AWS, not sure what they are exactly denoting. As long as this is unclear, and since it does not seem to make a difference for now, I hardcoded it to 1 with a comment for it.
> Prefix dynamodb streams shard iterator with stream arn

- localstack/services/cloudformation/engine/entities.py
- localstack/services/cloudformation/engine/parameters.py
- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/engine/template_preparer.py
- localstack/services/cloudformation/engine/transformers.py
- localstack/services/cloudformation/provider.py
- tests/integration/cloudformation/api/test_changesets.py
- tests/integration/cloudformation/resources/test_kinesis.py
- tests/integration/cloudformation/resources/test_kinesis.snapshot.json
- tests/integration/cloudformation/resources/test_s3.py
- tests/integration/cloudformation/test_template_engine.py
- tests/integration/templates/cfn_intrinsic_functions.yaml
- tests/integration/templates/cfn_kinesis_stream.yaml
- tests/unit/test_cloudformation.py
- Parameters are resolved only once when executing CREATE/UPDATE tasks. While the corresponding logic lives in `parameters.py` now, the responsibility is moved further up to the API provider to make this as transparent as possible.
- Unifies parameter resolving (previously this was done in multiple places such as in Stack methods, template_processing, transformations, template deployer)
- Update handling is now more robust and simpler.
- Does not affect how parameters are used when resolving values/refs in the TemplateDeployer/Stack, i.e. they are still merged with resources and mappings/conditions in `Stack.resources` for now. This will be split up in a future PR.
- No new parameter types have been added
Also note I didn't add further tests yet since I didn't want to bloat this too much. …
> Refactor handling of CFn stack parameters

- tests/integration/awslambda/test_lambda_performance.py
Add basic performance tests for Lambda. The main idea is to have an initial version of reproducible tests within the IDE.
I looked into the dedicated `performance` directory under tests but they do not integrate with pytest nor can they leverage the convenient test utils such as fixtures, running against external LocalStack, etc.
Initial results and basic plotting scripts are available at https://github.com/joe4dev/localstack-performance-testing/
The preliminary results support that warm starts are pretty fast around 17ms (min) to 77ms (p99) on macOS but even faster on Linux.
Cold starts seem pretty slow 3.3s (min) to 7.5s (p99) on macOS with Docker compared to 700ms (min) to 870ms (p99) on Linux in host mode. Daniel's summary of …
> Add basic lambda performance tests

- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/apigateway/test_apigateway_basic.py
- tests/integration/apigateway/test_apigateway_common.py
- tests/integration/apigateway/test_apigateway_common.snapshot.json
When looking at an OpenAPI file, I've spotted an issue where we didn't validate what the `apiKeySource` was before validating the key (if the source is set to `AUTHORIZER`, as authorizers are only mocked in community, it would always fail before). 
I've migrated one integration test to be AWS validated, there still one left but it'll be migrated when we pushed the migration further for `UsagePlan` and `ApiKey`. 
Also fixed a parity issue where we wouldn't validate if the key was enabled.
> fix validating APIGW API key when apiKeySource is AUTHORIZER

- localstack/cli/localstack.py
- localstack/cli/profiles.py
- localstack/utils/bootstrap.py
- tests/unit/cli/test_cli.py
This PR contains some cleanup and restructuring of the LocalStack CLI:
- It adds short-codes for most of the options (f.e. `localstack -p pro start` to select the `pro` profile, `localstack -v` to show the version, `localstack -h` for help, `localstack config validate -f docker-compose-test.yml`,...).
- It adds lots of help text. All commands now have a short help (shown on the group's help output) and a normal help (shown on the command's help output).
- All the help text is now in docstrings (see https://click.palletsprojects.com/en/latest/documentation/#help-texts).
- It does some restructuring (to keep utility functions close to the commands using them).
- It adds proper type hints everywhere.
> add help texts, short args, format option decorator

- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR will fix one case of #8422, the first case is already fixed. 
We would raise an exception when the `key["KeyMetadata"]["Enabled"]` was `False`, but there is a specific exception when the `key["KeyMetadata"]["KeyState"]` is `PendingDeletion`. We're now raising the proper exception, and it's AWS validated. 
This fix needs `S3_SKIP_KMS_KEY_VALIDATION=0` to be effective.
_fixes #8422_
> fix S3 exception when using KMS key state PendingDeletion

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/invocations.py
- tests/integration/apigateway/test_apigateway_import.py
- tests/integration/apigateway/test_apigateway_import.snapshot.json
- tests/integration/files/openapi.spec.global-auth.json
This PR is building on #8437, we were not properly setting the `apiKeySource` of the REST API when importing the file.
Also, we were not making use of default authorizer defined as a top level property. 
I also fixed passing `x-amazon-apigateway-any-method` as an HTTP method, but properly replaced it by  "ANY" like AWS does. I think we could remove any `x-amazon-apigateway-any-method` in the invocation code now, as it has been properly replaced.
> fix apigw import default authorizer, apiKeySource and ANY method

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/models.py
- localstack/services/apigateway/provider.py
- tests/integration/apigateway/apigateway_fixtures.py
- tests/integration/apigateway/test_apigateway_import.py
- tests/integration/apigateway/test_apigateway_import.snapshot.json
- tests/integration/files/openapi.spec.circular-ref-with-request-body.json
- tests/integration/files/openapi.spec.circular-ref.json
- tests/integration/files/openapi.spec.global-auth.json
- tests/unit/test_apigateway.py
Changes made to avoid circular references in `Model` containing references to itself, which can happen easily.
Example: A Person contains a `children` property, which is a collection of `Person`. After resolving the models, it will fail to be serialised to JSON because it contains circular references. Or a container which contains an object with a reference to its container. 
AWS solves this issue by storing the template with its absolute reference[[1]](https://json-schema.org/understanding-json-schema/structuring.html#retrieval-uri)[[2]](https://stackoverflow.com/questions/37823112/how-do-i-reference-one-model-from-another-model-using-aws-api-gateway). It might be stored fully resolved server-side, or might be resolved when actually validating the template. ~Still WIP, so I'll see how I …
> fix apigw model resolving when importing and when validating

- localstack/services/awslambda/invocation/docker_runtime_executor.py
Addresses https://github.com/localstack/localstack/issues/7539
This PR re-introduces the `LAMBDA_DOCKER_DNS` configuration previously supported in the [old lambda provider](https://docs.localstack.cloud/references/configuration/#lambda-legacy).
This optional configuration sets a DNS server for the container running your lambda function. `LAMBDA_DOCKER_DNS` takes precedence over [transparent endpoint injection](https://docs.localstack.cloud/user-guide/tools/transparent-endpoint-injection/dns-server/) when using LocalStack Pro. A warning message informs pro users.
Depends on ext companion PR to selectively disable transparent endpoint injection: https://github.com/localstack/localstack-ext/pull/1758
The following scenarios are tested:
Tested against Docker (locally built) with a Python …
> Add Lambda Docker DNS configuration

- localstack/utils/container_utils/container_client.py
- tests/unit/test_dockerclient.py
Currently, if additional flags like `LAMBDA_DOCKER_FLAGS` are provided at all, privileged is set to true for docker containers. This is not only dangerous, but also problematic in restricted docker environments, e.g. bitbucket.
Fixes #8460.
* Fixes argparser always adding privileged=True. The cause of this was the argparser setting the privileged flag to true or false, never None, even if not provided. This is expected behavior for the "store_true" action.
* Add test to check if privileged flags are indeed false for an empty string as argument string. This test extension would have caught the issue.
> Fix defaulting to privileged=true if additional flags are provided

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
This PR will fix #8415, and validate that #8441 has been fixed since 1.4. 
We needed to retrieve the attribute from moto, because moto is hardcoding what attributes it returns, and is not dynamic. 
Added bit of parity, but this is a small fix.
> fix SNS SignatureVersion for Topic and validate Subscription attributes when set a creation

- localstack/services/cloudformation/models/iam.py
- localstack/services/iam/provider.py
- tests/integration/test_iam.py
- tests/integration/test_iam.snapshot.json
If the AssumeRolePolicyDocument is not valid json, we have problems later with IAM enforcement, as it breaks the interface contract of the STS IAM plugin.
* Verify the AssumeRolePolicyDocument actually being valid json by trying to decode it
* AWS validated test for this behavior
> Verify AssumeRolePolicyDocument is valid json

- localstack/services/cloudformation/engine/template_deployer.py
Previously when deploying a resource in `determine_physical_resource_id` a fetch_state was executed and the result was then available in the resource props for later deletion.
With our rework of the physical resource ID, this will now not necessarily be the case anymore since the `PhysicalResourceId` is available immediately after the handler/boto call and therefore `determine_physical_resource_id` won't be called and the state missing from the props.
This sometimes now leads to issues when trying to delete resources because the attributes they depend on might not have been saved to the resource state if they haven't been added manually in the result handler to the resource properties.
> Add a fetch state call after CFn resource deployment

- localstack/services/apigateway/helpers.py
Fix an issue when issuing a log warning, I missed a string interpolation `%s` and provided 3 parameters for only 2 `%s`. 
This will fix it.
> fix apigateway issue with logging template

- localstack/services/events/provider.py
Make store lookups for Events rule jobs request context aware. This issue surfaced when restoring rule jobs from persistence/pods (companion PR following soon).
At its core, the PR replaces `aws_stack.connect_to_service(..)` calls with in-memory lookups, and adds `EventsStore` as a parameter for the `get_scheduled_rule_func`/`put_rule_job_scheduler` util methods, to ensure we're targeting the right account/region.
/cc @giograno 
* pass request context to `get_store(..)`, to extract account/region directly from the `context` object
* add `EventsStore` as a parameter for the `get_scheduled_rule_func`/`put_rule_job_scheduler` util methods
* add `get_event_bus_name(..)` util function that extracts the bus name from a name/ARN, or returns the `default` event bus as a …
> Make store lookups for Events rule jobs request context aware

- localstack/services/awslambda/event_source_listeners/adapters.py
- localstack/services/awslambda/event_source_listeners/dynamodb_event_source_listener.py
- localstack/services/awslambda/event_source_listeners/kinesis_event_source_listener.py
- localstack/services/awslambda/event_source_listeners/sqs_event_source_listener.py
- localstack/services/awslambda/event_source_listeners/stream_event_source_listener.py
- localstack/testing/pytest/fixtures.py
- tests/integration/awslambda/test_lambda_integration_dynamodbstreams.py
To provide IAM enforcement, we have to use the new clients, with the execution role assumed, for the event source mapping operations.
* Use Adapters to get the right clients for the operation
* Migrate to new client factory
* Consolidate `wait_for_dynamodb_stream_ready` fixtures
* Handle failure for get_records operation in the streams event source listener separately, to avoid crashing the whole thread
> Use new clients in lambda event source mappings

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/models/apigateway.py
- localstack/services/cloudformation/models/cloudformation.py
- localstack/services/cloudformation/models/ec2.py
- localstack/services/cloudformation/models/ecr.py
- localstack/services/cloudformation/models/events.py
- localstack/services/cloudformation/models/iam.py
- localstack/services/cloudformation/models/kms.py
- localstack/services/cloudformation/models/s3.py
- localstack/services/cloudformation/models/sns.py
- localstack/services/cloudformation/models/sqs.py
The CloudFormation `GenericBaseModel` classes allowed use of an arbitrary function to deploy the resource. The function signature was:
```
def create(resource_id, resources, resource_type, func, stack_name):
...
```
When deploying a single resource:
* the list of resources is redundant
* the resource type is already known
* the `func` argument is not relevant
This PR changes the function signature to `def create(logical_resource_id: str, resource: dict, stack_name: str)` to only supply the relevant information.
To prevent `-ext` breakage, if attempting to call this function raises a type error (because the signature is still the old signature) then we fall back to using the old function signature.
A PR integrating the new style resource providers depends on this change, since I need to …
> CFn: simplify deploy function handling

- localstack/services/sns/provider.py
- tests/integration/test_sns.py
- tests/integration/test_sns.snapshot.json
This PR fix #8486, the issue is pretty thorough in explaining what the issue is.
Basically, I forgot to add the logic I've implemented in `publish` for the `publish_batch`, that would already load the message into a dict if the message structure was `json`. This is now fixed and validated via 2 AWS validated and snapshot tests. 
I've also moved around some validations in order to be in line with AWS in how and what they validate in what order.
> fix SNS publish_batch when MessageStructure is JSON

- localstack/services/kms/provider.py
- tests/integration/test_kms.py
- tests/integration/test_kms.snapshot.json
- Add `EncryptionContext` parameter to `GenerateDataKeyWithoutPlaintext` and `GenerateDataKey'. 
- Write snapshot tests to check the expected behaviour against AWS. 
Related issues: https://github.com/localstack/localstack/issues/8505 and https://github.com/localstack/localstack/issues/8503
> kms: Add encryption context to generate data key with and without plaintext 

- localstack/services/kms/exceptions.py
- localstack/services/kms/models.py
- localstack/services/kms/provider.py
- localstack/services/kms/utils.py
- tests/unit/test_kms.py
A customer reported segmentation faults during persistence state restoration involving KMS keys and aliases. It turned out that we were persisting the private key object as part of the KMS key abstraction. This was problematic because this object, created by the underlying SSL implementation, maintained in-memory references. These references broke when the KMS state was deserialised and restored, causing a segfault.
This PR removes the assignment of the private key object to `KmsCryptoKey` abstraction, preventing it from going into the state. Instead it is created dynamically from the DER encoded private key string.
I've taken this opportunity to also refactor the KMS store definition. The helper methods have been moved out of the model definitions.
> KMS: Fix segfault during persistence state restore

- localstack/services/kms/provider.py
- tests/integration/test_kms.py
- tests/integration/test_kms.snapshot.json
- Add `EncryptionContext` parameter to `GenerateDataKeyPairWithoutPlaintext` and `GenerateDataKeyPair`.
- Write snapshot tests to check the expected behaviour against AWS.
> kms: add encryption context to generate data key pair apis in kms

- localstack/services/cloudformation/cfn_utils.py
- localstack/services/cloudformation/deployment_utils.py
- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/models/apigateway.py
- localstack/services/cloudformation/models/awslambda.py
- localstack/services/cloudformation/models/certificatemanager.py
- localstack/services/cloudformation/models/cloudformation.py
- localstack/services/cloudformation/models/cloudwatch.py
- localstack/services/cloudformation/models/dynamodb.py
- localstack/services/cloudformation/models/elasticsearch.py
- localstack/services/cloudformation/models/events.py
- localstack/services/cloudformation/models/iam.py
- localstack/services/cloudformation/models/kinesis.py
- localstack/services/cloudformation/models/opensearch.py
- localstack/services/cloudformation/models/route53.py
- localstack/services/cloudformation/models/s3.py
- localstack/services/cloudformation/models/secretsmanager.py
- localstack/services/cloudformation/models/sns.py
- localstack/services/cloudformation/models/sqs.py
- localstack/services/cloudformation/models/stepfunctions.py
- tests/integration/cloudformation/resources/test_lambda.py
Update call sites to the `params` helper function to not use `resources` since this is not available with the new provider structure.
*Note*: unfortunately there is still duplication: the `properties` argument is the same as `resource["Properties"]` however we have an extensive list of helper functions in `deployment_utils.py` that it's not worth re-writing at this stage. The main output is that we no longer depend on the `resources` dictionary.
> CFn: simplify signature of params helper 

- localstack/utils/aws/request_context.py
We are currently loading the flask request for a thread every time we call get_request_context(), even though we might find it in the thread local variable anyway.
This leads to the request streams being read, if you access methods like "get_region_from_request_context`, and the streams not being available anymore.
Instead of loading both, and then iterating, we will now load while iterating. This means, if the threadlocal request context is set, we will not call `get_flask_request_for_thread`, and therefore not load the request.
While this is still implicit, and it is still possibly loading the request into a flask request, it provides a reasonable improvement until we can get rid of the flask context one and for all.
> Avoid loading the request stream to retrieve context

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/models/apigateway.py
- localstack/services/cloudformation/models/awslambda.py
- localstack/services/cloudformation/models/cloudformation.py
- localstack/services/cloudformation/models/dynamodb.py
- localstack/services/cloudformation/models/ec2.py
- localstack/services/cloudformation/models/ecr.py
- localstack/services/cloudformation/models/events.py
- localstack/services/cloudformation/models/iam.py
- localstack/services/cloudformation/models/kinesis.py
- localstack/services/cloudformation/models/kms.py
- localstack/services/cloudformation/models/logs.py
- localstack/services/cloudformation/models/opensearch.py
- localstack/services/cloudformation/models/resourcegroups.py
- localstack/services/cloudformation/models/s3.py
- localstack/services/cloudformation/models/secretsmanager.py
- localstack/services/cloudformation/models/sns.py
- localstack/services/cloudformation/models/sqs.py
- localstack/services/cloudformation/models/stepfunctions.py
Update signature of the "result_handler" functions to remove unused parameters, and parameters that the provider should not have access to, particularly the full list of resource definitions.
This work is in preparation of integrating the new resource providers into the template deployer.
> CFn: simplify "result_handler" function signature

- localstack/config.py
- localstack/utils/docker_utils.py
* Podman has issues with empty entrypoints. While they seem to be fixed in some cases, using the docker sdk seems to still trigger this behavior.
* Podman cannot resolve `host.docker.internal`, which is necessary for services like EKS. The default fallback to the bridge network gateway is invalid as well. It can however use `host.containers.internal`.
* Start port detection container with `sh -c` instead of an empty entrypoint to circumvent the issue. We might seek a more fundamental fix at some point, but this will do for now.
* Add a fallback to `host.containers.internal` if `host.docker.internal` does not resolve. If this as well fails, the fallback behaves like it currently does.
> Fix container port check and host detection on podman

- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR supersedes #8182
This is needed for https://github.com/localstack/moto/pull/67, so that we can isolate the changes in this PR (adding the behaviour that has been removed in moto) and already release a new moto version without merging the big S3 stream handling PR. 
Also, moto does not handle the checksum for CRC32C as it depends on `awscrt`. We are recalculating it for this specific algorithm. 
It also has benefits on its own, as it allows us to properly cache the checksum value in the S3 Object instead of calculating it every time it's requested.
> use checksum stored in moto key, implement checksum for CopyObject

- localstack/services/cloudformation/resource_provider.py
Changes
- Adds logical resource ID to "meta"-resource data passed when instantiating a GenericBaseModel for updates. This missing lead to KeyErrors on LogicalResourceId
- Adds a patch from -ext here to avoid having to patch this in -ext.
> Fix resource type resolution and missing logical resource ID in update

- localstack/services/sqs/models.py
- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
Currently, SQS AddPermission and RemovePermission calls do only save the permissions in some internal datastructure - they are never returned with sqs.GetQueueAttributes. This is problematic, since this is a necessity for cross account evaluation.
You could just use SetQueueAttributes on the `Policy` attribute but we should match AWS behavior.
* Rework SQS permission management, by adapting the stored policy
* Add AWS validated test for permission lifecycles.
> Let SQS AddPermission call actually influence policy attribute

- README.md
This PR updates the `README.md` with new installation instructions promoting the binary builds of the LocalStack CLI (built in [localstack/localstack-cli](https://github.com/localstack/localstack-cli)).
Relates to:
- https://github.com/localstack/docs/pull/668
- https://github.com/localstack/localstack-cli/pull/9
> update readme with cli installation instructions

- localstack/utils/docker_utils.py
The command line docker client does not like an entrypoint with an argument. It will interpret this as a single binary, i.e. look for "sh -c" in the path.
Since we cannot have an empty entrypoint, due to podman, and not an entrypoint including a command prefix, due to the docker cmd client.
* Change entrypoint to "sh" and the command to "-c", "echo123". This should be compatible with all clients.
* We might want to change the docker cmd client to properly pass these entrypoints.
> Fix container port detection with the cmd docker client

- tests/integration/awslambda/test_lambda_integration_sqs.py
- tests/integration/awslambda/test_lambda_integration_sqs.snapshot.json
This PR adds a test to verify #7897. Basically it's just a normal "let the lambda echo the SQS message into another SQS queue and fetch it" test, but i added message attributes explicitly.
The test didn't really reproduce the issue, but it's useful as regression test I suppose. The only difference I could find is that AWS adds empty values for `stringListValues` and `binaryListValues` of message attributes, but 1) [those are not implemented in AWS](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_MessageAttributeValue.html), and 2) these empty values only show up when using the event source mapper, not in SQS in general. :thinking: :shrug: 
```
"Author": {
"stringValue": "John Grisham",
"stringListValues": [],
"binaryListValues": [],
"dataType": "String"
},
```
in …
> add sqs lambda event source listener test for message attributes

- localstack/aws/handlers/logging.py
- localstack/http/asgi.py
- tests/unit/http_/test_asgi.py
We are currently not closing down our response generators after the client closes the connection. This leads to resource leaks, as the generators keep running in the background, even though no one will ever read the response.
This snipped from hypercorn `http_stream.py` shows us, that all response `send` calls will return immediately once the connection is closed.
```python
async def app_send(self, message: Optional[ASGISendEvent]) -> None:
if self.closed:
return
```
We now need to also stop the generators, once we detect the client connection is closed.
* Access internals of `send` call to determine if the connection to the client is closed already and raise a `BrokenPipeError` in that case.
* If any `ConnectionError` is raised during sending data from the iterator, we stop reading from …
> Fix termination of generators when client connection is closed

- localstack/cli/localstack.py
- localstack/utils/bootstrap.py
- tests/bootstrap/test_cli.py
- tests/unit/cli/test_cli.py
This PR aims at unifying the CLI error- and exitcode-handling.
- It explicitly catches some common exceptions and prints proper error messages (f.e. Docker is not installed, localstack_main is not running for status command,...). /cc @SimonWallner 
- It uses the `ClickException` for all error cases to use a unified error message as well as a non-zero exit code: https://click.palletsprojects.com/en/8.1.x/exceptions/#exception-handling
Changes postponed to later iterations:
- Introduce more fine grained Docker exceptions, clearly indicating that a container cannot be started due to port- or naming conflicts. (This was initially the plan for this PR, but this needs some changes in the Docker clients, which would bloat up this PR quite a lot.) /cc @dfangl
> unify CLI error messages, add global error message handler

- localstack/services/cloudformation/resource_provider.py
Currently the logs get spammed with `KeyError`s caused by the stack cleanup and its `delete` action lookups on the GenericBaseModels. 
Example:
```
2023-06-28T09:20:35.957 ERROR --- [  asgi_gw_10] localstack.services.cloudformation.engine.template_deployer : Last cycle failed to delete resource with id Version. Final exception: 'delete'
File "/tmp/workspace/repo/localstack/services/cloudformation/engine/template_deployer.py", line 881, in delete_stack
executor.deploy_loop(resource_provider_payload)  # noqa
File "/tmp/workspace/repo/localstack/services/cloudformation/resource_provider.py", line 558, in deploy_loop
event = self.execute_action(payload)
File "/tmp/workspace/repo/localstack/services/cloudformation/resource_provider.py", line 602, in …
```
> Fix KeyError when looking up handlers on legacy models

- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
Adds two methods `get_system_info` and `get_system_id` to the container client interface. On docker, this is populated using `docker info`, and can provide a stable machine ID even from within the container.
Future work: check whether this works on podman (ad: daniel checked, it works), and how that would work on k8s.
> add docker client commands to get docker system info

- localstack/cli/localstack.py
- localstack/services/events/provider.py
- localstack/utils/bootstrap.py
- localstack/utils/run.py
- tests/bootstrap/test_cli.py
Add small fix and test to assert that `prepare_host` hooks are called with appropriate LocalStack directories layout. This is a follow-up from https://github.com/localstack/localstack/pull/8384 . 
The previous PR #8384 adjusted the logic to start up LocalStack using the CLI when running inside a Docker container, for example to run `localstack start` in a [Github Codespaces](https://github.com/codespaces/) environment. This works well for the Community version, but unfortunately there was an oversight for the Pro version, where we're performing operations on the host via `prepare_host` hooks. In particular, the hook used to cache the key locally was failing with a `PermissionError`, as it was trying to access the wrong directory (using the container dirs layout, not the host dirs layout). …
> Add small fix and test to assert prepare_host hook is called with correct dirs

- localstack/aws/api/iam/__init__.py
- localstack/aws/api/s3/__init__.py
- localstack/aws/protocol/parser.py
- tests/unit/aws/protocol/test_parser.py
This PR fixes a small issue in the ASF parser which was caused by the latest change of `botocore`: https://github.com/boto/botocore/commit/5c337d96e3ff0833fe639be6007ff94bd330bd55
It introduces a new, optional, list-shaped header field `OptionalObjectAttributes` in `ListObjectsV2Request` (header field name `x-amz-optional-object-attributes` in the HTTP request).
Thanks a lot to @dominikschubert for the info on the issue (currently blocking the pipeline on master), a perfect writeup, and a suggestion for the fix!
> fix ASF parsing for optional list header fields

- .github/workflows/sync-project.yml
We are currently testing a private GitHub Project (Beta / V2) to organize the issues in this repo.
Unfortunately, the new projects do not provide a sync (not even unidirectional) between labels and GitHub Project fields (like the status). 
This PR adds a small action which acts on issue (un-)label events to set a specific status value on a project card based on the labels set.
This is only a prototypical and uni-directional sync, issue labels -> project card status. The other way around (project card status -> issue labels) is unfortunately also not solvable with GitHub actions, because org projects do not trigger issue events. This could be solved if we decide to move the board from the org to the repo.
I'm grateful for any feedback!
> add initial action for issue label -> project status sync

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/provider.py
- tests/integration/apigateway/test_apigateway_api.py
- tests/integration/apigateway/test_apigateway_api.snapshot.json
- tests/integration/files/oas30_documentation_parts.json
REST API supports adding documentation to an API, using the "import documentation parts" API.
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-documenting-api-quick-start-import-export.html
This PR adds support to "import documentation parts" for REST API but only the "override" mode.
- implements `import_documentation_parts` for "overwrite" mode.
- adds snapshot testing.
> Support to import documentation parts

- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This fix the second issue reported in #8174
Moto will by default clean up the key name (I'm not sure to what end? I think this should be removed because it can cause conflict between keys, one url encoded and the other not will have the same key in moto). 
So I've added the key cleaning in our moto access, which at least allows us to use keys with `%XX` encoded in them.
However, as moto cleans up name, what returns from `ListObject` and `ListObjectsV2` is still wrong and is url decoded. However, we cannot for sure know if the key was clean or not, so we can't fix it in our provider. This would need to be fixed upstream.
> add special char s3 test + fix moto lookup with cleaned up key name

- localstack/deprecations.py
Removes `LAMBDA_DOCKER_DNS` from the deprecation list.
The feature was re-implemented for the new Lambda provider in https://github.com/localstack/localstack/pull/8448 but I missed removing it from the deprecation list.
* Updated in the Lambda Discuss post: https://discuss.localstack.cloud/t/new-lambda-implementation-in-localstack-2-0/258
* Pending PR to be merged after the v2.2 release: https://github.com/localstack/docs/pull/666
> Remove deprecation for re-implemented DNS feature

- localstack/services/apigateway/integration.py
- tests/integration/apigateway/test_apigateway_import.py
- tests/integration/files/openapi.spec.stage-variables.json
Adds support for HTTP integration URIs  https://docs.aws.amazon.com/apigateway/latest/developerguide/aws-api-gateway-stage-variables-reference.html
> Adds HTTP integration URIs

- localstack/services/awslambda/invocation/lambda_models.py
- localstack/utils/container_utils/container_client.py
* We got the case where we could not find the container in the list of connected endpoints in the network right after start with this network. If this happens, we want all the information we can get.
* Add additional debug logs in error case
* Proper defaults for different container configuration flags.
* Sneaked in using new clients for retrieving code archives
> Additional debugging for network connection failure

- localstack/services/transcribe/provider.py
This PR focuses to fix a special case of `TranscriptFileUri` where output key is not null and the file doesn't end with .json. 
The earlier implementation was as per the AWS transcribe docs, but the actual AWS behaviour was different. 
FYI: we are currently skipping the check for `TranscriptFileUri` in all the test cases of transcribe due to other parity issues in the service. 
This will fix a part of #8089.
> transcribe: fix transcription file uri

- CODEOWNERS
As joint service owners, we should be aware of any cloudformation PRs. In particular, as part of the migration to resource providers, there is some configuration in the CloudFormation service directory. We should all be made aware when new resource providers are added to ensure that the centralised configuration is updated.
> Update codeowners with Cris and Simon

- localstack/services/iam/provider.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/test_iam.py
- tests/integration/test_iam.snapshot.json
Currently, if a role has a `PermissionsBoundary` attached, the `ListRoles` operation fails with a serializer error.
This is due to the returning of the unexpected `PermissionsBoundary` field in the to-be-serialized response.
Fixes #7779
* Add new fields to iam_api snapshot transformer
* Remove removal of `MaxSessionDuration` from model, it should only not be returned in the `CreateRole` call
* Add aws validated + snapshotted tests for the `MaxSessionDuration` and the `PermissionsBoundary` behavior.
> Fix ListRoles operation with PermissionsBoundary attached

- .github/workflows/sync-project.yml
This is a first try, as the emoji part of the target is a bit tricky since it is a zero-width joined emoji, in contrast to the other once.
According to the github preview, however, it seems to render correctly, still not sure if it will create an issue with finding the correct category.
> Add status: in progress mapping to label -> project status sync

- tests/integration/test_ssm.py
This PR aims at unblocking the pipeline on master by marking the currently failing SSM test with xfail.
This is just a temprary measure until https://github.com/getmoto/moto/pull/6484 is merged.
Until then, SSM's `DescribeParameters` might break if `PutParameters` was used without a parameter type before (which is an invalid request, according to the service specifications).
> xfail flaky ssm describe_parameters test

- localstack/services/opensearch/cluster.py
- tests/integration/test_opensearch.py
This PR fixes a small issue where GZIP encoded responses from an OpenSearch backend were decompressed by the proxies before sending them to the requesting client.
This is fixed by using the `SimpleStreamingRequestsClient` introduced by @bentsku in #8148.
It also enables the GZIP feature on internal OpenSearch domains (which is only used if the client sends the appropriate `Accept-Encoding` header).
In the future we could think about removing this separate implementation and making this the default implementation.
Fixes #7742
> fix OpenSearch proxy for GZIP encoded responses

- localstack/services/awslambda/invocation/docker_runtime_executor.py
- localstack/services/awslambda/lambda_executors.py
- localstack/services/awslambda/lambda_utils.py
- tests/integration/awslambda/functions/lambda_networks.py
- tests/integration/awslambda/test_lambda_developer_tools.py
This PR will extend the functionality of `LAMBDA_DOCKER_NETWORK` to provide more than one network, as requested in #7338 .
Networks need to be provided comma separated, like this: `LAMBDA_DOCKER_NETWORK=network1,network2`.
As long as only one network is provided, the behavior does not change.
Fixes #7338.
* Allow multiple docker networks to be respected (only new provider)
* Add test for LAMBDA_DOCKER_NETWORK with multiple networks.
* After this is merged, we should document this.
> Allow multiple lambda docker networks configured

- localstack/services/apigateway/integration.py
- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/router_asf.py
- localstack/services/apigateway/templates.py
- localstack/services/events/provider.py
- localstack/utils/aws/templating.py
- tests/integration/apigateway/test_apigateway_eventbridge.py
- tests/integration/apigateway/test_apigateway_eventbridge.snapshot.json
- tests/integration/test_events.py
- tests/integration/test_events.snapshot.json
Adds support for API Gateway EventBridge integration
API Reference - https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEvents.html
- Adds support to eventbridge integration
- Adds support to eventbridge **test_event_pattern**
- Adds snapshot test
- Implements a first version of `requestOverride` just to support the use case, that will be augment on a follow up issue (https://github.com/localstack/localstack/issues/7727)
- Add support to hiphens in assignments (airspeed, https://github.com/localstack/airspeed/issues/4).
Implements - https://github.com/localstack/localstack/issues/6925
Fixes - https://github.com/localstack/localstack/issues/6806
https://github.com/localstack/localstack/issues/7727
https://github.com/localstack/airspeed/issues/4
terraform sample - …
> add apigateway eventbridge support

- localstack/state/pickle.py
Removing our custom `Unpickler` from the current implementation, as briefly discussed with @thrau.
To the best of my understanding, `dispatch_tables` are specific to `Picklers` only ([docs](https://docs.python.org/3/library/pickle.html#pickle.Pickler.dispatch_table)). 
cc @whummer
> Deleting custom Unpickler

- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
S3 can now accept empty value in the tag.
- Added test case for S3 tagging with empty tag
https://github.com/localstack/localstack/issues/8598
> added test case for s3 object tagging

- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/provider.py
- localstack/services/cloudformation/models/apigateway.py
- tests/integration/cloudformation/resources/test_apigateway.py
- tests/integration/cloudformation/resources/test_apigateway.snapshot.json
- tests/integration/templates/apigateway_models.json
- tests/integration/templates/template35.yaml
This PR will fix #7060 and a ticket from support. 
It appeared we store the JSON schema from Model directly as is, in Python `dict` format to `str`, without JSON encoding it, which made every request fail when validating against the schema.
- Added a method to jsonify the model before storing it
- snapshot validated tests uncovered additional issues:
- we didn't check for `ANY` method in `RequestValidator`
- we were missing `requestParameters` empty value if it was an empty `dict`
- we were missing `operationName` field when creating `Method` from Cfn
- the `PhysicalResourceId` of a `Model` is its name, and not its `id` (that's what you are using when calling `GetModel`, added a AWS validated test to verify this behaviour, a CDK stack uncovered the issue)
> fix ApiGateway Model schema from CFn/CDK

- localstack/services/s3/utils.py
- localstack/services/transcribe/provider.py
- tests/integration/test_transcribe.py
- tests/unit/test_s3.py
The PR fixes `GetTranscriptionJob` response for transcribe service that contains a presigned S3 URL valid for 15min.
Related issue #8097.
FYI: The related developer hub [sample for transcribe](https://github.com/localstack/sample-serverless-transcribe), needs to be changed accordingly.
> transcribe: add presign url to transcript file uri

- localstack/http/client.py
- tests/unit/http_/test_client.py
This PR fixes an issue in OpenSearch which was triggered by the following scenario:
- The OpenSearch security plugin is used (added with #7658).
- This enforces the usage of HTTPS when communicating with the OpenSearch backend.
- However, the server cannot be verified, because it's running on `localhost` and is being addressed via `127.0.0.1`.
- A custom CA certificate bundle is set according to our docs by setting `REQUESTS_CA_BUNDLE`: https://docs.localstack.cloud/references/custom-tls-certificates/
This triggered a bug in the health check, where the requests to the backend - effectively checking if the cluster is already up - would fail due to a but in the requests library (https://github.com/psf/requests/issues/3829). This bug always sets `verify=True` on requests if …
> fix proxy client to respect disabled session.verify

- localstack/services/awslambda/invocation/lambda_models.py
- localstack/services/awslambda/invocation/lambda_service.py
- localstack/utils/testutil.py
With PR #8235 , the persistence tests broke.
It seems, that connecting to the bucket from different accounts, made some problems with remote fetched layers. It is not quite clear what causes this behavior (maybe some cross account problem in s3?), but it needs to be solved ASAP to unblock the pipeline.
* All code archive buckets are moved to some random account. This is parity with AWS
@giograno
> A try fixing Lambda persistence

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR fixes #6764.
Moto was a bit overzealous in their validation of the bucket logging configuration. We're keeping the same checks that are made in moto, without the problematic part. We could extend the validation then, as now with Object Ownership, a bucket created without config shouldn't be able to get a config with `TargetGrants`. This would be part of a bigger effort to use the same new defaults as AWS.
> fix validation of PutBucketLogging

- localstack/services/s3/provider.py
- localstack/services/s3/provider_stream.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR fixes and implements #7555
This implements the different preconditions checks following the documentation here: https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html
It adds an AWS validated test, checking all wrong assumptions and a positive one.
> implement Precondition checks for CopyObject

- localstack/services/s3/provider.py
- localstack/services/s3/provider_stream.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
- tests/unit/test_s3.py
This PR will implement the request from #6654.
We will now validate the `BucketLifecycleConfiguration` when we call `PutBucketLifecycleConfiguration`, but only for the parts we actually use (see limitations).
We will now properly return the `Expiration` header from `PutObject`, `GetObject` and `HeadObject` depending on the lifecycle configuration and its rules/filters. 
Lifecycle configuration is quite the feature, as we can see from the length of the documentation on AWS:
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-expire-general-considerations.html
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html
- …
> add S3 Lifecycle logic and return Expiration header

- localstack/aws/serving/hypercorn.py
- localstack/http/hypercorn.py
- localstack/utils/server/http2_server.py
- setup.cfg
- tests/unit/aws/test_gateway.py
- tests/unit/http_/conftest.py
With #6778, Hypercorn has been pinned to `0.14.2`, since hypercorn reverted a fix to preserve header casing with https://github.com/pgjones/hypercorn/commit/68e832af53b55bcd7798eac1e84c974eb5753827 / `0.14.3` (since the spec defines that they should not be preserved).
@thrau suggested a config to enable preserving the headers with https://github.com/pgjones/hypercorn/pull/117, which is contained in the latest release: `0.14.4`.
This PR unpins `hypercorn` in the `setup.cfg` and enables the header preserving in the configs.
#6778 introduced a regression test which ensures that the gateway properly preserves the HTTP header casing (which is why this PR does not contain any tests).
Fixes #6849.
> unpin hypercorn, set h11_pass_raw_headers

- localstack/aws/handlers/cors.py
This PR adds a sanitization step to origins parsing from `EXTRA_CORS_ALLOWED_ORIGINS.
This is mainly to filter out `""` when  it's specified by accident, or intentionally.
> sanitize extra cors allowed origins

- setup.cfg
- tests/integration/test_ssm.py
Also reverts https://github.com/localstack/localstack/pull/8631
Ext tests passing :heavy_check_mark:
> Bump moto-ext to 4.1.12.post2

- localstack/services/s3/presigned_url.py
- tests/integration/s3/test_s3.py
As reported by #8663, we were not properly re-URL-encoding the request path before validating the signature of the pre-signed URL.
I've made the necessary modifications into both signature types, and simplified the HMACv1 (signature type `s3`) quite a bit by not recreating a `Request` object but instead directly recreating a `SplitResult` and the new `HTTPHeaders`. 
Added a test to validate the use case of the user and the fix.
> fix url encoding when validating pre-signed signature

- localstack/services/iam/provider.py
- localstack/testing/snapshots/transformer_utility.py
- tests/integration/cloudformation/resources/test_iam.snapshot.json
- tests/integration/cloudformation/resources/test_sam.snapshot.json
- tests/integration/test_iam.py
- tests/integration/test_iam.snapshot.json
Currently, we do not properly verify the policy arn in the `attach_*_policy` methods, and have not tests for this behavior.
Depens on https://github.com/getmoto/moto/pull/6482 , fixes #7934 .
Ext Test run (due to snapshot transform changes): https://github.com/localstack/localstack-ext/actions/runs/5522309201
* Add tests for role/user attach policies and errors of the operation
* Add verification of the policy arn
* Depends on the linked moto PR for correct error handling for the correct arn but policy does not exist case.
* Adds two more transform statements to iam_api transformer.
> Fix error with non-existent policy for AttachRolePolicy operation

- localstack/services/awslambda/packages.py
The new lambda init version will automatically set the `bootstrap` file to executable if it is not yet.
This will fix #8459 .
Releases https://github.com/localstack/lambda-runtime-init/pull/21
It will do so unconditionally, even though AWS, in some cases, will refuse to allow a bootstrap file without executable permissions. It is yet to determine, under which circumstances this happens.
This will not work for hot reloading, as the privileges are already dropped when the reload takes place. If you want hot reloading, please make sure to set your bootstrap binary as executable after compilation.
* Update lambda runtime init to get new bootstrap executable behavior.
> Update lambda runtime init to handle non-executable bootstrap files

- localstack/utils/container_utils/docker_cmd_client.py
- tests/integration/docker_utils/conftest.py
- tests/integration/docker_utils/test_docker.py
This PR performs a small fix to the `CmdDockerClient` (which is basically only used by the CLI), such that it raises a `DockerNotAvailable` exception in case the `DOCKER_CMD` (by default `docker`) is not available on the system.
Contrary to the `SdkDockerClient`, this is done only once (the result is cached) to avoid checking the command existence on every single usage of the client. We basically assume that, if the `DOCKER_CMD` is not available once, it won't become available during this python session lifetime.
This fixes the CLI error handling in this case (introduced in #8564).
> fix CmdDockerClient not raising DockerNotAvailable exception

- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR is a small parity fix to return the `ChecksumX` header when the `ChecksumMode` request parameter is enabled. 
This will fix #8676, also reported in #6659
> fix HeadObject ChecksumMode

- tests/integration/cloudformation/resources/test_lambda.py
- tests/integration/templates/cfn_lambda_s3_code.yaml
We didn't really have any tests that used `AWS::Lambda::Function` with the code uploaded to an s3 bucket. Instead the tests usually directly embedded the code in the template.
> Add basic invoke test for AWS::Lambda::Function with code package on S3

- localstack/services/s3/provider.py
Following the report from #8675, it seemed moto had introduced experimental support for `SelectObjectContent`. However, the format from the returned response would often end raising `ProtocolSerializerError`, as the serializer expect a stream of response (like for Kinesis, for example).
_fixes #8675_
> raise NotImplemented error for SelectObjectContent

- localstack/services/events/provider.py
This PR fixes a cron syntax error. Currently if you schedule an events rule hourly or daily, it will execute every minute. This is due to cron's syntax, which will match every minute due to the `*`.
The following resource helps to understand cron syntax: [https://crontab.guru/every-1-hour](https://crontab.guru/every-1-hour)
Thanks to @whummer for the help in finding this.
> fix schedule cron conversion in events

- localstack/services/s3/provider.py
This PR fixes #8072 
Basically, the issue stems from moto accessing thus creating a BackendDict with an `account_id` set to `None`.
Thanks to @taimourfenris, he discovered that it was after a `MultipartUpload`, the issue would arise. It happens also in lambda because lambda makes use of `upload_fileobj`, which will automatically switch to a multipart upload if the file is big.
I tried to debug moto to see when it would access a backend with an null account id.
I've created a small sample to create a multipart:
```python
chunk_size = 5_242_880 * 10  # around 52MB
with io.BytesIO() as data:
data.write(os.urandom(chunk_size * 2))
data.seek(0)
s3_client.upload_fileobj(data, "test-bucket", "test-key")
```
And I could confirm after running this command that `localstack pod save file://test.zip` …
> fix pod save after s3 multipart upload

- localstack/services/sns/constants.py
- localstack/services/sns/models.py
- localstack/services/sns/provider.py
- localstack/services/sns/publisher.py
- tests/integration/test_sns.py
This PR builds and rebase #7936, and fixes #7935. 
This adds retrospections endpoint for SMS published to SNS, and also adds a test case for the retrospection.
> add SNS retrospection endpoints for SMS

- localstack/aws/spec-patches.json
- localstack/services/s3/models.py
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
- tests/unit/test_s3.py
This PR partly implements #8694, at least the mocking part. We were actually not supporting any CRUD operations, as it was not implemented in moto. 
Also made use of the `context` in every `get_store` call, as we should remove any use of the `threadlocal` and make use of the nicely provided context. 
- `PutBucketInventoryConfiguration`
- `ListBucketInventoryConfigurations`
- `GetBucketInventoryConfiguration`
- `DeleteBucketInventoryConfiguration`
> implement S3 BucketInventoryConfiguration mocking

- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/container_utils/docker_sdk_client.py
- tests/integration/docker_utils/test_docker.py
- tests/unit/test_dockerclient.py
Extend Docker client to allow passing `--dns` user flags, e.g., via `DOCKER_FLAGS` or `ECS_DOCKER_FLAGS`.
* Turn the existing `dns` references from a `str` into a `List[str]`, as this is a multi-value attribute. Should be backward-compatible, and type hints were adjusted to `[Union[str, List[str]]]`
* Extend the `Util.parse_additional_flags(..)` utility to support parsing of `--dns ...` arguments
* Add a test to cover the new functionality
* Slightly restructure the tests and group the `test_run_with_additional_arguments_*` tests into a `TestRunWithAdditionalArgs` class
> Extend Docker client to allow passing --dns user flags

- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
- S3 Object Retention
- `PutObjectRetention` was not in parity with AWS
- implemented `GetObjectRetention`
- `PutObjectRetention` with expired date -> call `DeleteObject` (used errors out)
- https://github.com/localstack/localstack/issues/7517
> fix support for object retention

- localstack/services/events/provider.py
- localstack/services/s3/notifications.py
- localstack/services/s3/provider.py
- tests/integration/s3/test_s3_notifications_eventbridge.py
- tests/integration/s3/test_s3_notifications_eventbridge.snapshot.json
- tests/integration/s3/test_s3_notifications_sqs.py
- tests/integration/s3/test_s3_notifications_sqs.snapshot.json
- tests/integration/test_events.py
- tests/integration/test_events.snapshot.json
As requested in #8444, this adds support for `ObjectRestore:Post` and `ObjectRestore:Completed`, as well as sneak in a bug fix for EventBridge where we use the time provided to the `Entry` instead of `utcnow()`. 
See: 
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_RestoreObject.html#AmazonS3-RestoreObject-request-GlacierJobParameters
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-how-to-event-types-and-destinations.html
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/ev-events.html#ev-events-object-restore-complete
_fixes #8444_
> add ObjectRestore:Post and :Completed S3 Event Notification

- localstack/services/s3/constants.py
- localstack/services/s3/provider.py
- localstack/services/s3/provider_stream.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
This PR fixes #8703 (I got confirmation with a code sample), this is a follow up from #8699
We had to set the `body` directly to moto to avoid a persistence bug, but moto has a step that we didn't execute: `_handle_v4_chunk_signatures`, which will decode the `aws-chunked` format. 
I've refactored the code used in the streaming provider that already handles this case, and made use of it in the case of `aws-chunked` requests for `UploadPart`, as we're skipping this moto step (actually one of the only one before actually calling the backend like we're doing in our provider). 
As a example, that is what the Java/.NET SDK would send if you try to upload a part with the following content:
Content: `Hello Blob`
Becomes:
```
a;chunk-signature=b5311ac60a88890e740a41e74f3d3b03179fd058b1e24bb3ab22404 …
```
> fix decoding aws-chunked request for UploadPart

- localstack/aws/accounts.py
- localstack/config.py
quick fix for #8225 and #8380
i'd like to get some input from @dfangl and @viren-nadkarni whether this makes sense and is something we can expand on.
> add config variable to explicitly ignore AWS credentials

- tests/integration/cloudformation/resources/test_legacy.py
The upgrade to pyyaml>6 due to the Cython upgrade deprecated `yaml.load` without a loader specified.
* Replace `yaml.load` with `yaml.safe_load`, which automatically uses the SafeLoader loader.
> Fix deprecated pyyaml usage in cloudformation legacy test

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/models.py
- localstack/services/apigateway/provider.py
- tests/integration/apigateway/test_apigateway_extended.py
Custom domains created on any version of API Gateway should be visible across APIs. For example, using aws cli with apigatewayv2 client to create a custom domain and query the same domain using aws cli with apigateway client after, should return the previous domain created.
- Add a new field to the ApiGw model to hold the created domains.
- Implements the `create_domain_name,` `get_domain_name` and `get_domain_names` API calls to fetch the domains from the model. 
- Move away from moto store and use localstack apigw store to store created domains
- Almost all operations but update domains act on both APIs, for example deleting a domain happen in both stores, same as create and fetch.
> fix api gateway domains not being saved between versions

- localstack/services/cloudformation/engine/template_utils.py
- tests/integration/cloudformation/engine/test_conditions.py
- tests/integration/templates/conditions/intrinsic-functions-in-conditions.yaml
Allows for `Fn::Sub` intrinsic function evaluation in the resolving of the conditions. Still very explicit, but this area of code will soon be reworked into a sort of visitor pattern allowing us to structure this a bit better.
This regression was introduced recently when splitting the resolve path for Conditions from resolve_refs_recursively
> Fix regression for Fn::Sub in condition section

- localstack/utils/bootstrap.py
Since docker compose v2 is available, for many systems, `docker-compose` is not available any more (and not aliased to `docker compose`).
For these, we have to have a fallback to `docker compose`.
Fixes #8732
* Use `docker compose` instead of `docker-compose` if the latter is not available.
> Use `docker compose` as fallback if docker-compose is not available

- localstack/services/cloudformation/models/sns.py
Add missing `FilterPolicyScope` to `AWS::SNS::Subscription`
`template.yml`
```yaml
AWSTemplateFormatVersion: 2010-09-09
Resources:
SNSTopic:
Type: AWS::SNS::Topic
Properties:
TopicName: test-topic
SQSQueue:
Type: AWS::SQS::Queue
Properties:
QueueName: test-queue
SNSSubscription:
Type: AWS::SNS::Subscription
Properties:
TopicArn: !Ref SNSTopic
Endpoint: !GetAtt [SQSQueue, Arn]
Protocol: sqs
FilterPolicyScope: MessageBody
FilterPolicy:
entityName:
- Zone
```
`cfn.sh`
```bash
awslocal cloudformation deploy \
--template-file template.yml \
--stack-name test-stack \
--region us-west-2
subscription_arn=$(
awslocal sns list-subscriptions-by-topic \
--topic-arn arn:aws:sns:us-west-2:000000000000:test-topic \
--region us-west-2 | jq -r '.Subscriptions[0].SubscriptionArn'
)
awslocal sns …
```
> fix(cfn): add missing FilterPolicyScope for sns subs

- localstack/aws/connect.py
- localstack/services/cloudwatch/alarm_scheduler.py
This PR fixes an issue where this code would lead to an exception:
```python
from localstack.aws.connect import connect_to
service = "cloudwatch"
connect_to(region_name="us-east-1").get_client(service)
```
The created `ServiceLevelClientFactory` would try to resolve `get_client` as the service `get-client`, instead of `cloudwatch`.
This surfaced in the persistence tests with the `AlarmScheduler.restart_alarms` method of cloudwatch:
```
2023-07-22T13:46:19.3265223Z docker-run.sh: File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/threads.py", line 58, in run
2023-07-22T13:46:19.3265863Z docker-run.sh: result = self.func(self.params, **kwargs)
2023-07-22T13:46:19.3266515Z docker-run.sh: File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/servi …
```
> add get_client method to ServiceLevelClientFactory

- localstack/config.py
- localstack/services/cloudformation/deployment_utils.py
- localstack/services/cloudformation/engine/entities.py
- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/models/iam.py
- localstack/services/cloudformation/models/kms.py
- localstack/services/cloudformation/resource_provider.py
- localstack/services/cloudformation/service_models.py
- localstack/services/iam/resource_providers/aws_iam_user.py
- tests/integration/cloudformation/api/test_changesets.py
- tests/integration/cloudformation/resource_providers/iam/aws_iam_user/templates/user_getatt.yaml
- tests/integration/cloudformation/resource_providers/iam/aws_iam_user/test_basic.py
- tests/integration/cloudformation/resource_providers/iam/aws_iam_user/test_basic.snapshot.json
- tests/integration/cloudformation/resource_providers/iam/test_iam.py
- tests/integration/cloudformation/resource_providers/iam/test_iam.snapshot.json
- tests/integration/cloudformation/resources/test_cdk.py
- Introduced `CFN_IGNORE_UNSUPPORTED_RESOURCE_TYPES` config variable to determine if we should fail if a resource type doesn't exist. E.g. setting `CFN_IGNORE_UNSUPPORTED_RESOURCE_TYPES=0` will cause a stack deployment to fail if the resource type doesn't have an associated provider.
- Removed any access to `RESOURCE_MODELS`, i.e. the GenericBaseModel classes in the template_deployer, *except* the current fallback for retrieving `Fn::GetAtt` targets that still needs to use them. If we refactor the models to remove all `get_cfn_attribute` calls, we can delete this completely.
- Removed `retrieve_resource_details`
- Removed `extract_resource_attribute`
- Removed a lot of unnecessary code from `resolve_ref`
- Removed `get_resource_model_instance`
- Removed `invoke_function` (unused)
- …
> Remove usage of GenericBaseModel outside of LegacyResourceProvider

- localstack/aws/protocol/service_router.py
This PR fixes missing cors headers on calls made to `/_aws` routes.
> fix cors for /_aws calls

- localstack/services/s3/codec.py
- localstack/services/s3/constants.py
- localstack/services/s3/provider.py
- localstack/services/s3/provider_stream.py
- tests/integration/s3/test_s3.py
- tests/unit/test_s3.py
This PR implements a stream decoder which will decode on the fly the `aws-chunked` encoding, so that we only have one way to set the stream to the S3 objects value, which simplifies the code a lot, even for the new provider.
One of the main issue around this decoder is that we're getting data only after we read the whole stream, as the necessary headers for checksum calculation are appended at the end of the response.
We then need a way to access those headers for our logic to go forward. One way for this to be transparent is to pass the s3 object to the stream, so that once it has finish decoding, it will automatically set the trailing checksum to the object attribute.
Maybe one idea could also be to be able to register callback, but as it's always the same, I thought we don't need to …
> S3 AWS-chunked stream decoder

- localstack/services/s3/codec.py
- tests/unit/test_s3.py
This PR fix the newly arised issue #8756
Basically we were missing a reset to the signal for the end of a chunk. Quick fix, and added a test covering this case.
> fix S3 case where aws-chunked chunk is bigger than read size

- localstack/services/cloudformation/models/apigateway.py
- localstack/services/cloudformation/models/awslambda.py
- localstack/services/cloudformation/models/cloudformation.py
- localstack/services/cloudformation/models/cloudwatch.py
- localstack/services/cloudformation/models/dynamodb.py
- localstack/services/cloudformation/models/ec2.py
- localstack/services/cloudformation/models/ecr.py
- localstack/services/cloudformation/models/elasticsearch.py
- localstack/services/cloudformation/models/events.py
- localstack/services/cloudformation/models/iam.py
- localstack/services/cloudformation/models/kinesis.py
- localstack/services/cloudformation/models/kinesisfirehose.py
- localstack/services/cloudformation/models/kms.py
- localstack/services/cloudformation/models/logs.py
- localstack/services/cloudformation/models/resourcegroups.py
- localstack/services/cloudformation/models/s3.py
- localstack/services/cloudformation/models/secretsmanager.py
- localstack/services/cloudformation/models/sqs.py
- localstack/services/cloudformation/models/stepfunctions.py
- localstack/services/cloudformation/service_models.py
Removes all usage of `get_cfn_attribute` from the community resource models. 
It does not yet introduce a subset selection for the migrated resources to stay in parity with the previous behavior for now where we nearly always fall back to a direct property/state lookup.
A follow-up PR will soon remove the base method from the GenericBaseModel and unify the code paths between old and legacy providers.
> Remove get_cfn_attribute from legacy models

- localstack/aws/api/lambda_/__init__.py
- localstack/services/awslambda/api_utils.py
- localstack/services/awslambda/invocation/lambda_models.py
- localstack/services/awslambda/provider.py
- tests/integration/awslambda/conftest.py
- tests/integration/awslambda/test_lambda_api.snapshot.json
- tests/integration/awslambda/test_lambda_common.snapshot.json
AWS released the python3.11 managed runtime for AWS Lambda yesterday (https://aws.amazon.com/about-aws/whats-new/2023/07/aws-lambda-python-3-11/)
* Add support for python3.11 runtime
* Update snapshots
* Update error messages mentioning supported runtimes
> Add support for python3.11 lambda runtime

- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR fixes #8750
We didn't consider the case where `ExpiredObjectDeleteMarker` would be set in the `Expiration` field of rule. Basically, if this is set, you can't set `Days` or `Date` so we would serialize a proper header (and we should not).
Adjusted the logic to properly parse the lifecycle configuration so that we can't have `Days` or `Date` set with `ExpiredObjectDeleteMarker`, and adjusted the matching so that we wouldn't return a rule that contains `ExpiredObjectDeleteMarker`, because you shouldn't serialize a header then.
> fix S3 lifecycle rule matching with ExpiredObjectDeleteMarker

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/generic_proxy.py
Add `x-api-key` to the list of allowed CORS headers, to enable passing this header from the LocalStack Web app.
This header is used, among others, for API Gateway and AppSync GraphQL APIs. For AppSync, we've recently extended our resource browser to make requests directly from the Web app. Currently this requires starting LS with `EXTRA_CORS_ALLOWED_HEADERS=x-api-key` configured, and with the changes in this PR it works out of the box.
This PR also contains a minor fix for a logging statement (missing parameter for placeholder in format string), which was detected during testing.
> Add x-api-key to allowed CORS headers to enable access from Web app

- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/apigateway/test_apigateway_basic.py
- tests/integration/apigateway/test_apigateway_common.py
- tests/integration/apigateway/test_apigateway_common.snapshot.json
- tests/integration/cloudformation/resources/test_apigateway.py
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-key-source.html
> When you associate a usage plan with an API and enable [API key](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-basic-concept.html#apigateway-definition-api-key)s on API methods, every incoming request to the API must contain an API key. API Gateway reads the key and compares it against the keys in the usage plan. If there is a match, API Gateway throttles the requests based on the plan's request limit and quota. Otherwise, it throws an InvalidKeyParameter exception. As a result, the caller receives a 403 Forbidden response.
The changes go a bit beyond the api key authorizer implementation by adding usage plans parity.
- Override `create_api_key`, `create_usage_plan`, …
> 8701 enhancement request custom lambda authorizer apikeysource is not validated

- localstack/services/dynamodbstreams/provider.py
- tests/integration/test_dynamodb.py
Dynamodbstream's `list-streams` has a filter option on the `TableName` - [see here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodbstreams/client/list_streams.html).
this is easily double-checked with AWS, thanks to the nicely [detailed issue report](https://github.com/localstack/localstack/issues/8759):
```
$ aws dynamodb create-table --table-name 'table1' --attribute-definitions 'AttributeName=pk,AttributeType=S' 'AttributeName=sk,AttributeType=S' --key-schema 'AttributeName=pk,KeyType=HASH' 'AttributeName=sk,KeyType=RANGE'  --billing-mode PAY_PER_REQUEST
[...]
$ aws dynamodb update-table --table-name table1 --stream-specification '{"StreamEnabled": true, "StreamViewType": "NEW_AND_OLD_IMAGES"}'
[...]
$ aws dynamodbstreams list-streams …
```
> fix ddbstreams list-streams table filtering

- localstack/utils/bootstrap.py
- localstack/utils/container_utils/container_client.py
There was a long standing TODO in the `LocalstackContainer` class: `# TODO merge with docker_utils.py:ContainerConfiguration`, which this PR fixes. This will be useful as we use the `LocalstackContainer` object as an abstraction for the bootstrap tests (cc @simonrw).
Also, I want to add some flags to the `localstack start` command (like `--network` to specify the container network the container should be started in), and this will make it a bit cleaner to do that.
* Introduced `    def run_container_from_config(self, container_config: ContainerConfiguration) -> Tuple[bytes, bytes]:` to container client. adapted from the already existing `create_container_from_config`
* Refactored `LocalstackContainer` to use the `ContainerConfiguration` object internally to hold its configuration
* I was …
> use ContainerConfiguration object for LocalstackContainer

- localstack/cli/localstack.py
- localstack/utils/bootstrap.py
- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- tests/unit/cli/test_cli.py
There were a few things that bothered me about the localstack start command:
* No first-class flags for operations i need often (specifying the docker network, adding environment variables), I dislike using the `DOCKER_FLAGS` for common stuff
* If the docker image is not there, localstack didn't really tell you, and would be pulled implicitly sometime during the startup procedure.
* The "Localstack Runtime Log" ruler wasn't placed correctly
* added a `--network` and `-e` flag to `localstack start` which are handed down to the docker run command. for that i needed to hand down the CLI parameters to the plumbing
* added a check that creates the specified network if it doesn't exist yet
* added an `ensure_container_image` method that checks whether the requested container image is there, and …
> improve docker integration with localstack start command

- .github/workflows/tests-pro-integration.yml
This PR reverts the installation of `pymssql` build-time OS dependencies, introduced in https://github.com/localstack/localstack/pull/8774, after their wheels for the CPython 3 compatible release have been properly built and published (i.e. https://github.com/pymssql/pymssql/issues/832 has been resolved).
> remove pymssql build-dependencies after fix release

- localstack/services/sqs/provider.py
- tests/integration/test_sqs.py
- tests/integration/test_sqs.snapshot.json
closes #8566 
Just a small note, according to the docs
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html#SQS-ReceiveMessage-request-MessageAttributeNames
only `All` and `.*` are allowed as wild card, but actually it also supports `*` (as described in the issue)
> Allow asterisk only wild card

- tests/integration/apigateway/apigateway_fixtures.py
- tests/integration/apigateway/test_apigateway_basic.py
This PR removes the use of `aws_stack.create_external_boto_client` in the API Gateway test suite.
> APIGW: Refactor tests to use the aws_client fixtures

- localstack/packages/core.py
- localstack/services/kinesis/kinesis_mock_server.py
- localstack/services/kinesis/kinesis_starter.py
- localstack/services/kinesis/packages.py
This PR upgrades `kinesis-mock` to the new version `0.4.1`, which migrates to ScalaJS (with https://github.com/etspaceman/kinesis-mock/pull/531).
It creates a new `NodePackageInstaller` which handles the installation of `npm` packages in LocalStack.
Thanks to @etspaceman for the heads-up, and the discussions prior to the release!
Fixes #8680
> upgrade kinesis-mock to scalajs release, add node installer

- localstack/testing/pytest/fixtures.py
Just realised I had 101 buckets in my AWS account after doing some S3 testing, and seeing `TooManyBuckets` rang a bell somewhere 😄🚨 
You need to even delete `DeleteMarkers`, otherwise your bucket is not considered empty. It's weird, but that's how it is 🤷‍♂️
I tried the fixture against my 101 buckets and it worked, cleaned them up and deleted them.
> fix s3_empty_bucket fixture to delete DeleteMarkers

- localstack/services/s3/provider.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
This PR fixes #8812, we were not returning early if the payload was empty, and we were trying to validate it. 
Added an AWS test validated this.
> fix PutBucket logging with empty payload

- scripts/capture_notimplemented_responses.py
This PR explicitly sets credentials in the capture-not-implemented script to avoid any issues if the credentials are not implicitly set via environment variables (`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`).
In CircleCI, our test credentials are set globally, but executed in different environments, this caused issues.
> fix credentials handling for capture-not-implemented

- localstack/cli/localstack.py
Something I forgot to add with #8772, was to also configure the `MAIN_DOCKER_NETWORK` variable automatically.
> configure MAIN_DOCKER_NETWORK automatically if --network flag is used

- localstack/utils/venv.py
- tests/bootstrap/test_cli.py
Tiny fixes to support CLI use with Python 3.8. Discovered this while working on a support case of a customer who attempted to install the AWS replicator/proxy extension.
Can be replicated when installing Python 3.8 via `pyenv`, and then:
```
$ DEBUG_PLUGINS=1 localstack -d extensions install localstack-extension-aws-replicator
DEBUG:stevedore._cache:reading /Users/whummer/Library/Caches/Python Entry Points/5e2a6eb1bdd93e1d7b62ee754448916f77349878c2468e3c113c4965f6f6e4d7
DEBUG:stevedore.extension:found extension EntryPoint(name='ext-all', value='localstack_ext.cli.localstack:ExtCliPlugin', group='localstack.plugins.cli')
ERROR:plugin.manager:error importing entrypoint EntryPoint(name='ext-all', value='localstack_ext.cli.localstack:ExtCliPlugin', group='localstack.plugins.cli'): 'type' …
```
> Small fixes to support CLI use with Python 3.8

- .circleci/config.yml
- .github/workflows/tests-cli.yml
- .github/workflows/tests-podman.yml
- .github/workflows/tests-pro-integration.yml
- Makefile
- setup.cfg
This PR adds the [`pytest-tinybird`](https://github.com/tinybirdco/pytest-tinybird) plugin to the test dependencies and modifies all GitHub and CircleCI test workflows such that they send the test data to the Tinybird workspace `localstack_ci` (if the pipeline is executed on master).
This data-driven approach will help us to gain more insights into our tests (automatically identify flaky tests, create individual health dashboards, setup a notification infrastructure,...).
TODO:
> add pytest-tinybird to all CI runs on master

- Dockerfile
Certain users seem to have issues fetching the lambda init from GitHub which made us notice that we're not actually bundling it into the built Docker container. 
It's probably sensible to ship the lambda runtime init by default
> Bundle lambda init into docker image

- localstack/services/stepfunctions/asl/component/state/state_execution/state_task/lambda_eval_utils.py
- localstack/services/stepfunctions/backend/execution.py
- localstack/services/stepfunctions/backend/execution_worker.py
- localstack/services/stepfunctions/provider_v2.py
- tests/integration/stepfunctions/templates/services/lambdafunctions/return_bytes_str.py
- tests/integration/stepfunctions/templates/services/services_templates.py
- tests/integration/stepfunctions/templates/services/statemachines/lambda_invoke_resource.json5
- tests/integration/stepfunctions/v2/services/test_lambda_task.py
- tests/integration/stepfunctions/v2/services/test_lambda_task.snapshot.json
- tests/integration/stepfunctions/v2/services/test_lambda_task_service.py
- tests/integration/stepfunctions/v2/services/test_lambda_task_service.snapshot.json
Removed redundant lambda payload cleanups that caused failures whenever payloads were not json dictionaries.
Adds relevant tests.
Fixes deprecated events initiation call in Execution objects.
> [SFN] Fix execution input, fix handling lambda payload i/o

- localstack/services/s3/provider.py
- localstack/testing/pytest/fixtures.py
- tests/integration/s3/test_s3.py
- tests/integration/s3/test_s3.snapshot.json
- tests/integration/s3/test_s3_notifications_eventbridge.py
- tests/integration/s3/test_s3_notifications_eventbridge.snapshot.json
- tests/integration/s3/test_s3_notifications_lambda.snapshot.json
- tests/integration/s3/test_s3_notifications_sns.snapshot.json
- tests/integration/s3/test_s3_notifications_sqs.py
- tests/integration/s3/test_s3_notifications_sqs.snapshot.json
This PR regenerates all S3 snapshots. It might have been nice to actually split the S3 tests before regenerating the snapshots, but there are currently at least 7 open PRs targeting S3, most of them adding tests.
I'll tackle the split of the tests in the next weeks, and I'll move the snapshots manually then.
> regenerate S3 snapshots

- localstack/http/client.py
- tests/aws/s3/test_s3.py
- tests/aws/s3/test_s3.snapshot.json
- tests/aws/s3/test_s3_notifications_lambda.py
- tests/unit/http_/test_proxy.py
It appears AWS does not support `Transfer-Encoding: chunked` responses for `GetObject`. We always set the `Content-Length` when returning from `GetObject`, but when passing the request through the Virtual Host proxy, we would remove it every time. 
Added a check for the `Transfer-Encoding` header, so that we now conditionally remove it. Also added a unit test as well as an AWS validated integration tests for S3.
Also sneaked in a change, updating an already skipped path for `tests.aws.s3.test_s3_notifications_lambda.TestS3NotificationsToLambda.test_create_object_by_presigned_request_via_dynamodb` which seems to fail sporadically in CI. 
_fixes #8841_
> fix VirtualHost proxy removing ContentLength for GetObject

- localstack/testing/pytest/fixtures.py
- localstack/testing/pytest/marking.py
- tests/aws/awslambda/test_lambda_common.py
- tests/conftest.py
Introduce new aws markers `@markers.aws.*`
```python
validated = pytest.mark.aws_validated
manual_setup_required = pytest.mark.aws_manual_setup_required
needs_fixing = pytest.mark.aws_needs_fixing
only_localstack = pytest.mark.aws_only_localstack
unknown = pytest.mark.aws_unknown
```
> New pytest parity markers & marker registration

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/invocations.py
- localstack/services/apigateway/models.py
- localstack/services/apigateway/patches.py
- localstack/services/apigateway/provider.py
- localstack/testing/pytest/fixtures.py
- tests/aws/apigateway/conftest.py
- tests/aws/apigateway/test_apigateway_basic.py
- tests/aws/apigateway/test_apigateway_common.py
- tests/aws/apigateway/test_apigateway_common.snapshot.json
Enhance parity around API Gateway stage patch operations, add implementation for API GW documentation versions. Addresses https://github.com/localstack/localstack/issues/8739
The PR also adds some refactoring to the existing tests in `test_apigateway_basic.py` - grouping related tests into test classes, using proper fixtures for resource creation, getting rid of global constants to make tests more self-contained, etc. Still more work needs to be done to get them on par with our other integration tests - introduce more fixtures, add snapshots, etc.
* implement the `update_stage` method in the provider, and perform corresponding patch operations
* adds small changes to fix missing/invalid attributes in the responses for the `create_stage`, `get_stage`, `update_stage` …
> Enhance parity around API Gateway stage patch operations

- localstack/services/s3/cors.py
- tests/aws/s3/test_s3_cors.py
- tests/aws/s3/test_s3_cors.snapshot.json
Following a support case, added a test case validating that AWS does not return CORS headers if no `Origin` header is present, even if the `referer` one is there.
I took the opportunity to regenerate the snapshots, knowing there was now an issue regarding ACL, so I've added a new fixture to allow ACL on bucket. Something changed on AWS side, so I've fixed a small field for an Exception returned. 
Also refactored a bit the code to use the fix made in #6865, allowing us to add fields to the exception at instantiation as parameters and not by attaching them directly to the exception object like before. 
\cc @steffyP for the snapshot regeneration/fixture allowing AWS tests
> add S3 CORS test with referer header and regenerate CORS snaphots

- .circleci/config.yml
- Makefile
- localstack/testing/pytest/marking.py
- tests/aws/test_ses.py
- tests/aws/test_sns.py
- tests/conftest.py
To make sure we don't forget to properly mark tests in `tests/aws/` a new guard in the pytest collection step is introduced which will fail in the collect step, i.e. before attempting to execute any tests.
- Tests will immediately fail when they have no `@markers.aws.*` attached
- Tests will also immediately fail when they have more than one `@markers.aws.*` attached
- A new step has been added to the preflight job in circleci to fail as early as possible.
> Enforce exactly one AWS pytest marker on each test case

- localstack/services/s3/provider.py
Include part number 10000 in allowed part numbers when checking for PartNumber in UploadPart handler.
Fixes #8869
Fix a non-conformity with respect to AWS S3 API. Without this fix `localstack` doesn't allow part number 10000 in multipart upload.
Fix part number validation in UploadPart handler
> fix: S3 multipart upload part 10000

- localstack/aws/protocol/serializer.py
- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
- tests/aws/s3/test_s3.py
- tests/aws/s3/test_s3_api.py
- tests/aws/s3/test_s3_api.snapshot.json
- tests/unit/aws/protocol/test_serializer.py
This PR implements Bucket Versioning in the new native S3 provider. This in turn allowed me to properly tests what I had already written but couldn't test because I couldn't actually enable the versioning, and fix what was wrong. 
This PR also contains a new feature in the serializer: we couldn't add headers to exceptions, when S3 actually does that. I'm not sure this is common to all XML protocol based services, so I contained it only in S3 for now. I tried to keep the same existing logic as much as I could, but applied to exceptions.
> implement S3 native bucket versioning

- localstack/services/apigateway/patches.py
- localstack/services/apigateway/provider.py
- tests/aws/apigateway/test_apigateway_common.py
- tests/aws/apigateway/test_apigateway_common.snapshot.json
Further enhance parity of API Gateway patch operations. Follow-up from  #8836. Addresses #8739 Unfortunately,  #8836 introduced a regression where certain fields of Stages cannot be updated now.
In the process of more snapshot testing, I've discovered a few more discrepancies in the moto logic, which are also fixed in this PR (and some obsolete moto patches removed). 
* fix regression to allow updating `/*/*/throttling/burstLimit` stage attributes
* extend the snapshot test to cover this functionality
* remove obsolete moto patches
> Further enhance parity of API Gateway patch operations

- localstack/services/kms/provider.py
- tests/aws/test_kms.py
Some users have requested to specify custom IDs for KMS keys. The old `local-kms` KMS provider used to allow preseeding keys on LocalStack startup. This is now a bit more tricky, as with our new provider each key would get a new ID, making it harder for users to create test scripts that rely on static key IDs.
* Add ability to specify custom IDs for KMS keys. We're using the `_custom_id_` tag key, which is already used in other places, e.g., for [API Gateway](https://docs.localstack.cloud/user-guide/aws/apigateway/#custom-ids-for-api-gateway-resources-via-tags)
* Add a small integration test (marked as `only_localstack`) to cover this functionality
> Add ability to specify custom IDs for KMS keys

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/constants.py
- localstack/services/s3/utils.py
- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
- tests/aws/s3/test_s3.py
- tests/aws/s3/test_s3.snapshot.json
- tests/aws/s3/test_s3_api.py
- tests/aws/s3/test_s3_api.snapshot.json
This PR implements Bucket Encryption, and sets the new default to `AES256` like AWS does since April 2023.
It also implements a feature we've been missing, when not specifying a KMS KeyId when using `aws:kms` encryption, we're now creating and keeping the reference to the AWS managed key. We're however missing an internal way to specify that the key is "AWS managed", and not customer managed.
> add S3 native bucket encryption and AWS key managed key

- localstack/services/s3/notifications.py
- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
This PR implement notifications for the new native S3 provider.
Only 2 types of notifications are missing, concerning ACL and Tagging, because those operations are not yet implemented in the new provider but this will come. The most important was to make it compatible with the new provider.
> implement S3 native notifications

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/utils.py
- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
- tests/aws/s3/test_s3_api.py
- tests/aws/s3/test_s3_api.snapshot.json
This PR implements all tagging related operations and usage:
Tagging with:
- PutObject
- CopyObject (and `TaggingDirective`) 
- PutObjectTagging
- DeleteObjectTagging
- GetObjectTagging
- PutBucketTagging
- DeleteBucketTagging
- GetBucketTagging
As well as S3 notifications support for Put/Delete object tagging.
> implement S3 native tagging

- .gitignore
- bin/docker-entrypoint.sh
- bin/localstack-start-docker-dev.sh
- localstack/aws/serving/edge.py
- localstack/cli/localstack.py
- localstack/config.py
- localstack/http/hypercorn.py
- localstack/services/edge.py
- localstack/utils/collections.py
- localstack/utils/json.py
- setup.cfg
- tests/aws/conftest.py
- tests/integration/conftest.py
- tests/unit/aws/test_connect.py
- tests/unit/cli/test_cli.py
- tests/unit/http_/test_hypercorn.py
- tests/unit/test_config.py
- tests/unit/test_edge.py
Use GATEWAY_LISTEN to bind hypercorn and TCP proxies
- make the localstack-start-docker-env.sh script more system-agnostic (I run NixOS and `/bin/bash` does not exist). Also the `$VENV_DIR` variable was not honoured in the script.
- the hypercorn gateway now takes a list of `HostAndPort` types, which allows binding to multiple addresses
- the `HostAndPort.parse` method is more powerful (i.e. handles parse errors better)
- start the hypercorn gateway for unpriviliged ports and create TCP proxies for priviliged ports, running as sudo if required
- add a special case for our custom json encoder to handle `HostAndPort` instances
> Integrate GATEWAY_LISTEN

- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
This PR implements/migrate S3 Lifecycle to the new S3 native provider, as well as the following mocked APIs:
- AnalyticsConfiguration
- IntelligentTieringConfiguration
- InventoryConfiguration
This migrates the code to be compatible with both provider, and implements it in the new provider. As the changes were pretty minimal, I've also migrated simple only mocked APIs as well.
> implement S3 native Lifecycle + mocked Bucket APIs

- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
- localstack/services/s3/website_hosting.py
- tests/aws/s3/test_s3.py
This PR migrate the current S3 Website router to be compatible with both providers, as well as implementing the BucketWebsite API.
The current S3 website was very tightly coupled with the moto backend, making it impossible to use with the new provider. We discussed it quickly with @alexrashed, and the internal boto client makes much more sense to use here as it totally abstracts away any difference there might be in the providers. Currently the implementation is the same as the previous one.
I've also changed some operations to be multi-account aware, so that they're able to access any buckets in any account when using the boto client. \cc @viren-nadkarni
> implement S3 native Website

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/exceptions.py
- localstack/services/s3/utils.py
- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
- localstack/services/s3/v3/storage/core.py
- localstack/services/s3/v3/storage/ephemeral.py
- localstack/testing/pytest/fixtures.py
- tests/aws/s3/test_s3.py
- tests/aws/s3/test_s3.snapshot.json
- tests/aws/s3/test_s3_api.py
- tests/aws/s3/test_s3_api.snapshot.json
Implement the ObjectLock functionality in the new native S3 provider. This was partially implemented in our provider in order to fix Moto.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-overview.html
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-managing.html
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html
This PR adds the necessary API operations as well as a good amount of snapshot tests.
- `GetObjectLockConfiguration`
- `PutObjectLockConfiguration`
- `GetObjectLegalHold`
- `PutObjectLegalHold`
- `GetObjectRetention`
- `PutObjectRetention`
> implement S3 native object lock

- localstack/utils/aws/templating.py
- setup.cfg
There have been a couple of changes recently in our fork of [`airspeed`](https://github.com/localstack/airspeed) - introducing snapshot tests, improving parity with AWS, etc.
This PR updates the version of `airspeed-ext` to `0.6.0`, to leverage the latest enhancements and enhanced parity for Velocity templates in API Gateway and AppSync.
> bump version of airspeed-ext to 0.6.0

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
- localstack/services/s3/v3/storage/core.py
- localstack/services/s3/v3/storage/ephemeral.py
- tests/aws/s3/test_s3.py
- tests/aws/s3/test_s3.snapshot.json
- tests/unit/aws/protocol/test_serializer.py
This PR implements a small mocked API, BucketPaymentRequest, which is only mocked currently.
It was also an opportunity to add functionality to the "core" operations that were not done. Also, rounds of CI runs showed small issues in the current logic that were hard to spot earlier.
This PR implements `BucketRequestPayment` API, which are only mocked and do not have actual effect on the global behaviour of S3 (like moto today).
It also implements preconditions checks for `HeadObject`, `GetObject` and `CopyObject`. 
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Unmodified-Since
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since
- …
> implement S3 native RequestPayment, GetObject Part, Preconditions

- localstack/services/dynamodb/provider.py
- tests/aws/test_dynamodb.py
This PR enables `Scan` and `Query` operations to work on Global Tables.
An existing global tables tests is modified to make additional assertions on these operations.
Closes: #8824
> DynamoDB: Global table support for Scan and Query

- localstack/services/apigateway/templates.py
- tests/unit/test_apigateway.py
We recently had a couple of changes in our `airspeed` for, for better AWS parity - see also recent PR #8914 .
One of the main changes is that booleans are now properly rendered as `true`/`false`, and not via the Python syntax `True`/`False`.
This leads to some potential issues in API Gateway (detected by upstream tests in -ext). In the API GW `ResponseTemplates` we were using `ast.literal_eval`, instead of proper `json.loads`, mainly to be able to deal with the booleans in Python syntax. This is fixed in this PR, `ast.literal_eval` is replaced by `json.loads`, and the logic is extended with a small unit test to cover this functionality.
* fix parsing of booleans in API Gateway Velocity templates (replace `ast.literal_eval` with `json.loads`)
* add a small unit test to cover this …
> Fix parsing of booleans in API Gateway Velocity templates

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/constants.py
- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
- tests/aws/s3/test_s3_api.py
- tests/aws/s3/test_s3_api.snapshot.json
Implement Bucket API operations, those are currently only mocked and do not influence S3 behaviour. ObjectOwnership should have some impact, as it should prevent some ACLs to be set on Object, like in AWS. PublicAccessBlock cannot really be enforced, as we do not have the concept of public/anonymous access to S3 (credentials are always being set). It also has some logic tied to `s3control`, where the settings would be the most restrictive between the bucket PublicAccessBlock and the owner ones. As it's only mocked, we currently do not implemented this.
Implement the following API operations:
- `GetBucketOwnershipControls`
- `PutBucketOwnershipControls`
- `DeleteBucketOwnershipControls`
- `GetPublicAccessBlock`
- `PutPublicAccessBlock`
- `DeletePublicAccessBlock`
And the validation …
> implement S3 native PublicAccessBlock and ObjectOwnership

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/exceptions.py
- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
- tests/aws/s3/test_s3_api.py
- tests/aws/s3/test_s3_api.snapshot.json
This PR implements the BucketPolicy and BucketAccelerateConfiguration to the new S3 provider.
Those operations were only implemented in moto. Added a tiny bit of validation for the Bucket Policy, but we should/could go a bit further. 
Implemented operations:
- `PutBucketPolicy`
- `GetPolicyPolicy`
- `DeletePolicyPolicy`
- `GetBucketAccelerateConfiguration`
- `PutBucketAccelerateConfiguration`
> implement S3 native Bucket Policy and AccelerateConfig

- localstack/services/s3/provider.py
- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
- localstack/services/s3/v3/storage/ephemeral.py
- tests/aws/s3/test_s3.py
- tests/aws/s3/test_s3.snapshot.json
Implement S3 BucketLogging and BucketReplication mocking, only adding validation but not actually emulating the replication.
Added a small fix regarding locking when accessing a Multipart, to not create it twice.
Implemented the following API operations:
- `PutBucketLogging`
- `GetBucketLogging`
- `PutBucketReplication`
- `GetBucketReplication`
- `DeleteBucketReplication`
> implement S3 native BucketLogging and BucketReplication

- localstack/services/edge.py
- localstack/utils/net.py
- tests/unit/utils/test_net_utils.py
In order to test the DNS server on arbitrary ports, we need a way to get random free udp ports, similar to the `get_free_tcp_port` utility for tcp.
* Add `get_free_udp_port` utility
* Add a test for said utility
* use `shlex.join` instead of a normal string join for shell commandline in `run_module_as_sudo`
> Add get_free_udp_port utility + test

- localstack/services/s3/constants.py
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- localstack/services/s3/v3/models.py
- localstack/services/s3/v3/provider.py
- localstack/services/s3/validation.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/unit/test_s3.py
Implement S3 Bucket and Object ACL, even if not enforced, in the new S3 provider.
This combines Moto ACL implementation with the fixes we have in moto-ext. For this we are not going the extra miles, keeping the same functionality as we had. As we do not enforce ACL at the moment, this is fine. AWS does not encourage the use of ACL now.
Also added some tests for `GetObjectACL`/`PutObjectACL` which were missing.
This PR implements:
- `PutBucketACL`
- `GetObjectACL`
- `PutObjectACL`
- `GetObjectACL`
- Support for ACL in following operations:
- `PutObject`
- `CreateMultipartUpload`
- `CopyObject`
> implement S3 native ACL

- localstack/services/s3/constants.py
- localstack/services/s3/provider.py
- localstack/services/s3/utils.py
- localstack/services/s3/v3/provider.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/unit/test_s3.py
Implementing the missing PostObject operation, which is needed for pre-signed POST requests. 
`PostObject` is a bit of a weird operation in itself because everything is in a form, and the parser doesn't handle this kind of request right now, and maybe it shouldn't just for one operation. So most of the "parsing" is done directly in the provider method. I've added a bit more features than moto, as we now handle encryption parameters, tagging, and more response fields.
> implement S3 native pre-signed POST (PostObject)

- tests/aws/test_network_configuration.py
- tests/aws/test_serverless.py
We are currently running out of memory in our test runs.
This is a combination of the recent test reordering, which showed us this issue, and insufficient test cleanup.
* Cleanup serverless tests, even if the command fails
* Cleanup opensearch instances after starting them for endpoint strategy tests
> Fix community test against Pro runs

- localstack/http/request.py
- tests/unit/http_/test_request.py
This PR would fix #8928 and #8924. We had an issue with parsing the WSGI environ `RAW_URI`, because an HTTP request can also contain a full URL and not only an absolute path. See the RFC: https://www.ietf.org/rfc/rfc2616.txt
```
To allow for transition to absoluteURIs in all requests in future
versions of HTTP, all HTTP/1.1 servers MUST accept the absoluteURI
form in requests, even though HTTP/1.1 clients will only generate
them in requests to proxies.
```
We would then have more than the path with `get_raw_path`, which lead to issue down the road when trying to match in our router.
We now thanks to @dfangl parse the `RAW_URI` variable with `urllib.parse.urlparse` to then only get the `path` part of the `RAW_URI` in case there's more. 
Added a unit test covering this use case.
> fix get_raw_path parsing

- localstack/testing/pytest/fixture_conflicts.py
- localstack/testing/pytest/snapshot.py
- tests/conftest.py
It seems we lost the type hinting in PyCharm for the snapshot fixture in our tests, which makes especially adding new tests much less intuitive.
- Introduce new _snapshot_session fixture
- Add (technically redundant) snapshot fixture so that PyCharm picks up the correct typing.
-ext will receive a similar fixture that will expose the typed _snapshot_session and thus allow  us to have types again.
> Add back support for type hints in PyCharm for snapshot fixture

- localstack/services/cloudformation/models/ec2.py
- tests/aws/services/cloudformation/resources/test_ec2.py
Support issue with CDK stack where `UserData` is not applied to freshly launched EC2 instances. `UserData` itself is implemented and works in EC2.
Add the missing CloudFormation implementation for the `UserData` property. It requires a callback to decode the base64-encoded field.
Minor refactoring of verbose current folder implementation (initially started with EC2 test but I noticed that is better covered in a scenario test).
Tested through custom CDK stack and support sample. An EC2 scenario test is partially drafted for localstack-ext (follow up in separate PR).
> Fix missing implementation of CloudFormation EC2 UserData

- localstack/services/cloudformation/models/apigateway.py
- tests/aws/scenario/test_apigateway_scenario.py
- tests/aws/scenario/test_apigateway_scenario.snapshot.json
Support case https://localstack-community.slack.com/archives/C05HSNXLQ2J. The CF resource "AWS::ApiGateway::GatewayResponse" was missing a physical resource id value.
Adds a handler function and generates a physical resource id.
Uses the new cdk based test setup, thanks @dominikschubert for the heads up
Also thanks to @sannya-singal for helping out with the discover and testing :+1:
> provide result handle to AWS::ApiGateway::GatewayResponse

- localstack/services/cloudformation/models/apigateway.py
The signature required for the result handlers has recently been  changed in https://github.com/localstack/localstack/pull/8822 but afterwards https://github.com/localstack/localstack/pull/8925 was merged which added a result handler with the old signature.
- fix the signature of the result_handler introduced in https://github.com/localstack/localstack/pull/8925
> Fix result handler signature AWS::ApiGateway::GatewayResponse result handler

- localstack/services/cloudformation/engine/template_deployer.py
- tests/aws/services/cloudformation/engine/test_references.py
- tests/aws/services/cloudformation/engine/test_references.snapshot.json
- tests/aws/templates/engine/cfn_fn_sub.yaml
Fixes the issue multiple people experienced where pseudo-parameter couldn't be resolved correctly when used in `Fn::Sub`.
Example error message: `Unable to resolve attribute ref AWS::URLSuffix`
Resolves https://github.com/localstack/localstack/issues/8726
- check for pseudo-parameter when resolving a placeholder in a sub string and resolve them recursively
> Fix resolving pseudo-parameters in Fn::Sub

- localstack/testing/scenario/provisioning.py
The current configuration of the `WaiterConfig` used for the CDK based setup, does have a very limited waiting time configured. 
When running a complex scenario, e.g. setting up several database-cluster with instances, it will timeout on AWS before the deployment finishes, therefore failing the test, potentially starting the teardown. 
* Increased the `WaiterConfig` for setup + teardown
* Only delete the CDK_BOOTSTRAP_PARAM for LocalStack runs
> increase WaiterConfig for setting up scenarios on AWS

- localstack/services/cloudformation/resource_provider.py
In an effort to simplify our cloudformation service provider implementation in -ext we want to avoid patching as much as possible.
- the patch for get_service_name has been moved to community
> Move handling of special cases when mapping CFn type to service to community

- tests/aws/services/cloudformation/resources/test_dynamodb.py
- tests/aws/services/cloudformation/resources/test_dynamodb.snapshot.json
- tests/aws/services/dynamodb/test_dynamodb.py
- tests/aws/services/dynamodb/test_dynamodb.snapshot.json
Part of the workstream for AWS testing: updating old snapshots. 
This PR is for `dynamodb` service
- updated snapshots
- removed skip parameters for a few parameters
- added skip parameter for `DeletionProtectionEnabled`
- fixed invalid catch in a test (did not work against AWS)
> Update dynamodb snapshots

- localstack/services/edge.py
- localstack/testing/aws/lambda_utils.py
- tests/aws/services/lambda_/conftest.py
- tests/aws/services/lambda_/test_lambda.py
We also want multiruntime tests in -ext, in this case for transparent endpoint injection tests.
This slight refactoring basically moves the logic to the testing/aws/lambda_utils module instead of the conftest.py, which enables us to use the logic with very little duplicated code in -ext.
Also, there were some logical issues recently introduced with changes in edge.py for `run_module_as_sudo` which are corrected with this pr /cc @simonrw 
* Move the multiruntime test logic to testing module
* Fix `run_module_as_sudo` logic
> Move lambda multiruntime test logic to testing module

- localstack/services/lambda_/invocation/lambda_service.py
S3 `CreateBucket` is supposed to be idempotent in `us-east-1`. However, due to [failing tests](https://github.com/localstack/localstack/pull/8912/commits/6b23f6c114af828496d10507780d9154c9a75203) in a merge commit, a use case of this behaviour was removed in https://github.com/localstack/localstack/pull/8912/commits/cb6c4f196018ef4ab6dbf265ce9f4943d0e5d350.
cc: @dfangl 
This PR attempts to understand why this idempotent behaviour disappeared all of a sudden.
> Rely on S3 create bucket idempotency in us-east-1

- localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_sqs.py
- localstack/services/stepfunctions/backend/state_machine.py
- localstack/services/stepfunctions/provider_v2.py
- tests/aws/services/stepfunctions/v2/test_sfn_api_tagging.py
- tests/aws/services/stepfunctions/v2/test_sfn_api_tagging.snapshot.json
Adds support for Resource Tagging to Step Functions.
Added a TagManager to State Machine Revision instances.
Added support for api actions: `tag_resource`, `untag_resource`, `list_tags_for_resource`.
Added relevant positive and negative snapshot tests `tests.aws.services.stepfunctions.v2.test_sfn_api_tagging.TestSnfApiTagging`
> [SFN] Support for Resource Tagging

- setup.cfg
Bump version of airspeed to 0.6.1 - there have recently been some enhancements for handling of multi-line dict expressions: https://github.com/localstack/airspeed/pull/11
The PR updates `airspeed-ext` to `>= 0.6.1` - I'd argue we can use an open version range (instead of exact pin), as we're now in full control of our airspeed fork, and the functionality is covered by shapshot tests, so breaking changes should be unlikely. Using a version range will allow us to move a bit more quickly, not having to bump the version across different repos each time.
> bump version of airspeed to 0.6.1

- localstack/services/cloudformation/models/dynamodb.py
- tests/aws/services/cloudformation/resources/test_dynamodb.py
- tests/aws/services/cloudformation/resources/test_dynamodb.snapshot.json
- tests/aws/templates/dynamodb_table_defaults.yml
Tags for creating DynamoDB table are not created. The issue was raised in a support case.
* Add support for resource tags for the create table operation.
* Add `aws.validated` marker for `test_deploy_stack_with_dynamodb_table` and `test_globalindex_read_write_provisioned_throughput_dynamodb_table` because both tests ran successfully against AWS when executing all tests in the file.
Extended an AWS-validated test case to cover tags.
Fixes the sample from the support case.
> Add tags support for CloudFormation DynamoDB create table

- Dockerfile
- localstack/packages/api.py
- localstack/packages/core.py
- localstack/services/transcribe/packages.py
- localstack/services/transcribe/plugins.py
- localstack/services/transcribe/provider.py
- setup.cfg
This PR adds a new type of `PackageInstaller` which allows the installation of Python packages at runtime for specific services.
The PoC was implemented based on our Transcribe emulator, removing the `vosk` dependency in the `setup.cfg` and instead installing it on demand.
VOSC is one of the bigger dependencies, with ~7MB compressed and ~26MB uncompressed. In my tests this reduced the uncompressed layer size of the `venv` copying layer from 426 MB to 399 MB:
https://github.com/localstack/localstack/blob/10630f07dd838c9b5a71dd087de8bbc044b417fe/Dockerfile#L144
- It introduces two new linked virtual environments, one for static (docker build time) and one for var libs (runtime, using a shared folder mounted from the host) in the `Dockerfile`.
- This …
> add PythonPackageInstaller for runtime package installation

- localstack/testing/pytest/fixtures.py
- tests/aws/services/cloudformation/api/test_nested_stacks.py
This PR replace the usage of the wait_until method for boto3 waiters due to  the better behavior on stacks that take too much time to deploy.
> replace the method wait_until with boto3 waiters in cfn fixture

- localstack/utils/analytics/client.py
- localstack/utils/analytics/publisher.py
- tests/unit/utils/analytics/test_publisher.py
While working on the analytics backend, we noticed that the client actually isn't reacting to `track_events=False` responses from the server. Good catch @ackdav.
* Properly disable the global analytics bus if the backend responds with `track_events=False`
* Add a gate for 403 errors, which we will introduce in the analytics backend to properly terminate older clients. In the older clients a 403 would trigger an exception in the `AnalyticsClient.start_session` method, also leading to disabling of tracking, albeit less gracefully.
> fix global analytics bus to correctly disable tracking

- localstack/services/sns/constants.py
- localstack/services/sns/models.py
- localstack/services/sns/provider.py
- localstack/services/sns/publisher.py
- localstack/testing/pytest/fixtures.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
Refreshing SNS snapshots which were for most 1 year old
Organised the tests in more classes, to try to separate a little the different cases. It's not very precise, but it allows a bit more fine grained organisation, and it's easier to run/refresh only a certain kind of tests only after a change instead of re-running the whole suite locally. 
Refreshing snapshots put into a light a change regarding FIFO topics: they now accept regular SQS queue as subscribers. Those are not guaranteed to be FIFO, but the deduplication is working (as it's a the topic level, not the subscriber queue level). This is not yet implemented in LocalStack, but there's a TODO to implement it.
Also added a dummy subscription principal to the SNS subscription, as the field was missing. Maybe we could do a call to STS …
> refresh SNS snapshots

- localstack/services/edge.py
When binding hypercorn on privileged ports, if one of the ports is not available the entire hypercorn server will fail to bind, leaving LocalStack in a terminal failure state. This state is not caught in a user friendly way (the background thread dies leaving a traceback).
* This reverts commit 8246af9a3e3a8e1d17ead01932018c985c27aba2.
* allow hypercorn to only bind on unprivileged ports, and revert to using TCP proxies for unprivileged ports, meaning that at least hypercorn should be able to bind to _something_ even if the proxies fail
> Revert hypercorn binding to privileged ports

- localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_api_gateway.py
- tests/aws/services/stepfunctions/v2/services/test_apigetway_task_service.py
- tests/aws/services/stepfunctions/v2/services/test_apigetway_task_service.snapshot.json
When evaluating `StepFunction`'s `ApiGateway` tasks, the provided `ApiEndpoint` is converted to a path style LocalStack endpoint, if a url one is provided.
Improves loading of json `ResponseBody` and removes out of scope test inputs.
Added url transformation logic to the `ApiGateway`'s task resolver, as well as json request body parsing attempt.
> [SFN] ApiGW url implicit endpoint conversion

- localstack/services/lambda_/api_utils.py
- localstack/services/lambda_/invocation/lambda_models.py
- localstack/services/lambda_/provider.py
- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_api.snapshot.json
- tests/unit/test_lambda.py
This PR fixes an issue where Lambda layer compatibility check failed for the `python3.11` runtime:
```
$ awslocal lambda publish-layer-version --layer-name layer1 --zip-file fileb://.serverless/MyLayer.zip --compatible-runtimes python3.11
An error occurred (ValidationException) when calling the PublishLayerVersion operation: 1 validation error detected: Value '[python3.11]' at 'compatibleRuntimes' failed to satisfy constraint: Member must satisfy enum value set: [java17, provided, nodejs16.x, nodejs14.x, ruby2.7, python3.10, java11, python3.11, dotnet6, go1.x, nodejs18.x, provided.al2, java8, java8.al2, ruby3.2, python3.7, python3.8, python3.9]
```
This PR adds `python3.11` to the list of supported runtimes for Lambda layer validation.
A snapshot verified test creating a Lambda layer with …
> fix lambda layer version compatibility with Python 3.11

- localstack/services/cloudformation/models/opensearch.py
- tests/aws/services/cloudformation/resources/test_opensearch.py
- tests/aws/services/cloudformation/resources/test_opensearch.snapshot.json
- tests/aws/templates/opensearch_domain.yml
Working on scenario tests revealed that opensearch currently requires the `DomainName` attribute, which shouldn't necessarily be the case. 
The [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opensearchservice-domain.html) suggest that the parameter is "conditional" required and state:
> The name must have a minimum length of 3 and a maximum length of 28. If you don't specify a name, AWS CloudFormation generates a unique physical ID and uses that ID for the domain name. 
* adapted CFN model and genenerate a `DomainName` if none is set
* aws-validated test
> add domain-name for opensearch domain in cfn

- localstack/packages/core.py
This PR fixes a bug introduced with #8685.
The new `PythonPackageInstaller` detects the `venv` based on `constants.LOCALSTACK_ROOT_FOLDER`.
Unfortunately, this doesn't work if `localstack-core` is installed in the venv, so `LOCALSTACK_ROOT_FOLDER` is within the venv, resulting in a wrong venv dir detection.
This can easily be reproduced with the following `Dockerfile`:
```
FROM localstack/localstack-pro:latest
RUN export DEBUG=1; source .venv/bin/activate && python -m localstack.cli.lpm install vosk
```
It results in the following error:
```
0.623 installing... Vosk
0.624 2023-08-30T10:07:08.063 DEBUG --- [d-1 (worker)] localstack.packages.api    : Starting installation of vosk...
0.624 2023-08-30T10:07:08.064  INFO --- [d-1 (worker)] localstack.packages.core   : creating virtual …
```
> fix python installer when running LS from venv module

- localstack/services/s3/v3/provider.py
- localstack/services/s3/v3/storage/core.py
- localstack/services/s3/v3/storage/ephemeral.py
- tests/unit/test_s3.py
Improving the current S3 storage layer, introduce 2 more operations to allow easier cleanup of resources with bucket creation and deletion. Also separate between `close` and `reset` the store, to have better semantics between these 2 operations (closing does not always mean deleting all underlying objects, especially with persistence enabled). 
Separate between the `close` call for the Ephemeral object, so that it doesn't close the underlying file object, which would delete it in Ephemeral mode, following the fix to the response with #8926. 
Introduce said changes above, `create_bucket` and `delete_bucket` for the storage layer, and preparing support for persistence. 
Also added a quick fix regarding creating bucket in `us-east-1`, I wasn't returning early from the method and ended up …
> improve S3 v3 storage layer

- localstack/http/client.py
- localstack/services/opensearch/cluster.py
- localstack/services/s3/virtual_host.py
- tests/aws/services/opensearch/test_opensearch.py
- tests/unit/http_/test_client.py
- tests/unit/http_/test_proxy.py
This PR addresses #8793, which describes an issue with the handling of the `Accept-Encoding` header when communicating with OpenSearch clusters with enabled http compression (as enabled statically with #8628).
This bug is actually caused by our HTTP client used in the Proxy infrastructure used to proxy requests from the client via LocalStack to the started OpenSearch server. This HTTP client _always_ adds `Accept-Encoding: gzip, deflate` to the proxied HTTP request if no `Accept-Encoding` is set in the originating request.
With enabling the compression support for OpenSearch (i.e. OpenSearch will compress the responses using GZIP `Content-Encoding` in responses if the client sends `gzip` in the `Accept-Encoding` request header), this issue surfaced since every request to OpenSearch via …
> fix proxy Accept-Header handling, combine http clients

- localstack/testing/pytest/fixtures.py
The usage of the `deploy_cfn_template` fixture is a major cause of temporary resource leaks.
Not waiting for the deletion to be completed causes the delete operations to bleed into the next test exexution(s).
After the yield, `deploy_cfn_template` now properly waits for the stack deletion before moving on to the next test case.
This will increase test execution time. Part of the intention of this PR is to find out by how much.
Update: Seems this didn't introduce as much delay as initially thought:
> Wait for stack deletion in test cleanup

- localstack/services/cloudformation/models/opensearch.py
- tests/aws/services/cloudformation/resources/test_opensearch.py
- tests/aws/templates/opensearch_domain.yml
Follow-up for https://github.com/localstack/localstack/pull/9027. 
The `DomainEndpoint` seems to be a commonly used [return value for Opensearch Domain](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opensearchservice-domain.html#aws-resource-opensearchservice-domain-return-values).
Added support for output of `DomainEndpoint`.
> enable DomainEndpoint cfn output for Opensearch

- localstack/config.py
- localstack/utils/container_networking.py
- localstack/utils/net.py
- tests/unit/utils/test_net_utils.py
We should ideally not be performing I/O operations in the top-level import path, including `config.py`, but rather defer such operations until they are actually required. This has recently surfaced as a reproducible issue in the Testcontainers Go module (https://github.com/testcontainers/testcontainers-go/issues/1495), causing very slow startups under Linux in certain circumstances.
* add a `get_docker_host_from_container(..)` utility function to remove DNS operations from `config.py`
* remove top-level constant `DOCKER_HOST_FROM_CONTAINER` from `config.py`
* use the new `get_docker_host_from_container(..)` function from `get_endpoint_for_network(..)` in `container_networking.py`
* add `get_addressable_container_host(..)` utility, which covers a fairly common use case to get the …
> Add get_docker_host_from_container(..) util to remove DNS operations from config.py

- Dockerfile
@simonrw noticed that when you first install an extensions using localstack pro, and then go back to using localstack community, there will be wonkyness because the extensions/python_venv contains a copy of localstack-ext.
We don't want to do this linking of venvs in community in the first place, so removing it here. This should be safe since we have this explicitly in the ext Dockerfile.
* remove the extensions venv linking from the community Dockerfile
> remove extensions venv link from Dockerfile

- localstack/services/sns/provider.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
This issue was raised in #8816, SNS would not raise an exception if the `Subscribe` call had different attributes when the subscription already exists.
We now check if the found subscription if it exists would have the same attributes, and if it doesn't, raise an exception. Added a validated AWS test with it.
> fix SNS subscribe idempotency with different attrs

- localstack/services/dynamodb/provider.py
- tests/aws/services/dynamodb/test_dynamodb.py
This PR addresses that the DDB operations [DescribeTimeToLive](https://docs.aws.amazon.com/cli/latest/reference/dynamodb/describe-time-to-live.html) and [UpdateTimeToLive](https://docs.aws.amazon.com/cli/latest/reference/dynamodb/update-time-to-live.html) both had no checks in regards to the existence of the table, as highlighted in #9030. 
The `ResourceNotFoundException` message might look peculiar, but this is due to parity:
```
$ aws dynamodb describe-time-to-live --table-name test
An error occurred (ResourceNotFoundException) when calling the DescribeTimeToLive operation: Requested resource not found: Table: test not found
$ aws dynamodb update-time-to-live --table-name test --time-to-live-specification Enabled=true,AttributeName=ttl
An error occurred (ResourceNotFoundException) when …
```
> add ddb ttl resource-exceptions for inexistent tables

- setup.cfg
deepdiff released 6.4 overnight, which has an issue: https://github.com/seperman/deepdiff/issues/415. This PR pins the version to unblock the pipeline.
- pin deepdiff to 6.3.1
> pin deepdiff to version 6.3.1

- localstack/aws/protocol/serializer.py
- localstack/services/s3/presigned_url.py
- localstack/services/s3/provider.py
- localstack/services/s3/v3/provider.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3_cors.py
As reported in #9032, some S3 operations (the one using the `PUT` http method) would return an empty XML body when the S3 docs specifies that the body should be empty. After looking at the specs, only `CopyObject` and `CopyObjectPart` would return a body. Luckily, those operations implement a field specifying that they return a body, the `payload` one.
Removed the pre-signed handler deleting the response body, since this behaviour should have been for every `PUT` request except some, and it was actually fixing a symptom instead of the cause.
Implemented a check in the serializer for not serializing a body if the conditions were not set (if it's a PUT request without the `payload` field). 
Added 2 cases in a test checking the raw returned body without boto parsing, one for a known PUT …
> fix S3 PUT operations returning HTTP Body by default

- CODEOWNERS
- localstack/testing/pytest/container.py
- localstack/utils/bootstrap.py
- tests/bootstrap/conftest.py
- tests/bootstrap/test_container_listen_configuration.py
- tests/conftest.py
The container fixtures created in ... were:
* only usable in the `bootstrap` subdir, but we need them in the `cli` subdir (amongst others)
* are too widely scoped (session scoped `ContainerFactory`)
* uses a confusing fixture order (cleanups)
* did not store the running container, so automatic cleanup was not possible
Fix the items above
> Container fixture improvements

- localstack/services/cloudformation/models/ec2.py
While adding the resource for AWS::EC2::VPCCidrBlock as mentioned in https://github.com/localstack/localstack/issues/8511 in cloud formation template, there were parity issues found in resource `AWS::EC2::VPC`. 
This PR fixes value for param `CidrBlockAssociations`. 
Related test added in [#2018](https://github.com/localstack/localstack-ext/pull/2018)
> fix value of for CidrBlockAssociations in AWS::EC2::VPC

- localstack/services/apigateway/provider.py
- tests/aws/services/apigateway/test_apigateway_common.py
- tests/aws/services/apigateway/test_apigateway_common.snapshot.json
A user reported a stuck Terraform deployment with an API GW REST API: Terraform would loop and never finish while trying to update a stage when `xray_tracing_enabled` is set. 
When setting `TF_LOG=trace`, we see there's an issue when unmarshalling the response, because we were returning a string `"true"` instead of a boolean `True`.
```
DEBUG: Unmarshal Response apigateway/UpdateStage failed, attempt 9/25, error SerializationError: failed decoding JSON RPC response
```
Add a case to a snapshot test to validate this behaviour as well. 
Added a check if the path is `/tracingEnabled` to cast the value into a boolean.
Also used `copy.deepcopy` to the input, because we were modifying it in place, and the logging would show the modified input instead of what we really received. 
I could …
> fix APIGW UpdateStage with /tracingEnabled

- localstack/services/cloudformation/resource_provider.py
- localstack/services/opensearch/resource_providers/aws_opensearchservice_domain.py
- tests/aws/services/cloudformation/resources/test_opensearch.py
- tests/aws/services/cloudformation/resources/test_opensearch.snapshot.json
- tests/aws/templates/opensearch_domain.yml
Working with the Cfn and `opensearch` revealed a few shortcomings the past days. Already fixed some issues in the old provider, but it might be time to move the new `ResourceProvider` now 🙂 
* set the `opensearch` ResourceProvider as default for Cfn
* added logic to the `ResourceProvider` in a pairing session with @dominikschubert 
* enhanced test case a little (include `Tags`)
> add Cfn ResourceProvider for AWS::OpenSearchService::Domain

- localstack/utils/docker_utils.py
- localstack/utils/net.py
- tests/unit/test_common.py
- tests/unit/utils/test_net_utils.py
When creating multiple instances of localstack within tests, we need to randomize container ports. This includes the gateway port `4566`, but also the service port range. Specifically I need this in #9050 to make the `random_service_port_range` configurator work.
Until now, there was no good way of finding a random port range that is contiguous that could be mapped to the external service port range, this PR adds such a method to the `net` utils.
* add `get_free_tcp_port_range` that finds a random contiguous port range of `num_ports`
* made `PortRange` inclusive, i.e., it now correctly considers the port `5002` in range if the range is `PortRange(5000,5002)`
* add global `dynamic_port_range` that marks the default dynamic port range 49152 to 65535. this is now used in `get_free_tcp_port` …
> add utility to find contiguous port range

- localstack/dev/run/__main__.py
- localstack/dev/run/configurators.py
- localstack/dev/run/paths.py
- localstack/utils/container_utils/container_client.py
- localstack/utils/container_utils/docker_cmd_client.py
- localstack/utils/run.py
This PR introduces a script for developers that aims to replace `bin/docker-run.sh` and ultimately all its derivatives.
We have several ways of starting what I call a "dev container", i.e., a localstack container with various mounted things like source folders or dependencies. Here are some:
* `bin/localstack-start-docker-dev.sh`
* `make docker-mount-run`
* `make test-docker-mount`
* `make docker-run-tests`
* `test-docker-mount-code`
In ext:
* `bin/docker-run.sh`
* `bin/test-in-docker.sh`
* `make docker-mount-run`
* ...
With the introduction of #8781 and #9050, there was an opportunity to unify some of the code necessary to start and configure such a dev container.
Moreover, with the growing amount of bootstrap tests (network configs, extensions, persistence, ...) there was a need to run …
> add dev container run script

- .github/dependabot.yml
- .github/workflows/asf-updates.yml
- .github/workflows/dockerhub-description.yml
- .github/workflows/tests-cli.yml
- .github/workflows/tests-podman.yml
- .github/workflows/tests-pro-integration.yml
We are still seeing build issues related to https://github.com/actions/checkout/issues/1448, even though the incident should already be fixed (according to https://www.githubstatus.com/).
Some comments in this issue imply that an upgrade to the just newly released version 4 of [actions/checkout](https://github.com/actions/checkout) might fix the issue.
I used this opportunity toi also 
- Upgrades all usages of [actions/checkout](https://github.com/actions/checkout) to version 4.
- Add GitHub actions to the dependabot config to file these upgrade PRs automatically in the future.
> upgrade to actions/checkout@v4, add actions to dependabot

- localstack/aws/scaffold.py
The latest version of `botocore` contains a change in the spec (namely https://github.com/boto/botocore/commit/29dbcb9e1408c63ce9a3215447116789d6b4f528) which contains a backslash in the documentation of an operation of SESv2.
API code generated based on this botocore version fail the linting check, because the generated docstring contains the <code>\`\\`</code> (which violates [flake8's W605](https://www.flake8rules.com/rules/W605.html)).
This PR just adds the backslash to the list of characters which need to be escaped in the docstring to fix the linting errors.
The SESv2 API has been generated based on the change and it passes the linting.
> fix escaping backslash in comments

- localstack/services/secretsmanager/provider.py
- tests/aws/services/secretsmanager/test_secretsmanager.py
- tests/aws/services/secretsmanager/test_secretsmanager.snapshot.json
A regression was introduced in moto and part of localstack after #9044 when calling `PutSecretValue` on a secret with no value.
This adds a test for the fix in https://github.com/getmoto/moto/pull/6775
Edit: well, apparently this has been fixed with https://github.com/getmoto/moto/pull/6771
I don't know if we already want to do a moto bump, or we keep this fix inside LocalStack for now, this might be faster still. 
I've also put the fix in the patch for the moment until the next moto bump where we can remove it and use the one from upstream. This fix is kinda urgent, as the customer is downgrading moto in their LocalStack container in the meantime and it introduces incompatibilities, especially with `logs`.
> fix secretsmanager PutSecretValue on empty secret

- localstack/services/s3/models.py
- tests/aws/services/s3/test_s3_concurrency.py
We had some problem with simultaneous bucket operations. This PR adds a test for it. It should be fixed with #9044
* Add list wrapper to avoid issue with concurrent modification of a dict while iterating
* Add test for 10 simultaneous bucket creations with the requirement of us-east-1 bucket creation idempotency.
> Add test for s3 bucket concurrency

- localstack/services/apigateway/models.py
- localstack/services/apigateway/provider.py
- tests/aws/services/apigateway/test_apigateway_api.py
- tests/aws/services/apigateway/test_apigateway_api.snapshot.json
We've had a feature request to implement UpdateGatewayResponse, which was missing from the moto implementation.
After a quick check to the moto implementation and some AWS validated tests, it showed that the current implementation was lacking all the default `GatewayResponse` from AWS. It was then quicker to implement it in our provider than to patch the whole moto implementation just to add an operation, especially since the moto implementation did not implement any validation. 
To note: even though this is implemented, we don't currently use `GatewayResponse` in our actual invocation part of the code. It also shows that there are different kinds of exception raised internally, and this could help us restructure the code around those exceptions (looking at the response type documentation …
> Implement APIGW UpdateGatewayResponse

- tests/aws/test_terraform.py
The tests in `TestTerraform` have been a headache since forever.
They don't provide enough value given their flakiness, so we'll disable them and will look into some other strategy in the future. 
- Disables terraform tests
> Disable terraform tests

- .github/workflows/marker-report.yml
- localstack/testing/pytest/marker_report.py
- localstack/testing/pytest/marking.py
- tests/aws/services/cloudformation/resources/test_sns.py
- tests/conftest.py
We want to keep track of the state of our AWS tests, especially the correct marking.
A recently introduced plugin already enforces correct exactly-once marking with `aws_` markers, but we still have a lot of `aws_unknown` markers which we should try to get down to 0. 
We also want to track the progress over time.
The plugin has been implemented in a somewhat generic way, so we can use it for other non-aws markers as well.
- Add a new plugin to our pytest plugin suite which can be used to generate a json report about the markers used in our pytest tests
- Adds a new workflow that uploads data about marker usage to tinybird
- Adds the plugin to our pytest config
```bash
python -m pytest tests/aws/services/lambda_ --marker-report --marker-report-prefix aws_ --co -qqq
```
> Add pytest marker report plugin

- Makefile
- localstack/aws/connect.py
- localstack/config.py
- tests/aws/services/lambda_/test_lambda_api.py
These uncontrolled boto-client level retries are an inherent source of unpredictable behavior, so let's see if disabling them causes any unexpected issues.
Retries also cause unnecessary time waiting when we actually want to test a failure case.
- disables retries for all clients created via our client factories in our test suite (CI)
- adds config variable `DISABLE_BOTO_RETRIES`. Set `DISABLE_BOTO_RETRIES=1` to opt-tin of the new behavior.
Might also want to go through cases where we use SDKs in lambda functions etc. to disable any retries.
> add option to disable retries & disable boto retries for CI tests

- Makefile
- localstack/services/apigateway/provider.py
- tests/aws/services/apigateway/test_apigateway_common.py
- tests/aws/services/apigateway/test_apigateway_common.snapshot.json
Addresses a user issue reported in Slack. We are currently seeing parity issues in the linkage between API Gateway stages and deployments. In a nutshell, we need to establish a bidirectional link `stage<>deployment` for the `create_stage(..)` API. Moto was currently only adding the `stage->deployment`, but the reverse direction was still missing, leading to deployment errors, e.g., with Terraform.
* update `create_stage(..)` to update the `stage_name` on the Deployment on creation of a Stage
* add small fix in `get_stages(..)` to transform the result entries
* add Makefile parametrization for `DISABLE_BOTO_RETRIES` (API Gateway snapshot tests require retries, due to high frequency of `TooManyRequestsException`)
* add a snapshot test to cover a sequence of different creations/deletions of …
> Update deployment stage_name when creating API Gateway stages to fix parity issues

- localstack/services/s3/utils.py
- localstack/services/s3/v3/provider.py
- tests/aws/services/s3/test_s3_api.py
- tests/aws/services/s3/test_s3_api.snapshot.json
As reported in #9076, there is an issue in the way Moto and LocalStack handles HTTP Range requests for S3. AWS is apparently not following the RFC for range requests and is very, very forgiving, as shown by the added test.
> An [int-range](https://www.rfc-editor.org/rfc/rfc9110.html#rule.int-range) is invalid if the [last-pos](https://www.rfc-editor.org/rfc/rfc9110.html#rule.int-range) value is present and less than the [first-pos](https://www.rfc-editor.org/rfc/rfc9110.html#rule.int-range).
As pointed out by @sjperkins who went through the RFC, the server can ignore the range header for some conditions:
> A server that supports range requests MAY ignore or reject a [Range](https://www.rfc-editor.org/rfc/rfc9110.html#field.range) header field that contains an invalid …
> fix S3 v3 Range handling

- tests/aws/services/s3/test_s3_api.py
When writing the new S3 v3 provider, a lot of new tests have been written to either verify missing cases or tests things that were implemented in moto only.
This PR aims to enable those tests for the current provider, and xfail the ones that are not passing.
Remove all the `skip` pytest markers and go individually over each test to verify if they pass. 
> enable new s3 v3 tests for current provider

- tests/aws/services/cloudformation/resources/test_route53.py
- tests/aws/services/route53resolver/test_route53resolver.py
- tests/aws/services/route53resolver/test_route53resolver.snapshot.json
- tests/aws/templates/route53_recordset_without_resource_records.yaml
As part of our snapshot age project, the goal here is to simply re-validate the route53 integration tests and regenerate the collected snapshots.
- fixed tests where they were failing against AWS and made cleanup of resources more robust.
- updated all snapshots for route53resolver
> Refresh route53 snapshots

- localstack/services/s3/provider.py
- localstack/services/s3/v3/provider.py
- localstack/testing/pytest/fixtures.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
- tests/aws/services/s3/test_s3_api.py
- tests/aws/services/s3/test_s3_api.snapshot.json
It seems I introduced an issue when fixing the `s3_empty_bucket` fixture to force deleting locked objects.
```python
2023-09-08T17:33:09.910 DEBUG --- [  MainThread] localstack.testing.pytest.fixtures : error cleaning up bucket test-bucket-5c896954: An error occurred (InvalidArgument) when calling the DeleteObjects operation: x-amz-bypass-governance-retention is only applicable to Object Lock enabled buckets.
```
It also showed that LocalStack didn't have parity when checking this, and allowed the parameter to be passed if the bucket doesn't have it enabled. Added the fix in LocalStack as well, but this was an issue only when running against AWS (lots of clean up to do 😭)
- added a check in the fixture to check if the bucket can be locked.
- added a test for the fixture, so we're sure …
> fix S3 s3_empty_bucket fixture and add parity

- localstack/services/apigateway/patches.py
- tests/aws/services/apigateway/test_apigateway_common.py
- tests/aws/services/apigateway/test_apigateway_common.snapshot.json
Follow up from #9095
The scenario described by the user was the following:
1. Create api gateway
2. Create api gateway stage
3. Create api gateway stage deployment
4. Create another api gateway stage deployment (which updates the stage itself)
The issue was in the moto implementation: 
```python
if deployment.stage_name and deployment.stage_name in self.stages:
raise StageStillActive()
```
But it didn't check if the actual stage which had the same name was attached to the deployment we were deleting. 
I've created a patch as we don't have any `deployment` operation in our provider at the moment and this is a quick fix, the issue was long running and hindering their Terraform deployments.
Added an AWS test which was reproducing the issue.
> fix APIGW DeleteDeployment to verify if stage is assigned to it

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/integration.py
- localstack/services/apigateway/patches.py
- localstack/services/apigateway/provider.py
- localstack/services/apigateway/templates.py
- localstack/utils/xml.py
- setup.cfg
- tests/aws/services/apigateway/test_apigateway_basic.py
- tests/aws/services/apigateway/test_apigateway_sqs.py
- tests/aws/services/apigateway/test_apigateway_sqs.snapshot.json
Rework this PR to instead of forcing xml to json format exchange, it adds parity to AWS by defaulting SQS responses to JSON. It also works if the request parameter is set to `application/xml`, in that case, the response from the integration is not JSON but XML.
- Applies the same defaults as AWS, the default response being JSON.
- It also adds a basic implementation of `update_integration` and `update_integration_response` just to comply with the tests. A follow-up PR will improve the implementation.
- Snapshot tests and exercise multiple response formats
Adds a snapshot that tackles the customer issue
> add support for xml to json responses

- localstack/cli/localstack.py
- localstack/dev/run/__main__.py
- localstack/dev/run/configurators.py
- localstack/utils/bootstrap.py
- localstack/utils/container_utils/container_client.py
- tests/unit/utils/test_bootstrap.py
We want to make it easier to add customizations when running `localstack start`. For instance, to generalize something like `DNS_ADDRESS`, we could just provide a port mapping for `localstack start`, that allows people to map, say, `127.0.0.1:1053:53/udp`. Similarly, there's now easy way to mount custom volumes into the localstack container other than using `DOCKER_FLAGS`.
This PR adds a `-p` and `-v` flag to `localstack start`, which are the same as the flags used in `docker run`. This is a continuation of #8772
* Add `-p/--publish` and `-v/--volume` flags to `localstack start`
* Re-use and refactor the necessary code from dev configurators (was already there) into the bootstrap `ContainerConfigurators`
* Fixed an issue where volume parsing wasn't working correctly if `:ro` suffix was …
> add container port and volume flags to localstack start

- localstack/testing/snapshots/transformer_utility.py
- tests/aws/services/cloudwatch/test_cloudwatch.py
- tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json
These tests were quite flaky in CI, so I tried to make them a bit more robust now :sweat_smile: 
- Remove all unknown markers and replace with proper markers.
- Any tests that would've been `needs_fixing` have been adapted/fixed to be compatible with AWS.
- Skip `test_put_metric_alarm` instead of xfailing because it always fails with localstack and the test is usually running for 3 minutes.
> Validate and refactor cloudwatch tests

- .circleci/config.yml
- localstack/testing/pytest/marking.py
- tests/aws/scenario/test_apigateway_scenario.py
- tests/aws/scenario/test_bookstore.py
- tests/aws/scenario/test_ecs_scenario.py
In the future we want to experiment more with using only a subset of our integration tests as a sort of acceptance test suite.
Since we want to start early to get a feeling for how well this will work and what we need to look for in potential acceptance test candidates, we're now already starting with a very small subset of tests that are only executed in parallel to the current CI test jobs.
- introduce a new pytest marker `acceptance_test`
- initially this is exposed via our markers as `@markers.acceptance_tests_beta` to communicate more clearly that these tests aren't yet used as the only acceptance tests. (to avoid confusion)
- creates a job in CircleCI to execute all tests 
- tests are currently only executed on the default architecture (amd64) 
- as discussed previously, the tests …
> Set up acceptance test marker & CI job

- localstack/services/cloudformation/engine/template_deployer.py
- localstack/services/cloudformation/resource_provider.py
- localstack/services/iam/resource_providers/aws_iam_policy.py
- localstack/testing/snapshots/transformer_utility.py
- tests/aws/services/cloudformation/api/test_stacks.py
- tests/aws/services/cloudformation/api/test_stacks.snapshot.json
- tests/aws/services/cloudformation/api/test_update_stack.py
- tests/aws/templates/iam_policy_invalid.yaml
- tests/unit/utils/testing/test_snapshots.py
When working on other tasks, I noticed the AWS::IAM::Policy usually fails to clean up leading to a lot of cleanup issues since other resources usually depend on this resource. It seems this was also implemented wrong in the original `GenericBaseModel` version.
- Add proper delete for `AWS::IAM::Policy`
- Add test for a broken delete where resources need to be orphaned to "unblock" the delete.
- Fix transformers, so that it won't try to do a reference replacement with `""` values
> Fix deletion of AWS::IAM::Policy 

- localstack/services/dynamodb/provider.py
- localstack/services/kinesis/provider.py
- localstack/services/opensearch/provider.py
- localstack/services/redshift/provider.py
- localstack/services/s3/v3/provider.py
- localstack/services/stepfunctions/provider.py
- localstack/state/core.py
In the `StateVisitor` implementations that handle cloud pod state, there is currently no way to know which service the `AssetDirectory` being visited belongs to, unlike `AccountRegionBundle` and `BackendDict` which both have a `service_name` attribute.
Knowing the service name for an `AssetDirectory` is required for technical reasons for s3 v3 persistence.
* Make `StateContainer` a protocol and make `service_name` a mandatory attribute
* Refactor all instances of `AssetDirectory` to correctly use the service name
> add service_name attribute to AssetDirectory

- localstack/dev/run/configurators.py
I need to mount plux and localstack-plugin-persistence sources when running persistence tests.
These are two common dependencies maintained by the localstack team so i feel they belong here.
* add utility to make it easier to mount sources into site-packages
* add localstack-plugin-persistence and plux
> add plux and localstack-plugin-persistence to SourceVolumeMountConfigurator

- tests/aws/services/stepfunctions/v2/base/test_base.py
- tests/aws/services/stepfunctions/v2/base/test_base.snapshot.json
Adds tests to fix the behaviour of Result productions, which are treated as static json objects and json paths are never resolved
> [SFN] Minor tests for Results with jsonpath declaration

- localstack/config.py
Using `LAMBDA_DEV_PORT_EXPOSE` within Docker breaks Lambda leading to a connection error because the LocalStack container cannot reach the Lambda container:
```
Failed invocation MyHTTPConnectionPool(host='127.0.0.1', port=58301): Max retries exceeded with url: /invoke (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff40fa18a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
/cc @whummer 
* Remove the internal developer configuration `LAMBDA_DEV_PORT_EXPOSE` from `CONFIG_ENV_VARS`
* Add a code comment to clarify the intent of `CONFIG_ENV_VARS`
> Remove internal developer configuration from CONFIG_ENV_VARS

- localstack/logging/format.py
With https://github.com/localstack/localstack/pull/9084, logs contain the account ID and region from the request context when trace logging is enabled.
However, not all HTTP requests have an AWS context, a la ones made to the health endpoint `/_localstack/health` or stack info `/_localstack/stackinfo`. 
This was caused following:
```
localstack_main  | 2023-09-13T07:59:32.703 DEBUG --- [   asgi_gw_1] l.aws.serving.wsgi         : GET localhost.localstack.cloud:4566/_localstack/health
localstack_main  | 2023-09-13T07:59:32.712 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : GET localhost.localstack.cloud:4566/_localstack/stackinfo
localstack_main  | --- Logging error ---
localstack_main  | Traceback (most recent call last):
localstack_main  |   File …
```
> Fix KeyError in log format for requests without AWS context

- localstack/services/s3/notifications.py
- localstack/services/s3/provider.py
- localstack/services/s3/provider_stream.py
- localstack/services/s3/v3/provider.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
Issues with S3 Website were found from #9017, which showed a deeper issue in our S3 cross/multi account implementation.
`GetBucketWebsite` would return `NoSuchBucket` if a request from account A was done to a bucket in account B, even though you could get an object from account B.
We need to implement proper cross-account access for S3.
Before, if we tried to access a bucket existing in account A from account B, we would get some weird issue, as we got the bucket from moto but we would then access the store from account B, which wouldn't have the bucket properties. We now use the found moto bucket account id and region to fetch the store.
We now use the cross account access for every S3 operation, which will allow us to have some implementation of ACL if not using bucket policies, instead …
> implement S3 cross account across all operations

- localstack/aws/api/s3/__init__.py
- localstack/aws/spec-patches.json
- localstack/services/s3/provider.py
- localstack/services/s3/provider_stream.py
- localstack/services/s3/utils.py
- localstack/services/s3/v3/provider.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
As requested and reported in #8929, we were missing `Content-MD5` validation for `PutObject`, which was implemented in the `legacy` provider.
`ChecksumAlgorithm` or `Content-MD5` allows to verify that the payload sent is properly received in the right shape.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html#checking-object-integrity-md5
This will only concern `PutObject` for now, but many operation have this parameter (I think around 21, some like `PutBucketAcl` for example). 
As we had a look with @alexrashed a long, long time ago, the specs implement some kind of way to know which operations have to have some kind of required checksum.
The end goal would be to have a handler to manage the checksum verification for all operations, except the ones with a …
> implement Content-MD5 check for PutObject

- localstack/http/response.py
- tests/integration/aws/test_app.py
This is in some sense a follow up to #8926. I wanted to use the close callbacks of werkzeug to properly implement the restarting of localstack after extensions have been installed (see ext PR). I noticed this wasn't working because we actually often create new Response objects and then use `Response.update_from` in the handler chain, which didn't copy the internal on close callbacks correctly
* Update our `Response.update_from` method to copy the internal `_on_close` handlers correctly
* Add an integration test to make sure the close callbacks work correctly
> fix Response.update_from to also copy close handlers

- tests/aws/services/resource_groups/test_resource_groups.py
- tests/aws/services/resource_groups/test_resource_groups.snapshot.json
We did not have validated tests for the [ResourceGroups service](https://docs.aws.amazon.com/ARG/latest/userguide/resource-groups.html).
We would like to have more validated tests, especially covering the core operations and functionality (being able to query certain resources which have certain tags, or resources from a CloudFormation stack).
Resources:
- Support resources types: https://docs.aws.amazon.com/ARG/latest/userguide/supported-resources.html#services-sqs
- Type of groups: https://docs.aws.amazon.com/ARG/latest/userguide/gettingstarted-query.html
- Integrations with other services: https://docs.aws.amazon.com/ARG/latest/userguide/integrated-services-list.html
Added AWS validated tests for `ListGroupResources` for tag based queries and cloudformation based queries. One test also …
> add resourcegroups validated tests

- setup.cfg
CI started experiencing a failing unit test for snapshots with the recent `1.6.0` update of `jsonpath_ng`
- pins `jsonpath_ng` to version `1.5.3`
> Pin jsonpath_ng to 1.5.3 to unblock CI

- .github/bot_templates/MARKER_REPORT_ISSUE.md.j2
- .github/workflows/marker-report-issue.yml
- scripts/render_marker_report.py
When trying to open the [issue for the marker report](https://github.com/localstack/localstack/actions/runs/6172856621), we noticed that we're running into the maximum character limit of GitHub issues:
`Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}`
In a previous PR (https://github.com/localstack/localstack/pull/9141) we've reduced the number of marked tests in the report. We're still a bit off our target, but with this PR it should finally fall under the the `65536` character limit and allow us to open the first GH issue for the marker report.
- remove links to files
- shorten `CODEOWNER_MISSING` => `?`
> Slim down marker report issue template rendering

- localstack/aws/protocol/parser.py
- localstack/services/moto.py
- localstack/services/s3/v3/provider.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
This is a follow up from the Werkzeug upgrade, and the moto bump adapting to those changes, following the reported issue #9112
Moto now has a specific handling of special character to maintain compatibility between mocked botocore requests and werkzeuga requests. We've had issues when accessing directly moto's backend to get the key, with the proper key from the request.
I first suspected moto and tried working on a fix there and wrote some tests, but those were passing there, but not in LocalStack.
I've tracked it down to passing the request with `call_moto`, we would use the `request.url`, which is the decoded URL, which moto would then use to create its keys internally. 
Some examples of the issues:
Raw URL: `http://s3.localhost.localstack.cloud:4566/test-bucket-0ff73618/test%2540key/` …
> fix S3 handling of special character and trailing slash

- localstack/testing/pytest/in_memory_localstack.py
With #9139, we introduced a new way to start LS in tests, via a pytest plugin.
However, the hook chosen to start LS, and to check the configuration option, might be executed before the configuration option is set.
The configuration options are set in the `pytest_configure` hook, with the following definition:
```
pytest_configure(config)
Allow plugins and conftest files to perform initial configuration.
This hook is called for every plugin and initial conftest file after command line options have been parsed.
After that, the hook is called for other conftest files as they are imported.
```
In community, this works, as the hook is specified in the initial conftest file, before the pytest_sessionstart hook is executed.
This, however, does not work if the test directory specified is a parent …
> Fix running LS for tests in the new in_memory_localstack plugin

- tests/aws/services/sqs/test_sqs.py
Fixes some of the markers noted in #9147 that were obvious/worked out of the box
* Marked the two multi-account tests as only-localstack, since they require a secondary account/test endpoint strategies
* `test_message_with_carriage_return` seems to work now :-)
> update several SQS test markers

- localstack/testing/pytest/fixtures.py
- tests/aws/services/iam/test_iam.py
- tests/aws/services/iam/test_iam.snapshot.json
Fixes according to #9147.
* Fix easy fixable tests to run against AWS
* Mark tests correctly
* Mark `test_simulate_principle_policy` as needs fixing, as it is wrong
* Allow create_role and create_user fixture to skip users which have already been deleted.
> Set aws marker for all iam service tests

- localstack/aws/connect.py
- tests/unit/aws/test_connect.py
Alternative solution to #9130 , without the json serialization and without a separate cache.
It is not yet clear which approach proves to be the solution we go with, this PR is only for test runs for now.
* Patch botocore config object to be hashable and comparable for equality
* Add tests for caching behavior
* Limit client cache to 256 clients
> Make botocore config object hashable

- localstack/services/sns/provider.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
This is finally fixing SNS Subscribe idempotency and Subscription Attributes validation, reported again with #9154, which was introduced in #8976 and already fixed with #9055. 
This time, I think I've got the logic right, basically SNS will only validate present attributes in the `Subscribe` request. If an attribute is not provided, it won't be replaced by its default value but simply ignored.
This kinda shows that validation is good, but sometimes can be a bit tricky to write tests for, my bad 😬 
This PR introduces the above logic and should fix all subsequent issues. We now check if the attributes is provided, then check if individual validated attributes are present in the request before validating equality with the subscription's.
> fix SNS subscribe idempotency

- setup.cfg
Ext run passing :heavy_check_mark: ( see Ext Integration Tests # 2367 )
cc: @macnev2013
> Bump moto-ext to 4.2.2.post2

- localstack/services/apigateway/exporter.py
- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/provider.py
- tests/aws/services/apigateway/test_apigateway_extended.py
- tests/aws/services/apigateway/test_apigateway_extended.snapshot.json
What started as a quick fix for #9145 got a bit out of hand with the introduction of snapshot test.
This PR fixes the bug mentioned, and extend the behaviour of the OpenAPI Exporter. It introduces more parity and separate clearly both types of exporter (I'm not exactly sure of the split yet and if I like it, but this could be a good intro for the Importer). 
Also introduces one apigateway extension, but this will need to be extended to support almost all of them, same way as the importer. 
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-export-api.html
Fix the bug above by adding safety around getting attributes.
Refactored the importer for better separation of the two types of Exporter, those are pretty close but still quite different in their format, and it's …
> fix apigw import root and extend OpenAPIExporter

- localstack/services/lambda_/invocation/lambda_service.py
- tests/aws/services/lambda_/test_lambda.py
- tests/aws/services/lambda_/test_lambda.snapshot.json
Addresses https://github.com/localstack/docs/issues/785
Related to https://github.com/localstack/localstack-pro-samples/issues/224
The AWS CLI v1 and v2 differ in their Lambda payload encoding and using the wrong command or CLI version causes LocalStack to return a confusing `Internal error while executing lambda` rather than raising an `InvalidRequestContentException`.
This PR fixes the exception type and improves AWS parity of the error message. The detailed parsing message still differs at AWS but that's cumbersome to fix (probably not worth it).
Add an AWS-validated test with two different encoding errors.
> Fix lambda invoke exception with invalid payload

- localstack/config.py
- localstack/services/kinesis/kinesis_mock_server.py
...when it is not the same as the desired log level set in LS_LOG
Kinesis Mock Server Log-Level Logs when consistent with the other logs show when LS_LOG is set to debug is too verbose and so we would like a way to control those logs separately.
Added additional log level control to Kinesis Mock Server.
Tested Locally using the docker image built from source as the base image in our localstack project.
Description of how to test the changes
Enable a Localstack DynamoDB service that utilizes the KINESIS_MOCK_LOG_LEVEL env var and LS_LOG. Set them to be separate values (e.g LS_LOG=debug and KINESIS_MOCK_LOG_LEVEL=error).
> added support for overriding the log level of Kinesis Mock Server

- localstack/aws/app.py
- localstack/aws/handlers/__init__.py
- localstack/aws/handlers/internal.py
- localstack/aws/serving/edge.py
- localstack/runtime/shutdown.py
- localstack/services/infra.py
- localstack/services/internal.py
With providers now depending on other services for their internal functionality, it becomes important that we allow services to continue to use other services during the infra shutdown procedure so they can properly shut down themselves. This means we need to shutdown services *before* the gateway so services can still make internal requests to properly shut down This was previously not possible because of how shutdown handlers were implemented.
This PR adds a band-aid for this issue applied until we complete re-write the `start_infra` procedure.
Moreover, if we shut down the gateway last, then we should be rejecting incoming requests while we're shutting down the infra. This PR adds a handler that implements this logic. It accepts internal requests so internal components can continue …
> fix gateway shutdown procedure

- .github/workflows/tests-podman.yml
This PR deactivates the PR and the push trigger for the podman tests (`.github/workflows/tests-podman.yml`).
These tests have been introduced with #8349, but were never green.
The podman support is currently baked into the `CmdDockerClient` which makes it hard to skip the right tests based on a skip marker.
This is why I would like to deactivate the PR and push trigger for now, until we:
- Refactor the Docker client such that the Podman Docker client is in a separate class.
- The tests which are not working yet (because the support has not been enhanced wide enough), are skipped for the podman tests such that they can actually become green.
However, the workflow will not be disabled and can be triggered whenever you would like to execute them manually.
Delete the `pull_request` and `push` …
> deactivate PR and push trigger for podman tests

- localstack/dns/server.py
- localstack/services/lambda_/invocation/docker_runtime_executor.py
- tests/aws/services/lambda_/test_lambda_developer_tools.py
We want to enable our DNS integration for all lambda images. In community we only forward all subdomains of `localhost.localstack.cloud` to LS, which is already helpful when using lambdas to connect to returned endpoints (e.g. apigateway endpoints).
Also, the host mode version is currently broken, so this has to be fixed.
* Fix host mode DNS by creating a new server class for dns servers running in a separate (sudo) process. It is not possible to interact with it programatically yet, but it now it does not raise errors when calling DNSServerProtocol methods
* Set the DNS in lambda, if no other LAMBDA_DOCKER_DNS is set.
> Adopt lambda dns setting, fix dns in host mode

- localstack/services/lambda_/invocation/counting_service.py
- tests/aws/services/lambda_/test_lambda.py
A flaky Lambda test occasionally blocks the pipeline. 
Thank you @bentsku for raising this https://localstack-cloud.slack.com/archives/C02U7DN1B4M/p1695076802171769
* Increase reserved concurrency in test case
* Document race condition
* Add extra debug logging for concurrency exceptions
a) The safest fix is to increase ReservedConcurrentExecutions=3 but then we only occasionally test the border case.
b) We could slow down the test and use sleeps to have a high likelyhood of succeeding
c) We separate the mixed async/sync invoke into a separate test case (or after asserting the logs).
> Fix flaky lambda concurrency test

- localstack/aws/api/ram/__init__.py
- localstack/services/providers.py
- localstack/services/ram/provider.py
- tests/aws/services/ram/test_ram.py
- tests/aws/services/ram/test_ram.snapshot.json
This PR introduces the Resource Access Manager (RAM) service. RAM is an alternate way to grant access to principals for AWS resources.
LocalStack allows unrestricted cross-account and cross-region access (unless IAM enforcement is turned on) so this service is redundant. The primary use-case is to let users run and test their IaC workflows with minimal changes.
cc: @cabeaulac 
This is a very basic provider configured to fall back on Moto.
Currently following operations will be supported:
- CreateResourceShare
- UpdateResourceShare
- DeleteResourceShare
- GetResourceShares
- EnableSharingWithAwsOrganization
Includes a basic sanity test.
Closes: https://github.com/localstack/localstack/issues/7198
- Update aws-cli local to support this endpoint
- Update docs
> Introducing Resource Access Manager (RAM)

- localstack/http/asgi.py
This PR fixes a cosmetic error when a client unexpectedly closes the connection, because h11 would try to send a response with a predefined content length, even though the connection has been closed and there's no body left to send.
This can be reproduced f.e. if you exploit the initial service catalog cache building (which takes ~1.5 seconds):
- Start a bash which fires health requests to the (not yet running) LocalStack instance:
```
until curl --fail --silent --max-time 1 http://localhost:4566/_localstack/health; do sleep "0.1"; done
```
- Remove existing service catalog caches:
```
sudo rm -rf ~/.cache/localstack/volume/cache/
```
- Afterwards start LocalStack:
```
localstack start
```
- The following error will be logged:
```
2023-09-20T14:01:05.126 DEBUG --- [-functhread6] …
```
> fix h11 LocalProtocolError on connection close by client

- setup.cfg
Recent release `4.19.1` of `jsonschema` broke our pipeline due to our dependency on `openapi-schema-validator` (via moto).
Upstream issue: python-openapi/openapi-schema-validator#131 .
* Pin `jsonschema` to 4.19.0 or lower
> Fix build failures by pinning jsonschema<=4.19.0

- localstack/services/sns/provider.py
- tests/aws/services/sns/test_sns.py
These issues were reported in our community slack channel and converted into an issue: #9173 
We wouldn't check the endpoint status when publishing, and we had an incomplete fix for the `CreatePlatformEndpoint` idempotency, which led to an `skip` SNS test. 
- Properly return the `EndpointArn` when calling `CreatePlatformEndpoint` multiple times with the same `CustomUserData` or no user data, and return the proper exception when the `CustomUserData` is different ("InvalidParameter") 
- Properly validate the endpoint status before publishing and raise an exception if the endpoint is disabled. 
As always, we cannot AWS validate those because we need real credentials to a register mobile app in GCM (Firebase) or Apple for example to set up a test case. This is always in the backlog, and would …
> fix CreatePlatformEndpoint idempotency and Publish to mobile endpoint when disabled

- bin/release-helper.sh
Closes #9196 
Update `bin/release-helper.sh` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
Replace deprecated command with environment file.
**AS-IS**
```shell
function print_github_outputs() {
echo "::set-output name=current::${CURRENT_VER}"
echo "::set-output name=release::${RELEASE_VER}"
echo "::set-output name=develop::${DEVELOP_VER}"
echo "::set-output name=boundary::${BOUNDARY_VER}"
}
```
**TO-BE**
```shell
function print_github_outputs() {
echo "current=${CURRENT_VER}" >> $GITHUB_OUTPUT
echo "release=${RELEASE_VER}" >> …
```
> replace deprecated command with environment file

- localstack/services/lambda_/lambda_executors.py
I am fixing the issue in Step Functions when a Lambda function raise an exception without arguments, like: `raise ValueError()`.
Currently, the code fails in this case trying to get the error message to propagate and make controller upstream time out.
Address #9169
Patch the behavior of retrieving the error message from the exception during errors in the lambda invoked.
Just create a step function which lambda perform `raise ValueError()`
Now the SFN execution wont time out.
What's left to do: Nothing
> Fix handling of exceptions without arguments in legacy provider with local executor

- setup.cfg
Ext integration passing :heavy_check_mark:  See Ext Integration Tests # 2467 
Closes: https://github.com/localstack/localstack/issues/8550
> Bump moto-ext to 4.2.3.post1

- localstack/services/plugins.py
For legacy reasons, we used the `local_api_checker` as default health check. This made sense when we had backends running on different ports, but now almost all providers run in memory and not as backends, and those that require backends (like dynamodb), aren't considered anymore through the default `local_api_checker` health check (since we basically just call `:4566`).
Basically, doing health checks in this way makes no sense any more, and we can evaluate whether the concept as such makes sense and if so what we need to do to perform meaningful health checks.
I've seen errors related to these health checks in logs recently, and I think this is a good opportunity to get rid of them.
* When using `Service.for_provider` (which is done in most cases), disable the health check
> disable health check for default service providers

- .circleci/config.yml
- scripts/metrics_coverage/diff_metrics_coverage.py
With the introduction of the acceptance test suite in #9045 we started collecting metrics as well. 
This PR aims to provide the first prototype to quickly glance through the collected metrics.
Currently we have two kind of metrics:
- code coverage
- api coverage
In the future those metrics are intended to help service owners to choose tests that should be part of the acceptance test suite. 
The code coverage is collected using the pytest plugin `coverage`, and results in a sqlite database added as artifact in the `report` job. 
Code coverage for the "normal" integration test is already reported to coveralls.
In order to get an overview about the acceptance coverage and the diff, we create two html reports, using [pycobertura](https://github.com/aconrad/pycobertura):
* …
> CirecleCI: add report for acceptance and diff coverage

- localstack/cli/localstack.py
While working on #9210, I noticed that `localstack ssh` had some wonky terminal behavior.
I couldn't use CTRL+A, CTRL+E, CTRL+R and other control sequences correctly. New lines were also added twice.
It looks like the `tty=True` option of `run` doesn't really work correctly. <strike>For #8994 I added a `run_interactive` method that is a much simpler implementation of running an interactive command in a subprocess.</strike> Using `os.execlp` (based on @dfangl's suggestion), is much simpler. This works much better now:
* Use `run_interactive` for `localstack ssh`
> use run_interactive for localstack ssh to fix tty issues

- localstack/services/providers.py
- localstack/services/s3/legacy/s3_starter.py
* With 1.?, the new S3 `v2` provider became available as opt-in.
* With 1.4, the legacy `v1` provider was deprecated and we encouraged users to opt-in to our new S3 `v2` provider.
* With 2.0, the current S3 provider `v2` became the default implementation https://github.com/localstack/localstack/pull/6724.
* With 2.3, we add removal warnings in the old `v1` provider (this PR) and the new native S3 provider `v3` becomes available https://github.com/localstack/localstack/pull/8785.
* With 3.0 the old (v1) provider will be removed completely and the new native S3 provider `v3` becomes the default.
* With 3.1/3.2? (TBD), the current S3 provider `v2` provider will be deprecated
* With 4.0 the current S3 provider `v2` will be removed completely.
Add a log warning when the legacy S3 v1 provider …
> Add S3 deprecation warnings

- tests/aws/services/acm/test_acm.py
This small PR fixes ACM tests so that they correctly assert ARNs when resources are created in a non-default account ID.
> ACM: Fix ARN assertions when testing in non-default account

- setup.cfg
Final bump ahead of v2.3 release
Ext Integration Tests # 2494 (seems to be a flake)
```
2023-09-25T10:01:44.2398121Z =========================== short test summary info ============================
2023-09-25T10:01:44.2398381Z FAILED tests/aws/services/rds/test_rds.py::TestRdsMysql::test_data_api[True]
2023-09-25T10:01:44.3346634Z [31m= [31m[1m1 failed[0m, [32m463 passed[0m, [33m80 skipped[0m, [33m595 deselected[0m, [33m45 xfailed[0m, [33m6 xpassed[0m, [33m336857 warnings[0m, 
```
cc: @giograno @sannya-singal 
Closes https://github.com/localstack/localstack/issues/8984
> Bump moto-ext to 4.2.4.post1

- localstack/cli/localstack.py
As the number of CLI commands increases, it becomes harder to separate basic from advanced functionality that is part of our paid offering. This PR introduces the notion of command categories into our `localstack` command group, that allow us to visually separate the commands.
The current implementation is very rudimentary, with grouping commands manually with a list of commands. I know this is not great, but it's the easiest way to get started without having to introduce additional concepts in ext for now.
* Rename the `ExceptionCmdHandler` to a more generic `LocalStackCliGroup`
* Overwrite the `format_commands` method of `click.Group` with our own implementation that adds categories
> introduce CLI command categories to improve help display

- localstack/config.py
#7906 introduced the `LOCALSTACK_CLI` env variable, which is only used as a workaround to indicate that we are currently in a CLI environment (other than an actual runtime environment).
With #8307, we removed the install-dependency on `localstack_client`.
We added a global env prefix `LOCALSTACK_`. All environment variables with this prefix will be added to the container (no matter if they are listed in the `CONFIG_ENV_VARS` global variable). The intention for that is that we have a simple way of adding new variables which should be forwarded to a container without maintaining this global list.
Unfortunately, since #8307 is merged, we set the `LOCALSTACK_CLI` also in LocalStack containers started by the CLI, which shouldn't be set.
This PR fixes this.
- Explicitly exclude `LOCALSTACK_CLI` …
> avoid setting LOCALSTACK_CLI in the container

- .github/workflows/pr-welcome-first-time-contributors.yml
Unfortunately, #9068 broke the "Welcome First Time Contributors" GitHub action.
This PR upgraded the action from GitHub Script v2 to v6.
With GitHub Script v5, there were some breaking changes related to the REST operations on the `github` object.
More details can be found here: https://github.com/actions/github-script#breaking-changes-in-v5
- Use `github.rest.<rest-action>` instead of `github.<rest-action>`.
/cc @HarshCasper
> fix welcome action by upgrading to github-script v6

- localstack/deprecations.py
- localstack/services/lambda_/lambda_starter.py
* With 1.3, the new Lambda `v2` provider became available as opt-in.
* With 1.4 (ish), the legacy `v1` provider was deprecated and we encouraged users to opt-in to our new Lambda `v2` provider.
* With 2.0, the new lambda provider `v2` became the default implementation https://github.com/localstack/localstack/pull/6724.
* With 2.3, we add removal warnings in the old `v1` provider (this PR). We also ship the Lambda invocation loop rework https://github.com/localstack/localstack/pull/8970 (re-write of data plane).
* With 3.0 the old (v1) provider will be removed completely.
Add a log warning when the legacy Lambda v1 provider is used. Only logged during initialization (`on_after_init`) for people using the legacy Lambda service.
Pro-active warnings at LocalStack startup:
* Do we want to …
> Add removal warning for legacy lambda provider

- localstack/services/stepfunctions/provider.py
* With **2.3** we want to start advertising the new `v2` stepfunctions provider more broadly and also let users know that with the next major release, the defaults will change. Ideally anyone using stepfunctions should start to at least opt-in at some point and make sure their current applications are still working with `v2`.
* With **3.0** the old (`v1`) provider will become deprecated and `v2` will become the new default. Users can still opt-in to the old `v1` provider.
* With **4.0** the old (`v1`) provider will be removed completely.
- Log a warning when the stepfunctions `v1` provider is used. Only logged during initialization since a lot of people might not be affected at this point if they're not using the stepfunctions service at all.
We should also make sure our language is …
> add warning about future deprecation of stepfunctions v1 provider

- .circleci/config.yml
- .github/workflows/asf-updates.yml
- .github/workflows/marker-report-issue.yml
- .github/workflows/marker-report.yml
- .github/workflows/tests-podman.yml
- .github/workflows/tests-pro-integration.yml
- Dockerfile
- Makefile
- localstack/dev/run/paths.py
- localstack/utils/server/proxy_server.py
- setup.cfg
- tests/aws/services/lambda_/test_lambda.py
- tests/unit/test_proxy.py
This PR contains all changes necessary to upgrade our Python version for the runtime from 3.10 to 3.11.
- Update all CircleCI runners (which use Python 3.11 by default).
- Update all GitHub actions to install Python 3.11 instead of Python 3.10.
- Install `libsnappy-dev` instead of `libsasl2-dev` when running against Pro (see changes there for a detailed explanation).
- Update the dockerfile base image to the latest sha digest of Python 3.11.5.
- Update all references to virtual environments which contain the Python version (f.e. `/usr/lib/localstack/python-packages/lib/python3.11/site-packages`).
- Remove the SSL proxy (it's not used in Community anymore and the used library - `python-proxy` - is not maintained and not compatible with 3.11).
- Update dill to a Python 3.11 compatible …
> Update to Python 3.11

- localstack/aws/handlers/partition_rewriter.py
- tests/unit/test_partition_rewriter.py
#9064 introduced the MD5 checks for S3's PutObject operation.
Until now, the ARN Partition Rewriting did not update the MD5 hashes in requests.
This now causes issues with the MD5 check in S3, since the checksum is verified, but the content is maybe modified due to the rewriting.
- Replaces the `Content-MD5` header with a new value in case it is set.
> fix S3 PutObject with MD5 and enabled ARN Partition Rewriting

- localstack/config.py
- localstack/services/edge.py
This is basically a continuation of #8948 and #9012.
We basically reintroduce hypercorn binding directly to the privileged ports, if run as root.
Additionally, we check the `sys.net.ipv4.ip_unprivileged_port_start` kernel parameter, to check the port start of unprivileged ports.
We will need to provide proper paths of error handling, to avoid #9012 again.
* Bind hypercorn to privileged ports if root
* Check the actual unprivileged port start instead of assuming 1024.
> Let hypercorn listen directly to privileged ports if run as root

- localstack/services/apigateway/helpers.py
- tests/aws/services/apigateway/test_apigateway_basic.py
- tests/aws/services/apigateway/test_apigateway_common.py
- tests/aws/services/apigateway/test_apigateway_extended.py
- tests/unit/test_apigateway.py
As reported in #9207, we did not properly take into account the request method to retrieve the associated APIGW resource. We would take into account the path only, and then retrieve the method. 
We now take the method into account, and don't match a path if it doesn't contain the request method or `ANY`. Added tests validating this behaviour against AWS, and adapted the unit tests too.
I suppose a bigger refactor would be nice around this, but this seemed like a rather urgent thing to fix. I'll take this into the APIGW backlog together with the more global refactor around the invocation. 
Sneaked a quick fix regarding fixture usage and cleanup for some export tests importing API.
> fix APIGW matching with {proxy+} and methods

- localstack/services/apigateway/helpers.py
- localstack/services/apigateway/invocations.py
This issue was reported in a support case, the `pathParams` field was not available in the authorizer context. After checking, it seems we only resolved and added to the invocation context at the invocation step, which is executed after the authorizer.
~Beware, this PR is on top of #9208 because the new tests are using this routing to test different scenarios with the path.~
Updated a util to set the context as soon as we have the resource details (so that we're able to resolve the path parameters), and removed the resolving in the integration step.
> fix apigw pathParameters context resolving before authorizer run

- tests/unit/aws/test_service_router.py
This PR fixes the service router unit tests by excluding a newly added AWS Bedrock (which was added to `botocore` with https://github.com/boto/botocore/commit/730bfe40b1431f229d68f0d525756aaf67742a80)
Exclude bedrock for now from the service router testing.
> fix service router test by excluding bedrock

- localstack/config.py
- localstack/dev/run/__main__.py
- localstack/utils/diagnose.py
- tests/aws/conftest.py
- tests/integration/conftest.py
- tests/integration/utils/test_diagnose.py
- tests/unit/test_config.py
If `LOCALSTACK_HOST` is set to include port 443, and `GATEWAY_LISTEN` is not set, in -ext we by default add port 443 to the list, so `GATEWAY_LISTEN` becomes:
```
GATEWAY_HOST = [
HostAndPort("0.0.0.0", 443),
HostAndPort("0.0.0.0", 443),
]
```
Hypercorn then tries to bind to the port twice and crashes.
* Introduce the concept of a `UniqueHostAndPortList` - see the docstring for guarantees
* Configure the dev container to modify the edge port config
> Ensure unique addresses for GATEWAY_LISTEN

- localstack/services/sns/publisher.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
As reported with #9261, we would not properly filter for the `null` value in a FilterPolicy. This is because we set the value to `None` if it didn't exist. We luckily have a field to indicated the presence of the field or not `field_exists`. 
Add the check for the `field_exists` before comparing the value with the condition.
Added a snapshot tests for validating this use-case. 
_closes #9261_
> fix SNS FilterPolicy with null value

- setup.cfg
PR builds started failing yesterday. Example: https://app.circleci.com/pipelines/github/localstack/localstack/18636/workflows/bf96fc58-330d-4526-8720-fac54a29c45e
I had a hunch it may be Werkzeug again, since they released 3.0 the other day: https://github.com/pallets/werkzeug/releases/tag/3.0.0. I haven't had time to investigate yet, but assume it has something to do with deprecated code they removed.
* Constrain werkzeug version to <3.0
> exclude werkzeug 3.0

- .github/workflows/stale-bot.yml
- .github/workflows/sync-labels.yml
- .github/workflows/sync-project.yml
We are currently working on unifying processes across multiple repos in the GitHub organization.
For this purpose, we created an internal repo with some shared workflows.
This PR onboards `localstack/localstack` to these shared workflows.
- Add the new "Sync Labels" workflow.
- This means that labels defined in our shared repo are automatically added in this repo.
- This allows using a specific set of labels for other automations (like the project status sync) in multiple repos.
- The workflow allows defining multiple "categories", which is a way in defining different sets of labels for different kinds of repos.
- "Sync Project Cards" basically just migrates the existing code to the shared workflow.
- However, the workflow has been extended a bit such that issues are also automatically …
> add label sync, migrate workflows to shared workflows

- localstack/dev/run/__main__.py
- localstack/utils/bootstrap.py
It is sometimes nice to attach a remote debugger to a running container. For this we can use the `DEVELOP=1` flag with the CLI, which
* installs `debugpy` into the container before infrastructure startup, and
* publishes port 5678 (the default [DAP](https://microsoft.github.io/debug-adapter-protocol/) port) to the host.
These two commands _can_ be added to the debug script, however it is marginally annoying. And of course we know that developers hate to be _mildy_ annoyed... 😂
* Add a `--develop/--no-develop` flag to the CLI which performs the two above steps
```
python -m localstack.dev.run --develop`
```
should allow for remote debugging via the DAP protocol. Specifically it should:
* install debugpy into the container, and
* publish port 5678
> Add develop mode to dev script

- localstack/services/events/provider.py
- tests/aws/services/events/test_events.py
- tests/aws/services/events/test_events.snapshot.json
- tests/aws/test_integration.py
While using event bus, I noticed that specifying invalid rule expressions did not create the correct error response.
There was also a TODO related to us allowing `rate(1 minutes)` (value 1 with plural unit) which is for some reason not allowed in AWS. This may have some implications on user code.
* Added proper handling and an AWS validated test
* Added [weird plural/singular handling of rate units](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-rate-expressions.html)
* Fixed all occurrences of invalid rates
* drive-by validated a few other tests
> add error handling for Events.PutRule

- tests/aws/services/cloudwatch/test_cloudwatch.py
The  `tests.aws.services.cloudwatch.test_cloudwatch.TestCloudwatch.test_get_metric_data` test has been flaky in the past. This PR aims to fix the test to remove this flakiness.
Example flake: https://app.circleci.com/pipelines/github/localstack/localstack/18675/workflows/963c77f7-1832-4350-9fac-4cc9837e58c0/jobs/144301
- Check the sum of all values instead of only the first value, since the two `put_metric_data` entries might end up in two different 60s metric statistics "buckets"
To trigger the case where multiple "buckets" exist, i.e. where the array would be [18,23] instead of [41], simply add a time.sleep(60) like this:
```python
aws_client.cloudwatch.put_metric_data(
Namespace=namespace1, MetricData=[dict(MetricName="someMetric", Value=23)]
)
time.sleep(60) …
```
> fix flaky get_metric_data cloudwatch test

- localstack/aws/forwarder.py
- localstack/aws/serving/wsgi.py
- localstack/http/router.py
- localstack/services/lambda_/lambda_api.py
- setup.cfg
This PR upgrades Werkzeug to version 3 and fixes some issues caused by the removal of deprecations (or other breaking changes with version 3).
This PR removes the pin (avoiding the upgrade) added with https://github.com/localstack/localstack/pull/9272.
- Updates minimum version in `setup.cfg`.
- Fixes some issues which came up with the new major release:
- Decode headers when populating the WSGI request headers from the ASGI requests and when forwarding requests.
- Werkzeug's `Headers` object raises a `BadRequestKeyError` if a key is not of type `str`.
- See https://github.com/pallets/werkzeug/commit/5ff0a573f4b78d9724f1f063fb058fd6bc76b24d.
- Removes the usage of `charset` and `encoding_errors` on the `Map` (they have been removed).
- Also see …
> upgrade werkzeug to version 3

- Dockerfile
In the process of resolving some CVEs, we detected that the Docker image contains `python3.9`, which gets pulled in transitively from the `nodejs` package:
```
$ docker run -it --rm --entrypoint= localstack/localstack which python3.9
/usr/bin/python3.9
```
We should try to eliminate this 3.9 Python installation, to resolve CVEs, and also to slightly reduce the image size.
Update Dockerfile to skip installation of `python3.9` packages. We achieve this by downloading the `*.deb` package for nodejs, then extracting the `control.tar.xz` file from it, and updating the dependencies in the `control` file to remove the `python3` dependency. 
Below is the content of the `control` file, prior to replacing its content via `sed` (`python3` is then removed from the `Depends` list): 
```
Package: …
```
> avoid installation of python3.9 in docker image

- localstack/dns/server.py
- tests/bootstrap/test_container_listen_configuration.py
- tests/bootstrap/test_dns_server.py
The user may specify a custom value of `LOCALSTACK_HOST` which is the domain name of the LocalStack container from the outside. This will not work however in created compute environments, or external docker containers since we only resolve `localhost.localstack.cloud` to the LocalStack container.
- Bind LOCALSTACK_HOST to LocalStack IP address
- Update bootstrap tests to use `stream_container_logs` and `ContainerConfigurators`
> Resolve LOCALSTACK_HOST to the LocalStack container

- tests/aws/services/lambda_/test_lambda_api.py
- tests/aws/services/lambda_/test_lambda_developer_tools.py
- tests/aws/services/lambda_/test_lambda_legacy.py
- tests/aws/services/lambda_/test_lambda_performance.py
- tests/aws/services/lambda_/test_lambda_runtimes.py
Companion PR: https://github.com/localstack/localstack-ext/pull/2159
Fix AWS markers for Lambda according to marker report https://github.com/localstack/localstack/issues/9147
Grepped for some extra occurrences not covered in the marker report.
* Set markers to `localstack_only` where applicable
* Remove false positives and rename fixtures or inner asserts to clarify their intent
* Leave some to `unknown` scheduled to be removed at 3.0 (not worth fixing/testing)
> Screen AWS markers for Lambda

- localstack/dev/run/configurators.py
Currently, in the dev script, we only mount python modules which are in there own subfolder.
However, the assumption that all dependencies are located in a subfolder does not hold:
For example, `nest-asyncio` is only one file, and is not located in a separate folder in `site-packages`. (This is a dependency for serverless tests in -ext, and without it, test collection fails).
We should therefore also mount python files in `site-packages`, unless they start with `__` (sometimes linked editable installs have a python finder file like this: `__editable___localstack_core_2_2_1_dev0_finder.py`).
* Mount files from `site-packages` as dependency as well, unless they start with a dunder
> Allow --mount-dependencies for python modules which are not in a separate directory

- localstack/services/internal.py
- localstack/utils/analytics/metadata.py
- tests/integration/services/test_internal.py
- tests/unit/services/test_internal.py
Several other localstack systems need access to basic information about the running instance beyond the health status. Much like `docker info`, this new endpoint aims to provide this information.
Example:
```json
{
"version": "2.3.3.dev:c77b830",
"edition": "pro",
"is_license_activated": true,
"session_id": "1830110c-6e4d-4256-9bc0-9008b8c5b6b9",
"machine_id": "4256a311839b",
"system": "linux",
"is_docker": true,
"server_time_utc": "2023-10-04T14:59:40",
"uptime": 120
}
```
* Add a `/_localstack/info` endpoint
* Add two new metadata methods: getting the edition (from files we create in the Dockerfiles), and checking whether license activation has been successful
* Add the `edition` key also to the health endpoint, since that has long since been requested
* Add the output of info also to …
> add /_localstack/info endpoint for basic infos about the instance

- localstack/services/opensearch/resource_providers/aws_opensearchservice_domain.py
- tests/aws/services/cloudformation/resources/test_opensearch.py
- tests/aws/services/cloudformation/resources/test_opensearch.snapshot.json
- tests/aws/templates/opensearch_domain_alternative_types.yml
The example from the resource type cdocumentation cannot be deployed in LocalStack due to the lack of some extra type conversions for some parameters.
Extra type validations and transformations in the resource provider
The added test uses the template from the documentation
> Type conversion for AWS::OpenSearch::Domain

- localstack/services/s3/v3/provider.py
- tests/aws/services/s3/test_s3.py
- tests/aws/services/s3/test_s3.snapshot.json
As reported in https://github.com/localstack/localstack/issues/6659#issuecomment-1749013552, calling `HeadObject` on a an object with `ChecksumMode=ENABLED` will raise an exception. I totally missed it when copy/pasting the implementation from `GetObject`, because of a `#noqa` put there because of typing (dynamic key value inside the `*Response` object). 
Fixed the line to use the object checksum instead of a non-existent variable.
I've also removed all the `noqa` from the provider because some type warnings are better than fully failing that this.
> fix S3 v3 HeadObject with checksum

- localstack/aws/api/ec2/__init__.py
- localstack/aws/api/route53/__init__.py
- localstack/aws/api/sts/__init__.py
A recent botocore upgrade seems to have introduced some build failures https://pypi.org/project/botocore/1.31.61/
```
E             File "/opt/code/localstack/localstack/aws/api/core.py", line 160, in operation_marker
E               return fn(*args, **kwargs)
E                      ^^^^^^^^^^^^^^^^^^^
E           TypeError: Route53Api.list_hosted_zones() got an unexpected keyword argument 'hosted_zone_type'
.venv/lib/python3.11/site-packages/botocore/client.py:980: ClientError
```
Regenerating the APIs manually to get the build unblocked.
* regenerate ASF APIs
> regenerate ASF stubs for botocore 1.31.61 upgrade

- localstack/services/lambda_/provider.py
Addresses a support request.
Fixes a bug where fetching external layers broke when using multiple versions of the same layer.
Handle multiple versions of the same layer when fetching external layers.
Added in companion ext PR: https://github.com/localstack/localstack-ext/pull/2163
The logic starts to get quite complex here. Some thoughts for the future:
* a) Using an internal service call with added cross-account support could simplify this logic here quite a bit. This requires IAM support, which was not present at the moment we implemented this initial version.
* b) The layer fetcher could return a layer version. However, this would break up the logic between community and ext.
> Fix layer version handling for external Lambda layers

- .github/workflows/tests-cli.yml
Python 3.12 has been released on 2nd of October 2023.
We got an issue report explaining that the CLI installation is not working correctly (which is not reproducible).
But this is a good reminder to update the CLI tests to include the new version in the tests.
- Add Python 3.12 to the list of Python versions to test the CLI against.
/cc @thrau
> add Python 3.12 to the CLI test version matrix

- localstack/services/sns/provider.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
As reported in #9306, we would raise a 500 when the topic is not a properly formed ARN. This exception comes from moto, and should be handled there as well. In the meantime, we can fix it with our utils. 
Moved up our method to get the topic, which will raise the proper exception if there's an issue before calling moto. Added a test with a malformed arn to validated the behaviour.
> fix GetTopicAttributes exception when arn is malformed

- localstack/services/cloudformation/engine/template_utils.py
- tests/aws/services/cloudformation/engine/test_conditions.py
- tests/aws/templates/conditions/conditional-with-select.yml
As shown in the issue #9300 CFn should be able to support using a `!Select` function in a Conditional. 
The `resolve_condition` function now also supports a case for `Fn::Select`. According to the[ function documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-select.html), the select can also resolve references. 
Added a simplet AWS validated test to confirm the expected behaviour.
> Add support for fn::select in conditional

- localstack/aws/protocol/serializer.py
- setup.cfg
While working on the integration of Python 3.12, I realized that we still have a dependency on the legacy Python AWS SDK [`boto`](https://github.com/boto/boto) (not to confuse with [`boto3`](https://github.com/boto/boto3)).
This PR removes this direct dependency.
- Removes the only direct import from the legacy `boto` (which was a mistake anyways)
- Removes `boto` as an explicit direct dependency of `localstack-core`.
> remove dependency on legacy boto

- tests/aws/services/transcribe/test_transcribe.py
This PR fixes test execution error when a non-default `TEST_AWS_REGION_NAME` is used.
This happens because S3 CreateBucket requires `LocationConstraint` information when any region other than `us-east-1` is used. Our `s3_create_bucket` fixture takes care of such situations.
Just use the `s3_create_bucket` fixture to create the S3 bucket instead of the direct S3 CreateBucket.
> Use region-agnostic bucket create for Transcribe tests

- localstack/services/dynamodb/provider.py
- localstack/services/dynamodb/utils.py
- tests/unit/test_dynamodb.py
Fixes #9243 
* Adds a new method for internal cache invalidation to remove cached DynamoDB table schemas
* Adds cache invalidation calls when running update table calls against DynamoDB
> Adds internal cache invalidation on DynamoDB table update operations

- localstack/services/sns/publisher.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
This issue was reported in our Community Slack channel.
When trying to connect our SNS implementation to [Opsgenie](https://www.atlassian.com/software/opsgenie), a user encountered an 422 error.
After looking online, I fell on this post: https://community.atlassian.com/t5/Opsgenie-questions/Mimicking-CloudWatch-SNS-notification-in-Opsgenie/qaq-p/1886688, which indicates it should be possible.
It seems the headers are important for them to process our requests, so I've updated on our test to properly check that the header format was right.
We can also read about them here: https://docs.aws.amazon.com/sns/latest/dg/sns-message-and-json-formats.html#http-header
The most important for this specific integration seems to be:
`Content-Type: text/plain; charset=UTF-8`
And we had `Content-Type: …
> fix SNS headers when publishing to HTTP endpoints

- localstack/services/sns/publisher.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
This issue has been reported in our Community Slack.
The following SNS `FilterPolicy` with the `FilterPolicyScope` set `MessageBody` was not working like AWS:
`"FilterPolicy": "{\"detail.eventType\": [\"ride.requested\"]}"`
Note the `.` in the field name, which is very important.
The event that should pass and work this policy looks like this:
```json
{
"version": "0",
"id": "6a7e8feb-b491-4cf7-a9f1-bf3703467718",
"detail-type": "ride.requested",
"source": "lambda",
"account": "111122223333",
"time": "2017-12-22T18:43:48Z",
"region": "us-west-2",
"detail": {
"eventType": "ride.requested",
"data": "{}"
}
}
```
After checking with AWS, it seems that indeed, that event should work, even if it seems a bit counter-intuitive.
My first idea was to use JSONPath, but what AWS is doing is every …
> fix SNS MessageBody filtering with `.`

- localstack/services/cloudformation/api_utils.py
- tests/aws/services/cloudformation/api/test_templates.py
- tests/aws/services/cloudformation/api/test_templates.snapshot.json
Follow up from #9312 and following up a Community Slack issue, it seems the new validation added was missing one exception handling when the S3 key would be containing slashes.
For example:
`awslocal cloudformation create-stack --stack-name vpc-us-east-1 --template-url s3://cloudformation-templates/aws-account-cfn/vpc.json`
Is raising:
```python
File "/opt/code/localstack/localstack/services/cloudformation/api_utils.py", line 55, in get_template_body
result = client.get_object(Bucket=parts[0], Key=parts[2])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
return self._make_api_call(operation_name, kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> follow up on CloudFormation template URLs S3 URI

- localstack/testing/scenario/provisioning.py
In preparation for the CDK testing workshop we noticed a few issues with the tooling that this PR now addresses.
- AWS seems to have changes the `StatusReason` when creating a change set without changes recently. Since this seems extremely flaky, I've decided to remove this check and always assume on update that a failure can be ignored.
- Re-use stack event outputs for failed stack deployments from deploy_cfn_template fixture
- Fix typing of InfraProvisioner.provisioner to be compatible with pycharm => intellisense should work now
> Improve CDK test tooling with better error reporting and typing

- localstack/services/cloudformation/models/s3.py
When writing the workshop sample we noticed that it didn't create the necessary event bridge notification configuration.
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-event-notifications-eventbridge.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig-eventbridgeconfig.html
- Adds support for `EventBridgeConfiguration` to legacy `AWS::S3::Bucket` resource provider
> fix missing support for eventbridge notifications in legacy AWS::S3::Bucket

- localstack/services/sns/constants.py
- localstack/services/sns/provider.py
- tests/aws/services/sns/test_sns.py
- tests/aws/services/sns/test_sns.snapshot.json
This PR will add a new internal endpoint to be able to fetch subscription tokens used to confirm a subscription.
In case of email and most importantly HTTP(S) subscriptions, a special message is sent to the subscriber with a link to confirm the subscription so that it will receive the messages afterwards.
However, when working with external integrations (like Opsgenie: https://support.atlassian.com/opsgenie/docs/integrate-opsgenie-with-incoming-amazon-sns/), the link sent will most probably be a link to your own localhost (you could always use `HOSTNAME_EXTERNAL` and some way to link it to your own computer, but it's not a given the external integration will go on a link which is not AWS related).
Instead, we could expose the sent token with the internal endpoint, so that you can manually …
> add SNS internal endpoint to fetch SubscriptionTokens

- localstack/dev/run/__main__.py
When using LocalStack extensions, the CLI can be used to automatically mount the code in the correct place in the container to run dev extensions. This removes the possibility of making changes to LocalStack internals (e.g. to prototype any changes/monkeypatches that are required).
* Add a `--dev-extensions` flag which performs the same steps as the CLI when
* `EXTENSION_DEV_MODE=1` is supplied
* pro is enabled
> Dev script can load extensions

- .github/dependabot.yml
- .github/workflows/asf-updates.yml
- Dockerfile
This PR upgrades the OS version of the Docker image from Debian Bullseye to Debian Bookworm.
The last upgrade was done with the release of version `2.1.0` in https://github.com/localstack/localstack/pull/8344 / https://github.com/localstack/localstack/pull/7876.
Since the Debian repositories for bookworm do not contain `openjdk-11` anymore, I also switched the java-builder to use the `eclipse-temurin:11` image.
- The base image's OS has been upgraded from Debian Bullseye (oldstable) to Debian Bookworm (stable).
- The `java-builder` stage has been replaced to use [Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin) image (because Debian Bookworm does not have OpenJDK in the repos anymore).
- We are already using Eclipse Temurin in the Java installer if we need other Java versions …
> upgrade debian to bookworm

- .github/dependabot.yml
With https://github.com/localstack/localstack/pull/9288, we introduced a second base image in addition to the Python base image: Eclipse Temurin (in order to build our custom JRE).
This now causes Dependabot to create multiple PRs to update the base images:
- https://github.com/localstack/localstack/pull/9365
- https://github.com/localstack/localstack/pull/9364
This PR groups all docker base image updates into a single PR (still filed once a week).
- Introduce a Dependabot Group for docker base image updates.
> update Docker base images in a single PR

- localstack/services/cloudformation/resource_provider.py
- localstack/testing/pytest/fixtures.py
- localstack/utils/objects.py
We want to support `eksctl` in the -ext repo, but this requires some minor changes in utilities imported from community. Also there are some bugs that need fixing.
- Enable `AWS::EKS::NodeGroup` resource provider
- Fix logging bug in CFn
- `deploy_cfn_template` deletes stacks in reverse order of creation
- Add `keys_to_upper` function
> Helper changes to support `eksctl` and CDK L2 EKS construct

- localstack/aws/handlers/cors.py
- tests/aws/services/apigateway/test_apigateway_basic.py
- tests/integration/test_security.py
By default, we always add and send the CORS headers to LocalStack responses.
However, those headers should be sent only when the request has an `Origin` header set, indicating that this is a CORS request. 
We can read more about this here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#the_http_request_headers
https://jakearchibald.com/2021/cors/
> Note that in any access control request, the [Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) header is always sent.
When debugging and checking logs, we always have the CORS headers being sent, and they pollute the logs quite a lot for no benefits.
Added a check for the presence of the `Origin` header, and add the headers only if it's there.
Added the `Vary` header as we conditionally apply CORS headers …
> improve CORS handler: no CORS headers if no Origin

- localstack/services/ec2/provider.py
EC2 ModifyLaunchTemplate threw an error saying template not found for a template which could be listed. This only happened when a non-default account ID was used.
The cause was the use of a `connect_to()` field which did not take the current request account ID into consideration and instead looked for the template in the default `000000000000` account.
This PR removes the `connect_to()` call and constructs the response in the provider handler.
> EC2: Fix IndexError in ModifyLaunchTemplate
