localstack/localstack

localstack/services/sqs/models.py, localstack/services/sqs/provider.py, tests/aws/services/sqs/test_sqs_backdoor.py
A user [asked](https://discuss.localstack.cloud/t/a-way-to-see-invisible-sqs-messages/565) whether it's possible to see invisible messages through the SQS developer endpoint, and I thought this would be a really nice addition. I added delayed messages as well since it made sense.
If you now add the new query args to your request like this:
```python
response = requests.get(
"http://localhost:4566/_aws/sqs/messages",
params={"QueueUrl": queue_url, "ShowInvisible": True, "ShowDelayed": True},
headers={"Accept": "application/json"},
)
```
The endpoint now returns messages like this:
```json
[
{
"MessageId": "1c4187cc-f2c9-4f1c-9702-4a3bfaaa4817",
"MD5OfBody": "a06498de7fb4bd539c8895748f03175d",
"Body": "message-3",
"Attribute": [
{"Name": "SenderId", "Value": "000000000000"},
{"Name": …
```
=> add ability to peek delayed and invisible sqs messages

localstack/services/lambda_/packages.py, localstack/testing/snapshots/transformer_utility.py, tests/aws/services/lambda_/functions/lambda_request_id.py, tests/aws/services/lambda_/test_lambda.py, tests/aws/services/lambda_/test_lambda.snapshot.json, tests/aws/services/lambda_/test_lambda_common.py
Depends on https://github.com/localstack/lambda-runtime-init/pull/24
The official AWS lambda-runtime-init received some upstream updates (typically merged in big blobs from their internal repository). We should update our customized localstack version to support the latest features (e.g., response streaming) and updates (e.g., the new Golang version).
See https://github.com/localstack/lambda-runtime-init/pull/24
* Bump Lambda init version
* Improve the `request_id` test to cover a regression where the ID didn't match
* Extract `lambda_report_logs` transformers
* Update logs snapshots to yield individual lines for easier visual and more accurate matching (still missing selective list skip 😿 )
* Standardize Lambda commons test `get_arch`
See …
=> Integrate lambda init upstream changes

localstack/utils/aws/arns.py, localstack/utils/aws/dead_letter_queue.py, localstack/utils/aws/message_forwarding.py, localstack/utils/aws/queries.py, tests/aws/test_serverless.py, tests/performance/test_sqs_performance.py
This PR removes a redundant SQS ARN helper.
Ext codebase is not impacted.
=> Remove redundant SQS ARN helper

tests/aws/services/apigateway/test_apigateway_basic.py, tests/aws/services/dynamodb/test_dynamodb.py, tests/aws/services/ec2/test_ec2.py, tests/aws/services/kinesis/test_kinesis.py, tests/aws/services/lambda_/test_lambda_api.py, tests/aws/services/secretsmanager/test_secretsmanager.py
LocalStack test suite uses the `TEST_AWS_ACCOUNT_ID` and `TEST_AWS_REGION_NAME` to control the namespace of the test execution. Some of our tests do not run the correct assertions when these config options are set to non-default values.
This PR makes some of the test assertions account/region aware. Specifically, ARN constructions now make use of the proper account/region that was used to create the original testing resource. Plus, there is correct use of client fixtures in places.
=> Use account and region aware test assertions

.github/workflows/pr-enforce-no-major-master.yml, .github/workflows/pr-enforce-pr-labels.yml, .github/workflows/tests-pro-integration.yml
Currently, some GitHub workflows which are automatically triggered when a PR is created are failing due to the missing access to certain secrets
This PR should fix these issues such that workflow executions triggered by PRs coming from community forks can get fully green (after they have been approved by a contributor).
/cc @joe4dev 
- Disables the Pro integration tests for community forks.
- Changes the workflow trigger for the label checks from `pull_request` to `pull_request_target`.
- This is similar to the `pr-cla` action.
- This trigger is executed on the default branch of the target repo, rather than in the branch, which prevents secret leaking.
- This is why these workflows _can_  access secrets other than the default github token.
- More info on `pull_request_target` can be found …
=> disable pro tests for forks, fix label check for fork PRs

localstack/services/kinesis/packages.py
See
https://github.com/etspaceman/kinesis-mock/releases/tag/v0.4.4
and
https://github.com/etspaceman/kinesis-mock/releases/tag/v0.4.3
Notice that these releases introduce some interesting new items:
- http2 support
- Fix for persistence path
I have not updated anything outside of the version. But I'd be happy to have some guidance to update any related items here.
Bump kinesis-mock
Updates kinesis-mock to 0.4.4
=> Update kinesis-mock to 0.4.4

localstack/services/lambda_/invocation/docker_runtime_executor.py, localstack/services/lambda_/invocation/execution_environment.py, localstack/services/lambda_/provider.py
Adopt the new gateway-listen network configuration instead of `config.EDGE_PORT` (deprecated, at least as a configurable variable)
Change `config.EDGE_PORT` to `GATEWAY_LISTEN[0].port`
* The K8 executor still uses `config.get_edge_port_http()` but that will be migrated with the deprecation of `EDGE_PORT_HTTP` upon 3.0.
* The old provider still uses `EDGE_PORT` but will be removed anyways upon 3.0
=> Migrate Lambda to gateway listen

localstack/services/s3/notifications.py, tests/aws/services/s3/test_s3_notifications_eventbridge.py, tests/aws/services/s3/test_s3_notifications_eventbridge.snapshot.json, tests/aws/services/s3/test_s3_notifications_sqs.py, tests/aws/services/s3/test_s3_notifications_sqs.snapshot.json
It had been shown in the multi-account tests that we've had an issue where the `awsRegion` was not correct. It was using the client request region, when it should have been the bucket region.
Also, per the documentation for `events`: https://docs.aws.amazon.com/AmazonS3/latest/userguide/ev-events.html, the `region` field for the event should be the bucket region, which means the `events` client needs to be created with the bucket region and not the client region, as the `region` field in the event is from the internal client.
Also validated the behaviour with AWS, that the region was of the bucket and not the client.
Fix the event payload for SQS/SNS/Lambda to use the region of the bucket for the `awsRegion` field.
Fix the region for the `events` client used in the notifier.
Add 2 tests …
=> fix awsRegion field in S3 notification

localstack/services/s3/v3/storage/core.py, localstack/services/s3/v3/storage/ephemeral.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json
Reported in #9387: when creating a multipart upload on an existing key, we would not truncate the key before overwrite it like we do when calling `PutObject`.
This was due to our optimization with `append` on the StoredS3Object, which was stateless, and bad oversight on my side.
Flow for the sample in the linked issue is:
- CreateMultipart on key `test`
- UploadPart with value "first"
- CompletePart on key `test`
- GetObject on key `test` -> value is "first"
- CreateMultipart again on key `test`
- UploadPart with the result of previous GetObject ("first") + "second" -> value = "firstsecond"
- CompleteMultipart on key `test`
- GetObject on key `test`, result should be "firstsecond"
Issue was appending on top of existing key, resulting in "firstfirstsecond".
Added a new `truncate` method to …
=> fix s3 v3 multipart overwrite when key exists

localstack/services/s3/notifications.py
Follow up from  #9370, to add proper region support to S3 notifications, I've added the region to the client's creation, but also added the account id as done in #9023 for sending notifications. I'll trigger an -ext run on this PR and link it here. Sorry!
https://github.com/localstack/localstack-ext/actions/runs/6582528350
https://github.com/localstack/localstack-ext/runs/17885245621
S3 notifications are fixed, only appsync remains
Remove the account id from the client creation to trigger test event.
Also removed the account id from the client's creation to send to SQS/Lambda/SNS. But this might create issue again with multi account? \cc @viren-nadkarni why was this change made in the first place?
I believe that SNS/Lambda/SQS will retrieve the account id from the ARN passed and not from …
=> fix inter services IAM for S3 Notifications

localstack/services/sns/provider.py, tests/aws/services/sns/test_sns.py, tests/aws/services/sns/test_sns.snapshot.json
When using values other than `000000000000` for account ID or `us-east-1` for region, `sns` tests should still create the consequent resources in this accounts and region.
This PR fixes all the failing tests in `tests.aws.services.sns.test_sns.py` by:
- removing the use of `get_aws_account_id()` helper.
- use moto internals in `unsubscribe` handler. 
- use parsed arn instead of context arn 
See #8204
=> sns: add multi-account capability to failing tests

localstack/services/lambda_/invocation/lambda_service.py, localstack/utils/aws/client_types.py, localstack/utils/diagnose.py
Add mypy types for `appconfigdata` service client. Adding the `appconfigdata` provider implementation is done elsewhere - part of a customer issue we're working on with @cabeaulac . Will also address https://github.com/localstack/localstack/issues/6891
* Add mypy types for `appconfigdata` service client
The PR also sneaks in a few tiny changes
* add root cause exception in `LambdaService.invoke` - this has proven helpful for some recent persistence tests debugging /cc @giograno 
* fix some f-strings and return types
=> minor: add mypy types for appconfigdata service client

localstack/config.py, localstack/services/dynamodb/provider.py
We are investigating performance issues with dynamodb, and there it will be helpful to control which port dynamodb is created on. Moreover, this will enable workarounds where people may need to access ddb local directly. Tested locally.
cc @bentsku 
* add `DYNAMODB_LOCAL_PORT` port config, that is used if not None or > 0
* also sneaked in a changed that avoids a call to `random` when using `put_item`
=> add config variable DYNAMODB_LOCAL_PORT to control ddb local port

localstack/utils/aws/resources.py, tests/aws/services/apigateway/test_apigateway_sqs.py
When using values other than `000000000000` for account ID or `us-east-1` for region, sns tests should still create the consequent resources in this accounts and region.
This PR fixes `tests.aws.services.apigateway.test_apigateway_sqs` test cases when using non-default region and account id by:
- fixing `create_sqs_queue`, adding `region_name` and `aws_access_key_id` to the `connect_to()` client. 
- use queue arn for various sqs operations, this helps us fetching correct region and account id from arn instead of falling back to the default values. 
- remove `create_sqs_queue` in `localstack/utils/aws/resources.py`.
=> add multi account support to failing tests in apigateway-sqs integration

localstack/utils/aws/arns.py, localstack/utils/testutil.py, tests/aws/services/apigateway/test_apigateway_import.py, tests/aws/services/apigateway/test_apigateway_lambda.py, tests/aws/services/stepfunctions/v2/services/test_apigetway_task_service.py
The functions `aws_stack.get_region()` and `get_aws_account_id()` rely on the thread local storage. The LocalStack handler chain sets the right values for these functions on a per request basis.
Consequently, these utilities must not be used in tests because tests run in a different thread, this causes the functions to return the wrong values.
The ARN contruction utility `apigateway_invocations_arn` makes use of these helpers which is wrong. This leads to bugs when using multi-region and multi-accounts in LocalStack.
This PR removes the use of the above utilties from the tests and makes use of proper constants for ARN construction.
=> APIGW: Use proper account ID and region during Invocation construction

localstack/services/dynamodb/provider.py, tests/aws/services/dynamodb/test_dynamodb.py, tests/aws/services/dynamodb/test_dynamodb.snapshot.json
Ongoing work to optimize DynamoDB performance.
- remove the check for Lambda ESM:
- this is actually not needed, because lambda can only subscribe to a dynamodb stream, [which is what is passed to `CreateEventSourceMapping`](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.Lambda.Tutorial.html#Streams.Lambda.Tutorial.CreateTrigger). Our check was passing the table ARN, when it should have been the stream ARN, so it never actually returned a result. We have a better in-memory internal way to check if the table has a stream attached, so we should use this (there's actually no public API for DynamoDBStreams).
- optimize the `BatchWriteItem` operation. We would do operations that would have needed to be done only if a stream was attached all the time. Changed those …
=> enhancement: dynamodb performance optimization

.github/workflows/asf-updates.yml
With https://github.com/localstack/localstack-ext/pull/2217, we changed to `ruff` which replaces a bunch of tools (`flake8`, `isort`, `autoflake`). Previously, these tools were directly called in the ASF scaffold and the result of the code generation was already perfectly formatted.
`ruff` cannot be called from Python code on in-memory strings, which is why we switched to our `format-modified` `make` target.
Turns out, the target does not work in case there are no changes (since then black does not get any input).
This PR slightly modifies the ASF update action such that this issue is prevented.
- Changes the ASF Update action such that the `format-modified` target is only executed if there are changes in the repo.
- https://github.com/localstack/localstack/actions/runs/6610132434/job/1795 …
=> fix ASF update action if there are no changes

localstack/services/opensearch/provider.py, localstack/services/sqs/provider.py, localstack/services/stores.py
I need this pattern of iterating over the hierarchy of stores quite often and thought this little quality of life improvement would make code a bit cleaner.
* Add `AccountRegionBundle.iter_stores` method to iterate over all stores in the bundle
* Exemplified use on sqs and opensearch
=> add iter_stores method to AccountRegionBundle

localstack/services/lambda_/invocation/execution_environment.py, localstack/services/lambda_/packages.py
Depends on https://github.com/localstack/lambda-runtime-init/pull/26
This PR simplifies the user's configuration in the Lambda init Go binary. We drop root privileges in the Lambda init Go binary by default and offer a configuration variable to skip this parity feature. However, it is cumbersome to configure using a misleading empty string `""`. We skip dropping privileges when `LAMBDA_INIT_USER` is set to `root` (`""` is still supported but discouraged).
This is much easier to configure and leads to less errors around escaping quotes etc.
* Bump Lambda init version skipping privileges drop with `root`
* Fix the LocalStack configuration logic for `""`
=> Simplify localstack init user config

localstack/dns/server.py, tests/unit/test_dns_server.py
When on a support call with a customer, we noticed that the DNS server run by LocalStack was functioning and configured correctly, but running `curl -v s3.amazonaws.com` returned a public IP address, not `127.0.0.1` - expected because of transparent endpoint injection. When I investigated further, their `/etc/resolv.conf` contained `nameserver 127.0.0.11`.
We perform a check in `localstack.dns.server.add_resolv_entry` that if the `/etc/resolv.conf` contains `nameserver 127.0.0.1` then we don't update the file. `nameserver 127.0.0.11` _does_ contain `nameserver 127.0.0.1` and so I believe this is the source of the error.
* We only call the `add_resolv_entry` in one place, and only in the docker container, and so we can rework the function to be less conditional. We _always_ update the …
=> Fix LS container DNS configuration

localstack/services/apigateway/exporter.py, localstack/services/apigateway/provider.py
When using values other than `000000000000` for account ID or `us-east-1` for region, tests should still create the consequent resources in this accounts and region.
This PR fixes all the failing tests in `tests/aws/services/apigateway/test_apigateway_extended.py` by adding region and account id to the helper functions.
=> apigateway: add multi-account and region capability

localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3_api.py, tests/aws/services/s3/test_s3_api.snapshot.json
As reported in #9427, we would return `EncodingType` even when not specified. It was because of a wrong assumption on my side because boto always adds the parameter, which seemed like it was default.
Corrected the behaviour and validated it by using an HTTP client instead of boto and manually asserting the absence of the `EncodingType` field and the change in behaviour. 
Also sneaked a tiny test for `DeleteBucketPolicy` validating a question here: https://github.com/localstack/localstack/pull/9404#discussion_r1367149857
_fixes #9427_
=> fix s3 v3 EncodingType in List* operations

localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json
As reported in https://github.com/localstack/localstack/issues/9427#issuecomment-1773934333
> one thing I did notice was ListObjectsV2 startAfter appeared to be including the startAfter key, when it should be exclusive
After validating against AWS and writing some more tests which we didn't cover, we were not sorting keys properly (not leaving at the right moment in the loop).
This is based on #9429 as both are modifying the behaviour and I didn't want the merge conflict. 
Fixed the behaviour to properly match AWS and wrote a good amount of tests to validate this. Took the opportunity to validate and introduce the behaviour for `ListObjectVersions` pagination, which is not done in moto yet but is work in progress.
=> fix s3 v3 ListObjectsV2 and ListObjectVersions pagination

tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json
As reported in #9428, there's an issue with the URL encoding of S3 object keys. This is an issue in moto, and it's working properly in our `v3` provider.
I have a PR open here: https://github.com/getmoto/moto/pull/6933 but there's still some issue. This PR would only be green once the upstream fix is part of moto-ext, so I will `xfail` it for `v2` until the PR is merged as it's a big change (it requires moto to use `RAW_URI` as well and change how to handle raw path with the update of werkzeug, they are manually re-encoding the path and it has some drawbacks for some edge cases like emoji), knowing that `v3` is going to become default soon so I'd like to have it tested already now.
Only introducing tests to validate the proper behaviour.
=> add test for DeleteObjects encoding

localstack/services/cloudformation/engine/entities.py, localstack/services/cloudformation/provider.py
This PR ensures that CloudFormation Stacks and StackChangeSets have the correct ARNs when used in multi-account and multi-region setups.
=> Cfn: Add account ID and region awareness to Stacks and StackChangeSets

localstack/services/s3/utils.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json
Using the `object_store` rust crate test suite, I've spotted an issue in our handling of preconditions for v3.
Basically, the `LastModified` field on the S3 object is stored with millisecond precision for internal use like sorting when calling `ListObjects*`. 
But when comparing against `ModifiedSince`/`UnmodifiedSince` preconditions headers, those are sent using second precision, and we need to check for strict equality/superiority/inferiority. So something like the following should not be true if the precision is second:
`last_modified=datetime.datetime(2023, 10, 23, 16, 19, 41, 798495, tzinfo=zoneinfo.ZoneInfo(key='GMT')) > if_unmodified_since=datetime.datetime(2023, 10, 23, 16, 19, 41, tzinfo=datetime.timezone.utc)`
Adapted the check by rounding last modified before comparison, and …
=> fix s3 v3 preconditions

tests/aws/services/events/scheduled_rules/test_events_scheduled_rules_logs.py
We've been having a lot of issues with `tests.aws.services.events.scheduled_rules.test_events_scheduled_rules_logs` lately where it's been flaking in a weird way.
I believe this might stems from a small race condition in moto where we hit the `describe_log_streams` calls in between 2 operations: 
```python
log_backend.create_log_stream(name, log_stream_name)
log_backend.put_log_events(name, log_stream_name, log_events)
```
One of the failing run:
https://app.circleci.com/pipelines/github/localstack/localstack/19313/workflows/9dfaf4c0-6b06-4a7c-99df-17da978f99ea/jobs/150589/tests#failed-test-0
This is not optimal and should be fixed at the root, but the test is still validating behaviour and this is an edge case. We should fix the issue at the root, but for now this at least makes the test …
=> harden flaky test test_events_scheduled_rules_logs

README.md
Upon clicking on the copy button, the $ sign is copied as well, resulting in invalid command
=> Update README.md, remove dollar sign from brew command

localstack/services/kms/provider.py, tests/aws/services/kms/test_kms.py, tests/aws/services/kms/test_kms.snapshot.json
While importing parameters for import when key usage is `SIGN_VERIFY`, we got an `InvalidKeyUsageException` error. 
This PR:
- adds correct error response if key origin is not `EXTERNAL` which is mandatory for this operation. 
- removes a validation for checking key usage as `ENCRYPT_DECRYPT`.
- add an aws validated test case to check the above conditions.  
Related Issue: #9111
=> kms: fix get_parameters_for_import

localstack/services/s3/website_hosting.py
While configuring LocalStack, the `LOCALSTACK_HOST` variable can be used to configure domains that are returned from responses. We also have a few route matchers that match the host header of an HTTP request, which in turn dispatch to handlers depending on (usually) the request path. If the user customises the `LOCALSTACK_HOSTNAME` we should still accept their request, even if they do not use `*.localhost.localstack.cloud`.
* Update s3 website hosting to accept any host
=> Update route matchers to accept any host

localstack/services/lambda_/packages.py
Depends on https://github.com/localstack/lambda-runtime-init/pull/27
Fixes a parity issue of file permissions in `/var/task` when using Lambda layers. This fixes sample applications on LocalStack using the [aws-lambda-web-adapter](https://github.com/awslabs/aws-lambda-web-adapter). For example: https://github.com/awslabs/aws-lambda-web-adapter/tree/main/examples/expressjs-zip
* Bump lambda-runtime-init version
See localstack-ext https://github.com/localstack/localstack-ext/pull/2250
=> Fix lambda file permissions with layer

localstack/services/cloudformation/provider_utils.py
Since we have resource providers in -ext now, we need to fix the schema json lookup. Since -ext code is encrypted, files are renamed and have an `.py.enc` file suffix instead of the `.py` suffix in community.
- tries to remove both `.py.enc` as well as `.py` when searching for the schema json file.
=> Fix CFn schema json name resolution for -ext

localstack/aws/handlers/partition_rewriter.py, localstack/config.py, tests/unit/test_partition_rewriter.py
The ARN partition rewriter depends on the deprecated environment config variable `DEFAULT_REGION`. It uses this to determine which partition to use as a fallback.
This is preventing us from removing the `DEFAULT_REGION` config option with the upcoming major release.
This PR introduces a new config option `ARN_PARTITION_FALLBACK` which can be used to set which partition to use as fallback. It defaults to `aws`, which is identical to old behaviour where it would be determined from the `us-east-1` region.
The `DEFAULT_REGION` config option will no longer have any effect on the rewriter.
Acceptance of this PR will entail an update to enterprise image build steps.
Slightly tweaks existing tests to assert the new behaviour.
=> Add fallback partition config option for ARN partition rewriter

localstack/services/stepfunctions/provider_v2.py, tests/aws/services/stepfunctions/v2/test_sfn_api.py, tests/aws/services/stepfunctions/v2/test_sfn_api.snapshot.json
This PR fixes the exception raised when calling describe api on non-existing state machine. Which was causing the terraform to fail.
Replaced the `ExecutionDoesNotExists` exception to `StateMachineDoesNot` exists
Added AWS validated test cases for the updated exception
- https://github.com/localstack/localstack/issues/9439
=> fixed describe sfn exception

localstack/aws/connect.py, localstack/aws/forwarder.py, localstack/config.py, localstack/constants.py, localstack/deprecations.py, localstack/runtime/analytics.py, localstack/services/infra.py, localstack/services/kms/local_kms_server.py, localstack/services/s3/models.py, localstack/services/s3/v3/models.py, localstack/services/sqs/query_api.py, localstack/testing/pytest/fixtures.py, localstack/utils/aws/aws_stack.py, localstack/utils/aws/request_context.py, tests/aws/services/logs/test_logs.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3_cors.py, tests/aws/test_moto.py, tests/aws/test_terraform.py, tests/unit/conftest.py, tests/unit/test_apigateway.py, tests/unit/test_partition_rewriter.py
The `DEFAULT_REGION` environment config variable was used in early years of LocalStack when multi-region was unsupported. It has since been deprecated.
This PR removes this config variable for the upcoming major release.
=> Remove deprecated config DEFAULT_REGION

localstack/utils/aws/aws_stack.py, tests/aws/services/sns/test_sns.py, tests/aws/services/sqs/test_sqs_backdoor.py
Certains tests related to the backdoor/developer endpoints did not account for the multi-account nature of LocalStack.
This PR ensures that the this is tested appropriately.
With SNS, the assertions against the endpoints are performed in the account where the SNS resource was created.
With SQS, the tests are parametrised so that they run with endpoint schemes that support multi-region.
=> Ensure backdoor endpoint tests respect the test account ID

.github/workflows/asf-updates.yml
Recent ASF update PRs wrongly state that all services have changed (f.e. see https://github.com/localstack/localstack/pull/9500).
This is because in https://github.com/localstack/localstack/pull/9436 we moved the code formatting to after the "change" (and "changed service") detection.
Since we now generate all APIs without formatting them, all APIs seem to change.
- Move the formatting step in the GitHub action a bit such that it is executed before the changes are detected.
This test run shows that the formatting now works correctly (which is what #9500 was aiming at), and the change detection works correctly (which this PR is aiming at): https://github.com/localstack/localstack/actions/runs/6691512704
=> fix ASF update service detection

tests/aws/services/events/scheduled_rules/test_events_scheduled_rules_logs.py, tests/aws/services/s3/test_s3.py
Now that #9464 has been merged (thanks @viren-nadkarni!), the fix for S3 object key encoding is contained in LocalStack.
We need to remove the xfail marker to validate the fix and close the related the issue.
Also, `test_scheduled_rule_logs` has been really flaky, it might be a race condition but to not block the pipeline and force re-run, I've xfailed the test for now.
Remove the xfail marker for `test_delete_objects_encoding`. 
xfail `tests.aws.services.events.scheduled_rules.test_events_scheduled_rules_logs.test_scheduled_rule_logs`
_fixes #9428_
=> remove s3 encoding tets xfail marker and xfail flaky events scheduler test

tests/aws/services/cloudwatch/test_cloudwatch.py, tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json
The coverage of the operations tested for Cloudwatch v2 is lacking.
More tests
AWS validated test should pass with the new provider
- put_managed_insight_rules
- list_managed_insight_rules
=> Tests for Cloudwatch v2

localstack/services/sns/provider.py, tests/aws/services/sns/test_sns.py
When using values other than `000000000000` for account ID or `us-east-1` for region, `sns` tests should still create the consequent resources in this accounts and region.
This PR fixes the failing tests in `tests.aws.services.sns.test_sns.py` when using non default region and account by:
- using region and account from parsed `endpointArn` in case of platform endpoint messages. 
- using `TEST_AWS_REGION_NAME` instead of static `us-east-1` value. 
- remove use of region and account id in case `endpointArn` is present.
=> sns: get region and account from parsed `endpointArn`

localstack/services/s3/notifications.py
Fix multi account stabilty. This PR fixes s3 notification for lambda function invocation.
Modified the `lambda_client.invoke` function parameter to use the **Lambda Function ARN** (Amazon Resource Name) instead of the **Lambda function name**.
This PR fixes the test case mentioned below, when ran using non-default account id.
Required envs for the test
```
TEST_AWS_ACCOUNT_ID=111111111111;TEST_AWS_ACCESS_KEY_ID=111111111111;TEST_AWS_REGION=us-west-1
```
Test Case
```
tests/aws/services/s3/test_s3_notifications_lambda.py
```
=> fix s3 notification for lambda

localstack/services/stepfunctions/backend/execution.py, localstack/services/stepfunctions/backend/state_machine.py, localstack/services/stepfunctions/provider_v2.py, localstack/testing/pytest/cloudtrail_tracking.py
Persistence support has been requested by a customer using the v2 StepFunctions provider (running LS with `PROVIDER_OVERRIDE_STEPFUNCTIONS=v2 PERSISTENCE=1`). Addresses https://github.com/localstack/localstack/issues/9258
* Add state visitor handler (`accept_state_visitor(..)`) to the StepFunctions v2 provider, to enable persistence support and persist the `sfn_stores` object
* Pull out the nested classes in the store models as top-level classes - nested classes can be problematic from a persistence/pickle perspective, in fact, I did a quick check with the nested classes, and ran into a `EOFError: Ran out of input` error when attempting to load the pickled state from disk)
As a next step, tests will be added in the upstream repo.
=> Add state visitor handler for StepFunctions v2 persistence support

localstack/utils/collections.py, tests/unit/utils/test_collections.py
In [2263](https://github.com/localstack/localstack-ext/pull/2263) we moved quite some CLI-related code around.
During the core review, it turned out that `localstack.utils.collections` is a better place for this utility function.
- Moving the function;
- Adding a small unit test.
=> add utility function to check comma-delimited strings

localstack/services/s3/v3/models.py, tests/aws/services/s3/test_s3_concurrency.py
Following a failure when trying to set the v3 provider as default, I had this PR shelved since a while as I was expecting it to happen.
https://app.circleci.com/pipelines/github/localstack/localstack/19625/workflows/c064060a-3962-4b34-96a0-6c0bfe0efc00/jobs/153568/tests
This PR hardens S3 v3 concurrency, by shallow copying `dict` that will be accessed concurrently before calling `.values`, `.keys` or `.items` on them, which could trigger exception as they would be modified during iteration.
\cc @dfangl since we worked on this together for the v2 provider
Shallow-copy some dictionaries so that they wouldn't be modified during iteration from concurrent requests. 
Also added a test to check for iteration during `List*` calls.
=> harden s3 v3 concurrency

localstack/services/lambda_/event_source_listeners/kinesis_event_source_listener.py
The functions `aws_stack.get_region()` and `get_aws_account_id()` rely on the thread local storage. The LocalStack handler chain sets the right values for these functions on a per request basis.
Consequently, these utilities do not work as expected in multi-threaded environments and we are in process of deprecating these utilities. This is with the ultimate goal of having full multi-account and multi-region compatibility in LS.
This resolution also fixes failing `tests.aws.services.lambda_.test_lambda_integration_kinesis.TestKinesisSource.test_create_kinesis_event_source_mapping` for non-default account and region. 
This PR removes the use of the above helper functions and instead use region and account id from parsed ARN. 
When using values other than `000000000000` for account ID or …
=> kinesis-lambda: Remove aws_stack.get_region() and get_aws_account_id()

localstack/services/stepfunctions/asl/component/state/state_wait/wait_function/timestamp_path.py, tests/aws/services/stepfunctions/templates/scenarios/scenarios_templates.py, tests/aws/services/stepfunctions/templates/scenarios/statemachines/wait_timestamp.json5, tests/aws/services/stepfunctions/templates/scenarios/statemachines/wait_timestamp_path.json5, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.py, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.snapshot.json
In the current implementation of StepFunctions v2, the interpreter is unable to access the string value for `TimestampPath` definitions. This PR adds validated snapshot tests for `Wait` StateMachines with both `Timestamp` and `TimestampPath` invocations.
Updated json path access for `TimestampPath` declarations to the interpreter's standard logic.
=> [SFN] Fix TimestampPath Value Access

localstack/services/s3/provider.py, localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json
I was looking at the S3 v3 `CopyObject` code and spotted an issue in the code: we wouldn't check the bucket equality when validating the in-place checks.
The v3 provider has parity with the v2, but it could be nice to push things a bit further for `ListMultipartUploads` and `ListParts`, as well as adding more validated tests of `UploadPartCopy`. This is to be done in a follow up PR.
The PR was so small I also took a stab at the leftovers TODO in the v3 provider and added tests when removing some, and fixed the behaviour in both `v2` and `v3` for the following operations:
- `UploadPart`
- `CompleteMultipartUpload`
- `AbortMultipartUpload` and `ListParts` only for v3
- `CopyObject` additional validations for source object
=> fix s3 v3 CopyObject in place + general validations for S3

localstack/services/cloudformation/resource_provider.py, localstack/services/cloudformation/scaffolding/__main__.py, localstack/services/cloudformation/scaffolding/templates/plugin_template.py.j2, localstack/services/cloudformation/scaffolding/templates/provider_template.py.j2
We disabled AWS::ECR::Repository in #9315 because we did not have an override system for resource providers in community vs pro. In particular, we had:
* a community `GenericBaseModel` subclass
* a (new) community `ResourceProvider`
* a pro `GenericBaseModel` subclass
In this case, the community resource provider was being chosen, rather than the pro `GenericBaseModel` subclass.
Most of the changes to allow us to revert #9315 have been made in the pro repository. In addition, we are trying to handle the case where we have pro and community resource providers.
* Prioritise pro resource providers if present
* Update scaffolding to support scaffolding into the pro repo (partially, only the plugin for now)
* Fix scaffolding issues with unused imports
=> CFn: allow for pro resource provider overrides

localstack/services/lambda_/provider.py, tests/aws/services/lambda_/functions/lambda_echo_version_env.py, tests/aws/services/lambda_/test_lambda.py, tests/aws/services/lambda_/test_lambda_integration_sqs.py, tests/aws/services/lambda_/test_lambda_integration_sqs.snapshot.json
- Initiated by a support case, we saw that we never updated the stored function ARN in the event source mapping, which lead to the event source mapping still calling the previous version instead.
Example scenario (see accompanying test case):
```
Testing an update to an event source mapping that changes the targeted lambda function version
Resources used:
- Lambda function
- 2 published versions of that lambda function
- 1 event source mapping
First the event source mapping points towards the qualified ARN of the first version.
A message is sent to the SQS queue, triggering the function version with ID 1.
The lambda function is updated with a different value for the environment variable and a new version published.
Then we update the event source mapping and make the qualified ARN of the …
```
=> Fix updates of event source mapping targeting new function versions

bin/localstack-supervisor
We're currently hardcoding a maximum of 5 seconds for orderly process shutdown in `localstack-supervisor` before forcefully killing the process. This can be problematic in cases where a couple more seconds are required to perform shutdown logic, e.g., when storing cloud pods or CI run logs as part of the termination procedure of the LS container.
This PR adds a config option `SHUTDOWN_TIMEOUT` to make the shutdown timeout configurable. The change is backwards compatible and should not break existing functionality.
/cc @giograno @alexrashed @thrau 
* add `SHUTDOWN_TIMEOUT` environment config, to allow for shutdown handlers of more than 5sec (use `5` as default value, as before)
=> Add SHUTDOWN_TIMEOUT config to allow for shutdown handlers of more than 5sec

localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json
Going over the left overs TODOs from the v3 provider, I wanted to fixed the remaining important ones, namely handling the pagination for `ListMultipartUploads` and `ListParts`, and validate some behaviour that wasn't tested related to `List*` operations and pagination. 
~Currently based on #9483~
Added handling of pagination parameters for `ListMultipartUploads` and `ListParts`.
Improve handling of `isTruncated`. 
Added a lot of snapshot tests to validate ordering, filtering and pagination of `List*` operations.
=> improve s3 v3 ListMultipartUploads and ListParts & various List* improvements

localstack/aws/handlers/auth.py, localstack/services/apigateway/integration.py, localstack/services/edge.py, localstack/services/lambda_/legacy/aws_models.py, localstack/services/lambda_/legacy/lambda_executors.py, localstack/utils/aws/aws_stack.py, localstack/utils/aws/request_context.py, localstack/utils/testutil.py, tests/aws/services/apigateway/test_apigateway_basic.py, tests/aws/services/cloudformation/resources/test_cdk.py, tests/aws/services/cloudwatch/test_cloudwatch.py, tests/aws/services/kinesis/test_kinesis.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3_cors.py, tests/aws/services/secretsmanager/test_secretsmanager.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sts/test_sts.py, tests/integration/test_edge.py, tests/integration/test_security.py, tests/unit/test_dynamodb.py, tests/unit/test_partition_rewriter.py
The `aws_stack.mock_aws_request_headers()` utility is used in our codebase to generate headers for AWS requests. Among these headers include `Content-Type`, `Accept-Encoding`, date and especially the `Authorization` header.
The issue this PR is addressing is the optional nature of the access key and region name arguments for this function, in which the `get_aws_access_key_id()` and `aws_stack.get_region()` are used. We already know that these are problematic functions that rely on thread context storage and are not guaranteed to return the correct values. Furthermore they must not be used in tests, indirectly which is exactly what is happening.
This PR makes the access key ID and region name field mandatory.
=> Refactor aws_stack.mock_aws_request_headers()

localstack/services/cloudformation/engine/template_deployer.py, tests/aws/services/cloudformation/api/test_reference_resolving.py, tests/aws/templates/cfn_unexisting_resource_dependency.yml
The Logs are pretty hard to understand and are not helpful when a CloudFormation template resource uses a dependency or refers to a resource that is not defined in the template.
Now the TemplateDeployer raises an exception indicating that it doesn't find in the template the definition for a referenced resource.
Simple 'only_localstack' tests to validated the failed deployed with a readable reason for it
The alternative to raising an error is to just print a LOG and continue with the rest of resources but this can lead to unexpected results and it's an error that should make the template deployment fail.
AWS validates the template and dependencies before deployment, but that's a big issue to resolve in LocalStack.
cc/ @alexrashed
=> raise exception for undefined dependency in CFn template

Makefile, doc/external_services_integration/kafka_self_managed_cluster/docker-compose.yml, docker-compose-pro.yml, docker-compose.yml, localstack/cli/localstack.py, localstack/config.py, tests/unit/cli/test_cli.py, tests/unit/test_dockerclient.py
Hyphens are not allowed in URLs. When addressing the LocalStack container over a docker network, the container name resolves to the IP address of the container. This is a problem in particular for `boto3` which refuses to connect.
Rename `localstack_main` -> `localstack-main`
=> Rename default container name to localstack-main

localstack/services/cloudwatch/provider.py, localstack/services/infra.py, localstack/services/internal.py, localstack/services/ses/provider.py, localstack/utils/config_listener.py, tests/aws/services/ses/test_ses.py, tests/integration/test_config_endpoint.py, tests/unit/services/test_internal.py
This PR removes the routing for endpoints which have been deprecated for a long time:
- `/health` → Now `/_localstack/health` (since `1.3.0` )
- `/cloudwatch/metrics/raw` → Now `/_aws/cloudwatch/metrics/raw` (since `1.3.0`)
- Removes the registration of the deprecated routes for the health endpoint and the raw metrics from CloudWatch. /cc @steffyP 
Prior to the removal, all known usages in the repos of the `localstack` org on GitHub have been migrated:
- https://github.com/localstack/docs/pull/879
- https://github.com/localstack/localstack-on-k8s/pull/4
- https://github.com/localstack/localstack-terraform-test/pull/32
=> remove deprecated HTTP endpoints / routes

localstack/testing/snapshots/transformer_utility.py, tests/aws/services/route53/test_route53.py, tests/aws/services/route53/test_route53.snapshot.json
Looking at a few minor parity gaps issues on our board, I wanted to start introducing snapshot tests for route53.
- adding an initial simple snapshot test;
- adding fixture for self-cleaning hosted zones;
- initial set of transformers for route53.
=> adding route53 snapshot test

tests/aws/services/apigateway/test_apigateway_integrations.py, tests/aws/services/cloudformation/resources/test_legacy.py, tests/aws/services/lambda_/test_lambda_legacy.py, tests/aws/services/opensearch/test_opensearch.py, tests/aws/services/secretsmanager/test_secretsmanager.py, tests/aws/test_terraform.py, tests/integration/test_edge.py, tests/unit/services/opensearch/test_cluster_manager.py
The functions `aws_stack.get_region()` and `get_aws_account_id()` use thread local storage to retrieve their values. The correct values are set in LocalStack request handler chain. If these values are not set, these functions return the fallback values.
Consequently these functions must not be used in tests. This is because the account ID and regions used by the test fixture `aws_client` do not necessarily match the fallback values.
This PR removes all use of these functions from the community tests.
=> Remove aws_stack.get_region() and get_aws_account_id() from tests

localstack/services/internal.py, tests/integration/test_config_endpoint.py
One of the Chaos Engineering features we want to enable in the Web app with @webdev51  is setting the `KINESIS_ERROR_PROBABILITY`/`DYNAMODB_ERROR_PROBABILITY` config variables, to simulate rate limiting for Kinesis/DynamoDB.
This can be enabled by asking the user to enable `ENABLE_CONFIG_UPDATES=1` on LS startup (with the caveats / security implications that come with it, and which we have also documented in our docs), and then using the config update endpoint.
However, currently updating the value to `ENABLE_CONFIG_UPDATES=1` is not fully working, as the service providers expect those values to be numeric, whereas the config update listener sets them as string. It seems reasonable to check if config values are numeric, and then convert them to float (the other approach would be to fix …
=> Allow setting numeric config variables in config update endpoint

Dockerfile
We are discontinuing community pods (see [here](https://github.com/localstack/localstack/issues/9519)).
I will follow up by moving the code in the [persistence plugin](https://github.com/localstack/localstack-plugin-persistence) into `ext`.
Remove the installation of the localstack persistence plugin in the community image.
=> Deprecate community pods

localstack/services/opensearch/provider.py
Fixes #8092
`OpensearchProvider` implements the methods `on_after_state_load`, `on_before_state_reset`, and `on_before_stop`. However, they currently are never invoked because the provider is not a `ServiceLifecycleHook` ([which is checked here](https://github.com/localstack/localstack/blob/master/localstack/services/plugins.py#L165-L168)). This causes loaded elasticsearch/opensearch state to not behave correctly (i.e. #8092).
I didn't add a new test for this because I'm not sure where it should go - are there existing tests covering persistence? Fortunately, this change itself is fairly minimal.
=> Make OpensearchProvider inherit ServiceLifecycleHook

localstack/services/cloudwatch/alarm_scheduler.py, localstack/services/sqs/provider.py, localstack/utils/cloudwatch/cloudwatch_util.py
The purpose of this PR is to enhance the stability of CloudWatch's integration with SQS when dealing with multiple accounts. The main issue addressed is that when publishing queue metric data, the CloudWatch client was being instantiated without an `aws_access_key_id`. This omission caused the metrics to be associated with an incorrect account.
This PR introduces the `aws_access_key_id` parameter to the `connect_to` method. The remaining modifications involve propagating the `account_id` value to the relevant functions.
The tests were failing previously when executed with a non-default account ID, set through environment variables (`TEST_AWS_ACCOUNT_ID=111111111111, TEST_AWS_ACCESS_KEY_ID=111111111111, TEST_AWS_REGION=us-west-1`). The affected tests are:
- …
=> stabilized multi account for cloudwatch-sqs

localstack/config.py, localstack/utils/bootstrap.py, tests/unit/utils/test_bootstrap.py
Following the change merged in `master` with #9494, we now want to make it enabled by default with `v3.0`. 
Make use of `is_env_not_false` to validate if the feature is not disabled (which makes it enabled by default). 
Added a test for the default enabling and disabling of the feature as well.
=> make strict service loading default for v3

localstack/config.py, localstack/services/infra.py, localstack/utils/bootstrap.py, localstack/utils/container_utils/container_client.py, tests/aws/services/lambda_/test_lambda_developer_tools.py
When working on S3 performance, it was shown that using mounted volumes on macOS induces a drop in filesystem operation performance from between 25 to 50%. This can be acceptable if using persistence, as there wouldn't be any other way to do it. However, when not using persistence, for many services, we are using the `config.dirs.data` folder (which points to tmp), which is inside the mounted volume, to create assets. This creates a drop in performance that might not be needed, if we can use the container own filesystem where it wouldn't be mounted.
Use the `tempfile.gettempdir` method to create a temp dir which wouldn't clash inside the container for the `config.dirs.tmp`, which has the advantage of already having the logic for when persistence is disabled, data would direct to …
=> make config.dirs.tmp be inside the container filesystem, add mounted_tmp

localstack/config.py
This PR makes the `standard` SQS queue URL strategy the default. 
This will enable out-of-the-box multi-account and multi-region support in LocalStack SQS.
Depends on https://github.com/localstack/localstack/pull/9454
=> SQS: Use the 'standard' queue URL strategy by default

localstack/services/kms/provider.py, tests/aws/services/kms/test_kms.snapshot.json, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json
While working on broken multi account and region `s3` tests in [#9560](https://github.com/localstack/localstack/pull/9560) , we figured out some outdated snapshot tests for invalid `kms` key id giving `NotFoundException` exception throwing incorrect error message. 
This PR:
- Updates the incorrect invalid key id error message. 
- Updates the corresponding snapshot tests for `tests/aws/services/kms/test_kms` and `tests/aws/services/s3/test_s3`. 
- Adds support for multi account to `tests/aws/services/s3/test_s3/test_s3_sse_validate_kms_key` when using when using values other than `000000000000` for account ID or `us-east-1` for region, tests should still create the consequent resources in required accounts and region.
=> update kms invalid key format and fix a broken multi account test for s3

localstack/services/plugins.py, localstack/services/sqs/provider.py, tests/bootstrap/test_strict_service_loading.py
With `STRICT_SERVICE_LOADING` added in https://github.com/localstack/localstack/pull/9494, we can now start selected services only.
In this PR we fix the loading of `sqs` only (disable init of `cloudwatch` workers). 
Additionally, the `_localstack/health` endpoint returns the `available` and `disabled` services.
* `SQS` provider: skip init of cloudwatch workers if the service `cloudwatch` is not enabled
*  return the correct `ServiceState` if the service is not available
=> show available/disabled services in health endpoint + fix sqs strict loading

localstack/services/apigateway/provider.py
This PR improves the multi-account functionality for the API Gateway `test_invoke_method`. Previously, the `account_id` within the `invocation_context` was not being set and defaulted to "none". To rectify this, the `account_id` and `region` are now set from the `context` variable, with reference to the `invocation_context.api_id`.
The `invocation_context` object's `account_id` and `region` parameters have been updated to reflect accurate information extracted from the API ID.
The tests were failing previously when executed with a non-default account ID, set through environment variables (`TEST_AWS_ACCOUNT_ID=111111111111, TEST_AWS_ACCESS_KEY_ID=111111111111, TEST_AWS_REGION=us-west-1`). The affected tests are:
- `tests.aws.services.apigateway.test_apigateway_api.TestApiGatewayApi.test_inv …
=> stabilized multi account for apigw test_invoke_method

localstack/services/sns/provider.py, localstack/services/sns/publisher.py, tests/aws/services/sns/test_sns.py, tests/aws/services/sns/test_sns.snapshot.json
We had a TODO in the code because SNS Delivery logs were always-on for LocalStack when it's opt-in in AWS.
Also it has been shown they are making performance quite a bit worse.
Here are some numbers:
  | Base | Disable SQS metrics | Disable SNS Delivery logs | Both
-- | -- | -- | -- | --
Throughput for 1kb publish (req/s) | 20.17 | 28.72 | 31.87 | 68.78
- Base: `1000 requests took 49.5744 s = 49.5744 ms/op = 20.17 req/sec`
- Disable SQS metrics: `1000 requests took 34.8189 s = 34.8189 ms/op = 28.72 req/sec`
- Disable SNS Delivery logs: `1000 requests took 31.3768 s = 31.3768 ms/op = 31.87 req/sec`
- Both: `1000 requests took 14.5392 s = 14.5392 ms/op = 68.78 req/sec`
From a simple benchmark with one topic, one SQS queue subscribed to it, pushing 1000 messages/
I suspect the fact that the …
=> make SNS Delivery Logs opt-in 

localstack/cli/localstack.py
Removes the only deprecated CLI command in `localstack-core`: "infra"
- Removes the `infra` CLI command group
=> remove deprecated "infra" CLI command

localstack/aws/handlers/cors.py, localstack/config.py, localstack/dev/run/__main__.py, localstack/dev/run/configurators.py, localstack/services/infra.py, localstack/services/lambda_/provider.py, localstack/services/opensearch/cluster_manager.py, localstack/services/stepfunctions/legacy/stepfunctions_starter.py, localstack/utils/bootstrap.py, tests/aws/services/opensearch/test_opensearch.py, tests/unit/cli/test_cli.py, tests/unit/test_config.py, tests/unit/test_cors.py
Depends on `LOCALSTACK_HOST` migration: https://github.com/localstack/localstack/pull/9390
`EDGE_PORT`, `EDGE_PORT_HTTP` and `EDGE_BIND_HOST` are replaced by `GATEWAY_LISTEN`, and have been deprecated since version 2.0. These variables should be removed in a major version, and can be done in version 3.0.
* Make `EDGE_PORT` read-only. Internal use is widespread and therefore we consider it as a shortcut for now with the semantics `EDGE_PORT == GATEWAY_LISTEN[0].port`. We also keep exposing `EDGE_PORT` in LocalStack compute services because we have not advertised a migration path yet.
* Remove `EDGE_PORT_HTTP`
* Remove `EDGE_BIND_HOST`
* Announced networking changes upon 2.0: https://discuss.localstack.cloud/t/upcoming-changes-for-localstack-v2/239#networking-7
* GATEWAY_LISTEN behavior …
=> Migrate deprecated edge variables

localstack/config.py, localstack/constants.py, localstack/services/apigateway/helpers.py, localstack/services/cloudformation/models/s3.py, localstack/services/s3/cors.py, localstack/services/s3/resource_providers/aws_s3_bucket.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_api_gateway.py, localstack/testing/pytest/fixtures.py, localstack/utils/aws/aws_stack.py, localstack/utils/urls.py, tests/aws/services/route53/test_route53.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3_cors.py, tests/unit/test_config.py, tests/unit/test_s3.py
Some usages of `LOCALHOST_HOSTNAME` were missed during the migration to `LOCALSTACK_HOST`. This PR addresses that.
Note: usages of _returning_ `LOCALHOST_HOSTNAME` are changed, not internal usages of `LOCALHOST_HOSTNAME` to return to `localhost`. This is important, because `LOCALSTACK_HOST` is a "cosmetic" variable, and as such should not be used as a value to reach `localhost`.
* Update external usages of `LOCALHOST_HOSTNAME` to use `LOCALSTACK_HOST`.
* Move Route53 hosted zone fixture to a common location for use in the network configuration tests in LocalStack Pro
* `LOCALSTACK_HOST` no longer configures the edge port if `GATEWAY_LISTEN` is _not_ specified
* this was weird behaviour, and a confusing mix of cosmetic and functional variables
=> Update remaining usages of LOCALHOST_HOSTNAME

localstack/config.py, localstack/deprecations.py, localstack/services/cloudformation/engine/template_deployer.py, localstack/services/cloudformation/models/s3.py, localstack/services/infra.py, localstack/services/s3/resource_providers/aws_s3_bucket.py, localstack/services/s3/virtual_host.py, localstack/services/sns/publisher.py, localstack/services/sqs/models.py, tests/aws/services/apigateway/test_apigateway_integrations.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3_cors.py, tests/aws/services/sqs/test_sqs.py, tests/aws/test_network_configuration.py, tests/unit/services/s3/test_virtual_host.py
* `<SERVICE>_PORT_EXTERNAL` has been deprecated since 2022-07-13 in [this docs PR](https://github.com/localstack/docs/pull/201/files#diff-0502d352f33bf9d3db34ba16e95a02f45a111e7f9029f0577c2f37749c148d9fR328). However, it has never made it into `deprecations.py`. The migrations of `LOCALSTACK_HOST` offers a consistent way throughout LocalStack to achieve the same goal and should be preferred over service-specific solutions such as `SQS_PORT_EXTERNAL`.
* The migrations of `LOCALSTACK_HOST` (https://github.com/localstack/localstack/pull/9390) and removal of the legacy edge variables (https://github.com/localstack/localstack/pull/9405) has left some networking helpers in `config.py` in an inconsistent state.
* Some combine elements of internal and external usage (e.g., `get_edge_url()`). This …
=> Remove SQS_PORT_EXTERNAL and unify networking helpers

tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json
When using non-default values for account and region, S3 tests should still create the consequent resources in this accounts and region. If the region is set as `us-west-2` in `TEST_AWS_REGION_NAME` and we create a `KMS` client for the same region I get kms key ARN as `arn:aws:kms:<region>:111111111111:key/<uuid:1>` i.e. the value for `us-west-2` is replaced by the default region regex transformer `<region>`. But now if we create a KMS client say for some other region other than the `TEST_AWS_REGION_NAME`  assume `us-west-1` the value of the ARN is `arn:aws:kms:us-west-1:111111111111:key/<uuid:1>`. 
This PR adds a `RegexTransformer` to both the hardcoded regions and updates the corresponding snapshot for `tests.aws.services.s3.test_s3.TestS3.test_s3_sse_validate_kms_key`.
=> s3: add regex transformer for different regions

localstack/extensions/api/extension.py
I noticed that extensions' `on_extension_load` methods are called twice. This is because the extension manager in localstack_ext.extension.manager already calls `on_extension_load` via the `ExtensionLifecycleListener` (see ext code [here](https://github.com/localstack/localstack-ext/blob/master/localstack_ext/extensions/manager.py#L24-L28)).
* Remove the call to `self.on_extension_load()` in the `load` method of the extension.
=> remove duplicate on_extension_load call

localstack/services/internal.py
We needed config values in our web app and currently there's no endpoint which returns the config values so I added one.
Added an endpoint in  `localstack/services/internal.py` file
=> Add internal endpoint to return config

tests/aws/services/apigateway/test_apigateway_basic.py
The purpose of this PR is to enhance the stability of apigateway's integration with kinesis when dealing with multi-accounts and multi-regions. The main issue addressed is that when connecting api gateway to kinesis, the `apigateway` client was being instantiated without an `aws_access_key_id`. This omission caused the `kinesis` to be associated with an incorrect account.
This PR introduces the use of `region` and `account_id` as mandatory fields in order to connect with the correct `apigateway` client `connect_to` method. The remaining modifications involve propagating the values to the relevant functions.
=> apigateway-kinesis: add region and account id params

localstack/aws/protocol/parser.py, localstack/services/s3/virtual_host.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json
Following #9603, I've ran the OpenDAL integration test with `OPENDAL_S3_ENABLE_VIRTUAL_HOST_STYLE=on` to see if there would be any difference, and 2 tests failed. After investigation, it was because calling `ListObjectsV2` would return the keys without the trailing slash, making the test assertions fail. After investigating the difference between the calls, I could see the parsed request was different between the 2 modes:
Virtual-Host before the fix:
`PUT opendal-testing.s3.localhost.localstack.cloud:4566/CI/16b716e8-4cd2-4f6e-9d82-ee338b5e48b1/580cc505-82cf-424e-8448-ca4bf9dfd1ac/`
`-> PutObjectRequest({'ACL': None, 'Bucket': 'opendal-testing', ..., 'Key': 'CI/16b716e8-4cd2-4f6e-9d82-ee338b5e48b1/580cc505-82cf-424e-8448-ca4bf9dfd1ac', 'Metadata': {}...) `
Path style:
`PUT …
=> fix S3 v3 VirtualHost removing trailing slash

localstack/aws/protocol/parser.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json
When scrolling over my GitHub homepage, I stumbled upon this (edit: apparently dead) library: https://github.com/beyondstorage/go-storage
(Story: https://xuanwo.io/en-us/2023/01-beyond-storage-why-we-failed/, all commits are from dependabot now 😅 and it seems [OpenDAL](https://opendal.apache.org) ([repo](https://github.com/apache/incubator-opendal)) is superseding the project, I've ran their Rust test suite (106 tests!) and it's all green 🎉)
It seems it's has been sponsored by Vercel, and I saw they had coverage for S3, and an automated in CI integration test suite.
I've forked the repo and ran the suite locally with LocalStack 😄 I saw they had support for minio too.
I've ran it locally and found only one test failure:
```go
When ListMultiPart 
ListMultipart error should be nil ✔✔
Next …
```
=> fix S3 parser with empty integer query string parameters

localstack/aws/protocol/serializer.py, localstack/aws/protocol/service_router.py, localstack/services/providers.py, localstack/utils/bootstrap.py, localstack/utils/coverage_docs.py, tests/bootstrap/test_strict_service_loading.py, tests/unit/aws/test_spec.py, tests/unit/utils/test_bootstrap.py
To quickly merge the changes, the PR comments of #8268 had not been addressed yet. This PR does the second iteration.
- remove a debug print statement and fix a typo
- add a comment regarding the conflict resolution between `sqs` and `sqs-query` service names, might need to create a specific step in the service name parser resolution if more services start to migrate to the `json` protocol, based on `Content-Type` header?
- add `sqs-query` as a dependency of SQS in the API dependencies for `SERVICES`, so that we enable both in case `sqs` is enabled. 
```diff
-        with pytest.raises(aws_client.sqs.exceptions.QueueNameExists):
+        with pytest.raises(ClientError) as e:
```
(I don't think it would change anything in snapshot but we can verify then)
=> fix SQS JSON leftovers

localstack/aws/handlers/analytics.py, localstack/aws/handlers/logging.py, localstack/aws/handlers/metric_handler.py, localstack/aws/handlers/partition_rewriter.py, localstack/utils/aws/aws_stack.py
LocalStack now uses the `RequestContext.is_internal_call` attribute to indicate internal cross-service calls.
This PR removes the use of legacy helper which relies on `HEADER_LOCALSTACK_ACCOUNT_ID` header which itself is a vestige of the old `aws_stack.connect_to_service()` utility. 
The old client was removed in https://github.com/localstack/localstack/pull/9343, and this is not a breaking change.
=> Remove legacy internal call detection helper

localstack/constants.py, localstack/services/opensearch/versions.py, tests/aws/scenario/bookstore/test_bookstore.snapshot.json, tests/aws/services/es/test_es.py, tests/aws/services/opensearch/test_opensearch.py
This PR:
- Introduces support for OpenSearch 2.9 engine
- Makes it the default. The test suite now run against this 
Docs: https://github.com/localstack/docs/pull/911
Closes: https://github.com/localstack/localstack/issues/9408
Changes were migrated from https://github.com/localstack/localstack/pull/9606
=> OpenSearch: Bump engine version to 2.9

localstack/dev/run/configurators.py
We are internalizing the persistence plugin (see [2298](https://github.com/localstack/localstack-ext/pull/2298)). 
This step is not needed anymore.
- removed the mount of the persistence code.
=> remove mount for persistence plugin

localstack/services/sqs/query_api.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.snapshot.json
As reported in https://github.com/localstack/localstack/issues/8267#issuecomment-1810805915, it seems the [PHP SDK](https://github.com/aws/aws-sdk-php) still struggles to communicate with LocalStack.
After investigation, it showed that the PHP SDK is still sending the requests to the queue URL even though the specs are specifying that it should be against `/`. Our router caught the request and assumed it was a Query API. 
- if the `Content-Type` header is `application/x-amz-json-1.0`, raise `NotFound` in the route so that the handler chain can take of the request
- add a test testing this very weird behavior by creating a client with an endpoint set to the queue URL (tested against AWS, it weirdly works...)
Tested with a PHP sample, it solves the issue now
To test the changes with the PHP …
=> fix SQS json requests sent to query route

localstack/services/s3/presigned_url.py, tests/aws/services/s3/test_s3.py
Following up on #9603, I've quickly investigated the issue for the pre-signed URL message showing a non valid signature for a very simple request and quickly found the issue related to signed headers being in the ignore list.
- fix the logic when ignoring SigV4 headers, we should still include them if they're in the `SignedHeaders`, and only ignore if they're missing
- add a test validating this behavior and copying the Go SDK behavior with the help of registering handlers. This was extremely tricky to force boto to behave this way, as the AWS CRT library does not allow you to do so. The Go SDK seems a bit weird, but it allowed us to verify the behavior of previously thought "ignored" headers.
=> fix S3 pre-signed logic for IGNORED_SIGV4_HEADERS

localstack/config.py, localstack/utils/bootstrap.py, tests/integration/utils/test_diagnose.py, tests/unit/test_config.py
Depends on https://github.com/localstack/localstack/pull/9633
We initially discussed about keeping internal read-access of `EDGE_PORT` as an alias for `GATEWAY_LISTEN[0].port`. Partly because it was used all over the place. However, after finally removing its usages in https://github.com/localstack/localstack/pull/9633, @simonrw suggested removing `EDGE_PORT` altogether with 3.0. Keeping `EDGE_PORT` would risk legacy usages leading to several networking consistency issues, especially when returning URLs manually.
* Remove the deprecated internal read-access to `config.EDGE_PORT` and all remaining (test) usages.
Read-access to the provided environment variable `EDGE_PORT` in compute services such as Lambda, EMR, Batch, ECS, etc will remain supported in LocalStack 3.0. Our [networking …
=> Remove edge port config

localstack/utils/docker_utils.py
Currently we are getting unwarranted `Unexpected error when attempting to determine container port status:` errors on some systems, depending on the docker daemon API answer.
* Add additional possible log message to suppress faulty warning
=> Properly parse error message for container host port open detection

Makefile
Motivation is mentioned here: #9612
Added a new `stable` tag to Dockerhub publishing, this will allow users to be on the most latest code, without compromising stability - The new `stable` tag should only be published on non-dev code
`make docker-push-master` with `.dev` in `localstack/__init__.py`, and then without.
Validate that when we have `.dev` version - `stable` tag is not pushed, only `latest` is pushed
When we do not have `.dev` version - along side with the `IMAGE_TAG`, the `stable` is also pushed
=>  Publish stable version on non-dev versioning

localstack/services/s3/v3/provider.py, localstack/services/s3/v3/storage/core.py, localstack/services/s3/v3/storage/ephemeral.py, tests/aws/services/s3/test_s3_api.py, tests/aws/services/s3/test_s3_api.snapshot.json
s3 multipart copy_from fails when CopySourceRange header not specified with V3 s3 provider
fails with exception 
>   File "/opt/code/localstack/localstack/services/s3/v3/provider.py", line 1967, in upload_part_copy
>     range_data = parse_copy_source_range_header(source_range, src_s3_object.size)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/code/localstack/localstack/services/s3/utils.py", line 258, in parse_copy_source_range_header
>     _, rspec = copy_source_range.split("=")
>                ^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'split'
https://github.com/localstack/localstack/issues/9519
not a REQUIRED parameter in current docs https://boto3.amazonaws.com/v1/documentation/api/latest/reference/ …
=> fix: allow CopySourceRange to be empty on s3.upload_part_copy

localstack/services/sqs/models.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.snapshot.json
Customer reported an error when changing message visibility. This most likely comes from a discrepancy between AWS and us when calling `change_message_visibility`. 
Fixes #9598 
- fix behaviour when calling  `change_message_visibility` on an already expired handle, where AWS simply sends back an OK and does nothing while we returned an error.
=> fix change_message_visibility behaviour for expired handles

localstack/config.py, tests/unit/test_config.py
While migrating the networking configuration, @simonrw [commented](https://github.com/localstack/localstack/pull/9633#discussion_r1393271424) that subdomains are commonly used but insufficiently supported by the current helpers.
It would be nice to use:
```
subdomains = f"{api_id}.execute-api"
url = f"{config.external_service_url(subdomains=subdomains)}/{stage}/{path}"
```
rather than misusing the hostname and duplicating default values.
**Why 3.0?**
We anticipate that this API will be used from LocalStack Extensions quite a bit and therefore compatibility with LocalStack >=3.0 is important.
* Add optional `subdomains` parameter to `_service_url` helpers. This change is compatible with the existing code and primarily relevant internally within LocalStack as well as for LocalStack …
=> Add subdomains to service url helpers

localstack/aws/protocol/serializer.py, localstack/services/s3/utils.py, localstack/services/s3/v3/models.py, localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3_list_operations.py, tests/aws/services/s3/test_s3_list_operations.snapshot.json
As reported in #9637, we return too precise timestamps. AWS returns ISO6081 milliseconds timestamps for S3 List operations, but with the milliseconds set to `000` (`%Y-%m-%dT%H:%M:%S.000Z`). This is handled in the serializer, as the declared type of the fields of the `TypedDict` is `datetime`
On a related note, AWS also returns RFC1123 timestamps for `LastModified` headers, as they should, but I've validated the behavior as well with AWS validated tests. 
- updated the S3 serializer to return `ISO6081` datetime with this specific format. 
- wrote a whole bunch of test to validate that this does not alter behavior everywhere where we return timestamp in S3. I've checked most of the specs and the stubs, there might be some edge cases but I doubt they are using the base datetime parsing. …
=> fix S3 timestamp precision

localstack/services/apigateway/helpers.py, localstack/services/cloudformation/engine/template_deployer.py, localstack/services/cloudformation/engine/template_utils.py, localstack/services/s3/provider.py, localstack/services/sqs/query_api.py, localstack/utils/crypto.py
There were a few usages of the constant `localhost.localstack.cloud` that remain after #9578 and #9600. This PR updates these. Ideally all routes should match on a wildcard domain suffix, e.g. `*.opensearch.*` or `*.execute-api.*` rather than e.g. `*.localhost.localstack.cloud` as we currently have. If this is not possible, we should at least match on `*.LOCALSTACK_HOST` since this has been customised.
Thanks @bentsku for [pointing out that I missed some](https://github.com/localstack/localstack/pull/9638#pullrequestreview-1731644001).
* Update remaining functional uses of `localhost.localstack.cloud`. Note: the value is still ok in tests since they target localhost anyway.
=> Update remaining host matching for localhost.localstack.cloud

doc/interaction/README.md, localstack/config.py, localstack/deprecations.py, localstack/testing/pytest/cloudtrail_tracking/cloudtrail_tracking/handler/index.py, localstack/utils/net.py
`localstack.config.py` has become bloated by mixing up deprecated, removed, and current configurations.
`HOSTNAME_FROM_LAMBDA` is deprecated but still supported.
This PR primarily improves the organization of the config list and removes a deprecation:
* Synchronize removal grouping with the docs PR https://github.com/localstack/docs/pull/918
* Remove `HOSTNAME_FROM_LAMBDA` from deprecations. This was deprecated but then added to the new Lambda provider upon request. The Lambda team decided to un-deprecate it given the need and currently no supported alternatives.
* Migrate a leftover `AWS_ENDPOINT_URL`
* Remove some outdated comments with deprecated references to `LOCALSTACK_HOSTNAME`
=> Organize config list

setup.cfg
It seems botocore just released a minor version containing their `service-2.json` files now `gzip`.
Our loader should work, but it seems Moto is directly trying to load them manually and this fails.
One of the stack trace:
```python
.venv/lib/python3.11/site-packages/moto/emr/responses.py:61: in ElasticMapReduceResponse
aws_service_spec = AWSServiceSpec("data/emr/2009-03-31/service-2.json")
.venv/lib/python3.11/site-packages/moto/core/responses.py:964: in __init__
spec = load_resource("botocore", path)
.venv/lib/python3.11/site-packages/moto/utilities/utils.py:22: in load_resource
return json.loads(pkgutil.get_data(package, resource))  # type: ignore
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
```
- bin botocore to be above SQS changes, but under the …
=> pin botocore before gzip of services

tests/aws/services/s3/test_s3.py
The test was failing if there was more than one bucket in the `ListBuckets` call because of bad test cleanup
- fix the test to really handle the case where they are multiple buckets (my xml parsing guarding was wrong)
=> fix test_s3_timestamp_precision

localstack/dev/run/configurators.py
This PR skips mounting a few pip dependencies into the dev container, to improve compatibility for non-Linux environments (running on Macbook Pro M1 here).
Discovered this recently when running some integration tests that are spawning external dev containers, e.g.,  `tests/pod_remotes/test_remotes_save_load.py::TestSmokePodPlatform`
```
...
ls-dev-29ad46fe:   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 10, in <module>
ls-dev-29ad46fe:     from cryptography.exceptions import (
ls-dev-29ad46fe:   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/cryptography/exceptions.py", line 9, in <module>
ls-dev-29ad46fe:     from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ls-dev-29ad46fe: …
```
=> [minor] skip mounting binary pip dependencies in dev container

setup.cfg
Shortly before the v3 release we have seen some releases of dependencies which broke our pipelines.
This PR reverts the pin on `opensearch-py` and increases the minimum version:
The pin was introduced in b2b323019f0cebfaec6016a0fc62828aea13f81d due to https://github.com/opensearch-project/opensearch-py/issues/592, which has been addressed in https://github.com/opensearch-project/opensearch-py/pull/594 and is contained in [`opensearch-py==2.4.1`](https://github.com/opensearch-project/opensearch-py/releases/tag/v2.4.1).
- Reverts the pin on `opensearch-py` and increases the minimum version.
=> unpin opensearch-py

.github/workflows/pr-enforce-no-major-minor-master.yml, .github/workflows/pr-enforce-pr-labels.yml
We have several repositories where we want to enforce some label constraints on PRs.
This PR migrates these actions to shared workflows in https://github.com/localstack/meta.
These actions are only executed on _newly created_ PRs. The actions will only be triggered if the labels on a PR are changed.
So we still have to watch out for PRs which have already been created!
- Switch to shared workflows for:
- `pr-enforce-no-major-master.yml`
- `pr-enforce-pr-labels.yml`
- Introduce a new workflow (also using a shared one) to enforce that _neither_ `major` _nor_ `minor` labels are on the PR: `pr-enforce-no-major-minor-master.yml`.
- These changes were tested in another private org repo.
- After merging these PRs we have to disable the `pr-enforce-no-major-master.yml`, such that only the …
=> switch to shared pr label enforcers, add bugfix only action

localstack/services/sqs/constants.py, localstack/services/sqs/utils.py, tests/unit/test_sqs.py
The `is_sqs_queue_url()` utility relied on the `get_aws_account_id()` function, which is about to be deprecated and removed.
This PR reworks it to use dedicated regexes for each endpoint scheme.
=> SQS: Rework is_sqs_queue_url() utility

tests/aws/services/cloudwatch/test_cloudwatch_metrics.py, tests/aws/services/cloudwatch/test_cloudwatch_metrics.snapshot.json
While testing the pro-samples we found that lambda is not reporting the `Errors` metrics anymore. 
The metric should be reported when a lambda invocation fails.
We didn't have integration tests for lambda metrics yet, so I added those now.
/cc @joe4dev 
* added aws-validated tests
* skipping `test_lambda_invoke_error` for LS as it is currently not working -> this should be fixed 🙂
=> add cw tests for lambda Invocations and Errors metrics

localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3_api.py, tests/aws/services/s3/test_s3_api.snapshot.json
previously  `s3.get_object_tagging` worked on versioned buckets, without specifying an explicit `VersionId`
* localstack/services/s3/v3/provider.py::put_object_tagging sets tags version to `s3_object.version_id` if present
* localstack/services/s3/v3/provider.py::get_object_tagging uses `s3_object.version_id` if pesent
* small addtion to `tests/aws/services/s3/test_s3_api.py::TestS3BucketObjectTagging::test_object_tagging_versioned` to also exercise `put_object` with `Tagging` set on a versioned bucket
covered by `tests/aws/services/s3/test_s3_api.py::TestS3BucketObjectTagging::test_object_tagging_versioned`
=> fix get_object_tagging should work on versioned buckets without providing an explicit VersionId

localstack/services/stepfunctions/backend/execution.py
Pickling a boto client is currently not working and there's also no particular reason it should. Before we were saving the events client and when trying to pickle it, it was throwing an Exception when failing to pickle the SSLContext object.  With this PR we avoid this situation by just not saving the reference to the client in the stored `Execution` object.
Companion to https://github.com/localstack/localstack-ext/pull/2360
- Replace property with internal function. The client access is cached anyway, so there's no particular performance downside.
Needs access to the -ext repo. Run https://github.com/localstack/localstack-ext/pull/2360 with pro enabled and start an execution of any state machine (or run any integration test involving a step function). 
Manually verified this to be …
=> Fix execution storage for new stepfunctions provider

localstack/services/apigateway/helpers.py, localstack/services/apigateway/provider.py, tests/aws/services/apigateway/test_apigateway_api.py
Botocore exception for integer casting on empty strings when changing API gateway's minimum compression size from 0 to disabled.
- not allowing minimum compression size to be an empty string
- add some get api calls after update operations during tests
=> Fix int exception for API GW

localstack/services/cloudwatch/cloudwatch_database_helper.py, localstack/services/cloudwatch/provider_v2.py, tests/aws/services/cloudwatch/test_cloudwatch.py
wip, adding sqlite for storing metrics, 
started with:
* adding sqlite tables
* added `cloudwatch_database_helper` class where we will run all the queries
* started with `add_metric_data` -> only for single value metrics
* started `get_metric_data_stat` -> several TODOs left (see TODO section)
Follow-up Tasks + TODOs
=> add sqlite for metric storage cloudwatch v2

setup.cfg
With 815d6c77245e3ebfb9d298a70fe16bd12df032f7 we pinned `botocore` to version `1.31.85` to prevent incompatibilities with `moto`.
These issues were fixed in https://github.com/getmoto/moto/pull/7030.
This PR will coordinate the update of `botocore` to the newest version, once we have the `moto` fix in, which might be addressed in https://github.com/localstack/localstack/pull/9624.
- Remove the pin on `botocore` and update the minimum version.
- We have lots of tests in place and `botocore` used basically everywhere. If we're green, we're fine. :)
- Also tested integration with Pro. 💚
=> unpin botocore, update minimum version

localstack/services/iam/resource_providers/aws_iam_instanceprofile.py
This resource provider is not returning the correct status after the deletion which causes depending resources to fail during the deletion of a stack. cc/ @dominikschubert 
Returns correct event
=> corrects status for instance profile resource provider

localstack/services/internal.py, tests/bootstrap/test_strict_service_loading.py
This PR removes the service alias for SQS to support the old `query` protocol from the health endpoint (because it's not its own AWS service, just an alias for an existing service used to distinguish between the routing and allow loading a separate spec).
Explicitly removes `sqs-query` from the health endpoint as a temporary workaround (until the "service alias" has been removed again).
/cc @Pive01
=> remove sqs-query from health endpoint

localstack/services/apigateway/integration.py, localstack/utils/aws/resources.py, tests/aws/services/apigateway/test_apigateway_basic.py
The purpose of this PR is to enhance the stability of apigateway's integration with kinesis with multi-accounts and multi-regions. The main issue addressed is to introduce a proper IAM role required for the integration of these services. 
This PR introduces the use of role arn when integrating kinesis with apigateway and add `credentials` field to the api gateway `put_integrations` api.
The tests were failing previously when executed with a non-default account ID, set through environment variables (`TEST_AWS_ACCOUNT_ID=111111111111`, `TEST_AWS_ACCESS_KEY_ID=111111111111`, `TEST_AWS_REGION=us-west-1`). The affected tests are:
`tests.aws.services.apigateway.test_apigateway_basic.TestIntegrations.test_api_gateway_kinesis_integration`
=> apigateway: add IAM role to apigateway integration with services

localstack/aws/mocking.py
With a recent botocore update, we broke our collect-not-implemented operation in -ext.
Especially, the `transfer.ListTagsForResource` operation had issues, due to an arn pattern in the spec of `arn:\\S+`, which is not usable for generation.
* Add pattern `arn:\\S+` to sanitation list.
* Remove empty leftover files of lambda cleanup (sneaked those in here)
=> fix transfer.ListTagsForResource collect not implemented call

localstack/testing/snapshots/prototype.py, localstack/testing/snapshots/transformer.py, tests/unit/utils/testing/test_snapshots.py
This PR addresses an issue in the snapshot tests mechanism, specifically when dealing with dictionaries containing lists with non-homogeneous elements. An example scenario is shown below:
```python
d = {"key1": [{"key2": "value1"}, "value2", 3]}
snapshot.map("test_generic", d)
```
The proposed changes address the issue by altering the approach to parsing dictionaries containing lists. Instead of assuming the data type based on the first element of the list, this update ensures that the data type of each element in the list is checked and handled appropriately.
- added test case for testing out the supported element
=> fix: support for non-homogeneous lists

localstack/services/sns/provider.py, tests/aws/services/sns/test_sns.py, tests/aws/services/sns/test_sns.snapshot.json
Some users had issues with region in another issue, but their trace logs showed another issue badly handled by SNS when the topic didn't exist and wasn't properly checked. 
Added better check and a AWS validated test when trying to publish from another region.
=> fix SNS publish across region exception

localstack/http/request.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/unit/http_/test_request.py
As raised by #9723, when supplying a path only starting with double slashes, `get_raw_path` does not parse it properly, it returns an empty `.path` property. 
If `RAW_URI` contains only a path, `get_raw_path` does need to call `urlparse`, we can manually strip the query string and return the path from it. 
- manually return the path from `RAW_URI` if it starts with a double slashes
- add S3 tests in virtual host mode which validates the fix for the legacy provider (calling `get_raw_path` when rewriting the URL) 
- add a unit test
=> fix get_raw_path with double slash prefix path for legacy v-host S3

localstack/services/cloudformation/scaffolding/__main__.py
While activating the pro resource providers in https://github.com/localstack/localstack/pull/9601 I neglected to read the `pro` flag from the command line arguments when rendering the plugin file. This means that we will get conflicting plugin namespaces which has an undefined load order. To get around this, we chose to add a new namespace for the pro plugins, and load the plugins in priority order (pro first). This feature has not worked correctly!
In the companion PR in the pro repo, I migrate the current plugins to this new namespace.
cc @Morijarti 
* Read the `--pro` flag from the environment when rendering the plugin file
=> CFn: render ext providers with correct plugin namespace

localstack/services/stepfunctions/resource_providers/aws_stepfunctions_statemachine.py, tests/aws/services/stepfunctions/v2/test_sfn_api.py, tests/aws/services/stepfunctions/v2/test_sfn_api.snapshot.json
This pull request addresses the absence of support for CloudFormation Definition fields in JSON and YAML stack definitions in the current StepFunctions implementation. The proposed changes include support and tests for the four valid combinations: JSON with Definition, JSON with DefinitionString, YAML with Definition, and YAML with DefinitionString.
Closes #5204
Added support for Definition extraction in StepFunctions's resource_provider, and the 4 relevant tests.
=> [SFN] Support for CF Definition fields

localstack/services/stepfunctions/asl/utils/boto_client.py
Invocations of service integrations in SFN v2 currently trigger the default behaviour of boto for connection and read timeouts, as well as the retry strategy. This could potentially disrupt the State Machine's behaviour related to timeout and retry declarations.
Closes #9731 
This pull request deactivates the mentioned boto behaviour to guarantee that timeout issues are passed upstream to the interpreter as intended.
=> [SFN] Fix optimised integrations clients leading to timeouts and retries 

localstack/services/cloudwatch/resource_providers/aws_cloudwatch_alarm.py, localstack/services/cloudwatch/resource_providers/aws_cloudwatch_compositealarm.py, tests/aws/services/cloudformation/resources/test_cloudwatch.py, tests/aws/services/cloudformation/resources/test_cloudwatch.snapshot.json, tests/aws/templates/cfn_cw_composite_alarm.yml, tests/aws/templates/cfn_cw_simple_alarm.yml
The cloudwatch resource providers were found to be unusable. After researching it seems that the pipeline never failed for the migration PR due to the lack of tests.
- Resource Providers for AWS::Cloudwatch::MetricAlarm and AWS::Cloudwatch::CompositeAlarm now considers more parameters and also considers that not all parameters are mandatory.
- snapshoted test that validates the creation and  the deletion of  the resources
- snaphoted test for an alarm with no statistic
CC: @thrau @Morijarti
=> fix cloudwatch resource providers

localstack/aws/api/s3/__init__.py, localstack/aws/spec-patches.json, localstack/constants.py, localstack/services/s3/provider.py, localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json
While fixing a test case: `test_put_bucket_logging_wrong_target` for multiple accounts and regions in #9713, found AWS parity issues with parameters of `CrossLocationLoggingProhibitted` exception. 
This PR: 
- updates the exception `CrossLocationLoggingProhibitted` with `SourceBucketLocation`.
- update the raised exceptions in the `PutBucketLogging` handler. 
- validates the change with `test_put_bucket_logging_cross_locations` test case.
=> s3: add SourceBucketLocation for CrossLocationLoggingProhibitions exception

localstack/aws/handlers/auth.py, localstack/constants.py, localstack/services/apigateway/integration.py, localstack/utils/aws/aws_stack.py, localstack/utils/aws/request_context.py, localstack/utils/testutil.py, tests/aws/services/apigateway/test_apigateway_basic.py, tests/aws/services/cloudformation/resources/test_cdk.py, tests/aws/services/cloudwatch/test_cloudwatch.py, tests/aws/services/kinesis/test_kinesis.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3_cors.py, tests/aws/services/secretsmanager/test_secretsmanager.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sts/test_sts.py, tests/integration/test_security.py, tests/unit/test_dynamodb.py, tests/unit/test_partition_rewriter.py
This PR removes the long deprecated `HEADER_LOCALSTACK_ACCOUNT_ID`. It was used by the old `aws_stack.connect_to_service()` client to pass the Account ID of origin caller. 
We have since moved to the new client `connect_to()` which is more intelligent with cross-account calls by passing the appropriate IAM credentials in the process.
- Remove all use of `HEADER_LOCALSTACK_ACCOUNT_ID`
- Make the `mock_aws_request_headers()` use the current method of detecting internal calls
- Move the `mock_aws_request_headers()` to `localstack.utils.aws.request_context` to avoid a circular import. It also makes sense to group the AWS request related functions together - and this module already has `mock_request_for_region()`
=> Remove HEADER_LOCALSTACK_ACCOUNT_ID

setup.cfg
The `localstack-client` package used to define some of the core internals of LocalStack, particularly the service endpoints. This is a leftover from before we handled all requests through the single edge port 4566. Now that we don't use per-service ports, we have no need for the `localstack-client` package.
This PR has been open for a while, where previous changes removed the usage from within the Python code base itself. However, after rebasing recently I found no usages of the package in the code itself. The only change remaining is to stop installing the package. It is currently in the list of dependencies to support usage in -ext (arguably the dependency should have been moved there at some point, but it's not important), so we can remove it from this repo.
=> Remove localstack client dependency

localstack/services/stepfunctions/asl/component/intrinsic/function/statesfunction/string_operations/string_split.py, tests/aws/services/stepfunctions/templates/intrinsicfunctions/intrinsic_functions_templates.py, tests/aws/services/stepfunctions/templates/intrinsicfunctions/statemachines/string_operations/string_split_context_object.json5, tests/aws/services/stepfunctions/v2/intrinsic_functions/test_string_operations.py, tests/aws/services/stepfunctions/v2/intrinsic_functions/test_string_operations.snapshot.json
For the current implementation of the SFN interpreter, the Intrinsic Functions States.StringSplit does not filter for non-empty strings after computing the parts. This PR addresses such behaviour by filtering for empty string results.
Closes: #9742 
Added empty string filtering after computing the split parts in the implementation for States.StringSplit, and a number of relevant test cases
=> [SFN] Enhancements for Intrinsic Function StringSplit

localstack/services/sns/resource_providers/aws_sns_topic.py, tests/aws/services/cloudformation/resources/test_sns.py, tests/aws/services/cloudformation/resources/test_sns.snapshot.json
This will fix #9741, it's also related to a support case I am working on. During the migration to the new cfn provider, the usage of `canonicalize_bool_to_str` had been removed. 
Re-introduce using `canonicalize_bool_to_str` for the Topic Attributes, to enable creating Fifo Topic. 
Also updated the logic for creating names if not provided in case the topic is fifo.
=> fix AWS::SNS::Topic canonicalizing bool to str for Attributes

localstack/services/lambda_/provider.py, tests/aws/services/lambda_/functions/lambda_invocation_type.py, tests/aws/services/lambda_/test_lambda.py, tests/aws/services/lambda_/test_lambda.snapshot.json
Lambda provisioned concurrency misses a test for synchronous invokes with spillover from provisioned concurrency into on-demand instances. Related to the issue report https://github.com/localstack/localstack/issues/9658 (which is not a bug but highlights some testing deficit).
Why not:
* The synchronous test `test_provisioned_concurrency` already covers the prefer-provisioned-concurrency scenario but misses spillover
* The asynchronous test `test_reserved_concurrency_async_queue` covers a very similar scenario using async events
* Add a dedicated test for synchronous invokes with spillover from provisioned-concurrency into on-demand concurrency.
* Enable a previously skipped concurrency type assertion (now implemented)
* Fix reserved concurrency update exception when a reserved …
=> Test lambda provisioned concurrency scheduling

localstack/services/apigateway/context.py, localstack/services/apigateway/router_asf.py, localstack/utils/strings.py, tests/unit/http_/test_router.py
The RAW_URI can contain a path with a double slash for example, for the request ` https://28e9f096.execute-api.localhost.localstack.cloud:4566//hello`, RAW_URI will be `//hello`. 
This will cause an issue parsing the url using the function `urlparse`. With this fix, we replace `//` with `/` to proceed with the parsing.
Normalizes the RAW_URI by replacing the `//` with `/`. It does it in two places, on the `http` package and on the apigateway `router_asf`.
Unit tests for the specific parsing function.
=> Fix for double-slash uri request

localstack/utils/aws/aws_stack.py
Use of subscriptable types broke CLI tests in for older Python version, specifically the **cli-tests (3.8)** job.
This PR makes use of backward-compatible type hints.
=> fix type hints incompatible with python < 3.10 in aws_stack

localstack/services/apigateway/provider.py, tests/aws/services/apigateway/test_apigateway_api.py, tests/aws/services/apigateway/test_apigateway_api.snapshot.json
We had a support case where the user was having issue with the `HTTPS_PROXY` integration type. After some investigation, it looked like it didn't exist in AWS either. We need validation early so that it would fail when setting up infrastructure and not when actually calling the `execute-api` endpoint.
Add validation for `IntegrationType` in `PutIntegration`, and write a small snapshot test.
=> add APIGW PutIntegration IntegrationType validation

localstack/constants.py, localstack/services/s3/utils.py, localstack/services/s3/v3/provider.py
When using values other than `000000000000` for account ID or `us-east-1` for region, `test_s3_bucket_encryption_sse_kms_aws_managed_key` test should still create the consequent resources in the corresponding accounts and region.
This PR adds `account_id` when creating kms key for s3 bucket encryption in `create_s3_kms_managed_key_for_region` and the remaining modifications involve propagating the `account_id` value to the relevant functions.
=> fix kms key creation for s3 encryption

localstack/aws/accounts.py, localstack/aws/connect.py, localstack/aws/handlers/auth.py, localstack/aws/handlers/legacy.py, localstack/aws/proxy.py, localstack/utils/aws/aws_stack.py, localstack/utils/aws/request_context.py
This PR is the culmination of months of refactoring efforts!
We are finally deprecating and removing `aws_stack.get_region()` and `get_aws_account_id()` (and few other functions that rely on the thread-local storage).
Thanks for patiently reviewing all the PRs folks! cc: @alexrashed @baermat @bentsku @dfangl @dominikschubert @giograno @joe4dev @MEPalma @steffyP @thrau @whummer
=> Remove thread-local region, access key and account ID

localstack/utils/time.py
This PR adds util functions for time operations used in https://github.com/localstack/localstack-ext/pull/2392.
Added two new functions
- `iso1806_to_epoch`: to get epoch from iso1806 time string
- `epoch_to_iso1806`: to get iso1806 time string from epoch time
Tests for validating this is added in - https://github.com/localstack/localstack-ext/pull/2392.
=> added util function for time

tests/aws/services/lambda_/test_lambda_common.py
While attempting to run the Lambda runtime tests using the kubernetes executor against a k8s cluster (https://github.com/localstack/ls-on-k8s-testing/pull/1) we found that the Lambda runtime tests were being skipped. The skip condition was checking for a system architecture of `x86_64` but the helper method used (`localstack.utils.platform.get_arch`) standardises the name to return `amd64` meaning that even on a supported test architecture, the tests are being skipped.
* Update the skip condition to allow for test execution on x86_64
=> Update Lambda runtime test skip condition

.gitignore, localstack/testing/pytest/snapshot.py, localstack/testing/snapshots/prototype.py, tests/unit/utils/testing/test_snapshots.py
A useful util for debugging snapshots. RAW snapshots are the RAW untransformed recorded content . In contrast to normal snapshots these should not be committed (see gitignore) and should only be used for debugging & exploration purposes.
- Introduces **RAW snapshot mode**: Set `SNAPSHOT_RAW=1` or use the CLI argument `--snapshot-raw` to enable this mode. When enabled it will save a separate JSON file next to the normal snapshots with the "raw", i.e. untransformed recorded contents.
Set `SNAPSHOT_RAW=1` and execute a snapshot test
=> Add option to capture raw snapshots when running tests

localstack/services/cloudformation/engine/entities.py, localstack/services/cloudformation/provider.py, localstack/services/cloudformation/stores.py, tests/aws/services/cloudformation/api/test_changesets.py, tests/aws/services/cloudformation/api/test_changesets.snapshot.json, tests/aws/services/cloudformation/api/test_stacks.py, tests/aws/services/cloudformation/api/test_stacks.snapshot.json
Tackling the issue where we couldn't  cycle between deleting and creating stacks with the same name. E.g. doing a CDK deployment, deleting the stack and then doing another deployment which will typically use the same name again.
Resolves https://github.com/localstack/localstack/issues/7699
- Improved handling of stack ARN for `StackName` parameter in `CreateStack` and `CreateChangeSet`
- Creating multiple stacks with a single name are allowed now, as long as only one is an active state (i.e. not deleted).
- this should work for both `CreateStack` and `CreateChangeSet` now
- Better handling of Stack in `REVIEW_IN_PROGRESS`
- Added tests covering a few scenarios involving deleted
- Fixed `test_stack_lifecycle` which was implicitly depending on a stack being in `DELETE_IN_PROGRESS` and when …
=> Support creation of CloudFormation stacks with the same name after deletion

localstack/services/stepfunctions/asl/component/state/state.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/itemprocessor/map_run_record.py, localstack/services/stepfunctions/asl/eval/event/event_history.py, localstack/services/stepfunctions/backend/execution.py, localstack/services/stepfunctions/backend/state_machine.py, localstack/services/stepfunctions/provider.py, tests/aws/services/stepfunctions/templates/base/base_templates.py, tests/aws/services/stepfunctions/templates/base/statemachines/pass_start_time_format.json5, tests/aws/services/stepfunctions/v2/base/test_base.py
Resolves https://github.com/localstack/localstack/issues/9695
The returned string needs to look like this: "2023-11-21T06:27:31.545Z" which is not the default isoformat which we've been using previously. It also seems like AWS always returns UTC timestamps as far as I can see.
- Changes format of serialized timestamp for execution start and end date.
- Explicitly use UTC everywhere when creating timestamps to hopefully avoid any future issues.
=> Fix StepFunctions execution date formatting

localstack/utils/bootstrap.py, localstack/utils/docker_utils.py, tests/cli/test_cli.py
When starting LocalStack in Docker mode with the CLI, if the Docker image is not present we used to print "Pulling container image" to indicate that the Docker image was being pulled.
Since #9049, we instead start the DNS server first. To do this, we check if we can publish port 53 to the host, implemented via `container_ports_can_be_bound`. This in turn tries to run a docker image with the publish flag `-p 53`:
https://github.com/localstack/localstack/blob/c3348f842a875a9f7ba025ecaebb5f4bbdaac896/localstack/utils/docker_utils.py#L150-L156
We use the LocalStack docker image to check for port publishing, so we end up pulling the Docker image (silently) first before calling `ensure_container_image` which prints the "Pulling container image" message.
Possibly related: …
=> Fix missing "Pulling container image" message from CLI startup

localstack/aws/scaffold.py
This PR addresses a small issue when the scaffold is used to generate a recursive `TypedDict`.
- Automatically use forward references if members of a typed dict have the type name as the typed dict itself.
=> fix recursive types when generating TypedDicts

localstack/services/firehose/provider.py, localstack/utils/kinesis/kinesis_connector.py, tests/aws/services/firehose/test_firehose.py, tests/aws/services/kinesis/test_kinesis.py, tests/aws/test_integration.py
This PR adds support for multi account to tests
- `test_kinesis_firehose_elasticsearch_s3_backup`
- `test_delivery_stream_with_kinesis_as_source`
- `test_lambda_streams_batch_and_transactions`
- `test_run_kcl`
- `test_firehose_s3`
- `test_firehose_kinesis_to_s3`
- `test_lambda_streams_batch_and_transactions`
- `test_scheduled_lambda`
- Passed correct account id value through env for kcl process.
- Added correct account id in IAM role
The tests were failing previously when executed with a non-default account ID, set through environment variables (TEST_AWS_ACCOUNT_ID=111111111111, TEST_AWS_ACCESS_KEY_ID=111111111111, TEST_AWS_REGION=us-west-1). The affected tests are:
- `tests.aws.services.firehose.test_firehose.TestFirehoseIntegration.test_kinesis_firehose_elasticsearch_s3_backup`
- …
=> fixed account id for firehose integration

localstack/services/sqs/resource_providers/aws_sqs_queue.py
During a support case, it appeared we were not supporting updating SNS subscriptions with an SQS queue. The resolving of the queue was failing in CFN, multiple resources were waiting on it: SQS Queue Policy and SNS Subscriptions.
They were dependent on it with the following:
```json
"Resource": {
"Fn::GetAtt": [
"testqueuequeuefifo81DD86F9",
"Arn"
]
}
```
After looking into `AWS::SQS:Queue`, it seems the update called was returning the `desired_state` only, but this was lacking the `Arn` field, so the resolving failed. I don't know if this is the right way of fixing this, and I have no idea how to test it. \cc @dominikschubert could you maybe suggest something?
=> fix AWS::SQS::Queue update missing QueueArn and QueueUrl

tests/aws/services/cloudwatch/test_cloudwatch.py
When using values other than `000000000000` for account ID or `us-east-1` for region, `cloudwatch` tests should still create the consequent resources in corresponding accounts and region.
This PR fixes all the failing tests `tests.aws.services.cloudwatch.test_cloudwatch.TestCloudwatch.test_dashboard_lifecycle` by replacing the static value of region `us-east-1` with `TEST_AWS_REGION_NAME`. 
The tests were failing previously when executed with a non-default account ID, set through environment variables (`TEST_AWS_ACCOUNT_ID=111111111111`, `TEST_AWS_ACCESS_KEY_ID=111111111111`, `TEST_AWS_REGION=us-west-1`).
=> fix: fix failing dashboard lifecycle test for multi-account and region

localstack/services/cloudformation/engine/template_deployer.py, tests/aws/services/cloudformation/api/test_nested_stacks.py, tests/aws/services/cloudformation/engine/test_conditions.py, tests/aws/templates/nested-stack-conditions.nested.yaml, tests/aws/templates/nested-stack-conditions.yaml
Resolves https://github.com/localstack/localstack/issues/9628
The inital report was a bit misleading since this also fails for a normal stack deployment, i.e. it doesn't just affect nested stacks.
- Evaluate conditions on stack outputs and if they evaluate to false, drop them.
=> Add support for conditions on CFn stack outputs

localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py
As reported here: https://discuss.localstack.cloud/t/nosuchbucket-error-when-copying-file/640
The user had an issue where the bucket was created by another account, and he would then try to call `CopyObject` on it. 
I don't really have the setup for testing multi-account against AWS, but it feels like as S3 buckets are global, this should be possible and only a matter of IAM permission / ACL. 
https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html
- make `CopyObject` use cross-account access while getting the S3 buckets
- add a multi account test for it
=> add cross-account for CopyObject

localstack/constants.py, localstack/testing/scenario/cdk_lambda_helper.py, tests/aws/scenario/note_taking/functions/createNote.js, tests/aws/scenario/note_taking/functions/deleteNote.js, tests/aws/scenario/note_taking/functions/getNote.js, tests/aws/scenario/note_taking/functions/listNotes.js, tests/aws/scenario/note_taking/functions/updateNote.js
When using values other than `000000000000` for account ID or `us-east-1` for region, scenario tests should still create the consequent resources in corresponding accounts and region. When we try to upload lambas using non-default region value in scenario tests it throws `BucketAlreadyOwnedByYou` exception. 
This PR: 
- handles this exception and doesn't try to recreate the bucket if the existing bucket has the same owner for non-default region in `_upload_to_s3` helper function. 
- replaces static region value `us-east-1` from environment variables. 
The tests were failing previously when executed with a non-default account ID, set through environment variables (`TEST_AWS_ACCOUNT_ID=111111111111`, `TEST_AWS_ACCESS_KEY_ID=111111111111`, `TEST_AWS_REGION=us-west-1`). This PR fixes: …
=> fix: handle BucketAlreadyOwnedByYou exception when uploading lambda in scenario test cases 

localstack/constants.py, tests/aws/services/lambda_/functions/lambda_s3_integration_presign.js, tests/aws/services/lambda_/functions/lambda_s3_integration_sdk_v2.js, tests/aws/services/s3/test_s3.py
This PR adds support for multi account to tests
- `test_presigned_url_v4_x_amz_in_qs`
- `test_presigned_url_v4_signed_headers_in_qs`
- `test_s3_copy_md5`
- Updated lambda functions to use correct access key and secret keys (passed from env)
- Created custom s3 client to use `s3_v4` for presign url generation
The tests were failing previously when executed with a non-default account ID, set through environment variables (TEST_AWS_ACCOUNT_ID=111111111111, TEST_AWS_ACCESS_KEY_ID=111111111111, TEST_AWS_REGION=us-west-1). The affected tests are:
- `tests.aws.services.s3.test_s3.TestS3PresignedUrl.test_presigned_url_v4_x_amz_in_qs`
- `tests.aws.services.s3.test_s3.TestS3PresignedUrl.test_presigned_url_v4_signed_headers_in_qs`
- `tests.aws.services.s3.test_s3.TestS3PresignedUrl.test_s3_copy_md5` …
=> fix s3 presign tests for multi account support

localstack/services/sqs/provider.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.snapshot.json
Related discussion in https://github.com/localstack/localstack/pull/9710#discussion_r1419321271
> For empty lists, AWS often omits the field entirely, independent of the protocol. I noticed this behavior recently while parity testing different SDK versions (which use different protocols) in the Lambda multiruntime tests.
> I moved my Notion testing page to the SQS service to demonstrate the behavior for the listQueues operation (see [here](https://www.notion.so/localstack/SQS-SDK-parity-testing-164bfb9dbdd541928fd2b2abc275bac7?pvs=4)).
This behavior is independent of the protocol (both query + json).
* Add AWS-validated test scenario with queue prefix matching that returns an empty result
* Omit the `QueueUrls` in the API response for empty results.
=> Fix AWS parity for SQS list queues with empty response

Makefile
When running `make entrypoints`  the following line is printed:
```bash
test -s localstack_core.egg-info/entry_points.txt || (echo "Entrypoints were not correctly created! Aborting!" && exit 1)
```
This line does not indicate an error, but is `make` printing the command before running it. Some users do not check the exit code of the process, and assume that this message is an error.
* Prefix the line with `@` so it is not printed before running the command. This way the error message is only printed on failure, which is more useful and less worrying for new users.
=> Prevent error message being shown with entrypoints command

localstack/dns/server.py, tests/unit/test_dns_server.py
When resolving DNS names, if someone adds a more specific entry to an existing entry with a wildcard, the more specific name is not matched. For example:
```
ADD foo.example.com 1.2.3.4
ADD *.example.com 5.6.7.8
dig foo.example.com => 5.6.7.8
dig bar.example.com => 5.6.7.8
```
A request to `foo.example.com` should resolve to `1.2.3.4`
Look up the DNS name by string, which is what we store in the `add_host` method
=> Fix: lookup more specific DNS names directly

setup.cfg
In `docker-py` version 7.0.0 the automatic installation of `websocket-client` was removed. We require `websocket-client` in our tests as we test our websocket support there, however automatically updating docker to 7.0.0 (from 6.1.3) has removed this dependency for us.
Explicitly install `websocket-client` in our `tests` extra
=> Install websocket-client as it is no longer included with docker client

Makefile
In https://github.com/localstack/localstack/pull/9827 we prevented printing the line with "Aborting" in it to stop showing it as it is confusing to see as `make` prints the command, however the comment above it "# make sure that the entrypoints were correctly created and are non-empty" now sounds like an instruction, so we should comment it out.
Also comment out the instruction sounding comment
=> Skip comment for entrypoints line

localstack/services/lambda_/provider.py, tests/aws/services/lambda_/test_lambda_api.py, tests/aws/services/lambda_/test_lambda_api.snapshot.json, tests/aws/services/lambda_/test_lambda_common.py
The `FunctionName` in the Lambda `CreateFunction` operation is currently not validated and cannot handle function ARNs.
The [AWS API reference](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-FunctionName) describes that the operation can accept the following options for `FunctionName`:
* Function name – my-function.
* Function ARN – arn:aws:lambda:us-west-2:123456789012:function:my-function.
* Partial ARN – 123456789012:function:my-function.
This issue came up in a support case where a function ARN crashed in the `event_manager.py` because it tried to create an SQS queue with an invalid name (containing `:`).
* Add AWS-validated tests for exceptions and valid function ARNs
* Fix validation of `FunctionName` for the Lambda `CreateFunction` …
=> Fix lambda function name validation for CreateFunction

localstack/testing/snapshots/prototype.py
Since we're not using transformers with raw snapshots, we need to make sure datetime objects are handled properly, otherwise `json.dumps` with the default JSON encoder will fail.
- Use `CustomEncoder` from our json utils to encode the response.
=> Fix serialization of content in raw snapshots

localstack/aws/protocol/parser.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json
This would fix #9837. We've had multiple iterations of this, we were still unquoting the key to compare with the `base_url` but there was no need for it, I think this was a remnant of pre-Werkzeug 3.0
- update the logic to be more resilient in the parser (proper splitting of the path, multiple trailing slashes...) 
- add more test cases
=> fix s3 key handling with trailing slash

localstack/constants.py, tests/aws/test_serverless.py
When using values other than `000000000000` for account ID or `us-east-1` for region, `serverless` tests should still create the consequent resources in these accounts and region. When we try to deploy the serverless setup using non-default region value in tests it throws `IndexError` or `AssertionError` since the setup wasn't getting deployed in the correct account.
This PR: 
- passes `AWS_ACCESS_KEY_ID` as an environment variable to [`serverless-localstack`](https://github.com/localstack/serverless-localstack). 
- deletes(later undos), the `AWS_PROFILE` env variable. 
- replaces queue name with queue arn while fetching queue url in method `sqs_queue_url_for_arn`.
- passes `logs_client` in `get_lambda_log_events`. 
The tests were failing previously when executed with a non-default …
=> fix: serverless failing multi-account/region tests

setup.cfg
It doesn't seem to break anything here yet but it technically could lead to the same kind of issues for users of community.
Recently the docker PyPI package was updated to 7.0.0 which started breaking integration tests in -ext with the following kind of exception:
```
docker.errors.DockerException: invalid tag 'localhost.localstack.cloud:4514/r-a9dfa6f4:latest': invalid reference format` anymore.
```
Change that was included in their `7.0.0` release: https://github.com/docker/docker-py/pull/3191
- pin `docker` dependency to `<7.0.0` to avoid the breaking change for now until we know how to circumvent this
=> pin docker dependency to <7.0.0

localstack/services/s3/utils.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json
As reported in #9857, we have an issue with S3 lifecycle configuration and tag filters when the object does not have tags.
- add a proper check when applying lifecycle configuration if the object tags are not `None` before trying to get attributes from it
=> fix S3 lifecycle tags filter

localstack/services/cloudwatch/cloudwatch_database_helper.py, localstack/services/cloudwatch/provider_v2.py, tests/aws/services/cloudwatch/test_cloudwatch.py, tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json
=> CW v2 Tests and small improvements 

localstack/cli/localstack.py, localstack/config.py, tests/unit/test_config.py
We are often utilizing config profiles for our testing setups. However, those need quite some duplication for common variables.
This PR will introduce the ability to specify multiple config profiles, which are all loaded.
Use a comma separated list of config profiles for the `CONFIG_PROFILE` environment variable.
```
CONFIG_PROFILE=profile1,profile2
```
Identically named environment variables specified in earlier profiles will be overridden by those in later profiles.
Configuration profiles will never override environment variables already set.
If profile1.env looks like this:
```
VAR1=test1
VAR2=test2
VAR3=test3
```
and profile2.env looks like this:
```
VAR3=override3
VAR4=test4
```
the finally set variables will look like this:
```
VAR1=test1
VAR2=test2
VAR3=override3
VAR4=test4
```
* …
=> Allow merging of config profiles

localstack/services/lambda_/provider.py, localstack/services/lambda_/resource_providers/aws_lambda_version.py, tests/aws/services/lambda_/test_lambda_api.py, tests/aws/services/lambda_/test_lambda_api.snapshot.json
Investigation started due to a bug report that turned out to not actually be a bug (Select/ Join intrinsic functions).
At its core it was trying to create an `AWS::Lambda::EventSourceMapping` resource targeting a partial ARN like `<function_name>:live` which we didn't properly handle in the underlying `CreateEventSourceMapping` handler in the lambda API provider.
- Adds a test which creates event source mappings with different structures for the `FunctionName` parameter.
- Add support for partial ARNs and other edge cases in `CreateEventSourceMapping`
- Fix `create` handler for `AWS::Lambda::Version` to properly wait for the function version to be active (cc @Morijarti ). This was causing flakes and is a regression introduced in the migration from the old to the new CFn providers.
=> Add support for partial ARNs for EventSourceMappings and fix AWS::Lambda::Version state check

localstack/constants.py, localstack/services/cloudwatch/provider.py
SNS requires the Boto client to be in the same region as the topic (See test introduced in https://github.com/localstack/localstack/pull/9679)
This PR fixes CloudWatch <> SNS integration which was broken and detected in https://github.com/localstack/localstack/pull/8204.
Detected by:
=> CloudWatch: Use SNS client with same region as topic

docker-compose-pro.yml, docker-compose.yml
Our official `docker-compose-pro.yml` fails to start if port `53` is already bound on the host system. This is a common issue on macOS due to this [known Docker for Mac issue](https://docs.docker.com/desktop/release-notes/#known-issues-2) or due to enabled [internet sharing](https://github.com/docker/for-mac/issues/7008#issuecomment-1748344545). The comment `# (required for Pro)` is also misleading because publishing port `53` is only required if you wish to use the LocalStack DNS server on the system host, which requires extra configuration anyway as documented [here](https://docs.localstack.cloud/user-guide/tools/dns-server/#system-dns-configuration). For example, simply pointing the system DNS leads to `127.0.0.1` without configuring the default upstream `DNS_SERVER` leads to an …
=> Simplify the official docker-compose.yml

localstack/services/route53/provider.py, tests/aws/services/route53/test_route53.py, tests/aws/services/route53/test_route53.snapshot.json
While investigating https://github.com/localstack/localstack/issues/9486 I discovered that `moto` does not populate the VPC information for private hosted zones. This PR both addresses this missing information and adds an AWS validated test for private hosted zones.
*Note*: the existing test `test_associate_vpc_with_hosted_zone` will not work on AWS since creating a private zone without specifying VPC parameters fails with a client error from `boto3`. Rather than updating that test, which tests additional things, I created a new test that focuses purely on the create response.
* Update `route53::create_hosted_zone` response to populate the VPC parameters if missing and when creating a private zone
* Add AWS validated test to capture responses
* Update `test_associate_vpc_with_hosted_zone` …
=> Fix: Route53 populating VPC fields

localstack/services/apigateway/helpers.py, tests/aws/files/openapi-http-method-integration.json, tests/aws/services/apigateway/test_apigateway_import.py, tests/aws/services/apigateway/test_apigateway_import.snapshot.json
As reported in #9804, we would not take into account the `httpMethod` when importing integration of `AWS` type.
- create a test to validate the use case
- update the helper to take the `httpMethod` field, and ignore it for different type of integration
Note: test failure is unrelated
=> fix APIGW import integration method for AWS integration type

localstack/config.py, localstack/services/kinesis/kinesis_mock_server.py
With recent kinesis performance tests, we have seen a significant performance degradation up to an out-of-memory error of kinesis-mock, especially when pushing over 50 entries with the maximum payload of 1024KB to a stream.
This behavior is way worse when the persistence is enabled when starting kinesis-mock. For now, to fix it for users not needing persistence, we need a flag to disable it.
In the future, we need to spend some work on increasing the performance and memory usage of the persistence of our kinesis implementation.
- Add flag to disable the persistence mechanism for kinesis, which is currently active regardless of cloud pods or persistence being used on the localstack level.
=> Add flag to disable kinesis-mock persistence

localstack/services/dynamodb/server.py, tests/aws/services/cloudformation/resources/test_lambda.snapshot.json
We've started seeing repeatable failures in CI due to a snapshot mismatch for `tests/aws/services/cloudformation/resources/test_lambda.py::TestCfnLambdaIntegrations::test_cfn_lambda_dynamodb_source`.
```
=================================== FAILURES ===================================
__________ TestCfnLambdaIntegrations.test_cfn_lambda_dynamodb_source ___________
>> match key: describe_table_result
(+)  /Table/DeletionProtectionEnabled ( False )
```
My investigation pointed towards a new update of DynamoDB local as the culprit ([AWS recently released a 2.2.0 version with support for Table delete protection](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocalHistory.html))
Was running into some issues with the initial PR in …
=> Update dynamodb snapshot to unblock pipeline

tests/aws/services/kinesis/test_kinesis.py
Using the AWS CLI, it is easily accomplished to have surrounding double quotes around the Shard Iterator of the `get_records` request.
Even though this is not technically correct, both the CLI and AWS allow this.
This PR will add a test for the behavior on LS side
Kinesis-mock issue: etspaceman/kinesis-mock#682
Upstream PR: etspaceman/kinesis-mock#689
* Add test for double quotes within shard iterator
=> Allow kinesis get_records shard iterator to have surrounding quotes

localstack/aws/app.py, localstack/aws/chain.py, localstack/aws/gateway.py, localstack/aws/handlers/__init__.py, localstack/aws/trace.py, tests/unit/aws/test_chain.py
In the persistence plugin (and perhaps elsewhere), we are using a pattern where we are acquiring locks in request handlers, and freeing them in response handlers, to lock certain things across a request invocation. This can lead to locks never being freed, when handlers (like the CORS enforcer) call `chain.terminate()`, which prevents response handlers from being called.
This PR introduces the concept of finalizers into the handler chain, which are *always* called, even if the chain is terminated. Obviously these should be used sparsely, and only run essential finalization code.
* Introduce the `finalizer: List[Handler]` attribute
* Re-formatted a bunch of docs to match the column limit of our black config
=> introduce request finalizers into handler chain

localstack/services/cloudwatch/cloudwatch_database_helper.py, localstack/services/cloudwatch/provider_v2.py
This adds the ability to reset the Cloudwatch v2 state cleaning the database  metrics tables.  
Related to localstack/localstack#9347
- removed unused functions in the cloudwatch_database_helper.py and their calls
- the shutdown function in the helper implements the query to reset their metrics tables and the index Autoincrement.
=> add reset feature to CW v2

README.md
It would be great to explicitly motivate users to upvote top [feature requests](https://github.com/localstack/localstack/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+) (currently including issues).
Active voice could sound a little more inviting than a noun-heavy phrase.
* Refine call for action to get in touch
* Add visual icons (using different skin tones)
* Add link to top [feature requests](https://github.com/localstack/localstack/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+)
Should we filter out issues in the sorted [feature requests](https://github.com/localstack/localstack/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+) view and only show "feature requests" and "enhancements"?
=> Refine get in touch readme

localstack/services/stepfunctions/asl/component/state/state_execution/state_parallel/branches_decl.py, tests/aws/services/stepfunctions/templates/scenarios/scenarios_templates.py, tests/aws/services/stepfunctions/templates/scenarios/statemachines/parallel_state_order.json5, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.py, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.snapshot.json
The SFN v2 interpreter currently outputs parallel state outputs in a per-branch reversed order. This PR addresses such behaviours.
Closes: #9881 
Fixed branch output sampling process to not be reversed.
=> [SFN] Fix Parallel State Output Ordering

localstack/config.py
Originally, with #9873 , I added an error message if a config profile cannot be found. However, this interfered with the usages of the config in CLI tools where the output might get parsed, like lpm, since it is always the case due to the default profile.
Since this error message has quite significant impact, it is best for now to remove it, and find out a better way to debug profile loading should the need arise.
I also thought about only suppressing it in the default case, but the potential impact would still outweigh the benefits in my opinion.
* Remove error output printed to stdout in case profile does not exist.
=> Remove error message if environment does not exist

.github/workflows/tests-cli.yml, localstack/testing/pytest/validation_tracking.py, localstack/testing/snapshots/prototype.py, tests/conftest.py
When creating tests we validate that they are passing successfully against AWS. This can change over time and so we need a way to have a sensible way to periodically re-evaluate this validation status.  In the future we can do this e.g. on a schedule where we re-validate any tests that haven't been validated in the last x (e.g. 12) months.
Earlier this year we started a similar effort on keeping snapshots up to date to avoid recurring issues where changes on AWS' side cause undetected issues. We can probably re-target the tools used there to instead track the validation date, since the snapshot update date can actually just stay the same until it really needs to be changed.
In the past a few of our team expressed interest in having this data available, so there you go :)
- Add new pytest …
=> Track date of last passed validation run of tests targeting AWS

localstack/services/apigateway/resource_providers/aws_apigateway_requestvalidator.py, tests/aws/services/cloudformation/resources/test_apigateway.py, tests/aws/services/cloudformation/resources/test_apigateway.snapshot.json, tests/aws/templates/apigateway_models.json
We've seen a regression from #9320 where optional parameters were accessed directly from the model in CloudFormation. Those parameters are marked as optional, and will default to `False`.
See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-requestvalidator.html
Access those parameters with `.get` instead of direct attribute access, and make default to `False`.
Update a test to not specify a `False` parameter to check that it still properly create the resource and default to `False`.
=> fix CFN RequestValidator parameters being optional

localstack/aws/handlers/service.py, localstack/aws/protocol/service_router.py, tests/aws/services/s3/test_s3.py
As reported in #9867, we have an issue when using S3 pre-signed URL from a browser encoding the request as `application/x-www-form-urlencoded` and targeting a default LocalStack endpoint and not the S3 specific one. The `ServiceNameParser` will try to determine the AWS service, and as S3 is the "fallback" service, it will go through the whole service detection, which includes accessing `request.values`. This will:
- consume the stream
- if you send binary data, as the request is form encoded, Werkzeug will try to parse the form and fail decoding it as `utf-8`. 
```python
File "/Users/benjaminsimon/Projects/localstack/localstack-ext/.venv/lib/python3.11/site-packages/werkzeug/formparser.py", line 284, in _parse_urlencoded
stream.read().decode(), …
```
=> fix S3 service name parsing consuming the stream

localstack/services/acm/provider.py, tests/aws/services/acm/test_acm.py, tests/aws/services/acm/test_acm.snapshot.json
As reported in [issue #9768](https://github.com/localstack/localstack/issues/9768) the current behavior does not fully match the aws cli behavior regarding a certificate valid for multiple domains. 
The expected response should reflect all domains in `SubjectAlternativeNameSummaries`.   
All additional domains in `SubjectAlternativeName` returned from moto should also be present in `SubjectAlternativeNameSummaries` when calling `aws acm list-certificates`
- added all additional domain to `SubjectAlternativeNameSummaries`
- updated parity snapshot to reflect the additional functionality
=> Fix: ACM: Additional domains missing from subject alternative names summaries

localstack/services/events/provider.py, tests/aws/services/events/test_events.py, tests/aws/services/events/test_events.snapshot.json
As reported in [#9711](https://github.com/localstack/localstack/issues/9711) the current behavior does not fully match the aws cli behavior regarding the EventBridge pattern `anything-but`  and a `null` value. 
This rule:
```
{
"source": ["core.update-account-command"],
"detail-type": ["core.update-account-command"],
"detail": {"command": [{"anything-but": ["no-message"]}]},
}
``` 
In combination with this message:
```
{
"version": "0",
"id": "<uuid:2>",
"detail-type": "core.update-account-command",
"source": "core.update-account-command",
"account": "111111111111",
"time": "date",
"region": "<region>",
"resources": [],
"detail": {
"command": null,
"payload": "baz"
}
}
```
does not match on LocalStack, but does correctly match on AWS.
The issue arises from using the default fallback of …
=> Fix: EventBus: match null value for anything-but rule

localstack/cli/localstack.py, tests/cli/test_cli.py
This PR exposes a CLI option to restart the LocalStack runtime, which is often required for development/testing/running demos.
=> add cli option to restart localstack container

localstack/services/cloudformation/resource_providers/aws_cloudformation_stack.py, tests/aws/services/cloudformation/api/test_nested_stacks.py, tests/aws/templates/nested-stack-conditions.yaml
This PR fixes a bug where the internal name generation used request ARN instead of name which caused invalid Cfn stack names to be generated leading to CDK deployment errors which were caught by Lambda provider input validation:
```
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateFunction operation: 1 validation error detected: Value 'arn:aws:cloudformation:us-eas-LogRetentionaae0aa3c5b4d-25486f2c' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\\d{1}:)?(\\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\\$LATEST|[a-zA-Z0-9-_]+))?
```
Amended an existing test to assert that stack name does not contain invalid chars (`:` which is found …
=> Cfn: Fix nested stack name generation

localstack/services/events/provider.py, tests/aws/services/events/test_events.py, tests/aws/services/events/test_events.snapshot.json, tests/aws/services/events/test_events.validation.json
As reported in #8512 and #7305 the current behavior does not fully match the aws cli behavior regarding the EventBridge pattern `{"exists": True}`.
This rule:
```
{
"source": ["core.update-account-command"],
"detail-type": ["core.update-account-command"],
"detail": {"key": [{"exists": True}]},
}
```
in combination with this message:
```
{
"version": "0",
"id": "<uuid:2>",
"detail-type": "core.update-account-command",
"source": "core.update-account-command",
"account": "111111111111",
"time": "date",
"region": "<region>",
"resources": [],
"detail": {
"key":"value",
"payload":"baz"
}
}
```
does not match on LocalStack, but does correctly match on AWS.
The issue arises from the prefix `exists` not being considered.
Furthermore, the opposite pattern `[("exists"): False]` was also not …
=> Fix: EventBus: Exists prefix not considered for rule matching

localstack/services/secretsmanager/provider.py, tests/aws/services/secretsmanager/functions/lambda_rotate_secret.py, tests/aws/services/secretsmanager/test_secretsmanager.py, tests/aws/services/secretsmanager/test_secretsmanager.snapshot.json
Secret rotation seemed to be completely broken.
- added patch for response so immediate rotation is optional
- added logic to set/enable rotation but do not run immediately
- Lambda invokation happens via LS instead of moto using the user's previously created Lambda
- fixed AWSCURRENT and AWSPENDING tag on same secret version, which is pretty common (we were failing on it)
- calculating next rotation date now
- skipping other lambda steps in rotation if lambda returns an error 
- in progress rotation exception is delayed after lambda trigger so we can give a chance to the lambda function to fix the state, in AWS the runs are scheduled until tags are fixed
- smoke test
=> Fix secret rotation in secretsmanager

localstack/services/s3/cors.py, tests/aws/services/s3/test_s3_cors.py, tests/aws/services/s3/test_s3_cors.snapshot.json, tests/aws/services/s3/test_s3_cors.validation.json
As reported in #9957, the header matching was case sensitive for the `AllowedHeaders` field for `OPTIONS` requests with the `Access-Control-Request-Headers` header.
Wrote a AWS validated test to verify the behavior and fixed the matching to now be case insensitive.
=> fix S3 CORS headers casing matching

localstack/config.py, localstack/services/sqs/models.py, localstack/services/sqs/provider.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.validation.json
A user noted in #3525 that we currently do not support the MessageRetentionPeriod of SQS queues. Basically, messages are deleted from queues after a period controlled by `MessageRetentionPeriod`.
From [the SQS docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SetQueueAttributes.html)
> MessageRetentionPeriod – The length of time, in seconds, for which Amazon SQS retains a message. Valid values: An integer representing seconds, from 60 (1 minute) to 1,209,600 (14 days). Default: 345,600 (4 days). When you change a queue's attributes, the change can take up to 60 seconds for most of the attributes to propagate throughout the Amazon SQS system. Changes made to the MessageRetentionPeriod attribute can take up to 15 minutes and will impact existing messages in the …
=> add SQS message retention period functionality

localstack/services/sqs/models.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.validation.json
Even after the initial implementation of FIFO message groups in #8238, users have reported odd behavior when using SQS FIFO queues related to message group visibility specifically that consumers are triggered although the message group is expected to be invisible #8724. This also affected lambdas triggered with fifo queues #7036.
This PR fixes the mechanism we were using to reset message group visibility, which was too general. It assumed that every message put into the message group reset its visibility, when really it should just be messages that were previously invisible, not new ones.
* message group visibility is no longer reset when new messages are sent to the queue
Fixes
* #8724
* #7036 (tested with #7037)
=> fix sqs message group visibility when sending messages

localstack/services/sqs/provider.py, localstack/utils/cloudwatch/cloudwatch_util.py, tests/aws/services/cloudwatch/test_cloudwatch_metrics.py, tests/aws/services/cloudwatch/test_cloudwatch_metrics.validation.json
Improving the sqs-metrics reporting for the "Approximate*" metrics, by collecting metric-data in batches before sending the data to cloudwatch. 
As a reminder: those are the metrics that are reported regularly (by default once every minute) for all queues.
* Collect the data of all queues in slices, before sending the batch to cloudwatch (previously we would call the cloudwatch-api three times for each queue)
* Added a new helper in `cloudwatch_util.py` to handle sqs-batched data
=> use batches to report SQS metrics for approximate query metrics

localstack/utils/net.py, tests/unit/utils/test_net_utils.py
Sometimes we want to only consider a subrange of a `PortRange`, while also sharing the port cache and port reservation status. This PR adds functionality for that. The need came up when constraining the dynamic port range to ports that are also valid container ports (different on some systems).
* add `PortRange.subrange` command that creates a new `PortRange` that is synced with the original object
=> add subrange operation for ports

localstack/aws/protocol/serializer.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.validation.json
This will fix #9930. The `Net::Amazon::S3` Perl client is making using of XML namespace to parse the responses (https://metacpan.org/module/Net::Amazon::S3::Operation::Objects::List::Response/source), but we didn't add them to S3 responses, as the current logic in the serializer is counting on the namespace being defined on the operation, but it's not in S3 specs.
- manually add the S3 namespace to the root tag of the S3 response
- add additional checks to a specific S3 test checking raw XML S3 responses, to validate the behavior is in line with AWS
=> fix S3 missing XML namespace

localstack/services/cloudwatch/alarm_scheduler.py, localstack/services/cloudwatch/provider.py, tests/aws/services/cloudwatch/test_cloudwatch.py, tests/aws/services/cloudwatch/test_cloudwatch_metrics.py, tests/aws/services/cloudwatch/test_cloudwatch_metrics.snapshot.json, tests/aws/services/cloudwatch/test_cloudwatch_metrics.validation.json
Fix for https://github.com/localstack/localstack/issues/8934: the alarm did not trigger for `SampleCount` statistics, and was throwing errors. 
The issue was caused by casing-mismatch - the metric query was send to moto using the statistic `Samplecount` but it's expecting an exact match. 
* fixed the casing issue
* added a snapshot test for the reported scenario (it relies on metrics automatically reported by SQS when a message is send)
* some cleanup and fixes revealed by snapshot test
=> fix cloudwatch alarm evaluation for SampleCount

tests/aws/services/cloudwatch/test_cloudwatch_metrics.py
Fix for test `test_alarm_number_of_messages_sent` introduced with #9978. 
The `snapshot.match` must be called after the assertions, currently seeing flakes with:
```
Exception: Key NumberOfMessagesSent-describe used multiple times in the same test scope
```
The snapshots are collected in the `_verify_alarm_triggered` which is called using `retry` and have two assertions.
* only call `snapshot.match` after assertions
=> fix snapshot match order

localstack/services/sqs/provider.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.snapshot.json, tests/aws/services/sqs/test_sqs.validation.json
This PR fixes #8570, where a user noted that the `MaximumMessageSize` constraint is not handled correctly for `BatchSendMessage` commands in SQS. 
* message size is now checked for each individual message in a batch
* batch errors are now populated using `ServiceException` parameters rather than generic `Exception` properties
Limitations:
* Because of the way error serialization works in SQS (query vs json rest protocol), we currently serialize the exception code as `InvalidParameterValueException` instead of `InvalidParameterValue`. The message is also slightly different from what AWS returns. fixing this limitation in a generic way is IMO not worth it at the moment, but happy to reconsider if this is a blocker for users.
=> fix SQS send batch message validation for message size

localstack/services/cloudwatch/provider.py, tests/aws/services/cloudwatch/test_cloudwatch.py, tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json, tests/aws/services/cloudwatch/test_cloudwatch.validation.json
AWS recently [added support for AWS Lambda as an alarm state action](https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-cloudwatch-alarms-lambda-change-action/). 
This PR enables Lambda targets for alarm actions on LocalStack. 
* added snapshot test, that triggers a lambda on state ALARM
* implemented the lambda invocation for LS
=> add lambda alarm action for cloudwatch

localstack/services/s3/utils.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json, tests/aws/services/s3/test_s3_api.py, tests/aws/services/s3/test_s3_list_operations.py
As reported with #9990, we had an issue when copying a file with a space in the name with Go. This issue was not present with Python however. When looking at the sample provided by the user, it appeared that Go in URL encoding space character with `+` when Python is using `%20`.
When calling `unquote` with Python, it won't replace an encoded URL `+` character with a space. We will need to manually replace it before unquote the URL to not accidentally replaced an encoded `+`. 
Manually replace an encoded URL `+` when parsing the `CopySource` header. 
Added 2 different AWS tests to verify exactly the fix:
- one global with weird key encoding as we didn't have one
- one very specific test for this use case using the HTTP client because botocore will automatically encode space as `%20` so we …
=> fix CopySource unquoting of special + char

localstack/services/sqs/models.py, localstack/services/sqs/provider.py, localstack/services/sqs/utils.py, localstack/testing/snapshots/transformer_utility.py, tests/aws/services/sqs/test_sqs_move_task.py, tests/aws/services/sqs/test_sqs_move_task.snapshot.json, tests/aws/services/sqs/test_sqs_move_task.validation.json
A user requested in #8471 the Amazon SQS API for "[dead-letter queue redrive](https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-sqs-dead-letter-queue-redrive-aws-sdk-cli/)" which was launched on June 8 2023. The feature consists of three operations:
1) [StartMessageMoveTask](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_StartMessageMoveTask.html), to start a new message movement task from the dead-letter queue;
2) [CancelMessageMoveTask](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CancelMessageMoveTask.html), to cancel the message movement task;
3) [ListMessageMoveTasks](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ListMessageMoveTasks.html), to get 10 most recent message movement tasks for a …
=> add SQS message move task feature

tests/aws/services/dynamodb/test_dynamodb.py, tests/aws/services/dynamodb/test_dynamodb.snapshot.json, tests/aws/services/dynamodb/test_dynamodb.validation.json
This PR arises from #9040.
When an operation (e.g., `PutItem` or `DeleteItem`) fails on DDB due to a conditional check, we can ask to receive back the items that failed the check with the `ReturnValuesOnConditionCheckFailure` set to `ALL_OLD`.
This feature was implemented in DynamoDBLocal version 2.2.0, released in December 2023, so we can now support it out of the box. This PR simply adds a snapshot test to verify the behavior.
- Adding a snapshot test to verify we return a set of items when `ReturnValuesOnConditionCheckFailure` is set to `ALL_OLD`.
=> snapshot test for return values on condition check failure

localstack/services/lambda_/provider.py, localstack/testing/pytest/fixtures.py, tests/aws/services/lambda_/test_lambda_integration_dynamodbstreams.py, tests/aws/services/lambda_/test_lambda_integration_dynamodbstreams.snapshot.json, tests/aws/services/lambda_/test_lambda_integration_dynamodbstreams.validation.json, tests/aws/services/lambda_/test_lambda_integration_kinesis.py, tests/aws/services/lambda_/test_lambda_integration_kinesis.snapshot.json, tests/aws/services/lambda_/test_lambda_integration_kinesis.validation.json, tests/aws/services/lambda_/test_lambda_integration_sqs.py, tests/aws/services/lambda_/test_lambda_integration_sqs.snapshot.json, tests/aws/services/lambda_/test_lambda_integration_sqs.validation.json
Fixes https://github.com/localstack/localstack/issues/9219, where a user noted that duplicate event source mappings are not handled correctly. Of course exception messages differ across services, because why make things consistent :wink: 
Tested for sqs, kinesis, and dynamodbstreams.
* lambda `create_event_source_mapping` now raises a `ResourceConflictException` if a mapping with the same event source arn and function arn already exists.
* added a `create_event_source_mapping` fixture that does cleanup
=> fix lambda create event source mapping duplicates

localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py
This might be a fix to #9989, I could not reproduce the issue yet, but I suspect this could be one of the reason: we did not detect the payload was of `aws-chunked` format. We once set the detection to only be about the `Content-Encoding`, but it introduced a regression for some client SDKs, I think it was .NET. See #8712
So we can combine both detection to be sure. 
Added a test with a similar format as the reported issue, with no signing of the chunked payload. 
Improved the detection to check both the content encoding of the request and the special header AWS uses to indicate it's an `aws-chunked` payload even when the content-encoding is not set.
=> improve S3 aws-chunked detection

localstack/constants.py
There have been requests to install the `analysis-kuromoji` plugin when setting up OpenSearch clusters (f.e. in [Discuss](https://discuss.localstack.cloud/t/opensearch-kuromoji-tokenizer-plugin/681)).
In fact, this plugin is [one of the plugins which is installed by default](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-plugins.html), and is therefore now added.
For now, I did not add all the plugins listed there, because this would increase the package download / setup time by quite a bit. If we decide to add all these packages, we should maybe consider switching to a different distribution (which already contains all of them - maybe there is one?).
- Adds the `analysis-kuromoji` plugin to the list of plugins installed for OpenSearch.
- There is already a …
=> add OpenSearch analysis-kuromoji plugin

localstack/services/cloudwatch/cloudwatch_database_helper.py, localstack/services/cloudwatch/provider_v2.py, tests/aws/services/cloudwatch/test_cloudwatch.py
Adds the raw-metrics endpoint for the cloudwatch v2 provider, which was introduced in #3535 (customer request). 
* in v1 the endpoint currently requires aws headers, which seems a bit odd
* for v2 removed this requirement, instead we also return the account-id and region for each datapoint
* it currently returns all the single-metric data (like it did before)  
In a future iteration we should decide if we want to keep this endpoint, and/or collect data about how many people are actually using it. 
Considering that a AWS header is currently required to access the endpoint, I don't think it is actually used (it defeats the actual purpose). 
In case we keep the endpoint:
=> add raw-metrics endpoint for v2

localstack/services/cloudwatch/cloudwatch_database_helper.py, localstack/services/cloudwatch/provider_v2.py, tests/aws/services/cloudwatch/test_cloudwatch.py, tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json, tests/aws/services/cloudwatch/test_cloudwatch.validation.json
This PR fixes two issues revealed by tests that concern the returned unit for `get-metric-statistics`:
1) the unit is returned, even if was not part of the query
2) if no unit is provided for the query, but there are several units that match, the result is aggregated on `unit`
* add a query-helper to retrieve the unique units that will match a query
* run the statistic for each unit, aggregate the returned result
* enhanced the test `get_metric_statistics_with_different_units` by adding also metric-data that does not have a `unit`
=> fix unit-handling for get-metric-statistics

localstack/aws/app.py, localstack/aws/chain.py, localstack/aws/handlers/__init__.py, localstack/extensions/api/aws.py, localstack/extensions/api/extension.py
The need has come up in extensions to be able to hook in custom exception handlers into the handler chain. Specifically, @ackdav needs this for the snowflake extension.
This PR extends the handler chain with a composite exception handler that can be used in the same way as other handlers, and adds an `update_exception_handlers` method to the `Extension` interface.
* the handler chain now has a composite handler for custom exception handlers
* the extension api now supports adding exception handlers into this composite
=> add extension mechanism for exceptions

localstack/aws/serving/asgi.py, localstack/aws/serving/edge.py, localstack/config.py, localstack/http/hypercorn.py
On very high (burst) load scenarios, we can get connection refused errors quite quickly, if there are no worker threads available.
We should make it configurable, to see if we can bypass some of them.
* Add config option `GATEWAY_WORKER_COUNT` to control maximum number of worker threads
=> Add config option to control maximum gateway worker thread count

localstack/services/lambda_/invocation/event_manager.py
Tiny refactoring to make it easier to instrument the poller with logging. This is for a quick instrumentation exception we are pushing out to a user.
* the block to retry a lambda without increasing the counter is now in its own method
=> refactor Poller.handle_message and extract process_event_retry

localstack/services/cloudwatch/cloudwatch_database_helper.py, tests/aws/services/cloudwatch/test_cloudwatch.py, tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json, tests/aws/services/cloudwatch/test_cloudwatch.validation.json
This PR addresses an essential aspect by introducing tests that specifically target unique and critical scenarios within Cloudwatch. The motivation behind this effort is to enhance the robustness and reliability of our codebase, ensuring comprehensive test coverage for cases that are both distinctive and significant.
- Implemented a test case for scenarios where the query lacks dimensions, but the data contains them.
- Adjusted the database helper to ensure the success of the first test.
- Added a test to cover scenarios where the query results in no data.
=> add more tests for cw v2

setup.cfg
We just discovered an issue in the CLI which can be triggered if you have an already existing, somewhat older environment and only upgrade the LocalStack packages.
The following script can be used to reproduce the issue:
```bash
cd /tmp
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install click==7.0.0
python3 -m pip install localstack
localstack
```
This results in the following error:
```
File "/tmp/.venv/bin/localstack", line 23, in <module>
main()
File "/tmp/.venv/bin/localstack", line 19, in main
main.main()
File "/tmp/.venv/lib/python3.11/site-packages/localstack/cli/main.py", line 17, in main
cli()
File "/tmp/.venv/lib/python3.11/site-packages/localstack/cli/plugin.py", line 15, in __call__
self.group(*args, **kwargs)
File …
```
=> fix CLI issue with outdated click version

localstack/config.py, localstack/services/dynamodb/models.py, localstack/services/dynamodb/provider.py, tests/aws/services/dynamodb/test_dynamodb.py
This PR implements the Time to Live feature in DynamoDB, as reported in #10022.
- We added a `ExpiredItemsWorker` class in the DDB provider that schedules a thread removing the stale keys across all the tables that define an enabled TTL specification. It uses a `Scheduler` under the hood and runs every hour. We could make the period interval parameterized.
- We added the `DELETE /_aws/dynamodb/expired` endpoint that programmatically triggers the stale items' deletion.
- to implement the deletion, we scan every table with the `Scan` operation, collecting the stale items.
- we use `BatchItemWrite` to delete the collected stale items from the DBs. The call should consume write throughput, while TTL does not.
- an alternative would be to mark the expired element, instead of deleting them, and …
=> feat: DynamoDB TTL

tests/aws/services/cloudwatch/test_cloudwatch.py, tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json, tests/aws/services/cloudwatch/test_cloudwatch.validation.json
This PR aims at checking what happens when multiple units are present in the cloudwatch database, then no unit is specified in the get-metrics-data call.
The result is that this seems to be not as described [in the docs](https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/get-metric-data.html):
```
In a Get operation, if you omit Unit then all data that was collected with any unit is returned,
along with the corresponding units that were specified when the data was reported to CloudWatch.
If you specify a unit, the operation returns only data that was collected with that unit specified.
If you specify a unit that does not match the data collected, the results of the operation are null.
CloudWatch does not perform unit conversions.
```
AWS however acts differently with a given …
=> test get-metric-data with no unit

localstack/utils/container_utils/container_client.py, tests/integration/docker_utils/test_docker.py, tests/unit/test_dockerclient.py, tests/unit/test_misc.py
This is solution for #9419 
The differences in behavior are as follows.
1. Expose fixed port with `LAMBDA_DOCKER_FLAGS` setting.
```
LAMBDA_DOCKER_FLAGS=-e NODE_OPTIONS=--inspect=0.0.0.0:9229 -p 9229:9229
```
2. The first function execution succeeds and the container exposes the fixed port.
3. The second function execution fails due to an error in the bind to the same port.
1. Expose dynamic port with `LAMBDA_DOCKER_FLAGS` setting.
```
LAMBDA_DOCKER_FLAGS=-e NODE_OPTIONS=--inspect=0.0.0.0:9229 -p 0:9229
```
2. The first function execution succeeds and the container exposes the dynamic port.
3. The second function execution also succeeds and the container exposes another dynamic port.
It is possible to run multiple Lambda functions with remote debugging configured.
=> Support dynamic port on Lambda remote debugging

localstack/http/resource.py, localstack/http/router.py, localstack/services/lambda_/invocation/executor_endpoint.py, localstack/services/opensearch/cluster.py, localstack/services/sqs/provider.py, tests/unit/http_/test_router.py
Werkzeug has clever utilities such as `Submount` which allows you to streamline the creation of routers:
```python
url_map = Map([
Rule('/', endpoint='index'),
Submount('/blog', [
Rule('/', endpoint='blog/index'),
Rule('/entry/<entry_slug>', endpoint='blog/show')
])
])
```
Our `@route`, `@resource`, or endpoint concepts have not been compatible with these, because the werkzeug `Rule` objects are created within `Router.add`, instead of an encapsulating `RuleFactory`, which is werkzeug's mechanism of building higher-level routing utilities.
This PR moves all the code that generates `Rule` objects out of `Router.add`, and instead encapsulates them into `RuleFactory` classes. This makes them naturally compatible with werkzeug.
For instance, now you can do something like:
```python …
```
=> refactor http router for better werkzeug compatibility

tests/conftest.py
We've had issue with the pipeline timing out very frequently for the community tests against Pro.
It seems all test runs timing out had a leftover thread in common, spawned by the `httpserver` fixture. 
This thread was not spawned as `daemon`, meaning it would prevent the interpreter from shutting down.
Temporary fix: patch the fixture to spawn the thread as daemon, so that even if it's still running, we can force its removal.
- Investigate why this thread is still there, prevent it and remove the patch
=> patch HTTPServer fixture to spawn daemon thread

localstack/services/lambda_/event_source_listeners/adapters.py, localstack/services/lambda_/event_source_listeners/sqs_event_source_listener.py, tests/aws/services/lambda_/test_lambda_performance.py
Similar refactoring as in #10043, making it easier to instrument the lifecycle of an event source mapping call.
* sync and async invocations are now separated out into separate functions so we can instrument them
=> refactor EventSourceAsfAdapter for easier instrumentation

tests/aws/services/lambda_/test_lambda_api.py
For whatever reason suddenly the CodeSha256 field on the `tests.aws.services.lambda_.test_lambda_api.TestLambdaFunction.test_function_arns` started to fail 
[Source](https://github.com/localstack/localstack-ext/actions/runs/7493060692/job/20397932118)
```
2024-01-11T19:32:11.1504615Z =================================== FAILURES ===================================
2024-01-11T19:32:11.1505653Z ____________________ TestLambdaFunction.test_function_arns _____________________
2024-01-11T19:32:11.1506827Z >> match key: create-function-partial-arn-response
2024-01-11T19:32:11.1519213Z 	[33m(~)[0m /CreateFunctionResponse/CodeSha256 '<code-sha256:2>' → '<code-sha256:1>' ... (expected → actual)
2024-01-11T19:32:11.1519974Z 
```
* Skip snapshot verification for CodeSha256 field
* Figure out why …
=> Skip snapshot verification for CodeSha256 in lambda API test

localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3_api.py, tests/aws/services/s3/test_s3_api.snapshot.json, tests/aws/services/s3/test_s3_api.validation.json
AWS released this statement regarding enabling S3 Object Lock on existing buckets. It wasn't possible before, and the bucket needed to be created with a specific configuration flag. 
See https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-s3-enabling-object-lock-buckets/
Update the test and the logic to now allow enabling S3 object lock on existing buckets, if they are versioned.
=> supports enabling S3 Object Lock on existing buckets

localstack/services/cloudwatch/cloudwatch_database_helper.py, localstack/services/cloudwatch/provider_v2.py, tests/aws/services/cloudwatch/test_cloudwatch.py, tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json, tests/aws/services/cloudwatch/test_cloudwatch.validation.json, tests/aws/services/cloudwatch/test_cloudwatch_performance.py
Some improvements for thread handling when accessing the sqlite database.
Some observations for sqlite database:
- the sqlite database is compiled once per system, so when you run in host-mode you may have different configuration then when running in docker
- observations on my personal computer: 
- host mode runs a sqlite with different [threadsafety](https://docs.python.org/3.11/library/sqlite3.html#sqlite3.threadsafety): `THREADSAFE=2`, while in docker runs `THREADSAFE=1` (see also https://sqlite.org/threadsafe.html)
- 2 means Multithreaded: Threads may share the module, but not connections 
- 1 means Serialized: Threads may share the module, connections and cursors, should be save to access from multiple threads
General implementation:
* only `put_metric_data` requires write access
* …
=> improve + test thread safety for metric access

localstack/services/cloudwatch/alarm_scheduler.py, localstack/services/cloudwatch/provider_v2.py, tests/aws/services/cloudwatch/test_cloudwatch.py, tests/aws/services/cloudwatch/test_cloudwatch.snapshot.json, tests/aws/services/cloudwatch/test_cloudwatch.validation.json
When checking the tests, I realized there is still a flaky, and currently skipped test `test_put_metric_alarm`. 
It turns out that the current test setup was the reason for the flakiness, so I refactored it.
Also two operations where still missing from the provider v2 that are used in this test.
- added missing implementation for `describe_alarms_for_metric` and `describe_alarm_history`
- parity fixes, test refactoring
For the test `test_put_metric_alarm`:
- initially, it would treat missing data as not breaching. depending on when the alarm is evaluated the first state would either change to OK or to ALARM (because the metrics we insert after breaches the condition)
- changed the alarm evaluation to "ignore", and removed the second part, where we expected the alarm to go back to state OK
=> Add describe_alarms_for_metric and describe_alarm_history

localstack/services/s3/resource_providers/aws_s3_bucket.py, tests/aws/services/cloudformation/resources/test_s3.py, tests/aws/services/cloudformation/resources/test_s3.snapshot.json, tests/aws/services/cloudformation/resources/test_s3.validation.json, tests/aws/services/s3/test_s3.py, tests/aws/templates/s3_object_lock_config.yaml
As reported by #9912, we did not support enabling ObjectLock for S3 Bucket, nor setting the object lock configuration to the bucket.
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-objectlockconfiguration.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-objectlockenabled
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-objectlockconfiguration
- update the CloudFormation model to support it
- created a new test checking the functionality and the split between enabling the bucket to be locked and setting up the configuration
- renamed some variables in the regular S3 tests because PyCharm now checks for fixture usage, and the name …
=> add support for ObjectLock for CFN S3 Bucket

tests/unit/services/s3/test_virtual_host.py
We were missing an abstract class method definition following the rolo migration
Added the `close` method to the test class for the S3 vhost tests.
=> fix S3 v-host unit tests after rolo migration

localstack/services/apigateway/helpers.py, localstack/services/apigateway/integration.py, tests/unit/test_apigateway.py
Improves community PR by using the `RequestParametersResolver` that can handle, headers, path and query strings and also static values.
Fixes the previous test - static values are configured using single quotes, "'Fixed-Header-Value'", but transformed into normal header values when passed to the integration.
=> use request parameter resolvers

setup.cfg
The newest version of the cryptography package ([`42.0.0`](https://pypi.org/project/cryptography/42.0.0/)) seems to cause issues with the pipeline:
```
from cryptography.hazmat.backends.openssl.ec import _EllipticCurvePrivateKey
E   ModuleNotFoundError: No module named 'cryptography.hazmat.backends.openssl.ec'
```
Pin cryptography to below 42.0.0 until the underlying issue is resolved
=> Pin cryptography package to below 42.0.0

localstack/dev/run/__main__.py
In #9339, we added a way to explicitly load the extension dev mode configuration hooks. This was highly specific to this one use case, and a better way would be to run the hooks that are also run during bootstrapping when running `localstack start`.
This PR adds both the `prepare_host` and `configure_container` hooks to the dev script, to more closely match what `localstack start` is doing, which also includes extension dev mode when available.
The PR also passes through the config environment variables to the container as `localstack start` does
* `prepare_host` and `configure_container` hooks are now run when running `localstack.dev.run`
* as a consequence, a license check is performed on the host before starting the container (it's in a `prepare_host` hook in ext)
* this would require …
=> correctly execute host and container configuration hooks in dev.run

localstack/services/stepfunctions/provider.py, tests/aws/services/stepfunctions/v2/test_sfn_api.py, tests/aws/services/stepfunctions/v2/test_sfn_api.snapshot.json, tests/aws/services/stepfunctions/v2/test_sfn_api.validation.json
Currently, StepFunctions v2 does not support ReverseOrder options in GetExecutionHistory requests. This PR adds such functionality.
Closes: #10106 
Added reserve option in SFN v2 provider, and relevant snapshot test.
=> [SFN] Support for ReverseOrder in GetExecutionHistory Requests

localstack/aws/api/ec2/__init__.py, localstack/services/iam/provider.py, localstack/services/infra.py, localstack/services/moto.py, localstack/state/inspect.py, localstack/utils/aws/request_context.py, setup.cfg, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3_list_operations.py, tests/unit/state/test_inspect.py
[getmoto/moto](https://github.com/getmoto/moto) just had a new major release.
All changes are released with [moto-ext 5.0.0.post1](https://pypi.org/project/moto-ext/5.0.0.post1/)
This bump brings in the following fixes to LocalStack:
- https://github.com/getmoto/moto/pull/7204
- https://github.com/getmoto/moto/pull/7240 by @bentsku 
- https://github.com/getmoto/moto/pull/7251 by @bentsku 
- Upgrades moto-ext to v5
Closes https://github.com/localstack/localstack/issues/8642
=> Bump moto-ext to 5.0.0.post1

localstack/services/sqs/models.py
When there is no way to control the port creation of the localstack gateway port (say you're get a random port mapping `:34567->:4566/tcp` from docker), there's currently no good way of configuring localstack s.t. endpoints are accessible from both the host and inside the container network. The ideal solution would be to gain control of the port creation, and if you need random ports, make sure the gateway is bound to the same port by setting `GATEWAY_LISTEN=:<random-port>`.
In #9753, users mentioned that they work in an environment where this is not possible, and they rely on random ports. In this scenario, SQS queue URLs won't work either from the host or from within the container network. Users have asked us to put in place the old "dynamic" endpoint strategy which allowed queue URL …
=> add dynamic SQS endpoint strategy to build SQS queues from called host

localstack/services/lambda_/invocation/docker_runtime_executor.py, localstack/services/lambda_/invocation/executor_endpoint.py
With #10129, adding routes became way slower than before, due to fixes in regards of thread safety.
In lambda, we will add 5 routes for every spawned execution environment, and delete them after it shuts down.
This introduces unnecessary changes in the router, which can be solved faster and easier with an internal construct.
Core target of this PR is to reduce adding/removing of routes to the router.
* Add a `ExecutorRouter` (name to be decided) which will pass the request on to the right executor endpoint. It has a routing rule which parameterizes the executor id, which leads to only 5 routes for all executors.
* `ExecutorEndpoint`s will add / remove themselves from this "router".
* I tried to self contain the changes as much as possible
* I removed unnecessary log entries and the method …
=> Rework internal lambda routes to avoid router modifications for every spawned environment

localstack/utils/collections.py, tests/unit/utils/test_collections.py
Enhance implementation of `is_comma_delimited_list(..)` to fix --services in pods CLI.
We are currently not accepting dashes in items of comma-separated lists, which is required, e.g., for `cognito-idp` in the following command:
```
$ localstack -d pod save --services s3,cognito-idp test-123
...
❌ Error: Input the services as a comma-delimited list
```
* adjust the logic in `is_comma_delimited_list(..)` to allow passing an `item_regex`
* define a default `DEFAULT_REGEX_LIST_ITEM` regex that allows alphanumeric characters as well as dashes
* addjust and extend the unit tests
As far as I can see, the util function is currently only used for the pods client logic, so it should not break existing logic in other places.
=> Enhance implementation of is_comma_delimited_list to fix --services in pods CLI

localstack/services/sns/provider.py, tests/aws/services/sns/test_sns.py, tests/aws/services/sns/test_sns.snapshot.json, tests/aws/services/sns/test_sns.validation.json
As reported with #10009, we've had an issue when setting empty filter policy. This fix is based on https://github.com/getmoto/moto/pull/7251, now part of LocalStack with #10112, and has additional logic in place where we manually work with the filter policy.
Update existing tests to validate the fix, and update the logic in `Subscribe` too. 
_fixes #10009_
=> add tests for fix to SNS empty filter policy

tests/aws/services/cloudformation/resource_providers/ec2/test_ec2.py
In PR #10100, a failing test was introduced. Although the requested changes were implemented in the pull request (PR), I failed to thoroughly verify that the new test passed successfully before merging. Consequently, I proceeded with the merge without awaiting the completion of pipeline checks.
Include the 'Message' attribute in the list of snapshot skips. It is important to fix the issue in the EC2 API.
=> hot fix  for ec2 key pair deployment test

localstack/services/cloudformation/engine/template_deployer.py, tests/aws/services/cloudformation/engine/test_references.py
When we cannot resolve a `Ref` - specifically if it is targeting a non-existent resource or parameter, we currently print "Should be detected earlier." which is not very useful. Instead, since this is a programming error from the creator of the template, we should be more helpful and print out the ref that cannot be resolved.
- Increase clarity of error message when not finding a ref
- Add test to ensure the ref target is in the error message
- Add more clarity to additional error messages
=> CFn: improve error message for invalid ref

localstack/services/dynamodb/provider.py, localstack/services/dynamodb/utils.py, localstack/testing/pytest/fixtures.py, localstack/utils/aws/queries.py, tests/aws/services/dynamodb/test_dynamodb.py, tests/aws/services/dynamodbstreams/test_dynamodb_streams.py, tests/aws/services/dynamodbstreams/test_dynamodb_streams.snapshot.json, tests/aws/services/dynamodbstreams/test_dynamodb_streams.validation.json, tests/aws/services/kinesis/test_kinesis.py
Following a customer request, it seems that our integration between DynamoDB tables and Kinesis streams is not fully working for certain DDB operations, in particular when using the `transact_write_items` operation. (Apparently it worked for older versions prior to 3.0, but I haven't confirmed).
🚧  At this point, the PR only adds a snapshot test to illustrate the behavior - proper logic still needs to be implemented. (may need some help from service owners here, if possible 🙌 ) 
Wondering if this TODO comment could be related (as I know @bentsku has been working on some pretty significant performance enhancements recently 🚀 ): https://github.com/localstack/localstack/blob/45d39edbdc27c00d1f762c40e3c050d5b1b36e39/localstack/services/dynamodb/provider.py#L1112
**Update**: After discussing …
=> Enhance parity for DynamoDB to Kinesis stream integration

localstack/services/kinesis/kinesis_mock_server.py
I encountered this issue today:
```bash
2024-02-01T16:10:06.933  INFO --- [functhread10] localstack.utils.run       : Restarting process (received exit code 1): ['node', PosixPath('/Users/benjaminsimon/Projects/localstack/localstack/.filesystem/var/lib/localstack/lib/kinesis-local/0.4.5/node_modules/kinesis-local/main.js')]
2024-02-01T16:10:06.933 DEBUG --- [functhread10] localstack.utils.run       : Executing command: ['node', PosixPath('/Users/benjaminsimon/Projects/localstack/localstack/.filesystem/var/lib/localstack/lib/kinesis-local/0.4.5/node_modules/kinesis-local/main.js')]
2024-02-01T16:10:07.026  INFO --- [functhread10] l.s.k.kinesis_mock_server  : ciris.ConfigException: configuration loading failed with the following errors.
2024-02-01T16:10:07.026  INFO --- [functhread10] …
```
=> fix Kinesis rejection of log level

localstack/services/lambda_/invocation/metrics.py, localstack/services/lambda_/invocation/version_manager.py, localstack/utils/cloudwatch/cloudwatch_util.py
When using values other than `000000000000` for account ID or `us-east-1` for region, `cloudwatch` tests should still create the consequent resources in these accounts and region.
This PR adds `account_id` parameter to the `cloudwatch` client when publishing the lambda metric on function invoke. The remaining changes involves propagating its value to the corresponding functions.
The tests were failing previously when executed with a non-default account ID, set through environment variables (`TEST_AWS_ACCOUNT_ID=111111111111`, `TEST_AWS_ACCESS_KEY_ID=111111111111`, `TEST_AWS_REGION=us-west-1`). This PR fixes: 
```
tests.aws.services.cloudwatch.test_cloudwatch_metrics.TestCloudWatchLambdaMetrics.test_lambda_invoke_successful
tests.aws.services.cloudwatch.test_cloudwatch_metrics.TestCloudWatc …
```
=> cloudwatch: fix functionality of metrics for multi-accounts and region

localstack/services/dynamodb/provider.py
shutdown hook of dynamodb was using an old API to remove rules from the router, leading to exceptions:
```
File "/opt/code/localstack/localstack/utils/functions.py", line 41, in call_safe
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 481, in on_before_stop
ROUTER.remove_rule(rule)
^^^^^^^^^^^^^^^^^^
AttributeError: 'Router' object has no attribute 'remove_rule'
```
* dynamodb routes are now removed using `ROUTER.remove`
=> fix dynamodb router rule removal

tests/aws/services/dynamodbstreams/test_dynamodb_streams.py
https://github.com/localstack/localstack/pull/10143 introduced some new tests for DynamoDB Streams.
Unfortunately, it turned out that the test is pretty flaky, which is why we are skipping it for now.
For example:
- [CircleCI #177869](https://app.circleci.com/pipelines/github/localstack/localstack/22067/workflows/71a4c73b-6383-48eb-9bfb-e88b5476eeee/jobs/177869)
- [CircleCI #177580](https://app.circleci.com/pipelines/github/localstack/localstack/22041/workflows/3c98da8f-d1cc-4730-b0e4-26cbd1b51e1d/jobs/177580)
- Skip `TestDynamoDBStreams::test_enable_kinesis_streaming_destination`
=> skip flaky dynamodb streams test

localstack/constants.py, localstack/services/dynamodb/server.py
It was observed that `test_time_to_live_deletion` would fail in non-default account/region setting (https://github.com/localstack/localstack/pull/8204), specifically the second of the below two assertions that it performs:
https://github.com/localstack/localstack/blob/75042c5c7feb0a3eafa2beea6cc30471e2b527a0/tests/aws/services/dynamodb/test_dynamodb.py#L127-L128
The first assertion would pass with HTTP 200 but for the second, the response value would be `''` cause JSON deserialisation error.
There were two root problems:
1. How `rolo` works. By default, if an invalid route is queried at the LocalStack endpoint, it returns an HTTP 200 with an empty response by default. See https://github.com/localstack/localstack/pull/10167 for details
2. Lack of credentials passed to …
=> DynamoDB: Fix startup in non-default account ID/region

localstack/services/lambda_/urlrouter.py, tests/aws/services/lambda_/functions/lambda_echo_json_body.py, tests/aws/services/lambda_/test_lambda.py, tests/aws/services/lambda_/test_lambda.validation.json
Fixes #8213. To easily test it, I also created a new test function that makes it easier to return custom bodies. Different lambda URL body interpretations can be found [here](https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html).
* LocalStack now correctly parses the `statusCode` attribute field when translating lambda responses
=> fix custom status code for lambda URLs

localstack/services/lambda_/invocation/execution_environment.py, localstack/services/lambda_/packages.py
We pulled upstream changes into our lambda init binary. (see https://github.com/localstack/lambda-runtime-init/pull/30).
We should now update the binary, and set the account id in the environment, so it can properly returned when the `Lambda-Extension-Accept-Feature` header is set to `accountId` during the extension register call (https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html#extensions-registration-api-a)
* Update lambda init binary
* Set account id of function into execution environment
=> Update lambda init binary

.github/workflows/tests-pro-integration.yml, tests/aws/services/opensearch/test_opensearch.py
Recently, the Community Tests against Pro are failing somewhat regularly.
@maxhoheiser found out that they fail with an error message indicating that they are running out of disk space.
After a bit of analysis, it shows that there's a lot OpenSearch versions downloaded and cached. In order to mitigate these issues, I changed the tests a bit to avoid some OpenSearch versions to be downloaded.
If we hit the limit again, there's lot of potential in maximizing the disk space (f.e. with [easimon/maximize-build-space](https://github.com/easimon/maximize-build-space)).
- Reduces the disk space being used by decreasing the number of OpenSearch versions being used in the tests.
- The pipeline in question is now running stable again in this PR.
- I analyzed the cache storage logs of the following …
=> fix disk space issues in GitHub workflow

localstack/services/firehose/provider.py, localstack/testing/pytest/fixtures.py, tests/aws/services/firehose/conftest.py, tests/aws/services/firehose/test_firehose.py, tests/aws/services/firehose/test_firehose.snapshot.json, tests/aws/services/firehose/test_firehose.validation.json
Multiple instances of kcl listening to the same Kinesis event stream - only the "first" will process events, due to all using the same dynamoDB lease table. This was raised in #9476 
We are spinning up a mock Kinesis server (https://github.com/etspaceman/kinesis-mock) and use the java plication aws kinesis client library to connect to this mock server. For services queriing events from the mock kinesis server, we provide a connector function `listen_to_kinesis` in `kinesis_connector` 
This method starts the kcl for each listener. Kcl starts one or more instances with a worker bound to one or more shards. Each worker processes messages from the shard(s) and sends received messages to a programmatically created Python script that sends the messages to a socket. A listener function running …
=> Fix: Firehose: Multiple firehose delivery streams not receiving messages from kinesis event stream

localstack/services/apigateway/helpers.py, tests/aws/services/apigateway/test_apigateway_common.py, tests/aws/services/apigateway/test_apigateway_common.validation.json, tests/aws/services/apigateway/test_apigateway_lambda.snapshot.json, tests/unit/test_apigateway.py
There was a #TODO for the RequestParametersResolver to properly resolve `context` variables to integration request parameters. 
This was also lacking for a customer use case with AppSync. 
https://docs.aws.amazon.com/apigateway/latest/developerguide/request-response-data-mappings.html#mapping-request-parameters
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#context-variable-reference
- added the context variable manually into the dict used for resolving integration request parameters (this can be revisited  later with the `context.context` variable and more logic into it)
- added an AWS validated test to check we're properly passing integration request parameters and resolving them
=> add APIGW RequestParametersResolver support for context var

localstack/services/apigateway/integration.py
When a AWS_PROXY integration type with a lambda is used in API Gateway, the lambda must follow a specific format when responding. It's often a source of confusion when AWS Gateway returns `502` error. 
We would log the following line:
`2024-02-08T07:44:44.336  WARN --- [ asgi_gw_458] l.s.apigateway.integration : Lambda output should follow the next JSON format: { "isBase64Encoded": true|false, "statusCode": httpStatusCode, "headers": { "headerName": "headerValue", ... },"body": "..."}`
But in this specific user case, it looked like I could not find a response anywhere in the logs and would like to see what we actually received.
This is the AWS documentation page specifying the format:
https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gat …
=> APIGW: add more debug log when lambda proxy response format is wrong

tests/aws/services/lambda_/test_lambda_integration_kinesis.py, tests/aws/services/lambda_/test_lambda_integration_kinesis.snapshot.json, tests/aws/services/lambda_/test_lambda_integration_kinesis.validation.json
This snapshot test is added to remove questions about supported behavior differences between AWS and LocalStack, as requested by a user. Two lambda functions can be triggered by the same kinesis event stream, if the `StartingPosition="TRIM_HORIZON"` is correctly configured. 
`StartingPosition="LATEST"` does not reliably pick up every event from the subscribed stream. 
If a new subscribed lambda should not be triggered backward for all still existing events in the stream, `StartingPosition="AT_TIMESTAMP"` in combination with a valid timestamp is recommended.
=> Feature: Lambda: Add aws validated test for two lambdas subscribing to same kinensis event stream

localstack/services/events/provider.py, tests/aws/services/events/conftest.py, tests/aws/services/events/test_events.py, tests/aws/services/events/test_events.snapshot.json, tests/aws/services/events/test_events.validation.json
Currently, EventBus does not support [Input Transformation](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-transform-target-input.html) as mentioned in this #9918 feature request and requested by another customer. 
Input transformation allows for defining a custom template for the message body, that can be populated with up to 100 key-value pairs using JSON paths to reference values from the original message. This is used to customize the text from an event, before it is passed to the consumer specified by the respective rule. 
Input transformers are defined as InputPaths (JSON paths) and a InputTemplate string
```
{
"InputPathsMap": {"detail-type": "$.detail-type"},
"InputTemplate": '"This event was of <detail-type> type."',
}
```
This PR adds a validated test for input …
=> Feature: Events: Add input transformers

localstack/dns/plugins.py
While looking through a hanging test I saw the DNS server was alive waiting on a `.join` call. This _may_ have contributed to incorrect test shutdown. Regardless, we do not shut the server down properly.
Add a shutdown hook for the DNS server for clean termination.
Note: the priority of this hook must come after any hooks that use the gateway, which itself is shutdown with a priority of -20:
https://github.com/localstack/localstack/blob/bda6479827bf3bcf92a54d469588698187af6186/localstack/aws/serving/edge.py#L31-L35
in case DNS resolution is required for any requests using the gateway. The configuration of these priorities is brittle however. To prevent possible import problems I have not made `DNS_SHUTDOWN_PRIORITY` relative to other priorities, which would be more future proof. Instead, …
=> Stop DNS server on shutdown

.github/workflows/upgrade-python-dependencies.yml
#10127 introduced dependency pinning, and with #10195 we removed as many pins as possible.
Now we can use a shareable workflow by @silv-io in [localstack/meta](https://github.com/localstack/meta/blob/main/.github/workflows/upgrade-python-dependencies.yml) to automatically update the dependencies once a week using a scheduled GitHub workflow.
- Adds a GitHub workflow to update the requirements files once a week.
- This workflow has been tested in other repositories already, and it will be triggered manually once it has been merged to `master` (the workflow call trigger cannot be used as long as the workflow is not in `master`).
=> add automated Python requirements update

tests/aws/services/kinesis/conftest.py, tests/aws/services/kinesis/test_kinesis.py
I was working on implementing new tests for kinesis and kinesis firehose and wanted to use the opportunity to clean up the existing tests. I believe it is much cleaner to separate test fixtures and actual tests since this generally keeps test files shorter and easier to read.
Moved existing fixtures to `conftest.py` and added a new fixture for creating a kinesis stream consumer that handles cleanup after the fact.
=> Refactor: Kinesis: Clean-up test fixtures

localstack/services/logs/provider.py
This PR fixes multi account support for logs.
The region parameter was omitted when setting up a client with IAM roles. This Pull Request includes the missing region.
This PR is tested using [this commit](https://github.com/localstack/localstack/commit/e40421532b141ab2827892ed2ed766e9cadc4d35) on CI
=> fixed multi account support for logs

localstack/dns/plugins.py, localstack/dns/server.py
We are currently seeing failures due to DNS resolution issues on pytest session finish hooks in LS.
This is likely due to the shutdown of the DNS server after LS shuts down (which can happen before the last session finish hooks are executed).
After we stop the DNS server, we should restore the `resolv.conf` config to avoid all subsequent requests failing.
* Cache and restore `resolv.conf` on DNS server start/stop.
=> Restore DNS settings in container after dns server shuts down

localstack/services/cloudformation/engine/entities.py, localstack/services/cloudformation/engine/template_preparer.py, localstack/services/cloudformation/engine/transformers.py, localstack/services/cloudformation/provider.py, localstack/utils/objects.py, tests/aws/services/cloudformation/test_template_engine.py, tests/aws/templates/macros/return_random_string.py, tests/aws/templates/transformation_resource_att.yml
This feature was proposed in issue #9535 but @whummer has already implemented support for the Fn::Transform intrinsic function in LocalStack. This pull request builds upon that implementation by enhancing the functionality. Specifically, it enables the Fn::Transform intrinsic function to incorporate user-defined CloudFormation macros.
- Enable Fn::Intrinsic function to use user's macros.
- Refactoring to standarize the usage of snipped and global transformations
- Added a test where the macro returns a string and CFn applies to a resource value.
- Un-skipped some tests regarding snipped transformations.
Figure out a way to handle both a Fn::Instrinsic which contains a list of transformations and a Fn::Intrinsic that returns a single att.
=> enable Fn::Transform to use CFn macros

localstack/utils/aws/client_types.py
Required change for IAM implementation of EventBridge Pipes:
> To make API calls on the resources that you own, EventBridge Pipes needs appropriate permission. EventBridge Pipes uses the IAM role that you specify on the pipe for enrichment and target calls using the IAM principal `pipes.amazonaws.com`.
Source: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes-permissions.html#pipes-perms-enhance-target 
* Add pipes service principal
=> Add pipes service principal

localstack/services/lambda_/invocation/docker_runtime_executor.py, localstack/services/lambda_/invocation/execution_environment.py, tests/aws/services/lambda_/functions/lambda_process_inspection.py, tests/aws/services/lambda_/test_lambda.py, tests/aws/services/lambda_/test_lambda.snapshot.json, tests/aws/services/lambda_/test_lambda.validation.json
The lambda init binary should have the `AWS_EXECUTION_ENV` set to `AWS_Lambda_rapid`. The setting of the concrete value depending on the runtime will be done in `/var/runtime/bootstrap`, and is part of the lambda images.
Some extensions depend on that value being correct for checking what runtime is running (datadog).
Even though this is a parity adjustment, it is a quite significant change, so I labeled it minor for now.
* Change execution env variable to `AWS_Lambda_rapid`
* Allow a custom init even if `LAMBDA_INIT_DEBUG` is not set
* Add test for introspection of the init process environment
=> Change AWS_EXECUTION_ENV set in the lambda init binary

localstack/services/lambda_/api_utils.py, localstack/services/lambda_/provider.py, tests/aws/services/lambda_/test_lambda_api.py, tests/aws/services/lambda_/test_lambda_api.snapshot.json, tests/aws/services/lambda_/test_lambda_api.validation.json, tests/unit/services/lambda_/test_api_utils.py
A user reported an issue where invoking a lambda with an alias like `2024-01-01` would fail.
- Introduce test covering both a valid case like `2024-01-01` and invalid one like `2024`
- Fix the alias regex we're using to check if a qualifier is an alias or not
- Add a check to the `create_alias` method. In the reported case, the alias was created but we only checked the regex on invoke which then failed to resolve the proper alias.
=> Fix Lambda function alias name checks

localstack/services/sqs/models.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.snapshot.json, tests/aws/services/sqs/test_sqs.validation.json
Users reported an issue with message groups becoming blocked when polling fifo queues. It turned out that a [recent change](https://github.com/localstack/localstack/pull/9975) that was generally correct had a side effect on empty message groups which we didn't consider.
The current implementation relies on removing message groups from the group queue when receiving until the queue is empty. We cannot iterate over the group queue, and it seems to be impractical to add the groups back when new messages arrive (since we then have to distinguish between empty groups due to all messages processed and empty groups due to invisible messages). Therefore this PR collects all empty groups on receive and adds them back to the group queue once the receive call is finished.
- add  empty message groups …
=> Sqs fix message groups visibility

localstack/services/dynamodb/resource_providers/aws_dynamodb_table.py, tests/aws/cdk_templates/DDBTableTTL/DDBStackTTL.json, tests/aws/services/cloudformation/resources/test_dynamodb.py, tests/aws/services/cloudformation/resources/test_dynamodb.snapshot.json, tests/aws/services/cloudformation/resources/test_dynamodb.validation.json
With https://github.com/localstack/localstack/pull/10041 we recently introduced the TTL in DynamoDB.
While working on a platform test today @lukqw noticed that this feature was not working when deploying a DDB table with cdk. To enable TTL in DDB you would first create the table with the `CreateTable` operation and then call the `UpdateTimeToLive` operation to enable the feature and specify the attribute name.
The `AWS::DynamoDB::Table` template has a `TimeToLiveSpecification` attribute that carries the same payload we would pass to `UpdateTimeToLive`. However, we were not reading this attribute and performing the additional call in our `DynamoDBTableProvider`.
- We implemented the missing logic in the `DynamoDBTableProvider` cloudformation provider. We read the eventual …
=> Implement dynamodb TimeToLive in cloudformation

localstack/services/cloudformation/provider_utils.py
Adds a provider util which I needed for converting into lower camel case, e.g. from `ThisWord` into `thisWord` in the Amplify resource provider
It'll probably be common enough to add this to the util suite which we'll ultimately move into the externalized repo.
=> Add CFn provider util to convert into lower camel case

localstack/services/cloudformation/resource_provider.py
After https://github.com/localstack/localstack/pull/10242 the -ext pipeline started failing.
I unfortunately missed an edge case where we previously had legacy providers in both community and -ext (-ext providers with additional features) but now only have a new provider in community and no new one in -ext yet.
What needs to happen is that for those 3 resource types, if PRO is enabled, the **legacy** model from -ext is used. With the recently introduced logic it was falling back to the community provider before considering the legacy models though.
- Until we have corresponding resource providers for these 3 resource types in -ext, I've added a manual exemption list in community. Will refactor this soon though, so this is just a temporary inconvenience.
=> Fix override of legacy resource providers over new community ones for certain resources

tests/aws/services/lambda_/test_lambda.py
The test `TestLambdaMultiAccounts:test_cross_account_access` would fail if `short_uid()` returned a value consisting entirely of digits. This failed Boto input validation for `AliasName`
- Make sure `AliasName` contains alphabets
- Adds a note that prevented me from AWS validating the test. Is this a bug in AWS? Did this go unnoticed for three years? Not sure
=> Lambda: Fix test_cross_account_access flakes

.github/workflows/tests-s3-image.yml
As encountered here: https://github.com/localstack/localstack/actions/runs/7903228515/job/21570653837
We were getting rate limited by Docker Hub because we would not log in to pull the images.
Thanks to @alexrashed for the pointer!
Add a step to login to Docker Hub in order to not be rate limited
=> fix S3 image rate limiting with docker login

localstack/services/cloudformation/engine/quirks.py, localstack/services/cloudformation/resource_provider.py
Ran into this with the `AWS::EKS::FargateProfile` resource in -ext. We currently don't have a way to support the equivalent of this code from the old legacy model:
```python
def _handle_result(
account_id: str,
region_name: str,
result: dict,
logical_resource_id: str,
resource: dict,
):
fargateProfile = result["fargateProfile"]
resource[
"PhysicalResourceId"
] = f"{fargateProfile['clusterName']}|{fargateProfile['fargateProfileName']}"  # <== this here
resource["Properties"]["Arn"] = result["fargateProfile"]["fargateProfileArn"]
```
- Add a new way to optionally use multiple properties in a physical resource id quirk. Specify the json pointer enclosed in `<>` and those parts will be extracted and replaced to build the final value for the physical resource id
-  Example from this PR: …
=> Add support for composite physical resource ID quirks

localstack/utils/http.py, tests/unit/utils/test_http_utils.py
In LocalStack, we do download some packages / backends lazily when they are needed for the first time.
For example, when creating an OpenSearch domain with a specific version for the first time, the package will be downloaded and cached in the LocalStack volume directory.
Currently, the logs are quite verbose and log on every MB downloaded. For big packages, this can pollute the logs quite a lot.
This PR aims at reducing the amount of logs if possible: If the total size is known (e.g. the `Content-Length` header is set on the HTTP response), we log at most one line for every 10% of download progress.
- If the total content length is known, only log every 10% of the progress, instead of every MB.
- Fixes a small bug where the totally downloaded size was miscalculated for GZIP encoded …
=> enhance download progress logging

localstack/constants.py, localstack/services/lambda_/event_source_listeners/stream_event_source_listener.py, localstack/utils/aws/message_forwarding.py
When using values other than `000000000000` for account id or `us-east-1` for region, `events` tests should still create the consequent resources in the corresponding accounts and region.
This PR introduces the use of `account_id` field fetched from `target_arn` in order to connect with the correct client in `connect_to()` method while sending events to the target.
The tests were failing previously when executed with a non-default account ID, set through environment variables (`TEST_AWS_ACCOUNT_ID=111111111111`, `TEST_AWS_ACCESS_KEY_ID=111111111111`, `TEST_AWS_REGION=us-west-1`). The affected tests are:
```
tests.aws.services.events.test_events.TestEvents.test_put_events_into_event_bus[standard]
tests.aws.services.events.test_events.TestEvents.test_put_events_into_event_bus[domain] …
```
=> events: add account_id while creating client in sending events to target

localstack/services/cloudformation/engine/quirks.py
Update the CFn quirks file to correctly fetch the physical resource id from an `AWS::ECS::Service`
=> CFn: enable AWS::ECS::Service PhysicalResourceId quirk

localstack/services/cloudformation/engine/entities.py, localstack/services/cloudformation/engine/template_deployer.py, localstack/testing/pytest/fixtures.py
When a stack fails to deploy, the error is not always understandable. Especially in our tests. We should make the output easier to understand, and filter down events to only show the failures.
* Only print the resources that failed to create, but allow all events if `CFN_VERBOSE_ERRORS=1`
* Update formatting to be more human readable
* Log (to warning level by default) stack errors if the stack status is set to `*FAILED`
Before:
Log output: n/a
Test exception traceback output:
```
E           localstack.testing.pytest.fixtures.StackDeployError: Describe output:
E           {"StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/stack-cde16c5d/58ee10c2", "StackName": "stack-cde16c5d", "ChangeSetId": "arn:aws:cloudformation:us-east-1:000000000000:changeSet/change-set-471a5b1a/4cfe25 …
```
=> CFn: improve error reporting

localstack/services/lambda_/invocation/assignment.py, localstack/services/lambda_/invocation/execution_environment.py, localstack/services/lambda_/invocation/lambda_service.py, localstack/services/lambda_/invocation/version_manager.py, localstack/services/lambda_/provider.py, tests/aws/services/lambda_/functions/lambda_multiple_handlers.py, tests/aws/services/lambda_/test_lambda.py, tests/aws/services/lambda_/test_lambda.snapshot.json, tests/aws/services/lambda_/test_lambda.validation.json
The operation [UpdateFunctionConfiguration](https://docs.aws.amazon.com/lambda/latest/api/API_UpdateFunctionConfiguration.html) does not support updating the function [Handler](https://docs.aws.amazon.com/lambda/latest/api/API_UpdateFunctionConfiguration.html#lambda-UpdateFunctionConfiguration-request-Handler) in LocalStack. This issue was reported in a support case.
* Add a test `test_lambda_handler_update` to test updating a Lambda function handler
* Add API support for updating the function handler in the Lambda provider
* Introduce a new `id` in the version manager that can be used as a globally unique key within the assignment service to avoid key clashes for updating `$LATEST`
In addition to the missing API operation (easy fix), I discovered a race condition in our version manager …
=> Fix Lambda handler update for UpdateFunctionConfiguration

localstack/services/lambda_/provider.py, tests/aws/services/lambda_/test_lambda.py, tests/aws/services/lambda_/test_lambda.snapshot.json, tests/aws/services/lambda_/test_lambda.validation.json
[UpdateFunctionCode](https://docs.aws.amazon.com/lambda/latest/api/API_UpdateFunctionCode.html) does not support updating the [Architectures](https://docs.aws.amazon.com/lambda/latest/api/API_UpdateFunctionCode.html#lambda-UpdateFunctionCode-request-Architectures) (e.g., x64 => ARM).
This issue has been reported and reproduced by @cabeaulac based on customer input.
* Adjust the mixed architecture test `test_mixed_architecture` to use `UpdateFunctionCode`
* Implement Architecture update in `UpdateFunctionCode`
Our CI pipeline currently does not support cross-architecture emulation. Therefore, this change can only be tested locally on a machine with cross-architecture support (e.g., ARM MacBook):
1. Unskip `tests.aws.services.lambda_.test_lambda.TestLambdaBehavior.test_mixed_architecture` …
=> Fix architecture update for Lambda function

tests/aws/services/sns/test_sns.py
SNS provides developer endpoints for introspection and debugging. These endpoints accept the account ID and region for filtering purpose.
This PR makes a slight fix to the test so that assertions are made in the correct account ID and region ie. the test account ID and region. Earlier running the test in non-default account ID or region would cause failures because the resources would be created in the test region but assertion would happen in the default region ie. 'us-east-1'.
Cherry picked from #8204
=> SNS: Fix test assertions to query to correct account and region

Makefile, localstack/cli/plugin.py, localstack/cli/plugins.py, localstack/extensions/api/extension.py, localstack/packages/api.py, localstack/runtime/hooks.py, localstack/services/cloudformation/resource_provider.py, localstack/services/internal.py, localstack/services/lambda_/invocation/plugins.py, localstack/services/lambda_/invocation/runtime_executor.py, localstack/services/plugins.py, localstack/state/snapshot.py, localstack/utils/bootstrap.py, pyproject.toml, requirements-base-runtime.txt, requirements-basic.txt, requirements-dev.txt, requirements-runtime.txt, requirements-test.txt, requirements-typehint.txt, setup.cfg
This PR upgrade plux to 1.7 which provides python 3.12 support (see #10235). The PR also migrates `plugin` imports to the new way to do things (`from plux import ...`). Since 1.7 is backwards compatible, we can make these changes for ext separately.
Moreover, plux now has a way of regenerating entrypoints without invoking setup.py (which is deprecated), therefore unblocking us from moving away from a `setup.py` to `python -m build`.
We could also look into removing `localstack.cli.plugins`, and move some of the functionality to plux (if needed).
* localstack now uses plux>=1.7 (also adds a constraint for <2 where restructuring is expected)
* `make entrypoints` now uses the plux frontend `python -m plux entrypoints` instead of `setup.py plugins egg_info`
* localstack now favors `from plux` …
=> upgrade plux to 1.7

localstack/services/s3/constants.py, localstack/services/s3/presigned_url.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.validation.json
Currently in LocalStack, in order to use pre-signed URLs while validating the signature (with `S3_SKIP_SIGNATURE_VALIDATION` set to false), the user needs to set hardcoded credentials: `test`/`test`. 
This is due to the fact that we did not retrieve the Secret Access Key linked to the sent Access Key Id, which is needed to take the incoming request server side, sign it as well and compare with the received signature. 
We also used the `TEST_AWS*` credentials to generate the signature server side, which was a way for our test to always work as those are hardcoded. 
- Implement a way to retrieve the Secret Access Key of the user by directly accessing the moto backend, as there are no public API to retrieve the secret access key for obvious security reasons
- however, as we don't create IAM …
=> update S3 pre-signed credentials logic

tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.snapshot.json, tests/aws/services/sqs/test_sqs.validation.json
While investigating a support case, I stumbled upon this behaviour which is not yet implemented. If a message uses the same message deduplication ID while the fifo queue is set to "[high throughput mode](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/high-throughput-fifo.html)", the deduplication id seems to be evaluated at a group level and not at the queue level. The effects on ordering still need to be investigated once we implement this feature (it is unclear to me why I would use this high throughput fifo queue over a regular queue).
- adds 1 test each for:
- Same deduplication id with different message groups, normal mode
- Same deduplication id with different message groups, high throughput mode
=> Sqs fifo same dedup different message groups

localstack/testing/pytest/validation_tracking.py, localstack/testing/scenario/provisioning.py
Synthesized CloudFormation stacks (from CDK) and recorded validation files (i.e., `.validation.json`) are not compliant with our linter rules requiring a trailing newline. Example:
```diff
diff --git a/tests/aws/cdk_templates/HelloWorld/HelloWorldStack.json b/tests/aws/cdk_templates/HelloWorld/HelloWorldStack.json
index 19b415de9..f2a4165e2 100644
--- a/tests/aws/cdk_templates/HelloWorld/HelloWorldStack.json
+++ b/tests/aws/cdk_templates/HelloWorld/HelloWorldStack.json
@@ -3,7 +3,7 @@
"MyBucketF68F3FF0": {
"Type": "AWS::S3::Bucket",
"Properties": {
"BucketName": "my-unique-bucket-name-2942856d"
},
"UpdateReplacePolicy": "Retain",
"DeletionPolicy": "Retain"
@@ -16,4 +16,4 @@
}
}
}
-}
\ No newline at end of file
+}
diff --git a/tests/aws/scenario/hello_world/test_hello_world.validation.json …
```
=> Add trailing newline for linter compliance

bin/docker-entrypoint.sh
With #7197, we added a big warning to warn users when using our community project's Docker image with LocalStack Pro (as a preparation for the split of the images executed with v2 in #7927.
With v3, we deprecated the `LOCALSTACK_API_KEY` in favor of `LOCALSTACK_AUTH_TOKEN` in our pro offerings.
This PR adjusts the warning such that it also warns users when an auth token is used with the Docker image of the community project.
- Also check if the auth token is set when trying to warn the users that they might be using the wrong image.
- I tested the script locally:
```bash
LOCALSTACK_API_KEY="1" LOCALSTACK_AUTH_TOKEN="1" ./bin/docker-entrypoint.sh
LOCALSTACK_API_KEY="1" ./bin/docker-entrypoint.sh
LOCALSTACK_AUTH_TOKEN="1" ./bin/docker-entrypoint.sh
LOCALSTACK_API_KEY="" …
```
=> fix pro auth token check

localstack/services/sts/models.py, localstack/services/sts/provider.py, localstack/testing/pytest/fixtures.py
There is no API for retrieving session attributes once the session is created. Since we need the session tags for IAM evaluation, we need to store them.
We store them by access key id instead of session ARN, to avoid collisions with identical SessionNames (those sessions still preserve the right session tags).
* Allow `create_role` fixture users to pass additional variables
* Save session tags based on access key id.
=> Save session tags when assuming a role

.github/workflows/upgrade-python-dependencies.yml
Upgrading the botocore dependencies and the regular dependencies might run into conflicts at some point. Therefore we should only upgrade the other dependencies after the botocore dependency upgrades are already merged.
This PR changes the schedule so that the upgrade of the pinned dependencies happens on Tuesday morning instead of Monday morning, so that we have time to merge the botocore upgrades before the PR for the other dependencies is created.
=> Change schedule for dependency pin upgrade

localstack/services/cloudformation/engine/template_deployer.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-cachecluster.html#aws-resource-elasticache-cachecluster-return-values
For -ext we need to support a case where the schema has a conflict between the specified readOnlyProperties, i.e. normally the attributes and the actual property spec. 
Example:  a `!GetAtt Cluster.RedisEndpoint.Address` will look up `RedisEndpointAddress` on the resource
- Try to access attribute/property by removing `.` from the attribute name
=> Add support for CFn dot attributes that conflict with schema

.circleci/config.yml, .github/workflows/tests-cli.yml, .github/workflows/tests-podman.yml, .github/workflows/tests-pro-integration.yml, .github/workflows/tests-s3-image.yml
Currently, our CI tracking in Tinybird does not take into account the concept of a workflow (and reruns). This makes it difficult to truly understand if a workflow is finished or not.
This PR adds a notion of a workflow to tinybird by pushing information about workflows at the end of each run attempt. To this end, a github action, published on the marketplace was added: https://github.com/marketplace/actions/push-workflow-data-to-tinybird
Check in Tinybird if the data contains the same information (+ the newly added workflow start+end information) 
=> Add tracking of entire workflow scopes to Tinybird

localstack/runtime/init.py
Follow up to https://github.com/localstack/localstack/pull/10272#discussion_r1500576710
After an init hook has run, refrain from clearing the environment and doing a full restore. Instead only restore the Boto credentials and region if it has been overridden.
=> Allow extension hooks to modify non-Boto env vars

localstack/services/apigateway/integration.py, tests/aws/services/apigateway/test_apigateway_lambda.py, tests/aws/services/apigateway/test_apigateway_lambda.validation.json, tests/aws/services/lambda_/functions/lambda_aws_proxy_format.py, tests/aws/services/lambda_/test_lambda.py
As reported in #10310, it seems we were overzealous over the validation of the output of the AWS Proxy lambda integration. 
We need to validate that no wrong fields are returned, but no field is mandatory. 
The documentation was not clear on that:
https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format
- added a test to validate different formats of return of the lambda function
- updated the logic, not sure why it's duplicated in 2 spots but made it in both for now to be sure. We can refactor this in the future
=> update validation of Lambda AWS Proxy format

localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
As reported in #10309, we were supporting a multipart form that AWS supported. Thanks to the user's reproducer, I could inspect the request we received and see the differences:
This were the two different lines:
```
Content-Disposition: form-data; name="file"
Content-Disposition: form-data; name="file" filename="file"
```
Which made the access to `context.request.files["file"]` fail because it could not really parse `file` as a file because it had no filename. 
- added a case to directly fetch the file from the form is it is present there (if it is not, it is in the form) and updated the logic around that
- added a test reproducing this exact case
- also added a test case for when we don't set the multipart/form header, to prevent future issues
Also found something around the …
=> fix pre-signed POST when file is passed as regular form field

localstack/aws/serving/edge.py, localstack/aws/serving/werkzeug.py, localstack/config.py
There have been several situations in the recent past where we needed to figure out whether certain issues come from our Gateway or Hypercorn. Because we have no alternative way of serving the gateway other than hypercorn, this is very difficult. This PR does some refactoring and provides a first alternative: a werkzeug dev server, that can be activated by setting `GATEWAY_SERVER=werkzeug`.
The werkzeug dev server integration for now is mostly for testing/development purposes. With werkzeug there are also some expected test failures (websockets, anything streaming or HTTP2 related). So I wouldn't run a test suite on this regularly. Here's [a test run](https://app.circleci.com/pipelines/github/localstack/localstack/22651/workflows/3ab377f0-36b7-4bdd-a049-3491fe7716a5) showing the remaining …
=> add option to serve gateway through werkzeug

localstack/services/cloudformation/resource_provider.py, localstack/services/lambda_/resource_providers/aws_lambda_permission.py
Addresses a remaining issue from https://github.com/localstack/localstack/pull/10273 that was reported in https://github.com/localstack/localstack/issues/10169
Basically while the removal itself was now fixed, sometimes we perform delete operations in updates that can lead to similar issues because the resource was deleted first.
The proper fix will be in the update rework at some point but for now this should unblock further users that try to redeploy their resources.
- Add naive fallback for update operations (similar to delete operations). 
- Fix AWS::Lambda::Permission to just continue when the expected existing policy is missing (This will usually be caused by the uncontrolled delete that occurs before the update)
Verified against cdk deployment provided …
=> Add fallback for deletes in updates and fix update for AWS::Lambda::Permission

.github/workflows/tests-pro-integration.yml
Last bump to 14.10 was here: https://github.com/localstack/localstack/pull/9818
[Yesterday another bump to 14.11 was released](https://launchpad.net/ubuntu/+source/postgresql-14) breaking the pro integration pipeline.
- Update pinned postgres dependency to 14.11
=> Bump pinned postgres version in CI to 14.11

tests/aws/services/acm/test_acm.py, tests/aws/services/acm/test_acm.snapshot.json, tests/aws/services/acm/test_acm.validation.json
I wish to use ACM's `import_certificate` in a test, and want to ensure that it's behaviour is validated against AWS.
- Validate import_certificate test
A lot of fields in the `describe_certificate` response are skipped, due to mismatches between how `moto` and AWS represent the certificates, however some important fields _are_ validated:
* `CertificateArn`
* `DomainName`
* `KeyAlgorithm`
* `NotAfter`
* `NotBefore`
* `Status`
* `Type`
=> Validate import_certificate test

localstack/services/apigateway/resource_providers/aws_apigateway_usageplankey.py, localstack/services/kinesis/resource_providers/aws_kinesis_streamconsumer.py
When trying to do some analysis over the implemented resources / operations, I found that two resources had some issues in their implementation of deletes.
- Fix `AWS::ApiGateway::UsagePlanKey`: removed the exception raising
- Fix `AWS::Kinesis::StreamConsumer`: delete / read operations were exchanged
=> Fix delete issues in resource providers for "AWS::ApiGateway::UsagePlanKey" and "AWS::Kinesis::StreamConsumer"

localstack/services/cloudformation/provider_utils.py
Extended `keys_pascalcase_to_lower_camelcase` cloudformation resource provider util since a few resources need this functionality to be recursive.
- make `keys_pascalcase_to_lower_camelcase` recursive
=> Make keys_pascalcase_to_lower_camelcase recursive

localstack/services/apigateway/helpers.py, tests/aws/services/apigateway/test_apigateway_common.py, tests/aws/services/apigateway/test_apigateway_common.validation.json, tests/unit/test_apigateway.py
As reported in #10311, the order of resource creation mattered in our route matching logic, because we put at the same level "exact" matching and "parameter" matching. 
This is a follow up from #9208 in a way, which fixed the logic around method matching, but kept a flaw in the logic. 
- only do an early return if we have an exact match. If we have regular parameter matching, return the resource with the least parameters in the path, which means it has more "hardcoded" values. Keep the proxy logic the same
- add cases in the unit tests, which validate the order of the resources
- also add a validated integration test with the user use-case
I've also tested the use reproducer given here: https://github.com/Garethp/localstack-bugs/tree/order-dependant-path-parts, with instructions on how to …
=> fix API Gateway route matching order

localstack/services/sqs/models.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.snapshot.json, tests/aws/services/sqs/test_sqs.validation.json
Follow-up of #10274 
This PR implements "FIFO high-throughput" mode. More precisely, since we do not enforce any rate limits for SQS, this PR adds the necessary changes in regards to the deduplication behaviour.
Usually, messages in a queue are treated as duplicates simply if they have the same deduplication ID. Message groups are ignored. In HT mode deduplication happens at MessageGroup level.
On a side-note: it seems that you cannot change a "regular" FIFO queue to a HT one after creation. You can change the attributes, but AWS does not seem to change the deduplication behaviour of the queue. This makes it necessary to track HT FIFO queues somehow. For now this is simply a flag because a new queue type seemed like overkill.
- adds deduplication behaviour for high-throughput mode FIFO …
=> Add SQS high-throughput deduplication behaviour

README.md
This PR is raised to correct a minor typo found in the documentation under the "Getting Started" section. The FAQ link was mistakenly labeled as "Frequency Asked Questions," which could potentially confuse readers or detract from the professional quality of the documentation. Correcting this typo enhances readability and ensures accuracy in the documentation.
Related issue: https://github.com/localstack/localstack/issues/10343
Corrected the typo from "Frequency Asked Questions" to "Frequently Asked Questions" in the documentation markdown file responsible for the FAQ link description.
=> fix typo in FAQ link description, closes #10343

localstack/services/redshift/resource_providers/aws_redshift_cluster.py, tests/aws/services/cloudformation/resources/test_redshift.py, tests/aws/services/cloudformation/resources/test_redshift.validation.json, tests/aws/templates/cfn_redshift.yaml
@maxhoheiser found some issues with the current provider which this PR aims to address
- Made create wait for the actual cluster state
- Made delete wait for the resource not existing anymore
- Added missing read-only properties (`Endpoint.Address`, `Endpoint.Port`)
- Extended test with GetAtt
=> Fix attributes, create and delete for AWS::Redshift::Cluster

.circleci/config.yml, .github/workflows/tests-cli.yml, .github/workflows/tests-podman.yml, .github/workflows/tests-pro-integration.yml, .github/workflows/tests-s3-image.yml
The tracking of workflows does not happen currently when CircleCI tests are failing. Also, the tracked job ID in circle-ci does not match the semantics of the job id in the GitHub actions. In CircleCI it is a specific singular job run in a workflow. In GitHub it means the classifier of a job inside all the workflows.
- Use a [workaround](https://discuss.circleci.com/t/workaround-run-jobs-sequentially-regardless-of-the-outcome-of-the-required-jobs/40807) to send circle ci workflow data also on fail (something which CircleCI can't do out of the box)
- Set the job id in the circle-ci job to the classifier of the job.
- Set the GH action version to a major tag so that it does get minor release updates automatically
For the CircleCI fix, see these two (simplified) workflow runs:
1. In the …
=> Fix CircleCI workflow tracking

localstack/services/ec2/resource_providers/aws_ec2_instance.py
Initially introduced into the legacy model with https://github.com/localstack/localstack/pull/8957
Users reported this was broken again, so I investigated and found that there was a small bug in the provider migration that caused this setting to never be passed to the API call.
- Fix param selection for API call
=> Fix UserData regression from provider migration in AWS::EC2::Instance

localstack/services/ec2/resource_providers/aws_ec2_instance.py
During migration to new resource provider model, update method from GenericModel was skipped. 
This update reintroduces update
=> Added update for "AWS::EC2::Instance" CFn Resource Provider

.github/workflows/tests-pro-integration.yml, .github/workflows/tests-s3-image.yml, tests/integration/docker_utils/test_docker.py
Unfortunately, it turns out that the fix to avoid the execution of test pipelines which rely on secrets implemented in https://github.com/localstack/localstack/pull/9383 is not correctly working, as we saw with the workflows executed on the following PRs:
- https://github.com/localstack/localstack/pull/10363
- https://github.com/localstack/localstack/pull/10365
It turns out that `github.repository` evaluates to the PR target repo (which in this case is `localstack/localstack`.
However, we want to make sure that the source and the target of the PR are not the same repo.
This PR tries to fix this condition by checking the pull request head target as described in https://github.com/orgs/community/discussions/26829.
- Prevent the execution of the "Community Tests against Pro" (which …
=> fix workflow execution for PRs coming from forks

localstack/services/dynamodbstreams/dynamodbstreams_api.py, localstack/services/kinesis/resource_providers/aws_kinesis_stream.py
Deleting kinesis streams sometimes fails due to still existing consumers and/or because it is trying to be deleted while not in `ACTIVE` state yet.
- Add flag to delete so that we can delete even though consumers are still present
- Add flag also to the deletion of streams for dynamodb streams and remove exception suppression
=> Improve delete reliability for kinesis streams

localstack/services/stepfunctions/asl/component/common/error_name/failure_event.py, localstack/services/stepfunctions/asl/component/common/payload/payloadvalue/payloadbinding/payload_binding_path.py, localstack/services/stepfunctions/asl/component/state/state_execution/execute_state.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_map/item_reader/resource_eval/resource_output_transformer/resource_output_transformer_csv.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_map/item_reader/resource_eval/resource_output_transformer/resource_output_transformer_json.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/iteration_worker.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_parallel/branches_decl.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_api_gateway.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_aws_sdk.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_callback.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_dynamodb.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_events.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_lambda.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_sfn.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_sns.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_sqs.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/state_task.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/state_task_lambda.py, localstack/services/stepfunctions/asl/component/state/state_fail/state_fail.py, localstack/services/stepfunctions/asl/component/state/state_wait/wait_function/timestamp.py, localstack/services/stepfunctions/asl/component/state/state_wait/wait_function/timestamp_path.py, tests/aws/services/stepfunctions/templates/base/base_templates.py, tests/aws/services/stepfunctions/templates/base/statemachines/wait_timestamppath.json5, tests/aws/services/stepfunctions/utils.py, tests/aws/services/stepfunctions/v2/base/test_wait.py, tests/aws/services/stepfunctions/v2/base/test_wait.snapshot.json
Resolves https://github.com/localstack/localstack/issues/9722
We've been assuming that all timestamps should only include up to second precision, but StepFunctions on AWS also allows specifying milliseconds or microseconds (though they seem to be ignored anyway)
- Added tests for multiple different timestamp formats in `TimestampPath` (both positive & negative)  
=> Fix parsing of StepFunction timestamps 

localstack/services/cloudformation/engine/template_deployer.py, localstack/services/cloudformation/resource_provider.py, tests/aws/services/stepfunctions/v2/timeouts/test_timeouts.py
First part of the cleanup, now that we have basically finished the migration of the resource providers
- Remove adapter for legacy providers
- Remove special cases that were only in place for legacy usage
- Stricter handling of the returned OperationStatus from a resource provider
- Improved exception message for `TimeoutError` (now includes logical resource id / type)
- Delete old models
=> Disable legacy CFn model execution

localstack/services/apigateway/patches.py, localstack/services/apigateway/provider.py, tests/aws/services/apigateway/test_apigateway_common.py, tests/aws/services/apigateway/test_apigateway_common.snapshot.json, tests/aws/services/apigateway/test_apigateway_common.validation.json
Enhance parity for API Gateway deletion of wildcard method settings. This issue was recently reported by a customer - Terraform is running this particular type of API requests when deleting API GW resources and stages, which is currently leading to errors (see screenshot below):
* handle special logic to the provider to handle updates (for `op=remove`) for wildcard method settings (`*/*`)
* fix the default value for `throttlingBurstLimit`, which moto currently returns as `2000`, but AWS returns `5000`
* add a new snapshot test to cover the functionality
* refactor existing test and pull the creation of API/stage out into a `_create_api_with_stage` fixture, for better re-usability
=> Enhance parity for API Gateway deletion of wildcard method settings

localstack/services/s3/v3/models.py, localstack/services/s3/v3/provider.py, localstack/services/s3/v3/storage/core.py, localstack/services/s3/v3/storage/ephemeral.py, tests/aws/services/s3/test_s3_concurrency.py, tests/unit/test_s3.py
As reported in #10003 (also in https://github.com/apache/arrow-rs/issues/5283), we would sometimes encounter an error when doing a lot of concurrent access (read and write) to S3 on the same object. 
The bug is extremely hard to reproduce, the only way I could do it was by running the LocalStack image with the docker flag `--cpus=0.5` to simulate a constrained environment, and run the rust test suite of `object_store` (which is really fast) forever until it would break (between 5% and 10% of the time I would say...). 
When it would fail, we would have a cryptic message from the ASGI bridge. After reproducing the issue a few times, I could add a bunch of debug statement in `rolo` and find the culprit:
A GetObject request with Content-Length set to 1, with the key prefix RACE-, followed by …
=> refactor s3 storage to use context manager to avoid race condition

localstack/utils/threads.py
I noticed log lines in the builds during shutdown
```
'Thread' object has no attribute 'stop'
'Thread' object has no attribute 'stop'
...
```
After some digging, I found that our new stepfunctions provider is putting plain python threads into `TMP_THREADS` that don't have a `stop` attribute. This PR doesn't fix this problem, but it improves error logging during shutdown for these types of issues.
While doing that, I noticed that those stepfunction threads aren't daemon threads, and may potentially be blocking the shutdown, so I added specific logging for that as well.
I also noticed that `FuncThread` sets `self.daemon = True`, but it's never passed to the constructor which does some additional setup to create a daemonic thread.
* `FuncThread` instances are now properly instantiated as …
=> fix functhread daemon status and tmp_thread cleanup

tests/aws/services/cloudwatch/test_cloudwatch.py, tests/aws/services/cloudwatch/test_cloudwatch.validation.json
This pull request includes a documentation string for a test that verifies a specific functionality of the CloudWatch service. Additionally, an assertion has been added to ensure that the snapshot accurately reflects the expected values.
- Docstring  and validation before snapshot added to test
=> add docstring for cw test and assertion

localstack/services/dynamodb/provider.py, localstack/services/dynamodb/utils.py, localstack/services/dynamodbstreams/dynamodbstreams_api.py
Following #10411 and other reports from users, we need to investigate the performance issues of DynamoDB when streams are configured for the table (DynamoDB Streams or Kinesis).
This PR will try to explain the different changes done to get better results. After the changes, benchmarks will be provided to show the progress.
Maybe a bit of explanation on how we handle streams right now:
If the table has a stream configured, we will try to fetch the item to be inserted with a `connect_to` call directly to LocalStack (there can also be additional calls for the schema of the table), to check if the item already existed and if it will be updated.
We prepare the record to be sent to DynamoDB streams and/or Kinesis, if they're configured. 
Then, we forward the event to be sent (always via Kinesis …
=> fix DDB performance when Streams are enabled

tests/aws/services/lambda_/functions/lambda_s3_integration.mjs, tests/aws/services/lambda_/functions/lambda_s3_integration_presign.mjs, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.validation.json
~It seems the pipeline just failed with some missing dependency for some lambdas used in S3: `fast-xml-parser`. Not sure what produced this, maybe it's not a default dependency anymore.~
Edit: ah, well, they updated it. https://github.com/aws/aws-sdk-js-v3/pull/5869
It seems they released a version with an issue, so this is not blocking anymore. I'll remove the added dependency but updating the lambda can't be bad. 
~Added the dependency to the list of install.~
I've also spotted that Node14 is not supported anymore in lambda, so I've updated the lambda used to Node 20 + to use ES6.
=> update s3 lambdas to node20

localstack/services/s3/constants.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
As reported in #10393, the `GLACIER_IR` is not an archive type and can be retrieved instantly.
- update an existing test to validate the instant retrieval of storage classes or not
- remove `GLACIER_IR` from the archive types
=> fix S3 GLACIER_IR not being an archive type

tests/aws/services/stepfunctions/templates/callbacks/statemachines/sqs_wait_for_task_token_with_timeout.json5, tests/aws/services/stepfunctions/templates/errorhandling/statemachines/task_service_lambda_invoke_catch_timeout.json5, tests/aws/services/stepfunctions/templates/timeouts/statemachines/lambda_wait_with_timeout_seconds.json5, tests/aws/services/stepfunctions/templates/timeouts/statemachines/service_lambda_map_function_invoke_with_timeout_seconds.json5, tests/aws/services/stepfunctions/templates/timeouts/statemachines/service_lambda_wait_with_timeout_seconds.json5, tests/aws/services/stepfunctions/templates/timeouts/statemachines/service_sqs_send_and_wait_for_task_token_with_heartbeat.json5, tests/aws/services/stepfunctions/v2/callback/test_callback.snapshot.json, tests/aws/services/stepfunctions/v2/callback/test_callback.validation.json, tests/aws/services/stepfunctions/v2/error_handling/test_task_service_lambda.snapshot.json, tests/aws/services/stepfunctions/v2/error_handling/test_task_service_lambda.validation.json, tests/aws/services/stepfunctions/v2/timeouts/test_heartbeats.py, tests/aws/services/stepfunctions/v2/timeouts/test_heartbeats.snapshot.json, tests/aws/services/stepfunctions/v2/timeouts/test_heartbeats.validation.json, tests/aws/services/stepfunctions/v2/timeouts/test_timeouts.py, tests/aws/services/stepfunctions/v2/timeouts/test_timeouts.snapshot.json, tests/aws/services/stepfunctions/v2/timeouts/test_timeouts.validation.json
We've noticed some inconsistency in the StepFunctions tests, particularly related to timeout exceptions. These issues arise due to the strict 1-second timeout value. Consequently, there are instances where the interpreter doesn't have sufficient time to log the events for execution start and scheduling. While this behavior aligns with expectations, our focus lies in validating the state machine's sequence of events. We're particularly interested in testing the scenario where the state returns early.
This pull request aims to address these inconsistencies by mitigating the flakiness of these tests. The proposed solution, for now, involves increasing the timeout or heartbeat time allocated to the states.
- Increased Timeout/Heartbeat value
- Recomputed relevant snapshots
=> [SFN] Reduce Flakiness of Timeout and Heartbeat Tests

localstack/services/stepfunctions/provider.py, tests/aws/services/stepfunctions/v2/test_sfn_api.py, tests/aws/services/stepfunctions/v2/test_sfn_api.snapshot.json, tests/aws/services/stepfunctions/v2/test_sfn_api.validation.json, tests/aws/services/stepfunctions/v2/test_sfn_api_versioning.py, tests/aws/services/stepfunctions/v2/test_sfn_api_versioning.snapshot.json, tests/aws/services/stepfunctions/v2/test_sfn_api_versioning.validation.json
This PR enhances the detection of irregularities in api action requests concerning the arns given. Specifically, it improves the throwing of InvalidArn, StateMachineDoesNotExist, ExecutionDoesNotExist, ExecutionDoesNotExist errors. It also adds relative negative tests, and positive tests were missing.
Closes: #10382
- Detection of Invalid StateMachine Arns
- Detection of Invalid StateMachine Execution Arns
- Improved message body of errors: InvalidArn, StateMachineDoesNotExist, ExecutionDoesNotExist
- Added Arn validation in DescribeStateMachine, DescribeStateMachineForExecution, StartExecution, DescribeExecution, GetExecutionHistory, DeleteStateMachine, DeleteStateMachineVersion, StopExecution
- Added Arn validation and StateMachine existence check in ListExecutions, …
=> [SFN] Enhancements to api actions validations: InvalidArn, StateMachineDoesNotExist, ExecutionDoesNotExist

localstack/services/sns/provider.py, tests/aws/services/sns/test_sns.py, tests/aws/services/sns/test_sns.snapshot.json, tests/aws/services/sns/test_sns.validation.json
Found out this small issue when launching a benchmark without the initial setup. When calling `SNS.Publish(Message="test", TopicArn="")`, boto accepts it but it fails on LocalStack side. 
- add a test for the issue
- add a small check to use an empty string if the value is falsy
=> fix SNS Publish exception when using empty topic

localstack/services/lambda_/resource_providers/aws_lambda_function.py
Custom resource models backed by nodejs lambda are experiencing deployment issues as a result of the nodejs cfn-response file containing an additional line ending character within the container, and the request is directing traffic to port 443.
- convert standard string to raw string to avoid extra \n character in the container code
- the request for the insertion of the resource deployment into the bucket uses url port not directly 443
The custom resource are not able to be deployed on this project so there is no need for a test
=> add fix for cfn-response code for nodejs custome resource

localstack/config.py, localstack/services/sqs/models.py, localstack/services/sqs/utils.py, tests/unit/test_sqs.py
After a lengthy follow-up discussion of #9753, we decided to extend the "dynamic" SQS endpoint strategy to also guess path, standard, or domain strategy of the given host URL.
When starting localstack with `SQS_ENDPOINT_STRATEGY=dynamic`, it will now behave as follows:
* path (fallback)
```
% awslocal sqs list-queues                     
{
"QueueUrls": [
"http://localhost:4566/queue/us-east-1/000000000000/foobar"
]
}
```
* standard (when using `sqs.<region>.<host>`)
```
% aws --endpoint-url=https://sqs.us-east-1.localhost.localstack.cloud:4566 sqs list-queues
{
"QueueUrls": [
"https://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/foobar"
]
}
```
:warning: note that, using `--endpoint-url=https://sqs.localhost.localstack.cloud:4566` may not behave as expected, because we …
=> make SQS dynamic endpoint strategy guess the endpoint strategy used

pyproject.toml
The key for the non-python package data is set to `localstack_ext` which is wrong and leaves out those files in the distribution.
Change the key to the correct `localstack` so that those files are included
=> Set package data key to `localstack`

localstack/services/lambda_/invocation/docker_runtime_executor.py, localstack/services/lambda_/invocation/runtime_executor.py, localstack/services/lambda_/packages.py, tests/aws/services/lambda_/test_lambda.py
We currently always run a `chmod` operation on certain task related folders when starting up a Lambda environment.
This however can take a lot of time if lambda prebuild mode is on, since it will do a copy on write operation on all changed files (which can be a lot). This introduces unnecessary IO load and can lead to extremely long startup times.
We should avoid running `chmod` on everything but `/tmp` in prebuild mode, and configure which folders to `chmod` on the LocalStack side, to avoid relying on potentially unreliable heuristics.
* Update lambda init to include localstack/lambda-runtime-init#34
* Configure lambda init to run chmod operations:
- On `/tmp`: always
- On `/var/task` and `/opt` if there are layers configured (no matter if pro or not)
* Configure prebuild mode to run …
=> Update runtime init, add dynamic configuration for folders to run chmod on in Lambda

localstack/services/sqs/models.py, localstack/services/sqs/provider.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.snapshot.json, tests/aws/services/sqs/test_sqs.validation.json, tests/aws/services/sqs/test_sqs_move_task.py, tests/aws/services/sqs/utils.py
As discussed in #10414, SQS DLQ redrive returns the messages back to their original source when no destination ARN is specified. To implement that, "some sort of tracking" is needed, and it turns out that AWS already has an attribute for that, namely the `DeadLetterQueueSourceArn` (which of course is not really documented anywhere...).
Basically what @baermat suggested here:
>  This is only supported for DLQs, and we know where we move to DLQ -> add an internal field to sqs messages dlq_origin or something similar. Set this when moved to DLQ. Then retrieve the source from the message itself.
which is exactly how it's implemented now.
A necessary fix was to make sure that the `message["Attributes"]` dict is retained correctly when it's being passed around through the queues. I was also …
=> fix SQS DLQ message attributes and redrive into multiple source queues

localstack/aws/serving/twisted.py, localstack/config.py, pyproject.toml, requirements-dev.txt, requirements-runtime.txt, requirements-test.txt, requirements-typehint.txt, tests/integration/aws/test_app.py
The coded added for twisted integration in #9834 moved to rolo in https://github.com/localstack/rolo/pull/8, which also includes websocket support. This PR refactors our existing code to use the new rolo version.
* Remove duplicate code from rolo code migration
* Use rolo 0.4.0
* `localstack.http.asgi.ASGIWebSocket` is removed from the API
* added httpx as test library to test http2 support directly
=> use rolo twisted gateway integration

localstack/services/apigateway/templates.py, tests/unit/test_apigateway.py
https://github.com/localstack/localstack/issues/10380
Read the Accept header of the HTTP request and use the corresponding template and validate the response (only XML support added)
Define an API gateway with an XML template as response_template, and make an HTTP request with Accept: application/xml header. The response must be formatted as a valid XML instead of JSON.
- Add support to other media types
- **I can't label this PR as semver: patch**
=> Support XML responses in api gateway templating

.github/workflows/tests-pro-integration.yml
With https://github.com/localstack/localstack/pull/10186, we tried to optimize the tests a bit in order to mitigate issues where the Community Tests against Pro would run out of disk space on the default GitHub runners.
Unfortunately, we are seeing these issues again, which is why we will (as predicted in the previous PR) use an action to remove some of the (insane amount of) unused toolchains on the runner.
- Adds an initial action call for `easimon/maximize-build-space@v10` to remove some unused stuff from the runner.
- The action is quite effective in freeing some disk space, but it can cause issues with Docker (since it might reduce the root partition).
- The action's runtime could also be interesting to look at.
- Both things can be analyzed by triggering multiple runs from this PR's …
=> fix disk space issues in GitHub workflow again

localstack/testing/testselection/github.py, localstack/testing/testselection/scripts/generate_test_selection_from_pr.py
https://github.com/localstack/localstack/pull/10301 introduced a dynamic test selection based on the touched service code.
Unfortunately, this just broke the pipeline of https://github.com/localstack/localstack/pull/10116 (a community contribution) because it expects a `GITHUB_API_TOKEN` which is a secret not being set for PRs coming from forks.
I tested the call to retrieve the PR data locally:
```
curl -v https://api.github.com/repos/localstack/localstack/pulls/10116
```
This call is successful without an auth token.
However, this could be flaky if these runners and their IP are used for a lot of unauthenticated GitHub API calls.
- Make it optional to use the auth token, just send an unauthenticated request in case the token is not available.
- Test if the execution works without the …
=> fix test selection for community contributions

localstack/services/stepfunctions/provider.py, tests/aws/services/stepfunctions/utils.py, tests/aws/services/stepfunctions/v2/test_sfn_api.py, tests/aws/services/stepfunctions/v2/test_sfn_api.snapshot.json, tests/aws/services/stepfunctions/v2/test_sfn_api.validation.json
v2 stepfunctions provider `list-executions` should support `statusFilter`  ... not yet implmented
* added basic statusFilter to  localstack/services/stepfunctions/provider.py
* new test `tests/aws/services/stepfunctions/v2/test_sfn_api.py::TestSnfApi::test_state_machine_status_filter`
basic coverage `tests/aws/services/stepfunctions/v2/test_sfn_api.py::TestSnfApi::test_state_machine_status_filter`
=> Implement basic status filter for StepFunctions list-executions

localstack/services/secretsmanager/provider.py, tests/aws/services/secretsmanager/test_secretsmanager.py, tests/aws/services/secretsmanager/test_secretsmanager.snapshot.json, tests/aws/services/secretsmanager/test_secretsmanager.validation.json
Issue: https://github.com/localstack/localstack/issues/9986
Secret rotation currently doesn't work when the `RotateImmediately` parameter is unset. It looks like this is because `backend_rotate_secret` receives the argument `rotate_immediately` with the value `None` when the parameter `RotateImmediately` is unset (if the argument is unset it defaults to `True`, but in this case it's being explicitly set to `None`), this causes the `new_version_id` to not be set resulting in the error described in the issue `cannot access local variable 'new_version_id' where it is not associated with a value`.
Check if rotate_immediately is `None` and set it to `True` in that case
I'm unable to run any of the tests locally, so that'll be worth paying extra attention to when reviewing.
=> Fix secretsmanager secret rotation failing because RotateImmediately is unset

localstack/services/dynamodb/provider.py
Follow up from #10415
We previously spawned a thread for each incoming request, which resulted in a somewhat unbounded amount of threads being spawn when running benchmarks.
We could see this kind of error in logs:
```python
During handling of the above exception, another exception occurred:
[...]
raise ConnectionClosedError(
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "http://localhost:4566/".
2024-03-15T01:11:04.444  INFO --- [.reactor-120] localstack.request.aws     : AWS dynamodb.BatchWriteItem => 200
2024-03-15T01:11:16.509  WARN --- [uncthread379] urllib3.connectionpool     : Connection pool is full, discarding connection: localhost. Connection pool size: 150 …
```
=> use ThreadPoolExecutor to forward DDB Streams events

localstack/services/lambda_/event_source_listeners/utils.py, tests/aws/services/cloudformation/resources/test_lambda.py, tests/aws/services/cloudformation/resources/test_lambda.validation.json, tests/aws/templates/lambda_dynamodb_event_filter.yaml, tests/unit/services/lambda_/test_lambda_utils.py
While using Lambda event source mappings with Dynamodb Streams there was a bug reported in #10325 surrounding `FilterCriteria`. It appears that the comparison operator `exists` doesn't work as intended when it's false. When `exists` is set to false and the property doesn't exist in the item the lambda doesn't trigger.
For instance in the [AWS tutorial to process events with Lambda and DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.Lambda.Tutorial2.html), when we use `[{"homemade": {"S": [{"exists": false}]}}]` the lambda doesn't trigger when the property is missing in dynamodb `PutItem` call. 
This PR:
- Adds a condition in while filtering the stream record to handle special case of exists when the value is a `dict`. 
- Adds a test case to validate the …
=> fix lambda event source mapping FilterCriteria

localstack/testing/testselection/matching.py, localstack/testing/testselection/opt_in.py, localstack/utils/bootstrap.py, tests/unit/testing/testselection/test_matching.py, tests/unit/utils/test_bootstrap.py
Now that we have the selective test execution for opt-in services introduced in https://github.com/localstack/localstack/pull/10301, we can onboard additional services to the test selection.
In this PR I added the services I own to the list (😻), but it might make sense to collect the first iteration of opt ins here and merge them together.
So please feel free to push to this PR if you want the tests of your service being selectively executed in PRs here.
In order to to so, just:
1. Make sure the mandatory and optional service dependencies in `localstack/utils/bootstrap.py` are correct.
- They should list your service (if it's not completely self-contained).
- `API_DEPENDENCIES`
- This mapping states that a service requires one or more other services to provide it's basic functionality.
- …
=> add opt. service deps, opt-in services to test selection

localstack/testing/aws/util.py
In current implementation `TEST_DISABLE_RETRIES_AND_TIMEOUTS`  would get evaluated to True regardless if it was set to 0 or 1. Only way to get it to be false is to remove it from env variables
Replaced `os.environ.get` with `is_env_true`
=> Fixed issue where TEST_DISABLE_RETRIES_AND_TIMEOUTS would get always evaluated to True

localstack/services/s3/v3/provider.py
As reported by @cabeaulac and @webdev51, we had an issue with CORS when restoring S3 state which would go away if you would create a new bucket. This is because we did not invalidate the S3 CORS cache after loading the state, so it would not be aware of any bucket loaded with the state. 
- add a call to invalidate the CORS cache in the `on_after_state_reset` and `on_after_state_load` hooks. 
The provided steps to replicate the issues:
- first state LocalStack with Pro
```bash
$ awslocal s3 mb s3://test
$ curl -I -H "Origin: https://app.localstack.cloud" https://localhost.localstack.cloud:4566/test
HTTP/2 200 
content-type: application/xml
access-control-allow-origin: https://app.localstack.cloud
access-control-allow-credentials: true
access-control-allow-methods: …
```
=> fix invalidating S3 CORS cache after resetting state or loading

tests/aws/services/stepfunctions/v2/services/test_ecs_task_service.py
While working on another sample I've noticed some cases where we forgot to disable the `skip_teardown` and `force_synth` flags.
- Removes any `force_synth=True` and `skip_teardown=True` cases.
=> Fix skip_teardown and force_synth usage in CDK tests

localstack/services/stepfunctions/backend/execution.py, tests/aws/services/stepfunctions/utils.py, tests/aws/services/stepfunctions/v2/base/test_base.py, tests/aws/services/stepfunctions/v2/base/test_base.snapshot.json, tests/aws/services/stepfunctions/v2/base/test_base.validation.json
Bugfix in how SFN handles an ErrorState without any details.
Example template that I've used to verify this works against AWS:
```
{
"StartAt": "ChoiceStateX",
"States": {
"ChoiceStateX": {
"Type": "Choice",
"Choices": [
{
"And": [{"Variable": "$.type", "StringEquals": "Public"}],
"Next": "Public"
}
],
"Default": "DefaultState"
},
"Public": {"Type": "Pass", "End": true},
"DefaultState": {
"Type": "Fail"
}
}
}
```
Note the `DefaultState` at the end; it does not have an error or cause, and AWS will accept this (and simply return `'cause': None, 'error': None`)
This is what it looks like without these fixes:
```
File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/usr/lib/python3.10/threading.py", line 953, in run …
```
=> SFN: Allow ProgramError without details

localstack/services/dynamodb/models.py, localstack/services/dynamodb/provider.py, localstack/services/dynamodb/utils.py, localstack/services/dynamodbstreams/dynamodbstreams_api.py, tests/aws/services/dynamodb/test_dynamodb.py, tests/aws/services/dynamodbstreams/test_dynamodb_streams.py
When working with DDB Streams and Kinesis Destinations, we would execute a lot of logic for queries with a lot of updated/inserted/deleted records. 
I thought we could improve the throughput by streamlining the process of forwarding records, and making a bit easier to follow by introducing some typing and structure. 
- refactoring around the logic for DDB streams, trying to set up some typing and a notion of "RecordsMap" akin to a context to be passed to be forwarded. 
- improving performance by
- reducing creations of new objects
- no calls to `copy.deepcopy` which pickles/unpickles
- reduce the number of calls to get the table specification, and passing around the data needed instead
- conditionally set the `OldImage` and `NewImage` to the record, to not always have to `pop` it from the …
=> refactor DDB streaming, event creation and forwarding

localstack/services/s3/v3/storage/core.py, localstack/services/s3/v3/storage/ephemeral.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
As reported in the Community Slack, a user encountered an error after copying in place an object in a versioned bucket. The first reported what about a previously fixed issue, which took a while to understand what was the final bug. 
It turns out that I've had a big gap in the logic of the Storage system of S3 when copying in place. To avoid unnecessary copying of data, if the copy operation was detected as "in place", we would return the same underlying file object. However, for versioned bucket, those are not really "in place", they create a new version. 
- fix the logic to not return the same underlying stored object if any of the objects have a version id. Only minor issue is if both objects have their version id set to `null`, which would mean that the bucket has versioning disabled, …
=> fix S3 copy in place in versioned bucket

localstack/services/kms/models.py, localstack/services/kms/provider.py, tests/aws/services/kms/test_kms.py, tests/aws/services/kms/test_kms.snapshot.json, tests/aws/services/kms/test_kms.validation.json
KMS allows you to import key material, that is, create KMS keys with "private keys" you already have. In the context of Localstack this is fairly important now that the old "local-kms" backend was removed since the new backend cannot be preseeded at the moment and controlling key material can be very important in testing.
This PR drops the restriction on encrypt/decrypt for the KeyUsage in ImportKeyMaterial (the restriction for GetParametersForImport was already dropped as part of the fix for #9111) and should therefore fix #10115. It then fixes the issues that crop up when trying to use this with existing code - notably the hardcoded assumption that all imported key material is a symmetric key. Finally, it adds a new test to track this usecase and fixes a few other small issues you bump …
=> KMS: Fixup ImportKeyMaterial for non-symmetric keys

.circleci/config.yml
#10346 introduced reporting of our CircleCI workflow metadata to Tinybird for our internal CI analytics.
Unfortunately, we are seeing that the reporting is not properly updated in case a failed workflow is "rerun workflow from failed":
This is because this really only executes jobs that failed as well as their dependents.
This PR fixes this by also failing the waiter (running alongside the workflow waiting for the pipeline to finish and to report the result) in case any of the steps failed. This results in the waiter being rerun as well with the "Rerun workflow from failed" feature.
- Simplify the waiter jobs to a single job.
- Fail the waiter job in case the outcome of the main workflow is not `success`.
- The last commit always fails and removes the filter to only run the waiter on …
=> fix CircleCI Tinybird reporting on reruns

.circleci/config.yml
https://github.com/localstack/localstack/pull/10282 added workflow metadata tracking using Tinybird.
https://github.com/localstack/localstack/pull/10367 introduced a new test type to the main CircleCI workflow: Multi-accounts and multi-region testing. /cc @sannya-singal 
Currently, these runs cannot be distinguished in the Tinybird datasource.
This PR fixes that by setting a specific Tinybird target datasource in case the multi-accounts tests are executed.
- Use `circle_ci_workflows_ma_mr` as datasource name (instead of `circle_ci_workflows`) in case the `randomize-aws-credentials` parameter is set to `true`.
=> fix Tinybird workflow datasource for multi-account tests

tests/aws/services/resourcegroupstaggingapi/test_rgsa.py, tests/aws/services/resourcegroupstaggingapi/test_rgsa.snapshot.json, tests/aws/services/resourcegroupstaggingapi/test_rgsa.validation.json
Updated test in `ResourceGroupTaggingApi` and made it snapshot validated.
- Changed test cases to be snapshot validated
- Used cleanups to delete resources instead of try catch
=> test: aws validated test cases in the rgsa

localstack/services/secretsmanager/provider.py, tests/aws/services/secretsmanager/test_secretsmanager.py, tests/aws/services/secretsmanager/test_secretsmanager.snapshot.json, tests/aws/services/secretsmanager/test_secretsmanager.validation.json
This Pull Request introduces support for resource-based policies in `secretsmanager`.
**Supported APIS**
- `DescribeSecret`
- `GetResourcePolicy`
- `ListSecretVersionIds`
- `PutResourcePolicy`
- `TagResource`
- `UntagResource`
We now return data for resources that are in other account based on the `ARN` provided.
- NOTE: IAM enforcement is supported in LocalStack PRO - which means we are not testing against unauthorized resource access in Community version.
Added aws validated test cases to access secretsmanager from cross-account.
=> added support for resource based policies in secretsmanager

localstack/utils/aws/aws_responses.py, tests/unit/utils/aws/test_aws_responses.py
As reported in #10451, we would have an issue when trying to parse query string parameters containing a URL. 
I suspected a split somewhere with `http://`. It seems it was a somewhat related issue.
Fix the `parse_query_string` util (actually only used in APIGW, would maybe be good to move it around). 
It was checking for the presence of `http://` in the string (to check if it was a full URL, a path or a query string), but it could be container as a query string parameter also. 
I've replaced it with a regex containing lower case characters between 2 and 5 (for `ws://` to `https://`) now at the beginning of the string. I've added more cases to the test and verified that it fixes the issue. (More tests in the companion PR).
=> fix query string parser with non encoded http url in parameters

localstack/services/apigateway/integration.py, tests/aws/services/apigateway/test_apigateway_lambda.py, tests/aws/services/apigateway/test_apigateway_lambda.snapshot.json, tests/aws/services/apigateway/test_apigateway_lambda.validation.json
As reported in #10437, we were missing the capitalization of Authorization header in API Gateway AWS_PROXY integration. 
This is a weird fix, because it seems that AWS_PROXY integrations are behind CloudFront in some way, because it returns CloudFront headers even if not configured. The user does not have any say in the configuration of said "default" cloudfront distribution. But it seems to have the same logic around the Authorization header.
See https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/add-origin-custom-headers.html#add-origin-custom-headers-forward-authorization
- add a fix to capitalize the authorization header if present in any casing
- modify a currently existing test to verify the assumption
\cc @giograno @Morijarti
=> fix capitalization of Authorization header for AWS_PROXY integration

localstack/services/kms/models.py, localstack/services/kms/provider.py, tests/aws/services/kms/test_kms.py
Add support for creating KMS keys with custom key material using custom tags. This is similar to an existing feature that allows the KMS Key ID to be set when creating KMS keys. This is necessary when working with external systems and decryption or HMACs must work across localstack reboots.
Fixes #8910
* Introduces a new special tag `_custom_key_material_` that can be used when creating a KMS key to set the key material of the key.
* Refactors the existing `_custom_id_` so that it handled in the `KmsKey` model.
I've introduced two new unit tests to ensure the custom key material is working for symmetric and HMAC KMS keys.
=> Support custom key material when creating KMS keys

tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
We ran a pipeline for randomised region and account: [here](https://app.circleci.com/pipelines/github/localstack/localstack/23423/workflows/679f1237-6253-495d-947e-45f19e2fc8e9/jobs/191264/tests) and found that `test_region_header_exists` fails with the following error: 
> >> match key: head_bucket
> 	#x1B[33m(~)#x1B[0m /BucketRegion 'eu-west-1' → region... (expected → actual)
> 
> 	Ignore list (please keep in mind list indices might not work and should be replaced):
> 	["$..BucketRegion"]
So, basically when we set the `TEST_AWS_REGION_NAME` to `eu-west-1` we get this error. 
This PR adds a transformer for region and re-generates the snapshot for `tests.aws.services.s3.test_s3.TestS3.test_region_header_exists`.
=> fix: add transformer to region attribute in failing s3 for 'eu-west-1'

.circleci/config.yml
As per our recent discussions about how to handle the randomised region for cross-accounts workflow considering the fact that not all services are available in all regions we need to limit the number of regions in our scheduled workflow. 
This PR limits the number of regions.
=> add limited number of regions to random creds

localstack/services/secretsmanager/provider.py, tests/aws/services/secretsmanager/test_secretsmanager.py, tests/aws/services/secretsmanager/test_secretsmanager.snapshot.json, tests/aws/services/secretsmanager/test_secretsmanager.validation.json
This PR aims to add support for arn based resource retrivals for the following apis.
- `get_secret_value`
- `put_secret_value`
- `restore_secret`
- `rotate_secret`
- `delete_secret`
- ➕ We now return data for resources that are in other account based on the ARN provided.
- ✅  added snapshot validated test case `RestoreSecret` since we are moving the responses away from moto and there were no validation tests for it.
- 🧹 Cleanup for dead code  
NOTE ⚠️ : IAM enforcement is supported in LocalStack PRO - which means we are not testing against unauthorized resource access in Community version.
Added aws validated test cases to access secretsmanager from cross-account.
- https://github.com/localstack/localstack/pull/10457
=> support for arn based retrivals in secretsmanager

bin/release-helper.sh
https://github.com/localstack/localstack/pull/10497 broke the `set-ver` command of the release-helper script, which in turn prevents us from pushing dev releases in the CircleCI pipeline on `master` runs:
- Workflow run: https://app.circleci.com/pipelines/github/localstack/localstack/23599/workflows/84eb52c3-af01-4bf4-b4f3-a620bb083c1e/jobs/193324
- Executed commands:
```
#!/bin/bash -eo pipefail
source .venv/bin/activate
bin/release-helper.sh set-ver $(bin/release-helper.sh next-dev-ver)
make publish
```
- Output:
```
cat: 3.2.1.dev20240322105931: No such file or directory
Exited with code exit status 1
```
This PR addresses this small issue in the script.
- Fix the `set-ver` command of the release-helper script.
- Tested locally:
```
source .venv/bin/activate
bin/release-helper.sh …
```
=> fix release helper

tests/aws/files/petstore-authorizer.swagger.json, tests/aws/services/apigateway/test_apigateway_import.py, tests/aws/services/apigateway/test_apigateway_import.snapshot.json, tests/aws/services/apigateway/test_apigateway_import.validation.json
We ran a pipeline for randomised region and account: [here](https://app.circleci.com/pipelines/github/localstack/localstack/23423/workflows/679f1237-6253-495d-947e-45f19e2fc8e9/jobs/191264/tests) and found that `test_import_swagger_api` fails with the following error: 
> >> match key: method-pets-get
> 	#x1B[33m(~)#x1B[0m /methodIntegration/uri 'http://petstore.execute-api.eu-west-1.amazonaws.com/petstore/pets' → 'http://petstore.execute-api.region.amazonaws.com/petstore/pets' ... (expected → actual)
> 
> 	Ignore list (please keep in mind list indices might not work and should be replaced):
> 	["$..methodIntegration.uri"]
> >> match key: integration-pets-post
> 	#x1B[33m(~)#x1B[0m /uri 'http://petstore.execute-api.eu-west-1.amazonaws.com/petstore/pets' → …
=> fix 'test_import_swagger_api' for 'eu-west-1'

localstack/services/apigateway/integration.py, localstack/utils/testutil.py, tests/aws/services/apigateway/test_apigateway_basic.py, tests/aws/services/apigateway/test_apigateway_lambda.py, tests/aws/services/apigateway/test_apigateway_lambda.snapshot.json, tests/aws/services/apigateway/test_apigateway_lambda.validation.json
Apigateway's integration with AWS_PROXY can only use POST as integration method. See [AWS Documentation](api-gateway-integration-proxy-only-accepts-POST-method) and documented on issue #10473 . Currently, we were accepting and forwarding any calls with consideration for this expected error to be returned.
Aws does allow for the Proxy Integration to be created even with the wrong method. And returning a Internal Server Error when a call is attempted. This fix will mimic this behavior.
One `aws.validated` test was added to confirm the error message. Many other `aws.unknown` tests were failing as they were creating integration with `integrationHttpMethod` not equal to `POST`. One of these test was removed but in view of the upcoming rework of the service, the other tests simply got patched …
=> Api gateway integration proxy only accepts post method

localstack/services/cloudformation/engine/template_utils.py, tests/aws/services/cloudformation/engine/test_attributes.py, tests/aws/services/cloudformation/engine/test_attributes.snapshot.json, tests/aws/services/cloudformation/engine/test_attributes.validation.json, tests/aws/templates/engine/cfn_getatt_dot_dependency.yml
There is limitation in Localstack's cloudformation implementation (#10481) where it is unable to successfully deploy a resource that utilizes an attribute of another resource when the GetAtt function is used with a string containing a dot instead of an array of parameters.
- fix the function that list the dependencies of a resource
- snapshoted test to validate the behavior
=> add support for getAtt string parameter in dependency

.github/workflows/asf-updates.yml
The latest `ruff` upgrade switched some defaults avoiding unsafe fixes to remove unused imports in init dunder files (since they would change the API interface of the module): https://github.com/astral-sh/ruff/pull/10365 contained in [0.3.3](https://github.com/astral-sh/ruff/releases/tag/v0.3.3).
This causes our ASF update action to fail because of unfixed linting errors: https://github.com/localstack/localstack/actions/runs/8415318713
The changes in the defaults are safe, but we want to explicitly fix this for the generated APIs (which is all in the init dunder) explicitly directly when generating them.
This PR explicitly executes an unsafe lint fix with a changed config on the generated APIs in the ASF update action.
Tested locally:
```
source .venv/bin/activate
python3 -m …
```
=> fix ASF update action to fix unused imports

localstack/services/apigateway/resource_providers/aws_apigateway_method.py
The `AWS::ApiGateway::Method` resource was not using the `authorizedScopes` parameter.
This led to a bug in APIGW Cognito Authorizer as described in the [companion PR](https://github.com/localstack/localstack-ext/pull/2776).
=> Adding missing parameter for authorization scopes

pyproject.toml, requirements-base-runtime.txt, requirements-basic.txt, requirements-dev.txt, requirements-runtime.txt, requirements-test.txt, requirements-typehint.txt
In `localstack-ext`, the dependency pinning can take a very long time now. This is connected to the switch to `pyproject.toml` as well as to backtracking a lot inside the dependencies of `localstack-core`. 
This PR reduces the admissible range for the following packages, so that the backtracking is reduced:
- `awscli>=1.32.69`
- `boto3-stubs>=1.34.69`
Locally, this achieves a reduction in the pinning of `localstack-ext` from 45min to 6min30 on my machine. 
To check it locally, you can replace the dependencies to `localstack-core` in `localstack-ext` to reference this instead:
`localstack-core @ file://localhost/{absolute-path-to-package}#egg=localstack_core`
However, effectively checking the performance is not possible this way, as using such a specific version of `localstack-core` here …
=> Reduce the range of dependencies to speed up pinning

localstack/services/lambda_/provider.py
(Open for suggestions and discussions)
When creating an event-source-mapping localstack is validating some not mandatory parameters.
Removed check for non mandatory parameter and added check for self-managed-kafka service
---
In our scenario we are trying to create the lambda using `sam` but it fails with the event-source-mapping
```
Resources:
MyLambda:
Type: AWS::Serverless::Function
Properties:
Handler: handler.lambda_handler
Events:
SelfManagedKafkaEvent:
Type: SelfManagedKafka
Properties:
KafkaBootstrapServers:
- <host:port>
ConsumerGroupId: MyLambda
SourceAccessConfigurations:
- Type: BASIC_AUTH
URI: arn:aws:secretsmanager:eu-central-1:000000000000:secret:kafka/local-nTMBRS
Topics:
- <topic>
```
But it fails, asking for `EventSourceArn` which is not mandatory for self-managed kafka. …
=> Fix parameter validation for self-managed Kafka event source mapping

tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
Test `test_different_location_constraint` fails for `us-east-2` and throws the following error: 
```
=================================== FAILURES ===================================
__________________ TestS3.test_different_location_constraint ___________________
>> match key: get_bucket_location_bucket_3
(~) /LocationConstraint 'us-east-2' → '<region>' ... (expected → actual)
Ignore list (please keep in mind list indices might not work and should be replaced):
["$..LocationConstraint"]
>> match key: get_bucket_location_bucket_2
(~) /LocationConstraint 'us-east-2' → '<region>' ... (expected → actual)
Ignore list (please keep in mind list indices might not work and should be replaced):
["$..LocationConstraint"]
```
when the scheduled flow was triggered: …
=> fix `test_different_location_constraint` for `us-east-2`

tests/aws/files/petstore-swagger.json, tests/aws/services/apigateway/test_apigateway_extended.py, tests/aws/services/apigateway/test_apigateway_extended.snapshot.json, tests/aws/services/apigateway/test_apigateway_extended.validation.json
There were failing api gateway tests for `eu-west-1` in the workflow: https://app.circleci.com/pipelines/github/localstack/localstack/23655/workflows/49291732-7851-49ea-917a-2a293dde3288/jobs/193896/tests
This PR:
- removes the static `uri` value hardcoded for `eu-west-1`
- regenerates the snapshots
=> fix apigw tests for `eu-west-1`

bin/release-helper.sh
The release helper currently does not commit the generated `version.py` file. (Which is created everywhere consistently with the change in the release workflow)
It adds the `version.py` file to the commits for releasing and incrementing development iteration
Check the changes in the release workflow for guides on how to test this
=> Add version.py file to list of added git files in release helper

.circleci/config.yml
There are failing tests when primary and secondary regions are same. We have set the [TEST_AWS_SECONDARY_REGION_NAME](https://github.com/localstack/localstack/blob/b7f34c67c49c8f8d4aa6e0b08584b248501a64bb/localstack/constants.py#L158) to `ap-southeast-1`.
Example workflow: https://app.circleci.com/pipelines/github/localstack/localstack/23655/workflows/49291732-7851-49ea-917a-2a293dde3288/jobs/193896/tests
This PR removes `ap-southeast-1` from the list of random regions.
=> remove `ap-southeast-1` from random regions

localstack/services/cloudformation/provider.py, localstack/services/cloudformation/stores.py, tests/aws/services/cloudformation/api/test_stacks.py, tests/aws/services/cloudformation/api/test_stacks.snapshot.json, tests/aws/services/cloudformation/api/test_stacks.validation.json
As reported in #10327 , we still have problems while redeploying AWS SAM stacks with the same stack name against LocalStack.
The root cause of this issue is `describe_stack_events` not only returning the events for a single stack, but for all stacks with that name. The expected behavior is for that operation to only work by name if the stack is active (i.e. not deleted), and by id for every stack, but only return the events for one in any case (since there can only be one active with a name, and stack ids are unique anyway).
Also, the `delete_stack` operation by name did not affect the active stack with the name, but the first stack with it (which might already be deleted), leading to deletes not working.
* Add new `find_active_stack_by_name_or_id` function, for operations which work on …
=> Fix handling reuse of stack names for describe stack events / delete stack operations

localstack/services/stepfunctions/asl/component/common/retry/max_attempts_decl.py, tests/aws/services/stepfunctions/templates/scenarios/scenarios_templates.py, tests/aws/services/stepfunctions/templates/scenarios/statemachines/retry_interval_features_max_attempts_zero.json5, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.py, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.snapshot.json, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.validation.json
Currently the SFN v2 interpreter incorrectly reports MaxAttempts declarations with non zero positive integers as the only valid range of values. This excluded the [scenario of zero values](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-error-handling.html), which resulting in no attempts. This PR addresses such preprocessing errors and adjusts MaxAttempts logic to support zero values. It also adds snapshot test for this scenario.
Addresses: #10547 
- Fix preprocessing errors for zero values to handle the correct range
- Adjust MaxAttempts evaluation logic to handle zero attempts
- Added positive snapshot test for MaxAttempts of zero values
=> [SFN] Fix MaxAttempts with Zero Values 

tests/aws/services/lambda_/test_lambda_api.py, tests/aws/services/lambda_/test_lambda_api.snapshot.json, tests/aws/services/lambda_/test_lambda_api.validation.json
The `lambda` test was failing when the [workflow](https://app.circleci.com/pipelines/github/localstack/localstack/23708/workflows/e17be93c-ffcb-446f-a8f0-2f355da30539/jobs/194487/tests) was run against `eu-central-1` with the following error: 
```
>> match key: long_function_arn_exc
#x1B[33m(~)#x1B[0m /Error/Message "1 validation error detected: Value 'arn:aws:lambda:<region>:111111111111:function:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' at 'functionName' failed to satisfy constraint: Member must have length less than or equal to 140" → "1 validation error detected: Value 'arn:aws:lambda:<region>:111111111111:function:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' at 'functionName' failed …
```
=> fix `test_function_arns` for `eu-central-1`

localstack/services/lambda_/api_utils.py, localstack/services/lambda_/provider.py, tests/aws/services/lambda_/test_lambda_api.py, tests/aws/services/lambda_/test_lambda_api.snapshot.json, tests/aws/services/lambda_/test_lambda_api.validation.json
This surfaced when debugging a customer issue where a lambda was invoked via stepfunctions but the specified ARN was incorrect. This lead to a misleading error message which should be fixed with this PR
- Extract regex from exception message and raise ValidationException when a  non-matching function name is provided on invoke(). 
We might want to add this to other places as well but that will require more extensive test adaptations.
=> Validation lambda function name pattern on invoke

tests/aws/services/cloudwatch/test_cloudwatch.py
The `cloudwatch` test was failing when the [workflow](https://app.circleci.com/pipelines/github/localstack/localstack/23708/workflows/e17be93c-ffcb-446f-a8f0-2f355da30539/jobs/194487/tests) was run against `eu-central-1` with the following error: 
```
>> match key: list_dashboards_prefix
#x1B[33m(~)#x1B[0m /DashboardEntries/[0]/Size 225 → 228 ... (expected → actual)
Ignore list (please keep in mind list indices might not work and should be replaced):
["$..DashboardEntries..Size"]
>> match key: list_dashboards
#x1B[33m(~)#x1B[0m /DashboardEntries/[0]/Size 225 → 228 ... (expected → actual)
Ignore list (please keep in mind list indices might not work and should be replaced):
["$..DashboardEntries..Size"]
```
The issue is caused due to variable lengths regions causing difference in `size` …
=> fix `test_dashboard_lifecycle` for `eu-central-1`

localstack/services/lambda_/api_utils.py, localstack/services/lambda_/provider.py, tests/aws/services/lambda_/test_lambda_api.py, tests/aws/services/lambda_/test_lambda_api.snapshot.json, tests/aws/services/lambda_/test_lambda_api.validation.json
With #10323 we introduced a validation of lambda arns when invoking. However, the test hardcoded us-east-1 in the arn, which was by default replaced by the region snapshot transformer.
However, with different regions, it does not get replaced, making the test incompatible with multiple regions (the functionality itself was correct, though).
Also, there seems to have been a recent update to the error message and validation regex for iso regions, which I adapted in LocalStack as well.
* Use current region for invalid arn to allow region snapshot transformer to work properly @sannya-singal 
* Adjust regex and error message to recent AWS changes
=> Fix non-default-region compatibility for recent lambda invalid invoke test

scripts/tinybird/upload_raw_test_metrics_and_coverage.py
The helper script to upload tinybird coverage metrics was silently failing on ext, as we only had a return statement if any ENV was missing.
* raise Exception if required ENV is missing to fail the workflow
=> raise exception if required ENV is missing

tests/aws/services/cloudformation/resources/test_ec2.py, tests/aws/services/cloudformation/resources/test_ec2.snapshot.json, tests/aws/services/cloudformation/resources/test_ec2.validation.json, tests/aws/templates/ec2_vpc_default_sg.yaml, tests/aws/templates/transit_gateway_attachment.yml
Test `test_vpc_creates_default_sg` and `test_transit_gateway_attachment`fail when run in the [workflow](https://app.circleci.com/pipelines/github/localstack/localstack/23755/workflows/5d782a03-6bc1-4bd2-bcad-c6f1170e5381/jobs/194931/tests) for region: `ap-northeast-1` and throws a `StackDeployError`. 
This PR validates test: `test_vpc_creates_default_sg` against AWS and deploys both the tests specifically in `us-east-1`.
=> fix clouformation ec2 tests for `ap-northeast-1` and validate against AWS

README.md
Yesterday, we released [LocalStack 3.3.0](https://github.com/localstack/localstack/releases/tag/v3.3.0)!
This PR really just updates the README accordingly.
- Adjusts the release announcement on top of the README to the [latest release 3.3.0](https://github.com/localstack/localstack/releases/tag/v3.3.0). 🥳
=> update README after 3.3.0 release

localstack/services/moto.py, localstack/services/sns/provider.py, tests/aws/services/sns/test_sns.py, tests/aws/services/sns/test_sns.snapshot.json, tests/aws/services/sns/test_sns.validation.json
As shown in #10545, we had an issue with the SNS provider not lower casing incoming value, even though it works with AWS.
- fix the casing of `RawMessageDelivery` for `SetSubscriptionAttributes` and `Subscribe`
- add positive and negative tests for both `SetSubscriptionAttributes` and `Subscribe`
- remove a doc string for `call_moto_with_request` that I had added a while back and forgot to remove when the PR was updated
\cc @pinzon
=> fix SNS RawMessageDelivery casing

localstack/services/sns/resource_providers/aws_sns_subscription.py, localstack/services/sqs/resource_providers/aws_sqs_queuepolicy.py, tests/aws/services/cloudformation/resources/test_sns.py, tests/aws/services/cloudformation/resources/test_sns.snapshot.json, tests/aws/services/cloudformation/resources/test_sns.validation.json, tests/aws/services/cloudformation/resources/test_sqs.py, tests/aws/services/cloudformation/resources/test_sqs.snapshot.json, tests/aws/services/cloudformation/resources/test_sqs.validation.json, tests/aws/templates/sns_subscription.yml, tests/aws/templates/sns_subscription_update.yml, tests/aws/templates/sqs_with_queuepolicy_updated.yaml
This pull request (PR) addresses a feature request from a customer. It introduces the update operation functionality for two AWS resource types: AWS::SNS::Subscription and AWS::SQS::QueuePolicy. 
- update operation for AWS::SNS::Subscription
- update operation for AWS::SQS::QueuePolicy
- tests that create the resource in a CFn stack and update them.
=> add update operations for AWS::SNS::Subscription and AWS::SQS::QueuePolicy. 

tests/aws/services/cloudwatch/test_cloudwatch.py
As per previous discussion in #10550 PR [here](https://github.com/localstack/localstack/pull/10550#pullrequestreview-1963137286), we should remove the conditional provider in `test_dashboard_lifecycle`  to make the test more robust for old and `v2` both cloudwatch providers.  
This PR removes the conditional old provider in skip snapshot verifification. 
The following test has been verified against new(`PROVIDER_OVERRIDE_CLOUDWATCH=v2`) and old providers.
=> remove the conditional provider in `test_dashboard_lifecycle`

localstack/services/events/provider_v2.py, localstack/services/providers.py, tests/aws/services/events/helper_functions.py, tests/aws/services/events/scheduled_rules/test_events_scheduled_rules_logs.py, tests/aws/services/events/scheduled_rules/test_events_scheduled_rules_sqs.py, tests/aws/services/events/test_events.py, tests/aws/services/events/test_events.snapshot.json, tests/aws/services/events/test_events.validation.json, tests/aws/services/events/test_events_inputs.py, tests/aws/services/events/test_events_integrations.py, tests/aws/services/events/test_events_rules.py
This PR layers the groundwork for the implementation of the new EventBridge native provider. 
This PR implements the basic scaffold of the new native EventBridge provider. 
It also updates the API stubs to add missing docstrings.
Furthermore, a flag to select the new provider is introduced, with `PROVIDER_OVERRIDE_EVENTS=v2`.
Test selection is introduced for all eventbridge tests that are not yet supported by the new provider, as the implementation improves these skips tests will be continuously removed, to gain full test coverage also for the new provider.
To test the new provider manually, the env variable `PROVIDER_OVERRIDE_EVENTS=v2` needs to be set. 
All except the test `test_events.TestEventsEventBus.test_create_custom_event_bus` are marked as skipped, since the mocked new provider …
=> Feature: Eventbridge v2: Scaffold new provider

localstack/services/cloudformation/engine/template_deployer.py, tests/aws/services/cloudformation/resources/test_ec2.validation.json, tests/aws/templates/ec2_vpc_default_sg.yaml, tests/aws/templates/transit_gateway_attachment.yml
While working on greenifying cross accounts pipeline #10563, we discovered the issue with creating cfn templates in invalid availability zones.  
This PR: 
- updates the way we fetch the AZs: rather than traversing over `"a", "b", "c", "d", "e", "f"`, we call `connect_to().ec2.describe_availability_zones(...)`
- reverts the changes in #10563 for deploying the templates specifically in `us-east-1`.
=> fix cfn templates deployed in invalid AZs

localstack/services/secretsmanager/provider.py, tests/aws/services/secretsmanager/test_secretsmanager.py, tests/aws/services/secretsmanager/test_secretsmanager.snapshot.json, tests/aws/services/secretsmanager/test_secretsmanager.validation.json
This pull request addresses the issue highlighted in https://github.com/localstack/localstack/issues/8026, where `lastRotatedDate` was not being updated upon secret rotation. This fix ensures that `lastRotatedDate` is correctly updated when secrets are rotated.
- `lastRotatedDate` is updated during secret rotation.
- Added `Versions`, `VersionId` to snapshot matching: It was causing test flakiness.
- Added AWS validated test case.
=> fix lastRotatedDate updation on secret rotation

.pre-commit-config.yaml, Makefile
We now automatically update our pinned dependencies in the `requirements*.txt` files every week using a scheduled GitHub action. However, this currently does not update the - separately managed - `pre-commit` hook versions. This could lead to problems because we enforce the linting rules based on the latest `ruff` version, while the `pre-commit` hook is outdated.
This PR fixes this issue by updating the pre-commit hooks together with the pinned dependencies.
- Automatically executes `pre-commit autoupdate` when updating the dependencies such that they are updated together with the dev tools in the venv.
- Tested locally, the resulting update of `.pre-commit-config.yaml` is the result of `make upgrade-pinned-dependencies`
=> update pre-commit hook versions on dep updates

.circleci/config.yml
https://github.com/localstack/localstack/pull/10552 introduces a new v2 provider for EventBridge, that can be selected via the env variable `PROVIDER_OVERRIDE_EVENTS=v2`. We need a new step in the CI run, that sets this env variable and runs tests against the new provider.
Adds new step for CircleCi to test new EventBridge provider
=> Feat: Events v2: add ci step for eventbridge v2 provider

localstack/services/apigateway/integration.py, tests/aws/services/apigateway/conftest.py, tests/aws/services/apigateway/test_apigateway_http.py, tests/aws/services/apigateway/test_apigateway_http.snapshot.json, tests/aws/services/apigateway/test_apigateway_http.validation.json, tests/aws/services/lambda_/functions/lambda_echo_status_code.py, tests/aws/services/lambda_/test_lambda.py
As mentioned in issue #10461, we were matching the response status code to the integration method for `HTTP_PROXY` integrations. As documented [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-method-settings-method-response.html), `With a proxy integration, API Gateway passes the backend response through to the method response automatically.`
Skipping entirely the response response template rendering for `HTTP_PROXY` integrations. As neither status code nor body transformation should be processed for this type of integration.
=> Fix apigw http proxy response passthrough

localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/distributed_iteration_component.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/inline_iteration_component.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/job.py, tests/aws/services/stepfunctions/templates/scenarios/scenarios_templates.py, tests/aws/services/stepfunctions/templates/scenarios/statemachines/map_state_nested.json5, tests/aws/services/stepfunctions/templates/scenarios/statemachines/parallel_state_nested.json5, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.py, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.snapshot.json, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.validation.json
Currently the SFN interpreter is unable to evaluate nested Map states as the deep copying of executed programs during the closing of Map jobs fails to serialise lock objects within the program. As the evaluated program is not useful when propagated after job closure, this PR resolved this issue by propagate JobClosed objects past closure which only consist of the index (useful for output ordering) and output value.
Addresses #10467
- Adds JobClosed objects as output of closed objects in Job Pools
- nested Map and Parallel state
=> [SFN] Fix Evaluation of Nested Map States

bin/release-helper.sh
Switching the release helper to work with `pyproject.toml` broke the CLI release since it did not work with `requirements.txt` files anymore. Also, changing the version single sourcing broke the release commit function, since it does not have a version.py file.
1. The regular expressions in `grep` and `sed` were changed, so that they can capture both `requirements.txt` as well as `pyproject.toml` files.
2. The `git add` for the release and increment commits was changed, so that only files are added that truly exist. 
3. Reintroduce the usage of `egrep` which was previously removed because it is deprecated in modern versions of `grep`. However, on macOS, `egrep` is still the way to go.
In `localstack/localstack-cli` you can execute the following:
```
DEPENDENCY_FILE="requirements.txt" …
```
=> Fix release helper for cli release

pyproject.toml, requirements-dev.txt, requirements-runtime.txt, requirements-test.txt, requirements-typehint.txt
Bumps Moto to latest upstream release and brings in:
- https://github.com/getmoto/moto/pull/7496
- https://github.com/getmoto/moto/pull/7511
- https://github.com/getmoto/moto/pull/7547
Ext Integration Tests # 5639 :green_circle: Passing
cc: @macnev2013
=> Bump moto-ext to 5.0.4.post1

tests/aws/services/cloudformation/test_template_engine.py, tests/aws/services/cloudformation/test_template_engine.snapshot.json, tests/aws/services/cloudformation/test_template_engine.validation.json, tests/aws/templates/functions_get_azs.yml
The cfn test to check the template engine `test_get_azs_function` generates a snapshot against `us-east-1` AWS region. But when it is run against localstack for different AZs of non-default region values it results in error after the merge of #10586 which instead of just expanding values from a to f, now uses `connect_to().ec2.describe_availability_zones(...)` to get AZs of a specified region. 
According to previous commits in this file, we can see that this is a known gap and there is already a TODO added: 
```
TODO parametrize this test.
For that we need to be able to parametrize the client region. The docs show the we should be
able to put any region in the parameters but it doesn't work. It only accepts the same region from the client config
if you put anything else it just returns an …
```
=> fix function get azs cloudformation template 

localstack/services/dynamodb/provider.py, tests/aws/services/dynamodb/test_dynamodb.py, tests/aws/services/dynamodb/test_dynamodb.snapshot.json, tests/aws/services/dynamodb/test_dynamodb.validation.json
As reported by #10588, we had an issue when calling `TransactWriteItems` with requests targeting different tables, when some of them had stream enabled and some didn't. 
- add a test checking the scenario
- add a check to skip the requests where the table has no stream enabled when iterating over the transact items
_fixes #10588_
=> fix DDB issue when TransactWriteItems targets tables with and without streams

localstack/services/sns/publisher.py, tests/aws/services/sns/test_sns.py, tests/aws/services/sns/test_sns.snapshot.json, tests/aws/services/sns/test_sns.validation.json, tests/unit/test_sns.py
As reported by #10567, JSON array properties were not handled well when the scope of the filter was `MessageBody`. We would handle it correctly for `MessagesAttributes` but it was only tested in unit tests. 
- add 2 AWS validated tests: one for `MessageAttributes` scope with `String.Array` filter and one for array property in a JSON message body
- add the fix to recursively match the values of an array if the value is an array in an `OR` fashion (at least one value must match)
_fixes #10567_
=> fix SNS MessageBody filtering when value is a list

tests/aws/services/secretsmanager/test_secretsmanager.py, tests/aws/services/secretsmanager/test_secretsmanager.validation.json
This PR introduces AWS-validated test cases to verify the filtering functionality of the `secretsmanager` list API.
The issue was originally reported [here](https://github.com/localstack/localstack/issues/4820). The fix has been implemented in [Moto](https://github.com/getmoto/moto/pull/7511).
⚠️ NOTE: This PR should only be merged after the dependent PR in [Moto](https://github.com/getmoto/moto/pull/7511) has been merged and moto version in LocalStack is bumped to support this fix.
- Implemented an AWS-validated test case.
cc. @viren-nadkarni
=> added aws validate test case for ListSecrets filtering

localstack/aws/api/s3/__init__.py, localstack/aws/spec-patches.json, localstack/services/s3/exceptions.py, localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
We had some issues with our WebApp regarding Bucket Location Constraint, and one proposed fixed was to pass a `undefined` location constraint when the bucket region was `us-east-1`. This fix worked with LocalStack, but this was missing parity. AWS will not accepted an empty constraint either for `us-east-1`. 
- add a check if the constraint is actually set or not. Some quirks of XML parsing makes it that a full empty body and the location constraint set to `None` will end up as an empty dict for both. We have to check if the body is really empty, in that case no constraint are set. 
- extend the test to validate a constraint for `us-east-1` and validate a `None` constraint
\cc @webdev51 @lukqw
=> fix s3 create bucket constraint

localstack/dev/kubernetes/__main__.py
This pull request introduces a new script that simplifies the development workflow for LocalStack contributors and developers working with Kubernetes.
The script generates two essential files:
1. **Configuration File**: This file contains the necessary configurations to mount the LocalStack code into the k3d container when creating a Kubernetes cluster. This allows developers to make changes to the LocalStack codebase and have them immediately reflected in the running cluster, facilitating a streamlined development and testing experience.
2. **Overrides File**: This file provides overrides for the LocalStack Helm charts, enabling the mounting of the LocalStack code into the LocalStack container itself. By mounting the code directly into the container, developers can seamlessly debug and …
=> add script for generating Kubernetes dev files

localstack/services/events/utils.py, localstack/utils/testutil.py, tests/aws/services/events/event_pattern_templates/list_within_dict.json5, tests/aws/services/events/test_event_patterns.snapshot.json, tests/aws/services/events/test_event_patterns.validation.json, tests/aws/services/events/test_events_integrations.py, tests/aws/services/events/test_events_integrations.snapshot.json, tests/aws/services/events/test_events_integrations.validation.json
A customer reported internal errors when submitting events that contained a list within a dict. This PR adds the presumably correct behavior as AWS does it (checked with 2 validated tests). During the replication, another issue surfaced in our own testing code: The function that collects the event logs will also discard actual messages if the message happens to contain certain key words, while we should only discard messages that *start* with said keywords.
/cc @maxhoheiser 
- Fixes handling of list entries in dicts in eventbridge
- Fixes the discarding of status event logs
=> eventbridge: fix handling of list elements

localstack/services/secretsmanager/provider.py, tests/aws/services/secretsmanager/test_secretsmanager.py, tests/aws/services/secretsmanager/test_secretsmanager.snapshot.json, tests/aws/services/secretsmanager/test_secretsmanager.validation.json
This PR is raised to address the issue highlighted in [Issue #10086](https://github.com/localstack/localstack/issues/10086). The issue concerns the handling of deprecated secrets within LocalStack. 
Previously, LocalStack removed deprecated secrets, deviating from AWS of retaining up to 100 deprecated secrets. This set of changes aligns LocalStack with AWS by implementing a limit on the number of stored deprecated secrets.
Note: AWS does not remove versions created less than 24 hours ago. Whereas we do not check time difference before deleting the secret as of now.
- **`ListSecretVersionIds`:** Enhanced the `ListSecretVersionIds` API to support the `IncludeDeprecated` argument, allowing for the inclusion of deprecated secrets in the response.
- **Deprecated Secrets Management:** …
=> fix deprecated secret versions preservation in secretsmanager

localstack/services/lambda_/invocation/docker_runtime_executor.py, localstack/services/lambda_/invocation/lambda_service.py, localstack/services/lambda_/invocation/version_manager.py, localstack/testing/aws/lambda_utils.py, tests/aws/services/lambda_/test_lambda_api.py, tests/aws/services/lambda_/test_lambda_api.snapshot.json, tests/aws/services/lambda_/test_lambda_api.validation.json
We are currently raising a custom exception if an update cannot be performed yet, as another update is currently in progress. Instead, we should raise the correct exception AWS also raises.
This was planned as an investigation how to make updates concurrent, with the realization that this is currently not possible in AWS.
* Remove callback after start, but add complete logic into the lambda service
* Adapt exception
* Add two test, one for config, one for code, to test the changes. They use a threading event to block the update if run against LocalStack, to avoid test flakyness when the updates are too fast.
=> Raise correct exceptions for simultaneous lambda function updates

localstack/utils/container_utils/container_client.py, localstack/utils/container_utils/docker_sdk_client.py, tests/integration/docker_utils/test_docker.py
We are currently not supporting container labels the `run_container` method and the `ContainerConfiguration` class.
Since we want to make use of labels more often, to allow grouping containers and adding additional information, we should allow setting labels for these options to create containers.
* Add `labels` parameter to `run_container` methods
* Add `labels` as a new field in the `ContainerConfiguration` class
* Add small test assuring `labels` to be correctly set during the `run_container` call
We currently have no explicit tests for the `ContainerConfiguration` class, but test it rather implicitly. The `labels` field of it will be tested while testing new `ecs` changes.
=> Add container labels to container configuration and container run methods

Dockerfile, tests/aws/services/transcribe/test_transcribe.py
In Transcribe, when executing on ARM, we receive errors of a missing shared object (#10522). This is because the `libvosk.so` depends on `libatomic1.so`, which is not present in the ARM image. Installing `libatomic1` via `apt` in the running container fixes this issue.
This PR adds `libatomic1` as a dependency in the apt installation step of the `Dockerfile`. 
Removed the skip marker for ARM on the Transcribe tests. If they're green on this build, the issue should be resolved
=> Add missing library for transcribe on ARM

localstack/utils/container_utils/docker_cmd_client.py, tests/integration/docker_utils/test_docker.py, tests/unit/test_dockerclient.py
Currently, the `docker_cmd_client` returns labels on the `list_container` operations in this format: `key1=value1,key2=value2`
The SDK based client however returns a dict: `{"key1": "label1", "key2": "label2"}`
As they should behave identical, we need to change the CMD client to use the same dict format (as it is easier to use).
* Change the CMD docker client to return a dict of labels, instead of a comma separated list of key-value pairs
* Add a test asserting that format
=> Ensure container clients return the same format for container labels on list call

localstack/aws/api/s3/__init__.py, localstack/aws/spec-patches.json, localstack/services/s3/presigned_url.py, localstack/services/s3/provider.py, localstack/services/s3/v3/provider.py, localstack/services/s3/v3/storage/core.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
As requested with #10351, we did not implement specific policy validation for pre-signed POST. 
We were lacking validating the conditions specified in the policy. This PR will take a stab at implementing the requested ones with a general implementation. 
See: https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html
Some are still left to do: 
- AWS will reject a policy that has extra fields passed to it that are not defined in the `Conditions` field (for ex. if you set `success_action_redirect` without defining it as a condition, the request should fail). This is not implemented yet as we need to know and test exactly which fields are considered "extra", with help from the documentation but will need quite some tests
- some fields only support one kind of …
=> add s3 POST policy validation

localstack/utils/container_utils/docker_cmd_client.py, localstack/utils/container_utils/docker_sdk_client.py, tests/integration/docker_utils/test_docker.py
Trying to setup ulimits for a container using the `ContainerClient.run_container()` method leads to invalid configuration. 
The sdk client tried to transform the Ulimit object twice. Once in `run_container` and then again in `start_container`. Removed it from `run_container` as it calls the `start_container`, which should keep it's interface.
The cmd client had a typo in ulimit.
=> fix docker client ulimits

localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_aws_sdk.py, localstack/services/stepfunctions/provider.py, tests/aws/services/stepfunctions/templates/services/services_templates.py, tests/aws/services/stepfunctions/templates/services/statemachines/aws_sdk_sfn_send_task_failure.json5, tests/aws/services/stepfunctions/templates/services/statemachines/aws_sdk_sfn_send_task_success.json5, tests/aws/services/stepfunctions/v2/services/test_aws_sdk_task_service.py, tests/aws/services/stepfunctions/v2/services/test_aws_sdk_task_service.snapshot.json, tests/aws/services/stepfunctions/v2/services/test_aws_sdk_task_service.validation.json
The current version of the SFN v2 interpreter lacks the capability to enhance aws-sdk failures if the service name of the resource isn't associated with any explicit bindings or isn't available in boto's service catalog. As a result, it generates unknown service error messages, causing the interpreter to fail without reporting the decorated aws-sdk source error.
This pull request aims to resolve this issue by refining the logic for decorating service error names to accurately search for a normalised error name. In cases where none is found, it logs such incidents and returns the original service name as an error. This adjustment is intended to enable the computation to continue, albeit with slightly different cause and error string formatting, while also emphasising the necessity for more …
=> [SFN] Fix Unknown Service sfn errors

tests/unit/aws/test_connect.py
After the merge of #10253 the scheduled workflow for randomised AWS credentials started to fail [here](https://app.circleci.com/pipelines/github/localstack/localstack/24025/workflows/acdd44d3-7f7e-40f2-8c85-759ce17b1980/jobs/197842/tests). 
This PR removes the hardcoded `us-east-1` region from `test_external_client_credentials_origin` and `test_external_aws_client_credentials_loaded_from_env_if_set_to_none` unit test cases and uses the `region_name` fixture instead.
=> fix `connect` unit tests for cross-accounts 

.circleci/config.yml
#10568 hardened the Tinybird Metrics Upload script such that it strictly fail in case the needed secret is not set (because we realized it silently broke before).
In a recent community contribution (https://github.com/localstack/localstack/pull/10625 🥳), we have seen the [`report` job in CircleCI fail](https://app.circleci.com/pipelines/github/localstack/localstack/24104/workflows/b6f652c4-42c7-4060-9bde-4bb21e6506ae/jobs/198814/parallel-runs/0/steps/0-107) because the secret is (due to security reasons) not set for workflow executions triggered on forks (untrusted code):
```
METRIC_REPORT_DIR_PATH=parity_metrics, IMPLEMENTATION_COVERAGE_FILE=scripts/implementation_coverage_full.csv, SOURCE_TYPE=community
missing data, please check the available ENVs that are required to run the script …
```
=> fix metrics upload failure on community PRs

localstack/services/route53/provider.py, tests/aws/services/route53/test_route53.py, tests/aws/services/route53/test_route53.snapshot.json, tests/aws/services/route53/test_route53.validation.json
If a hosted zone is to be created in a VPC, `moto` does not check for existence for that VPC whereas AWS does.
* If the VPC details are specified by the caller of `create_hosted_zone`, look up the VPC and raise an error if it does not exist.
* Update `test_create_private_hosted_zone` to call `list_hosted_zones_by_vpc` and snapshot the result
=> Check for VPC existence for hostedzone

localstack/services/cloudformation/engine/template_deployer.py
When adding new resources, CFn logs a message like:
```
Handling "Add" for resource "V1MysqlClusterSecretAttachment649A3B90" (1/1) type "AWS::SecretsManager::SecretTargetAttachment" in loop iteration 2
```
Which is useful context.
When deleting resources, CFn does not print anything 😥
- Add log message for handling removes during stack deletes
- Add logging for _resource_ removal
=> More consistent CFn logging for individual resources

.github/workflows/tests-pro-integration.yml
This PR prepares the community CI for the upcoming Libvirt virtualisation for EC2.
The `libvirt-dev` Debian package is required by `libvirt-python` Python package during the build time of Docker image.
Adds `libvirt-dev` as a build-time dependency.
=> Add libvirt as a build dependency

localstack/utils/run.py
Running a dev container with `python -m localstack.dev.run` does not return the terminal to "cooked" mode correctly. This means the user has to press Enter multiple times to get their prompt back.
Swap out `run_interactive` for `subprocess.check_call` since I think all functionality implemented in `run_interactive` is performed by `check_call`. TBC
=> Fix dev run container exiting from raw mode

Makefile
With the recently released setuptools version `69.3.0` (https://setuptools.pypa.io/en/latest/history.html#v69-3-0), setuptools normalizes the source distribution name to conform with [PEP 625](https://peps.python.org/pep-0625/).
In summary, source distribution names should be named as followed: `{distribution}-{version}.tar.gz`.
Only a single hypen is now allowed:
> Conforming sdist files can be recognised by the presence of the .tar.gz suffix and a single hyphen in the filename.
Since our package was named `localstack-core-{version}.tar.gz`, it is now normalized to the above format with `localstack_core-{version}.tar.gz`.
In our Makefile we look for the source distribution when checking the source distribution for valid entrypoints using a glob, which has to be adapted.
* Adapt glob for …
=> Adapt source distribution glob to new PEP 625 canonicalized name

Makefile
The setuptools upgrade which necessitated #10652 was yanked due to issues with the name normalization, but it is expected that the change will be re-released soon.
To avoid waiting for that release, and to avoid reverting now and reintroducing the changes when it happens, we should make the pattern more resilient.
* Use a `?` (single character wildcard) instead of `-` or `_` in the publish operation, to always match the name, no matter the setuptools version.
=> Use single character wildcard when matching the source distribution to avoid breaking with yanked setuptools

localstack/services/secretsmanager/provider.py, tests/aws/services/secretsmanager/test_secretsmanager.py, tests/aws/services/secretsmanager/test_secretsmanager.snapshot.json, tests/aws/services/secretsmanager/test_secretsmanager.validation.json
This PR addresses the issue described in https://github.com/localstack/localstack/issues/10621.
Updated moto exception handling in LocalStack.
- Added aws validated test cases.
=> fixed exception handling in secretsmanager

tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
Just adding a sanity check that AWS properly validate all fields when using a fully created client with access key / secret key / session token, linked to the raised issue here: https://github.com/localstack-samples/sample-serverless-image-resizer-s3-lambda/pull/24
- add an AWS test with full credentials for a S3 pre-signed POST, validating the boto SDK automatically sets all the authorization fields as conditions
=> add S3 pre-signed POST test with credentials

localstack/testing/pytest/fixtures.py, tests/aws/services/acm/test_acm.py, tests/aws/services/acm/test_acm.snapshot.json, tests/aws/services/acm/test_acm.validation.json, tests/aws/services/apigateway/test_apigateway_basic.py, tests/aws/services/apigateway/test_apigateway_basic.snapshot.json, tests/aws/services/apigateway/test_apigateway_basic.validation.json
Part of the effort to improve parity with aws. This first step sorts all `aws.unknown` tags and replaces them with `aws.validated` or `aws.needs_fixing`.
Started to go through apigw
=> Validate existing test apigw

localstack/services/cloudformation/engine/template_deployer.py, localstack/services/cloudformation/resource_provider.py
CloudFormation resource providers are able to return the `PENDING` status from operations such as `create` or `delete`, indicating that the operation is in progress. We can use this status in our CloudFormation engine to signal to the `do_apply_changes_in_loop` loop (and equivalent in `delete_stack`) that the operation is _knowingly_ not going to work at the moment, and we should come back to the operation and try again after continuing to attempt to operate on the other resources in the stack.
Specific example:
* Resource `A` depends on resources `B` and `C` (e.g. `A` = `AWS::RDS::DBCluster` and `B` and `C` are `AWS::RDS::DBInstance`s)
* CFn tries to delete `A` before deleting `B` and `C`, which raises an exception from the service
We can use the `PENDING` status to tell CloudFormation …
=> CFn: handle `OperationStatus.PENDING` events from resource providers

localstack/aws/app.py, localstack/aws/handlers/service_plugin.py, localstack/aws/protocol/service_router.py, localstack/services/lambda_/urlrouter.py, tests/aws/services/lambda_/test_lambda.py, tests/aws/services/lambda_/test_lambda.validation.json
I noticed an error when calling non-existing lambda function URLs. The code we had was apparently faulty, and I got this error:
```
2024-04-11T17:20:40.966 ERROR --- [et.reactor-0] l.aws.handlers.logging     : exception during call chain
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/handlers.py", line 27, in __call__
router_response = self.router.dispatch(context.request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/router.py", line 378, in dispatch
return self.dispatcher(request, handler, args) …
```
=> fix lambda function URLs when they don't exist or the service is not loaded

localstack/aws/handlers/cors.py, localstack/aws/protocol/service_router.py
After merging https://github.com/localstack/localstack/pull/10640, we noticed an issue in ext that a request to apigwv2 websockets would mistakenly go into the service parser, which would fail because the request was detected as "apigateway" when it really should have been "apigatewaymanagementapi". It turns out setting `apigateway` as a service simply based on the condition `if `.execute-api. in request.host` is much too strong, because it's ambiguous.
however, we were relying on this (wrong) behavior in the CORS handler, to trigger the custom apigw cors check, so we had to weaken the condition for that control path as well, now that we're no longer setting the service name in the request to `apigateway`.
Moving forward, we have the option to handle data plane service loading without …
=> fix apigw data plane service matching

localstack/services/apigateway/helpers.py, localstack/services/apigateway/provider.py, localstack/testing/pytest/fixtures.py, localstack/testing/snapshots/transformer_utility.py, tests/aws/services/apigateway/conftest.py, tests/aws/services/apigateway/test_apigateway_api.py, tests/aws/services/apigateway/test_apigateway_api.snapshot.json, tests/aws/services/apigateway/test_apigateway_api.validation.json, tests/aws/services/apigateway/test_apigateway_extended.py, tests/aws/services/apigateway/test_apigateway_extended.snapshot.json, tests/aws/services/apigateway/test_apigateway_extended.validation.json, tests/aws/services/apigateway/test_apigateway_import.py, tests/aws/services/apigateway/test_apigateway_import.snapshot.json, tests/aws/services/apigateway/test_apigateway_import.validation.json, tests/aws/services/apigateway/test_apigateway_integrations.py, tests/aws/services/apigateway/test_apigateway_integrations.snapshot.json, tests/aws/services/apigateway/test_apigateway_integrations.validation.json, tests/aws/services/cloudformation/api/test_transformers.py, tests/aws/services/cloudformation/api/test_transformers.snapshot.json, tests/aws/services/cloudformation/api/test_transformers.validation.json, tests/aws/services/cloudformation/resources/test_apigateway.snapshot.json, tests/aws/services/cloudformation/resources/test_apigateway.validation.json
We've had a report with #10657 that the latest Terraform AWS provider would fail with LocalStack because APIGW is not returning the `rootResourceId` field from APIGW REST API creation. 
A lot of our tests will snapshot the rest API creation, so we need to regenerate a lot of snapshots to avoid this fix breaking the test suite.
- add the `rootResourceId` field to `CreateRestApi`, `PutRestApi`, `GetRestApi`, `GetRestApis` and `ImportRestApi`
- update some of the tests to try to make use of this new field
- update all the snapshots that might fail (regenerated all `test_apigateway_api.py` file
- above uncovered a new validation, last snapshot validation was from March 2023, so added a quick fix
- refactored `test_apigateway_api.py` file to be more contained in class, because regenerating …
=> fix APIGW: add rootResourceId to REST API creation

localstack/services/dynamodb/provider.py, tests/aws/services/dynamodb/test_dynamodb.py, tests/aws/services/dynamodb/test_dynamodb.snapshot.json, tests/aws/services/dynamodb/test_dynamodb.validation.json
As reported with #10679, we would return `MODIFY` when the call to `Update` would insert data that didn't exist.
A condition was wrong and was checking for the wrong value (`updated_item` instead of `existing_item`). 
- added a new call in the `test_transact_write_items_streaming` test to test for an `Update` call which inserts data
- fix the condition check 
_fixes #10679_
=> fix DDB eventName for TransactWriteItems Update inserting data

localstack/aws/handlers/cors.py, tests/integration/test_security.py
Follow up from #10682, Alex has raised valid concerns that we were weakening the CORS/CRSF checks for APIGW by removing the service check.
- I've added a bit stricter check than before, and added tests for APIGW CORS handling.
=> improve user request route detection for APIGW in CORS

tests/unit/test_common.py
According to our CI analytics, the `tests/unit/test_common.py::TestExternalServicePortsManager::test_reserve_port_all_reserved` failed with a flake in ~6.25% of the runs of the last week.
Here are some example runs with this test failing:
- https://app.circleci.com/pipelines/github/localstack/localstack/24295/workflows/5b1fe023-a6b9-4dc0-8172-5b76cf17e9cb/jobs/200959
- https://app.circleci.com/pipelines/github/localstack/localstack/24237/workflows/3f7cb5a1-416b-4cdb-8d5c-16301dc77346/jobs/200239
- https://app.circleci.com/pipelines/github/localstack/localstack/23899/workflows/4fb96fb0-be61-4a20-a719-1438685cd55b/jobs/196354
- https://app.circleci.com/pipelines/github/localstack/localstack/23884/workflows/8d5757b5-f794-4208-a605-579bc0219a61/jobs/196268
- …
=> fix external service ports manager unit test flakiness

localstack/services/lambda_/runtimes.py, tests/aws/services/lambda_/test_lambda_api.snapshot.json, tests/aws/services/lambda_/test_lambda_api.validation.json, tests/aws/services/lambda_/test_lambda_common.py, tests/aws/services/lambda_/test_lambda_common.snapshot.json, tests/aws/services/lambda_/test_lambda_common.validation.json
AWS recently (Apr 4, 2024) announced support for the new Lambda Ruby 3.3 runtime and we should support it in LocalStack.
- https://aws.amazon.com/about-aws/whats-new/2024/04/aws-lambda-ruby-3-3/
- https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
Add support and tests for the new Ruby 3.3 Lambda runtime
The other snapshots were already updated in https://github.com/localstack/localstack/pull/10591
* Updated multiruntime snapshots
* localstack-ext should be safe to update because Ruby 3.* does not support transparent endpoint injection, so there are no tests to update there. localstack-ext tests (including ARM) run for sanity check:
* Attempt#1+2 (ARM64 🟢, AMD64 🔴, ECS 🔴): https://github.com/localstack/localstack-ext/actions/runs/8782702295
* Attempt#3 🟢 (except for ECS on …
=> Add Ruby 3.3 Lambda runtime

tests/aws/services/lambda_/test_lambda_developer_tools.py
The hotreloading test failed in CI, this PR makes it more reliable.
After merging https://github.com/localstack/localstack/pull/10591
We got this test failure: https://app.circleci.com/pipelines/github/localstack/localstack/24343/workflows/37c4c31a-3a5c-40d1-8f05-ee83f59d9209/jobs/201483/tests
* Increase sleep time slightly
* Bump Lambda runtimes (using the same as many other tests reduces the likelihood of an extra pull)
=> Bump Lambda runtime versions and increase sleep time

localstack/services/events/event_bus.py, localstack/services/events/models_v2.py, localstack/services/events/provider_v2.py, localstack/services/events/rule.py, localstack/services/events/target.py, localstack/testing/aws/asf_utils.py, tests/aws/services/events/conftest.py, tests/aws/services/events/test_events.py, tests/aws/services/events/test_events.snapshot.json, tests/aws/services/events/test_events.validation.json, tests/aws/services/events/test_events_integrations.py
This PR introduces the core structure of the new localstack native implementation of event bridge. 
Furthermore, it implements the CRUD functionality based on snapshots of verified AWS tests. A clean pattern for keeping data stored in the AccountRegionBundle store separate from related functionality is required. Separation of different sender functionality based on the target should be handled more efficiently than in a if else chain.
These API operations are implemented:
- create_event_bus
- delete_event_bus
- describe_event_bus
- list_event_buses
- enable_rule
- delete_rule
- describe_rule
- disable_rule
- list_rules
- list_rule_names_by_target
- put_rule
- list_targets_by_rule
- put_targets
- remove_targets
- put_events
- put_partner_events
- Implement new provider, and crud API …
=> Feature: Eventbridge v2: CRUD

localstack/utils/container_utils/container_client.py, localstack/utils/container_utils/docker_sdk_client.py, localstack/utils/docker_utils.py
The `get_host_path_for_path_in_docker` function should not fail if we have no docker daemon available.
If docker is required later, we can still fail there. If not, because there are other options available, we should not fail.
This is a bandaid fix, we need to have a bigger refactoring for this method in the future.
* Check if we have access to the docker socket before executing operations for it
* Check `has_docker` call for the sdk client as well, similar to the cmd client.
* Properly pass ulimit configuration from `ContainerConfiguration` to `create_container`.
=> Avoid failing host_path_for_path_in_docker if no docker daemon is available

localstack/extensions/patterns/webapp.py
Webapp extensions such as:
* https://github.com/localstack/localstack-ngrok-tunnels
* https://github.com/thrau/localstack-aws-log-viewer
* https://github.com/localstack/localstack-extension-event-studio
Follow a common pattern. They
* expose routes through subdomains and submounts (`http://my-extension.localhost.localstack.cloud:4566`, and `http://localhost.localstack.cloud:4566/_extension/my-extension`)
* Enable logging for their root module `my_extension`
* Serve jinja2 templates
* Serve static files
Their file layout will typically look like this:
```
my_extension
├── extension.py
├── __init__.py
├── static              <-- make sure static resources get packaged!
│   ├── __init__.py
│   ├── favicon.ico
│   └── style.css
└── templates            <-- jinja2 templates
└── index.html
``` …
=> create pattern construct for a webapp extension

localstack/aws/protocol/serializer.py, localstack/services/s3/provider.py, localstack/services/s3/utils.py, localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
As reported by #10712, LocalStack would return some `Content-Type` headers when AWS would not. Even though this was still in line with HTTP specs, some client were relying on this behavior.
We could not put this in the serializer, as the serializer handler calls `Response.update_from`, which is only additive. We cannot remove headers from this, and a default `Content-Type` is set at the beginning of the handler chain. 
- create a new simple handler for S3 responses, which will remove some headers to be in line with AWS
- modify some tests to validate the new changes
_fixes #10712_
=> fix headers for empty S3 responses

localstack/services/lambda_/invocation/docker_runtime_executor.py
Currently, if multiple lambda functions are created at the same time, with the same runtime, the image is pulled multiple times, concurrently.
Only after the images has been successfully pulled once, the image will not be pulled anymore.
In an extreme case, this could lead to a lot of lambdas pulling images concurrently, with the operation being slowed down for all of them (due to parallel downloads).
We need a solution where all the lambdas wait for the image, but it is only pulled once.
* Add method to pull images with lock to avoid concurrent pulls of the same image (different images can still be pulled concurrently)
Old behavior:
```
2024-04-25T11:16:08.109  INFO --- [   asgi_gw_0] l.request.internal.aws     : AWS s3.GetObject => 200
2024-04-25T11:16:08.119 DEBUG --- [rvice-task_0] …
```
=> Avoid concurrent pulling of identical images in lambda

localstack/config.py, localstack/services/cloudformation/resource_provider.py
LocalStack's CloudFormation implementation has a hard limit of 2.5 mins to deploy a single resource which is not always enough for bigger resource deployments like nested stacks.
- Add CFN_PER_RESOURCE_TIMEOUT env variable
- Increase default value to 300s
=> CFN_PER_RESOURCE_TIMEOUT env variable

localstack/services/cloudformation/provider_utils.py, tests/unit/services/cloudformation/test_provider_utils.py
The CloudFormation template engine passes values from attributes that are expected to be numbers as strings, resulting in potential parameter rejection by boto3 when numeric values are required.
New utility to easily convert the values that are digits into numbers.
New unit test for the function.
Notes: In the future all the resource provider utilities should have a test.
=> add utility for resource providers

localstack/utils/container_utils/docker_sdk_client.py
While using LocalStack without mounting the docker socket, an annoying traceback is shown in the terminal, but the error does not help. It adds noise and does not explain what is going on.
This is especially true on Kubernetes, where there is no docker socket available by default.
<details>
<summary>Traceback example</summary>
```
2024-04-23T15:35:49.577 DEBUG --- [-functhread1] l.u.c.docker_sdk_client    : Creating Docker SDK client failed: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
response = self._make_request(
^^^^^^^^^^^^^^^^^^^
File …
```
=> Hide docker sdk error unless trace logging

localstack/utils/objects.py
`SubtypesInstanceManager` is supposed to lazily create a singleton instance of subtypes and return it. However a bug caused all subtypes to be instantiated eagerly if any subtype was requested.
This was identified when the Libvirt EC2 VM manager was being instantiated in the CI (which would fail since CI runners do not have a Libvirt socket) despite not being enabled explicitly in code or configuration.
Fix `SubtypesInstanceManager` so that only the requested subtype is instantiated.
=> Fix SubtypesInstanceManager not loading subtypes lazily

.github/ISSUE_TEMPLATE/feature-request.yml
We have seen lots of confusion about the difference between "enhancements" and "features" in the past.
While it might make sense in a few cases to differentiate between smaller improvements to existing emulators or the base emulation layer, we discussed recently that we want to make this easier by removing the "enhancement" categorization altogether.
After migrating the labels on the issues, this PR changes the issue template to the new phrasing.
- Changes the "Enhancement request" issue template to the "Feature request" template.
=> migrate from enhancement request to feature request

localstack/services/stepfunctions/asl/component/common/catch/catcher_decl.py, localstack/services/stepfunctions/asl/component/common/error_name/custom_error_name.py, localstack/services/stepfunctions/asl/component/common/error_name/error_name.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_callback.py, localstack/services/stepfunctions/asl/eval/callback/callback.py, tests/aws/services/stepfunctions/templates/callbacks/callback_templates.py, tests/aws/services/stepfunctions/templates/callbacks/statemachines/sqs_parallel_wait_for_task_token.json5, tests/aws/services/stepfunctions/templates/callbacks/statemachines/sqs_wait_for_task_token_catch.json5, tests/aws/services/stepfunctions/v2/callback/test_callback.py, tests/aws/services/stepfunctions/v2/callback/test_callback.snapshot.json, tests/aws/services/stepfunctions/v2/callback/test_callback.validation.json
Currently the StepFunctions v2 interpreter is unable of handling empty SentTaskFailure api calls. These are SendTaskFailure messages for waitForTaskToken tasks which do not provide an error string. Such calls would result in internal States.Runtime errors, and misleading error messages such as `Custom Error Names MUST NOT begin with the prefix 'States.', got 'State.Runtime'`.  This PR adds snapshot tests replicating this occurrence and add support for CustomErrorNames to have nullable error strings. It also identifies need for future work on StateTaskAbort events logging.
- Nullable error strings in CustomErrorName objects
- Related handling of null error strings
- Snapshot tests
=> [SFN] Improve Handling of Empty SendTaskFailure Calls

localstack/config.py
@thrau added twisted as supported gateway server with #9834. Since then this was tested by selected users, and it turned out to be a great server. In reduced complexity and improved performance.
- Switches the default for `GATEWAY_SERVER` from `hypercorn` to `twisted`.
- Since the gateway is the foundation for every single request served in LocalStack, this change has an insane coverage. If all our tests are 💚, we should be good to go!
- We also need to execute tests for our downstream projects, to make sure other projects don't break.
=> switch default gateway server from hypercorn to twisted

.github/workflows/tests-pro-integration.yml, CODEOWNERS, localstack/testing/testselection/matching.py, localstack/testing/testselection/scripts/generate_test_selection_from_commits.py, localstack/testing/testselection/scripts/generate_test_selection_from_pr.py
Using the test selection scripts in repositories with slightly different requirements is difficult because of a lack of parametrization.
This PR adds parametrization in regards to repository name, opt_in dictionary and matching rules for test selection.
/cc @alexrashed 
The test selection should still work as before:
1. Create a dummy change commit where you only change a simple thing in one service
2. Run
`python -m localstack/testing/testselection/scripts/generate_test_selection_from_commits.py . <HEAD~> <HEAD> test-selection`
Output should be only the service tests (if it's opted in)
=> Parametrize test selection scripts for usage in dependent repositories

localstack/services/cloudformation/engine/quirks.py
This PR addresses the issue with the `PhysicalResourceId` format for `AWS::Glue::SchemaVersionMetadata`. Previously, it was generated as `<uuid>-<key>-<value>`, whereas in AWS it should be `<uuid>|<key>|<value>`.
Modified `PhysicalResourceId` to align with AWS.
- This changes are validated (snapshot tested) in https://github.com/localstack/localstack-ext/pull/584.
=> fixed physical resource id for AWS::Glue::SchemaVersionMetadata

tests/aws/services/stepfunctions/utils.py, tests/aws/services/stepfunctions/v2/test_sfn_api.py, tests/aws/services/stepfunctions/v2/test_sfn_api.snapshot.json, tests/aws/services/stepfunctions/v2/test_sfn_api.validation.json
Currently the test `tests.aws.services.stepfunctions.v2.test_sfn_api.TestSnfApi.test_stop_execution` is flaky as the wait condition before sending the interrupt action does not wait on a (semi)terminal point, when the evaluation starts executing the wait state, but rather on the start of the program evaluation. This PR addresses this issue by defining the wait condition before sending the interrupt to be the execution of the wait state.
- Changed the wait condition to be the wait state execution, not the execution start
- Exposes the wait on event logic as other test cases may benefit from this flexibility
- Regenerated snapshot test
=> [SFN] Fix Flaky Stop Execution Test

localstack/services/events/event_ruler.py, localstack/services/events/models_v2.py, localstack/services/events/provider_v2.py, localstack/services/events/rule.py, localstack/services/events/target.py, tests/aws/services/events/test_event_patterns.py, tests/aws/services/events/test_event_patterns.snapshot.json, tests/aws/services/events/test_event_patterns.validation.json, tests/aws/services/events/test_events.py, tests/aws/services/events/test_events.snapshot.json, tests/aws/services/events/test_events.validation.json, tests/aws/services/events/test_events_integrations.py, tests/aws/services/events/test_events_integrations.snapshot.json, tests/aws/services/events/test_events_integrations.validation.json, tests/aws/services/events/test_events_rules.py
This PR adds pattern matching to distribute incoming events based on event bus specified in the event, rules in the matching event bus and matches the patterns in the rules. 
It uses the existing rule matching algorithm from v1, which is limited, e.g. patterns with `anything but` or `exists = True`. 
Add parsing for event pattern to a dictionary, and add validating of pattern.
Add correct formatting of events and add additional keys. 
Add API method to test event pattern using same matching algorithm as for distributing events to targets.
Remove skip markers from now passing tests.
Set the env variable `PROVIDER_OVERRIDE_EVENTS=v2` and run tests in events folder. All unsupported tests have the appropriate skip markers.
=> Feat: Eventbridge v2:  Add pattern matching

localstack/aws/protocol/serializer.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.validation.json, tests/unit/aws/protocol/test_serializer.py
When performing API calls for sqs like "ReceiveMessage" directly via HTTP outside the CLI, the response was malformed. It was malformed in general, and had an additional error for json messages. This PR addresses these issues.
- fixes the json parsing by taking into account the escaping of a potential json dump
=> fix serialization for sqs http calls

localstack/services/cloudformation/provider.py, tests/aws/services/cloudformation/api/test_stacks.py, tests/aws/services/cloudformation/api/test_stacks.snapshot.json, tests/aws/services/cloudformation/api/test_stacks.validation.json, tests/aws/templates/simple_no_change.yaml, tests/aws/templates/simple_no_change_with_transformation.yaml
Fixes #10562
The CloudFormation `UpdateStack` operation behaves differently in the case of no updates depending on if there's template processing involved or not (e.g. via transformation/macro). This is a sort of hotfix for #10562 and we might need to investigate a bit more *why* this happens, e.g. via also looking at the situation when using ChangeSets. 
- If the template is undergoing a transformation on UpdateStack, we now don't raise an exception anymore to be in parity with AWS.
See #10562. Two validated tests have been added as well (replacing one old `needs_fixing`).
=> Fix CFn UpdateStack response on identical templates that include a transformation

DOCKER.md, README.md
https://github.com/localstack/localstack/pull/10775 renamed the `doc` folder to `docs`.
The README of the repo and the DockerHub description references the banner in this directory.
This PR updates these links.
- Updates the links to the README.
- Tested the new links manually.
=> fix banner link in READMEs

localstack/services/stepfunctions/asl/component/state/state_execution/state_map/iteration/distributed_iteration_component.py, tests/aws/services/stepfunctions/templates/scenarios/scenarios_templates.py, tests/aws/services/stepfunctions/templates/scenarios/statemachines/map_state_config_distributed_reentrant.json5, tests/aws/services/stepfunctions/templates/scenarios/statemachines/map_state_config_distributed_reentrant_lambda.json5, tests/aws/services/stepfunctions/templates/scenarios/statemachines/map_state_legacy_reentrant.json5, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.py, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.snapshot.json, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.validation.json
Currently the StepFunctions v2 interpreter is unable to execute reentrant distributed map states. This is due to a lack of end of evaluation cleanups, which means the workers activate logic does not start any new workers. This PR addresses such issue and adds relevant snapshot tests. Addresses: #10662
- Added member cleanups at the end of distributed map evaluation
- Added relevant snapshot tests
=> [SFN] Execution of Reentrant Distributed Map States

.circleci/config.yml
CircleCI Pipeline started failing on the steps that are not actively using the test selection but were using the tinybird pytest setup command since it assumed the existence of the generated test selection file without having an actual dependency on it defined via the workflow.
See: https://github.com/localstack/localstack/pull/10785
And especially the run here: https://app.circleci.com/pipelines/github/localstack/localstack/24674/workflows/f7383c5f-7a94-48c3-8734-eb4a6d4387b7/jobs/205055
- Separates the env setup command for the testselection from the tinybird setup so it will only be executed on jobs that actually make use of it and depend on it.
=> Separate test selection env setup from tinybird setup

README.md
Previously: `install`, `installation`, and `installing` we're all used. Clicking on `Install` link inside README did nothing.
Currently: use `install` everywhere.
- fix a link that is not working in README
=> fix missing href inside README.md

localstack/services/kinesis/kinesis_mock_server.py
I randomly came across this `FIXME` comment here. The use of the relative path should not be needed, as the upstream [issue](https://github.com/etspaceman/kinesis-mock/issues/554) has been resolved.
I also run the persistence tests in a [companion branch](https://github.com/localstack/localstack-ext/actions/runs/8929367616/job/24527310273?pr=2937).
- Removed the use of `os.path.relpath` for the `PERSIST_PATH` env variable.
=> Remove fix to relative persistence path for Kinesis

.github/workflows/asf-updates.yml
Last week we upgraded to `ruff==0.4.3`.
With this release, the [ASF update action broke](https://github.com/localstack/localstack/actions/runs/9057484320) due to https://github.com/astral-sh/ruff/pull/11168.
This PR starts reworking the F401 fixes, and now `lint.ignore-init-module-imports = false` is ignored and `lint.preview = true` has to be set to enable the F401 fixer.
- Updates the ruff command such that the linting fixes are working again (switching from `lint.ignore-init-module-imports = false` to `lint.preview = true`).
- Tested the commands executed in the [ASF update action](https://github.com/localstack/localstack/blob/7917b4af501720cdff328b38298f6bd71245b307/.github/workflows/asf-updates.yml) locally:
```
make install-dev
source .venv/bin/activate
pip install --upgrade …
```
=> fix asf update action by updating ruff fix command

localstack/services/events/models.py, localstack/services/events/provider.py, localstack/services/events/target.py, tests/aws/services/events/conftest.py, tests/aws/services/events/test_events_inputs.py, tests/aws/services/events/test_events_inputs.snapshot.json, tests/aws/services/events/test_events_inputs.validation.json, tests/aws/services/events/test_events_integrations.py
Enable the input path (transformer) feature (https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_Target.html).
This allows to specify an input path for the target, the body of matching event is parsed based on the specified json path and only the filtered content is sent to the target.
Add input transformer functionality to rule class. 
Add `process_event` method that transforms the event content with the input path transformer if an input path is specified in the target.
Change from `send_event` to `process_event` method invoced by the provider.
=> Feature: Eventbridge v2: Add input path

tests/aws/services/stepfunctions/v2/callback/test_callback.py, tests/aws/services/stepfunctions/v2/test_sfn_api.py
Currently two test cases concerning heartbeat notifications appear to be flaky, this PR adds temporary skips to these tests until the root cause can be addressed.
The PR also removes a redundant check in a stop execution test.
https://app.circleci.com/pipelines/github/localstack/localstack/24756/workflows/5cf27d74-2876-4903-8510-1e31ee87541b/jobs/206021/parallel-runs/3?filterBy=FAILED
https://app.circleci.com/pipelines/github/localstack/localstack/24760/workflows/321dcfb5-ca16-46f8-a7a9-7ec3fbc871f6/jobs/206069
=> [SFN] Temporary Skip of Flaky Test Cases

localstack/services/sns/provider.py, tests/aws/services/sns/test_sns.py, tests/aws/services/sns/test_sns.snapshot.json, tests/aws/services/sns/test_sns.validation.json
As reported with #10796, I've introduced a small regression with #10788 by fixing cross-account and pulling the listing operations from moto. 
- re-introduced the pagination and an AWS validated test for the pagination. 
_fixes #10796_
=> fix pagination for SNS ListSubscriptions and ListSubscriptionsByTopic

localstack/aws/api/s3/__init__.py, localstack/aws/spec-patches.json, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.validation.json
Similar to #8329, we had a report with #10801 where the AWS Java SDK v1 could not properly parse the Bucket name out of the field. The reporter added very useful information about `AmazonS3.xsd`, we quickly communicated with @alexrashed about it, especially the fact that the S3 fields are reported as `<xsd:sequence>`, meaning the order is required/important. We will need to think about how we could add such specs, but also keep them in sync. 
- similar to #8329, removing the `Versions` field from the spec and re-adding it, counting of Python dictionary ordering to make it last
- added a test to verify the fix
_fixes #10801_
=> fix ListObjectVersions field order

localstack/services/apigateway/templates.py, tests/unit/test_templating.py
Reverts localstack/localstack#10816
The reverted PR causes an -ext test to fail, which uses the following request template: `Action=SendMessage&MessageBody=$util.urlEncode($input.body)`.
An empty body is defaulted to a dict, which cannot be urlencoded. We either need special handling, a different default value, or a completely different fix for the original issue the PR tried to address.
cc @marcciosilva
=> Revert "APIGW: Default to an empty dict when the provided body for an API Gateway step function is an empty string"

.github/ISSUE_TEMPLATE/bug-report.yml, localstack/services/infra.py
Going through issues it's often quite hard to reproduce issues, especially when a bug report simply specifies that it was run with `localstack/localstack:latest`. Even with the date of the bug report this is not reliable information since the issue reporter might not have pulled a new version right before the issue was opened.
This PR intends to improve the bug report template a tiny bit by giving us better information about the version of localstack used.
- Add another line to the startup logs of LocalStack, e.g. `LocalStack Docker image sha: sha256:f7c3a25c88a7888fafe5029069fc7d093a888abd0bdd9c4303ead58e90d8bc8a`
- Remove `latest` from the bug report template and instead refer to this startup output.
=> Add image sha to startup information and more details to bug report template

.circleci/config.yml
The run time of our pipeline increased dramatically somewhat around the time of our latest bump of moto (with https://github.com/localstack/localstack/pull/10742).
This is causing some timeouts in the pipeline due to the hard limit of 60 minutes for a job in CircleCI.
While we are still investigating the issue, this PR tries to unblock the pipeline by adding another parallel runner in the meantime.
- Adds another runner to the CircleCI integration tests for until we identified the issue.
/cc @viren-nadkarni
=> mitigate CI timeouts by increasing parallelism

tests/aws/services/sns/test_sns.py, tests/aws/services/sns/test_sns.snapshot.json, tests/aws/services/sns/test_sns.validation.json
As shown by https://app.circleci.com/pipelines/github/localstack/localstack/24900/workflows/810d396a-b56e-4ad2-bb6c-ce6e4d73f4b4/jobs/207505/tests, there was a wrong assertion in `test_list_subscriptions_by_topic_pagination` and the base64 string finishing by `==`, which worked with the length of the ARN in `us-east-1` and against AWS and most probably needed padding. 
- changed the assertion to just assert it is base64
=> fix SNS test with wrong base64 assumption

pyproject.toml, requirements-base-runtime.txt, requirements-basic.txt, requirements-dev.txt, requirements-runtime.txt, requirements-test.txt, requirements-typehint.txt
Plux 1.10.0 now properly supports entry point resolution for editable wheels, the lack of which has caused headaches in the past, and also blocks #10800.
* localstack now uses plux 1.10.0 and no longer needs stevedore
=> update plux to 1.10.0

localstack/services/sqs/constants.py, localstack/services/sqs/models.py, tests/aws/services/cloudformation/resources/test_sqs.py, tests/aws/services/cloudformation/resources/test_sqs.validation.json, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.snapshot.json, tests/aws/services/sqs/test_sqs.validation.json, tests/aws/templates/sqs_fifo_autogenerate_name.yaml
Looking into issue #10812, I realised that the attributes were not being validated at queue creation.
While the [documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html#API_CreateQueue_RequestParameters) does mention `false` as an appropriate value for this attribute, reports are dating back 2017 that providing it results in `AttributeNameError`. 
The method `validate_queue_attributes` was already enforcing this behaviour but it wasn't called when originally creating the queue.
A test for fifo queue attributes is also now fixed. :smile: 
fix #10812
=> validate attributes when creating SQS queues

localstack/services/sns/filter.py, tests/aws/services/sns/test_sns_filter_policy.py, tests/aws/services/sns/test_sns_filter_policy.snapshot.json, tests/aws/services/sns/test_sns_filter_policy.validation.json, tests/unit/test_sns.py
As reported in #9738, AWS launched new operators for SNS filtering. `suffix` and `equals-ignore-case` are pretty simple to implement, but `$or` necessitated a quite consequent rewrite, as the logic can get quite convoluted pretty fast. It quickly creates a lot of different forks, where one rule can have multiple branches and a payload can have multiple branches too if it contains array. 
Also included better support for `anything-but`, which can accept any regular "plain" values like string, numbers and list of string & number. It can also accept the `prefix` operator, see https://docs.aws.amazon.com/sns/latest/dg/string-value-matching.html#string-anything-but-matching-prefix
Also, we still had an issue with some ordering of complex payload with arrays, see …
=> implement SNS Filter/operators $or, suffix, equals-ignore-case, anything-but

localstack/services/cloudformation/engine/transformers.py, tests/aws/services/cloudformation/test_template_engine.py, tests/aws/services/cloudformation/test_template_engine.snapshot.json, tests/aws/services/cloudformation/test_template_engine.validation.json, tests/aws/templates/pyplate_deploy_template.yml, tests/aws/templates/pyplate_example.yml
When creating resource from `AWS::CloudFormation::Macro`, there was a missing support of parameter type `CommaDelimitedList`. This was reported in https://github.com/localstack/localstack/issues/10794 where user is trying to create a nested template with the following parameter:
```
Subnets:
Type: CommaDelimitedList
Description: The IDs of the public DMZ subnets
```
using PyPlate Macros: https://github.com/aws-cloudformation/aws-cloudformation-macros/tree/master/PyPlate.  
Sample template: 
```
AWSTemplateFormatVersion: "2010-09-09"
Description: tests String macro functions
Parameters:
Tags:
Default: "Env=Prod,Application=MyApp,BU=ModernisationTeam"
Type: "CommaDelimitedList"
Resources:
S3Bucket:
Type: "AWS::S3::Bucket"
Properties:
Tags: |
#!PyPlate
output = []
for tag in params['Tags']: …
```
=> add support for `CommaDelimitedList` in cloudformation macro

localstack/dev/run/configurators.py
When using the CLI in extension dev mode under windows, the custom container entrypoint file gets generated using windows file endings (`\r\n`).
This file is then mounted into the linux container, and fails to execute due to the wrong line endings.
To avoid this, we now force linux file endings for container entrypoints, and in addition utf-8 encoding, since some entrypoints (for example the extension dev mode one) contains unicode characters.
- LocalStack now starts in extension dev mode under windows without additional intervention
=> Fix entrypoint script configurator encoding and line endings in windows

localstack/services/cloudformation/engine/quirks.py, localstack/services/cloudformation/scaffolding/propgen.py
This PR adds changes to allow the correct deployment of WAFv2 resource providers. These resources physical ids are composed like: Name|Id|Scope. 
Also, trying to use the scaffolding tool to generate the files for WAFv2::WebACL throws a RecursionError. 
- CFn quirks added for WAFv2 resources
- Scaffolding changes for correct WebACL scaffolding
=> add small quirks for new resource providers

localstack/services/events/models.py, localstack/services/events/provider.py, localstack/utils/tagging.py, tests/aws/services/events/conftest.py, tests/aws/services/events/test_events.py, tests/aws/services/events/test_events_schedule.py, tests/aws/services/events/test_events_tags.py, tests/aws/services/events/test_events_tags.snapshot.json, tests/aws/services/events/test_events_tags.validation.json
Event bridge allows for adding tags to event buses and rules: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-tagging.html
This PR introduces the ability to create event buses and rules with tags, add and remove tags to existing buses or rules and list tags for buses and rules.
Use most widely used pattern of handling tags from multiple other services by extend store with TagDict mapping resource arn to the dictionary of tags.
Exten test suite to cover all different options of tagging.
=> Feature: Eventbridge v2: Add tagging

localstack/services/secretsmanager/resource_providers/aws_secretsmanager_resourcepolicy.py, tests/aws/services/cloudformation/resources/test_secretsmanager.py, tests/aws/services/cloudformation/resources/test_secretsmanager.snapshot.json, tests/aws/services/cloudformation/resources/test_secretsmanager.validation.json
When deploying an `AWS::SecretsManager::ResourcePolicy` resource with CloudFormation, if `BlockPublicPolicy` is not specified, it should default to `True` however in LocalStack it is represented as `None` which is not a valid type for this property.
* Default the property to `True` if not specified
* Update existing test that creates a ResourcePolicy to either specify the value, or use `AWS::NoValue` to _not_ provide a value
=> CFn: handle secretsmanager policy BlockPublicPolicy

localstack/services/s3/presigned_url.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
Following #10844 where the request sent was malformed but the raised exception was an internal one:
```python
2024-05-17T09:08:44.719 ERROR --- [et.reactor-0] l.aws.handlers.logging     : exception during call chain
File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
File "/opt/code/localstack/localstack/aws/handlers/presigned_url.py", line 23, in __call__
handler(chain, context, response)
File "/opt/code/localstack/localstack/services/s3/presigned_url.py", line 201, in __call__
validate_presigned_url_s3v4(context)
File "/opt/code/localstack/localstack/services/s3/presigned_url.py", line 425, in validate_presigned_url_s3v4
sigv4_context, exception = …
```
=> add S3 pre-signed credentials validation

tests/aws/services/events/test_events_schedule.py
https://app.circleci.com/pipelines/github/localstack/localstack/25066/workflows/65d9646b-f169-4529-8921-372196cc9876/jobs/209167
I've seen it fail in another run as well, but it wasn't mine and can't find it anymore. 
Also, I know this is hard to test but those tests are taking a long time to execute due to their nature:
```
============================= slowest 10 durations =============================
121.51s call     tests/aws/services/events/test_events_schedule.py::TestScheduleRate::tests_schedule_rate_target_sqs
120.07s call     tests/aws/services/events/test_events_schedule.py::TestScheduleCron::test_schedule_cron_target_sqs
63.36s call     tests/aws/services/lambda_/test_lambda_integration_sqs.py::test_fifo_message_group_parallelism
62.26s call …
```
=> skip flaky test_schedule_cron_target_sqs

localstack/services/s3/presigned_url.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
As reported in [our Slack community](https://localstack-community.slack.com/archives/CMAFN2KSP/p1716214732559039), we had an issue validating a S3 Pre-signed POST request containing the following condition in the policy: `{"Content-Type": "text/plain"}`. This was due to an issue in the condition matching where we would lower all the form keys, but tried to get the original casing condition key in the form. 
- use the lowered condition key to fetch the value from the form
- add a test validating the use case for this condition format (using `dict` format instead of list with `eq`).
=> fix S3 Pre-signed POST policy condition casing

tests/unit/utils/test_net_utils.py
We saw that the `tests.unit.utils.test_net_utils.test_get_free_tcp_port_range_fails_if_cannot_be_bound` is not stable in the pipeline. 
This can be seen in the following workflow [here](https://app.circleci.com/pipelines/github/localstack/localstack/25074/workflows/bcb0f2ac-094c-410f-9086-ed18ada8d50c), and a re-run [here](https://app.circleci.com/pipelines/github/localstack/localstack/25074/workflows/d2099223-8997-467b-8abe-56f070e1879d) which greenifies the pipeline. 
The CircleCI test insights show that the test failed at least 2 times by now:
And has observed failures in past runs as well.  
Skips flaky test: `test_get_free_tcp_port_range_fails_if_cannot_be_bound` in order to decrease the instability in pipelines.
=> skip flaky test_get_free_tcp_port_range_fails_if_cannot_be_bound

localstack/services/lambda_/invocation/lambda_models.py, localstack/services/lambda_/invocation/lambda_service.py, tests/aws/services/lambda_/test_lambda_developer_tools.py
When specifying a path for hot-reloading, we require an absolute path on the host, as it is expected for docker bind mounts.
However, this has an important limitation: Templates with a path defined or Cloudpods cannot be easily shared between systems where the code location differs.
For example, a checked out repository with the code at `/home/user1/shared-repository/src` could be checked out at `/home/user2/repositories/shared-repository/src` at another users machine.
To enable sharing of templates and cloudpods with hot-reloading paths between different machines without modification, this PR will add the option to use environment variables expansion within the hot-reloading paths. A hot-reloading path like `$HOST_DIR/src` can now be used in the templates or cloud pods, if an environment …
=> Add support for environment variable placeholders in hot-reloading paths

localstack/aws/handlers/partition_rewriter.py
Client using ARN_PARTITION_REWRITING flag has reported that content-length provided by head-object method in s3api is always invalid.
Since in WerkzeugResponse class, setting data also causes header content-length to be invalid, I've added skip for partition adjustment of response data if it is empty.
Since we are working on new solution for partitions and this is a temporary fix until then,  I've only did manual tests.
=> Using ARN_PARTITION_REWRITING flag causes s3api head-object to provide invalid content-length

localstack/services/apigateway/provider.py, tests/aws/services/apigateway/test_apigateway_ssm.py, tests/aws/services/apigateway/test_apigateway_ssm.snapshot.json, tests/aws/services/apigateway/test_apigateway_ssm.validation.json
When attempting to use `uri: arn:aws:apigateway:region:ssm:action/GetParameter` the following error is retuned to the user
```{"Type": "User", "message": "Error invoking integration for API Gateway ID '12345678': API Gateway integration type \"AWS\", method \"GET\", URI \"arn:aws:ssm:region:000000000000:action/GetParameter\" not yet implemented", "__type": "InvalidRequest"}```
As there is no documentation regarding this integration, this test will verify this is currently not available. And when it is this test can be update to reflect the GetParameter on SSM.
This is a test only PR.
This is a test only PR.
=> Add SSM apigateway service test

tests/aws/services/firehose/test_firehose.py
We saw that the `tests.aws.services.firehose.test_firehose.TestFirehoseIntegration.test_kinesis_firehose_opensearch_s3_backup` is not stable in the pipeline. 
This can be seen in the following workflow [here](https://app.circleci.com/pipelines/github/localstack/localstack/25035/workflows/3b85a30f-79b8-43c8-b68c-4b038071a0f8/jobs/208800/tests), and a re-run [here](https://app.circleci.com/pipelines/github/localstack/localstack/25035/workflows/fa01e003-fa58-4361-bc76-dfa1942aa000) which fixed the pipeline. 
From the test insights on CircleCI its observed that the success rate of this test is 99%:
And has observed failures in past runs as well.  
Skips flaky test: `tests.aws.services.firehose.test_firehose.TestFirehoseIntegration.test_kinesis_firehose_opensearch_s3_backup` in order to …
=> skip flaky tests.aws.services.firehose.test_firehose.TestFirehoseIntegration.test_kinesis_firehose_opensearch_s3_backup

localstack/runtime/analytics.py
With the current push on developing the chaos engineering suite, we want to gain an insight on how existing chaos features are being used.
This PR adds the following env config options to analytics collection:
- [`DYNAMODB_ERROR_PROBABILITY`](https://docs.localstack.cloud/references/configuration/#dynamodb)
- [`KINESIS_ERROR_PROBABILITY`](https://docs.localstack.cloud/references/configuration/#kinesis)
=> Collect analytics on error probability config options

.github/workflows/tests-cli.yml
Hey! 🙂
I've made the following changes to the workflow:
- Use permissions whenever using Github Token
- Permissions should be used when using the GitHub token as this token full access to the whole repository otherwise meaning that malicious code can tamper with the whole repository.
- Run tests on multiple OS's
- Running the tests on multiple OS's provides a better test suite as all the functionality will be tested on the supported OS's by the platform.
- Define permissions for workflows with external actions
- Permissions should be used when running actions written by other developers because there may be security leaks exposed through these actions.
- Avoid uploading artefacts forks
- Uploading artefacts from forks is usually unwanted behaviour, especially to places outside GitHub. …
=> limit github token permissions, fix cli action for fork runs

localstack/services/sqs/models.py, localstack/services/sqs/provider.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.snapshot.json, tests/aws/services/sqs/test_sqs.validation.json
Users [raised the issue](https://github.com/localstack/localstack/issues/10107) that fifo queues become unusable after messages were moved to a DLQ.
After a fifo queue's message's receive count exceeds the maximum and is moved to a DLQ, its message group remains invisible. This PR addresses this issue.
fixes #10107 
- add method to allow the provider to call the missing visibility changes to the message group after moving the message
I am not happy with how this change is implemented, but I am unsure what the best way is.
The root cause is that we simply never addressed the message group visibility when a dlq move is triggered, so obviously we need to address that. There are two main ways to do this that I see:
- Provider calls the necessary code in the "move to dlq" block directly. …
=> fix Sqs fifo message group invisibility after triggering move to dlq

localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_factory.py, localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_unsupported.py
Currently the SFN v2 interpreter lacks support for a subset of the (stepfunctions optimised service integrations)[https://docs.aws.amazon.com/step-functions/latest/dg/connect-supported-services.html]. This results in state machine that define unsupported service integrations to fail on creation. However, this prevents the execution of state machines that may never execute such logic, or prevents the execution in circumstances in which a simple forward to the target service with support for `.waitForTaskToken` may be required. This PR addresses such behaviour by logging the incident and attempting to relay the call to the target service, and also expose support for `.waitForTaskToken` workflows.
- Added generic resolver for unsupported service integrations.
=> [SFN] Add Generic Resolver for Unsupported Optimised Service Integrations

localstack/services/s3/v3/provider.py, localstack/services/s3/v3/storage/core.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
As reported in #10881, we hit a deadlock in S3 when copying in place from a never versioned bucket into a `Suspended` bucket. This was due to a missing check in the copy in-place detection. We only ever checked if the object did not have a `version_id`, but `version_id = None` give the same result as `version_id = "null"`. 
This part of the code was then responsible for the deadlock:
```python
if should_copy_in_place(src_bucket, src_object, dest_bucket, dest_object):
return self.open(dest_bucket, dest_object, mode="r")
with self.open(src_bucket, src_object, mode="r") as src_stored_object:
dest_stored_object = self.open(dest_bucket, dest_object, mode="w")
dest_stored_object.write(src_stored_object)
```
As the copy was not flagged as "in-place" when it should, we would not return early and …
=> fix S3 CopyObject in place deadlock for Suspended buckets

localstack/services/secretsmanager/resource_providers/aws_secretsmanager_secret.py, tests/aws/services/cloudformation/resources/test_secretsmanager.py, tests/aws/services/cloudformation/resources/test_secretsmanager.snapshot.json, tests/aws/services/cloudformation/resources/test_secretsmanager.validation.json
Client has reported issue where using CDK would generate SecretString value on AWS but not on LS
In CFn if you omit both GenerateSecretString and SecretString, you create an empty secret.
CDK wil generate empty dictionary, which means that CFn will receive value for GenrateSecretString (empty dictionary). 
In which case we also need to generate SecretString.
I've modified CFn provider for Secret, to also work with empty dictionary and added tests.
=> Resolved issue where using CDK wouldn't generate SecretString value

localstack/config.py, localstack/services/lambda_/invocation/docker_runtime_executor.py, localstack/services/lambda_/invocation/event_manager.py, localstack/services/lambda_/invocation/lambda_models.py, localstack/services/lambda_/invocation/version_manager.py, localstack/services/lambda_/provider.py, tests/aws/services/lambda_/functions/lambda_s3_integration_function_version.py, tests/aws/services/lambda_/test_lambda.py, tests/aws/services/lambda_/test_lambda.snapshot.json, tests/aws/services/lambda_/test_lambda.validation.json, tests/aws/services/lambda_/test_lambda_performance.py, tests/aws/services/lambda_/utils.py
Addresses https://github.com/localstack/localstack/issues/10280
Re-creating a Lambda function immediately after deleting it, triggers a race condition and deletes the internal async invoke queue. This causes continuous error logs and breaks async invokes.
The namespace clash also causes further issues because queued invokes can get deleted.
* Introduce a volatile (i.e., non-persisted) function instance id unique to a running LocalStack installation that can be used for the async queue namespace
* Add test `test_recreate_function` to reproduce the reported function recreate issue
* Add test `test_function_update_during_invoke` to validate the AWS behavior of function updates during a running invocation => Currently broken on LocalStack ⚠️ 
* Add test …
=> Fix Lambda async invocation queue namespace

localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service.py, tests/aws/services/stepfunctions/templates/services/services_templates.py, tests/aws/services/stepfunctions/templates/services/statemachines/aws_sdk_s3_get_object.json5, tests/aws/services/stepfunctions/v2/services/test_aws_sdk_task_service.py, tests/aws/services/stepfunctions/v2/services/test_aws_sdk_task_service.snapshot.json, tests/aws/services/stepfunctions/v2/services/test_aws_sdk_task_service.validation.json
Currently the StepFunctions interpreter does not perform normalisation steps to the output values of service responses. This is observable whenever the response type is not json inferable. For example responses of `s3` `GetObject` that include StreamingBody data types. This PR addresses such issue by adding a normalisation step for the response values, and uses this pattern to normalise StreamingBody data types. Addresses: #10787 
- Add a response value normalisation step to the response normalisation workflow
- Add normalisation of StreamingBody data types
- Add related tests using `aws-sdk:s3:getObject`
=> [SFN] Add Normalisation of Service Response Values

localstack-core/localstack/services/kinesis/resource_providers/aws_kinesis_stream.py, localstack-core/localstack/testing/pytest/fixtures.py, tests/aws/services/cloudformation/test_template_engine.py, tests/aws/services/cloudformation/test_template_engine.snapshot.json, tests/aws/services/cloudformation/test_template_engine.validation.json, tests/aws/templates/functions_get_azs.yml
We cannot currently run the `test_get_azs_function` test against any other region but us-east-1 due to snapshot capture, and the `deploy_cfn_template` fixture being locked to the current profile region. We do not get coverage of other regions with this test.
Note: the `Fn::GetAZs` intrinsic function _must_ be called with the stack region as its argument, otherwise it returns nothing.
- Test cleanup
- Support custom AWS client for `deploy_cfn_template` including standardising the stack deletion process between the automatic fixture cleanup, and the `DeployResult.destroy` method, ensuring the correct region is used
- Parametrize `test_get_azs_function` to evaluate all regions. This basically ignores the chosen region for the cross-region tests, but in a sense we gain _more_ coverage as we …
=> CFn: Parametrize Fn::GetAZs test across all regions

localstack-core/localstack/services/lambda_/invocation/lambda_models.py
With #10831 we introduced an function instance id, which should not be persisted.
However, on persistence restore we do not set the instance_id again, so the restored state does not contain the attribute, which leads to errors down the road.
We need to explicitly set the instance id after restore, `__post_init__` is not called by default on unpickling.
* LocalStack Lambda persistence should be fixed, no more `AttributeError` thrown after persistence restore
=> Fix lambda persistence restore

.circleci/config.yml, bin/docker-helper.sh, tests/bin/test.docker-helper.bats
#10872 migrated the make targets to push the Docker images to a separate helper script.
Unfortunately a few small issues sneaked into the script and its usage, which are fixed with this PR.
- Fixes the usage of the docker-helper in the CircleCI workflow (small typo, `push-manifests` instead of `push-manifest`)
- Fix the push targets in case `FORCE_VERSION_TAG_PUSH` is not set.
- Fix the detection of a version bump.
- There was still the old version detection from #10276, but this has changed by @silv-io with #10497 in the meantime.
=> fix docker helper usage typo and push without force flag

tests/aws/services/logs/test_logs.py, tests/aws/services/logs/test_logs.validation.json
As an initiative to remove all `markers.aws.unknown` markers from the tests, this PR tackles the ones concerning logs.
* changed the marker to `validated` if it passed with AWS
* changed the marker to `needs_fixing` if it didn't pass with AWS
=> remove unknown-markers in test_logs

localstack-core/localstack/services/cloudformation/provider.py
For some reason the moto backend was probably unintentionally added last year to the persisted CFn state even though we don't actually use moto in the service.
Saw this by chance when trying to debug persistence. It shouldn't have any actual effect on persistence tests since we're not using moto in the service but still good to clean this up.
- Only our internal CloudFormation store will be persisted now
=> Remove CloudFormation moto backend from persisted state

localstack-core/localstack/testing/testselection/opt_in.py, localstack-core/localstack/utils/bootstrap.py
The test selection allows future PRs containing strictly service changes to only execute tests corresponding to those services and services that depend on them. However, to enable this, services need to opt in. 
This PR offers the opportunity to opt in services to the test selection. These services are opting in with this PR:
- IAM
- STS
- KMS
- Transcribe
- Secretsmanager
- Route53 Resolver
- <add your service as needed>
Furthermore, paths are adjusted to the new structure, prefixed with `localstack-core/`
=> Opt in services to the test selection

localstack-core/localstack/services/s3/presigned_url.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
As a follow up from #10862, the same user encounter an issue when the policy condition were the following:
`["content-length-range", "0", "104857600000"]]`, as being generated by https://docs.fineuploader.com/endpoint_handlers/amazon-s3.html
This was a hole in our validation, we didn't check that the content length range could be a string. 
- added test cases for content length range with strings (valid and invalid)
- fixed the logic to properly handle strings
=> fix pre-signed POST str type for content-length-range

localstack-core/localstack/utils/container_utils/container_client.py, tests/integration/docker_utils/test_docker.py, tests/unit/test_dockerclient.py
We currently do not support `--env-file` specification in the `DOCKER_FLAGS` variables.
It has, however, been requested by a customer to support this flag.
Please note that in the case of `--env-file`, the path to the env file has to be inside the LocalStack docker container.
This means, that the file has to be copied or mounted into the container before its usage, in essence before an affected container is spawned.
I avoided the usage of `docker-dotenv` (even though already installed) and wrote a simple manual parser of the environment files here, since the docker environment file parsing is quite limited. It for example does not respect comments at the end of a line (only when the line starts with a #) and also does not support referencing existing variables.
The usage of …
=> Add support for the --env-file flag in docker flags

localstack-core/localstack/services/s3/utils.py, localstack-core/localstack/services/s3/v3/models.py, localstack-core/localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
As reported in #10898, multipart uploads still did not have checksum implemented. This was left as a TODO during the migration of S3, and I've now implemented it. 
See https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html#large-object-checksums
- enable and regenerate tests for this feature
- implement logic in the models for checksum logic, properly checking if the checksum provided are there, and if we're providing checksum or not depending on what was done during `CreateMultipartUpload`
- additional fixes around `PartsCount` for `HeadObject`
_fixes #10898_
=> implement S3 checksum for Multipart uploads

tests/aws/services/transcribe/test_transcribe.py
This PR aims to remove `markers.aws.unknown` in transcribe tests. 
This PR updates the marker to `needs_fixing` if it didn't pass against AWS.
=> remove unknown-markers in test_transcribe

tests/aws/services/kms/test_kms.py
As an initiative to remove all `markers.aws.unknown` markers from the tests, this PR aims to deal with the ones present in kms tests.
This PR: 
- changes the marker to `validated` if it runs against AWS
- changed the marker to `needs_fixing` if it didn't runs against AWS
=> remove unknown-markers in test_kms

.github/workflows/tests-pro-integration.yml
A new [security patch](https://packages.ubuntu.com/search?keywords=postgresql-14) was release for postgresql-14. `14.11-0ubuntu0*` is no longer available and we should use the latest `14.12-0ubuntu0*` instead. 
Currently broken [Community Integration Tests against Pro](https://github.com/localstack/localstack/actions/runs/9306747645/job/25616582221#logs)
This is a quick fix. We should probably consider an approach that would not break the build when security patches are released.
=> fix postgress install in ci

localstack-core/localstack/aws/protocol/parser.py, localstack-core/localstack/aws/protocol/serializer.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json, tests/unit/aws/protocol/test_parser.py
As reported in #10925, we've had an issue parsing header list for the `GetObjectAttributes` S3 operation, following some updates in the Ruby SDK. The reporter also opened an issue in the ruby SDK repo, where they linked the RFC regarding header list and that optional whitespace is indeed accepted. 
RFC: https://www.rfc-editor.org/rfc/rfc9110.html#name-lists-rule-abnf-extension
- create an AWS validated test to validate the change
- add test for the parser
- add the fix in the parser: stripping the whitespace of header list values
_fixes #10925_
=> fix header list parsing in ASF

localstack-core/localstack/services/s3/resource_providers/aws_s3_bucket.py, tests/aws/services/cloudformation/resources/test_s3.py, tests/aws/services/cloudformation/resources/test_s3.snapshot.json, tests/aws/services/cloudformation/resources/test_s3.validation.json, tests/aws/services/s3/test_s3.py, tests/aws/templates/s3_bucketpolicy.yaml
This PR is a part of removing `unknown` test markers.
The only `unknown` markers were on the cross account tests. As those are simplified tests with no IAM permissions, verifying that we can access cross-account resources, those might be marked `only_localstack` for now.
It could also be considered `needs_fixing`, but I think we could move those tests as part of the IAM tests for cross buckets access? 
Also, I believe you would need a set of 2 AWS accounts to validate it, making use of the secondary account fixture, which not many people have? 
I've tried to look around what already existed for other services, and some are `only_localstack`, some `validated` and some `unknown`. Maybe @viren-nadkarni can chime in for how those tests should be considered? 
I've also taken the opportunity to …
=> remove unknown markers from S3 tests 

tests/aws/services/s3control/test_s3control.py, tests/aws/services/s3control/test_s3control.snapshot.json, tests/aws/services/s3control/test_s3control.validation.json
As part of the S3 Control provider migration, I had started to add more tests with #9730.
Sadly, I didn't have the time to fully go through with the migration, and we didn't get a request yet for it. I'll focus more on it if we have then, it only needs a bit more work which should be fine (+ integration with S3 itself). 
But as part of validating and removing `aws.unknown` test markers, I'm already cherry picking the tests.
- validate existing tests for S3 Control
- add more tests regarding S3 Control resources, but those are skipped for now as we don't implement the logic yet
=> validate and add S3Control tests

localstack-core/localstack/utils/aws/aws_stack.py
We currently create the boto3 session multiple times for checking available regions in the RegionBundle.
This code is called on the first store access per account for every service.
The changes in this PR should cache the result, and reduce the initial store instantiation time from around 200ms to around 50ms.
Due to the caching, the first request in additional accounts will be instantenous.
* LocalStack should respond ~150ms (depending on the system) faster on the first store-accessing call for each service for a new account.
=> Increase performance for first store creation per account/service

localstack-core/localstack/services/cloudformation/deploy_ui.py, localstack-core/localstack/services/cloudformation/plugins.py, localstack-core/localstack/services/internal.py, tests/unit/services/cloudformation/test_deploy_ui.py, tests/unit/services/test_internal.py
In an effort to reduce coupling between generic and aws-specific runtime components #10946, I'm moving the cloudformation deploy UI `/_localstack/cloudformation/deploy` to the cloudformation provider package, and registering it into the internal resources with a hook.
* The `CloudFormationUi` now lives in the cloudformation provider package, and is registered with a runtime hook instead of a static import
=> move cloudformation deploy ui to cloudformation provider

tests/aws/test_serverless.py
We have seen some flakes due to `test_kinesis_stream_handler_deployed (tests.aws.test_serverless.TestServerless)`.
This PR disables this test.
- Skip `test_kinesis_stream_handler_deployed`.
=> fix flaky TestServerless.test_kinesis_stream_handler_deployed

localstack-core/localstack/dns/server.py, tests/unit/test_dns_server.py
A user mentioned that their DNS lookups within their Kubernetes cluster did not work with "simple" names, e.g. looking up a service by its name only - not specifying `.cluster.local` or `.<namespace>.svc.cluster.local` etc.
* Rather than clobbering the entire `/etc/resolv.conf` we only update the `nameservers` fields, leaving the `search` and `ndots` (and others) at their original values
=> Include old resolv.conf contents without nameservers

tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.validation.json, tests/aws/test_notifications.py
Support the ongoing initiative of #9141 and remove remaining unknown markers for sqs related tests.
Side note: the tests in test_notifications.py should probably be moved/deleted, they not seem special or complex enough to warrant its own test class
- remove unknown markers and replace them with validated/needs_fixing
- fix all tests so that they at least work against AWS
=> Validate remaining unknown sqs tests

tests/aws/scenario/kinesis_firehose/test_kinesis_firehose.py
`TestKinesisFirehoseScenario.test_kinesis_firehose_s3` just failed in the main pipeline with the following error:
https://app.circleci.com/pipelines/github/localstack/localstack/25416/workflows/effbcb5f-d331-4bc6-892b-4e976bb395dc/jobs/213380
```
_____________ TestKinesisFirehoseScenario.test_kinesis_firehose_s3 _____________
>> match key: s3
(~) /[0]/Id 'message_id_0' → 'message_id_6' ... (expected → actual)
(~) /[1]/Id 'message_id_1' → 'message_id_7' ... (expected → actual)
(~) /[2]/Id 'message_id_2' → 'message_id_8' ... (expected → actual)
(~) /[3]/Id 'message_id_3' → 'message_id_9' ... (expected → actual)
(~) /[4]/Id 'message_id_4' → 'message_id_0' ... (expected → actual)
(~) /[5]/Id 'message_id_5' → 'message_id_1' ... (expected → actual)
(~) /[6]/Id 'message_id_6' → 'message_id_2' …
```
=> skip flaky TestKinesisFirehoseScenario.test_kinesis_firehose_s3

localstack-core/localstack/services/s3/constants.py, localstack-core/localstack/services/s3/utils.py, localstack-core/localstack/services/s3/v3/models.py, localstack-core/localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
As reported by #10914, we had an issue with Checksum validation for S3. We would rely on the `x-amz-sdk-checksum-algorithm` header, but this one is not considered for `PutObject` and `UploadPart`, AWS does not use it. It is only internally used by the SDK to know it needs to automatically calculate the right `x-amz-checksum-{checksum_algorithm}` value to send along. 
This is only valid for `UploadPart` and `PutObject`. Some other requests like `CreateMultipartUpload` uses only the `ChecksumAlgorithm` parameter with no value (same headers but different purposes). 
The logic was then a bit flawed, because when the client would send a checksum we would not properly consider it if the SDK `x-amz-sdk-checksum-algorithm` was not sent. 
- add multiple tests related to the change:
- add a test …
=> fix Checksum validation and assumptions for S3

localstack-core/localstack/utils/patch.py, tests/unit/utils/test_patch.py
While debugging test failures in #10942, I had a hunch that it had something to do with missing patches, but didn't have the tools to verify. This PR adds these tools.
With the added utilities, I was able to add this simple python snippet after the runtime was ready:
```python
from localstack.utils.patch import Patch
for p in Patch.applied_patches:
print("- {p}"
```
And compare the outputs when running with the old/new runtime:
```
applied patches:
- Patch(function(botocore.waiter:Waiter.wait) -> function(localstack.aws.connect:my_patch), applied=True)
- Patch(function(botocore.parsers:BaseJSONParser._parse_body_as_json) -> function(localstack.aws.client:_patch_botocore_json_parser.<locals>._parse_body_as_json), applied=True)
- Patch(function(moto.core.utils:convert_to_flask_response.__cal …
```
=> add code to debug monkey patches applied through localstack.utils.patch

localstack-core/localstack/aws/patches.py, localstack-core/localstack/services/infra.py, localstack-core/localstack/utils/aws/request_context.py
As part of the effort to reduce coupling of runtime and AWS code #10946, I'm moving some patches that are specific to moto AWS into their own package, and applying them using a hook rather than statically in the infra code. This will also help in #10942.
I left some parts of the `patch_moto_request_handling` because I'd like to separately investigate whether we can simplify or remove it.
* `patch_instance_tracker_meta` is now applied using a hook
* patching the moto config to set `load_aws_managed_policies` is now done in its own patch
=> move aws-specific patches into localstack.aws.patches

localstack-core/localstack/aws/data/sqs-query/2012-11-05/README.md, localstack-core/localstack/aws/data/sqs-query/2012-11-05/service-2.json, localstack-core/localstack/services/sqs/provider.py, tests/aws/services/sqs/test_sqs.py, tests/aws/services/sqs/test_sqs.snapshot.json, tests/aws/services/sqs/test_sqs.validation.json
AWS deprecated the `attribute-names` parameter for `receive-message` operation and changed it to `message-system-attribute-names`. This PR addresses this change.
fixes #10908 
- adds the necessary alias handling in LocalStack
- add tests
- add custom entry to query spec. Our sqs-query spec is not updated automatically. Kudos to @bentsku for going through the query spec code with me! For now this PR adds this change manually, if the solution is too hacky we have to reconsider. /cc @alexrashed
=> SQS: Add MessageSystemAttributeNames for receive-message

.github/workflows/tests-s3-image.yml
As seen here with this manual run to publish the S3 image, we did not checkout the repo in the publish job or download the docker helper script, so we did not have access to it.
https://github.com/localstack/localstack/actions/runs/9382410974/job/25834104662
- ~download the docker helper script in order to be able to execute it~
- checkout the repo in order to have the script available and the git hash
Currently running with the `publish` flag set to `true` in order to test the fix, as I need a new image out to contain all the latest changes.
=> fix S3 image publishing

localstack-core/localstack/services/s3/codec.py, localstack-core/localstack/services/s3/v3/provider.py, tests/aws/services/s3/test_s3.py
Follow up from #10954, a case has not been thought of in this PR, when the checksum would be manually provided as a header and not part of a trailing header with the `aws-chunked` encoding.
This PR fixes this case. 
- update the logic so that if the checksum is provided, do not override it by trying to get the trailing headers that might not be present
- add a test for this use case
_fixes #10914_ (again)
=> fix S3 aws-chunked when checksum is provided

localstack-core/localstack/services/dynamodb/provider.py, tests/aws/services/dynamodb/test_dynamodb.py, tests/aws/services/dynamodb/test_dynamodb.snapshot.json, tests/aws/services/dynamodb/test_dynamodb.validation.json
`test_dynamodb_stream_records_with_update_item` still had the `unknown` marker. 
While AWS validating it, it showed that our implementation was not right: we would send an event if the update operation was not actually updating the record. So I quickly fixed it and add some validations in the test for this use-case.
- validated `test_dynamodb_stream_records_with_update_item`
- changed the logic in `update_item`, `put_item` and `transact_write_items` to not send events if the update operation did not actually update the record
- updated two test for `put_item` and `transact_write_items` validation of behavior
=> validate unknown dynamodb streams test and update behavior

Dockerfile.s3
As reported and fixed in #10969, the S3 image health check had not been migrated following the refactoring/move into `localstack-core` (#10800). The fix is the same as #10894, and is now ported to the S3 image as well.
The original PR could not merge quickly due to the CLA, but in order to unblock the S3 image, we can merge this quicker.
Thanks again to @krishanbhasin-px for the fix.
- pick the health check from the regular localstack Dockerfile
=> fix S3 image healthcheck

tests/aws/services/dynamodb/test_dynamodb.py, tests/aws/services/dynamodb/test_dynamodb.snapshot.json, tests/aws/services/dynamodb/test_dynamodb.validation.json
As seen [in this run](https://app.circleci.com/pipelines/github/localstack/localstack/25500/workflows/dd484d9d-b92e-4fca-92f1-40298a91e645/jobs/214277), the ARM test failed for `test_dynamodb_stream_records_with_update_item`.
This looks like it can be due to parallel request being processed and not leaving the time to DynamoDB to properly ingest the first item (so it does not return it when looking if the object already exists when "updating" the item with the second call). 
This is a race condition, DynamoDB has a somewhat eventual consistency, so maybe this can happen in AWS, or this could be treated as a race condition/bug in LocalStack, but we do not have a real way of preventing it for now. At least the test is more robust now. 
- update the test to make sure the first request has …
=> fix flaky new DDB test

tests/aws/services/apigateway/test_apigateway_integrations.py, tests/aws/services/apigateway/test_apigateway_integrations.snapshot.json, tests/aws/services/apigateway/test_apigateway_integrations.validation.json
It showed in the CI pipeline that a newly validated test of APIGW was flaky around region snapshot transforms, and took longer than before. 
Also showed up in CircleCI: https://app.circleci.com/insights/github/localstack/localstack/workflows/main/tests?branch=master
- updated the test to no longer need an echo server
- replace the hard coded region and account id with fixtures, as it was not important for the test
- modify the snapshot of exception to validate the whole exception value from boto
=> fix flaky APIGW test

localstack-core/localstack/aws/protocol/parser.py, tests/aws/services/apigateway/test_apigateway_sqs.py, tests/aws/services/apigateway/test_apigateway_sqs.snapshot.json, tests/aws/services/apigateway/test_apigateway_sqs.validation.json, tests/unit/aws/protocol/test_parser.py
Fixes #10949 
It appears to be a similar issue to #6091 where sqs accepts both `MessageAttribute.1.Name` and `MessageAttributes.1.Name` when resolving url encoded forms.
In addition to verifying for the presence of `.1.Key` we also need to look for `.1.Name` when deciding if we use `MessageAttribute` or `MessageAttributes` to build the object.
=> Fix sqs urlencoded parsing

localstack-core/localstack/services/cloudformation/engine/validations.py, localstack-core/localstack/services/cloudformation/provider.py, localstack-core/localstack/services/cloudformation/resource_providers/aws_cloudformation_stack.py, tests/aws/services/cloudformation/api/test_validations.py, tests/aws/services/cloudformation/api/test_validations.snapshot.json, tests/aws/services/cloudformation/api/test_validations.validation.json
We currently allow templates that are not allowed on AWS. For example, extra top level fields for resources, or outputs without a `Value` field.
Users deploying these get a false sense of security when deploying CFn stacks. To make LocalStack more useful to users of CloudFormation, we should repliate AWS behaviour and perform template validations.
* Add new `validations` submodule to the CloudFormation service
* Define a "static" template validation type, which is performed on the template only
* Implement two checks
* that the resources blocks are well formed
* that the outputs all have a `Value`, and that it is not statically known to be `null`
=> CFn: add simple template validations

tests/aws/services/apigateway/test_apigateway_api.py, tests/aws/services/apigateway/test_apigateway_basic.py, tests/aws/services/cloudformation/api/test_changesets.py, tests/aws/services/cloudformation/resource_providers/opensearch/test_domain.py, tests/aws/services/cloudformation/resources/test_lambda.py, tests/aws/services/cloudformation/resources/test_legacy.py, tests/aws/services/cloudformation/test_template_engine.py, tests/aws/services/events/test_events_rules.py, tests/aws/services/events/test_events_schedule.py, tests/aws/services/iam/test_iam.py, tests/aws/services/lambda_/test_lambda.py, tests/aws/services/s3/test_s3.py, tests/aws/services/sns/test_sns.py, tests/aws/services/sqs/test_sqs.py, tests/aws/test_terraform.py, tests/aws/test_validate.py, tests/integration/aws/test_app.py, tests/integration/docker_utils/test_docker.py, tests/unit/aws/test_service_router.py
I've noticed we have a lot of tests that are xfailed vs. skipped. I'd argue we actually want to skip all of those, since they can still lead to issues for either the pipeline (e.g. by extending the total duration) or other tests. The whole reason they're xfailed is because there's some issue that we usually don't immediately want to deal with. Often that's issues that lead to timeouts for example where an xfail won't help at all. I'm also not aware that we would've ever actually looked at any XPASS results to "un-xfail" tests.
In favor of simplicity and improving stability of the pipeline, let's fully skip the tests that we know to be flaky/broken.
- All previously xfailed tests are now being skipped and thus not executed at all in our tests. This should provide a minor speed up of the …
=> Refactor all pytest xfail markers to skip instead

localstack-core/localstack/utils/bootstrap.py
Introduce test selection: https://github.com/localstack/localstack/pull/10301
As discussed in our Lambda service owner sync (2024-06-03), we missed some optional dependencies and should split the definitions between community + Pro since merging is now supported.
* Add missing optional dependencies for Lambda destinations
* Add comments to clarify the integration type
* Move Pro services into ext
=> Refine optional Lambda dependencies

localstack-core/localstack/dev/run/configurators.py
When running the `localstack.dev.run` script, the LocalStack community source code is not mounted. This is due to #10800 as it moved the source code locations around. Looks like this particular instance was missed.
* Mount the community code from `localstack/localstack-core/localstack` rather than `localstack/localstack`.
=> Update dev script to mount community code correctly

localstack-core/localstack/services/cloudformation/engine/transformers.py, tests/aws/services/cloudformation/api/test_transformers.py, tests/aws/services/cloudformation/api/test_transformers.snapshot.json, tests/aws/services/cloudformation/api/test_transformers.validation.json
Based on a reported issue from a user where they loaded a stepfunction statemachine definition through the `AWS::Include` macro from s3 which lead to the RoleArn missing. 
The issue was that the transformation replaced the whole level of the current object in the iteration and not just the one particular key it's at.
- The `Fn::Transform` can now be used with additional keys at the same object level as the intrinsic function.
=> Fix CloudFormation Fn::Transform replacing unintended values

tests/aws/test_multiregion.py, tests/aws/test_multiregion.validation.json
As an initiative to remove all `markers.aws.unknown` markers from the tests, this PR handles the ones concerning multi region tests.
This PR: 
- updates the marker to `validated` if it passes against AWS
- updates the marker to `needs_fixing` if it didn't pass against AWS
=> remove unknown markers in test_multiregion

.github/workflows/asf-updates.yml, pyproject.toml
https://github.com/localstack/localstack/pull/10537 extended the pinning of dependencies performed in the `asf-updates.yaml` action - from just `botocore` to also include the transitive pins `boto3`, `boto3-stubs`, as well as `awscli` - in order to reduce the time it takes to perform the backtracking.
However, for the AWS CLI the versioning is not aligned with `botocore`, which is why we introduced a hacky way to determine the AWS CLI version. This hacky approach now broke due to a minor release, as we can see [in the latest scheduled run of the action](https://github.com/localstack/localstack/actions/runs/9442735748):
```
ERROR: Cannot install awscli==1.32.122 because these package versions have conflicting dependencies.
File …
```
=> fix asf update action by avoiding aws cli pin

tests/aws/services/lambda_/test_lambda.py, tests/aws/services/lambda_/test_lambda.snapshot.json
As an initiative to remove all `markers.aws.unknown` markers from the tests, this PR handles the ones concerning cross account test in lambda.
This PR updates the marker to `needs_fixing` for `test_cross_account_access`
=> remove unknown markers in cross accounts test in lambda

localstack-core/localstack/services/lambda_/event_source_listeners/adapters.py
Fix for successfully invoked lambdas not deleting source SQS message if the lambda does not have a return value
To resolve the issue I have been having using LocalStack with .net lambdas https://github.com/localstack/localstack/issues/10307
It checks if the lambda returned a value before trying to parse it as json
Please excuse the lack of tests included with this, I am not a python developer.
To manually test:
* Create a new .net AWS lambda using the `AWS Lambda Project (.NET Core - C#)` template from the Amazon.Lambda.Templates. This will create a function handler without any return value.
* Package and deploy the sample lambda
* Associate with SQS/SNS
* Send a test message
Before this change the message would not be deleted
See the steps to reproduce in …
=> Fix handling None payload in Lambda Event Source Mapping

tests/aws/services/es/test_es.py
ElasticSearch tests are very flaky recently in the CI. For example:
Flaky runs:
* Silvio: commented [here](https://localstack-cloud.slack.com/archives/C06PA09NU3U/p1718026531370819?thread_ts=1718026230.448389&cid=C06PA09NU3U) in Slack
* Joel: https://github.com/localstack/localstack/actions/runs/9450891131/job/26030567990
Skip flaky tests for ElasticSearch following testing guideline [R01](https://github.com/localstack/localstack/tree/master/docs/testing#r01).
Should we be more selective in skipping the tests? I guess it's all the ones with skip_offline, hence `test_list_versions`, `test_get_compatible_versions`, and `test_update_domain_config` should be fine.
Silvio's run:
```
../localstack/tests/aws/services/es/test_es.py::TestElasticsearchProvider::test_create_domain RERUN [ 54%] …
```
=> Skip flaky ElasticSearch tests

localstack-core/localstack/services/stepfunctions/provider.py, tests/aws/services/stepfunctions/v2/test_sfn_api.py, tests/aws/services/stepfunctions/v2/test_sfn_api.snapshot.json, tests/aws/services/stepfunctions/v2/test_sfn_api.validation.json
For Step Functions, we can create a state machine or state machine execution that contains a period (.) in the name, but
trying to "describe" that state machine (or execution) incorrectly gives an`InvalidArn` exception. See #10976.
Validation code for state machine ARNs and state machine execution ARNs now allows for periods (.) in the name. This matches AWS behaviour.
Unit tests were added.
=> Step Functions: Allow describing ARNs that contain periods

localstack-core/localstack/utils/container_utils/container_client.py, tests/integration/docker_utils/test_docker.py
While revisting the features of the `--env-file` parameter for the docker CLI, I noticed we did not include the support for placeholders (variable names without an `=`) in #10880.
To achieve parity with the docker CLI client, I implemented the missing feature + tests.
* An env file like this:
```
TEST
```
with the `TEST` environment variable set inside the container, should correctly be passed (with that value) into the Lambda container (for `LAMBDA_DOCKER_FLAGS`).
=> Add support for placeholder values in env-file flag for docker flags

localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service.py, localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_lambda.py, tests/aws/services/stepfunctions/templates/services/services_templates.py, tests/aws/services/stepfunctions/templates/services/statemachines/aws_sdk_s3_put_object.json5, tests/aws/services/stepfunctions/v2/services/test_aws_sdk_task_service.py, tests/aws/services/stepfunctions/v2/services/test_aws_sdk_task_service.snapshot.json, tests/aws/services/stepfunctions/v2/services/test_aws_sdk_task_service.validation.json
The SFN interpreter sometimes fails to implicitly normalise `Parameter` values to match the request shape of the target api action. This lead to errors when performing `putObject` requests to `s3` for which the body was not of string type. This PR addresses such issue by normalising blob target shapes. This issue was highlighted in a [followup report](https://github.com/localstack/localstack/issues/10787#issuecomment-2134740148) in issue https://github.com/localstack/localstack/issues/10787.
- Extracted upload value normalisation logic
- Added normalisation of `blob` Shapes
- Added related snapshot tests
=> [SFN] Normalise Upload Values

tests/aws/services/support/test_support.py
As part of the effort to validate tests, I've tried to run the AWS Support test against AWS.
It seems you need a Premium account to use the Support API. I had rewritten the test to be easily snapshot-able. 
- mark the test a `needs_fixing` as you cannot run them against AWS without a premium plan. Debatable if this is `needs_fixing` or `only_localstack` though, technically it's not by design, but also needs something specific.
=> check AWS Support validation status

tests/aws/services/scheduler/test_scheduler.py, tests/aws/services/scheduler/test_scheduler.validation.json, tests/aws/services/swf/test_swf.py
As those 2 services were small, I've done PR for 2:
- Scheduler test was easy to validate as it does basically nothing
- SWF is more complex, I've added comments to it but the test does not cleanup, does not use fixtures and will most probably need rework
- add markers
=> validate scheduler test and check SWF validation

localstack-core/localstack/services/stepfunctions/asl/eval/event/logging.py
Currently the CloudWatch Logs integration for StepFunctions does not support Multi-account and Multi-region setups. This PR aims to address this issue by connecting to Cloud Watch Logs with the supplied account and region.
These changes are green in the Multi Account and Multi Region CI.
Build the Cloud Watch Logs Client using the AWS account and region provided in the Cloud Watch Logs group arn provided on creation.
=> [SFN] Multi-account and Multi-region Logging

localstack-core/localstack/cli/localstack.py, localstack-core/localstack/utils/bootstrap.py, tests/cli/test_cli.py
With recent Docker Desktop changes, port 53 is not exposable on the host from docker any more, as the port is already taken. Due to the specific error circumstances, our check whether or not we can expose it does not work any more.
As a fix, this PR will remove the automatic binding of the DNS port to the host, as this a rarely used feature (presumably), since it requires additional configuration to make proper use of it (like setting `DNS_SERVER` to avoid loops in the resolution).
This PR introduces a new flag `--host-dns` instead, which will expose the port to the host.
The flag has two shortcomings we should discuss:
1. Per default, we bind the host port to the same address as the `GATEWAY_LISTEN` sets, so per default 127.0.0.1. It will not be seperately configureable, you can only …
=> Add new option to manually expose the DNS port to the host, remove binding by default

localstack-core/localstack/testing/aws/util.py, localstack-core/localstack/testing/config.py, tests/aws/services/secretsmanager/test_secretsmanager.validation.json, tests/conftest.py
Currently, we only allow setting credentials for the secondary account test fixtures using the `SECONDARY_TEST_AWS_ACCESS_KEY_ID` variables and so forth.
This can be quite cumbersome, especially when you want to take advantage of temporary credentials using the AWS IAM Identity Center.
To mitigate this, I refactored our client fixtures a tad, so we can now use `SECONDARY_TEST_AWS_PROFILE` to set an aws profile, if the tests are run against AWS. If it runs against LS, nothing changes to the current behavior, only that credentials are now set on the session, and not on the clients anymore.
Also, the secondary clients now use a different session, but the impact of that should be negligable.
* You can now use `SECONDARY_TEST_AWS_PROFILE` to set the profile used for your secondary aws account …
=> Allow secondary client fixtures to take credentials from an aws profile

localstack-core/localstack/services/infra.py, localstack-core/localstack/utils/bootstrap.py
I was asked about the different meaning of localstack version/commit/image SHAs and coincidentally noticed that the digests we were showing were actually the local image ids and not the digest on docker hub that we can actually pull for reproducing the issue.
- The diagnose endpoint now also outputs the image sha that can be used to pull from docker hub via `docker pull localstack/localstack@sha256:....`
- On startup the value of `LocalStack Docker image sha` is now the actual digest that can be pulled (see above). This was a bit unfortunate since we now also refer to this in our GitHub issue template. If there's no manifest yet, it returns the fallback value `Unavailable`
@dfangl I noticed that fortunately the docker client works correctly when called with `image_details = …
=> Fix detection of docker image digest for diagnostic purposes

localstack-core/localstack/aws/components.py, localstack-core/localstack/config.py, localstack-core/localstack/http/duplex_socket.py, localstack-core/localstack/runtime/__init__.py, localstack-core/localstack/runtime/components.py, localstack-core/localstack/runtime/current.py, localstack-core/localstack/runtime/events.py, localstack-core/localstack/runtime/hooks.py, localstack-core/localstack/runtime/legacy.py, localstack-core/localstack/runtime/main.py, localstack-core/localstack/runtime/patches.py, localstack-core/localstack/runtime/runtime.py, localstack-core/localstack/runtime/server/__init__.py, localstack-core/localstack/runtime/server/core.py, localstack-core/localstack/runtime/server/hypercorn.py, localstack-core/localstack/runtime/server/plugins.py, localstack-core/localstack/runtime/server/twisted.py, localstack-core/localstack/services/infra.py, localstack-core/localstack/services/internal.py, localstack-core/localstack/testing/pytest/in_memory_localstack.py
This is part of the effort to generalize certain aspects of the codebase to make them more re-usable (see #10946). One concept that was difficult to re-use was `infra.py`, which is responsible for starting what we now call the localstack _Runtime_. The reason is that it imports all sorts of aws-specific code.
The Runtime is roughly responsible for
- running runtime lifecycle hooks
- managing the localstack filesystem (creating directories and cleaning up afterwards)
- clean up thread and process pools
- serving the main Gateway
Another annoying thing with the previous runtime is that the server (either hypercorn or twisted), couldn't properly register signal handlers, such as a code reloader, because it can only do that from the main thread, and we were starting the server in a separate …
=> implement new runtime framework for bootstrapping localstack

localstack-core/localstack/runtime/runtime.py
tbd
- Spawns the runtime shutdown in a new thread instead of the main thread
=> Fix runtime shutdown when called triggered via signal handlers

localstack-core/localstack/services/lambda_/urlrouter.py, requirements-base-runtime.txt, requirements-dev.txt, requirements-runtime.txt, requirements-test.txt, requirements-typehint.txt, tests/aws/services/lambda_/test_lambda.py, tests/aws/services/lambda_/test_lambda.snapshot.json, tests/aws/services/lambda_/test_lambda.validation.json
This PR updates to rolo to include https://github.com/localstack/rolo/pull/13
While writing a test for APIGW upstream, I've realized Lambda URL were parsing the form and just forwarding an empty body instead of the raw body containing the form data, so I've fixed it as well, as it feels logical to fix in the same PR where we update rolo to include a fix for form parsing
- update rolo to `0.5.1`
- add a fix for lambda URL, calling `restore_payload` to restore the form/multipart part of the request
- add an AWS validate test for it
=> update rolo and fix lambda url form parsing

tests/bootstrap/test_localstack_container_server.py
With the latest refactoring of the runtime (https://github.com/localstack/localstack/pull/10942) we had some issues with the restart handling (which can be triggered via the health endpoint).
This issue was fixed in https://github.com/localstack/localstack/pull/11018.
This PR aims at extending an existing bootstrap lifecycle test to also include the restart.
- Extends `tests.bootstrap.test_localstack_container_server.TestLocalstackContainerServer.test_lifecycle` to send a restart command and check if the restart in the container is working correctly.
=> extend bootstrap lifecycle test to include restarts

localstack-core/localstack/services/dynamodb/resource_providers/aws_dynamodb_globaltable.py, localstack-core/localstack/testing/snapshots/transformer_utility.py, tests/aws/cdk_templates/TestTableV2Stream/TableV2StreamStack.json, tests/aws/services/dynamodb/test_dynamodb.py, tests/aws/services/dynamodbstreams/test_dynamodb_streams.py, tests/aws/services/dynamodbstreams/test_dynamodb_streams.snapshot.json, tests/aws/services/dynamodbstreams/test_dynamodb_streams.validation.json
LocalStack is not able to deploy a [TableV2 construct](https://aws.amazon.com/blogs/devops/a-new-and-improved-aws-cdk-construct-for-amazon-dynamodb-tables/) with `StreamSpecification` enabled.
A sample was provided by a user and is reflected in the implemented test.
Specifying the stream view type in the new construct should be enough to enable the stream (while LocalStack was failing with a missing required field).
- Improve provider for `AWS::DynamoDB::GlobalTable` to account for `StreamSpecification`;
- Write a validated CDK test.
=> Fix TableV2 construct with streaming enabled

tests/aws/services/route53/test_route53.py, tests/aws/services/route53/test_route53.validation.json
As an initiative to validate tests and remove all `markers.aws.unknown` markers, this PR handles the ones concerning the route53 integration tests. 
This PR adds changes for the tests to work against AWS and thereby update the marker to `validated` for: 
- `tests/aws/services/route53/test_route53.py::TestRoute53::test_crud_health_check`
- `tests/aws/services/route53/test_route53.py::TestRoute53::test_associate_vpc_with_hosted_zone`
- `tests/aws/services/route53/test_route53.py::TestRoute53::test_reusable_delegation_sets`
=> validate route53 integration tests against AWS

localstack-core/localstack/services/secretsmanager/provider.py, tests/aws/services/secretsmanager/test_secretsmanager.py, tests/aws/services/secretsmanager/test_secretsmanager.snapshot.json, tests/aws/services/secretsmanager/test_secretsmanager.validation.json
This PR aims to fix issue described in https://github.com/localstack/localstack/issues/10621. As per the current implementation, localstack was not catching `ResourceNotFound` exception from moto.
- Adds exception handling for `GetSecretValue`
- Added AWS validated test cases
=> fixed error handling in GetSecretValue in secretsmanager

bin/release-helper.sh
In the release commit, which is created by `bin/release-helper.sh git-commit-release <version>`, the glob used to find `version.py` in this and dependent repositories, does not work anymore with the new source layout introduced in #10800. See the [release commit for 3.5.0](https://github.com/localstack/localstack/commit/54edb407df341515a6348e751fa20f4c41732b7d) for the result of this error
Since everything is now a level deeper, we need to change the glob `*/version.py` to something else. `**/version.py` will be the more robust way going forward. This requires a small change in the way that we add files to the commit. Instead of checking if a file exists and then staging it, we stage it immediately now and print an error if it does not exist. This is because `[ -e **/version.py ]` …
=> Fix version.py file glob for release commit

localstack-core/localstack/services/apigateway/integration.py, tests/aws/services/apigateway/test_apigateway_basic.py, tests/aws/services/apigateway/test_apigateway_s3.py, tests/aws/services/apigateway/test_apigateway_s3.snapshot.json, tests/aws/services/apigateway/test_apigateway_s3.validation.json
fixes #10886 
Basic implementation of PUT and DELETE actions for apigw s3 integration.
controls GET, PUT and DELETE operation over s3 objects
A more transparent solution where we could mostly proxy the requests would be better and allow for all actions, but we can tackle that as part of the rewrite which should make the implementation along with the s3 xml  response passthrough  easier.
- We are still returning errors instead of the XML object when performing POST or attempting to get a non-existent object
- We are not mapping method from `HttpMethod` to `IntegrationHttpMethod`. It appears we were also not doing it for http integration. The rewrite should allow us to toggle the extra added test when we get there!
=> Apigw improve s3 integration support

.github/workflows/tests-bin.yml, bin/docker-helper.sh, tests/bin/README.md, tests/bin/test.docker-helper.bats
When switching to the acceptance tests only in the future, the default tag for pushing a new release will be `dev`, which means that releasing a new version won't also upgrade the latest tag. However, there is an implicit expectation that the latest tag at the point of releasing a new version should be the same as the new version. 
This PR forces a push of the latest tag when a new version is pushed, regardless of what the default tag is. 
It also adds instructions on how to use BATS since not everyone might be familiar with it.
It also switches on the Helper tests for changes in the helper test workflow file and changes in the tests themselves. This enables test-driven development, where the tests are changed before the helper script.
The newly added BATS test checks whether a latest tag …
=> Push latest image tag with version tags, regardless of default tag

localstack-core/localstack/services/cloudformation/engine/validations.py, localstack-core/localstack/services/cloudformation/provider.py, tests/aws/services/cloudformation/api/test_transformers.py, tests/aws/services/cloudformation/api/test_transformers.validation.json, tests/aws/services/cloudformation/api/test_validations.py
A regression was reported on [Discuss ](https://discuss.localstack.cloud/t/validation-error-when-creating-stack-with-cloudformation/943) where not having a `Type` field in the Resource section leads to the following validation error now:
```
An error occurred (ValidationError) when calling the CreateChangeSet operation: Template format error: [/Resources/NotificationsTable] Every Resources object must contain a Type member.
```
This is generally correct behavior but not in combination with transformations since we don't know which fields will be available when processed before doing the actual processing/transformation.
Changing the order to validate only after processing happened still had issues since we currently modify the template by e.g. adding a `LogicalResourceId` field which then …
=> Disable CloudFormation template validation

localstack-core/localstack/utils/container_utils/container_client.py, tests/unit/test_dockerclient.py
Per request, we want to support environment files as supported in docker-compose as well as env-files for the docker cli.
They have a quite different feature set, as docker compose allows stripping quotes, end of line comments, and support referencing other variables in a bash-expansion style syntax.
This PR will add, at least to the docker SDK client used within the container, a flag called `--compose-env-file`, which will support these environment files.
It uses the python `dotenv` library for this usecase.
* Support for `--compose-env-file`, which will parse the env file similar to docker compose (which uses `godotenv`)
=> Add *_DOCKER_FLAGS option to support docker compose-style environment files

localstack-core/localstack/services/apigateway/resource_providers/aws_apigateway_deployment.py, tests/aws/services/cloudformation/resources/test_apigateway.snapshot.json, tests/aws/services/cloudformation/resources/test_apigateway.validation.json, tests/aws/templates/apigateway-url-output.yaml, tests/aws/templates/apigateway_integration_from_s3.yml
The resource provider for AWS::ApiGateway::Deployment fails to deploy when the StageDescription attribute is define due to a missing conversion. Evidence shown in in #11019
- Add conversion from dict to a json string of the attribute in the Create method for the resource.
- extended existing deployment test
=> fix for ApiGW resource provider

localstack-core/localstack/services/apigateway/next_gen/execute_api/gateway_response.py, tests/unit/test_apigateway.py
Base python exception to handle gateway integration error.
Each exception is subclassed from one of the Default response. It will allow us to quickly check if `error.default_type` is a configured `GatewayResponse` by the user when building the response in the exception handler
=> apigw create python exceptions for gateway response

localstack-core/localstack/services/events/event_bus.py, localstack-core/localstack/services/events/models.py, localstack-core/localstack/services/events/provider.py, tests/aws/services/events/test_events.py, tests/aws/services/events/test_events.snapshot.json, tests/aws/services/events/test_events.validation.json
`put_events` is the main method to directly put events to an event bus, it takes as input argument a list of events containing `source` `detail-type` `detail` and `bus-name` but it is limited to a maximum of 10 events at a time.
In addition, AWS introduced some changes to default parameters for event buses, in particular creation time and update time, these changes are also incorporated here to get updated snapshot tests passing.
Add error handling for `put_events` number of entries exceeding 10
Pars entries and return correctly parsed events
=> Feature: EventBridge v2: Add test put events limit to 10 messages

localstack-core/localstack/services/s3/provider.py, tests/aws/services/s3/test_s3.py, tests/aws/services/s3/test_s3.snapshot.json, tests/aws/services/s3/test_s3.validation.json
As reported in #11037, we've had an issue with empty `Tagging` when using the `TaggingDirective` `REPLACE` with `CopyObject`. This was because we would set the result of `if tagging := request.get("Tagging"):` to the tags, which would be `None`. The fix would be to conditionally set the data, but in that case we would need to pop the previous value, or add `tagging or {}` which will set a dict if the value is `None`. 
- add a regression test for this particular use case
- add the fix in the provider
_fixes #11037_
=> fix TaggingDirective REPLACE for CopyObject

localstack-core/localstack/logging/format.py, tests/unit/logging_/test_format.py
With #10858, I introduced a replacement for large binary payloads when logging HTTP request which do not directly access a service (e.g. while proxying to a backend), to avoid performance degradations when pushing big ECR blobs.
However, I made a mistake by avoiding to LOG the input altogether if the payload is not `bytes`, by not passing the request input shape to the logging formatter at all.
So, all request payloads (other than bytes across a threshold) are currently logged as `None`.
Broken request logging:
```
2024-06-19T17:23:04.469  INFO --- [et.reactor-0] localstack.request.aws     : AWS lambda.ListFunctions => 200; 000000000000/us-east-1; ListFunctionsRequest(None, headers={'Host': 'localhost:4566', ... stripped for readability}); ListFunctionsResponse(None, …
```
=> Fix payload not being shown in trace logging

localstack-core/localstack/aws/app.py, localstack-core/localstack/http/trace.py
More efforts towards #10946. I wanted to debug something in a different emulator using `DEBUG_HANDLER_CHAIN`, but couldn't re-use it because of the coupling to the AWS request context.
This PR generalizes the `TracingHandlerChain` so it can be re-used outside AWS. The biggest change was just to create a loop over `context.__dict__` rather than hard-coding each attribute.
I also removed the `Handler` and `ExceptionHandler` from the list of implemented classes, since in rolo they are Protocols, and you shouldn't inherit from protocol classes unless you are creating other protocols.
* The `TracingHandlerChain` is now generalized and free of AWS concepts
* The `TracingHandlerChain` now lives in `localstack.http` instead of `localstack.aws`
* check out the PR and run ls with …
=> generalize tracing for gateway and handler chain

localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/__init__.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/parse.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/resource_router.py, tests/unit/services/apigateway/test_handler_request.py
This PR is currently target #11051.
Follow up from #11051, looking at the `op_router` code, I realized the format of the paths for our specs were the same as API Gateway, so much that we could reuse a simplified version of the `RestServiceOperationRouter` (we do not need to match on required headers and query string parameters, so that makes it much, much simpler). 
All the logic to already create the rules were there, so I've re-used most of the code.
Only issue is that some of the code is private, I'm not sure how to re-architecture to make it re-usable, maybe in some `routing` package? \cc @alexrashed 
- migrate the previous legacy routing and path parameters extraction to the Werkzeug routing
=> migrating NG APIGW routing to Werkzeug routing

localstack-core/localstack/runtime/main.py
With #10942, we switched to the new runtime framework.
However, with that change, we stopped logging `LocalStackExit` errors, which especially were used during license activation. This leads to the activation error message not being logged correctly (e.g. if both `LOCALSTACK_API_KEY` and `LOCALSTACK_AUTH_TOKEN` are set).
To avoid that, I reintroduced printing the error before exiting.
* LocalStack prints a LocalStackExit error before exiting in the new runtime, for example during activation
=> Print LocalStackExitErrors in the new runtime

tests/unit/services/apigateway/test_handler_exception.py
Following #11062 and #11051, we've had hidden merge conflicts, the signature of one of the class changed, weirdly the CI run was green even though the other PR had been merge quite much earlier. 
Not exactly sure why it happened, ~maybe some caching regarding unit tests~? 
edit: ah, I think this is because CircleCI checks out the repo on the branch, whereas GitHub Actions adds your PR on top of master, which would have caught this. 
- fix the usage of `RestApiDeployment` to match the signature
=> fix NG APIGW unit tests usage of RestApiDeployment

localstack-core/localstack/services/apigateway/resource_providers/aws_apigateway_method.py, tests/aws/services/cloudformation/resources/test_apigateway.py, tests/aws/services/cloudformation/resources/test_apigateway.snapshot.json, tests/aws/services/cloudformation/resources/test_apigateway.validation.json, tests/aws/templates/template35.yaml
We got a report in our Slack channel regarding a type cast error for the `selectionPattern` field for `APIGW::Method` resource. 
After taking a look and updating one of our test to validate the fix, I've realized we've had a few parity issues and snapshot skips. I've also fixed them in the meantime 😄 
- add type casting of `selectionPattern`
- remove default value of `{}` for multiple fields, which should not be sent at all if they are not set. AWS can accept empty dicts from them, so we have to check against `None` value directly
=> improve CFN APIGW Method parity

localstack-core/localstack/aws/protocol/op_router.py, localstack-core/localstack/aws/protocol/routing.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/resource_router.py
Follow up from #11057 and this comment: https://github.com/localstack/localstack/pull/11057#pullrequestreview-2130154194
I've pulled everything not directly related to service-operation-routing out of `op_router`, in order to be able to use them in API Gateway resource routing as well. 
- pull some utilities outside of `op_router.py` into `routing.py` and update the imports
=> split routing utilities not related to service operation routing out of op_router.py

localstack-core/localstack/aws/protocol/parser.py, tests/aws/services/kinesis/test_kinesis.py, tests/aws/services/kinesis/test_kinesis.snapshot.json, tests/aws/services/kinesis/test_kinesis.validation.json, tests/unit/aws/protocol/test_parser.py, tests/unit/aws/protocol/test_parser.snapshot.json, tests/unit/aws/protocol/test_parser.validation.json
This PR fixes the Kinesis request parsing in ASF for timestamp fields.
Where JSON timestamps are normal unix timestamps (where milliseconds can be defined via floating point), for CBOR the timestamp contains the milliseconds (so it's basically JSON * 1000).
#6791 fixed this issue for the serialier, but it was overlooked that the same format used for responses also needs to be considered when parsing incoming requests from clients.
Fixes #10037.
- Uses `unixtimestampmillis` for CBOR timestamp request fields when parsing.
- The integration tests are unfortunately not AWS validated because `botocore` does not yet support CBOR requests to AWS.
- However, the issue reported in #10037 was verified, and the fix and test directly address this issue.
=> fix kinesis cbor timestamp parsing

localstack-core/localstack/services/lambda_/invocation/execution_environment.py
The Lambda RIE logs are extremely verbose and customers miss their application errors within these verbose logs.
This issue was also raised by the SaaS team upon sharing their dogfooding experience with Lambda.
* `DEBUG=1` does not affect the Lambda RIE log level anymore (using default `warn` level)
* `LS_LOG=trace|trace-internal` sets the Lambda RIE log level to `info` (rather than `debug` before)
It is always possible to explicitly configure the Lambda RIE log level using: `LAMBDA_DOCKER_FLAGS=-e LOCALSTACK_INIT_LOG_LEVEL=debug` 
Options: trace, debug, info, warn (default), error, fatal, panic
The RIE and X-Ray logs are currently mixed and log level configuration coupled as defined in `main.go` of our RIE.
Using the test case `aws.services.lambda_.test_lambda.TestLambdaBehavior.test_runt …
=> Reduce Lambda RIE log level

localstack-core/localstack/aws/app.py, localstack-core/localstack/aws/handlers/__init__.py, localstack-core/localstack/aws/handlers/legacy.py, localstack-core/localstack/services/apigateway/helpers.py, localstack-core/localstack/services/apigateway/router_asf.py, localstack-core/localstack/utils/aws/request_context.py
We've been meaning too remove the `THREAD_LOCAL` usage since a long time, and we could finally do so while working on the refactor of APIGW. 
This did not have any use anymore, and it relied on setting additional data in a threadlocal, but thanks to the awesome work of @viren-nadkarni, nothing uses `aws_stack.get_region()` anymore, so we can be sure nothing is accessing/reading those values anymore. 
I really want to emphasis that this is only possible thanks to the relentless work of Viren 😄 
- remove `THREAD_LOCAL` and its usages across the codebase
=> remove THREAD_LOCAL usage

localstack-core/localstack/services/lambda_/event_source_listeners/kinesis_event_source_listener.py, tests/aws/services/lambda_/test_lambda_integration_kinesis.py, tests/aws/services/lambda_/test_lambda_integration_kinesis.snapshot.json, tests/aws/services/lambda_/test_lambda_integration_kinesis.validation.json
This PR fixes a minor parity issue for AWS Lambda Kinesis Data Streams event source mappings.
As per [docs](https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html), the event payload should have a `kinesisSchemaVersion` key.
Few libraries (e.g., AWS Java SDK) seem to expect this value.
- adding `kinesisSchemaVersion` to the event payload;
- removing snapshot skip from our tests;
=> parity: kinesis event payload

localstack-core/localstack/dev/run/configurators.py
Following source code refactor in -ext initiated by #10860, the command `python -m localstack.dev.run --mount-source-code` was failing to mount -pro source code as the location change. This is a very useful command allowing for running localstack in docker mode with local code mounted. 
Point the pro source code to the new code directory.
=> update pro source code location

.github/workflows/validate-codeowners.yml, CODEOWNERS
Codeowners can get outdated quickly when refactoring code, or shuffling around modules.
This PR aims to introduce a safety net which warns a user about changes in PRs that would introduce such issues to the Codeowners file 
This PR adds a small workflow to our suite of actions, which on each PR raised will verify whether the codeowners file is still valid.
In the checks of this PR you should already see the workflow with the name `LocalStack - Validate Codeowners` show up.
It's currently red, as the codeowners file has some issues.
```
[err] line 83: "/tests/unit/utils/testing/" does not match any files in repository
```
Should we just remove this line?
=> add codeowners validation to gh actions

localstack-core/localstack/services/cloudformation/scaffolding/__main__.py
Recent changes when migrating to a src layout in both community/pro have broken the resource provider generation. This PR fixes this by adapting the paths to their new nesting structure.
- CFn resource provider scaffolding script should now work correctly again with both pro and community.
- run `python -m localstack.services.cloudformation.scaffolding generate -w -r "AWS::<svc>::<model>"` to test community generation
- run `python -m localstack.services.cloudformation.scaffolding generate -w -r --pro "AWS::<svc>::<model>"` to test pro generation
=> Adapt CFn resource scaffolding script to new src layout

localstack-core/localstack/dev/kubernetes/__main__.py
Recent changes when migrating to a src layout in pro have broken the `localstack.dev.kubernetes` CLI. This PR fixes this by adapting the path to the new nesting structure.
- Fixed mounting of pro code into k8s cluster via `localstack.dev.kubernetes` script.
- Fixed mounting of community entrypoints
- `python -m localstack.dev.kubernetes --pro` (and check the volume mount paths in the output)
=> Adapt localstack.dev.kubernetes script to new src layout

localstack-core/localstack/aws/patches.py, localstack-core/localstack/services/moto.py, localstack-core/localstack/utils/aws/aws_responses.py, localstack-core/localstack/utils/aws/request_context.py, pyproject.toml, requirements-base-runtime.txt, requirements-dev.txt, requirements-runtime.txt, requirements-test.txt, requirements-typehint.txt
We don't use the moto server in a long time, and we also don't use flask to serve anything in LocalStack itself anymore for quite a while.
Now that we [finally got rid of the thread local](https://github.com/localstack/localstack/pull/11069) (thanks @bentsku!) access to the flask request context, we can just remove the dependency completely.
- Removes any remaining references to `flask`:
- A weird indirection of creating a `requests` response via a `flask` response (might just have been a leftover from a previous cleanup?)
- The patching of the moto server (since we don't use it anymore this patch should not be necessary anyways?)
- Updates the dependency pins after removing the dependency definition from the `pyproject.toml`
- If all our pipelines are green, we should be good to go 😄 
- …
=> remove flask

localstack-core/localstack/services/apigateway/models.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/context.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/gateway_exception.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/resource_router.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/helpers.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/moto_helpers.py, tests/unit/services/apigateway/test_handler_exception.py, tests/unit/services/apigateway/test_handler_request.py
During a pair programmation session with @cloutierMat, he emphasized the need to get decoupled from Moto very early, so that we would not be polluted nor have a lot of tech debt across the new invocation logic. 
We then removed the `MotoRestAPI` usage in our deployment/invocation, and only return the APIGW `Resources` needed for the invocation.
If we realize we need more things from Moto, we will need to pull them out of it in  `reeze_rest_api` and add fields to the `MergedRestApi` class.
Once we tackle the removal and split brain situation of Moto from APIGW, we can remove the `MergedRestApi` class and only use the container from our store. 
This will also help us during testing, as we won't need to setup Moto resources like currently done in …
=> refactor Moto out of APIGW next-gen invocation logic

localstack-core/localstack/testing/pytest/marking.py, tests/aws/scenario/bookstore/test_bookstore.py, tests/aws/services/apigateway/test_apigateway_lambda_cfn.py
The acceptance tests are used as proper acceptance tests now in the main pipeline (#11049). However, their marker still indicates a beta status. 
This PR removes the `_beta` suffix from the acceptance test marker.
=> Mark acceptance test marker as GA

localstack-core/localstack/services/apigateway/helpers.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/method_request.py, tests/unit/services/apigateway/test_handler_method_request.py
This PR ports the functionality from `apigateway/invocations.py:RequestValidator` to a method request handler.
The old invocation process wasn't routing the request before validation so some "passthrough" were required when no matching method were found. Cleaning up some of that code will make it cleaner and more obvious as to what is happening.
We can also start raising error from the gateway responses to be prepared for it's future implmentation.
- updated the method request handler to validate the request parameters and the body.
- removed passthrough when no methods exists
- raise proper gateway exceptions
- added tests porting from the previous unit tests of the `RequestValidator` to ensure the functionality hasn't regressed.
- added a debug statement when the `ModelResolver` fails …
=> Apigw NG create method request handler

tests/aws/services/dynamodb/test_dynamodb.py, tests/aws/services/dynamodb/test_dynamodb.snapshot.json, tests/aws/services/dynamodb/test_dynamodb.validation.json
Following up another test failure in https://app.circleci.com/pipelines/github/localstack/localstack/26140/workflows/8cc6ef1b-70fd-4e35-bea3-77ff3637a2db/jobs/221443/tests
And follow up from #10973 which was unsuccessful at fixing the test as it didn't tackle the proper origin of the problem. 
I've tried to harden the test to be more resilient. It seems the flake came from the fact that we would try to fetch the records, and if there weren't enough in the kinesis stream, we would fetch again and extend the already existing list of records with newly fetched records, leading to duplicate items (we can see the two`INSERT` events have the same `SequenceNumber`
- update the logic to fetch the records from DynamoDB Streams
\cc @alexrashed
=> harden test_dynamodb_stream_records_with_update_item

localstack-core/localstack/aws/protocol/serializer.py, localstack-core/localstack/services/apigateway/helpers.py, localstack-core/localstack/utils/aws/aws_responses.py, localstack-core/localstack/utils/aws/queries.py
Looking at #11090, I saw some dead code related to the legacy S3 provider(true legacy, the legacy v1 and not v2 😄)
This PR removes it the dead code, and move a bit of code around related to APIGW as it is only used there. 
- remove dead code related to S3 select
- move one function to APIGW helpers
- remove a comment related to the dead code
=> remove dead code related to S3 v1 (pre-ASF)

localstack-core/localstack/runtime/main.py
Follow-up to a minor regression from https://github.com/localstack/localstack/pull/10942
Equivalent to https://github.com/localstack/localstack/pull/10951 but for the code path of the new runtime startup now.
- On startup the value of LocalStack Docker image sha is now again the actual digest that can be pulled from the registry.
=> Fix docker image digest in startup runtime information for new runtime

localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/__init__.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/core.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/http.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/mock.py
This is first iteration to introduce the different REST API integrations.
The first idea was to use Plugins for each different `IntegrationType`, which allows easy discovery and to extend the list of integration in a transparent way.
However, while working on the `AWS` integration type, it became apparent that we could pull off all AWS services with a single integration, with no need to subclass like the current code does (we have `KinesisIntegration`, `S3Integration`...). But it happens that the `AWS` integration has the same logic for every service, and we will work to make it possible in the new iteration. 
- create the different Integration types with their base class and some documentation
=> add empty integrations for NG APIGW

.circleci/config.yml, .github/workflows/tests-pro-integration.yml
This PR is a follow up to #9045, which introduced acceptance tests to LocalStack! 
This PR changes our integration testing strategy such that:
- On (merge) pushes to `master` we do not run the whole integration test suite anymore.
- We really only run the preflight checks (including unit tests) and our fine, small, super-stable set of acceptance tests for both architectures against the soon-to-be-pushed product (tests against a separately started LocalStack container).
- If this is successful, we "accept" the state of the product and push the image.
- As **an intermediary step** we initially push these images to a newly introduced tag called `dev`, i.e. `localstack/localstack:dev`.
- However, this is just a precautionary, intermediary solution to avoid any issues for our customers which …
=> Execute only acceptance tests on pushes to master

.circleci/config.yml
The `push-to-tinybird` job in the CircleCI workflow is only executed on master. Due to this, changes introduced with #11049 could not be sufficiently tested and therefore introduced a typo in an echo statement.
Fix the typo.
=> Fix a typographical error introduced in push-to-tinybird

.circleci/config.yml
During executing the tests of PR #11097, I noticed that the pipeline failed on runners which did not have a single test selected:
https://app.circleci.com/pipelines/github/localstack/localstack/26179/workflows/2df3bb7b-5594-41db-ac5a-3009c0ed19b9/jobs/221845
The `TEST_PATH` ended up being empty, so all tests are selected - leading to diverse import and pytest errors.
To circumvent that, I added (thanks @silv-io for your help with this), a skip step, so the pipeline would not be executed, to be discussed.
* Skip an integration test run on a runner if no tests are selected.
=> Avoid circleci test-runner failure if no tests are run on that runner

localstack-core/localstack/services/apigateway/next_gen/execute_api/context.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_request.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/parse.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/resource_router.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/moto_helpers.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/router.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/variables.py, tests/unit/services/apigateway/test_handler_request.py
We need a separate context, representing the `$context` variables used to render VTL templates, and which is also passed in the payload to `AWS_PROXY` integrations. 
More informations about `$context` here. 
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#context-variable-reference
It is a bit of duplicated information from the original `RestApiInvocationContext` object and the `InvocationRequest`, but they serve different purposes.
If we need to update different contexts at the same time, then maybe we could simplify. But we learned that creating those context when needed, collecting informations from different sources, can be pretty hard. 
The `InvocationRequest` goal is simply to represent the incoming request "as is", with no …
=> add context variables and stage variables to API NG context

localstack-core/localstack/utils/container_utils/container_client.py, localstack-core/localstack/utils/container_utils/docker_cmd_client.py, localstack-core/localstack/utils/container_utils/docker_sdk_client.py, tests/integration/docker_utils/test_docker.py
We currently have no support for docker logs configs, to set different docker log drivers, in our docker client implementation.
In order to facilitate some future functionality, we need to be able to use different log drivers.
This PR adds this functionality, and an example test which streams the logs to fluent-bit.
* Support docker log configuration in the docker client
=> Add support for docker container log configs

localstack-core/localstack/services/apigateway/next_gen/execute_api/gateway.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/__init__.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/api_key_validation.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/moto_helpers.py, tests/unit/services/apigateway/test_handler_api_key_validation.py
Implementation of a new api key validation handler. There is a mix of moto helpers in the implementation as not all relevant information live in the deployment. 
- The resource method describes `apiKeyRequired`, which determines if validation is required or skipped.
- The rest api describes `apiKeySource`, which determines if the key is to be retrieved from the headers or from an identity context populated by an Lambda Authorizer
Those items, when created, modified or deleted, will affect a deployment without the need to redeploy. see https://docs.aws.amazon.com/apigateway/latest/developerguide/updating-api.html
- Api keys and their properties are stored in moto (contradicts the documentation, but manually tested that updating `enabled` from the key will affect without redeploying)
- …
=> APIGW NG implement api key validation handler

localstack-core/localstack/services/apigateway/next_gen/execute_api/gateway_response.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/gateway_exception.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_request.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/parameters_mapping.py, tests/unit/services/apigateway/test_parameters_mapping.py
This PR implements Parameter Mappings and the base util class. It is also integrated into the Integration Request handler, but that part is still untested because we will wait for the handler to be complete before testing its behavior. 
More informations about Parameters Mappings in this documentation page:
https://docs.aws.amazon.com/apigateway/latest/developerguide/request-response-data-mappings.html
It allows you to map values from your incoming request (path parameters, query string and headers), as well as the body and even parts of the body with JSON Path. You can also map values from the `$context` variable and stage variables, as well as static data. 
- implement a small change to Gateway Response, as it seems AWS is raising `DEFAULT_4XX` exceptions directly and that wasn't …
=> APIGW NG implement request data mapping for integration request

localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_request.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/template_mapping.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/variables.py, tests/unit/services/apigateway/test_handler_integration_request.py, tests/unit/services/apigateway/test_template_mapping.py
Adding VTL Template Mapping to our Integration request handler and port `ApiGatewayVtlTemplate` class to NG provider.
The request template allows to create a request body based on the provided VTL template. You can also use it to `#set` requests override the path parameters, headers and query strings. See: https://docs.aws.amazon.com/apigateway/latest/developerguide/models-mappings.html
When no templates are found based on content-type, an `UnsupportedMediaTypeError` can be raised depending on the set passthrough behaviour.
- Implements `ApiGatewayVtlTemplate`, which is ported and simplified from legacy `templates.py`. 
- adds logic for and exception for passthrough behavior
- augments request template with the request overrides
=> Apigw ng request template mapping

pyproject.toml, requirements-base-runtime.txt, requirements-dev.txt, requirements-runtime.txt, requirements-test.txt, requirements-typehint.txt
This PR bumps moto-ext to 5.0.10.post1
Contains:
- https://github.com/getmoto/moto/pull/7794
- https://github.com/getmoto/moto/pull/7784
=> Bump moto-ext to 5.0.10.post1

localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/state_map.py, localstack-core/localstack/services/stepfunctions/asl/component/state/state_execution/state_map/tolerated_failure.py, localstack-core/localstack/services/stepfunctions/asl/component/state/state_props.py, localstack-core/localstack/services/stepfunctions/asl/parse/preprocessor.py, tests/aws/services/stepfunctions/templates/scenarios/statemachines/map_state_tolerated_failure_count.json5, tests/aws/services/stepfunctions/templates/scenarios/statemachines/map_state_tolerated_failure_count_path.json5, tests/aws/services/stepfunctions/templates/scenarios/statemachines/map_state_tolerated_failure_percentage.json5, tests/aws/services/stepfunctions/templates/scenarios/statemachines/map_state_tolerated_failure_percentage_path.json5, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.py, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.snapshot.json, tests/aws/services/stepfunctions/v2/scenarios/test_base_scenarios.validation.json
This PR is a follow up to https://github.com/localstack/localstack/pull/10057 which recently introduced parsing support for Map tolerance fields. In particular, it improves the preprocessing logic to utilise the same sub-type pattern used in other areas of the interpreter, such as MaxConcurrency. It also provides improvements to the validation and related error messages for the values supplied to these fields, as well as logging warning to let the user know that although the values are recorded and validated, these do not yet affect the evaluation. Finally, positive and negative tests are added.
- preprocessing logic of tolerance declaration
- warning of unsupported tolerance declaration
- error messages for tolerance values
- positive and negative snapshot tests
- adjusted map logging …
=> [SFN] Enhancements to Parsing Support for Map Toleration Fields

localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_response.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/method_response.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/parameters_mapping.py, tests/unit/services/apigateway/test_handler_integration_response.py, tests/unit/services/apigateway/test_parameters_mapping.py
This PR starts implementing the Integration Response handler, who's responsible for selecting the right `IntegrationResponse` based on the response status code (or an `errorMessage` field very specific to the `AWS` integration with Lambda, which we will tackle later). 
The handler should then do the response parameters mapping, then the VTL rendering of the body. 
We do not test the handler yet, same as the Integration Request handler, as the behavior is incomplete yet.
Instead, we can focus on the integration response selection, and the response parameters mapping. All of the unit tests have been manually tested against AWS, with the console and a SSH tunnel with localhost.run to my own small flask server to be able to return arbitrary payload from my HTTP payload. 
More informations …
=> APIGW NG add Integration Response selection and parameter mapping

localstack-core/localstack/aws/client.py, localstack-core/localstack/aws/protocol/parser.py, localstack-core/localstack/aws/protocol/serializer.py, tests/aws/services/kinesis/test_kinesis.py, tests/aws/services/kinesis/test_kinesis.validation.json, tests/unit/aws/protocol/test_parser.py, tests/unit/aws/protocol/test_serializer.py
Kinesis supports _CBOR_ (Concise Binary Object Representation) encoding as `Content-Type` in addition to JSON.
CBOR support was added for LocalStack with #6494 by extending our ASF parsers and serializers, and patching CBOR support into `botocore` (when being used as a proxy to `kinesis-mock`).
Unfortunately, AWS does not properly implement the CBOR spec when it comes to timestamp handling:
- [RFC8949](https://datatracker.ietf.org/doc/html/rfc8949) defines CBOR timestamps as floating-point epoch seconds:
> The tag content MUST be an unsigned or negative integer (major types 0 and 1) or a floating-point number (major type 7 with additional information 25, 26, or 27).
> ...
> To indicate fractional seconds, floating-point values can be used within tag number 1 instead of integer values.
- …
=> fix CBOR timestamp parsing

docs/testing/integration-tests/README.md, docs/testing/parity-testing/README.md, localstack-core/localstack/services/ec2/resource_providers/aws_ec2_securitygroup.py, tests/aws/services/cloudformation/resource_providers/ec2/test_ec2.py, tests/aws/services/cloudformation/resource_providers/ec2/test_ec2.snapshot.json, tests/aws/services/cloudformation/resource_providers/ec2/test_ec2.validation.json, tests/aws/templates/ec2_security_group_with_tags.yml
Add tags to EC2 Security Group resource when specified in CloudFormation template.
Fixes #10768 
Pass the `TagSpecifications` parameter to the `create_security_group` method when the `Tags` have been passed to the CloudFormation template.
Using this CloudFormation template:
```
Resources:
SecurityGroup:
Type: AWS::EC2::SecurityGroup
Properties:
GroupDescription: Security Group
Tags:
- Key: key1
Value: value1
- Key: key2
Value: value2
```
run:
```
awslocal cloudformation create-stack --stack-name sg --template-body "$(cat cfn.yaml)"
awslocal ec2 describe-security-groups
```
Output should contain `Tags` in the newly created EC2 security group as in the following example:
```
{
"Description": "Security Group",
"GroupName": "sg-SecurityGroup-4e42e960",
"IpPermissions": [],
"OwnerId": …
```
=> EC2SecurityGroup: add TagSpecifications parameter when Tags present in CloudFormation template

localstack-core/localstack/services/apigateway/next_gen/execute_api/context.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/parse.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/resource_router.py, tests/unit/services/apigateway/test_handler_request.py
As @cloutierMat reported, when actually using the next gen APIGW provider, we would not properly route requests, because we had the full path containing the `stage` which didn't map properly to any created Werkzeug Rule. This is how APIGW represents their `path`, this is only what is after the `stage`. 
Only the `$context.path` contains the `stage` and `path`, so we can get weird snapshot with one field named `path` containing `/your-path` and one named `requestContext.path` containing `/stage-name/your-path`. 🤷‍♂️ 
We also had the issue with the `ANY` method, we would try to pass that when creating a Werkzeug Rule. 
We now create a special case where `ANY` gets mapped to `DELETE`, `GET`, `HEAD`, `OPTIONS`, `PATCH`, `POST`, and `PUT` (the supported HTTP methods of APIGW).
I was worried …
=> APIGW NG fix routing with `ANY` request and remove stage from path

localstack-core/localstack/services/apigateway/next_gen/execute_api/gateway_response.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/gateway_exception.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/parameters_mapping.py, tests/unit/services/apigateway/test_handler_exception.py, tests/unit/services/apigateway/test_handler_integration_request.py, tests/unit/test_apigateway.py
This PR adds `x-amzn-errortype` header to all gateway responses.
These are not documented and the value of the token isn't consistent from error to error. The `DEFAULT_XXX` errors appears to be raised with different header value depending on the cause of the error.
- Add `x_header` to `BaseGatewayException`
- Add the header to the response in the Gateway Exception Handler
- Populate the value for all errors. Only some were validated using the console or curl. The others have been marked with a TODO so as to avoid confusion in the future. As we get more snapshot tests going, we should be able to populate more of them
- Some unit tests were moved out of `/unit/apigateway.py` to help separating the legacy tests with the NG tests.
=> Apigw ng add x header to gateway responses

localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_request.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/helpers.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/template_mapping.py, tests/unit/services/apigateway/test_handler_integration_request.py, tests/unit/services/apigateway/test_uri_interpolation.py
Throughout APIGW invocation, there are several places where you can use stageVariables inside some URI and ARN. 
We also need to interpolate path parameters inside the Integration URI
This PR implements 2 utils, to render stage variables following the VTL syntax, and another one to render path parameters, only in curly braces.
The Integration Request handler combines those 2 utils to render the Integration URI. 
More informations about stage variables here:
https://docs.aws.amazon.com/apigateway/latest/developerguide/aws-api-gateway-stage-variables-reference.html#stage-variables-in-integration-HTTP-uris
We will also use the utils inside the Integration for the credentials, and in the cognito authorizer to render the UserPool. 
- implement stage variables rendering util
- implement path …
=> APIGW NG implement URI rendering

tests/aws/services/kinesis/test_kinesis.py, tests/aws/services/kinesis/test_kinesis.validation.json, tests/aws/services/opensearch/test_opensearch.py, tests/aws/services/opensearch/test_opensearch.validation.json
While working on #11133, I saw that the test module contains a few tests with "needs fixing".
Also, @bentsku made me aware of the fact that the opensearch test module contains a lot of `markers.aws.unkown` which we try to get rid of with lots of PRs in the last few months. Just adding a few cross-links to connect these efforts a bit:
- https://github.com/localstack/localstack/pull/10994
- https://github.com/localstack/localstack/pull/10991
- https://github.com/localstack/localstack/pull/10987
- https://github.com/localstack/localstack/pull/10929
- https://github.com/localstack/localstack/pull/10920
- https://github.com/localstack/localstack/pull/10892
- https://github.com/localstack/localstack/pull/10653
- https://github.com/localstack/localstack/pull/9151
- …
=> fix opensearch and kinesis test markers

localstack-core/localstack/services/stepfunctions/asl/parse/intrinsic/preprocessor.py, tests/aws/services/stepfunctions/templates/intrinsicfunctions/intrinsic_functions_templates.py, tests/aws/services/stepfunctions/templates/intrinsicfunctions/statemachines/json_manipulation/json_merge_escaped_argument.json5, tests/aws/services/stepfunctions/templates/scenarios/scenarios_templates.py, tests/aws/services/stepfunctions/v2/intrinsic_functions/test_json_manipulation.py, tests/aws/services/stepfunctions/v2/intrinsic_functions/test_json_manipulation.snapshot.json, tests/aws/services/stepfunctions/v2/intrinsic_functions/test_json_manipulation.validation.json
Currently the StepFunctions v2 interpreter is unable to accurately parse escaped quote sequences (eg. `'\"Hello\"'`), which can appear as String Literal arguments. This PR addresses such issue and added relevant snapshot test.
- Add escape sequence override logic for quotes
- Relevant snapshot test
=> [SFN] Fix Parsing of Escape Sequences in Intrinsic Functions

localstack-core/localstack/services/stepfunctions/provider.py, localstack-core/localstack/services/stepfunctions/stepfunctions_utils.py, tests/aws/services/stepfunctions/v2/test_sfn_api.py, tests/aws/services/stepfunctions/v2/test_sfn_api.snapshot.json, tests/aws/services/stepfunctions/v2/test_sfn_api.validation.json, tests/aws/services/stepfunctions/v2/test_sfn_api_versioning.py, tests/aws/services/stepfunctions/v2/test_sfn_api_versioning.snapshot.json, tests/aws/services/stepfunctions/v2/test_sfn_api_versioning.validation.json
Improve parity of StepFunctions provider by adding pagination for [ListStateMachines](https://docs.aws.amazon.com/step-functions/latest/apireference/API_ListStateMachines.html), [ListStateMachineVersions](https://docs.aws.amazon.com/step-functions/latest/apireference/API_ListStateMachineVersions.html), and [ListExecutions](https://docs.aws.amazon.com/step-functions/latest/apireference/API_ListExecutions.html).
- Add pagination functionality and parameter validation checks to `list_state_machines`, `list_state_machine_versions`, and `list_executions` using `PaginatedList`.
- Fix in `list_state_machines`: `ListStateMachine` response now returns `stateMachine` items in alphanumeric order as opposed to by datetime.
- Fixed typo in `list_state_machine_versions` when raising a `RuntimeError` …
=> Add pagination for SFN ListStateMachines, ListStateMachineVersions, and ListExecutions

localstack-core/localstack/testing/aws/util.py, localstack-core/localstack/testing/pytest/fixtures.py
In our [latest scheduled run testing multi-account / multi-region capabilities of LocalStack](https://app.circleci.com/pipelines/github/localstack/localstack/26458/workflows/852a2bc9-8c02-497f-a314-9b4c048af228/jobs/225179/parallel-runs/1/steps/1-111), the Kinesis tests adjusted with https://github.com/localstack/localstack/pull/11133 and https://github.com/localstack/localstack/pull/11141 failed:
```
FAILED tests/aws/services/kinesis/test_kinesis.py::TestKinesis::test_subscribe_to_shard_cbor_at_timestamp - assert 200 == 500
+  where 500 = <Response [500]>.status_code
FAILED tests/aws/services/kinesis/test_kinesis.py::TestKinesis::test_get_records - assert 200 == 400
+  where 400 = <Response [400]>.status_code
FAILED tests/aws/services/kinesis/test_kinesis.py::TestKinesis::test_get_records …
```
=> fix aws_http_client_factory fixture to use TEST_AWS_REGION_NAME

localstack-core/localstack/services/lambda_/invocation/lambda_models.py, localstack-core/localstack/services/lambda_/provider.py, localstack-core/localstack/services/lambda_/urlrouter.py, tests/aws/services/lambda_/test_lambda.py, tests/aws/services/lambda_/test_lambda_api.py
This PR allows users to apply a tag to a lambda function that results in a deterministic, user-specified function URL when subsequently calling the ``create_function_url_config`` endpoint.
This is useful, for example, in static scripts or code samples, where fetching the randomly-generated ID from the created URL is undesirable.
**Note: I'll create a separate PR for updating the docs accordingly.**
+ Added module global for the tag key
+ Updated the ``create_function_url_config`` endpoint to find the tag and, if available, use it
+ Added a test to verify desired behavior
In addition to the added unit test, I also verified locally that it works (using ``awslocal``).
Lambda functions can actually have more than one custom URL:
+ URLs are associated with a ``(function, [version alias])`` …
=> Add custom lambda function URLs via _custom_id_ tag

localstack-core/localstack/services/apigateway/next_gen/execute_api/context.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/gateway.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_request.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/integration_response.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/parse.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/http.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/parameters_mapping.py, tests/aws/services/apigateway/conftest.py, tests/aws/services/apigateway/test_apigateway_http.py, tests/aws/services/apigateway/test_apigateway_http.snapshot.json, tests/aws/services/apigateway/test_apigateway_http.validation.json, tests/unit/services/apigateway/test_handler_integration_request.py, tests/unit/services/apigateway/test_parameters_mapping.py
This PR implements the `HTTP` and `HTTP_PROXY` integrations. The previous work we have done make those extremely simple to implement and understand, and it shows how much the current work is going to simplify APIGW. 
The PR also contains a few changes across the board, because we can now test full end-to-end integration tests: the `tests/aws/services/apigateway/test_apigateway_http.py` test file is fully green with the new PR, with improved parity. 
- implemented the `HTTP` and `HTTP_PROXY` integrations
- change some typing around some existing contexts, as those were not really `Optional` and it helps with making sure we're not lacking data once we're in the integration
- remove the `legacy` handler as we can now enable full end-to-end tests
- remove the full clear of headers when …
=> APIGW NG add HTTP and HTTP_PROXY integration

.github/workflows/tests-pro-integration.yml
With https://github.com/localstack/localstack/pull/10800 the main module in localstack/localstack has been moved from the root of the repository to the `localstack-core` folder.
Unfortunately, this silently killed the caching in the workflow which runs the Community tests against the LocalStack Pro code (since the `.filesystem` folder now is in `localstack/localstack-core/.filesystem`).
This PR addresses this issue which should hopefully lead to an increase in the pipeline stability.
- Adjusts the path for the var lib cache in `tests-pro-integration.yml`
=> fix caching in tests-pro-integration after source move

.circleci/config.yml
With https://github.com/localstack/localstack/pull/11049 we switched our testing methodology such that we only run acceptance tests on `master`. In order to avoid any disturbance, we introduced an intermediary tag `dev` to make sure that we do not break the `latest` image (which is directly used by a lot of our users) too often.
We have now learned that the acceptance tests in combination with the PR tests are a good gate, and there is no known instance where a dev tag contained issues which would even have been caught by the full integration test suite.
This is why this PR removes the `dev` tag again, runs on master which only execute the acceptance tests will directly push the `latest` image tag.
- Removes the selective usage of the `dev` tag when only the acceptance tests are executed. …
=> abandon dev tag, directly push latest on acceptance test run

.circleci/config.yml
Since #11049 by default we only run the acceptance tests for commits on `master`.
While this PR skips pushing test results to our internal test analytics, it still pushes the coverage data, [which leads to the coverage metrics jumping between 47% (acceptance tests only) and 84% (full test suite)](https://coveralls.io/github/localstack/localstack).
- Avoids the report step completely for the `acceptance-only-run` workflow in CircleCI.
=> fix coverage drops by skipping report step for `acceptance-only-run`

localstack-core/localstack/utils/container_utils/container_client.py, localstack-core/localstack/utils/container_utils/docker_cmd_client.py, localstack-core/localstack/utils/container_utils/docker_sdk_client.py, tests/cli/test_cli.py, tests/integration/docker_utils/test_docker.py, tests/unit/test_dockerclient.py
Our current usage of bind mounts in docker utilizes the docker `volumes` API. However, this API has been superceded by the `mounts` API.
There was also one, so far unsuccessful, try to use `mounts` for everything in LocalStack, with #9887.
There are some drawbacks when using the mounts API for bind mounts, for example the fact that the host path is not automatically created.
However, it would also achieve many advantages, like being able to mount subpaths of named volumes into containers.
To prepare for the future use of mounts, for now in addition to volumes, this PR renames all current occurrences of `mounts` or `mount_volumes` to `volumes`, to make the differenciation clearer.
We can then start to implement the mounts API in the docker client, and step by step migrate usages of …
=> Clarify docker client volume API

localstack-core/localstack/aws/handlers/internal.py, localstack-core/localstack/runtime/runtime.py, tests/bootstrap/test_init.py
@HarshCasper noted that this sample didn't work with the new runtime https://github.com/localstack-samples/localstack-init-hooks/tree/main/example-docker-compose
This is because we were running shutdown hooks after the runtime server was shut down. I changed the runtime to correct the order to what we were doing previously.
I also noticed that we're returning 503 errors when calling `/_localstack` APIs when shutting down, which I find stifles the use of shutdown hooks. I added an exception for those internal APIs.
Moreover I added a bootstrap test to validate the shutdown hook behaviors
* Gateway is now shut down _after_ shutdown hooks are run
* `/_localstack` endpoints can now be called while localstack is shutting down
* added a bootstrap test for testing shutdown hooks
=> add ability for shutdown hooks to call internal APIs

localstack-core/localstack/utils/bootstrap.py
With #10942 we wanted to deprecate `localstack start --host`, which is why I didn't update it. However, @alexrashed argued (correctly) that people are still using it and we should keep backwards compatibility.
This PR does a minimal change to simply make `localstack start --host` basically equivalent to ``python -m localstack.runtime.main``.
* `localstack start --host` now uses the new runtime to start localstack
* check out the PR, activate venv
* run `python -m localstack.cli.main start --host`, observe it still works
=> use new runtime procedure for starting localstack in host mode

.circleci/config.yml, localstack-core/localstack/dev/run/__main__.py, localstack-core/localstack/dev/run/configurators.py, pyproject.toml
This PR serves two purposes. It (a) adjusts the coverage config a bit such that the package path and the source config are properly separated, and (b) removes an obsolete coverage-related dev container config which is not used anymore.
- Removes the `CoverageRunScriptConfigurator` since the `run-coverage.py` is not used anymore.
- Slightly changes the `pyproject.toml` to properly separate between the configuration of the sources and the package lookup config.
=> update coverage config, remove obsolete dev run configurator

localstack-core/localstack/services/s3/models.py, localstack-core/localstack/services/s3/provider.py, tests/aws/services/s3/test_s3_api.py, tests/aws/services/s3/test_s3_api.snapshot.json, tests/aws/services/s3/test_s3_api.validation.json
As reported in #11180, we've had the wrong behavior for DeleteMarker with `ObjectTagging` operations. 
However, my previous assumptions were wrong due to a mistake in a test, which lead to a design decision in the S3 models (the `S3Bucket` `get_object` method signature). 
We will need to update it to support properly this behavior, however this might break persistence as the previous loaded objects might have the previous signature, and fails when used in the provider. We will need to wait for the next major release to remove the previous parameter `raise_for_delete_marker` and add a new one permitting use to separate behavior between calls from `GetObject` vs `GetObjectTagging` (one raise `NoSuchKey` and the other `MethodNotAllowed`). 
- add a hacky way to support the behavior reported, …
=> fix ObjectTagging with DeleteMarker

localstack-core/localstack/services/apigateway/next_gen/execute_api/gateway_response.py, localstack-core/localstack/services/apigateway/next_gen/provider.py
While implementing the `AWS_PROXY` integration with #11167, I've stumbled onto a weird issue: AWS would raise an `INTEGRATION_FAILURE` error, which the default status code should be 504 (Gateway Timeout, that's already suspicious), but instead returned `500`. 
After a lot of investigation with @cloutierMat, we came to the conclusion that the CRUD later (`PutGatewayResponse`, `GetGatewayResponse` etc) is not in line with the actual behavior, and that the actual default status code is `500`, but the CRUD calls still returns 504. 
This PR implements the logic to enable the difference between the CRUD layer and the actual invocation layer by attaching a default status code to the exception, while still using the previous default for other exceptions, allowing us to override the behavior. …
=> APIGW NG implement AWS bug for INTEGRATION_FAILURE GatewayResponse

localstack-core/localstack/services/lambda_/provider.py, tests/aws/services/lambda_/test_lambda_api.py, tests/aws/services/lambda_/test_lambda_api.snapshot.json, tests/aws/services/lambda_/test_lambda_api.validation.json
We are currently experiencing a bug when deleting a Lambda function version without deleting the entire function, due to a misuse of the `qualified_arn` property.
We had not test deleting only the function version before, which is why I added one as well.
* Lambda function versions can now be deleted without an error
=> Fix deletion of lambda function versions

localstack-core/localstack/config.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/api_key_validation.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/handlers/parse.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/helpers.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/aws.py, localstack-core/localstack/services/apigateway/next_gen/execute_api/variables.py, tests/aws/services/apigateway/test_apigateway_lambda.py, tests/aws/services/apigateway/test_apigateway_lambda.snapshot.json, tests/aws/services/apigateway/test_apigateway_lambda.validation.json, tests/unit/services/apigateway/test_handler_api_key_validation.py
This PR implements the `AWS_PROXY` API Gateway integration. 
https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html
- populate the `identity` field of the context with the default values for a method with no authorizer
- port a few utils needed for the lambda integration
- implement the `AWS_PROXY` integration, adding the utils to create the input payload and parsing the response from lambda and passing it down the chain
All the tests related to `AWS_PROXY` in `tests.aws.services.apigateway.test_apigateway_lambda` are passing when forcing the provider, with way less snapshot ignore than before 🥳 
(With `test_lambda_aws_proxy_integration_non_post_method` depending #11183 to be merged due to the gateway response default value issue).
What's left …
=> APIGW NG add AWS_PROXY integration

localstack-core/localstack/services/apigateway/next_gen/execute_api/integrations/mock.py, tests/unit/services/apigateway/test_mock_integration.py
Implements Mock integration. https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-mock-integration.html
Upon testing with the console, I confirmed that any integer, positive or negative will work. It will then get matched to the response as usual.
I didn't test much of the validated tests yet as #11143 and #11144 both bring fixes required to enable end to end integrations.
- Mock integration
- Unit tests
=> Apigw ng implement mock integration
